Replace master with main in links and docs/conf.py
pytorch/pytorch pull request #100176
Opened 2023-04-27 16:01 UTC by svekars

Fixes #ISSUE_NUMBER

cc @carljparker

2023-04-27 20:45 UTC, albanD requested changes
I want to ask "why this is not pointing to stable instead of main" for a bunch of these. But that can be a separate conversation.

Also I feel like this PR is reverting some recent cleanups that happened in the doc. We should not do that.

2023-04-27 20:45 UTC, albanD commented on docs/source/fx.rst
> +        torch.testing.assert_allclose(traced(x), x)
WHy?

2023-04-27 20:45 UTC, albanD commented on docs/source/jit.rst
> +            super(MyScriptModule, self).__init__()
Is this due to a bad merge? We definitely don't want that.

2023-04-27 20:45 UTC, albanD commented on docs/source/jit.rst
> +    try:
Why not the version from typing?

2023-04-27 20:45 UTC, albanD commented on docs/source/notes/modules.rst
> +  Alternatively, these hooks can be installed globally for all modules with the analagous
no?

2023-04-27 20:59 UTC, svekars commented on docs/source/fx.rst
> +        torch.testing.assert_allclose(traced(x), x)
fixed.

2023-04-27 21:04 UTC, albanD approved these changes
Change sounds ok.
What's the plan to test that it doesn't break nightly / release?

2023-05-02 15:54 UTC, malfet approved these changes

2023-05-02 18:20 UTC, closed without merging