Have testing overhead dashboard only use successful workflows
pytorch/pytorch pull request #100580
Opened 2023-05-03 21:16 UTC by PaliC

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-05-03 21:20 UTC, huydhn approved these changes

2023-05-03 21:21 UTC, PaliC commented
@pytorchbot merge

2023-05-03 22:07 UTC, ZainRizvi requested changes
Loooks good for the most part, but the workflow linked doesn't seem to specify a specific repo. The rockset query contains data from many repos beyond just pytorch/pytorch.

You probably want to add the repo owner & name as an additional filter here

2023-05-04 20:17 UTC, PaliC commented
@pytorchbot merge -r

2023-05-04 22:49 UTC, closed without merging