Flatten exceptions in dynamo
pytorch/pytorch pull request #100779
Opened 2023-05-06 01:33 UTC by mlazos

Fixes https://github.com/pytorch/pytorch/issues/93571

2023-05-06 01:47 UTC, ezyang requested changes
I can't accept this. You've lost the PrimTorch stack trace, which is the most important part for internal debugging purposes!

2023-05-06 02:23 UTC, mlazos commented
> I can't accept this. You've lost the PrimTorch stack trace, which is the most important part for internal debugging purposes!

Oh oops, I can apply this rule recursively and get it back. I thought this was perfect ootb!!

2023-05-07 19:12 UTC, ezyang commented on torch/_dynamo/utils.py
> +        raise RuntimeError(str(e)).with_traceback(e.__traceback__) from None
The incremental info (op args kwargs) here was very useful, please preserve it.

2023-05-07 19:13 UTC, ezyang commented
I'm not sure how I feel about str'ing the exception. Can we preserve the original structure maybe? IDK.

2023-05-08 23:00 UTC, mlazos commented
> I'm not sure how I feel about str'ing the exception. Can we preserve the original structure maybe? IDK.

Yeah I actually ended up keeping the structure in a spot where it was needed in an upstream handler. Do you have a specific need in mind? If anyone needs the `__cause__` to be populated in the future, you're allowed to do new_exc.with_traceback(old_exc) from old_exc to preserve the structure, it's just nobody else is using that rn.

2023-05-09 15:07 UTC, ezyang commented
You don't want `from old_exc` because that will trigger chained printing, and if you're overriding the traceback you definitely don't want chaining.

I guess we can give this a try. For downstream consumers who want the original error, this is going to depend a lot on what exactly those systems are doing. Maybe we can reach out to some folks who work on those systems to figure it out.

2023-05-09 15:07 UTC, ezyang approved these changes

2023-05-09 17:12 UTC, mlazos commented
@pytorchbot merge

2023-05-09 20:15 UTC, mlazos commented
@pytorchmergebot merge

2023-05-10 00:07 UTC, mlazos commented
@pytorchbot merge

2023-05-10 00:13 UTC, mlazos commented
@pytorchbot merge

2023-05-10 05:20 UTC, mlazos commented
@pytorchbot merge

2023-05-11 17:17 UTC, mlazos commented
@pytorchbot merge

2023-05-12 21:08 UTC, mlazos commented
@pytorchbot merge

2023-05-12 21:49 UTC, mlazos commented
@pytorchbot merge

2023-05-13 00:59 UTC, closed without merging