inductor: fallback ConvTranspose when output_padding is big
pytorch/pytorch pull request #100846
Opened 2023-05-08 02:47 UTC by chunyuan-w

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-05-08 10:42 UTC, jgong5 commented on torch/_inductor/mkldnn.py
> +    return is_big
a more pythonic impl and you don't need an extra function:
`any(padding >= stride for padding, stride in zip(m.output_padding, m.stride))`

2023-05-09 01:06 UTC, jgong5 approved these changes

2023-05-09 12:32 UTC, EikanWang approved these changes

2023-05-09 16:18 UTC, jansel requested changes

2023-05-09 16:18 UTC, jansel commented on torch/_inductor/mkldnn.py
> +                        output_padding >= stride
This won't work with dynamic shapes.  You will just get `TypeError: cannot determine truth value of Relational`
```
>>> 10 > sympy.Symbol("x")
x < 10
```

2023-05-11 03:02 UTC, jansel approved these changes

2023-05-11 06:14 UTC, chunyuan-w commented
@pytorchbot merge

2023-05-11 06:18 UTC, closed without merging