Perform CSE across block boundaries.
pytorch/pytorch pull request #10105
Opened 2018-07-31 23:50 UTC by resistor

@zdevito

2018-08-06 00:58 UTC, apaszke approved these changes

2018-08-06 00:58 UTC, apaszke commented on torch/csrc/jit/passes/common_subexpression_elimination.cpp
> +    if (node->blocks().size()) {
nit: it might be slightly nicer to do `!node->blocks().empty()`

2018-08-06 00:58 UTC, apaszke commented on torch/csrc/jit/passes/common_subexpression_elimination.cpp
> +        [&](Node *n) {
nit: can you please indent this? otherwise it looks as if you were just continuing code on the same level, while it's really an argument to the call

2018-08-07 02:18 UTC, apaszke requested changes

2018-08-07 03:39 UTC, resistor commented on torch/csrc/jit/passes/common_subexpression_elimination.cpp
> +      if (lhs_outputs[i]->type()->kind() != rhs_outputs[i]->type()->kind())
Fixed.

2018-08-09 14:06 UTC, resistor commented
@apaszke ping

2018-08-09 20:43 UTC, apaszke reviewed
Actually when does it happen that CSE replaces a node with a different output type, even though its kind and all types of inputs are the same! We shouldn't really have nodes overloaded on output types

2018-08-09 22:35 UTC, resistor commented
@apaszke I did not observe any differences in test results switching from kind equality + input equality to operator==.  That said, even if the difference does not inherently matter in CSE, I'd prefer to use the semantically correct check to make this easier to maintain in case CSE or our operator changes in the future in a way that would break the clever way.

2018-08-13 15:02 UTC, apaszke commented
@resistor this is because most of our types are singletons, and so their pointers will compare equal iff they compare equal. However, this is not always true (e.g. TensorType has many distinct instances), and we should use the reference-level equality in place of the pointer-level one.

Do you remember which test has triggered failure because of missing equality checks? I'm not 100% sure if they're needed.

2018-08-13 16:06 UTC, resistor commented
@apaszke 
$ python test/test_jit.py -v 2>&1 | grep ERROR
test_beam_search (__main__.TestBatched) ... ERROR
test_greedy_search (__main__.TestBatched) ... ERROR

2018-08-14 16:32 UTC, yf225 commented
@apaszke What should be the next step for this patch?

2018-08-15 06:44 UTC, zdevito approved these changes
I think all the changes were addressed and this is ready to land.

2018-08-16 07:27 UTC, closed without merging