Fix device normalization of automatically generate methods for custom backends.
pytorch/pytorch pull request #101796
Opened 2023-05-18 11:07 UTC by fakeYan

Fixes #ISSUE_NUMBER
Fix the problem of error handling when the device input parameter adopts string type, Align capabilities.

`foo_storage = torch.DoubleStorage(4).foo(device="foo:0, non_blocking=False")`

2023-05-18 11:18 UTC, fakeYan commented
@pytorchbot label "topic: not user facing"

2023-05-18 14:24 UTC, Skylion007 commented on torch/utils/backend_registration.py
> +            raise RuntimeError(f"Invalid device, must be {custom_backend_name} device")
```suggestion
            raise ValueError(f"Invalid device, must be {custom_backend_name} device")
```

2023-05-19 17:58 UTC, Skylion007 approved these changes

2023-05-19 18:00 UTC, Skylion007 commented on torch/utils/backend_registration.py
> +        if device.split(":")[0] == custom_backend_name:
Actually, hold on, what about `device="cuda"` or device="foo". Do you need to add error handing for that case as well?

2023-05-19 18:02 UTC, Skylion007 requested changes
Actually, hold on there might be a better way to do this. Why not just `torch.device(device)` to the conversion from str to device?

2023-05-22 06:26 UTC, fakeYan commented
@pytorchbot merge

2023-05-22 08:23 UTC, fakeYan commented
> Actually, hold on there might be a better way to do this. Why not just `torch.device(device)` to the conversion from str to device and then reuse the existing logic?

I understand the relevant logic. I moved the logic of converting str type to torch.device type to the front, so that objects of type torch.device can be processed normally later.  I think it looks better.

2023-05-22 16:41 UTC, bdhirsh approved these changes
lgtm, thanks!

2023-05-22 16:42 UTC, bdhirsh commented
@pytorchbot merge

2023-05-22 19:02 UTC, closed without merging