normalize squeeze
pytorch/pytorch pull request #102294
Opened 2023-05-25 19:54 UTC by devashishshankar

Summary: Sometimes, squeeze can be a "call_method" instead of a "call_function". Normalizing it will make it amenable to pattern matching by passes like "split->squeeze"

Test Plan: * CI tests

Differential Revision: D46031846

2023-05-25 20:00 UTC, devashishshankar commented
@pytorchbot label "topic: not user facing"

2023-05-26 21:47 UTC, jansel requested changes
Test failures seem real

2023-05-31 01:05 UTC, devashishshankar commented
> Test failures seem real

@jansel fixed

2023-05-31 18:06 UTC, jansel approved these changes

2023-06-01 19:05 UTC, closed without merging