Feature:To add --tolerance option to benchmark scripts
pytorch/pytorch pull request #102218
Opened 2023-05-24 22:11 UTC by vinayburugu

--tolerance option will evaluate the model on the baseline device on eager mode (default CPU) and on the test device (eg. cuda, xla etc.) and compare the output tensors to get the absolute tolerance value based on the [formula](https://pytorch.org/docs/stable/generated/torch.allclose.html) and dumps the results in a csv file. This will highlight the tolerance / accuracy difference between XLA and GPU devices. This can also be used to evaluate newer accelerators.

Fixes #ISSUE_NUMBER

2023-05-25 00:45 UTC, vinayburugu commented
@pytorchbot label "topic: not user facing"

2023-05-27 03:04 UTC, jansel reviewed
This seems very similar to `--accuracy`, which also checks correctness of a backend compared to eager and we have other flags to control the tolerance of that check and a few different modes.  What is the motivation for a different top-level command?

2023-05-30 18:46 UTC, vinayburugu commented
> 

Hi @jansel --accuracy will only use specific tolerance value and say whether a model is passing the accuracy test or not. This new --tolerance option will calculate the maximum tolerance value for each model using the fomulae. This will highlight the accuracy differences between XLA and eager mode/inductor. This option can be used to generate the csv data with tolerance values for each model which in turn can be manually summarized as below:
| Suite                     | Max Tolerance |          | No. of models with high inaccuracy(>=0.005) |          | Mean Tolerance |          |
|-------------|:-------------:|:--------:|:-------------------------------------------:|:--------:|:--------------:|:--------:|
|                             |      xla           | inductor |                     xla     | inductor |                                                xla      | inductor |
| huggingface       |        0.1169  |   0.0032 |                            1 |        0 |                                                   0.0022 |   0.0005 |
| timm_models     |        0.0373 |   2.8892 |                          10 |        8 |                                                   0.0028 |   0.7044 |
| torchbench        |         3.013   |   3.0381 |                            6 |        2 |                                                    0.0016 |   0.0016 |
| All models          |         3.013   |   3.0381 |                           17 |       10 |                                                  0.0028 |   0.7044 |

2023-05-30 21:34 UTC, jansel requested changes

2023-05-30 21:34 UTC, jansel commented on benchmarks/dynamo/common.py
> -#!/usr/bin/env python3
Is this breaking the tests?

2023-05-30 21:36 UTC, jansel commented
Got it, makes sense.  Please fix tests/lints.

2023-06-01 00:55 UTC, jansel approved these changes

2023-06-01 00:55 UTC, jansel commented
@pytorchbot merge

2023-06-01 21:27 UTC, jansel commented
@pytorchbot merge

2023-06-02 17:16 UTC, vinayburugu commented
@jansel I am not sure about the workflow errors. Is there any problem with the CI?

2023-06-03 01:42 UTC, huydhn commented
@pytorchbot rebase

2023-06-03 01:45 UTC, jansel commented
> @jansel I am not sure about the workflow errors. Is there any problem with the CI?

Not sure, lets see if rebase fixes it.

2023-06-03 04:16 UTC, jansel commented
@pytorchbot merge

2023-06-03 06:40 UTC, closed without merging