[inductor][pattern matcher] Retain meta tags
pytorch/pytorch pull request #102462
Opened 2023-05-29 00:10 UTC by anijain2305

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-05-29 04:49 UTC, jansel requested changes

2023-05-29 04:49 UTC, jansel commented on torch/_inductor/pattern_matcher.py
> +                    result.meta.update(first_node.meta)
Do we need to skip updating meta["val"] here?

2023-05-29 04:49 UTC, jansel commented on torch/_inductor/pattern_matcher.py
> +        with graph.inserting_before(first_node):
Is this change needed?

2023-05-30 18:06 UTC, anijain2305 commented on torch/_inductor/pattern_matcher.py
> +        with graph.inserting_before(first_node):
Oh, this is just variable name change.

2023-05-31 00:52 UTC, jansel approved these changes

2023-05-31 00:52 UTC, jansel approved these changes

2023-05-31 01:13 UTC, anijain2305 commented
@pytorchbot merge

2023-05-31 03:59 UTC, closed without merging