[Dynamo] Correct UserDefinedObjectVariable.var_getattr on function/method type
pytorch/pytorch pull request #102580
Opened 2023-05-30 22:53 UTC by yanboliang

Fixes #102329

2023-05-31 04:12 UTC, wconstab commented on torch/_dynamo/variables/user_defined.py
> +            dynamic_subobj = getattr(self.value, name)
is there a problem with dynamic getattr?  I don't understand that part. Otherwise this looks better to me.

2023-05-31 05:45 UTC, yanboliang commented on torch/_dynamo/variables/user_defined.py
> +            dynamic_subobj = getattr(self.value, name)
Dynamic getattr works well, but we prefer to use static getattr at ```self._getattr_static``` for efficiency, so the result may mess up function type with method type, look at here https://github.com/python/cpython/issues/100418.
The change I made is to trigger dynamic getattr if the result type is ```types.FunctionType``` to get more accurate type for this function/method and wrap it with correct Dynamo variables.

2023-05-31 18:12 UTC, jansel requested changes

2023-05-31 18:12 UTC, jansel commented on torch/_dynamo/variables/user_defined.py
> +            dynamic_subobj = getattr(self.value, name)
`getattr` can execute arbitrary code, so we can't call it unconditionally.  You could check that `__getattr__`/`__getattribute__` is in some known safe list...

2023-05-31 21:57 UTC, yanboliang commented on torch/_dynamo/variables/user_defined.py
> +            dynamic_subobj = getattr(self.value, name)
https://github.com/pytorch/pytorch/blob/d9f75dded18b835ca39272491d8e859c3951258b/torch/_dynamo/variables/user_defined.py#L381-L393

If there is custom ```__getattribute__```, we have fall back at L381;
If there is custom ```__getattr__```, the corresponding handling is at L388-L393.

If we run into this branch, that means no custom ```__getattribute__``` and the attribute is not accessed by custom ```__getattr__```, so it seems we are safe to call ```getattr``` here. Do I understand it correctly? @jansel

2023-06-01 00:53 UTC, jansel commented on torch/_dynamo/variables/user_defined.py
> +            dynamic_subobj = getattr(self.value, name)
Yes, I am convinced.

2023-06-01 00:53 UTC, jansel approved these changes

2023-06-01 05:01 UTC, yanboliang commented
@pytorchbot merge

2023-06-01 05:04 UTC, closed without merging