Template file "DispatchKeyNativeFunctions.h" add new header file.
pytorch/pytorch pull request #103242
Opened 2023-06-08 09:21 UTC by huihoaan

I use the function `gen_dispatchkey_nativefunc_headers` and the file `DispatchKeyNativeFunctions.h` to generate my own header file. My team have a module like `libtorch`, others may call the function in that header file directly. So we want to add default value to the argument in my header file. 
But my namespace is not `c10`, so I change `MemoryFormat::Contiguous`  to `c10::MemoryFormat::Contiguous`.
And `ATen/ATen.h` is required by `at::Reduction::Mean`.

2023-06-09 08:34 UTC, heidongxianhua commented
@pytorchbot label "ciflow/periodic"

2023-06-09 08:42 UTC, heidongxianhua commented
@pytorchbot label "topic: not user facing"

2023-06-12 14:34 UTC, malfet requested changes
I'm fine with `c10` change, but including including Reduction.h(also, a bit surprised it's still enums there, rather than enum class) to TensorBody is wrong: it should only contain includes needed to make definition in the header correct.

Why Reduction.h can't be include from the header you are generating?

2023-06-13 02:33 UTC, huihoaan commented
> I'm fine with `c10` change, but including including Reduction.h(also, a bit surprised it's still enums there, rather than enum class) to TensorBody is wrong: it should only contain includes needed to make definition in the header correct.
> 
> Why Reduction.h can't be include from the header you are generating?

All right，I have add `Reduction.h` in my own header.   Can you take a second look at this pr?

2023-06-16 01:21 UTC, closed without merging