Iop self
pytorch/pytorch pull request #103376
Opened 2023-06-11 00:17 UTC by lkct

Fixes #103375

Changes:
- Make `__iop__` return `Self`
- Complete `__iop__` and `__rop__`
- Sort them to have the same order as `__op__` (looks more clear)

2023-06-11 16:59 UTC, lkct commented
@pytorchbot label "topic: not user facing"

2023-06-12 14:54 UTC, soulitzer reviewed
Thanks for the fix, just some small comments

2023-06-12 14:54 UTC, soulitzer commented on tools/pyi/gen_pyi.py
> +            # _TensorBase.__iadd__() etc and _TensorBase.idd_() etc should return self
typo: idd_ -> add_

2023-06-12 18:56 UTC, lkct commented on tools/pyi/gen_pyi.py
> +            # _TensorBase.__iadd__() etc and _TensorBase.idd_() etc should return self
fixed

2023-06-12 19:02 UTC, lkct commented on tools/pyi/gen_pyi.py
> -    "rpow",  # reverse arithmetic
I mentioned this in the last item in the description. Typing for these methods is another story, addressed in #103394.

To give some further information:
```python
>>> import torch  # nightly 20230611
>>> [a for a in dir(torch._C._TensorBase) if a.startswith('__r')]
['__radd__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__ror__', '__rshift__', '__rxor__']
```

2023-06-12 20:53 UTC, malfet requested changes
Can you please add a test (say to `test_typing.py`) otherwise it can easily regress again.

Also, in PR description would be nice to add how mypy inferred type looked before and after the change

2023-06-12 20:58 UTC, lkct commented
> Can you please add a test (say to `test_typing.py`) otherwise it can easily regress again.

Can you please give some hint on what this test should look like? It should be fed to mypy for static checking but not for runtime testing.

> Also, in PR description would be nice to add how mypy inferred type looked before and after the change

Will add soon.

2023-06-12 21:21 UTC, lkct commented
> Can you please add a test (say to `test_typing.py`) otherwise it can easily regress again.

I found some examples.

> Also, in PR description would be nice to add how mypy inferred type looked before and after the change

Added

2023-06-12 22:41 UTC, lkct commented
@malfet Help please!

I cannot get `test_typing.py` working locally. Can you please confirm this test actually works and is active?

Following is why I think this file does not work. Please point out if I'm wrong.

---

Firstly in this test file, it loads some reveal tests from this location.
https://github.com/pytorch/pytorch/blob/31ee1512d3108a2856f799250fcefc667c13832c/test/test_typing.py#L23-L24

And here is a test in the referred folder.
https://github.com/pytorch/pytorch/blob/31ee1512d3108a2856f799250fcefc667c13832c/test/typing/reveal/namedtuple.py#L12-L15

The function `qr` is defined here.
https://github.com/pytorch/pytorch/blob/31ee1512d3108a2856f799250fcefc667c13832c/torch/linalg/__init__.py#L2661

Where the `_linalg` is imported in this line of the same file.
https://github.com/pytorch/pytorch/blob/31ee1512d3108a2856f799250fcefc667c13832c/torch/linalg/__init__.py#L5

However, I cannot find `_linalg` from `torch._C`.

2023-06-16 15:15 UTC, lkct commented
@malfet Can you please kindly provide some hints on what to do with the tests? Many thanks!

2023-06-16 17:24 UTC, huydhn commented
For the context, `test_typing` is in the test blocked list atm https://github.com/pytorch/pytorch/blob/main/test/run_test.py#L187, so it's not even run on CI

2023-06-21 13:10 UTC, lkct commented on tools/pyi/gen_pyi.py
> -    "rpow",  # reverse arithmetic
@soulitzer May I consider this resolved?

2023-09-19 13:33 UTC, closed without merging