[ROCm] Limit world_size to 8 for FSDP Unit tests
pytorch/pytorch pull request #103412
Opened 2023-06-12 05:50 UTC by lcskrishna

There are few unit tests in FSDP that can support upto 8 GPUs.
In this case, for example test_fsdp_uneven has an input size of [8,3]. For each process/rank we pass the data as input[self.rank] as below. So when we use 16 GPUs for our tests, these tests throw an index/key error. So basically to avoid such corner cases, I would like to add this change to use 8GPUs if there are more than 8 GPUs. This is applicable to both ROCm and CUDA builds as well.

https://github.com/pytorch/pytorch/blob/main/test/distributed/fsdp/test_fsdp_uneven.py#L44
https://github.com/pytorch/pytorch/blob/main/test/distributed/fsdp/test_fsdp_uneven.py#L55

cc: @jithunnair-amd

2023-06-12 05:52 UTC, jithunnair-amd approved these changes

2023-06-13 09:31 UTC, pruthvistony approved these changes
LGTM

2023-06-13 09:34 UTC, pruthvistony commented
@lcskrishna ,
I have added the labels to trigger more CI tests related to ROCm. Lets wait for the CI to finish.

2023-06-15 03:19 UTC, lcskrishna commented
Seems like CI is unstable. 
@pytorchbot retest this please

2023-06-15 13:53 UTC, lcskrishna commented
@pytorchbot rebase

2023-06-22 12:16 UTC, lcskrishna commented
Unrelated test failures and broken trunk @pytorchbot rebase

2023-06-23 14:43 UTC, lcskrishna commented
@malfet Could you please review this PR.

2023-06-29 14:38 UTC, lcskrishna commented
@pytorchbot rebase

2023-06-30 06:51 UTC, jithunnair-amd commented
@rohan-varma Please review this straightforward change and let us know if you would like to rework the tests so that they work even on 16 GPUs, or is this workaround reasonable since none of the CI jobs test on >8 GPUs anyway?

2023-07-12 17:10 UTC, jithunnair-amd commented
@malfet @kit1980 This is a straightforward PR which shouldn't impact upstream CI since it uses <=8 GPUs anyway, but will help us in our testing with >8 GPUs. CI failures were unrelated.

2023-07-12 18:34 UTC, malfet requested changes
This does not look ROCM specific, can we somehow check `torch.hip.is_available` before applying the min? (Otherwise it will affect 8+ GPU testing for NVIDIA GPUs as well)

2023-07-12 18:38 UTC, jeffdaily commented
> This does not look ROCM specific, can we somehow check `torch.hip.is_available` before applying the min? (Otherwise it will affect 8+ GPU testing for NVIDIA GPUs as well)

8+ GPU testing for NVIDIA GPUs would fail in the same way as AMD GPUs currently because the test we're trying to fix is using the GPU index to slice an input dimension of fixed-size 8.

2023-08-21 17:12 UTC, pruthvistony commented
@malfet ,
Can you please check on it.

2023-08-21 17:13 UTC, pruthvistony commented
@pytorchbot rebase

2023-10-10 20:56 UTC, malfet approved these changes

2023-10-10 20:57 UTC, malfet commented
@pytorchbot rebase

2023-10-10 21:24 UTC, malfet commented
@pytorchbot merge

2023-11-08 05:39 UTC, pruthvistony commented
@pytorchbot rebase

2023-11-08 17:19 UTC, pruthvistony commented
@pytorchbot merge -f "Unrelated CI failures"

2023-11-08 17:21 UTC, closed without merging