Normal and Uniform return earlier without entering kernel<RNG>
pytorch/pytorch pull request #103507
Opened 2023-06-13 12:47 UTC by yewentao256

Fixes [#103418](https://github.com/pytorch/pytorch/issues/103418)

By the way, should we update other distribution funcs in `aten\src\ATen\native\DistributionTemplates.h`?

2023-06-13 12:49 UTC, yewentao256 commented
@pytorchbot label "topic: not user facing"

2023-06-13 18:19 UTC, mikaylagawarecki reviewed
Should this apply only to Normal and Uniform or do we want to enforce this across other impls in this file (e.g. exponential etc.) Seems like they mostly also invoke TensorIterator so should run into the same issue mentioned by https://github.com/pytorch/pytorch/issues/103418

2023-06-14 00:19 UTC, yewentao256 commented
> Should this apply only to Normal and Uniform or do we want to enforce this across other impls in this file (e.g. exponential etc.) Seems like they mostly also invoke TensorIterator so should run into the same issue mentioned by #103418

Sure, I'll apply to all of them in `aten\src\ATen\native\DistributionTemplates.h`

How about making a micro to check and return earlier?

2023-06-14 03:00 UTC, jgong5 requested changes
Please take care of other functions as @mikaylagawarecki suggested.

> How about making a micro to check and return earlier?

Either way is fine. There are not many functions anyway.

2023-06-14 04:30 UTC, yewentao256 commented
> Either way is fine. There are not many functions anyway.

Done~

2023-06-14 09:55 UTC, jgong5 approved these changes

2023-06-14 09:55 UTC, jgong5 commented on aten/src/ATen/native/DistributionTemplates.h
> +  // see https://github.com/pytorch/pytorch/issues/103418 for more details
A bit weird to only leave the comment in `normal_impl_` while this logic applies to other functions here too. Maybe revise and move the comment to the definition of `CHECK_EMPTY_AND_RETURN`?

2023-06-17 00:23 UTC, yewentao256 commented
Hello jgong5 @jgong5, I am wondering is there anything else I need to do? Otherwise could this pr be merged? Thanks!

2023-06-20 15:48 UTC, mikaylagawarecki reviewed
The failures on HUD seem related https://hud.pytorch.org/pr/103507 

For example, [this assertion](https://github.com/pytorch/pytorch/blob/main/test/test_tensor_creation_ops.py#L2707) is failing. Perhaps an empty shape with the wrong dtype should still be raising this RuntimeError but the new macro has bypassed this check. Could you update accordingly to fix this please 

Also cc @jgong5 for thoughts

2023-06-23 02:42 UTC, yewentao256 commented
@mikaylagawarecki Thank you for pointing out this issue. I have addressed it by moving the empty return statement after the original check (dtype, etc.). Please let me know if there is anything else that needs to be fixed.

2023-06-23 17:24 UTC, mikaylagawarecki commented
@pytorchbot rebase

2023-06-23 19:45 UTC, mikaylagawarecki approved these changes

2023-06-23 19:46 UTC, mikaylagawarecki commented
@pytorchbot merge

2023-06-23 21:54 UTC, closed without merging