Allow skipping wrapping indices if returned from nonzero
pytorch/pytorch pull request #10378
Opened 2018-08-09 14:53 UTC by zasdfgbnm

In https://github.com/pytorch/pytorch/pull/10374, I made the helper function that wrap indices a method of tensor to allow profiling how much overhead this feature adds to advanced indexing. But unfortunately, the indices wrapping is very expensive.

A simple demo is:
```python
import torch
d = torch.device('cuda')

a = torch.rand(1000, 1000, device=d)
i = torch.ones(1000, 1000, dtype=torch.uint8, device=d).triu()

with torch.autograd.profiler.profile(use_cuda=True) as prof:
	a[i]
	
prof.export_chrome_trace('triu')
print(prof)
```

This gives:
```
-----------------------  ---------------  ---------------  ---------------  ---------------  ---------------
Name                            CPU time        CUDA time            Calls        CPU total       CUDA total
-----------------------  ---------------  ---------------  ---------------  ---------------  ---------------
_th_get_device                   5.958us          5.216us                1          5.958us          5.216us
_th_get_device                   2.896us          2.272us                1          2.896us          2.272us
_th_get_device                   3.140us          3.072us                1          3.140us          3.072us
_cast_Byte                      15.384us         15.360us                1         15.384us         15.360us
_th_get_device                   2.801us          2.848us                1          2.801us          2.848us
_th_get_device                   2.805us          2.784us                1          2.805us          2.784us
index                         1832.829us       1862.496us                1       1832.829us       1862.496us
_th_get_device                   2.832us          3.040us                1          2.832us          3.040us
nonzero                        328.179us        605.728us                1        328.179us        605.728us
select                          30.519us          1.024us                1         30.519us          1.024us
select                           5.983us          1.024us                1          5.983us          1.024us
_wrap_index_once               628.163us        442.368us                1        628.163us        442.368us
max                            295.205us         78.048us                1        295.205us         78.048us
_local_scalar                   41.098us         41.088us                1         41.098us         41.088us
_th_get_device                   2.954us          3.072us                1          2.954us          3.072us
_local_scalar_dense             19.456us         19.456us                1         19.456us         19.456us
min                             81.825us         82.240us                1         81.825us         82.240us
_local_scalar                   26.363us         26.240us                1         26.363us         26.240us
_th_get_device                   4.620us          4.864us                1          4.620us          4.864us
_local_scalar_dense             12.135us         12.192us                1         12.135us         12.192us
remainder                      154.303us        195.424us                1        154.303us        195.424us
mul                            234.862us        229.376us                1        234.862us        229.376us
_wrap_index_once               255.512us        277.504us                1        255.512us        277.504us
max                             94.118us         76.192us                1         94.118us         76.192us
_local_scalar                   25.571us         26.016us                1         25.571us         26.016us
_th_get_device                   2.874us          2.432us                1          2.874us          2.432us
_local_scalar_dense             12.734us         12.768us                1         12.734us         12.768us
min                             75.452us         76.576us                1         75.452us         76.576us
_local_scalar                   26.015us         25.952us                1         26.015us         25.952us
_th_get_device                   2.980us          3.008us                1          2.980us          3.008us
_local_scalar_dense             11.987us         12.032us                1         11.987us         12.032us
remainder                       12.788us         55.776us                1         12.788us         55.776us
mul                            151.378us        140.288us                1        151.378us        140.288us
add_                            20.204us         53.248us                1         20.204us         53.248us
view                             9.550us          1.024us                1          9.550us          1.024us
take                            82.686us         80.896us                1         82.686us         80.896us
```
We can see that `_wrap_index_once` is a major cost of computation.

However, wrapping indices is not always necessary. For example, if an index tensor is constructed by `expandByteTensors`, then there is no need to wrap indices because `nonzero` will not return indices out of range.

This PR adds a `bool` to store if wrap index can be skipped. And if yes, then skip this expensive operation. As a result of this change, we get the following profiling:

```
------------------  ---------------  ---------------  ---------------  ---------------  ---------------
Name                       CPU time        CUDA time            Calls        CPU total       CUDA total
------------------  ---------------  ---------------  ---------------  ---------------  ---------------
_th_get_device              7.707us          7.328us                1          7.707us          7.328us
_th_get_device              3.011us          2.784us                1          3.011us          2.784us
_th_get_device              3.460us          3.072us                1          3.460us          3.072us
_cast_Byte                 17.001us         17.408us                1         17.001us         17.408us
_th_get_device              4.109us          4.064us                1          4.109us          4.064us
_th_get_device              2.808us          2.752us                1          2.808us          2.752us
index                     975.918us       1005.408us                1        975.918us       1005.408us
_th_get_device              3.208us          3.072us                1          3.208us          3.072us
nonzero                   339.928us        615.424us                1        339.928us        615.424us
select                     30.331us          1.024us                1         30.331us          1.024us
select                      5.766us          1.024us                1          5.766us          1.024us
mul                       257.175us         81.920us                1        257.175us         81.920us
mul                       146.566us        147.456us                1        146.566us        147.456us
add_                       19.227us         53.248us                1         19.227us         53.248us
view                        9.385us          2.048us                1          9.385us          2.048us
take                       86.470us         69.632us                1         86.470us         69.632us
```

We can see that advanced indexing is now much faster.

One more point is, this pull request is based on https://github.com/pytorch/pytorch/pull/10374, so it include changes there. I suggest not reverting these changes. Since wrap indices is expensive, it worth to add a custom cuda kernel to do that job to reduce cost. Adding it to `native_functions.yaml` allows automatic dispatching CPU and GPU. I'm planning this in a future PR to see how much a custom kernel can improve.

2018-08-09 15:58 UTC, ezyang commented
Haven't read the patch completely, but I'm a little confused about the numbers; doesn't it look like the CPU total time got worse?

2018-08-09 17:42 UTC, zasdfgbnm commented
@ezyang Does it look worse? Doesn't the total time for `index` reduce from `1832.829us` to `975.918us`?

2018-08-09 18:17 UTC, goldsborough requested changes

2018-08-09 18:17 UTC, goldsborough commented on aten/src/ATen/native/Indexing.cpp
> +static bool hasContiguousSubspace(std::vector<std::tuple<Tensor, bool>> tl) {
This should be `const std::vector<std::tuple<Tensor, bool>>&` or `at::ArrayRef<std::tuple<Tensor, bool>>`, right now you're making a copy each time.

2018-08-09 18:17 UTC, goldsborough commented on aten/src/ATen/native/Indexing.cpp
> +transposeToFront(Tensor self, std::vector<std::tuple<Tensor, bool>> indices) {
Copying `indices` here too (fix to `const&` or `ArrayRef`)

2018-08-09 18:17 UTC, goldsborough commented on aten/src/ATen/native/Indexing.cpp
> +static Tensor computeLinearIndex(const Tensor & src, std::vector<std::tuple<Tensor, bool>> indices) {
copying argument

2018-08-09 18:17 UTC, goldsborough commented on aten/src/ATen/native/Indexing.cpp
> +static std::vector<std::tuple<Tensor, bool>>
copying argument

2018-08-09 19:08 UTC, zasdfgbnm commented
@goldsborough Done

2018-08-09 20:36 UTC, colesbury commented
I'm not sure this is worth it, since it makes the code more complicated. We still have to wrap indices if they're not the result of a nonzero, which is much more common.

We need to speed up advanced indexing, but that's going to be a more substantial change.

2018-08-14 04:50 UTC, soumith commented
@zasdfgbnm do you agree or disagree with @colesbury ? I'd like to see you unblocked in your perf, whether it's via this PR or in another ways

2018-08-14 19:51 UTC, zasdfgbnm commented
@soumith My application was simple, so I just replace advanced indexing with `masked_select` and the performance improved a lot. I was using advanced indexing, because it looks neater than `masked_select` and I was assuming the performance should be comparable.

And yes, I do think the hacking I'm making in this PR is ugly, but I do think we need some mechanism to handle special cases for better performance. Maybe something like:

```C++
if (indices.size() == 1 && indices[0].type().scalarType() == kByte) {
  return self.masked_select(indices[0]);
}
```

2018-08-14 21:09 UTC, fmassa commented
@zasdfgbnm We have already tried in the past to add some special-case handling in the indexing code https://github.com/pytorch/pytorch/pull/6770, but the TH/THC functions are less generic and don't handle all cases (like negative indices), so the patch was reverted.

I agree with @colesbury that we should preferably make the indexing code more efficient.

2018-08-16 19:37 UTC, colesbury commented
@zasdfgbnm I think the special case you suggest might work. You would also need to check that `indices[0].sizes() == self.sizes()` since advanced indexing handles broadcasting but masked_select does not.

2018-08-19 19:09 UTC, zasdfgbnm commented
close this in favor of https://github.com/pytorch/pytorch/pull/10668

2018-08-19 19:09 UTC, closed without merging