Fix bug for buffer reuse
pytorch/pytorch pull request #103720
Opened 2023-06-15 23:44 UTC by FindHao

When disable `allow_buffer_reuse` in `torch/_inductor/config.py`, the buffer reuse still happens. This PR fixes the missing check.

2023-06-16 04:05 UTC, jansel requested changes
This type of reuse is actually controlled by `config.inplace_buffers` (in the check above).

`inplace_buffers` means reusing a kernel input as the output

`allow_inplace_buffers` means reusing a buffer for an unrelated purpose.

Perhaps we could add a comment to config.py clarifying the difference.

2023-06-16 18:41 UTC, FindHao commented
@jansel Thanks for your clarification! I changed the check to `config.inplace_buffers` and update the comments in config.py. There is also an error for double `del` in the wrapper codes. The final stage `free_buffers` didn't check the buffer freed in the inplace buffer reusing, so the buffer freed previously will be freed again. Could you tell me if the fix is correct?

2023-06-20 18:47 UTC, jansel approved these changes

2023-06-20 18:48 UTC, jansel commented
@pytorchbot merge

2023-06-20 23:28 UTC, closed without merging