[onnx] Convert aten::flatten with 0d input to onnx Reshape and 1d to Identity
pytorch/pytorch pull request #104089
Opened 2023-06-23 04:12 UTC by CYuxian

Avoid empty tensor generated by Slice op if using _flatten_helper for aten::flatten with 0d/1d input.

2023-06-23 14:57 UTC, thiagocrepaldi reviewed
Thank you for your first PR!
Could you add a unit test that verifies the new behavior?

2023-06-24 10:07 UTC, CYuxian commented
> Thank you for your first PR! Could you add a unit test that verifies the new behavior?

Sure, will add a test to test_onnx_opset.py.

2023-06-26 08:56 UTC, CYuxian commented
> Thank you for your first PR! Could you add a unit test that verifies the new behavior?

Test has been added. Please @thiagocrepaldi help to review, thanks!

2023-06-26 17:18 UTC, thiagocrepaldi requested changes
Linter is breaking CI.

To fix it, on your bash terminal, run:
```
make setup_lint
lintrunner init
lintrunner -a
```
Then resubmit the PR with the changes

2023-06-28 14:39 UTC, thiagocrepaldi approved these changes

2023-06-28 14:40 UTC, thiagocrepaldi commented
@pytorchbot merge

2023-06-28 17:01 UTC, closed without merging