[Xcode 15][caffe2] Avoid redundant redeclaration of 'constexpr' static data member
pytorch/pytorch pull request #104049
Opened 2023-06-22 17:40 UTC by cesar-vargas88

Summary: Handling the `out-of-line definition of constexpr static data member is redundant in C++17 and is deprecated [-Werror,-Wdeprecated]` warning on Xcode 15.

Test Plan: Build

Reviewed By: n0shake

Differential Revision: D46875270

2023-06-22 18:09 UTC, malfet requested changes
All PyTorch builds should be done with C++17 compliant compiler, so it feels like it's better to just remove the this block.

2023-06-22 21:24 UTC, malfet approved these changes

2023-06-22 21:24 UTC, malfet commented on aten/src/ATen/core/dynamic_type.cpp
>  ivalue::TupleTypeFactory<TupleType>::fallback(const Type& type) {
This is the intention, isn't it?
```suggestion
TORCH_API TupleTypePtr
ivalue::TupleTypeFactory<TupleType>::fallback(C10_UNUSED const Type& type) {
```

2023-06-28 00:15 UTC, cesar-vargas88 commented
@pytorchbot rebase

2023-06-28 00:18 UTC, cesar-vargas88 commented
@pytorchbot rebase -b main

2023-06-28 18:42 UTC, cesar-vargas88 commented
@pytorchbot rebase

2023-06-30 03:48 UTC, huydhn commented
I think we have an interesting case when the merge process was impacted by GitHub outage yesterday.  The diff D46875270 was landed internally and the merge was triggered on OSS.  However, the merge was never finished creating a divergence between OSS and fbcode.  I will merge this manually now.

2023-06-30 03:48 UTC, huydhn commented
@pytorchbot merge

2023-06-30 06:52 UTC, huydhn commented
@pytorchbot merge

2023-06-30 06:59 UTC, closed without merging