Add check for malformed tensor in load.
pytorch/pytorch pull request #104044
Opened 2023-06-22 14:31 UTC by kobrineli

Hi! We've been fuzzing torchvision project with [sydr-fuzz](https://github.com/ispras/oss-sydr-fuzz).
We've found the input for the `torch::load` function, which makes `data_ptr` field of input Tensor `NULL` after loading from file. This can lead to the null pointer dereference later, the example with reproducing is shown below.
To prevent the error we suggest to add the check for the `data_ptr` field.

torchvision version: 9d0a93eee90bf7c401b74ebf9c8be80346254f15

pytorch version: 0f1621df1a0a73956c7ce4e2f72f069e610e0137

OS: Ubuntu 20.04

How to reproduce

1. Build docker from [here](https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/torchvision) and run the container:

        sudo docker build -t oss-sydr-fuzz-torchvision .
        sudo docker run --privileged --rm -v `pwd`:/fuzz -it oss-sydr-fuzz-torchvision /bin/bash

2. Run the target on this input: [null-ptr-deref-vec.txt](https://github.com/pytorch/pytorch/files/11835087/null-ptr-deref-vec.txt)

        /encode_png_fuzz null-ptr-deref-vec.txt

3. You will see the following output:

        =================================================================
        AddressSanitizer:DEADLYSIGNAL
        ==936==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000011582f19 bp 0x7ffc439944b0 sp 0x7ffc439943c0 T0)
        ==936==The signal is caused by a READ memory access.
        ==936==Hint: address points to the zero page.
            #0 0x11582f19 in at::vec::AVX2::Vectorized8<unsigned char>::loadu(void const*) /pytorch/aten/src/ATen/cpu/vec/vec256/vec256_int.h:681:12
            #1 0x11582f19 in function_traits<at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(at::vec::AVX2::Vectorized<unsigned char>)&>::ArgsTuple at::native::AVX2::dereference_vec_impl<function_traits<at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(at::vec::AVX2::Vectorized<unsigned char>)&>, 0ul>(char* restrict*, function_traits<at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(at::vec::AVX2::Vectorized<unsigned char>)&>::result_type const&, unsigned long, long, std::integer_sequence<unsigned long, 0ul>) /pytorch/aten/src/ATen/native/cpu/Loops.h:73:7
            #2 0x11581524 in function_traits<at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(at::vec::AVX2::Vectorized<unsigned char>)&>::ArgsTuple at::native::AVX2::dereference_vec<function_traits<at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(at::vec::AVX2::Vectorized<unsigned char>)&> >(char* restrict*, function_traits<at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(at::vec::AVX2::Vectorized<unsigned char>)&>::result_type const&, unsigned long, long) /pytorch/aten/src/ATen/native/cpu/Loops.h:80:10
            #3 0x11581524 in void at::native::AVX2::vectorized_loop<at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(unsigned char)&, at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(at::vec::AVX2::Vectorized<unsigned char>)&>(char**, long, long, at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(unsigned char)&, at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(at::vec::AVX2::Vectorized<unsigned char>)&) /pytorch/aten/src/ATen/native/cpu/Loops.h:213:18
            #4 0x11580a03 in at::native::AVX2::VectorizedLoop2d<at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(unsigned char), at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(at::vec::AVX2::Vectorized<unsigned char>)>::operator()(char**, long const*, long, long) /pytorch/aten/src/ATen/native/cpu/Loops.h:275:9
            #5 0x11580a03 in void c10::function_ref<void (char**, long const*, long, long)>::callback_fn<at::native::AVX2::VectorizedLoop2d<at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(unsigned char), at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(at::vec::AVX2::Vectorized<unsigned char>)> >(long, char**, long const*, long, long) /pytorch/c10/util/FunctionRef.h:43:12
            #6 0x8c1eb6 in at::internal::serial_for_each(c10::ArrayRef<long>, c10::ArrayRef<long>, char**, unsigned long, c10::function_ref<void (char**, long const*, long, long)>, at::Range) /pytorch/aten/src/ATen/TensorIteratorInternal.h:65:7
            #7 0x8bff21 in at::TensorIteratorBase::serial_for_each(c10::function_ref<void (char**, long const*, long, long)>, at::Range) const /pytorch/aten/src/ATen/TensorIterator.cpp:777:3
            #8 0x83d498 in std::function<void (long, long)>::operator()(long, long) const /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/std_function.h:622:14
            #9 0x83ce7a in at::internal::invoke_parallel(long, long, long, std::function<void (long, long)> const&)::$_0::operator()(int, unsigned long) const /pytorch/aten/src/ATen/ParallelNative.cpp:168:9
            #10 0x83ce7a in void std::__invoke_impl<void, at::internal::invoke_parallel(long, long, long, std::function<void (long, long)> const&)::$_0&, int, unsigned long>(std::__invoke_other, at::internal::invoke_parallel(long, long, long, std::function<void (long, long)> const&)::$_0&, int&&, unsigned long&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/invoke.h:60:14
            #11 0x8246f2 in std::function<void (int, unsigned long)>::operator()(int, unsigned long) const /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/std_function.h:622:14
            #12 0x822039 in at::(anonymous namespace)::_run_with_pool(std::function<void (int, unsigned long)> const&, unsigned long) /pytorch/aten/src/ATen/ParallelNative.cpp:96:3
            #13 0x820e00 in at::internal::invoke_parallel(long, long, long, std::function<void (long, long)> const&) /pytorch/aten/src/ATen/ParallelNative.cpp:183:3
            #14 0x8c0703 in void at::parallel_for<at::TensorIteratorBase::for_each(c10::function_ref<void (char**, long const*, long, long)>, long)::$_5>(long, long, long, at::TensorIteratorBase::for_each(c10::function_ref<void (char**, long const*, long, long)>, long)::$_5 const&) /pytorch/aten/src/ATen/Parallel-inl.h:31:3
            #15 0x8bf680 in at::TensorIteratorBase::for_each(c10::function_ref<void (char**, long const*, long, long)>, long) /pytorch/aten/src/ATen/TensorIterator.cpp:751:5
            #16 0x115802cc in void at::native::AVX2::cpu_kernel_vec<true, at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(unsigned char), at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(at::vec::AVX2::Vectorized<unsigned char>)>(at::TensorIteratorBase&, at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(unsigned char)&&, at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::$_7::operator()() const::'lambda'()::operator()() const::'lambda'(at::vec::AVX2::Vectorized<unsigned char>)&&, long) /pytorch/aten/src/ATen/native/cpu/Loops.h:352:8
            #17  [...]

2023-06-22 22:06 UTC, jbschlosser commented
Hey @kobrineli, thanks for the contribution! I think a bit more investigation & a unit test are required before accepting a fix. Given that `read_tensor` has an empty storage here, it may be preferable to set the output tensor to match rather than erroring out.

Unfortunately, I'm not aware of anyone who currently owns the code in this area, so sadly I can't guarantee anyone will take a look at this soon.

2023-06-24 16:28 UTC, bdhirsh approved these changes
this looks reasonable to me. thanks for the fix!

2023-06-24 16:29 UTC, bdhirsh requested changes
sorry, that approval was a bit preemptive and agreed with Joel's comments.

2023-06-27 08:19 UTC, kobrineli commented
@jbschlosser
Hi! What do you mean  `set the output tensor to match`? Should it have zero shape and size or something like that?

2023-07-03 13:35 UTC, kobrineli commented
@jbschlosser
Hi! Do we really need to set the output tensor to match, when we have the empty storage? In case with the attached input and the example above, we have a non-empty input, which leads to the tensor with empty storage but with non-zero dimension and sizes, so I think this case must be reported and the execution needs to be aborted.

Unfortunately, I still don't understand exactly what error leads to non-zero sizes of tensor with empty storage, but I think that this simple check is ok until the moment the real problem is investigated.

2023-07-27 09:28 UTC, kobrineli commented
@bdhirsh 
Hi! I still think that this check is enough.
Anyway, having this check is better than not having it, the program will not crash with it, so maybe just add it?

2023-10-25 10:34 UTC, closed without merging