Use Homebrew OpenMP on macOS for dynamo
pytorch/pytorch pull request #104192
Opened 2023-06-26 15:21 UTC by lhoenig

Fixes https://github.com/pytorch/pytorch/issues/95708

Ship `omp.h` in `torch/include` and add Homebrew OpenMP library search path if Homebrew is installed.

With this change, `torch.compile` on macOS CPU works for me now (install OpenMP via `brew install libomp`.

2023-06-27 15:46 UTC, malfet requested changes
Change looks good to me, but please do not check omp.h into the PyTorch codebase, but rather bundle it during packaging step in `setup.py`, for example see https://github.com/pytorch/pytorch/blob/ad2905ad27ad8b770713e29683601da08643cec7/setup.py#L461

Also, it only needs to be bundle if PyTorch has been built with OpenMP supprt

2023-06-27 23:01 UTC, lhoenig commented
> Change looks good to me, but please do not check omp.h into the PyTorch codebase, but rather bundle it during packaging step in `setup.py`, for example see
> 
> https://github.com/pytorch/pytorch/blob/ad2905ad27ad8b770713e29683601da08643cec7/setup.py#L461
> 
> Also, it only needs to be bundle if PyTorch has been built with OpenMP supprt

Ok have a question about that -
So compiling with `LIBRARY_PATH=/opt/homebrew/opt/libomp/lib CFLAGS="-I/opt/homebrew/opt/libomp/include" python3 setup.py install` enables the `USE_OPENMP` flag and builds PyTorch with OpenMP enabled. Which method should I then use to locate `omp.h`? Should I use paths relative to the linked `libomp.dylib`, basically bundling `libomp.dylib/../include/omp.h`, or resolve the file using some cmake functionality that uses the same search path as during compilation? I guess directly using `CFLAGS` should be avoided but I'm not sure about the best way to get `omp.h` in `setup.py`.

2023-06-29 11:15 UTC, lhoenig commented
Oh ok I still had `omp.h` in my tree when using the `setup.py` command above. Deleting `omp.h` from `torch/include`, then deleting `build/` and re-compiling, compilation fails and seems to reveal a problem: the generated MPS compile commands don't include the CMake CXXFLAGS at all - but all other parts of PyTorch do for any C/C++ files. That is what `compile_commands.json` reveals. So I think this may need to be fixed first.

2023-06-29 11:34 UTC, lhoenig commented
> Oh ok I still had `omp.h` in my tree when using the `setup.py` command above. Deleting `omp.h` from `torch/include`, then deleting `build/` and re-compiling, compilation fails and seems to reveal a problem: the generated MPS compile commands don't include the CMake CXXFLAGS at all - but all other parts of PyTorch do for any C/C++ files. That is what `compile_commands.json` reveals. So I think this may need to be fixed first.

Ok, of course they are not C/C++ files but `.mm`, i.e. Objective-C++ code, this is why the standard CXXFLAGS don't apply to these compilation units I realize. They are OBJCXX objects and not CXX objects. But setting `OBJCXXFLAGS` does not seem to work, hence I am still not sure how to inject the libomp include path into these compilation commands. libomp is installed keg-only by brew, that is why it is not in the system header search paths.

2023-06-29 12:23 UTC, lhoenig commented
I dug a little more and found that this functionality is implemented already in `cmake/Dependencies.cmake`:
```cmake
if(USE_OPENMP AND NOT TARGET caffe2::openmp)
  include(${CMAKE_CURRENT_LIST_DIR}/Modules/FindOpenMP.cmake)
  if(OPENMP_FOUND)
    message(STATUS "Adding OpenMP CXX_FLAGS: " ${OpenMP_CXX_FLAGS})
    if(APPLE AND USE_MPS)
      string(APPEND CMAKE_OBJCXX_FLAGS " ${OpenMP_CXX_FLAGS}")
    endif()
    ...
```

But `OpenMP_CXX_FLAGS` only  contains `-Xpreprocessor -fopenmp`, which also show up in the relevant compilation commands. This flag string comes from `cmake/Modules/FindOpenMP.cmake` which also seems to be aware of a special need for handling the this special case of ObjC++ and the OMP header:

```cmake
    if(WIN32)
      # Prefer Intel OpenMP header which can be provided by CMAKE_INCLUDE_PATH.
      # Note that CMAKE_INCLUDE_PATH is searched before CMAKE_SYSTEM_INCLUDE_PATH (MSVC path in this case)
      find_path(__header_dir "omp.h")
    else()
      # AppleClang may need a header file, search for omp.h with hints to brew
      # default include dir
      find_path(__header_dir "omp.h" HINTS "/usr/local/include")
    endif()
    set(OMP_FLAG_AppleClang "-Xpreprocessor -fopenmp" "-Xpreprocessor -fopenmp -I${__header_dir}")
```

I am not too familiar with CMake but it seems that `__header_dir` ends with `-NOTFOUND` and thus the second string is not used, and we end up with the first string that doesn't contain the include dir.

Not sure what the best way to fix this is, I suppose if the brew formula weren't keg-only, there wouldn't be all these problems as everything would be in the system header search path, but there's probably a good reason for it.

`/usr/local` is not the brew default include dir though I think, regardless? Maybe the arguments to `find_path` could be updated?

2023-06-29 13:39 UTC, lhoenig commented
> /usr/local is not the brew default include dir though I think, regardless? Maybe the arguments to find_path could be updated?

That was half correct. `/usr/local` is actually the default brew prefix, expect on Apple Silicon, where it is `/opt/homebrew`. And of course for MPS, Apple Silicon environments are the most (only?) relevant ones.

> I suppose if the brew formula weren't keg-only, there wouldn't be all these problems

Turned out to be correct. Running `brew link --force libomp` and then doing a fresh build using the default command `python3 setup.py install` works without any problems and both the header and library are found, even without the above
suggested modification. I'm not sure why the formula is keg-only. There don't seem to be any preinstalled OpenMP files on macOS as far as I can tell, so there shouldn't be any conflicts.

So, to summarize, if the user installs libomp via brew **and** force-links it, detection will work automatically, otherwise it may require some modifications.

Regardless, the question of where to get the `omp.h` path from during the bundling step remains. Using the CMake Python API could be an option I suppose.

2023-09-27 15:34 UTC, closed without merging