[benchmark][export] Add torch.export passrate for TB/HF/TIMM benchmarks
pytorch/pytorch pull request #104382
Opened 2023-06-28 23:44 UTC by willfengg

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

issues resolved: https://github.com/pytorch/pytorch/issues/104294

local test
* python benchmarks/dynamo/torchbench.py -d cuda --inference --accuracy --progress --export
* python benchmarks/dynamo/timm_models.py -d cuda --inference --accuracy --progress --export
* python benchmarks/dynamo/huggingface.py -d cuda --inference --accuracy --progress --export

local test result
* torchbench P779570524

2023-06-30 22:05 UTC, yanboliang commented
Offline discussed with @willfengg:
* Correct the pass rate number, e.g, TIMM has 61 models and only one error, that pass rate should be 98%.
* Take a further look at HF pass rate, a bit wired. Check if applying ```torch.compile``` directly on top of models can make different, and figure out why HF benchmark has so many failures like ```Dynamo input and output is a strict subset of traced input/output```.

2023-07-05 17:09 UTC, willfengg commented
> Offline discussed with @willfengg:
> 
> * Correct the pass rate number, e.g, TIMM has 61 models and only one error, that pass rate should be 98%.
> * Take a further look at HF pass rate, a bit wired. Check if applying `torch.compile` directly on top of models can make different, and figure out why HF benchmark has so many failures like `Dynamo input and output is a strict subset of traced input/output`.

TIMM pass rate error is fixed and now it is 95% (58 ouf of 61 passed). I also updated TB and HF. The root cause for inaccurate pass error was because: I started TB/TIMM runs at the same time and they both write results to the same file export.csv. Now I run each one independently, they are good

for HF failure 'Dynamo input and output is a strict subset of traced input/output',  unlike TIMM or TB, candidate_args is a subclass of transformers.modeling_outputs.ModelOutput instead of a tensor. id(MaskedLMOutput) in dict_of_source_args will fail, but id(MaskedLMOutput.logits) can pass the assert code pointer: https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/eval_frame.py#L884

2023-07-05 17:43 UTC, zhxchen17 requested changes
looks great and thanks for the work! some comment.

2023-07-05 17:43 UTC, zhxchen17 commented on benchmarks/dynamo/common.py
> +            torch._dynamo.export,
The correct API to use should be torch._export.export(). If you check the implementation it uses _dynamo.export internally as well and have extra logic to make sure we preserve all metadata correctly.

2023-07-05 22:33 UTC, zhxchen17 approved these changes

2023-07-06 05:42 UTC, willfengg commented
@pytorchbot merge

2023-07-06 17:14 UTC, willfengg commented
@pytorchbot label "topic: not user facing"

2023-07-06 17:14 UTC, willfengg commented
@pytorchbot merge

2023-07-06 17:16 UTC, closed without merging