[dynamo] Add `tensorrt` backend for Torch compile
pytorch/pytorch pull request #104426
Opened 2023-06-29 16:58 UTC by gs-olive

#94632 reserved the `tensorrt` namespace in Dynamo compile and this PR adds the corresponding implementation for it, as a reference to [`torch_tensorrt.dynamo.backend.torch_tensorrt_backend`](https://github.com/pytorch/TensorRT/blob/2844630aa8301bc937eb38356026973f74024c0e/py/torch_tensorrt/dynamo/backend/backends.py#L27-L33). This is a placeholder backend which we intend to point to whichever backend implementation is the intended default in Torch-TensorRT. We have a growing suite of tests ([see here](https://github.com/pytorch/TensorRT/tree/2844630aa8301bc937eb38356026973f74024c0e/py/torch_tensorrt/dynamo/backend/test)) which test this backend in multiple different contexts.

- Add backend code to `tensorrt` placeholder file, with imports nested in try/except clauses to fail gracefully
- Add skipped test to CI
- Add documentation to compile docs

cc: @narendasan

2023-06-29 17:09 UTC, gs-olive commented
@pytorchbot label "release notes: dynamo"

2023-07-17 21:05 UTC, malfet requested changes
Can you please explain, why it needs to be intree vs just available via the extensions point?

2023-07-17 23:05 UTC, gs-olive commented
@msaroufim asked us to push this up as a way to make sure there are no collisions on the `tensorrt` name from alternative backends

2023-07-17 23:32 UTC, msaroufim commented
@malfet I think this is fine to merge in core because
1. There was already a `tensort` backend but it was not correctly referencing the right one
2. The code does not include tensorrt specific bits
3. The test is skipped by default in CI so we aren't including unwanted dependencies

2023-07-17 23:40 UTC, malfet commented
@msaroufim is there a document somewhere, that outlines that this is an acceptable pattern for certain backends to avoid naming conflicts?

2023-07-18 00:16 UTC, msaroufim commented
Well the name conflict problem is specific to backends that have already been merged. The original problem was the `tensorRT` backend was using ONNXRT

So our options are either we merge this change or remove both backends. Current situation is not good

2023-07-18 17:32 UTC, gs-olive commented
@pytorchbot rebase

2023-08-30 22:03 UTC, gottbrath commented
Just chiming in with my 2c here: 

This looks reasonable as an integration of an out-of-core back-end. 

TensorRT team has been working on this integration for a while. We know that in the past there was a non-official implementation that was removed and someone redirected the TensorRT back end name to the ONNX runtime. 

Since we've already seen the TensorRT name get unintentionally but effectively hijacked I can certainly understand why the TensorRT team would like to ensure that it stays reserved.

2023-09-12 18:34 UTC, gs-olive commented
Closed subsequent to discussion, in favor of https://github.com/pytorch/TensorRT/pull/2311

2023-09-12 18:34 UTC, closed without merging