Update reduce_scatter_tests to work for world_size > 1
pytorch/pytorch pull request #104424
Opened 2023-06-29 16:54 UTC by H-Huang

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-06-29 18:00 UTC, kwen2501 requested changes

2023-06-29 21:37 UTC, H-Huang commented on test/distributed/test_c10d_nccl.py
> +        output_tensors = torch.zeros(2, 2).to(self.rank)
I'm not entirely sure how coalesced collectives work, is it able to operate on different parts of the same tensor? In this test world_size=2 so

output_tensors = [[0, 0], [0, 0]]
input_tensors = [[[1, 1],[1, 1]], [[1, 1],[1, 1]]]

coalesced (twice)
dist.reduce_scatter_tensor([0,0], [[1,1], [1,1]])

so each row of output_tensors ([0,0]) will be updated with reduce_scatter from itself and the other rank, for a total of 4 reduce_scatters. The test is passing, but does that assumption work?

2023-06-29 21:38 UTC, H-Huang commented
CI failures are due to Github outage, will rerun when github is back

2023-07-06 15:35 UTC, H-Huang commented
@pytorchbot rebase

2023-08-21 20:09 UTC, awgu approved these changes
Thanks!

2023-08-21 20:09 UTC, awgu commented on test/distributed/test_c10d_nccl.py
> +        output_tensors = torch.zeros(2, 2).to(self.rank)
@H-Huang  this matches my understanding. 

@kwen2501 The test looks okay to me: @H-Huang  is using dim-0 of `output_tensors` as the "list".

2023-08-21 20:19 UTC, H-Huang commented
@pytorchbot merge -r

2023-08-21 23:14 UTC, closed without merging