Add
pytorch/pytorch pull request #104475
Opened 2023-06-30 18:54 UTC by drisspg

Fixes #ISSUE_NUMBER

2023-07-08 20:19 UTC, ezyang approved these changes

2023-07-08 20:19 UTC, ezyang commented
@pytorchbot merge

2023-07-10 22:47 UTC, malfet requested changes
Just use `append_cxx_flag_if_supported`, because not all versions of clang will support it

2023-07-10 22:47 UTC, malfet commented on CMakeLists.txt
> +  endif()
```suggestion
  append_cxx_flag_if_supported("-fstandalone-debug" CMAKE_CXX_FLAGS_DEBUG)
```

2023-07-10 22:51 UTC, drisspg commented
@pytorchbot merge

2023-07-10 23:04 UTC, malfet approved these changes

2023-07-11 01:29 UTC, closed without merging