[Dynamo] Enable torch._dynamo.config.suppress_errors by default
pytorch/pytorch pull request #105307
Opened 2023-07-17 05:52 UTC by yanboliang

Summary:
We are working toward full model compilation, where when compilation error happens, we just fall back to eager mode rather than error out.
But at the same time, we should fix these issues if the particular function frame can be compiled correctly. We will:
* 1/ log warnings in OSS;
* 2/ log warnings and write them into Scuba in fbcode;
to prevent us from ignoring these issues.

Test Plan: Manual test

Differential Revision: D47506314

2023-07-17 16:38 UTC, jansel requested changes

2023-07-17 16:38 UTC, jansel commented on torch/_dynamo/exc.py
> +def format_error_msg(exc, code, record_filename=None, frame=None, verbose=config.verbose):
this will read `config.verbose` at program startup, but then ignore any changes to it after that.

2023-07-17 22:05 UTC, ezyang commented
What's the oncall monitoring plan for the scuba stats?

2023-07-18 05:43 UTC, yanboliang commented
> What's the oncall monitoring plan for the scuba stats?

1/ I'll add one more responsibility for PT2 internal oncall and update runbook;
2/ I'll regularly check the scuba table, triage and fix these issues.

2023-07-18 16:09 UTC, jansel commented on torch/_dynamo/config.py
> +suppress_errors = bool(os.environ.get("TORCHDYNAMO_SUPPRESS_ERRORS", True))
```suggestion
suppress_errors = os.environ.get("TORCHDYNAMO_SUPPRESS_ERRORS", "1")=="1"
```

Prior code would confusingly mean `TORCHDYNAMO_SUPPRESS_ERRORS=0` does nothing.

2023-07-21 17:20 UTC, yanboliang commented
@jansel kindly remind in case you miss this.

2023-07-21 18:57 UTC, jansel approved these changes

2023-07-21 19:17 UTC, closed without merging