[BE]: pyupgrade Python to 3.8 - remove extraneous parentheses only - `torch/` only
pytorch/pytorch pull request #105498
Opened 2023-07-18 20:41 UTC by bryant1410

Same as #101606 but only for the `torch/` folder.

2023-07-18 20:48 UTC, albanD commented
Won't this conflict with https://github.com/pytorch/pytorch/pull/105436 ?

2023-07-18 22:12 UTC, Skylion007 approved these changes

2023-07-19 18:40 UTC, albanD requested changes
Since https://github.com/pytorch/pytorch/pull/105436 contains more things, let's land it first, we can rebase an land the remaining of this PR afterwards

2023-07-21 16:09 UTC, bryant1410 commented
Okay, I'm closing this one as the only change now (after the related PRs have been merged) is removing an empty blank line and this change is already reflected in #101606

2023-07-21 16:09 UTC, closed without merging