[inductor] Enable vectorization in fbcode
pytorch/pytorch pull request #105756
Opened 2023-07-21 18:51 UTC by bertmaher

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

The method of running a test binary doesn't really work well in fbcode
for various reasons, but there's no reason to do it;
`torch.backends.cpu.get_cpu_capability()` will tell us AVX2 or AVX512 (or
DEFAULT).

I think this might actually be a better method even outside of fbcode, but I
don't have a great way to test AVX512 behavior.

Differential Revision: [D47678649](https://our.internmc.facebook.com/intern/diff/D47678649/)

2023-07-21 20:00 UTC, jansel requested changes
I'd vote for just using `torch.backends.cpu.get_cpu_capability()` always and not diverging behavior based on `is_fbcode()`

2023-07-21 22:34 UTC, bertmaher commented
Cool.  As long as the run-a-test-script approach doesn’t have some hidden benefit that I’m not seeing, I prefer that approach as well

2023-07-21 22:39 UTC, mikekgfb commented
A unified approach seems more robust to me, and I think it would be great to have a unified solution.
If we need more build time or hardware time data, we can quite plausibly obtain this by extending the get_cpu_capability with whatever hardware queries are necessary?

2023-07-22 02:11 UTC, bertmaher commented
> A unified approach seems more robust to me, and I think it would be great to have a unified solution. If we need more build time or hardware time data, we can quite plausibly obtain this by extending the get_cpu_capability with whatever hardware queries are necessary?

I think so.  It seems like a pretty minimalist interface right now, just exposing a few target ISAs.  If we want to get really fancy, it'd be nice to have python bindings for https://github.com/pytorch/cpuinfo (which is the C library we call into to get feature flags)

2023-07-24 13:34 UTC, bertmaher commented
Okay, I'm reverting to the subprocess approach; get_cpu_capability is possibly buggy, and I was able to figure out how to get subprocess calls to python working properly @ FB anyways

2023-07-24 14:21 UTC, desertfire commented
> In CI, we apparently are picking INVALID_VEC_ISA (at least when running inductor_timm_cpu_accuracy)

Hmm, this is a problem. @EikanWang , can you help to investigate?

2023-07-24 14:24 UTC, bertmaher commented
> > In CI, we apparently are picking INVALID_VEC_ISA (at least when running inductor_timm_cpu_accuracy)
> 
> Hmm, this is a problem. @EikanWang , can you help to investigate?

Here is some example output from a previous version of the diff where I logged what we are picking: https://ossci-raw-job-status.s3.amazonaws.com/log/15275831688

2023-07-24 16:35 UTC, mikekgfb approved these changes
Looks good to me.  Approving.

2023-07-24 18:27 UTC, jansel approved these changes

2023-07-25 08:01 UTC, closed without merging