[quant][pt2e] Add reference representation for quantized conv2d
pytorch/pytorch pull request #105784
Opened 2023-07-22 05:26 UTC by jerryzh168

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Summary:
Implementing reference representation for quantized ops we decided in https://docs.google.com/document/d/17h-OEtD4o_hoVuPqUFsdm5uo7psiNMY8ThN03F9ZZwg/edit#heading=h.ov8z39149wy8

Test Plan:
python test/test_quantization.py TestQuantizePT2E.test_representation_quantize_dequantize_per_channel

Although right now it is not really testing things since there is some problem with dynamo export

Summary:

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

2023-08-03 23:39 UTC, kimishpatel requested changes

2023-08-03 23:39 UTC, kimishpatel commented on torch/ao/quantization/pt2e/representation/rewrite.py
> +    out_i8 = torch.ops.aten.clamp(acc_i32, out_quant_min, out_quant_max).to(torch.int8)
You havent added bias to acc_i32

2023-08-03 23:39 UTC, kimishpatel commented on torch/ao/quantization/pt2e/representation/rewrite.py
> +    out_i8 = torch.ops.aten.clamp(acc_i32, out_quant_min, out_quant_max).to(torch.int8)
Also, requantization happens after adding bias. and you need to add out_zero_point too.

2023-08-08 16:58 UTC, kimishpatel approved these changes
unblock:

please add comments, that we landing this to unblock but this needs to be vetted since these are not functionally tested and some comments are not addressed

2023-08-09 16:07 UTC, jerryzh168 commented
> unblock:
> 
> please add comments, that we landing this to unblock but this needs to be vetted since these are not functionally tested and some comments are not addressed

I have tested these locally and fixed the bias stuff as well, will probably enable the tests in CI soon since I didn't find it is timing out in sandcastle recently. what is the not addressed comment are you referring to btw?

2023-08-09 19:56 UTC, jerryzh168 commented
@pytorchbot merge

2023-08-09 19:58 UTC, jerryzh168 commented
TODO: we need to support autograd for out_dtype op so that user don't need to use torch.no_grad to run the quantized model.

2023-08-09 22:41 UTC, closed without merging