removing some redundant str splits
pytorch/pytorch pull request #106089
Opened 2023-07-26 23:47 UTC by Borda

drop some redundant string splits, no factual changes, just cleaning the codebase

2023-07-27 12:42 UTC, mikaylagawarecki commented
@pytorch rebase

(rebasing as it looks like there is some duplication with https://github.com/pytorch/pytorch/pull/106013)

2023-07-27 12:48 UTC, mikaylagawarecki commented
@pytorchbot rebase

2023-07-27 12:53 UTC, mikaylagawarecki commented
@pytorchbot rebase

2023-07-27 12:53 UTC, albanD approved these changes

2023-07-27 16:45 UTC, malfet approved these changes

2023-07-27 16:45 UTC, malfet commented
@pytorchbot merge -i

2023-07-27 16:46 UTC, malfet commented
I'll fwd fix lint failures when this PR lands

2023-07-27 17:12 UTC, albanD commented
@Borda could you rebase on latest main and fix the lint please?

2023-07-27 19:57 UTC, albanD commented
@pytorchbot merge

Thanks!

2023-07-28 15:01 UTC, albanD commented
Ho the lint is still not ok :/

2023-07-31 08:04 UTC, Borda commented
> Ho the lint is still not ok :/

is there a log I could check because to mee all seems fine...

2023-08-30 20:16 UTC, Borda commented
This link complains looks the same to me... :thinking: 
```
    2026  2026 |     param_to_param_names = _get_param_to_fqns(model)
    2027  2027 |     for param_names in param_to_param_names.values():
    2028  2028 |         assert (
    2028       |-len(param_names) > 0
          2029 |+len(param_names) > 0
    2030  2030 |         ), "`_get_param_to_fqns()` should not construct empty lists"
    2031  2031 |         if len(param_names) > 1:
    2032  2032 |             raise RuntimeError(

2023-08-30 20:29 UTC, mikaylagawarecki commented
@borda this is what I see on the CI logs [here](https://hud.pytorch.org/pr/106089). Seems like it is complaining about the lack of spaces.

<img width="849" alt="Screenshot 2023-08-30 at 4 26 24 PM" src="https://github.com/pytorch/pytorch/assets/35276741/132c8655-abf0-4edb-8a03-e0c33b487b3b">


To fix the failing lint job running `setup_lint` and `quicklint` from your local pytorch directory and following the corresponding instructions (running lintrunner -a to fix the remaining failures) should be sufficient, see [here](https://github.com/pytorch/pytorch/blob/4721553431e968ee5e90753346d92252cce98e84/Makefile#L25-L34)

2023-08-30 20:34 UTC, Borda commented
> this is what I see on the CI logs [here](https://hud.pytorch.org/pr/106089), but it seems like you see something different locally (?). Seems like it is complaining about the lack of spaces.

o, then there is some issue with how the logs are passed to the GH check at the bottom of a PR because this is what you can find there:
![image](https://github.com/pytorch/pytorch/assets/6035284/ace64c93-065e-4a31-9f73-3983b50586fd)

2023-08-30 20:45 UTC, awgu commented on torch/distributed/tensor/parallel/api.py
> + # Copyright (c) Meta Platforms, Inc. and affiliates
Curious: Is this added space intentional?

2023-08-30 21:22 UTC, Borda commented on torch/distributed/tensor/parallel/api.py
> + # Copyright (c) Meta Platforms, Inc. and affiliates
```suggestion
# Copyright (c) Meta Platforms, Inc. and affiliates
```

2023-08-30 21:25 UTC, mikaylagawarecki commented
@pytorchbot merge

2023-08-31 21:32 UTC, albanD requested changes
I think the one in collect_env is not ok. Rest looks good.

2023-08-31 21:32 UTC, albanD commented on torch/utils/collect_env.py
> +        cudnn_cmd = 'ldconfig -p | grep libcudnn | rev | cut -d -f1 | rev'
This does NOT look right!

2023-08-31 21:53 UTC, Borda commented on torch/utils/collect_env.py
> +        cudnn_cmd = 'ldconfig -p | grep libcudnn | rev | cut -d -f1 | rev'
ahh, my mistake, thx
```suggestion
        cudnn_cmd = 'ldconfig -p | grep libcudnn | rev | cut -d" " -f1 | rev'
```

2023-08-31 22:04 UTC, albanD approved these changes
Thanks!

2023-08-31 22:04 UTC, albanD commented
@pytorchbot merge

2023-09-01 00:23 UTC, closed without merging