implement autograd function trace
pytorch/pytorch pull request #1061
Opened 2017-03-22 15:33 UTC by chenyuntc

implement autograd  function   `trace` in linalg, and add it to Variable.
also add tests

2017-03-22 15:52 UTC, soumith commented
@pytorchbot test this please!

2017-03-22 16:19 UTC, apaszke requested changes

2017-03-22 16:19 UTC, apaszke commented on torch/autograd/_functions/linalg.py
> +        return grad_output[0] * (torch.eye(*self.size)).type_as(grad_output)
I think it's better to expand the `grad_output` and call `torch.diag` on it. This implementation will do a large CPU -> GPU transfer, just to create the identity matrix.

2017-03-22 16:57 UTC, Haoyanlong commented
it's too late here, I'll fix it tomorrow.

2017-03-22 17:13 UTC, apaszke commented
Can you please fix the lint error? Looks good now.

2017-03-22 17:13 UTC, apaszke approved these changes

2017-03-22 17:15 UTC, soumith commented
i've fixed the lint

2017-03-22 17:15 UTC, soumith approved these changes

2017-03-22 17:42 UTC, fmassa commented on torch/autograd/_functions/linalg.py
> +        return torch.diag(grad_output.expand(self.size[0]))
`trace` supports non-square matrices. Maybe we should support that as well?

2017-03-22 17:44 UTC, soumith commented
Over here, I wrote a trace Function that correctly computes it for non-square matrices as well:
https://discuss.pytorch.org/t/function-for-trace/1015/2?u=smth

```
class CustomTrace(torch.autograd.Function):
    
    def forward(self, input):
        self.isize = input.size()
        return input.new([torch.trace(input)])
    
    def backward(self, grad_output):
        isize = self.isize
        grad_input = grad_output.new(isize).copy_(torch.eye(*isize))
        grad_input.mul_(grad_output[0])
        return grad_input
```

2017-03-22 17:49 UTC, apaszke commented
I really think we should somehow avoid the CPU -> GPU copy... I think that using some smart stride tricks we could zero the gradient and only fill the diagonal (tensor that has stride[0] = size[1] + 1, and appropriate size will be a 1D view on the diagonal)

2017-03-22 17:50 UTC, fmassa commented
The only annoying thing is that we calling `torch.eye` generates it on the CPU, and I'm not sure we already have a CUDA support for `torch.eye`.
We can get the `eye` function by something like
```python
a = torch.zeros(3, 2)
b = a.view(-1)
b[::3] = 1
print(a)
```

2017-03-22 18:18 UTC, apaszke commented
Yeah, that's exactly what I wanted to do. Create a zeroed grad output of appropriate size, take a square slice, and fill the view of the diagonal with grad output

2017-03-23 03:36 UTC, chenyuntc commented
```python
class Trace(Function):

    def forward(self, input):
        self.isize = input.size()
        return input.new((input.trace(),))

    def backward(self, grad_output):
        isize = self.isize
        grad_input = grad_output.new(isize).zero_()
        grad_input.view(-1)[::(isize[1] + 1)] = grad_output[0]
        return grad_input
```
is this implementation ok?

2017-03-23 09:36 UTC, apaszke approved these changes

2017-03-23 09:37 UTC, merged

2017-03-23 09:37 UTC, apaszke commented
Thanks!