Documentation fix in contributing.md file
pytorch/pytorch pull request #106119
Opened 2023-07-27 07:29 UTC by Cyril-Anto

Fixes #104872 Errors in contributing.md file

2023-07-27 18:06 UTC, kit1980 commented on CONTRIBUTING.md
> +This will run clang-tidy on the entire codebase or on your changes only, respectively.
lintrunner will not only run clang-tidy, but other linters.

2023-07-27 18:32 UTC, malfet requested changes
Please see suggested changes.
And please test the commands, read tool documentation before proposing updates (i.e. `lintrunner CHANGED_ONLY=--changed-only` is just syntactically incorrect)

2023-07-27 18:32 UTC, malfet commented on CONTRIBUTING.md
>  We currently only support Linux and MacOS (x86).
This steps becomes redundant, if you are to use `lintrunner`

2023-07-27 18:32 UTC, malfet commented on CONTRIBUTING.md
> +lintrunner
```suggestion
lintrunner --take CLANG-TIDY --all-files
```

2023-07-27 18:32 UTC, malfet commented on CONTRIBUTING.md
> +lintrunner CHANGED_ONLY=--changed-only
```suggestion
lintrunner --take CLANGTIDY
```

2023-08-04 14:23 UTC, Cyril-Anto commented
@malfet Please review the suggested changes.

2023-08-08 11:26 UTC, Cyril-Anto commented
@eellison Can you please review the suggested changes

2023-08-10 16:25 UTC, Cyril-Anto commented
@malfet I've made the changes based on your suggestions, and can you please review them again?

2023-08-10 16:28 UTC, malfet commented
@Cyril-Anto did you tried running the commands you've proposed?(Hint: they will not work, as you forgot to init the linters) And  last paragraph contradicts proposed linter invocation, isn't it?

2023-08-17 21:08 UTC, malfet requested changes
Please do not request re-reviews until you address the feedback

2023-08-17 21:08 UTC, malfet commented on CONTRIBUTING.md
> +The reason why LLVM 8 is needed is because it is the version of LLVM that clang-tidy was tested with.
Sorry, can you please elaborate what you mean by that? As one can see from tools/linter/adapters/s3_init_config.json as of time of this writing, clang-tidy from llvm-15 is used

2023-11-16 02:37 UTC, closed without merging