Fix Clang compilation error with Lib ATen for ppc64le
pytorch/pytorch pull request #106446
Opened 2023-08-02 06:22 UTC by pratiklp00

This patch fixes error while compiling with Clang for ppc64le
Errors are as follow:
No matching function for call to 'vec_sel’
No matching function for call to 'vec_splats'
Excess elements in scalar initializer
Use of undeclared identifier 'vec_vsubudm'
Fix for multiple error within int64_t  DEFINE_MEMBER_OP_AND_ONE

2023-08-17 09:32 UTC, pratiklp00 commented
@malfet @XiaobingSuper Hi, please let me know if there is any suggestion or change/comment

2023-08-17 21:03 UTC, malfet requested changes
Few remakrs:
 - Please specify clang version in PR description and reference some doc explaining why `__attribute((altivec(vector__))` does not work for clang, but works for gcc , and vice versa (i.e. if say gcc-9+ supports `__attribute__((vector_size(16))` as alternative to altivec attribute, perhaps entire code can be changed to it
 - Please explain why `vint64` needs to be defined as `signed long long` rather than `signed long` or even `int64_t`? (This would also avoid force casting `vec_splats`, wouldn't it?)

2023-09-20 03:05 UTC, pratiklp00 commented on aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h
> +#if !defined(vec_splats)
No, I will combine it.

2023-09-20 03:29 UTC, pratiklp00 commented on aten/src/ATen/cpu/vec/vec256/vsx/vec256_int64_vsx.h
> +      : _vec0{vec_splats((ElementType)scalar)}, _vec1{(vint64)vec_splats((ElementType)scalar)} {}
I have removed them.

2023-09-20 03:48 UTC, pratiklp00 commented on aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h
> + return vec_splats(static_cast<signed long long>(a));
No it is not different. I will remove the casting.

2023-10-09 06:47 UTC, vinithakv commented
@pratiklp00 
Some extra spaces reported by linter. Otherwise looks good to me.

2023-10-23 03:44 UTC, pratiklp00 commented
@malfet Hi, I have made the required changes Please review it.

2023-11-09 02:13 UTC, pratiklp00 commented
@malfet @ezyang @ezyang Hi Please let me know if any changes are required.

2023-11-09 14:23 UTC, malfet commented
@pratiklp00 at the very list current form of the change break CI all over the place, can you please fix it?

2023-11-09 14:23 UTC, malfet commented
@pytorchbot rebase

2023-11-09 14:26 UTC, malfet commented on aten/src/ATen/cpu/vec/vec256/vsx/vec256_complex_float_vsx.h
> +         vec_sel(a._vec1, b._vec1,reinterpret_cast<vbool32>(mask_complex._vec1)),
```suggestion
        vec_sel(a._vec0, b._vec0,reinterpret_cast<vbool32>(mask_complex._vec0)),       
        vec_sel(a._vec1, b._vec1,reinterpret_cast<vbool32>(mask_complex._vec1)),
```

2023-11-09 14:26 UTC, malfet commented on aten/src/ATen/cpu/vec/vec256/vsx/vec256_complex_float_vsx.h
> +         vec_sel(a._vec1, b._vec1, reinterpret_cast<vbool32>(mask._vec1)),
```suggestion
        vec_sel(a._vec0, b._vec0, reinterpret_cast<vbool32>(mask._vec0)),
        vec_sel(a._vec1, b._vec1, reinterpret_cast<vbool32>(mask._vec1)),
```

2023-11-09 14:28 UTC, malfet approved these changes

2023-11-09 14:28 UTC, malfet commented
@pytorchbot merge

2023-11-09 15:57 UTC, malfet commented on aten/src/ATen/cpu/vec/vec256/vsx/vec256_complex_float_vsx.h
> +        vec_sel(a._vec0, b._vec0,reinterpret_cast<vbool32>(mask_complex._vec0)),
```suggestion
        vec_sel(a._vec0, b._vec0,reinterpret_cast<vbool32>(mask_complex._vec0)),
```

2023-11-09 15:58 UTC, malfet commented on aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h
> +#endif
```suggestion
#endif
```

2023-11-09 15:58 UTC, malfet commented on aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h
> +#endif
```suggestion
#endif
```

2023-11-09 16:00 UTC, malfet commented on aten/src/ATen/cpu/vec/vec256/vsx/vec256_complex_float_vsx.h
> +        vec_sel(a._vec1, b._vec1,reinterpret_cast<vbool32>(mask_complex._vec1)),
```suggestion
        vec_sel(a._vec0, b._vec0, reinterpret_cast<vbool32>(mask_complex._vec0)),
        vec_sel(a._vec1, b._vec1, reinterpret_cast<vbool32>(mask_complex._vec1)),
```

2023-11-09 16:00 UTC, malfet commented on aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h
> +#endif
```suggestion
#if defined(__clang__) && !defined(vec_splats)
C10_ALWAYS_INLINE vint64 vec_splats(const int64_t& a) {
  return vec_splats(a);
}
#endif
```

2023-11-09 17:25 UTC, malfet commented
@pytorchbot merge -f "Lint is green"

2023-11-09 17:27 UTC, closed without merging