Enable Mypy Checking in torch/_inductor/fx_passes/split_cat.py
pytorch/pytorch pull request #106538
Opened 2023-08-03 08:36 UTC by Cyril-Anto

Fixes #105230 Enable Mypy Checking in torch/_inductor

2023-08-03 17:55 UTC, Skylion007 commented on torch/_inductor/fx_passes/split_cat.py
> +            return # type: ignore[return-value]
This does seem like an actual bug in our typing logic. Should be equivalent to returning None

2023-08-03 17:55 UTC, Skylion007 commented on torch/_inductor/fx_passes/split_cat.py
> +            return None # type: ignore[return-value]
We probably need to mark the return type as an Optional here too

2023-08-07 06:31 UTC, Cyril-Anto commented
@Skylion007 Kindly review the changes made.

2023-08-10 18:41 UTC, Cyril-Anto commented
@Skylion007 I've made the changes based on your suggestions, and can you please review them again?

2023-08-13 19:25 UTC, Skylion007 commented on torch/_inductor/fx_passes/split_cat.py
> +            return # type: ignore[return-value]
Should be return None here too?

2023-08-13 19:26 UTC, Skylion007 commented on torch/_inductor/fx_passes/split_cat.py
> +                        return # type: ignore[return-value]
And here

2023-08-13 19:26 UTC, Skylion007 commented on torch/_inductor/fx_passes/split_cat.py
> +    ) -> Optional[List[Tuple[int, int]]]:
The return type here just looks entirely wrong and needs to be changed.

2023-08-13 19:27 UTC, Skylion007 requested changes
The return types for these functions need to be fixed.

2023-08-31 06:10 UTC, Cyril-Anto commented
@Skylion007 I have made the changes you suggested, Can you please do review it once?

2023-12-10 15:33 UTC, closed without merging