[Quantization] Make annotation util functions return annotated nodes
pytorch/pytorch pull request #107106
Opened 2023-08-13 23:22 UTC by kimishpatel

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Summary:
Having annotation functions return nodes that are annotated is useful
specifically for adding "quantization_tag" to those nodes

Test Plan:
CI

Reviewers:

Subscribers:

Tasks:

Tags:

2023-08-14 17:41 UTC, jerryzh168 commented on torch/ao/quantization/quantizer/xnnpack_quantizer_utils.py
> +            print(p.nodes)
please remove print before landing

2023-08-14 17:43 UTC, jerryzh168 requested changes
please update the return type for annotate functions in xnnpack_quantizer.py as well

2023-08-18 23:25 UTC, kimishpatel commented
@kimishpatel has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D48488415).

2023-08-18 23:36 UTC, jerryzh168 approved these changes

2023-08-24 21:50 UTC, kimishpatel commented
@kimishpatel has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D48488415).

2023-08-31 17:28 UTC, kimishpatel commented
@kimishpatel has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D48488415).

2023-08-31 23:30 UTC, kimishpatel commented
@kimishpatel has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D48488415).

2023-09-01 00:49 UTC, kimishpatel commented
@kimishpatel has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D48488415).

2023-09-01 15:40 UTC, kimishpatel commented
@kimishpatel has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D48488415).

2023-09-01 20:20 UTC, kimishpatel commented
@kimishpatel has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D48488415).

2023-09-02 06:20 UTC, closed without merging