fix: flake8-bugbear code B024
pytorch/pytorch pull request #107265
Opened 2023-08-15 23:13 UTC by fapont

Fixes #106571 item B024

This fix concerns the addition of @abstractmethod to methods declared inside abstract classes.

Should I also include PEP8 compliant reformatting on the files I had to modify ?

2023-08-15 23:18 UTC, fapont commented
I'm not sure to understand why my commit is not authorized even after several attempt to generate my CLA

2023-09-28 23:43 UTC, kit1980 approved these changes

2023-09-28 23:45 UTC, kit1980 commented
Looks good to me, thanks.
Regarding re-formatting, the formatting should be already correct.
If not for some reason, then it should a separate PR.

2023-09-28 23:45 UTC, kit1980 commented
@pytorchbot merge -r

2023-09-28 23:47 UTC, kit1980 commented
I removed "Fixes" from the description because we don't want to close the issue yet (and GitHub will autoclose seeing "Fixes").

2023-09-29 00:09 UTC, kit1980 commented
@fapont There is an error, please see https://github.com/pytorch/pytorch/actions/runs/6345393257/job/17237391159?pr=107265

> TypeError: Can't instantiate abstract class ConfigurableQuantizeHandler with abstract methods is_custom_module, is_standalone_module

2023-09-29 00:11 UTC, kit1980 requested changes

2023-09-29 00:11 UTC, kit1980 commented on torch/ao/quantization/fx/quantize_handler.py
> +    @abstractmethod
This should not be marked abstract.

2023-09-29 00:11 UTC, kit1980 commented on torch/ao/quantization/fx/quantize_handler.py
>      def is_standalone_module(self):
This should not be marked abstract.

2023-09-29 00:11 UTC, kit1980 commented on torch/ao/quantization/fx/quantize_handler.py
> +    @abstractmethod
Doesn't look abstract to me.

2023-10-03 16:30 UTC, kit1980 approved these changes

2023-10-03 16:32 UTC, fapont commented
Hi @kit1980, thank you for your feedback. I removed unnecessary decorator. I'm waiting for the tests to run and then try to find something else to do :)

2023-10-03 16:55 UTC, fapont commented
A problem.. I'll take a look at it and suggest a solution when I get home

2023-10-03 16:57 UTC, kit1980 commented
> A problem.. I'll take a look at it and suggest a solution when I get home

I'd say just add # noqa: B024 for those. Not every abstract class must have abstract methods.

2023-10-04 13:17 UTC, fapont commented
This time it should be good.
- I fixed few warnings by adding "# noqa: B024"
- I fixed instance creation error by implementing a dummy function here https://github.com/pytorch/pytorch/pull/107265/files#diff-bb87e3b609df0eee1ef22dad1fd3a122cc5b0102106e5451f60cae0ef3dbc07bR75
- I added `isort` suggestion on 1 file (auto formatting on other would change too much things and affect PR review visibility)

2023-10-04 23:50 UTC, kit1980 commented
@pytorchbot merge

2023-10-04 23:52 UTC, closed without merging