Expose dynamic_dim and register_dataclass_as_pytree_node under torch.compiler
pytorch/pytorch pull request #107304
Opened 2023-08-16 17:22 UTC by gmagogsfm

2023-08-16 20:10 UTC, msaroufim commented on torch/compiler/__init__.py
> +    Note - [On Export Dynamic Dimension UX]
I'm not sure this will render correctly so worth taking a look at docbuild and seeing what this will actually look like

2023-08-16 20:11 UTC, msaroufim commented on torch/compiler/__init__.py
> +    Registers a customized flatten/unflatten/serialization/deserialization for a dataclass.
same comment as above, new code snippets look fine but just wanna make sure docstrings are correct when you look at docs so plz post a screenshot when you're done

2023-08-17 19:15 UTC, avikchaudhuri requested changes
I have a general question. What motivates moving this to `torch.compiler` instead of `torch.export`? IMO this API is tied to export, no?

2023-08-17 19:15 UTC, avikchaudhuri commented on torch/compiler/__init__.py
> +    After a lot of discussion, we have settled on a dynamic marking API
This docstring should be rewritten (at least the early part is very old). We have docs you can pull from. Also, document equality constraints.

2023-08-18 20:17 UTC, ezyang commented
Hottest of hot takes: `torch.export` should be a module. You should say `torch.export.export` and we can put other utilities in this module.

2023-08-24 18:56 UTC, closed without merging