Enable Mypy Checking in torch/_inductor/scheduler.py
pytorch/pytorch pull request #108138
Opened 2023-08-29 09:13 UTC by Cyril-Anto

Fixes #105230 

Summary:

As suggested in https://github.com/pytorch/pytorch/issues/105230 mypy checking is enabled in torch/_inductor/kernel/scheduler.py

After Fix:

mypy --follow-imports=skip torch/_inductor/kernel/scheduler.py Success: no issues found in 1 source file

2023-08-29 13:54 UTC, Skylion007 requested changes
Many of these fixes to the typing are not correct / need to be better specified. I went through the top half of the commit to provide some examples.

2023-08-29 13:54 UTC, Skylion007 commented on torch/_inductor/scheduler.py
> +            *[x.recursive_predecessors for x in snodes] # type: ignore[arg-type]
While you are changing this, it probably should be a generator instead of a list.

2023-08-29 13:54 UTC, Skylion007 commented on torch/_inductor/scheduler.py
> +        self.min_order = min([x.min_order for x in self.snodes]) # type: ignore[type-var]
Likewise with these two lines are generators instead of lists

2023-08-29 13:54 UTC, Skylion007 commented on torch/_inductor/scheduler.py
> +        future_used_buffers = set() # type: ignore[var-annotated]
This just needs to be specified as what type of set it is. Ie Set[Buffer] or whatever the proper type is.

2023-08-29 13:54 UTC, Skylion007 commented on torch/_inductor/scheduler.py
> +        self.origins: set = set()
What's stored in the set though?

2023-09-01 22:40 UTC, ipiszy reviewed
Thanks @Cyril-Anto for working on this!

FYI I had a draft PR to fix this long time ago: https://github.com/pytorch/pytorch/pull/105600/. Then it was somehow dropped. I just tried to resume it and found your PR. I would probably just discard my original PR.

It seems to me that some `type: ignore` can be avoided by adding some type hints or adding some conditions in code. Could you help try that? Thanks!

2023-09-01 22:40 UTC, ipiszy commented on torch/_inductor/scheduler.py
> +                input_node: BaseSchedulerNode = self.scheduler.name_to_node.get( # type: ignore[assignment]
Should be `input_node: Optional[BaseSchedulerNode]`?

2023-09-06 00:55 UTC, eellison commented
defering to @ipiszy on this review

2023-09-25 16:39 UTC, ipiszy commented
Hi @Cyril-Anto, wonder are you still going to work on this PR?

2023-10-14 01:57 UTC, ipiszy commented
FYI I revived the previous PR: https://github.com/pytorch/pytorch/pull/105600.

2023-12-09 17:44 UTC, Skylion007 commented
Obsoleted by #105600

2023-12-09 17:44 UTC, closed without merging