[Inductor] Add fused_attention pattern matcher with additional clone
pytorch/pytorch pull request #108141
Opened 2023-08-29 10:48 UTC by Valentine233

A previous PR https://github.com/pytorch/pytorch/pull/106274 decomposes `aten.dropout` and would create a `clone()` when `eval()` or `p=0`. This makes many SDPA-related models fail to match fused_attention pattern matchers.

This PR adds new fused_attention pattern matchers with an additional clone to re-enable the SDPA op matching.

2023-08-29 13:57 UTC, jgong5 requested changes
Can we add `remove_extra_clones` call to `joint_graph_passes` the similar way as it is invoked in the post grad pass? This way, we don't need to add extra patterns to match the redundant clones.

2023-08-29 21:36 UTC, eellison approved these changes
@jgong5 the clone removal pass has subtle correctness conditions, so it might be better to do in post grad. we could look into doing it in the joint but I don't know if it should block this pr.

2023-08-30 00:39 UTC, jgong5 commented
> @jgong5 the clone removal pass has subtle correctness conditions, so it might be better to do in post grad. we could look into doing it in the joint but I don't know if it should block this pr.

Oh, I didn't realize it. Yes, let's get this PR in first then.

2023-08-30 00:39 UTC, jgong5 approved these changes

2023-08-30 00:51 UTC, eellison commented
@pytorchbot merge

2023-08-30 05:07 UTC, closed without merging