Adaptive max and average pooling (1D & 2D)
pytorch/pytorch pull request #1084
Opened 2017-03-24 08:57 UTC by xternalz

2017-03-24 14:35 UTC, apaszke reviewed
Looks good! Only some minor comments.

2017-03-24 14:35 UTC, apaszke commented on torch/nn/_functions/thnn/pooling.py
> +        self.output_size = output_size
Use `_single` here. This should be a 1-element tuple

2017-03-24 14:35 UTC, apaszke commented on torch/nn/_functions/thnn/pooling.py
> +        if (input.dim() != 3):
remove parenthesis

2017-03-24 14:35 UTC, apaszke commented on torch/nn/functional.py
> +def adaptive_max_pool2d(input, output_size, return_indices):
Use the same default for `return_indices` that we have for other pooling functions. Also, can you add at least some very short descriptions of these modules, so they show up in the docs?

2017-03-24 14:35 UTC, apaszke commented on torch/nn/functional.py
> +    if input.dim() != 3:
This check should be only done inside a Function

2017-03-24 23:17 UTC, xternalz commented
@apaszke please check again.

2017-03-25 16:43 UTC, apaszke reviewed
Looks good apart from my two comments (no idea how could the tests pass), and a conflict in `__init__.py`.

2017-03-25 16:43 UTC, apaszke commented on torch/nn/_functions/thnn/pooling.py
> +                                                       self.output_size, 1)
How is it possible that it works without unpacking the tuple?

2017-03-25 16:43 UTC, apaszke commented on torch/nn/_functions/thnn/pooling.py
> +            self.output_size[1], self.output_size[0])
Shouldn't one of the sizes be a 1 constant here? How could that even pass the tests?

2017-03-25 23:47 UTC, xternalz commented on torch/nn/_functions/thnn/pooling.py
> +                                                       self.output_size, 1)
which tuple are you referring to?

2017-03-25 23:48 UTC, xternalz commented on torch/nn/_functions/thnn/pooling.py
> +            self.output_size[1], self.output_size[0])
fixed this.

2017-03-26 12:10 UTC, apaszke requested changes

2017-03-26 12:10 UTC, apaszke commented on torch/nn/_functions/thnn/pooling.py
> +        self.output_size = output_size
Why did you revert it so that it no longer uses `_single` here? I already said it should be a tuple.

2017-03-26 12:10 UTC, apaszke commented on torch/nn/_functions/thnn/pooling.py
> +                                                       self.output_size, 1)
Why not just use `self.output_size[0]`?

2017-03-26 12:31 UTC, xternalz commented
How is `output_size` for `AdaptiveMaxPool1d` or `AdaptiveAvgPool1d` a tuple, not a single integer? Isn't it should be similar to `kernel_size` of `MaxPool1d`?

2017-03-26 12:38 UTC, apaszke commented
I didn't notice that, but I think it's better to keep it a tuple, so that the attribute types are the same for any dimension. We should change other pooling functions too, but just leave it for now, because it will need some additional `__setattr__` methods for backward compatibility.

2017-03-26 14:27 UTC, apaszke approved these changes

2017-03-26 14:27 UTC, apaszke commented
@pytorchbot test this please

2017-03-26 15:09 UTC, merged

2017-03-26 15:09 UTC, apaszke commented
Thanks!