Fix bug with pickling optimizers and then adding param groups
pytorch/pytorch pull request #10906
Opened 2018-08-27 16:46 UTC by person594

__setstate__ in optimizer doesn't save self.defaults, and so this field does not persist through pickling.  This causes add_param_group to fail on optimizers which have been pickled and unpickled.  This should fix that.

2018-08-29 10:49 UTC, person594 commented
Has anyone had a chance to review this yet?

2018-08-29 17:58 UTC, soumith commented
thanks @person594 . This looks good. can you add a test to test_optim.py so that we dont regress on this in the future.

2018-11-20 17:29 UTC, ailzhang commented
I'll add a test and merge this.

2018-11-20 17:35 UTC, person594 commented
Thank you :)

On Tue, Nov 20, 2018, 18:30 Ailing <notifications@github.com> wrote:

> I'll add a test and merge this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pytorch/pytorch/pull/10906#issuecomment-440360473>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGMmYVtMAiqyWx96E88VQ3KnpmV66ESQks5uxDwvgaJpZM4WOHjS>
> .
>

2018-12-07 02:16 UTC, ailzhang commented
@person594 I pushed a testcase for it. 
As a side note, I'm not sure what's your usecase that need `defaults` to be set. But a more common usage is `torch.save(opt.state_dict(), 'filename')` and the `opt.load_state_dict(`filename`)` which doesn't contain `defaults` value.

2019-02-26 17:46 UTC, VitalyFedyunin requested changes

2019-02-26 17:46 UTC, VitalyFedyunin commented on test/test_optim.py
> +        filename = 'test_save_optim.pth'
Please generate file names randomly. This will allow to run tests in parallel.

2019-02-26 17:46 UTC, VitalyFedyunin commented on test/test_optim.py
> +            os.remove(filename)
If any assert fails you are not cleaning up file. Consider using try, finally blocks.

2022-06-27 20:35 UTC, closed without merging