Adding index function for lists
pytorch/pytorch pull request #109284
Opened 2023-09-14 10:03 UTC by Deusy94

Fixes #109031

2023-09-14 14:13 UTC, Deusy94 commented
@pytorchbot label "realease notes: dynamo"

2023-09-14 14:13 UTC, Deusy94 commented
@pytorchbot label "release notes: dynamo"

2023-09-15 15:28 UTC, ezyang commented
Needs tests

2023-09-15 16:43 UTC, voznesenskym commented on torch/_dynamo/variables/lists.py
> +def _index_helper(items, search, tx, args, options):
Lots of as_python_constant() and ConstantVariable() is sus, I don't believe this will work properly for a lot of types.

2023-09-15 16:44 UTC, voznesenskym commented on torch/_dynamo/variables/lists.py
> +def _index_helper(items, search, tx, args, options):
I don't see SliceVariable created directly, or indirectly (wrap_slice_range). You might be doing that via BuiltinVariable below but it is not clear to me.

2023-09-15 16:47 UTC, voznesenskym commented on torch/_dynamo/variables/lists.py
> +        raise ValueError(f"\'{search.as_python_constant()}\' is not in list")
I would let eager handle this

2023-09-15 16:48 UTC, voznesenskym requested changes
Missing tests, missing guards. It's hard to trust that the impl is right off the cuff like this.

Please add the following tests:

1) regular indexing
2) indexing with a slice
3) Indexing with invalid indices
4) negative indexing

With lists that are composed of all of, or some of: constants, Tensors, UDOs.

An important test aside from functionality is around recompilation to ensure we propagate guards correctly.

2023-09-15 17:35 UTC, Deusy94 commented
Thank you for answering, it's my first issue, I'll do my best!
I think I can manage to fix what you said here, it still seems easy enough!

2023-09-27 14:23 UTC, ezyang commented
any progress on this?

2023-09-27 14:37 UTC, Deusy94 commented
I'm still on it, but I had some other work that blocked me.
I'm a bit stuck on some case, I think the use of BuiltinVariable should be enough if the input are not constant. 
do you have any suggestion?

2023-10-04 12:07 UTC, ezyang commented
Can you redo this PR using a polyfill? I just landed https://github.com/pytorch/pytorch/pull/109972 which gives a recipe for how to do it. You have to implement index in pure Python using only operations supported by Dynamo.

2024-01-02 12:40 UTC, closed without merging