Switch to CUDA event based profiling
pytorch/pytorch pull request #109338
Opened 2023-09-15 00:18 UTC by ipiszy

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-09-15 04:30 UTC, frank-wei approved these changes
LGTM!

2023-09-15 09:31 UTC, aakhundov requested changes
@ipiszy Should we also change these call sites: 

1. https://github.com/pytorch/pytorch/blob/0cbca85707eb95ad40babc4edadaf614a5ca86e1/torch/_inductor/select_algorithm.py#L648

2. https://github.com/pytorch/pytorch/blob/0cbca85707eb95ad40babc4edadaf614a5ca86e1/torch/_inductor/codegen/common.py#L1068

2023-09-15 20:05 UTC, ipiszy commented
@pytorchbot merge

2023-09-15 20:06 UTC, ipiszy commented
Thanks @adnanaziz ! Good catch! Sorry I missed these.

2023-09-15 20:14 UTC, ipiszy commented
@pytorchbot label "topic: not user facing"

2023-09-15 20:15 UTC, ipiszy commented
@pytorchbot merge

2023-09-15 21:00 UTC, ipiszy commented
@pytorchbot merge

2023-09-17 03:17 UTC, ipiszy commented
@pytorchbot merge

2023-09-17 06:03 UTC, ipiszy commented
@pytorchbot merge -f "unrelated failure"

2023-09-17 06:04 UTC, closed without merging