[WIP] Better invariants - always route list/tuple to their requisite VTs instead of ConstantVariable
pytorch/pytorch pull request #109869
Opened 2023-09-22 07:59 UTC by voznesenskym

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-09-22 14:20 UTC, ezyang commented
Can you do the ConstantVariable.create change on its own? I'll stamp it. (BTW, if you don't want to update the call sites, you can technically make the constructor do what you want by defining `__new__` on ConstantVariable lol)

2023-09-22 17:41 UTC, voznesenskym commented
> Can you do the ConstantVariable.create change on its own? I'll stamp it. (BTW, if you don't want to update the call sites, you can technically make the constructor do what you want by defining `__new__` on ConstantVariable lol)

no `__new__` please. Also `.create` is a well known pattern in dynamo. Also sure, can make the change on its own.

2023-09-22 18:58 UTC, jansel approved these changes

2023-09-22 19:34 UTC, voznesenskym commented
@pytorchbot merge

2023-09-22 22:38 UTC, voznesenskym commented
@pytorchbot merge

2023-09-22 22:44 UTC, voznesenskym commented
@pytorchbot merge -f "Flaky ci"

2023-09-23 22:40 UTC, huydhn commented
@pytorchbot revert -m 'Sorry for reverting your change, but the failed test looks legit as it is also failing in trunk https://hud.pytorch.org/pytorch/pytorch/commit/06aa6966a88586d34e6470cc2149121d17971056' -c nosignal

Let me check why it's classified as flaky (it shouldn't)

2023-09-24 03:27 UTC, voznesenskym commented
@pytorchbot merge

2023-09-24 03:46 UTC, peterbell10 requested changes

2023-09-24 03:46 UTC, peterbell10 commented on torch/_inductor/utils.py
> +    return False
Staged the wrong file?

2023-09-24 04:53 UTC, voznesenskym commented on torch/_inductor/utils.py
> +    return False
yeah, weird

2023-09-24 04:55 UTC, voznesenskym commented
@pytorchbot merge

2023-09-24 04:57 UTC, voznesenskym commented
@pytorchbot merge

2023-09-24 04:57 UTC, voznesenskym commented
The CI fiasco on this pr has been vaguely awful

2023-09-24 08:52 UTC, closed without merging