Fix linalg_vector_norm ONNX export with wrong output dtype
pytorch/pytorch pull request #110078
Opened 2023-09-26 15:18 UTC by fxmarty

Up to now, the export of `aten::linalg_vector_norm` was wrongly giving as output dtype `torch.float32` although the input may be of other dtype. This does not match PyTorch behavior (e.g. see https://github.com/pytorch/pytorch/blob/23938640706214921c0c0c29b1ed4855a0536cd8/torch/_refs/linalg/__init__.py#L72 or https://github.com/pytorch/pytorch/blob/23938640706214921c0c0c29b1ed4855a0536cd8/aten/src/ATen/native/LinearAlgebra.cpp#L2713 - though the second one is quite unreadable to me, I would need to compile pytorch with `DEBUG=1` and use `TORCH_SHOW_DISPATCH_TRACE=1` to understand where the output is allocated).

Example of the issue:
```python
import torch
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = nn.Linear(10, 20)
        self.eps = 1e-12
        self.dim = -1
        
    def forward(self, x):
        denom = x.norm(2.0, self.dim, keepdim=True)
        print("denom", denom.dtype)
        return denom

model = MyModel()
model = model.eval().to(torch.float16).to("cuda")

inp = torch.rand(8, 10, device="cuda", dtype=torch.float16)

with torch.no_grad():
    res = model(inp)

    torch.onnx.export(model, (inp,), f="normalize.onnx")
```

giving out
![image](https://github.com/pytorch/pytorch/assets/9808326/44b3ea0b-e1d2-4f23-a963-e8bc8e7cb9df)
with the current implementation, while giving
![image](https://github.com/pytorch/pytorch/assets/9808326/dc737a45-bcc1-464e-bce0-d68728033a79)
in this proposed PR.

WDYT @justinchuby @BowenBao? This is an issue for the ONNX export in fp16 for some models, where ORT later raise at load time the error `FAIL : Load model from speecht5_onnx/decoder_model.onnx failed:Type Error: Type parameter (T) of Optype (MatMul) bound to different types (tensor(float) and tensor(float16)` due to this bug.

2023-09-26 16:07 UTC, thiagocrepaldi requested changes
Thanks @fxmarty 

Try using `JitScalarType.from_dtype` instead. Depending on some scenarios, directly calling `type()` or `dtype()` can raise an exception (because type information is not available).

[JitScalarType](https://github.com/pytorch/pytorch/blob/bd1229477dbf260d97f523cebcacdf685f030ce6/torch/onnx/_type_utils.py#L61) prevents that

2023-09-26 16:09 UTC, thiagocrepaldi commented
Please add a unit test too

2023-09-26 16:54 UTC, thiagocrepaldi reviewed
One last comment that I am not sure whether we really should care about, but this change is being done for onnx opset 9. however, bfloat16 was not introduced in reducemax/reducemin until opset 13. Ideally this PR should be broken in two: opset 9 and opset 13

2023-09-26 16:54 UTC, thiagocrepaldi commented on torch/onnx/symbolic_opset9.py
> +            result = g.op("Cast", result, to_i=_C_onnx.TensorProtoDataType.BFLOAT16)
```suggestion
        out_dtype = _type_utils.JitScalarType.from_value(self)
        if _try_get_scalar_type(k) != _type_utils.JitScalarType.FLOAT:
            result = g.op("Cast", result, to_i=out_dtype.onnx_type())
```
Maybe something like this (not tested)

2023-09-26 16:54 UTC, fxmarty commented
Thank you @thiagocrepaldi! Is `test/onnx/test_pytorch_onnx_onnxruntime.py` a good place to add a test?

2023-09-26 17:10 UTC, justinchuby commented
Please enable the test in https://github.com/pytorch/pytorch/blob/main/test/onnx/test_op_consistency.py

2023-10-03 20:53 UTC, thiagocrepaldi requested changes
Adding the test at https://github.com/pytorch/pytorch/blob/main/test/onnx/test_op_consistency.py should be ok.

2023-10-10 10:07 UTC, fxmarty commented
Thank you, updated on your suggestion.

Still have to understand how `SingleOpModel` and `ReductionOpInfo` work, having some unexpected and unrelated errors enabling `linalg.vector_norm` in test_op_consistency.py

2023-10-10 13:56 UTC, justinchuby commented
What are the errors? Feel free to push the changes in test for them to run in CI

2023-10-10 14:08 UTC, fxmarty commented
Typically:

```
torch.onnx.errors.SymbolicValueError: Unsupported: ONNX export of linalg_vector_norm in opset 9. ord=0 not supported. Please try opset version 11.  [Caused by the value '5 defined in (%5 : Float(*, strides=[1], device=cpu) = onnx::Reshape[allowzero=0](%0, %4), scope: test_op_consistency.SingleOpModel::
)' (type 'Tensor') in the TorchScript graph. The containing node has kind 'onnx::Reshape'.]
```

&

```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (/ReduceSum) Op (ReduceSum) [ShapeInferenceError] axis must be in [-rank, rank-1]. input rank was 0
```

2023-11-29 16:51 UTC, thiagocrepaldi commented
@fxmarty bump

2024-01-25 22:56 UTC, thiagocrepaldi commented
@fxmarty is this PR still relevant for you? Feel free to close otherwise

2024-01-26 07:59 UTC, fxmarty commented
@thiagocrepaldi Sorry did not have time to wrap it up. I'll see if the bug this PR fixes is still there.

2024-04-25 09:34 UTC, closed without merging