Grouped query attention
pytorch/pytorch pull request #110047
Opened 2023-09-25 23:23 UTC by drisspg

# Summary
Closed: #106730 in favor of this PR since the rebase would have been more difficult then just recreating.

There is still some edge cases I need to appropriately handle but this is how it could look.#109887 

## Design choices
This is currently implemented by looking at the "num heads" dimension, size(1) and determining if it can be repeat_interleaved to fill the query num_heads. 

Another option would be to pass in an explicit `groups` parameter to the top level SDPA and passing down.

2023-09-25 23:23 UTC, drisspg commented on aten/src/ATen/native/transformers/attention.cpp
> +#include "ATen/ops/repeat_interleave.h"
remove

2023-09-26 20:37 UTC, cpuhrsch requested changes
Please use an explicit keyword argument to enable this behavior.

We can always switch that to `True` by default, but right now your operator violates PyTorch broadcasting principles.

2024-02-10 08:20 UTC, Muennighoff commented
@drisspg Does the new PyTorch 2.2 support GQA / MQA? As this PR was closed, are there plans for adding it in the future if not?

2024-04-11 02:17 UTC, drisspg commented
@pytorchbot rebase

2024-05-11 08:33 UTC, closed without merging