[RELAND] Disallow skipping dynamo
pytorch/pytorch pull request #110222
Opened 2023-09-28 15:15 UTC by tugsbayasgalan

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-09-28 15:30 UTC, zhxchen17 approved these changes

2023-10-30 15:34 UTC, zhxchen17 commented
@pytorchbot merge

2023-11-07 18:03 UTC, tugsbayasgalan commented on torch/_export/exported_program.py
> +    def __call__(self, *args, **kwargs):
Should we also do this for forward?

2023-11-07 18:06 UTC, zhxchen17 commented
Can you also support this for unflattened module? You can find it in .module(flat=False)

2023-11-07 18:06 UTC, zhxchen17 requested changes

2023-11-07 18:08 UTC, tugsbayasgalan commented
@tugsbayasgalan has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51078056).

2023-11-09 03:57 UTC, zhxchen17 commented
@tugsbayasgalan test failures

2023-11-09 03:57 UTC, zhxchen17 requested changes
@tugsbayasgalan test failures

2023-11-12 00:38 UTC, tugsbayasgalan commented
@tugsbayasgalan has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51078056).

2023-11-14 02:23 UTC, zhxchen17 approved these changes

2023-11-14 15:59 UTC, zhxchen17 commented
@pytorchbot merge

2023-11-14 16:02 UTC, closed without merging