Update html jobs location in .circleci
pytorch/pytorch pull request #110442
Opened 2023-10-03 11:44 UTC by emmanuel-ferdman

**PR Summary**:
PR updates the location of `binary_update_htmls.yml` which was moved in PR #38688. Also fixes small typo error.

2023-10-03 18:23 UTC, kit1980 commented
@emmanuel-ferdman Thanks for fixing, but the circleci jobs are not used anymore for quite a long time.
I don't think we want to update that README, we should delete the whole .circleci dir soon.

2023-10-03 22:59 UTC, colesbury approved these changes

2023-10-03 23:00 UTC, colesbury requested changes
Oh, I missed @kit1980's comment. @kit1980, what do you want to do with this?

2023-10-04 00:03 UTC, kit1980 commented
> Oh, I missed @kit1980's comment. @kit1980, what do you want to do with this?

@colesbury I'm against landing this cause it may give a false impression that .circleci dir is current and relevant.
DevInfra has plans to migrate last useful bits from the dir and remove it.

2023-10-06 21:40 UTC, closed without merging