revert realize_input for ExternKernel
pytorch/pytorch pull request #110811
Opened 2023-10-08 05:36 UTC by Valentine233

Fixes #108754.

2023-10-08 07:03 UTC, jgong5 requested changes

2023-10-08 07:03 UTC, jgong5 commented on torch/_inductor/ir.py
> +            ):
According to the analysis in https://github.com/pytorch/pytorch/issues/108754#issuecomment-1751908453. The data layout to bmm before and after changes is actual the same. Note that the stride doesn't matter when the corresponding size is 1: `reinterpret_tensor(buf2, (8, 1, 64), (64, 512, 1))` and `reinterpret_tensor(buf2, (8, 1, 64), (64, 0, 1), 0)` are equivalent. We'd better understand why bmm is slower with the latter but not with the former first. Reverting the change here looks a workaround to me.

2023-10-09 08:07 UTC, lezcano approved these changes

2023-10-09 08:38 UTC, Chillee approved these changes

2023-10-10 06:44 UTC, jgong5 approved these changes

2023-10-10 06:48 UTC, closed without merging