Normalize gradients before reduction in DistributedDataParallelC10d
pytorch/pytorch pull request #11109
Opened 2018-08-30 21:17 UTC by myleott

Summary: Normalizing by the world size before the reduction is less likely to cause overflow in FP16 training.

Differential Revision: D9594708

2018-08-30 21:20 UTC, apaszke requested changes
Normalization should happen on the coalesced buffers instead of individual parameters

2018-09-02 03:34 UTC, soumith commented
would be super dope if you added a test for this, so that we dont regress on this in the future.

2018-09-08 21:38 UTC, myleott commented
@pytorchbot retest this please

2018-09-10 07:38 UTC, teng-li commented
@myleott agreeing on the above comment, it's super risky to do any DDP change right before our release

2018-09-10 11:32 UTC, myleott commented
I added the test. But also this is a pretty trivial change and without it fp16 training distributed is much worse.

2018-09-10 16:39 UTC, apaszke approved these changes
This might be important for stability and has a test now, so I'd vote to merge it before the release.

2018-09-10 20:56 UTC, closed without merging