torch.export: cannot instantiate Dim from REPL
pytorch/pytorch pull request #111231
Opened 2023-10-13 20:18 UTC by kflu

Summary:
```
In [1]: import torch
   ...: torch.export.Dim('foo', min=1, max=16)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 2
      1 import torch
----> 2 torch.export.Dim('foo', min=1, max=16)

File /..../torch/export/__init__.py:319, in Dim(name, min, max)
    317 assert _max > _min, f"Cannot create Dim with inconsistent min={min}, max={max}"
    318 dim = _Dim(name, (int,), {"min": _min, "max": _max})
--> 319 dim.__module__ = inspect.getmodule(inspect.stack()[1][0]).__name__  # type: ignore[union-attr]
    320 return dim

AttributeError: 'NoneType' object has no attribute '__name__'
```

Test Plan: Repeat above repro

Differential Revision: D50275165

2023-10-20 21:57 UTC, kflu commented
Hi @angelayi can I also get an approval here? Thanks.

2023-10-23 20:36 UTC, avikchaudhuri approved these changes

2023-10-23 20:37 UTC, avikchaudhuri commented
Thanks!

2023-10-27 19:36 UTC, kflu commented
@pytorchbot merge

2023-10-27 19:39 UTC, angelayi commented
@pytorchbot merge

2023-10-27 19:46 UTC, angelayi requested changes

2023-10-27 19:46 UTC, angelayi commented on torch/_export/__init__.py
> +class AotInductorTransformationHook:
Wait sorry, I didn't see this change. I would rather you just pass the passes to export.aot_compile instead of having these hooks.

2023-10-30 16:52 UTC, angelayi approved these changes

2023-10-30 17:13 UTC, zhxchen17 commented
@pytorchbot merge

2023-10-30 17:15 UTC, closed without merging