[Dynamo] add a hook to make dynamo generated bytecode debuggable
pytorch/pytorch pull request #111472
Opened 2023-10-18 12:05 UTC by youkaichao

Currently, dynamically translated bytecode from Dynamo can only be run as a black box. There are some tools like https://github.com/thuml/depyf to help understand the bytecode, but the scope is only for understanding.

This PR tries to take a step further, by wiring things together, so that **Dynamo generated bytecode is debuggable**. We can leverage the full-capability of existing debuggers.

This PR is not final, but just a proof-of-concept to discuss.

It requires running the program twice: 
- run the program with hooks, to generate source code.
- user set breakpoints in functions they want to debug.
- run the program again. the debugger will work smoothly.

There are two requirements, though:
- The correctness of decompiler (I partially tested its correctness at https://github.com/pytorch/pytorch/pull/110714 )
- How to have a meaningful qualified name for each generated bytecode, so that we can log decompiled source code without accidentally overwriting previous ones. (Currently I use hash of decompiled source code.)

Here, I managed to debug the generated bytecode in vscode:

<img width="1373" alt="image" src="https://github.com/pytorch/pytorch/assets/23236638/15f763f3-a317-49e0-91a2-8c08a903400b">

cc @jansel @ezyang

2023-10-19 03:50 UTC, bdhirsh commented
@voznesenskym @yanboliang who would be a good person to take a look at this PR?

2023-10-19 04:07 UTC, youkaichao commented
Oh, I added @jansel @ezyang , because they are related to the previous PR https://github.com/pytorch/pytorch/pull/110714 .

2023-10-19 17:28 UTC, jansel requested changes
This is really neat!  But I don't think makes sense to enable it by default because:
1) it adds extra dependencies to PyTorch
2) it will add runtime overhead slowing down tracing
3) any bugs in depyf will break `torch.compile`, which will reduce stability

I'd suggest making a post of dev-discuss about this, and putting the hook in the depyf repo that people can register if they want to use it.

2023-10-19 22:59 UTC, youkaichao commented
@jansel I'm thinking of making some additional functionality in logging like this, but it doesn't fit into any existing category though. 

Yes we can always do it in `depyf` as an external hook. However I find that I need some help from PyTorch to assist the debugging ability. For example, I want PyTorch to have valid function name for these code object (I'm referring to those `<resume in xxx>` function names). Can I push forward these changes when debugging is pure external with `depyf`?

2023-10-20 03:16 UTC, ezyang commented
>  For example, I want PyTorch to have valid function name for these code object (I'm referring to those <resume in xxx> function names)

This is fine, we'll take patches for it. You can file issues for any other improvements you need if you want to check if we'll accept them.

2023-10-20 11:35 UTC, youkaichao commented
Move the discussion to https://github.com/pytorch/pytorch/issues/111633 now.

2023-10-20 11:35 UTC, closed without merging