Supports ROCm6.0 reorganization and cleanup
pytorch/pytorch pull request #111486
Opened 2023-10-18 17:29 UTC by BLOrange-AMD

2023-10-20 13:33 UTC, jeffdaily requested changes

2023-10-20 13:33 UTC, jeffdaily commented on torch/utils/hipify/cuda_to_hip_mappings.py
> +        ("cublas_v2.h", ("rocblas/rocblas.h", CONV_INCLUDE_CUDA_MAIN_H, API_BLAS)),
Undo this change.  This should be hipblas.

2023-10-30 01:08 UTC, pruthvistony commented on cmake/public/LoadHIP.cmake
>  # HCC_PATH
This section can also be removed till line 145.

2023-10-31 14:25 UTC, BLOrange-AMD commented
@pytorchbot rebase

2023-10-31 16:36 UTC, jeffdaily commented on cmake/public/LoadHIP.cmake
> +if(ROCM_VERSION_DEV VERSION_GREATER_EQUAL "6.0.0")
ROCM_VERSION_DEV isn't defined until later in this file.

2023-11-10 21:47 UTC, BLOrange-AMD commented
@pytorchbot rebase

2023-11-14 19:16 UTC, BLOrange-AMD commented
@pytorchbot rebase

2023-11-14 21:54 UTC, pruthvistony commented
@pytorchbot rebase -f

2023-11-14 21:55 UTC, pruthvistony commented
@pytorchbot rebase

2023-11-15 22:47 UTC, jithunnair-amd approved these changes

2023-11-16 06:45 UTC, pruthvistony approved these changes

2023-11-16 06:46 UTC, pruthvistony commented
@malfet ,
Can you please help review this PR.

2023-11-16 16:07 UTC, malfet approved these changes

2023-11-16 18:35 UTC, pruthvistony commented
@pytorchbot merge -f "Unrelated CI failure"

2023-11-16 18:37 UTC, closed without merging