[inductor] Defer memory operation lowering to wrapper
pytorch/pytorch pull request #111402
Opened 2023-10-16 23:11 UTC by int3

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Right now, memory ops are being lowered to strings partly in
scheduler.codegen() and partly in wrapper.codegen(). But that makes
static memory planning (which is done entirely in `wrapper.codegen()`)
difficult to implement as information is "lost" by that point.

2023-10-16 23:17 UTC, int3 commented
`codegen_inplace_reuse()` is still being called from `scheduler.codegen()`, but I guess reuse decisions don't affect memory planning decisions as it is currently implementated. I'm wondering if it would make sense to move that to wrapper.codegen() too though

2023-10-17 21:24 UTC, jansel requested changes
Tests are failing

2023-10-17 21:24 UTC, jansel commented on torch/_inductor/codegen/wrapper.py
> +        if name in self.freed:
Don't we need to do this on the last free, not the first one?

2023-10-17 23:14 UTC, int3 commented
This wasn't meant for review yet, that's why I marked it as a draft... should I be taking off the reviewers as well? This isn't the first time I've had a draft reviewed :/

2023-10-18 00:33 UTC, int3 commented on torch/_inductor/codegen/wrapper.py
> +        if name in self.freed:
sorry, not sure I understand this comment. What is the first/last free you're referring to here?

2023-10-19 21:32 UTC, int3 commented on torch/_inductor/codegen/wrapper.py
> +        self.freed.add(name)
I've removed these entirely. I'm not sure why this change was introduced in your initial diff... but things seem to work regardless

2023-10-21 04:21 UTC, jansel approved these changes

2023-10-24 00:21 UTC, int3 commented
@pytorchbot merge

2023-10-24 03:48 UTC, closed without merging