[Dynamo]remove an unnecessary check
pytorch/pytorch pull request #111883
Opened 2023-10-24 01:31 UTC by youkaichao

Per the discussion at https://github.com/pytorch/pytorch/issues/111633#issuecomment-1774076606 , this debug check is unnecessary, and will cause segmentation fault.

For resume functions, the `nlocals` is unnecessarily large.

Let's use the typical toy example:

```python
import torch

@torch.compile(backend="eager")
def toy_example(a, b):
    x = a / (torch.abs(a) + 1)
    if b.sum() < 0:
        b = b * -1
    return x * b

for _ in range(100):
    toy_example(torch.randn(10), torch.randn(10))
```

For example, resume functions have 3 local variables `('b', 'x', 'a')`, but the bytecode only uses two: `('b', 'x')`.

2023-10-24 01:32 UTC, youkaichao commented
For those who are tiaging PR, please route it to @jansel .

2023-10-24 01:33 UTC, youkaichao commented
@pytorchbot label "topic: not user facing"

2023-10-24 03:18 UTC, jansel approved these changes

2023-10-24 03:23 UTC, jansel requested changes
Actually, looking over the rest of the file -- I think this check is needed, because of the loops below:
https://github.com/pytorch/pytorch/blob/e3bd088c277dd6d882275c92d57348c9b7f893d1/torch/csrc/dynamo/eval_frame.c#L809-L817

If the check fails then it will write off the end of fastlocals_new.

2023-10-24 03:25 UTC, youkaichao commented
> If the check fails then it will write off the end of fastlocals_new.

I have this question, too. However, when I disable the debug check, the rest code still runs well. I don't know why.

2023-10-24 03:35 UTC, jansel commented
fastlocals is usually at the end of the frame object, so you will be writing to unallocated memory or possibly corrupting some other object allocated after yours... which will lead to impossible to debug crashes when some unrelated code tries to use those objects.

2023-10-24 03:41 UTC, youkaichao commented
Maybe the problem comes from the creation of resume functions? For resume functions, the `nlocals` is unnecessarily large. It seems we should prune unused variables from resume functions, so that bytecode of resume functions sound like normal bytecode.

By normal bytecode, I mean CPython probably won't generate functions with a local variable that is not used by any bytecode.

2023-12-04 23:06 UTC, youkaichao commented
Should be resolved by https://github.com/pytorch/pytorch/pull/115062 .

2023-12-04 23:06 UTC, closed without merging