Backport `trace frames with np.ndarray` (#110512)
pytorch/pytorch pull request #112011
Opened 2023-10-25 08:41 UTC by ev-br

Backport https://github.com/pytorch/pytorch/pull/110512 to 2.1.1.

2023-10-25 10:45 UTC, lezcano commented
It looks you'll also need to add the PR that fixes the `as_array(list[str])` issue

2023-10-26 17:10 UTC, malfet commented on torch/_dynamo/variables/builder.py
> +        elif isinstance(value, np.generic):
This will crash if numpy is not installed, wouldn't it?

2023-10-26 17:12 UTC, malfet requested changes
Looks like this will crash if numpy is not installed, will submit a fix soon

2023-11-02 16:52 UTC, huydhn commented
@pytorchbot rebase -b release/2.1

2023-11-02 16:54 UTC, lezcano commented
Note that this PR depends on https://github.com/pytorch/pytorch/pull/112027

2023-11-21 17:32 UTC, closed without merging

2023-11-21 17:32 UTC, ev-br commented
Missed the 2.1.1 window, so closing.