Doc: Add and Fix docstrings for torch.util.data files
pytorch/pytorch pull request #112817
Opened 2023-11-03 00:58 UTC by guptaaryan16

Fixes #112635 

Fix docstrings for `torch.utils.data` files.

```
Before:
> pydocstyle torch/utils/data/graph.py --count
Before: 5
After: 1

> pydocstyle torch/utils/data/graph_settings.py --count
Before: 8
After: 3

> pydocstyle torch/utils/data/dataloader.py --count
Before: 12
After: 6

> pydocstyle torch/utils/data/dataset.py --count
Before: 28
After: 23

> pydocstyle torch/utils/data/sampler.py --count
Before: 24
After: 19

> pydocstyle torch/utils/data/_utils/signal_handling.py --count
Before: 1
After: 0

> pydocstyle torch/utils/data/_utils/__init__.py --count
Before: 2
After: 0

> pydocstyle torch/utils/data/_utils/collate.py --count
Before: 20
After: 6

> pydocstyle torch/utils/data/_utils/fetch.py --count
Before: 3
After: 0

> pydocstyle torch/utils/data/_utils/pin_memory.py --count
Before: 4
After: 1 

> pydocstyle torch/utils/data/datapipes/_decorator.py --count
Before: 19
After: 16

> pydocstyle torch/utils/data/datapipes/_hook_iterator.py --count
Before: 13
After: 0

> pydocstyle torch/utils/data/datapipes/_typing.py --count
Before: 17
After: 4

> pydocstyle torch/utils/data/datapipes/gen_pyi.py --count
Before: 19
After: 4
```

cc @svekars @carljparker

2023-11-03 01:00 UTC, guptaaryan16 commented
@pytorchbot label "docathon-h2-2023"

2023-11-03 04:00 UTC, kit1980 requested changes

2023-11-03 04:16 UTC, guptaaryan16 commented on torch/utils/data/_utils/collate.py
> +    Define function that converts each NumPy array element into a :class:`torch.Tensor`.
Hey @kit1980 thanks for the review, fixed the changes. Can you please review it again?

2023-11-03 07:08 UTC, kit1980 commented
Please fix "Line too long" linter issues.

2023-11-03 15:38 UTC, guptaaryan16 commented
Hey @svekars @kit1980  can you approve the rest of workflows so that I can see the lint is fixed. Thanks.

2023-11-06 18:50 UTC, kit1980 approved these changes

2023-11-06 19:27 UTC, kit1980 commented
@guptaaryan16 need to fix https://github.com/pytorch/pytorch/actions/runs/6762782751/job/18414431782?pr=112817

2023-11-06 19:52 UTC, guptaaryan16 commented
Hey @kit1980 I think now the error warning will be fixed, please approve all workflows
cc @svekars @carljparker

2023-11-06 21:52 UTC, guptaaryan16 commented
Hey @kit1980 I updated the base so that the tests can pass. Please allow the workflows again.
cc @svekars @carljparker

2023-11-07 18:00 UTC, closed without merging