[dynamo] Graph break on `setattr(Tensor, "data", Tensor)`
pytorch/pytorch pull request #113043
Opened 2023-11-06 18:06 UTC by jon-chuang

Fixes https://github.com/pytorch/pytorch/issues/113030

Alias information needs to be applied in eager before we can continue to trace the graph.

Perhaps this is too strict - couldn't we fx trace the mutation/aliasing instead? :thinking:

2023-11-06 18:55 UTC, ezyang commented on torch/_dynamo/variables/builtin.py
> +        print("SETATTR", obj, tx.output.side_effects.is_attribute_mutation(obj))
print

2023-11-06 18:56 UTC, ezyang approved these changes
Thanks, appreciated. @voznesenskym, heads up!

2023-11-06 19:05 UTC, voznesenskym commented
I can also just add support for it.

2023-11-06 19:17 UTC, voznesenskym requested changes
I think setting .data = None will fall through here?

2023-11-06 19:29 UTC, jon-chuang commented
Good point, let's just forbid setattr data generally. 

> I can also just add support for it.

@albanD also mentioned in slack that it's p hard to support .data and we're trying to migrate used off it.

2023-11-06 19:36 UTC, jon-chuang commented
> Good point, let's just forbid setattr data generally.

Actually, Dynamo will handle this case. `TypeError: Variable data has to be a tensor, but got NoneType`

2023-11-06 19:45 UTC, jon-chuang commented
> Actually, Dynamo will handle this case. TypeError: Variable data has to be a tensor, but got NoneType

I added this behaviour as a test case

2023-11-06 19:48 UTC, voznesenskym commented
Actually, let me just add a PR to enable this, I am almost done.

2023-11-06 19:48 UTC, voznesenskym commented
> > Good point, let's just forbid setattr data generally.
> 
> Actually, Dynamo will handle this case. `TypeError: Variable data has to be a tensor, but got NoneType`

Yeah, you're right :)

2023-11-06 20:57 UTC, voznesenskym commented
https://github.com/pytorch/pytorch/pull/113069

2023-11-06 20:57 UTC, voznesenskym approved these changes
LGTM

2023-11-06 21:26 UTC, jon-chuang commented
@voznesenskym I'm gonna merge this first then you can adapt the tests for https://github.com/pytorch/pytorch/pull/113069/? Maybe could add a fullgraph=True and change frame_count = 1

2023-11-07 01:13 UTC, jon-chuang commented
@pytorchbot merge

2023-11-07 03:56 UTC, closed without merging

2023-11-07 21:20 UTC, voznesenskym commented
I'll be reverting this in my grad enablement PR

2023-11-07 21:20 UTC, voznesenskym commented
> @voznesenskym I'm gonna merge this first then you can adapt the tests for #113069?
> 
> In that PR you could add a fullgraph=True and change frame_count = 1

That's already the case

2023-11-08 18:39 UTC, PaliC commented
@pytorchbot revert -m "causing dynamo regressions internally (see error message below)" -c ghfirst

```
self = <caffe2.test.dynamo.test_input_attr_tracking.TestInputAttrTracking testMethod=test_set_data_on_input_tensor>

    def test_set_data_on_input_tensor(self):
        def fn(x, y):
            x.data = y.data
            if x.size() == y.size():
                return x * y
            else:
                return y * y
    
        x = torch.randn([5, 5])
        y = torch.randn([2, 2])
    
        eager_result = fn(x, y)
    
        counter = CompileCounter()
    
        fn = torch._dynamo.optimize(counter, nopython=True)(fn)
    
>       compile_result = fn(x, y)

...

msg = '.data assignment to a tracked tensors can introduce aliasing, hence we need to graph break to apply the aliasing (or track new aliased tensors) to continue to trace the graph'

    def unimplemented(msg: str) -> NoReturn:
        assert msg != os.environ.get("BREAK", False)
>       raise Unsupported(msg)
E       torch._dynamo.exc.Unsupported: .data assignment to a tracked tensors can introduce aliasing, hence we need to graph break to apply the aliasing (or track new aliased tensors) to continue to trace the graph
E       
E       from user code:
E          File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/6081734815403318/caffe2/test/dynamo/__test_dynamo__/test_dynamo#link-tree/caffe2/test/dynamo/test_input_attr_tracking.py", line 282, in fn
E           x.data = y.data
E       
E       Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
E       
E       
E       You can suppress this exception and fall back to eager by setting:
E           import torch._dynamo
E           torch._dynamo.config.suppress_errors = True

...

[internal_folder]/caffe2/test/dynamo/__test_dynamo__/test_dynamo#link-tree/torch/_dynamo/exc.py:192: Unsupported
"
                            [resultArtifactsHandle:TestInfraTestResult:private] => 
                            [metadata:TestInfraTestResult:private] => Array
                                (
                                )

                            [metadataLoaded:TestInfraTestResult:private] => 1
                            [metadataHandle:TestInfraTestResult:private] => 
                            [prov:TestInfraTestResult:private] => TestInfraTestDataProvider Object
                                (
                                    [queryTimeout:TestInfraTestDataProvider:private] => 30
                                    [instanceKey:TestInfraTestDataProvider:private] => "1699462559.63675816"
                                    [shardedRun:TestInfraTestDataProvider:private] => TestInfraShardedRun Object
                                        (
                                            [queryTimeout:TestInfraShardedRun:private] => 30
                                            [readOnMaster:TestInfraShardedRun:private] => 1
                                            [caller:TestInfraShardedRun:private] => "SandcastleFBCodeContbuildBase"
                                        )

                                    [shardedTest:TestInfraTestDataProvider:private] => TestInfraShardedTest Object
                                        (
                                            [queryTimeout:TestInfraShardedTest:private] => 30
                                            [readOnMaster:TestInfraShardedTest:private] => 1
                                            [caller:TestInfraShardedTest:private] => "SandcastleFBCodeContbuildBase"
                                        )

                                    [readOnMaster:TestInfraTestDataProvider:private] => 1
                                    [caller:TestInfraTestDataProvider:private] => "SandcastleFBCodeContbuildBase"
                                )

                            [extraData:TestInfraTestResult:private] => Array
                                (
                                )

                            [verdictExplanation:TestInfraTestResult:private] => 
                            [completePromise:TestInfraTestResult:private] => 
                            [landFrictionOverride:TestInfraTestResult:private] => 
                            [suppressionInformation:TestInfraTestResult:private] => 
                        )

                    [arePreviousTriesLoaded:TestInfraTestResult:private] => 1
                    [summary:TestInfraTestResult:private] => ""
                    [details:TestInfraTestResult:private] => "============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-7.2.2, pluggy-0.13.1
rootdir: [redacted[
plugins: hypothesis-6.70.1
collected 12 items

. unimplemented [('.data assignment to a tracked tensors can introduce aliasing, hence we need to graph break to apply the aliasing (or track new aliased tensors) to continue to trace the graph', 1)]
F
```

Hopefully, this should be enough of an error message to help you debug

2023-11-08 18:55 UTC, jon-chuang commented
I think the internal test needs to be xfailed until https://github.com/pytorch/pytorch/pull/113080 is merged. @voznesenskym 

Setting data is completely broken atm

2023-11-08 20:55 UTC, voznesenskym commented
> I think the internal test needs to be xfailed until #113080 is merged. @voznesenskym
> 
> Setting data is completely broken atm

mmmm not clear, that test was passing. It should graph break now, this is not an internal test. Looking.