patch 113084
pytorch/pytorch pull request #113092
Opened 2023-11-06 23:26 UTC by ahoblitz

Fixes #113084

2023-11-06 23:37 UTC, ahoblitz commented
@pytorchbot label "topic: not user facing"

2023-11-06 23:43 UTC, kit1980 commented on torch/_refs/__init__.py
> +        >>> b = torch.tensor([-1.0, 2.0, -3.0])
`b` should be probably different from the result to properly show what the function does.

2023-11-06 23:48 UTC, kit1980 requested changes
@ahoblitz Did you use help of ChatGPT or something like that? There are a lot of details I'm not sure are correct.

Also all the examples are wrong, should not use numpy arrays.

2023-11-06 23:52 UTC, kit1980 commented
@ahoblitz please verify all details you provide are correct and also that all the examples are correct.

2023-11-07 00:01 UTC, ahoblitz commented
@kit1980 The values were computed by hand but they should be correct. Updated to use `torch.tensor` since we are in torch rather than numpy

2023-11-07 00:06 UTC, ahoblitz reviewed
Updated to use torch.tensor

2023-11-07 00:18 UTC, kit1980 commented
@ahoblitz I still see incorrect details and verifying some other takes time.
Please verify/remove the details.

2023-11-07 15:56 UTC, ahoblitz commented
@kit1980 
I have
- [X] Simplified some comments
- [X] Fixed some details with the linter
- [X] Validated inputs/outputs match execution (in addition to mental math), no changes seem to be required here

I am not sure if this resolves the details you would like verified or removed. One other potential subjective issue I saw may be around type aliasing and using `TensorLike` for example inputs over `tensor`, but please let me know if you see this change or any other specific changes as appropriate

2023-11-07 17:39 UTC, kit1980 commented
@ahoblitz For `copysign`, can left argument be a scalar?

2023-11-07 20:07 UTC, kit1980 commented
Sorry, we've realized that the docstrings already exist, just defined in a different file: https://github.com/pytorch/pytorch/blob/main/torch/_torch_docs.py#L3071

2023-11-08 10:02 UTC, ahoblitz commented
I will close this since due to the docstrings existing elsewhere

2023-11-08 10:02 UTC, closed without merging