ADD child module at ARBITRAY POSITION in current module
pytorch/pytorch pull request #11328
Opened 2018-09-06 07:54 UTC by tomguluson92

I revised member function add_module(...) of Module. I reinforce it by add child module to arbitary position of the current module.
Samples like this:

I revised member function `add_module(...)` of Module. I reinforce it by add child module to arbitary position of the current module.
Samples like this:
``` python
class Perceptron(nn.Module):

    def __init__(self, in_features, out_features, hidden_features):
        super(Perceptron, self).__init__()

        self.layer1 = nn.Linear(in_features, hidden_features)
        self.layer2 = nn.Linear(hidden_features, 4)
        self.layer3 = nn.Linear(4, out_features)

    def forward(self, x):

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)

        return x
```
When we have a lot of module like this kind. if we need to add a child module to all of this kind of module.
We can easily specify the child module position via setting the parameter `index` to a number(default is -1, the same
as now PyTorcher's already define.)

It can easily use the following code to do add a specified child module between **model.layer2** and **model.layer3**:
``` python
class Perceptron_ADD(nn.Module):
    def __init__(self):
        super(Perceptron_ADD, self).__init__()
        model = Perceptron(10, 5, 4)

        model.add_module("arbitarylayer", nn.Linear(4, 4), index=2)

        self.model = model

    def forward(self, x):
        return self.model(x)

2018-09-06 14:52 UTC, apaszke requested changes
I don't understand the actual use case you're proposing here. Squeezing an extra submodule in between other submodules won't make the `Perceptron` actually use it, so in your code snippet the `add_module` call is pretty much a no-op.

2018-09-06 15:16 UTC, tomguluson92 commented
Thank you for answer! @apaszke , This idea strike to me that is when i read someone's code[SE net](https://github.com/moskomule/senet.pytorch/blob/master/se_inception.py) use  `add_module`  function add a submodule followed by their module's last submodule.

Could you please explain it to me why that ops work and this **squeezing an extra submodule in between other submodules** won't work? Thanks a lot!

2018-09-07 02:13 UTC, tomguluson92 commented
@apaszke , I have already test it and found that the weights of `arbitarylayer`  did not change(as it's first initialized) during training. Could you please give some advices for solve this problem? Thank you!

2018-09-07 15:37 UTC, apaszke commented
Because the order of submodule of your module doesn't really matter for most things. The only important thing is what code you have in `forward`. If this code doesn't use the new submodules, they are not needed for anything.

Thanks for the PR and feel free to post more questions on [our forums](discuss.pytorch.org).

2018-09-07 15:37 UTC, closed without merging