Add vectorized batch_norm_cpu_collect_stats_contiguous_impl
pytorch/pytorch pull request #113350
Opened 2023-11-09 13:49 UTC by pratiklp00

This patch Adds the  vectorized  implementation of batch_norm_cpu_collect_stats_contiguous_impl.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

2023-11-15 15:54 UTC, janeyx99 commented
@jgong5 assigning you as reviewer, please reassign if you are not the best reviewer for this PR.

2023-11-16 00:51 UTC, jgong5 approved these changes

2023-11-16 00:51 UTC, jgong5 commented on aten/src/ATen/native/cpu/batch_norm_kernel.cpp
> +    // compute mean per input
nit: indent

2023-11-16 06:02 UTC, mingfeima reviewed
As long as CI passes, I am fine with it. Otherwise you have to deal with the numerical stability issue for large feature map plane.

2023-11-16 06:02 UTC, mingfeima commented on aten/src/ATen/native/cpu/batch_norm_kernel.cpp
> +      sum_val += vec_reduce_all([](Vec& x, Vec& y) { return x + y; }, sum_val_vec);
`vec_reduce_all(const Op&, const Vectorized<scalar_t>&)` here is already the `fast` version: https://github.com/pytorch/pytorch/tree/main/aten/src/ATen/cpu#L82C17-L82C31, it goes into a vectorized horizontal reduce of SIMD

`vec_reduce_all(const Op&, const Vectorized<scalar_t>&), int64_t` is a slow version when the size < vector length.

2023-11-16 06:02 UTC, mingfeima commented on aten/src/ATen/native/cpu/batch_norm_kernel.cpp
> +      Vec sum_val_vec = Vec(scalar_t(0));
you can use a simple `vec::map_reduce` so save some effort: https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/cpu/vec/functional_base.h#L137

2023-11-16 16:57 UTC, malfet commented
@pytorchbot rebase

2023-11-16 17:00 UTC, malfet requested changes
If goal of this PR is to increase performance I think it needs some before and after performance numbers, otherwise it does not make much sense.

Also, considering that you are chaning accumulation type from float to double would be interested to see some analysis on accuracy of old vs new op implementation

2024-01-17 12:25 UTC, pratiklp00 commented on aten/src/ATen/native/cpu/batch_norm_kernel.cpp
> -
Hi @mingfeima as you said after the changes 3 test cases are failing from file test_deferred_batch_norm.py. if you have any suggestions please let me know.

2024-02-16 12:39 UTC, closed without merging