[Inductor CUTLASS backend] Cutlass EVT Addmm support for Inductor Cutlass backend
pytorch/pytorch pull request #113367
Opened 2023-11-09 16:31 UTC by kadeng

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Adding support for pre-fused ADDMM using Cutlass EVT functors, which
would allow to fuse EVT epilogues with Cutlass GEMM ops, which
implement the aten.addmm operation.

Note:

Currently this is not of much practical use, since at some
point during torch.compile, most non-standalone aten.addmm ops
seem to be decomposed into aten.mm + further ops before
lowering.

Test Plan:
 - CI
 - Added unit test within test/inductor/test_max_autotune.py

2023-11-20 10:48 UTC, aakhundov requested changes
Thanks, @kadeng, LGTM overall! Left a few minor comments. Some CI errors look legit. Also there are linter errors.

2023-11-20 10:48 UTC, aakhundov commented on torch/_inductor/codegen/cuda/cutlass_epilogue_gen.py
> +        """returns the name of the ADDMM EVT type which has been declared like this:
Super-nit: let's start from upper-case R.

2023-11-20 10:48 UTC, aakhundov commented on torch/_inductor/codegen/cuda/cutlass_epilogue_gen.py
> +
Nit: move this up to other `_op_*`s?

2023-11-20 10:48 UTC, aakhundov commented on torch/_inductor/codegen/cuda/cutlass_epilogue_gen.py
> +            (epilogue_nodes is None) or len(epilogue_nodes) == 0
Can `epilogue_nodes` be `None`? Need to update the type hint above if so.

2023-11-20 10:48 UTC, aakhundov commented on torch/_inductor/codegen/cuda/cutlass_epilogue_gen.py
> +        result = pre_fused_evt_args
I believe, it would be cleaner to move this line (using `pre_fused_evt_args`) after the following `if` statement. A bit confusing otherwise.

2023-11-20 10:48 UTC, aakhundov commented on torch/_inductor/codegen/cuda/cutlass_epilogue_gen.py
> +          {},               // leaf op+args : C
Are `C` and `acc` not specified in the argument structure?

2023-11-20 10:48 UTC, aakhundov commented on torch/_inductor/codegen/cuda/gemm_template.py
> +        Bias: Optional[Buffer] = None,
Nit: does this need to be upper-case?

2023-11-20 10:48 UTC, aakhundov commented on torch/_inductor/codegen/cuda/gemm_template.py
> +        Bias: Optional[Buffer] = None,
ditto

2023-11-20 10:48 UTC, aakhundov commented on torch/_inductor/codegen/cuda/gemm_template.py
> +            f"Cutlass GEMM Layout change: Input and/or output layouts have changed between autotuning and call to render on {self}. Applying workaround. This can lead to suboptimal performance." # no
Nit: could still break this into multiple strings and avoid `# noqa`.

2023-12-15 10:12 UTC, kadeng commented
Moved to a (draft) feature branch, see https://github.com/pytorch/pytorch/pull/115919

2023-12-15 10:12 UTC, closed without merging