Resolve docstring errors relating to issue#112633
pytorch/pytorch pull request #113311
Opened 2023-11-08 22:49 UTC by zabboud

Fixes #112633 

Fixed errors relating to pydocstyle in the following files. The remaining errors are not covered in this issue. `torch/utils/dlpack.py` was not modified as the errors are relating to the function signature in the first line in the docstring which must be maintained as is for proper Sphinx interpretation. 

```python
def from_dlpack(ext_tensor: Any) -> 'torch.Tensor':
    """from_dlpack(ext_tensor) -> Tensor
         .....
    """
```

pydocstyle torch/utils/_contextlib.py --count
before: 4
after: 0

pydocstyle torch/backends/mps/__init__.py --count
before: 8 
after: 1

**remaining errors**
```
torch/backends/mps/__init__.py:1 at module level:
        D104: Missing docstring in public package
```

pydocstyle torch/backends/xeon/run_cpu.py --count
before: 13
after: 1
```
torch/backends/xeon/run_cpu.py:864 in public function `main`:
        D103: Missing docstring in public function
```

pydocstyle torch/backends/cpu/__init__.py --count
before: 2
after: 1
```
torch/backends/cpu/__init__.py:1 at module level:
        D104: Missing docstring in public package
```

pydocstyle torch/utils/cpp_backtrace.py --count
before: 4 
after: 1
```
torch/utils/cpp_backtrace.py:1 at module level:
        D100: Missing docstring in public module
```

pydocstyle torch/utils/bundled_inputs.py --count       
before: 8
after: 1
```
torch/utils/bundled_inputs.py:1 at module level:
        D100: Missing docstring in public module
```

pydocstyle torch/utils/file_baton.py --count    
before: 8
after: 1
```
torch/utils/file_baton.py:1 at module level:
        D100: Missing docstring in public module
```

pydocstyle torch/utils/mobile_optimizer.py --count     
before: 6
after: 1

```
torch/utils/mobile_optimizer.py:8 in public class `LintCode`:
        D101: Missing docstring in public class
```

pydocstyle torch/backends/opt_einsum/__init__.py --count
before: 7
after: 5

**remaining errors**
```
torch/backends/opt_einsum/__init__.py:1 at module level:
        D104: Missing docstring in public package
torch/backends/opt_einsum/__init__.py:67 in public function `set_flags`:
        D103: Missing docstring in public function
torch/backends/opt_einsum/__init__.py:77 in public function `flags`:
        D103: Missing docstring in public function
torch/backends/opt_einsum/__init__.py:93 in public class `OptEinsumModule`:
        D101: Missing docstring in public class
torch/backends/opt_einsum/__init__.py:94 in public method `__init__`:
        D107: Missing docstring in __init__
```

pydocstyle torch/utils/_device.py --count              
before:  9
after: 6 

**remaining errors**
```
torch/utils/_device.py:58 in public class `DeviceContext`:
        D101: Missing docstring in public class
torch/utils/_device.py:59 in public method `__init__`:
        D107: Missing docstring in __init__
torch/utils/_device.py:62 in public method `__enter__`:
        D105: Missing docstring in magic method
torch/utils/_device.py:68 in public method `__exit__`:
        D105: Missing docstring in magic method
torch/utils/_device.py:73 in public method `__torch_function__`:
        D105: Missing docstring in magic method
torch/utils/_device.py:80 in public function `device_decorator`:
        D103: Missing docstring in public function

```

pydocstyle torch/utils/_freeze.py --count
before: 15
after: 7

**remaining errors**
```
torch/utils/_freeze.py:77 in public function `indent_msg`:
        D103: Missing docstring in public function
torch/utils/_freeze.py:89 in public class `FrozenModule`:
        D101: Missing docstring in public class
torch/utils/_freeze.py:100 in public class `Freezer`:
        D101: Missing docstring in public class
torch/utils/_freeze.py:101 in public method `__init__`:
        D107: Missing docstring in __init__
torch/utils/_freeze.py:106 in public method `msg`:
        D102: Missing docstring in public method
torch/utils/_freeze.py:185 in public method `get_module_qualname`:
        D102: Missing docstring in public method
torch/utils/_freeze.py:206 in public method `compile_string`:
        D102: Missing docstring in public method

```

utils/hooks.py: 14-11
utils/mkldnn.py: 28 - 26

utils/throughput_benchmark.py: 25-8
utils/weak.py: 32-30
utils/_traceback.py: 19-14

2023-11-08 22:56 UTC, zabboud commented
@pytorchbot label "docathon-h2-2023"

2023-11-09 13:18 UTC, zabboud commented
@pytorchbot label "topic: not user facing"

2023-11-09 13:19 UTC, zabboud commented
@mikaylagawarecki @jbschlosser @svekars

2023-11-09 14:47 UTC, ezyang approved these changes

2023-11-09 14:47 UTC, ezyang commented
@pytorchbot merge

2023-11-09 16:31 UTC, zabboud commented
@ezyang Can i do anything to fix this linter failure?

2023-11-09 22:00 UTC, kit1980 commented
@pytorchbot rebase

2023-11-09 22:02 UTC, kit1980 commented
> Can i do anything to fix this linter failure?

@zabboud looks like this PR is based on an old commit and this causes problem.
I ran rebase, it should update and re-trigger.

2023-11-09 23:07 UTC, svekars commented
Now, the lint is failing with the [errors](https://github.com/pytorch/pytorch/actions/runs/6817941019/job/18543299459?pr=113311) from your changes - a lot of them can be autofixed with `lintrunner -a` or `quicklint` ran locally.

2023-11-10 14:59 UTC, zabboud commented
@svekars @kit1980 checks have passed - just awaiting approval.

2023-11-10 17:42 UTC, svekars commented
It looks like all these changes in the `third-party/` might be causing the build issues. Can you unstage them?

2023-11-10 21:01 UTC, svekars commented
There are still many [linter errors](https://github.com/pytorch/pytorch/actions/runs/6828104218/job/18571923866?pr=113311#step:11:1348) related to your changes. Can you please fix them?

2023-11-10 23:14 UTC, zabboud commented
@svekars  seems like the linter didnt catch all the issues the first time around. Just pushed a few of them.

2023-11-12 20:24 UTC, zabboud commented
@svekars The automated linter -- i.e. running `lintrunner -a` is not fixing the problems. It seems to keep coming up with more and exting with a statement saying "successfully applied all patches" but no files were modified. see output below -- also a lot of the errors seem to be related to f-strings that have nothing to do with the modifications covered in this PR. 

```
lintrunner -a
  CLANGFORMAT success!
  FLAKE8 failure
  MYPY success!
  MYPYNOFOLLOW success!
  MYPYSTRICT success!
  CLANGTIDY success!
  TYPEIGNORE success!
  NOQA success!
  CIRCLECI success!
  NEWLINE success!
  CONSTEXPR success!
  SPACES success!
  TABS success!
  NATIVEFUNCTIONS success!
  INCLUDE success!
  PYBIND11_INCLUDE success!
  ERROR_PRONE_ISINSTANCE success!
  PYBIND11_SPECIALIZATION success!
  PYPIDEP success!
  EXEC success!
  CUBINCLUDE success!
  RAWCUDA success!
  RAWCUDADEVICE success!
  ROOT_LOGGING success!
  DEPLOY_DETECTION success!
  CMAKE success!
  SHELLCHECK success!
  ACTIONLINT success!
  TESTOWNERS success!
  CALL_ONCE success!
  ONCE_FLAG success!
  WORKFLOWSYNC success!
  UFMT success!
  COPYRIGHT success!
  BAZEL_LINTER success!
  LINTRUNNER_VERSION success!
  RUFF success!
  MERGE_CONFLICTLESS_CSV success!

>>> Lint for torch/backends/xeon/run_cpu.py:

  Warning (FLAKE8) E702
    multiple statements on one line (semicolon)
    See https://www.flake8rules.com/rules/E702.html

        480  |                if args.ninstances > len(cores):
        481  |                    raise RuntimeError(
        482  |                        f"there are {len(cores)} total cores but you specify {args.ninstances} ninstances; \
    >>> 483  |please make sure ninstances <= total_cores)"
        484  |                    )
        485  |                else:
        486  |                    args.ncores_per_instance = len(cores) // args.ninstances

  Advice (FLAKE8) E231
    missing whitespace after ','
    See https://www.flake8rules.com/rules/E231.html

        625  |                            range_elem = {"start": core, "end": core}
        626  |                            core_ranges.append(range_elem)
        627  |                for r in core_ranges:
    >>> 628  |                    cur_process_cores = f"{cur_process_cores}{r['start']}-{r['end']},"
        629  |                cur_process_cores = cur_process_cores[:-1]
        630  |                if not args.disable_numactl:
        631  |                    numa_params = f"-C {cur_process_cores} "



>>> Lint for torch/utils/_freeze.py:

  Warning (FLAKE8) E702
    multiple statements on one line (semicolon)
    See https://www.flake8rules.com/rules/E702.html

        137  |        with open(os.path.join(install_root, "main.c"), "w") as outfp:
        138  |            outfp.write(MAIN_INCLUDES)
        139  |            for m in self.frozen_modules:
    >>> 140  |                outfp.write(f"extern unsigned char {m.c_name}[];\n")
        141  |
        142  |            outfp.write(MAIN_PREFIX_TEMPLATE.format(symbol_name))
        143  |            for m in self.frozen_modules:

  Advice (FLAKE8) E231
    missing whitespace after ';'
    See https://www.flake8rules.com/rules/E231.html

        137  |        with open(os.path.join(install_root, "main.c"), "w") as outfp:
        138  |            outfp.write(MAIN_INCLUDES)
        139  |            for m in self.frozen_modules:
    >>> 140  |                outfp.write(f"extern unsigned char {m.c_name}[];\n")
        141  |
        142  |            outfp.write(MAIN_PREFIX_TEMPLATE.format(symbol_name))
        143  |            for m in self.frozen_modules:

  Advice (FLAKE8) E231
    missing whitespace after ','
    See https://www.flake8rules.com/rules/E231.html

        141  |
        142  |            outfp.write(MAIN_PREFIX_TEMPLATE.format(symbol_name))
        143  |            for m in self.frozen_modules:
    >>> 144  |                outfp.write(f'\t{{"{m.module_name}", {m.c_name}, {m.size}}},\n')
        145  |            outfp.write(MAIN_SUFFIX)
        146  |            if oss:
        147  |                outfp.write(FAKE_PREFIX)



>>> Lint for torch/utils/bundled_inputs.py:

  Advice (FLAKE8) E231
    missing whitespace after ','
    See https://www.flake8rules.com/rules/E231.html

        304  |                        skip_size_check=skip_size_check,
        305  |                    )
        306  |                    deflated_args.append(deflated)
    >>> 307  |                    parts.append(f"    {inflater},")
        308  |                    if helper_definition:
        309  |                        model.define(textwrap.dedent(helper_definition))
        310  |                deflated_inputs.append(tuple(deflated_args))

  Advice (FLAKE8) E231
    missing whitespace after ','
    See https://www.flake8rules.com/rules/E231.html

        336  |        # Add to the high level helper methods
        337  |        inputs_info = repr(info[function]) if info and function in info else '[]'
        338  |        get_bundled_inputs_functions_and_info_template += f"""
    >>> 339  |            temp_dict : Dict[str,List[str]] = {{}}
        340  |            info: List[str] = {inputs_info}
        341  |
        342  |            temp_dict['info'] = info

  Advice (FLAKE8) E272
    multiple spaces before keyword
    See https://www.flake8rules.com/rules/E272.html

        356  |                """))
        357  |
        358  |    # Define some high level helper methods that act on all bundled inputs
    >>> 359  |    model.define(textwrap.dedent(f"""
        360  |        def get_bundled_inputs_functions_and_info(self):
        361  |            all_inputs : Dict[str, Dict[str,List[str]]] = {{}}
        362  |            {get_bundled_inputs_functions_and_info_template}

  Advice (FLAKE8) E231
    missing whitespace after ':'
    See https://www.flake8rules.com/rules/E231.html

        358  |    # Define some high level helper methods that act on all bundled inputs
        359  |    model.define(textwrap.dedent(f"""
        360  |        def get_bundled_inputs_functions_and_info(self):
    >>> 361  |            all_inputs : Dict[str, Dict[str,List[str]]] = {{}}
        362  |            {get_bundled_inputs_functions_and_info_template}
        363  |            return all_inputs
        364  |        """))

  Advice (FLAKE8) E241
    multiple spaces after ':'
    See https://www.flake8rules.com/rules/E241.html

        358  |    # Define some high level helper methods that act on all bundled inputs
        359  |    model.define(textwrap.dedent(f"""
        360  |        def get_bundled_inputs_functions_and_info(self):
    >>> 361  |            all_inputs : Dict[str, Dict[str,List[str]]] = {{}}
        362  |            {get_bundled_inputs_functions_and_info_template}
        363  |            return all_inputs
        364  |        """))

  Advice (FLAKE8) E231
    missing whitespace after ','
    See https://www.flake8rules.com/rules/E231.html

        358  |    # Define some high level helper methods that act on all bundled inputs
        359  |    model.define(textwrap.dedent(f"""
        360  |        def get_bundled_inputs_functions_and_info(self):
    >>> 361  |            all_inputs : Dict[str, Dict[str,List[str]]] = {{}}
        362  |            {get_bundled_inputs_functions_and_info_template}
        363  |            return all_inputs
        364  |        """))

  Advice (FLAKE8) E272
    multiple spaces before keyword
    See https://www.flake8rules.com/rules/E272.html

        359  |    model.define(textwrap.dedent(f"""
        360  |        def get_bundled_inputs_functions_and_info(self):
        361  |            all_inputs : Dict[str, Dict[str,List[str]]] = {{}}
    >>> 362  |            {get_bundled_inputs_functions_and_info_template}
        363  |            return all_inputs
        364  |        """))
        365  |

  Advice (FLAKE8) E221
    multiple spaces before operator
    See https://www.flake8rules.com/ru [...]

2023-11-14 18:46 UTC, zabboud commented
@svekars @kit1980 Can you please assist in these failures? How can they be addressed?

2023-11-14 18:57 UTC, kit1980 commented
@zabboud I don't see these lint failures in the CI.

2023-11-14 18:58 UTC, kit1980 commented
@pytorchbot rebase

2023-11-14 19:18 UTC, zabboud commented
@kit1980 thanks for reading, looks all good, can we go ahead with the merge?

2023-11-14 19:50 UTC, kit1980 commented
@pytorchbot merge

2023-11-14 23:19 UTC, kit1980 requested changes

2023-11-14 23:19 UTC, kit1980 commented on torch/utils/_traceback.py
> +    return f"{extra_line}{shorten_filename(frame.filename, base=base)}: {frame.lineno} in {frame.name}"
Don't change this.

2023-11-15 13:50 UTC, zabboud commented
@kit1980 can you please initiate the merge?

2023-11-15 17:36 UTC, kit1980 commented
@zabboud FYI anyone can initiate the merge after a project member approval

2023-11-15 17:37 UTC, kit1980 commented
@pytorchbot merge

2023-11-15 17:39 UTC, zabboud commented
> @zabboud FYI anyone can initiate the merge after a project member approval

I am not authorized to do so unfortunately. it says next to merge PR 

"You’re not [authorized](https://docs.github.com/articles/about-protected-branches/) to merge this pull request."

2023-11-15 17:40 UTC, closed without merging

2023-11-15 17:51 UTC, kit1980 commented
> I am not authorized to do so unfortunately. it says next to merge PR
> 
> "You’re not [authorized](https://docs.github.com/articles/about-protected-branches/) to merge this pull request."

@zabboud we don't merge directly in PyTorch.
We merge by posting "@pytorchbot merge", and you could post the same way I did.

2023-11-15 17:53 UTC, zabboud commented
@kit1980 duly noted - thank you.