Docs: Fixes for FDSP Files
pytorch/pytorch pull request #113532
Opened 2023-11-12 13:38 UTC by guptaaryan16

Fixes #113190 

Fixed the docstrings for FDSP files 

cc @svekars @carljparker

2023-11-12 13:40 UTC, guptaaryan16 commented
@pytorchbot label "docathon-h2-2023"

2023-11-13 21:02 UTC, kit1980 requested changes

2023-11-13 21:02 UTC, kit1980 commented on torch/distributed/fsdp/_runtime_utils.py
> +    Return a tuple with the following conditions.
The first line of a docstring should be mostly self-contained.

2023-11-15 00:16 UTC, kit1980 requested changes
In many places "hook" word is removed, this looks incorrect to me.

2023-11-15 00:16 UTC, kit1980 commented on torch/distributed/fsdp/_runtime_utils.py
> +    """Prefetche the next handles if needed (without synchronization).
Prefetche - typo?

2023-11-15 00:16 UTC, kit1980 commented on torch/distributed/fsdp/_state_dict_utils.py
> +    """Call a helper function to exit ``_unshard_fsdp_state_params`` context."""
This function doesn't "call a helper function", it is a helper function.

2023-11-15 00:16 UTC, kit1980 commented on torch/distributed/fsdp/_state_dict_utils.py
> +    """Run before model.state_dict() is called.
"Hook" looks like an important keyword here, why remove?

2023-11-15 00:16 UTC, kit1980 commented on torch/distributed/fsdp/_state_dict_utils.py
> +    """Run after model.state_dict() is called and before returning result to user.
"Hook" looks like an important keyword here, why remove?

2023-11-15 00:16 UTC, kit1980 commented on torch/distributed/fsdp/_state_dict_utils.py
> +    """Run before model.state_dict() is called.
"Hook" looks like an important keyword here, why remove?

2023-11-15 00:16 UTC, kit1980 commented on torch/distributed/fsdp/_state_dict_utils.py
> +    r"""Create a ``ShardedTensor`` from the local flat_param.
"Hook" looks like an important keyword here, why remove?

2023-11-15 06:52 UTC, guptaaryan16 commented
@kit1980 Since the hook method names are marked by `_hook`, I thought that it's redundant to mention it in the first line of docstrings, but lets add it back if it seems wrong.

2023-11-15 07:02 UTC, kit1980 commented
> @kit1980 Since the hook method names are marked by `_hook`, I thought that it's redundant to mention it in the first line of docstrings, but lets add it back if it seems wrong.

I'm not sure I agree with this, and changing this wasn't part of the linked issue.

2023-11-15 07:03 UTC, guptaaryan16 commented
@kit1980 Sure let me revert it back

2024-02-13 16:35 UTC, closed without merging