Add Bfloat16 scalar support to gloo backend
pytorch/pytorch pull request #113557
Opened 2023-11-13 13:07 UTC by anko-intel

There was missing support for bfloat scalars. When I use gloo backend
`torch.distributed.init_process_group(backend='gloo')`
and run 
`torch.nn.parallel.DistributedDataParallel(model)`
and _model_ has Bfloat16 features I receive following error:
`RuntimeError: Invalid scalar type`

This change fix this issue. 
c10::BFloat16 defines conversions from/to float, so calculations are made on float for bfloat.

2023-11-13 20:11 UTC, XilunWu requested changes
Thanks for adding BFloat16 support to gloo PG. I'm not sure if this is the best way to support BFloat16 because we do have float16 support in gloo (`Half` i.e. `gloo:;float16`).

2023-11-13 20:11 UTC, XilunWu commented on torch/csrc/distributed/c10d/ProcessGroupGloo.cpp
> +      func<c10::BFloat16>(args);                 \
use `__VA_ARGS__` instead of `args`?

2023-11-14 00:58 UTC, jgong5 commented
> Thanks for adding BFloat16 support to gloo PG. I'm not sure if this is the best way to support BFloat16 because we do have float16 support in gloo (`Half` i.e. `gloo:;float16`).

@XilunWu are you suggesting to add `gloo::bfloat16` to gloo instead of using `c10::bfloat16`?

2023-11-14 00:58 UTC, jgong5 requested changes
Please add UT.

2023-11-14 01:23 UTC, XilunWu commented
@jgong5 That seems to be a reasonable call, right? But to quickly unblock, we can merge this PR once the windows part is fixed, and add bfloat16 to gloo later.

2023-11-14 05:10 UTC, jgong5 commented
> @jgong5 That seems to be a reasonable call, right? But to quickly unblock, we can merge this PR once the windows part is fixed, and add bfloat16 to gloo later.

Yes, that sounds reasonable.

2023-11-14 21:34 UTC, XilunWu commented
Just a reminder that the windows part has issue. Need to fix.

2023-11-15 11:29 UTC, anko-intel commented on torch/csrc/distributed/c10d/ProcessGroupGloo.cpp
> +      func<c10::BFloat16>(args);                 \
Thanks, done

2023-11-15 11:33 UTC, anko-intel commented
> Please add UT.

I added 2 test cases for bfloat. I think this will be enough and will not increase too much the time needed for testing.

2023-11-16 00:34 UTC, jgong5 approved these changes
LGTM as long as CI passes.

2023-11-16 16:49 UTC, anko-intel commented
@XilunWu can we go forward with this change?

2023-11-17 18:09 UTC, XilunWu approved these changes
LGTM! Really appreciate the effort of adding BFloat16 scalar support!

2023-11-17 18:36 UTC, XilunWu commented
@pytorchbot merge

2023-11-17 21:17 UTC, closed without merging