More replacing assert with CUDA_KERNEL_ASSERT in kernels
pytorch/pytorch pull request #113563
Opened 2023-11-13 15:25 UTC by hongxiayang

Fixes #103973

**Background:** 
After https://github.com/pytorch/pytorch/pull/113098, user verified that torch.sum() worked for environment where PCIe atomics was exposed as a problem for such operation.
 
**Goal:**
This is the to expend the changes to other kernels where assert is called. The goal is the same so that we can disable kernel assertion easily for those users when the call sites consistently use CUDA_KERNEL_ASSERT.

2023-11-13 16:56 UTC, jeffdaily requested changes
Please revert all changes to aten/src/ATen/native/cuda/reduction_template.cuh.  That code block is a raw string that is used for JIT.  The assert() statement was already being #define'd away.  Renaming assert -> CUDA_KERNEL_ASSERT in this file may have unintended consequences for JIT.

2023-11-17 03:50 UTC, jeffdaily approved these changes

2023-11-17 04:36 UTC, ezyang commented
@pytorchbot merge

2023-11-17 04:56 UTC, ezyang approved these changes

2023-11-17 04:56 UTC, ezyang commented
@pytorchbot merge

2023-11-17 07:28 UTC, closed without merging