[Quant][Inductor] Enable quantization linear pattern fusion for geli inside inductor
pytorch/pytorch pull request #114101
Opened 2023-11-20 06:53 UTC by Le-Zheng

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-11-20 08:42 UTC, leslie-fang-intel commented
Hi @Le-Zheng, please add a UT for it. Refer to: https://github.com/pytorch/pytorch/blob/7963aaac4157c961c1d54033d1f2515d0c987360/test/inductor/test_mkldnn_pattern_matcher.py#L1007

2023-11-20 08:51 UTC, leslie-fang-intel requested changes
- Please add a UT for it.

2023-11-20 08:51 UTC, leslie-fang-intel commented on torch/_inductor/fx_passes/quantization.py
> +            UnaryAttr("gelu", [], ""): generate_pattern_with_output_quant(
We need to cover both `None` and `tanh` as `algorithm_attr`, right? Should we need to register it twice with different `algorithm_attr`?

2023-11-30 09:34 UTC, Le-Zheng commented
This pull requested is migrated to https://github.com/pytorch/pytorch/pull/114854

2023-11-30 09:34 UTC, closed without merging