Pin CI numpy version to 1.22.2
pytorch/pytorch pull request #114146
Opened 2023-11-20 18:31 UTC by huydhn

This is to prevent pip from pulling in 1.22.4 and fails Docker image builds https://github.com/pytorch/pytorch/actions/runs/6923861547/job/18842791777

2023-11-20 20:31 UTC, malfet requested changes
Is numpy currently installed via conda? If that is the case, can we stop installing it there?
Also, can't we unify version of numpy used in docker and say in lintrunner?

2023-11-20 20:33 UTC, malfet commented on .ci/docker/requirements-ci.txt
> +numpy==1.21.2 ; python_version == "3.10"
I don't like current rule as it excludes python 3.11 and 3.12, so I wonder if something like that would be more inclusive
```suggestion
numpy<=1.21.2 
```

2023-11-20 20:34 UTC, huydhn commented
> Is numpy currently installed via conda? If that is the case, can we stop installing it there? Also, can't we unify version of numpy used in docker and say in lintrunner?

Yes, the version is currently pinned via conda, but we actually install numba here, and that's the one that tries to pull numpy `1.22.4`.  Let me see if I can find a way to avoid that, probably installing numba via conda too

2023-11-20 21:47 UTC, huydhn commented
@pytorchbot drci

2023-11-20 21:49 UTC, malfet approved these changes

2023-11-21 01:27 UTC, huydhn commented
@pytorchbot merge -f 'Merge to unblock Docker image rebuild.  All Docker build jobs have passed'

2023-11-21 01:29 UTC, kit1980 approved these changes

2023-11-21 01:29 UTC, closed without merging