Fix hang in VonMises rejection sampling for small values of concentration
pytorch/pytorch pull request #114498
Opened 2023-11-24 04:45 UTC by julian-urban

Fixes #88443

Forces the internal `dtype` of `torch.distributions.von_mises.VonMises` to be `torch.double` and mirrors the numpy implementation of the second order Taylor expansion for `concentration < 1e-5`. Samples and log probs are returned with `dtype` of argument `loc`.

In principle one could also use masking in the rejection sampler to return uniformly distributed numbers for `concentration < 1e-8`, as in numpy. This may be slightly more efficient, but isn't required to solve the hanging issue.

2023-11-24 04:48 UTC, julian-urban commented
@pytorchbot label "topic: not user facing"

2023-11-29 00:48 UTC, fritzo requested changes
Thanks for fixing this!  Could we move your logic to three `@lazy_property`s, to keep the other code paths entirely single precision?

2023-11-29 00:48 UTC, fritzo commented on torch/distributions/von_mises.py
> +        self.loc, self.concentration = broadcast_all(loc.to(torch.double), concentration.to(torch.double))
It seems a safer to use double versions only in `.sample()`, maybe storing a
```
self._concentration = self.concentration.to(torch.double)
```
for use in `self._proposal_r`.  This way `.log_prob()` can remain single precision, and `.mean` won't magically cast to double.

If we're going to use double stuff in `_proposal_r`, we should change it to a lazy property:
```python
@lazy_property
def _loc(self):
    return self.loc.to(torch.double)

@lazy_property
def _concentration(self):
    return self.concentration.to(torch.double)

@lazy_property
def _proposal_r(self):
    if self._concentration < 1e-5:
        # second order Taylor expansion around kappa = 0
        self._proposal_r = 1 / self._concentration + self._concentration
    else:
        tau = 1 + (1 + 4 * self._concentration**2).sqrt()
        rho = (tau - (2 * tau).sqrt()) / (2 * self._concentration)
        self._proposal_r = (1 + rho**2) / (2 * rho)
```
Then we can use `self._loc` and `self._concentration` in `.sample()`, but continue using `.loc` and `concentration` elsewhere.

2023-11-29 00:50 UTC, fritzo commented on torch/distributions/von_mises.py
> +        self.loc, self.concentration = broadcast_all(loc.to(torch.double), concentration.to(torch.double))
Actually, concentration can be a tensor, so we'll need a `torch.where(self._concentration < 1e-5, -, -)`

2023-11-30 17:29 UTC, julian-urban commented
@fritzo Thanks for picking it up, please check my latest commit. I followed your suggestion of implementing the `_loc` and `_concentration` attributes with double prec as lazy properties and similarly `_proposal_r`, also replacing the `if/else` with `torch.where` to make sure it works with tensor-valued `loc` and `concentration`. The hard-coded double prec stuff should now be confined to calls of `sample()` only.

I'm not sure if I was supposed to resolve the above conversation already, this is my first PR and I'm not familiar with the proper etiquette. Apologies.

2023-11-30 21:03 UTC, fritzo approved these changes
Looks great @julian-urban!  It might be worth adding a line comment in `.sample()` explaining why sampling is performed using double precision, but feel free to leave as is.

2023-11-30 23:17 UTC, julian-urban commented
@fritzo whoopsie. The test passes now and I added a clarifying comment to `sample()`.

2023-12-02 05:32 UTC, fritzo approved these changes

2023-12-02 05:33 UTC, fritzo commented
@ezyang could you please merge this?

2023-12-04 20:41 UTC, fritzo commented
@pytorchmergebot merge

2023-12-04 23:07 UTC, closed without merging