[BE]: ruff enable SLOT checks and add fixes
pytorch/pytorch pull request #114470
Opened 2023-11-23 17:46 UTC by Skylion007

Enable ruff `SLOT` rules and fixes all offending classes (leaves tests alone since performance does not matter there).

2023-11-29 05:10 UTC, jansel requested changes
It is a matter of taste, but IMO adding lots of:
```
 __slots__ = ()
```
to the codebase is an annoying, make things uglier, and doesn't bring any benefits.

Why do we want this rule?

2023-11-29 05:19 UTC, kit1980 commented
> Why do we want this rule?

@jansel apparently "Defining __slots__ for subclasses of tuple prevents the creation of a dictionary for each instance, reducing memory consumption" - https://docs.astral.sh/ruff/rules/no-slots-in-tuple-subclass/

But I agree we need the motivation listed and some discussion of the tradeoffs for such things.

2023-11-29 05:24 UTC, Skylion007 commented
Yeah, it prevents a performance regression from subclassing builtin classes. Otherwise, these classes will be less efficient from their parent class for no reason.

2023-12-02 18:46 UTC, Skylion007 commented
@pytorchbot rebase

2023-12-02 21:04 UTC, Skylion007 commented
> @Skylion007 can you add some sort of a benchmark to the PR description demonstrating the benefit? If it indeed helps (even my a little bit) then we should take the change

Honestly, I am not sure it will help now, but it will certainly not hurt. If someone introduces a namedTuple or a subclass that becomes really common in the future, that could hurt performance. I can absolutely matter in practice too, a rather extreme example can be found in this dated blogpost. https://tech.oyster.com/save-ram-with-python-slots/ . The maintenance burden is rather minimal and there is no reason a subclass should be less efficient than it's parent for no reason.

2023-12-07 22:46 UTC, jansel reviewed
Not seeing much data to make me see this as worth it.  I've benchmarked slots in the past (for other projects) and couldn't see any performance difference from then.

So my prior comment still stands.

2023-12-31 09:18 UTC, ezyang commented
To add a counter opinion, I don't think the burden of proof from @Skylion007 is that high here. In particular, he is not proposing we add slots to ALL classes in our codebase (the PR would have been substantially longer in that case), but only for subclasses of objects that *already*, by default, do not allocate a `__dict__` by default. @albanD's comment here, in particular, is not relevant, because none of the objects that Aaron has modified here actually have anything to do with C bindings. This seems pretty benign, and very easy to undo if it actually is a bad idea.

One thing to note: the presence of slots or not is a public API change, as it prevents users assigning arbitrary properties on these objects:

```
>>> "sdf".foo = True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute 'foo'
```

So there is potentially a breaking change (though I doubt it, tbh).

2025-01-24 16:04 UTC, Skylion007 commented
> New datapoint for this, though it is of limited use for this PR given the object we change. The new https://pytorch.org/docs/main/generated/torch.utils.swap_tensors.html utility that we are starting to use within nn.Module and other features is preventing swaps between Tensors with different slots. So at least on the Tensor subclass side, we don't want slots for sure.

Which of these are Tensor subclasses though? This is only adds these annotations for classes which only subclass builtin classes with slots.

2025-02-02 18:00 UTC, closed without merging