[AOTInductor] Support freezing model in aoti
pytorch/pytorch pull request #114451
Opened 2023-11-23 07:45 UTC by imzhuhl

Fixes #114450

This commit supports aotinductor processing opaque tensor, so we can enable freezing in aoti. Need community support to see if this is the right way to go.

2023-11-30 14:51 UTC, desertfire requested changes
First of all, thanks for contributing to AOTInductor! I left some comments about the aoti_torch interfaces, and I will leave MKLDNN-related part to @jgong5 and @chunyuan-w

2023-11-30 14:51 UTC, desertfire commented on torch/csrc/inductor/aoti_torch/c/shim.h
> +    int8_t layout,
All the APIs in this file is supposed to be ABI-stable. If you need to add a parameter like this, you will have to create a v2 version of this function.

2023-11-30 14:51 UTC, desertfire commented on test/inductor/test_aot_inductor.py
> +    if not TEST_WITH_ROCM:
You need to make sure all the cuda tests are decorated with `@requires_cuda` if you want to remove this.

2023-11-30 14:51 UTC, desertfire commented on torch/csrc/inductor/aoti_torch/opaque_tensor.h
> +at::Tensor mkldnn_tensor_from_data_ptr(
If `mkldnn_tensor_from_data_ptr` is only used by `aoti_torch_create_tensor_from_blob`, it's better to keep it as a utility function in shim_common.cpp. Files in `atoi_torch` are a set of limited interfaces used by the generated `model.so`, so adding a generic torch function here can cause confusion and people may use it by mistake.

2023-12-01 02:14 UTC, jgong5 requested changes
It doesn't seem the right way of serializing/deserializing the MKLDNN tensors. Inline comments added for details.

2023-12-01 02:14 UTC, jgong5 commented on torch/csrc/inductor/aoti_torch/opaque_tensor.cpp
> +}
Oh, I don't think this is a right way of serializing/deserializing mkldnn tensors. The MKLDNN tensor contains both the memory buffer (the `data_ptr` points to) and the metadata that describes the layout of the memory buffer. When the model is frozen, the weight tensors are with blocked layout which is described with the metadata. So, only serializing/deserializing the memory buffer cannot restore all the information held in the MKLDNN tensor. oneDNN folks are adding the serialization support for MKLDNN tensors per our request. I would suggest we wait for the support ready before adding the support for frozen models.

2023-12-05 02:48 UTC, imzhuhl commented
> First of all, thanks for contributing to AOTInductor! I left some comments about the aoti_torch interfaces, and I will leave MKLDNN-related part to @jgong5 and @chunyuan-w

Thanks for your review. I will make changes. 
@jgong5 is right, mkldnn tensor serialization and deserialization is not that simple, it requires a deeper understanding of the oneDNN prepack mechanism, I need some time to figure this out. If it is difficult to complete in this pr, waiting for support from oneDNN team may be the best option.

2024-01-24 08:01 UTC, jgong5 commented on torch/csrc/inductor/aoti_torch/opaque_tensor.cpp
> +}
We are working on a POC and will tag you when the PR is ready. cc @chunyuan-w

2024-04-02 17:43 UTC, eellison commented
Clearing review queue please re-request when needed

2024-05-02 18:34 UTC, closed without merging