[Draft] [XPU] [Kineto] [Profiler] Add XPU support in Kineto based Profiler (2/3)
pytorch/pytorch pull request #114500
Opened 2023-11-24 06:44 UTC by xunsongh

In this patch, we focus on XPU support modification in data post processor scripts such as `torch/autograd/profiler.py` and `torch/autograd/profiler_util.py`.
Also we add one more change missed in the first patch which let kineto_shim return correct device type for different gpu devices.

Fixes #ISSUE_NUMBER

2023-12-12 03:55 UTC, gujinghui commented on torch/autograd/profiler.py
> +                        )
This change is not necessary?

2023-12-12 03:56 UTC, gujinghui commented on torch/autograd/profiler.py
> +        ]
This should be a bug fix for CPU + other device case. Should we split it to a separate PR?

2023-12-12 03:57 UTC, gujinghui commented on torch/autograd/profiler.py
> +                    elif f_evt.device_type == DeviceType.PrivateUse1:
Why we need to add code for PrivateUse1?

2023-12-12 03:58 UTC, gujinghui commented on torch/autograd/profiler_util.py
> +                for k in evt.privateuse1_kernels:
ditto.

2023-12-12 03:58 UTC, gujinghui commented on torch/autograd/profiler_util.py
> +    def append_privateuse1_kernel(self, name, device, duration):
ditto.

2023-12-20 13:11 UTC, EikanWang requested changes

2023-12-20 13:11 UTC, EikanWang commented on torch/autograd/profiler_util.py
> +        if self.is_async:
Why do we need to change cuda code?

2023-12-20 13:11 UTC, EikanWang commented on torch/csrc/profiler/kineto_shim.cpp
> +      return gpu_device;
Since the activity type is MTIA CCP Event, may I know why we still need to check the gpu device is not GPU?

2023-12-20 13:13 UTC, EikanWang commented
Please refine your PR description.

2024-02-19 02:59 UTC, xunsongh commented
Will rebase on latest master and create a new clean pull request with final written commit messages. Close this draft now.

2024-02-19 02:59 UTC, closed without merging