[export] Fix state dict device serialization
pytorch/pytorch pull request #114695
Opened 2023-11-28 19:53 UTC by angelayi

Summary:
Fixes https://github.com/pytorch/pytorch/issues/114000
Will check with SherlockNoMad on why we need to convert to cpu after his PTO

Test Plan: CI

Differential Revision: D51629068

2023-11-28 20:00 UTC, ydwu4 approved these changes
Left a few non-blocking comments. Overall looks good to me.

2023-11-28 20:00 UTC, ydwu4 commented on torch/_export/serde/serialize.py
> +        convert_to_cpu: bool = False,
Do we need to store the original devices for each tensor somewhere so that we could retrieve the original devices?

2023-11-28 20:00 UTC, ydwu4 commented on torch/_export/serde/serialize.py
>      def serialize(self, exported_program: ep.ExportedProgram) -> SerializedArtifact:
compared with a self.convert_to_cpu attibute, can we make it a default kwarg to serialize? This makes the Serializer less stateful.

2023-11-29 04:41 UTC, zhxchen17 requested changes
the way we add flags everywhere looks sus...

2023-11-29 04:41 UTC, zhxchen17 commented on torch/_export/serde/serialize.py
> +        convert_to_cpu=False,
I think we should have a unified behavior on serialize API.

2023-11-29 05:05 UTC, closed without merging