Adds Checkpointer Wrapper for DCP [3/N]
pytorch/pytorch pull request #114603
Opened 2023-11-27 17:20 UTC by LucasLLC

Adds a useful high level wrapper for calling `dist.save/load` with the correct storage readers and writers. 

Instead of doing:

```
DCP.save(
    state_dict={...},
    storage_writer=StorageWriter(...)
)

DCP.load(
    state_dict={...},
    storage_reader=StorageReader(...)
)
```

We can now do:

```
checkpointer = Checkpointer(...)

checkpointer.save(state_dict={...})
checkpointer.load(state_dict={...})
```

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @gujinghui @PenghuiCheng @jianyuh @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @voznesenskym @penguinwu @EikanWang @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @mrshenli @zhaojuanmao @rohan-varma @kiukchung @lucasllc @XilunWu @tianyu-l @d4l3k

2023-11-30 23:56 UTC, wconstab reviewed
this seems like a nice convenience. it is a lot of lines of code for something that mostly just tries to save passing a reader/writer into calls to save/load though.

i wonder if its necessary to allow overwriting the reader/writer in checkpointer.save/load after you opted into using a checkpointer to save you the trouble of passing in a reader/writer.

I like the concrete class for filesystem. so that part makes it worth it to me.  (and assume there would be other implementations coming too)

2023-12-01 17:09 UTC, LucasLLC commented
> this seems like a nice convenience. it is a lot of lines of code for something that mostly just tries to save passing a reader/writer into calls to save/load though.
> 
> i wonder if its necessary to allow overwriting the reader/writer in checkpointer.save/load after you opted into using a checkpointer to save you the trouble of passing in a reader/writer.
> 
> I like the concrete class for filesystem. so that part makes it worth it to me. (and assume there would be other implementations coming too)

This is a really good point - I may have been overly cautious since I was concerned there may be some specific customization users were relying on and didn't want to remove the flexibility.

I think you're totally right though, I'll leave as is since to give other a chance to review, but removing the extra fluff is probably a good idea.

2023-12-06 22:07 UTC, fegin requested changes
We should NOT remove the documentation for load_state_dict and save_state_dict. They are not removed yet.

2023-12-06 22:07 UTC, fegin commented on torch/distributed/checkpoint/checkpointer.py
> +        self,
Can we make all the arguments keyword based? Or at least for those which are not required.

2023-12-06 22:07 UTC, fegin commented on docs/source/distributed.checkpoint.rst
We should NOT remove these function documentation. They are not removed yet.

2023-12-07 17:47 UTC, wz337 commented on torch/distributed/checkpoint/filesystem.py
> +class FileSystemCheckpointer(Checkpointer):
Oh ye. I somehow missed it. LGTM! Thanks!

2023-12-07 17:47 UTC, wz337 approved these changes

2023-12-07 18:05 UTC, fegin approved these changes
LGTM, please ensure all tests are green before merging.

2023-12-07 18:05 UTC, fegin commented on torch/distributed/checkpoint/checkpointer.py
> +    ):
nit: these can be in one line to avoid a possible linter error.

2023-12-07 18:05 UTC, fegin commented on torch/distributed/checkpoint/checkpointer.py
> +    ):
nit: these can be in one line to avoid a possible linter error.

2023-12-08 01:03 UTC, closed without merging