Add a decomposition for take()
pytorch/pytorch pull request #114813
Opened 2023-11-30 00:12 UTC by asmeurer

Presumably this can close https://github.com/pytorch/pytorch/pull/109784

Also related to https://github.com/pytorch/pytorch/issues/93757 (though `take` is not listed there). 

There's no bounds checking here (out of bounds indices cause a segfault or undefined behavior). Should that be added somehow?

2023-11-30 10:03 UTC, lezcano reviewed
Mind posting the triton code it generates? Do so running it with `TORCH_LOGS=output_code`

2023-11-30 10:03 UTC, lezcano commented on torch/_decomp/decompositions.py
> +    flattened = self.reshape(-1)
we also have `self.flatten()` which is a bit more explicit, but they both do the same, so whatever.

2023-11-30 15:08 UTC, asmeurer commented
> Mind posting the triton code it generates? Do so running it with TORCH_LOGS=output_code

```
>>> @torch.compile
... def test(x, idx):
...     return torch.take(x, idx)
>>> test(x, idx)
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] Output code:
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] from ctypes import c_void_p, c_long
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] import torch
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] import math
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] import random
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] import os
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] import tempfile
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] from math import inf, nan
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] from torch._inductor.hooks import run_intermediate_hooks
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] from torch._inductor.utils import maybe_profile
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] from torch._inductor.codegen.memory_planning import _align as align
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] from torch import device, empty, empty_strided
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] from torch._inductor.codecache import AsyncCompile
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] from torch._inductor.select_algorithm import extern_kernels
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] aten = torch.ops.aten
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] inductor_ops = torch.ops.inductor
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] assert_size_stride = torch._C._dynamo.guards.assert_size_stride
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] alloc_from_pool = torch.ops.inductor._alloc_from_pool
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] reinterpret_tensor = torch.ops.inductor._reinterpret_tensor
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] async_compile = AsyncCompile()
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] cpp_fused_take_0 = async_compile.cpp('''
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] #include "/var/folders/wc/dppcpmxs1tlb36nqcw853wkm0000gn/T/torchinductor_aaronmeurer/2l/c2ljzlm4sosod7u6lyrroqdba6hmfcyijrric6p4t3fhbcmw6osp.h"
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] extern "C" void kernel(const long* in_ptr0,
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]                        const long* in_ptr1,
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]                        long* out_ptr0)
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] {
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]     {
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]         #pragma GCC ivdep
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]         for(long x0=static_cast<long>(0L); x0<static_cast<long>(3L); x0+=static_cast<long>(1L))
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]         {
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]             auto tmp0 = in_ptr0[static_cast<long>(x0)];
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]             auto tmp1 = static_cast<long>(0);
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]             auto tmp2 = tmp0 < tmp1;
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]             auto tmp3 = static_cast<long>(10);
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]             auto tmp4 = decltype(tmp0)(tmp0 + tmp3);
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]             auto tmp5 = tmp2 ? tmp4 : tmp0;
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]             auto tmp6 = decltype(tmp5)(tmp5 + 10);
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]             auto tmp7 = tmp5 < 0;
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]             auto tmp8 = tmp7 ? tmp6 : tmp5;
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]             TORCH_CHECK((0 <= tmp8) & (tmp8 < 10L), "index out of bounds: 0 <= tmp8 < 10L")
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]             auto tmp9 = in_ptr1[static_cast<long>(tmp8)];
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]             out_ptr0[static_cast<long>(x0)] = tmp9;
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]         }
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]     }
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] }
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] ''')
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] async_compile.wait(globals())
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] del async_compile
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] def call(args):
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]     arg0_1, arg1_1 = args
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]     args.clear()
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]     assert_size_stride(arg0_1, (10, ), (1, ))
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]     assert_size_stride(arg1_1, (3, ), (1, ))
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]     buf0 = empty((3, ), device='cpu', dtype=torch.int64)
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]     cpp_fused_take_0(c_void_p(arg1_1.data_ptr()), c_void_p(arg0_1.data_ptr()), c_void_p(buf0.data_ptr()))
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]     del arg0_1
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]     del arg1_1
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]     return (buf0, )
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG] def benchmark_compiled_module(times=10, repeat=10):
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]     from torch._dynamo.testing import rand_strided
[2023-11-30 08:06:00,486] [1/0] torch._inductor.graph.__output_code: [DEBUG]     fro [...]

2023-11-30 15:20 UTC, lezcano commented
It seems that we are doing the wrapping twice. The issue her is that even if gather does not supports wrapping, `torch.compile`'s implementation does. We should either xfail the tests that test the decomposition with a comment or implement in a different PR wrapping for gather.

2023-11-30 22:37 UTC, asmeurer commented
Here's the result of that benchmark run https://gist.github.com/asmeurer/0dae083265e52973ceb2f7fb5385b407. Note that you have to comment out [this line](https://github.com/pytorch/pytorch/blob/38ae17d166a001ef6837553d1ddffa111624df27/torch/_inductor/lowering.py#L1674) to get the lowering bit to run.

2023-11-30 22:57 UTC, asmeurer commented
> It seems that we are doing the wrapping twice. The issue her is that even if gather does not supports wrapping, torch.compile's implementation does. We should either xfail the tests that test the decomposition with a comment or implement in a different PR wrapping for gather.

I don't see how to xfail just a single `SampleInput`. Is there an easy way to do it? Of course, I can also just comment the failing test out.

2023-11-30 23:02 UTC, asmeurer commented
I added benchmarks for both versions to the gist. The duplicate negative index handling doesn't seem to affect the timings. Presumably it just gets compiled away?

2023-11-30 23:20 UTC, lezcano commented
It doesn't get compiled away. The thing here is that doing the wrapping takes no time compared to loading data from global memory.

Now, the generated code as it stands is not correct, as it would work for things that are more negative than `-size`.

For now, xfail the whole decomp test and leave a comment

2023-12-01 07:30 UTC, lezcano commented on torch/testing/_internal/common_methods_invocations.py
> +               DecorateInfo(unittest.expectedFailure),
This is skipping all tests. You should just skip the failing tests. See how other OpInfos do it

2023-12-01 07:40 UTC, lezcano commented
The benchmarks and generated code LGTM. Let's fix the OpInfo and this should be ready to be merged

2023-12-06 21:02 UTC, asmeurer commented
> Now, the generated code as it stands is not correct, as it would work for things that are more negative than -size.

Ah, good point. Although, as I noted in the OP, this doesn't do any kind of bounds checking and is already undefined/segfaults in that case.

2023-12-06 22:22 UTC, asmeurer commented
I've updated the opinfos.

2023-12-06 22:45 UTC, peterbell10 requested changes

2023-12-06 22:48 UTC, asmeurer commented on torch/_decomp/decompositions.py
> +    return flattened.gather(dim=0, index=index)
Oh nice. I was under the impression from the `gather` suggestion that indexing wouldn't work, but it seems to work just fine.

2023-12-07 08:48 UTC, peterbell10 approved these changes

2023-12-22 15:06 UTC, lezcano approved these changes

2023-12-22 15:06 UTC, lezcano commented
@pytorchbot merge

2023-12-22 18:15 UTC, closed without merging