[quant][pt2e] XNNPACKQuantizer skip inserting observers for non-float Tensors
pytorch/pytorch pull request #114999
Opened 2023-12-02 01:02 UTC by jerryzh168

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #114999

Summary:
att

Test Plan:
python test/test_quantization.py -k test_add_mul_long

Reviewers:

Subscribers:

Tasks:

Tags:

2023-12-05 15:50 UTC, kimishpatel requested changes
If only float tensors are observable, then this change should apply to all ops not just binary, right?

2023-12-05 15:50 UTC, kimishpatel commented on torch/ao/quantization/quantizer/xnnpack_quantizer_utils.py
> +            fake_mode = n.meta["val"].fake_mode
why is this change needed?

2023-12-05 19:38 UTC, kimishpatel commented
> > If only float tensors are observable, then this change should apply to all ops not just binary, right?
> 
> technically yes, but other ops probably don't get non-float tensor inputs right now so I think we can fix on demand

I will accept for now, but I would say this should be in the observer. If you have observer that can observer non float, let them do it.

2023-12-05 19:38 UTC, kimishpatel approved these changes

2023-12-05 20:39 UTC, jerryzh168 commented
> I will accept for now, but I would say this should be in the observer. If you have observer that can observer non float, let them do it.

yeah this is specific to observer, in the meantime we are making a decision in the quantizer to insert observer or not, so quantizer need to know this as well, since we are using histogram observer in xnnpack quantizer which does not work for int/long tensors, we have to skip it. But if we have a different observer that works in this case, we could use that instead as well.

or are you saying that each observer can return some structured information so that all quantizer can just use? something like: observer.supported_input_dtypes() -> List[dtype] and each quantizer can check this before hand?

2023-12-05 21:00 UTC, kimishpatel commented
> are you saying that each observer can return some structured information so that all quantizer can just use? something like: observer.supported_input_dtypes() -> List[dtype] and each quantizer can check this before hand?

Yeah sometime like that and when quantizer still configures it with incompatible type observer can just throw error.

2023-12-05 21:27 UTC, jerryzh168 commented
> > are you saying that each observer can return some structured information so that all quantizer can just use? something like: observer.supported_input_dtypes() -> List[dtype] and each quantizer can check this before hand?
> 
> Yeah sometime like that and when quantizer still configures it with incompatible type observer can just throw error.

OK that sounds good, I think we can do that

2023-12-06 01:28 UTC, guangy10 approved these changes
The fix looks good to me. Thanks Jerry!

2023-12-07 01:27 UTC, jerryzh168 commented
@pytorchbot merge

2023-12-07 22:11 UTC, jerryzh168 commented
@pytorchbot merge

2023-12-07 22:13 UTC, closed without merging