[C++ API] Allow building the C++ API without cereal
pytorch/pytorch pull request #11498
Opened 2018-09-11 00:53 UTC by goldsborough

I am working on unifying the C++ extensions and C++ API, and one constraint for this is that we will want to be able to build the C++ API without cereal, since we won't want to ship it with the PyTorch package.

For this I introduce a `TORCH_API_WITH_CEREAL` option to CMake. If on, the C++ API will be built with cereal and thus serialization support. If off, serialization functions will throw exceptions, but the library will otherwise still compile the same. __This option is on by default, so for regular C++ API users nothing will change__. However, from C++ extensions, we'll be able to turn it off. This effectively means we won't be searching for any cereal headers from C++ API headers, which wouldn't be installed in the Python package.

@ebetica @ezyang @soumith

2018-09-11 00:55 UTC, ebetica approved these changes

2018-09-11 18:02 UTC, goldsborough commented
@pytorchbot retest this please

2018-09-12 15:38 UTC, ezyang approved these changes

2018-09-12 16:08 UTC, orionr requested changes
Nice! This should land. However, it would be great if you could move `TORCH_USE_CEREAL` to the root level CMake if possible. Also maybe just call it `USE_CEREAL` until we prefix all of those with `PT_` or `TORCH_`. I'm open to `TORCH_USE_CEREAL`, though.

2018-09-12 16:08 UTC, orionr commented on torch/CMakeLists.txt
> +  option(TORCH_WITH_CEREAL "Build the C++ API with Cereal for serialization support" OFF)
Can we make this `TORCH_USE_CEREAL` to match the other CMake flags? Also, might be best to put this in the root-level CMake (and cmake/Summary.cmake) so people are aware of it. Generally all the options are defined there and then used in caffe2/, torch/, etc.

2018-09-12 18:31 UTC, orionr approved these changes
Nice! Thank you.

2018-09-12 23:57 UTC, closed without merging