Implement aten::upsample_linear1d on mps
pytorch/pytorch pull request #115031
Opened 2023-12-03 13:14 UTC by kaieberl

Related to #77764

2023-12-06 22:18 UTC, malfet requested changes
Hmm, you implement linear as an alias to bilinear, which is probably acceptable, but then why not do a simple redispatch + warning (because bilinear != linear)?

2023-12-16 11:31 UTC, kaieberl commented on aten/src/ATen/native/mps/operations/UpSample.mm
> + c10::optional<double> scale,
Sorry I missed the part with c10::optional not supported, will change this

2023-12-18 02:07 UTC, kaieberl commented on aten/src/ATen/native/mps/operations/UpSample.mm
> + c10::optional<double> scale,
I replaced `c10::optional` now.
Here is an explanation on the bilinear vs linear topic: https://en.wikipedia.org/wiki/Bilinear_interpolation

> As the name suggests, the bilinear interpolant is not linear; but it is linear (i.e. affine) along lines parallel to either the x or the y direction, equivalently if x or y is held constant. Along any other straight line, the interpolant is quadratic. Even though the interpolation is not linear in the position (x and y), at a fixed point it is linear in the interpolation values, as can be seen in the (matrix) equations above.

In this case, the second dimension is constant and thus the interpolation is equivalent to the linear case.

2023-12-26 15:41 UTC, malfet submitted a review, later dismissed
Thank you for the explanation and the updates. Looks good to me.

2023-12-26 15:42 UTC, malfet commented
@pytorchbot merge -f "MPS and Lint are green"

2023-12-26 17:59 UTC, malfet commented
@pytorchbot revert -m "Broke lint, will fwd fix and re-land" -c landrace

2023-12-26 18:07 UTC, malfet commented
@pytorchbot rebase

2024-02-19 07:52 UTC, kaieberl commented
@malfet Is there something else I need to do?

2024-02-26 22:04 UTC, malfet commented
@pytorchbot merge -r

2024-02-26 22:06 UTC, malfet approved these changes

2024-02-26 22:06 UTC, malfet commented
@pytorchbot merge -r

2024-02-26 23:02 UTC, malfet commented
@pytorchbot merge -f "Lint and MPS tests are green"

2024-02-26 23:04 UTC, closed without merging