[DeviceMesh] add torch.distributed.device_mesh to public_allowlist
pytorch/pytorch pull request #115162
Opened 2023-12-05 10:02 UTC by wz337

Forward fix for the MacOS test_modules_can_be_imported failure due to  https://github.com/pytorch/pytorch/pull/115099?fbclid=IwAR1DjyVgOfjl2pgX40Gv6iBLb9vMV7giu1aA4ZDfdgseUHMXgfh2p3GkjRc

2023-12-05 16:07 UTC, albanD reviewed
I don't think this is ok to add this to the allow list as the comment suggests.
We really shouldn't have public API modules that just crash on import.
Would it be possible to actually fix the module to properly import on all platform (including macos where we build USE_DISTRIBUTED=0)

2023-12-05 16:53 UTC, malfet requested changes
If you want to add new public module, I'm unsure why its ok to fail to import it

2023-12-06 21:22 UTC, wconstab commented
@albanD I have a clarifiying question.  This is more about the broader need to improve torch.distributed's import situation, not specific to this PR.

> I don't think this is ok to add this to the allow list as the comment suggests.
We really shouldn't have public API modules that just crash on import.
Would it be possible to actually fix the module to properly import on all platform (including macos where we build USE_DISTRIBUTED=0)

we can make a module such as distributed.device_mesh safe to import on all platforms, by making that module guard everything it does on 'is_available()' and produce an empty namespace otherwise -- e.g. `python -c "import torch.distributed.device_mesh` passes, but nothing useful comes out of it.

otoh, if users wrote a statement like `from torch.distributed.device_mesh import Blah`, then their script will fail at import time regardless of our above proposed handling.  so the ux is still pretty bad.  But the import test doesn't catch this.

Should we be handling the second case too?  Or should users be expected to not import stuff from distributed if they don't build it?

2023-12-07 21:29 UTC, albanD commented
> well, agreed. but also we're very very far from that state. is it even realistic?

I think it is yes. from what I've seen, only the torch.distributed API don't follow this rule.

2023-12-12 19:35 UTC, closed without merging