Blob doesn't allow access to destroyCall anymore
pytorch/pytorch pull request #11548
Opened 2018-09-11 20:57 UTC by smessmer

This removes getting/setting the DestroyCall of a Blob,
paving the way to removing DestroyCall from Blob entirely and using the destructor stored in TypeMeta instead.

Use sites have been fixed in diffs stacked below this.

Differential Revision: [D9775191](https://our.internmc.facebook.com/intern/diff/D9775191/)

2018-09-12 01:05 UTC, ezyang approved these changes

2018-09-12 01:06 UTC, ezyang requested changes
You're not allowed to have a diff in a stack of diffs that breaks. Every diff has to continue compiling. So use site fixes need to be squashed into this diff.

2018-09-13 03:05 UTC, smessmer commented
@ezyang The diffs fixing use sites had some fbcode-only diffs. I removed them from the stack because the ghexport script didn't support that yet. I'll land them separately and then rebase this stack on top of new master.

2018-09-21 14:48 UTC, ezyang approved these changes

2018-09-26 08:46 UTC, closed without merging