Fix missing dependency in torch.utils.tensorboard
pytorch/pytorch pull request #115598
Opened 2023-12-11 23:55 UTC by sachahu1

Fixes #114591 

Version package was removed in this pull request: #114108 but is still used in `torch.utils.tensorboard` causing import errors. The fix removes the import and uses a simpler check.

2023-12-12 00:02 UTC, sachahu1 commented
@pytorchbot label "release notes: fix missing import from torch.utils.tensorboard"

2023-12-12 00:08 UTC, sachahu1 commented
@pytorchbot label "release notes: fx"

2023-12-12 00:51 UTC, malfet requested changes
It feels like the same can be achieved by replacing the 2nd line with
`from torch._vendor.packaging.version import Version`, can't it?

2023-12-12 08:05 UTC, sachahu1 commented
@malfet Yes, you're right, my mistake! Thanks!

2023-12-18 08:50 UTC, sachahu1 commented
@malfet @soulitzer Are we happy to merge this ?

2023-12-20 21:09 UTC, malfet approved these changes
LGTM, thank you for the fix.

2023-12-20 21:09 UTC, malfet commented
@pytorchbot merge -f "It's not tested anyway"

2023-12-20 21:11 UTC, closed without merging

2024-01-18 19:22 UTC, atalman commented
Validated  via:
```
>>> import torch
>>> from torch.utils.tensorboard import SummaryWriter
```