Update ONNX's IO Adapter to support FakeTensor with ExportedProgram (…
pytorch/pytorch pull request #115578
Opened 2023-12-11 20:05 UTC by thiagocrepaldi

…#114407)

Currently, the ONNX exporter using torch.nn.Module as input can support FakeTensor because the ONNX model stores all initializers

When using torch.export.ExportedProgram as input, the initializers are lifted as inputs. In order to execute the ONNX model, we need to pass a reference to the non-fake model to the
ONNXProgram.adapt_torch_inputs_to_onnx API, so that initializers can be fetched from the model and fed to the ONNX model as input

ps: https://github.com/pytorch/pytorch/issues/115461 will track the API revision for the cases where additional `model_with_state_dict` are required to produce complete ONNX files exported with fake support. This is also tracked by the umbrella fake tensor issue https://github.com/pytorch/pytorch/issues/105464 FYI @BowenBao
Pull Request resolved: https://github.com/pytorch/pytorch/pull/114407
Approved by: https://github.com/BowenBao

Fixes #ISSUE_NUMBER

2023-12-19 21:27 UTC, atalman approved these changes

2023-12-19 21:57 UTC, atalman requested changes
Posted notes to Release 2.2 issue tracker

2024-01-02 16:45 UTC, thiagocrepaldi commented
> Posted notes to Release 2.2 issue tracker

@atalman is this PR blocked for some reason?

2024-01-02 17:39 UTC, huydhn commented
> @atalman is this PR blocked for some reason?

I think the potential blocker here is that https://github.com/pytorch/pytorch/issues/105464 looks like a new feature work, and not a regression or a critical fix per our cherry pick criteria https://github.com/pytorch/pytorch/issues/115300#issue-2029464446 as @atalman has called out.

2024-01-02 17:49 UTC, thiagocrepaldi commented
> > @atalman is this PR blocked for some reason?
> 
> I think the potential blocker here is that #105464 looks like a new feature work, and not a regression or a critical fix per our cherry pick criteria [#115300 (comment)](https://github.com/pytorch/pytorch/issues/115300#issue-2029464446) as @atalman has called out.

Thanks for the quick reply. This is not a new feature, exactly. 

`torch.onnx.dynamo_export` was published on 2.1release with internal torch dynamo API (e.g. `torch._dynamo.expoet`) because `torch.export` was merged as public API really close to the branch cut date. The ONNX exporter team didn't have time to update the exporter in time.

As a consequence, `torch.onnx.dynamo_export` was shipped with lots of known issues (dynamic axes and functionalization are the biggest ones) that were solved by the `torch.export` API. 

This series of PR fixes `torch.onnx.dynamo_export` on 2.1 by replacing `torch._dynamo.export` by `torch.export` plus some changes to accomodate the new `ExportedProgram` concept

2024-01-04 20:35 UTC, huydhn commented
@thiagocrepaldi So, @atalman and I chat a bit about your changes here.  Could you help provide us with a validation script that we could use to validate that this one and probably https://github.com/pytorch/pytorch/pull/115583 too?  In order to safely cherry pick this, we will need a way to validate to confirm that this works as expected.

2024-01-05 20:00 UTC, malfet approved these changes

2024-01-05 21:57 UTC, atalman approved these changes

2024-01-05 21:57 UTC, huydhn approved these changes

2024-01-05 21:57 UTC, merged