[Dynamo] Make resume function name more explicit by adding lineno
pytorch/pytorch pull request #115608
Opened 2023-12-12 01:45 UTC by yanboliang

Adding lineno to resume function name for easy aggregation in Scuba table.

2023-12-12 03:31 UTC, jansel requested changes

2023-12-12 03:31 UTC, jansel commented on torch/_dynamo/resume_execution.py
> +                ] = f"resume_in_{code_options['co_qualname']}_at_{lineno}"
Doesn't qualname contains module names?  Will this be:
```
resume_in_foo.bar_at_100
```
when we want:
```
foo.resume_in_bar_at_100
```

2023-12-12 06:55 UTC, williamwen42 approved these changes

2023-12-12 18:21 UTC, yanboliang commented
@pytorchbot merge

2023-12-12 19:07 UTC, jansel approved these changes

2023-12-12 21:08 UTC, closed without merging

2023-12-13 14:44 UTC, youkaichao commented
Just find this PR because it breaks my expected tests at https://github.com/thuml/depyf . No worry, I updated my expected tests. I think it is a good fix, and it would be better if we can make the resume function name consistent with resume code name. Just a suggestion, it would better (clearer) if it is there, and no harm if not :)

Currently, the function name is `__resume_at_30_1` (the key name in globals dict), and the code name is `resume_in_toy_function_at_3`. Maybe we can use the same name for them.