[innductor] make inductor work with new triton compile interface
pytorch/pytorch pull request #115878
Opened 2023-12-14 22:28 UTC by shunting314

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-12-15 21:09 UTC, eellison reviewed
Looks like there are some other changes needed, see `TypeError("max() missing 1 required positional argument: 'propagate_nan'")`

2023-12-15 22:14 UTC, shunting314 commented on torch/_inductor/triton_heuristics.py
> +                if hasattr(bin, "run"):
hmm, this fail if bin does not have 'c_wrapper' attribute? The attribute is removed in newer triton.

```
>>> class Cls: pass
...
>>> o = Cls()
>>> o.a = 3
>>> getattr(o, "a", o.b) # this fail. Look like o.b is evaluated even if o has attribute 'a' and o.b is not used
```

2023-12-15 22:52 UTC, eellison commented on torch/_inductor/triton_heuristics.py
> +                if hasattr(bin, "run"):
oh, true.. nvm. `getattr(bin, "run", getattr(bin, "c_wrapper", None))`. Probably not worth it though.

2023-12-16 01:20 UTC, jansel requested changes

2023-12-16 01:20 UTC, jansel commented on torch/_inductor/codegen/triton.py
> +                        pass  # ignore
Let's check the Triton version either include or exclude this to keep code cleaner.

2023-12-16 01:20 UTC, jansel commented on torch/_inductor/triton_heuristics.py
> +                                stream, function, None, None, None,
Let's do the version check at compile time and emit smaller/faster launcher code.  No need to call `hasattr` a bunch of times on every single kernel launch.

2023-12-20 06:20 UTC, jansel approved these changes

2023-12-21 00:01 UTC, shunting314 commented
@pytorchbot merge -f 'test failure unrelated'

2023-12-21 00:59 UTC, kit1980 commented
This broke ROCm tests:
> torch._dynamo.exc.BackendCompilerFailed: backend='compile_fx_wrapper' raised:
> NotImplementedError: No interface for device hip

https://github.com/pytorch/pytorch/actions/runs/7282149837/job/19844618618

2023-12-21 01:57 UTC, kit1980 commented
@pytorchbot revert -m "Broke ROCm https://github.com/pytorch/pytorch/actions/runs/7282149837/job/19844618618" -c nosignal

2023-12-21 20:57 UTC, kit1980 commented
@shunting314 Fix the typo in the PR title while you're at it?

2023-12-22 00:07 UTC, shunting314 commented
@pytorchbot merge -f "test failure unrelated"

2023-12-22 00:09 UTC, closed without merging