[dynamo][collective_op] Raise unimplemented for collective ops with attribute async_op=True
pytorch/pytorch pull request #115921
Opened 2023-12-15 10:36 UTC by zejun-chen

I found whatever the attribute `async_op` in collective ops is `True` or `False` explicitly set by the users, it always leads to the graph break because the argument `async_op` is wrappered as `ConstantVariable(bool)`. So here we need to use the `value` for the judgement.

2023-12-15 10:37 UTC, zejun-chen commented
@pytorchbot label "topic: not user facing"

2023-12-18 04:26 UTC, zejun-chen commented
Hi, @wconstab 
Could you help review the PR? Thank you:)

2023-12-18 21:38 UTC, jansel requested changes
Can you add a test?

2023-12-18 21:38 UTC, jansel commented on torch/_dynamo/variables/functions.py
> +        if "async_op" in kwargs and kwargs["async_op"].value:
```suggestion
        if "async_op" in kwargs and kwargs["async_op"].as_python_constant():
```

2023-12-19 05:30 UTC, zejun-chen commented
> Can you add a test?

OK. Sure.

2023-12-20 20:02 UTC, wconstab approved these changes

2023-12-20 22:47 UTC, jansel approved these changes

2023-12-20 22:47 UTC, jansel commented
@pytorchbot merge

2023-12-21 03:28 UTC, closed without merging