Some tiny modification about torch.set/get_default_device
pytorch/pytorch pull request #116014
Opened 2023-12-18 11:33 UTC by FFFrog

1. fix bug of torch.set_default_device in multi-threading
2. add new interface named torch.get_default_device

Fixes #115333
Fixes #115917

2023-12-18 11:57 UTC, FFFrog commented
@pytorchbot label "topic: not user facing"

2023-12-18 17:44 UTC, malfet requested changes
Do you mind splitting the fix for `set_default_device` and PR that adds new public API (name seems uncontroversial to me, but I think it needs a bit more discussion)

2023-12-18 18:26 UTC, malfet approved these changes

2023-12-18 18:26 UTC, malfet commented on test/test_utils.py
> +        not (torch.cuda.is_available() and torch.cuda.device_count() > 1),
Please use `TEST_MULTIGPU` from `torch.testing._internal.common_cuda`
```suggestion
        not TEST_MULTIGPU,
```

2023-12-18 21:32 UTC, jansel approved these changes

2023-12-18 23:29 UTC, FFFrog commented
@pytorchbot merge -i

2023-12-19 01:24 UTC, FFFrog commented on test/test_utils.py
> +        not (torch.cuda.is_available() and torch.cuda.device_count() > 1),
Done :D

2023-12-19 05:05 UTC, FFFrog commented
@pytorchbot  merge -i

2023-12-19 05:08 UTC, closed without merging