[C++ API][Prototype] Abstract serialization and add Protobuf serialization
pytorch/pytorch pull request #11619
Opened 2018-09-13 02:49 UTC by goldsborough

This PR serves two purposes:

1. Design an abstraction over a serialization scheme for C++ modules, optimizers and tensors in general,
2. Add serialization to the ONNX/PyTorch proto format.

This is currently a rough prototype I coded up today, to get quick feedback.

For this I propose the following serialization interface within the C++ API:

```cpp
namespace torch { namespace serialize {
class Reader {
 public:
  virtual ~Reader() = default;
  virtual void read(const std::string& key, Tensor& tensor, bool is_buffer = false) = 0;
  virtual void finish() { }
};

class Writer {
 public:
  virtual ~Reader() = default;
  virtual void writer(const std::string& key, const Tensor& tensor, bool is_buffer = false) = 0;
  virtual void finish() { }
};
}} // namespace torch::serialize
```

There are then subclasses of these two for (1) Cereal and (2) Protobuf (called the "DefaultWriter" and "DefaultReader" to hide the implementation details). See `torch/serialize/cereal.h` and `torch/serialize/default.h`. This abstraction and subclassing for these two allows us to:

1. Provide a cereal-less serialization forward that we can ship and iterate on going forward,
2. Provide no-friction backwards compatibility with existing C++ API uses, mainly StarCraft.

The user-facing API is (conceptually):

```cpp
void torch::save(const Module& module, Writer& writer);
void torch::save(const Optimizer& optimizer, Writer& writer);
void torch::read(Module& module, Reader& reader);
void torch::read(Optimizer& optimizer, Reader& reader);
```

with implementations for both optimizers and modules that write into the `Writer` and read from the `Reader`

2018-09-13 02:56 UTC, ebetica commented
I wouldn't worry about (2). How would you change this if you didn't have to support Cereal at all?

2018-09-13 06:19 UTC, dzhulgakov reviewed
Looks neat!

For future we should have some mechanism of encoding at least typename of the c++ module in the serialized file for reference. Since for now modules are different from jit modules I guess it's ok

P.S. reusing jit module serialization is... cute :)

2018-09-13 06:19 UTC, dzhulgakov commented on torch/csrc/api/include/torch/serialize/reader.h
> +  read(key + ".size", size);
at some point it might be nice to gain an ability to read lists proper in the file format, but we're not there yet

2018-09-13 06:19 UTC, dzhulgakov commented on torch/csrc/api/include/torch/optim/adam.h
> +    serializer(
you don't have names of parameters available here to use instead of indices, do you?

2018-09-13 06:19 UTC, dzhulgakov commented on torch/csrc/api/src/serialize/default.cpp
> +  module_.register_parameter(patched_key, tensor, is_buffer);
so it represents the entire module as a gigantic flat module even in presence of submodules?

2018-09-18 16:58 UTC, goldsborough commented
After discussing with @ebetica we found that backwards compatibility with cereal is not as important and that StarCraft would be happy to switch to protobuf. For this reason I've opted to specialize my design a little more towards our Protobuf serialization format. The new primitives are `InputArchive` and `OutputArchive`, which both wrap a `ScriptModule`, which we use as a vehicle for serialization. The API for e.g. `InputArchive` is:

```
class InputArchive {
 public:
  void read(const std::string& key, Tensor& tensor, bool is_buffer = false);
  void read(const std::string& key, InputArchive& archive);

  template <typename... Ts>
  void operator()(Ts&&... ts) {
    read(std::forward<Ts>(ts)...);
  }

 private:
  std::shared_ptr<jit::script::Module> module_;
};
```

which gets populated e.g. in `nn::Module::load`:
```
void Module::load(serialize::InputArchive& archive) {
  for (auto& parameter : parameters_) {
    archive.read(parameter.key, parameter.value);
  }
  for (auto& buffer : buffers_) {
    archive.read(buffer.key, buffer.value, /*is_buffer=*/true);
  }
  for (const auto& child : children_) {
      serialize::InputArchive child_archive;
      archive.read(child.key, child_archive);
      child.value->load(child_archive);
  }
}
```

This API is not intended for inheritence. The reason why is that `InputArchive`s are recursively built (1 InputArchive = 1 ScriptModule) and have to be re-instantiated inside of `save()` or `load()`. This re-instantiation wouldn't work (nicely) if `InputArchive` were an abstract class.

This means we only support protobuf serialization out of the box. However, I've made sure that all parameters and buffers in modules and optimizers that one would want to store are properly exposed. This means if one wanted to, one could write a new serialization library on top of the `Module` base class. I believe this is more the strategy we have in Python, where we have one blessed serialization API (Pickle), but generally modules and optimizers expose enough state that anyone could dump their models into a Thrift or JSON interface.

CC @ebetica @dzhulgakov @zdevito @apaszke

2018-09-18 19:05 UTC, ebetica commented
Do you think overloading torch::save for a stream is nice? It just feels more C++-y to me, and is more flexible for users.

2018-09-20 17:50 UTC, ebetica approved these changes
Happy with the API changes, I didn't do a deep reading of this PR.

2018-09-20 21:40 UTC, ezyang commented on torch/csrc/api/include/torch/serialize.h
> +void load(Tensor& tensor, InputArchive& archive);
Can we please not have mutable references in this API. Just pass in a `const Tensor&`, it's just as good (unless you're actually bonking in a new pointer value for Tensor, in which case just return the Tensor here!)

2018-09-20 21:53 UTC, ezyang commented on .gitmodules
> -	url = https://github.com/USCiLab/cereal
I think you need to work with OSS team to land a diff that removes a submodule.

2018-09-20 21:57 UTC, ezyang commented on test/cpp/api/util.h
> +  mkstemp(filename);
whoa whoa whoa, what is this? You're leaking a file descriptor here! Don't do that!

Also, an API that gives you a tempfile filename is basically *asking* for the user of the API to leak temporary files. Please clean up after yourself using an RAII class.

2018-09-20 22:00 UTC, ezyang requested changes
Please don't leak file descriptors

2018-09-21 03:05 UTC, ezyang approved these changes

2018-09-21 03:40 UTC, closed without merging