[jit] Add support for global list() in script
pytorch/pytorch pull request #11615
Opened 2018-09-13 00:42 UTC by driazati

Allows script code to call `list()` on multiple elements of the same type
to construct a list

2018-09-13 04:44 UTC, zdevito commented
We already support `[]`, which does the same thing. The code should not be duplicated across these two functions (note the subtle semantic differences).

2018-09-13 14:39 UTC, apaszke requested changes

2018-09-13 14:39 UTC, apaszke commented on test/test_jit.py
> +            y = list(x + 1, x + 2, x + 3)
This is not what the Python semantics are. `list(1, 2, 3)` throws with `list() takes at most 1 argument (3 given)`

2018-09-13 19:18 UTC, apaszke commented on test/expect/TestScript.test_list_builtin.expect
> +  %10 : Dynamic[] = prim::ListConstruct(%5, %7, %9)
Shouldn't this be a `TupleConstruct`?

2018-09-13 19:18 UTC, apaszke commented on torch/csrc/jit/register_prim_ops.cpp
> +    Operator("aten::list(Tensor[] a) -> Tensor[]", listList<Shared<TensorList>>),
This is confusing. I thought the purpose of this constructor is to be able to cast tuples to lists. Right now it's completely useless.

2018-09-13 19:28 UTC, apaszke commented
If something, `list()` should behave similarly to a `for` loop:
```
x = list(iter)
# is equivalent to
x = []
for elem in iter:
  x.append(elem)
```

2018-09-25 16:26 UTC, yf225 commented
@driazati  Would you like to rebase to master and also address the reviews?

2018-09-26 18:43 UTC, driazati commented
Closing until mutable lists are finished

2018-09-26 18:43 UTC, closed without merging