Intel GPU oneDNN upstreaming for library compilation
pytorch/pytorch pull request #116249
Opened 2023-12-21 08:03 UTC by ZhiweiYan-96

# Motivation
As proposed  in https://github.com/pytorch/pytorch/issues/114848 and https://github.com/pytorch/pytorch/issues/114723, oneDNN library is an important component for Intel GPU software ecosystem. 

This PR is intended to enable oneDNN compilation for Intel GPU.  It is a first step for we enabling any operators like `at::baddmm`.
With this PR, a static library `libdnnl.a` for GPU would be compiled in directory `/build/xpumkldnn_proj-prefix`.  It can be further linked to `libtorch_xpu.so` in future. The compilation would  depend on `USE_XPU` bool variables.

The modification is independent to oneDNN CPU compilation, hence no modification would be introduced for CPU Cmakefiles(e.g. FindMKLDNN.cmake)

2023-12-21 15:07 UTC, EikanWang requested changes
In general, let's refine the code align with CPU build and check if we can merge the CMake to CPU.

2023-12-22 04:25 UTC, jgong5 commented on cmake/External/XPUMKLDNN.cmake
> +set(xpumkldnn_dep xpumkldnn_proj)
yes, it makes sense to add underscore after "xpu" for all the symbol names.

2023-12-22 04:25 UTC, jgong5 commented on cmake/External/XPUMKLDNN.cmake
> +    # g++ is soft linked to /usr/bin/cxx, oneDNN woule not treat it as an absolute path
Why do we have to treat GNU separately? Can you explain?

2023-12-22 05:01 UTC, ZhiweiYan-96 commented on cmake/External/XPUMKLDNN.cmake
> +    # g++ is soft linked to /usr/bin/cxx, oneDNN woule not treat it as an absolute path
Sorry for the confusion here. 
The issue here is build option DNNL_HOST_COMPILER cannot be properly handle when it is `c++` (soft link `g++` created by system). oneDNN would complain that, `cxx` is not an absolute path "The valid values for DNNL_DPCPP_HOST_COMPILER: DEFAULT and g++ or absolute path to it"

2023-12-22 06:38 UTC, closed without merging

2023-12-22 06:39 UTC, kit1980 commented
Too many people are notified on this PR, please create a new one.