[Inductor Intel GPU backend Upstream]  Step 2: Register and add Intel GPU Inductor backend
pytorch/pytorch pull request #116330
Opened 2023-12-22 14:46 UTC by etaf

Following the [RFC](https://github.com/pytorch/pytorch/issues/114856) , this is the step 2 to add Intel GPU backend as an alternative inductor backend. This PR focus on implementing the basic functionality of Intel GPU backend. 
### Design:
1. Reuse `WrapperCodegen` and `TritonScheduling` for python wrapper code and triton kernel code generation, implement device-bias code generation in `XPUDeviceOpOverrides`.
2. Generalize device-bias interface in triton heuristic to reuse triton kernel configuration and auto-tuning.
3. Reuse python Codecache and triton compilation process.

 Feature request: #114856

2023-12-24 01:56 UTC, EikanWang requested changes
How about making this PR focusing on device runtime generalization? The device code generalization contains two parts.

1. To use device runtime code as the logic of the kernel code
2. To use device runtime code to produce the kernel code when code generation.

In terms of bullet 1, PR #116020 can generalize the logic. Regarding 2, let's take this PR to generalize it.

2023-12-24 01:56 UTC, EikanWang commented on torch/_inductor/codegen/common.py
> +        return XPUDeviceOpOverrides()
Regarding XPU related code, Please add unit test cases.

2023-12-24 01:56 UTC, EikanWang commented on torch/_inductor/codegen/triton.py
> +            compile_wrapper.writeline(f"''', \"{V.graph.scheduler.current_device.type}\")")
The Triton community is refactoring the API. Please double-check if the change is still workable. By the way, it is better to add some comments here.

2023-12-24 01:56 UTC, EikanWang commented on torch/_inductor/graph.py
> +
There should be no test cases can cover this code block.

2023-12-24 01:56 UTC, EikanWang commented on torch/_inductor/triton_heuristics.py
> +        self.device_interface = get_interface_for_device(self.triton_meta["device_type"])
How about renaming it as `gpgpu_device`? Current device abstraction is modeling the gpgpu device for computation. Therefore, I think it is better to make it more specific.

2023-12-25 01:16 UTC, jgong5 approved these changes

2023-12-25 05:11 UTC, EikanWang commented on torch/_inductor/triton_heuristics.py
> +        self.gpgpu_device = get_interface_for_device(self.triton_meta["device_type"])
How about renaming it to `gpu_device`?

2023-12-25 13:15 UTC, etaf commented
@pytorchbot label intel

2023-12-25 13:16 UTC, etaf commented
@pytorchbot label topic: not user facing

2023-12-25 13:17 UTC, etaf commented
@pytorchbot label "topic: not user facing"

2023-12-26 05:59 UTC, EikanWang approved these changes
LGTM

2023-12-26 05:59 UTC, EikanWang commented on torch/_inductor/config.py
> +
Should it be part of Triton section?

2023-12-26 05:59 UTC, EikanWang commented on torch/_inductor/config.py
> +
Regarding the variable name, please follow the style of other variables of config.py.

2023-12-26 05:59 UTC, EikanWang commented on torch/_inductor/autotune_process.py
> +    def initialize(self, device_type: str = "cuda") -> None:
In terms of the device type, you can leverage `V.graph` but don't need to add a dedicated parameter.

2023-12-26 05:59 UTC, EikanWang commented on torch/_inductor/autotune_process.py
> +        get_interface_for_device(device_type).synchronize()
Please leverage `V.graph`

2023-12-28 15:25 UTC, desertfire approved these changes

2023-12-29 00:19 UTC, etaf commented
@pytorchbot merge

2023-12-29 02:49 UTC, closed without merging