[BugFix] Fix SegFault when torch.all/any dispatched to mps or other backends
pytorch/pytorch pull request #116457
Opened 2023-12-27 14:46 UTC by LamForest

Fixes #116452 
Fixes #116451

2023-12-27 15:00 UTC, LamForest commented
@pytorchbot  label "topic: not user facing"

2023-12-27 16:06 UTC, malfet commented
@LamForest thank you for the fix, but why have you marked this one as not user facing, as indeed it is?

2023-12-27 16:12 UTC, malfet requested changes
Hmm, not sure how the changes in reduce ops are related to MPS, as quantized tensors are not tested there at all.

2023-12-27 16:30 UTC, LamForest commented
> @LamForest thank you for the fix, but why have you marked this one as not user facing, as indeed it is? Also, Fixes attribution is wrong...

Because the pytorch-bot suggested....
<img width="897" alt="image" src="https://github.com/pytorch/pytorch/assets/17798738/ae064850-8fa0-429c-8aaf-ba1fca63b5ff">

2023-12-27 16:36 UTC, LamForest commented
> Hmm, not sure how the changes in reduce ops are related to MPS, as quantized tensors are not tested there at all.

any.dims only implemented CPU and CUDA. Other backends, including MPS and quantized dispatch to CompositeExplicitAutograd(see native_functions.yaml):
```
CompositeExplicitAutograd: all_dims_out_default
....
CompositeExplicitAutograd: any_dims_out_default
```
Thats why MPS is related to this PR.

It is no need to test quantized tensors because testing MPS is enough. MPS and quantized shared the same CompositeExplicitAutograd implementation.

2023-12-28 03:00 UTC, LamForest commented
Would you mind reviewing it once more? @malfet 👀

2023-12-30 04:38 UTC, LamForest commented on test/test_mps.py
> -        # Segfaults
segfault is fixed on mps. no need to skip.

2023-12-30 16:46 UTC, LamForest commented
@pytorchbot rebase

2023-12-31 08:34 UTC, LamForest commented
@malfet CI passed, ready to merge

2024-01-04 14:52 UTC, malfet approved these changes
Thank you for the fix!

2024-01-04 14:52 UTC, malfet commented
@pytorchbto merge

2024-01-04 14:53 UTC, malfet commented
@pytorchbot merge

2024-01-04 17:06 UTC, LamForest commented
@pytorchbot label "release notes: mps"

2024-01-04 17:07 UTC, LamForest commented
@pytorchbot merge

2024-01-04 17:37 UTC, closed without merging