[inductor] add C-shim for index_put
pytorch/pytorch pull request #116667
Opened 2024-01-02 23:22 UTC by ColinPeppler

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #116667

2024-01-03 04:08 UTC, aakhundov commented on torch/_inductor/ir.py
> +                f"std::vector<AtenTensorHandle>{{{', '.join(indices)}}}.data()"
Not sure if `std` is allowed in the ABI-compatible mode or whether it should be pure C. cc @desertfire.

2024-01-05 16:05 UTC, ColinPeppler commented
Got an implementation to work that doesn't use `std::vector`. But need to rewrite this to call `at::index_put_out`.

2024-01-08 20:50 UTC, ColinPeppler commented on torch/_inductor/codegen/wrapper.py
> +            args = [x, tensor_handle_array_var, values, accumulate, num_indices]
example codegen
```
AtenTensorHandle tensor_handle_array_1[] = {arg1_1};
aoti_torch_index_put_out(buf0, buf0, tensor_handle_array_1, arg2_1, 1, 1);
```

2024-01-09 17:52 UTC, desertfire requested changes
LGTM other than the parameter order comment I left.

2024-01-09 17:52 UTC, desertfire commented on torch/csrc/inductor/aoti_torch/shim_common.cpp
> +    const AtenTensorHandle* indices,
In other C-shim APIs, the array length comes right after the pointer, e.g. https://github.com/pytorch/pytorch/blob/0ef1266bc631fa8e91bf26a052eacf4b7173ff13/torch/csrc/inductor/aoti_torch/c/shim.h#L256 . Let's keep it that way here.

2024-01-12 01:35 UTC, desertfire approved these changes

2024-01-12 08:53 UTC, chenyang78 approved these changes
LGTM. Thanks!

2024-01-16 17:23 UTC, ColinPeppler commented
@pytorchbot merge

2024-01-16 18:01 UTC, ColinPeppler commented
@pytorchbot merge

2024-01-16 20:29 UTC, closed without merging