Pass Storage by value
pytorch/pytorch pull request #11677
Opened 2018-09-14 00:08 UTC by smessmer

-

Differential Revision: [D9823457](https://our.internmc.facebook.com/intern/diff/D9823457/)

2018-09-14 03:00 UTC, ezyang commented on aten/src/ATen/core/TensorImpl.cpp
> +    scalar_type_(storage_ ? dataTypeToScalarType(storage_.dtype().id()) : ScalarType::Undefined),
So... is referencing `storage_` actually valid here?

2018-09-20 15:13 UTC, ezyang requested changes
doesn't pass ci

2018-09-25 16:55 UTC, SsnL commented
ping @smessmer

2019-02-21 12:10 UTC, soumith commented
looks abandoned

2019-02-21 12:10 UTC, closed without merging