Refactor Logging System for Enhanced Debugging and Clarity
pytorch/pytorch pull request #116953
Opened 2024-01-07 20:25 UTC by RazaProdigy

Fixes #114935

### Key Changes:

1. Introduction of Logging Module: Implemented Python's built-in logging module, replacing existing print statements used for debugging and error reporting.
2. Logging Level and Format Configuration: Configured the logging system with an appropriate level (INFO) and a standard format that includes timestamps and log levels for easier tracking and readability of log messages.
3. Error and Information Handling: Transformed all critical error messages to use logging.error and standard information outputs to logging.info, ensuring a clear distinction between different types of log messages.

### Impact of Changes:

- Improved Debugging: Easier identification and troubleshooting of issues with detailed, timestamped log messages.
- Code Cleanliness and Consistency: A more standardized approach to handling logs and errors throughout the codebase.
- Scalability for Future Development: Establishes a robust foundation for expanding the logging system with additional levels or formats as the application evolves.

I look forward to the team's review and feedback on this enhancement. Thank you!

2024-01-07 20:34 UTC, RazaProdigy commented
@pytorchbot label "topic: not user facing"

2024-01-09 16:04 UTC, ezyang commented on torch/utils/cpp_extension.py
> +logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
this is not allowed

2024-01-09 16:04 UTC, ezyang commented
It is reasonable to make these logs, but it is not ok to change log setting on module import. But unfortunately, there isn't really a good place to change the log setting since we suppress INFO by default. Maybe we should just make them all warnings

2024-01-09 19:51 UTC, RazaProdigy commented
@ezyang Understood. Committed the changes. Could you please have a look again? Thank you!

2024-01-09 21:09 UTC, ezyang requested changes

2024-01-09 21:09 UTC, ezyang commented on torch/utils/cpp_extension.py
> +log.setLevel(logging.WARNING)
no you don't need thi

2024-01-09 21:30 UTC, closed without merging