Fix MSVC build with CUDA enabled
pytorch/pytorch pull request #116926
Opened 2024-01-06 17:25 UTC by pbelcak

Fixes #115922 and #101135

2024-01-06 17:27 UTC, pbelcak commented
@pytorchbot label "topic: not user facing"

2024-01-06 17:28 UTC, pbelcak commented
Also fixes #116242

2024-01-06 17:30 UTC, pbelcak commented
@pytorchbot label "module:cuda"

2024-01-06 17:31 UTC, pbelcak commented
@pytorchbot label "module: cuda"

2024-01-06 17:39 UTC, Skylion007 commented
@pbelcak For the NVTX issue, you should probably take a look at this PR: https://github.com/pytorch/pytorch/pull/109843 . It tries to add NVTK3 as a PyTorch submodule, but was never merged. cc: @cyyever

2024-01-06 17:41 UTC, Skylion007 commented
@atalman Is the signal for NVTX3 Green Internally yet? https://github.com/pytorch/pytorch/pull/109843

2024-01-06 17:49 UTC, pbelcak commented
> @atalman Is the signal for NVTX3 Green Internally yet? #109843

Not sure if this PR depends on it (though it might); building pytorch with the CUDA Toolkit 12.x installed out of the box simply fails on Windows because the cudaToolsExt libraries are simply no longer there; the PR makes changes that alleviate this.

2024-01-06 19:20 UTC, malfet requested changes
Thank you for the change, but do you mind splitting this one int two PRs:
 - One that fixes compilation problem in vec_base.h (please mention the compiler error that were generated before it applied)
 - Another that fixes nvtx discovery (though I it would be better to modify torch:nvtoolsext discovery logic with trying to find it in the cuda toolkit folder and then fallback to the one embedded into the nccl, rather than add `CUDA_VERSION_MAJOR > 12` condition, which is not actually correct, nvtx is shipped with the toolkit but no longer installed by default)

2024-01-06 19:20 UTC, malfet commented on aten/src/ATen/cpu/vec/vec_base.h
> +  //static constexpr size_type size_T = sizeof(T);  // Workaround to compile with VS2022.
Do you mind deleting this line altogether? And half of the preamble about not supporting C++17 yet?

2024-01-08 07:20 UTC, cyyever commented
I can't find cudaToolsExt on Windows too, that is why I was pushing the PR. Unfortunately, some META builds should be fixed before it can be landed.

2024-01-22 20:03 UTC, patrikhuber commented
> Thank you for the change, but do you mind splitting this one int two PRs:
> 
> * One that fixes compilation problem in vec_base.h (please mention the compiler error that were generated before it applied)
> * Another that fixes nvtx discovery (though I it would be better to modify torch:nvtoolsext discovery logic with trying to find it in the cuda toolkit folder and then fallback to the one embedded into the nccl, rather than add `CUDA_VERSION_MAJOR > 12` condition, which is not actually correct, nvtx is shipped with the toolkit but no longer installed by default)

Hi,

I've been encountering both of these issues too and I can provide a bit more information on them.

1) The latest MSVC produced an ICE (internal compiler error). It looks like the workaround in vec_base that was originally needed for an earlier version of MSVC is now no longer needed in the latest MSVC, and in fact creates an ICE. I've logged this with the Visual Studio team https://developercommunity.visualstudio.com/t/post/10539393 but the easiest is, like done in this PR, just to remove the workaround.

2) NVTX **are** indeed still present in the latest CUDA versions, but they're no longer a compiled library: It's now a header-only library. That's why there isn't a .lib file anymore. See here for more details: https://nvidia.github.io/NVTX/. Thus, I believe the best way forward is probably to update libtorch's CMake scripts so that they now look for the header-only version of NVTX if libtorch needs it. Or obviously if NVTX is not needed to build libtorch, it should be removed as a dependency in libtorch's CMake scripts.

2024-01-22 20:10 UTC, patrikhuber commented
And just in case it's helpful, it's not a proper fix I believe, but I made the NvToolsExt issue go away by:

Adding in cuda.cmake L59 after find_package(CUDAToolkit REQUIRED):
```
add_library(CUDA::nvToolsExt INTERFACE IMPORTED)
set_property(TARGET CUDA::nvToolsExt APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${CUDAToolkit_nvToolsExt_INCLUDE_DIRS}")
```

And in share/cmake/Torch/TorchConfig.cmake, this needs to be commented in the if(MSVC)... branch:
```
    set(TORCH_CUDA_LIBRARIES
      # ${NVTOOLEXT_HOME}/lib/x64/nvToolsExt64_1.lib
      ${CUDA_LIBRARIES})
```

And then I think I also needed to add this environment variable in Windows:
`NVTOOLSEXT_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\`

A dirty workaround for sure but perhaps it helps someone to craft the right PR.

2024-03-16 14:49 UTC, patrikhuber commented
Any update on the NVTX issue?

See my comment here for what's happening:

> NVTX are indeed still present in the latest CUDA versions, but they're no longer a compiled library: It's now a header-only library. That's why there isn't a .lib file anymore. See here for more details: https://nvidia.github.io/NVTX/. Thus, I believe the best way forward is probably to update libtorch's CMake scripts so that they now look for the header-only version of NVTX if libtorch needs it. Or obviously if NVTX is not needed to build libtorch, it should be removed as a dependency in libtorch's CMake scripts.

2024-03-17 00:03 UTC, cyyever commented
@patrikhuber We had some troubles when imported the previous NVTX PR into META since some inner builds failed.

2024-03-18 17:23 UTC, patrikhuber commented
> @patrikhuber We had some troubles when imported the previous NVTX PR into META since some inner builds failed.

I'm not sure what you mean with "previous NVTX PR" but I'm not necessarily advocating to merge this PR, I'm just saying this is quite a big issue (basically it breaks using/importing the library with CUDA 12 on Windows) and it would be nice to get it fixed.

2024-03-19 00:10 UTC, cyyever commented
@patrikhuber  I meant #109843

2024-04-02 18:17 UTC, ricardoassaad commented
> And just in case it's helpful, it's not a proper fix I believe, but I made the NvToolsExt issue go away by:
> 
> Adding in cuda.cmake L59 after find_package(CUDAToolkit REQUIRED):
> 
> ```
> add_library(CUDA::nvToolsExt INTERFACE IMPORTED)
> set_property(TARGET CUDA::nvToolsExt APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${CUDAToolkit_nvToolsExt_INCLUDE_DIRS}")
> ```
> 
> And in share/cmake/Torch/TorchConfig.cmake, this needs to be commented in the if(MSVC)... branch:
> 
> ```
>     set(TORCH_CUDA_LIBRARIES
>       # ${NVTOOLEXT_HOME}/lib/x64/nvToolsExt64_1.lib
>       ${CUDA_LIBRARIES})
> ```
> 
> And then I think I also needed to add this environment variable in Windows: `NVTOOLSEXT_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\`
> 
> A dirty workaround for sure but perhaps it helps someone to craft the right PR.

in Cuda 11.8 nvtoolsext is also a header file. the lib file does not exist. I tried your workaround but now i get this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Torch (missing: TORCH_LIBRARY)		C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake	230

2024-04-02 19:34 UTC, patrikhuber commented
The proper way forward with this is that PyTorch has to use `find_package(CUDAToolkit)` and its `CUDA::nvtx3` target - see here https://gitlab.kitware.com/cmake/cmake/-/issues/22893#note_1503430. @malfet @atalman who is the PyTorch CMake maintainer?

2024-04-02 21:08 UTC, ricardoassaad commented
> And just in case it's helpful, it's not a proper fix I believe, but I made the NvToolsExt issue go away by:
> 
> Adding in cuda.cmake L59 after find_package(CUDAToolkit REQUIRED):
> 
> ```
> add_library(CUDA::nvToolsExt INTERFACE IMPORTED)
> set_property(TARGET CUDA::nvToolsExt APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${CUDAToolkit_nvToolsExt_INCLUDE_DIRS}")
> ```
> 
> And in share/cmake/Torch/TorchConfig.cmake, this needs to be commented in the if(MSVC)... branch:
> 
> ```
>     set(TORCH_CUDA_LIBRARIES
>       # ${NVTOOLEXT_HOME}/lib/x64/nvToolsExt64_1.lib
>       ${CUDA_LIBRARIES})
> ```
> 
> And then I think I also needed to add this environment variable in Windows: `NVTOOLSEXT_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\`
> 
> A dirty workaround for sure but perhaps it helps someone to craft the right PR.

this worked for me. i am on cuda 11.8. I only needed to change the NVTOOLEXT_HOME and change this line list(APPEND TORCH_INCLUDE_DIRS ${NVTOOLEXT_HOME}) under the MSVC section in the TorchConfig.cmake. Thanks

2024-04-03 00:50 UTC, cyyever commented
@patrikhuber That means we need to jump CMake version, which may affect packaging.

2024-04-03 10:06 UTC, patrikhuber commented
> @patrikhuber That means we need to jump CMake version, which may affect packaging.

It looks like the nvtx3 target was added in 3.25 https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#findcudatoolkit.
In any case, if you don't want to bump the CMake version, some patch is needed to fix the problem.

2024-06-02 18:03 UTC, patrikhuber commented
I guess if https://github.com/pytorch/pytorch/pull/109843 could be merged, then this could be closed. The other MSVC build problem that this PR tackled was already fixed and merged here https://github.com/pytorch/pytorch/pull/117497.

@pbelcak maybe you want to have a look at https://github.com/pytorch/pytorch/pull/109843?

In any case, @malfet, it would be really great if the NVTX CMake issues could finally be solved, merged, and released.

2024-07-02 18:35 UTC, closed without merging

2024-08-14 11:06 UTC, aleksandaratanasov commented
Bumping up the CMake version doesn't help since the affected `TorchConfig.cmake`, Caffe2's `cuda.cmake` and perhaps other files depending on the `nvToolsExt` binary library are shipped with the download of `libtorch` 11.8, 12.1 and possibly other versions.

In `cuda.cmake` from Caffe2 (found inside `share\cmake\Caffe2\public` of the unpacked libtorch ZIP archive) the dependency is on `CUDA::nvToolsExt`.

2024-08-14 11:44 UTC, aleksandaratanasov commented
I have an older download of `libtorch 2.1.0` where the DLL `nvToolsExt64_1.dll` can be found inside `lib` of the root directory of `libtorch` (wherever you have extracted the ZIP/tar archive).

2024-08-19 11:31 UTC, aleksandaratanasov commented
[This](https://discuss.pytorch.org/t/failed-to-find-nvtoolsext/179635/4) points a working solution (at least in my case) that does not involve copying DLLs from somewhere. The installer of CUDA 11.8 allows to select only the NXVT component that is then installed at `C:/Program Files/NVIDIA Corporation/NvToolsExt`.