[inductor] skip if not reinterpret_view and unbacked symint
pytorch/pytorch pull request #117013
Opened 2024-01-09 03:58 UTC by ColinPeppler

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #117013

2024-01-11 01:59 UTC, ColinPeppler commented
Need to write unit test but requesting review for some thoughts

2024-01-11 14:10 UTC, ezyang commented
I don't know enough about this code to evaluate this change, but you should add a test ;)

2024-01-11 17:13 UTC, jansel requested changes
Add a test please

2024-01-18 14:38 UTC, ezyang approved these changes
@jansel having recently fixed a similar bug in this vein (https://github.com/pytorch/pytorch/pull/117444) it makes sense to me why this would fix a bug, but what I am less sure about is whether or not this is indicative of some sort of systemic problem in the rest of inductor: the `x.realize()` idiom is *very* common in our lowerings. In my other PR, I reasoned correctness through ExternKernelAlloc, where it seemed to me that you needed to do the "harder" realize to materialize a real tensor. But I am less sure about the generalizable lesson here.

I'll go ahead and stamp this for now

2024-01-18 14:38 UTC, ezyang commented on test/inductor/test_unbacked_symints.py
> +        with dynamo_config.patch({"capture_dynamic_output_shape_ops": True}):
nit: you can conveniently use this as a decorator on the test function!

2024-01-18 17:22 UTC, jansel commented
> @jansel having recently fixed a similar bug in this vein (#117444) it makes sense to me why this would fix a bug, but what I am less sure about is whether or not this is indicative of some sort of systemic problem in the rest of inductor: the `x.realize()` idiom is _very_ common in our lowerings. In my other PR, I reasoned correctness through ExternKernelAlloc, where it seemed to me that you needed to do the "harder" realize to materialize a real tensor. But I am less sure about the generalizable lesson here.

I think we already have that "harder" realize that requires stride orders to be the same.  `require_stride_order` -- it comes with a perf cost though since it could introduce a copy.

2024-01-18 17:22 UTC, jansel approved these changes

2024-01-19 18:04 UTC, ColinPeppler commented
@pytorchbot merge

2024-01-19 18:06 UTC, ColinPeppler commented on test/inductor/test_unbacked_symints.py
>      from torch._dynamo.test_case import run_tests
Whoops didn't see this before attempting to merge, I'll quickly test this.

2024-01-19 21:32 UTC, ColinPeppler commented
Included both cuda & cpu paths for test_unbacked_symints.py

2024-01-20 15:32 UTC, ezyang commented
Thanks!!

2024-01-22 22:10 UTC, ColinPeppler commented
I was seeing `AssertionError: Redefinition of test inner_device_cuda` in CI tests. So, hopefully using `instantiate_device_type_tests()` instead of `instantiate_parametrized_tests()` resolves it.

2024-01-22 22:34 UTC, closed without merging