[Inductor Intel GPU backend Upstream] Generalize part of Inductor test case
pytorch/pytorch pull request #117513
Opened 2024-01-16 03:04 UTC by etaf

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

so that the new GPU backend can reuse the existing test case with
minimal code change.
This Pull Request preferentially generalizes the test cases that cover
Inductor's base functionality as follow:
test/inductor/test_codecache.py
test/inductor/test_codegen_triton.py
test/inductor/test_kernel_benchmark.py
test/inductor/test_torchinductor.py
test/inductor/test_torchinductor_codegen_dynamic_shapes.py
test/inductor/test_torchinductor_dynamic_shapes.py
test/inductor/test_torchinductor_opinfo.py
test/inductor/test_triton_heuristics.py
test/inductor/test_triton_wrapper.py

2024-01-16 03:11 UTC, etaf commented
@pytorchbot label intel

2024-01-16 03:11 UTC, etaf commented
@pytorchbot label "topic: not user facing"

2024-01-16 03:12 UTC, etaf commented
@pytorchbot label "ciflow/rocm"

2024-01-16 03:18 UTC, etaf commented
@pytorchbot label "ciflow/inductor"

2024-01-16 06:11 UTC, etaf commented
@pytorchbot label "ciflow/periodic"

2024-01-16 06:11 UTC, etaf commented
@pytorchbot label "ciflow/trunk"

2024-01-17 13:01 UTC, EikanWang requested changes

2024-01-17 13:02 UTC, EikanWang commented
Overall, LGTM.

2024-01-17 13:26 UTC, etaf commented on test/inductor/test_codecache.py
> +        if device in GPU_TYPE and not HAS_GPU:
Yes. Sorry for the typo.

2024-01-17 13:48 UTC, etaf commented on test/inductor/test_torchinductor.py
> +requires_gpu = functools.partial(unittest.skipIf, not HAS_GPU, "requires gpu")
Yes, I will remove this. The reason I keep it here is that  other two test file that we did not cover yet, will import `test_torchinductor.requires_cuda`. I would like to update the other two file.

2024-01-18 01:52 UTC, EikanWang approved these changes

2024-01-18 03:16 UTC, jansel approved these changes

2024-01-18 08:20 UTC, EikanWang commented
@pytorchbot merge

2024-01-18 08:26 UTC, closed without merging

2024-01-18 12:52 UTC, jeanschmidt commented
I am investigating the breakage of `pull / linux-focal-cuda12.1-py3.10-gcc9-sm86 / test` on main. I suspect that the origin is not the PR itself, but instead how tests are grouped in chunks. Reaching out to the respective team.