Drop hard dependency on `networkx`
pytorch/pytorch pull request #117536
Opened 2024-01-16 09:41 UTC by akx

Sibling of #117535.

Aside from `caffe2/python/memonger.py`, all of the imports for `networkx` within the library and tests are optional and guarded with user-friendly error messages, so it probably does not need to be a hard dependency.

2024-01-17 00:35 UTC, Chillee commented
I'm ok with doing this, but we do want networkx to be installed by default. Does this affect that? I'm sure @malfet knows.

If it isn't, I'm fine with landing this.

2024-01-17 06:10 UTC, akx commented
@Chillee Yes, networkx wouldn't be installed by default when you `pip install torch`. The point is that if networkx is not required by most users of the library, it might not need to be a hard dependency, which will save bandwidth, time, and possibly supply chain attack surface.

2024-03-18 17:50 UTC, akx commented
@Chillee Please see my earlier comment. How can we move this forward? 

(Sorry for the ping.)

2024-03-18 20:16 UTC, malfet commented
@pytorchbot rebase

2024-03-18 20:26 UTC, malfet commented
I see it's used in https://github.com/pytorch/pytorch/blob/685ace3834244ead8bccbfde15a437943211565a/torch/_functorch/partitioners.py#L637-L640

https://github.com/pytorch/pytorch/blob/685ace3834244ead8bccbfde15a437943211565a/torch/_functorch/partitioners.py#L666-L670

Which in turn is called from aot_inductor. @zou3519 do you know if this codepath is exercised by default or whether it is a fallback?

2024-03-18 20:46 UTC, Chillee commented
@malfet this codepath is used by default.

2024-03-18 21:33 UTC, zou3519 commented
Deferring to @Chillee

2024-03-18 21:53 UTC, malfet requested changes
If networkx is used by compiler by default and there are no fallback , it is a PyTorch dependency

2024-03-19 04:17 UTC, Chillee commented
@akx Is there any particular reason you want it removed? To be honest, I'm just using it because I was too lazy to write my own min-cut implementation, but writing my own min-cut implementation would not be that difficult if there was a reasonable use case.

2024-04-18 07:33 UTC, closed without merging

2024-04-18 09:00 UTC, akx commented
Why did this get bot-closed? 🤔