add mask_convert_to_lp to support bool->fp16/bf16 convert
pytorch/pytorch pull request #117830
Opened 2024-01-19 05:48 UTC by zhuhaozhe

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-01-20 09:46 UTC, jgong5 requested changes

2024-01-20 09:46 UTC, jgong5 commented on torch/_inductor/codegen/cpp_prefix.h
> +inline at::vec::Vectorized<scalar_t> mask_convert_to_lp(at::vec::Vectorized<float> src) {
```suggestion
template <typename scalar_t>
inline
typename std::enable_if<std::is_same<scalar_t, bfloat16>::value || std::is_same<scalar_t, half>::value, at::vec::Vectorized<scalar_t>>::type
mask_convert_to_lowp(at::vec::Vectorized<float> src) {
```

2024-01-20 09:46 UTC, jgong5 commented on torch/_inductor/codegen/cpp.py
> +            return f"mask_convert_to_lp<{DTYPE_TO_CPP[dtype]}>({x})"
```suggestion
            return f"mask_convert_to_lowp<{DTYPE_TO_CPP[dtype]}>({x})"
```

2024-01-20 09:46 UTC, jgong5 commented on test/inductor/test_cpu_repro.py
> +    def test_logical_op_store_to_lp_data_dtype(self):
```suggestion
    def test_logical_op_store_to_lowp_data_dtype(self):
```

2024-01-22 01:05 UTC, zhuhaozhe commented on test/inductor/test_cpu_repro.py
> +    def test_logical_op_store_to_lp_data_dtype(self):
thanks for advice, all revised.

2024-01-22 01:42 UTC, jgong5 approved these changes

2024-01-22 07:47 UTC, zhuhaozhe commented
@pytorchbot  rebase

2024-01-22 19:38 UTC, jansel approved these changes

2024-01-23 01:14 UTC, zhuhaozhe commented
@pytorchbot merge

2024-01-23 01:25 UTC, zhuhaozhe commented
@pytorchbot merge

2024-01-23 02:07 UTC, zhuhaozhe commented
@pytorchbot merge

2024-01-23 07:52 UTC, closed without merging