fix torch.cumsum docs
pytorch/pytorch pull request #117944
Opened 2024-01-21 16:34 UTC by jeejeelee

2024-01-22 14:08 UTC, zou3519 requested changes
This is expected due to floating-point differences: the printing of a does not actually show all the digits. A better example would probably be to construct some sequence of numbers (ints to make things easier to visualize), and then call cumsum on it.

2024-01-23 16:35 UTC, jeejeelee commented
@zou3519  Thanks for your review. I am still a rookie when it comes to PR, Does it mean that I should modify torch.cumsum docs in the following way?
```doc

    >>> a = torch.randint(1, 20, (10,))
    >>> a
    tensor([ 5,  8, 12, 15, 11,  6, 11, 16, 15,  8])
    >>> torch.cumsum(a, dim=0)
    tensor([  5,  13,  25,  40,  51,  57,  68,  84,  99, 107])
```

2024-01-23 18:02 UTC, zou3519 commented
> @zou3519 Thanks for your review. I am still a rookie when it comes to PR, Does it mean that I should modify torch.cumsum docs in the following way or close this PR?
> 
> ```
> 
>     >>> a = torch.randint(1, 20, (10,))
>     >>> a
>     tensor([ 5,  8, 12, 15, 11,  6, 11, 16, 15,  8])
>     >>> torch.cumsum(a, dim=0)
>     tensor([  5,  13,  25,  40,  51,  57,  68,  84,  99, 107])
> ```

That sounds reasonable to me

2024-01-24 02:39 UTC, zou3519 commented on torch/_torch_docs.py
> +    ttensor([13, 20, 23, 33, 46, 49, 64, 74, 83, 93])
tensor with one t

2024-01-24 03:18 UTC, jeejeelee commented on torch/_torch_docs.py
> +    ttensor([13, 20, 23, 33, 46, 49, 64, 74, 83, 93])
I have already corrected this error.

2024-01-26 20:07 UTC, zou3519 approved these changes

2024-01-29 02:29 UTC, jeejeelee commented
@zou3519 ,some checks were not successful ,what should Ido ?

2024-02-05 06:12 UTC, jeejeelee commented
@pytorchbot  merge

2024-02-05 10:45 UTC, jeejeelee commented
@pytorchbot merge -i

2024-02-12 13:36 UTC, zou3519 commented
@pytorchbot rebase

2024-02-13 15:26 UTC, jeejeelee commented
@pytorchbot merge

2024-02-13 15:29 UTC, closed without merging