[Inductor] optimize transpose_mxn with bf16 data type
pytorch/pytorch pull request #117958
Opened 2024-01-22 02:42 UTC by leslie-fang-intel

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-01-22 07:35 UTC, jgong5 requested changes
How about avx256?

2024-01-22 08:21 UTC, leslie-fang-intel commented on aten/src/ATen/cpu/vec/vec512/vec512_bfloat16.h
> +  // t[31]: 992 993 994 995 996 997 998 999 1000 1001 1002 1003 1004 1005 1006 1007 1008 ... 1023
Thanks for the suggestion and removed.

2024-01-22 08:21 UTC, leslie-fang-intel commented on aten/src/ATen/cpu/vec/vec512/vec512_bfloat16.h
> +  // t[31]: 992 993 994 995 996 997 998 999 1000 1001 1002 1003 1004 1005 1006 1007 1008 ... 1023
Same to remove this part.

2024-01-22 08:22 UTC, leslie-fang-intel commented on aten/src/ATen/cpu/vec/vec512/vec512_bfloat16.h
> +  }
Thanks for the suggestion and added `#pragma unroll(n)` to force the compiler unroll these loops.

2024-01-22 08:22 UTC, leslie-fang-intel commented on aten/src/ATen/cpu/vec/vec512/vec512_bfloat16.h
> +  r[7] = _mm512_inserti64x4(_mm512_castsi256_si512(t[11]), t[15], 0x01);
Sure, simplify the code with loops.

2024-01-22 08:24 UTC, leslie-fang-intel commented
> How about avx256?

Thanks for the suggestion. Add a TODO to enable the AVX2 counterparts. Can we enable it later?

2024-01-22 08:47 UTC, jgong5 approved these changes

2024-01-23 01:16 UTC, leslie-fang-intel commented
@pytorchbot merge

2024-01-23 09:40 UTC, lezcano approved these changes
I have not reviewed, but @jgong5 has.

2024-01-23 09:40 UTC, lezcano commented
@pytorchbot merge

2024-01-23 09:43 UTC, closed without merging