Fuse dict keys into a DICT_KEYS guard if we are guarding on all of them.
pytorch/pytorch pull request #118096
Opened 2024-01-23 15:15 UTC by lezcano

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

We group guards on keys that are "easily printable" and we
transform them into just one `DICT_KEYS`.

It feels a bit silly to first split the guards in the `builder` and then
regroup them, but this allows for a number of things:
1. Correctness. `DICT_KEYS` was trying to do too much before this set of
   PRs. Now `DICT_KEYS` will be reserved for things that are easy to
   print. If they are not then we fallback to the slower but correct
   getitem method. Even more so, if the builder places several guards on
   find which ones can be elided by the `DICT_KEYS` transformation,
   while the others will be kept there for correctness.
2. Can be applied to lazy keys. We can generalize `DICT_KEYS` so that it
   just checks that a subset of keys exist within the dict. We just have
   this info at guard creation, not at guard instantiation.

For now we just perform this optimisation for CONSTANT_MATCH, but we
plan to generalize this to other types in the future, once we have lazy
key support.

2024-01-23 16:00 UTC, peterbell10 reviewed
Needs some tests but otherwise LGTM.

2024-01-23 16:00 UTC, peterbell10 commented on torch/_dynamo/guards.py
> +        # (ConstDictKeySource.reconstruct is O(n), we just place a guard
```suggestion
        # (ConstDictKeySource.reconstruct is O(n)), we just place a guard
```

2024-01-23 16:00 UTC, peterbell10 commented on torch/_dynamo/guards.py
> +            if len(elem_guards) == l:
NIT: `l` (ell) is easily confused with `1` (one). Maybe call this `n_elems`?

2024-01-24 01:13 UTC, jansel requested changes
Add a test

2024-01-24 17:02 UTC, lezcano commented
Superseded by https://github.com/pytorch/pytorch/pull/118194

2024-01-24 17:02 UTC, closed without merging