Update oneDNN build option for older systems
pytorch/pytorch pull request #118057
Opened 2024-01-23 02:27 UTC by yanbing-j

Fixes [#116623](https://github.com/pytorch/pytorch/issues/116623).

As we discussed in https://github.com/pytorch/pytorch/issues/116623#issuecomment-1900406773 and https://github.com/pytorch/pytorch/issues/116623#issuecomment-1900825829, we update oneDNN build option to support older systems and document we only support CPUs with SSE4.1+.

2024-01-23 06:20 UTC, malfet requested changes
Change to FindMKLDNN looks OK, but change in the README feels in the conflict with what this PR is trying to do, isn't it?

2024-01-23 06:37 UTC, yanbing-j commented
> Change to FindMKLDNN looks OK, but change in the README feels in the conflict with what this PR is trying to do, isn't it?

Yes. Or I just remove the change of documents, and remain the change of FindMKLDNN. WDYT?

2024-01-23 06:50 UTC, malfet commented
Yes, and also it would be nice to revive the qemu test similar to one that existed in https://github.com/pytorch/pytorch/pull/38094

2024-01-23 07:40 UTC, malfet commented
By the way, I can confirm, by running `qemu-x86_64 -cpu Opteron_G1 /usr/bin/python3 -c "import torch"` that fix indeed works, would be nice to include this one at least in PRs test plan

2024-01-23 08:22 UTC, yanbing-j commented
Hi @malfet , thanks for the guidance!

I only remove the document change, because I cannot find `config.yml` and `pytorch-job-specs.yml` listed in https://github.com/pytorch/pytorch/pull/38094. Could you please tell me the right place to add the qemu test? Thanks!

2024-01-23 15:20 UTC, malfet approved these changes
Let's land it as is and I'll add the test later (perhaps to the nightly builds)

2024-01-24 00:58 UTC, yanbing-j commented
@pytorchbot merge

2024-01-24 11:45 UTC, yanbing-j commented
Hi @malfet , the only 1 failure `trunk / linux-focal-rocm5.7-py3.8 / test (default, 1, 1, linux.rocm.gpu, unstable) (push)` seems not related to this PR, could you please help merge? Thanks!

2024-01-25 11:31 UTC, yanbing-j commented
@pytorchbot merge

2024-01-25 11:34 UTC, closed without merging