Replace `constraints` with dynamic_shapes
pytorch/pytorch pull request #118345
Opened 2024-01-26 00:53 UTC by BoyuanFeng

Differential Revision: D53109299

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

2024-01-29 21:33 UTC, tugsbayasgalan requested changes
I don't think we should be adding pre_dispatch flag at top level export API

2024-01-29 21:33 UTC, tugsbayasgalan commented on torch/export/__init__.py
> +        pre_dispatch=pre_dispatch,
Why do we need this?

2024-01-31 03:33 UTC, zhxchen17 approved these changes

2024-01-31 22:25 UTC, avikchaudhuri approved these changes

2024-01-31 22:25 UTC, avikchaudhuri commented on torch/export/__init__.py
> +    dynamic_shapes: Optional[Union[Dict[str, Any], Tuple[Any], List[Any]]] = None,
Why does it have to be a list (i.e., why not just tuple)?

2024-01-31 22:30 UTC, tugsbayasgalan approved these changes

2024-02-02 00:38 UTC, closed without merging