Updated docs styles
pytorch/pytorch pull request #11835
Opened 2018-09-18 21:59 UTC by brianjo

Updated requirements.txt and conf.py.

2018-09-18 22:11 UTC, SsnL commented
Need a rebase

2018-09-19 13:52 UTC, ericnakagawa approved these changes
All internal tests pass. Thanks Brian.

2018-09-19 14:58 UTC, ssnl reviewed
Local build is busted. It succeeds, but when viewing, I'm getting a lot of http errors, e.g.,
```
127.0.0.1 - - [19/Sep/2018 07:55:59] "GET /build/html/_static/images/chevron-right-orange.svg HTTP/1.1" 304 -
127.0.0.1 - - [19/Sep/2018 07:55:59] code 404, message File not found
127.0.0.1 - - [19/Sep/2018 07:55:59] code 404, message File not found
```

I installed the dependencies and used the usual build command `make clean; make html`.

2018-09-19 14:58 UTC, SsnL commented on docs/source/conf.py
>  # Theme options are theme-specific and customize the look and feel of a theme
This comment seems obsolete.

2018-09-19 14:59 UTC, SsnL commented
Here's how local build looks like for me.

<img width="1414" alt="screenshot 2018-09-19 10 57 32" src="https://user-images.githubusercontent.com/5674597/45761818-fe737e00-bbfa-11e8-87f3-53dfbcab81fc.png">
<img width="1459" alt="screenshot 2018-09-19 10 57 40" src="https://user-images.githubusercontent.com/5674597/45761819-fe737e00-bbfa-11e8-9cc2-e159d4e4d151.png">

2018-09-19 15:15 UTC, SsnL commented
After cmd+shift+r the website loads! Thanks @brianjo . However, it seems that the declarations are all rendered wrongly, e.g.,
```
torch.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, profile=None)
```
looks like
<img width="1120" alt="screenshot 2018-09-19 11 15 07" src="https://user-images.githubusercontent.com/5674597/45762857-50b59e80-bbfd-11e8-857b-947683dee8b8.png">

and
```
torch.distributed.send(tensor, dst, group=<object object>, tag=0)
```
looks like
<img width="785" alt="screenshot 2018-09-19 11 15 44" src="https://user-images.githubusercontent.com/5674597/45762890-61661480-bbfd-11e8-991b-b0db6453b483.png">

2018-09-19 18:34 UTC, zou3519 requested changes
Requesting changes based on @SsnL's comments (website not rendering correctly locally)

2018-09-19 18:40 UTC, SsnL commented
@zou3519 Yes, this seems like a theme-related issue. @brianjo is actively working with the vendors to resolve this. Hopefully we can get this nice looking theme merged soon. :)

2018-09-20 23:44 UTC, ericnakagawa commented
Folks, the theme issue has been resolved.

<img width="735" alt="screen shot 2018-09-20 at 4 26 49 pm" src="https://user-images.githubusercontent.com/23874/45852388-7376ae80-bcf4-11e8-9070-8e33794223c4.png">

Please merge.

2018-09-21 04:12 UTC, closed without merging