[dynamo] Validate check_fn
pytorch/pytorch pull request #118448
Opened 2024-01-27 00:40 UTC by anijain2305

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-01-28 01:16 UTC, jansel requested changes
Test errors?  Are you looking for feedback here?

2024-01-28 04:40 UTC, anijain2305 commented
I thought that there were only a couple of category of errors and my stack fixed them, but there are just too many :( I will debug and send fixes for others.

2024-01-28 06:09 UTC, anijain2305 commented
Categorizing the errors. All these require specific knowledge, so asking for help

1) `pytest -vs test/dynamo/test_dynamic_shapes.py::DynamicShapesMiscTests::test_getset_descriptor_dynamic_shapes` - cc @mlazos. This is because the `id(torch.Tensor.shape.__get__)` changes invocation to invocation (idk why). Can you please follow up?

2) `pytest -s test/dynamo/test_higher_order_ops.py::HigherOrderOpVmapGuardTests::test_vmap_guard_fail` - This is vmap + dynamo issue - tracked here https://github.com/pytorch/pytorch/issues/118493

3) `pytest test/dynamo/test_repros.py::ReproTests::test_odict_get_item_index_name` - This happens because of `list(dict.keys()) == [..]` guard. @lezcano  is already working on removing it. Many tests under `quantization` are due to the same issue.

4) `python -s test/dynamo/test_export.py -k test_export_with_symbool_inputs` - This one likely fails because running `check_fn` runs guard `cast_symbool_to_symint_guardless` which upsets the testing code. cc @ydwu4 @ezyang for this one.

5) `python distributions/test_distributions.py::TestJit::test_variance` - Doesnt repro on my machine.

2024-01-28 14:05 UTC, ezyang approved these changes
The assert message when this fails is going to be pretty bad, maybe at minimum print the guard code

2024-01-28 14:06 UTC, ezyang commented
Oops i need to read comments lol

2024-01-28 17:48 UTC, jansel commented
I'm kind of surprised we didn't find this earlier... won't it just result in a recompile loop until we hit the cache limit?

2024-01-28 22:44 UTC, anijain2305 commented
> I'm kind of surprised we didn't find this earlier... won't it just result in a recompile loop until we hit the cache limit?

The tests just invoke the `opt_fn` once. So, we never reach cache limit.

2024-01-29 04:19 UTC, ezyang commented
Re (4), I don't remember exactly how @ydwu4 implemented this, but one thing I remember discussing in PR review was that guard checks on inflowing SymInts must do checks entirely on hints, and only force guards on the underlying SymInts if the guard actually matches. Assuming that there is a mechanism like this, then to validate check fn, what you want to do is do the hint check but omit the part where guards are actually forced. Not sure how to spell this, but morally that's what should be done. Hopefully @ydwu4 can elaborate.

2024-01-29 18:15 UTC, ydwu4 commented
I can take a deeper look at the (4). It could be that we should return the hint of the symbolic expression (i.e. a concrete boolean value) instead of the expression itself. I'll sync with @anijain2305 later today.

2024-01-30 19:01 UTC, ydwu4 commented
For 4), discussed with @anijain2305. The test is expecting dynamo tracing doesn't specialize symbool's shape_env. However, in this pr, check_fn is called immediately, which specializes the outer shape_env of `L['pred']` because of the `if cast_symbool_to_symint(L['pred']) == False `check in the check_fn.

I think it might be the correct behavior to call check_fn immediately to specialize the outer shape_env and we just need to modify the expected guards of outer shape_env. Because the symbool inputs are indeed specialized for this particular code path that dynamo traces and guards. By propagating the guard immediately, it is also consistent with the behavior where we have a symbool inputs for a eager program and we run it without torch.compile, where it specializes the symbool's shape_env. Any comments? @ezyang

2024-01-31 16:33 UTC, ezyang commented
Although I agree it all works out in the end, in this case, I would prefer for us to keep the invariant that no updates to the enclosing Python runtime can be made until we are DONE with compiling. Prematurely modifying the Python runtime state during compilation is an invariant violation.

2024-02-07 00:35 UTC, anijain2305 commented
Another issue discovered at https://github.com/pytorch/pytorch/issues/119338

2024-07-02 22:01 UTC, anijain2305 commented on test/dynamo/test_subclasses.py
> +    @unittest.expectedFailure
@ydwu4 Another xfail here. Let me know if thats ok.

2024-07-02 22:02 UTC, anijain2305 commented on test/export/test_export.py
> +    @unittest.expectedFailure
@ydwu4 xfail here.

2024-07-02 22:16 UTC, ydwu4 commented on test/dynamo/test_subclasses.py
> +    @unittest.expectedFailure
Discussed offline. I'll take a look.

2024-07-03 00:15 UTC, anijain2305 commented
@jansel @ezyang This is ready for review.

Many tests are xfailed. Fixing them would take some time and help from other engineers on the torch.compile stack. They are covered by the tracker.But, I think xfailing and merging this PR is better than waiting.

2024-07-03 05:13 UTC, jansel approved these changes

2024-07-04 21:22 UTC, anijain2305 commented
@pytorchbot merge

2024-07-04 22:01 UTC, anijain2305 commented
@pytorchbot merge

2024-07-05 14:51 UTC, anijain2305 commented
@pytorchbot merge

2024-07-05 18:04 UTC, closed without merging