[Inductor] Skip triton templates for mixedmm on V100
pytorch/pytorch pull request #118591
Opened 2024-01-29 23:55 UTC by malfet

As it results in numerical errors, see https://github.com/pytorch/pytorch/issues/117144

Fixes https://github.com/pytorch/pytorch/issues/117144

2024-01-29 23:56 UTC, malfet commented
I wonder if I should move `is_v100_gpu` to utils (and perhaps rename it to `is_volta_gpu`?

2024-01-30 04:45 UTC, jansel requested changes

2024-01-30 04:45 UTC, jansel commented on torch/_inductor/kernel/mm.py
> +    return props.major == 7
```suggestion
    return props.major <= 7
```

2024-01-30 04:45 UTC, jansel commented on torch/_inductor/kernel/mm.py
> +def _is_v100_gpu(index: Optional[int]) -> bool:
```suggestion
def _is_v100_or_older_gpu(index: Optional[int]) -> bool:
```

2024-01-30 04:46 UTC, jansel commented
Seems safer to also disable for older GPUs than Volta.

2024-01-30 19:16 UTC, malfet commented
@jansel renamed to `_is_sm7x_or_older_gpu` (I wonder if I should just return False for ROCM GPUs)

2024-01-31 05:12 UTC, jansel approved these changes

2024-01-31 05:13 UTC, jansel commented
Not sure what to do about rocm.  Maybe someone from AMD can help figure out minimum requirements there.

2024-01-31 20:46 UTC, malfet commented
@pytorchbot merge

2024-01-31 21:09 UTC, malfet commented
@pytorchbot merge

2024-01-31 23:30 UTC, closed without merging