[torch] fix comment typo
pytorch/pytorch pull request #118656
Opened 2024-01-30 18:47 UTC by wilson100hong

Summary: as title

Differential Revision: D49841787

2024-01-30 18:55 UTC, Skylion007 approved these changes

2024-01-31 02:43 UTC, zhxchen17 requested changes
the doc needs some update

2024-01-31 02:43 UTC, zhxchen17 commented on torch/export/_trace.py
> +        f: the callable to trace.
Actually, this should only support nn.Module, not the other way around

2024-01-31 02:43 UTC, zhxchen17 commented on torch/export/_trace.py
> +        f: the callable to trace.
We can also change the type annotation of `f` to be torch.nn.Module here.

2024-01-31 20:56 UTC, zhxchen17 approved these changes
thanks!

2024-02-04 19:20 UTC, zhxchen17 commented
@pytorchbot merge

2024-02-04 19:28 UTC, zhxchen17 commented
@pytorchbot merge

2024-02-04 22:20 UTC, closed without merging