Remove DICT_KEYS guard
pytorch/pytorch pull request #118630
Opened 2024-01-30 11:03 UTC by lezcano

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

This guard was trying to do too much. We replace it for the weaker
DICT_CONST_KEYS, which is only valid when all the values are constants
(i.e. easy to print out).

We also implement an optimisation where, if all the keys to a dictionary
are constant, we generate just one guard of the form
```
list(d.keys()) == ["key1", "key2"]
```

This is the type of guards we used to generate initially before this set
of PRs.

2024-01-30 11:04 UTC, lezcano commented
The trickiest use of the DICT_KEYS guard was within `optimizer.py`.
There, this guard was used to "manually trace" through `optim.state`.
I have replaced that manual tracing with a call to `VariableBuilder`,
but that currently sets some dupe guards between `optim.state` and
`optim.param_groups["params"]`.

@mlazos do you originally wrote the code
this way to avoid that guard? If so, I can remove it and change it by a
`DICT_ID_KEYS` and still remove `DICT_KEYS`

2024-01-30 14:13 UTC, peterbell10 requested changes
Makes sense, but `test_compiled_optimizers.py` failure looks real.

2024-01-30 14:22 UTC, lezcano commented
This fixed a graphbreak in asgd and nadam apparently. I have not looked into what happened there really, but I guess that's good.

2024-01-30 14:24 UTC, lezcano commented on torch/_dynamo/guards.py
> +    def DICT_CONST_KEYS(self, guard):
I mean, there is a streak of 3 that are in alphabetical order... jajajajaj I'll leave it as is to keep the diff minimal.

2024-01-30 17:39 UTC, lezcano commented
Triggered a benchmark run to see if there's any perf hit in all the changes in this stack.

2024-01-30 17:40 UTC, jansel approved these changes

2024-01-30 17:58 UTC, mlazos approved these changes

2024-01-30 17:59 UTC, peterbell10 approved these changes

2024-01-30 17:59 UTC, peterbell10 commented on test/inductor/test_compiled_optimizers.py
> +    "test_asgd_recompile_single": 16,
NIT: I think this value is defined here

https://github.com/pytorch/pytorch/blob/44632939b5aa0c3e658d807c294df8fb3018fb91/test/inductor/test_compiled_optimizers.py#L320-L323

2024-02-01 10:17 UTC, lezcano commented
The optim changes seem to regress a bit. I'll look into how to get the graphbreak wins from this PR without regressing. I'm merging the rest of the stack, as that seems fine (might need to split the constant dict optimisation into its own PR tho as there are some regressions on gnns otherwise)

2024-07-17 09:18 UTC, closed without merging