make nanogpt work with both compiled autograd and _LazyGraphModule
pytorch/pytorch pull request #118981
Opened 2024-02-02 07:57 UTC by shunting314

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-02-02 19:36 UTC, jansel requested changes
Add a test

2024-02-03 00:09 UTC, shunting314 commented
@jansel  I just added a simple enough repro. Looks like the key to repro is to do an extra compilation on the function to test.

2024-02-04 18:11 UTC, jansel approved these changes

2024-02-05 06:51 UTC, shunting314 commented
@pytorchbot merge

2024-02-05 10:40 UTC, closed without merging