Moving function_schema to aten/core
pytorch/pytorch pull request #11895
Opened 2018-09-20 18:50 UTC by bwasti

Summary: Couple more moves to unblock IR unification

Differential Revision: D9819906

2018-09-21 14:44 UTC, ezyang commented on aten/src/ATen/core/function_schema.h
> +#include "ATen/ATen.h"
You can't do this, `ATen/ATen.h` pulls in a lot of other stuff that's not core, and if you actually use those symbols you'll get a linker error in envs that only link against source files in core. Try deleting it and see what you actually need.

2018-09-21 14:50 UTC, ezyang commented on aten/src/ATen/core/interned_strings.h
> +#include "torch/csrc/jit/generated/aten_interned_strings.h"
We talked about this: the plan is to remove this `#include` from `interned_strings.h` entirely

2018-09-21 14:52 UTC, ezyang requested changes
aten_interned_strings.h needs to be handled

2018-09-25 16:35 UTC, fmassa commented
@bwasti could you look into addressing @ezyang comments?

2022-05-12 02:14 UTC, closed without merging