Fix constant propagation in builtins and UserClasses
pytorch/pytorch pull request #118994
Opened 2024-02-02 12:13 UTC by lezcano

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #118994

Fixes https://github.com/pytorch/pytorch/issues/118675

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @aakhundov

2024-02-02 19:01 UTC, lezcano commented on torch/_dynamo/variables/builtin.py
> +            return builder(getattr(obj.as_python_constant(), name))
Note that `is_python_constant` is much more general than `ConstantVariable`. That's one of the reasons why,e ven after fixing the SourcelessBuilder errata, I'm still getting tons of errors.
Let me put this as WIP for now.

2024-02-02 19:11 UTC, peterbell10 commented on torch/_dynamo/variables/builtin.py
> +            return builder(getattr(obj.as_python_constant(), name))
Note that the code I linked is in the `VariableTracker` base class, not `ConstantVariable`. I'm actually surprised that `const_getattr` doesn't have a base implementation. I would think this is pretty general:
```python
return getattr(self.as_python_constant(), name)
```

2024-02-06 13:54 UTC, lezcano commented on torch/_dynamo/variables/builtin.py
> +            return builder(getattr(obj.as_python_constant(), name))
Implementing this in the base class took me down a rabbit hole, but if I manage to get it right, I think we should get quite a bit of functionality for free. Let's see...

2024-02-06 16:47 UTC, jansel requested changes

2024-02-06 16:47 UTC, jansel commented on torch/_dynamo/variables/tensor.py
> +            return
Returning `None` seems wrong since the call above is expecting to catch NotImplementedError.

2024-07-22 18:29 UTC, closed without merging