[dynamo] Refactor TorchHigherOrderOperatorVariable method handling with dispatch table implementation
pytorch/pytorch pull request #119136
Opened 2024-02-04 01:49 UTC by ragizaki

[Fixes #119128](https://github.com/pytorch/pytorch/issues/119128)

hey all, first oss contribution in this repo so I would appreciate any feedback. I tackled one of the issues mentioned with the handling of switch statements and implemented a factory that calls a dispatch table to reduce time complexity of the switch statements from `O(n)` to `O(1)`

2024-02-04 01:55 UTC, ragizaki commented
@pytorchbot label "topic: not user facing"

2024-02-04 18:20 UTC, jansel approved these changes

2024-02-04 18:23 UTC, jansel commented
@pytorchbot merge

2024-02-04 18:23 UTC, jansel commented
Thanks!

2024-02-04 22:45 UTC, jansel reviewed
Looks like there is a syntax error, see:

2024-02-04 22:46 UTC, jansel requested changes
Tests are failing due to syntax error:
https://hud.pytorch.org/pr/pytorch/pytorch/119136#21202444172

2024-02-05 00:15 UTC, jansel commented
`make setup_lint && lintrunner -a` to fix lint errors

2024-02-08 15:39 UTC, zou3519 reviewed
tests look like they're failing

2024-05-08 16:35 UTC, closed without merging