[dynamo] inliing into __iter__ of user defined object
pytorch/pytorch pull request #119243
Opened 2024-02-06 00:31 UTC by ydwu4

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #119243

2024-02-07 04:58 UTC, ezyang commented on torch/_dynamo/variables/builtin.py
> +        if self.fn is iter and args and isinstance(args[0], UserDefinedObjectVariable):
Do you actually need to test for UDOV here, it seems to me that the meaning of `iter` is literally "run the `__iter__` impl" (which is either in Python, or tp_iter).

2024-02-07 05:41 UTC, jansel requested changes

2024-02-07 05:41 UTC, jansel commented on torch/_dynamo/variables/builtin.py
> +            unimplemented(f"__iter__ is not implemented for {args[0]} {args[0].value}")
Why not just:
```
args[0].call_method(tx, "__iter__", [], {})
```

2024-02-07 06:14 UTC, anijain2305 commented on torch/_dynamo/variables/builtin.py
> +        if self.fn is iter and args and isinstance(args[0], UserDefinedObjectVariable):
We should create a new helper - `call_iter` to handle this? There is a handler business in L692 which will redirect the logic to newly created `call_iter` helper.

2024-02-08 04:13 UTC, jansel approved these changes

2024-02-08 17:04 UTC, ydwu4 commented
@pytorchbot merge

2024-02-08 17:07 UTC, closed without merging