[jit] Add default values in script
pytorch/pytorch pull request #11962
Opened 2018-09-22 01:46 UTC by driazati

PR adds support for `int` and `float` default values for script functions (values get cast to `Tensor` implicitly)

2018-09-22 01:47 UTC, driazati commented on torch/csrc/jit/script/tree_views.h
> +// Helper nodes (mostly for function arguments)
Had to move this to use `Const` from inside `Param` to add `Param::has_default()` and `Param::default_value()`

2018-10-02 03:51 UTC, zdevito requested changes
Adding support for default arguments is a great thing to work on, but I think this is ultimately not the right approach. Instead, I would suggest a much simpler set of changes:

1. Extract the default values from the original functions using: https://stackoverflow.com/questions/12627118/get-a-function-arguments-default-value
2. Compile the function into a graph as is, without changing the compiler or `ir.h`, deriving a `script::Method` object without any default values in it. Use the types inside of the derived `FunctionSchema`object and `inline IValue toIValue(py::handle obj, const TypePtr& type)` to turn the python default value into an IValue. 
3. Generate a new `FunctionSchema` object that includes the default IValues, and call `setSchema` on the Method to install it.

This approach is more modular (it doesn't require changes to AST parsing, the compiler, or the IR), and it relies on components we already have to robustly convert python values into IValue objects.

2018-10-02 03:51 UTC, zdevito commented on torch/csrc/jit/ir.h
> +  virtual ~Value() {}
There is no need for any changes to ir.h to add default values. We already support default values in `FunctionSchema` and each `script::Method` object has a function schema.

2018-10-02 03:51 UTC, zdevito commented on torch/csrc/jit/script/compiler.cpp
> +      Const default_const = decl_arg.default_value();
I am not sure what is going on here. I would rather not support default arguments from our string frontend yet, as it requires implementing a bunch more infrastructure than we currently have.

2018-10-04 21:55 UTC, closed without merging