[caffe2]Export symbols for pybind and other libs after caffe2 rebase
pytorch/pytorch pull request #11975
Opened 2018-09-22 14:18 UTC by gujinghui

Export symbols for pybind and other libs after caffe2 rebase

2018-09-22 16:06 UTC, yinghai commented
What's the test command to show before and after this PR?

2018-09-23 14:53 UTC, gujinghui commented
@yinghai 

The two failures above should be not related to ideep code.
In build log, you can see USE_MKL option is OFF, so dose USE_IDEEP.

In recent master branch, the USE_IDEEP is always disabled, that's why there're so many issues...
And I'm trying to fix all of them in #11853, simplify iDEEP options and enable MKL-DNN.
Pls help me.

To enable iDEEP for caffe2 only, please try below config.
cmake -DBLAS=MKL -DUSE_MKL=ON -DUSE_IDEEP=ON -DUSE_MKLML=ON ..

2018-09-24 20:36 UTC, yinghai commented
Could you rebase on upon recent master?

2018-09-25 02:27 UTC, gujinghui commented
@yinghai  Done. pls have a try.

2018-09-25 17:42 UTC, yinghai commented
I think this is suspicious. Master doesn't have any failures.

2018-09-25 21:17 UTC, ezyang commented
this was briefly broken on master.

2018-09-25 21:17 UTC, ezyang commented
Did you intend to update the submodule?

2018-09-25 21:17 UTC, ezyang commented
@pytorchbot retest this please

2018-09-25 23:37 UTC, yinghai approved these changes
Cool! Looks like things are good. Next step would be unifying the build for MKLDNN.

2018-09-26 04:37 UTC, yinghai requested changes

2018-09-26 04:37 UTC, yinghai commented on caffe2/ideep/utils/ideep_context.h
> +BaseStaticContext* CAFFE2_EXPORT GetIDEEPStaticContext();
Actually, we have this error: 
```
caffe2/caffe2/ideep/utils/ideep_context.h:11:56: error: ‘__visibility__’ attribute ignored on non-class types [-Werror=attributes]
 BaseStaticContext* CAFFE2_EXPORT GetIDEEPStaticContext();
                                                        ^
```

2018-09-26 04:48 UTC, yinghai commented on caffe2/ideep/utils/ideep_context.h
> +BaseStaticContext* CAFFE2_EXPORT GetIDEEPStaticContext();
You probably need to change it to 
```
C10_EXPORT BaseStaticContext* GetIDEEPStaticContext();
```

BTW, due to recent changes, we need to replace `CAFFE2_EXPORT` to `C10_EXPORT`. 

And what is the reason to update ideep submodule again?

2018-09-26 09:46 UTC, gujinghui commented
@yinghai 
rebased to use C10_EXPORT.
pls review.

2018-09-27 21:17 UTC, yinghai approved these changes

2018-09-27 21:41 UTC, closed without merging