[quant][pt2e] Add `model_is_exported` util function
pytorch/pytorch pull request #119726
Opened 2024-02-12 23:05 UTC by andrewor14

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #119726
* #119725

Summary: This commit adds the `model_is_exported` util function
for users to be able to easily tell what APIs to call to move
their models between train and eval modes. This has the
additional advantage of hiding the implementation of how we
detect a model is exported, in case the metadata format changes
in the future.

Test Plan:
python test/test_quantization.py TestQuantizePT2E.test_model_is_exported

2024-02-13 01:33 UTC, tugsbayasgalan approved these changes

2024-02-14 20:16 UTC, andrewor14 commented
@pytorchbot rebase

2024-02-15 16:00 UTC, andrewor14 commented
@andrewor14 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D53812972).

2024-02-15 16:01 UTC, andrewor14 commented
@pytorchbot merge

2024-02-15 16:36 UTC, albanD requested changes

2024-02-15 16:36 UTC, albanD commented on docs/source/conf.py
> +    "model_is_exported",
Adding new entries in this file is not ok.
Please properly document this API so that it appears properly on the website. Or make it private

2024-02-15 21:53 UTC, andrewor14 commented
@andrewor14 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D53812972).

2024-02-16 03:33 UTC, andrewor14 commented
@andrewor14 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D53812972).

2024-02-16 15:47 UTC, andrewor14 commented
@andrewor14 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D53812972).

2024-02-16 19:26 UTC, albanD approved these changes
SGTM!
Thanks for the update

2024-02-16 19:27 UTC, andrewor14 commented
@pytorchbot merge

2024-02-16 19:29 UTC, closed without merging