update threshold for fft.hff2
pytorch/pytorch pull request #119940
Opened 2024-02-14 23:54 UTC by tinglvv

Similar error and fix referring to https://github.com/pytorch/pytorch/pull/81416

cc @Aidyn-A @eqy @ptrblck

2024-02-15 00:05 UTC, eqy approved these changes

2024-02-15 05:43 UTC, tinglvv commented
@pytorchmergebot merge

2024-02-29 23:27 UTC, malfet requested changes
Please change the PR title (as you are not updating the limits but rather constrain inputs to [-1, 1] range)

Also, if this is only needed for half precision types, do you mind guarding this constraint behind `is_fp16_or_chalf` condition?

2024-03-02 00:00 UTC, Aidyn-A commented
> Also, if this is only needed for half precision types, do you mind guarding this constraint behind is_fp16_or_chalf condition?

It is already in `else` statement of  `if not is_fp16_or_chalf`:
https://github.com/pytorch/pytorch/blob/0a38a6ac8046e4d3f9cfaba86b7ec6517038646f/torch/testing/_internal/opinfo/core.py#L2470-L2474




> And wouldn't it be better to indeed adjust thresholds rather than inputs? Or does it needs input.mean() to be close to zero?

The decision towards [-1, 1] range was made upon the comment https://github.com/pytorch/pytorch/pull/81416#discussion_r921369845. Indeed, with large thresholds we may miss the real numerical degradation or data corruption.

2024-05-02 21:58 UTC, Aidyn-A commented
@pytorchbot rebase

2024-05-06 23:37 UTC, eqy commented
@pytorchmergebot merge

2024-06-06 00:48 UTC, closed without merging