Masked scale meta function registration
pytorch/pytorch pull request #119984
Opened 2024-02-15 11:05 UTC by satheeshhab

Fixes #119983

2024-02-16 08:50 UTC, satheeshhab commented
Can this be reviewed please?

2024-02-20 01:35 UTC, soulitzer commented on torch/_meta_registrations.py
> +def _masked_scale(self, mask, scale):
```suggestion
def meta__masked_scale(self, mask, scale):
```

2024-02-20 01:36 UTC, soulitzer reviewed
Thanks, this looks good to me
I added a small comment

2024-02-20 06:01 UTC, satheeshhab commented
Updated patch based on review comment from @soulitzer

2024-02-20 06:06 UTC, Dalian991 commented
-- 
Adrian Rosales

From: Jeffrey Wan ***@***.***> ***@***.***>
Reply: pytorch/pytorch
***@***.***>
***@***.***>
Date: February 19, 2024 at 8:35:19 PM
To: pytorch/pytorch ***@***.***>
***@***.***>
CC: Subscribed ***@***.***>
***@***.***>
Subject:  Re: [pytorch/pytorch] Masked scale meta function registration (PR
#119984)

***@***.**** commented on this pull request.
> ------------------------------
>
> In torch/_meta_registrations.py
> <https://github.com/pytorch/pytorch/pull/119984#discussion_r1495140748>:
>
> > @@ -3796,6 +3796,12 @@ def meta_masked_scatter_backward(self, mask, sizes):
>      return self.new_empty(sizes)
>
>
> ***@***.***_meta(aten._masked_scale.default)
> +def _masked_scale(self, mask, scale):
>
> ⬇️ Suggested change
>
> -def _masked_scale(self, mask, scale):
> +def meta__masked_scale(self, mask, scale):
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pytorch/pytorch/pull/119984#pullrequestreview-1889353693>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCE3BLKKO3EXVUM3I6J32ODYUP4VPAVCNFSM6AAAAABDKBKLFSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBZGM2TGNRZGM>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-02-20 06:07 UTC, Dalian991 commented
-- 
Adrian Rosales

From: satheeshhab ***@***.***> ***@***.***>
Reply: pytorch/pytorch
***@***.***>
***@***.***>
Date: February 20, 2024 at 1:01:56 AM
To: pytorch/pytorch ***@***.***>
***@***.***>
CC: Subscribed ***@***.***>
***@***.***>
Subject:  Re: [pytorch/pytorch] Masked scale meta function registration (PR
#119984)

Updated patch based on review comment from @soulitzer
> <https://github.com/soulitzer>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pytorch/pytorch/pull/119984#issuecomment-1953539597>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCE3BLP7LQD42Q5RE2ONH4DYUQ35JAVCNFSM6AAAAABDKBKLFSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNJTGUZTSNJZG4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-02-20 17:09 UTC, soulitzer approved these changes
Thanks for the update

2024-02-20 17:09 UTC, soulitzer commented
@pytorchbot merge

2024-02-20 17:12 UTC, soulitzer commented
@pytorchbot merge

2024-02-20 20:22 UTC, soulitzer commented
@pytorchbot rebase

2024-02-20 22:37 UTC, soulitzer commented
Whoops, looks like it wasn't able to automatically rebase. Do you mind doing the rebase manually and force pushing?

2024-02-20 22:38 UTC, soulitzer commented
@pytorchbot rebase --help

2024-02-20 22:39 UTC, soulitzer commented
@pytorchbot rebase -b main

2024-02-20 22:43 UTC, soulitzer commented
@pytorchbot merge

2024-02-21 15:43 UTC, soulitzer commented
It means your change, by side-effect, might have fixed something that previously failed, e.g. some logic in quantization depends on the masked scale function is now able to be compiled. The test suite asserts that it is failing to make sure the state is being explicitly tracked. You should update dynamo_test_failures.py to remove the tests that are now passing from the list of tests expected to fail.

2024-02-21 15:54 UTC, soulitzer commented
Hmm actually this might be a preexisting, failure. https://github.com/pytorch/pytorch/pull/120271 should fix it.

2024-02-22 03:13 UTC, satheeshhab commented
ok, will wait for #120271 to come in

2024-02-22 15:01 UTC, zou3519 reviewed
can you add a test please?

2024-02-23 08:52 UTC, satheeshhab commented
@zou3519 - We actually encountered this while testing masked_scale with dynamic=True set on Habana "hpu" backend. The test used looks like the following and I am guessing that this can probably be adapted for other dummy test backends too.

def test_masked_scale():
    def fn(input, mask, val):
        t1 = torch.add(input, 1)
        t2 = torch.relu(t1)
        t3 = torch._masked_scale(t2, mask, val)
        t4 = torch.sub(t3, 1)
        t5 = torch.relu(t4)
        return t5

    input = torch.randn((3, 4))
    mask = torch.randn((3, 4)) > 0.5
    val = 100.0
    h_input = input.to("hpu")
    h_mask = mask.to("hpu")
    # HPU
    compiled_fn = torch.compile(fn, backend="aot_hpu_training_backend", dynamic=True)
    hresult = compiled_fn(h_input, h_mask, val)

2024-02-27 07:12 UTC, satheeshhab commented
@zou3519 @soulitzer - is there still a problem with this change?

2024-03-04 17:43 UTC, peterbell10 requested changes

2024-03-04 17:43 UTC, peterbell10 commented on torch/_meta_registrations.py
> +    masked_scale = self.new_empty(self.size())
This should be created with `memory_format=utils.suggest_memory_format(self)`.

You also need to rebase to fix some of the flaky tests, but many are genuine test failures caused by tests marked as xfail passing.  You need to update the xfails.

2024-03-06 15:37 UTC, peterbell10 commented on torch/_meta_registrations.py
> +    masked_scale = self.new_empty(self.size())
You still need to fix the xpasses.

2024-06-04 06:09 UTC, closed without merging