[dynamo][guards-cpp-refactor] NO_TENSOR_ALIASING guard
pytorch/pytorch pull request #120065
Opened 2024-02-16 06:37 UTC by anijain2305

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-02-16 22:55 UTC, jansel requested changes

2024-02-16 22:55 UTC, jansel commented on torch/csrc/dynamo/guards.cpp
> +        _tensor_names(tensor_names) {}
Call `unique_tensors.reseve(_num_tensors)`

2024-02-18 06:36 UTC, anijain2305 commented on torch/csrc/dynamo/guards.cpp
> +        _tensor_names(tensor_names) {}
Done.

2024-02-18 23:01 UTC, jansel approved these changes

2024-02-20 18:26 UTC, jansel requested changes

2024-02-20 18:26 UTC, jansel commented on torch/csrc/dynamo/guards.cpp
> +      reset_state();
You should avoid the virtual method call here for slightly better performance.  I think you can use `final` for this.

2024-02-20 19:10 UTC, anijain2305 commented
@jansel Ready for another review.

2024-02-20 19:23 UTC, jansel approved these changes

2024-02-21 17:56 UTC, closed without merging