[dtensor] add torchrec row-wise sharding example
pytorch/pytorch pull request #120260
Opened 2024-02-20 23:37 UTC by XilunWu

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-02-21 01:20 UTC, wanchaol requested changes
These are not like tests but rather examples, please put them under `torch/distributed/_tensor/examples/torchrec_sharding_example.py`

2024-02-21 01:59 UTC, wanchaol commented on test/distributed/_tensor/test_dtensor_sharding.py
> +        dtensor = distribute_tensor(
DTensor.from_local

2024-02-21 02:02 UTC, wanchaol commented on test/distributed/_tensor/test_dtensor_sharding.py
> +        splice_result = row_wise_sharding_placements[0]._split_tensor(
no private API should be exposed

2024-02-21 02:13 UTC, XilunWu commented
we want to show:
1) DTensor sharding in load state dict pre hook
2) DTensor copy in load state dict
3) DTensor construction in _initialize_torch_state()

2024-02-26 23:58 UTC, wanchaol reviewed
Looks much better! please see inlined comments

2024-02-26 23:58 UTC, wanchaol commented on torch/distributed/_tensor/examples/torchrec_sharding_example.py
> +    os.environ["MASTER_ADDR"] = "localhost"
if we use torchrun directly we don't need to setup those environments at all (from L138 - L146)

2024-02-26 23:58 UTC, wanchaol commented on torch/distributed/_tensor/examples/torchrec_sharding_example.py
> +    global_ranks = torch.arange(world_size)
I don't see we are using `global_ranks` anywhere?

2024-02-26 23:58 UTC, wanchaol commented on torch/distributed/_tensor/examples/torchrec_sharding_example.py
> +        visualize_sharding(dtensor)
I think we can enhance visualize_sharding to only do printing on rank 0 by default, instead of doing it on user code.

2024-02-26 23:58 UTC, wanchaol commented on torch/distributed/_tensor/examples/torchrec_sharding_example.py
> +    assert torch.equal(local_shard_spliced, local_shard_spliced)
hmmm here you are comparing the same thing with itself?

2024-03-06 01:30 UTC, wanchaol approved these changes
lgtm

2024-03-06 01:30 UTC, wanchaol commented on torch/distributed/_tensor/examples/torchrec_sharding_example.py
> +        dtensor, prompt="DTensor's sharding be-like in row-wise sharding:"
```suggestion
        dtensor, prompt="Row-wise sharding example in DTensor"
```

2024-03-07 04:50 UTC, closed without merging