Wangjiangben hw pass device str
pytorch/pytorch pull request #120202
Opened 2024-02-19 13:35 UTC by wangjiangben-hw

Fixes #ISSUE_NUMBER

2024-02-19 16:08 UTC, jansel requested changes
What happens if a graph contains a mix of devices?  For example CPU +CUDA?  Two GPUs?

2024-02-20 03:10 UTC, wangjiangben-hw commented
> What happens if a graph contains a mix of devices? For example CPU +CUDA? Two GPUs?

Currently, Triton is also developing multiple backends. We can see that XPU and CPU are preparing for related matters, https://github.com/openai/triton/pull/2551. The modification here is only to align the input parameters with "device_type" in triton_meta. This ensures that the triton function correctly transfers parameters during compilation.

2024-02-20 03:18 UTC, wangjiangben-hw commented on torch/_inductor/codegen/triton.py
> +            compile_wrapper.writeline(f"''', device_str='{V.graph.scheduler.current_device.type}')")
For GPU, yes, it is always cuda. 
If triton supports other devices in the future, the parameter may be incorrect.
I modified it like this, for the cuda device, there will be no change, just to supplement the parameters to be passed down.

2024-02-20 03:41 UTC, jansel approved these changes

2024-02-20 06:14 UTC, wangjiangben-hw commented
@pytorchbot merge

2024-02-20 06:16 UTC, wangjiangben-hw commented
@pytorchbot label "topic: not user facing"

2024-02-20 06:18 UTC, wangjiangben-hw commented
@pytorchbot merge

2024-02-20 06:33 UTC, wangjiangben-hw commented
@pytorchbot merge

2024-02-21 03:49 UTC, closed without merging