prevent logging from within Tensor.__repr__ from infinite recursion
pytorch/pytorch pull request #120206
Opened 2024-02-19 17:57 UTC by aorenste

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #118192
* __->__ #120206

2024-02-19 20:08 UTC, oulgen commented on torch/_tensor.py
> +        _in_recursive_repr = getattr(self, "_in_recursive_repr", 0)
why do you need to count here, seems like a boolean would have been enough?

2024-02-19 20:08 UTC, oulgen commented on torch/_tensor.py
> +            self._in_recursive_repr = _in_recursive_repr
not sure i follow why you need the try finally? if any of this throws an exception, then the repr results wont be important anyway?

2024-02-19 20:08 UTC, oulgen commented on torch/_tensor.py
> +        finally:
shouldn't you unset this attr after the result is determined? otherwise the user can observe it

2024-02-23 05:39 UTC, yanboliang approved these changes

2024-02-25 11:03 UTC, pearu requested changes
This PR does not fix the underlying reason for the infinite recursion within `repr` and it introduces a "recursive tensor" concept that meaning does not apply to the tensors used in the reproducer of the issue.

Considering the traceback of the infinite recursion exception, I think the cause of the underlying problem lies in
https://github.com/pytorch/pytorch/blob/834c7a1d3ea07878ad87d127ee28606fc140b552/torch/_subclasses/fake_tensor.py#L1203
that calls `repr` within `repr` call.

Here's another way to stop the infinite recursion:
```
diff --git a/torch/_subclasses/fake_tensor.py b/torch/_subclasses/fake_tensor.py
index c3f19a94e50..995e6c2dfff 100644
--- a/torch/_subclasses/fake_tensor.py
+++ b/torch/_subclasses/fake_tensor.py
@@ -1200,8 +1200,15 @@ class FakeTensorMode(TorchDispatchMode):
 
     def dispatch(self, func, types, args=(), kwargs=None):
         kwargs = kwargs or {}
-        log.debug("%s %s %s", func, args, kwargs)
 
+        # Some attribute queries that can be serviced directly
+        # See Note [is_coalesced is dispatched]
+        if func in _DISPATCH_HANDLE_DIRECTLY:
+            # NB: no_dispatch is ok here too, this func is very simple
+            with in_kernel_invocation_manager(self):
+                return func(*args, **kwargs)
+
+        log.debug("%s %s %s", func, args, kwargs)
         if func in _DISPATCH_META_HANDLERS:
             return _DISPATCH_META_HANDLERS[func](args)
 
@@ -1787,6 +1794,8 @@ _DISPATCH_HANDLE_DIRECTLY = ordered_set(
     torch.ops.aten.is_coalesced.default,
     torch.ops.aten.dense_dim.default,
     torch.ops.aten.sparse_dim.default,
+    torch.ops.aten._indices.default,
+    torch.ops.aten._values.default,
 )
```

However, ideally, there should be a way to break the recursive dispatch calls that is initiated by the call path `repr(coo)->coo._indices()->...->log.debug(..., coo)->repr(coo)->...`. Can you find it?

2024-02-27 00:51 UTC, aorenste commented
Hey - thanks for the feedback!

> This PR does not fix the underlying reason for the infinite recursion within `repr` and it introduces a "recursive tensor" concept that meaning does not apply to the tensors used in the reproducer of the issue.

I was purposely not trying to fix the underlying reason but rather trying a "bigger hammer" to make sure that other code that has the same problem (logging a tensor from within that tensor's `__repr__`) doesn't infinitely recurse either.  But I can see that that's not necessarily a good solution.

> Considering the traceback of the infinite recursion exception, I think the cause of the underlying problem lies in

Correct - I alluded to this in the summary where I said that it was recursive logging that was the problem.

> Here's another way to stop the infinite recursion:

This makes sense.

> However, ideally, there should be a way to break the recursive dispatch calls that is initiated by the call path `repr(coo)->coo._indices()->...->log.debug(..., coo)->repr(coo)->...`. Can you find it?

I can't tell if you know another way and are challenging me to find it or if you're just not sure and are asking. I'm pretty new to the codebase so I'm pretty unfamiliar with many of the options the code can take.  As far as I can tell the ways to break the recursion would be:
1. detect the recursion and return early (which is what this diff originally does)
2. dispatch the indices call before the log (what you suggested above)
3. do something else that causes us to not call the dispatcher - either calling aten._indices() directly or something that defeats the override? But I'm not sure what that would be.
4. Log `args[1:]` instead of `args` assuming that it's going to be `self` (or possible do an `is` check for that possibility)

2024-02-28 08:04 UTC, pearu requested changes
> I can't tell if you know another way and are challenging me to find it or if you're just not sure and are asking.

It is a combination of all the above because I vaguely remembered that there is a way to do that:) Here is the answer:
```
diff --git a/torch/_subclasses/fake_tensor.py b/torch/_subclasses/fake_tensor.py
index 9d2b38f40fe..6a9a4ea27f3 100644
--- a/torch/_subclasses/fake_tensor.py
+++ b/torch/_subclasses/fake_tensor.py
@@ -1184,7 +1184,8 @@ class FakeTensorMode(TorchDispatchMode):
 
     def dispatch(self, func, types, args=(), kwargs=None):
         kwargs = kwargs or {}
-        log.debug("%s %s %s", func, args, kwargs)
+        with no_dispatch():
+            log.debug("%s %s %s", func, args, kwargs)
 
         if func in _DISPATCH_META_HANDLERS:
             return _DISPATCH_META_HANDLERS[func](args)
```
and there is not need to add `_indices`/`_values` to `_DISPATCH_HANDLE_DIRECTLY` set.

2024-02-28 17:23 UTC, pearu approved these changes
LGTM! Thanks, @aorenste!

2024-03-06 23:36 UTC, aorenste commented
@pytorchbot merge

2024-03-07 02:24 UTC, closed without merging