symbolic_shapes.py extra variants
pytorch/pytorch pull request #120313
Opened 2024-02-21 13:37 UTC by mingxzhao

Fixes #119969

Adds extra variants for sympy.Lt

2024-02-23 19:36 UTC, ezyang commented
A test would be nice

2024-02-23 19:50 UTC, ezyang commented on torch/fx/experimental/symbolic_shapes.py
> +                    subst[sympy.Le(-e.lhs, -e.rhs)] = sympy.true
If `a < b`, then it is NOT true that `-a < -b`, indeed, you need to flip the inequality

2024-02-23 19:51 UTC, ezyang requested changes
seems wrong

2024-02-27 16:26 UTC, lezcano reviewed
There are a number of equations still missing

2024-02-27 16:26 UTC, lezcano commented on torch/fx/experimental/symbolic_shapes.py
> +                    subst[sympy.Gt(e.lhs, e.rhs)] = sympy.false
The canonicalised expressions do not have `Gt`, so this is unnecessary

2024-02-27 16:26 UTC, lezcano commented on torch/fx/experimental/symbolic_shapes.py
> +                    subst[sympy.Lt(e.lhs, e.rhs)] = sympy.true
This is already added above

2024-02-27 16:26 UTC, lezcano commented on torch/fx/experimental/symbolic_shapes.py
> +                    subst[sympy.Ge(e.lhs, e.rhs)] = sympy.false
Same as Gt

2024-02-27 16:26 UTC, lezcano commented on torch/fx/experimental/symbolic_shapes.py
> +                    subst[sympy.Ne(e.lhs, e.rhs)] = sympy.true
We should probably canonicalise `Ne` into `Or(Lt(a,b), Lt(b, a))`, but I guess this is fine for now.

2024-02-27 16:27 UTC, lezcano commented
It's still missing a test.

2024-02-27 16:31 UTC, mingxzhao commented
Yes apologies, working on test soon. Just wanted to resolve the comment, not quite ready for review yet.

2024-03-28 12:51 UTC, closed without merging