[dynamo][guards-cpp-refactor] DICT_VERSION guard
pytorch/pytorch pull request #120416
Opened 2024-02-22 18:05 UTC by anijain2305

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-02-22 18:07 UTC, anijain2305 commented
@jansel I am bringing this back for now. We can remove this once we improve the `DictGuardManager` to rely on the fast path of tags. Removing this later is pretty easy.

2024-02-23 05:35 UTC, jansel requested changes

2024-02-23 05:35 UTC, jansel commented on torch/csrc/dynamo/guards.cpp
> +    return PyDict_Check(value) && get_dict_version(value) == _tag;
Is it safe to use this?  Didn't it bite us before?

I was expecting this to be a fast-path with a fallback.

2024-02-25 20:29 UTC, jansel approved these changes

2024-02-25 21:41 UTC, anijain2305 commented
@pytorchbot merge

2024-02-25 23:21 UTC, anijain2305 commented
@pytorchbot merge -f "unrelated CI failure"

2024-02-25 23:24 UTC, closed without merging