Optionally use hipblaslt
pytorch/pytorch pull request #120551
Opened 2024-02-24 12:34 UTC by trixirt

The hipblaslt package is not available on Fedora.
Instead of requiring the package, make it optional. If it is found, define the preprocessor variable HIPBLASLT Convert the checks for ROCM_VERSION >= 507000 to HIPBLASLT checks

Fixes #119081

2024-02-28 23:42 UTC, jeffdaily commented
@xw285cornell would appreciate your review of this.  I'm assuming this PR will break your internal build?

2024-03-02 12:28 UTC, trixirt commented
Update for a couple more hipblaslt usages that were added in main this week.

2024-04-26 18:23 UTC, FelixSchwarz commented
This PR looks pretty straight forward and using a variable instead of "magic" version numbers seem to be much cleaner. It would be nice if this PR wouldn't linger around much longer.

2024-04-26 22:38 UTC, jeffdaily commented
@trixirt I am in favor of this PR. My apologies for adding yet more exposure to hipblaslt APIs that you need to work around again.  Please resolve conflicts likely due to https://github.com/pytorch/pytorch/pull/122106.

2024-05-30 23:03 UTC, jithunnair-amd requested changes
Suggest `USE_HIPBLASLT` instead of `HIPBLASLT` as name for define

2024-06-10 17:06 UTC, xw285cornell commented
Sorry just see this. Thanks @jeffdaily for pinging, this will break our internal codebase but it should be an easy fix. I'm not objecting the idea, if you can ping me before this PR lands, I can put a fix to our internal system easily.

2024-07-01 20:14 UTC, jithunnair-amd approved these changes

2024-07-01 20:24 UTC, jithunnair-amd commented
@trixirt Please resolve conflicts and I'll request an upstream maintainer to approve.

2024-07-01 20:44 UTC, jithunnair-amd commented
> Suggest `USE_HIPBLASLT` instead of `HIPBLASLT` as name for define

@trixirt Please do consider this renaming to be aligned with current naming

2024-07-01 22:24 UTC, trixirt commented
I am working on this.  Its a bit involved and in a parallel track i trying to get hipblastlt to build on Fedora.

2024-07-02 20:51 UTC, malfet approved these changes
LGTM

2024-07-04 15:51 UTC, trixirt commented
I have submitted the hipBLASLt package for Fedora here
[hipBLASLt package review
](https://bugzilla.redhat.com/show_bug.cgi?id=2295820)

A prelim refactoring of the above change is here[refactored for 2.4
](https://src.fedoraproject.org/rpms/python-torch/blob/rawhide/f/next/0001-Optionally-use-hipblaslt.patch)

Fedora/My preference is to use the package once it is available.

2024-07-20 18:16 UTC, AngryLoki commented
@trixirt , could you fix git conflict, please? I'd like to see this patch merged

2024-07-24 23:27 UTC, trixirt commented
@AngryLoki 
This is not really fixing a merge conflict, the base code changed out for under the original patch.
I am more in favor of having hipblaslt packaged than having to rebase the patch.
If I refactor this patch for 2.4, can I also help you package up hipblaslt in gentoo or your favorite distro ?

2024-07-25 09:31 UTC, AngryLoki commented
> If I refactor this patch for 2.4, can I also help you package up hipblaslt in gentoo or your favorite distro ?

Yes, please. For 2.3.x I will add current patch ([with USE_HIPBLASLT cmake flag](https://github.com/AngryLoki/gentoo/blob/c369eb4d1fe358de2acc64e34c33181a7c9c7058/sci-libs/caffe2/files/caffe2-2.3.0-optional-hipblaslt.patch)), but in next versions I'd like to see it in upstream.

2024-07-25 09:38 UTC, IMbackK commented
> @trixirt , could you fix git conflict, please? I'd like to see this patch merged

the problem is that this patch is not just required to support distros that dont want to package hipblaslt but also because hipblaslt has a bug steming from a missunderstanding how the rocm runtime works that subtly breaks (or crashes, depends on if assertions in the runtime are enabled) all systems with gpus that dont support hipblaslt when a binary is run that links against it.

2024-07-29 21:40 UTC, pruthvistony commented
@trixirt ,
I have moved the PR to draft since it is NOT yet ready for review, please move it out of draft when the PR is ready for review and CI is green. Thank you.

2024-08-09 11:24 UTC, AngryLoki commented
> If I refactor this patch for 2.4, can I also help you package up hipblaslt in gentoo or your favorite distro ?

@trixirt , hi again. I tried to update this patch myself and now I understand what do you mean by "the base code changed". I think it is too difficult to do it now, so I packaged pytorch-2.4.0 with required hipblaslt (but it is still possible to build hipblaslt with 0 gpus). Feel free to close this PR if you don't need it anymore.

2024-08-14 15:19 UTC, trixirt commented
> > If I refactor this patch for 2.4, can I also help you package up hipblaslt in gentoo or your favorite distro ?
> 
> @trixirt , hi again. I tried to update this patch myself and now I understand what do you mean by "the base code changed". I think it is too difficult to do it now, so I packaged pytorch-2.4.0 with required hipblaslt (but it is still possible to build hipblaslt with 0 gpus). Feel free to close this PR if you don't need it anymore.

Fedora has hipblaslt now with 1 gpu (WEEEE) .. so closing

2024-08-14 15:19 UTC, closed without merging