enable complex128 in test_addmm_sizes_all_sparse_csr for rocm for trivial (k,n,m) cases
pytorch/pytorch pull request #120504
Opened 2024-02-23 18:08 UTC by dnikolaev-amd

This PR enables `test_addmm_sizes_all_sparse_csr_k_*_n_*_m_*_cuda_complex128` for ROCm for trivial cases  (m or n or k = 0)

CUSPARSE_SPMM_COMPLEX128_SUPPORTED also used for `test_addmm_all_sparse_csr` and ` test_sparse_matmul` and both of them are skipped for ROCm by `@skipIfRocm` or `@skipCUDAIf(not _check_cusparse_spgemm_available())`

cc: @jithunnair-amd

2024-02-26 15:35 UTC, dnikolaev-amd commented
@pytorchbot rebase

2024-02-26 19:04 UTC, pruthvistony requested changes

2024-02-26 19:04 UTC, pruthvistony commented on test/test_sparse.py
> +) or (not IS_WINDOWS)
Can you please update this condition to check for torch.version.hip for 6.0.0 on ROCm.

2024-02-27 20:56 UTC, dnikolaev-amd commented
@pytorchbot rebase

2024-02-28 15:58 UTC, dnikolaev-amd commented
@pytorchbot rebase

2024-02-29 22:47 UTC, dnikolaev-amd commented
from ROCm job status artifacts
Enabled 19 tests total

https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/8098575107/1/artifact/test-reports-test-default-1-6-linux.rocm.gpu.2_22133823040.zip

```xml
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_0_n_0_m_0_cuda_complex128" time="0.087" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_0_n_0_m_25_cuda_complex128" time="0.011" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_0_n_1_m_1_cuda_complex128" time="0.306" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_1_n_0_m_0_cuda_complex128" time="0.011" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_1_n_10_m_0_cuda_complex128" time="0.011" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_1_n_1_m_0_cuda_complex128" time="0.011" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_8_n_0_m_1_cuda_complex128" time="0.011" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_8_n_10_m_0_cuda_complex128" time="0.011" file="test_sparse_csr.py" />
```

https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/8098575107/1/artifact/test-jsons-test-default-2-6-linux.rocm.gpu.2_22133823352.zip
```xml
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_0_n_0_m_1_cuda_complex128" time="0.011" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_0_n_10_m_0_cuda_complex128" time="0.011" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_0_n_10_m_1_cuda_complex128" time="0.302" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_0_n_10_m_25_cuda_complex128" time="0.012" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_0_n_1_m_0_cuda_complex128" time="0.011" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_0_n_1_m_25_cuda_complex128" time="0.012" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_1_n_0_m_1_cuda_complex128" time="0.010" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_1_n_0_m_25_cuda_complex128" time="0.010" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_8_n_0_m_0_cuda_complex128" time="0.010" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_8_n_0_m_25_cuda_complex128" time="0.010" file="test_sparse_csr.py" />
<testcase classname="TestSparseCSRCUDA" name="test_addmm_sizes_all_sparse_csr_k_8_n_1_m_0_cuda_complex128" time="0.011" file="test_sparse_csr.py" />
```

2024-03-04 15:03 UTC, dnikolaev-amd commented
@pytorchbot rebase

2024-03-05 18:47 UTC, dnikolaev-amd commented
@pytorchbot rebase

2024-03-06 16:52 UTC, dnikolaev-amd commented
All tests passed. 19 tests enabled for ROCm https://github.com/pytorch/pytorch/pull/120504#issuecomment-1972101794

2024-03-06 16:57 UTC, jithunnair-amd approved these changes

2024-03-06 16:58 UTC, jithunnair-amd commented
@malfet Please review and merge this PR, it's enabling some trivial cases for sparse unit tests for ROCm6.0 and above. CI passed: https://github.com/pytorch/pytorch/pull/120504#issuecomment-1981342639

2024-03-08 12:42 UTC, dnikolaev-amd commented
@pytorchbot rebase

2024-03-11 13:23 UTC, dnikolaev-amd commented
@pytorchbot rebase

2024-03-12 04:34 UTC, ezyang approved these changes

2024-03-12 04:34 UTC, ezyang commented
@pytorchbot merge

2024-03-12 07:30 UTC, closed without merging