[Not for land] Update onednn to latest rls v3.3
pytorch/pytorch pull request #120767
Opened 2024-02-28 03:16 UTC by Xia-Weiwen

2024-03-01 03:55 UTC, chuanqi129 approved these changes

2024-03-01 08:56 UTC, jgong5 approved these changes

2024-03-04 19:44 UTC, atalman commented
@Xia-Weiwen @jgong5 Please note here is the currently list of OneDNN regressions:  https://github.com/pytorch/pytorch/issues/121150

2024-03-04 21:33 UTC, malfet commented
@Xia-Weiwen unrelated to the above, can you please you markup instead of screenshots to represent perf gains, i.e. use something like:

| Test name | Geomean speedup|
| ------------- | ------------- |
| eager_throughput_bf16_eager | 1.0018 |
| eager_throughput_fp32_eager  | 1.00025 |

...

2024-03-05 01:06 UTC, Xia-Weiwen commented
> @Xia-Weiwen unrelated to the above, can you please you markup instead of screenshots to represent perf gains, i.e. use something like:
> 
> Test name	Geomean speedup
> eager_throughput_bf16_eager	1.0018
> eager_throughput_fp32_eager	1.00025
> ...

Sure. I have updated.

2024-03-05 15:20 UTC, malfet requested changes
This update likely fixes number of regressions, but completely lacks any testing, so nothing prevents one from re-introducing the same regressions during the next update. Please add tests for functional regressions to this PR

2024-03-06 08:40 UTC, Xia-Weiwen commented
> This update likely fixes number of regressions, but completely lacks any testing, so nothing prevents one from re-introducing the same regressions during the next update. Please add tests for functional regressions to this PR

Thanks. I have added test cases for functionality issues listed above.

2024-03-06 17:19 UTC, malfet commented on test/nn/test_convolution.py
> +            image = torch.rand([1, 1024, 1024, 3], dtype=torch.float32, device=torch.device('cpu'))
Nit
```suggestion
            image = torch.rand(1, 1024, 1024, 3)
```

2024-03-07 01:11 UTC, Xia-Weiwen commented on test/nn/test_convolution.py
> +            image = torch.rand([1, 1024, 1024, 3], dtype=torch.float32, device=torch.device('cpu'))
Thanks. It's fixed.

2024-03-08 23:57 UTC, malfet commented
Looks like ARM wheels are green, so let's merge those and see if it will break internal system or some other CI

2024-03-08 23:58 UTC, malfet commented
@pytorchbot merge -i

2024-03-11 12:53 UTC, atalman approved these changes

2024-03-11 12:53 UTC, atalman commented
@pytorchbot merge -f "Everything is green"

2024-03-11 12:57 UTC, closed without merging

2024-03-13 15:43 UTC, malfet commented
I have a question about https://github.com/pytorch/builder/pull/1716 and https://github.com/pytorch/builder/pull/1717

Why those changes are not part of the release?

2024-03-13 18:27 UTC, vpirogov commented
@snadampal, please open PR with cherry picked changes in oneDNN repo targeting rls-v3.3 branch. I'll have v3.3.6 tagged as soon as all changes required for Pytorch land. Anything else we need besides https://github.com/oneapi-src/oneDNN/pull/1768?

2024-03-13 18:53 UTC, malfet commented
@vpirogov thank you for the prompt reply. Let me create a cherry-pick for xbyak change (another ARM related one), but first check if those changes are in trunk already

2024-03-13 19:07 UTC, snadampal commented
@vpirogov , thank you, will create it right away.

2024-03-13 19:53 UTC, atalman commented
@vpirogov @malfet Should we update this way 3.3.2 oneDNN release with this patch :
https://github.com/oneapi-src/oneDNN/commit/bbaec145f8c64818fd5c3ed2cb9e2ae69daef887
To fix this issue: 
https://github.com/pytorch/pytorch/issues/120547

We are having exactly same situation in patch release 2.2.2

2024-03-13 20:00 UTC, malfet commented
> Should we update this way 3.3.2 oneDNN release with this patch : [oneapi-src/oneDNN@bbaec14](https://github.com/oneapi-src/oneDNN/commit/bbaec145f8c64818fd5c3ed2cb9e2ae69daef887) To fix this issue: #120547


@atalman alas, there are no 3.3.2 vs 3.3.5 branches, so no, it's not possible, we need to do the patching for binary builds to fix that issue

2024-03-13 20:08 UTC, vpirogov commented
@malfet, rls-v3.3 is used to tag patch releases and includes only bug fixes. This should be safe mechanism to pick up bug fixes when updating oneDNN version in Pytorch.

2024-03-13 20:16 UTC, atalman commented
@vpirogov @malfet In this case should we consider moving to oneDNN 3.3.5 with all the fixes for 2.2.2 release ? There are about ~20 cherry-picks difference I see between 3.3.5 and 3.3.2 release.  This way we can totally avoid having oneDNN patches like above.

2024-03-13 20:25 UTC, vpirogov commented
@atalman, oneDNN 3.3.5 is already tagged and will not change. We should consider adding all the necessary fixes to rls-v3.3 branch and updating Pytorch to oneDNN v3.3.6.

2024-03-13 20:29 UTC, snadampal commented
@vpirogov , here is the cherrypick PR for rls-v3.3: https://github.com/oneapi-src/oneDNN/pull/1831

2024-03-13 20:30 UTC, atalman commented
@vpirogov This is clear. Hence we will have to : 
- Land it in main
- Cherry-pick into release 2.3 branch
I am proposing to cherry-pick it in 2.2 branch at the same time

2024-03-13 23:48 UTC, vpirogov commented
@atalman, I'm not intimately familiar with Pytorch branch management, but it sounds reasonable.

https://github.com/oneapi-src/oneDNN/pull/1831 has landed. If anything else is needed in oneDNN v3.3.6 please open PRs to rls-v3.3. Otherwise I'm ready to tag the patch.

2024-03-14 02:05 UTC, Xia-Weiwen commented
Hi @snadampal @atalman @malfet I am trying to figure out what we need to do next on our side. Looks like we need to
- wait for all patches related to aarch64 issues landed in oneDNN rls-v3.3
- wait for oneDNN v3.3.6 tag & release
- upgrade oneDNN in PyTorch main to v3.3.6

Is that correct?

2024-03-14 03:34 UTC, snadampal commented
Hi @Xia-Weiwen , yes, that's what my understanding.  my PR got merged to rls-v3.3.
@malfet was planning to check the xbyak change whether it can be cherrypicked too.

2024-03-14 03:48 UTC, Xia-Weiwen commented
@snadampal How many patches/PRs are still pending and not landed in oneDNN rls-v3.3? And about the xbyak change you mentioned, will it be cherry-picked to oneDNN or Pytorch itself?

2024-03-14 04:23 UTC, snadampal commented
I was tracking only the onednn#1768 which was landed via onednn#1831. may be @malfet  or @atalman can comment on the other.

2024-03-14 05:00 UTC, Xia-Weiwen commented
Ok. Thanks.
Hi @atalman @malfet Since PT 2.3 branch cut is already done, how shall we upgrade oneDNN for PT 2.3 and PT 2.4? We have planned to upgrade oneDNN to v3.4 for PT 2.4 and we hope the upgrade to v3.4 can be done in PyTorch main branch by this month. Looks like we need to (1) upgrade oneDNN to v3.3.6 in main branch; then (2) cherry-pick it to 2.3 release branch; and finally (3) upgrade oneDNN to v3.4 in main. Do you have any suggestions or comments? Thanks!

2024-03-14 19:19 UTC, atalman commented
@Xia-Weiwen
Yes this is correct:
(1) upgrade oneDNN to v3.3.6 in main branch; then 
(2) cherry-pick it to 2.3 release branch; and finally 
(3) upgrade oneDNN to v3.4 in main.

2024-03-15 01:08 UTC, Xia-Weiwen commented
Hi @snadampal Looks like you are the owner of the second PR (https://github.com/oneapi-src/oneDNN/pull/1773). Will you cherry-pick this to oneDNN rls-v3.3 branch?

2024-03-15 12:52 UTC, snadampal commented
Yes, I raised this https://github.com/oneapi-src/oneDNN/pull/1773 for xbyak sysfs issue, but later I saw the similar fix https://github.com/fujitsu/xbyak_aarch64/pull/96 from @malfet , where he fixed it in the xbyak repo instead of oneDNN. that's why I closed mine.

Hi @Xia-Weiwen , is xbyak upgrade in oneDNN possible now? 

if it not a trivial change for oneDNN 3.3.x branch, I will cherrypick my oneDNN PR, https://github.com/oneapi-src/oneDNN/pull/1773, into oneDNN 3.3 and 3.4 branches.

2024-03-15 13:04 UTC, Guobing-Chen commented
> Yes, I raised this [oneapi-src/oneDNN#1773](https://github.com/oneapi-src/oneDNN/pull/1773) for xbyak sysfs issue, but later I saw the similar fix [fujitsu/xbyak_aarch64#96](https://github.com/fujitsu/xbyak_aarch64/pull/96) from @malfet , where he fixed it in the xbyak repo instead of oneDNN. that's why I closed mine.
> 
> Hi @Xia-Weiwen , is xbyak upgrade in oneDNN possible now?
> 
> if it not a trivial change for oneDNN 3.3.x branch, I will cherrypick my oneDNN PR, [oneapi-src/oneDNN#1773](https://github.com/oneapi-src/oneDNN/pull/1773), into oneDNN 3.3 and 3.4 branches.

@vpirogov to help answer the question of xbyak upgrade in OneDNN.

2024-03-15 16:05 UTC, vpirogov commented
@snadampal, I would avoid upgrading xbyak in the patch release as it adds unnecessary risk. I suggest cherry picking https://github.com/fujitsu/xbyak_aarch64/pull/96 into rls-v3.3 branch. Once this lands I'll have oneDNN v3.3.6 tagged.

2024-03-15 16:14 UTC, snadampal commented
Hi @vpirogov , makes sense, here are the cherrypicked PRs, I did for both rls-v3.3 and rls-v3.4 branches.

https://github.com/oneapi-src/oneDNN/pull/1834
https://github.com/oneapi-src/oneDNN/pull/1835

2024-03-18 15:49 UTC, vpirogov commented
Thanks, @snadampal.

oneDNN [v3.3.6](https://github.com/oneapi-src/oneDNN/releases/tag/v3.3.6) is posted.

2024-03-19 01:21 UTC, Guobing-Chen commented
> Thanks, @snadampal.
> 
> oneDNN [v3.3.6](https://github.com/oneapi-src/oneDNN/releases/tag/v3.3.6) is posted.

@vpirogov, there seems 6 more commits since v3.3.5, with 4 related to AARCH64 and 2 related X64. Just to confirm with you, have OneDNN part done release test for this patch release version? And does the test covers previously escaped regression cases? Especially AARCH64 related.

From our part, we plan to 
1. Submit a new PR for this v3.3.6 version
2. Do a round of test with same scope as previous we tested for OneDNN v3.3.5 upgrade
3. And suppose we also need help from @milpuz01 to validate for AARCH64 also.

Any comments? @malfet and @atalman

2024-03-19 01:25 UTC, Xia-Weiwen commented
Hi. FYI, the PR for oneDNN v3.3.6 upgrade is here: https://github.com/pytorch/pytorch/pull/122164 (under validation)

2024-03-19 06:56 UTC, Guobing-Chen commented
@malfet and @atalman, there is another issue marked by @albanD as for PT 2.3 -- https://github.com/pytorch/pytorch/issues/120982. OneDNN team seems have fixed this issue at main branch. Do you suggest to have this fix included for PT 2.3? If yes, we may need OneDNN team to backport this fix into v3.3 branch and tag a new version.

2024-03-19 20:20 UTC, vpirogov commented
> @vpirogov, there seems 6 more commits since v3.3.5, with 4 related to AARCH64 and 2 related X64. Just to confirm with you, have OneDNN part done release test for this patch release version? And does the test covers previously escaped regression cases? Especially AARCH64 related.

Validation on x64 platforms is complete, no regressions identified. Validation of AArch64 changes was done by @snadampal.