Include a warning in cuda get_allany_iter
pytorch/pytorch pull request #120977
Opened 2024-03-01 07:12 UTC by lancerts

Fixes #120875

The root cause of the discrepancy between CPU and GPU is in this line

https://github.com/pytorch/pytorch/blob/63b259492a8e5519edb45bb34c5b2a275baebf63/aten/src/ATen/native/ReduceOps.cpp#L1536

.

1. torch.all on CPU will explicitly cast everything into bool. However, the cast is done by `Casting complex values to real discards the imaginary part`. Therefore, a pure imaginary number is treated as zero and thus false.
2. torch.all on cuda does dynamical casting, anything non-zero, including pure imaginary numbers treated as True.

2024-03-11 19:17 UTC, lancerts commented
@janeyx99 mind tagging the relevant reviewers? thanks

2024-03-11 19:25 UTC, jbschlosser commented
cc @malfet / @lezcano

2024-03-11 19:28 UTC, lezcano requested changes
This doesn't fix the issue.

2024-03-11 20:20 UTC, jbschlosser commented
@lancerts As specified in the issue, rather than a warning, we'd accept a fix that follows python's bool conversion behavior for complex numbers (i.e. treat `0+0j` as False and everything else as True).

2024-05-10 22:53 UTC, lezcano commented
The relevant issue was fixed at https://github.com/pytorch/pytorch/pull/121803

2024-05-10 22:53 UTC, closed without merging