Add bfloat dispatch for `AT_DISPATCH_FLOATING_TYPES_AND_HALF`
pytorch/pytorch pull request #121087
Opened 2024-03-02 23:20 UTC by bhack

Can we add bfloat in `AT_DISPATCH_FLOATING_TYPES_AND_HALF` ?

2024-03-03 22:08 UTC, eqy reviewed
This is a global change that would affect many kernels and would dramatically increase binary sizes

2024-03-03 23:07 UTC, bhack commented
Is there any other way to dispatch float, half and bfloat?

2024-03-04 03:23 UTC, eqy commented
> Is there any other way to dispatch float, half and bfloat?

`AT_DISPATCH_FLOATING_TYPES_AND2`
see here for an example:
https://github.com/pytorch/pytorch/blob/4b494d075093096d822b9d614e2719a0e821c6af/aten/src/ATen/native/cuda/Lerp.cu#L108

2024-03-04 10:57 UTC, lezcano requested changes
Agreed, we should do this in a per-operator basis as people request it to avoid having a bloated binary.

2024-03-04 19:23 UTC, bhack commented
OK the `AND` it means that they are "extra" over the float baseline.

2024-03-04 19:23 UTC, closed without merging