Add lowerings for  and allow tracing of /
pytorch/pytorch pull request #121354
Opened 2024-03-06 22:43 UTC by amjames

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #121354

2024-03-07 11:12 UTC, lezcano reviewed
This looks like it could work. That being said, it needs some thorough testing (different sizes, strides, and memory inputs)

2024-03-07 11:12 UTC, lezcano commented on torch/_inductor/lowering.py
> +    return resize_(self_, other.get_size(), memory_format=memory_format)
These can be decomp / refs

2024-03-07 11:12 UTC, lezcano commented on torch/_inductor/lowering.py
> +    new_stride = ir.make_contiguous_strides_for(size)
There are relevant helpers in `_prims_common/__init__.py` for all the strides.

2024-03-07 11:12 UTC, lezcano commented on torch/_inductor/lowering.py
> +    new_numel = V.graph.sizevars.evaluate_static_shape(sympy_product(size))
Putting guards unconditionally here is not great. You should do something like `statically_known_equals`.

2024-03-07 16:00 UTC, peterbell10 requested changes

2024-03-07 16:00 UTC, peterbell10 commented on torch/_inductor/lowering.py
> +    x = resize_storage_bytes_(x, new_numel * dtype_item_size)
I don't think these semantics are correct. You resize the storage of `x` but return a new view of it so the tensor `x` itself is not updated. AFAICT the expected behavior is to return a new tensor with new storage.

2024-03-07 16:00 UTC, peterbell10 commented on torch/_inductor/lowering.py
> +    x.data = resize(x, size, memory_format=memory_format).data
I don't see how it's possible to implement `resize_` in terms of `resize`. The expected semantics are that `x.data` (i.e. the storage) is modified but you're actually reassigning it to a new storage.

2024-03-07 16:00 UTC, peterbell10 commented on torch/_inductor/lowering.py
> +    return resize(self_, other.get_size(), memory_format=memory_format)
I believe you need to handle `torch.preserve_format` here, which should take the suggested memory format from `other`.

2024-03-12 23:39 UTC, amjames commented
I am a bit stuck when it comes to the in-place variants. The out-of-place versions are fine, but as soon as I try anything which attempts to impose a new layout on the original input even if the underlying storage is now compatible with that layout something gets upset. 

In order to get the in-place versions working this might need to be handled as a special case somewhere in FakeTensor or Dynamo?

2024-03-13 01:06 UTC, peterbell10 commented on torch/_inductor/lowering.py
> +def resize_(x, size, *, memory_format=None):
I'm not sure exactly what errors you're seeing but you probably need to add the resize ops to this list:
https://github.com/pytorch/pytorch/blob/7d05c4c093ad980d8c73d6af552fd603c321f6d1/torch/_inductor/graph.py#L959-L970

2024-03-13 01:06 UTC, peterbell10 commented on torch/_inductor/lowering.py
> +        as_strided_(pointwise, size, new_strides)
You could use `require_contiguous` or `require_channels_last` here depending on the memory format? Either that or `ir.ExternKernel.require_stride_order` is the preferred method.

2024-03-13 01:06 UTC, peterbell10 commented on torch/_inductor/lowering.py
> +    self_flat = view(self, (-1,))
I think you need to have `unwrap_view` first in case `self` is only viewing a subset of the full storage.

2024-03-13 01:06 UTC, peterbell10 commented on torch/_inductor/lowering.py
> +        return sliced
Out of place version shouldn't return a view

2024-03-13 01:06 UTC, peterbell10 commented on torch/_inductor/lowering.py
> +    mutate_to(x, val)
1. You will need to unwrap_view here as well I think.
2. In the slow path where `mutate_to` actually does a copy, you would need to fallback to `ir.ResizeStorageBytes` instead.

2024-03-13 08:35 UTC, lezcano commented on torch/_inductor/lowering.py
> +>>>>>>> 995e9cae642 (Add lowerings for  and allow tracing of resize/resize_as)
oops

2024-03-15 18:21 UTC, amjames commented on torch/_inductor/ir.py
> -        assert len(self.stride) == len(order)
Didn't mean to leave this in.

2024-03-15 18:22 UTC, amjames commented on torch/_inductor/ir.py
> +    def require_stride_order_for_format(cls, x, format):
Also not needed

2024-03-15 19:37 UTC, amjames commented
@peterbell10 The inplace versions are still having issues in functionalization. 

`resize_as_`: Traceback leads [here](https://github.com/pytorch/pytorch/blob/d04faf4531aa499e0f03bca1c97224e7b2f47b84/torch/_functorch/_aot_autograd/traced_function_transforms.py#L472-L488). The last line is the copy which is actually invoked, but the comment at the top of this section is what gives me pause. 

` # We found an input which has a (data-only) mutation. ` 

This is not the case here as we are also mutating the meta-data, attempting to copy back into the input is invalid. 

`resize_`: They symptom is out of bounds access on `constraint` when producing guards [here](https://github.com/pytorch/pytorch/blob/409b1a6081e9fdbe087f7db9cd2aac45fb34e8be/torch/fx/experimental/symbolic_shapes.py#L3104-L3107). The real cause is not clear to me, but it is not a coincidence that only one `constraint` has been created, but the tensor has 4 dimensions (this is occurring on the first test-input, which resizes `(1, ) -> (1, 3, 2, 3)`.

2024-04-17 00:43 UTC, closed without merging