[BE]: Add tensor to constant comparison test
pytorch/pytorch pull request #121496
Opened 2024-03-08 15:41 UTC by Skylion007

Add additional test of tensor to constant comparisons.

2024-03-08 15:54 UTC, albanD approved these changes
More tests :tada:

2024-03-08 16:03 UTC, Skylion007 commented
@pytorchbot merge

2024-03-08 21:02 UTC, zou3519 commented on test/dynamo/test_functions.py
> +                opt_fn = torch.compile(fullgraph=True)(fn)
Use torch._dynamo.optimize or torch.compile(backend="eager"). This is test/dynamo -- we don't generally run things through all of PT2 stack in tests in this directory.

2024-03-08 21:03 UTC, zou3519 requested changes
See comment

2024-03-18 17:22 UTC, zou3519 approved these changes

2024-06-16 17:33 UTC, closed without merging