Register COLLECTIVE_COMM profiler activity type, if available
pytorch/pytorch pull request #121461
Opened 2024-03-08 00:38 UTC by sanrise

**Summary:**
Instantiate a collective communications profiler. If a collectives profiler exists then add COLLECTIVE_COMM activity type to the CUDA activity types.

**Test Plan:**
Sample output trace (**internal** use only): https://www.internalfb.com/intern/perfdoctor/trace_view?filepath=tree/traces/clientAPI/0/1707520266/devgpu007.pci1/nccl_activities_2643654_1707520266977.json.gz&bucket=gpu_traces

2024-03-08 14:34 UTC, aaronenyeshi approved these changes
Looks good, wondering about the two macros: KINETO_HAS_NCCL_PROFILER and NCCL_PROXY_PROFILER_ENABLED. When are either of them set and what differentiates them? Thanks!

2024-03-08 14:34 UTC, aaronenyeshi commented on torch/csrc/profiler/kineto_shim.cpp
> +  // reord collective names then we can use it here.
```suggestion
  // record collective names then we can use it here.
```

2024-03-09 16:14 UTC, aaronenyeshi approved these changes

2024-03-11 14:48 UTC, aaronenyeshi requested changes
Please check lintrunner failure signal

2024-03-13 02:05 UTC, shengbao-zheng commented
Just curious if we have to wait this until NCCL_PROXY_PROFILER_ENABLED being upstreamed to NCCL? Otherwise looks like we are using a non-public API where some code is not accessible by all PyTorch users?

2024-03-13 02:14 UTC, sanrise commented
> Just curious if we have to wait this until NCCL_PROXY_PROFILER_ENABLED being upstreamed to NCCL? Otherwise looks like we are using a non-public API where some code is not accessible by all PyTorch users?

You make a fair point. I should've actually just used the KINETO_HAS_NCCL_PROFILER macro. 

KINETO_HAS_NCCL_PROFILER is only set when Kineto finds any NCCL profiler on startup, so it essentially wraps NCCL_PROXY_PROFILER_ENABLED; so we can just use that and remove this macro usage.

2024-03-13 03:07 UTC, sanrise commented
@shengbao-zheng I have removed the custom internal API changes to an internal diff at [D54836235] - this one simply registers the correct activity type if Kineto has a NCCL profiler.

2024-03-26 17:27 UTC, aaronenyeshi approved these changes

2024-04-08 18:21 UTC, aaronenyeshi approved these changes
Looks great! merging this now

2024-04-08 18:21 UTC, aaronenyeshi commented
@pytorchbot merge

2024-04-08 18:24 UTC, closed without merging