[inductor] disable linear weight prepacking pass on double
pytorch/pytorch pull request #121478
Opened 2024-03-08 07:05 UTC by blzheng

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-03-14 14:48 UTC, jgong5 requested changes

2024-03-14 14:48 UTC, jgong5 commented on torch/_inductor/fx_passes/mkldnn_fusion.py
> +        if weight_meta_value.dtype == torch.float64:
```suggestion
        if input_meta_value.dtype == torch.float64 or weight_meta_value.dtype == torch.float64:
```

2024-03-15 12:27 UTC, jgong5 approved these changes

2024-03-15 23:09 UTC, desertfire approved these changes

2024-03-16 06:58 UTC, blzheng commented
@pytorchbot merge

2024-03-16 07:03 UTC, blzheng commented
@pytorchbot label "topic: not user facing"

2024-03-16 07:04 UTC, blzheng commented
@pytorchbot merge

2024-03-16 13:22 UTC, blzheng commented
@pytorchbot merge

2024-03-16 13:24 UTC, closed without merging