Const symint
pytorch/pytorch pull request #121415
Opened 2024-03-07 15:00 UTC by cyyever

Fixes #ISSUE_NUMBER

2024-03-07 15:29 UTC, malfet requested changes
PR title does not seem to match the change you are trying to make: it's not about std::optional, but rather about mutability of arguments, isn't it?

2024-03-07 15:33 UTC, cyyever commented
> PR title does not seem to match the change you are trying to make: it's not about std::optional, but rather about mutability of arguments, isn't it?

Sorry, I split the old PR into two parts, now the title is changed.

2024-03-12 04:07 UTC, ezyang approved these changes
okey dokey

2024-03-12 04:07 UTC, ezyang commented
@pytorchbot merge -r

2024-03-12 06:14 UTC, cyyever commented
@ezyang Thank you, but it can't be merged until #120076 is relanded.

2024-03-24 03:28 UTC, ezyang commented
@pytorchbot merge

2024-03-25 20:12 UTC, ezyang commented
@pytorchbot revert -c weird -m "I think this needs to be reverted to after https://github.com/pytorch/pytorch/pull/120076 revert"

2024-06-24 00:48 UTC, closed without merging