[Profiler] add missing field device_resource_id
pytorch/pytorch pull request #121480
Opened 2024-03-08 07:36 UTC by lucifer1004

Fixes #121479

2024-03-08 23:46 UTC, davidberard98 commented
@pytorchbot rebase -s

2024-03-08 23:47 UTC, davidberard98 commented
@lucifer1004 thanks for the PR! can you take a look at the linter failures? (also, I rebased the PR past some failures, so you might have to pull again when you check out your code. You can develop off of the `viable/strict` branch to avoid some of these preexisting failures)

2024-03-11 14:45 UTC, aaronenyeshi approved these changes
LGTM!

2024-03-11 14:46 UTC, aaronenyeshi commented
@pytorchbot merge

2024-03-11 15:46 UTC, aaronenyeshi requested changes
Please remove the update to third_party/XNNPACK, looks like this may be accidentally picked up in your change. Also, please check lintrunner error for torch/autograd/profiler_util.py

2024-03-11 15:48 UTC, aaronenyeshi commented on torch/autograd/profiler_util.py
> +thread if device_resource_id is None else device_resource_id
This need proper indentation, around 12 spaces.
```suggestion
            thread if device_resource_id is None else device_resource_id
```

2024-03-11 16:01 UTC, lucifer1004 commented
I do see the difference via `git diff`, but cannot edit it since it is a directory.

2024-03-12 21:39 UTC, aaronenyeshi approved these changes
LGTM!

2024-03-12 21:39 UTC, aaronenyeshi commented
@pytorchbot merge

2024-03-12 21:42 UTC, closed without merging