Add Winograd Conv method for CPU
pytorch/pytorch pull request #12154
Opened 2018-09-28 03:01 UTC by wuhuikx

Add winograd conv method. Users can select the direct conv or winograd conv in the model file.

2018-10-12 17:49 UTC, ezyang commented
CC @yinghai

2018-10-26 02:37 UTC, wuhuikx commented
@yinghai @jgong5

2018-10-29 17:25 UTC, yinghai requested changes

2018-10-30 07:50 UTC, wuhuikx commented on caffe2/ideep/operators/conv_pool_base_op.h
> +#define CONV_ALGORITHM_AUTO 0
Have changed the macros to constexpr and move them to  caffe2/ideep/ideep_utils.h file.
The patch #9488 will also use the constexpr.

2018-11-07 03:01 UTC, yinghai reviewed
Btw, do we have tests for this?

2018-11-13 05:49 UTC, wuhuikx commented
Yes, we have test this for several models.

2018-11-13 06:49 UTC, yinghai commented
I mean localized unit tests?

2018-11-14 08:11 UTC, yinghai commented
Could you check the test failures? Rebase maybe?

2018-11-15 05:19 UTC, wuhuikx commented
> Could you check the test failures? Rebase maybe?

We depend on this PR https://github.com/pytorch/pytorch/pull/12164

2018-12-14 01:18 UTC, closed without merging