Express y grid > 2^16 in terms of z grid
pytorch/pytorch pull request #121554
Opened 2024-03-08 23:19 UTC by eellison

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #121554

2024-03-09 01:24 UTC, aakhundov approved these changes

2024-03-09 01:24 UTC, aakhundov commented on torch/_inductor/codegen/triton.py
> +            key = f'{key} * {f"tl.program_id({self.grid_dim + 1})"}'
Maybe use one f-string?

2024-03-09 01:24 UTC, aakhundov commented on torch/_inductor/triton_heuristics.py
> +                lambda: f"Generated y grid behind 2^16 ({y_grid}) not supported with z dimension present. File issue",
Maybe s/behind/larger than/ for clarity? Although likely a non-native-speaker issue on my side :)

2024-03-09 17:18 UTC, jansel requested changes, later dismissed
Tests are failing

2024-03-09 17:18 UTC, jansel commented on torch/_inductor/triton_heuristics.py
> +        MAX_Y_GRID = 65536
move to global scope (and remove the other copy)

2024-03-09 17:18 UTC, jansel commented on torch/_inductor/triton_heuristics.py
> +                y_grid <= 65535,
```suggestion
                y_grid < MAX_Y_GRID,
```

2024-03-11 01:13 UTC, aakhundov commented
> Tests are failing

Sorry, was too hasty to accept.

2024-03-11 22:04 UTC, eellison commented
@pytorchbot merge

2024-03-12 01:25 UTC, eellison commented
@pytorchbot merge

2024-03-12 02:34 UTC, eellison commented
@pytorchbot merge -f "infra failure"

2024-03-12 02:36 UTC, closed without merging