[MPS] Fix sliceOffset calculation in getMPSGraphTensorDataForView: FIX #96153
pytorch/pytorch pull request #121645
Opened 2024-03-11 17:32 UTC by Jckwind

Description:
This PR addresses an issue in the PyTorch MPS backend where the sliceOffset calculation in the `getMPSGraphTensorDataForView` function was incorrect, leading to issues with reshaped tensors. The problem was caused by the way `sliceOffset` was calculated using `view_numel`.

My fix:
- Simplifies the calculation of `sliceOffset` by using the modulo operator directly with `src_base_shape[firstDimToSlice]` instead of calculating `view_numel`.
- Updates the calculation of `sliceOffset` inside the loop for remaining dimensions to use the modulo operator directly with `src_base_shape[crtSliceOffset]`.

A unit test `test_reshape_after_indexing` has been added to verify the correct behavior after applying these changes.

This PR continues the work started in PR #117456.

Fixes #96153

Testing:
- Added a new unit test `test_reshape_after_indexing` to test the specific case of reshaping a tensor after indexing.
- The new test passes without causing any issues with existing tests in the PyTorch MPS backend test suite.

Summary:
- Fixed an issue in the PyTorch MPS backend where the sliceOffset calculation in `getMPSGraphTensorDataForView` was incorrect, leading to issues with reshaped tensors.

2024-03-17 21:57 UTC, Jckwind commented
@malfet @kulinseth can I get some eyes on this PR please? Thanks

2024-03-19 14:25 UTC, malfet requested changes
It fixes one thing, but breaks another, i.e. before this change following test is passing, but with this one it fails with the sliceOffice calculation this PR claims to fix
```
% python ../test/test_modules.py -v -k test_forward_nn_Bilinear_mps_float32
test_forward_nn_Bilinear_mps_float32 (__main__.TestModuleMPS) ... /AppleInternal/Library/BuildRoots/4e1473ee-9f66-11ee-8daf-cedaeb4cabe2/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:120: failed assertion `[MPSNDArrayDescriptor sliceDimension:withSubrange:] error: subRange.start (4) is not less than length of dimension[2] (4)'
zsh: abort      python ../test/test_modules.py -v -k test_forward_nn_Bilinear_mps_float32
```

2024-03-19 14:33 UTC, Jckwind commented
hey @malfet, you're right, I didn't know that this fix was causing other tests to fail until this morning. 
This change was originally implemented to address #96153,  but the tests that are failing are pointing to my fix being inadequate to address the underlying issue. 

I've outlined my understanding of the underlying problem in #122123.

I haven't had time to explore *why* these new tests are failing - perhaps exploring why these tests are passing will shed light on the underlying issue. Will explore later today when I have free time

2024-04-18 07:58 UTC, kulinseth commented
Hi @Jckwind , I have requested @jhavukainen and @DenisVieriu97 to take a look and help shepherd this PR along.. This code is tricky and handles a lot of our View code logic, so its likely to break bunch of things.

2024-04-23 19:17 UTC, closed without merging