[codemod] Fix some namespace issues in caffe2
pytorch/pytorch pull request #121847
Opened 2024-03-13 21:15 UTC by r-barnes

Summary:
Removes `using namespace` from a header file. Having `using namespace` in a header file is *always* a bad idea. A previous raft of diffs provided appropriate qualifications to everything that relied on this `using namespace`, so it is now safe to remove it in this separate diff.

Helps us enable `-Wheader-hygiene`.

Test Plan: Sandcastle

Reviewed By: dmm-fb

Differential Revision: D54838298

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen

2024-03-14 18:43 UTC, malfet reviewed
Haven't you forgot to remove `using namespace caffe2` from the header?

2024-03-14 18:45 UTC, malfet requested changes
Please actually remove `using namespace caffe2 from `conv_transpoe_unpool...h`

2024-03-15 13:58 UTC, Skylion007 approved these changes

2024-04-01 17:43 UTC, clee2000 commented
@pytorchbot merge -f "internal diff was landed"

2024-04-01 17:45 UTC, closed without merging