enable test_sampled_addmm_zero_sized_cuda for rocm
pytorch/pytorch pull request #121940
Opened 2024-03-15 00:32 UTC by dnikolaev-amd

Enable test_sampled_addmm_zero_sized_cuda_* only for ROCm and not for CUDA
Passed since ROCm 5.6

test_sampled_addmm_zero_sized_cuda_float32
test_sampled_addmm_zero_sized_cuda_float64
test_sampled_addmm_zero_sized_cuda_complex64
test_sampled_addmm_zero_sized_cuda_complex128

2024-03-15 20:45 UTC, pruthvistony requested changes

2024-03-15 20:45 UTC, pruthvistony commented on test/test_sparse_csr.py
> +    @skipCUDAIf(not TEST_WITH_ROCM, "Causes CUDA memory exception, see https://github.com/pytorch/pytorch/issues/72177")
Please update the comment to indicate - it works on ROCm and CUDA issue is currently active.

2024-03-18 09:38 UTC, dnikolaev-amd commented
@pytorchbot rebase

2024-03-18 22:59 UTC, jeffdaily approved these changes

2024-03-19 16:06 UTC, dnikolaev-amd commented
Enabled tests
```xml
<testcase classname="TestSparseCSRCUDA" name="test_sampled_addmm_zero_sized_cuda_complex128" time="0.002" file="test_sparse_csr.py"/>
<testcase classname="TestSparseCSRCUDA" name="test_sampled_addmm_zero_sized_cuda_complex64" time="0.002" file="test_sparse_csr.py"/>
<testcase classname="TestSparseCSRCUDA" name="test_sampled_addmm_zero_sized_cuda_float32" time="0.002" file="test_sparse_csr.py"/>
<testcase classname="TestSparseCSRCUDA" name="test_sampled_addmm_zero_sized_cuda_float64" time="0.002" file="test_sparse_csr.py"/>
```

2024-03-21 15:42 UTC, dnikolaev-amd commented
@pytorchbot rebase

2024-03-25 09:17 UTC, dnikolaev-amd commented
@pytorchbot rebase

2024-03-26 07:05 UTC, pruthvistony approved these changes

2024-03-26 07:05 UTC, pruthvistony commented
@malfet 
Can you please review this PR.

2024-03-28 21:39 UTC, dnikolaev-amd commented
@pytorchbot rebase

2024-04-01 10:21 UTC, dnikolaev-amd commented
@pytorchbot rebase

2024-04-04 21:02 UTC, dnikolaev-amd commented
@pytorchbot rebase

2024-04-04 21:29 UTC, jithunnair-amd commented
@malfet Please review. Few lines of change to enable some UTs

2024-04-04 22:35 UTC, malfet approved these changes

2024-04-04 22:36 UTC, malfet commented
@pytorchbot merge -f "It affects only ROCM and I assume it had green signal before"

2024-04-04 22:38 UTC, closed without merging