Fix empty_like bug for sparse tensors.
pytorch/pytorch pull request #121900
Opened 2024-03-14 12:10 UTC by KungYork

Fixes #121671

2024-03-15 15:40 UTC, janeyx99 reviewed
Adding @pearu as reviewer. At first glance, could you add a test case?

2024-03-16 02:10 UTC, KungYork commented
No problem, I would add one in `test/test_sparse_csr.py`.

2024-03-26 18:21 UTC, janeyx99 commented
This looks good to me, let's see what CI says.

2024-03-27 14:03 UTC, pearu requested changes
Thanks for the PR! I have a suggestion to avoid unnecessary copies and removing the introduced test (see below). Otherwise, LGTM!

Re `test_ops.py::TestCommonCUDA::test_errors_sparse_randn_like_layout1_cuda` failures in CI: the function `_validate_sample_input_sparse_like_fns` in `torch/testing/_internal/opinfo/definitions/sparse.py` requires an update. IIRC, removing the `if sample.kwargs.get("device", sample.input.device) != sample.input.device:` block there should be sufficient.

In fact, adding the new test case is not necessary because the bug fix is tested via opinfo framework.

2024-03-27 14:44 UTC, pearu commented on aten/src/ATen/native/sparse/SparseCsrTensor.cpp
> +        self.col_indices().clone().to(options.device()),
A bug fix to the above: using `options.dtype()` is wrong because this is not indices type. Use, say, `self.crow_indices().dtype()` or similar.

2024-03-31 16:34 UTC, KungYork commented on aten/src/ATen/native/sparse/SparseCsrTensor.cpp
> +        self.col_indices().clone().to(options.device()),
Thanks! I have made related modification and remove the added test.

2024-04-01 14:16 UTC, pearu approved these changes
LGTM! Thanks, @KungYork!

2024-04-01 15:47 UTC, KungYork commented
@pytorchbot merge

2024-04-01 15:55 UTC, KungYork commented
Looks like there is some problem with docs of torch.ao.quantization.quantize, I will check that.

2024-04-01 18:54 UTC, janeyx99 commented
@KungYork This is an existing issue, probably not related to your PR. See https://github.com/pytorch/pytorch/issues/123068

2024-04-01 22:38 UTC, KungYork commented
@pytorchbot merge

2024-04-01 22:40 UTC, closed without merging

2024-04-01 22:54 UTC, KungYork commented
It is ok now, thank you again! @pearu