[inductor]re-enable cpu reduction ut
pytorch/pytorch pull request #122289
Opened 2024-03-20 07:43 UTC by zhuhaozhe

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #122289

2024-03-21 01:13 UTC, jgong5 requested changes
UT failure is relevant.

2024-03-28 09:10 UTC, zhuhaozhe commented
> UT failure is relevant.

I can pass it in my local. Might be caused by different random seed. The reduction numbers look large for `test_dense_mask_index`.
I set a larger tolerance for it. `rtol=1e-4, atol=1.3e-5"

2024-03-29 03:45 UTC, jgong5 approved these changes

2024-03-30 16:38 UTC, jansel approved these changes

2024-03-31 08:31 UTC, zhuhaozhe commented
@pytorchbot merge

2024-03-31 08:33 UTC, closed without merging