[Profiler] Make Kineto traces export ns granularity for finer timestamps
pytorch/pytorch pull request #122425
Opened 2024-03-21 18:31 UTC by sraikund16

Summary:
Kineto traces use microsecond level granularity because of chrome tracing defaults to that precision. Fix by adding preprocessor flag to TARGETS and BUCK files. Also remove any unnecessary ns to us conversions made in the profiler itself.

This diff contains profiler changes only. Libkineto changes found in D54964435.

Test Plan:
Check JSON and chrome tracing to make sure values are as expected. Tracing with flags enabled should have ns precision. Tracings without flags should be same as master.
Tracing with flags enabled: https://www.internalfb.com/intern/perfdoctor/trace_view?filepath=tree/traces/dynocli/devvm2185.cco0.facebook.com/rank-0.Mar_18_14_37_22.4155151.pt.trace.json.gz&bucket=gpu_traces
Tracing without flags enabled: https://www.internalfb.com/intern/perfdoctor/trace_view?filepath=tree/traces/dynocli/devvm2185.cco0.facebook.com/rank-0.Mar_18_14_39_15.4166047.pt.trace.json.gz&bucket=gpu_traces
Tracing on main: https://www.internalfb.com/intern/perfdoctor/trace_view?filepath=tree/traces/dynocli/devvm2185.cco0.facebook.com/rank-0.Mar_18_14_42_43.4177559.pt.trace.json.gz&bucket=gpu_traces

Ran key_averages() to make sure FunctionEvent code working as expected:
--  ------------  ------------  
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg    # of Calls  

                                          ProfilerStep*         0.74%       3.976ms        64.40%     346.613ms      69.323ms       0.000us         0.00%      61.710ms      12.342ms             5  
                      Optimizer.zero_grad#SGD.zero_grad         0.76%       4.109ms         0.76%       4.109ms     821.743us       0.000us         0.00%       0.000us       0.000us             5  
                                          ## forward ##         6.89%      37.057ms        27.19%     146.320ms      29.264ms       0.000us         0.00%      58.708ms      11.742ms             5  
                                           aten::conv2d         0.22%       1.176ms         7.74%      41.658ms     157.199us       0.000us         0.00%      27.550ms     103.962us           265  
                                      aten::convolution         0.79%       4.273ms         7.52%      40.482ms     152.762us       0.000us         0.00%      27.550ms     103.962us           265  
                                     aten::_convolution         0.69%       3.688ms         6.73%      36.209ms     136.637us       0.000us         0.00%      27.550ms     103.962us           265  
                                aten::cudnn_convolution         6.04%      32.520ms         6.04%      32.520ms     122.719us      27.550ms         8.44%      27.550ms     103.962us           265  
                                             aten::add_         2.42%      13.045ms         2.42%      13.045ms      30.694us      12.700ms         3.89%      12.700ms      29.882us           425  
                                       aten::batch_norm         0.19%       1.027ms         8.12%      43.717ms     164.971us       0.000us         0.00%      16.744ms      63.185us           265  
                           aten::_batch_norm_impl_index         0.31%       1.646ms         7.93%      42.691ms     161.096us       0.000us         0.00%      16.744ms      63.185us           265  
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------

Differential Revision: D55087993

2024-03-23 00:18 UTC, davidberard98 reviewed
you'll probably need to update the referenced pin in `third_party/kineto`.

It'll be something like this - need to run this in a git checkout of pytorch, not the internal repo:
```
cd third_party/kineto
git checkout [commit hash from the kineto repo]
cd ../../
git add third_party/kineto
git commit ... # etc 
```

You can probably do this in a separate PR and then land this change after that separate PR lands.

2024-03-25 14:45 UTC, aaronenyeshi requested changes
Please check the CI failing signals.

2024-03-25 14:45 UTC, aaronenyeshi commented on torch/csrc/profiler/collection.cpp
> +             static_cast<c10::time_t>(end_time_ns))) {
```suggestion
             converter, python_enters, static_cast<c10::time_t>(end_time_ns))) {
```
looks like lintrunner needs a fix like so.

2024-03-27 20:32 UTC, aaronenyeshi approved these changes
LGTM! Thanks for fixing the CI issues!

2024-04-06 06:02 UTC, clee2000 commented
@pytorchbot merge -f "merged internally"

2024-04-06 16:17 UTC, malfet commented
@pytorchbot revert -m "Breaks ROCM builds" -c ignoredsignal

2024-04-08 15:05 UTC, aaronenyeshi commented
> @sraikund16 , @clee2000 I'm on PTO for the next couple of days, please revert internal PR and make sure that Kineto changes are compatible with OSS (and internal) ROCM builds

Sorry about this. Kineto had commits that changed RocTracer usage. I suspect the Kineto hash update caused the regression in ROCM builds. We are looking into it.

2024-04-11 16:10 UTC, closed without merging