[Quant] [PT2] Add EmbeddingBag  into X86InductorQuantizer Annotation
pytorch/pytorch pull request #122488
Opened 2024-03-22 08:11 UTC by zhuhaozhe

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-03-22 10:09 UTC, jgong5 requested changes
tests are failing.

2024-03-22 10:09 UTC, jgong5 commented on test/quantization/pt2e/test_x86inductor_quantizer.py
> +        def __init__(self, ntables=3, embedding_dim=128, num_embedings=1000) -> None:
nit:
```suggestion
        def __init__(self, ntables=3, embedding_dim=128, num_embeddings=1000) -> None:
```

2024-03-22 13:18 UTC, zhuhaozhe commented on test/quantization/pt2e/test_x86inductor_quantizer.py
> +        def __init__(self, ntables=3, embedding_dim=128, num_embedings=1000) -> None:
Thanks for reminder

2024-03-22 13:19 UTC, zhuhaozhe commented
> tests are failing.

I should use `elif` but used `if', fixed.

2024-03-23 00:24 UTC, leslie-fang-intel requested changes

2024-03-23 00:24 UTC, leslie-fang-intel commented on torch/ao/quantization/quantizer/x86_inductor_quantizer.py
> +            elif node.target is torch.ops.aten.embedding_bag.padding_idx:
`_annotation_propagation_quantizable_pattern` is used to annotate operators like `maxpool2d`, `cat` which will depend on previous nodes to decide whether we should insert observer for it. But here, the recipe for `embedding_bag` is insert observer at weight no matter of previous node.

- Can we double check in IPEX whether it's a desired recipe?
- If so, I think the implementation of recipe for `embedding_bag` shouldn't in `_annotation_propagation_quantizable_pattern` but somewhere like the conv/linear.

2024-03-23 00:32 UTC, leslie-fang-intel commented on torch/ao/quantization/quantizer/x86_inductor_quantizer.py
> +    copy.deepcopy(embedding_ops)
If we always annotate weight of `embedding_ops`. We don't need to add it into `quantizable_ops_pt2e ` as the comment above.

2024-06-21 00:48 UTC, closed without merging