[Inductor] Support custom op in cpp wrapper codegen
pytorch/pytorch pull request #122554
Opened 2024-03-23 16:21 UTC by desertfire

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #122554

2024-03-25 04:12 UTC, jansel requested changes

2024-03-25 04:12 UTC, jansel commented on torch/_inductor/codegen/cpp_wrapper_cpu.py
> +                            Py_DECREF(codecache_module);
Should we add a small RAII wrapper for all the decrefs?

2024-03-25 15:44 UTC, desertfire commented
Update with a `RAIIPyObject` class. Updated the gist link in the comment to https://gist.github.com/desertfire/be2a65b0a9b47780bb716b53ac2cd2b3

2024-03-25 16:03 UTC, jansel approved these changes

2024-03-25 18:11 UTC, desertfire commented
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D55326556).

2024-03-26 06:18 UTC, chenyang78 approved these changes
LGTM. Thanks!

2024-03-26 18:47 UTC, desertfire commented
@pytorchbot merge -f "landed internally, somehow the auto merge here was not triggered"

2024-03-26 18:48 UTC, closed without merging

2024-03-27 18:15 UTC, jeffdaily commented
This did break ROCm inductor CI.  I opened a DISABLED issue to skip.  https://github.com/pytorch/pytorch/issues/122811