[DCP] Support partial load
pytorch/pytorch pull request #122829
Opened 2024-03-27 21:18 UTC by LucasLLC

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Adds ability to load a subset of keys directly from a checkpoint, avoiding the need to initialize state dict first

Differential Revision: [D55441391](https://our.internmc.facebook.com/intern/diff/D55441391/)

2024-03-27 21:23 UTC, LucasLLC commented on torch/distributed/checkpoint/default_planner.py
> +class _EmptyStateDictLoadPlanner(DefaultLoadPlanner):
I had to move this out of format utils to avoid a circular dependency. I'm very open to suggestions on where a better home might be for this class

2024-03-29 17:02 UTC, wz337 commented
Looks like `test/distributed/checkpoint/test_partial_load.py` is empty?

2024-03-29 17:54 UTC, fegin commented
`_load_state_dict_from_keys` seems to violate the fundamental philosophy of DCP. 1. It does not support resharding, 2. It does not support in-place loading. Why do we actually need such an API?

2024-03-29 17:54 UTC, fegin requested changes
_load_state_dict_from_keys seems to violate the fundamental philosophy of DCP. 1. It does not support resharding, 2. It does not support in-place loading. Why do we need such an API?

2024-03-29 20:34 UTC, LucasLLC commented
> _load_state_dict_from_keys seems to violate the fundamental philosophy of DCP. 1. It does not support resharding, 2. It does not support in-place loading. Why do we need such an API?

This was answered offline:
The use case is that researchers often want to just load specific modules and inspect them on the fly. E.g. someone shared a checkpoint file with you, and we would like to load it into a notebook and inspect it on the fly. I think we can consider this a “utility” for that use case.

2024-03-29 22:07 UTC, fegin commented on torch/distributed/checkpoint/state_dict_loader.py
> +    keys: Optional[set],
Why is this optional? If users pass None, is this API going to load everything? If so, we may want to mention that in the docstring. If this API will do nothing, then I suggest that we should simply not support the None case.

2024-03-29 22:07 UTC, fegin commented on torch/distributed/checkpoint/state_dict_loader.py
> +    Load only the specified keys from the checkpoint.
We should also mention that the checkpoint will not be sharded and all the ranks, if distributed is initialized, are going to load the full checkpoint.

2024-04-01 17:06 UTC, fegin approved these changes

2024-04-02 16:20 UTC, LucasLLC commented
@pytorchbot merge

2024-04-02 19:22 UTC, closed without merging