[TP] Add wildcard support
pytorch/pytorch pull request #122968
Opened 2024-03-29 17:29 UTC by kwen2501

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-04-01 21:15 UTC, kurman commented
I wonder if jq or xpath style spec would improve UX given the hierarchical nature? It comes with a higher complexity though.

2024-04-01 21:28 UTC, XilunWu commented
Users need be aware that the patterns in the dict param must be mutually exclusive otherwise the repetitive `parallelize_module` may cause issue.

2024-04-01 21:28 UTC, XilunWu approved these changes
LGTM

2024-04-02 00:11 UTC, wz337 approved these changes
LGTM! Could we add some tests to demonstrate the usage as well?

2024-04-02 00:29 UTC, kwen2501 commented
@wz337 Thanks for the review! The tests are in a stacked PR: #123101

2024-04-02 04:12 UTC, wanchaol requested changes
Can you fold the tests PR to this PR? I think every new feature PR should come with tests in the PR itself, not a separate PR

2024-04-02 14:01 UTC, kwen2501 commented
@wanchaol Done!

2024-04-02 17:24 UTC, wanchaol approved these changes
looks great, thanks for addressing comments!

2024-04-02 17:24 UTC, wanchaol commented on torch/testing/_internal/distributed/_tensor/common_dtensor.py
> +    def __init__(self, device):
nit: I think it would be nice to have a `num_layers` arg (can have a default) to control how many MLP layers this stacked MLP construct

2024-04-02 17:24 UTC, wanchaol commented on test/distributed/tensor/parallel/test_parallelize_api.py
> +                "layers.*.net?": ColwiseParallel(output_layouts=Replicate()),
wondering can we do a e2e col + row test here?
```
{
    "layers.*.net[1]": ColwiseParallel(),
    "layers.*.net[2]": RowwiseParallel()
}
```

2024-04-02 18:01 UTC, kwen2501 commented
@pytorchbot merge

2024-04-02 18:20 UTC, kwen2501 commented
@pytorchbot merge

2024-04-03 02:18 UTC, kwen2501 commented
@pytorchbot merge

2024-04-22 21:06 UTC, closed without merging