Add cudnn_rnn_flatten_weight meta kernel
pytorch/pytorch pull request #123138
Opened 2024-04-01 23:59 UTC by angelayi

I'm not sure if this is a correct meta kernel 😅 
https://github.com/pytorch/pytorch/issues/120626

2024-04-02 18:05 UTC, eellison reviewed
I think this kernel is metdata-mutating. Adding support for it and rnn might be a little tricky, and require a larger change in approach. 

What is the motivation here ?

2024-04-02 18:05 UTC, eellison commented on torch/_meta_registrations.py
> +    return weight_buf
I believe this `_cudnn_rnn_flatten_weight` does in-place stride modifications to the input parameters. See, this comment here: https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/rnn.py#L203-L204

We would to in-place update the metas of the inputs.

2024-04-09 01:12 UTC, ezyang approved these changes
meta is not accurate. Maybe a stopgap is to test if the parameters are already in the correct stride (and error if they are not).

2024-04-09 01:12 UTC, ezyang requested changes
oops clicked wrong button, see above

2024-07-08 01:53 UTC, closed without merging