[BASE_MODULE] removing base_module for glow/fb/test:test_utils
pytorch/pytorch pull request #123263
Opened 2024-04-03 15:29 UTC by azad-meta

Summary: This is an attempt to reduce the number of buck targets with unnecessary base_module.

Test Plan: CI

Differential Revision: D55695054

2024-04-04 18:24 UTC, atalman commented
cc @malfet @albanD @ezyang

2024-04-04 18:52 UTC, malfet commented
@atalman sorry, what's the ask?

2024-04-04 18:54 UTC, malfet requested changes
One should not export anything to OSS that depends on `.fb.` modules

2024-04-04 19:38 UTC, ezyang approved these changes
Meh it's caffe2 whatever

2024-04-04 20:41 UTC, malfet commented
@ezyang it's still wrong to ship clearly broken code, perhaps remove is in order

2024-04-04 20:42 UTC, malfet commented
> @malfet as you can see nothing has changed with the dependency list. Those were .fb dependencies all along. The namespace was rewritten with base_module to make it look like it was from a different path.

You PR makes following change
```patch
- from caffe2.python.fakelowp.test_utils import print_test_debug_info
+ from glow.fb.test.test_utils import print_test_debug_info
```

I.e. from referencing this function in the repo
https://github.com/pytorch/pytorch/blob/d486cb7c1b6a4a80f6287c1092b9223b11826428/caffe2/python/fakelowp/test_utils.py#L9

to something that clearly does not exists on github

2024-04-09 20:55 UTC, albanD commented
I think we should block such change on https://github.com/pytorch/pytorch/pull/122527 to ensure sanity.
Teams that know the caffe2 folder well can start disabling the OSS sync and then they will be able to change these folders without touching OSS faster.

2024-07-08 22:33 UTC, closed without merging