[Compile FSDP2][1/n] Support using user-defined object instance method as hook
pytorch/pytorch pull request #123399
Opened 2024-04-04 23:28 UTC by yf225

FSDP2 has this pattern of using user-defined object instance method as hook, and it will throw this error under compile:
`torch._dynamo.exc.Unsupported: call_function UserDefinedObjectVariable(_pre_forward) [FSDPManagedNNModuleVariable(), TupleVariable(), ConstDictVariable()] {}`

This PR adds support for it by always allowing to call into a UserDefinedObjectVariable that's an instance method (i.e. `MethodType`).

2024-04-04 23:45 UTC, jansel requested changes

2024-04-04 23:45 UTC, jansel commented on torch/_dynamo/variables/user_defined.py
> +            func_src = AttrSource(self.source, "__func__") if self.source else None
I believe source is required for VariableBuilder to work.  We should call `unimplemented()` if `source=None`

2024-04-05 18:27 UTC, jansel approved these changes

2024-04-05 20:30 UTC, thiagocrepaldi commented
@yf225 out of curiosity, will the user-defined object be represented in the graphModule FX graph? I dont think I understood what you mean by "allow to call into a UserDefinedObjectVariable that's an instance method" in this context

2024-04-05 20:38 UTC, yf225 commented
> @yf225 out of curiosity, will the user-defined object be represented in the graphModule FX graph? I dont think I understood what you mean by "allow to call into a UserDefinedObjectVariable that's an instance method" in this context

The user-defined object here does not show up in the Dynamo-produced FX graph. "allow to call into a UserDefinedObjectVariable" means allowing Dynamo to trace into it (I updated the desc).

2024-04-09 17:14 UTC, yf225 commented
@pytorchbot merge

2024-04-09 17:26 UTC, yf225 commented
@pytorchbot merge

2024-04-09 17:29 UTC, closed without merging