[compiled autograd][dynamo] codegen aliases to keep grad mutated tensors alive
pytorch/pytorch pull request #123359
Opened 2024-04-04 16:49 UTC by xmfan

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-04-11 22:48 UTC, jansel requested changes
Add a test?

2024-04-12 00:39 UTC, xmfan commented on test/inductor/test_compiled_autograd.py
> +    def test_inputs_aliasing_bytecode(self):
Adding a test to cover the bytecode directly. The behavior of this PR is covered by all tests once we add the inputs list clear on aot side in next PR.

2024-04-12 00:52 UTC, xmfan commented on test/inductor/test_compiled_autograd.py
> +    def test_inputs_aliasing_bytecode(self):
Adding a test to cover the bytecode directly. The behavior of this PR is covered by all tests once we add the inputs list clear on aot side in next PR.

2024-04-12 03:30 UTC, jansel approved these changes

2024-04-12 10:29 UTC, closed without merging