[BE]: Update cudnn to 9.0.0.312
pytorch/pytorch pull request #123475
Opened 2024-04-05 21:31 UTC by eqy

cuDNN has managed to upload cu11 and cu12 wheels for 9.0.0.312, so trying this out...

CC @Skylion007 @malfet

2024-04-08 15:49 UTC, Skylion007 approved these changes
Looks good assuming you fix the Caffe2 issue.

2024-04-08 18:44 UTC, eqy commented
@Skylion007 do we anticipate #122527 landing in the near-future? caffe2 fixes might be involved and look something like #115719 which might be a bit involved if caffe2 is being removed soon

2024-05-06 13:41 UTC, johnnynunez commented
9.1.1 is out

2024-05-10 20:19 UTC, eqy commented
@pytorchmergebot rebase (checking to see if caffe2 issue has been resolved)

2024-05-10 20:19 UTC, eqy commented
@pytorchmergebot rebase

2024-05-10 23:43 UTC, malfet approved these changes

2024-05-12 18:43 UTC, Skylion007 commented
@eqy Looks like the issues were fixed. Let's merge.

2024-05-13 21:06 UTC, eqy commented
@pytorchmergebot merge

2024-05-14 14:48 UTC, Skylion007 commented
@eqy Yeah looks like we need a builder PR: https://github.com/pytorch/builder/blob/ead2e21b24038ed9117060bb2c00bc79c4e91d85/CUDA_UPGRADE_GUIDE.MD?plain=1

2024-05-14 14:55 UTC, Skylion007 commented
@malfet You helped with the last cudnn PR, mind helping this land with the corresponding builder PR?

2024-05-14 17:02 UTC, ptrblck commented
CC @nWEIdia for the corresponding `pytorch/builder` PR.

2024-05-14 17:13 UTC, nWEIdia commented
[like]  Wei Wang reacted to your message:
________________________________
From: ptrblck ***@***.***>
Sent: Tuesday, May 14, 2024 5:02:43 PM
To: pytorch/pytorch ***@***.***>
Cc: Wei Wang ***@***.***>; Mention ***@***.***>
Subject: Re: [pytorch/pytorch] [BE]: Update cudnn to 9.1.0.70 (PR #123475)


CC @nWEIdia<https://github.com/nWEIdia> for the corresponding pytorch/builder PR.

—
Reply to this email directly, view it on GitHub<https://github.com/pytorch/pytorch/pull/123475#issuecomment-2110714895>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BCHE4QEGJ37RY6HTHZ4Z5VDZCI7THAVCNFSM6AAAAABFZZ7ITOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMJQG4YTIOBZGU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-05-15 15:32 UTC, Skylion007 commented
The workflow lint checker also seems to be bugged out. ;-;

2024-05-15 16:21 UTC, nWEIdia commented
The builder branch has been created, to test this PR, I recall we may need to change the following file as well since cudnn gets bumped from 8 to 9, e.g. https://github.com/pytorch/pytorch/blob/updatecudnn9/.ci/docker/build.sh#L94 

We can test with companion builder branch via recommendations in https://github.com/pytorch/pytorch/pull/124014#issuecomment-2058144686 and https://github.com/pytorch/builder/pull/1822 
and fix lint and resolve conflicts (https://github.com/pytorch/pytorch/pull/125944 went in).

2024-05-15 21:57 UTC, nWEIdia commented
@atalman just reminded me that https://github.com/pytorch/pytorch/pull/121684/files generate_binary_build_matrix file may also need to be changed to reflect cudnn change.

2024-05-15 22:02 UTC, nWEIdia commented
@atalman and I would recommend this PR waiting for https://github.com/pytorch/pytorch/pull/121956, which is enabling CUDA 12.4 CI. Please wait for 12.4 CI to land first, thanks!

2024-05-24 15:07 UTC, Skylion007 commented
@nWEIdia CUDA 12.4 in, let's merge the NCCL and CUDNN dependency updates too.

2024-05-24 23:44 UTC, bhack commented
Can we link this to the ticket https://github.com/pytorch/pytorch/pull/123475 so that it will be autoclosed?

2024-05-24 23:49 UTC, nWEIdia requested changes
cudnn9 has to show up in docker image, so the build.sh under .ci/docker needs to embrace cudnn v9 in full.

2024-05-24 23:49 UTC, nWEIdia commented on .ci/docker/build.sh
>      CUDNN_VERSION=8
@eqy, CUDNN_VERSION=8 has to be changed to CUDNN_VERSION=9

2024-05-24 23:49 UTC, nWEIdia commented on .ci/docker/build.sh
>      CUDNN_VERSION=8
Same here since you chnaged install_cudnn.sh for all cuda versions?

2024-05-24 23:49 UTC, nWEIdia commented on .ci/docker/build.sh
>      CUDNN_VERSION=8
ditto

2024-05-24 23:49 UTC, nWEIdia commented on .ci/docker/build.sh
>      CUDNN_VERSION=8
same

2024-05-24 23:49 UTC, nWEIdia commented on .ci/docker/build.sh
>      CUDNN_VERSION=8
same

2024-05-24 23:49 UTC, nWEIdia commented on .github/scripts/generate_binary_build_matrix.py
12.4 also needs to be changed. Only changed 12.1 and 11.8

2024-05-25 00:06 UTC, bhack commented
> cudnn9 has to show up in docker image, so the build.sh under .ci/docker needs to embrace cudnn v9 in full.

`12.4.1` Images are with cudnn `9.1.0.70`
https://hub.docker.com/layers/nvidia/cuda/12.4.1-cudnn-runtime-ubuntu20.04/images/sha256-de9acc3e4d3aace101541899b95f6a4af897994124713f7131dffaf9967cb514?context=explore

But this is only eventually valid for pytorch nightly images.

In the CI Docker images I suppose we install cudnn `manually` https://github.com/pytorch/pytorch/issues/126005#issuecomment-2125841248

2024-05-28 13:01 UTC, atalman commented
Since we have generated docker images with cudnn 9.0. Please temporarily pin docker manywheel builder images to these values:
```
pytorch/manylinux-builder:cuda12.1-7e4bdab63653ad6af8d92fdfa69d7e96780ce258
pytorch/manylinux-builder:cuda11.8-7e4bdab63653ad6af8d92fdfa69d7e96780ce258
pytorch/manylinux-builder:cuda12.4-7e4bdab63653ad6af8d92fdfa69d7e96780ce258
```

2024-05-28 18:41 UTC, Skylion007 commented
Ugh, cudnn 9.1.1.17 just had pip wheels generated too. :(

2024-05-29 05:30 UTC, nWEIdia commented on .ci/docker/common/install_cudnn.sh
> +        CUDNN_NAME="cudnn-linux-x86_64-9.1.0.70_cuda11-archive"
cuda11 does not look right. 
We still support cuda 11.8, right? So three versions: cuda 12.1, cuda 12.4, and cuda 11.8

2024-05-30 00:37 UTC, nWEIdia commented
there are a few places like: https://github.com/pytorch/pytorch/blob/updatecudnn9/.github/workflows/trunk.yml#L91 
https://github.com/pytorch/pytorch/blob/updatecudnn9/.github/workflows/trunk.yml#L115 
https://github.com/pytorch/pytorch/blob/updatecudnn9/.github/workflows/trunk.yml#L129 

Please check the other yml files too.

2024-05-30 00:42 UTC, nWEIdia approved these changes
Epic changes!

2024-05-31 12:17 UTC, atalman commented on .github/scripts/generate_binary_build_matrix.py
> +        "nvidia-cudnn-cu11==9.1.0.70; platform_system == 'Linux' and platform_machine == 'x86_64' | "
```suggestion
        "nvidia-cudnn-cu12==9.1.0.70; platform_system == 'Linux' and platform_machine == 'x86_64' | "
```

2024-05-31 12:24 UTC, atalman commented on .github/scripts/generate_binary_build_matrix.py
> +        "nvidia-cudnn-cu12==9.1.0.70; platform_system == 'Linux' and platform_machine == 'x86_64' | "
```suggestion
        "nvidia-cudnn-cu11==9.1.0.70; platform_system == 'Linux' and platform_machine == 'x86_64' | "
```

2024-05-31 12:24 UTC, atalman commented on .github/scripts/generate_binary_build_matrix.py
> +        "nvidia-cudnn-cu12==9.1.0.70; platform_system == 'Linux' and platform_machine == 'x86_64' | "
put back cu11

2024-05-31 13:32 UTC, Skylion007 commented
It would be nice if we could update to 9.1.1.17 as it appears as though it has fixed some bad heuristics in 9.1.0 that could cause perf regressions.

2024-05-31 21:25 UTC, eqy commented
> It would be nice if we could update to 9.1.1.17 as it appears as though it has fixed some bad heuristics in 9.1.0 that could cause perf regressions.
> 
> > On NVIDIA Hopper and Ampere architectures, fused flash attention bprop would return an execution failed when sequence lengths greater than or equal to 512k were used. This issue has been fixed.
> > Fixed heuristics regression in version 9.1.0 with mixed input precision MatMul/convolution use cases.
> > On NVIDIA Hopper architectures, fused flash attention bprop could lead to incorrect results in version 8.9.7; we missed documenting the issue in that version. This issue was fixed in version 9.0.0.
> > The scale and bias tensor descriptor checks for Layer and RMS Normalization have been updated to require the normalizing dimensions to be specified in the correct order. These checks were missing in cuDNN version 9.0 and prior version
> > https://docs.nvidia.com/deeplearning/cudnn/latest/release-notes.html

We're a bit hesistant to move to 9.1.1 here last minute as 9.1.0 has been much more thoroughly tested in NGC containers while 9.1.1 has had basically no testing in that form. AFAIK mixed-precision conv/matmul are a rare use-case that isn't supported at the moment? e.g., even for batchnorm it has not been merged yet https://github.com/pytorch/pytorch/pull/121124

Layer and RMSNorm do not go through cuDNN; see also https://github.com/pytorch/pytorch/pull/125350

2024-06-01 02:59 UTC, nWEIdia requested changes
Line 131 in workflows/generated-linux-binary-manywheel-nightly.yml is wrong, 
causes https://github.com/pytorch/pytorch/actions/runs/9325276243/job/25674005681#step:17:450 to download wrong cudnn version. 

Note that the generated-* file should not be manually changed and needs to be generated from .github/regenerate.sh 

I will push a fix.

2024-06-01 05:26 UTC, nWEIdia commented
for future reference, the failures in https://github.com/pytorch/pytorch/actions/runs/9327166331/job/25676708999 means this PR was testing with pytorch/builder main branch and are missing changes in https://github.com/pytorch/builder/pull/1847 (manywheel/build_cuda.sh changes, to be specific). This is also the reason to land these two PRs together. 

```
2024-06-01T05:14:23.4785350Z ++ for filepath in '"${DEPS_LIST[@]}"'
2024-06-01T05:14:23.4786766Z +++ basename /usr/local/cuda/lib64/libcudnn_adv_infer.so.8
2024-06-01T05:14:23.4794447Z ++ filename=libcudnn_adv_infer.so.8
2024-06-01T05:14:23.4794921Z ++ destpath=libtorch/lib/libcudnn_adv_infer.so.8
2024-06-01T05:14:23.4795861Z ++ [[ /usr/local/cuda/lib64/libcudnn_adv_infer.so.8 != \l\i\b\t\o\r\c\h\/\l\i\b\/\l\i\b\c\u\d\n\n\_\a\d\v\_\i\n\f\e\r\.\s\o\.\8 ]]
2024-06-01T05:14:23.4797021Z ++ cp /usr/local/cuda/lib64/libcudnn_adv_infer.so.8 libtorch/lib/libcudnn_adv_infer.so.8
2024-06-01T05:14:23.4804470Z cp: cannot stat ‘/usr/local/cuda/lib64/libcudnn_adv_infer.so.8’: No such file or directory
```

2024-06-01 06:04 UTC, eqy commented
might be related to rocm failures? https://github.com/pytorch/pytorch/pull/125396#issuecomment-2142646195

2024-06-01 06:06 UTC, nWEIdia commented
> might be related to rocm failures? [#125396 (comment)](https://github.com/pytorch/pytorch/pull/125396#issuecomment-2142646195)

Yeah, we may need to rebase to avoid this failure because the rocm change was reverted but this PR probably did not include the revert.

2024-06-01 06:36 UTC, nWEIdia commented
linux conda build jobs are failing for this PR, 
but linux conda build jobs are not failing for the equivalent PR + pytorch/builder change (pytorch/pytorch #127589), again meaning this PR depends on pytorch/builder PR. 

Failure (this PR): https://github.com/pytorch/pytorch/actions/runs/9327166376/job/25676701472
Working (equivalent PR #127589 ): https://github.com/pytorch/pytorch/actions/runs/9327183348/job/25676738895 

The difference between failure and working is again the libcudnn_adv_infer.so.8 -> libcudnn_adv.so.9 difference (working)

2024-06-01 06:53 UTC, nWEIdia commented
Both this PR and the other PR fails for libtorch build but for difference reasons: 
1) this PR fails  https://github.com/pytorch/pytorch/actions/runs/9327166331/job/25676708999, because again 

2024-06-01T05:14:23.4786766Z +++ basename /usr/local/cuda/lib64/libcudnn_adv_infer.so.8
2024-06-01T05:14:23.4794447Z ++ filename=libcudnn_adv_infer.so.8
2024-06-01T05:14:23.4794921Z ++ destpath=libtorch/lib/libcudnn_adv_infer.so.8
2024-06-01T05:14:23.4795861Z ++ [[ /usr/local/cuda/lib64/libcudnn_adv_infer.so.8 != \l\i\b\t\o\r\c\h\/\l\i\b\/\l\i\b\c\u\d\n\n\_\a\d\v\_\i\n\f\e\r\.\s\o\.\8 ]]
2024-06-01T05:14:23.4797021Z ++ cp /usr/local/cuda/lib64/libcudnn_adv_infer.so.8 libtorch/lib/libcudnn_adv_infer.so.8
2024-06-01T05:14:23.4804470Z cp: cannot stat ‘/usr/local/cuda/lib64/libcudnn_adv_infer.so.8’: No such file or directory

steering this PR towards pytorch/builder branch should fix 

2) the other PR failed here https://github.com/pytorch/pytorch/actions/runs/9327183345/job/25676742766 (that is linux-binary-libtorch-cxx11-abi  job) but successful here (https://github.com/pytorch/pytorch/actions/runs/9327183368/job/25679146488), the reason is the docker image has to use the customized one (not cu124-main, cu121-main, cu118-main, but the one with the {sha}. One succeed and one failure means, this PR needs to modify the .github/scripts/generate_binary_build_matrix.py to be consistent for both libtorch builds.

2024-06-01 06:56 UTC, nWEIdia commented
In addition, https://github.com/pytorch/pytorch/actions/runs/9327166354/job/25676707213#step:16:4504 is saying arm cuda was not picking up cudnn v9 changes.

2024-06-01 22:46 UTC, nWEIdia approved these changes
It seems only 1) rebase and 2) revert testing changes are needed. 
Need to watch out inductor tiny* model accuracy failures.

2024-06-01 23:10 UTC, nWEIdia commented
@pytorchbot rebase

2024-06-03 13:40 UTC, tinglvv commented
cuda-aarch64 builds are failing due to 
`FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda/lib64/libcudnn.so.9'`
https://github.com/pytorch/pytorch/actions/runs/9333823315/job/25691260378?pr=123475

We would need to merge https://github.com/pytorch/builder/pull/1847 which copies this file to ARM wheel.

2024-06-04 13:38 UTC, Skylion007 commented
Remaining failures seem unrelated. Let's coordinate the builder merge @malfet @albanD

2024-06-04 16:30 UTC, atalman commented
@pytorchmergebot merge -f "All required workflows are green"

2024-06-05 00:16 UTC, eqy commented
For inductor EfficientConvBN failure, see #127984

2024-06-05 08:57 UTC, huydhn commented
@pytorchbot revert -m 'CUDA trunk jobs are pretty red after this change, and the forward fix https://github.com/pytorch/pytorch/pull/127984 does not look working' -c weird

2024-06-05 11:21 UTC, atalman commented
@huydhn Here is the signal on the same PR before merging it: https://github.com/pytorch/pytorch/actions/runs/9358133192/job/25760440684
This looks like land race.

2024-06-05 15:45 UTC, nWEIdia commented
> @huydhn Here is the signal on the same PR before merging it: https://github.com/pytorch/pytorch/actions/runs/9358133192/job/25760440684 This looks like land race.

Agree. There should only be https://github.com/pytorch/pytorch/issues/127990 after merging cudnn v9. We just missed one model beit which we could have communicated. 

![image](https://github.com/pytorch/pytorch/assets/143543872/91f35730-d22b-450b-bc6b-993fd954bda2)

Just that one model.

2024-06-05 17:56 UTC, eqy commented
@huydhn looks like another fix of the same type is needed for grads https://github.com/pytorch/pytorch/pull/123475, I'll open

2024-06-05 18:21 UTC, nWEIdia commented
For this PR, after https://github.com/pytorch/pytorch/pull/127825, we need to rebase **AND** cudnn8-> cudnn9 related changes.

2024-06-06 16:56 UTC, atalman approved these changes

2024-06-06 18:43 UTC, atalman commented
@pytorchmergebot merge -f "lint is green"

2024-06-06 18:45 UTC, closed without merging