[AOTI] Move c10/util ostream function implementations to their headers
pytorch/pytorch pull request #123847
Opened 2024-04-11 15:18 UTC by desertfire

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Summary: AOTInductor generated code for CPU models may have direct reference to these c10-implemented data types, see _inductor/codegen/cpp_prefix.h. To make sure the AOTI generated code is ABI backward compatible, we have to ensure these data types are implemented in a header-only fashion.

2024-04-11 17:49 UTC, jansel approved these changes

2024-04-12 00:18 UTC, ezyang requested changes
No, this extremely suspicious. Why are we printing floats from AOTInductor generated so?

2024-04-12 02:49 UTC, desertfire commented
> No, this extremely suspicious. Why are we printing floats from AOTInductor generated so?

This is to enable the next PR in this stack, standalone floating-point type unit tests. AOTInductor generated .so doesn't use those printing AFAIK.

I know in the next PR you suggested to check undefined symbols in the generated .so and compare them against a whitelist of libtorch symbols, in which case if those printing functions are not used by the .so, they should not show up as undefined symbols. However, I think the unit tests I am adding is a way to guarantee those used symbols stay implemented in a header-only way.

2024-04-12 14:34 UTC, ezyang commented
I guess the point I want to make is that this PR is just rearranging chairs on the Titanic. Our ABI compatible requirement is that you have no dependency on C++ symbols (e.g., symbols from libstdc++). If the ostream function is in the cpp file, then you end up with a dependency on `operator<<`. But if the ostream function is in the header file, then you end up with a dependency on whatever bits from libstdc++ operator<< needs to work. Concretely:

```
(base) ezyang-mbp:~ ezyang$ cat a.cpp
#include <iostream>

int g(std::ostream& out, int x) {
  out << x;
  return x + 2;
}
(base) ezyang-mbp:~ ezyang$ clang++ -shared -O2 a.cpp
(base) ezyang-mbp:~ ezyang$ nm ./a.out 
0000000000003f88 T __Z1gRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEEi
                 U __ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEElsEi
```

Dependency on `__ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEElsEi` is big no no for ABI stability.

I think a compromise might be to have some sort of macro which disables "unsafe" functions from these headers, and then have that macro set when compiling AOTInductor. That will also prevent people from improperly using these fucntions.

2024-04-15 20:47 UTC, ezyang commented
Ah, this is the libstdc++ discussion that is also going on the other swolchok PR with thread_local signifier.

I guess this is a multi-objective optimization problem. If you are solely optimizing for ABI compatibility, it's best not to have libstdc++ at all, because while some of it stable, other parts of it are not (changes to std::string ABI are a particularly notable ABI change that has happened in living memory). I think if you are very careful, it is possible to stick to the parts of libstdc++ which haven't changed and are effectively stable.

2024-04-19 00:51 UTC, closed without merging