also clone cse cache
pytorch/pytorch pull request #124597
Opened 2024-04-22 06:47 UTC by zhuhaozhe

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-04-23 13:37 UTC, jgong5 requested changes

2024-04-24 01:32 UTC, zhuhaozhe commented on torch/_inductor/codegen/cpp.py
> +            with self.swap_buffers(code, cse_cache=self.cse.cache), code.indent():
> When new variables are defined in the scope, they cannot be used outside the scope afterwards. So, it is not safe to reuse the existing `self.cse.cache` here. I guess we want to create a wrapper around the cache abstraction that supports scoping, allowing variables and expressions defined within a scope to be valid only within that scope while still leveraging the existing cache from the outer scope before it. How about we create something like below?
> 
> ```python
> def scope_cse(cse):
>     new_cse = cse.clone()
>     new_cse.cache = ScopedDict(cse.cache)
>     new_cse.reduction_cache = ScopedDict(cse.reduction_cache)
>     new_cse.store_cache = ScopedDict(cse.store_cache)
>     return new_cse
> ```
> 
> Here the `ScopedDict` allows read-only access to the original dict while uses a separate dict to hold newly-added items:
> 
> ```python
> class ScopedDict:
>     def __init__(self, original_dict):
>         self.original_dict = original_dict
>         self.new_items = {}
>     
>     def __getitem__(self, key):
>         if key in self.new_items:
>             return self.new_items[key]
>         return self.original_dict[key]
>     
>     def __setitem__(self, key, value):
>         self.new_items[key] = value
>     
>     def __contains__(self, key):
>         return key in self.new_items or key in self.original_dict
>     
>     def get(self, key, default=None):
>         if key in self.new_items:
>             return self.new_items[key]
>         return self.original_dict.get(key, default)
> ```

Sounds better, I will try this way.

2024-04-25 11:35 UTC, zhuhaozhe commented
Hi, @jgong5. For this issue https://github.com/pytorch/pytorch/issues/123502, your recommendation for `ScopedDict` should not work because
```
            auto tmp8 =
            [&]
            {
                __at_align__ std::array<int64_t, 16> tmpbuf;
                tmp7.store(tmpbuf.data());
                return tmpbuf;
            }
            ()
            ;
            auto tmp9 =
            [&]
            {
                __at_align__ std::array<float, 16> tmpbuf;
                #pragma GCC unroll 16
                for (long x0_inner = 0; x0_inner < 16; x0_inner++)
                {
                    tmpbuf[x0_inner] = out_ptr0[static_cast<long>(tmp8[x0_inner])];
                }
                return at::vec::Vectorized<float>::loadu(tmpbuf.data());
            }
            ()
            ;
```
the `tmp8` is created inside this [scope](https://github.com/pytorch/pytorch/blob/58806d65317c1a890d536c0c347598bfb1ee337f/torch/_inductor/codegen/cpp.py#L2360) [here](https://github.com/pytorch/pytorch/blob/58806d65317c1a890d536c0c347598bfb1ee337f/torch/_inductor/codegen/cpp.py#L2352). But actually I observed the `tmp8` should be able to be used outside because the `buffer` here in `csevar = self.cse.generate(buffer, code)` is not inside the lambda function (of `tmp9`) scope.
```
For my current understanding we may not need to always put a `swap_buffer` after a `[&]`, for `_load_or_store_non_contiguous` ,should it be safe to remove `swap buffer` here?

2024-04-25 11:38 UTC, zhuhaozhe commented
As for the `ScopedDict`, it indeed help.
I found a case `test_AllenaiLongformerBase_repro_cpu` and make at as a UT in another PR https://github.com/pytorch/pytorch/pull/124921.
It will only generate `tmp_x=static_cast<int>(256)` once after `ScopedDict` impl, and it will be 3 times before it.

2024-04-26 02:08 UTC, jgong5 approved these changes

2024-04-26 15:23 UTC, jansel approved these changes

2024-04-28 01:00 UTC, zhuhaozhe commented
@pytorchbot merge

2024-04-28 01:02 UTC, closed without merging