[Aten] Fix convolution_overrideable input memory format.
pytorch/pytorch pull request #124841
Opened 2024-04-24 13:40 UTC by etaf

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #124841

2024-04-24 14:13 UTC, EikanWang approved these changes
Any test cases?

2024-04-24 18:38 UTC, etaf commented
> Any test cases?

Test case added.

2024-04-25 02:16 UTC, EikanWang requested changes

2024-04-25 02:16 UTC, EikanWang commented on test/xpu/test_conv.py
> +        dtype = torch.float32
We should verify different data types.

2024-04-25 02:16 UTC, EikanWang commented on test/xpu/test_conv.py
> +        assert_size_stride(out, (2, 512, 7, 7), (25088, 49, 7, 1))
It is xpu-specific. Please separate it from current case and add a decorator - `@onXPUOnly`

2024-04-25 02:17 UTC, EikanWang commented
@etaf , could you please check how to enhance ops to add such cases?

2024-04-25 02:22 UTC, jgong5 approved these changes

2024-04-25 05:30 UTC, EikanWang approved these changes

2024-04-25 05:53 UTC, EikanWang commented
@malfet , @albanD , @atalman , any comments?

2024-04-25 15:31 UTC, albanD commented
I'm not sure what the contract with backend_memory_format and convolution_overrideable is tbh. @jbschlosser do you know?
I would expect that the most generic thing we do here is to pass in the inputs as-is and if your implementation has contraints on the contiguousness, you should call .contiguous() inside your kernel.
The problem with the proposal here is that if your kernel was effectively handling non-contiguous inputs. We're introducing and extra full copy that you cannot opt-out of.

2024-04-26 02:35 UTC, EikanWang commented
The initial concept is that aligning with the backend-specific memory format may be a common practice for performance reasons. Thank you, @albanD. We will enhance the PR by transferring the modification to XPU-Conv.

2024-04-26 06:55 UTC, EikanWang approved these changes
LGTM.

2024-04-26 14:24 UTC, albanD approved these changes
Thanks for the update, SGTM

2024-04-26 15:50 UTC, etaf commented
@pytorchbot merge

2024-04-26 15:53 UTC, etaf commented
@pytorchbot merge

2024-04-26 15:55 UTC, closed without merging