[BE] Remove JNI from libtorch builds
pytorch/pytorch pull request #124995
Opened 2024-04-26 02:00 UTC by PaliC

Fixes #ISSUE_NUMBER

2024-05-17 16:06 UTC, atalman requested changes
Could you please add more context here why we want to stop distributing these ? Will people using Java will still be able to use libtorch ? etc...

2024-06-15 00:06 UTC, malfet approved these changes
LGTM

2024-06-16 01:09 UTC, PaliC commented
@pytorchbot merge

2024-06-16 01:18 UTC, PaliC commented
@pytorchbot merge -i

2024-06-21 22:26 UTC, PaliC commented
@pytorchbot merge -r

2024-06-22 05:45 UTC, PaliC commented
@pytorchbot merge -i

2024-06-22 07:41 UTC, closed without merging