[ATen][CUDA][AMP] Fix dtype mismatch in linalg_vector_norm
pytorch/pytorch pull request #125175
Opened 2024-04-29 18:02 UTC by Aidyn-A

Fixes #125174
cc @eqy @nWEIdia @tinglvv 

TODO: add unit-test

2024-04-29 18:07 UTC, eqy approved these changes

2024-04-29 21:18 UTC, eqy commented on aten/src/ATen/native/LinearAlgebra.cpp
> +    self.copy_(self_);
Is this allowed if we have `const& self`

2024-04-30 04:30 UTC, lezcano requested changes

2024-04-30 04:30 UTC, lezcano commented on aten/src/ATen/native/LinearAlgebra.cpp
> +    self.copy_(self_);
??
The returned tensor is `result`. Here you are potentially changing the input tensor!

2024-04-30 20:16 UTC, Aidyn-A commented
I believe the test failure is unrelated. @lezcano, can you take another look?

2024-05-01 07:51 UTC, lezcano approved these changes
This is more reasonable. Thank you!

2024-05-01 07:52 UTC, lezcano commented
@pytorchbot merge -i

2024-05-01 10:57 UTC, closed without merging