CI: aarch64 linux: upgrade ACL version to 24.04 and skip test_mkldnn
pytorch/pytorch pull request #125549
Opened 2024-05-05 10:35 UTC by snadampal

Fixes #ISSUE_NUMBER

2024-05-05 14:15 UTC, snadampal commented
The 2 CI failures seem to be unrelated to this PR. 
cc: @atalman , @malfet

2024-05-06 16:56 UTC, atalman approved these changes
LGTM. Please rebase to fix lint issue

2024-05-06 18:02 UTC, malfet requested changes
I don't think it's a good idea, we should revert the offending PR and figure out how to update oneDNN without regressing ARMs

2024-05-07 05:26 UTC, snadampal commented
Hi @malfet , @atalman , I have posted my findings about the regression on the test_mkldnn failure issue, https://github.com/pytorch/pytorch/issues/125548#issuecomment-2097466615
looks like the new versions are uncovering some existing issue.

2024-05-08 17:02 UTC, snadampal commented
I have updated this PR to limit it to ACL version update alone, and this has to before/along relanding https://github.com/pytorch/pytorch/pull/122472

The other failures in the CI are being addressed separately:
1. test_mkldnn failure in https://github.com/pytorch/pytorch/issues/125548
2. dynamo/test_model_output failure in https://github.com/pytorch/pytorch/pull/125761

2024-05-28 17:58 UTC, snadampal commented
this is imported and merged in this PR https://github.com/pytorch/pytorch/pull/126137

2024-05-28 17:58 UTC, closed without merging