bool inherited from number
pytorch/pytorch pull request #125577
Opened 2024-05-06 08:49 UTC by Ma-Jian1

Fixes #125003

2024-05-09 03:36 UTC, colesbury commented
@EikanWang - would you please review this PR?

2024-05-09 08:18 UTC, EikanWang commented
LGTM.

2024-05-09 08:19 UTC, EikanWang approved these changes

2024-05-09 13:58 UTC, EikanWang requested changes
Please fix UT failures.

2024-05-14 07:02 UTC, jgong5 approved these changes

2024-05-15 05:18 UTC, Ma-Jian1 commented
@ezyang Could you help to take a review?

2024-05-15 14:38 UTC, ezyang commented
You are still failing a bunch of tests

2024-05-20 05:29 UTC, Ma-Jian1 commented
hi all,
`torch/optim/asgd.py` is not part of this patch. what should I do next?
@EikanWang @ezyang

2024-05-21 00:24 UTC, ezyang commented
@pytorchbot merge -r

2024-05-21 01:43 UTC, ezyang commented
I am not convinced I want to deal with the fallout from this in TorchScript. @davidberard98 for a second opinion

2024-05-22 16:42 UTC, davidberard98 commented
I'm seeing internal failures - not sure if I'll be able to get to this for a few days, but I'll need to take a closer look to understand what's failing. I'll report back once I have a better understanding.

2024-06-12 06:24 UTC, Ma-Jian1 commented
hi @davidberard98 ，does it still failed on your test？

2024-06-12 16:21 UTC, davidberard98 commented
@Ma-Jian1 yes - do you think you can check using torchvision to better understand the failures?

2024-06-13 03:49 UTC, Ma-Jian1 commented
hi @davidberard98 ，I clone torchvision into local pytorch fold，and run `python setup.py develop` in torchvision subfolder, and then ` python -m pytest -sv test/test_transforms_tensor.py -k test_convert_image_dtype`, I can reproduce 3 failed cases.
but after I reverted my patch, the failure still existed. 
seems not related to my patch?

investigated further:
I found the max_int literal `2147483647.0` will be captured as `2147483648.` in torch.script, so weird.

``` cpp
test/test_transforms_tensor.py::test_convert_image_dtype[out_dtype0-in_dtype0-cpu] graph(%image.1 : Tensor,
      %dtype.1 : int):
  %382 : int = prim::Constant[value=4294967294]()
  %377 : float = prim::Constant[value=9.2233720368547758e+18]()
  %376 : float = prim::Constant[value=2147483648.]()
  %333 : Function = prim::Constant[name="_max_value"]()
  %332 : str = prim::Constant[value="builtins.RuntimeError"]() # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:79:18
  %329 : str = prim::Constant[value="The cast from {} to {} cannot be performed safely."]() # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:78:18
  %321 : int = prim::Constant[value=7]() # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:76:27
  %319 : bool = prim::Constant[value=1]() # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:75:12
  %312 : int = prim::Constant[value=4]() # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:75:68
  %311 : int = prim::Constant[value=3]() # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:75:55
  %307 : int = prim::Constant[value=6]() # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:75:27
  %206 : bool = prim::Constant[value=0]()
  %205 : NoneType = prim::Constant()
  %12 : int = prim::Constant[value=0]() # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:71:24
  %64 : float = prim::Constant[value=0.001]() # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:86:14
  %72 : float = prim::Constant[value=1.]() # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:88:37
  %3 : int = prim::dtype(%image.1)
  %5 : bool = aten::eq(%3, %dtype.1) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:65:7
  %305 : Tensor = prim::If(%5) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:65:4
    block0():
      -> (%image.1)
    block1():
      %198 : bool = aten::is_floating_point(%image.1) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:68:7
      %201 : Tensor = prim::If(%198) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:68:4
        block0():
          %207 : Tensor = aten::tensor(%12, %dtype.1, %205, %206) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:71:11
          %208 : bool = aten::is_floating_point(%207) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:71:11
          %345 : Tensor = prim::If(%208) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:71:8
            block0():
              %215 : Tensor = aten::to(%image.1, %dtype.1, %206, %206, %205) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:72:19
              -> (%215)
            block1():
              %306 : int = prim::dtype(%image.1)
              %308 : bool = aten::eq(%306, %307) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:75:12
              %310 : bool = prim::If(%308) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:75:12
                block0():
                  %314 : int[] = prim::ListConstruct(%311, %312)
                  %315 : bool = aten::__contains__(%314, %dtype.1) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:75:45
                  -> (%315)
                block1():
                  -> (%206)
              %318 : bool = prim::If(%310) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:75:12
                block0():
                  -> (%319)
                block1():
                  %320 : int = prim::dtype(%image.1)
                  %322 : bool = aten::eq(%320, %321) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:76:12
                  %324 : bool = prim::If(%322) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:76:12
                    block0():
                      %326 : bool = aten::eq(%dtype.1, %312) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:76:45
                      -> (%326)
                    block1():
                      -> (%206)
                  -> (%324)
               = prim::If(%318) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:75:8
                block0():
                  %330 : int = prim::dtype(%image.1)
                  %msg.7 : str = aten::format(%329, %330, %dtype.1) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:78:18
                   = prim::RaiseException(%msg.7, %332) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:79:12
                  -> ()
                block1():
                  -> ()
              %334 : int = prim::CallFunction(%333, %dtype.1) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:87:24
              %max_val.7 : float = aten::Float(%334) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:87:18
              %337 : float = aten::add(%max_val.7, %72) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:88:27
              %338 : float = aten::sub(%337, %64) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:88:27
              %result.7 : Tensor = aten::mul(%image.1, %338) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:88:17
              %343 : Tensor = aten::to(%result.7, %dtype.1, %206, %206, %205) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:89:15
              -> (%343)
          -> (%345)
        block1():
           = prim::Print(%376) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:93:8
          %263 : Tensor = aten::tensor(%12, %dtype.1, %205, %206) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:97:11
          %264 : bool = aten::is_floating_point(%263) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:97:11
          %375 : Tensor = prim::If(%264) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:97:8
            block0():
              %image.65 : Tensor = aten::to(%image.1, %dtype.1, %206, %206, %205) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:98:20
              %273 : Tensor = aten::div(%image.65, %376) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:99:19
              -> (%273)
            block1():
               = prim::Print(%377) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:103:8
               = prim::Print(%377, %376, %382) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:116:12
              %image.91 : Tensor = aten::to(%image.1, %dtype.1, %206, %206, %205) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:117:20
              %373 : Tensor = aten::mul(%image.91, %382) # /home/jianma/repo/pytorch/vision/torchvision/transforms/_functional_tensor.py:118:19
              -> (%373)
          ->  [...]

2024-06-24 03:29 UTC, Ma-Jian1 commented
I have to run "pip uninstall torch" **several times** to clean the virtual env.
now verified that the test passed without this patch.

2024-06-26 07:54 UTC, Ma-Jian1 commented
hi @davidberard98, the failed case in torchvision is related to cast int to float, which has an accuracy issue.
fixed it and add an extra unit test.

2024-07-02 01:07 UTC, Ma-Jian1 commented
hi @davidberard98 , 
could you help to take a review?
I have no mac device, and it shouldn't affect this unit test.

2024-08-07 06:07 UTC, Ma-Jian1 commented
@ezyang @davidberard98 Could you help to resolve the “Meta Internal-Only Changes Check”

2024-08-23 02:16 UTC, EikanWang approved these changes

2024-12-05 08:39 UTC, closed without merging

2025-02-26 08:14 UTC, zhejiangxiaomai commented
Hi, @davidberard98. We found this PR to be quite important during testing. Can we rebase and merge it in? me and @majian4work  can do rebase work.

2025-03-04 01:54 UTC, zhejiangxiaomai commented
Hi @davidberard98 Any suggestion?

2025-03-20 02:20 UTC, zhejiangxiaomai commented
Hi @davidberard98, can you please take a look at my comment?