Enable ufmt on test/test_expanded_weights.py
pytorch/pytorch pull request #125675
Opened 2024-05-07 10:52 UTC by huniu20

Part of #123062 
cc @ezyang

2024-05-09 00:16 UTC, ezyang approved these changes

2024-05-09 00:17 UTC, ezyang commented
@pytorchbot merge

2024-05-09 15:49 UTC, malfet requested changes
@ezyang not sure why you've approved this PR, all it does is adding more files to exclude patterns, which seems contrary to the PR title

2024-05-10 00:06 UTC, ezyang commented
oh no we botched the merge 🤣

2024-05-10 00:06 UTC, closed without merging