[CI]enable AMP accuracy test for inductor on SPR CPU
pytorch/pytorch pull request #125748
Opened 2024-05-08 08:55 UTC by DiweiSun

Fixes #ISSUE_NUMBER

2024-05-08 09:38 UTC, chuanqi129 commented on .github/workflows/inductor.yml
> +          { config: "dynamic_cpu_inductor_huggingface_amp", shard: 1, num_shards: 1, runner: "linux.c7i.metal-24xl" },
Let's add amp static shape as the first step

2024-05-08 09:38 UTC, chuanqi129 commented on .github/workflows/inductor.yml
> +          { config: "cpu_inductor_torchbenc_amp", shard: 2, num_shards: 2, runner: "linux.c7i.metal-24xl" },
```suggestion
          { config: "cpu_inductor_huggingface_amp", shard: 1, num_shards: 1, runner: "linux.16xlarge.spr" },
          { config: "cpu_inductor_timm_amp", shard: 1, num_shards: 2, runner: "linux.16xlarge.spr" },
          { config: "cpu_inductor_timm_amp", shard: 2, num_shards: 2, runner: "linux.16xlarge.spr" },
          { config: "cpu_inductor_torchbench_amp", shard: 1, num_shards: 2, runner: "linux.16xlarge.spr" },
          { config: "cpu_inductor_torchbenc_amp", shard: 2, num_shards: 2, runner: "linux.16xlarge.spr" },
```

2024-05-08 09:38 UTC, chuanqi129 commented on .github/workflows/inductor.yml
> +          { config: "cpu_inductor_torchbenc_amp", shard: 2, num_shards: 2, runner: "linux.c7i.metal-24xl" },
runner label refer to https://github.com/pytorch/test-infra/blob/main/.github/scale-config.yml#L36

2024-05-08 09:38 UTC, chuanqi129 commented on .ci/pytorch/test.sh
> +      fi
```suggestion
      local dt="float32"
      if [[ "${TEST_CONFIG}" == *amp* ]]; then
        dt="amp"
      fi
      test_single_dynamo_benchmark "inference" "$suite" "$shard_id" --inference --"$dt" "$@"
```

2024-05-08 09:59 UTC, chuanqi129 approved these changes

2024-05-08 10:05 UTC, jgong5 approved these changes

2024-05-09 02:17 UTC, desertfire requested changes

2024-05-09 03:41 UTC, DiweiSun commented on .github/workflows/inductor.yml
> +          { config: "cpu_inductor_torchbenc_amp", shard: 2, num_shards: 2, runner: "linux.16xlarge.spr" },
Oops, sorry for the typo. Corrected. 

Thanks!

2024-05-09 03:57 UTC, DiweiSun commented
@jgong5 , could you please kindly help review it again? Thanks

2024-05-16 18:31 UTC, desertfire approved these changes

2024-05-17 03:06 UTC, chuanqi129 commented
@pytorchbot rebase

2024-05-20 08:12 UTC, DiweiSun commented
All failures happens on NVDIA GPU, however the PR is not supposed to impact on them.

2024-05-29 21:58 UTC, atalman approved these changes

2024-06-03 10:35 UTC, DiweiSun commented
@pytorchbot rebase

2024-06-03 10:37 UTC, closed without merging

2024-06-03 10:37 UTC, lezcano commented
Bad rebase. Too many people tagged. Please submit a new PR.