Fix CMake find Torch script
pytorch/pytorch pull request #12570
Opened 2018-10-11 17:21 UTC by fmder

On Windows, when using torch we get torch-NOTFOUND as linked library. Reusing the found library should be done with ${TORCH_LIBRARY}.

2018-10-11 18:27 UTC, ezyang requested changes
Seems to break OS X

2018-10-11 18:36 UTC, orionr commented
cc @anderspapitto as well

2018-10-11 19:21 UTC, fmder commented
I think the CMakeLists.txt in the test is missing

``target_include_directory(test_custom_ops PRIVATE ${TORCH_INCLUDE_DIRS})``

2018-10-13 20:51 UTC, goldsborough commented
I've been trying to get this working on Windows forever now. It's all in https://github.com/pytorch/pytorch/pull/11527

I don't think that `torch` should be replaced with `TORCH_LIBRARY`, because you should be linking against the target, not the library directly. The target also brings along headers in its interface, so you wouldn't have to and shouldn't have to set `target_include_directories(test_custom_ops SHARED ${TORCH_INCLUDE_DIRS})`. All you should need to do in user-space cmake is `target_link_libraries(my_lib torch)` and everything else gets pulled in via the interface.

I'll try to get this working sooner. @orionr maybe you have time to look into it too.

2018-10-23 14:41 UTC, fmder commented
I'm far from being an expert on cmake, but the traditional way of doing things in FindModule.cmake (as I see it) is to provide a list of libraries in NAME_LIBRARIES and a list of include directories in NAME_INCLUDE_DIRS. The FindModule.cmake is not supposed to build anything nor create any target.

2018-10-23 16:45 UTC, goldsborough commented
@fmder that's indeed the traditional way, but the modern way is to set up your libraries interface such that the user need not add dependencies manually, but instead just automatically gets them pulled in by CMake. The fix (https://github.com/pytorch/pytorch/pull/12928) is now landed btw. Please try it out.

2022-07-11 02:16 UTC, closed without merging