Xu add new cpp builder 5
pytorch/pytorch pull request #125849
Opened 2024-05-09 15:50 UTC by xuhancn

Fully manual rebase the code of PR: https://github.com/pytorch/pytorch/pull/124045
The old PR seems crashed due to too many rebase.

2024-05-10 02:21 UTC, jgong5 approved these changes

2024-05-11 17:16 UTC, jansel commented
I'll let @desertfire handle the review/landing here.

2024-05-15 02:27 UTC, desertfire commented
Internal test failure, `CUDA_HOME` not set, although I haven't dug into why.
```
  File "/dev/shm/uid-30083/5b4bda56-seed-nspid4026534425_cgpid3897394-ns-4026534632/torch/_inductor/codecache.py", line 2320, in load_async
    name="o", sources="i", BuildOption=CppTorchCudaOptions(**compile_command)
  File "/dev/shm/uid-30083/5b4bda56-seed-nspid4026534425_cgpid3897394-ns-4026534632/torch/_inductor/cpp_builder.py", line 912, in __init__
    ) = get_cpp_torch_cuda_options(aot_mode=aot_mode)
  File "/dev/shm/uid-30083/5b4bda56-seed-nspid4026534425_cgpid3897394-ns-4026534632/torch/_inductor/cpp_builder.py", line 855, in get_cpp_torch_cuda_options
    ) = _get_cuda_related_args(aot_mode)
  File "/dev/shm/uid-30083/5b4bda56-seed-nspid4026534425_cgpid3897394-ns-4026534632/torch/_inductor/cpp_builder.py", line 779, in _get_cuda_related_args
    include_dirs = cpp_extension.include_paths(cuda)
  File "/dev/shm/uid-30083/5b4bda56-seed-nspid4026534425_cgpid3897394-ns-4026534632/torch/utils/cpp_extension.py", line 1171, in include_paths
    cuda_home_include = _join_cuda_home('include')
  File "/dev/shm/uid-30083/5b4bda56-seed-nspid4026534425_cgpid3897394-ns-4026534632/torch/utils/cpp_extension.py", line 2417, in _join_cuda_home
    raise OSError('CUDA_HOME environment variable is not set. '
 ```

2024-05-15 12:02 UTC, xuhancn commented
> Internal test failure, `CUDA_HOME` not set, although I haven't dug into why.
> 
> ```
>   File "/dev/shm/uid-30083/5b4bda56-seed-nspid4026534425_cgpid3897394-ns-4026534632/torch/_inductor/codecache.py", line 2320, in load_async
>     name="o", sources="i", BuildOption=CppTorchCudaOptions(**compile_command)
>   File "/dev/shm/uid-30083/5b4bda56-seed-nspid4026534425_cgpid3897394-ns-4026534632/torch/_inductor/cpp_builder.py", line 912, in __init__
>     ) = get_cpp_torch_cuda_options(aot_mode=aot_mode)
>   File "/dev/shm/uid-30083/5b4bda56-seed-nspid4026534425_cgpid3897394-ns-4026534632/torch/_inductor/cpp_builder.py", line 855, in get_cpp_torch_cuda_options
>     ) = _get_cuda_related_args(aot_mode)
>   File "/dev/shm/uid-30083/5b4bda56-seed-nspid4026534425_cgpid3897394-ns-4026534632/torch/_inductor/cpp_builder.py", line 779, in _get_cuda_related_args
>     include_dirs = cpp_extension.include_paths(cuda)
>   File "/dev/shm/uid-30083/5b4bda56-seed-nspid4026534425_cgpid3897394-ns-4026534632/torch/utils/cpp_extension.py", line 1171, in include_paths
>     cuda_home_include = _join_cuda_home('include')
>   File "/dev/shm/uid-30083/5b4bda56-seed-nspid4026534425_cgpid3897394-ns-4026534632/torch/utils/cpp_extension.py", line 2417, in _join_cuda_home
>     raise OSError('CUDA_HOME environment variable is not set. '
> ```

Some debug discussion sent to you via slack, thanks. @desertfire

2024-05-16 20:33 UTC, desertfire commented
> Some debug discussion sent to you via slack, thanks. @desertfire

https://github.com/pytorch/pytorch/pull/126408/ should solve this CUDA_HOME not set issue.

2024-05-17 06:58 UTC, xuhancn commented
@pytorchbot rebase

2024-05-17 21:52 UTC, int3 commented
JFYI I'm on PTO and won't be able to land https://github.com/pytorch/pytorch/pull/126408 till Tuesday

2024-05-25 16:59 UTC, xuhancn commented
> > Some debug discussion sent to you via slack, thanks. @desertfire
> 
> #126408 should solve this CUDA_HOME not set issue. You need to rebase after that one lands. After that, I will give another try in fbcode.

I have synced code to https://github.com/pytorch/pytorch/pull/126408 , @desertfire please help on import fb_code to validate, much appreciated.

2024-05-30 13:14 UTC, desertfire requested changes

2024-05-30 13:14 UTC, desertfire commented on torch/_inductor/codecache.py
> +
Thanks to @int3 , adding `_set_gpu_runtime_env()  # cpp_extension consults the env` here makes fbcode tests pass.

2024-05-30 19:55 UTC, xuhancn commented
@desertfire apply code follow your request, please take a look.

2024-05-31 03:23 UTC, xuhancn commented
@pytorchmergebot rebase

2024-06-04 05:35 UTC, xuhancn commented
@pytorchmergebot rebase

2024-06-04 13:06 UTC, xuhancn commented
@desertfire fixed some fb_code issues from new cpp_builder.

2024-06-05 05:15 UTC, desertfire commented
test_new_cpp_build_logical still fails because of missing openmp and python include paths, https://github.com/pytorch/pytorch/blob/30788739f4cec672cdabc21c155bbe30ac5d66e6/torch/_inductor/codecache.py#L1755-L1756 . Other than that, there are macro definition differences like '-DC10_USE_GLOG' vs. '-D C10_USE_GLOG' which is benign, but it does mean you need to either relax your testing, or just skip it for fbcode.

2024-06-05 05:15 UTC, desertfire commented on torch/_inductor/codecache.py
> +    input_path = "/temp/dummy_input.cpp"
Can you use `tempfile.TemporaryDirectory()` instead of hard-code it?

2024-06-06 00:35 UTC, xuhancn commented
@desertfire try to fixed use_absolute_path in fb_code.

2024-06-06 04:37 UTC, xuhancn commented
@desertfire fix fb_code issues:
1. omp lib.
2. torch, torch_cpu and torch_python libs.

2024-06-06 16:54 UTC, xuhancn commented
@desertfire update code:
1. Sync _get_python_include_dirs to new cpp_builder.
2. Fix fb_code cuda include.

2024-06-06 21:41 UTC, desertfire approved these changes

2024-06-07 00:04 UTC, xuhancn commented
@pytorchmergebot merge

2024-06-07 00:15 UTC, xuhancn commented
> ## Merge failed
> **Reason**: 1 jobs have failed, first few of them are: [Meta Internal-Only Changes Check](https://opensource.facebook.com/)
> 
> Details for Dev Infra team

@desertfire How to solve this issue?

2024-06-07 00:24 UTC, xuhancn commented
@pytorchmergebot merge

2024-06-07 05:39 UTC, xuhancn commented
@pytorchmergebot merge

2024-06-07 11:44 UTC, xuhancn commented
@pytorchmergebot merge

2024-06-07 12:26 UTC, xuhancn commented
@pytorchmergebot rebase

2024-06-07 18:20 UTC, xuhancn commented
@pytorchmergebot merge

2024-06-07 19:23 UTC, xuhancn commented
@pytorchmergebot merge

2024-06-07 20:50 UTC, closed without merging