Don't run addruntimeassertion pass
pytorch/pytorch pull request #125948
Opened 2024-05-10 18:53 UTC by tugsbayasgalan

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #125948
* #125860

2024-05-10 19:01 UTC, zhxchen17 requested changes

2024-05-10 19:01 UTC, zhxchen17 commented on torch/fx/proxy.py
> +        if kind == "call_function" and "mul_2" in str(args):
lol

2024-05-10 19:02 UTC, zhxchen17 approved these changes

2024-05-21 18:12 UTC, tugsbayasgalan commented
@tugsbayasgalan has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D57630436).

2024-06-24 18:59 UTC, tugsbayasgalan commented
@tugsbayasgalan has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D57630436).

2024-09-24 00:49 UTC, closed without merging