add VectorizedN support for welford_vec_reduce_all and add float<->bf16/fp16 conversion specialization for VectorizedN
pytorch/pytorch pull request #126500
Opened 2024-05-17 02:08 UTC by CaoE

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-08-21 03:26 UTC, jgong5 requested changes
Please fix CI failures...

2024-08-26 04:06 UTC, jgong5 approved these changes

2024-08-27 14:47 UTC, CaoE commented on torch/_inductor/codegen/cpp_prefix.h
> +  return welford_combine(result0, result1);
Thanks for your comments. This change has been merged in another PR.

2024-08-27 14:47 UTC, CaoE commented
@peterbell10 Could you please review this PR ? Thank you.

2024-08-29 15:57 UTC, jansel approved these changes

2024-09-03 01:59 UTC, CaoE commented
@pytorchbot merge

2024-09-03 02:02 UTC, CaoE commented
@pytorchbot merge

2024-09-03 02:09 UTC, closed without merging