Update _dedup_save_plans.py
pytorch/pytorch pull request #126569
Opened 2024-05-17 19:52 UTC by bigning

To resolve https://github.com/pytorch/pytorch/issues/125740, save each tensor on the lowest rank.

Fixes #125740

2024-05-17 19:57 UTC, LucasLLC requested changes
At minimum, we would need this to be optional and it should not replace the current deduplication logic. The current logic is a storage optimization, and this would cause a regression in terms of calling dcp.save on models which are replica heavy.

I think in the originally linked issue, we considered not applying this logic to scalars as a fix for minimizing the number of files which need to be loaded

2024-05-17 20:12 UTC, bigning commented
>  The current logic is a storage optimization, and this would cause a regression in terms of calling dcp.save on models which are replica heavy.

it's "optimization" only in terms of saving balance. But it hurts the loading performance in multi-node case. 

> we considered not applying this logic to scalars as a fix

i don't think that works. The root cause is the duplicated tensors are saved in different files, no matter if it's scalar tensor or not.

2024-05-17 20:20 UTC, bigning commented
@LucasLLC , i replied to your comment. Could you please take a look ?

2024-05-20 13:53 UTC, LucasLLC commented
@bigning , I believe this generally this isn't seen as a large issue during saving since files are all expected to live in the same NFS directory. Could we change this PR to make the de-duplication optional (and true by default)?

2024-05-20 14:31 UTC, Skylion007 commented on torch/distributed/checkpoint/_dedup_save_plans.py
> +        select_plan_idx = min(plan_indices, key=lambda plan_idx: plan_idx)
```suggestion
        select_plan_idx = min(plan_indices)
```

2024-05-20 16:53 UTC, bigning commented
> make the de-duplication optional 

If we skip the dedup, it fails here https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/default_planner.py#L386-L387. 

> files are all expected to live in the same NFS directory.

For NFS, the issue is not about if the file exists in the NFS. It's that each node needs to download the Nx times more files. If it's using cloud, this introduces:
1. Nx cloud storage money cost for downloading more data
2. Nx more time blocking the training. For saving, it can be async, but for loading, usually loading checkpointing blocks the training. 
3. Downloading large files from cloud is not stable, this is really a pain point for using cloud storage. The more files you download, the more chance the checkpointing downloading fails. 

Can I just add a `save_to_same_rank`  param to `dedup_save_plans` and `DefaultSavePlanner` ?

2024-05-21 00:23 UTC, LucasLLC commented
> Can I just add a `save_to_same_rank` param to `dedup_save_plans` and `DefaultSavePlanner`

@bigning I understand the pain points in having to download multiple files. I think we would accept a PR which makes this behavior configurable.

2024-05-21 19:06 UTC, bigning commented
> makes this behavior configurable.

@LucasLLC , this makes sense. I added a param to `dedup_save_plans` and `DefaultSavePlanner`, could you take a look? Thanks!

2024-05-22 21:35 UTC, LucasLLC commented
Thanks @bigning ! This looks good to me. Will merge if tests pass

2024-05-22 21:35 UTC, LucasLLC approved these changes

2024-05-23 16:21 UTC, bigning commented
thanks @LucasLLC , it seems two lints failed, I can't find useful error message, do you know how to fix or how to re-run?

2024-05-23 21:26 UTC, bigning commented
> thanks @LucasLLC , it seems two lints failed, I can't find useful error message, do you know how to fix or how to re-run?

NVM, i just submitted another commit. Looks all tests are green now.

2024-05-31 14:59 UTC, LucasLLC commented
@pytorchbot merge

2024-05-31 17:06 UTC, bigning commented
@pytorchbot merge

2024-05-31 19:52 UTC, LucasLLC commented
@pytorchbot merge

2024-06-03 01:52 UTC, bigning commented
@pytorchbot merge

2024-06-03 01:55 UTC, closed without merging

2024-07-02 10:04 UTC, johnmullan commented
@bigning would this PR allow me to pull down specific `__{rank}_0.distcp` files from cloud storage onto a local NVME (provided world size stays same) and load from there? For more context I'm trying to prevent loading from an NFS to improve start up times.

2024-07-02 17:45 UTC, bigning commented
yeah, this PR allows you to download as few files as possible for each rank. Before this PR, if you have non-sharded tensors in the state dict that are needed by each rank, those tensors would be saved to different files. So each rank needs to download many files. After the PR, those non-sharded tensors are only saved to one file.