[Inductor] Fix bug in MutationOutput IR
pytorch/pytorch pull request #127516
Opened 2024-05-30 08:49 UTC by Xia-Weiwen

Fixes #127402

https://github.com/pytorch/pytorch/pull/127151 made some changes to the MutationOutput IR. In the constructor, an argument is missing when calling its parent's constructor.

The issue can be reproduced by the following script (run with `TORCHINDUCTOR_FREEZING=1`):
```python
import torch
from torch._export import capture_pre_autograd_graph
from torch.ao.quantization.quantize_pt2e import (
    convert_pt2e,
    prepare_pt2e,
)
from torch.ao.quantization.quantizer.x86_inductor_quantizer import X86InductorQuantizer
import torch.ao.quantization.quantizer.x86_inductor_quantizer as xiq

class M(torch.nn.Module):
    def __init__(
        self,
        add_fn,
    ):
        super().__init__()
        self.linear1 = torch.nn.Linear(4, 4)
        self.linear2 = torch.nn.Linear(4, 4)
        self.add_fn = add_fn
        self.relu = torch.nn.ReLU()
        self.linear3 = torch.nn.Linear(4, 4)
        self.linear4 = torch.nn.Linear(4, 4)
        self.add_fn2 = add_fn
        self.relu2 = torch.nn.ReLU()

    def forward(self, x):
        x1 = self.linear1(x)
        x2 = self.linear2(x)
        tmp = self.add_fn(x1, x2)
        return tmp
        # tmp1 = self.linear3(tmp)
        # tmp2 = self.linear4(tmp)
        # res = self.add_fn2(tmp1, tmp2)
        # return res

add_fn = lambda x, y: x.add_(y)
mod = M(add_fn)
x = torch.randn((4, 4), dtype=torch.float32, requires_grad=False).add(1)
inputs = (x,)

with torch.no_grad():
    export_model = capture_pre_autograd_graph(mod, inputs)
    quantizer = X86InductorQuantizer()
    quantizer.set_global(
        xiq.get_default_x86_inductor_quantization_config()
    )

    prepare_model = prepare_pt2e(export_model, quantizer)
    prepare_model(*inputs)
    convert_model = convert_pt2e(prepare_model)
    torch.ao.quantization.move_exported_model_to_eval(convert_model)
    print(convert_model)

    out_ref = convert_model(*inputs)
    compiled_model = torch.compile(convert_model)
    compiled_model(*inputs)
    out = compiled_model(*inputs)
    print(torch.allclose(out_ref, out))
    print(torch.abs(out_ref - out).max())
```

Without this fix, a linear op is missing in the generated code.

2024-05-30 09:37 UTC, leslie-fang-intel approved these changes

2024-05-30 14:12 UTC, peterbell10 requested changes
Can you add a test?

2024-05-30 18:34 UTC, Chillee commented
Hm... that change was actually deliberate. Is the breakage a correctness or performance issue?

2024-05-30 18:34 UTC, Chillee requested changes
Hm... that change was actually deliberate. Is the breakage a correctness or performance issue?

2024-05-30 23:55 UTC, leslie-fang-intel commented
Hi @Chillee, I think it breaks the correctness.

2024-05-31 01:54 UTC, leslie-fang-intel commented
One another Question is `ConvolutionBinaryInplace` doesn't have similar issue. It looks like a `QLinearPointwiseBinaryPT2E` specific issue. Could we further compare what's the difference between these 2 IRs?

2024-05-31 02:37 UTC, Xia-Weiwen commented
@leslie-fang-intel  @Chillee  Thanks for the inputs. The issue will be fixed via a change to QLinearPointwiseBinaryPT2E IR: https://github.com/pytorch/pytorch/pull/127592. So, close this PR.

2024-05-31 02:37 UTC, closed without merging