Handle aten::__contains__ during TorchScript to ExportedProgram conversion
pytorch/pytorch pull request #127544
Opened 2024-05-30 17:24 UTC by jiashenC

2024-05-30 17:24 UTC, jiashenC commented on torch/_export/converter.py
> +        elif node_kind == "prim::device":
Unrelated changes brought from https://github.com/pytorch/pytorch/pull/127466

2024-05-30 17:30 UTC, angelayi approved these changes

2024-05-31 23:17 UTC, BoyuanFeng requested changes

2024-06-04 15:46 UTC, vadimkantorov commented
Maybe some useful feedbacks on me recently trying to execute TorchScript code printouts in eager PyTorch: https://github.com/pytorch/pytorch/issues/41625#issuecomment-2147682813

It would be nice to be able to have an automated working converter towards a graph (or a code printout as well - better for debugging)

2024-06-05 00:15 UTC, angelayi approved these changes

2024-06-06 04:58 UTC, jiashenC commented
@pytorchbot merge -f "skip regressed tests"

2024-06-06 05:00 UTC, closed without merging