[dynamo] Fix graph breaks related to HF ModelOutput
pytorch/pytorch pull request #127780
Opened 2024-06-03 18:04 UTC by williamwen42

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #127780

2024-06-04 00:25 UTC, jansel requested changes
Test failures?

2024-06-07 23:40 UTC, anijain2305 approved these changes
Nice!

2024-06-11 23:33 UTC, jansel approved these changes

2024-06-11 23:43 UTC, williamwen42 commented
@pytorchbot merge

2024-06-12 02:16 UTC, closed without merging