Update start method docstring for  profiler.py
pytorch/pytorch pull request #128098
Opened 2024-06-06 02:29 UTC by anandptl84

document https://github.com/pytorch/pytorch/issues/127917 start function of cuda/ profiler.py

Fixes #ISSUE_NUMBER

2024-06-11 20:23 UTC, aaronenyeshi approved these changes
Could we also document the other apis?

2024-06-11 21:00 UTC, davidberard98 requested changes

2024-06-11 21:00 UTC, davidberard98 commented on torch/cuda/profiler.py
> +        >>> profiler.start()
I think the usage would be more like `torch.cuda.profiler.start()`, I don't think there's a `Profiler()` object that would have to be constructed first

2024-06-12 14:30 UTC, malfet commented
@pytorchbot merge

2024-06-13 23:53 UTC, davidberard98 commented
@pytorchbot merge

2024-06-14 01:44 UTC, closed without merging