Add simple scripts for checking if generated code changed.
pytorch/pytorch pull request #12835
Opened 2018-10-18 20:41 UTC by gchanan

This is designed to make it easier to see how your codegen changes affected actual generated code.

Limitations:
A) This is NOT robust; if new directories are added that include generated files, they need to be added to tools/generated_dirs.txt.  Note that subdirectories of the list are not included.

B) This is particular to my workflow which I don't claim is generally applicable.  Ideally we would have a script that pumped out a diff that could be attached to PRs.

C) Only works on OSS and definitely won't work on windows.

How to use:
1) python setup.py ...
2) tools/git_add_generated_dirs
3) Edit codegen
4) python setup.py ...
4) git diff to see changes
5) If satisfied: tools/git_reset_generated_dirs, commit, etc.
   If not satisfied: Go to 3)

2018-10-18 20:42 UTC, gchanan commented
I am happy to be told these are too specific for my workflow and we shouldn't bless it by putting this in the tree.  My real hope is that someone takes this and makes it actually generally useful.

2018-10-18 20:52 UTC, ezyang commented on tools/git_add_generated_dirs.sh
> +(< $BASEDIR/generated_dirs.txt xargs -i find {} -type f) | xargs git add -f
woooow I didn't know you could put the `<` before the command. Fancy shmancy.

For max portability, you should put a shebang on the shell script

2018-10-18 20:53 UTC, ezyang requested changes
The scripts themselves should have the docs you wrote in the commit.

2018-10-22 13:19 UTC, ezyang commented on tools/git_reset_generated_dirs.sh
> +# HOW TO USE:
You could use a `Note [git generated dirs]` script to avoid having to copy paste it two places ;)

2018-10-22 13:19 UTC, ezyang approved these changes

2018-10-22 14:14 UTC, ezyang approved these changes

2018-10-22 14:34 UTC, closed without merging