Instance norm
pytorch/pytorch pull request #1283
Opened 2017-04-18 19:01 UTC by DmitryUlyanov

Implements instance normalization modules (1d, 2d, 3d). Based on batch norm, allows affine transform, but  it is switched off by default.

2017-04-22 09:26 UTC, soumith requested changes
almost looks good. Please check inline comments.

2017-04-22 09:26 UTC, soumith commented on torch/nn/modules/instancenorm.py
> +    def force_eval(self):
is there really value provided with this? I suggest just remove force_eval

2017-04-22 09:26 UTC, soumith commented on torch/nn/modules/instancenorm.py
> +        input_reshaped = input.view(1, b * c, *input.size()[2:])
might be worth making `input` contiguous right before this, as view will only work on contiguous inputs:
```
input = input.contiguous()
```

2017-04-22 16:42 UTC, DmitryUlyanov commented on torch/nn/modules/instancenorm.py
> +    def force_eval(self):
Removed. Anyway there is a way to force it with `.train(False)`

2017-04-23 12:49 UTC, soumith approved these changes

2017-04-23 12:49 UTC, merged

2017-04-23 12:49 UTC, soumith commented
thank you!

2017-09-16 11:15 UTC, mys007 commented
As `training=False` in fixed in calling `F.batch_norm()`, is it really necessary to:
1) keep running stats at all? One could throw out their keeping as parameters (they could be allocated in `forward() each time anew) as well as repeating them and averaging them back.
2) offer `momentum` in constructor?