[dynamo] - Add JK killswitch for dynamo compilation.
pytorch/pytorch pull request #128538
Opened 2024-06-12 19:11 UTC by c00w

This allows easy disablement of dynamo in emergency situations where env variables are hard to set.

2024-06-14 05:14 UTC, jansel requested changes
Tests seem broken.  Should this only be enabld in fbcode?

2024-06-18 16:21 UTC, c00w commented
@jansel  - justknobs_check returns true by default, the bug is just a missing parenthesis.

2024-06-19 17:30 UTC, jansel approved these changes

2024-06-20 22:55 UTC, c00w commented
@pytorchmergebot merge

2024-06-21 02:32 UTC, jansel commented
@pytorchbot merge

2024-06-21 06:14 UTC, closed without merging