[inductor] Add Triton template for Conv3D
pytorch/pytorch pull request #129518
Opened 2024-06-25 21:45 UTC by antiagainst

This commit adds a Triton template for Conv3D ops,
by following the same logic like Conv2D. Conv3D
aren't as frequently used like Conv2D so they might
enjoy less optimizations in various libraries. So having
a Triton based inductor impl can improve performance
for cases.

2024-06-26 04:59 UTC, jansel requested changes
Thanks for the contribution!  At a high level these seem fine, but looks like tests are failing.  Hopefully you can figure out why, let us know if you get stuck.

I'd also note that our conv2d templates a pretty poorly optimized, so there is definitely room to improve them if you are interested in diving deeper here.

2024-07-01 11:28 UTC, jataylo commented
@antiagainst @jansel cc: @jeffdaily @jithunnair-amd  Looks like we are seeing slight inaccuracy with ROCm causing this UT to fail. I took a deeper look, with a standalone comparison fp16/fp32 models are accurate and meet tolerance when comparing  eager torch.conv3d to torch.compile (both with and without max_autotune) but the issue in the UT arises due to the `reference_in_float` arg of `check_model_gpu`.

With this enabled the compiled version runs as fp16 but the reference runs as fp32 and the results are casted back to fp16 in the comparison, this seems to be exacerbating some inaccuracy with miopen conv3d leading to this UT to fail.
```
2024-06-27T10:42:54.3264958Z Mismatched elements: 6 / 1560 (0.4%)
2024-06-27T10:42:54.3265625Z Greatest absolute difference: 0.00018310546875 at index (0, 1, 0, 1, 0) (up to 6e-05 allowed)
2024-06-27T10:42:54.3266429Z Greatest relative difference: 0.161376953125 at index (0, 1, 1, 6, 16) (up to 0.002 allowed)    
```

I think for now we can either bump the tolerance on ROCm or set `reference_in_float=False` on ROCm for the time being e.g.

```
    def test_convolution5(self):
        m = torch.nn.Sequential(
            torch.nn.Conv3d(3, 3, kernel_size=7),
            ToTuple(),
        )

        self.common(
            m,
            (torch.randn([1, 3, 8, 16, 32]),),
            atol=6e-5,
            rtol=0.001,
+          reference_in_float=False if torch.version.hip else True
        )
```

P.S also need to rename this unit test now as convolution5 is taken.

2024-07-02 06:24 UTC, antiagainst commented
Nice, thanks a lton for the pointers @jataylo! That helps a lot. I've updated tests according to your suggestions. Let's see. :)

2024-07-03 05:11 UTC, jansel approved these changes

2024-07-04 09:22 UTC, jataylo commented
There's a few cpu failures for the conv3d test, maybe conv3d cpu doesn't support max autotune cc: @jansel 

Will take a look. Rebasing to check if `inductor/test_compiled_autograd.py::TestCompiledAutograd::test_free_activation_memory_subclass` failure is flakey

2024-07-04 09:22 UTC, jataylo commented
@pytorchbot rebase

2024-07-04 15:20 UTC, jataylo commented
Rebasing again due to minifier issues

2024-07-04 18:46 UTC, jataylo approved these changes

2024-07-04 20:23 UTC, jataylo commented
@pytorchbot merge

2024-07-04 20:30 UTC, closed without merging