Add pinned memory support to sparse COO/CSR/CSC/BSR/BSC tensors
pytorch/pytorch pull request #129645
Opened 2024-06-27 09:52 UTC by pearu

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #129645

2024-06-28 17:15 UTC, amjames requested changes
I see one major issue that should be addressed. 

What should happen when one component tensor passed to _with_tensors` constructors, but not all. In particular consider when the `values` are pinned, but indices tensor(s) are not.

```python
a = torch.randn(10, 10)
a[::2, ::2] = 0
sp1 = a.to_sparse_coo()
values = a._values().clone().pin_memory()
indices = a._indices()
sp2 = torch.sparse_coo_tensor(indices, values, size=(10, 10))
```

Here `sp2.is_pinned()` would return true, but `sp2._indices().is_pinned()` is false. This is inconsistent with

```python
sp3 = sp1.pin_memory()
```

which also has `sp3.is_pinned()` True, but `sp3._indices().is_pinned()` is True. Inconsistency like this will be a pain point for some users. 

I see two options: 
1. Expect this meta data field to match across members -> We should add this to the invariant checks, or enforce this by pinning out-of-sync members if any member is pinned in the constructors. 
2. Allow for these to be out-of-sync 
   - `sparse.is_pinned()` should be a short hand for `values.is_pinned() && indices.is_pinned()` (and the plain/compressed indices for sparse compressed layouts) the same way that `sparse.pin_memory()` is short hand for pinning all member tensors. 

Personally I think option 1) is better for the simplicity and I can't see a reason why one would want some members to be pinned while others are not.

2024-06-29 06:50 UTC, pearu commented
> I see two options: ...

Registering a CPU tensor with CUDA is essentially a copy operation to another device (although the pinned tensor can still be accessed by CPU processes). In the case of sparse tensors, we don't allow indices and values to be on different devices: an error is raised when trying to create a sparse tensor from indices and values that have different devices.

I suggest that we treat pinned and non-pinned tensors as having different devices. So, when one tries to create a sparse tensor from indices and values that have different pinning state then an exception will be raised. This corresponds to the first part of option 1).

2024-06-29 07:52 UTC, pearu commented on aten/src/ATen/native/sparse/SparseTensor.cpp
> +  TensorOptions options = self.options().pinned_memory(true);
Done.

2024-06-29 07:52 UTC, pearu commented on aten/src/ATen/native/sparse/SparseCsrTensor.cpp
> +  CheckSparseTensorInvariants _(false);
Done.

2024-07-01 19:55 UTC, amjames approved these changes

2024-07-30 19:31 UTC, cpuhrsch approved these changes

2024-07-30 20:16 UTC, eqy approved these changes

2024-08-02 05:56 UTC, pearu commented
@pytorchbot merge

2024-08-02 08:55 UTC, closed without merging