Format readme
pytorch/pytorch pull request #129822
Opened 2024-06-29 14:34 UTC by furtnerthomas

format README.md with markdown lint

2024-07-02 12:47 UTC, soulitzer commented
Thanks for the change. Unfortunately this also seems to alter the style of the markdown.

2024-07-02 12:49 UTC, soulitzer requested changes
.

2024-07-03 07:17 UTC, furtnerthomas commented on README.md
> +**Linux**
having ** instead of unordered list would be more consistent

2024-07-03 07:18 UTC, furtnerthomas commented on README.md
> +**Linux**
having "**" instead of "-" would be more consistent

2024-10-01 07:34 UTC, closed without merging