Use @fx.wrap for python-side NJT construction
pytorch/pytorch pull request #130183
Opened 2024-07-05 22:23 UTC by jbschlosser

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-07-05 23:33 UTC, YuqingJ commented
Thanks for hiding the fx.wrap from users. Could you please import this to internal and then I can run some jobs to verify it works in prod? 
By the way, just confirming, will it be fine if we call fx.wrap on both nested_view_from_values_offsets_lengths and the model side function at the same time (wrap on a wrap)?  If not, might need to check for compatibility too.

2024-07-08 16:11 UTC, jbschlosser commented
> Could you please import this to internal and then I can run some jobs to verify it works in prod?

Sure thing!

> By the way, just confirming, will it be fine if we call fx.wrap on both nested_view_from_values_offsets_lengths and the model side function at the same time (wrap on a wrap)? If not, might need to check for compatibility too.

My understanding is that the outer wrapped function will end up in the fx graph and the inner wrapped function (i.e. `nested_view_from_values_offsets_lengths()`) won't be. I think things will still function like this, but if we want the BC surface to be `nested_view_from_values_offsets_lengths()` instead of the model-side function, then it would be good to eventually remove the outer fx.wrap from the model-side function.

2024-07-08 19:15 UTC, soulitzer commented
It would be nice if the bc-surface introduced by fx.wrap match the public API, e.g. fx.wrap on `torch.nested.nested_tensor_from_jagged`, but if I understand correctly, the reason we don't do this is because we need to make sure the fx.wrapped function is called in the correct way.

2024-07-11 15:53 UTC, jbschlosser commented
@jbschlosser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59638229).

2024-07-11 22:26 UTC, YuqingJ commented on torch/nested/_internal/nested_tensor.py
> +    values, offsets, lengths, ragged_idx=1, min_seqlen=None, max_seqlen=None
can length has a default None value?

2024-07-12 02:18 UTC, davidberard98 reviewed
fx usage seems correct to me, though maybe let's wait for @YuqingJ 's tests (and her comment about length=None seems good too?)

also, not sure if you prefer this or not, but another option is to wrap `_nt_view_dummy()`.

and idk how to do this, but it might also be nice to mark this function as needing to be backward compatible so that CI would catch changes to its signature

2024-07-12 17:10 UTC, davidberard98 requested changes

2024-07-12 17:10 UTC, davidberard98 commented on torch/nested/__init__.py
> +    return torch.nested._internal.nested_tensor.nested_view_from_values_offsets_lengths(
I think we need to also `import torch.nested._internal.nested_tensor`

2024-07-12 22:54 UTC, davidberard98 commented on torch/nested/__init__.py
> +    return torch.nested._internal.nested_tensor.nested_view_from_values_offsets_lengths(
okay, apparently we can't do this, repro:

```python
import torch
import torch.nested._internal.nested_tensor

asdf = "asdf"

def fn(x, y):
    return torch.nested.nested_tensor_from_jagged(x, y)

x = torch.randn(10, 16)
y = torch.tensor([0, 1, 3, 6, 10])

fn_fx = torch.fx.symbolic_trace(fn)
torch.fx.symbolic_trace(fn_fx)
```

2024-07-13 00:26 UTC, davidberard98 commented on torch/nested/__init__.py
> +    return torch.nested._internal.nested_tensor.nested_view_from_values_offsets_lengths(
i think this is why - fns from torch/ have some special handling here:

https://www.internalfb.com/code/fbsource/[4060bddc90fe1f9357b0a73656e0879678a364d1]/fbcode/caffe2/torch/fx/graph.py?lines=398-400

2024-07-15 20:48 UTC, jbschlosser commented
Closing this PR according to @davidberard98's findings that this doesn't fix the fx-tracing problems. For now, we'll require that users apply `fx.wrap()` to functions that call `nested_tensor_from_jagged()`.

2024-07-15 20:48 UTC, closed without merging