switch CppCodeCache to new cpp_builder.
pytorch/pytorch pull request #130132
Opened 2024-07-05 00:44 UTC by xuhancn

Fixes #ISSUE_NUMBER

2024-07-05 05:17 UTC, jgong5 approved these changes

2024-07-05 22:27 UTC, jansel requested changes, later dismissed

2024-07-05 22:27 UTC, jansel commented on torch/_inductor/codecache.py
> +            """
remove old code

2024-07-06 02:47 UTC, xuhancn commented on torch/_inductor/codecache.py
> +            """
Done.

2024-07-06 17:40 UTC, xuhancn commented
@pytorchbot drci

2024-07-06 18:35 UTC, jansel approved these changes

2024-07-06 18:50 UTC, xuhancn commented
@pytorchbot merge

2024-07-08 21:21 UTC, izaitsevfb commented
@pytorchbot revert -m "Depends on  #130105 which has to be reverted" -c ghfirst

2024-07-10 23:19 UTC, xuhancn commented
@pytorchmergebot merge

2024-07-10 23:51 UTC, xuhancn commented
@pytorchmergebot merge

2024-07-11 05:54 UTC, xuhancn commented
@pytorchmergebot merge

2024-07-11 07:03 UTC, closed without merging