Add _sync_module_states_with_mesh util for broadcasting module states with DeviceMesh
pytorch/pytorch pull request #130356
Opened 2024-07-09 18:58 UTC by fegin

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Summary:
Similar to _sync_module_states but is designed for taking DeviceMesh.

2024-07-29 05:18 UTC, wz337 approved these changes
LGTM

2024-07-29 18:23 UTC, wanchaol requested changes

2024-08-13 17:57 UTC, fegin commented on torch/distributed/utils.py
> +    from torch.distributed._tensor import DeviceMesh
Yes.

2024-08-14 21:54 UTC, fegin commented
We are still discussing whether we should just let users to set a synchronized random seed. Converting this PR to draft and waiting for the conclusion.

2024-10-14 15:14 UTC, closed without merging