add JK kill switch for subprocess parallel compile
pytorch/pytorch pull request #130499
Opened 2024-07-10 22:34 UTC by dshi7

Fixes #ISSUE_NUMBER

2024-07-11 00:50 UTC, dshi7 commented
compared to `async_compile.py`, it's easier to inject JK switch (default False) in the beginning of `config.worker_start_method` because it will determine `config.compile_threads` too.

2024-07-11 20:37 UTC, masnesral requested changes

2024-07-11 20:37 UTC, masnesral commented on torch/_inductor/config.py
> +    if justknobs_check("pytorch/inductor:subprocess_parallel_compile"):
I don't think we can do it this way. This is evaluated at import time and there a big warning that this is not safe: https://github.com/pytorch/pytorch/blob/726a2872717f45e4508f19445b4e496ce6a02e6f/torch/_utils_internal.py#L169-L171

2024-09-09 21:39 UTC, masnesral commented
Oh I may have accidentally marked this as not stale. I thought this was my PR. @dshi7 , I guess we can abandon this. We can use https://github.com/pytorch/pytorch/pull/132467

2025-05-13 15:41 UTC, closed without merging