Make c10::string_view an alias of std::string_view
pytorch/pytorch pull request #130417
Opened 2024-07-10 05:22 UTC by cyyever

Fixes #ISSUE_NUMBER

2024-07-11 12:25 UTC, ezyang approved these changes

2024-07-11 12:28 UTC, cyyever commented
@pytorchmergebot merge -f "Test failure are unrelated"

2024-07-12 00:35 UTC, izaitsevfb commented
@pytorchbot revert -m "depends on #130009 which needs to be reverted" -c ghfirst

2024-10-13 23:31 UTC, cyyever commented
@pytorchmergebot merge

2024-10-14 08:01 UTC, cyyever commented
@pytorchbot merge -i

2024-10-14 09:26 UTC, cyyever commented
@pytorchbot merge -f "Pending jobs"

2024-10-15 18:53 UTC, clee2000 commented
@pytorchbot revert -m "breaking some internal tests, probably usages of string_view that need to be changed?" -c ghfirst

Here are some random bits of logs
```
E1014 23:25:34.291942 12014 ExceptionTracer.cpp:221] exception stack complete
terminate called after throwing an instance of 'c10::Error'
  what():  Type c10::basic_string_view<char> could not be converted to any of the known types.
Exception raised from operator() at ...ATen/core/jit_type.h:1810 (most recent call first):

# 2  c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
# 3  c10::detail::getTypePtr_<c10::basic_string_view<char> >::call()::{lambda()#1}::operator()() const
# 4  c10::Type::SingletonOrSharedTypePtr<c10::Type> c10::getFakeTypePtrCopy<c10::basic_string_view<char> >()
# 5  0x000000000058d7f7
# 6  c10::detail::infer_schema::make_function_schema(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>)
# 7  0x000000000003bba4
# 8  call_init.part.0
# 9  _dl_init
# 10 __GI__dl_catch_exception
# 11 dl_open_worker
# 12 __GI__dl_catch_exception
```

```
Stderr:
error: use of undeclared identifier 'str'; did you mean 'at::str'?
  158 |           tupleNames_.push_back(str(*it));
      |                                 ^~~
      |                                 at::str
c10/util/StringUtil.h:115:23: note: 'at::str' declared here
  115 | inline decltype(auto) str(const Args&... args) {
      |                       ^
1 error generated.
```

I'm going to try changing the str to at::str but idk if that's the correct thing to do

2024-10-16 04:17 UTC, cyyever commented
@clee2000 Fixed, help import it to verify?

2024-10-16 20:27 UTC, albanD reviewed
Please do add details on why you added the skip-pr-sanity-check label and in general I wouldn't not expect you to add it without discussing it.
Int this particular case, this would ONLY be acceptable to skip it if you share the command you used to codemod the change you did. From a quick look, this covers a lot more than just making it an alias as the title of the PR suggests.

Please do add these details to the description if you do want to skip the pr sanity check tests.

2024-10-17 02:23 UTC, cyyever commented
@albanD Thank you for your advice.  I will refine the description.

2024-10-17 18:44 UTC, albanD commented
Thanks!
Would you be able to share a set of sed/codemod command we can run locally to re-generate the exact same diff without having to check every line?

2024-10-17 23:34 UTC, cyyever commented
@albanD I managed to simplify the test file changes and rebased.

2024-10-18 13:07 UTC, albanD reviewed
Ho much easier to review, thanks!
I'll let @clee2000 check if this needs an internal equivalent.

2024-10-18 16:55 UTC, clee2000 commented
I'm seeing failures on the import like 
```
...\NNTorchScriptBackend.cpp(647): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'fmt::v9::string_view'
    ...\NNTorchScriptBackend.cpp(647): note: 'fmt::v9::basic_string_view<char>::basic_string_view': no overloaded function could convert all the argument types
    ...\fmt\core.h(442): note: could be 'fmt::v9::basic_string_view<char>::basic_string_view(const Char *,size_t) noexcept'
            with
            [
                Char=char
            ]
    ...\NNTorchScriptBackend.cpp(647): note: 'fmt::v9::basic_string_view<char>::basic_string_view(const Char *,size_t) noexcept': cannot convert argument 1 from 'std::_String_view_iterator<_Traits>' to 'const Char *'
            with
            [
                Char=char
            ]
            and
            [
                _Traits=std::char_traits<char>
            ]
            and
            [
                Char=char
            ]
    ...\NNTorchScriptBackend.cpp(647): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
    ...\fmt\core.h(468): note: or       'fmt::v9::basic_string_view<char>::basic_string_view(S) noexcept'
    ...\fmt\core.h(462): note: or       'fmt::v9::basic_string_view<char>::basic_string_view(const std::basic_string<Char,Traits,Alloc> &) noexcept'
            with
            [
                Char=char
            ]
    ...\NNTorchScriptBackend.cpp(647): note: while trying to match the argument list '(std::_String_view_iterator<_Traits>, std::basic_string_view<char,std::char_traits<char>>::size_type)'
            with
            [
                _Traits=std::char_traits<char>
            ]
    ...\NNTorchScriptBackend.cpp(647): error C3615: constexpr function 'fmt::v9::basic_format_parse_context<char,fmt::v9::detail::error_handler>::on_error' cannot result in a constant expression
    ...\fmt\core.h(718): note: failure was caused by call of undefined function or one not declared 'constexpr'
    ...\fmt\core.h(718): note: see usage of 'fmt::v9::detail::error_handler::on_error'
    ...\NNTorchScriptBackend.cpp(647): note: the call stack of the evaluation (the oldest call first) is
    ...\NNTorchScriptBackend.cpp(647): note: while evaluating function 'fmt::v9::basic_format_string<char,const size_t &,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>::basic_format_string<char[48],0>(const S (&))'
            with
            [
                S=char [48]
            ]
    ...\fmt\core.h(3169): note: while evaluating function 'void fmt::v9::detail::parse_format_string<true,char,checker>(fmt::v9::basic_string_view<char>,Handler &&)'
            with
            [
                Handler=checker
            ]
    ...\fmt\core.h(2731): note: while evaluating function 'const Char *fmt::v9::detail::parse_replacement_field<char,Handler&>(const Char *,const Char *,fmt::v9::detail::format_string_checker<Char,fmt::v9::detail::error_handler,unsigned __int64,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>&)'
            with
            [
                Char=char,
                Handler=checker
            ]
    ...\fmt\core.h(2662): note: while evaluating function 'int fmt::v9::detail::format_string_checker<Char,fmt::v9::detail::error_handler,unsigned __int64,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>::on_arg_id(void)'
            with
            [
                Char=char
            ]
    ...\fmt\core.h(2971): note: while evaluating function 'int fmt::v9::detail::compile_parse_context<Char,ErrorHandler>::next_arg_id(void)'
            with
            [
                Char=char,
                ErrorHandler=fmt::v9::detail::error_handler
            ]
    ...\fmt\core.h(747): note: while evaluating function 'void fmt::v9::basic_format_parse_context<char,fmt::v9::detail::error_handler>::on_error(const char *)'
```

2024-10-25 02:24 UTC, cyyever commented
@pytorchbot rebase

2024-10-25 15:12 UTC, cyyever commented
@clee2000 I restored the old behavior under FBCODE macro.

2024-10-28 00:58 UTC, cyyever commented
@pytorchbot rebase

2024-10-28 06:52 UTC, cyyever commented
@clee2000 The failures seem unrelated. If META builds work, then it's possible to merge.

2024-10-28 18:15 UTC, clee2000 commented
Yeah I'm still seeing stuff like 
```
    ...\Caffe2Common.cpp(42): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'fmt::v9::string_view'
    ...\Caffe2Common.cpp(44): note: No constructor could take the source type, or constructor overload resolution was ambiguous

```

```
    ...\NNTorchScriptBackend.cpp(647): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'fmt::v9::string_view'
    ...\NNTorchScriptBackend.cpp(647): note: 'fmt::v9::basic_string_view<char>::basic_string_view': no overloaded function could convert all the argument types
    ...\core.h(442): note: could be 'fmt::v9::basic_string_view<char>::basic_string_view(const Char *,size_t) noexcept'
            with
            [
                Char=char
            ]
    ...\NNTorchScriptBackend.cpp(647): note: 'fmt::v9::basic_string_view<char>::basic_string_view(const Char *,size_t) noexcept': cannot convert argument 1 from 'std::_String_view_iterator<_Traits>' to 'const Char *'
            with
            [
                Char=char
            ]
            and
            [
                _Traits=std::char_traits<char>
            ]
            and
            [
                Char=char
            ]
    ...\NNTorchScriptBackend.cpp(647): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
    ...\core.h(468): note: or       'fmt::v9::basic_string_view<char>::basic_string_view(S) noexcept'
    ...\core.h(462): note: or       'fmt::v9::basic_string_view<char>::basic_string_view(const std::basic_string<Char,Traits,Alloc> &) noexcept'
            with
            [
                Char=char
            ]
    ...\NNTorchScriptBackend.cpp(647): note: while trying to match the argument list '(std::_String_view_iterator<_Traits>, std::basic_string_view<char,std::char_traits<char>>::size_type)'
            with
            [
                _Traits=std::char_traits<char>
            ]
    ...\NNTorchScriptBackend.cpp(647): error C3615: constexpr function 'fmt::v9::basic_format_parse_context<char,fmt::v9::detail::error_handler>::on_error' cannot result in a constant expression
    ...\core.h(718): note: failure was caused by call of undefined function or one not declared 'constexpr'
    ...\core.h(718): note: see usage of 'fmt::v9::detail::error_handler::on_error'
    ...\NNTorchScriptBackend.cpp(647): note: the call stack of the evaluation (the oldest call first) is
    ...\NNTorchScriptBackend.cpp(647): note: while evaluating function 'fmt::v9::basic_format_string<char,const size_t &,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>::basic_format_string<char[48],0>(const S (&))'
            with
            [
                S=char [48]
            ]
    ...\core.h(3169): note: while evaluating function 'void fmt::v9::detail::parse_format_string<true,char,checker>(fmt::v9::basic_string_view<char>,Handler &&)'
            with
            [
                Handler=checker
            ]
    ...\core.h(2731): note: while evaluating function 'const Char *fmt::v9::detail::parse_replacement_field<char,Handler&>(const Char *,const Char *,fmt::v9::detail::format_string_checker<Char,fmt::v9::detail::error_handler,unsigned __int64,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>&)'
            with
            [
                Char=char,
                Handler=checker
            ]
    ...\core.h(2662): note: while evaluating function 'int fmt::v9::detail::format_string_checker<Char,fmt::v9::detail::error_handler,unsigned __int64,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>::on_arg_id(void)'
            with
            [
                Char=char
            ]
    ...\core.h(2971): note: while evaluating function 'int fmt::v9::detail::compile_parse_context<Char,ErrorHandler>::next_arg_id(void)'
            with
            [
                Char=char,
                ErrorHandler=fmt::v9::detail::error_handler
            ]
    ...\core.h(747): note: while evaluating function 'void fmt::v9::basic_format_parse_context<char,fmt::v9::detail::error_handler>::on_error(const char *)'
```

This seems to be a windows only thing, is there a chance I need to change something internally as well to enable this?

Also seeing
```
*** Assertion failure in void FBRegisterAllGoogleTestCases()(), FBGoogleXCTestUtils.mm:192
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to add Google Test method \"testConversionToString\", this method may already exist in the class.'
```
on mac/ios tests

2024-10-28 19:29 UTC, malfet commented on c10/util/string_view.h
> +#ifdef fbcode_caffe2
This should have been uppercase :)
```suggestion
#ifdef FBCODE_CAFFE2
```

2024-10-28 19:30 UTC, malfet commented on c10/test/util/string_view_test.cpp
> +#ifndef fbcode_caffe2
```suggestion
#ifndef FBCODE_CAFFE2
```

2024-10-28 19:44 UTC, r-barnes requested changes

2024-10-28 19:45 UTC, r-barnes approved these changes

2024-10-29 04:23 UTC, cyyever commented on c10/util/TypeIndex.h
> +inline constexpr c10::string_view_ext fully_qualified_type_name_impl() {
Different c++ libraries will have different demangled name (libc++,libstdc++, MSVC STL).

2024-10-29 04:24 UTC, cyyever commented on caffe2/serialize/inline_container.cc
> +  if ((!load_debug_symbol_) && c10::string_view_ext(name).ends_with(kDebugPklSuffix)) {
In a latter PR.

2024-10-29 06:45 UTC, malfet commented
Just FYI it still fails internally, I guess parts of the code need to be guarded a bit further...

2024-10-29 06:47 UTC, cyyever commented
> Just FYI it still fails internally, I guess parts of the code need to be guarded a bit further...

Should be the problem of old libfmt from the posted info.

2024-12-01 20:34 UTC, closed without merging