[3.13, dynamo] support TO_BOOL
pytorch/pytorch pull request #130565
Opened 2024-07-11 20:44 UTC by williamwen42

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-07-11 22:33 UTC, jansel requested changes

2024-07-11 22:33 UTC, jansel commented on torch/_dynamo/symbolic_convert.py
> +            self.push(BuiltinVariable(bool).call_function(self, [value], {}))
Shouldn't this be able to handle the constant case as well?

2024-07-12 20:06 UTC, williamwen42 commented
Changed approach: we don't actually need to do anything for `TO_BOOL`, based on how CPython codegens this instruction.

2024-07-13 04:31 UTC, jansel approved these changes

2024-07-15 18:28 UTC, williamwen42 commented
@pytorchbot merge

2024-07-16 19:57 UTC, williamwen42 commented
@pytorchbot merge

2024-07-17 06:29 UTC, williamwen42 commented
@pytorchbot merge

2024-07-17 09:48 UTC, closed without merging