Use 3.25.0 as the minimum CMake version
pytorch/pytorch pull request #130522
Opened 2024-07-11 05:40 UTC by cyyever

Fixes #ISSUE_NUMBER

2024-07-13 05:29 UTC, cyyever commented
@pytorchbot rebase

2024-08-29 02:17 UTC, cyyever commented
@pytorchbot rebase

2024-08-29 19:47 UTC, ezyang commented
@malfet can I defer to you on this?

2024-10-05 01:29 UTC, cyyever commented
@pytorchbot rebase

2024-10-05 06:19 UTC, malfet commented
@cyyever do you know why it fails? And also, it looks like fbgemm is compatible with 3.18, so I don't see a really good reason to move to 3.25

2024-10-05 06:24 UTC, cyyever commented
> @cyyever do you know why it fails? And also, it looks like fbgemm is compatible with 3.18, so I don't see a really good reason to move to 3.25

The android failures may be real failures unrelated to this upgrade. Other failures are about gtest linking, which are interesting and unexpected, it may indicate some undiscovered CMake error and need further investigation.

2024-10-05 08:50 UTC, cyyever commented
@malfet gtest failures are due to CMake policy 0126 and how we cache and change BUILD_SHARED_LIBS. See https://cmake.org/cmake/help/latest/policy/CMP0126.html#policy:CMP0126

2024-11-02 13:44 UTC, cyyever commented
@malfet With the recent deprecation of Andriod jobs, the PR works.

2025-01-05 04:49 UTC, cyyever commented
@malfet CMake is still the main obstacle for fbgemm upgrade. And by the way, newer CMake has better support for linking options and other features.

2025-03-15 05:42 UTC, cyyever commented
@pytorchbot rebase

2025-03-15 09:18 UTC, cyyever commented
I saw another attempt to update FBGEMM.

2025-03-15 17:55 UTC, q10 approved these changes

2025-03-16 00:28 UTC, cyyever commented
@pytorchmergebot merge

2025-03-18 17:23 UTC, q10 commented
@cyyever let me know when this PR is ready.  We are trying to land https://github.com/pytorch/pytorch/pull/149213, which is dependent on this PR

2025-03-19 03:11 UTC, cyyever commented
@q10 The main obstacle is that some conda build files have 'cmake=3.22' hardcoded, but they are in test-infra.

2025-03-21 18:23 UTC, q10 commented
(for reference, https://github.com/pytorch/test-infra/pull/6443)

2025-04-30 08:44 UTC, cyyever commented
@pytorchbot rebase

2025-05-01 04:41 UTC, q10 approved these changes
LGTM, though you might want to run it by @atalman

2025-05-01 05:09 UTC, cyyever commented
Interestingly, MacOS tests segmentation fault.. 
@malfet If you are curious about why..

2025-05-01 05:11 UTC, malfet requested changes
Why do you want to use latest cmake? Is there a feature from 3.25 you want to use?

2025-05-01 05:16 UTC, cyyever commented
@malfet We want to update FBGEMM, which relies on 3.25. However, it is easier to install latest CMake via `brew`

2025-05-05 00:49 UTC, cyyever commented
@pytorchbot rebase -b main

2025-05-11 00:53 UTC, cyyever commented
@pytorchbot rebase -b main

2025-05-12 14:47 UTC, cyyever commented
@pytorchmergebot merge -i

2025-05-12 15:38 UTC, cyyever commented
@pytorchmergebot merge -i

2025-05-12 15:43 UTC, closed without merging