[inductor] adapte windows file path
pytorch/pytorch pull request #130713
Opened 2024-07-15 06:49 UTC by xuhancn

Fixes #ISSUE_NUMBER

2024-07-15 07:08 UTC, jgong5 requested changes, later dismissed

2024-07-15 07:08 UTC, jgong5 commented on torch/_inductor/cpp_builder.py
> +def adapte_file_path(orig_path: str) -> str:
`normalize_path_separator` sounds more specific.

2024-07-15 07:08 UTC, jgong5 commented on torch/_inductor/cpp_builder.py
> +        return orig_path.replace("\\", "/")
```suggestion
        return orig_path.replace(os.sep, "/")
```

2024-07-15 07:12 UTC, xuhancn commented on torch/_inductor/cpp_builder.py
> +def adapte_file_path(orig_path: str) -> str:
Done.

2024-07-15 07:20 UTC, jgong5 approved these changes

2024-07-15 15:24 UTC, jansel approved these changes

2024-07-16 01:43 UTC, desertfire approved these changes
Test files need to be updated because of "Unexpected success"

2024-07-16 03:20 UTC, xuhancn commented
@pytorchbot merge

2024-07-16 03:23 UTC, xuhancn commented
@pytorchbot merge

2024-07-16 03:26 UTC, xuhancn commented
@pytorchbot rebase -b main

2024-07-16 13:51 UTC, xuhancn commented
@pytorchmergebot merge -f "not related issue."

2024-07-16 22:06 UTC, clee2000 commented
@pytorchbot revert -m "broke functorch\test_eager_transforms.py on windows https://github.com/pytorch/pytorch/actions/runs/9958208725/job/27530132704 https://hud.pytorch.org/pytorch/pytorch/commit/69e99172450e40536bf2e6c110183d34a0e283e2.  Test failure on PR is real, possibly force merged to get around lint error?" -c ignoredsignal

2024-07-16 22:12 UTC, xuhancn commented
> @pytorchbot revert -m "broke functorch\test_eager_transforms.py on windows https://github.com/pytorch/pytorch/actions/runs/9958208725/job/27530132704 https://hud.pytorch.org/pytorch/pytorch/commit/69e99172450e40536bf2e6c110183d34a0e283e2. Test failure on PR is real, possibly force merged to get around lint error?" -c ignoredsignal

Lint error is unchanged file, it is not bring from me. @clee2000

2024-07-16 23:03 UTC, xuhancn commented
@pytorchmergebot drci

2024-07-17 01:09 UTC, xuhancn commented
@pytorchmergebot merge

2024-07-17 19:35 UTC, clee2000 commented
@pytorchbot revert -m "sorry but I think its still failing, this time on windows CUDA https://github.com/pytorch/pytorch/actions/runs/9971126834/job/27552761451 https://hud.pytorch.org/pytorch/pytorch/commit/bb62e9d7c3e4c4de6c84b37479372024a048b0b6.  It was not run on PR due to being on the periodic workflow, which isnt usually run on PRs due to capacity issues for windows CUDA machines.  I will add ciflow/periodic to the PR to ensure the test gets run" -c nosignal

2024-07-18 03:05 UTC, xuhancn commented
@pytorchmergebot merge

2024-07-18 11:36 UTC, xuhancn commented
@pytorchmergebot merge

2024-07-18 20:22 UTC, xuhancn commented
@pytorchmergebot merge

2024-07-19 01:15 UTC, closed without merging