[aoti] refactor _scaled_mm and skip fp8 test for some cases
pytorch/pytorch pull request #130868
Opened 2024-07-16 22:49 UTC by henrylhtsang

Differential Revision: D59833074

2024-07-17 01:33 UTC, drisspg approved these changes

2024-07-17 01:44 UTC, chenyang78 approved these changes

2024-07-17 01:49 UTC, chenyang78 requested changes
On a second thought, we may actually want to add a new API with "_v2" suffix, since changing the arguments breaks the backward compatibility. 

cc @desertfire

2024-07-17 22:11 UTC, henrylhtsang commented
@chenyang78 I added the v2 functions. Should I modify the implementation of v1 to use that of v2 as well? 

btw does aot inductor know to use v2 automatically?

2024-07-18 22:09 UTC, henrylhtsang commented
Verified with internal testing that the tests are passing

2024-07-19 07:08 UTC, chenyang78 approved these changes
LGTM. Thanks!

2024-07-19 19:01 UTC, desertfire approved these changes

2024-07-19 20:41 UTC, henrylhtsang commented
@pytorchbot label "topic: not user facing"

2024-07-19 20:41 UTC, henrylhtsang commented
@pytorchbot merge

2024-07-22 15:22 UTC, henrylhtsang commented
@pytorchbot merge

2024-07-22 15:24 UTC, closed without merging