BE: reset dynamo before each test in test_ops_gradients.py
pytorch/pytorch pull request #131397
Opened 2024-07-22 22:13 UTC by shunting314

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #131397

2024-07-22 22:33 UTC, zou3519 approved these changes

2024-07-22 22:34 UTC, zou3519 commented on test/test_ops_gradients.py
> +
Btw, torch._dynamo.reset() might be expensive (when called so many times), so you might want to guard this on if we are doing PYTORCH_TEST_WITH_INDUCTOR

2024-07-22 22:39 UTC, zou3519 requested changes
Sorry, I changed my assessment: see the comments in https://github.com/pytorch/pytorch/pull/131388

2024-07-23 23:30 UTC, zou3519 approved these changes

2024-07-24 00:32 UTC, shunting314 commented
@pytorchbot merge

2024-07-29 17:36 UTC, shunting314 commented
@pytorchbot merge

2024-07-29 21:08 UTC, kit1980 commented
This stack should have ciflow/inductor label.

2024-10-28 21:43 UTC, ZainRizvi commented
Please rebase this PR onto the latest viable/strict in order to get a functional CI signal.

2024-11-27 22:36 UTC, closed without merging