[inductor pattern][cpu] add a new int8 woq mm pattern
pytorch/pytorch pull request #131310
Opened 2024-07-22 07:27 UTC by Valentine233

Add int8 woq mm pattern for llama, which successfully hits all the 224 woq linears.

### Implementation
Differences with previous patterns:
- scale is fp32 instead of bf16.
- no reshape for x and output.

### Performance
Performance data on llama, with 1 numa node:
- Before pattern match:
 ---------- Summary: ----------
inference-latency: 7.172 sec.
first-token-latency: 0.812 sec.
rest-token-latency: 0.204 sec.
P90-rest-token-latency: 0.210 sec.

- After pattern match:
---------- Summary: ----------
inference-latency: 2.993 sec.
first-token-latency: 1.010 sec.
rest-token-latency: 0.063 sec.
P90-rest-token-latency: 0.064 sec.

2024-07-22 12:58 UTC, leslie-fang-intel commented
Why the first token latency even worse after this PR?

2024-07-22 13:03 UTC, leslie-fang-intel commented on torch/_inductor/fx_passes/quantization.py
> +            and scales.dtype in [torch.bfloat16, torch.float32]
How did we decide the dtype of scales here? Will it be double?

2024-07-22 13:19 UTC, leslie-fang-intel reviewed
just curious, why the data type of `scales` has changed from `bf16` to `fp32`? `fp32` here caused overhead of 2 conversion and not sure how much overhead it will induce.

2024-07-22 13:19 UTC, leslie-fang-intel commented on torch/_inductor/fx_passes/quantization.py
> +            scales = L[prims.convert_element_type.default](scales, torch.bfloat16)
Instead of hardcode bf16 here, should we get the dtype of x and use it?

2024-07-23 02:29 UTC, jgong5 requested changes

2024-07-23 02:29 UTC, jgong5 commented on test/inductor/test_mkldnn_pattern_matcher.py
> +        s = torch.randn(s_shape, dtype=torch.float32)
does the scale have to be fp32, or it can be of the same type as the input tensor (bf16) as well?

2024-07-23 02:29 UTC, jgong5 commented on torch/_inductor/fx_passes/quantization.py
> +            func2 = L[computation_woq](func1, weight, scales)
I'm a bit confused about the output dtype of woq. Here, we explicitly convert scales to the dtype of the input tensor to match the dtypes and then convert it back to the dtype of scales to match the dtype of the original subgraph. But would these down-conversation worsen the accuracy? Instead, is it better to make the woq return the dtype that matches the scales directly?

2024-07-25 08:43 UTC, Valentine233 commented
Summary
1. The fp32-related discussions above are expected to be solved by https://github.com/pytorch/ao/pull/534.2. 
2. The regression of first token needs a further analysis.

2024-07-27 03:12 UTC, sanchitintel commented
I wonder if it'd make sense to have 2 WoQ GEMM auto-tuning templates & micro-kernel in the future that could leverage such patterns - one for QAT (weights not frozen, so won't be cached),  and another that caches weights.

2024-08-05 00:27 UTC, sanchitintel commented
Hi @Valentine233, can you please add info about the precise benchmark you used, perhaps from your bash history?
I used the following command, but [the benchmark](https://github.com/intel/ai-reference-models/blob/main/models_v2/pytorch/llama/inference/cpu/run_llm.py) goes on for a long time, and only posts E2E latency. I'm guessing computing per-token latency requires modifying the transformers library. Please confirm, thanks!

```
 numactl --membind=0 --cpunodebind=0 -C 0-31 python run_llm.py -m "meta-llama/Llama-2-7b-hf" --device cpu --dtype bf16 --output_dir$(pwd)/tmp --batch-size 256 --ws-total-cores 32 --ws-cores-per-instance 32 --weight-dtype INT8 --benchmark --torchao --inductor --num-iter 10 --num-warmup 1 --profile
```

I'm also seeing this warning. Please advise if it's normal. Thanks!
```
W0804 17:20:34.220000 2951501 torch/_dynamo/convert_frame.py:828] [0/8] torch._dynamo hit config.cache_size_limit (8)
W0804 17:20:34.220000 2951501 torch/_dynamo/convert_frame.py:828] [0/8]    function: 'forward' (transformers/src/transformers/models/llama/modeling_llama.py:639)
W0804 17:20:34.220000 2951501 torch/_dynamo/convert_frame.py:828] [0/8]    last reason: 0/0: ___check_obj_id(L['past_key_values'], 94511674602464)
W0804 17:20:34.220000 2951501 torch/_dynamo/convert_frame.py:828] [0/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W0804 17:20:34.220000 2951501 torch/_dynamo/convert_frame.py:828] [0/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
```

2024-08-05 01:30 UTC, Valentine233 commented
> Hi @Valentine233, can you please add info about the precise benchmark you used, perhaps from your bash history? I used the following command, but [the benchmark](https://github.com/intel/ai-reference-models/blob/main/models_v2/pytorch/llama/inference/cpu/run_llm.py) goes on for a long time, and only posts E2E latency. I'm guessing computing per-token latency requires modifying the transformers library. Please confirm, thanks!
> 
> ```
>  numactl --membind=0 --cpunodebind=0 -C 0-31 python run_llm.py -m "meta-llama/Llama-2-7b-hf" --device cpu --dtype bf16 --output_dir$(pwd)/tmp --batch-size 256 --ws-total-cores 32 --ws-cores-per-instance 32 --weight-dtype INT8 --benchmark --torchao --inductor --num-iter 10 --num-warmup 1 --profile
> ```
> 
> I'm also seeing this warning. Please advise if it's normal. Thanks!
> 
> ```
> W0804 17:20:34.220000 2951501 torch/_dynamo/convert_frame.py:828] [0/8] torch._dynamo hit config.cache_size_limit (8)
> W0804 17:20:34.220000 2951501 torch/_dynamo/convert_frame.py:828] [0/8]    function: 'forward' (transformers/src/transformers/models/llama/modeling_llama.py:639)
> W0804 17:20:34.220000 2951501 torch/_dynamo/convert_frame.py:828] [0/8]    last reason: 0/0: ___check_obj_id(L['past_key_values'], 94511674602464)
> W0804 17:20:34.220000 2951501 torch/_dynamo/convert_frame.py:828] [0/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
> W0804 17:20:34.220000 2951501 torch/_dynamo/convert_frame.py:828] [0/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
> ```

This is the script to run on one node: `numactl -C 56-111 -m 1 python ../../../../../../models/language_modeling/pytorch/llama/inference/cpu/run_llm.py --benchmark --num-warmup 1 --num-iter 2 --token-latency --dtype 'bf16' -m 'meta-llama/Llama-2-7b-hf' --max-new-tokens 32 --input-tokens 32 --batch-size 1 --weight-only-quant --torchao --weight-dtype INT8`. Can't remember about the warning.

2024-08-05 20:12 UTC, sanchitintel commented
After offline discussion with @Valentine233, it turns out that the runtime error I'm encountering at my end (`torch._dynamo.exc.InternalTorchDynamoError: 'PlainAQTLayout' object has no attribute 'layout_type') is similar to https://github.com/pytorch/ao/pull/534#issuecomment-2246726387.

@Valentine233, is it possible for you to rebase your local PyTorch repo & verify whether or not you're also encountering the same problem? Thanks

2024-08-08 03:19 UTC, Valentine233 commented
**Update for first token regression:**

First token has a regression because `aten::_weight_int8pack_mm` is slower than the decomposed one, given certain input shapes. cc @mingfeima @jgong5 @leslie-fang-intel 

### First token
For the first token, the input shapes are x: [128, 4096], w: [4096, 4096], scale: [4096].
**Profiling**
With woq pattern:
![image](https://github.com/user-attachments/assets/18803301-938a-4318-b475-651a89fe083c)
Without woq pattern:
![image](https://github.com/user-attachments/assets/1886de9c-ea07-4ca2-8021-1f693db674d7)


### Next token
For the next token, the input shapes are x: [4, 4096], w: [4096, 4096], scale: [4096].
**Profiling**
With woq pattern:
![image](https://github.com/user-attachments/assets/ff66dd14-a8b5-4dd3-b935-cadbbfdd03fe)
Without woq pattern:
![image](https://github.com/user-attachments/assets/5472b371-1ffb-4096-906d-9ec3f8270c54)

### Reproduce
You could reproduce the result by running the UT added in this PR.

2024-08-08 03:59 UTC, sanchitintel commented
Auto-tuning with WoQ GEMM would not run into this issue because for the first token, the WoQ AMX micro-kernel based implementation would be 1.5x faster than its ATen kernel counterpart (benchmarked with 32 physical cores on a Xeon 4th gen machine with Intel OpenMP & libtamlloc preloaded) .

2024-08-08 06:13 UTC, sanchitintel commented
While auto-tuning would be 1.5x faster for the first token, it too would've resulted in a regression.
`x: [128, 4096], w: [4096, 4096], scale: [4096]` seems to do better if weights are dequantized upfront.

2024-08-19 19:39 UTC, sanchitintel commented
Potential fix - since Xeon CPUs are used on system with a large amount of RAM, we can _optionally_ cache both quantized & dequantized weights for large values of `M` (based on some heuristic), and lower the corresponding FX pattern to a custom function (like the way `quantized_decomposed` custom functions have been defined) that accepts both quantized & dequantized weights. Then that custom function could be lowered to auto-tune WoQ GEMM.

In such a case, the auto-tuning GEMM template could allow a fallback that could be used for large values of `M`, and use the cached dequantized weights if a large value of `M` would be encountered at runtime.

2024-11-17 21:34 UTC, closed without merging