[dynamo][sourceless] Return UserDefinedObjectVariable for unhandled objects
pytorch/pytorch pull request #131414
Opened 2024-07-22 23:57 UTC by anijain2305

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Fixes https://github.com/pytorch/pytorch/issues/130533

2024-07-23 00:21 UTC, williamwen42 approved these changes

2024-07-23 01:18 UTC, mlazos requested changes
I don't think this is a good idea; it will hide issues with SourcelessBuilder and mislead a developer into thinking it's working as intended. Curious if there was a specific use case that drove this? I think I would support this if we already had parity tests with the standard VariableBuilder but we don't today.

2024-07-23 04:26 UTC, anijain2305 commented
@mlazos The usecase is TensorDict and I also remember seeing other issues with similar graph breaks. I agree with your assessment that sourceless builder is not at parity with variable builder, and also that it can hide issues (like using a more narrow variable tracker). 

At the same time, I also think that UserDefinedObjectVariable is not so bad. For `fullgraph=True`, any missing opportunity will be quickly exposed. For `fullgraph=False`, the situation is not so different from today, where once someone works on graph breaks, the opportunity will soon be visible. 

I think I need to maybe make the warning loud or quickly visible, but I don't know where to put it.

2024-07-23 04:37 UTC, anijain2305 commented on torch/_dynamo/variables/builder.py
> +        elif inspect.isclass(type(value)):
Bleh .. this is always True

2024-07-24 14:11 UTC, jansel requested changes
Without a source, how will we property guard on things?

2024-08-15 21:55 UTC, closed without merging