Implement filter in dynamo
pytorch/pytorch pull request #131674
Opened 2024-07-24 17:29 UTC by isuruf

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #131674

Fixes https://github.com/pytorch/pytorch/issues/128944

2024-08-08 00:47 UTC, xinyu-intel commented
@isuruf Hi, can this feature be merged?

2024-08-08 01:21 UTC, isuruf commented
This needs a review. Can you review?

cc @amjames

2024-08-08 17:27 UTC, amjames approved these changes

2024-08-10 01:56 UTC, jansel requested changes

2024-08-10 01:56 UTC, jansel commented on torch/_dynamo/variables/builtin.py
> +                return
Can you add a test the exercise this code path?

2024-08-13 22:43 UTC, jansel approved these changes

2024-08-13 22:44 UTC, jansel commented
@pytorchbot merge

2024-08-14 14:45 UTC, isuruf commented
@pytorchbot merge

2024-08-14 14:54 UTC, closed without merging

2024-09-05 14:44 UTC, tmct commented
Thank you for fix @isuruf - do you know roughly when this might get released? It doesn't look like it made it into 2.4.1

2024-09-05 15:00 UTC, isuruf commented
I assume this will be in the 2.5.0 release.