Change signature of CompilerFn for register_backend decorator
pytorch/pytorch pull request #131880
Opened 2024-07-26 09:05 UTC by redradist

## Description
Add `...` to show that CompilerFn for custom backend could take additional options

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

2024-07-27 01:25 UTC, jansel submitted a review, later dismissed

2024-07-27 01:25 UTC, jansel commented
@pytorchbot merge

2024-07-27 22:21 UTC, redradist commented
@jansel merge bot failed by timeout

2024-07-30 02:56 UTC, jansel commented
@pytorchbot merge

2024-07-30 09:11 UTC, redradist commented
@jansel Again the same issue ...
Something wrong with pipeline, this small PR with typing annotation should not take so much time ...

2024-08-02 10:52 UTC, jansel commented
@pytorchbot merge -f timeouts

2024-08-02 10:53 UTC, jansel commented
@pytorchbot merge

2024-08-02 14:28 UTC, jansel commented
@pytorchbot merge -f "regular merge timeouts multiple times"

2024-08-02 15:47 UTC, albanD commented
@pytorchbot revert -m "Breaking lint" -c nosignal

2024-08-05 17:21 UTC, jansel requested changes
Fix failing CI

2024-11-03 21:34 UTC, closed without merging