[Inductor][CPP] Turns on inline_inbuilt_nn_modules for CPP GEMM template testing
pytorch/pytorch pull request #132487
Opened 2024-08-02 13:32 UTC by leslie-fang-intel

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-08-02 13:51 UTC, anijain2305 approved these changes

2024-08-02 13:51 UTC, anijain2305 commented
Thanks. I forgot to remove that line in the last PR.

2024-08-03 01:27 UTC, jgong5 requested changes
CI failures?

2024-08-03 01:27 UTC, jgong5 commented on test/inductor/test_cpu_select_algorithm.py
>          # Fails due to https://github.com/pytorch/pytorch/issues/131929
Should remove this comment too?

2024-08-03 02:28 UTC, leslie-fang-intel commented on test/inductor/test_cpu_select_algorithm.py
>          # Fails due to https://github.com/pytorch/pytorch/issues/131929
Thanks and removed.

2024-08-03 02:41 UTC, leslie-fang-intel commented
> CI failures?

Hi @anijain2305 @jgong5,

I would like to explain a little more about the UT failures, since it seems tricky....
Generally, I have saw 2 issues related to below 2 test cases.

* Test Case 1:
```
python -u -m pytest -s -v test/inductor/test_cpu_select_algorithm.py -k test_linear_with_pointwise_dynamic_shapes_batch_size_384_in_features_196_out_features_385_bias_False_epilogue_add_cpu_float32
```

* Test Case 2:
```
python -u -m pytest -s -v test/inductor/test_cpu_select_algorithm.py -k test_linear_with_pointwise_dynamic_shapes_batch_size_384_in_features_196_out_features_384_bias_False_epilogue_add_cpu_float32
```

* Issue 1: test with test case 1

  For the way, we modeling post-op add: https://github.com/pytorch/pytorch/blob/64720f3b89a1316d6e0131b20c43d6402bcce4aa/test/inductor/test_cpu_select_algorithm.py#L111
  
  - With `inline_inbuilt_nn_modules` as False, the `other` in add seems be taken as the module attr and cause the batch size dimension specialized. In this way, we can hit `mkl_linear` fusion and lowering into cpp gemm template with `add` be taken as `epilogue` in backend codegen.
  - With `inline_inbuilt_nn_modules` as ON, the `other` in add is a input parameter and the batch size will be a symbolic symbol. For the mkl-linear, we can't do deal with symbolic batch size, and the new lowering flow will be:
      - Fuse `mm` + `add` into `addmm`. The `other` will be taken as the `inp(bias)`.
      - Lowering `addmm` into gemm template.
  
  I feels the above behavior is as expected, @anijain2305 what do you think? If so, we can change the UT correspondingly.

* Issue 2: discrepancy between Test Case 1 and Test Case 2

The only difference is output features is 385 or 384 (same as batch size).

    * For Test Case 1, we have saw batch size as symbolic

    ```
    V0802 19:05:22.665000 3118430 torch/_inductor/freezing.py:117] [0/0]  ===== FROZEN GRAPH =====
    V0802 19:05:22.665000 3118430 torch/_inductor/freezing.py:117] [0/0]  /localdisk/leslie/torch_inductor_community/pytorch/torch/fx/_lazy_graph_module.py class <lambda>(torch.nn.Module):
    V0802 19:05:22.665000 3118430 torch/_inductor/freezing.py:117] [0/0]     def forward(self, arg1_1: "Sym(s0)", arg2_1: "f32[s0, 196]", arg3_1: "f32[s0, 385]"):
    V0802 19:05:22.665000 3118430 torch/_inductor/freezing.py:117] [0/0]          # File: /localdisk/leslie/torch_inductor_community/pytorch/test/inductor/test_cpu_select_algorithm.py:231 in forward, code: return self.epilogue(self.linear(x))
    V0802 19:05:22.665000 3118430 torch/_inductor/freezing.py:117] [0/0]         _frozen_param1: "f32[196, 385]" = self._frozen_param1
    V0802 19:05:22.665000 3118430 torch/_inductor/freezing.py:117] [0/0]         mm: "f32[s0, 385]" = torch.ops.aten.mm.default(arg2_1, _frozen_param1);  arg2_1 = _frozen_param1 = None
    V0802 19:05:22.665000 3118430 torch/_inductor/freezing.py:117] [0/0]         
    V0802 19:05:22.665000 3118430 torch/_inductor/freezing.py:117] [0/0]          # File: /localdisk/leslie/torch_inductor_community/pytorch/test/inductor/test_cpu_select_algorithm.py:110 in <lambda>, code: return lambda x: x + other
    V0802 19:05:22.665000 3118430 torch/_inductor/freezing.py:117] [0/0]         add: "f32[s0, 385]" = torch.ops.aten.add.Tensor(mm, arg3_1);  mm = arg3_1 = None
    V0802 19:05:22.665000 3118430 torch/_inductor/freezing.py:117] [0/0]         return (add,)
    ```

    * For Test Case 2, we have saw batch size as static

    ```
    V0802 19:04:34.003000 3117875 torch/_inductor/freezing.py:117] [0/0]     def forward(self, arg1_1: "f32[384, 196]", arg2_1: "f32[384, 384]"):
    V0802 19:04:34.003000 3117875 torch/_inductor/freezing.py:117] [0/0]         # No stacktrace found for following nodes
    V0802 19:04:34.003000 3117875 torch/_inductor/freezing.py:117] [0/0]         _frozen_param2 = self._frozen_param2
    V0802 19:04:34.003000 3117875 torch/_inductor/freezing.py:117] [0/0]         _frozen_param3 = self._frozen_param3
    V0802 19:04:34.003000 3117875 torch/_inductor/freezing.py:117] [0/0]         
    V0802 19:04:34.003000 3117875 torch/_inductor/freezing.py:117] [0/0]          # File: /localdisk/leslie/torch_inductor_community/pytorch/test/inductor/test_cpu_select_algorithm.py:231 in forward, code: return self.epilogue(self.linear(x))
    V0802 19:04:34.003000 3117875 torch/_inductor/freezing.py:117] [0/0]         _mkl_linear: "f32[384, 384]" = torch.ops.mkl._mkl_linear(arg1_1, _frozen_param3, _frozen_param2, None, 384);  arg1_1 = _frozen_param3 = _frozen_param2 = None
    V0802 19:04:34.003000 3117875 torch/_inductor/freezing.py:117] [0/0]         
    V0802 19:04:34.003000 3117875 torch/_inductor/freezing.py:117] [0/0]          # File: /localdisk/leslie/torch_inductor_community/pytorch/test/inductor/test_cpu_select_algorithm.py:110 in <lambda>, code: return lambda x: x + other
    V0802 19:04:34.003000 3117875 torch/_inductor/freezing.py:117] [0/0]         add: "f32[384, 384]" = torch.ops.aten.add.Tensor(_mkl_linear, arg2_1);  _mkl_linear = arg2_1 = None
    V0802 19:04:34.003000 3117875 torch/_inductor/freezing.py:117] [0/0]         return (add,)
    ```

It looks like a bug?

2024-08-05 20:30 UTC, anijain2305 commented
I think your observation about the + add makes sense to me. When you use +dynamic, torch.compile marks everything dynamic. Taking a step back, if you dont want to mark the batch size dynamic, you could use `torch._dynamo.mark_dynamic` on dimensions to selectively mark dims as dynamic (instead of full blown dynamism).

For issue 2, I don't fully understand the issue. So, let me take a look to understand. Give me a few hours.

2024-08-05 23:25 UTC, anijain2305 commented
@leslie-fang-intel I am struggling with setting up MKL? Are there any instructions? I have 

* Ran `pip install mkl-static mkl-include`
* Ran `USE_MKL=1 USE_MKLDNN=1 python setup.py develop"

But I get these logs during configure
`Library mkl_intel_lp64: not found`

2024-08-06 02:04 UTC, leslie-fang-intel commented
Here is another script to reproduce issue2: https://gist.github.com/leslie-fang-intel/aa58be19808779313cb9aca9730d736e

- Test 1 has symbolic batch size
- Test 2 has static batch size

2024-08-06 04:33 UTC, leslie-fang-intel commented
Sync with @anijain2305, the behavior of second issue mentioned above is expected by design, since dynamo wants to reuse symbols by keeping the num of symbols as low as possible.

2024-08-06 04:37 UTC, anijain2305 commented
@leslie-fang-intel and I debugged this further over slack. Our findings are this

* The discrepancy between N=385 vs N=384 is expected. For N=384,  there are no more symbolic shapes in AOT graph, but  for N=385, batch size is symbolic. This is expected because of a quirk in symbolic shapes infra.

For the test case with N = 384, these are the dimensions M = 384, N = 384, K = 196. The point to note is that M = N. Dynamic shapes infra reuses symbols wherever possible (duck typing) to reduce the number of symbols. And therefore, `s0` is reused and then later get removed.

For the test case with N=385, the dimensions are M = 384, N = 385, and K = 196. 3 different dimensions, 3 different symbols, no removal, resulting in symbolic batch size.

In nutshell, the testcase exposes a quirk (expected though) in dynamic shapes infra. 

I would suggest to rewrite the test cases with M = 16 so that M, N, K are always different, always resulting in symbolic batch size.

2024-08-06 05:33 UTC, xmfan commented
I didn't get the chance to relax the heuristic yet, but I did expose it as a config in https://github.com/pytorch/pytorch/pull/129804. You can also decorate tests with `@torch.fx.experimental._config.patch(use_duck_shape=False)`

2024-08-06 08:48 UTC, leslie-fang-intel commented
After adding `@torch.fx.experimental._config.patch(use_duck_shape=False)`, the preCI passes, @anijain2305 @jgong5 please help to take a look again.

2024-08-06 19:47 UTC, anijain2305 approved these changes

2024-08-07 02:05 UTC, jgong5 approved these changes

2024-08-07 02:11 UTC, leslie-fang-intel commented
@pytorchbot merge

2024-08-08 15:45 UTC, PaliC commented
@pytorchbot revert -m "this pr is breaking inductor tests internally" -c "ghfirst"

I think you should be able to repro these in OSS

pytorch/inductor:cpu_select_algorithm - test_linear_with_pointwise_dynamic_shapes_batch_size_384_in_features_196_out_features_385_bias_False_epilogue_add_cpu_float32

stack trace - https://pastebin.com/xwCrxAa8

pytorch/test/inductor:cpu_select_algorithm - test_linear_with_pointwise_dynamic_shapes_batch_size_384_in_features_196_out_features_384_bias_False_epilogue_add_cpu_float32 

stack trace - https://pastebin.com/WjM6AnAj

2024-08-09 00:39 UTC, leslie-fang-intel commented
Hi @PaliC,

> I think you should be able to repro these in OSS

The testing shows in https://hud.pytorch.org/pr/132487 are all green. Do I need to use some specific system to reproduce this failure?

2024-08-09 01:22 UTC, leslie-fang-intel commented
Hi @PaliC, is the failure you posted running with `is_fbcode == True`?
Since `inline_inbuilt_nn_modules` only turns on when `is_fbcode == False` https://github.com/pytorch/pytorch/blob/313aa151da1b84ccaa7fe0067a683490474f11da/torch/_dynamo/config.py#L374, will it be the root-cause for this failure? I have forced `inline_inbuilt_nn_modules == True` for above testcase, do you think it makes senses @anijain2305?

2024-08-09 11:47 UTC, leslie-fang-intel commented
Hi @PaliC @anijain2305, I have changed to force to turn on `inline_inbuilt_nn_modules`. Could you kindly help to import and check the internal CI status?

2024-08-09 16:46 UTC, anijain2305 approved these changes

2024-08-09 16:49 UTC, anijain2305 commented
ghstack PRs cant be imported internally. I am confident that explicitly turning on the flag should be good enough. Merging for now.

2024-08-09 16:49 UTC, anijain2305 commented
@pytorchbot merge

2024-08-15 21:37 UTC, jansel commented
Reverted by #133570

2024-08-21 03:19 UTC, anijain2305 commented
Requesting here to wait for a week before merging this PR. My reland PR (merged in Oss), which this PR depends upon, is going through internal tests and might need to be reverted again.

2024-08-21 04:14 UTC, leslie-fang-intel commented
> Requesting here to wait for a week before merging this PR. My reland PR (merged in Oss), which this PR depends upon, is going through internal tests and might need to be reverted again.
> 
> Let's wait for a week for things to be stable.

Thanks for the comment. sure, let's wait for a week to land it.

2024-09-03 01:03 UTC, leslie-fang-intel commented
> Requesting here to wait for a week before merging this PR. My reland PR (merged in Oss), which this PR depends upon, is going through internal tests and might need to be reverted again.

> Let's wait for a week for things to be stable.

Hi @anijain2305, since https://github.com/pytorch/pytorch/pull/134136 has landed for more than 2 weeks. I am going to rebase and land this PR. Thanks.

2024-09-03 01:43 UTC, anijain2305 commented
Yes, please. Thanks for your patience.

2024-09-03 04:58 UTC, leslie-fang-intel commented
@pytorchbot merge

2024-09-03 05:05 UTC, closed without merging