use VSL_BRNG_PHILOX4X32X10 for MKL exponential
pytorch/pytorch pull request #132742
Opened 2024-08-06 08:09 UTC by CaoE

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-08-06 08:18 UTC, jgong5 approved these changes

2024-08-06 09:57 UTC, malfet reviewed
Besides the performance number while using this new algorithm, it would be nice to see comparison to the default algorithm as well as some some sort of random distribution tests to validate we would not step into the same issue again. 

Considering that internal state of those algorithms are much larger than 64-bit seed, wouldn't it  be more prudent to construct new vslStream as part of the generator rather than create new stream every time bernoully or exponential kernel is requested to avoid mistakes as it was mentioned in the previous thread

2024-08-06 10:00 UTC, malfet requested changes
I don't think it fixes issue raised in https://discuss.pytorch.org/t/bug-in-torch-multinomial-generated-distribution-is-modestly-incorrect-edit-this-is-a-regression-and-appears-to-be-due-to-an-analogous-bug-in-tensor-exponential namely, 
> seeding a local mersenne twister with the global mersenne twister would still
not be a best practice

2024-10-17 09:20 UTC, CaoE commented
@jeffcoop @malfet  We use `VSL_BRNG_PHILOX4X32X10` (to align with CUDA) instead of `VSL_BRNG_MCG31` for MKL exponential to avoid duplicated permutations under a low number of iterations in this PR. Philox4x32-10 counter-based pseudorandom number generator with a period of 2^128. 
I'm not sure how to avoid seeding a local mersenne twister with the global mersenne twister to use MKL generator (or should we consider integrate MKL generator  to the default generator of torch ? ). Could you please give some advice ? Thanks.

2024-11-11 05:54 UTC, CaoE commented
Hi @malfet @jeffcoop What‘s the best practice do you mean ? 

> seeding a local mersenne twister with the global mersenne twister would still
not be a best practice

What's the problem with this and how do we evaluate it?

2024-11-17 08:06 UTC, jeffcoop commented
Sorry for the delay in reply - If I understand the proposed change correctly, it sounds like each time exponential_ or bernoulli would be called, you'd take 64 bits from the global PRNG as a seed for the local PRNG using VSL_BRNG_PHILOX4X32X10. Even if VSL_BRNG_PHILOX4X32X10 has a period of 2^128, if you use only 64 bits for seeding and you seed/recreate the PRNG every time exponential_ or bernoulli is called, there are still only 2^64 series that exponential_ or bernoulli will ever create. While not as bad as seeding a local PRNG with only 2^32 bits, the birthday paradox still gives a significant chance that in the real world there will situations where exponential_ or bernoulli will have produced identical output at different times.

What seems to me as the 'best' fix for this would be to use a PRNG with a long period and keep it around for multiple calls to exponential_ or bernoulli (i.e. don't re-create it with a new small 64 bit seed on each call). If that can be accomplished, I suspect it is OK to seed the long lived PRNG with 64 bits of the pytorch global PRNG. It would be better still if a single PRNG could be used for both the global pytorch PRNG and the calls to functions like exponential_/bernoulli, but if you have to spawn an additional PRNG you'd be best off if it was long lived and not created/seeded every time it is needed.

All this said, I am not a crypto or rng expert, so this is just my best but still naive suggestion.

2024-12-05 03:19 UTC, CaoE commented
@jeffcoop Thank you for your patience in explaining this. We are looking for the best way to solve this issue. Maybe we can request MKL to add the ability to save intermediate state and avoid setting the seed each time or leverage others RNG libs. Before that, we need to turn on MKL generator https://github.com/pytorch/pytorch/pull/132532.

2025-03-04 06:22 UTC, closed without merging

2025-03-17 10:58 UTC, knjmooney commented
Hi @jeffcoop,

I don't think the birthday paradox is an issue here.

VSL_BRNG_MCG31 produces 1 sequence with a period of 2^32.

VSL_BRNG_PHILOX4X32X10 produces 2^64 sequences, each with a period of 2^128. The proposed patch, as is, will generate a unique non-overlapping sequence for each seed.

I think this patch is good enough as is, but I also posted on #132395 (because it was open) with instructions on how to seed with 128 bits and/or how to avoid reseeding.