xpu: support sycl with torch.utils.cpp_extension.load
pytorch/pytorch pull request #132945
Opened 2024-08-07 22:40 UTC by dvrogozh

This patch adds support for sycl kernels build via `torch.utils.cpp_extension.load` API. Files having `.sycl` extension are considered to have sycl kernels and are compiled with `icpx` (dpc++ sycl compiler from Intel). Files with other extensions, `.cpp`, `.cu`, are handled as before. API supports building sycl along with other file types into single extension.

By default SYCL kernels are compiled for all Intel GPU devices for which pytorch native aten SYCL kernels are compiled. At the moment `pvc,xe-lpg`. This behavior can be overridden by setting `TORCH_CUDA_ARCH_LIST` environment variables to the comma separated list of desired devices to compile for.

Fixes: #132944

2024-08-07 22:54 UTC, dvrogozh commented
FYI, here is PR on HF quanto side which is using this feature:
* https://github.com/huggingface/optimum-quanto/pull/273.

2024-08-08 00:44 UTC, fengyuan14 commented on test/cpp_extensions/xpu_extension.sycl
`.sycl` is not documented by SYCL spec and Intel SYCL compiler implementation. For now, I think it is not proper time to deliver the usage to community. We are following up the feature with compiler team. @EikanWang Please correct me. BTW, it is a good example to show compiler team.

2024-08-08 00:55 UTC, dvrogozh commented on test/cpp_extensions/xpu_extension.sycl
> .sycl is not documented by SYCL spec and Intel SYCL compiler implementation.

Actually I used a documented feature to support files named with `.sycl` extension. Which is while this extension is not automatically recognized by the compiler, you can use `-x <lang>` option to say what's the type of the file which is being compiled. I used `-x c++ file.sycl`.
```
$ icpx --help | grep "\-x "
  -x <language>           Treat subsequent input files as having type <language>
```

I agree that we should follow up with dpc++ compiler asking for automated support of `.sycl` extension. I fill file issue for that tomorrow. But I believe we can proceed in a meanwhile with approach I described above.

2024-08-12 12:39 UTC, EikanWang commented
Feature-wise, I think this PR duplicates with https://github.com/pytorch/pytorch/pull/131276

2024-08-12 12:53 UTC, EikanWang commented on test/cpp_extensions/xpu_extension.sycl
We'd prefer to leave the flexibility to the SYCL compiler community to provide the solution. If SYCL compiler community decides to use file extension to support this case, it is the freedom of the SYCL compiler community to decide which the file extension for SYCL source files should be.

2024-08-12 14:16 UTC, dvrogozh commented
> Feature-wise, I think this PR duplicates with https://github.com/pytorch/pytorch/pull/131276

No, it does not. My PR adds support for the API not handled in 131276. Note that you did not handle this API in IPEX as well. Please, help review again.

2024-08-13 02:20 UTC, EikanWang commented
> > Feature-wise, I think this PR duplicates with #131276
> 
> No, it does not. My PR adds support for the API not handled in 131276. Note that you did not handle this API in IPEX as well. Please, help review again.

It should be part of https://github.com/pytorch/pytorch/pull/131276 as #131276 is an initial support for Intel GPU `cpp_extension`. And why is the #131276 not the prerequisite PR of this PR?

2024-08-13 03:03 UTC, dvrogozh commented
@EikanWang : pytorch provides 3 APIs to build extensions. I think that thru these APIs only 1 was actually implemented by IPEX (`XPUExtension`), another 2 were not - `load()` and `load_inline` ( correct if I am wrong, please). Pay attention that `load*` and `XPUExtension` paths are not actually based on each other - these follow separate implementation paths. There might be few overlapping utility methods, but they are mostly generic without xpu specifics. In general these API paths are different. Thus, I can't consider mine or #131276 to be prerequisite for another. And that was the reason I did not base my PR on top of #131276. Plus, there were some changes I made vs. #131276:
* My PR follows XPU pytorch build pattern where icpx used for sycl code only and clang/gcc used for host compilation. #131276 builds everything with icpx.
* My PR adds test coverage for added extension. It also does not introduce regression in torchvision build 
* My PR also has associated PR in Huggingface quanto adding actual usage for the API. I did not see associated external PR for #131276

| API | IPEX |
| --- | --- |
| `XPUExtension` | implemented |
| `load` | not implemented |
| `load_inline` | not implemented |

2024-08-15 18:44 UTC, dvrogozh commented
Rebased and added support for `load_inline()`

2024-08-16 03:30 UTC, dvrogozh commented
@EikanWang : following our offline discussion I've updated PR to include the full story for `torch.utils.cpp_extension` APIs. This includes implementations for:
* `torch.utils.cpp_extension.load`
* `torch.utils.cpp_extension.load_inline`
* `torch.utils.cpp_extension.SyclExtension` (name to be discussed)

See 3 respective commits for each step. Note that I could not use #131276 as a base even for `SyclExtension` - implementation in this PR follows different pattern and required significant changes.

Things to note:
1. Name of `torch.utils.cpp_extension.SyclExtension`. Should this be `XPUExtension` as suggested in #131276?
2. `SyclExtension` can be built only with Ninja. That's for the reason that current cpp_extension architecture supports devlink step required for SYCL kernels only via Ninja. Non-ninja path (make?) supports only 2 steps: compile and link. Thus, to support this case of SYCL we will need to build everything with icpx compiler which might not be desirable for non-SYCL extensions which can be combined in a build process (see attached test extension architecture). Problem is that at the moment I don't know how to switch build to icpx only for SyclExtension. Hence this limitation.
3. oneDNN, oneMKL and any oneAPI non-SYCL libs are out of the scope of this PR.

I will add comments to #131276 and suggest to help review @132945 instead.

2024-08-16 05:52 UTC, EikanWang commented
@dvrogozh have you synced with @uniartisan?

2024-08-16 14:09 UTC, dvrogozh commented
> @dvrogozh have you synced with @uniartisan?

I replied to @uniartisan in his PR, see https://github.com/pytorch/pytorch/pull/131276#pullrequestreview-2241718169. I hope he will reply there or comment here once he will get a chance.

2024-08-16 19:30 UTC, dvrogozh commented on test/test_cpp_extensions_jit.py
> +            extra_cflags=["-DC10_USING_CUSTOM_GENERATED_MACROS"],
That's not needed anymore after merging #132847. Need to remove.

2024-08-16 19:39 UTC, dvrogozh commented on test/test_cpp_extensions_jit.py
> +            extra_cflags=["-DC10_USING_CUSTOM_GENERATED_MACROS"],
done

2024-08-28 01:17 UTC, dvrogozh commented
@gujinghui @EikanWang @guangyey : can you, please, help review this PR? also, can someone, please, approve to run ci. It would be nice to understand whether there are any issues, for example with bc check.

2024-08-28 23:58 UTC, dvrogozh commented
@EikanWang : as we discussed offline I dropped last commit from this PR which was adding `class SyclExtension`. I pushed a draft #134735 which has the full version from me.

@uniartisan : we are trying to separate PRs for different enabling parts. This one (#132945) will focus on `load()` and `load_inline()` APIs. Please, help to revise your PR with the `class XPUExtension` API. Feel free to borrow code from the draft PR from me (#134735) where I have full version from me covering class API as well.

2024-09-24 19:25 UTC, dvrogozh commented
@pytorchbot label "topic: release notes: xpu"

2024-09-24 19:30 UTC, dvrogozh commented
@EikanWang : please, let me know what I can do to help accelerate review of this PR.

2024-11-21 21:46 UTC, dvrogozh commented
@EikanWang : since we've finished discussions with compiler team, I hope we can continue review of this PR. Since a long time have passed, I brought back full story around cpp_extension API for XPU into this PR including the part I previously separated out into #134735. I think that by now it makes sense to review the story all together since we already spend a lot of time waiting for resolution with compiler team.

2024-11-21 22:01 UTC, dvrogozh commented on test/cpp_extensions/xpu_extension.sycl
Here is summary of discussions with our compiler team and compiler community. At the moment they oppose introducing `.sycl` file extension into the compiler. They also encourage to deal with SYCL/C++ compilation differences on build system level using build system agreed custom file extensions or other methods to logically separate sources. This discussion needs to happen here for PyTorch. Similar discussion is ongoing around SYCL support in cmake.

Overall for the PyTorch cpp_extension feature we have 2 options to proceed:

* **Option 1.** We agree on and introduce custom file extension for SYCL source in PyTorch. That's what this PR is currently doing. **So, proposal is to adopt `.sycl` as a file extension specific to PyTorch ecosystem and further influence other communities to align on that.**
2. **Option 2.** As an alternative, we can introduce other logical separation for SYCL sources. In particular we can:
    * Have `sycl_sources = [ ... ]` variable to take sycl source in `torch.utils.cpp_extension.load` (this will be new a new addition, CUDA does not have that)
    * `torch.utils.cpp_extension.load` already has `cuda_sources` and this PR introduces `sycl_sources`
    * Have both `sources = [...]` and `sycl_sources = [ ... ]` variable on `class SyclExtension` (that will be difference vs. how CUDAExtension class is defined)

Currently PR follows Option 1. Please, let me know your opinions on the better option.

2024-11-22 04:31 UTC, dvrogozh commented
I addressed linter and docs issues found by ci. No functional changes from prev. commit. @EikanWang : please, approve ci run again at your convenience.

2025-01-06 03:32 UTC, EikanWang reviewed
In general, the idea looks good to me. In terms of implementation, I think we need to refine the design gradually to make the torch extension to be modular to generalize the CUDA and XPU extension as different modules.

2025-01-06 03:32 UTC, EikanWang commented on torch/utils/cpp_extension.py
> +            # Ensure at least an empty list of flags for 'cxx', 'nvcc' and 'sycl' when
The list is a compiler list. In terms of SYCL compiler, Intel's brand is DPC++. @gujinghui , do you think we should use `dpc++` here rather than `sycl`?

2025-01-06 03:32 UTC, EikanWang commented on torch/utils/cpp_extension.py
> +        extra_sycl_cflags: optional list of compiler flags to forward to icpx
`icpx` is a new term. We need to unify the sycl compiler term. Either `dpc++` or `icpx`. Meanwhile, I remember that the compiler name is `icx` on windows.

2025-01-06 03:32 UTC, EikanWang commented on torch/utils/cpp_extension.py
> +        sycl_dlink_post_cflags = None
Could we reuse the code block  - https://github.com/pytorch/pytorch/pull/132945/files#diff-258d5272916c8cf5ac89aad77f7c114b585848826f6bbaeee91fe62a4391ee5eR727-R751?

2025-01-06 03:32 UTC, EikanWang commented on torch/utils/cpp_extension.py
> +        ldflags += ['-lsycl-preview']
The Intel GPU development bundle has upgraded to the latest version.
```suggestion
        ldflags += ['-lsycl]
```

2025-01-06 03:33 UTC, EikanWang commented
@pytorchbot rebase

2025-01-06 23:55 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +            # Ensure at least an empty list of flags for 'cxx', 'nvcc' and 'sycl' when
Note that here `sycl` is a key of `extra_compile_args` dictionary which sets a mapping between languages and additional compiler flags to pass to compiler. Note comment to this function:

https://github.com/pytorch/pytorch/blob/729b7c0a84f8819e0bb31ce8f1e048d7bde64b45/torch/utils/cpp_extension.py#L500-L503

I have introduced a new key called `sycl` for the reason that I am actually trying to abstract away from Intel branded DPC++ compiler. Note that in the future. hopefully, SYCL support will be available in clang. And in general there might be other SYCL compilers besides DPC++. Thus, question here is: should they key be named per language (in this case it should be `sycl`) or per-compiler (in this case I should rename to `dpc++`)?

2025-01-06 23:56 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +        extra_sycl_cflags: optional list of compiler flags to forward to icpx
I reworded from icpx to DPC++ compiler here and in few other places in comments.

2025-01-07 00:02 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +        sycl_dlink_post_cflags = None
Well, that's challenging. As much as I wished to reuse, unfortunately these code blocks are different. They correspond to 2 different Extension APIs: one for `torch.utils.cpp_extension.load()` and anther for `class SyclExtension`. And these paths are implemented differently (same for cuda and cpp).

Additional difficulty is `-fsycl-host-compiler-options` option which is qouted space containing string which should be properly escaped. And code to correctly escape it is different for 2 Extension API scenarios noted above.

I have tried to improve this code block - see few new commits. I can't 100% reuse the code due to above reasons, but at least I moved definition of common flags to the global scope which allowed to simplify code a bit and somewhat reduce duplication.

2025-01-07 03:55 UTC, gujinghui commented on torch/utils/cpp_extension.py
> +            # Ensure at least an empty list of flags for 'cxx', 'nvcc' and 'sycl' when
In this context, `cxx` and `nvcc` are specifying the compilers, instead of languages.
If not introduce `dpc++`, we should use `sycl compiler` at least, instead of `sycl`?

2025-01-07 03:59 UTC, gujinghui commented on test/cpp_extensions/xpu_extension.sycl
> +// NOTE: this is a cuda_extension.cu kernel converted to SYCL
Do we still need this comments? @dvrogozh

2025-01-07 04:03 UTC, gujinghui commented on torch/utils/cpp_extension.py
> -    languages (``cxx`` or ``nvcc``) to a list of additional compiler flags to
why they called nvcc is a language? Is it correct?

2025-01-07 04:04 UTC, gujinghui commented on torch/utils/cpp_extension.py
> +        self.compiler.src_extensions += ['.cu', '.cuh', '.hip', '.sycl']
should we highlight here, the .sycl is not a SYCL std file ext, actually...

2025-01-07 04:06 UTC, gujinghui commented on torch/utils/cpp_extension.py
> +                # escaping quoted arguments to pass them thru DPC++ compiler
Sounds like confused. Here we introduced DPC++ compiler brand...
Should we unify the name in both comments and code line?
`dpc++` or `sycl compiler`

2025-01-07 05:43 UTC, EikanWang commented on torch/utils/cpp_extension.py
> -    languages (``cxx`` or ``nvcc``) to a list of additional compiler flags to
It should be a typo.

2025-01-09 22:01 UTC, dvrogozh commented on test/cpp_extensions/xpu_extension.sycl
> +// NOTE: this is a cuda_extension.cu kernel converted to SYCL
I left this comment since I thought it might be useful (in a sense of support) to highlight that this sycl kernel is basically the same as the noted cuda kernel. If you think that's not needed, I can drop.

2025-01-09 22:07 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +            # Ensure at least an empty list of flags for 'cxx', 'nvcc' and 'sycl' when
> If not introduce `dpc++`, we should use `sycl compiler` at least, instead of sycl?

`sycl compiler` does not make a sense to me as a dictionary key. Review https://github.com/pytorch/pytorch/blob/main/test/cpp_extensions/setup.py or here in this PR above. `nvcc`, `cxx` and (this PR introduces) `sycl` are dictionary keys:

```
    extension = CUDAExtension(
        "torch_test_cpp_extension.torch_library",
        ["torch_library.cu"],
        extra_compile_args={"cxx": CXX_FLAGS, "nvcc": ["-O2"]},
    )
...
    extension = SyclExtension(
        "torch_test_cpp_extension.sycl",
        ["xpu_extension.sycl"],
        extra_compile_args={"cxx": CXX_FLAGS, "sycl": ["-O2"]},
    )
```

2025-01-09 22:08 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> -    languages (``cxx`` or ``nvcc``) to a list of additional compiler flags to
Note that this ended up in the API (see `nvcc` key below):
https://github.com/pytorch/pytorch/blob/379b54603a41f31e4524e83321497af255e50aeb/test/cpp_extensions/setup.py#L52

2025-01-09 22:53 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +                # escaping quoted arguments to pass them thru DPC++ compiler
ok, I switched to `SYCL compiler` in the comments to be consistent with the code.

2025-01-09 22:53 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +        self.compiler.src_extensions += ['.cu', '.cuh', '.hip', '.sycl']
I left a comment in the last version. Done.

2025-01-10 02:36 UTC, EikanWang requested changes

2025-01-10 02:36 UTC, EikanWang commented on torch/utils/cpp_extension.py
> +e.
```suggestion
    `sycl_dlink_post_cflags`: list of flags to append to the $nvcc device code link invocation. Can be None.
```

2025-01-10 02:36 UTC, EikanWang commented on torch/utils/cpp_extension.py
> +]
We have upgraded the oneAPI to the latest version, the two flags are not necessary.

2025-01-10 02:36 UTC, EikanWang commented on torch/utils/cpp_extension.py
> +SYCL_ARCH_LIST = os.environ.get('TORCH_XPU_ARCH_LIST', 'pvc,xe-lpg')
Pls. help add `xe2-lpg` and `xe2-hpg` to the default `ARCH_LIST`

2025-01-10 02:36 UTC, EikanWang commented on torch/utils/cpp_extension.py
> +        with_sycl = any(map(_is_cuda_file, sources))
```suggestion
        with_sycl = any(map(_is_sycl_file, sources))
```

2025-01-10 02:37 UTC, EikanWang commented on torch/utils/cpp_extension.py
> +        sycl = 'icpx'
@dvrogozh , For Windows, it should be `icx`

2025-01-10 03:08 UTC, gujinghui commented on test/cpp_extensions/xpu_extension.sycl
> +// NOTE: this is a cuda_extension.cu kernel converted to SYCL
better to remove it, not sure it gives right message to user.

2025-01-10 15:08 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +e.
thx. And need to change `$nvcc` to "SYCL compiler".

2025-01-10 19:40 UTC, dvrogozh commented on test/cpp_extensions/xpu_extension.sycl
> +// NOTE: this is a cuda_extension.cu kernel converted to SYCL
removed

2025-01-10 19:41 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +e.
fixed

2025-01-10 19:44 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +        with_sycl = any(map(_is_cuda_file, sources))
fixed

2025-01-10 19:44 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +        sycl = 'icpx'
fixed

2025-01-10 20:03 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +]
removed

2025-01-24 21:34 UTC, dvrogozh commented
@EikanWang @gujinghui : I addressed your comments, can you, please, review again?

@albanD : can you, please, help to review this PR?

2025-01-26 04:45 UTC, EikanWang commented
> @EikanWang : 2 cases are failing with overflow error. I have some doubt that this is a regression associated with this PR. Did you see such behavior in other runs?

Nope. However, it is an Inductor test case. I am perplexed that this PR could impact Inductor behavior.

2025-01-27 17:04 UTC, albanD reviewed
Sounds mostly ok!

2025-01-27 17:04 UTC, albanD commented on torch/utils/cpp_extension.py
> +    languages (``cxx``, ``nvcc`` or ``sycl``) to a list of additional compiler flags to
```suggestion
    languages/compiler (the only expected values are``cxx``, ``nvcc`` or ``sycl``) to a list of additional compiler flags to
```

2025-01-27 17:04 UTC, albanD commented on torch/utils/cpp_extension.py
> +                if cuda_ext and sycl_ext:
```suggestion
                if cuda_ext or sycl_ext:
```
?

2025-01-27 17:04 UTC, albanD commented on torch/utils/cpp_extension.py
> +    libraries.append("torch_python")
You should handle py_limited_api properly here like others.
(this was added after the original version of this PR, so expected to be missing right now).

2025-01-27 18:24 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +
I think these should not be made public. I just reused naming convention I saw above. If you are ok, I will make new ones (SYCL related) as not public. Is adding leading underscore to the names enough or you have better way to handle that? (`s/COMMON_SYCL_FLAGS/_COMMON_SYCL_FLAGS/`, etc.)

2025-01-27 18:36 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +                if cuda_ext and sycl_ext:
That was not a typo. The reason for  `and` was to support a potential case when someone builds an extension which mixes cuda and sycl sources. In such a case we are looking for _all_ known extensions in this loop and condition is to stop looking once there is no more need to continue the loop, i.e. we found that both are used.

If you believe mix of cuda/sycl sources is too artificial to support - I can change to `or`. I in any case will update and add a comment describing the reasoning behind the condition.

2025-01-27 18:51 UTC, albanD commented on torch/utils/cpp_extension.py
> +
Leading underscore is the way to go yes.

2025-01-27 18:54 UTC, albanD commented on torch/utils/cpp_extension.py
> +                if cuda_ext and sycl_ext:
Yeah I was assuming you never have both haha
This check is inconsistent with the while loop condition though. If you want to handle having both, the while condition needs updating. Otherwise this one can be relaxed.

2025-01-28 01:25 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +                if cuda_ext and sycl_ext:
I fixed condition in `while` and added a comment. Hope that's correct now. Let me know if not :).

2025-01-28 01:25 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +
done

2025-01-28 01:35 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +    libraries.append("torch_python")
I've added handling of `py_limited_api`.. However, at the moment I can't verify that this path is working for XPU. Looking into https://github.com/pytorch/pytorch/pull/138088 I see that test was added for `py_limited_api`. I've extended test (locally) to work for XPU and it occurs that XPU does not install as much aten headers as CUDA does. For the test  `ATen/ops/cat_cuda_dispatch.h` and `ATen/ops/norm_cuda_dispatch.h` are missing. Basically currently for XPU we have:
```
$ find torch/include/ATen/ops -name "*xpu*"
torch/include/ATen/ops/baddbmm_xpu_dispatch.h
torch/include/ATen/ops/bmm_xpu_dispatch.h
torch/include/ATen/ops/mm_xpu_dispatch.h
torch/include/ATen/ops/_addmm_activation_xpu_dispatch.h
torch/include/ATen/ops/addmm_xpu_dispatch.h
torch/include/ATen/ops/addmv_xpu_dispatch.h
torch/include/ATen/ops/addbmm_xpu_dispatch.h
```
And for CUDA we have a bunch more:
```
$ find torch/include/ATen/ops -name "*cuda*" | wc -l
604
```
So I need to find out why XPU does not install all these headers (we do generate them, but they are not getting installed). Unfortunately I am not familiar with this part of the pytorch build system... So I am investigating. If someone can give me some hints to help - post a comment.

2025-01-28 17:55 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +    languages (``cxx``, ``nvcc`` or ``sycl``) to a list of additional compiler flags to
done

2025-01-28 18:21 UTC, albanD approved these changes
Change sounds ok to me !
Thanks for the update

2025-01-29 01:10 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +    libraries.append("torch_python")
I have filed https://github.com/pytorch/pytorch/issues/145902 to track issue with missing aten xpu header files.

2025-02-08 02:14 UTC, guangyey commented on torch/utils/cpp_extension.py
> +_SYCL_ARCH_LIST = os.environ.get('TORCH_XPU_ARCH_LIST',
Could we add a function to determine which arch list is preferred? When `TORCH_XPU_ARCH_LIST` is `None,` should we recommend using `torch.xpu.get_arch_list` by default?

2025-02-08 02:46 UTC, guangyey commented on torch/utils/cpp_extension.py
> +        shlex.quote(f'-fsycl-host-compiler-options={cflags}'),
Refer to https://github.com/intel/llvm/blob/1e3940b05297795d2584fccc7f0de2a3152dec09/sycl/doc/UsersManual.md?plain=1#L385, `opts` should be quoted as a string instead of the whole statement.
```suggestion
        f'-fsycl-host-compiler-options="{cflags}",
```

2025-02-08 02:56 UTC, guangyey commented on torch/utils/cpp_extension.py
> +                with_sycl=False)
Why sycl doesn't support on windows + ninja?

2025-02-08 02:58 UTC, guangyey approved these changes
Some nits, overall LGTM.

2025-02-08 05:30 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +        shlex.quote(f'-fsycl-host-compiler-options={cflags}'),
@guangyey, unfortunately this won't work. I tried your change - it causes compilation failure. Actually I have spent significant time figuring out how to make this place working. What I currently have in the PR is the working variant. Other variants did not work for me. The reason why this is complicated is that we need to pass quoted arguments inside a quoted string. Something like:
```
-fsycl-host-compiler-options="-Wno-unused-result -DPYBIND11_COMPILER_TYPE=\"_gcc\" "
```
And the way dpc++ compiler is implemented complicates this out (due to having a shell wrapper). By fact we have few layers which attempt to drop quotes. As a result we need to heavily escape them.

Note that ultimate goal is to pass `-fsycl-host-compiler-options=str` argument as a single argument to dpc++. Quotes in the documentation is just one way to achieve that. Another way is to quote entire argument and yet another way would be to escape spaces. So, PR achieves the goal by quoting the whole argument, i.e. we pass:
```
<...> -fsycl-host-compiler=c++  '-fsycl-host-compiler-options=-Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/dvrogozh/git/pytorch/pytorch/torch/include -I/home/dvrogozh/git/pytorch/pytorch/torch/include/torch/csrc/api/include -I/home/dvrogozh/git/pytorch/pytorch/test/cpp_extensions/self_compiler_include_dirs_test -I/home/dvrogozh/pytorch.xpu/include -I/usr/include/python3.10 -c -g -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\\"_gcc\\" -DPYBIND11_STDLIB=\\"_libstdcpp\\" -DPYBIND11_BUILD_ABI=\\"_cxxabi1016\\" -DTORCH_EXTENSION_NAME=sycl -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++17' <...> 
```

See also https://github.com/intel/llvm/issues/15016 on that.

2025-02-08 05:31 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +                with_sycl=False)
In this PR - by intent. I focused on implementing this support for Linux as the first step. In followed up PR this support might need to be extended for Windows.

2025-02-08 06:09 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +_SYCL_ARCH_LIST = os.environ.get('TORCH_XPU_ARCH_LIST',
Done. `torch.xpu.get_arch_list` was added after I created a PR, so I missed it. I think it's a good idea to align with how pytorch is built using this mechanism. Thank you for advice.

2025-02-08 08:56 UTC, guangyey commented on torch/utils/cpp_extension.py
> +        shlex.quote(f'-fsycl-host-compiler-options={cflags}'),
I see. Thanks for your elaboration.

2025-02-11 03:09 UTC, dvrogozh commented
@EikanWang, @gujinghui : can you, please, help review again and merge if no more concerns?

2025-02-15 03:34 UTC, EikanWang commented
@pytorchbot rebase

2025-02-16 07:48 UTC, EikanWang commented
@pytorchbot merge

2025-02-16 16:00 UTC, malfet commented
@pytorchbto revert -m "It just broke all the tests, see https://hud.pytorch.org/hud/pytorch/pytorch/b16ae97ad03a6f376988e505fa23734523d0b4c5/1?per_page=50" -c nosignal

2025-02-16 16:02 UTC, malfet commented
@pytorchbot revert -m "It just broke all the tests, see https://hud.pytorch.org/hud/pytorch/pytorch/b16ae97ad03a6f376988e505fa23734523d0b4c5/1?per_page=50" -c nosignal

2025-02-16 16:05 UTC, malfet commented on torch/utils/cpp_extension.py
> +    f'-Xs "-device {_get_sycl_arch_list()}"',
Two remarks: this is computed at import time, therefore, as most of the users will not have `TORCH_XPU_ARCH_LIST` calls `torch.xpu.get_arch_list()` which causes extension compilation to fail on platforms that compiled without Sycl

2025-02-16 16:06 UTC, malfet commented on torch/utils/cpp_extension.py
> +    arch_list = torch.xpu.get_arch_list()
```suggestion
    if not torch.xpu.is_available():
        return ""
    arch_list = torch.xpu.get_arch_list()
```

2025-02-16 16:07 UTC, malfet approved these changes

2025-02-16 16:26 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +    f'-Xs "-device {_get_sycl_arch_list()}"',
`ciflow/trunk` label was missing on this PR before the merge was triggered. So, we've missed the failure. Thank you for the quick notice.

2025-02-16 16:39 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +    arch_list = torch.xpu.get_arch_list()
While this change will probably resolve the failure noticed by ci, it binds compiling of sycl extension to the systems which have XPU devices unless `TORCH_XPU_ARCH_LIST` is explicitly set.

I guess failure is coming from this line:
https://github.com/pytorch/pytorch/blob/dd5d0ea6bb058e84625a05b0531650d890824b30/torch/xpu/__init__.py#L423
I.e. at the moment `torch.xpu.get_arch_list()` will work only if torch is compiled with XPU support. I suggest to modify `torch.xpu.get_arch_list()` in a way that it will return `[]` in such a case instead. This will help to avoid having XPU device to compile sycl extensions.

2025-02-16 16:49 UTC, malfet commented
@pytorchbot merge -f "Lint is green, let's test in prod"

2025-02-16 16:51 UTC, closed without merging

2025-02-16 16:53 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +    arch_list = torch.xpu.get_arch_list()
I will follow up on this proposal in a separate PR.

2025-02-19 02:19 UTC, dvrogozh commented on torch/utils/cpp_extension.py
> +    arch_list = torch.xpu.get_arch_list()
> I will follow up on this proposal in a separate PR.

Submitted https://github.com/pytorch/pytorch/pull/147431