Fix clang-tidy warnings
pytorch/pytorch pull request #133067
Opened 2024-08-09 03:43 UTC by cyyever

Fixes #ISSUE_NUMBER

2024-08-09 16:01 UTC, Skylion007 commented on torch/csrc/jit/mobile/file_format.h
> -// NOLINTNEXTLINE(facebook-hte-NamespaceScopedStaticDeclaration)
Ugh, I think these are internal clang-tidy checks? We can't  shouldn't just disable them.

2024-08-09 16:02 UTC, Skylion007 requested changes
don't disable facebook clang-tidy lint. It will break internal lints

2024-08-10 00:42 UTC, cyyever commented
> don't disable facebook clang-tidy lint. It will break internal lints

Turned them from 'static inline' to inline, which should fix the lints.

2024-08-13 12:41 UTC, Skylion007 approved these changes

2024-08-13 13:15 UTC, cyyever commented
@pytorchmergebot merge

2024-08-13 15:59 UTC, closed without merging