[dynamo] simplify implementation for `functools.reduce`
pytorch/pytorch pull request #133778
Opened 2024-08-17 19:11 UTC by XuehaiPan

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-08-19 17:24 UTC, jansel approved these changes

2024-08-23 09:09 UTC, XuehaiPan commented
@pytorchbot merge -f "all tests pass, stuck at rocm ci queue"

2024-08-26 15:07 UTC, ZainRizvi commented
@pytorchbot revert -c "ghfirst" -m "Sorry, but this breaks internal tests because of using functools"

Exact error:

```
Unsupported: Graph break due to unsupported builtin _functools.reduce. This function is either a Python builtin (e.g. _warnings.warn) or a third-party C/C++ Python extension (perhaps created with pybind). If it is a Python builtin, please file an issue on GitHub so the PyTorch team can add support for it and see the next case for a workaround. If it is a third-party C/C++ Python extension, please either wrap it into a PyTorch-understood custom operator (see [https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html](https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html) for more details) or, if it is traceable, use torch.compiler.allow_in_graph.
```

2024-08-26 15:08 UTC, ZainRizvi commented
@jansel can you please help @XuehaiPan test his fixes?  The corresponding diff is D61717934

2024-08-26 17:45 UTC, anijain2305 approved these changes

2024-08-30 16:03 UTC, ZainRizvi commented
@pytrochbot revert -c ghfirst -m "This is still failing internally with the same error about "Graph break due to unsupported builtin _functools.reduce'"

@jansel, I would recommend helping @XuehaiPan by doing a ghimport of this diff to validate that it passes internal tests before this is relanded. 

Error:
torch/_dynamo/variables/functions.py:730: UserWarning: Graph break due to unsupported builtin _functools.reduce. This function is either a Python builtin (e.g. _warnings.warn) or a third-party C/C++ Python extension (perhaps created with pybind). If it is a Python builtin, please file an issue on GitHub so the PyTorch team can add support for it and see the next case for a workaround. If it is a third-party C/C++ Python extension, please either wrap it into a PyTorch-understood custom operator (see [https://pytorch.org/.../adva.../custom_ops_landing_page.html](https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html) for more details) or, if it is traceable, use torch.compiler.allow_in_graph.
  torch._dynamo.utils.warn_once(msg)

2024-08-30 16:03 UTC, ZainRizvi commented
@pytorchbot revert -c ghfirst -m "This is still failing internally with the same error about "Graph break due to unsupported builtin _functools.reduce'"

@jansel, I would recommend helping @XuehaiPan by doing a ghimport of this diff to validate that it passes internal tests before this is relanded.

Error:
torch/_dynamo/variables/functions.py:730: UserWarning: Graph break due to unsupported builtin _functools.reduce. This function is either a Python builtin (e.g. _warnings.warn) or a third-party C/C++ Python extension (perhaps created with pybind). If it is a Python builtin, please file an issue on GitHub so the PyTorch team can add support for it and see the next case for a workaround. If it is a third-party C/C++ Python extension, please either wrap it into a PyTorch-understood custom operator (see [https://pytorch.org/.../adva.../custom_ops_landing_page.html](https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html) for more details) or, if it is traceable, use torch.compiler.allow_in_graph.
torch._dynamo.utils.warn_once(msg)

2024-08-30 16:04 UTC, ZainRizvi commented
@pytorchbot revert -c ghfirst -m "This is still failing internally with the same error about 'Graph break due to unsupported builtin _functools.reduce'"

@jansel, I would recommend helping @XuehaiPan by doing a ghimport of this diff to validate that it passes internal tests before this is relanded.

Error:
torch/_dynamo/variables/functions.py:730: UserWarning: Graph break due to unsupported builtin _functools.reduce. This function is either a Python builtin (e.g. _warnings.warn) or a third-party C/C++ Python extension (perhaps created with pybind). If it is a Python builtin, please file an issue on GitHub so the PyTorch team can add support for it and see the next case for a workaround. If it is a third-party C/C++ Python extension, please either wrap it into a PyTorch-understood custom operator (see [https://pytorch.org/.../adva.../custom_ops_landing_page.html](https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html) for more details) or, if it is traceable, use torch.compiler.allow_in_graph.
torch._dynamo.utils.warn_once(msg)

2024-08-30 16:04 UTC, ZainRizvi commented
details on the failure are in D62009011

2024-08-31 11:21 UTC, XuehaiPan commented on torch/_dynamo/variables/builtin.py
> -            return BuiltinVariable(functools.reduce).call_function(
We need to change some hardcoded handlers to use `SourcelessBuilder.create(tx, value)`.

2024-08-31 18:00 UTC, jansel requested changes
Please add a test that reproduces the error message that caused the revert.

2024-09-11 19:06 UTC, XuehaiPan commented on torch/_dynamo/trace_rules.py
> +    if issubclass(rule, UserFunctionVariable):
I think the internal breakage is caused by this.

2024-09-12 05:15 UTC, jansel requested changes
Test failures?

2024-09-16 03:16 UTC, jansel approved these changes

2024-09-16 04:53 UTC, closed without merging