update xeon launch script for GNR support
pytorch/pytorch pull request #133835
Opened 2024-08-19 05:30 UTC by jingxu10

Add support to Intel Xeon SP GNR and Core CPUs with E and P cores.

2024-08-22 02:20 UTC, jingxu10 commented
Hi @malfet @albanD @kiukchung Any suggestions how should we step forward? Thank you.

2024-10-16 23:05 UTC, malfet commented on torch/backends/xeon/_cpu_info.py
> +        elif platform.system() == "Linux":
IMO this should be `if platform.system() == "Linux" and platform.machine() == "x86_64": ... else: raise RuntimeError(f"Unsupported platform {platform.system()}")` to cover both Windows, MacOS as well as LinuxARM

2024-10-16 23:06 UTC, malfet commented on torch/backends/xeon/_cpu_info.py
> +                )
Why this information can be queried from `lscpu` rather than using cpuinfo?

2024-10-18 01:40 UTC, malfet requested changes
My biggest challenge with this change, is that it `lscpu --extended` output is not really defined anywhere.

I.e. on my machine it produces following output
```
 lscpu --extend --all
CPU CLUSTER CORE L1d:L1i:L2 ONLINE
  0       0    0 0:0:0         yes
  1       0    1 1:1:0         yes
  2       0    2 2:2:0         yes
  3       0    3 3:3:0         yes
  4       0    4 4:4:0         yes
  5       0    5 5:5:0         yes
  6       0    6 6:6:0         yes
  7       0    7 7:7:0         yes
  8       0    8 8:8:0         yes
  9       0    9 9:9:0         yes
```
whereas `lscpu --parse=CPU,Core,Socket,Node` always produces results in the same manner


`lscpu --extended --json` seems to be a good middle ground

2025-01-16 02:46 UTC, closed without merging