[training ir migration] Fix ReorderConvertTest
pytorch/pytorch pull request #134010
Opened 2024-08-20 16:44 UTC by yushangdi

Summary:
Change ReorderConvertTest to work with the new `capture_pre_autograd_graph` implementation using D61175223.

Note that now `ReorderConvertTest` doesn't work with the old `capture_pre_autograd_graph` anymore.

Test Plan:
```
buck2 run 'fbcode//mode/dev-nosan' fbcode//bolt/nn/executorch/passes/tests:optimize_test -- -r ReorderConvertTest
```

Differential Revision: D61507772

2024-08-20 18:09 UTC, tugsbayasgalan approved these changes

2024-08-20 18:10 UTC, tugsbayasgalan requested changes
Sorry we still need the rollout check right?

2024-08-20 18:17 UTC, tugsbayasgalan approved these changes

2024-08-20 18:19 UTC, yushangdi commented
> Sorry we still need the rollout check right?

discussed in chat. The rollout check list is empty now because all tests now works for the default capture_preautograd_grpah. We'll add back the rollout check list in https://github.com/pytorch/pytorch/pull/132815

2024-08-20 23:48 UTC, yushangdi commented
@pytorchbot merge

2024-08-21 04:41 UTC, yushangdi commented
@pytorchbot merge -i

2024-08-21 04:48 UTC, closed without merging