Support __class__ attr and construct from class for tuple and list
pytorch/pytorch pull request #134099
Opened 2024-08-21 09:20 UTC by jerrychenhf

Fixes #134086

This supports __class__ attribute for TupleVariable and ListVariable. And allows to construct a tuple or list by using __class__ attribute. This patch also fix a bug in NamedTupleVariable which misses a return on calling super var_getattr.

2024-08-28 02:38 UTC, xinyu-intel commented
@jgong5 @EikanWang @jansel Hello, can you help review this PR?

2024-08-28 04:49 UTC, anijain2305 approved these changes

2024-08-29 01:29 UTC, jansel requested changes
Failing tests?

2024-08-29 05:18 UTC, jerrychenhf commented
@jansel Fixed the test failures. And also refined the PR for considering tuple and list as builtin instead of user defined class.

2024-08-29 05:23 UTC, xinyu-intel commented
@pytorchbot label "topic: not user facing"

2024-08-29 15:59 UTC, jansel approved these changes

2024-08-29 22:55 UTC, anijain2305 commented
@pytorchbot merge

2024-08-30 01:57 UTC, closed without merging