Fix module call_impl to support module level full backward hooks
pytorch/pytorch pull request #134411
Opened 2024-08-25 10:41 UTC by jerrychenhf

Fixes #133303
When there is a backward hook registered for sub module, there are graph breaks caused by Unsupported: call_method NNModuleVariable() _get_backward_hooks [] {}. The same thing happened for _get_backward_pre_hooks. 

These functions were defined as member of nn.Module which is not supported in NNModuleVariable. While instead of implementing the complex thing in NNModuleVariable, it is more proper to just make _get_backward_hooks  and _get_backward_pre_hooks being traceable directly by Dynamo. This is can be achieved simply by moving the two functions out from nn.Module as utility function and pass the nn.Module (self) as parameter.

2024-08-26 18:16 UTC, xmfan commented
The _get_backward_hooks implementation seems reasonable, and its pattern is likely to appear in other forms of user code. I feel like this should be supported by Dynamo. Let me take a look at what's breaking

2024-08-26 18:22 UTC, xmfan commented
Answered in issue, I think this is already supported in nightly

2024-08-28 04:52 UTC, anijain2305 requested changes
We should make TorchDynamo support this.

2024-08-30 10:21 UTC, jerrychenhf commented
Based on the discussion in the issue, Set flag torch._dynamo.config.inline_inbuilt_nn_modules=True can solve the issue on PT 2.4.0. And torch._dynamo.config.inline_inbuilt_nn_modules is by default to True on nightly (2.5.0).

Thus the PR is not needed.

2024-09-13 17:51 UTC, closed without merging