aarch64: add neoverse_v2 checks to matmul gemm heuristics
pytorch/pytorch pull request #134548
Opened 2024-08-27 03:46 UTC by snadampal

2024-09-04 21:44 UTC, snadampal commented
Hi @malfet , could you please review and approve if it looks good.

2024-09-04 21:47 UTC, malfet commented
@snadampal overall looks good, but can you please provide a short description on why this change is needed?

2024-09-04 21:50 UTC, malfet commented on aten/src/ATen/native/LinearAlgebra.cpp
> +          (cpuinfo_get_uarch(0)->uarch == cpuinfo_uarch_neoverse_v1 || cpuinfo_get_uarch(0)->uarch == cpuinfo_uarch_neoverse_v2)) {
Can you please elaborate why this heuristic should be applied to neonvese_v2 but not to neonverse_n2?
Also, considering the code is almost identical between `get_mkldnn_matmul_min_dim` and `get_mkldnn_matmul_min_size` do you mind refactoring this into `is_arm_neonverse()` helper routine

2024-09-05 17:31 UTC, malfet requested changes
@snadampal please ping me on PR when this change will apply to all neonverse arches and condition is refactored into a common function

2024-09-05 23:19 UTC, malfet approved these changes
Thank you for the updates, looks good to me

2024-09-05 23:20 UTC, malfet commented
@pytorchbot merge

2024-09-06 00:28 UTC, snadampal commented
@malfet , thanks for initiating the merge. I was waiting for the CI runs to complete to ping you.

2024-09-06 01:40 UTC, closed without merging