Return unsafe_view instead of view from matmul when folding occurs
pytorch/pytorch pull request #134568
Opened 2024-08-27 08:48 UTC by jwieczorekhabana

When tensor folding occurs during matmul operation returned tensor is a view. This can cause issues when matmul is used inside a custom function and such view is then returned as output. Then it cannot be modified inplace and causes errors.
It can be especially problematic when after such function inplace allreduce is performed.
Issue is resolved when unsafe_view is returned from matmul instead. This solution aligns matmul decomposition with eager implementation in such a way that a non view tensor is returned.

Test included in this PR reproduces the issue.

2024-08-27 12:08 UTC, xinyu-intel commented
@jgong5 @EikanWang Hi, can you help on review the PR?

2024-08-27 12:52 UTC, jwieczorekhabana commented
Error thrown:
![image](https://github.com/user-attachments/assets/e1cd31d9-6a3d-424a-9531-6a53026e342f)

2024-08-28 07:34 UTC, jwieczorekhabana commented
@zou3519 Hi I have linter patch ready. In the error messages I've also seen note about adding test owner. From what I've seen in similar test it's just '# Owner(s): ["module: unknown"]. I'm also wondering whether it's the right place for this kind of test or you might already have a more fitted suite somewhere else. Could you give any hints on that?

2024-08-30 14:56 UTC, zou3519 commented on test/custom_function/test_custom_function.py
> +        """
Move this to test/dynamo/test_misc.py

2024-08-30 14:56 UTC, zou3519 reviewed
The code change makes sense to me. Let's move the test to an existing file rather than put it in its own testcase.

2024-09-02 11:50 UTC, xinyu-intel commented
@pytorchbot label "topic: not user facing"

2024-09-03 18:01 UTC, zou3519 approved these changes

2024-09-05 05:47 UTC, jwieczorekhabana commented
@pytorchbot rebase

2024-09-05 14:21 UTC, zou3519 commented
@pytorchbot rebase

2024-09-05 23:06 UTC, zou3519 requested changes
lint failing

2024-09-18 06:27 UTC, jwieczorekhabana commented
> lint failing

done

2024-09-18 16:17 UTC, zou3519 approved these changes

2024-09-19 11:44 UTC, jwieczorekhabana commented
@pytorchbot merge

2024-09-19 11:52 UTC, closed without merging