[Flex Attention] update __getitem__ without tree_map_only to support compile
pytorch/pytorch pull request #134627
Opened 2024-08-27 23:25 UTC by BoyuanFeng

Adds a helper function for getting the block mask for a specific row index during decoding. We need this change to avoid the pytree + torch.compile issue #134731. Tested in gpt-fast [pr](https://github.com/pytorch-labs/gpt-fast/pull/196).

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

2024-08-27 23:34 UTC, Chillee requested changes

2024-08-27 23:34 UTC, Chillee commented on torch/nn/attention/flex_attention.py
> +    def get_mask(
Can't we just put this into `__getitem__`? That way, we can do `block_mask[:, :, index]`.

2024-08-27 23:35 UTC, Chillee reviewed
Also, even if we're testing in `gpt-fast`, still definitely need a test in core haha.

2024-08-28 18:12 UTC, drisspg commented on torch/nn/attention/flex_attention.py
> +        if self.full_kv_num_blocks is not None:
I don tthink we need this second assert as its already checked on construction

2024-09-04 17:39 UTC, Chillee approved these changes

2024-09-04 20:09 UTC, closed without merging