[dynamo] mark_static_nn_module
pytorch/pytorch pull request #134713
Opened 2024-08-28 19:34 UTC by anijain2305

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #134713
* #134653

2024-08-28 19:49 UTC, anijain2305 commented on torch/_dynamo/decorators.py
> +def mark_static_nn_module(mod_class):
More commentary.

Today's world - Consider user defined nn module int attributes automatic dynamic. Use `mark_static_nn_module` to make them static if you want.

Alternative work - Consider all int attributes of any user defined nn module class static. And then introduce an API - `torch._dynamo.mark_nn_module_attribute_dynamic`. The default being static is worrying if users have counter in their model which is updated in each forward invocation.

2024-08-28 19:49 UTC, anijain2305 commented on torch/_dynamo/decorators.py
> +def mark_static_nn_module(mod_class):
cc @ezyang @bdhirsh @zou3519

2024-08-29 01:21 UTC, jansel requested changes
I'd suggest just making the `mark_static()` API accept an nn.Module rather than adding a new method.

2024-08-29 16:02 UTC, jansel approved these changes

2024-08-30 03:38 UTC, anijain2305 commented
@pytorchbot merge

2024-08-30 03:42 UTC, anijain2305 commented
@pytorchbot merge

2024-08-30 07:01 UTC, closed without merging