fix torch.acos and torch.asin for torch.complex32 datatype on CPU
pytorch/pytorch pull request #134838
Opened 2024-08-30 06:46 UTC by jiayisunx

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #134838

2024-08-30 15:43 UTC, Skylion007 commented
Can we add tests / op tests to catch this regression in the future?

2024-09-04 08:15 UTC, jiayisunx commented
> Can we add tests / op tests to catch this regression in the future?

I removed the skip, now the UT covers torch.cfloat and torch.cdouble datatypes.

2024-09-04 08:18 UTC, mingfeima requested changes
wouldn't this be a severe downgrade for performance ?

2024-09-06 13:33 UTC, Skylion007 commented
@mingfeima true, but the code was incorrect before, and better to have correct code than faster code (I do agree it would be better to have vectorized correct code though)

2024-09-09 10:02 UTC, jiayisunx commented
> wouldn't this be a severe downgrade for performance ?

I tested the op benckmark, the performance did not drop, because the sqrt and log operations in the previous vectorized implementation of asin are still implemented in scalar.

2024-11-26 08:02 UTC, mingfeima approved these changes

2024-11-26 08:05 UTC, jiayisunx commented
hi @Skylion007 , could you please review this PR again? thanks!

2025-01-02 17:35 UTC, Skylion007 approved these changes

2025-01-06 06:10 UTC, jiayisunx commented
@pytorchbot merge

2025-01-06 06:17 UTC, closed without merging