update CMAKE_PREFIX_PATH setting command
pytorch/pytorch pull request #134934
Opened 2024-09-02 01:36 UTC by jingxu10

Current setting command of the `CMAKE_PREFIX_PATH` environment variable will overwrite values if it had already been set with values. Changing it to `+=` appends the conda env search path to its values to avoid library not found issues.
`export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}`

2024-09-13 18:39 UTC, malfet requested changes
This would not solve the problem, as `CMAKE_PREFIX_PATH` must be a semicolon separate list, this will just mangle last part, wouldn't it?
Running `+=` will ruing the path, wouldn't it, see example below:
```
$ export CMAKE_PREFIX_PATH=/usr/local/cmake
$ export CMAKE_PREFIX_PATH+=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
$ echo $CMAKE_PREFIX_PATH
/usr/local/cmake/home/nshulga/miniconda3
```
Also, I assume we want it in front of the existing list, don't we?
So if you want to replace this, you need to do something like
```shell
export CMAKE_PREFIX_PATH="${CONDA_PREFIX:-'$(dirname $(which conda))/../'};${CMAKE_PREFIX_PATH}"
```

2024-09-14 08:32 UTC, jingxu10 commented
Yeah, you are correct. Updated.

2024-09-26 02:12 UTC, EikanWang approved these changes

2024-10-15 20:55 UTC, jingxu10 commented
@pytorchbot merge

2024-10-16 21:29 UTC, jingxu10 commented
Hi @malfet , Can we merge this PR?

2024-10-16 21:46 UTC, malfet approved these changes
Sure, but please update PR description (as it still talks about using `+=`)
And can you please outline a test plan? 
And to be frank, I'm quite unsure why this CMAKE_PREFIX_PATH is needed in the first place, I never hard to use it as Anaconda should set it up correctly on its own, shouldn't it?

2024-10-16 21:58 UTC, jingxu10 commented
Hi @malfet , Updated the description.
What do you mean by the test plan? Do you mean something else than normal CI?
The `CMAKE_PREFIX_PATH` is needed for cmake to search library files in customized directories. Originally the `CMAKE_PREFIX_PATH` was required to set manually by users in the README file, thus, users need to handle how to append new values to it.
I just checked conda env activation script of miniforge, there's no such mechanism to set `CMAKE_PREFIX_PATH`.

2024-10-17 04:12 UTC, jingxu10 commented
@pytorchbot merge

2024-10-17 04:19 UTC, closed without merging