[Inductor][CPP] generalize the wgt tensor delete
pytorch/pytorch pull request #135101
Opened 2024-09-04 09:36 UTC by leslie-fang-intel

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #135101
* #135100

2024-09-11 01:46 UTC, leslie-fang-intel commented
TAS test (BF16 Dynamic shape/FP32 Static shape) shows no extra failure.

2024-10-09 02:31 UTC, jgong5 requested changes
minor comments on naming, others LGTM.

2024-10-09 02:31 UTC, jgong5 commented on torch/_inductor/codegen/cpp_gemm_template.py
>                      # The wgt tensor has been used by only 1 get_attr node
```suggestion
                    # The candidate tensor has been used by only 1 get_attr node
```

2024-10-09 02:31 UTC, jgong5 commented on torch/_inductor/codegen/cpp_gemm_template.py
> +                            comp_tensor = V.graph.constants[new_node.get_name()]
To name things consistently?
```suggestion
                            new_tensor = V.graph.constants[new_node.get_name()]
```

2024-10-09 02:31 UTC, jgong5 commented on torch/_inductor/codegen/cpp_gemm_template.py
> +            def share_storage(base_tensor: torch.Tensor, comp_tensor: torch.Tensor):
perhaps we can factor it out and shared by other code?

2024-10-09 05:05 UTC, leslie-fang-intel commented on torch/_inductor/codegen/cpp_gemm_template.py
>                      # The wgt tensor has been used by only 1 get_attr node
Thanks and changed.

2024-10-09 05:06 UTC, leslie-fang-intel commented on torch/_inductor/codegen/cpp_gemm_template.py
> +                            comp_tensor = V.graph.constants[new_node.get_name()]
Thanks and changed.

2024-10-10 02:47 UTC, jgong5 approved these changes

2024-10-10 02:49 UTC, leslie-fang-intel commented
Hi @jansel, could you kindly help to take a look of this PR?

2024-10-10 04:39 UTC, jansel approved these changes

2024-10-10 05:52 UTC, leslie-fang-intel commented
@pytorchbot merge

2024-10-10 06:01 UTC, closed without merging