[Inductor] Enable UniformValueConstantFolder for general get_attr node
pytorch/pytorch pull request #135205
Opened 2024-09-05 10:15 UTC by leslie-fang-intel

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #135205

2024-09-05 11:53 UTC, jgong5 requested changes
CI failing?

2024-09-05 11:58 UTC, leslie-fang-intel commented
> CI failing?

DLRM has been marked as `expected` failure previously, changed it to pass as it should be fixed by this PR. Seems we can take this model as the UT to cover this issue.

2024-09-05 12:56 UTC, desertfire approved these changes

2024-09-05 12:56 UTC, desertfire commented on torch/_inductor/codecache.py
> +            all_cuda = all(
I originally proposed to skip alignment for all_cuda case, but it seems unnecessarily complex. Ok to stick with it for this PR, but I will create a followup PR to skip all_cuda check, and verify if it looks fine for GPU.

2024-09-06 00:12 UTC, leslie-fang-intel commented
The same failure of `test/inductor/test_cudacodecache.py::TestCUDACodeCache::test_cuda_load` also exists on main: https://github.com/pytorch/pytorch/actions/runs/10722567567/job/29736827985

2024-09-06 02:51 UTC, jgong5 approved these changes

2024-09-06 03:02 UTC, leslie-fang-intel commented
@pytorchbot merge -i "un-related ci failure"

2024-09-06 03:05 UTC, leslie-fang-intel commented
@pytorchbot merge -f "un-related ci failure"

2024-09-06 03:06 UTC, closed without merging

2024-09-06 17:27 UTC, aorenste commented
@aorenste has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D62307347).