[WIP] Support dlpack for privateuse1
pytorch/pytorch pull request #135331
Opened 2024-09-06 07:08 UTC by hipudding

Fixes #129652

2024-09-06 09:29 UTC, shink approved these changes

2024-09-09 02:06 UTC, FFFrog commented on test/test_cpp_extensions_open_device_registration.py
> +        t1 = torch.from_dlpack(capsule)
```suggestion
        t1 = torch.from_dlpack(capsule)
        t1 = torch.from_dlpack(capsule)
        self.assertTrue(t1.device == t.device)
```

2024-09-10 15:08 UTC, FFFrog approved these changes

2024-10-16 07:38 UTC, hipudding commented
@albanD , Would you please review this PR? Thanks.

2024-11-04 06:12 UTC, hipudding commented
Hey @ezyang, Could you please review this PR? Thanks.

2024-11-04 19:00 UTC, ezyang requested changes
You can't just add a new value to the dlpack header, it's a standard. Fortunately, I think you just want to use kDLExtDev here

2024-11-09 02:50 UTC, ezyang approved these changes

2024-11-12 06:44 UTC, hipudding commented
@pytorchbot rebase -b main

2024-11-12 06:45 UTC, FFFrog commented
@pytorchbot rebase -b main

2024-11-13 10:11 UTC, hipudding commented
@pytorchbot merge

2024-11-13 13:13 UTC, closed without merging