[Intel GPU] qconv.pointwise with mixed dtype XPU support
pytorch/pytorch pull request #135465
Opened 2024-09-09 06:48 UTC by ZhiweiYan-96

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-12-30 08:40 UTC, liangan1 commented on aten/src/ATen/native/mkldnn/xpu/qconv_pt2e.cpp
> +        : (bfloat16_output ? c10::kBFloat16 : c10::kByte);
What is the logic of this part?  can you add more comments about it? how about fp16?

2025-01-07 06:35 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/qconv_pt2e.cpp
> +        : (bfloat16_output ? c10::kBFloat16 : c10::kByte);
The cases where output is not a quantized tensor could happen when an `int8_op + fp32_op` runs sequentially. Then we can let `int8_in ->int8_op =>int8_out ->deuqnt->fp32->fp32_op` directly mapping to `int8_in ->int8_op => fp32_out ->fp32_op`.

Additionally, with autocast, we could might change `fp32_op` to `bf16_op` and let `int8_op` directly outputs bf16 tensor.

2025-01-09 01:03 UTC, liangan1 approved these changes

2025-02-11 02:15 UTC, EikanWang requested changes
Pls. fix the linter error.

2025-02-11 03:17 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/qconv.cpp
> +#include <c10/core/ScalarType.h>
Place this under line 3.

2025-02-11 03:30 UTC, guangyey commented on test/inductor/test_mkldnn_pattern_matcher.py
> +            torch.ops.mkldnn._is_mkldnn_bf16_supported() or has_xpu
```suggestion
        has_xpu = any(
            isinstance(input, torch.Tensor) and input.device.type == "xpu"
            for input in inputs
        )
        device_type = 'xpu' if has_xpu else 'cpu'
        if torch.ops.mkldnn._is_mkldnn_bf16_supported() or torch.ops.mkldmm._is_mkldnn_fp16_supported():
            maybe_autocast = torch.amp.autocast(device_type, check_autocast)
```
`torch.cpu.amp.autocast` is deprecated now. Use `torch.amp.autocast` instead.

2025-02-11 03:35 UTC, guangyey approved these changes

2025-02-12 01:41 UTC, EikanWang approved these changes

2025-02-12 07:38 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/qconv.cpp
> +#include <c10/core/ScalarType.h>
modified

2025-02-12 07:38 UTC, ZhiweiYan-96 commented on test/inductor/test_mkldnn_pattern_matcher.py
> +            torch.ops.mkldnn._is_mkldnn_bf16_supported() or has_xpu
modified

2025-02-24 16:33 UTC, desertfire approved these changes

2025-02-24 19:10 UTC, jerryzh168 approved these changes

2025-02-24 19:27 UTC, closed without merging