[FlexAttention] Add broadcast support for kv batch dimension
pytorch/pytorch pull request #135505
Opened 2024-09-09 16:46 UTC by BoyuanFeng

This PR adds broadcast support for KV batch dimension.

## Details
Consider Q of shape `[Bq, Hq, Q_LEN, D]`, and K, V of shape `[Bkv, Hkv, KV_LEN, D]`. Prior to this diff, we require `Bq == Bkv`. However, for some use cases, we may have Bkv < Bq. For example, in paged attention, we provide K, V of shape `[1, Hkv, MAX_LEN, D]`, while still providing Q of shape `[Bq, Hq, Q_LEN, D]`. Here, MAX_LEN is the maximal number of tokens supported by paged attention.

This PR relax this requirement to be `Bq == Bkv or (Bq > 1 and Bkv == 0)`. This support covers both flex decoding, flex attention forward and backward.

## Benchmark
GPU: H100

We see negligible (1%~2%) performance change from this PR when `Bq == Bkv`.

```
python benchmarks/transformer/score_mod.py --calculate-bwd
```
### Perf before this PR

**FWD**

| Type    |   Speedup | score_mod     | mask_mod   | dtype          | shape(B,Hq,M,Hkv,N,D)        |
|---------|-----------|---------------|------------|----------------|------------------------------|
| Average |     0.743 |               |            |                |                              |
| Max     |     0.955 | head_bias     | None       | torch.bfloat16 | (2, 16, 1024, 2, 1024, 64)   |
| Min     |     0.548 | relative_bias | None       | torch.bfloat16 | (16, 16, 1024, 2, 1024, 128) |

**BWD**

| Type    |   Speedup | score_mod   | mask_mod   | dtype          | shape(B,Hq,M,Hkv,N,D)       |
|---------|-----------|-------------|------------|----------------|-----------------------------|
| Average |     0.834 |             |            |                |                             |
| Max     |     1.261 | head_bias   | None       | torch.bfloat16 | (8, 16, 512, 16, 512, 64)   |
| Min     |     0.456 | None        | causal     | torch.bfloat16 | (2, 16, 1024, 2, 1024, 128) |

<details>
<summary> Full performance sweep </summary>

| score_mod     | mask_mod   | dtype          | shape(B,Hq,M,Hkv,N,D)         |   fwd_eager_time |   fwd_compiled_time |   bwd_eager_time |   bwd_compiled_time |   fwd_speedup |   bwd_speedup |
|---------------|------------|----------------|-------------------------------|------------------|---------------------|------------------|---------------------|---------------|---------------|
| None          | None       | torch.bfloat16 | (2, 16, 512, 16, 512, 64)     |           15.264 |              17.184 |          107.040 |             140.800 |         0.888 |         0.760 |
| None          | causal     | torch.bfloat16 | (2, 16, 512, 16, 512, 64)     |           15.840 |              19.744 |          112.576 |             140.064 |         0.802 |         0.804 |
| relative_bias | None       | torch.bfloat16 | (2, 16, 512, 16, 512, 64)     |           15.232 |              17.344 |           87.744 |             142.496 |         0.878 |         0.616 |
| head_bias     | None       | torch.bfloat16 | (2, 16, 512, 16, 512, 64)     |           15.264 |              17.184 |          108.192 |             143.328 |         0.888 |         0.755 |
| None          | None       | torch.bfloat16 | (2, 16, 512, 16, 512, 128)    |           19.904 |              22.400 |          106.432 |             136.512 |         0.889 |         0.780 |
| None          | causal     | torch.bfloat16 | (2, 16, 512, 16, 512, 128)    |           19.424 |              26.752 |           91.712 |             106.688 |         0.726 |         0.860 |
| relative_bias | None       | torch.bfloat16 | (2, 16, 512, 16, 512, 128)    |           19.808 |              22.432 |           89.024 |             101.920 |         0.883 |         0.873 |
| head_bias     | None       | torch.bfloat16 | (2, 16, 512, 16, 512, 128)    |           19.840 |              22.272 |           88.896 |             102.592 |         0.891 |         0.867 |
| None          | None       | torch.bfloat16 | (2, 16, 1024, 16, 1024, 64)   |           30.240 |              32.416 |          116.768 |             112.256 |         0.933 |         1.040 |
| None          | causal     | torch.bfloat16 | (2, 16, 1024, 16, 1024, 64)   |           29.536 |              37.024 |          113.664 |             102.688 |         0.798 |         1.107 |
| relative_bias | None       | torch.bfloat16 | (2, 16, 1024, 16, 1024, 64)   |           30.656 |              32.800 |          116.992 |             127.008 |         0.935 |         0.921 |
| head_bias     | None       | torch.bfloat16 | (2, 16, 1024, 16, 1024, 64)   |           30.592 |              32.480 |          116.928 |             112.160 |         0.942 |         1.043 |
| None          | None       | torch.bfloat16 | (2, 16, 1024, 16, 1024, 128)  |           40.448 |              61.920 |          198.656 |             204.512 |         0.653 |         0.971 |
| None          | causal     | torch.bfloat16 | (2, 16, 1024, 16, 1024, 128)  |           37.760 |              62.528 |          189.536 |             170.624 |         0.604 |         1.111 |
| relative_bias | None       | torch.bfloat16 | (2, 16, 1024, 16, 1024, 128)  |           40.896 |              62.368 |          198.304 |             205.824 |         0.656 |         0.963 |
| head_bias     | None       | torch.bfloat16 | (2, 16, 1024, 16, 1024, 128)  |           40.448 |              61.952 |          198.432 |             203.648 |         0.653 |         0.974 |
| None          | None       | torch.bfloat16 | (2, 16, 4096, 16, 4096, 64)   |          318.528 |             355.904 |          947.232 |            1162.496 |         0.895 |         0.815 |
| None          | causal     | torch.bfloat16 | (2, 16, 4096, 16, 4096, 64)   |          199.776 |             252.128 |          677.792 |             813.184 |         0.792 |         0.834 |
| relative_bias | None       | torch.bfloat16 | (2, 16, 4096, 16, 4096, 64)   |          316.512 |             363.328 |          947.712 |            1361.984 |         0.871 |         0.696 |
| head_bias     | None       | torch.bfloat16 | (2, 16, 4096, 16, 4096, 64)   |          317.984 |             356.864 |          947.264 |            1165.024 |         0.891 |         0.813 |
| None          | None       | torch.bfloat16 | (2, 16, 4096, 16, 4096, 128)  |          446.656 |             734.656 |         1664.288 |            2172.960 |         0.608 |         0.766 |
| None          | causal     | torch.bfloat16 | (2, 16, 4096, 16, 4096, 128)  |          278.688 |             467.648 |         1182.624 |            1339.296 |         0.596 |         0.883 |
| relative_bias | None       | torch.bfloat16 | (2, 16, 4096, 16, 4096, 128)  |          447.872 |             744.096 |         1662.944 |            2196.544 |         0.602 |         0.757 |
| head_bias     | None       | torch.bfloat16 | (2, 16, 4096, 16, 4096, 128)  |          448.128 |             732.928 |         1663.072 |            2156.800 |         0.611 |         0.771 |
| None          | None       | torch.bfloat16 | (2, 16, 512, 2, 512, 64)      |           15.648 |              16.640 |          107.520 |             143.008 |         0.940 |         0.752 |
| None          | causal     | torch.bfloat16 | (2, 16, 512, 2, 512, 64)      |           15.776 |              18.240 |          129.056 |             141.920 |         0.865 |         0.909 |
| relative_bias | None       | torch.bfloat16 | (2, 16, 512, 2, 512, 64)      |           15.168 |              16.640 |          103.616 |             139.648 |         0.912 |         0.742 |
| head_bias     | None       | torch.bfloat16 | (2, 16, 512, 2, 512, 64)      |           15.616 |              16.640 |          128.608 |             164.448 |         0.938 |         0.782 |
| None          | None       | torch.bfloat16 | (2, 16, 512, 2, 512, 128)     |           19.776 |              21.952 |          125.344 |             170.304 |         0.901 |         0.736 |
| None          | causal     | torch.bfloat16 | (2, 16, 512, 2, 512, 128)     |           19.776 |            [...]

2024-09-09 23:32 UTC, Chillee requested changes

2024-09-09 23:32 UTC, Chillee commented on torch/_higher_order_ops/flex_attention.py
> +    # broadcast query & key along batch dim for paged attention
Remove the comments that these are for paged attention.

2024-09-09 23:32 UTC, Chillee commented on torch/_higher_order_ops/flex_attention.py
> +    # broadcast query & key along batch dim for paged attention
Also, we don't want to support interleaving, just broadcasting.

So, basically, we should only support it if `key == 1` and `query > 1`.

2024-09-09 23:32 UTC, Chillee commented on torch/_higher_order_ops/flex_attention.py
> +    # broadcast query & key along batch dim for paged attention
So, we should just call `expand`, not `repeat_interleave`.

2024-09-09 23:32 UTC, Chillee commented on torch/_higher_order_ops/flex_attention.py
> +    batch_group = query.size(0) // key.size(0)
same here

2024-09-09 23:32 UTC, Chillee commented on torch/_inductor/kernel/flex_attention.py
> +    assert Bq % Bkv == 0, "Bq must be divisible by Bkv"
Again, we shouldn't support interleaving, just broadcasting.

2024-09-09 23:32 UTC, Chillee commented on torch/_inductor/kernel/flex_attention.py
> +    off_zkv = off_zq // KV_SHARED_BATCH
It makes more sense to me to modulo this by the batch size of kv.

2024-09-09 23:32 UTC, Chillee commented on torch/_inductor/kernel/flex_attention.py
> +        broadcasted_grad_key = lowerings[aten.as_strided](
Same, I don't think this is needed since we're just broadcasting.

2024-09-10 00:51 UTC, Chillee approved these changes
Please make the mentioned changes.

2024-09-10 00:51 UTC, Chillee commented on torch/_inductor/kernel/flex_attention.py
> +        kv_shared_batch = Bq // Bkv
`kv_shared_batch` should always be `bq` size here. Add some asserts and make this more explicit.

2024-09-10 00:51 UTC, Chillee commented on torch/_higher_order_ops/flex_attention.py
> +        ), "Batch dimension must match. Otherwise, Bkv should be 1 and Bq should be larger than 1."
Raise a runtime error, not an assert, and say `Bq and Bkv must broadcast. Got Bq={Bq} and Bkv={Bkv}`.

2024-09-10 00:51 UTC, Chillee commented on torch/_higher_order_ops/flex_attention.py
> +    kv_shared_batch = Bq // Bkv
this should just always be `Bq` now.

2024-09-10 00:51 UTC, Chillee commented on torch/_higher_order_ops/flex_attention.py
> +        grad_key = torch.sum(grad_key, 0, keepdim=True) / kv_shared_batch
Are you sure there's a division here?

2024-09-10 00:51 UTC, Chillee commented on torch/_inductor/kernel/flex_attention.py
> +    off_zkv = off_zq % ZKV
Add a comment here explaining what's going on.

2024-09-10 09:30 UTC, closed without merging

2024-09-10 14:21 UTC, drisspg reviewed
Why wouldn't just calling kv.expand in the composite, flex attention wrapper achieve the same thing?

2024-09-10 19:52 UTC, Chillee commented
@BoyuanFeng Actually, i think this might be a fair point 🤔 Can you try that and see if it works? If Inductor realizes it we should just fix that.