[WIP][Inductor UT] Generalize Newly introduced inductor UTs for intel GPU (Part 1)
pytorch/pytorch pull request #136069
Opened 2024-09-14 02:19 UTC by hoshibara

[Inductor UT] Generalize Newly introduced inductor UTs for intel GPU
reuse `test/inductor/test_autoheuristic.py`
reuse `test/inductor/test_b2b_gemm.py`

2024-09-14 02:20 UTC, hoshibara commented
@pytorchbot label intel

2024-09-23 10:09 UTC, hoshibara commented
@pytorchbot rebase

2024-09-30 01:13 UTC, hoshibara commented
@pytorchbot rebase

2024-10-07 01:30 UTC, hoshibara commented
@pytorchbot rebase

2024-10-14 03:26 UTC, etaf requested changes

2024-10-14 05:54 UTC, hoshibara commented on test/inductor/test_efficient_conv_bn_eval.py
> +        class EfficientConvBNEvalCudaTests(TestCase):
Fixed

2024-10-14 05:57 UTC, etaf approved these changes

2024-10-15 14:45 UTC, hoshibara commented
@pytorchbot rebase

2024-10-15 15:09 UTC, EikanWang requested changes

2024-10-15 15:09 UTC, EikanWang commented on torch/_inductor/fx_passes/b2b_gemm.py
> +    ):
```suggestion
    fake_tensors = (
        A_node.meta["val"],
        B_node.meta["val"],
        C_node.meta["val"],
    )  # torch._subclasses.fake_tensor.FakeTensor
    
    A, B, C = fake_tensors
    
    # Lambda to check if all objects have a specific attribute set to True
    all_have = lambda objects, attr: all(getattr(obj, attr) for obj in objects)
    
    if not all_have(fake_tensors, 'is_cuda') and not all_have(fake_tensors, 'is_xpu'):
```

2024-10-16 01:45 UTC, hoshibara commented on test/inductor/test_b2b_gemm.py
> +@skipIfXpu(msg="Segmentation fault on CI machine")
https://github.com/pytorch/pytorch/issues/138045
File an issue

2024-10-16 02:22 UTC, hoshibara commented on test/inductor/test_custom_lowering.py
> +
`j2pd_xpu` and `j2pd_cuda` have been renamed and merge to `j2pd_gpu`.

2024-10-16 02:22 UTC, hoshibara commented on torch/_inductor/fx_passes/b2b_gemm.py
> +    ):
Merged

2024-10-16 02:23 UTC, hoshibara commented on test/inductor/test_custom_lowering.py
> +        )
Merged

2024-10-16 12:20 UTC, EikanWang commented on test/inductor/test_b2b_gemm.py
> +@skipIfXpu(msg="Segmentation fault on CI machine")
So, should we mark it as expectfailure rather than skip it?

2024-10-16 13:07 UTC, hoshibara commented on test/inductor/test_b2b_gemm.py
> +@skipIfXpu(msg="Segmentation fault on CI machine")
expectedFailureXPU cannot block this error message.
Maybe this `Fatal Python error: Segmentation fault` cannot be caught in python level.

2024-10-17 08:22 UTC, etaf commented
Please not enable b2b_gemm for now, see https://github.com/pytorch/pytorch/issues/138045

2024-10-18 00:59 UTC, jansel approved these changes

2024-10-18 05:39 UTC, EikanWang approved these changes

2024-10-18 05:39 UTC, hoshibara commented
@pytorchbot merge

2024-10-18 16:51 UTC, hoshibara commented
@pytorchbot merge

2024-10-18 16:58 UTC, closed without merging