[NCCL] Don't override `waitUntilInitialized`'s setting of `comm->initialized_`
pytorch/pytorch pull request #136155
Opened 2024-09-16 18:14 UTC by eqy

#133630 sets `initialized_` to `true` which causes previous wait codepaths to skip necessary waits, see also #https://github.com/pytorch/pytorch/issues/136151

CC @shuqiangzhang @wconstab

2024-09-16 21:09 UTC, fduwjj approved these changes

2024-09-16 21:47 UTC, kwen2501 approved these changes
Makes sense. Thanks for the fix!

2024-09-16 21:54 UTC, kwen2501 commented
I also wonder if this fix is complete. 

For the case of `using_nonblocking`, we have to set `initialized_` to true somewhere, right?

2024-09-16 21:54 UTC, c-p-i-o approved these changes

2024-09-16 21:56 UTC, kwen2501 requested changes
I also wonder if this fix is complete.
For the case of using_nonblocking, we have to set initialized_ to true somewhere, right?
@shuqiangzhang thought?

2024-09-16 22:32 UTC, eqy commented
@kwen2501 it is set in `waitUntilInitialized` itself https://github.com/pytorch/pytorch/blob/f639687eaa2a9a58c8ae1825f3057c75329376a1/torch/csrc/distributed/c10d/NCCLUtils.cpp#L54

2024-09-16 23:08 UTC, kwen2501 approved these changes
I see. Thanks for the pointer

2024-09-17 15:53 UTC, kwen2501 commented
@pytorchbot merge

2024-09-17 17:49 UTC, shuqiangzhang approved these changes
LGTM, thanks for the fix

2024-09-17 18:50 UTC, closed without merging

2024-09-17 23:36 UTC, nWEIdia commented
Oops, my internal testing does not show this would completely avoid/fix the SIGSEGV. 
Suggest reverting both this and the original https://github.com/pytorch/pytorch/pull/133630

2024-09-18 19:07 UTC, nWEIdia commented
To double check the testing, I switching to using nightly image: 
docker pull ghcr.io/pytorch/pytorch-nightly:2.6.0.**dev20240918**-cuda12.4-cudnn9-devel 
apt update && apt install -y git 
git clone https://github.com/pytorch/pytorch.git
git checkout e000cf0ad980e5d140dc895a646174e9b945cf26  (to avoid some rocm import error) 
pytest -v distributed/test_c10d_nccl.py -k test_non_blocking_init 

It errors out but seems a slightly different issue: 

`[rank1]:E0918 18:46:44.190000 698 site-packages/torch/testing/_internal/common_distributed.py:671]   File "/workspace/pytorch/test/distributed/test_c10d_nccl.py", line 778, in test_non_blocking_init                                                                                                                                                                                                    [rank1]:E0918 18:46:44.190000 698 site-packages/torch/testing/_internal/common_distributed.py:671]     new_pg.broadcast(broadcast_tensor, 0).wait()                                                  [rank1]:E0918 18:46:44.190000 698 site-packages/torch/testing/_internal/common_distributed.py:671]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                         
[rank1]:E0918 18:46:44.190000 698 site-packages/torch/testing/_internal/common_distributed.py:671] torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2777, invalid argument (run with NCCL_DEBUG=WARN for details), NCCL version 2.21.5                                                                                                              
[rank1]:E0918 18:46:44.190000 698 site-packages/torch/testing/_internal/common_distributed.py:671] ncclInvalidArgument: Invalid value for an argument.                                               [rank1]:E0918 18:46:44.190000 698 site-packages/torch/testing/_internal/common_distributed.py:671] Last error:                                                                                       [rank1]:E0918 18:46:44.190000 698 site-packages/torch/testing/_internal/common_distributed.py:671] Broadcast : comm argument is NULL                                                                 [rank1]:E0918 18:46:44.190000 698 site-packages/torch/testing/_internal/common_distributed.py:671]                                                                                                   
[rank1]:E0918 18:46:44.190000 698 site-packages/torch/testing/_internal/common_distributed.py:671] To execute this test, run the following from the base repo dir:                                   [rank1]:E0918 18:46:44.190000 698 site-packages/torch/testing/_internal/common_distributed.py:671]     python test/distributed/test_c10d_nccl.py ProcessGroupNCCLGroupTest.test_non_blocking_init    [rank1]:E0918 18:46:44.190000 698 site-packages/torch/testing/_internal/common_distributed.py:671]                                                                                                   
[rank1]:E0918 18:46:44.190000 698 site-packages/torch/testing/_internal/common_distributed.py:671] This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0                        [rank1]:E0918 18:46:44.190000 698 site-packages/torch/testing/_internal/common_distributed.py:671]  exiting process 1 with exit code: 10                                                             [rank1]:[E918 18:46:44.920775929 ProcessGroupNCCL.cpp:542] [Rank 1] Collective WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=100, NumelOut=100, Timeout(ms)=600000) raised the following async exception: NCCL error: invalid argument (run with NCCL_DEBUG=WARN for details), NCCL version 2.21.5                                                                                                         
ncclInvalidArgument: Invalid value for an argument.                                                                                                                                                  
Last error:                                                                                                                                                                                          
Broadcast : comm argument is NULL                                                                                                                                                                    Exception raised from checkForNCCLErrorsInternal at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2027 (most recent call first):    `

For some reason I do not observe this in internal docker image. So this could be docker image difference.

2024-10-02 19:34 UTC, kit1980 commented
@pytorchbot cherry-pick -c regression --onto release/2.5