Add oneDNN BRGEMM config for Half cpp gemm template
pytorch/pytorch pull request #136255
Opened 2024-09-18 07:33 UTC by CaoE

2024-09-23 12:28 UTC, jgong5 requested changes

2024-09-24 07:14 UTC, CaoE commented on torch/_inductor/codegen/cpp_micro_gemm.py
> +        return LayoutType.VNNI2
Yes. brgemm also supports non-AMX compute. Will enable it on non-AMX cases.

2024-10-21 13:03 UTC, CaoE commented on torch/csrc/cpu/Module.cpp
> +  cpu.def("_is_amx_fp16_supported", at::cpu::is_amx_fp16_supported);
Add `_is_amx_tile_supported` for `_is_amx_fp16_supported`.

2024-10-21 13:03 UTC, CaoE commented on torch/_inductor/codegen/cpp_micro_gemm.py
> +        return LayoutType.VNNI2
Added non-AMX compute support.

2024-10-23 05:30 UTC, jgong5 requested changes

2024-10-24 06:26 UTC, CaoE commented on test/inductor/test_cpu_select_algorithm.py
> +            torch.cpu._is_amx_fp16_supported() or torch.cpu._is_avx512_fp16_supported()
Checking avx512_fp16 is enough. Modified. Thanks.

2024-10-29 07:22 UTC, jgong5 commented on test/inductor/test_cpu_select_algorithm.py
> +            torch.cpu._is_amx_fp16_supported() or torch.cpu._is_avx512_fp16_supported()
No, my question is why we care about avx512_fp16 here. We only use AMX FP16, right?

2024-10-29 07:22 UTC, jgong5 reviewed
Please explain why we need avx512 fp16 here.

2024-10-29 08:53 UTC, CaoE commented on test/inductor/test_cpu_select_algorithm.py
> +            torch.cpu._is_amx_fp16_supported() or torch.cpu._is_avx512_fp16_supported()
Removed non-amx fp16 support. Only check AMX FP16 here.

2024-10-29 08:53 UTC, CaoE commented
> Please explain why we need avx512 fp16 here.

Removed non-amx fp16 support.

2024-10-30 03:11 UTC, jgong5 approved these changes

2024-10-31 15:31 UTC, jansel approved these changes

2024-11-03 10:54 UTC, CaoE commented
@pytorchbot merge

2024-11-03 12:08 UTC, CaoE commented
@pytorchbot rebase

2024-11-03 12:08 UTC, CaoE commented
@pytorchbot merge

2024-11-05 05:25 UTC, CaoE commented
@pytorchbot merge

2024-11-05 05:33 UTC, closed without merging