[not for land][export] Implement cpp serializer.
pytorch/pytorch pull request #136398
Opened 2024-09-21 23:05 UTC by zhxchen17

Differential Revision: D63206258

2024-11-06 18:18 UTC, seemethere requested changes
You should add the generated file to the list of generated files here:

https://github.com/pytorch/pytorch/blob/main/.gitattributes

Then the check should pass since it ignores generated files.

2024-11-07 18:45 UTC, zhxchen17 commented on torch/_export/serde/serialize.py
> +        elif type(arg) is bool:
I think it's for keeping consistency with isinstance(arg, int). no difference I know of, but instance(arg, bool) might have surprises we don't know, like int.

2024-11-07 18:45 UTC, zhxchen17 commented on torch/_C/_aoti.pyi
> +class CppExportedProgram: ...
oki

2024-11-13 01:38 UTC, angelayi approved these changes

2024-11-14 15:03 UTC, zhxchen17 commented
@pytorchbot merge -i

2024-11-14 16:35 UTC, closed without merging