[CI]Move AOT inductor AMP cases to linux.16xlarge.spr runner
pytorch/pytorch pull request #136313
Opened 2024-09-19 10:12 UTC by zxd1997066

Fixes #ISSUE_NUMBER

2024-09-20 00:18 UTC, huydhn commented
@zxd1997066 Could you help provide some of the context of why this is needed? A CI PR without any description is hard to review

2024-09-20 02:55 UTC, zxd1997066 commented
> @zxd1997066 Could you help provide some of the context of why this is needed? A CI PR without any description is hard to review

Thanks for the comment, added the description.

2024-11-05 07:53 UTC, chuanqi129 commented
@zxd1997066 please resolve the code conflict firstly

2024-11-05 08:51 UTC, zxd1997066 commented
@pytorchbot rebase -b main

2024-11-05 14:13 UTC, desertfire commented
@huydhn or @ZainRizvi probably have already talked to you guys, but the context is we are trying to cut the Inductor CI expense. This PR will further increase the cost. Fine if this is short-term and you will eventually move them to a different CI tier or CI infra. Just want to bring that for awareness.

2024-11-06 05:47 UTC, jgong5 requested changes
@zxd1997066 Can you share the motivation of this change?

2024-11-06 06:18 UTC, zxd1997066 commented
> @zxd1997066 Can you share the motivation of this change?

yes, for CPU, only SPR(linux.16xlarge.spr) has native support for AMP BF16, cascade Lake (linux.12xlarge) does not have.

2024-11-07 02:28 UTC, jgong5 approved these changes

2024-11-08 15:56 UTC, chuanqi129 commented on .github/workflows/inductor-periodic.yml
> +      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
This is build job, we need add test job in here also

2024-11-08 15:56 UTC, chuanqi129 commented on .github/workflows/inductor.yml
> +          { config: "cpu_inductor_timm", shard: 1, num_shards: 2, runner: "linux.8xlarge.amx" },
Let's check whether we can move some fp32 test into inductor-periodic also

2024-11-08 16:06 UTC, huydhn commented
Looking at the change right now, `linux.8xlarge.amx` is cheaper than both `linux.12xlarge` and `linux.16xlarge.spr`, so cost-wise, this is better I think

2024-11-08 17:15 UTC, zxiiro approved these changes
+1 to moving to cheaper systems!

2024-11-08 17:23 UTC, zxiiro commented on .github/workflows/inductor-periodic.yml
> +    secrets:
Fix the linter issue.

```suggestion
    secrets:
```

2024-11-11 17:53 UTC, chuanqi129 commented
> Looking at the change right now, `linux.8xlarge.amx` is cheaper than both `linux.12xlarge` and `linux.16xlarge.spr`, so cost-wise, this is better I think

Hi @huydhn , can we create a new label `ciflow/inductor-periodic`? So that we can test the workflow change in this PR in advance before the landing

2024-11-11 17:58 UTC, zxiiro commented
> > Looking at the change right now, `linux.8xlarge.amx` is cheaper than both `linux.12xlarge` and `linux.16xlarge.spr`, so cost-wise, this is better I think
> 
> Hi @huydhn , can we create a new label `ciflow/inductor-periodic`? So that we can test the workflow change in this PR in advance before the landing

Looks like I was able to add the label. I see some jobs starting now so I hope it works as expected.

2024-11-12 00:04 UTC, huydhn commented
Anyone with write access to the repo can able to create the label.  Thank @zxiiro for picking it up!

2024-11-12 08:24 UTC, chuanqi129 approved these changes

2024-11-12 08:27 UTC, chuanqi129 commented
Thanks @huydhn and @zxiiro. The PR and test results LGTM. But there is an unrelated failure. @zxiiro please help to merge it if you don't have further comments

2024-11-12 13:23 UTC, zxiiro commented
Looks like we need some additional approvals first.

2024-11-12 13:57 UTC, desertfire approved these changes
Stamping. I think .github/workflows/inductor.yml can be further trimmed.

2024-11-12 14:19 UTC, zxiiro commented
@pytorchbot merge -i

2024-11-12 16:15 UTC, closed without merging