Enable -Werror on s390x
pytorch/pytorch pull request #136527
Opened 2024-09-24 13:10 UTC by AlekseiNikiforovIBM

Enable -Werror on s390x

2024-09-24 13:36 UTC, AlekseiNikiforovIBM commented
@pytorchbot label "topic: not user facing"

2024-09-25 10:59 UTC, AlekseiNikiforovIBM commented
Fixes for different files are split into separate commits. Every commit has fixed errors listed in commit message.

2024-10-01 12:57 UTC, AlekseiNikiforovIBM commented
@pytorchbot rebase

2024-10-11 17:30 UTC, malfet approved these changes

2024-10-11 17:33 UTC, malfet requested changes
Please restrict warning suppressions in CMakeLists to a specific lists

2024-10-11 17:33 UTC, malfet commented on CMakeLists.txt
> +  append_cxx_flag_if_supported("-Wno-error=redundant-move" CMAKE_CXX_FLAGS)
Let's restrict those to a specific specific GCC versions and if the are arechitecture specific let's restrict them to s360

2024-10-18 14:05 UTC, AlekseiNikiforovIBM commented on torch/csrc/jit/serialization/export_module.cpp
> +      const TypePtr key_type = t->containedTypes()[0];
I've removed this commit, replacing it with warning suppression. Is this commend still relevant?

2024-10-18 14:05 UTC, AlekseiNikiforovIBM commented
@malfet @huydhn , could you please take a look at this PR again?

2024-10-18 14:29 UTC, malfet commented
@AlekseiNikiforovIBM this PR reports 83 failures? Are you sure all of them are unrelated? Please give a reasonable explanaiton why or better rebase to `viable/strict`

2024-10-18 14:29 UTC, malfet commented
@pytorchbot rebase

2024-10-18 14:31 UTC, malfet approved these changes
4 changes files LGTM though

2024-10-18 14:31 UTC, malfet commented
@pytorchbot merge

2024-10-18 16:05 UTC, malfet commented
@pytorchbot merge -i

2024-10-19 01:11 UTC, huydhn commented
@pytorchbot merge

2024-10-19 01:18 UTC, closed without merging