[WIP][Inductor] auto-chunker
pytorch/pytorch pull request #136702
Opened 2024-09-26 00:55 UTC by shunting314

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136702

2025-04-10 21:02 UTC, shunting314 commented on torch/_inductor/fx_passes/auto_chunker/__init__.py
> +    out_gm = ChunkingApplier(gm, config.AutoChunker.num_chunk or 8).apply()
Right now this PR defaults to use 8 chunks.

I'll do in a follow up PR to make it better by
- either use some heuristics to create as many chunks as possible until the M dimension of matmul is smaller than some threshold
- or build some autotuning functionality

2025-04-15 19:42 UTC, jansel requested changes
Looks like tests are failing, re-request review once you want me to look in more detail.

2025-06-10 02:55 UTC, etaf requested changes, later dismissed

2025-06-10 02:55 UTC, etaf commented on test/inductor/test_auto_chunker.py
> +    if HAS_GPU:
Hi, since the test cases are all hard coded `cuda`, suggest to not use `HAS_GPU` which allows other GPU run this test case and then failed with no `cuda` support. 
```suggestion
    if HAS_CUDA:
```

2025-06-10 02:56 UTC, etaf commented on test/inductor/test_auto_chunker.py
> +from torch.testing._internal.inductor_utils import GPU_TYPE, HAS_GPU
```suggestion
from torch.testing._internal.inductor_utils import GPU_TYPE, HAS_CUDA
```

2025-06-14 03:59 UTC, jansel requested changes
Have we done a full CI run and benchmark run with this enabled?

2025-06-14 03:59 UTC, jansel commented on torch/_inductor/config.py
> +class AutoChunker:
match naming convention elsewhere in config file

2025-06-14 03:59 UTC, jansel commented on torch/_inductor/fx_passes/auto_chunker/__init__.py
> +    log.debug("Joint graph before chunking:\n%s", gm.print_readable(False))
Avoid calling print_readable if debug mode not enabled.

2025-06-14 03:59 UTC, jansel commented on torch/_inductor/fx_passes/auto_chunker/applier.py
> +# mypy: disable-error-code=union-attr
Type this file

2025-06-14 03:59 UTC, jansel commented on torch/_inductor/fx_passes/auto_chunker/core.py
> +# mypy: allow-untyped-defs
Type this file

2025-06-14 03:59 UTC, jansel commented on torch/_inductor/fx_passes/auto_chunker/core.py
> +    for node in graph.nodes:
Do we need to iterate over the graph some many times?  Any place we could use `graph.find_nodes()` instead?

2025-06-14 03:59 UTC, jansel commented on torch/_inductor/fx_passes/auto_chunker/propagate_scale_by.py
> +# mypy: allow-untyped-defs
Type this file

2025-06-14 03:59 UTC, jansel commented on torch/_inductor/fx_passes/auto_chunker/propagator.py
> +# mypy: allow-untyped-defs
Same

2025-06-16 23:14 UTC, shunting314 commented
> Have we done a full CI run and benchmark run with this enabled?

Not yet. I'll kick off one. I may need tweak the batch size for accuracy test a bit. Right now it's very small and auto-chunker will be skipped in that case. I'll try to override the batch size so we can test for accuracy with auto-chunker taking effect

2025-11-14 02:07 UTC, v0i0 commented
@shunting314 @jansel should we try to get this in? what would it take? i can take a pass reviewing it

2025-11-14 23:41 UTC, shunting314 commented
@v0i0 thanks for offering review. That would be great!

I just need find bandwidth to resolve comments, do more tests and get this in.

2025-11-16 06:27 UTC, jansel commented
Yeah, I think we should get this landed.  Re-request review when you want me to take another look.

2025-12-12 15:41 UTC, v0i0 reviewed
this is amazing! what does the generated code look like? why is this a bunch of invoke_subgraph rather than vmap w/ chunk_size or hop.scan?

2025-12-12 15:41 UTC, v0i0 commented on torch/_inductor/fx_passes/auto_chunker/__init__.py
> +    log.debug("Joint graph before chunking:\n%s", gm.print_readable(False))
maybe just wrap with GraphTransformObserver instead?

2025-12-12 15:41 UTC, v0i0 commented on torch/_inductor/fx_passes/auto_chunker/propagator.py
> +def propagate_general_copy_metadata(out_node, ignore_broadcast=False):
while i admittedly have no idea how to do it, this seems like a special case of propagating along vmap/batching rules. if they exist somewhere, you could probably cut this down a lot.

2025-12-13 00:03 UTC, shunting314 commented
> what does the generated code look like? 

For linear+cross entropy , the fx graph before chunking is : https://gist.github.com/shunting314/231e4e5c15923f3d16e069768628daaf , the fx graph after chunking is: https://gist.github.com/shunting314/2583db2ea0ea36bdad4ed1a5732bbc49 . 
There is a subgraph being extracted out and invoked 4 times because I set number-of-chunk to 4 (can be autotuned/better decided later).

2025-12-13 00:17 UTC, shunting314 commented
> why is this a bunch of invoke_subgraph rather than vmap w/ chunk_size or hop.scan?

Thanks for mentioning the similarity with vmap. yea, maybe some functionality can be borrowed/shared. I'm not sure. But for auto-chunker, the different chunks have to be handled serially so we reuse intermediate buffers.

hop.scan was not available when I started prototyping auto-chunker.

2025-12-13 00:48 UTC, v0i0 commented
> > what does the generated code look like?
> 
> For linear+cross entropy , the fx graph before chunking is : https://gist.github.com/shunting314/231e4e5c15923f3d16e069768628daaf , the fx graph after chunking is: https://gist.github.com/shunting314/2583db2ea0ea36bdad4ed1a5732bbc49 . There is a subgraph being extracted out and invoked 4 times because I set number-of-chunk to 4 (can be autotuned/better decided later).

Amazing! Would it be possible to run this against a bunch of training code (e.g. torchtitan w/ num_gpus=1 & torchbench) to see if anything is missing / get some more memory savings data?

2025-12-13 00:59 UTC, shunting314 commented
> Amazing! Would it be possible to run this against a bunch of training code (e.g. torchtitan w/ num_gpus=1 & torchbench) to see if anything is missing / get some more memory savings data?

Sure. That's actually the tests I plan to do and share results. torchtitan/torchtune are both good choices. I'll share more results 

Our dashboard (HF/torchbench/TIMM) may be stretchy to test AutoChunker since for the small workload, AutoChunker most likely will be skipped.

2025-12-13 01:13 UTC, shunting314 commented on torch/_inductor/fx_passes/auto_chunker/core.py
> +    for node in graph.nodes:
This loop is absolutely unneeded. Removed.

2025-12-19 07:11 UTC, shunting314 commented
CI is neutral with AutoChunker enabled (https://github.com/pytorch/pytorch/pull/170730).

Dashboard [run](https://hud.pytorch.org/benchmark/compilers?dashboard=torchinductor&startTime=Thu%2C%2011%20Dec%202025%2019%3A59%3A06%20GMT&stopTime=Thu%2C%2018%20Dec%202025%2019%3A59%3A06%20GMT&granularity=hour&mode=training&dtype=amp&deviceName=cuda%20(h100)&lBranch=gh/shunting314/275/head&lCommit=615e188e7acfe24b9a1d75e2bfc9d21ca1947d05&rBranch=main&rCommit=9eb2fc0e3fdc6c39907ee87558070684dab48b0f)
- 2 models in TB and 1 model in TIMM fail the accuracy test. I can repro. But these errors already exists in base revision.
- the perf drop on TIMM is not due to AutoChunker. It because vit_base_patch16_siglip_256 has 0.0025x speedup and autochunker is skipped for this model.
- I checked specifically memory saving for HF benchmark suite. There is only 1% improvement shown on the dashboard because in general batch sizes are too small. AutoChunker takes effect for only 6 of the models. And even if AutoChunker takes effect for a model, because of small batch size, either the saving will be smaller or the perf loss will be larger.

I tried on BertForMaskedLM with larger batch-size (256 rather than default 16) and 64 chunks and got 15% memory saving with 2% perf loss.

More tests will be done on TorchTitan/TorchTune

2025-12-21 18:34 UTC, jansel reviewed
Is the `doctr_det_predictor` failure real?

2025-12-21 18:34 UTC, jansel commented on test/inductor/test_flex_attention.py
> +            return full_default_1
What is cuasing this change?

2025-12-21 18:34 UTC, jansel commented on torch/_inductor/compile_fx.py
> +) -> GraphModule:
Why change the return value?  It looks like we are still mutating `gm` not creating a new GraphModule?

2025-12-21 18:34 UTC, jansel commented on torch/_inductor/fx_passes/auto_chunker/__init__.py
> +        return gm
Should this be an error?

2025-12-21 18:34 UTC, jansel commented on torch/_inductor/fx_passes/auto_chunker/propagate_scale_by.py
> +propagate_rules = {}  # type: ignore[var-annotated]
Annotate types?

2025-12-21 18:34 UTC, jansel commented on torch/_inductor/fx_passes/auto_chunker/propagator.py
> +"""
IMO we should get the types working properly.

2025-12-22 19:42 UTC, shunting314 commented
> Is the doctr_det_predictor failure real?

It's unrelated to this PR. Eager fails to run due to network error .

2025-12-22 19:56 UTC, shunting314 commented on torch/_inductor/compile_fx.py
> +) -> GraphModule:
The ChunkingApplier would create a new GraphModule: 
```
        newgm = torch.fx._lazy_graph_module._make_graph_module(
            self.gm,
            self.parent_graph,
        )
```

I initially decided to create a new GraphModule since it's easier to fallback.

2025-12-22 19:57 UTC, shunting314 commented on torch/_inductor/fx_passes/auto_chunker/__init__.py
> +        return gm
yea. I'll add a error message and fallback to not chunking

2025-12-22 20:17 UTC, shunting314 commented on test/inductor/test_flex_attention.py
> +            return full_default_1
It turns out to be a bug:

```
        old_subgraph_names = _get_subgraph_names(gm, skip_invoke_subgraph)
        for subgraph_name in old_subgraph_names:
            _run_on_sub_graph_module(subgraph_name)

        out_gm = joint_graph_passes(gm)

        # Some joint graph passes may create new sub graph module. Run one round
        # for the newly created graph modules.
        # We should not skip graphs for invoke_subgraph HOPs for newly
        # generated subgraphs.
        for subgraph_name in _get_subgraph_names(out_gm, skip_invoke_subgraph=False):
            if subgraph_name not in old_subgraph_names:
                _run_on_sub_graph_module(subgraph_name)
```

The first line returns a Python generator. It's iterated once in the first for loop. When it's used in the second for-loop, it's already empty. This cause joint-graph passes being applied to sub-graph a second time and triggers the codegen change.

Fixed it in the next commit.

2025-12-22 21:29 UTC, shunting314 commented on torch/_inductor/fx_passes/auto_chunker/propagator.py
> +"""
Looks like pyre does not 'see' lines like 'assert isinstance(bias_node, Node)' in the enclosing function (mypy can do that).

I'll workaround this by moving the assertion to nested function.

2025-12-23 00:28 UTC, jansel approved these changes

2025-12-23 19:25 UTC, shunting314 commented
@pytorchbot merge -i

A comment about the PR size. The PR has more than 2K lines and violate a lint. TBH, all the code here are necessary to make  a workable version of AutoChunker. If people have strong option for splitting it, I can move the test file to a separate PR, or land the PR module by module but test in the last PR.

2025-12-23 19:26 UTC, shunting314 commented
@pytorchbot merge -i

2025-12-24 05:21 UTC, shunting314 commented
@pytorchbot merge -i

2025-12-24 07:47 UTC, huydhn commented
@pytorchbot revert -m 'Sorry for reverting your change but this seems to break vLLM CI' -c nosignal

[GH job link](https://github.com/pytorch/pytorch/actions/runs/20479091241/job/58851064679) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/3cd6766108c76fac50de3deca135122ecc6837e1)

2025-12-27 01:54 UTC, shunting314 commented
@pytorchbot merge -i

2025-12-27 02:55 UTC, closed without merging