[2.5.0 Cherrypick] [CI] Companion PR to #134022 (#136818)
pytorch/pytorch pull request #136898
Opened 2024-09-27 21:45 UTC by nWEIdia

Cherry-picking #136818 

Note:[ cusparselt 0.6.0](https://docs.nvidia.com/cuda/cusparselt/release_notes.html#cusparselt-v0-6-0)+ supports SM90 (Hopper). Thanks @xwang233 for catching this bug while testing upstream binaries!

Fixes the issues like:

  ```
  A_compressed = torch._cslt_compress(A)
RuntimeError: CUDA error: architecture mismatch when calling `cusparseLtInit(&handle)`
```

@kit1980 Could we get this cherry-picked to 2.5.0 please?
Pull Request resolved: https://github.com/pytorch/pytorch/pull/136818
Approved by: https://github.com/eqy, https://github.com/jcaip, https://github.com/malfet

2024-09-27 22:10 UTC, eqy approved these changes

2024-09-27 23:51 UTC, jcaip approved these changes
lgtm

2024-09-28 00:17 UTC, malfet requested changes
I don't think we should do dependency updates after the branch cut

2024-09-28 00:21 UTC, nWEIdia commented
> I don't think we should do dependency updates after the branch cut

It is bug fix for a "partial" dependency update. To clarify: x86 cuda users would get cusparselt 0.6.2. Without this PR, arm cuda users would be getting cusparselt 0.5. 

Are we comfortable with this discrepancy?

2024-09-28 00:27 UTC, malfet commented
> Are we comfortable with this discrepancy?


Sorry, I have not realized, that it only affects package version for aarch64... Perhaps this is fine to cherry pick, though I'm also fine with sticking to 0.5.2. Can you please explain, why this is critical to migrate from 0.5.2 to 0.6.2 on that platform?

2024-09-28 00:31 UTC, nWEIdia commented
> > Are we comfortable with this discrepancy?
> 
> Sorry, I have not realized, that it only affects package version for aarch64... Perhaps this is fine to cherry pick, though I'm also fine with sticking to 0.5.2. Can you please explain, why this is critical to migrate from 0.5.2 to 0.6.2 on that platform?

0.5.2 is missing Hopper support.  Basic compression on Hopper with cusparselt 0.5.2 would simply error out. cusparselt enabled sm90 support since 0.6.0. Since @jcaip bumped cusparselt to 0.6 and only a small set of people are aware of a mostly duplicated install_cuda_aarch64, this is just making the update as complete as it can be. 

Of course, we can argue how many users have H100 and how many of them use cusparselt. So, up to you :)

2024-09-30 18:42 UTC, nWEIdia commented
> > > Are we comfortable with this discrepancy?
> > 
> > 
> > Sorry, I have not realized, that it only affects package version for aarch64... Perhaps this is fine to cherry pick, though I'm also fine with sticking to 0.5.2. Can you please explain, why this is critical to migrate from 0.5.2 to 0.6.2 on that platform?
> 
> 0.5.2 is missing Hopper support. Basic compression on Hopper with cusparselt 0.5.2 would simply error out. cusparselt enabled sm90 support since 0.6.0. Since @jcaip bumped cusparselt to 0.6 and only a small set of people are aware of a mostly duplicated install_cuda_aarch64, this is just making the update as complete as it can be.
> 
> Of course, we can argue how many users have H100 and how many of them use cusparselt. So, up to you :)

Actually, after discussing with @ptrblck , I realize it is best to not cherrypicking this one into v2.5.0, since this issue (of not using cusparseLt 0.6.2) is present with v2.4.1 and it is not a regression.  Not cherrypicking this would also give us time testing cusparselt 0.6.2 on Grace Hopper. :)

2024-09-30 18:42 UTC, closed without merging