Improvements for associative_scan - Autograd
pytorch/pytorch pull request #136966
Opened 2024-09-29 22:42 UTC by bohnstingl

This is part of a series of PRs to improve the functionality of the associatve_scan functionality. This specific PR implements the Autograd for associative_scan. This PR has been derived from https://github.com/pytorch/pytorch/pull/129307.

@ydwu4

2024-10-23 17:00 UTC, ydwu4 commented on test/functorch/test_control_flow.py
> +        torch.concatenate([e[leave_ind] for e in op(result_flat)], dim)
Why is it a concatenate? if we associative_scan over (4, 2, 3) over dim=0, each subgraph should work on a slice of (2, 3), and the end results should be of shape (4, 2, 3). Anything wrong with this interface?  After the change, does subgraph takes (1, 2, 3) or result becomes (8, 3).

2024-10-23 17:23 UTC, ydwu4 requested changes

2024-10-23 17:23 UTC, ydwu4 commented on torch/_dynamo/variables/higher_order_ops.py
> +        def arg_extractor(combine_fn, xs):
i feel we should split this diff into 2, first is the the dim change, then the autograd.

2024-10-23 17:23 UTC, ydwu4 commented on torch/_higher_order_ops/associative_scan.py
> +    leaves = [shift_source_dim_to_target_dim(elem, int(dim), 0) for elem in leaves]
we might replace `shift_source_dim_to_target_dim` with torch.movedim(elem, int(dim), 0).

2024-10-23 17:23 UTC, ydwu4 commented on torch/_higher_order_ops/associative_scan.py
> +        shift_source_dim_to_target_dim(elem, 0, orig_scan_dim) for elem in result_flat
shift_source_dim_to_target_dim -> movedim

2024-10-23 17:23 UTC, ydwu4 commented on torch/_higher_order_ops/associative_scan.py
> +# TODO: Provide inductor support for generic scan
What's missing in inductor for generic scan. Is it the test failure we talked about?

2024-10-23 17:23 UTC, ydwu4 commented on torch/_higher_order_ops/associative_scan.py
> +    def backward(ctx, *flat_grads_unmasked):
I trust you on this. 

Didn't look into the details of the backward implementation.  Some general thoughts for better testing this: can we use scan to implement a baseline version first and add much more tests to verify the correctness (e.g. nesting cond, scan and associative scan with autograd, more types of ops inside the body of associative scan(e.g. different kinds of view ops, non-continous inputs and outputs.)

2024-10-23 17:25 UTC, ydwu4 commented on test/functorch/test_control_flow.py
> +        torch.concatenate([e[leave_ind] for e in op(result_flat)], dim)
oh, this one should deleted i feel? _fake_scan is now in _higher_order_ops/scan.py.

2024-11-06 23:40 UTC, bohnstingl commented
Closing this PR, as it is split into several smaller PRs: https://github.com/pytorch/pytorch/pull/138858, https://github.com/pytorch/pytorch/pull/139864, https://github.com/pytorch/pytorch/pull/139939

2024-11-06 23:40 UTC, closed without merging