Deprecate `skip_code_recursive_on_cache_limit_hit` config flag
pytorch/pytorch pull request #136970
Opened 2024-09-30 01:28 UTC by zeshengzong

Fixes #136862

Make `skip_code_recursive_on_cache_limit_hit` flag deprecated.

2024-09-30 17:39 UTC, williamwen42 requested changes
Keep the `justknobs_check` for now.

2024-09-30 20:55 UTC, anijain2305 requested changes
This is introduced very recently 2.5. So, I would like to keep this flag for quite some time, possibly after 2.6 is released (so somewhere around Jan).

2024-10-01 00:10 UTC, zeshengzong commented
> This is introduced very recently 2.5. So, I would like to keep this flag for quite some time, possibly after 2.6 is released (so somewhere around Jan).

Thanks for review, will try to do it after 2.6 released :D

2025-02-17 11:36 UTC, zeshengzong commented
Hi, is this right time to apply deprecation? Thanks!

2025-02-18 16:14 UTC, williamwen42 commented
I haven't seen any issues in the last while - should be safe by now.

2025-02-18 16:14 UTC, williamwen42 approved these changes

2025-02-18 16:21 UTC, williamwen42 commented
@pytorchbot merge

2025-02-18 18:48 UTC, closed without merging