clean up error_on_nested_jit_trace flag
pytorch/pytorch pull request #136961
Opened 2024-09-29 17:04 UTC by bobrenjc93

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136961

2024-09-29 17:17 UTC, bobrenjc93 commented
@pytorchbot rebase

2024-09-30 20:50 UTC, anijain2305 requested changes, later dismissed

2024-09-30 20:50 UTC, anijain2305 commented on torch/_dynamo/config.py
> -error_on_nested_jit_trace = True
Dont delete the flag from here.

2024-10-03 20:13 UTC, jansel submitted a review, later dismissed
Please add a comment to `config.py` that `error_on_nested_jit_trace` is ignored and maintained for backwards compatbility.

Also do this for all the other ignored flags.

2024-10-03 21:59 UTC, bobrenjc93 commented
> Please add a comment to `config.py` that `error_on_nested_jit_trace` is ignored and maintained for backwards compatbility.
> 
> Also do this for all the other ignored flags.

Done. I only landed one other PR without this comment. For that PR I made another PR adding the comment https://github.com/pytorch/pytorch/pull/137309

2024-10-03 22:35 UTC, jansel approved these changes

2024-10-03 22:40 UTC, bobrenjc93 commented
@pytorchbot merge

2024-10-04 02:07 UTC, closed without merging