remove capture_autograd_function flag
pytorch/pytorch pull request #136959
Opened 2024-09-29 16:57 UTC by bobrenjc93

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136959

2024-09-29 17:17 UTC, bobrenjc93 commented
@pytorchbot rebase

2024-09-30 14:58 UTC, bobrenjc93 commented
@pytorchbot rebase -b main

2024-09-30 20:47 UTC, anijain2305 commented on torch/_dynamo/config.py
> -capture_autograd_function = True
You should not delete the flag. The idea is to keep the flag here, but make it a no-op.

2024-09-30 20:47 UTC, anijain2305 requested changes, later dismissed
Lets not delete the flag from the config.py. Everything else LGTM.

2024-10-01 15:49 UTC, amjames commented on torch/_dynamo/variables/misc.py
> +        if requires_grad and torch.is_grad_enabled():
The flag is no longer participating in the logic here, but it seems like it has not actually been removed. Is it still used somewhere else? 

If not, and here is some downstream issue blocking actual removal, we should at least produce a warning on set if the config option is going to have no effect.

2024-10-02 04:23 UTC, jansel requested changes
(edit) nevermind saw discussion above

2024-10-02 04:24 UTC, jansel approved these changes

2024-10-02 16:57 UTC, bobrenjc93 commented
@pytorchbot merge -f "ci failures unrelated"

2024-10-02 16:59 UTC, closed without merging