[Inductor UT] Skip `test_autotune_unbacked` for XPU
pytorch/pytorch pull request #137189
Opened 2024-10-02 17:15 UTC by anmyachev

as far as i know cpp wrapper is not implemented for XPU yet: 
https://github.com/pytorch/pytorch/blob/466623fb511105a0bbbdb0836be87c66da953ff3/torch/_inductor/codegen/common.py#L265-L270

cc @etaf

2024-10-08 12:06 UTC, jgong5 commented
The support is being enabled, see this: https://github.com/pytorch/pytorch/pull/135318, cc @etaf

2024-10-09 02:54 UTC, jgong5 requested changes
Suggest to allow PR https://github.com/pytorch/pytorch/pull/135318 to land so the change is not necessary.

2024-10-09 09:26 UTC, anmyachev commented
> Suggest to allow PR #135318 to land so the change is not necessary.

Hi @jgong5, thanks for the review. 

That pull request has been open for quite some time, most likely it won't be merged for some time. Wouldn't it be better to merge my pull request so that CI works without errors? (and in #135318 remove the added skip mark)

2024-10-11 03:47 UTC, etaf commented
The test case has been skipped in main branch.

2024-10-11 10:14 UTC, closed without merging