[dynamo][pytree][2/N] make CXX pytree traceable: `tree_flatten` / `tree_unflatten`
pytorch/pytorch pull request #137398
Opened 2024-10-05 11:45 UTC by XuehaiPan

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-10-13 18:46 UTC, jansel approved these changes

2024-11-20 17:56 UTC, XuehaiPan commented
@pytorchbot merge

2024-11-21 06:08 UTC, jansel requested changes
Tests seem pretty broken now

2024-12-03 13:36 UTC, zou3519 commented
Just to reiterate: I haven't had the bandwidth to review this stack. I likely won't until next year. If someone else wants to, please feel free. The thing that I want is a careful enumeration of all differences between C++ pytree and Python pytree; I don't want users or developers to have a difficult time migrating over. As I understand it optree faithfully repros the semantics of JAX's pytree which has different semantics from torch.utils._pytree.

2024-12-09 13:41 UTC, XuehaiPan commented
> The thing that I want is someone to spend a week or two doing a careful enumeration of all differences between C++ pytree and Python pytree (I don't have a high-level view of this right now)

The existing C++ pytree and Python pytree share the same API and function signature. There are tests in our CI to ensure this. More, the pytree tests and dynamo tests are both tested against the Python pytree, C++ pytree, and the new public pytree API (a thin wrapper around the underlying pytree implementation).

2024-12-11 14:42 UTC, XuehaiPan commented
Hi @jansel, could you take a look at this PR and the next PR in the stack? Then the follow-ups can be reviewed and merged separately.

- #137398
- #137399

2024-12-12 17:12 UTC, jansel approved these changes

2024-12-12 18:05 UTC, closed without merging

2025-02-11 17:20 UTC, zou3519 commented on torch/_dynamo/polyfills/pytree.py
> +    class PyTreeSpec:
@XuehaiPan, if I'm understanding this correctly, you're adding a polyfill for cxx_pytree.tree_flatten such that it will return an instance of this PyTreeSpec class. I'm not sure this works if we are trying to return a PyTreeSpec from a torch.compile'd function: does it create an instance of this "class PyTreeSpec" object, or does it create an instance of torch.utils._cxx_pytree.TreeSpec?

2025-02-11 17:22 UTC, XuehaiPan commented on torch/_dynamo/polyfills/pytree.py
> +    class PyTreeSpec:
In a compiled function, it returns `torch._dynamo.polyfills.pytree.PyTreeSpec`. This class provides the exactly same interfaces with `torch.utils._cxx_pytree.TreeSpec`.

2025-02-11 17:25 UTC, zou3519 commented on torch/_dynamo/polyfills/pytree.py
> +    class PyTreeSpec:
Yeah this is wrong, see the following:
```py
import torch
import torch.utils._cxx_pytree as pytree

@torch.compile(backend="eager", fullgraph=True)
def f(x, y):
    vals, spec = pytree.tree_flatten(x)
    return vals, spec, y.sin()

y = torch.randn(3)
x = [1, [2, [3, 4]]]
vals, spec, _ = f(x, y)
this_doesnt_work = pytree.tree_unflatten(vals, spec)
```

2025-02-11 17:33 UTC, XuehaiPan commented on torch/_dynamo/polyfills/pytree.py
> +    class PyTreeSpec:
I see. It may cause problems if we only compile part of the program.

There is an in-progress polyfill infra for C++ classes.

- #146678