[WIP] graph break dispatch mode
pytorch/pytorch pull request #137334
Opened 2024-10-04 07:24 UTC by yf225

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137334

2024-10-12 11:20 UTC, ezyang commented
I need to check, do you have other use cases in mind? Because for the AutoFSDP use case having only the eager-only dispatch mode is not enough; we also need some integration on the Inductor side, and I'd therefore prefer to design these together as a package deal.

2024-10-12 11:22 UTC, ezyang commented
The naming in this PR is also puzzling to me. There's nothing about the implementation that's specific to modes. You are simply setting a flag that lets you tell if you're in a compiled region or not.

2024-10-12 11:22 UTC, ezyang commented
The current implementation is also in the hotpath for kernel launches and would have to be benchmarked

2024-10-12 23:20 UTC, yf225 commented
> I need to check, do you have other use cases in mind? Because for the AutoFSDP use case having only the eager-only dispatch mode is not enough; we also need some integration on the Inductor side, and I'd therefore prefer to design these together as a package deal.

Yes - I would like to resurrect the "cross-graph overlap" idea but make it easier on the UX side than LazyScheduler (draft design: https://docs.google.com/document/d/13UdWl1t4JR7CoSg4PeQDVZYCQ2k-sb4GOWWmNVs85W0/edit), and it will likely need this feature. I'll build a prototype there for discussion before iterating again on this PR.

2024-10-13 04:24 UTC, jansel requested changes
I share some of @ezyang's concerns here.  I'm not sure if this use case feels fully baked to me, or is common enough it needs to be built into the core infra (rather than on top of it).

Could we use `torch.compiler.is_compiling()` to change the behavior here?  That is our main existing tool for "do A if compiling, else B".

2025-01-11 05:34 UTC, closed without merging