[Inductor]: Support updated Triton `AttrsDescriptor`
pytorch/pytorch pull request #137757
Opened 2024-10-11 03:28 UTC by alexbaden

The Triton `AttrsDescriptor` object was refactored in https://github.com/triton-lang/triton/pull/4734. These changes add support for the new `AttrsDescriptor` while maintaining backwards compatibility with the existing version. The main changes are different names for the initialized of the descriptor parameters, and a creation via a static method instead of the class constructor. 

Depends on #137458 which removes some unused logic around the old descriptor. Those changes make this PR cleaner, but if for some reason that old logic is still used I can make adjustments. 

Use of the new `AttrsDescriptor` depends on https://github.com/triton-lang/triton/pull/4888

2024-10-11 03:47 UTC, alexbaden commented
@pytorchbot label "topic: not user facing"

2024-10-11 17:04 UTC, jansel requested changes

2024-10-11 17:04 UTC, jansel commented on torch/_inductor/runtime/hints.py
> +            return AttrsDescriptor.from_dict(kwargs)
Let's add some asserts to ensure things don't change over time (or with different backends).  For example:
```
assert res.property_values["tt.divisibility"] == 16
```

If that changes, this code will be incorrect.

2024-10-14 21:10 UTC, alexbaden commented
@jansel I rebased and addressed your change request. Please let me know if this needs anything else.

2024-10-15 16:32 UTC, jansel approved these changes

2024-10-15 16:52 UTC, jansel commented
@pytorchbot merge

2024-10-15 19:35 UTC, closed without merging