Avoid grabbing DeviceGuard in at::empty when possible
pytorch/pytorch pull request #13785
Opened 2018-11-09 19:27 UTC by zou3519

Changed at::empty to allocate the correct amount of memory instead of
"allocate 0 memory and then resize it to the necessary size".

This leads to a 300 ns speedup for at::empty for a cuda tensor of size (64, 2048).
(1790ns -> 1460ns for at::empty).

Also does the following:
Removes DeviceGuards for:
- empty_* functions that end up calling functions that already have a
  DeviceGuard
- t(), which gets called a lot in LSTMs,
- Remove one of the two DeviceGuard that at::empty(...) uses. It only
  needs one for correctness, the other comes from the resize_
  implementation.

Test Plan:
- run tests

2018-11-09 22:01 UTC, colesbury commented
This will likely have a merge conflict with https://github.com/pytorch/pytorch/pull/13751

2018-11-09 22:25 UTC, colesbury requested changes
I'm concerned by a few things:

1) The static_cast of the allocator
2) The calls into the CUDA API from a different device than the one allocating

For (2), I'm concerned that a call like `torch.empty(10, device=2)` will still initialize the current device (0) due to the CUDA calls in `process_events()`

2018-11-11 20:30 UTC, ezyang commented
I just merged the DeviceGuard patch, you probably want to rebase on top of that one.

2018-11-11 20:34 UTC, ezyang commented on aten/src/THC/THCCachingAllocator.cpp
> +      c10::optional<at::cuda::CUDAGuard> guard;
Post my DeviceGuard patch, you should write `at::cuda::OptionalCUDAGuard` here now. (DeviceGuard no longer has a default constructor.)

2018-11-12 18:11 UTC, zou3519 commented
Discussed with @colesbury and we decided it was better to not complicate the THCCachingAllocator with an "allocate_on_device" function. I've removed that part of the PR; now this PR only removes the use of `resize_` in `at::empty`

2018-11-12 22:15 UTC, zou3519 commented
Test failures should be fixed by #13864

2018-11-13 17:13 UTC, ezyang approved these changes

2018-11-14 15:41 UTC, closed without merging