[POC] automatic_dynamic_local_pgo
pytorch/pytorch pull request #138052
Opened 2024-10-16 03:21 UTC by ezyang

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #138052

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

2024-10-16 04:40 UTC, jansel requested changes

2024-10-16 04:40 UTC, jansel commented on torch/_dynamo/pgo.py
> +    with open(path, "wb") as f:
Do we need a FileLock + rename when ready?  What about multiple processes?  There may be a race condition here.

2024-10-16 04:40 UTC, jansel commented on torch/_dynamo/pgo.py
> +        cache_dir(), "dynamo", sha256_hash(pickle.dumps((filename, firstlineno, name)))
`pickle.dumps` is slow, I'd suggest `f"{filename},{firstlineno},{name}".encode("utf-8")`

2024-10-16 04:40 UTC, jansel commented on torch/_dynamo/pgo.py
> +                log.warning("get_code_object_cache failed while reading %s", path)
include error?

2024-10-18 01:55 UTC, ezyang commented on torch/_dynamo/config.py
> +automatic_dynamic_local_pgo = False
NB: this isn't wired up yet

2024-10-27 03:06 UTC, ezyang commented
Obsoleted by https://github.com/pytorch/pytorch/pull/139001

2024-10-27 03:06 UTC, closed without merging