fix trace nn.parameters()
pytorch/pytorch pull request #138149
Opened 2024-10-17 02:27 UTC by majian4work

Fixes #137764

2024-10-17 02:30 UTC, majian4work commented
@pytorchbot label "topic: not user facing"

2024-10-17 05:02 UTC, majian4work commented
@anijain2305 Could you help to take a review?

2024-10-21 05:13 UTC, majian4work commented
@anijain2305 @ydwu4 
Could you help to retrigger the failed test?

2024-10-24 02:07 UTC, majian4work commented
hi @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @rec
anybody can help to take an review.
thanks very much.

2024-10-24 02:46 UTC, ezyang commented
Can you put your test into the test suite too

2024-10-24 02:48 UTC, majian4work commented
> Can you put your test into the test suite too

Sure.

2024-10-24 07:13 UTC, majian4work commented
@ezyang seems still the same machine

2024-10-27 17:43 UTC, ezyang commented
@anijain2305 I think I need to defer to you for this

2024-11-04 01:41 UTC, majian4work commented
hi @anijain2305，
Could you help to take a review？

2024-11-11 05:58 UTC, majian4work commented
hi @anijain2305 
What's your opinion about this? hope for your feedback.

2024-11-11 23:20 UTC, anijain2305 commented
Sorry for the delay. Looking into this.

2024-11-11 23:29 UTC, anijain2305 requested changes

2024-11-12 06:36 UTC, anijain2305 approved these changes

2024-11-12 06:37 UTC, anijain2305 commented
@pytorchbot merge

2024-11-12 09:44 UTC, closed without merging