Issues/unravel index advance indexing
pytorch/pytorch pull request #138223
Opened 2024-10-17 15:12 UTC by Rahul-Ram-03

Fixes #136736

2024-10-17 16:35 UTC, Rahul-Ram-03 commented
Just noticed the CC spam. I am not entirely sure how that happened; I am a new contributor so, please forgive me.

2024-10-18 10:44 UTC, nikitaved commented on torch/functional.py
> +    )
This is exactly why we avoid checking indices. The problem is that if tensors live on the GPU, the `all` will cause a CPU-GPU synchronization, which can be expensive. Is the check missing in the kernel? If so, it is best to be placed there.

2024-10-19 03:45 UTC, ezyang requested changes
This implementation triggers DtoH sync and cannot be landed as is

2024-10-19 04:43 UTC, Rahul-Ram-03 commented
> This implementation triggers DtoH sync and cannot be landed as is

I assume the issue is with the fact that `coefs` is a "local" variable and as such, exists on the host, whilst `indices` could potentially exist on device. And I also assume that using `coefs[0]` causes the entire array to move to the device. As a workaround, should I initialize a tensor with just the value of `coefs[0]`?

2024-10-21 17:42 UTC, ezyang commented
The problem is not coefs, it's indices, which is a Tensor

2024-10-21 18:03 UTC, eellison commented on torch/functional.py
> +    )
can you do assert_async instead ?

2024-10-22 18:09 UTC, Rahul-Ram-03 commented on torch/functional.py
> +    )
Thank you for the pointer!

2024-10-29 03:36 UTC, Rahul-Ram-03 commented
Paging @eellison @ezyang

2024-10-29 14:34 UTC, ezyang requested changes
Nope

2024-12-13 15:57 UTC, closed without merging