Add documentation for torch.default_generator
pytorch/pytorch pull request #138295
Opened 2024-10-18 00:57 UTC by axsseldz

These changes add documentation for `torch.default_generator`, addressing the need raised in an issue by @ssnl  (Issue [#9886](https://github.com/pytorch/pytorch/issues/9886)).

- [x] torch.default_generator

2024-10-18 01:23 UTC, axsseldz commented
@pytorchbot label "topic: not user facing"

2024-10-18 01:32 UTC, axsseldz commented
Hey @ezyang , could you let me know what you think? :)

2024-10-20 21:32 UTC, ezyang commented
waiting to check render

2024-10-21 00:21 UTC, axsseldz commented
> waiting to check render

Thanks!

2024-10-21 17:36 UTC, ezyang requested changes
Looks misrendered

<img width="1261" alt="image" src="https://github.com/user-attachments/assets/58dad38b-4bbc-4d9d-a0fc-59e4ef2d4020">

It shouldn't be an entry directly, it should be a link to the actual doc page for it.

2024-10-21 18:25 UTC, axsseldz commented
> Looks misrendered
> 
> <img alt="image" width="1261" src="https://private-user-images.githubusercontent.com/13564/378539094-58dad38b-4bbc-4d9d-a0fc-59e4ef2d4020.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MzUyOTQsIm5iZiI6MTcyOTUzNDk5NCwicGF0aCI6Ii8xMzU2NC8zNzg1MzkwOTQtNThkYWQzOGItNGJiYy00ZDlkLWEwZmMtNTllNGVmMmQ0MDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE4MjMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYmJhOTYzN2RlYWIzZGRmNmQzZDZhMDZlM2M5OGQ3MDg0OWU3NTAyYjM1NzMxZmIyMWZjNTk1NGMzZjAyZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sX3pNEbWupxE0stNYF2exSfo9Vo2VArTGRKJTV0gXeE">
> It shouldn't be an entry directly, it should be a link to the actual doc page for it.

Oh i see, I'll do the changes asap

2024-10-24 03:05 UTC, ezyang commented
still misrendered

<img width="985" alt="image" src="https://github.com/user-attachments/assets/da73ac1c-79f0-4fce-89fa-785896561487">

Please check it yourself and retag me when it works

2024-10-24 04:44 UTC, axsseldz commented
> * Python docs built from this PR

yep will do

2024-10-31 16:08 UTC, axsseldz commented
Hi @ezyang

I've been working on the documentation updates. Initially, I was making changes in `torch/_torch_docs.py` using `add_docstr` for `default_generator`. However, it seems that `add_docstr` doesn't work for instances of classes or module-level variables.

Noticing that some documentation changes were made in `torch/random.py`, I applied my changes there as well, but they still aren’t visible in the generated docs. Could you confirm if `torch/random.py` is the correct place to make these changes, or if there’s another approach I should consider?

Thanks for your guidance!

<img width="833" alt="Screenshot 2024-10-31 at 8 59 18 AM" src="https://github.com/user-attachments/assets/fd6049bf-8a41-4e16-876c-b542b64825d3">
<img width="1008" alt="Screenshot 2024-10-31 at 8 59 27 AM" src="https://github.com/user-attachments/assets/8d3fab6e-cfa7-4f16-8f42-79b9417e59d9">

2024-11-01 03:57 UTC, ezyang commented
seems ok, given that it's available in torch.random too

2024-11-04 18:58 UTC, ezyang commented on torch/random.py
> +            device_mod.set_rng_state(device_rng_state, device)
need fix

2024-11-04 18:58 UTC, ezyang requested changes
this is now just wrong

2024-11-04 19:18 UTC, axsseldz commented
> this is now just wrong
I'm stuck with adding documentation for `default_generator`. For functions like `manual_seed` in `random.py`, their descriptions are in the function's docstring, and then added in `torch.rst`. But since `default_generator` is an object, I can't add a docstring directly, that's why I added the changes you can see. I tried updating `torch.rst`, but it's not rendering the description properly. I've been checking the codebase but haven't found where else to update it if its not in `random.py`. Any advice on this?

2024-11-04 19:18 UTC, axsseldz commented
> this is now just wrong

I'm stuck with adding documentation for `default_generator`. For functions like `manual_seed` in `random.py`, their descriptions are in the function's docstring, and then added in `torch.rst`. But since `default_generator` is an object, I can't add a docstring directly, that's why I added the changes you can see. I tried updating `torch.rst`, but it's not rendering the description properly. I've been checking the codebase but haven't found where else to update it if its not in `random.py`. Any advice on this?

2024-11-05 08:18 UTC, axsseldz commented
@ezyang, I created a `.rst` file for `default_generator` because `autosummary` in `docs/source/torch.rst` works for functions and classes with docstrings, but `default_generator` doesn't have a docstring. This is why my earlier description didn’t appear.

To fix this, I created a manual `.rst` file and linked it using `toctree`. While the link works, `default_generator` now shows as a bullet point, which breaks the design consistency.

Do you think it is possible to retain the correct design while keeping the link to the `.rst` file?

2025-02-04 23:34 UTC, closed without merging