[Inductor] support Conv/Linear + broadcast add fusion
pytorch/pytorch pull request #138201
Opened 2024-10-17 12:05 UTC by jiayisunx

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #138201

2024-11-06 05:32 UTC, jgong5 requested changes

2024-11-07 03:09 UTC, jiayisunx commented on .gitmodules
> +    url = https://github.com/jiayisunx/ideep
This is temporary for CI testing. I will upgrade ideep first and then try to merge the PR.

2024-11-13 05:39 UTC, jgong5 requested changes
Please tag me for review after you upgrade ideep and CI passes.

2024-11-20 00:51 UTC, jiayisunx commented
> Please tag me for review after you upgrade ideep and CI passes.

It's ready for review, could you please review it again? thanks!

2024-11-20 03:02 UTC, jgong5 approved these changes

2024-11-20 03:02 UTC, jgong5 commented on third_party/ideep
Better to separate this ideep upgrade to a different PR?

2024-11-20 03:12 UTC, jiayisunx commented on third_party/ideep
Okay, thanks for your comments!

2024-11-21 06:06 UTC, jansel approved these changes

2024-11-22 00:39 UTC, jiayisunx commented
@pytorchbot merge

2024-11-22 00:47 UTC, closed without merging

2025-01-17 23:43 UTC, masnesral commented
@jiayisunx / @jgong5 any guesses on why the new tests `test_conv2d_binary_broadcast_shapes_cpu` and `test_conv3d_binary_broadcast_shapes_cpu` would fail with: `RuntimeError: could not create a primitive descriptor for a reorder primitive`. We've got failures on Meta's internal testing. I wonder if it's just a matter of skipping if some lib version is too old?

Note that the failure doesn't seem to be related to torch.compile at all. I see the same problem if I try `torch.ops.mkldnn._convolution_pointwise.binary()` directly in eager..

2025-01-18 00:51 UTC, leslie-fang-intel commented
If I remember correctly, this PR has a update of IDEEP version. cc @jiayisunx to take a look.

2025-01-22 18:40 UTC, masnesral commented
@jiayisunx thanks for looking. It looks like we have incorporated those 2 PRs internally. Any other ideas that come to mind?

2025-01-26 02:20 UTC, jiayisunx commented
> @jiayisunx thanks for looking. It looks like we have incorporated those 2 PRs internally. Any other ideas that come to mind?

hi @masnesral , Is this PR (https://github.com/pytorch/pytorch/pull/141759) included internally? This PR was internally tested by @atalman before being merged and it passed. Are the internal tests you two are talking about the same test? You mentioned that you reproduced the issue by running torch.ops.mkldnn._convolution_pointwise.binary() directly in eager. Can you share this reproducer with me and I will try it locally?