Use thread-safe getenv functions
pytorch/pytorch pull request #138438
Opened 2024-10-21 03:19 UTC by cyyever

Fixes #ISSUE_NUMBER

2024-10-21 03:32 UTC, r-barnes requested changes
Not all of the `get_env` seem to have been used appropriately: some are associated with `const char *`. Those probably need attention.

Please use `const` whenever possible.

2024-10-21 03:34 UTC, cyyever commented on aten/src/ATen/Context.cpp
> +    auto workspace_config = c10::utils::get_env(cublas_config_var_name);
std::optional support == with the value type, see 
```
https://en.cppreference.com/w/cpp/utility/optional/operator_cmp
```

2024-10-21 03:47 UTC, cyyever commented
> Not all of the `get_env` seem to have been used appropriately: some are associated with `const char *`. Those probably need attention.
> 
> Please use `const` whenever possible.

Fixed

2024-10-21 03:49 UTC, cyyever commented
@pytorchbot rebase -b main

2024-10-24 03:14 UTC, cyyever commented on aten/src/ATen/cuda/tunable/Tunable.cpp
> +  static const char *env = c10::utils::get_env("PYTORCH_TUNABLEOP_MAX_WARMUP_DURATION_MS");
Fixed

2024-10-24 03:14 UTC, cyyever commented on aten/src/ATen/cuda/tunable/Tunable.cpp
> +  static const char *env = c10::utils::get_env("PYTORCH_TUNABLEOP_MAX_TUNING_ITERATIONS");
Fixed

2024-11-05 00:25 UTC, cyyever commented
@pytorchbot rebase

2025-01-06 02:15 UTC, closed without merging