[ONNX] Bypass mark_static_address when converting a model to onnx
pytorch/pytorch pull request #138580
Opened 2024-10-22 12:10 UTC by xadupre

Similar to torch.jit.isinstance #137592, torch.export.export does not support torch._dynamo.mark_static_address. This function is replaced by a function doing nothing before exporting and restored after.

2024-10-22 17:00 UTC, titaiwangms approved these changes
Interesting. People actually put internal dynamo API in the model

2024-10-22 17:57 UTC, justinchuby commented
Should this change be in some torch export code instead? I would be concerned that onnx export is taking more responsibility than it is designed to

2024-10-22 17:57 UTC, justinchuby commented
@tugsbayasgalan  @angelayi  do you have any suggestions? Thanks.

2024-10-22 17:58 UTC, justinchuby requested changes
Holding on for now, thanks

2024-10-23 05:17 UTC, xadupre commented
> Should this change be in some torch export code instead? I would be concerned that onnx export is taking more responsibility than it is designed to

Up to you. It is three lines of codes similar to jit.isinstance. Feel free to suggest another way.

2025-02-02 14:33 UTC, closed without merging