[compiled autograd] match eager behavior for post hooks
pytorch/pytorch pull request #138553
Opened 2024-10-22 05:56 UTC by YangQun1

Partially fixes #138538

2024-10-22 06:07 UTC, YangQun1 commented
Without reorder:
```python
def forward(self, inputs, sizes, scalars, hooks):
    # No stacktrace found for following nodes
    aot0_tangents_1: "f32[][]cpu" = inputs[0]
    aot0_primals_2: "f32[8, 16][16, 1]cpu" = inputs[1]
    aot0_mm: "f32[8, 16][16, 1]cpu" = inputs[2]
    aot0_permute_4: "f32[16, 16][16, 1]cpu" = inputs[3]
    getitem_4: "f32[16, 16][16, 1]cpu" = inputs[4];  inputs = None
    
    aot0_expand: "f32[8, 16][0, 0]cpu" = torch.ops.aten.expand.default(aot0_tangents_1, [8, 16]);  aot0_tangents_1 = None
    aot0_permute_2: "f32[16, 8][0, 0]cpu" = torch.ops.aten.permute.default(aot0_expand, [1, 0])
    aot0_mm_2: "f32[16, 16][16, 1]cpu" = torch.ops.aten.mm.default(aot0_permute_2, aot0_mm);  aot0_permute_2 = aot0_mm = None
    aot0_permute_3: "f32[16, 16][1, 16]cpu" = torch.ops.aten.permute.default(aot0_mm_2, [1, 0]);  aot0_mm_2 = None
    aot0_mm_3: "f32[8, 16][16, 1]cpu" = torch.ops.aten.mm.default(aot0_expand, aot0_permute_4);  aot0_expand = None
    aot0_permute_5: "f32[16, 16][16, 1]cpu" = torch.ops.aten.permute.default(aot0_permute_3, [1, 0]);  aot0_permute_3 = None
    
    accumulate_grad_ = torch.ops.inductor.accumulate_grad_.default(aot0_permute_4, aot0_permute_5);  aot0_permute_4 = accumulate_grad_ = None
    
    aot0_permute_6: "f32[16, 8][1, 16]cpu" = torch.ops.aten.permute.default(aot0_mm_3, [1, 0]);  aot0_mm_3 = None
    aot0_mm_4: "f32[16, 16][16, 1]cpu" = torch.ops.aten.mm.default(aot0_permute_6, aot0_primals_2);  aot0_permute_6 = aot0_primals_2 = None
    aot0_permute_7: "f32[16, 16][1, 16]cpu" = torch.ops.aten.permute.default(aot0_mm_4, [1, 0]);  aot0_mm_4 = None
    aot0_permute_8: "f32[16, 16][16, 1]cpu" = torch.ops.aten.permute.default(aot0_permute_7, [1, 0]);  aot0_permute_7 = None
    
    accumulate_grad__1 = torch.ops.inductor.accumulate_grad_.default(getitem_4, aot0_permute_8);  getitem_4 = accumulate_grad__1 = None
    
    getitem_5 = hooks[0]
    call_hook = torch__dynamo_external_utils_call_hook(getitem_5, [], [aot0_permute_5], hook_type = 'post_hook');  getitem_5 = aot0_permute_5 = call_hook = None
    
    getitem_6 = hooks[1];  hooks = None
    call_hook_1 = torch__dynamo_external_utils_call_hook(getitem_6, [], [aot0_permute_8], hook_type = 'post_hook');  getitem_6 = aot0_permute_8 = call_hook_1 = None
    _exec_final_callbacks_stub = torch__dynamo_external_utils__exec_final_callbacks_stub();  _exec_final_callbacks_stub = None
    return []
```

With reorder:
```python
def forward(self, inputs, sizes, scalars, hooks):
    # No stacktrace found for following nodes
    aot0_tangents_1: "f32[][]cpu" = inputs[0]
    aot0_primals_2: "f32[8, 16][16, 1]cpu" = inputs[1]
    aot0_mm: "f32[8, 16][16, 1]cpu" = inputs[2]
    aot0_permute_4: "f32[16, 16][16, 1]cpu" = inputs[3]
    getitem_4: "f32[16, 16][16, 1]cpu" = inputs[4];  inputs = None
    
    aot0_expand: "f32[8, 16][0, 0]cpu" = torch.ops.aten.expand.default(aot0_tangents_1, [8, 16]);  aot0_tangents_1 = None
    aot0_permute_2: "f32[16, 8][0, 0]cpu" = torch.ops.aten.permute.default(aot0_expand, [1, 0])
    aot0_mm_2: "f32[16, 16][16, 1]cpu" = torch.ops.aten.mm.default(aot0_permute_2, aot0_mm);  aot0_permute_2 = aot0_mm = None
    aot0_permute_3: "f32[16, 16][1, 16]cpu" = torch.ops.aten.permute.default(aot0_mm_2, [1, 0]);  aot0_mm_2 = None
    aot0_mm_3: "f32[8, 16][16, 1]cpu" = torch.ops.aten.mm.default(aot0_expand, aot0_permute_4);  aot0_expand = None
    aot0_permute_5: "f32[16, 16][16, 1]cpu" = torch.ops.aten.permute.default(aot0_permute_3, [1, 0]);  aot0_permute_3 = None
    
    accumulate_grad_ = torch.ops.inductor.accumulate_grad_.default(aot0_permute_4, aot0_permute_5);  aot0_permute_4 = accumulate_grad_ = None
    getitem_5 = hooks[0]
    call_hook = torch__dynamo_external_utils_call_hook(getitem_5, [], [aot0_permute_5], hook_type = 'post_hook');  getitem_5 = aot0_permute_5 = call_hook
    
    aot0_permute_6: "f32[16, 8][1, 16]cpu" = torch.ops.aten.permute.default(aot0_mm_3, [1, 0]);  aot0_mm_3 = None
    aot0_mm_4: "f32[16, 16][16, 1]cpu" = torch.ops.aten.mm.default(aot0_permute_6, aot0_primals_2);  aot0_permute_6 = aot0_primals_2 = None
    aot0_permute_7: "f32[16, 16][1, 16]cpu" = torch.ops.aten.permute.default(aot0_mm_4, [1, 0]);  aot0_mm_4 = None
    aot0_permute_8: "f32[16, 16][16, 1]cpu" = torch.ops.aten.permute.default(aot0_permute_7, [1, 0]);  aot0_permute_7 = None
    
    accumulate_grad__1 = torch.ops.inductor.accumulate_grad_.default(getitem_4, aot0_permute_8);  getitem_4 = accumulate_grad__1 = None
    getitem_6 = hooks[1];  hooks = None
    call_hook_1 = torch__dynamo_external_utils_call_hook(getitem_6, [], [aot0_permute_8], hook_type = 'post_hook');  getitem_6 = aot0_permute_8 = call_ho
    _exec_final_callbacks_stub = torch__dynamo_external_utils__exec_final_callbacks_stub();  _exec_final_callbacks_stub = None
    return []
```

2024-10-22 06:11 UTC, YangQun1 commented
@pytorchbot label "topic: not user facing

2024-10-22 06:11 UTC, YangQun1 commented
@pytorchbot label "topic: not user facing"

2024-10-22 17:07 UTC, xmfan requested changes
The change looks good for post hooks in isolation, but we can't land it alone because it would break the relative ordering among the hooks. See The order in which the different hooks are fired), post-hooks are item 6, so we need to ensure items 1-5 are also reordered.

2024-10-25 06:41 UTC, YangQun1 commented
The following is the bwd graph after reorder all bwd hooks. Hooks are called in this order:
- weight grad tensor pre hook
- weight acc_grad node pre hook
- weight acc_grad node
- weight post acc_grad hook
- weight acc_grad node post hook

The final weight grad values are same as eager mode.

```python
def forward(self, inputs, sizes, scalars, hooks):
    # No stacktrace found for following nodes
    aot0_tangents_1: "f32[][]cpu" = inputs[0]
    aot0_primals_1: "f32[4, 4, 3, 3][36, 1, 12, 4]cpu" = inputs[1]
    aot0_primals_2: "f32[1, 4, s2, s2][4*s2**2, 1, 4*s2, 4]cpu" = inputs[2]
    aot0_primals_3: "f32[4, 4, 3, 3][36, 1, 12, 4]cpu" = inputs[3]
    aot0_convolution: "f32[1, 4, s3, s3][4*s3**2, 1, 4*s3, 4]cpu" = inputs[4]
    getitem_5: "f32[4, 4, 3, 3][36, 9, 3, 1]cpu" = inputs[5]
    getitem_6: "f32[4, 4, 3, 3][36, 9, 3, 1]cpu" = inputs[6];  inputs = None
    
     # File: /home/quyang/venv_upstream_pt/lib/python3.10/site-packages/torch/_dynamo/compiled_autograd.py:772 in set_node_origin, code: CompiledFunctionBackward0 (NodeCall 1)
    aot0_expand: "f32[1, 4, 28, 28][0, 0, 0, 0]cpu" = torch.ops.aten.expand.default(aot0_tangents_1, [1, 4, 28, 28]);  aot0_tangents_1 = None
    aot0_convolution_backward = torch.ops.aten.convolution_backward.default(aot0_expand, aot0_convolution, aot0_primals_3, [0], [1, 1], [0, 0], [1, 1], False, [0, 0], 1, [True, True, False]);  aot0_expand = aot0_convolution = aot0_primals_3 = None
    aot0_getitem: "f32[1, 4, s3, s3][4*s3**2, 1, 4*s3, 4]cpu" = aot0_convolution_backward[0]
    aot0_getitem_1: "f32[4, 4, 3, 3][36, 1, 12, 4]cpu" = aot0_convolution_backward[1]
    getitem_13 = hooks[0]
    call_hook: "f32[4, 4, 3, 3][36, 1, 12, 4]cpu" = torch__dynamo_external_utils_call_hook(getitem_13, aot0_getitem_1, hook_type = 'tensor_pre_hook');  getitem_13 = aot0_getitem_1 = None
    getitem_14 = hooks[1]
    call_hook_1 = torch__dynamo_external_utils_call_hook(getitem_14, [call_hook], hook_type = 'pre_hook');  getitem_14 = call_hook = None
    getitem_15: "f32[4, 4, 3, 3][36, 1, 12, 4]cpu" = call_hook_1[0];  call_hook_1 = None
    
     # File: /home/quyang/venv_upstream_pt/lib/python3.10/site-packages/torch/_dynamo/compiled_autograd.py:772 in set_node_origin, code: torch::autograd::AccumulateGrad (NodeCall 2)
    accumulate_grad_ = torch.ops.inductor.accumulate_grad_.default(getitem_5, getitem_15);  accumulate_grad_ = None
    getitem_16 = hooks[3]
    call_hook_2: "f32[4, 4, 3, 3][36, 9, 3, 1]cpu" = torch__dynamo_external_utils_call_hook(getitem_16, getitem_5, hook_type = 'post_acc_grad_hook');  getitem_16 = getitem_5 = call_hook_2 = None
    getitem_17 = hooks[2]
    call_hook_3 = torch__dynamo_external_utils_call_hook(getitem_17, [], [getitem_15], hook_type = 'post_hook');  getitem_17 = getitem_15 = call_hook_3 = None
    
     # File: /home/quyang/venv_upstream_pt/lib/python3.10/site-packages/torch/_dynamo/compiled_autograd.py:772 in set_node_origin, code: CompiledFunctionBackward0 (NodeCall 1)
    getitem_9 = aot0_convolution_backward[2];  aot0_convolution_backward = getitem_9 = None
    aot0_convolution_backward_1 = torch.ops.aten.convolution_backward.default(aot0_getitem, aot0_primals_2, aot0_primals_1, [0], [1, 1], [0, 0], [1, 1], False, [0, 0], 1, [False, True, False]);  aot0_getitem = aot0_primals_2 = None
    getitem_10 = aot0_convolution_backward_1[0];  getitem_10 = None
    aot0_getitem_4: "f32[4, 4, 3, 3][36, 1, 12, 4]cpu" = aot0_convolution_backward_1[1]
    
     # File: /home/quyang/venv_upstream_pt/lib/python3.10/site-packages/torch/_dynamo/compiled_autograd.py:772 in set_node_origin, code: torch::autograd::AccumulateGrad (NodeCall 2)
    getitem_18 = hooks[4]
    call_hook_4: "f32[4, 4, 3, 3][36, 1, 12, 4]cpu" = torch__dynamo_external_utils_call_hook(getitem_18, aot0_getitem_4, hook_type = 'tensor_pre_hook');  getitem_18 = aot0_getitem_4 = None
    getitem_19 = hooks[5]
    call_hook_5 = torch__dynamo_external_utils_call_hook(getitem_19, [call_hook_4], hook_type = 'pre_hook');  getitem_19 = call_hook_4 = None
    getitem_20: "f32[4, 4, 3, 3][36, 1, 12, 4]cpu" = call_hook_5[0];  call_hook_5 = None
    
     # File: /home/quyang/venv_upstream_pt/lib/python3.10/site-packages/torch/_dynamo/compiled_autograd.py:772 in set_node_origin, code: torch::autograd::AccumulateGrad (NodeCall 3)
    accumulate_grad__1 = torch.ops.inductor.accumulate_grad_.default(getitem_6, getitem_20);  accumulate_grad__1 = None
    getitem_21 = hooks[7]
    call_hook_6: "f32[4, 4, 3, 3][36, 9, 3, 1]cpu" = torch__dynamo_external_utils_call_hook(getitem_21, getitem_6, hook_type = 'post_acc_grad_hook');  getitem_21 = getitem_6 = call_hook_6 = None
    getitem_22 = hooks[6];  hooks = None
    call_hook_7 = torch__dynamo_external_utils_call_hook(getitem_22, [], [getitem_20], hook_type = 'post_hook');  getitem_22 = getitem_20 = call_hook_7 = None
    
     # File: /home/quyang/venv_upstream_pt/lib/python3.10/site-packages/torch/_dynamo/compiled_autograd.py:772 in set_node_origin, code: CompiledFunctionBackward0 (NodeCall 1)
    getitem_12 = aot0_convolution_backward_1[2];  aot0_convolution_backward_1 = getitem_12 = None
    sym_size_int: "Sym(3)" = torch.ops.aten.sym_size.int(aot0_primals_1, 3)
    eq: "Sym(True)" = 3 == sym_size_int;  sym_size_int = eq = None
    sym_size_int_1: "Sym(4)" = torch.ops.aten.sym_size.int(aot0_primals_1, 1);  aot0_primals_1 = None
    eq_1: "Sym(True)" = 4 == sym_size_int_1;  sym_size_int_1 = eq_1 = None
    
     # File: /home/quyang/venv_upstream_pt/lib/python3.10/site-packages/torch/_dynamo/compiled_autograd.py:772 in set_node_origin, code: torch::autograd::AccumulateGrad (NodeCall 3)
    _exec_final_callbacks_stub = torch__dynamo_external_utils__exec_final_callbacks_stub();  _exec_final_callbacks_stub = None
    return []
```

Hi @xmfan , could you help to trigger the CI workflow and review?

2024-10-27 05:32 UTC, xmfan commented
In eager, pre hooks aren't scheduled as soon as possible, they are scheduled right before their node's execution

Here's a test that must pass:

```python
    # add this to test_autograd.py
    def test_hook_relative_ordering(self):
        x = torch.randn(10, 10, requires_grad=True)
        linear = torch.nn.Linear(10, 10)
        loss = linear(x).sum()

        SumBackward0 = loss.grad_fn
        ((AddmmBackward0, _),) = SumBackward0.next_functions
        ((AccumulateGrad0, _), (AccumulateGrad1, _), (TBackward0, _)) = (
            AddmmBackward0.next_functions
        )
        ((AccumulateGrad2, _),) = TBackward0.next_functions

        order = []

        def make_tensor_pre_hook(id):
            return lambda _: order.append(f"tensor_pre_hook_{id}")

        def make_pre_hook(id):
            return lambda _: order.append(f"pre_hook_{id}")

        def make_post_acc_grad_hook(id):
            return lambda _: order.append(f"post_acc_grad_hook_{id}")

        def make_post_hook(id):
            return lambda _1, _2: order.append(f"post_hook_{id}")

        x.register_hook(make_tensor_pre_hook("x"))
        linear.weight.register_hook(make_tensor_pre_hook("weight"))
        linear.bias.register_hook(make_tensor_pre_hook("bias"))

        SumBackward0.register_prehook(make_pre_hook("SumBackward0"))
        AddmmBackward0.register_prehook(make_pre_hook("AddmmBackward0"))
        AccumulateGrad0.register_prehook(make_pre_hook("AccumulateGrad0"))
        AccumulateGrad1.register_prehook(make_pre_hook("AccumulateGrad1"))
        TBackward0.register_prehook(make_pre_hook("TBackward0"))
        AccumulateGrad2.register_prehook(make_pre_hook("AccumulateGrad2"))

        x.register_post_accumulate_grad_hook(make_post_acc_grad_hook("x"))
        linear.weight.register_post_accumulate_grad_hook(
            make_post_acc_grad_hook("weight")
        )
        linear.bias.register_post_accumulate_grad_hook(make_post_acc_grad_hook("bias"))

        SumBackward0.register_hook(make_post_hook("SumBackward0"))
        AddmmBackward0.register_hook(make_post_hook("AddmmBackward0"))
        AccumulateGrad0.register_hook(make_post_hook("AccumulateGrad0"))
        AccumulateGrad1.register_hook(make_post_hook("AccumulateGrad1"))
        TBackward0.register_hook(make_post_hook("TBackward0"))
        AccumulateGrad2.register_hook(make_post_hook("AccumulateGrad2"))

        loss.backward()

        expected_order = [
            "pre_hook_SumBackward0",
            "post_hook_SumBackward0",
            "pre_hook_AddmmBackward0",
            "post_hook_AddmmBackward0",
            "tensor_pre_hook_bias",
            "pre_hook_AccumulateGrad0",
            "post_acc_grad_hook_bias",
            "post_hook_AccumulateGrad0",
            "tensor_pre_hook_x",
            "pre_hook_AccumulateGrad1",
            "post_acc_grad_hook_x",
            "post_hook_AccumulateGrad1",
            "pre_hook_TBackward0",
            "post_hook_TBackward0",
            "tensor_pre_hook_weight",
            "pre_hook_AccumulateGrad2",
            "post_acc_grad_hook_weight",
            "post_hook_AccumulateGrad2",
        ]
        breakpoint()

        self.assertEqual(len(expected_order), len(order))
        for expected, actual in zip(expected_order, order):
            self.assertEqual(expected, actual)
```

2024-10-29 12:36 UTC, YangQun1 commented
hi @xmfan , the pre hook reorder rule is modified, could help to review?

2024-10-30 03:53 UTC, xmfan approved these changes
Thanks for the change!

2024-10-30 04:53 UTC, YangQun1 commented
@pytorchbot merge

2024-10-30 08:46 UTC, closed without merging