Fix a bug that causes nvcc to emit a redefinition of argument error
pytorch/pytorch pull request #13905
Opened 2018-11-13 17:20 UTC by sgolodetz

From CMake 3.5 onwards, the host flag `-std=c++11` is automatically
propagated to nvcc. Manually setting it causes nvcc to emit the
following error message:

    nvcc fatal   : redefinition of argument 'std'

This fix prevents the flag from being set for versions of CMake >= 3.5,
thereby fixing the problem.

2018-11-13 17:29 UTC, soumith approved these changes

2018-11-14 04:32 UTC, soumith requested changes
what you said doesn't seem to be true, or your patch isn't working as intended.

See: https://circleci.com/gh/pytorch/pytorch/239529?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
Nov 14 03:43:53 /usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
Nov 14 03:43:53  #error This file requires compiler and library support \
Nov 14 03:43:53   ^
Nov 14 03:43:53 CMake Error at caffe2_gpu_generated_THCReduceApplyUtils.cu.o.Release.cmake:219 (message):
Nov 14 03:43:53   Error generating
Nov 14 03:43:53   /var/lib/jenkins/workspace/build_caffe2/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCReduceApplyUtils.cu.o
Nov 14 03:43:53 
```

2018-11-14 08:54 UTC, sgolodetz commented
Indeed - needs another look, apologies. Will investigate and try to fix it. One option might be to only add the flag if it's not already there.

The merge resolution currently undoes the other pull request I submitted btw - will fix that up at the same time.

2018-12-06 05:47 UTC, ezyang commented
Closing this for now, please feel free to reopen with a fix

2018-12-06 05:47 UTC, closed without merging