Add missing description for input parameters
pytorch/pytorch pull request #139020
Opened 2024-10-27 22:32 UTC by cz2h

Add missing descriptions for parameter `_use_new_zipfile_serialization` and `_disable_byteorder_record`.

Fixes #138017

2024-10-27 22:43 UTC, cz2h commented
@pytorchbot label "module: docs"

2024-11-15 22:23 UTC, cz2h commented
Hi @svekars @brycebortree @sekyondaMeta, could you help take a quick look when available? Thanks in advanced!

2024-11-15 22:48 UTC, mikaylagawarecki requested changes
I don't think we should document these private flags

2024-11-15 22:52 UTC, cz2h commented
> I don't think we should document these private flags

Thanks @mikaylagawarecki , I have also notice some broken links in the docs, for example this one https://pytorch.org/docs/stable/generated/torch.Tensor.is_shared.html. Do you think we can simply remove this one? I tried to look for _tensor.html under Module code, but this _tensor page seems to be removed.

2024-11-15 23:03 UTC, mikaylagawarecki commented
@cz2h  Could you clarify what you mean by broken links? I was able to click that link and it seemed to work okay

2024-11-16 00:41 UTC, cz2h commented
> @cz2h Could you clarify what you mean by broken links? I was able to click that link and it seemed to work okay

For sure. In this [page](https://pytorch.org/docs/stable/generated/torch.Tensor.is_shared.html) there is a source link (refercing https://pytorch.org/docs/stable/_modules/torch/_tensor.html#Tensor.is_shared). But that 'tensor.html#Tensor.is_shared' is a broken link, I am suspecting this is refercing a sub page under this [one](https://pytorch.org/docs/stable/_modules/#:~:text=torch._lowrank-,torch._tensor,-torch._tensor_str)  which is broken as well.

2024-11-27 22:19 UTC, closed without merging