[PyTorch] Move bf16_gemv_trans to ReducedPrecisionFloatGemvFastPathKernel
pytorch/pytorch pull request #139081
Opened 2024-10-28 17:20 UTC by swolchok

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Following the previous move of fp16_gemv_trans.

Differential Revision: [D64930872](https://our.internmc.facebook.com/intern/diff/D64930872/)

2024-11-01 16:48 UTC, malfet requested changes
This move will cause failures with compiled with SVE support

2024-11-01 17:37 UTC, swolchok commented
need to reorder this after https://github.com/pytorch/pytorch/pull/139090 and pull the fmadd(Vectorized<BFloat16>, Vectorized<BFloat16>, Vectorized<float>) from https://github.com/pytorch/pytorch/pull/139159 into this rev so that the vectorized tail loop will use SVE if appropriate rather than trying to mix Vectorized with NEON intrinsics.

2024-11-04 20:54 UTC, swolchok commented
some tests still in progress, but none of them are mps/aarch64 so I'm optimistic and re-requesting review.

2024-11-08 23:16 UTC, malfet approved these changes

2024-11-08 23:24 UTC, closed without merging