[Flex Attention] Dynamic shapes fix
pytorch/pytorch pull request #139069
Opened 2024-10-28 15:02 UTC by alexdremov

Fixes #139064

@Chillee

2024-10-28 15:23 UTC, alexdremov commented
There are fixes that required in `flex_decoding.py` too. For example https://github.com/pytorch/pytorch/blob/3b0f39336c88574fe63e8093d24fa00bcf6d2f62/torch/_inductor/kernel/flex_decoding.py#L297

2024-10-30 09:24 UTC, alexdremov commented
In my tests this results in recompilations when batch size and sequence length changes — there's a guard that checks L['query'][0] == <exact number>

@Chillee are there ways to check where this guard comes from specifically? So far, I was running code with dynamo debug, gusrds and recompilations logs and was not able to trace back where recompilation-causing guard comes from

2024-10-30 11:11 UTC, alexdremov commented on torch/_inductor/kernel/flex_attention.py
> +    fill_order = get_fill_order([V.graph.sizevars.evaluate_expr(sympy.sympify(i)) for i in query.get_stride()])
https://github.com/pytorch/pytorch/pull/139069/commits/c67f25cb3a960d12751819259825755579afbaad

should be a fix, let's see if the test passes

2024-10-30 12:07 UTC, alexdremov commented
@Skylion007 may I ask you to trigger tests?

2024-11-12 00:17 UTC, Chillee commented
@alexdremov Do you mind if I take over this PR?

2024-11-12 07:55 UTC, alexdremov commented
> @alexdremov Do you mind if I take over this PR? 

no, that's fine

2024-12-10 23:13 UTC, drisspg approved these changes

2024-12-11 21:17 UTC, drisspg requested changes
Will land here; https://github.com/pytorch/pytorch/pull/142816

2024-12-11 21:17 UTC, closed without merging