Bring back `io.BytesIO` type annotation for the output destinotion of `torch.onnx.export`
pytorch/pytorch pull request #139187
Opened 2024-10-29 12:43 UTC by antoinebrl

The support for `io.Bytes` was lost in [this refactoring](https://github.com/pytorch/pytorch/commit/e8fc1e0118da85c3529f71fa60823fdbbbebee56#diff-c3c8c09b65c1235ca4494633c6a0aab2761a11a7653ddaf9f874bbcd91e15553R148)

2024-10-29 14:16 UTC, justinchuby requested changes
Blocking for now

2024-10-29 17:35 UTC, antoinebrl commented
By exporting the model while keeping it in memory, we reduce the number of write operations to storage and minimize side effects of each test.

2024-10-29 18:16 UTC, justinchuby commented
> We use `io.Bytes` in our test suite. By exporting the model while keeping it in memory, we reduce the number of write operations to storage and minimize side effects of each test.

I see. Correcting what I said above: even though it is deprecated, you may continue to expect this behavior in the `torch.onnx.export` to stay unchanged. With the new `onnx_program = torch.onnx.export(..., dynamo=True)` api, you can call `onnx_program.model_proto` to get an `onnx.ModelProto` object.

2024-10-31 13:33 UTC, antoinebrl commented
I see ! Thanks for the speudo code. I will try that approach. I'm always a bit confused when a function returns something or nothing depending on the input arguments.

2024-12-30 17:27 UTC, closed without merging