typing ir.py - Disallow untyped defs for ir.py
pytorch/pytorch pull request #139238
Opened 2024-10-29 23:42 UTC by aorenste

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-10-30 00:59 UTC, Skylion007 commented on torch/_inductor/ir.py
> +    def index_length(self):  # type: ignore[no-untyped-def]
```suggestion
    def index_length(self) -> int:
```

2024-10-30 00:59 UTC, Skylion007 commented on torch/_inductor/ir.py
> -# mypy: allow-untyped-defs
Use ruff ANN rules to infer trivial return type annotations here

2024-10-30 19:27 UTC, Skylion007 approved these changes

2024-10-31 02:55 UTC, ezyang approved these changes
The "add per line suppresses" is not a very common strategy in our codebase but I guess it works

2024-10-31 05:36 UTC, aorenste commented
> The "add per line suppresses" is not a very common strategy in our codebase but I guess it works

I have a stack of PRs which I'm slowly landing in the background which removes a lot of these per-line suppressions.  My general philosophy is to set the flags to prevent new missing types from being accidentally landed and then backfill the existing missing types.

2024-10-31 11:53 UTC, ezyang commented
The main problem is that it is difficult to distinguish intentional suppressions from

2024-10-31 15:10 UTC, Skylion007 commented
> The main problem is that it is difficult to distinguish intentional suppressions from automatically added ones. This is less of a problem if you immediately fix them

We can add some other pragma that these are autogenerated, it only has to have type:ignore in the regex if I recall.

2024-10-31 15:10 UTC, Skylion007 commented
@pytorchbot merge

2024-10-31 16:39 UTC, aorenste commented
For my info: what's an example or case where we add an automatically added suppression? Are these added and expected to be permanent additions or is it more like "some PR broke lint and we're fixing it forward but you should fix this"?

2024-11-01 00:10 UTC, malfet approved these changes

2024-11-04 22:01 UTC, aorenste commented
@pytorchbot merge

2024-11-05 17:02 UTC, malfet commented on torch/_inductor/ir.py
> +    def mark_reuse(self, users) -> None:  # type: ignore[no-untyped-def]
```suggestion
    def mark_reuse(self, users) -> None:
```

2024-11-05 17:05 UTC, malfet requested changes
You have an anti pattern of
```
def foo() -> None:  # type: ignore[no-untyped-def]
```
Please fix it (suggested a few changes)
Also, if you want to enforce it, you'll need to modify lint runner.yaml, don't you?

2024-11-05 17:05 UTC, malfet commented on torch/_inductor/ir.py
> +    def should_realize_on_reuse(self, users):  # type: ignore[no-untyped-def]
```suggestion
    def should_realize_on_reuse(self, users) -> bool:
```

2024-11-05 17:05 UTC, malfet commented on torch/_inductor/ir.py
> +    def has_exceeded_max_reads(self):  # type: ignore[no-untyped-def]
```suggestion
    def has_exceeded_max_reads(self) -> bool:
```

2024-11-05 17:05 UTC, malfet commented on torch/_inductor/ir.py
> +    def codegen(self, wrapper) -> None:  # type: ignore[no-untyped-def]
```suggestion
    def codegen(self, wrapper) -> None:
```

2024-11-05 19:35 UTC, aorenste commented
> You have an anti pattern of
> 
> ```
> def foo() -> None:  # type: ignore[no-untyped-def]
> ```
> 
> Please fix it (suggested a few changes) Also, if you want to enforce it, you'll need to modify lint runner.yaml, don't you?

I think you're confused.  The purpose of this is to get us to a better state:
1. Disallow untyped defs by default and mark broken files individually (this was done in #127838)
2. When fixing a given file start by removing the file-level ignore and replace with function-level ignores (this PR)
3. Fix individual functions removing their function-level ignores. This is done in the rest of this stack (I did this during the last BE week but haven't had a lot of time to land) - this is the stack ending with #131852

The problem is that any one change can cause a ripple effect affecting MANY files so it's a lot easier to land smaller changes with temporary ignores than trying to land an single large change.

2024-11-06 00:01 UTC, closed without merging