[dynamo] Improve codegen for `DataPtrVariable` and fix tensor reference issue
pytorch/pytorch pull request #139487
Opened 2024-11-01 16:17 UTC by StrongerXi

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #139487

This addresses
https://github.com/pytorch/pytorch/pull/137677/files#r1799836499, which
had to set `allow_cache=False` for codegen on `DataPtrVariable.base`,
which is a `TensorVariable`, otherwise we observe failure of
`test_no_grad_copy` when testing with Dynamo.

I've seen `test_no_grad_copy` failing a few times, and every single time
it's related to cyclic reference, my best guess is the cyclic reference
holds some tensor object longer in memory than necessary, preventing the
optimization introduced in #11165.

This patch makes `OutputGraph.cleanup()` more aggressive by clearing out
all fields that might reference a `VariableTracker`. As a result, we can
remove the aforementioned `allow_cache=False`, which helps generate
better code (e.g., in the case of `test_no_grad_copy`, it ended up
skipping a redundant graph whose only op is returning the input tensor).

2024-11-01 16:24 UTC, StrongerXi commented
Why did `test_no_grad_copy` fail without `allow_cache=False`, I found that if you remove it, Dynamo ends up skipping this branch https://github.com/pytorch/pytorch/blob/087c0e776aaaa313f07d321971900d1bd9ef5a57/torch/_dynamo/output_graph.py#L1171-L1180

So why was this branch solving/hiding the memory issue? I have no idea. My wild guess is that it forced more memory usage and GC fired, preemptively clearing up the memory cycle before the code path in #11165.

As for the root cause of the cycle, I really dug hard on this one (tried to trace object and check gc at multiple places), and still couldn't find anything. So I just tried clearing more fields in `OutputGraph.cleanup()`, and it worked. I was able to nail it down to a `TensorVariable` (built from a pre-existing Python Tensor) -- if you just clear reference to that thing alone, it fixes the failure. But to make us more future proof, I ended up clearing all suspicious fields as well.

2024-11-01 17:26 UTC, jansel requested changes
Tests a failing?

2024-11-01 17:37 UTC, StrongerXi commented
> Tests a failing?

Probably went too aggressive and cleared something I shouldn't, will look.

2024-11-01 20:53 UTC, StrongerXi commented
Don't reset `cleanup_hooks` and `cleanups`, which are needed later in `convert_frame.py`. They also don't contain `VariableTracker` upon a closer look. Lastly, don't reset `random_values_var` since it's just a string.

2024-11-01 21:53 UTC, StrongerXi commented
Don't reset `random_calls`, it's captured by `_gen_rand_values` which needs to be installed in globals. It also operates on concrete Python values, so no reference to `VariableTracker`.

2024-11-03 05:21 UTC, jansel approved these changes

2024-11-03 18:08 UTC, aakhundov approved these changes

2024-11-04 16:28 UTC, StrongerXi commented
@pytorchbot merge

2024-11-04 19:14 UTC, closed without merging

2024-11-04 19:26 UTC, mlazos commented
FYI, clearing more fields in the output graph is the right approach, when I've seen memory issues it is usually caused by a cyclical reference with the output graph.