fix xpu build libm issue.
pytorch/pytorch pull request #139577
Opened 2024-11-03 09:55 UTC by xuhancn

Fixes #ISSUE_NUMBER

2024-11-03 10:37 UTC, xuhancn commented
@pytorchbot rebase

2024-11-05 06:38 UTC, EikanWang requested changes

2024-11-05 06:38 UTC, EikanWang commented on cmake/Dependencies.cmake
> +    endif()
It does not make sense to add such work around changes.

2024-11-13 07:17 UTC, xuhancn commented
Close by: https://github.com/pytorch/pytorch/issues/134989#issuecomment-2472664715

2024-11-13 07:17 UTC, closed without merging