WIP - Windows Arm64 Nightly Builds
pytorch/pytorch pull request #139760
Opened 2024-11-05 15:30 UTC by iremyux

Draft PR to trigger workflows

2024-11-12 16:17 UTC, seemethere commented
@pytorchbot label ciflow/binaries

2025-02-19 03:11 UTC, huydhn commented on .github/workflows/_win-arm64-build.yml
> +          role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_s3_and_ecr_read_only
Could you try to use `gha_workflow_sscache` instead?
```suggestion
          role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_sscache
```

2025-02-19 13:19 UTC, atalman commented on .ci/pytorch/win-arm64-test-helpers/build_pytorch.bat
> +    echo NOTE: To run `import torch`, please make sure to activate the conda environment by running `call %CONDA_PARENT_DIR%\Miniconda3\Scripts\activate.bat %CONDA_PARENT_DIR%\Miniconda3` in Command
Hi @iremyux do we really need to install conda here ? We are trying to get rid of conda dependency

2025-02-19 13:21 UTC, atalman commented on .ci/pytorch/windows/arm64/smoke_test.bat
> +set CORE_TEST_LIST=test_autograd.py test_nn.py test_torch.py
Can we also call 
```https://github.com/pytorch/pytorch/blob/main/.ci/pytorch/smoke_test/smoke_test.py```

2025-02-21 10:02 UTC, iremyux commented on .ci/pytorch/win-arm64-test-helpers/build_pytorch.bat
> +    echo NOTE: To run `import torch`, please make sure to activate the conda environment by running `call %CONDA_PARENT_DIR%\Miniconda3\Scripts\activate.bat %CONDA_PARENT_DIR%\Miniconda3` in Command
hey, yeap i think we missed it, conda is not available for arm64 anyway, I removed the installation.

2025-02-25 14:48 UTC, iremyux commented on .ci/pytorch/windows/arm64/smoke_test.bat
> +set CORE_TEST_LIST=test_autograd.py test_nn.py test_torch.py
done. results can be seen here:

2025-02-25 16:02 UTC, iremyux commented
Removing ciflow/binaries label since windows-arm64-binary-wheel, windows-arm64-binary-libtorch-debug and windows-arm64-binary-libtorch-release are all stable and green now. No need to trigger them anymore.

2025-02-26 14:29 UTC, iremyux commented
Removing ciflow/binaries label since nightlies are all stable and green now. Here are the last runs: 
[windows-arm64-binary-wheel · pytorch/pytorch@65d08a2](https://github.com/pytorch/pytorch/actions/runs/13542265024)
[windows-arm64-binary-libtorch-release · pytorch/pytorch@415728c](https://github.com/pytorch/pytorch/actions/runs/13519381877)
[windows-arm64-binary-libtorch-debug · pytorch/pytorch@415728c](https://github.com/pytorch/pytorch/actions/runs/13519381887)

2025-03-01 11:37 UTC, iremyux commented
last successful arm64 nightly workflows: 
[windows-arm64-binary-libtorch-release · pytorch/pytorch@415728c](https://github.com/pytorch/pytorch/actions/runs/13519381877)
[windows-arm64-binary-libtorch-debug · pytorch/pytorch@415728c](https://github.com/pytorch/pytorch/actions/runs/13519381887)
[windows-arm64-binary-wheel · pytorch/pytorch@97dafd8](https://github.com/pytorch/pytorch/actions/runs/13589031393)

2025-03-03 10:33 UTC, Blackhex commented on .ci/pytorch/test_example_code/rnn_smoke_win_arm64.py
> +output, hn = rnn(inputs, h0)
This change and the change in `.ci/pytorch/test_example_code/cnn_smoke_win_arm64.py` file seem to be unnecessary and not relevant to the rest of the PR.

2025-03-03 10:38 UTC, Blackhex commented on .ci/pytorch/windows/arm64/bootstrap_buildtools.bat
> +setlocal enabledelayedexpansion
What was the issue with the original version of the script so this line had to be added?

2025-03-03 10:39 UTC, Blackhex commented on .ci/pytorch/windows/arm64/bootstrap_buildtools.bat
> +    "%INSTALLER_FILE%" --norestart --quiet --wait --installPath "%DEPENDENCIES_DIR%\VSBuildTools" ^
When such significant change of the list is done, I 'd sort them by component names alphabetically as well to make the future maintenance easier.

2025-03-03 10:44 UTC, Blackhex commented on .ci/pytorch/windows/arm64/bootstrap_buildtools.bat
> -    echo "Failed to install Visual Studio Build Tools with C++ components. (exitcode = %errorlevel%)"
This and the change of the previous lines does not make much sense: When the `%errorlevel%` is non-zero it's better to print the value together with the error message, when it's zero it's kind of unecessary to print it.

2025-03-03 11:00 UTC, Blackhex commented on .ci/pytorch/windows/arm64/smoke_test.bat
> -set "PATH=%ORIG_PATH%"
This line was there for a reason. Is that reason no longer valid? If yes, saving the path to `ORIG_PATH` at the beginning fo the script should be removed as well.

2025-03-03 11:48 UTC, Blackhex reviewed
Overall looks good, I left some minor comments.

2025-03-03 12:33 UTC, iremyux commented on .ci/pytorch/test_example_code/rnn_smoke_win_arm64.py
> +output, hn = rnn(inputs, h0)
you're right, they do not appear as changed now.

2025-03-03 13:38 UTC, Blackhex commented on .ci/pytorch/windows/arm64/bootstrap_buildtools.bat
> -    echo "Failed to install Visual Studio Build Tools with C++ components. (exitcode = %errorlevel%)"
OK, thank you for the explanation.

2025-03-03 17:48 UTC, malfet requested changes
Please do not add testing to CD builds, as tests should have been run during CI.
Otherwise, looks OK to me, though I don't understand why it's necessary to keep adding new batch scripts in 2025. Aren't PowerShell available by default on all Windows-on-ARM systems?

2025-03-03 17:48 UTC, malfet commented on .ci/pytorch/windows/arm64/bootstrap_buildtools.bat
> +    "%INSTALLER_FILE%" --norestart --quiet --wait --installPath "%DEPENDENCIES_DIR%\VSBuildTools" ^
@ozanMSFT does it mean that this is still a draft PR or a final version?

2025-03-03 17:48 UTC, malfet commented on .ci/pytorch/windows/arm64/bootstrap_buildtools.bat
>  ) else if "%MSVC_VERSION%" == "14.40" (
Why do you need to support so many different versions of the toolchain right away? For CI you can always pick one, can't you?

2025-03-03 17:48 UTC, malfet commented on .ci/pytorch/windows/arm64/smoke_test.bat
> +)
We usually don't do full test runs during nightly builds, this should be part of CI pipeline

2025-03-04 22:22 UTC, malfet commented on .ci/pytorch/windows/arm64/bootstrap_buildtools.bat
>  ) else if "%MSVC_VERSION%" == "14.40" (
Since we are not testing those, do you mind deleting dead code from the script?
Also, I would advice against latest, as this would results in CD builds starting to fail on one day and it makes it really hard to figure out that it was due to the version change

2025-03-05 16:07 UTC, malfet approved these changes
I'm sad about amount of copy-and-paste (and batch scripts), but sure, let's land it as is to get some signal.

But let's plan to revert this change(in say a month from now) if no dedup/batch->powershell migration happens

2025-03-05 16:07 UTC, malfet commented on .github/scripts/generate_ci_workflows.py
> +            python_versions=["3.12"],
I guess windows-on-arm users only care about Python-3.12.. Oh well.

2025-03-05 16:07 UTC, malfet commented on .github/templates/windows_arm64_binary_build_workflow.yml.j2
> +{% import 'common.yml.j2' as common %}
This whole copy-n-paste makes me sad, but whatever

2025-03-05 16:10 UTC, malfet requested changes
Hmm, I didn't notice you've also added `main` builds.
Please remove them, no need to build Windows-on-ARM binaries for every trunk commit

2025-03-05 16:45 UTC, malfet approved these changes

2025-03-05 16:55 UTC, seemethere commented on .github/templates/windows_arm64_binary_build_workflow.yml.j2
> +          repository:  "iremyux/pytorch"
This will probably need to change

2025-03-05 21:08 UTC, malfet commented on .github/pytorch-probot.yml
> +- ciflow/win-arm64
Why are you adding this one? `ciflow/` labels are usually reserved for CI, for CD everything should be triggered by `ciflow/binaries`

2025-03-05 21:08 UTC, malfet requested changes
Please do not trigger CD, on `ciflow/win-arm64` labels (`ciflow/binary_wheels` should be sufficient)

2025-03-06 12:45 UTC, iremyux commented on .github/scripts/generate_ci_workflows.py
> +            python_versions=["3.12"],
I think we discussed this on yesterday's meeting.

2025-03-06 12:45 UTC, iremyux commented on .github/templates/windows_arm64_binary_build_workflow.yml.j2
> +{% import 'common.yml.j2' as common %}
I think we discussed this on yesterday's meeting.

2025-03-06 12:48 UTC, iremyux commented on .github/templates/windows_arm64_binary_build_workflow.yml.j2
> +          repository:  "iremyux/pytorch"
Done

2025-03-06 12:51 UTC, iremyux commented
@malfet @seemethere 
All of the reviews are addressed and resolved, can you please take a look again?

2025-03-07 18:50 UTC, malfet approved these changes
LGTM, but I'm filing a followup task to https://github.com/pytorch/pytorch/issues/148776 and propose to revert this PR if this is not closed within next say 30 days

2025-03-07 18:54 UTC, closed without merging