Revert D65583004
pytorch/pytorch pull request #140162
Opened 2024-11-08 18:27 UTC by huydhn

Summary:
This diff reverts D65583004
D65583004, broke 10+ tests. See details in T207079384

Test Plan: NA

Reviewed By: cr333

Differential Revision: D65670779

2024-11-08 18:33 UTC, podgorskiy commented
@pytorchbot label "topic: not user facing"

2024-11-08 19:21 UTC, ZainRizvi approved these changes

2024-11-08 19:57 UTC, malfet requested changes
Looking at it again, the justification looks somewhat weak

2024-11-09 01:17 UTC, huydhn commented
Closing this as I think the PR has been reverted

2024-11-09 01:17 UTC, closed without merging