fix bug in utils/cpp_extension.py
pytorch/pytorch pull request #14029
Opened 2018-11-15 13:49 UTC by whllhw

when i build [maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark) , this file throws this warning :
```
lib/python3.7/site-packages/torch/utils/cpp_extension.py:182: UserWarning: Error checking compiler version for g++: a bytes-like object is required, not 'str' warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
```
and i checked subprocess.check_output return bytes not str in python3 , so it is some bug here.i hope remove this warning.

2018-11-15 14:01 UTC, fmassa requested changes
There is a lint error, but I think this is right.

Can we maybe add a test for this use-case?

cc @goldsborough as this issue was introduced in https://github.com/pytorch/pytorch/pull/13092

2018-11-15 14:04 UTC, whllhw commented on torch/utils/cpp_extension.py
> +            if not isinstance(version,str):
I am so sorry, I committed online and ignored lint.

2018-11-15 14:05 UTC, fmassa commented on torch/utils/cpp_extension.py
> +            if not isinstance(version,str):
No worries, thanks for the fix!

2018-11-18 01:22 UTC, closed without merging

2018-11-30 11:02 UTC, aoyingchen commented
Whether this bug has been fixed, I looked at the source code and it seems that this bug has not been FIX yet.