[mobile] Fix Conv1d optimization with 'same' padding mode
pytorch/pytorch pull request #140221
Opened 2024-11-10 06:19 UTC by AkiSakurai

Adds a filter to prevent rewriting Conv1d operations that use string-based padding modes ('same') to Conv2d. This resolves a runtime error where string padding values were incorrectly handled as lists during mobile optimization.

Added test coverage for Conv1d with 'same' padding to verify the fix.

Fixes #104606

2024-11-14 19:47 UTC, davidberard98 reviewed
like #140224, will wait for @digantdesai for a day for review, otherwise lgtm.

If it's been a day and both I and Digant have forgotten to respond on these PRs, feel free to ping me as a reminder :)

2024-11-15 17:37 UTC, davidberard98 requested changes

2024-11-15 17:37 UTC, davidberard98 commented on torch/csrc/jit/passes/xnnpack_rewrite.cpp
> +        return node->schema().overload_name() != "padding";
It seems like previously, `padding == "valid"` wouldn't error out. Is that accurate?

If so - to minimize any fallout from this PR - could you make this `not (overload == "padding" and op.padding == "same")` ?

2024-11-16 07:10 UTC, AkiSakurai commented
Another attempt was made to rewrite SAME padding using explicit padding values. However, even-sized weights require asymmetric padding, making this approach impractical. The effort required to fix PyTorch Mobile's quirks would be comparable to addressing ExecTorch's beta issues.

2024-11-16 07:10 UTC, closed without merging