[Intel GPU] Enable mkdnn._linear_pointwise at XPU backend
pytorch/pytorch pull request #140365
Opened 2024-11-12 06:07 UTC by ZhiweiYan-96

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-11-20 07:53 UTC, etaf requested changes
Please check if the suggested change is reasonable.

2024-11-24 15:47 UTC, EikanWang commented
Pls. ensure your PR to be small enough for the sake of review

2024-11-25 05:00 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/Linear.h
> +        result, _input, weight, /*trans*/ true, attr, is_fused_, _bias);
Thanks for your reminding. I have changed the code and uts.

2025-05-13 09:27 UTC, etaf requested changes
Please fix lint error first.

2025-05-13 09:27 UTC, etaf commented on test/xpu/test_fusion.py
> +                    mod = mod.to("xpu")
This isn’t a big issue, but since you’ve already used
instantiate_device_type_tests(TestoneDNNFusion, globals(), only_for="xpu", allow_xpu=True),
it’s best not to hardcode "xpu" inside the test cases.

2025-05-13 09:27 UTC, etaf commented on aten/src/ATen/native/mkldnn/xpu/Linear.cpp
> +    c10::string_view attr,
c10::string_view is an alias of std::string_view and the community are planning to deprecate it. Please replace all in this PR with std::string_view.

2025-05-13 09:27 UTC, etaf commented on aten/src/ATen/native/mkldnn/xpu/Linear.cpp
> +    c10::string_view binary_attr) {
```suggestion
    std::string_view binary_attr) {
```

2025-05-13 09:27 UTC, etaf commented on aten/src/ATen/native/mkldnn/xpu/Linear.cpp
> +    c10::string_view attr,
```suggestion
    std::string_view attr,
```

2025-05-14 15:25 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/Linear.cpp
> +    c10::string_view attr,
modified

2025-05-14 15:25 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/Linear.cpp
> +    c10::string_view binary_attr) {
modified

2025-05-14 15:26 UTC, ZhiweiYan-96 commented on test/xpu/test_fusion.py
> +                    mod = mod.to("xpu")
Thanks for reminding, I add `device` argument in tests, and uses `model.to(device)` instead.

2025-05-14 15:51 UTC, EikanWang commented
@ZhiweiYan-96 , is this PR ready for the pre-review?

2025-05-15 05:09 UTC, ZhiweiYan-96 commented
@EikanWang Yes, please review the PR, thanks!

2025-05-15 12:46 UTC, EikanWang commented
@ZhiweiYan-96 , pls. check the copilot's comments.

2025-05-19 02:02 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +
```suggestion
```

2025-05-19 02:03 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +    c10::optional<c10::string_view> algorithm = c10::nullopt,
```suggestion
    std::optional<c10::string_view> algorithm = std::nullopt,
```

2025-05-19 02:05 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +        c10::nullopt,
```suggestion
        std::nullopt,
```

2025-05-19 02:05 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +    torch::List<c10::optional<at::Scalar>> scalars,
```suggestion
    torch::List<std::optional<at::Scalar>> scalars,
```

2025-05-19 02:06 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +    c10::optional<at::Scalar> alpha,
```suggestion
    std::optional<at::Scalar> alpha,
```

2025-05-19 02:07 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.h
> +    torch::List<c10::optional<at::Scalar>> scalars,
```suggestion
    torch::List<std::optional<at::Scalar>> scalars,
```

2025-05-19 02:07 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.h
> +    c10::optional<c10::string_view> algorithm,
```suggestion
    std::optional<c10::string_view> algorithm,
```

2025-05-19 02:07 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.h
> +    torch::List<c10::optional<at::Scalar>> scalars,
```suggestion
    torch::List<std::optional<at::Scalar>> scalars,
```

2025-05-19 02:07 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.h
> +    c10::optional<c10::string_view> algorithm,
```suggestion
    std::optional<c10::string_view> algorithm,
```

2025-05-19 02:07 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.h
> +    c10::optional<at::Scalar> alpha,
```suggestion
    std::optional<at::Scalar> alpha,
```

2025-05-19 02:08 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.h
> +  }
Need a `TORCH_CHECK`

2025-05-19 02:13 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/Linear.cpp
> +
Need a device guard to ensure the current device is expected.

2025-05-19 02:13 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/Linear.cpp
> +
Need a device guard to ensure the current device is expected.

2025-05-19 02:14 UTC, guangyey requested changes
Please add a device guard when registering an op via `m.impl`

2025-05-21 05:55 UTC, etaf approved these changes

2025-05-21 06:23 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.h
> +  }
hi, @guangyey  could you please elaborate more here?

2025-05-21 06:54 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +
modified

2025-05-21 06:55 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +    c10::optional<c10::string_view> algorithm = c10::nullopt,
modified

2025-05-21 06:55 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +        torch::List<c10::optional<at::Scalar>>(),
ditto

2025-05-21 06:55 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +    torch::List<c10::optional<at::Scalar>> scalars,
ditto

2025-05-21 06:55 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.h
> +    torch::List<c10::optional<at::Scalar>> scalars,
done

2025-05-21 06:55 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.h
> +    c10::optional<c10::string_view> algorithm,
done

2025-05-21 06:55 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.h
> +    torch::List<c10::optional<at::Scalar>> scalars,
done

2025-05-21 06:55 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.h
> +    c10::optional<at::Scalar> alpha,
done

2025-05-21 06:56 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/Linear.cpp
> +
added

2025-05-21 07:55 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.h
> +  }
I mean need to check if `binary` is supported.
```suggestion
  } else {
      TORCH_CHECK(false, ...)
  }
```

2025-05-21 08:03 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.h
> +  }
got it and modified. Besides, could you please resolve some `c10` related comments for easier reviewing? I should modified them all

2025-05-21 08:13 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +    if (algorithm.value() == "none") {
We should detect `algorithm.has_value()` before fetching its value, otherwise it will crash.

2025-05-21 08:19 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +  std::set<std::string_view> simple_unary = {
```suggestion
  static const std::set<std::string_view> simple_unary = {
```

2025-05-21 08:25 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +    Attr attr = Attr()) {
Would it introduce non-negligible overhead of its copy constructor about `oneDNN::Attr`? I see you pass this struct through the call stack instead of its reference.

2025-05-21 09:01 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +    std::optional<std::string_view> algorithm = std::nullopt,
In general, default values are typically specified in the function declaration, most often in the header file.

2025-05-21 09:04 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.h
> +    std::optional<at::Scalar> alpha,
where is `aplha` used?

2025-05-23 03:39 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +    if (algorithm.value() == "none") {
add TORCH_CHECK for avoid issue, thanks.

2025-05-23 03:39 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +  std::set<std::string_view> simple_unary = {
added

2025-05-23 03:40 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +    Attr attr = Attr()) {
good catch. I modify all usage in `FusionUtils.cpp` and `FusionUtils.h` with reference arguments.

2025-05-23 03:42 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +    std::optional<std::string_view> algorithm = std::nullopt,
the argument list is too much complex with default value. I did a little order change(move attr to 1st) and lots of overloading syntax error. So, I decides the remove all default arguments in these utils.

2025-05-23 03:42 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.h
> +    std::optional<at::Scalar> alpha,
argument removed.

2025-05-26 02:15 UTC, guangyey commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +    return attr.append_post_eltwise(1.0, alpha, 0.f, attr.kind_with_relu);
following your style.
```suggestion
    return attr.append_post_eltwise(1.0f, alpha, 0.0f, attr.kind_with_relu);
```

2025-05-26 02:17 UTC, EikanWang approved these changes

2025-05-26 02:17 UTC, EikanWang commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
@ZhiweiYan-96 , in terms of these literals like hardswish, slilu, etc, they should be defined as a constant variable.

2025-05-26 02:19 UTC, guangyey approved these changes

2025-05-26 02:31 UTC, etaf commented
> @etaf , is the failure a new issue?

Yes, Rebase can resolve the issue.

2025-05-26 06:47 UTC, ZhiweiYan-96 commented on aten/src/ATen/native/mkldnn/xpu/FusionUtils.cpp
> +    return attr.append_post_eltwise(1.0, alpha, 0.f, attr.kind_with_relu);
modified ,thanks for reminding

2025-05-27 01:52 UTC, EikanWang approved these changes

2025-05-27 15:49 UTC, ZhiweiYan-96 commented
@pytorchbot merge

2025-05-27 15:57 UTC, closed without merging