add fp8 scaled_mm for XPU
pytorch/pytorch pull request #140434
Opened 2024-11-12 19:03 UTC by yuchengliu1

add fp8 scaled_mm for XPU
Fixes #ISSUE_NUMBER

2024-11-13 01:14 UTC, Xia-Weiwen commented
CC @Guobing-Chen and @yanbing-j as this PR tries to change ideep version.

2024-11-13 01:21 UTC, yanbing-j commented
> CC @Guobing-Chen and @yanbing-j as this PR tries to change ideep version.

I suppose this is a draft PR to involve oneDNN v3.6 inside. @yuchengliu1 Could you please use ghstack to split the ideep/onednn change and other code change? And after we upgrade oneDNN into PyTorch, you can rebase this ghstack.

2024-11-14 06:57 UTC, mingfeima requested changes
this PR right now has a lot of unnecessary format changes, can we just remove such changes. Usually if we want to scrap format changes, we can open a separate PR to do the job, otherwise it is harder to tell what this PR is really about.

2024-11-14 07:27 UTC, airMeng commented on test/inductor/test_fp8.py
>      @unittest.skipIf(not PLATFORM_SUPPORTS_FP8, f8_msg)
remember to update the definition of this

2024-11-14 12:15 UTC, EikanWang commented
It does not make sense to change non-XPU related code. Pls. refine this PR. Meanwhile, pls. ensure your PR is small enough for the sake of review.

2024-11-14 12:17 UTC, EikanWang requested changes
Pls. refine the PR and attach right labels!

2024-11-18 19:56 UTC, closed without merging