Add boolean conversion support for SymNodeVariable
pytorch/pytorch pull request #140621
Opened 2024-11-13 22:06 UTC by axsseldz

Adds support for boolean conversion of tensor operations involving SymNodeVariable, fixing the "Unsupported: builtin: bool [SymNodeVariable]" error.

Changes:
- Add `__bool__` method to SymNodeVariable for tensor-to-boolean conversion
- Implement bool_handler in builtin operations to handle SymNodeVariable
- Add test coverage for boolean conversion scenarios

## Testing
- Added test case in test_higher_order_ops.py verifying both tensor ops and explicit bool conversion
- Test covers both True and False cases with different tensor inputs

Fixes [#136075](https://github.com/pytorch/pytorch/issues/136075)

2024-11-13 22:08 UTC, axsseldz commented
@pytorchbot label "topic: not user facing"

2024-11-13 22:10 UTC, axsseldz commented
hey @ezyang, could you provide me with feedback on these changes, please

2024-11-14 03:22 UTC, ezyang requested changes
bool handler should not be `__bool__` method. Not sure about the rest

2024-11-14 03:22 UTC, ezyang commented
@anijain2305 can you send this to correct dynamo reviewer

2024-11-18 21:05 UTC, axsseldz commented
hi @anijain2305, you could provide me with some feedback regarding these changes, please

2025-02-16 22:34 UTC, closed without merging