Fix MPS synchronize by waiting for root buffer to complete
pytorch/pytorch pull request #140725
Opened 2024-11-14 17:19 UTC by skotapati

Fixes #139550

2024-11-14 17:22 UTC, malfet commented
@skotapati this fixes 2nd issue (when explicit synchronize is used, but not the 1st one, when async copy should not require synchronization at all, as from PyTorch point of view it is done in the context of the same stream.

2024-11-14 22:46 UTC, qqaatw commented
I think we need

1. to address the second issue mentioned here: https://github.com/pytorch/pytorch/issues/139550#issuecomment-2477020067. A simple solution would be: before replace `_prevCommandBuffer` with `_commandBuffer`, we check whether the previous command buffer has been committed. If so, wait for it and then dispose.

https://github.com/pytorch/pytorch/blob/891ba2ec8a3e2e71137fab4a8e91940a19c8272b/aten/src/ATen/mps/MPSStream.mm#L131-L133

``` c++
if (!_enableCommitAndContinue) {
    if (_prevCommandBuffer) {
      // the previous command buffer (if exists) has already been committed,
      // so we just wait until it's completed and then dispose it.
      [_prevCommandBuffer waitUntilCompleted];
      [_prevCommandBuffer release];
      _prevCommandBuffer = nil;
    }
   _prevCommandBuffer = _commandBuffer; 
}
```

2. testing to prevent regression.

2024-11-18 21:18 UTC, qqaatw commented on test/test_mps.py
> +    def test_sync(self, device="mps", dtype=torch.float):
`dtype` is unused.

2024-11-19 22:32 UTC, malfet approved these changes

2024-11-19 22:32 UTC, kulinseth approved these changes

2024-11-19 22:32 UTC, malfet approved these changes

2024-11-19 22:34 UTC, malfet commented
@pytorchbot merge -f "LGTM"

2024-11-19 23:08 UTC, malfet commented
@pytorchbot merge -f "Lint + MPS tests are green"

2024-11-21 21:54 UTC, malfet commented
@pytorchbot revert -m "It causes deadlocks when I try to run something benchmark from  https://github.com/pytorch/pytorch/pull/127242" -c nosignal

2024-11-21 22:06 UTC, malfet commented
If this change is landed, running something like
```python
import torch
from timeit import default_timer
from torch.utils.benchmark import Measurement, Timer


def bench_cross(
    m,
    dtype=torch.float32,
    device: str = "cpu",
) -> Measurement:
    setup = f"""
     x = torch.rand({m}, 3, dtype={dtype}, device="{device}")
     y = torch.rand({m}, 3, dtype={dtype}, device="{device}")
    """

    t = Timer(
        stmt="torch.cross(x, y);torch.mps.synchronize()", setup=setup, language="python", timer=default_timer
    )
    return t.blocked_autorange()


if __name__ == "__main__":
    torch.set_num_threads(1)
    print(bench_cross(1024, device='mps'))
```

Causes a deadlock with the following backtrace
```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00000001aa919084 Metal`pthread_cond_wait + 12
    frame #1: 0x00000001aa78b1b4 Metal`-[_MTLCommandBuffer waitUntilCompleted] + 84
    frame #2: 0x00000001032bf358 libtorch_python.dylib`torch::mps::MPSModule_deviceSynchronize(_object*, _object*) + 40
    frame #3: 0x0000000100e94c20 Python`cfunction_vectorcall_NOARGS + 100
    frame #4: 0x0000000100e389b8 Python`PyObject_Vectorcall + 92
    frame #5: 0x0000000100f61e38 Python`_PyEval_EvalFrameDefault + 19040
    frame #6: 0x0000000100f5d180 Python`PyEval_EvalCode + 200
    frame #7: 0x0000000100fcd1a4 Python`run_eval_code_obj + 104
    frame #8: 0x0000000100fccbe4 Python`run_mod + 168
    frame #9: 0x0000000100fcb518 Python`pyrun_file + 164
    frame #10: 0x0000000100fca854 Python`_PyRun_SimpleFileObject + 256
    frame #11: 0x0000000100fca4e8 Python`_PyRun_AnyFileObject + 80
    frame #12: 0x0000000100ff2028 Python`pymain_run_file_obj + 164
    frame #13: 0x0000000100ff1ce4 Python`pymain_run_file + 72
    frame #14: 0x0000000100ff0f74 Python`Py_RunMain + 988
    frame #15: 0x0000000100ff1564 Python`pymain_main + 304
    frame #16: 0x0000000100ff1604 Python`Py_BytesMain + 40
    frame #17: 0x000000019f630274 dyld`start + 2840
```

2024-11-21 22:08 UTC, malfet requested changes
Before next attempt to land it, please provide a quick description why it was causing the deadlock

2024-11-21 22:24 UTC, malfet commented
A much simpler reproducer (going to turn it into a regression test)
```python
import torch
y=torch.nextafter(torch.ones(1024, device='mps'), torch.zeros(1024, device='mps'))
torch.mps.synchronize()
torch.mps.synchronize()
```

2024-11-21 22:34 UTC, qqaatw reviewed
I couldn't repro with Nikita's scripts though.

2024-11-21 22:34 UTC, qqaatw commented on aten/src/ATen/mps/MPSStream.mm
> +  [_commandBuffer commitAndContinue];
I guess after this point we should check if the `rootCommandBuffer`'s status is `committed`. If so, then wait until completed.

2025-01-07 17:53 UTC, skotapati commented
I'm no longer able to repro this issue on current main, even when putting the system under heavy load or using a very large tensor, which repro'd the issue reliably earlier. I'll try to figure out why the deadlock occurred and how it was resolved, but other than that I think this should be ready to merge

2025-04-07 21:35 UTC, closed without merging