[AOTI XPU] Add XPUStreamGuard for XPU which is necessary for AOTI.
pytorch/pytorch pull request #140819
Opened 2024-11-15 16:14 UTC by etaf

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #140686
* #140664
* #140269
* __->__ #140819
* #140268
* #135320
* #135318

This PR created XPUStreamGuard instead of reuse StreamGuard for the following reason:
1.  it can be profitable to replace some interfaces with refined types (e.g., return XPUStream instead of Stream) https://github.com/pytorch/pytorch/blob/e2e67a010ac359899e24cebcbd04337831d10b9b/c10/core/DeviceGuard.h#L188C1-L200C53 
2. `XPUStreamGuard`/`CudaStreamGuard` set the guarded stream as current stream which is necessary in AOTI, but `StreamGuard` not

2024-11-20 14:29 UTC, desertfire approved these changes

2024-11-21 02:33 UTC, guangyey requested changes
Please don't introduce `XPUStreamGuard`. Use `c10::StreamGuard` instead.

2024-11-21 02:35 UTC, etaf commented
> Please don't introduce `XPUStreamGuard`. Use `c10::StreamGuard` instead.

Can you check the PR description?

2024-11-21 02:47 UTC, guangyey commented
> Can you check the PR description?

> it can be profitable to replace some interfaces with refined types (e.g., return XPUStream instead of Stream

You can use c10::Stream to construct `XPUStream`.

> XPUStreamGuard/CudaStreamGuard set the guarded stream as current stream which is necessary in AOTI, but StreamGuard not

No, `StreamGuard` has the same functionality.

2024-11-23 15:50 UTC, closed without merging