Add facility to run dynamo UTs for non-cuda devices
pytorch/pytorch pull request #140929
Opened 2024-11-18 04:54 UTC by ankurneog

This is in line with changes introduced with https://github.com/pytorch/pytorch/pull/130714, additional files are included to support non-cuda devices.

2024-11-22 15:08 UTC, ankurneog commented
@anijain2305 : Can you please help with the review and approval , this is in lines of https://github.com/pytorch/pytorch/pull/130714
Thanks

2024-12-03 06:09 UTC, ankurneog commented
@pytorchbot  rebase

2024-12-11 05:10 UTC, ankurneog commented
@anijain2305  : Gentle reminder, can you please help with the approval. Thanks !

2024-12-16 04:37 UTC, ankurneog commented
@anijain2305  :  Can you please help with the approval ? thanks

2024-12-18 10:19 UTC, ankurneog commented
@pytorchbot  rebase

2025-01-17 03:27 UTC, ankurneog commented
Hello @kwen2501 , @guangyey , @anijain2305 , @albanD  : can anyone of you please help with this approval, its been pending for long. Thank you.

2025-01-17 06:13 UTC, guangyey commented on test/dynamo/test_activation_checkpointing.py
> +instantiate_device_type_tests(
I think you need to refactor the logic of `instantiate_device_type_tests`, otherwise it will not work for other devices except `CUDA`, `MPS`, and `XPU`.

2025-01-17 07:05 UTC, kwen2501 approved these changes
LGTM. @anijain2305 @angelayi @ydwu4 @tugsbayasgalan please review to confirm, thanks!

2025-01-17 09:36 UTC, EikanWang requested changes
In general, it is fine to add device information to the test cases for flexibility. However, the `only_for` of `instantiate_device_type_tests` does not align with the original semantics. It does not sever other devices. For example, it cannot support `privateuse1` backend

2025-01-17 09:36 UTC, EikanWang commented on test/dynamo/test_activation_checkpointing.py
> +instantiate_device_type_tests(
Agree with Guangye. It does not make sense to skip other devices.

2025-01-17 09:36 UTC, EikanWang commented on test/dynamo/test_backends.py
> +
ditto

2025-01-17 09:40 UTC, ankurneog commented on test/dynamo/test_activation_checkpointing.py
> +instantiate_device_type_tests(
Its the responsibility teams from other accelerator to ensure support is available. This change merely adds the generalization aspects, so that tests are flexible enough to run on other accelerators ( instead of cuda alone)

2025-01-17 09:45 UTC, ankurneog commented
> In terms of the landed #130714, it introduced the similar issue. We need to track it and refine the test case by removing `only_for` or extending `only_for`.

These were running for "only cuda" till now, if other accelerators want the support they can verify and add on to the list

2025-01-17 10:12 UTC, guangyey commented on test/dynamo/test_activation_checkpointing.py
> +instantiate_device_type_tests(
I see, refer to https://github.com/pytorch/pytorch/blob/dbed747aae223d53ca4e22fe45c24d1d9a8b4432/torch/testing/_internal/common_device_type.py#L833, so far `instantiate_device_type_tests` will work only for `CUDA`, `MPS`, `XPU` and `HPU`. It should not work for privateuser1, cc @FFFrog @egienvalue

2025-01-17 14:50 UTC, EikanWang commented
I do not think it is a general design. Per my understanding, it is HPU-bias. Let's focus on the HPU enabling rather than limiting the scope `cuda` and `hpu`.

> @EikanWang : Note that these tests were written only for cuda , the PR here removes that and generalizes it for other accelerators, if other accelerators support the TC, they can add on to the list. hope the intent is clear

Actually, not. For example, https://github.com/pytorch/pytorch/blob/main/test/dynamo/test_activation_checkpointing.py#L1116 works for CPU as well. why does this PR limit the case to CUDA?

2025-01-17 15:18 UTC, ankurneog commented
@EikanWang : The CPU TC related comment is a "valid" one and will be addressed but the general device related  comment is unacceptable . This is towards a goal for device abstraction in the UTs. The scheme is already followed in all ops related modules eg : test_ops.py and most recently added for FSDP and D tensor as well. I would  request @albanD  to moderate here. Thanks

2025-01-17 15:23 UTC, EikanWang commented on test/dynamo/test_activation_checkpointing.py
>      @unittest.skipIf(IS_WINDOWS, "torch.compile doesn't work with windows")
This case serves the CPU as well. However, `only_for("cuda", "hpu")` skips it.

2025-01-17 15:42 UTC, EikanWang commented
> @EikanWang : The CPU TC related comment is a "valid" one and will be addressed but the general device related comment is unacceptable . This is towards a goal for device abstraction in the UTs. The scheme is already followed in all ops related modules eg : test_ops.py and most recently added for FSDP and D tensor as well. I would request @albanD to moderate here. Thanks

@ankurneog , I agreed with that to use `instantiate_device_type_tests` to support different devices. My point is `only_for` may not align with the original semantics.

- `only_for("cuda", "hpu")` skips the test cases like `test_compile_selective_checkpoint_parametrization` and `test_compile_selective_checkpoint_invalid_context`
- `only_for("cuda", "hpu")` intends to enable `cuda` and `hpu`. However, most of the test cases are decorated as `require_cuda`. `hpu` should not work as expected as most test cases will be skipped.

2025-01-17 16:03 UTC, guangyey commented on test/dynamo/test_activation_checkpointing.py
> +instantiate_device_type_tests(
I think this is acceptable. If other devices want to support it, `instantiate_device_type_tests` will need to be refactored.

2025-01-17 16:06 UTC, guangyey commented on test/dynamo/test_activation_checkpointing.py
>      @requires_cuda
@ankurneog I agreed with @EikanWang, I think here we need to remove `@requires_cuda`, otherwise, it is still CUDA-specific.

2025-01-17 16:23 UTC, ankurneog commented on test/dynamo/test_activation_checkpointing.py
>      @requires_cuda
Yes , I agree to that part. Thanks

2025-01-17 17:14 UTC, ankurneog commented on test/dynamo/test_activation_checkpointing.py
>      @requires_cuda
@guangyey  , @EikanWang  : There is a catch here , i kept the ```requires_cuda``` this for a reason 
requries_cuda is defined as follows : 
```requires_cuda = unittest.skipUnless(HAS_CUDA, "requires cuda")```
And HAS_CUDA is 
```HAS_CUDA = torch.cuda.is_available() and HAS_TRITON```

Now if we remove this check the CI fails as it don't skip if the device is not triton supported. 
Some cleanup is required here, like decoupling Triton and Cuda support. In the meantime we can leave it as is. Since the original functionality is unchanged.

2025-01-17 17:16 UTC, ankurneog commented on test/dynamo/test_activation_checkpointing.py
> +    @skipIfHpu
I will remove the skipIfHpu. the reason for requires_cuda decorator is listed in my previous comment. I had originally removed the requires_cuda decorator, but the CI failed. hence this needs to be kept. Some more refactor for such cases are required. In the meantime we can push this as is since the original functionality is unchanged.

2025-01-17 17:21 UTC, ankurneog commented
> > @EikanWang : The CPU TC related comment is a "valid" one and will be addressed but the general device related comment is unacceptable . This is towards a goal for device abstraction in the UTs. The scheme is already followed in all ops related modules eg : test_ops.py and most recently added for FSDP and D tensor as well. I would request @albanD to moderate here. Thanks
> 
> @ankurneog , I agreed with that to use `instantiate_device_type_tests` to support different devices. My point is `only_for` may not align with the original semantics.
> 
> * `only_for("cuda", "hpu")` skips the test cases like `test_compile_selective_checkpoint_parametrization` and `test_compile_selective_checkpoint_invalid_context`
> * `only_for("cuda", "hpu")` intends to enable `cuda` and `hpu`. However, most of the test cases are decorated as `require_cuda`. `hpu` should not work as expected as most test cases will be skipped.

@EikanWang  , @guangyey  : Please see my comment on the  reason for inclusion of  ```@requires_cuda``` ,  the decorator ultimately checks for Triton capable NVIDIA HW, ( this needs to be decoupled eventually) . Hence the CI fails. 
we can clean this up later after modifying the whole logic for requires_cuda. in the meantime we can leave this as such, since the original functionality is unchanged.

2025-01-17 17:30 UTC, ankurneog commented on test/dynamo/test_activation_checkpointing.py
>      @unittest.skipIf(IS_WINDOWS, "torch.compile doesn't work with windows")
we cannot remove the requires_cuda here as stated due to the Triton HW dependency. We can clean it up as part of a different PR. I have remove the skipIfHpu

2025-01-17 17:31 UTC, ankurneog commented on test/dynamo/test_activation_checkpointing.py
>      @requires_cuda
Have removed ```skipIfHpu``` which was introduced before the CI failure.

2025-01-18 01:13 UTC, EikanWang approved these changes

2025-01-18 01:15 UTC, EikanWang commented
@ankurneog , I just run the CI. Let's wait for the CI signal.

2025-01-20 01:24 UTC, guangyey commented on test/dynamo/test_activation_checkpointing.py
>      @requires_cuda
Thanks for your explanation.

2025-01-20 01:28 UTC, guangyey approved these changes

2025-01-20 03:46 UTC, ankurneog commented
@pytorchbot merge

2025-01-20 05:56 UTC, closed without merging