Update XPU C Shim Header
pytorch/pytorch pull request #141086
Opened 2024-11-20 01:36 UTC by ratnampa

The windows XPU builds are failing: https://github.com/pytorch/pytorch/actions/runs/11922274722/job/33228175750 
due to recent PR merge with changes in fallback ops: https://github.com/pytorch/pytorch/commit/34e420519df9c711ac997888470022cd7c4a90f6

This PR updates the XPU C Shim header file to overcome these build failures.

2024-11-20 02:21 UTC, etaf approved these changes

2024-11-20 02:23 UTC, EikanWang approved these changes

2024-11-20 06:43 UTC, jansel requested changes
Failing tests?

2024-11-20 06:49 UTC, etaf commented
> Failing tests?

Hi, @jansel the failed job [xpu / linux-jammy-xpu-2025_0-py3.9 / test (default, 1, 4, linux.idc.xpu)](https://hud.pytorch.org/pr/pytorch/pytorch/141086#33239534178) ([gh](https://github.com/pytorch/pytorch/actions/runs/11925422585/job/33239534178)) is known issue at #140917  and is fixed in PR #140916  (It's blocked by this PR to fix the build issue)


and the [Lint / lintrunner-noclang / linux-job](https://hud.pytorch.org/pr/pytorch/pytorch/141086#33237484419) ([gh](https://github.com/pytorch/pytorch/actions/runs/11925056010/job/33237484419))
>>> Lint for test/test_nestedtensor.py:

should be non related issue because this PR did not change the file test/test_nestedtensor.py.

2024-11-21 06:08 UTC, etaf commented
@pytorchbot rebase

2024-11-21 20:08 UTC, dvrogozh reviewed
@ratnampa : I suggest to update PR description and commit message by adding links to issue (#141268) and 2 commits (34b2165bdb5 and 34e420519df) which caused this issue:
```
Fixes: #141268
Fixes: 34b2165bdb5 ("Insert aten.add into fallback_ops...")
Fixes: 34e420519df ("[Reland] dont decompose baddbmm (#141045)")
```

2024-11-21 21:11 UTC, malfet approved these changes

2024-11-21 21:21 UTC, dvrogozh approved these changes

2024-11-21 22:20 UTC, jansel approved these changes

2024-11-22 00:51 UTC, desertfire approved these changes

2024-11-22 02:12 UTC, guangyey commented
@pytorchbot rebase

2024-11-22 02:49 UTC, guangyey commented
@pytorchbot rebase -b main

2024-11-22 02:58 UTC, EikanWang commented on torch/csrc/inductor/aoti_torch/generated/c_shim_xpu.h
> +AOTI_TORCH_EXPORT AOTITorchError aoti_torch_xpu_add_Scalar(AtenTensorHandle self, double other, double alpha, AtenTensorHandle* ret0);
@dvrogozh `aten.add.Tensor` can be well supported by the Inductor. We do not need to fall back to Aten.

2024-11-22 03:14 UTC, EikanWang commented
@pytorchbot rebase

2024-11-22 03:46 UTC, guangyey commented
@pytorchbot rebase -b viable/strict

2024-11-22 05:20 UTC, EikanWang commented
The failure, `AttributeError: module 'distutils' has no attribute '_msvccompiler'`, is irrelevant with this PR. We reproduced the failure - https://github.com/pytorch/pytorch/actions/runs/11966075707/job/33361111091#step:11:493. We have filed an issue - https://github.com/pytorch/pytorch/issues/141319 and submitted a PR https://github.com/pytorch/pytorch/pull/141318 to fix it.

Since this PR is critical to address the AOTI-XPU CI failure, we will land this PR first if there are no other failures.

2024-11-22 06:58 UTC, etaf commented on torch/csrc/inductor/aoti_torch/generated/c_shim_xpu.h
> +AOTI_TORCH_EXPORT AOTITorchError aoti_torch_xpu_add_Scalar(AtenTensorHandle self, double other, double alpha, AtenTensorHandle* ret0);
@dvrogozh @EikanWang ,  Comparing with `aten.add.Scalar`, the `aten.add.Tensor` is registered the torch-xpu-ops as an out-of-tree op, and it's aoti API is generated in `torch/csrc/inductor/aoti_torch/generated/extend/c_shim_xpu.h`.

2024-11-22 07:28 UTC, guangyey commented
"Unrelated failures"
@pytorchbot merge -i

2024-11-22 08:49 UTC, chuanqi129 commented
@pytorchbot merge -i viable/strict

2024-11-22 08:49 UTC, chuanqi129 commented
@pytorchbot merge -b viable/strict

2024-11-22 08:50 UTC, chuanqi129 commented
@pytorchbot rebase -b viable/strict

2024-11-22 08:56 UTC, guangyey commented
@pytorchbot rebase -b main

2024-11-22 15:32 UTC, desertfire commented on torch/csrc/inductor/aoti_torch/generated/c_shim_xpu.h
> +AOTI_TORCH_EXPORT AOTITorchError aoti_torch_xpu_add_Scalar(AtenTensorHandle self, double other, double alpha, AtenTensorHandle* ret0);
> @dvrogozh `aten.add.Tensor` can be well supported by the Inductor. We do not need to fall back to Aten.

Annoyingly, it was needed for complex number.

2024-11-22 21:36 UTC, atalman commented
@chuanqi129 please fix lint. The rest of the errors seems to be not related

2024-11-23 04:27 UTC, EikanWang commented
@atalman , the lint error is not related with this PR as this PR does not touch the rnn.py.

2024-11-23 08:57 UTC, etaf commented
> @chuanqi129 please fix lint. The rest of the errors seems to be not related

Hi, @atalman , The lint error happens on main branch, seems not related to this PR:
![image](https://github.com/user-attachments/assets/b063c0a9-91ab-4473-aace-533edef05527)

2024-11-23 10:32 UTC, guangyey commented
@pytorchbot rebase

2024-11-23 10:35 UTC, guangyey commented
We will rebase this PR to the latest `viable/strict` branch and land this PR once there are no other failures.

2024-11-23 13:37 UTC, guangyey commented
@pytorchbot rebase

2024-11-24 09:03 UTC, EikanWang commented
@pytorchbot merge

2024-11-24 12:24 UTC, closed without merging