support input mutations on tangents
pytorch/pytorch pull request #141131
Opened 2024-11-20 15:26 UTC by bdhirsh

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #141131

2024-11-25 15:27 UTC, zou3519 approved these changes

2024-12-14 00:52 UTC, albanD requested changes, later dismissed
I'm quite confused. This is explicitly forbidden by autograd :) 
Doing this in eager will lead to undefined behavior, so I don't think you need to handle it in compile :D

2024-12-14 00:54 UTC, ngimel commented
Mutating tangents is a dangerous pattern, and I'm not even sure we should support it in eager. Imagine you have 
```
z = x + y
```
where `x` is output of a custom autograd function. In backward, `x` and `y` will get references to the same grad, and then `x` will secretly modify it. I can imagine that a lot of networks actually don't have this pattern and can modify gradOutputs without issues, but for those that do debugging this will be painful.

2025-01-03 20:18 UTC, bdhirsh commented
@yanboliang (and maybe @albanD) what do you think, given Natalia and Alban's comments above? I guess we have to reconcile "mutating tangents in the backward is undefined behavior" with "...but megatron does it". Would it be possible to get megatron not to do this?

fwiw, this is the autograd.Function example that Yanbo linked ([here](https://github.com/pytorch/pytorch/issues/141111#issue-2674527127)):
```
class Foo(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        return x.clone(), x.clone()

    @staticmethod
    def backward(ctx, grad1, grad2):
        return grad1.copy_(grad2)
```

2025-01-05 03:31 UTC, yanboliang commented
@bdhirsh More context at https://github.com/pytorch/pytorch/issues/141111#issuecomment-2571487271

2025-01-09 19:40 UTC, bdhirsh commented
From composability discussion: it was agreed that:

(1) the "silent correctness" issue around mutating tangents exists specifically in the case where a tangent tensor gets passed to multiple grad_fn's, and is mutated in one of them. We can beef up autograd to track mutation on tangents using version counters, and figure out how to error only in the case where we know there will be silent correctness (which should not be the case for megatron, at least in the common transformer architectures today)

(2) We need someone to sign up for that work, but in the meantime we can land this PR to unblock support on the compile side

2025-01-16 16:10 UTC, bdhirsh commented
@pytorchbot merge

2025-02-13 17:41 UTC, Skylion007 commented
@pytorchbot merge

2025-02-13 17:48 UTC, closed without merging