[Build] Add `COMMIT_SHA` to `caffe2::GetBuildOptions`
pytorch/pytorch pull request #141313
Opened 2024-11-22 02:00 UTC by malfet

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Using the same `tools/generate_torch_version.py` script

It's already available on Python level, but not on C++ one

2024-11-22 05:00 UTC, ezyang requested changes
Won't this force a recompile time every time you do a commit? Header seems bad. You need to bong it in at the very end of the build process.

2024-11-22 15:20 UTC, malfet commented
> Won't this force a recompile time every time you do a commit? Header seems bad. You need to bong it in at the very end of the build process.

No, it would not, this header will be regenerated if and only if one runs cmake. So it might be stale during the incremental builds, but will be correct during the cold build, which are all our CD builds are.

2024-11-22 21:05 UTC, ezyang approved these changes

2024-11-25 20:43 UTC, malfet commented
@malfet has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D66468257).

2024-11-26 00:09 UTC, closed without merging