Fix windows ci build python env issue
pytorch/pytorch pull request #141318
Opened 2024-11-22 03:43 UTC by chuanqi129

Fixes #ISSUE_NUMBER

2024-11-22 18:00 UTC, malfet commented on .ci/pytorch/win-test-helpers/build_pytorch.bat
> +call pip list
Well, I think it's interesting to see what's present in the AMI

2024-11-22 18:01 UTC, malfet approved these changes

2024-11-22 18:01 UTC, malfet commented
@pytorchot merge -f "This sounds OK to me"

2024-11-22 18:04 UTC, malfet requested changes
Hmm, can you please elaborate why this only surfaces for XPU bulids, but not for the regular torch ones?

2024-11-22 19:03 UTC, chuanqi129 commented on .ci/pytorch/win-test-helpers/build_pytorch.bat
> +call pip list
Yes, just as @malfet said

2024-11-22 19:14 UTC, chuanqi129 commented
> Hmm, can you please elaborate why this only surfaces for XPU builds, but not for the regular torch ones? Instead of pinning distutils, can't we get rid of deprecated path and remove the constraint?

Hi @malfet, thanks for your review and comments. I'm also not sure why just xpu windows build met this issue, because I don't where those required packages installed into the Windows runner env. The only thing I can check is that the setuptools version is [72.1.0](https://github.com/pytorch/pytorch/actions/runs/11977411789/job/33395239331?pr=141318#step:11:302) , but the xpu used runner is [75.1.0](https://github.com/pytorch/pytorch/actions/runs/11977412753/job/33395232288#step:11:409). And I also agree with your suggestion to remove the deprecated path and move forward, I think we can have another PR to do it. And this PR change is safe enough to make sure such issue won't appear in the future. I suggest to land this PR first to unblock XPU CI test for other PRs. How do you think?

2024-11-23 10:38 UTC, guangyey commented
@pytorchbot rebase

2024-11-24 13:41 UTC, guangyey commented
@pytorchbot rebase

2024-11-25 03:44 UTC, chuanqi129 commented
Due to the original issue https://github.com/pytorch/pytorch/issues/141319 has been fixed by https://github.com/pytorch/pytorch/pull/141363, I have updated the PR title and description. @malfet @huydhn do you think whether this is a reasonable change?

2025-02-24 00:49 UTC, closed without merging