Add README for torch._inductor.runtime
pytorch/pytorch pull request #141492
Opened 2024-11-25 15:37 UTC by ezyang

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #141492
* #141491

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

2024-11-25 19:02 UTC, jansel requested changes

2024-11-25 20:15 UTC, ezyang commented on torch/_inductor/runtime/README.md
> +still plenty of torch imports in this folder.
I took this suggestion and reworded a little bit of it

2024-11-25 21:58 UTC, jansel approved these changes

2024-11-26 14:41 UTC, ezyang commented
@pytorchbot merge -f "unrelated failures"

2024-11-26 14:43 UTC, closed without merging