Fix a bug for wrong stride in fake tensor
pytorch/pytorch pull request #141427
Opened 2024-11-23 09:13 UTC by ywq880611

Fixes #141426

Please see details in the issue.

2024-11-25 19:05 UTC, jansel requested changes
How are the strides becoming wrong in the first place?  Can we refactor the meta kernel to use the same code as eager to set the strides of the output?

2024-11-26 00:50 UTC, ywq880611 commented
It seems the `CUFFT` lib requests to batch all dimensions not in the dim list together for output to improve performance.

Please see the code:
https://github.com/pytorch/pytorch/blob/5d7c3701e40374113921771097ebc65d9c2876bf/aten/src/ATen/native/cuda/SpectralOps.cpp#L172-L213

For example, if the output tensor's shape is `(5, 3, 6)` and stride is `(18, 6, 1)`. if we do `fft_c2c` for its second dim, its shape will be modified as  `(30, 3)` (30 = 5 * 6), and stride is `(3, 1)`.

So I suspected we may have to manually update the stride for the tensor when we back from the `CUFFT` lib invocation.

2024-11-26 20:06 UTC, jansel commented
We should make the meta function correctly model which bakend will be chosen.

2024-11-30 02:53 UTC, jansel commented
Based on that I think the implementation of `_prims._conj_physical_meta` is wrong. It should not call `utils.compute_elementwise_output_strides(input)`.   It is the job of the meta function to return the correct strides.

2024-12-02 10:56 UTC, ywq880611 commented
> Based on that I think the implementation of `_prims._conj_physical_meta` is wrong. It should not call `utils.compute_elementwise_output_strides(input)`. It is the job of the meta function to return the correct strides.

Uh... Sorry, I'm still not very clear about why you thought `_prims._conj_physical_meta` is wrong, because I understood that it takes an input (shape as `(5, 3, 6)`, stride as `(18, 1, 3)`), and returns a output tensor(shape as `(5, 3, 6)`, stride as `(18, 1, 3)`). Both size and stride for output is same as its input, did that not meet our expectation? Or did you mean that we would like to return a tensor with stride as `(18, 6, 1)` here, then modify the stride in some else place latter?

I'm not sure whether my understand is correct or not, but I thought the root cause may be here:
https://github.com/pytorch/pytorch/blob/4ae1c4cbb59deeae2aabc61ea1e02cf1d5992812/torch/_prims_common/wrappers.py#L315-L321
We copy the size but not stride here, hence it returns a tensor with stride as `(18, 6, 1)`.

2024-12-02 16:45 UTC, jansel commented
> Both size and stride for output is same as its input, did that not meet our expectation?

No, both the size and the stride should be the same as *running the kernel with real tensors*.  Meta functions are required to model *both* strides and sizes accurately.  If _conj_physical returns a different stride than its input, then the meta function must do the same.

2024-12-03 10:46 UTC, ywq880611 commented
For this case with `cuda` as device (`cpu` is same):

```
import torch

t = torch.zeros((5, 3, 6), dtype=torch.complex128, device='cuda')

def func(a):
    print("a:")
    print("size:", a.shape)
    print("stride:", a.stride())
    b = torch.ops.aten._fft_c2c.default(a, [1], 1, True)
    print("b:")
    print("size:", b.shape)
    print("stride:", b.stride())
    c = torch.ops.aten._conj_physical.default(b)
    print("c:")
    print("size:", c.shape)
    print("stride:", c.stride())
    return c

func(t)
```

its output is:
```
a:
size: torch.Size([5, 3, 6])
stride: (18, 6, 1)
b:
size: torch.Size([5, 3, 6])
stride: (18, 1, 3)
c:
size: torch.Size([5, 3, 6])
stride: (18, 1, 3)
```

For the `_conj_physical` _running with a real tensor_ (stride as `(18, 1, 3)`) will also return an output tensor with stride as `(18, 1, 3)`, it was aligned with `_prims._conj_physical_meta`.

I suspected the reason why we see stride as `(18, 6, 1)` is that it was resized after calling the meta function.

2024-12-06 05:12 UTC, jansel commented
> I suspected the reason why we see stride as `(18, 6, 1)` is that it was resized after calling the meta function.

Where is this resize coming from?

2024-12-07 03:12 UTC, ywq880611 commented
It's from here:

https://github.com/pytorch/pytorch/blob/4ae1c4cbb59deeae2aabc61ea1e02cf1d5992812/torch/_prims_common/wrappers.py#L315-L321

The `result` variable in the snippet came from the meta function, its stride is `(18, 1, 3)`, then the function will take `out` as return value, so it copy the `shape` from `result` to `out`, but not copy the `stride`, so after this method, the stride of `out` is `(18, 6, 1)` (because we just copy shape only, the `(18, 6, 1)` was inference with shape of `(5, 3, 6)`).

If you thought it's the root cause, we could fix it like this [commit](https://github.com/pytorch/pytorch/pull/141427/commits/9e62eb01c2228cb2dac4cd82b151b74a16b343e9#).

2024-12-07 05:37 UTC, jansel commented
The example you gave doesn't seem to have an `out=` arg, so where is that out coming from?

We should change the FakeTensor behavior to match eager, rather than changing eager to match the FakeTensor (and introducing a copy).

2024-12-08 04:35 UTC, ywq880611 commented
Yes, I'm also curious about where the `out` came from, but there is a weird call stack, I couldn't found where the `out` came from in python side, so I suspect it may be from cpp side, here are some code snippets:

1) It will call `_conj_physical`
https://github.com/pytorch/pytorch/blob/2682e5e0d48a8200c1672b6a42250d3c8de44190/aten/src/ATen/native/UnaryOps.cpp#L619-L624
At this place, there is just `self` tensor.
2) then it will call `unary_op_impl`
https://github.com/pytorch/pytorch/blob/2682e5e0d48a8200c1672b6a42250d3c8de44190/aten/src/ATen/native/UnaryOps.cpp#L461-L465
We allocate a empty tensor here: `Tensor result = at::empty({0}, self.options()); `
**I suspect it's the source for the `out` came from in the python code.**

I tried to update the [PR](https://github.com/pytorch/pytorch/pull/141427/commits/2d5ed4f42e5645b501d71433dfaeca44cc08d242) to assign a tensor with same shape and stride for the `_conj_physical`, WDYT?

2024-12-08 23:05 UTC, jansel commented
How is the out tensor in C++ making the FakeTensor code in `torch/_prims/__init__.py` incorrect?

I'll repeat, we should change the FakeTensor behavior to match the non-FakeTensor behavior.

2024-12-09 16:24 UTC, jansel commented
> 2. Both copy size and stride from fake result tensor to out tensor, like this PR.

This one seems closer to correct, since it is fixing the FakeTensor behavior (rather than the non-FakeTensor behavior).  Though I am still confused as to where `out=` is coming from.

Can you try changing your code to:
```
c = torch.ops.aten._conj_physical(b, out=torch.empty_like(b))
```
If you actually pass a real `out=` value, does the eager mode op respect the original strides?  Or does it mutate the strides like you are doing with `as_strided_`?

Whatever we do should be correct both with and without the `out=` arg.  I worry this solution will make the `out=` version incorrect.

Also, this wrapper in wrapper.py is used in many places and this behavior might not apply to all ops.  Another solution would be to remove the wrapper from _conj_physical_meta.  This will let you define the `out=` behavior yourself to match eager mode.

2024-12-10 12:44 UTC, ywq880611 commented
I understand the reason why there is an `out` even we didn't explicitly passed it is that `conj_physical` was implement based on `conj_physical_out`, which means we must pass two arguments to `conj_physical_out`, even we didn't explicitly pass an `out` tensor to `conj_physical`, there is a code snippet for `conj_physical` (`torch/csrc/autograd/generated/python_torch_functions_2.cpp` from generated files, couldn't be linked to repo file):
```cpp
  if (_r.isNone(1)) {
    // aten::conj_physical(Tensor self) -> Tensor
    
    auto dispatch_conj_physical = [](const at::Tensor & self) -> at::Tensor {
      pybind11::gil_scoped_release no_gil;
      return self.conj_physical();
    };
    return wrap(dispatch_conj_physical(_r.tensor(0)));
  } else {
    // aten::conj_physical.out(Tensor self, *, Tensor(a!) out) -> Tensor(a!)
    
    auto dispatch_conj_physical_out = [](at::Tensor out, const at::Tensor & self) -> at::Tensor {
      pybind11::gil_scoped_release no_gil;
      return at::conj_physical_out(out, self);
    };
    return wrap(dispatch_conj_physical_out(_r.tensor(1), _r.tensor(0)));
  }
```
There are two branches:
1) For the first `if (_r.isNone(1))`, which means there is no explicit `out` argument, so **it will allocate an empty tensor** like `Tensor result = at::empty({0}, self.options());` in `return self.conj_physical();` before it call to `conj_physical_out`.
2) For the else branch, it means **we explicitly pass an `out` tensor** in `return at::conj_physical_out(out, self);`, so **it didn't need to allocate an empty tensor** for it.

As your question about `c = torch.conj_physical(b, out=torch.empty_like(b))`, I tried it, it will go through the 2nd branch mentioned above, so it will return a correct result.

BTW, I update the PR, could you help me run CI again? Thank you!

2024-12-10 17:08 UTC, jansel commented
Can you add a test for this?

I think this new version is subtly wrong.  If you pass an `out=` to `_conj_physical` it will respect the strides of the existing `out=`.

```py
>>> torch.ops.aten._conj_physical(b, out=torch.empty_like(a)).stride()
(18, 6, 1)
>>> torch.ops.aten._conj_physical(b, out=torch.empty_like(b)).stride()
(18, 1, 3)
>>> torch.ops.aten._conj_physical(b, out=torch.empty_strided((5, 3, 6), (1, 5, 15), dtype=torch.complex128, device='cuda')).stride()
(1, 5, 15)
>>> 
```
calling `out.as_strided_()` will discard the existing strides.  Which is only correct in the case that no `out=` is passed.  So it would be better to fix where the default (`out=None`) out is allocated to give that the correct strides.

2024-12-16 13:46 UTC, ywq880611 commented
## Case
Your case is interesting, but I tried it with `meta` device, it seems returns the same results, I tried to debug it and see why it works for `meta` device.
The code looks like:
```
import torch

t = torch.zeros((5, 3, 6), dtype=torch.complex128, device="meta")

def func(a):
    b = torch._fft_c2c(a, [1], 1, True)
    print(torch.ops.aten._conj_physical(b, out=torch.empty_strided((5, 3, 6), (1, 5, 15), dtype=torch.complex128, device='meta')).stride())
    print(torch.conj_physical(b, out=torch.empty_strided((5, 3, 6), (1, 5, 15), dtype=torch.complex128, device='meta')).stride())

func(t)
```

it's output is:
```
(1, 5, 15)
(18, 1, 3)
```
So we could see we got **expected result** from `torch.ops.aten._conj_physical`, but got **unexpected result** from `torch.conj_physical`, here are a simple analysis:

## torch.ops.aten._conj_physical
1) The arguments for `_fn`:
https://github.com/pytorch/pytorch/blob/4ae1c4cbb59deeae2aabc61ea1e02cf1d5992812/torch/_prims_common/wrappers.py#L270-L272
the out seems came from `Tensor result = at::empty({0}, self.options());`, so it's not the out we passed in.
1) At `_fn` it do modify the stride same as input tensor after my modification:
https://github.com/pytorch/pytorch/commit/f7afb5194747ebaaa7d78c595d5eef9afb34bb17#diff-ec5749db5ba92a707aa61e5358775eb5385a2a01ebeed49dd72c70fee979e894L320-L321
Its stride is `(18, 1, 3)` now (same as `b`).
2) After return from the `_fn` function, it seems it will go to a cpp function (in `build/aten/src/ATen/CompositeViewCopyKernels.cpp`):
```
at::Tensor & _conj_physical_out(const at::Tensor & self, at::Tensor & out) {
  auto tmp_output = at::_ops::_conj_physical::call(self);
    resize_out_helper(out, tmp_output);
  copy_arg(out, tmp_output);
  return out;
}
```
There is a `resize_out_helper(out, tmp_output);` to modify its output same as the out `out=torch.empty_strided((5, 3, 6), (1, 5, 15), dtype=torch.complex128, device='cuda')`

To be honest, I'm a little dizzy about the invocation logic between `cpp` and `python` and the logic, but it seems the `resize_out_helper(out, tmp_output);` will keep corretness.

## torch.conj_physical
it' wrong as you said.
1. The arguments for `_fn`:
https://github.com/pytorch/pytorch/blob/4ae1c4cbb59deeae2aabc61ea1e02cf1d5992812/torch/_prims_common/wrappers.py#L270-L272
the `out` have stride as `(1, 5, 15)`, so it's what we passed for the `torch.conj_physical`.
2. It didn't go to the `at::Tensor & _conj_physical_out(const at::Tensor & self, at::Tensor & out)`, so after the `as_stride_` we will get a tensor with wrong stride.

## Bug fix
I tried to fix this bug by checking whether the `out` is an empty tensor or not for `_fn` method, it works for this case, but I'm still not very clear about the mechanism diff between `torch.ops.aten._conj_physical` and `torch.conj_physical`, I guess it was caused by the different call stack and dispatch way of the two method, I will try to investigate it later.

PTAL, thanks!

2024-12-17 05:01 UTC, jansel approved these changes

2024-12-17 05:04 UTC, jansel commented
Thanks, I think this is right now.  Though it might be cleaner to refactor this behavior into `_maybe_resize_out`.

2024-12-17 05:04 UTC, jansel commented
@pytorchbot merge

2024-12-17 12:40 UTC, ywq880611 commented
Thank you for your review! I tried to refactor the `_maybe_resize_out`, PTAL! And I also saw there are some tests failed:
1. [test bot 1](https://github.com/pytorch/pytorch/actions/runs/12353675806/job/34513803983) failed with `Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/ec2-user/actions-runner/_work/pytorch/pytorch/.github/actions/upload-sccache-stats'. Did you forget to run actions/checkout before running your local action?`
2. [test bot 2](https://github.com/pytorch/pytorch/actions/runs/12353675865/job/34513799198?pr=141427) failed with `Item "object" of "Tensor | _T" has no attribute "stride"`.

I have no idea about how to fix them... I suspected the first kind is not related to this PR, and the second kind is related to the change, but I have no idea about how to fix them, any insights would be very appreciated, thanks again!

2024-12-17 17:01 UTC, jansel commented
For those tests, you may need to rebase against the `viable/strict` branch (which only gets updated when upstream tests pass)

It looks like there are some other test failures too though.

2024-12-19 20:46 UTC, jansel requested changes
Looks like this is failing tests

2024-12-24 14:25 UTC, ywq880611 commented
Hi @jansel , merry Christmas!

## Case
There is a case came in my mind, like `torch.conj_physical(b, out=torch.empty(0, dtype=torch.complex128, device='meta')`).

If we pass an explicit `out` argument with `torch.empty(0)`, it will be passed into `_fn`:
https://github.com/pytorch/pytorch/blob/4ae1c4cbb59deeae2aabc61ea1e02cf1d5992812/torch/_prims_common/wrappers.py#L270-L272

## Behavior
We will see an empty tensor for `out` in `_fn`, so we could image there is ambiguity for `out` in `_fn`, it will be either **a tensor form the explicit assignment** or **a tensor from some ops' implement**(like `conj_physical`, it was implement based on `conj_physical_out`, so it will pass an empty `out` tensor even the user didn't pass anything. 

## Solution:
Under such background, we couldn't know whether the `out` in `_fn` is an **user defined behavior** or **some other logic from the ops' implement**, then we couldn't do restride here because we may hurt correctness, there are some potential solution in my mind, like:
1. Don't wrap the ops (like `conj_physical`) with `_fn`.
2. Refactor the current implement of `conj_physical` to make it didn't rely on `conj_physical_out`.

Are these solutions feasible? WDYT? Any suggestion is appreciated! And happy new year :)

2024-12-24 21:39 UTC, jansel commented
I'd be ok updating conj_physical to use empty_like() rather than empty({0}) and no rely on the output resise behavior.

2024-12-26 11:17 UTC, ywq880611 commented
The PR was updated, PTAL, thanks!

2024-12-26 18:48 UTC, jansel requested changes
Looks like you need to remove some xfails to fix CI.

2024-12-30 13:27 UTC, ywq880611 commented
It seems there is a known [issue](https://github.com/pytorch/pytorch/pull/106319), so I tried to remove the `xfail`, PTAL, thanks!

2024-12-30 18:45 UTC, jansel commented
I approved CI, things still seem to be failing

2024-12-31 14:31 UTC, ywq880611 commented
I removed more xfail, could you please help me to run CI again, thanks!

2024-12-31 23:36 UTC, jansel approved these changes

2024-12-31 23:37 UTC, jansel commented
@pytorchbot merge

2024-12-31 23:45 UTC, closed without merging

2025-01-08 11:22 UTC, wizzniu commented on aten/src/ATen/native/UnaryOps.cpp
> +  if (c10::isIntegralType(self.scalar_type(), /*includeBool=*/true)) {
Sry, @ywq880611 @jansel . I am curious why change the dtype of result here(from Int to float)? Doesn't it raise error when calling `at::conj_physical_out(result, self)` in the subsequent code?

2025-01-08 11:29 UTC, wizzniu commented
Before this PR merged, the following code can run normally:
```python
import torch
x = torch.ones((2,3,4), dtype=torch.int, device='mlu')
out_cpu = torch._conj_physical(x)
```
After this PR merged, it would raise error just like: ``RuntimeError: Found dtype Float but expected Int``.

2025-01-08 12:10 UTC, ywq880611 commented on aten/src/ATen/native/UnaryOps.cpp
> +  if (c10::isIntegralType(self.scalar_type(), /*includeBool=*/true)) {
Oops, you're right, I suppose we shouldn't convert type here, I will submit a PR to fix it latter.

2025-01-08 12:25 UTC, ywq880611 commented
Hi @jansel , I'm sorry that I may make some mistake in this PR, I shouldn't convert the data type, here is the new [PR](https://github.com/pytorch/pytorch/pull/144391/files) to fix it, PTAL, thanks!