Remove special handling of torchvision.ops imports in onnx export
pytorch/pytorch pull request #141569
Opened 2024-11-26 13:48 UTC by Bludator

Fixes #141568

2024-11-26 22:24 UTC, justinchuby requested changes, later dismissed
This will remove support for the torch vision ops, right? Is that intended?

2024-11-26 23:05 UTC, justinchuby commented
Ok sorry. I think what should be done instead is to remove "ops." from the get attr line

2024-11-26 23:06 UTC, justinchuby commented on torch/onnx/_internal/exporter/_registration.py
> +        if importlib.util.find_spec("torchvision.ops") is None:
```suggestion
        if importlib.util.find_spec("torchvision") is None:
```

thanks for this change

2024-11-27 01:17 UTC, titaiwangms commented
@justinchuby I tested this locally, and it actually fixes the bug. We do have [torchvision::nms](https://github.com/microsoft/onnxscript/blob/99cf79fd4ab150e3726b36fb3e9104304e203200/onnxscript/function_libs/torch_lib/ops/vision.py#L17). It's the bug in registration that we wrongly registered it under the function nms itself. In [here](https://github.com/titaiwangms/pytorch/blob/605392bd0630df895efac20a27a6a82e70d9b3de/torch/onnx/_internal/exporter/_registration.py#L70), it will register torchvision::nms symbolic function under nms function itself because that's what we get from `return getattr(torchvision.ops, op_name)`. In fact, torchvision ops are accessible the same way as aten ops it seems.

2024-11-27 01:56 UTC, titaiwangms commented
@Bludator Do you mind adding your repro as a test here: https://github.com/titaiwangms/pytorch/blob/main/test/onnx/exporter/test_small_models_e2e.py

2024-11-27 02:48 UTC, justinchuby commented
> @justinchuby I tested this locally, and it actually fixes the bug. We do have [torchvision::nms](https://github.com/microsoft/onnxscript/blob/99cf79fd4ab150e3726b36fb3e9104304e203200/onnxscript/function_libs/torch_lib/ops/vision.py#L17). It's the bug in registration that we wrongly registered it under the function nms itself. In [here](https://github.com/titaiwangms/pytorch/blob/605392bd0630df895efac20a27a6a82e70d9b3de/torch/onnx/_internal/exporter/_registration.py#L70), it will register torchvision::nms symbolic function under nms function itself because that's what we get from `return getattr(torchvision.ops, op_name)`. In fact, torchvision ops are accessible the same way as aten ops it seems.

thank you!

2024-11-27 23:21 UTC, justinchuby reviewed
LGTM if torch.ops.torchvision.* is defined

2024-11-28 00:03 UTC, Bludator commented
> @Bludator Do you mind adding your repro as a test here: https://github.com/titaiwangms/pytorch/blob/main/test/onnx/exporter/test_small_models_e2e.py

Is the torchvision installed in the test environment?

2024-11-28 00:11 UTC, titaiwangms commented
> > @Bludator Do you mind adding your repro as a test here: https://github.com/titaiwangms/pytorch/blob/main/test/onnx/exporter/test_small_models_e2e.py
> 
> Is the torchvision installed in the test environment?

I believe so. We have torchvision [tests](https://github.com/pytorch/pytorch/blob/45ed7c13fafcc16687e4b80c8ab13d2e2834e954/test/onnx/test_pytorch_onnx_onnxruntime.py#L8799) for legacy torchscript exporter.

2024-11-28 00:33 UTC, titaiwangms commented on test/onnx/exporter/test_small_models_e2e.py
> +        torch.onnx.export(VisionModel(), args, dynamo=True)
```suggestion
        onnx_program = torch.onnx.export(VisionModel(), args, dynamo=True)
        onnx_testing.assert_onnx_program(onnx_program)
```

2024-11-28 00:34 UTC, titaiwangms approved these changes
Thanks!

2024-11-28 00:46 UTC, titaiwangms commented
@pytorchbot merge

2024-11-28 01:37 UTC, titaiwangms commented
@pytorchbot merge

2024-11-28 13:35 UTC, Bludator commented
Now it should work, I had broken environment so I didn't properly test it.
@pytorchbot merge

2024-11-28 15:04 UTC, titaiwangms commented
@pytorchbot merge

2024-11-28 18:05 UTC, closed without merging