[AOTI] Clean up temporary files generated by AOTI package loader.
pytorch/pytorch pull request #141773
Opened 2024-11-28 14:21 UTC by etaf

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #141773

Fix #141772

2024-12-02 16:26 UTC, desertfire requested changes

2024-12-02 16:26 UTC, desertfire commented on torch/csrc/inductor/aoti_package/model_package_loader.cpp
>  namespace fs = std::filesystem;
We can't use std::filesystem due to https://github.com/pytorch/pytorch/issues/133437. I know it's annoying, but until you resolve that linking issue, we have to still with the current way.

2024-12-05 15:40 UTC, desertfire commented
@etaf , any follow-up on this one? I will switch all the AOTI unit test to use the new package API, but this PR needs to land first.

2024-12-06 00:45 UTC, etaf commented
> @etaf , any follow-up on this one? I will switch all the AOTI unit test to use the new package API, but this PR needs to land first.

@desertfire thanks, I'm working on it, and will update today.

2024-12-06 01:03 UTC, EikanWang approved these changes

2024-12-06 03:34 UTC, desertfire approved these changes

2024-12-06 11:46 UTC, closed without merging