fix c10::Event UT on XPU backend
pytorch/pytorch pull request #141800
Opened 2024-11-29 10:40 UTC by guangyey

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-11-29 12:58 UTC, EikanWang approved these changes

2024-11-29 12:59 UTC, EikanWang requested changes
pls. fix the failure

2024-12-02 03:05 UTC, EikanWang approved these changes

2024-12-02 08:44 UTC, guangyey commented
@pytorchbot rebase

2024-12-03 01:27 UTC, guangyey commented
"Unrelated failures, we have an issue https://github.com/pytorch/pytorch/issues/141861 to track this failure"
@pytorchbot merge -i

2024-12-03 01:34 UTC, closed without merging