Reduce num_layers to enable autoquant in CI
pytorch/pytorch pull request #141910
Opened 2024-12-02 20:57 UTC by jerryzh168

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #141910

Summary:
original autoquant will require A100-80G to run in CI, but we don't have that right now, so reducing num_layer so that we can
track autoquant in dashboard

Test Plan:
dashboard
https://hud.pytorch.org/benchmark/llms?repoName=pytorch%2Fpytorch

Reviewers:

Subscribers:

Tasks:

Tags:

2024-12-06 18:40 UTC, huydhn approved these changes
LGTM! The model shows up on [the dashboard](https://hud.pytorch.org/benchmark/llms?startTime=Fri%2C%2029%20Nov%202024%2018%3A38%3A57%20GMT&stopTime=Fri%2C%2006%20Dec%202024%2018%3A38%3A57%20GMT&granularity=hour&lBranch=ciflow/inductor-micro-benchmark/141910&lCommit=0b7b6152e629780c61c1636842952421a970756c&rBranch=ciflow/inductor-micro-benchmark/141910&rCommit=e99647c09350e59339e7c4e011d6907c794a01c2&repoName=pytorch%2Fpytorch&modelName=All%20Models&dtypeName=autoquant&deviceName=All%20Devices)

2024-12-06 19:07 UTC, yanboliang approved these changes

2024-12-06 19:09 UTC, yanboliang requested changes, later dismissed
sorry I think we should only reduce num of layers for a particular model, because the perf number is correlated with the num of layers. I'd like to suggest to define a subclass for the ```run_llama2_7b_autoquant``` model, otherwise, we have to adjust all of these per numbers.

2024-12-07 03:46 UTC, jerryzh168 commented
@yanboliang sounds good. I reverted the n_layer changes, seems to be fine

2024-12-07 04:26 UTC, yanboliang approved these changes

2024-12-09 21:37 UTC, jerryzh168 commented
@pytorchbot merge

2024-12-18 00:13 UTC, jerryzh168 commented
Some issues with this right now
running llama-autoquant standalone:
```
Compilation time: 82.14 seconds
Average tokens/sec: 115.20 tokens/sec
Average bandwidth achieved: 1522.33 GB/s
Memory used: 14.99 GB
```


running both int8 llama and llama-autoquant together:
```
Compilation time: 283.86 seconds
Average tokens/sec: 110.52 tokens/sec
Average bandwidth achieved: 1460.47 GB/s
Memory used: 15.01 GB
Loading model Llama-2-7b-chat-hf
Time to load model: 0.14 seconds
Compilation time: 283.28 seconds
Average tokens/sec: 87.44 tokens/sec
Average bandwidth achieved: 1155.46 GB/s
Memory used: 17.52 GB
```

Repro: python benchmark.py

switch between two experiments: https://github.com/pytorch/pytorch/pull/141910/files#diff-5412ff53aeb6bc81cc81dcfb32204983950a098d7fb89fd28bc7876dd862c633R321-R331

2025-03-18 02:06 UTC, closed without merging