Update torch-xpu-ops commit pin
pytorch/pytorch pull request #141949
Opened 2024-12-03 07:00 UTC by xytintel

Update the torch-xpu-ops commit to [f31219](https://github.com/intel/torch-xpu-ops/commit/f312190a927b21caa34f18505cf350faaed6f455), includes:

- Add lazy init for empty_xpu
- Nan propagation for soft_shrink

2024-12-03 23:54 UTC, cpuhrsch approved these changes

2024-12-03 23:54 UTC, cpuhrsch requested changes
@malfet - Do we support updates to third_party this way?

2024-12-04 01:48 UTC, EikanWang approved these changes

2024-12-04 01:54 UTC, EikanWang commented
@cpuhrsch FYI - https://github.com/pytorch/pytorch/pull/120891#pullrequestreview-1929849651

2024-12-05 05:22 UTC, closed without merging