Fix undefined behavior
pytorch/pytorch pull request #142121
Opened 2024-12-05 08:09 UTC by cyyever

Fixes #ISSUE_NUMBER

2024-12-05 08:11 UTC, cyyever commented
@pytorchbot label "topic: not user facing"

2024-12-05 14:21 UTC, ezyang commented
@swolchok WDYT, should be willing to add another predictable branch here?

2024-12-11 18:51 UTC, swolchok commented
> @swolchok WDYT, should be willing to add another predictable branch here?

ideally get_data is inlined and we don't actually pay for a branch. I will have to check assembly later today.

2024-12-11 19:02 UTC, swolchok commented
> > @swolchok WDYT, should be willing to add another predictable branch here?
> 
> ideally get_data is inlined and we don't actually pay for a branch. I will have to check assembly later today.

oh, I was thrown off because this code has changed since I last looked at it. I think the control flow I would like to see is as follows:
```
const auto ptr = get_data();
if (!ptr) {
  if (numel_ == 0) {
    return nullptr;
  }
  storage_initialized_torch_check_fail(); // outlined slow path for the TORCH_CHECK
}
return ptr + storage_offset_;
```

I haven't been able to check assembly yet to see if we are already getting this control flow at the assembly level (modulo the outlined slow path), though as a general rule I think it would be best to write what we want directly.

(also mildly concerned that the data_ptr_impl_impl setup makes us once again critically dependent on inlining, this time in particular across lambdas with capture)

2025-03-26 00:45 UTC, ezyang requested changes
.

2025-06-27 00:49 UTC, closed without merging