Extended TensorMetadata with device property
pytorch/pytorch pull request #142263
Opened 2024-12-06 21:39 UTC by bohnstingl

This PR intends to extend the TensorMetadata with the device property

cc @ydwu4

2024-12-07 01:48 UTC, ezyang requested changes
The location of the new field is BC breaking because this is a NamedTuple and thus subsequent fields were reordered

2024-12-07 19:38 UTC, bohnstingl commented
Thank you @ezyang for looking at this. I moved the new property to the end and also introduced `None` as a default argument to ensure BC. Would this be better?

2024-12-09 18:17 UTC, ezyang approved these changes
suuuuure why not

2024-12-09 18:17 UTC, ezyang commented
@pytorchbot merge

2024-12-10 04:43 UTC, ezyang commented
Hmm, I guess you need to shut up some tests too

2024-12-10 16:01 UTC, bohnstingl commented
Yes, I monitored these tests. However, they were failing with 
```
****** ERROR ******
An FX class that has been marked as backwards-compatible has experienced change in its public members. See the above exception context for more information. If this change was unintended, please revert it. If it was intended, check with the FX team to ensure that the proper deprecation protocols have been followed and subsequently --accept the change.
```
and I wasn't sure whether I am allowed to run with `--accept`. I did now and the CI tests pass

2024-12-11 17:42 UTC, bohnstingl commented
No, I don't. I just thought that adding this property could be helpful as in some HOPs we wanted to check whether the output of the operations is still on the same device, that's why we added it.
In the case that you mentioned, when creating the TensorMetadata by hand, I have no preference. One way would be to enhance the TensorMetadata with a dedicated __eq__ function that ignores `None` values?

2024-12-11 19:52 UTC, ezyang commented
So, another thing I could suggest to you, is instead of using TensorMetadata, use the fake tensor in meta["val"] instead, which has the device. Does that work here?

2025-02-09 21:22 UTC, closed without merging