Expand OpInfo-based testing for MPS
pytorch/pytorch pull request #142202
Opened 2024-12-06 01:42 UTC by skotapati

PR to make MPS runnable for all remaining OpInfo tests `test_operators`, `test_unary_ufuncs`, `test_binary_ufuncs`, `test_reductions`, & `test_spectral_ops`

This should bring MPS more in line with how other backends are testing, and also enables non-contiguous test cases, which are insufficiently covered in the current `test_mps`

2024-12-06 01:42 UTC, skotapati commented
Still a WIP, just putting this up so I can see live CI results

2025-01-13 21:45 UTC, skotapati commented
@albanD Could I get an override for the LOC limit in the PR sanity checks? I'm not sure how to break down the OpInfo implementation any further than I already have

2025-01-14 20:05 UTC, seemethere commented
> @albanD Could I get an override for the LOC limit in the PR sanity checks? I'm not sure how to break down the OpInfo implementation any further than I already have. Thanks!

Howdy! I'd probably say for any change that's this big we would probably say no to bypassing the LOC limit. Is there absolutely no way of breaking up this change?

2025-01-14 20:06 UTC, seemethere requested changes
We should find a way to do this that does not require a 25k+ LOC change

2025-01-14 21:36 UTC, skotapati commented
@seemethere the change got this big because I kept having to reformat common_method_invocations.py to pass the lintrunner. Perhaps I had my linter configured wrong, but it seems like common_method_invocations.py was already out of compliance so I ended up having to reformat much of the document. It is mostly just indentation changes though

One alternative could be to exempt the OpInfo definitions from the linter, is that possible?

2025-01-14 23:14 UTC, malfet requested changes
Do you mind breaking it down into several smaller PRs, and may be have some sort of a summary of how many ops are passing right now vs how many are failing.

From a reviewer side, it looks like thousands of `xfail-if-mps` are being added to common_methods_invocation, which IMO too verbose and isn't helpful.

- If one needs to xfail all `test_non_standard_bool` it should be done via `for op in ops: ops.skips.append(xfail-non-standard-bool)`
- If majority of non-contiguous ops fail for MPS, again one can codegen it with
```python
MPS_NON_CONTIG_PASS_LIST={add, sum}
for op in op_db:
  if op.name not in MPS_NON_CONTIG_PASS_LIST:
     op.skip.append(xfail-if-non-contig-on-mps)
```

2025-01-17 07:18 UTC, skotapati commented on test/run_test.py
> +            ]
Forgot to pull that out, we definitely want to test MacOS 14 as well

2025-01-17 07:20 UTC, skotapati commented on torch/testing/_internal/opinfo/definitions/special.py
> +        skips=(
Will add test_out implementation to a separate PR & explain further there

2025-01-17 07:20 UTC, skotapati commented on torch/testing/_internal/opinfo/definitions/fft.py
> +                "test_non_standard_bool_values",
Not all the tests fail for non_standard_bool_values, but I agree that it would be better to enable it in a separate PR

2025-01-17 18:19 UTC, skotapati commented
@pytorchbot rebase

2025-01-17 20:39 UTC, skotapati commented
@seemethere @malfet I refactored the code to make it a bit more manageable to review. This should also make it a bit easier to enable the remaining MPS OpInfo tests in future PRs.

I've pulled out all the tests except noncontiguous_samples for this PR, on MacOS15 there are 1006 passes, 118 skips, and 380 xfails. All the skips & xfails added by me can be seen in mps_utils.py

2025-01-21 18:29 UTC, malfet reviewed
Thank you for the update, this looks like a move in the right direction.
Can you please clarify the following:
 - Why do you want to enable non-contig first, instead of migrating the skiplist from test_mps to mps_utils and enable `test_out`?
 - Delete `dtypesIfMPS` part for now (as it's not used in this PR, unless I'm missing something)
 - Can you add `MPSXfailUnimplemented` subclass, that will add xfail decorators to all ops which are currently unimplemented?

2025-01-21 18:29 UTC, malfet commented on test/test_ops.py
> +    @skipMPS
This feels very wrong. First and foremost, we should enable `test_out`, than one can do flavors like non-contig, etc

2025-01-21 18:29 UTC, malfet commented on torch/testing/_internal/mps_utils.py
> +    "special.zeta": MPSSkipInfo(NONCONTIGUOUS),
It feels like those should be skipped with `unimplemented` reason, shouldn't they?

2025-01-21 18:29 UTC, malfet commented on torch/testing/_internal/opinfo/core.py
> +    # dtypes this function is expected to work with on MPS
Those all look unrelated to the change in question, are they?

2025-01-21 19:46 UTC, skotapati commented
I thought it was best to split out the enablement of each test since the previous version of this PR was too unmanageable to review. But if test_out is the baseline test then I'll add it back in here

2025-01-21 19:46 UTC, skotapati commented on torch/testing/_internal/opinfo/core.py
> +    # dtypes this function is expected to work with on MPS
Yes it's an artifact of the earlier version of the PR, I'll pull it out

2025-01-21 19:47 UTC, skotapati commented on test/test_ops.py
> +    @skipMPS
Ok, will add test_out back into this PR

2025-01-24 03:46 UTC, skotapati commented on torch/testing/_internal/opinfo/core.py
> +    # dtypes this function is expected to work with on MPS
Actually on further inspection, these changes are needed in order for MPS to properly pick up the default dtypes during test parametrization. I honestly didn't realize this beforehand, I added these changes in case I wanted to manually specify a dtype override for MPS. But if I revert this change, the MPS opinfo tests fail due to not picking the dtypes specified in the various test decorators

2025-01-28 00:14 UTC, malfet requested changes
Thank you for your continuous improvements. It looks much better, but do you mind reworking/splitting it a bit:
 - PR that updates error codes in various OPs  can be landed right away
 - It would be great to have list of unimplemented ops just as a list
 -  This is already exists in https://github.com/pytorch/pytorch/blob/5a4d959cdb18b0079a7f0b804ba15b79394c953d/test/test_mps.py#L661, why can't it be reused
- Please note that `test_mps.py` already has a similar op_db concept, see

2025-01-28 20:09 UTC, skotapati commented
Yeah I went ahead and removed the lower MacOS14 bounds, that wasn't accurate. 

The existing operator list in test_mps wasn't written in a way where I could easily add test-specific xfails. I suppose I can try and merge the test_mps list into the mps_op_db in mps_utils, and also separate out the unimplemented ops into a different list for easier tracking. There is an odd issue though where some of the unimplemented ops actually pass certain tests

2025-01-28 22:00 UTC, skotapati commented
@pytorchbot drci

2025-01-28 22:02 UTC, skotapati commented
@pytorchbot rebase

2025-04-29 02:58 UTC, closed without merging