[ROCm] Improvements for vectorized elementwise kernels
pytorch/pytorch pull request #142498
Opened 2024-12-10 17:55 UTC by jerrymannil

*  Make calc_io_size() return the size based on the input or output datatype, rather than the summaztion of all sizes
   * for e.g, for torch.add() on half dtypes (bfloat16/float16), calc_io_size() returns 6 causing elems_per_thread to be 4
   * But elems_per_thread = 8 works better on half datypes for AMD gpus
* Enable *_load_dwordx4 ISA for 16-bit and 8-bit dtypes and by using vector size of 8 and 16 respectively

Co-author: @akadutta

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

2024-12-11 03:34 UTC, pruthvistony requested changes

2024-12-11 03:34 UTC, pruthvistony commented on aten/src/ATen/native/cuda/thread_constants.h
> +constexpr int thread_work_size() { return 8; }
this change needs to be kept in ROCm specific guard

2024-12-13 14:59 UTC, jerrymannil commented
Closing this one. will create a new one to upstream

2024-12-13 14:59 UTC, closed without merging

2024-12-15 19:38 UTC, jerrymannil commented
New PR: https://github.com/pytorch/pytorch/pull/143269