Make `mean` function work across multiple dimensions.
pytorch/pytorch pull request #14252
Opened 2018-11-20 23:09 UTC by umanwizard

Multi-dimensional `sum` is already implemented, and it's trivial to implement `mean` in terms of `sum`, so just do it.

Bonus: Fix incomplete language in the `torch.sum` documentation which doesn't take into account multiple dimensions when describing `unsqueeze` (at the same time as introducing similar language in `torch.mean`).

2018-11-26 18:13 UTC, apaszke requested changes
fbgemm submodule has been accidentally updated

2018-11-27 21:01 UTC, colesbury approved these changes
LGTM, although I'm not familiar with the torch/csrc/jit/passes/shape_analysis.cpp code.

2018-11-27 21:03 UTC, colesbury commented on torch/csrc/jit/passes/shape_analysis.cpp
> +    static const register_formula_for multidim_reduce_ops {
@zou3519 are you familiar with this file? Can you take a look at this change?

2018-11-28 12:57 UTC, apaszke approved these changes
@colesbury shape prop lgtm

2018-11-28 14:54 UTC, closed without merging