Align CPU behavior with CUDA for `ConvTranspose` when `out_channels=0`
pytorch/pytorch pull request #142859
Opened 2024-12-11 09:16 UTC by chunyuan-w

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-12-20 08:48 UTC, chunyuan-w commented
Hi @mingfeima could you help review this PR when you get time?

2025-01-18 03:00 UTC, shaoyuyoung commented
Hi @mingfeima, if you are very busy, can anyone else review this PR?

2025-01-20 02:28 UTC, mingfeima commented on test/nn/test_convolution.py
> +    def test_ConvTranspose_output_channels_0(self):
is this test going to be launched for both CPU and CUDA device?

2025-01-20 02:28 UTC, mingfeima approved these changes

2025-01-20 02:29 UTC, mingfeima commented
Generally LGTM:) just make sure that the test is enabled for both CUDA and CPU device.

2025-01-20 05:59 UTC, chunyuan-w commented
> Generally LGTM:) just make sure that the test is enabled for both CUDA and CPU device.

I moved the test to `TestConvolutionNNDeviceType` and it will be enabled for both CUDA and CPU:
```
python -u test/nn/test_convolution.py -k test_ConvTranspose_output_channels_0_cpu_float32
python -u test/nn/test_convolution.py -k test_ConvTranspose_output_channels_0_cuda_float32
```

One thing to note is that it fails on MPS in the assertion here. I guess similar fix is needed on MPS side to align with CUDA as well.
https://github.com/pytorch/pytorch/blob/972d4a154d896b0b1c64ef9cc312e52f7b669ba1/aten/src/ATen/native/mps/OperationUtils.mm#L558

2025-01-20 06:00 UTC, chunyuan-w commented on test/nn/test_convolution.py
> +    def test_ConvTranspose_output_channels_0(self):
Update the test to be launched for both CPU and CUDA device.

2025-01-20 06:08 UTC, shaoyuyoung commented
> One thing to note is that it fails on MPS in the assertion here. I guess similar fix is needed on MPS side to align with CUDA as well.

maybe @malfet is interested in this?

2025-01-22 03:29 UTC, chunyuan-w commented
Hi @malfet could you please review this PR when you get time?

2025-01-22 05:34 UTC, malfet approved these changes
Sure, if it passes ASAN, than LGTM

2025-01-22 05:34 UTC, malfet commented on test/nn/test_convolution.py
> +            )
IMO this is equivalent but much more readable than previous statement
```suggestion
            self.assertEqual(y.numel(), 0)
            self.assertEqual(x.shape[1:], y.shape[1:])
```

2025-01-22 09:18 UTC, chunyuan-w commented on test/nn/test_convolution.py
> +            )
Thanks for the suggestion! I've simplified the code.

2025-01-23 01:08 UTC, huydhn commented
@pytorchbot revert -m 'Sorry for reverting your change but the XLA failures look legit' -c ignoredsignal

The failure is at the end of the log:

```
2025-01-22T23:20:25.5939454Z   test_ConvTranspose_output_channels_0_xla_float32 (__main__.TestConvolutionNNDeviceTypeXLA) ... /opt/conda/lib/python3.10/site-packages/torch/nn/init.py:511: UserWarning: Initializing zero-element tensors is a no-op
2025-01-22T23:20:25.5940679Z   warnings.warn("Initializing zero-element tensors is a no-op")
2025-01-22T23:20:25.5941117Z *** Received signal 8 ***
2025-01-22T23:20:25.5941411Z *** BEGIN MANGLED STACK TRACE ***
2025-01-22T23:20:25.5971238Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(+0x5d3ff26)[0x7f1465da0f26]
2025-01-22T23:20:25.5972166Z /lib/x86_64-linux-gnu/libpthread.so.0(+0x13140)[0x7f16a7e6a140]
2025-01-22T23:20:25.6004362Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(_ZN9torch_xla26MakeXlaBackpropInputConvOpESt17basic_string_viewIcSt11char_traitsIcEERKN3xla5ShapeENS4_5XlaOpES8_RKNS_11ConvOpAttrsEPS8_+0x1ce)[0x7f14658a158e]
2025-01-22T23:20:25.6030017Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(+0x583c194)[0x7f146589d194]
2025-01-22T23:20:25.6051479Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(_ZN9torch_xla28BuildConvolutionOverrideableEN3xla5XlaOpES1_N4absl12lts_202308024SpanIKlEES6_S6_bS6_l+0x2da)[0x7f146589d81a]
2025-01-22T23:20:25.6080743Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(+0x5bb02d9)[0x7f1465c112d9]
2025-01-22T23:20:25.6107808Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(+0x5bb0516)[0x7f1465c11516]
2025-01-22T23:20:25.6130123Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(_ZN9torch_xla16InferOutputShapeEN4absl12lts_202308024SpanIKN3xla5ShapeEEERKSt8functionIFNS3_5XlaOpENS2_IKS8_EEEE+0x221)[0x7f1465c44451]
2025-01-22T23:20:25.6159612Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(+0x5bb008e)[0x7f1465c1108e]
2025-01-22T23:20:25.6186040Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(+0x5bb0198)[0x7f1465c11198]
2025-01-22T23:20:25.6208713Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(_ZNK9torch_xla7XlaNode10GetOpShapeERKSt8functionIFN3xla5ShapeEvEE+0x1e6)[0x7f1465cd63d6]
2025-01-22T23:20:25.6239440Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(_ZN9torch_xla7XlaNodeC2EN5torch4lazy6OpKindEN3c108ArrayRefINS2_5ValueEEERKSt8functionIFN3xla5ShapeEvEEmNS2_6hash_tE+0x89)[0x7f1465cd6cd9]
2025-01-22T23:20:25.6265364Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(_ZN9torch_xla23ConvolutionOverrideableC2ERKN5torch4lazy5ValueES5_S5_St6vectorIlSaIlEES8_S8_bS8_l+0x4bb)[0x7f1465c11ecb]
2025-01-22T23:20:25.6287430Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(_ZN9torch_xla8MakeNodeINS_23ConvolutionOverrideableEJN5torch4lazy5ValueES4_S4_St6vectorIlSaIlEES7_S7_RbS7_RlEEESt10shared_ptrINS3_4NodeEEDpOT0_+0x19a)[0x7f1465951b8a]
2025-01-22T23:20:25.6317320Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(_ZN9torch_xla14tensor_methods24convolution_overrideableERKN3c1013intrusive_ptrINS_9XLATensorENS1_6detail34intrusive_target_default_null_typeIS3_EEEES9_S9_St6vectorIlSaIlEESC_SC_bSC_l+0x9a)[0x7f1465951d5a]
2025-01-22T23:20:25.6342948Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(_ZN9torch_xla18XLANativeFunctions24convolution_overrideableERKN2at6TensorES4_RKSt8optionalIS2_EN3c108ArrayRefIlEESB_SB_bSB_l+0x1fc)[0x7f146583c33c]
2025-01-22T23:20:25.6363954Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(+0x5ab3ab7)[0x7f1465b14ab7]
2025-01-22T23:20:25.6390328Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(+0x5b41de4)[0x7f1465ba2de4]
2025-01-22T23:20:25.6391954Z /opt/conda/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so(+0xf8e48d)[0x7f1697d5f48d]
2025-01-22T23:20:25.6395455Z /opt/conda/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so(+0xf8910d)[0x7f1697d5a10d]
2025-01-22T23:20:25.6399316Z /opt/conda/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so(+0x1fd0aeb)[0x7f1698da1aeb]
2025-01-22T23:20:25.6404249Z /opt/conda/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so(_ZN2at4_ops24convolution_overrideable4callERKNS_6TensorES4_RKSt8optionalIS2_EN3c108ArrayRefINS9_6SymIntEEESC_SC_bSC_SB_+0x756)[0x7f169939fcd6]
2025-01-22T23:20:25.6407068Z /opt/conda/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so(+0x14a2ce0)[0x7f1698273ce0]
2025-01-22T23:20:25.6410871Z /opt/conda/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so(_ZN2at6native12_convolutionERKNS_6TensorES3_RKSt8optionalIS1_EN3c108ArrayRefIlEESA_SA_bSA_lbbbb+0xef1)[0x7f1698255491]
2025-01-22T23:20:25.6415174Z /opt/conda/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so(+0x2a2d549)[0x7f16997fe549]
2025-01-22T23:20:25.6419914Z /opt/conda/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so(+0x2a2da20)[0x7f16997fea20]
2025-01-22T23:20:25.6423630Z /opt/conda/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so(_ZN2at17functionalization23functionalize_op_helperERKN3c1014OperatorHandleEPSt6vectorINS1_6IValueESaIS6_EE+0x538)[0x7f1697d53bf8]
2025-01-22T23:20:25.6450908Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(_ZN2at17functionalization22_functionalize_aten_opINS_4_ops12_convolutionELb0EFNS_6TensorERKS4_S6_RKSt8optionalIS4_EN3c108ArrayRefINSB_6SymIntEEESE_SE_bSE_SD_bbbbEJEE4callES6_S6_SA_NSC_IlEESH_SH_bSH_lbbbb+0x310)[0x7f1465872280]
2025-01-22T23:20:25.6480778Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(_ZN9torch_xla18XLANativeFunctions12_convolutionERKN2at6TensorES4_RKSt8optionalIS2_EN3c108ArrayRefIlEESB_SB_bSB_lbbbb+0xe0)[0x7f1465872480]
2025-01-22T23:20:25.6506632Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(+0x5ab368b)[0x7f1465b1468b]
2025-01-22T23:20:25.6527508Z /opt/conda/lib/python3.10/site-packages/torch_xla-2.7.0+gitb2b890e-py3.10-linux-x86_64.egg/_XLAC.cpython-310-x86_64-linux-gnu.so(+0x5ab5578)[0x7f1465b16578]
2025-01-22T23:20:25.6530439Z /opt/conda/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so(+0x1fd2a4d)[0x7f1698da3a4d]
2025-01-22T23:20:25.6534643Z /opt/conda/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so(_ZN2at4_ops12_convolution4callERKNS_6TensorES4_RKSt8optionalIS2_EN3c108ArrayRefINS9_6SymIntEEESC_SC_bSC_SB_bbbb+0x329)[0x7f1698ca3999]
2025-01-22T23:20:25.6537522Z /opt/conda/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so(+0x14964c2)[0x7f16982674c2]
2025-01-22T23:20:25.6541352Z /opt/conda/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so(_ZN2at6native11convolutionERKNS_6TensorES3_RKSt8optionalIS1_EN3c108 [...]

2025-01-24 05:26 UTC, chunyuan-w commented
I verified that using the main branch (without the cpp code change in this PR), the case `test_ConvTranspose_output_channels_0` will still fail on XLA with the same error message. Thus I added a `@skipXLA` decorator for this UT since the failure is not brought by this PR. Similar fix is needed on the XLA device as well.

The CI is all green now.

2025-01-26 01:49 UTC, chunyuan-w commented
@pytorchbot merge

2025-01-26 17:47 UTC, malfet commented
@pytorchbot revert -m "It broke ROCM tests again, see https://hud.pytorch.org/hud/pytorch/pytorch/5cd2b34e821c293909fe3f6a958767b9c535c094/1?per_page=50&name_filter=rocm&mergeLF=true" -c ignoredsignal

2025-01-26 21:45 UTC, malfet requested changes
Rather than adding more and more "skipIfFoo", imo the right solution is to move the check up thru the stack (or turn the op into structured one)

2025-01-28 18:48 UTC, jeffdaily commented on test/nn/test_convolution.py
> +    def test_ConvTranspose_output_channels_0(self, device, dtype):
```suggestion
    @skipCUDAIfRocm
    def test_ConvTranspose_output_channels_0(self, device, dtype):
```
I tried a few things to get this to work on ROCm but it's going to take longer to dig into it.  I updated the use_miopen check to avoid miopen when weight.size(1) == 0 but it falls through to hipblas and then fails there instead.

2025-04-28 20:35 UTC, closed without merging