Upgrade MKL-DNN to version 0.17
pytorch/pytorch pull request #14308
Opened 2018-11-22 03:16 UTC by gujinghui

upgrade MKL-DNN to version 0.17
update mkldnn bridge to latest.

2018-11-22 07:52 UTC, yinghai requested changes
We cannot consume MKL-DNN 0.17 yet because of MKL dependency of IGEMM support. We need to wait for MKL-DNN to provide a build option to exclude int8 ops to do so for now.

2018-11-22 09:35 UTC, gujinghui commented
@yinghai 
I tried to disable blas dependency in this PR. But not sure.
Could you try it on your side. If still not work, could you send the error log?
There should be some way to avoid the linking error.

According to MKL-DNN src, the IGEMM should be disabled if MKL is too old.
So, I'm sure the root-cause of the error you encountered so far.

2018-11-22 09:37 UTC, gujinghui commented
@Jianhui-Li @jgong5

2018-11-22 16:14 UTC, yinghai commented
Could you point me the line of code that disables the IGEMM? Thanks.

2018-11-23 02:54 UTC, gujinghui commented
@yinghai 
Pls review mkl-dnn code in below file:
third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp

#include "mkl_version.h"

#define USE_MKL_PACKED_GEMM (INTEL_MKL_VERSION >= 20170000)
#define USE_MKL_IGEMM \
    (INTEL_MKL_VERSION >= 20180000 && __INTEL_MKL_BUILD_DATE >= 20170628)

2018-11-26 19:11 UTC, Jianhui-Li commented
>>>According to MKL-DNN src, the IGEMM should be disabled if MKL is too old.
>>>#define USE_MKL_IGEMM 
(INTEL_MKL_VERSION >= 20180000 && __INTEL_MKL_BUILD_DATE >= 20170628)

@gujinghui the link error of cblas_gemm_s8u8s32 @yinghai reported is not guarded by this macro (USE_MKL_IGEMM), it is guarded by "USE_CBLAS". So the version check for USE_MKL_IGEMM won't solve the link error for cblas_gemm_s8u8s32. 

Link error reported by @yinghai -
/home/engshare/third-party2/mkl-dnn/trunk/src/mkl-dnn-trunk/src/cpu/gemm/gemm.cpp:230:27: error: '**cblas_gemm_s8u8s32**' was not declared in this scope
cblas_gemm_s8u8s32(CblasColMajor, Cblas_trA, Cblas_trB, Cblas_offsetc,

@yinghai @wesolwsk

2018-11-27 02:20 UTC, yinghai commented on cmake/Modules/FindMKLDNN.cmake
> +  SET(MKLDNN_THREADING "OMP:COMP")
What does this line mean?

2018-12-06 05:36 UTC, ezyang commented
@yinghai Any update on this PR?

2018-12-06 08:42 UTC, yinghai commented
Ok. I've ported mkldnn 0.17 internally and we are good to go. 

I'd suggest enable Ideep ops in our mkl CI though.

2018-12-07 03:01 UTC, gujinghui commented
> @gujinghui Can we add IDEEP test to MKL CI to test things? Add something like MKLDNN=1 to
> https://github.com/pytorch/pytorch/blob/master/.jenkins/caffe2/build.sh#L134
> should work.

Should. Will do it soon.

2018-12-07 09:15 UTC, gujinghui commented
@yinghai  pls help review

2018-12-07 20:44 UTC, yinghai approved these changes
Thanks!

2018-12-08 00:46 UTC, closed without merging

2018-12-08 05:06 UTC, happydig commented
python3 ./setup.py install
```
Building wheel torch-1.0.0a0+25110d6
running install
setup.py::run()
running build_deps
setup.py::build_deps::run()
+ SYNC_COMMAND=cp
++ command -v rsync
+ '[' -x /usr/bin/rsync ']'
+ SYNC_COMMAND='rsync -lptgoD'
+ CMAKE_COMMAND=cmake
++ command -v cmake3
+ [[ -x '' ]]
+ USE_CUDA=0
+ USE_FBGEMM=1
+ USE_ROCM=0
+ USE_NNPACK=0
+ USE_MKLDNN=0
+ USE_QNNPACK=0
+ USE_GLOO_IBVERBS=0
+ CAFFE2_STATIC_LINK_CUDA=0
+ RERUN_CMAKE=1
+ [[ 4 -gt 0 ]]
+ case "$1" in
+ USE_NNPACK=1
+ shift
+ [[ 3 -gt 0 ]]
+ case "$1" in
+ USE_MKLDNN=1
+ shift
+ [[ 2 -gt 0 ]]
+ case "$1" in
+ USE_QNNPACK=1
+ shift
+ [[ 1 -gt 0 ]]
+ case "$1" in
+ break
+ CMAKE_INSTALL='ninja install'
+ BUILD_SHARED_LIBS=ON
+ USER_CFLAGS=
+ USER_LDFLAGS=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
++ uname
+ '[' Linux == Darwin ']'
+++ dirname ../tools/build_pytorch_libs.sh
++ cd ../tools/..
+++ pwd
++ printf '%q\n' /studio/pytorch
+ BASE_DIR=/studio/pytorch
+ TORCH_LIB_DIR=/studio/pytorch/torch/lib
+ INSTALL_DIR=/studio/pytorch/torch/lib/tmp_install
+ THIRD_PARTY_DIR=/studio/pytorch/third_party
+ C_FLAGS=
+ C_FLAGS=' -DOMPI_SKIP_MPICXX=1'
+ LDFLAGS=
+ LD_POSTFIX=.so
++ uname
+ [[ Linux == \D\a\r\w\i\n ]]
+ [[ 0 -eq 1 ]]
+ LDFLAGS=' -Wl,-rpath,$ORIGIN'
+ CPP_FLAGS=' -std=c++11 '
+ THD_FLAGS=
+ [[ 0 -eq 1 ]]
+ CUDA_NVCC_FLAGS=' -DOMPI_SKIP_MPICXX=1'
+ [[ -z '' ]]
+ CUDA_DEVICE_DEBUG=0
+ '[' -z '' ']'
++ getconf _NPROCESSORS_ONLN
+ MAX_JOBS=4
+ BUILD_TYPE=Release
+ [[ -n '' ]]
+ [[ -n '' ]]
+ echo 'Building in Release mode'
Building in Release mode
+ mkdir -p /studio/pytorch/torch/lib/tmp_install
+ for arg in "$@"
+ [[ caffe2 == \c\a\f\f\e\2 ]]
+ build_caffe2
+ [[ -z '' ]]
+ EXTRA_CAFFE2_CMAKE_FLAGS=()
+ [[ -n '' ]]
+ [[ -n /opt/mpython/lib/python3.7/site-packages ]]
+ EXTRA_CAFFE2_CMAKE_FLAGS+=("-DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH")
+ [[ 1 -eq 1 ]]
+ cmake /studio/pytorch -GNinja -DPYTHON_EXECUTABLE=/opt/mpython/bin/python3 -DPYTHON_LIBRARY=/opt/mpython/lib/libpython3.7m.a -DPYTHON_INCLUDE_DIR=/opt/mpython/include/python3.7m -DBUILDING_WITH_TORCH_LIBS=ON -DTORCH_BUILD_VERSION=1.0.0a0+25110d6 -DCMAKE_BUILD_TYPE=Release -DBUILD_TORCH=ON -DBUILD_PYTHON=ON -DBUILD_SHARED_LIBS=ON -DBUILD_BINARY=OFF -DBUILD_TEST=ON -DINSTALL_TEST=ON -DBUILD_CAFFE2_OPS=ON -DONNX_NAMESPACE=onnx_torch -DUSE_CUDA=0 -DUSE_DISTRIBUTED=ON -DUSE_FBGEMM=1 -DUSE_NUMPY= -DNUMPY_INCLUDE_DIR=/opt/mpython/lib/python3.7/site-packages/numpy/core/include -DUSE_SYSTEM_NCCL=OFF -DNCCL_INCLUDE_DIR= -DNCCL_ROOT_DIR= -DNCCL_SYSTEM_LIB= -DCAFFE2_STATIC_LINK_CUDA=0 -DUSE_ROCM=0 -DUSE_NNPACK=1 -DUSE_LEVELDB=OFF -DUSE_LMDB=OFF -DUSE_OPENCV=OFF -DUSE_QNNPACK=1 -DUSE_TENSORRT=OFF -DUSE_FFMPEG=OFF -DUSE_GLOG=OFF -DUSE_GFLAGS=OFF -DUSE_SYSTEM_EIGEN_INSTALL=OFF -DCUDNN_INCLUDE_DIR= -DCUDNN_LIB_DIR= -DCUDNN_LIBRARY= -DUSE_MKLDNN=1 -DNCCL_EXTERNAL=0 -DCMAKE_INSTALL_PREFIX=/studio/pytorch/torch/lib/tmp_install -DCMAKE_C_FLAGS= -DCMAKE_CXX_FLAGS= '-DCMAKE_EXE_LINKER_FLAGS= -Wl,-rpath,$ORIGIN ' '-DCMAKE_SHARED_LINKER_FLAGS= -Wl,-rpath,$ORIGIN ' -DTHD_SO_VERSION=1 -DCMAKE_PREFIX_PATH=/opt/mpython/lib/python3.7/site-packages
-- The CXX compiler identification is GNU 8.2.0
-- The C compiler identification is GNU 8.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Not forcing any particular BLAS to be found
-- Performing Test COMPILER_WORKS
-- Performing Test COMPILER_WORKS - Success
-- Performing Test SUPPORT_GLIBCXX_USE_C99
-- Performing Test SUPPORT_GLIBCXX_USE_C99 - Success
-- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED
-- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED - Success
-- std::exception_ptr is supported.
-- Performing Test CAFFE2_IS_NUMA_AVAILABLE
-- Performing Test CAFFE2_IS_NUMA_AVAILABLE - Success
-- NUMA is available
-- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING
-- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING - Success
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS - Success
-- Current compiler supports avx2 extension. Will build perfkernels.
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX512F_EXTENSIONS
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX512F_EXTENSIONS - Success
-- Current compiler supports avx512f extension. Will build fbgemm.
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC - Success
-- Building using own protobuf under third_party per request.
-- Use custom protobuf build.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/studio/pytorch/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
-- The BLAS backend of choice:MKL
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
--   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
-- Looking for cblas_sgemm
-- Looking for cblas_sgemm - found
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Brace yourself, we are building NNPACK
-- Found PythonInterp: /opt/mpython/bin/python3 (found version "3.7.1") 
-- Failed to find LLVM FileCheck
-- Found Git: /usr/bin/git (found version "2.19.1") 
-- git Version: v1.4.0-505be96a
-- Version: 1.4.0
-- Performing Test HAVE_CXX_FLAG_STD_CXX11
-- Performing Test HAVE_CXX_FLAG_STD_CXX11 - Success
-- Performing Test HAVE_CXX_FLAG_WALL
-- Performing Test HAVE_CXX_FLAG_WALL - Success
-- Performing Test HAVE_CXX_FLAG_WEXTRA
-- Performing Test HAVE_CXX_FLAG_WEXTRA - Success
-- Performing Test HAVE_CXX_FLAG_WSHADOW
-- Performing Test HAVE_CXX_FLAG_WSHADOW - Success
-- Performing Test HAVE_CXX_FLAG_WERROR
-- Performing Test HAVE_CXX_FLAG_WERROR - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC
-- Performing Test HAVE_CXX_FLAG_PEDANTIC - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS - Success
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 - Failed
-- Performing Test HAVE_CXX_FLAG_WFLOAT_EQUAL
-- Performing Test HAVE_CXX_FLAG_WFLOAT_EQUAL - Success
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING - Success
-- Performin [...]

2018-12-10 04:41 UTC, gujinghui commented
> python3 ./setup.py install
> 
> ```
> Building wheel torch-1.0.0a0+25110d6
> running install
> setup.py::run()
> running build_deps
> setup.py::build_deps::run()
> + SYNC_COMMAND=cp
> ++ command -v rsync
> + '[' -x /usr/bin/rsync ']'
> + SYNC_COMMAND='rsync -lptgoD'
> + CMAKE_COMMAND=cmake
> ++ command -v cmake3
> + [[ -x '' ]]
> + USE_CUDA=0
> + USE_FBGEMM=1
> + USE_ROCM=0
> + USE_NNPACK=0
> + USE_MKLDNN=0
> + USE_QNNPACK=0
> + USE_GLOO_IBVERBS=0
> + CAFFE2_STATIC_LINK_CUDA=0
> + RERUN_CMAKE=1
> + [[ 4 -gt 0 ]]
> + case "$1" in
> + USE_NNPACK=1
> + shift
> + [[ 3 -gt 0 ]]
> + case "$1" in
> + USE_MKLDNN=1
> + shift
> + [[ 2 -gt 0 ]]
> + case "$1" in
> + USE_QNNPACK=1
> + shift
> + [[ 1 -gt 0 ]]
> + case "$1" in
> + break
> + CMAKE_INSTALL='ninja install'
> + BUILD_SHARED_LIBS=ON
> + USER_CFLAGS=
> + USER_LDFLAGS=
> + [[ -n '' ]]
> + [[ -n '' ]]
> + [[ -n '' ]]
> ++ uname
> + '[' Linux == Darwin ']'
> +++ dirname ../tools/build_pytorch_libs.sh
> ++ cd ../tools/..
> +++ pwd
> ++ printf '%q\n' /studio/pytorch
> + BASE_DIR=/studio/pytorch
> + TORCH_LIB_DIR=/studio/pytorch/torch/lib
> + INSTALL_DIR=/studio/pytorch/torch/lib/tmp_install
> + THIRD_PARTY_DIR=/studio/pytorch/third_party
> + C_FLAGS=
> + C_FLAGS=' -DOMPI_SKIP_MPICXX=1'
> + LDFLAGS=
> + LD_POSTFIX=.so
> ++ uname
> + [[ Linux == \D\a\r\w\i\n ]]
> + [[ 0 -eq 1 ]]
> + LDFLAGS=' -Wl,-rpath,$ORIGIN'
> + CPP_FLAGS=' -std=c++11 '
> + THD_FLAGS=
> + [[ 0 -eq 1 ]]
> + CUDA_NVCC_FLAGS=' -DOMPI_SKIP_MPICXX=1'
> + [[ -z '' ]]
> + CUDA_DEVICE_DEBUG=0
> + '[' -z '' ']'
> ++ getconf _NPROCESSORS_ONLN
> + MAX_JOBS=4
> + BUILD_TYPE=Release
> + [[ -n '' ]]
> + [[ -n '' ]]
> + echo 'Building in Release mode'
> Building in Release mode
> + mkdir -p /studio/pytorch/torch/lib/tmp_install
> + for arg in "$@"
> + [[ caffe2 == \c\a\f\f\e\2 ]]
> + build_caffe2
> + [[ -z '' ]]
> + EXTRA_CAFFE2_CMAKE_FLAGS=()
> + [[ -n '' ]]
> + [[ -n /opt/mpython/lib/python3.7/site-packages ]]
> + EXTRA_CAFFE2_CMAKE_FLAGS+=("-DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH")
> + [[ 1 -eq 1 ]]
> + cmake /studio/pytorch -GNinja -DPYTHON_EXECUTABLE=/opt/mpython/bin/python3 -DPYTHON_LIBRARY=/opt/mpython/lib/libpython3.7m.a -DPYTHON_INCLUDE_DIR=/opt/mpython/include/python3.7m -DBUILDING_WITH_TORCH_LIBS=ON -DTORCH_BUILD_VERSION=1.0.0a0+25110d6 -DCMAKE_BUILD_TYPE=Release -DBUILD_TORCH=ON -DBUILD_PYTHON=ON -DBUILD_SHARED_LIBS=ON -DBUILD_BINARY=OFF -DBUILD_TEST=ON -DINSTALL_TEST=ON -DBUILD_CAFFE2_OPS=ON -DONNX_NAMESPACE=onnx_torch -DUSE_CUDA=0 -DUSE_DISTRIBUTED=ON -DUSE_FBGEMM=1 -DUSE_NUMPY= -DNUMPY_INCLUDE_DIR=/opt/mpython/lib/python3.7/site-packages/numpy/core/include -DUSE_SYSTEM_NCCL=OFF -DNCCL_INCLUDE_DIR= -DNCCL_ROOT_DIR= -DNCCL_SYSTEM_LIB= -DCAFFE2_STATIC_LINK_CUDA=0 -DUSE_ROCM=0 -DUSE_NNPACK=1 -DUSE_LEVELDB=OFF -DUSE_LMDB=OFF -DUSE_OPENCV=OFF -DUSE_QNNPACK=1 -DUSE_TENSORRT=OFF -DUSE_FFMPEG=OFF -DUSE_GLOG=OFF -DUSE_GFLAGS=OFF -DUSE_SYSTEM_EIGEN_INSTALL=OFF -DCUDNN_INCLUDE_DIR= -DCUDNN_LIB_DIR= -DCUDNN_LIBRARY= -DUSE_MKLDNN=1 -DNCCL_EXTERNAL=0 -DCMAKE_INSTALL_PREFIX=/studio/pytorch/torch/lib/tmp_install -DCMAKE_C_FLAGS= -DCMAKE_CXX_FLAGS= '-DCMAKE_EXE_LINKER_FLAGS= -Wl,-rpath,$ORIGIN ' '-DCMAKE_SHARED_LINKER_FLAGS= -Wl,-rpath,$ORIGIN ' -DTHD_SO_VERSION=1 -DCMAKE_PREFIX_PATH=/opt/mpython/lib/python3.7/site-packages
> -- The CXX compiler identification is GNU 8.2.0
> -- The C compiler identification is GNU 8.2.0
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Not forcing any particular BLAS to be found
> -- Performing Test COMPILER_WORKS
> -- Performing Test COMPILER_WORKS - Success
> -- Performing Test SUPPORT_GLIBCXX_USE_C99
> -- Performing Test SUPPORT_GLIBCXX_USE_C99 - Success
> -- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED
> -- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED - Success
> -- std::exception_ptr is supported.
> -- Performing Test CAFFE2_IS_NUMA_AVAILABLE
> -- Performing Test CAFFE2_IS_NUMA_AVAILABLE - Success
> -- NUMA is available
> -- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING
> -- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING - Success
> -- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS
> -- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS - Success
> -- Current compiler supports avx2 extension. Will build perfkernels.
> -- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX512F_EXTENSIONS
> -- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX512F_EXTENSIONS - Success
> -- Current compiler supports avx512f extension. Will build fbgemm.
> -- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY
> -- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY - Success
> -- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY
> -- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY - Success
> -- Performing Test COMPILER_SUPPORTS_RDYNAMIC
> -- Performing Test COMPILER_SUPPORTS_RDYNAMIC - Success
> -- Building using own protobuf under third_party per request.
> -- Use custom protobuf build.
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/studio/pytorch/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
> -- The BLAS backend of choice:MKL
> -- Looking for sys/types.h
> -- Looking for sys/types.h - found
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Looking for stddef.h
> -- Looking for stddef.h - found
> -- Check size of void*
> -- Check size of void* - done
> -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
> --   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
> --   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
> --   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
> -- Found OpenMP_C: -fopenmp (found version "4.5") 
> -- Found OpenMP_CXX: -fopenmp (found version "4.5") 
> -- Found OpenMP: TRUE (found version "4.5")  
> --   Library gomp: -fopenmp
> --   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
> --   Library m: /usr/lib/x86_64-linux-gnu/libm.so
> --   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
> -- Looking for cblas_sgemm
> -- Looking for cblas_sgemm - found
> -- The ASM compiler identification is GNU
> -- Found assembler: /usr/bin/cc
> -- Check if compiler accepts -pthread
> -- Check if compiler accepts -pthread - yes
> -- Brace yourself, we are building NNPACK
> -- Found PythonInterp: /opt/mpython/bin/python3 (found version "3.7.1") 
> -- Failed to find LLVM FileCheck
> -- Found Git: /usr/bin/git (found version "2.19.1") 
> -- git Version: v1.4.0-505be96a
> -- Version: 1.4.0
> -- Performing Test HAVE_CXX_FLAG_STD_CXX11
> -- Performing Test HAVE_CXX_FLAG_STD_CXX11 - Success
> -- Performing Test HAVE_CXX_FLAG_WALL
> -- Performing Test HAVE_CXX_FLAG_WALL - Success
> -- Performing Test HAVE_CXX_FLAG_WEXTRA
> -- Performing Test HAVE_CXX_FLAG_WEXTRA - Success
> -- Performing Test HAVE_CXX_FLAG_WSHADOW
> -- Performing Test HAVE_CXX_FLAG_WSHADOW - Success
> -- Performing Test HAVE_CXX_FLAG_WERROR
> -- Performing Test HAVE_CXX_FLAG_WERROR - Success
> -- Performing Test HAVE_CXX_FLAG_PEDANTIC
> -- Performing Test HAVE_CXX_FLAG_PEDANTIC - Success
> -- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS
> -- Performing Test HA [...]

2018-12-11 07:44 UTC, happydig commented
```
[1336/2379] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state.cc.o
FAILED: caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state_ideep.cc.o 
/usr/bin/c++  -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -DUSE_C11_ATOMICS=1 -DUSE_MKL -D_FILE_OFFSET_BITS=64 -Dcaffe2_pybind11_state_EXPORTS -I../aten/src -I. -I../ -I../third_party/protobuf/src -I../cmake/../third_party/benchmark/include -Icaffe2/contrib/aten -I../third_party/onnx -Ithird_party/onnx -Icaffe2/aten/src/TH -I../aten/src/TH -Icaffe2/aten/src -Iaten/src -I../aten/../third_party/catch/single_include -I../aten/src/ATen/.. -Icaffe2/aten/src/ATen -I../caffe2/core/nomnigraph/include -I../third_party/miniz-2.0.8 -I../c10/.. -isystem third_party/gloo -isystem ../cmake/../third_party/gloo -isystem /opt/intel/mkl/include -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../cmake/../third_party/googletest/googletest/include -isystem ../third_party -isystem ../cmake/../third_party/eigen -isystem /opt/mpython/include/python3.7m -isystem /opt/mpython/lib/python3.7/site-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -isystem ../third_party/ideep/include -fvisibility-inlines-hidden -D_FORCE_INLINES -D_MWAITXINTRIN_H_INCLUDED -D__STRICT_ANSI__ -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -Wno-stringop-overflow -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3  -fPIC   -fvisibility=hidden -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -Wno-maybe-uninitialized -DTH_HAVE_THREAD -std=c++11 -std=gnu++11 -MD -MT caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state_ideep.cc.o -MF caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state_ideep.cc.o.d -o caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state_ideep.cc.o -c ../caffe2/python/pybind_state_ideep.cc
In file included from ../third_party/ideep/include/ideep.hpp:44,
                 from ../caffe2/ideep/ideep_utils.h:6,
                 from ../caffe2/ideep/operators/operator_fallback_ideep.h:6,
                 from ../caffe2/python/pybind_state_ideep.cc:12:
../third_party/ideep/include/ideep/computations.hpp: In constructor ‘ideep::channel_shuffle_forward::descriptor::descriptor(const ideep::param::descriptor&, int, int, ideep::prop_kind)’:
../third_party/ideep/include/ideep/computations.hpp:4229:7: error: ‘mkldnn_shuffle_desc_t’ was not declared in this scope
       mkldnn_shuffle_desc_t data;
       ^~~~~~~~~~~~~~~~~~~~~
../third_party/ideep/include/ideep/computations.hpp:4229:7: note: suggested alternative: ‘mkldnn_softmax_desc_t’
       mkldnn_shuffle_desc_t data;
       ^~~~~~~~~~~~~~~~~~~~~
       mkldnn_softmax_desc_t
../third_party/ideep/include/ideep/computations.hpp:4231:45: error: ‘data’ was not declared in this scope
           mkldnn_shuffle_forward_desc_init(&data,
                                             ^~~~
../third_party/ideep/include/ideep/computations.hpp:4231:45: note: suggested alternative:
In file included from ../aten/src/ATen/core/jit_type.h:4,
                 from ../aten/src/ATen/core/function_schema.h:3,
                 from ../caffe2/core/operator.h:27,
                 from ../caffe2/python/pybind_state.h:10,
                 from ../caffe2/python/pybind_state_ideep.cc:7:
../aten/src/ATen/core/aten_interned_strings.h:753:9: note:   ‘c10::attr::data’
 _(attr, data) \
         ^~~~
../aten/src/ATen/core/interned_strings.h:269:35: note: in definition of macro ‘DEFINE_SYMBOL’
   namespace ns { constexpr Symbol s(static_cast<unique_t>(_keys::ns##_##s)); }
                                   ^
../aten/src/ATen/core/interned_strings.h:115:3: note: in expansion of macro ‘FORALL_ATTR_BASE_SYMBOLS’
   FORALL_ATTR_BASE_SYMBOLS(_)      \
   ^~~~~~~~~~~~~~~~~~~~~~~~
../aten/src/ATen/core/interned_strings.h:270:1: note: in expansion of macro ‘FORALL_NS_SYMBOLS’
 FORALL_NS_SYMBOLS(DEFINE_SYMBOL)
 ^~~~~~~~~~~~~~~~~
In file included from ../third_party/ideep/include/ideep.hpp:44,
                 from ../caffe2/ideep/ideep_utils.h:6,
                 from ../caffe2/ideep/operators/operator_fallback_ideep.h:6,
                 from ../caffe2/python/pybind_state_ideep.cc:12:
../third_party/ideep/include/ideep/computations.hpp:4231:11: error: ‘mkldnn_shuffle_forward_desc_init’ was not declared in this scope
           mkldnn_shuffle_forward_desc_init(&data,
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/ideep/include/ideep/computations.hpp:4231:11: note: suggested alternative: ‘mkldnn_softmax_forward_desc_init’
           mkldnn_shuffle_forward_desc_init(&data,
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           mkldnn_softmax_forward_desc_init
../third_party/ideep/include/ideep/computations.hpp: In constructor ‘ideep::channel_shuffle_backward::descriptor::descriptor(const ideep::param::descriptor&, int, int)’:
../third_party/ideep/include/ideep/computations.hpp:4313:7: error: ‘mkldnn_shuffle_desc_t’ was not declared in this scope
       mkldnn_shuffle_desc_t data;
       ^~~~~~~~~~~~~~~~~~~~~
../third_party/ideep/include/ideep/computations.hpp:4313:7: note: suggested alternative: ‘mkldnn_softmax_desc_t’
       mkldnn_shuffle_desc_t data;
       ^~~~~~~~~~~~~~~~~~~~~
       mkldnn_softmax_desc_t
../third_party/ideep/include/ideep/computations.hpp:4314:60: error: ‘data’ was not declared in this scope
       error::wrap_c_api(mkldnn_shuffle_backward_desc_init(&data,
                                                            ^~~~
../third_party/ideep/include/ideep/computations.hpp:4314:60: note: suggested alternative:
In file included from ../aten/src/ATen/core/jit_type.h:4,
                 from ../aten/src/ATen/core/function_schema.h:3,
                 from ../caffe2/core/operator.h:27,
                 from ../caffe2/python/pybind_state.h:10,
                 from ../caffe2/python/pybind_state_ideep.cc:7:
../aten/src/ATen/core/aten_interned_strings.h:753:9: note:   ‘c10::attr::data’
 _(attr, data) \
         ^~~~
../aten/src/ATen/core/interned_strings.h:269:35: note: in definition of macro ‘DEFINE_SYMBOL’
   namespace ns { constexpr Symbol s(static_cast<unique_t>(_keys::ns##_##s)); }
                                   ^
../aten/src/ATen/core/interned_strings.h:115:3: note: in expansion of macro ‘FORALL_ATTR_BASE_SYMBOLS’
   FORALL_ATTR_BASE_SYMBOLS(_)      \
   ^~~~~~~~~~~~~~~~~~~~~~~~
../aten/src/ATen/core/interned_strings.h:270:1: note: in expansion of macro ‘FORALL_NS_SYMBOLS’
 FORALL_NS_SYMBOLS(DEFINE_SYMBOL)
 ^~~~~~~~~~~~~~~~~
In file included from ../third_party/ideep/include/ideep.hpp:44,
                 from ../caffe2/ideep/ideep_utils.h:6,
                 from ../caffe2/ideep/operators/operator_fallback_ideep.h:6,
                 from ../caffe2/python/pybind_state_ideep.cc:12:
../third_party/ideep/include/ideep/computations.hpp:4314:25: error: ‘mkldnn_shuffle_backward_desc_init’ was not declared in this scope
       error::wrap_c_api(mkldnn_shuffle_backward_desc_init(&data,
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/ideep/include/ideep/computations.hpp:4314:25: note: suggested alternative: ‘mkldnn_relu_backward_desc_init’
       error::wrap_c_api(mkldnn_shuffle_backward_desc_init(&data,
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                         mkldnn_relu_backward_desc_init
[1339/2379] Building CXX object caffe2/CMakeFiles/caffe2_p [...]

2018-12-11 07:58 UTC, gujinghui commented
@happydig 
caused by too older mkldnn in third_party/ideep.
Pls try below cmd:
git submodule update --init third_party/ideep
cd third_party/ideep
git submodule update --init mkl-dnn