cache cleaned_instructions: 33.7 -> 30.0
pytorch/pytorch pull request #143070
Opened 2024-12-11 22:31 UTC by aorenste

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

See #143056 for overall docs.

This PR: Cache the interesting/expensive bits of `cleaned_instructions()`

2024-12-11 23:06 UTC, laithsakka commented
you might want to rebase on https://github.com/pytorch/pytorch/pull/143075

2024-12-12 17:31 UTC, jansel requested changes

2024-12-24 00:22 UTC, jansel approved these changes

2024-12-26 15:44 UTC, aorenste commented
@pytorchbot merge

2024-12-26 19:02 UTC, closed without merging