Support unique id for Tensor Storage Object
pytorch/pytorch pull request #143093
Opened 2024-12-12 01:57 UTC by shengfukevin

Summary: Suppoer unique id for Tensor Storage Object

Differential Revision: D66849516

2024-12-12 18:00 UTC, shengfukevin commented
@pytorchbot label "topic: not user facing"

2024-12-17 18:02 UTC, sraikund16 approved these changes
Can we get someone from the PT core team to sign off as well?

2024-12-17 21:32 UTC, sraikund16 commented
Also can we add a test

2024-12-18 00:09 UTC, sraikund16 requested changes
Lets get an extra review and add tests please

2024-12-18 15:14 UTC, ezyang requested changes
You can't do this without, AT MINIMUM, some performance analysis, atomics are very expensive when there is contention, and you are affected EVERY tensor allocation that happens.

2024-12-18 15:15 UTC, ezyang commented
I read the longer description in the Phabricator diff. I don't understand why you need a unique id. I assume ET knows about deallocation events. Then you can easily tell if a storage is the same as an old one or not by deduping at ingestion time. No reason to have an atomic.

2024-12-18 17:54 UTC, shengfukevin commented
> I read the longer description in the Phabricator diff. I don't understand why you need a unique id. I assume ET knows about deallocation events. Then you can easily tell if a storage is the same as an old one or not by deduping at ingestion time. No reason to have an atomic.

ET only records ATen ops and collectives. It does not know the deallocation events. So ET replay analyzes the execution graph to find out the last node that access the tensor storage, which is identified by storage id. When the last node got executed, ET replay releases the tensor storage. So if storage id is not unique, this implementation does not work.

2024-12-18 17:57 UTC, shengfukevin commented
> You can't do this without, AT MINIMUM, some performance analysis, atomics are very expensive when there is contention, and you are affected EVERY tensor allocation that happens.

I can add some stress tests. However, as fas as I know, PyTorch only use one thread for FWD pass and one thread for BWD pass. So the chance to have the contention is very low. Do I miss any other use case?

2024-12-18 19:09 UTC, ezyang commented
Multithreaded inference from C++ is the notable one

2024-12-18 19:10 UTC, ezyang commented
Where is the current ET implementation. How are you instrumenting and what factor performance penalty are you willing to pay

2025-01-02 23:17 UTC, swolchok commented
I agree this is likely to be relatively expensive. On x86_64, `inc` is already relatively expensive, and `lock inc` is more so. See uops.info:
 
![image](https://github.com/user-attachments/assets/1e4b5ed0-a27e-467d-a1b6-a997ec99ecf5)

and this is *without* considering the impact of contention.

2025-04-03 23:35 UTC, closed without merging