c++ strip_function_call: 49.12 -> 47.77
pytorch/pytorch pull request #143063
Opened 2024-12-11 22:30 UTC by aorenste

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

See #143056 for overall docs.

This PR: Convert `strip_function_call()` into C++

2024-12-12 17:22 UTC, jansel requested changes
Should we delete the old versions of these functions?

2024-12-14 03:04 UTC, jansel approved these changes

2024-12-22 03:42 UTC, aorenste commented
@pytorchbot merge

2024-12-22 06:38 UTC, closed without merging

2025-02-12 03:28 UTC, ezyang commented
@aorenste I think it's actually important to implement the 2byte/4byte case, they get exercised in Kokoro TTS

```
#0  0x00007ffff7c8bdac in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff7c3e886 in raise () from /lib64/libc.so.6
#2  0x00007ffff7c28833 in abort () from /lib64/libc.so.6
#3  0x00007ffff4ad4ed0 in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#4  0x00007ffff4ad340c in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#5  0x00007ffff4ad345e in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#6  0x00007ffff4ad3650 in __cxxabiv1::__cxa_throw (obj=0xb594f60, tinfo=0x7ffff4bf0560 <typeinfo for std::runtime_error>, 
    dest=0x7ffff4ae0242 <std::runtime_error::~runtime_error()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:98
#7  0x00007ffea62c38a2 in torch::dynamo::(anonymous namespace)::_strip_function_call(_object*, _object* const*, long) [clone .cold]
    () from /data/users/ezyang/a/pytorch/torch/lib/libtorch_python.so
#8  0x00000000004fccc4 in cfunction_vectorcall_FASTCALL (func=0x7ffea7319670, args=0x7ffc746b7b90, nargsf=<optimized out>, 
    kwnames=<optimized out>) at /usr/local/src/conda/python-3.10.13/Objects/methodobject.c:430
#9  0x00000000004ed2bf in _PyObject_VectorcallTstate (kwnames=0x0, 
    kwnames@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, nargsf=<optimized out>, 
    args=0x7ffc746b7b90, args@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
    callable=0x7ffea7319670, callable@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
    tstate=0x7743e0) at /usr/local/src/conda/python-3.10.13/Include/cpython/abstract.h:123
#10 PyObject_Vectorcall (kwnames=0x0, 
    kwnames@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, nargsf=<optimized out>, 
    args=0x7ffc746b7b90, args@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
    callable=0x7ffea7319670, callable@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>)
    at /usr/local/src/conda/python-3.10.13/Include/cpython/abstract.h:123
#11 call_function (kwnames=0x0, 
    kwnames@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, oparg=<optimized out>, 
    pp_stack=<synthetic pointer>, 
    pp_stack@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
    trace_info=0x7fffffffa0d0, 
    trace_info@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, tstate=<optimized out>)
    at /usr/local/src/conda/python-3.10.13/Python/ceval.c:5893
#12 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7ffc746b7a00, throwflag=<optimized out>)
    at /usr/local/src/conda/python-3.10.13/Python/ceval.c:4213
#13 0x00000000004fcadf in _PyEval_EvalFrame (

```

Also the current error message is very bad

```
I0211 19:23:50.270000 3175207 torch/fx/experimental/symbolic_shapes.py:3288] [1/0_1] create_env                                       
I0211 19:23:51.816000 3175207 torch/_dynamo/output_graph.py:1460] [1/0_1] Step 2: calling compiler function eager                     
I0211 19:23:51.816000 3175207 torch/_dynamo/output_graph.py:1465] [1/0_1] Step 2: done compiler function eager                        
I0211 19:23:52.323000 3175207 torch/fx/experimental/symbolic_shapes.py:4670] [1/0_1] produce_guards                                   
terminate called after throwing an instance of 'std::runtime_error'                                                                   
  what():  unimplemented - 2byte
```

2025-02-13 15:20 UTC, colesbury commented on torch/csrc/dynamo/init.cpp
> +    return THPObjectPtr::none();
You can't return `None` if you are setting an exception. If you are using the Python C API directly, you must return `NULL` when setting an exception.

(Or use pybind11, or PyTorch's error handling: https://github.com/pytorch/pytorch/blob/main/torch/csrc/README.md#exceptions)

2025-02-18 18:51 UTC, aorenste commented on torch/csrc/dynamo/init.cpp
> +  // TODO: what about endianism?
This function is fairly hot so using a function that converts the string to UTF8 isn't a great solution - similarly I originally used pybind11 and it was noticeably slower than the raw C++ version. I'll fix the other issues you and @ezyang brought up.

2025-02-19 00:31 UTC, colesbury commented on torch/csrc/dynamo/init.cpp
> +  // TODO: what about endianism?
The typical case is that the string is already represented as UTF-8 and `PyUnicode_AsUTF8AndSize` doesn't have to do any conversion or copying.

2025-02-19 01:19 UTC, aorenste commented on torch/csrc/dynamo/init.cpp
> +  // TODO: what about endianism?
That can't be right - the existence of `PyUnicode_[124]BYTE_DATA` as a trivial static cast (defined in unicodeobject.h) implies that the underlying internal representation must be fixed-width. Looking at the source code for `PyUnicode_AsUTF8AndSize` (in unicodeobject.c) it looks like it does a conversion and caches it.

2025-02-19 19:20 UTC, colesbury commented on torch/csrc/dynamo/init.cpp
> +  // TODO: what about endianism?
The guard names are basically Python expressions, right? The vast majority of these names will only contain ASCII characters. In that case, when the string is constructed, it will use the 1-byte encoding and set `ascii` bit:

https://github.com/python/cpython/blob/ccf17323c218a2fdcf7f4845d3eaa74ebddefa44/Include/cpython/unicodeobject.h#L141-L144

That also means that the `utf8` pointer just points to the string's internal data. Every ASCII string is also a valid UTF-8:

https://github.com/python/cpython/blob/73801864d866c76ae26a120b9db9de21b08f8b50/Objects/unicodeobject.c#L15521-L15525

2025-02-19 19:33 UTC, aorenste commented on torch/csrc/dynamo/init.cpp
> +  // TODO: what about endianism?
Good points.

ezyang's original comment shows that at least sometimes it's not ASCII - and it's not like the code is significantly more complex to handle the multi-byte encodings (handling it as UTF8 would basically be the same code, just without the template arg and T specialized as uint8)