[WIP] Add definition interval [a,b] to Beta distribution instead of forcing [0,1]
pytorch/pytorch pull request #143110
Opened 2024-12-12 10:17 UTC by AlboAlby00

Fixes #142825
This PR extends the  Beta distribution with two additional parameters "high" and "low".
`  def __init__(
        self, concentration1, concentration0, low=0.0, high=1.0, validate_args=None
    )` 
The Beta distribution can be defined on custom intervals and not only on [0,1], like it is possible to do with scipy.stats.beta.
I am facing some numerical instabilities, I will try to fix the problem in the next days.

2024-12-12 11:45 UTC, AlboAlby00 commented
@pytorchbot label "module: distributions"
@pytorchbot label "release notes: distributions"

2024-12-12 15:33 UTC, fritzo requested changes
Hmm, this implementation will slow down all existing users of `Beta` and increase their memory footprint. I'd lean towards recommending `TransformedDistribution`, or if we really want to add `lo,hi` parameters, to pythonically branch on the special case of `(0,1)`, for example:
```python
@property
def mode(self):
  result = self._dirichlet.mode[..., 0]
  if not (isinstance(self._scale, number) and self._scale == 1):
      result = result * self.scale
  if not (isinstance(self._location, number) and self._location == 0):
      result = result + self._location
  return result 
```
That seems like the minimum bar to avoid performance regression.  Do we want that much additional code complexity?  Should we instead focus effort on making `TransformedDistribution` more feature rich?

2024-12-12 21:39 UTC, AlboAlby00 commented
> Hmm, this implementation will slow down all existing users of `Beta` and increase their memory footprint. I'd lean towards recommending `TransformedDistribution`, or if we really want to add `lo,hi` parameters, to pythonically branch on the special case of `(0,1)`, for example:
> ```python
> @property
> def mode(self):
>   result = self._dirichlet.mode[..., 0]
>   if not (isinstance(self._scale, number) and self._scale == 1):
>       result = result * self.scale
>   if not (isinstance(self._location, number) and self._location == 0):
>       result = result + self._location
>   return result 
> ```
> That seems like the minimum bar to avoid performance regression.  Do we want that much additional code complexity?  Should we instead focus effort on making `TransformedDistribution` more feature rich?

Thanks for the review. 
I would still lean towards adding the low and high parameters fixing the increased memory footprint / computation time implementing the requested changes.
The way I see it, Beta should be defined with 4 parameters ("concentration1, concentration0, low, high") since the scale and location are conceptually part of the distribution the same way they are for the Uniform distribution, which could be implemented only on (0,1) as well.

2024-12-13 00:38 UTC, fritzo commented
Well if others agree, I guess it seems fine to add (low,high) arguments as long as we short-circuit to avoid tensor computations in the default case (low=0,high=1). In Pyro we do this with [helper functions](https://github.com/pyro-ppl/pyro/blob/d6ebf5a5f6a796b5d48efd9bd800995fbce88a02/pyro/distributions/util.py#L188-L211) `is_identically_zero()` and `is_identically_one()`, which you might consider copying into `torch.distributions.utils`.

Zooming out, I see this design question along the spectrum of "do we want a few things with many features or many things with few features". A major advantage of the latter compositional approach is that machinery scales across implementations. For example, you can implement a smarter `.entropy()` here, or implement it once in `TransformedDistribution(-,Affine)` and get it for free in all affine transformed distributions.  You can make the `kl_divergence()` computation smarter for `Beta` (which btw is missing from this PR), or you can do it once for `TransformedDistribution(-,AffineDistribution)`. Simpler parts means they are easier to override: I can implement a moment matched continuous version of `Beta` and pass that through `TransformedDistribution(-,AffineTransform)` in place of `Beta`, whereas after this PR it will be more difficult to customize subclasses or substitutes for `Beta`.

On the other hand, as a modeling practitioner, I often wish `Beta` were more flexible, or that it were easier to use `TransformedDistribution`. 🤷

2024-12-17 01:19 UTC, AlboAlby00 commented
@fritzo 
The code turned to out to be way messier than I thought, now I am of the same idea that it would be better to extend the TransformedDistribution. I created[ a different PR](https://github.com/pytorch/pytorch/pull/143349/files).

2025-03-17 02:07 UTC, closed without merging