Enable AArch64 CI scripts to be used for local dev
pytorch/pytorch pull request #143190
Opened 2024-12-13 11:49 UTC by jondea

- Allow user to specify custom ComputeLibrary directory, which is then built rather than checking out a clean copy
- Remove `setup.py clean` in build. The CI environment should be clean already, removing this enables incremental rebuilds
- Use all cores for building ComputeLibrary

Mostly a port of https://github.com/pytorch/builder/pull/2028 with the conda part removed, because aarch64_ci_setup.sh has changed and can now handle being called twice.

2025-01-03 10:45 UTC, jondea commented
@pytorchbot label "topic: not user facing"

2025-02-25 14:43 UTC, jondea commented
Can I get a review on this please?

2025-02-28 14:21 UTC, annop-w commented
@pytorchbot label "module: arm"

2025-04-30 09:45 UTC, fadara01 commented
@pytorchbot label "ciflow/linux-aarch64"

2025-04-30 10:18 UTC, fadara01 commented
@malfet - could you please approve the CI? We don't have enough permissions the approve it.

2025-04-30 10:25 UTC, aditew01 commented
@pytorchbot rebase

2025-04-30 10:26 UTC, aditew01 approved these changes

2025-04-30 10:45 UTC, fadara01 commented
@pytorchbot label "ciflow/linux-aarch64"

2025-04-30 10:46 UTC, fadara01 commented
Oh I now see the "Enable CI Workflow" button after the rebase, thanks @aditew01!

2025-04-30 10:54 UTC, fadara01 requested changes
Generally LGTM, thank you!
This should improve dev workflow for devs trying to perfectly mirror pytorch's manylinux builds, without changing behavior in CI.

... just the minor question about the need `ACL_SOURCE_DIR`

2025-04-30 10:54 UTC, fadara01 commented on .ci/aarch64_linux/aarch64_wheel_ci_build.py
> +    acl_checkout_dir = os.getenv("ACL_SOURCE_DIR", "ComputeLibrary")
I don't see why the `ACL_SOURCE_DIR` is needed here. 
This script is meant to be run inside the docker container and one can make it pick up their custom local ACL directory by mounting the docker container to it (along with the other changes introduced in this PR).

For development outside docker, isn't `ACL_ROOT_DIR` in `setup.py` [here](https://github.com/pytorch/pytorch/blob/main/setup.py#L179) enough?

2025-05-15 17:21 UTC, malfet approved these changes

2025-05-20 07:19 UTC, jondea commented on .ci/aarch64_linux/aarch64_wheel_ci_build.py
> +    acl_checkout_dir = os.getenv("ACL_SOURCE_DIR", "ComputeLibrary")
The use case is that you have a local dev container already running, and you want to swap out the ComputeLibrary directory. You can't restart the container without losing a whole load of state.

2025-05-20 07:30 UTC, fadara01 commented on .ci/aarch64_linux/aarch64_wheel_ci_build.py
> +    acl_checkout_dir = os.getenv("ACL_SOURCE_DIR", "ComputeLibrary")
Got it, thanks!

2025-05-20 07:30 UTC, fadara01 approved these changes

2025-05-22 19:53 UTC, fadara01 commented
@pytorchbot merge

2025-05-23 09:21 UTC, fadara01 commented
@pytorchbot rebase

2025-05-23 09:38 UTC, fadara01 commented
@pytorchbot merge

2025-05-23 12:10 UTC, closed without merging