build with np2 and compatible scipy & numba versions
pytorch/pytorch pull request #143234
Opened 2024-12-13 23:36 UTC by haifeng-jin

This is a follow-up for https://github.com/pytorch/pytorch/pull/141925.

The installed version of SciPy and Numba were not compatible with 2.0.2 while building.
This PR specifies compatible versions of SciPy and Numba to install.

2024-12-13 23:37 UTC, haifeng-jin commented
@pytorchbot label "topic: not user facing"

2024-12-13 23:44 UTC, malfet requested changes
PyTorch build system does not depend on neither scipy nor numba, so not sure why are you installing those

2024-12-15 18:26 UTC, Skylion007 commented
@haifeng-jin You want to update the docker requirements file: https://github.com/pytorch/pytorch/blob/e0bdae7884aed09d9e3f1a3f7a53c095e74a9aff/.ci/docker/requirements-ci.txt#L248 and the one for macos I believe

2024-12-16 17:56 UTC, haifeng-jin commented
Closing the PR since compatible versions of SciPy and Numba are not needed for the build.

2024-12-16 17:56 UTC, closed without merging