[ROCm] Inductor-gemm tuning
pytorch/pytorch pull request #143286
Opened 2024-12-16 13:12 UTC by jataylo

Adds tuning options for extra_args in mm_common.py on ROCm side we can supply specific triton tuning args such as waves_per_eu, kpack, matrix_instr_nonkdim. This PR also introduces behavior to allow tuning for GROUP_M in triton gemm case.

Also brings in specific tuning for general ROCm gemm case.

2024-12-17 14:17 UTC, jataylo commented
@pytorchbot rebase

2024-12-19 10:40 UTC, jataylo commented
Passing now just need to take a look at the lint.

2024-12-19 20:56 UTC, jansel requested changes
High level:

Can we refactor the mm config stuff to be a bit more extensible.   

We could move some of the config choices to V.choices to allow it to be overridden from out of tree.

Rather than `if hip` everywhere, maybe we could have an abstract class representing mm heuristics and subclasses for different devices.

2024-12-19 21:00 UTC, jataylo commented
> High level:
> 
> Can we refactor the mm config stuff to be a bit more extensible.
> 
> We could move some of the config choices to V.choices to allow it to be overridden from out of tree.
> 
> Rather than `if hip` everywhere, maybe we could have an abstract class representing mm heuristics and subclasses for different devices.

I think a refactor makes sense but due to how active this file is I'm worried if we do this then features may be disabled on ROCm by default by being hidden away in our own subclass, if we had to reimplement everything ourselves it would be hard to keep up.

2024-12-19 23:10 UTC, jansel commented
The files can still be in torch and tested by CI, I'm just hoping for a bit better code organization.  I don't think these files are changing that often, especially over the next few weeks with the holidays.

2025-02-12 16:45 UTC, LunNova commented
Is this likely to fix triton mm being strangely slow on MI100/gfx908?

```
SingleProcess AUTOTUNE benchmarking takes 10.1072 seconds and 0.0007 seconds precompiling for 39 choices
AUTOTUNE mm(1024x4096, 4096x1024)
  mm 0.1752 ms 100.0% 
  triton_mm_22482 0.2426 ms 72.2% ACC_TYPE='tl.float32', ALLOW_TF32='False', BLOCK_K=32, BLOCK_M=64, BLOCK_N=64, B_PROLOGUE_CAST_TYPE=None, EVEN_K=True, GROUP_M=8, matrix_instr_nonkdim=0, num_stages=2, num_warps=4
  triton_mm_22483 0.2632 ms 66.6% ACC_TYPE='tl.float32', ALLOW_TF32='False', BLOCK_K=32, BLOCK_M=64, BLOCK_N=64, B_PROLOGUE_CAST_TYPE=None, EVEN_K=True, GROUP_M=8, matrix_instr_nonkdim=16, num_stages=2, num_warps=4
  triton_mm_22492 0.2659 ms 65.9% ACC_TYPE='tl.float32', ALLOW_TF32='False', BLOCK_K=64, BLOCK_M=64, BLOCK_N=128, B_PROLOGUE_CAST_TYPE=None, EVEN_K=True, GROUP_M=8, matrix_instr_nonkdim=0, num_stages=2, num_warps=4
  triton_mm_22488 0.2680 ms 65.4% ACC_TYPE='tl.float32', ALLOW_TF32='False', BLOCK_K=32, BLOCK_M=64, BLOCK_N=128, B_PROLOGUE_CAST_TYPE=None, EVEN_K=True, GROUP_M=8, matrix_instr_nonkdim=0, num_stages=2, num_warps=4
  triton_mm_22480 0.2706 ms 64.8% ACC_TYPE='tl.float32', ALLOW_TF32='False', BLOCK_K=16, BLOCK_M=64, BLOCK_N=64, B_PROLOGUE_CAST_TYPE=None, EVEN_K=True, GROUP_M=8, matrix_instr_nonkdim=0, num_stages=2, num_warps=4
  ```

2025-02-12 17:02 UTC, jataylo commented
> Is this likely to fix triton mm being strangely slow on MI100/gfx908?
> 
> ```
> SingleProcess AUTOTUNE benchmarking takes 10.1072 seconds and 0.0007 seconds precompiling for 39 choices
> AUTOTUNE mm(1024x4096, 4096x1024)
>   mm 0.1752 ms 100.0% 
>   triton_mm_22482 0.2426 ms 72.2% ACC_TYPE='tl.float32', ALLOW_TF32='False', BLOCK_K=32, BLOCK_M=64, BLOCK_N=64, B_PROLOGUE_CAST_TYPE=None, EVEN_K=True, GROUP_M=8, matrix_instr_nonkdim=0, num_stages=2, num_warps=4
>   triton_mm_22483 0.2632 ms 66.6% ACC_TYPE='tl.float32', ALLOW_TF32='False', BLOCK_K=32, BLOCK_M=64, BLOCK_N=64, B_PROLOGUE_CAST_TYPE=None, EVEN_K=True, GROUP_M=8, matrix_instr_nonkdim=16, num_stages=2, num_warps=4
>   triton_mm_22492 0.2659 ms 65.9% ACC_TYPE='tl.float32', ALLOW_TF32='False', BLOCK_K=64, BLOCK_M=64, BLOCK_N=128, B_PROLOGUE_CAST_TYPE=None, EVEN_K=True, GROUP_M=8, matrix_instr_nonkdim=0, num_stages=2, num_warps=4
>   triton_mm_22488 0.2680 ms 65.4% ACC_TYPE='tl.float32', ALLOW_TF32='False', BLOCK_K=32, BLOCK_M=64, BLOCK_N=128, B_PROLOGUE_CAST_TYPE=None, EVEN_K=True, GROUP_M=8, matrix_instr_nonkdim=0, num_stages=2, num_warps=4
>   triton_mm_22480 0.2706 ms 64.8% ACC_TYPE='tl.float32', ALLOW_TF32='False', BLOCK_K=16, BLOCK_M=64, BLOCK_N=64, B_PROLOGUE_CAST_TYPE=None, EVEN_K=True, GROUP_M=8, matrix_instr_nonkdim=0, num_stages=2, num_warps=4
> ```

These optimisations are largely being targeted for MI300, I doubt it will make a significant improvement for MI100. This is something that would likely have to be addressed at the triton level. It's could be worth running some of the standalone gemm benchmarks available in the triton repository and raising an issue there for MI100 perf if it seems unsatisfactory.

2025-03-04 09:53 UTC, closed without merging