[WIP][export][dynamic shapes] log provenance for locals & symbols for non-strict
pytorch/pytorch pull request #143378
Opened 2024-12-17 08:07 UTC by pianpwk

Adds logging for `TORCH_LOGS="+dynamic"` so when guards / runtime asserts are added, or a data-dependent error is raised, the relevant user code with local values & symbols are logged, e.g.

Runtime assert:
```
I1217 00:04:17.641000 1064362 torch/fx/experimental/symbolic_shapes.py:6355] eval s0 - (Mod(s0, 8)) + 8 < s0*(s0 - (Mod(s0, 8)) + 8) [guard added] (_prims_common/__init__.py:501 in should_swap), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="s0 - (Mod(s0, 8)) + 8 < s0*(s0 - (Mod(s0, 8)) + 8)"
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6303] /home/pianpwk/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py(665)forward()
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6304]         attn_output = torch.nn.functional.scaled_dot_product_attention(
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6304]             query_states,
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6304]             key_states,
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6304]             value_states,
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6304]             attn_mask=causal_mask,
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6304]             dropout_p=self.attention_dropout if self.training else 0.0,
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6304] 
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6306] Values during FakeTensor propagation:
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6310] query_states: Tensor(shape: torch.Size([1, 32, s0, 128]),stride: (4096*s0, 128*s0, 128, 1), storage_offset: 0)
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6310] key_states: Tensor(shape: torch.Size([1, 32, s0, 128]),stride: (4096*s0, 128*s0, 128, 1), storage_offset: 0)
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6310] value_states: Tensor(shape: torch.Size([1, 32, s0, 128]),stride: (4096*s0, 128*s0, 128, 1), storage_offset: 0)
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6310] causal_mask: Tensor(shape: torch.Size([1, 1, s0, s0]),stride: (s0**2, s0**2, s0, 1), storage_offset: 0)
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6312] 
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6312] Symbols:
I1217 00:04:17.643000 1064362 torch/fx/experimental/symbolic_shapes.py:6315] s0: L['args'][0][0].size()[1]
```

Data-dependent error:
```
I1217 00:07:18.012000 1082692 torch/fx/experimental/symbolic_shapes.py:6303] /data/users/pianpwk/pytorch/test_max_lucy_repro.py(21)forward()
I1217 00:07:18.012000 1082692 torch/fx/experimental/symbolic_shapes.py:6304]         large_resized = large.narrow(0, 0, A1).narrow(1, 0, A2)
I1217 00:07:18.012000 1082692 torch/fx/experimental/symbolic_shapes.py:6304] 
I1217 00:07:18.012000 1082692 torch/fx/experimental/symbolic_shapes.py:6306] Values during FakeTensor propagation:
I1217 00:07:18.012000 1082692 torch/fx/experimental/symbolic_shapes.py:6310] large: Tensor(shape: torch.Size([u2, u3]),stride: (Max(1, u3), 1), storage_offset: 0)
W1217 00:07:18.012000 1082692 torch/fx/experimental/symbolic_shapes.py:6384] failed during evaluate_expr(Eq(Max(1, u3), u1), hint=None, size_oblivious=True, forcing_spec=False
E1217 00:07:18.012000 1082692 torch/fx/experimental/recording.py:299] failed while running evaluate_expr(*(Eq(Max(1, u3), u1), None), **{'fx_node': False, 'size_oblivious': True})
```

2024-12-17 16:47 UTC, avikchaudhuri approved these changes

2024-12-18 19:18 UTC, ezyang requested changes
I see this is logging at INFO level. This is probably too much spam for a text log. Will write more shortly.

2024-12-18 19:20 UTC, ezyang commented
Can you walk me through the intended user story for interacting with this? My experience is that more than one log line per guard at INFO level overwhelms the logs and users can no longer find what they need. Here it is very important to be designing for the hypothetical HTML viewer / tlparse-like view.

2025-01-30 18:09 UTC, pianpwk commented on torch/fx/experimental/symbolic_shapes.py
> +                self._log_guard("eval", g, forcing_spec=forcing_spec)
moving these to log the locals/symbolic state before the guard is added, to avoid replacements/specialization erasing the state. With logging after, with a guard like `s0 == 4`, we'd just log FakeTensors with shape [4] instead of [s0].

2025-01-30 18:14 UTC, pianpwk commented
> Can you walk me through the intended user story for interacting with this? My experience is that more than one log line per guard at INFO level overwhelms the logs and users can no longer find what they need. Here it is very important to be designing for the hypothetical HTML viewer / tlparse-like view.

@ezyang Ah that makes sense. I just updated to log to tlparse (and the CLI report) instead.

2025-02-01 00:24 UTC, bobrenjc93 commented on torch/export/_draft_export.py
> +            "propagate_real_tensors (dtrace)",
my understanding of dtrace is it's by default off, so it feels redundant to have dtrace in the log name.

cc @angelayi can't this just be `propagate_real_tensors`?

or if this really is different than that in a meaningful way, maybe we can have a more descriptive name like `propagate_real_tensors_provenance`

2025-02-01 00:26 UTC, bobrenjc93 commented on torch/fx/experimental/symbolic_shapes.py
> +        result: dict[str, Any] = {
should this be a dataclass? eg. something like 

```
@dataclass
class FrameLocalResult:
    loc: Optional[str] = None
    locals: Dict[str, Any] = field(default_factory=dict)
    symbols: Dict[str, str] = field(default_factory=dict)
```

2025-02-01 00:27 UTC, bobrenjc93 approved these changes
Good work! Bonus points if you extract this out into its own module and add some unit tests. Feel free to stack on top if easier.

2025-02-03 17:47 UTC, angelayi commented on torch/export/_draft_export.py
> +            "propagate_real_tensors (dtrace)",
I guess @pianpwk wants to distinguish between trace_structured propagate_real_tensors vs. dtrace_structured propagate_real_tensors, because from a log parser, both would show up if we turn on dtrace_structured, and these two lines would then look the same. +1 for a more detailed name (without spaces :P ), `propagate_real_tensors_provenance` or something like `propagate_real_tensors_with_locals`

2025-02-03 23:55 UTC, pianpwk commented on torch/export/_draft_export.py
> +            "propagate_real_tensors (dtrace)",
Yep, that's the unfortunate reason for it. I'll go with the more detailed name.

2025-02-03 23:57 UTC, pianpwk commented on torch/fx/experimental/symbolic_shapes.py
> +        return result
Hm I'll take a look. This is really only needed for formatted calls where the lineno doesn't capture the entire call & local variables, like
```
f(
    a,
    b,
)
```

2025-02-03 23:57 UTC, pianpwk commented on torch/fx/experimental/symbolic_shapes.py
> +                                },
No, but I guess I wasn't sure what source to use for those. That might be more involved...

2025-02-04 00:01 UTC, angelayi commented on torch/fx/experimental/symbolic_shapes.py
> +                                },
Actually, for unbacked symints we have logs from create_unbacked_symbol, so it's probably fine

2025-02-07 05:46 UTC, closed without merging