Add more detail description on error for arguments
pytorch/pytorch pull request #143336
Opened 2024-12-16 23:14 UTC by nluu175

Fixes #122129 
- Added a more detail description for argument type checking error.

2024-12-16 23:17 UTC, nluu175 commented
Hi @ezyang. Since the requirement for better error is quite vague. Could you please take a look and let me know if there are any changes I need to make? Thank you!

2024-12-17 15:34 UTC, ezyang commented
How did you test?

2024-12-18 19:16 UTC, nluu175 commented
> How did you test?

Hello! I'm sorry for missing the test. I made a new commit with a test added (successfully tested in new local build).

2025-01-24 16:16 UTC, ezyang requested changes
Unfortunately, I think this advice over-triggers. For example, it will report this even when there aren't any SymInts in the arguments at all.

2025-04-24 16:39 UTC, closed without merging