[WIP] parallelize epilogue/prologue benchmarking
pytorch/pytorch pull request #143408
Opened 2024-12-17 18:50 UTC by eellison

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #143408

2025-01-17 09:18 UTC, etaf requested changes, later dismissed

2025-01-17 09:18 UTC, etaf commented on test/inductor/test_max_autotune.py
> +        x = torch.rand([128, 16], device="cuda")
Since this test suit is shared by GPUs(CUDA, XPU), suggest to use `GPU_TYPE` instead of `cuda` here,  or decorate this case as requires_cuda.

Otherwise this case will failed on XPU. Thanks.

2025-01-17 09:18 UTC, etaf commented on test/inductor/test_max_autotune.py
> +        x = torch.rand([128, 128], dtype=torch.float16, device="cuda")
As above.

2025-01-17 23:31 UTC, jansel approved these changes

2025-01-17 23:31 UTC, jansel commented on torch/_inductor/scheduler.py
> +                        future.result()
Any concern about the ongoing parallel compiles messing up timings?

2025-01-21 19:17 UTC, shunting314 approved these changes

2025-01-21 19:17 UTC, shunting314 commented on torch/_inductor/codegen/triton.py
> +                node_names,
argument order get flipped?

2025-01-21 19:17 UTC, shunting314 commented on torch/_inductor/scheduler.py
> +                fut = None
Does this fall back to serial compilation?

2025-01-21 20:15 UTC, eellison commented on torch/_inductor/scheduler.py
> +                fut = None
yes

2025-01-21 20:18 UTC, eellison commented on torch/_inductor/scheduler.py
> +                        future.result()
We do the same thing for base mm compile + benchmarking. so not overly concerned. but open to suggestions if theres anything else we should do to handle this

2025-01-28 16:02 UTC, eellison commented on torch/_inductor/codegen/triton.py
> +                node_names,
good catch - will update in latter diff, landing now..

2025-01-28 16:02 UTC, eellison commented
@pytorchbot merge

2025-01-28 18:18 UTC, closed without merging