BF16 act, int8 WoQ GEMM with FP16 compute & accum from IPEX for m dim <= 4
pytorch/pytorch pull request #143527
Opened 2024-12-18 21:12 UTC by sanchitintel

Intel Extension for PyTorch computes GEMM for int8 WoQ case with BF16 activation when `M` dimension <=4  by converting both the activation & weights to FP16, and fusing application of scale. Then FP16 FMA instructions are used in the GEMM micro-kernel, and accumulation is also in FP16.

The current approach in PyTorch is using FP32 compute & FP32 accum for this case. FP16 accum is faster but has poorer accuracy.

TODO: Explore why micro-kernels based on BF16 dot production instruction `_mm512_dpbf16_ps` that use FP32 accum don't work as well.

2025-01-26 06:04 UTC, leslie-fang-intel requested changes

2025-01-26 06:04 UTC, leslie-fang-intel commented on torch/_inductor/cpu_vec_isa.py
> +        _arch_flags = _arch_flags + " -mavx512fp16"
I feels it will break all the AVX512 usage for the GCC version doesn't support `-mavx512fp16`

2025-01-26 19:48 UTC, sanchitintel commented on torch/_inductor/codegen/cpp_micro_gemm.py
> +            // Convert VLEN int8 elements to int32, and then fp32, then fp16, then apply scale
Will check, thanks

2025-01-26 19:48 UTC, sanchitintel commented on torch/_inductor/quantized_lowerings.py
> +                epilogue_creator=None if _fuse_scale(m, n) else _mul_epilogue,
It's required for correctness with FP16

2025-01-26 19:49 UTC, sanchitintel commented on torch/_inductor/cpu_vec_isa.py
> +        _arch_flags = _arch_flags + " -mavx512fp16"
Oh, good point!

2025-02-05 17:24 UTC, sanchitintel commented on torch/_inductor/codegen/cpp_micro_gemm.py
> +            // Convert VLEN int8 elements to int32, and then fp32, then fp16, then apply scale
Caching weight here wouldn't help since it wouldn't be reused (this kernel would only be called for M <=4, and n is currently always equal to `block_n` anyway).

However caching `A` converted to FP16 just after this line would help:

https://github.com/pytorch/pytorch/blob/616ac94175216afe8dfb612e2caf7a5ddf01db7e/torch/_inductor/codegen/cpp_gemm_template.py#L222

I tried doing so after adding a method `CppTemplateKernel.to_half`, but template codegen fails without even throwing any exception:

```
    def to_half(self, node) -> ir.View:
        node = wrap_with_tensorbox(node)
        return L.to_dtype(node, torch.float16).data
```

2025-05-07 02:12 UTC, closed without merging