fix: all_gather_intotensor in torch.compile graph
pytorch/pytorch pull request #143700
Opened 2024-12-21 07:47 UTC by yangxiaorun

Fixes #ISSUE_NUMBER

2024-12-21 08:02 UTC, yangxiaorun commented
@pytorchbot label "topic: not user facing"

2024-12-23 14:34 UTC, zou3519 commented
@yf225 could you find someone to look at this please?

2024-12-26 20:03 UTC, yf225 requested changes

2024-12-26 20:03 UTC, yf225 commented on torch/distributed/_functional_collectives.py
> +    group=None,  # TODO add a type
I think this fix looks good, thanks!

Would you like to add a unit test similar to https://github.com/pytorch/pytorch/blob/46624359c3ccea12c288068cfa7df2c0b849a11b/test/distributed/test_inductor_collectives.py#L378-L401, but not passing in the `pg` argument?

2024-12-27 08:12 UTC, yangxiaorun commented
![image](https://github.com/user-attachments/assets/aebaa853-98b8-429a-a830-acdfc856ac11)
The flag was very confusing to me, and when I clicked in from details, I found that there were only a few simple errors in it, and I couldn't see more information. I thought there was something wrong with my use case or incorrectly initialized the UT environment until I found out that someone else's PR also had this flag. So can someone tell me exactly what he means? :)

2025-02-26 02:33 UTC, closed without merging