[Inductor] Add MPS device op overrides
pytorch/pytorch pull request #143892
Opened 2024-12-27 03:51 UTC by malfet

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Mostly dummy interface as MPS backend currently limited to a single device

2024-12-27 17:16 UTC, jansel requested changes

2024-12-27 17:16 UTC, jansel commented on torch/_inductor/codegen/common.py
> +        from . import (  # noqa: F401  # noqa: F401
Does double noqa do anything extra?

2024-12-27 17:16 UTC, jansel commented on torch/_inductor/codegen/mps_device_op_overrides.py
> +# mypy: allow-untyped-defs
Remove this and add types

2024-12-27 18:26 UTC, malfet commented on torch/_inductor/codegen/common.py
> +        from . import (  # noqa: F401  # noqa: F401
Nope, just linter being linter.. Fixed.

2024-12-27 18:26 UTC, malfet commented on torch/_inductor/codegen/mps_device_op_overrides.py
> +# mypy: allow-untyped-defs
Done

2024-12-28 00:13 UTC, jansel approved these changes

2024-12-28 02:04 UTC, malfet commented
@pytorchbot merge

2024-12-28 02:11 UTC, closed without merging