fix the adaptive_avg_pool
pytorch/pytorch pull request #143802
Opened 2024-12-24 14:34 UTC by shaoyuyoung

Fixes #143801

2024-12-24 14:43 UTC, shaoyuyoung commented
@pytorchbot label "topic: not user facing"

2024-12-24 14:52 UTC, shaoyuyoung commented
It seems that I don't have permission to request a review.
(I am very sorry that I tried the CI process of pytorch for the first time.)

2024-12-24 21:36 UTC, jansel requested changes
Minor typo, but otherwise looks good.  I approved CI for you.

2024-12-24 21:36 UTC, jansel commented on torch/_inductor/lowering.py
> +        raise RuntimeError("'adaptive_max_pool2d' not implemented for 'Long'")
```suggestion
        raise RuntimeError("'adaptive_avg_pool2d' not implemented for 'Long'")
```

2024-12-25 01:14 UTC, shaoyuyoung commented on torch/_inductor/lowering.py
> +        raise RuntimeError("'adaptive_max_pool2d' not implemented for 'Long'")
thank you for pointing out, updated.

2024-12-25 01:16 UTC, shaoyuyoung commented
Hi, @jansel .
I really appreciate that you can still help me review and point out my mistakes during the holiday. I have updated.
Merry Christmas (Eve)!

2024-12-25 05:46 UTC, jansel approved these changes

2024-12-25 05:46 UTC, jansel commented
@pytorchbot merge

2024-12-25 09:08 UTC, closed without merging