Fix fft jit ops/zzq
pytorch/pytorch pull request #143894
Opened 2024-12-27 05:54 UTC by ZhaoqiongZ

Fixes 142484

2024-12-27 05:57 UTC, ZhaoqiongZ commented
@pytorchbot label "topic: not user facing"

2024-12-27 06:01 UTC, ZhaoqiongZ commented
@pytorchbot rebase -b main

2024-12-28 13:45 UTC, mgorny commented
Thanks! I can confirm that this fixes the problem for me.

2024-12-30 03:21 UTC, jgong5 reviewed
Add UT?

2024-12-30 03:21 UTC, jgong5 commented on aten/src/ATen/native/mkl/SpectralOps.cpp
> +  }
Using `std::all` is simpler?

2025-01-02 01:32 UTC, ZhaoqiongZ commented on aten/src/ATen/native/mkl/SpectralOps.cpp
> +  }
It seems that the latest main branch of PyTorch no longer triggers the issue, even without the fix. However, the behavior for CPU and CUDA will only be consistent after applying the fix. I'm still trying to figure out what has changed

2025-01-07 07:26 UTC, ZhaoqiongZ commented
> Add UT?

test case is included in the #142484  with python test/test_ops_jit.py TestJitCPU.test_variant_consistency_jit_fft_fft2_cpu_complex64, so no new UT need for this pr

2025-01-08 01:10 UTC, ZhaoqiongZ commented on aten/src/ATen/native/mkl/SpectralOps.cpp
> +  }
Hi @jgong5 , Please review the code again, have replaced the for loop with std::all_of. 
The unit test test/test_ops_jit.py TestJitCPU.test_variant_consistency_jit_fft_fft2_cpu_complex6 already includes the necessary test case for this PR, so no additional unit tests should be needed.

2025-01-08 02:09 UTC, jgong5 approved these changes

2025-01-08 07:28 UTC, mingfeima approved these changes

2025-01-08 07:29 UTC, mingfeima commented
@pytorchbot merge

2025-01-09 07:02 UTC, ZhaoqiongZ commented
Hi @malfet , please help review the pr.

2025-01-16 21:47 UTC, malfet requested changes
Please add regression test. Also, `clone` will always copy, even when input is already contigous, wouldn't it?

2025-01-16 21:47 UTC, malfet commented on aten/src/ATen/native/mkl/SpectralOps.cpp
> +  input = input.clone(MemoryFormat::Contiguous);
Clone will always copy, even when input is contiguous, isn't it? Shouldn't it be `input.contiguous()` which is a no-op

2025-01-16 21:48 UTC, malfet commented on aten/src/ATen/native/mkl/SpectralOps.cpp
> +  input = input.clone(MemoryFormat::Contiguous);
```suggestion
  input = input.contiguous();
```

2025-01-21 03:47 UTC, ZhaoqiongZ commented on aten/src/ATen/native/mkl/SpectralOps.cpp
> +  input = input.clone(MemoryFormat::Contiguous);
yes, clone will always copy, input.contiguous() will be better to keep the original tensor if it is contiguous already!

2025-01-21 03:51 UTC, ZhaoqiongZ commented
Hi @malfet , for regression test, what kind of test do I need?
Let me explain a little background about this pr and the issue related.
In MKL 2024.1.0, data with stride=0 was accepted, but this behavior was incorrect. Therefore, MKL 2024.2.0 modified this behavior, which exposed previously unnoticed issues, causing the related issue #142484  to fail. This change converts non-contiguous tensors to contiguous ones to ensure that tensors with stride=0 due to broadcasting or other operations become contiguous, thus eliminating the stride=0 condition.

2025-01-21 05:27 UTC, mingfeima commented
@ZhaoqiongZ please update test cases as well.

2025-04-21 09:35 UTC, closed without merging