cpp_wrapper: Move #includes to per-device header files
pytorch/pytorch pull request #143909
Opened 2024-12-27 15:35 UTC by benjaminglass1

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #144349
* #144293
* #144002
* __->__ #143909

This prepares us for the next PR in the stack, where we introduce pre-compiled per-device header files to save compilation time.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

Differential Revision: [D67938955](https://our.internmc.facebook.com/intern/diff/D67938955)

2024-12-31 19:14 UTC, benjaminglass1 commented
@desertfire For your consideration: would it also be worth doing this for things built in non-cpp_wrapper AOTI mode? The precompiled header seems to be a big enough boost to make it potentially worthwhile.

2025-01-02 16:12 UTC, desertfire approved these changes

2025-01-02 16:12 UTC, desertfire commented on torch/csrc/inductor/cpp_wrapper/xpu.h
> +#ifndef TORCH_CSRC_INDUCTOR_CPP_WRAPPER_CUDA
`CUDA`->`XPU`

2025-01-02 16:12 UTC, desertfire commented on torch/csrc/inductor/cpp_wrapper/xpu.h
> +#include <torch/csrc/inductor/aoti_torch/generated/c_shim_cuda.h>
`cuda`->`xpu`

2025-01-02 16:12 UTC, desertfire commented on torch/_inductor/codegen/cpp_wrapper_cpu.py
> +                #include <torch/csrc/inductor/aoti_runtime/arrayref_tensor.h>
FYI, `arrayref_tensor.h` and `thread_local.h` should also conditional depends on whether we turn on the array-ref mode. Refactor them out should also help to cut the compilation time.

2025-01-02 16:13 UTC, desertfire commented
> @desertfire For your consideration: would it also be worth doing this for things built in non-cpp_wrapper AOTI mode? The precompiled header seems to be a big enough boost to make it potentially worthwhile.

Reasonable to do something similar for AOTI

2025-01-02 17:16 UTC, benjaminglass1 commented
> > @desertfire For your consideration: would it also be worth doing this for things built in non-cpp_wrapper AOTI mode? The precompiled header seems to be a big enough boost to make it potentially worthwhile.
> 
> Reasonable to do something similar for AOTI

@desertfire I think I'm going to get the `array_ref` work done in this PR, then do the AOTI work in a follow-on. The further I've dug into this, the more I've realized that the AOTI work will take some design effort, since the build step is implemented differently.

2025-01-03 17:59 UTC, benjaminglass1 commented
After I actually did the AOT implementation, the changeset wasn't as large as I expected, so I've squashed everything back together into two total PRs. @desertfire Please re-review this!

2025-01-07 21:31 UTC, malfet requested changes
Haven't looked thru the entire codebase, but please update it to use `#pragma once` as an include guard

2025-01-07 21:31 UTC, malfet commented on .lintrunner.toml
> +    '--pattern=#include <pybind11\/(^|[^(gil\.h)])',
Why this change is needed?

2025-01-07 21:31 UTC, malfet commented on torch/csrc/inductor/cpp_wrapper_array_ref/implementation.h
> +#define TORCH_CSRC_INDUCTOR_CPP_WRAPPER_ARRAY_REF_IMPLEMENTATION
Use `#pragma once` as a modern guard (I remember there were a document somewhere against `#ifndef` guards, which are really old)
```suggestion
#pragma once
```

2025-01-07 21:41 UTC, benjaminglass1 commented on .lintrunner.toml
> +    '--pattern=#include <pybind11\/(^|[^(gil\.h)])',
@malfet The `cpp_wrapper` code doesn't depend on the full `pybind11` library; it only needs the GIL handling classes. This linter ensures that we include all our `pybind11` class specializations when including any `pybind11` header, but those specializations aren't relevant to the GIL handling header specifically. Additionally, including the specializations would include the entire `pybind11` header, which is what we're trying to avoid here (for compile-time reasons).

This change just adds an exception for including the GIL header specifically.

2025-01-07 21:43 UTC, benjaminglass1 commented on torch/csrc/inductor/cpp_wrapper_array_ref/implementation.h
> +#define TORCH_CSRC_INDUCTOR_CPP_WRAPPER_ARRAY_REF_IMPLEMENTATION
@malfet GCC versions less than 15 display a warning that cannot be disabled when `#pragma once` is found in a precompiled header; see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64117. I figured include guards were a lesser evil than a pointless warning which wouldn't go away, but I can change this back if this is a strong preference.

2025-01-07 22:17 UTC, malfet commented on torch/csrc/inductor/cpp_wrapper_array_ref/implementation.h
> +#define TORCH_CSRC_INDUCTOR_CPP_WRAPPER_ARRAY_REF_IMPLEMENTATION
Thank you for the reference. But we hide all the warnings when torch.compiled function is invoked, aren't we? In that case I think this is fine. (unless this warning slows down compilation significnatly)

2025-01-07 22:18 UTC, benjaminglass1 commented on torch/csrc/inductor/cpp_wrapper_array_ref/implementation.h
> +#define TORCH_CSRC_INDUCTOR_CPP_WRAPPER_ARRAY_REF_IMPLEMENTATION
@malfet Will do!

2025-01-08 13:51 UTC, desertfire commented
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D67938955).

2025-01-09 19:30 UTC, desertfire commented on torch/csrc/inductor/cpp_wrapper/aoti_cpu.h
I prefer to have aoti header files under an aoti directory, maybe aoti_runtime.

2025-01-09 19:34 UTC, benjaminglass1 commented on torch/csrc/inductor/cpp_wrapper/cuda.h
@desertfire Yes. `device_internal/cuda.h` represents a set of headers included by all CUDA header possibilities (in both AOT and cpp_wrapper mode, and with or without arrayref enabled). By putting them in their own header, we don't have to maintain that list in 4 separate places.

`cuda.h` represents the header that will be precompiled, and includes the common AOT/cpp_wrapper/arrayref code, as well as this device-specific generic header.

2025-01-09 19:34 UTC, benjaminglass1 commented on torch/csrc/inductor/cpp_wrapper/aoti_cpu.h
@desertfire Can do.

2025-01-10 23:54 UTC, benjaminglass1 commented on torch/csrc/inductor/cpp_wrapper/aoti_cpu.h
@desertfire Done. I went with `aoti_include` to avoid cluttering up `aoti_runtime` further.

Additionally, I recognized that `ArrayRef` is only used on the CPU, so I was able to delete several unneeded header variants.

2025-01-14 20:01 UTC, desertfire approved these changes
In a better shape now. Ping me before you merge it. I will need to update internal build rules first.

2025-01-14 20:01 UTC, desertfire commented on torch/csrc/inductor/cpp_wrapper/array_ref.h
I don't think array_ref for cpp_wrapper is available?

2025-01-14 20:01 UTC, desertfire approved these changes

2025-01-14 22:00 UTC, benjaminglass1 commented on torch/csrc/inductor/cpp_wrapper/array_ref.h
@desertfire This one is for `cpp_wrapper_cpu_array_ref.py`, which does both AOT and non-AOT mode. I've tested that manually by setting the appropriate config variables.

2025-01-15 21:06 UTC, benjaminglass1 commented
@pytorchbot merge

2025-01-17 00:35 UTC, kit1980 commented
@pytorchbot revert -m "breaking internal builds because of removal of torch‎/_inductor‎/codegen‎/aoti_runtime‎/implementation.cpp‎" -c ghfirst

2025-01-17 00:35 UTC, kit1980 commented
@desertfire Can you help with updating the internal build files as needed?

2025-01-17 13:40 UTC, etaf commented
Hi, @benjaminglass1,  I learned this PR and find some XPU code change, so I added the `ciflow/xpu` label.

2025-01-17 15:57 UTC, desertfire commented
> @desertfire Can you help with updating the internal build files as needed?

I did make some internal changes to D67938955, but looks some tests were not triggered when I imported this PR. I will do another around of fix.

2025-01-17 16:51 UTC, benjaminglass1 commented
Re-implemented in https://github.com/pytorch/pytorch/pull/145083 to ease internal bugfixing.

2025-01-17 16:51 UTC, closed without merging