Enable readability checks
pytorch/pytorch pull request #143987
Opened 2024-12-30 15:39 UTC by cyyever

Fixes #ISSUE_NUMBER

2025-01-04 16:25 UTC, Skylion007 commented on aten/src/ATen/core/NamedTensor.h
> +  void reset() const {
Resetting it is inherently non-const, right?

2025-01-04 16:25 UTC, Skylion007 commented on c10/core/SymInt.h
> +  void release_() const {
Release is definitely non-const

2025-01-04 16:26 UTC, Skylion007 requested changes
I wouldn't enable readability const as it leads to load of false positives on non-trivial codebases unless we nolintnextline really well.

2025-01-04 16:26 UTC, Skylion007 commented on .clang-tidy
> +readability-make-member-function-const,
This has a ton of false positives when dealing with objects with pointers inside of them

2025-01-04 17:22 UTC, cyyever commented on aten/src/ATen/core/NamedTensor.h
> +  void reset() const {
It's semantically non-const, but in this case the object is not modified.

2025-01-05 18:41 UTC, Skylion007 commented on aten/src/ATen/TensorIterator.cpp
> +void TensorIteratorBase::for_each(loop2d_t loop, int64_t grain_size) const {
For foreach really now modify any internal TensorIterator states?

2025-01-05 18:41 UTC, Skylion007 commented on c10/util/Logging.cpp
> +bool InitCaffeLogging(const int* argc, char** argv) {
These can't be const right? They are initializing global loggers

2025-01-06 00:22 UTC, cyyever commented on c10/util/Logging.cpp
> +bool InitCaffeLogging(const int* argc, char** argv) {
argc is argument number, making it const is intuitive.

2025-01-06 00:26 UTC, cyyever commented on aten/src/ATen/TensorIterator.cpp
> +void TensorIteratorBase::for_each(loop2d_t loop, int64_t grain_size) const {
The internal state is not modified.

2025-01-28 05:30 UTC, cyyever commented
@pytorchbot rebase -b main

2025-06-24 02:35 UTC, cyyever commented
@pytorchbot rebase

2025-07-24 14:02 UTC, cyyever commented
@pytorchbot rebase

2025-08-23 20:34 UTC, closed without merging