Fix kl_div default behavior
pytorch/pytorch pull request #14457
Opened 2018-11-28 06:48 UTC by ailzhang

Fixes #6622 . 
We used to average over all elements for kl divergence, which is not aligned with its math definition. 
This PR corrects the default reduction behavior of KL divergence that it now naverages over batch dimension. 

- In KL, default behavior `reduction=mean` averages over batch dimension. While for most other loss functions, `reduction=mean` averages over all elements. 
- We used to support scalar tensor as well. For BC purpose, we still support it, no reduction is performed on scalar tensor. 
- I chose to not add a new reduction option, since "mean over batch dimension" is kinda special, and it only makes sense in few cases like KL. We don't want to explain why there's a option "batchmean" but it's not applicable for all other functions. I'm open to discussion on this one, as I cannot think of a perfect solution for this.

2018-11-28 07:41 UTC, ssnl reviewed
can we get an expect test that this averages along batch dimension?

2018-11-28 17:02 UTC, ailzhang commented
@SsnL  I added a test to compare it with `reduction='none'`. Let me know what you think, thanks!

2018-11-29 03:44 UTC, soumith commented on torch/nn/functional.py
> +            batches in the output, 'sum': the output will be summed, 'mean': the output will be
"the number of batches" -> "the batch size" or "the number of elements in the input batch"

2018-12-03 18:58 UTC, yf225 commented
@pytorchbot retest this please

2018-12-04 03:47 UTC, ssnl requested changes
I don't think `batch_mean` should be an enum element. It will also introduce weird behavior for the losses still defined in TH if used with `batch_mean` since if-statements there are not written with `batch_mean` in mind.

2018-12-04 03:47 UTC, SsnL commented on aten/src/ATen/core/Reduction.h
> +  BatchMean,        // Mean over batches. = Sum / batchsize
Can't you just hack this up in python? It should only be a workaround for kl_div and doesn't make sense for other losses.

2018-12-04 06:04 UTC, ssnl approved these changes
I'm now wondering if reduction='none' is wrong.. But this generally LGTM.

2018-12-04 20:26 UTC, closed without merging