Make SequentialSampler be in the same order
pytorch/pytorch pull request #15044
Opened 2018-12-11 04:42 UTC by tczhangzhi

The original function does not return a sequence that is the same as the input order. It returns a natural number sequence no matter what the user enters. We need to fix it or explain it on the documentation

2018-12-11 10:11 UTC, apaszke requested changes
The current code works as expected. What you implemented will start returning elements from the dataset, which is not what a sampler should do.

2018-12-11 17:22 UTC, fmassa commented
@apaszke is right. Do you want to send a PR fixing the documentation? The `Sampler` should return the indices in the `Dataset` to be sampled, not the sampled elements

2018-12-11 17:22 UTC, closed without merging

2018-12-12 18:13 UTC, tczhangzhi commented
Thank you for your comments, maybe my understanding is individual.

2018-12-12 18:31 UTC, tczhangzhi commented
I used to think the sequential sampler should work as following:
```
class SequentialSampler(Sampler):
    r"""Samples elements sequentially, always in the same order.
    Arguments:
        indices (sequence): a sequence of indices
    """

    def __init__(self, indices):
        self.indices = indices

    def __iter__(self):
        return iter(self.indices)

    def __len__(self):
        return len(self.indices)
```
Now I notice that you mean to pass the dataset as the parameter. Thanks.