[Deprecate THCState] Moves p2pAccessEnabled to ATen
pytorch/pytorch pull request #15155
Opened 2018-12-13 04:12 UTC by syed-ahmed

This PR moves `p2pAccessEnabled` table from THCState to ATen, and hence works towards removing THCState. Previously, we were maintaining a lookup table of p2p connections. These connections were established during cuda init in groups of 8. That is, for instance, if you have a 16 gpu system and assuming all devices can access each other via p2p in that system, the current code sets up p2p connections between {0,1,2...7} and {8,9,10,..15} during lazy initialization. if a user want a connection from 1 to 10 let's say, and even though a p2p connection from 1 to 10 might be possible, the current code would not do a P2P memcpy, since Copy.cu reads from the p2pAccessEnabled table established at initialization. 

In the following figure, left is a copy from device 0 to 10, and right is from 0 to 1, which shows that we can't do p2p memcpy from 0 to 10, due to the connections being established in groups of 8. 
![image 1](https://user-images.githubusercontent.com/8906225/49915065-a8eced00-fe48-11e8-8ba1-1ea89d6decdb.png)

The current max number of simultaneous p2p connections that a device can have is 8 and even though if this number was increased in the future, our Copy.cu code would not allow someone from copying to devices outside their groups with P2P memcpy (since we use the conditional p2p_enabled in there which reads from the global p2pAccessEnabled table).

In this PR, rather than maintaining a lookup table, I created a CUDAP2PState struct, which establishes a p2p connection during construction and releases the connection when the connection is no longer needed. I have found that there is no significant overhead of not caching if a connection was established between two devices.

2018-12-20 23:30 UTC, ezyang commented
> I have found that there is no significant overhead of not caching if a connection was established between two devices.

How did you do this performance experiment?

2018-12-20 23:31 UTC, ezyang commented on aten/src/ATen/cuda/CUDAContext.h
> +    } else if (!(p2p_enable_status)) {
Isn't this guaranteed to be true at construction

2018-12-20 23:31 UTC, ezyang commented on aten/src/ATen/cuda/CUDAContext.h
> +      c10::cuda::set_device(src_device);
Use CUDAGuard!

2018-12-20 23:34 UTC, ezyang commented on aten/src/ATen/cuda/CUDAContext.h
> +        if (err == cudaErrorPeerAccessAlreadyEnabled || err == cudaSuccess) {
This looks very dodgy. Suppose two threads create CUDAP2PState(0,1). They will both attempt to enable the P2P access. Fine, you've written code to work around it. Then on destruction of the first state, peer access will be disabled, EVEN if another thread thinks it still wants it.

2018-12-20 23:34 UTC, ezyang requested changes
Unfortunately this design is not reentrant. Can't accept.

2018-12-21 00:48 UTC, ngimel commented on aten/src/ATen/cuda/CUDAContext.h
> +          // get a cudaErrorTooManyPeers
No, it did not. It is lifted on the explorer systems. Docs erroneously don't list cudaErrorTooManyPeers as a possible return from cudaDeviceEnablePeerAccess, but the comment still says "Each device can support a system-wide maximum of eight peer connections." which is true for all systems except explorer. https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__PEER.html#group__CUDART__PEER_1g2b0adabf90db37e5cfddc92cbb2589f3

2018-12-21 04:49 UTC, syed-ahmed commented
@ezyang Thanks for the review! I'll soon followup on it.

2022-04-12 05:23 UTC, closed without merging