Fixed trivial typos in Dropout2D and Dropout3D classes
pytorch/pytorch pull request #15200
Opened 2018-12-14 02:21 UTC by bombs-kim

Fixed trivial typos in Dropout2D and Dropout3D classes

2018-12-20 21:31 UTC, ezyang approved these changes

2018-12-20 21:32 UTC, ezyang requested changes
Actually, I'm not sure these typofixes are valid. The original sentences seem grammatical, and you introduce a capitalization error by turning the comma into a period

2018-12-21 02:12 UTC, bombs-kim commented
@ezyang Thanks! I made the changed that you requested.

2018-12-21 16:04 UTC, ezyang approved these changes

2018-12-21 19:59 UTC, closed without merging