[DOC] Delete ffi documentation
pytorch/pytorch pull request #15220
Opened 2018-12-14 13:19 UTC by krishnakalyan3

Deleting FFI documentation since its deprecated.

cc: @zou3519
#15066

2018-12-15 04:04 UTC, soumith requested changes
also need to remove reference to this file from index.rst

2018-12-15 13:03 UTC, krishnakalyan3 commented
@soumith thanks for the feedback :)

2018-12-15 17:15 UTC, soumith approved these changes

2018-12-16 05:06 UTC, vishwakftw commented
This PR has been merged, can be closed now.

2018-12-16 06:55 UTC, closed without merging