Add timers to test_jit.py.
pytorch/pytorch pull request #16327
Opened 2019-01-24 18:46 UTC by ZolotukhinM

To use it one needs to set PYTORCH_TEST_TIMING environment variable: when it's
set, the test outputs time spent on each unit test, like this:
```
.__main__.TestBatched.test_batch_argmax: 0.257
.__main__.TestBatched.test_batch_cat: 0.004
.__main__.TestBatched.test_batch_elementwise_binary: 0.004
.__main__.TestBatched.test_batch_elementwise_unary: 0.002
.__main__.TestBatched.test_batch_index_select: 0.070
.__main__.TestBatched.test_batch_matmul: 0.064
.__main__.TestBatched.test_batch_mm: 0.006
.__main__.TestBatched.test_batch_select: 0.004
.__main__.TestBatched.test_batch_softmax: 0.325
.__main__.TestBatched.test_batch_sum: 0.005
```
Otherwise, the behavior should not change.

2019-01-24 18:47 UTC, ZolotukhinM commented
Hey Elias! Since you've been working on tests I thought this diff might be interesting to you - I used it to find tests taking significantly longer than others.

2019-01-24 19:04 UTC, eellison commented
Awesome, thanks @ZolotukhinM! 

 I'll look into test_batch_argmax, and it might be a good idea to print out a warning if a test runs longer than a certain threshold.

2019-01-24 19:05 UTC, eellison approved these changes

2019-01-24 20:08 UTC, apaszke requested changes
You can get the same thing if you use pytest, so why add this to our code? https://stackoverflow.com/questions/27884404/printing-test-execution-times-and-pinning-down-slow-tests-with-py-test

2019-01-24 20:59 UTC, ZolotukhinM commented
@apaszke Nice, I didn't know that, thanks! 👍 

@eellison `test_batch_argmax` is not the slowest one, it just happened to be in my example output. Here are the 10 slowest tests if you want to take a look at them:
```
19.37s call     test/test_jit.py::TestEndToEndHybridFrontendModels::test_super_resolution
9.82s call     test/test_jit.py::TestEndToEndHybridFrontendModels::test_neural_style
9.56s call     test/test_jit.py::TestBatched::test_beam_search
8.52s call     test/test_jit.py::TestEndToEndHybridFrontendModels::test_snli
4.75s call     test/test_jit.py::TestBatched::test_greedy_search
4.36s call     test/test_jit.py::TestEndToEndHybridFrontendModels::test_vae
3.25s call     test/test_jit.py::TestJit::test_export_batchnorm
2.25s call     test/test_jit.py::TestEndToEndHybridFrontendModels::test_dcgan_models
1.59s call     test/test_jit.py::TestJit::test_ge_optimized
1.10s call     test/test_jit.py::TestEndToEndHybridFrontendModels::test_time_sequence_prediction
```

2019-01-24 20:59 UTC, closed without merging

2019-03-25 23:18 UTC, eellison commented
How do you invoke this exactly? I'm trying to use --durations but unsuccessfully so far