DDP flag to remove null gradients
pytorch/pytorch pull request #16349
Opened 2019-01-25 00:03 UTC by borguz

Summary: Distributed training hangs if some parameters don't receive gradients at every step.  Diff implements a flag to remove null gradients as a workaround.

Differential Revision: D13798663

2019-01-27 18:31 UTC, pietern reviewed
Can you add a test for this as well?

2019-01-27 18:31 UTC, pietern commented on torch/nn/parallel/distributed.py
> +        remove_null_grads: set to True to support cases where some paramters may
Typo: paramters

2019-02-01 13:28 UTC, apaszke requested changes
Unfortunately this is a big can of worms, and we should be careful. This is only a partial implementation that allows us to omit a subset of parameters provided that *all processes will have the same set of unused parameters at every step*. Otherwise you'll get a deadlock/error/who knows. We should either improve the implementation or at least have a big warning sign in the docs.

2019-03-07 22:02 UTC, pietern commented
@borguz I think this one can be abandoned, right? I recall you mentioned you found a workaround for this. Was it related to zero'ing gradients and letting them all participate?

2019-03-07 22:41 UTC, borguz commented
Already closed internally, did not realize it's still open in github.

2019-03-07 22:41 UTC, closed without merging