ONNX Export Maxpool Indices
pytorch/pytorch pull request #16455
Opened 2019-01-28 19:19 UTC by lara-hdr

2019-02-04 23:21 UTC, houseroad requested changes
The change seems not keeping the semantics of the max_pool_with_indices. Could you explain why you want to flatten the indices? If you export the pytorch model like this, the exported graph won't be correct.

2019-02-04 23:46 UTC, lara-hdr commented
@houseroad , in ONNX, for the Maxpool operator the indices are computed as flatten 1-D tensor (https://github.com/onnx/onnx/blob/master/docs/Operators.md#MaxPool). 
Without this conversion, the output values won't be matching in both models.

2019-02-05 01:09 UTC, houseroad commented
Please check the doc here: https://github.com/pytorch/pytorch/issues/16742
```
Indices tensor from max pooling across the input tensor. The dimensions of indices are the same as output tensor. The values in indices of are the indices of the selected values during pooling. The indices are computed as flatten 1-D tensor, and the indices do not consider padding. So the values in indices are in [0, N x C x D1 x ... x Dn).
```

The dimension is the same as the dimension of the first output. Only the indices are computed as flatten 1d tensor. Actually, ONNX is aligned with PyTorch.

Also I am wondering whether we can discard the second output if it's not used. (Right now, it starts causing the caffe2 failing.)

2019-02-05 19:43 UTC, lara-hdr commented
This is a simple example to better explain the issue.

For **Maxpool1d(kernel=1,stride=1,return_indices=True)**, with the input **torch.ones(1,2,2)**. The computed indices are the following.
- output **indices pytorch** :
[[0,1],
 [0,1]]
 - output **indices onnx**:
[[0,1],
 [2,3]]

In the added code, my purpose was to convert the indices from one format to the other to be able to match the results.

So **flattened_indices** will have the value of each index and will be equal to :
[[0,1],
 [2,3]]

Then **s** will get the first value of each line (so 0 and 2).

And the subtraction executes : 
[[0-0,1-0],
 [2-2,3-2]]

So **indices** results to the expected output which is  :
[[0,1],
 [0,1]]


Definitely discarding the second output if it's not used would be great. However, I am not sure were to make this change since the functions in symbolic.py do not have the "return_indices" param. Could you point me to the right file to modify to do so?
Thanks

2019-02-13 19:50 UTC, ezyang commented
ping @houseroad

2019-02-13 19:53 UTC, houseroad commented
We had discussion offline. We will update the MaxPool and MaxUnpool in ONNX. But for current version, we need more change to make sure the test case passing.

2019-02-13 19:53 UTC, houseroad commented
For now, let's put this PR on hold.

2019-02-14 08:15 UTC, houseroad commented on torch/onnx/symbolic.py
> +    # convert indices to have non-flattened indices values
Could you add more comments on how to compute the non-flattened indices? It's tricky, and not easy to understand.

2019-02-14 08:16 UTC, houseroad reviewed
Looks good, but please add more comments about how to compute non-flatten indices.

2019-02-19 19:29 UTC, houseroad reviewed
Since the PR is created 20+ days ago, let's rebase to master. Otherwise, CI may give many false positive signals.

2019-02-19 19:29 UTC, houseroad commented on torch/onnx/symbolic.py
> +    # easy but hacky way to get flattened indices values
Let's just keep the comment at one place, and refer it at other places.

2019-02-19 21:38 UTC, houseroad approved these changes
Thanks a lot for the contribution. Looks good now!

2019-02-20 05:11 UTC, closed without merging

2019-04-02 23:15 UTC, ananiask8 commented
> This is a simple example to better explain the issue.
> 
> For **Maxpool1d(kernel=1,stride=1,return_indices=True)**, with the input **torch.ones(1,2,2)**. The computed indices are the following.
> 
> * output **indices pytorch** :
>   [[0,1],
>   [0,1]]
> * output **indices onnx**:
>   [[0,1],
>   [2,3]]
> 
> In the added code, my purpose was to convert the indices from one format to the other to be able to match the results.
> 
> So **flattened_indices** will have the value of each index and will be equal to :
> [[0,1],
> [2,3]]
> 
> Then **s** will get the first value of each line (so 0 and 2).
> 
> And the subtraction executes :
> [[0-0,1-0],
> [2-2,3-2]]
> 
> So **indices** results to the expected output which is :
> [[0,1],
> [0,1]]
> 
> Definitely.. Discarding the second output if it's not used would be great. However, I am not sure were to make this change since the functions in symbolic.py do not have the "return_indices" param. Could you point me to the right file to modify to do so?
> Thanks

Hello @lara-hdr . Is there any way that I could use the indices returned and have an output with the same size as the input, with the frequencies that each index appears?

I think I could do it with the original indices that ONNX returns, and using `bincount`. Is there a way to get these indices in a way that is efficient in `cuda`?

Also, if there is any alternative way to do it?

For a more specific explanation, see [here](https://discuss.pytorch.org/t/max-min-pooling-winner-counter-layer/41500).