Reset grad attribute when called using del
pytorch/pytorch pull request #16525
Opened 2019-01-29 21:02 UTC by bhushan23

del Tensor.grad set PyObject to nullptr
and Tensor.grad = None set PyObject to Py_None
Handling both the cases now
fixes ##16471

2019-01-29 21:05 UTC, bhushan23 commented
@colesbury as we cannot control what PyObject gets, we need to add above check.
Is it correct? If so, Will add respective test cases

2019-01-29 21:10 UTC, colesbury commented
Yes. This same problem occurs in some other setters in THPVariable_properties and maybe other classes. Including:

- THPVariable_set_grad_fn
- THPVariable_set_data
- THPVariable_set_requires_grad

(i.e. they crash when the someone tries to delete the property)

2019-01-30 02:00 UTC, vishwakftw commented
@colesbury Is `grad_fn` deletable? `grad_fn` is not writable, I believe.

https://github.com/pytorch/pytorch/blob/21193bf12314f9d1be5ea36cbce3162c54b35225/torch/csrc/autograd/python_variable.cpp#L409

2019-01-30 15:40 UTC, vishwakftw commented on test/test_autograd.py
> +        x = torch.randn((5,5), requires_grad = True)
Spaces before and after `=` would probably cause lint error, and so will no space after `,` in `(5,5)`.

2019-02-01 05:20 UTC, bhushan23 commented
@colesbury

2019-02-01 10:04 UTC, albanD commented on test/test_autograd.py
> +        self.assertIsNone(x.data)
What does it mean for a Tensor `.data` field to be `None` ? What happens to `x` when you do `del x.data` ? Does it become unusable?

2019-02-01 13:01 UTC, albanD commented on test/test_autograd.py
> +        self.assertIsNone(x.data)
From my point of view, not allowing it would be better as this is a state you never want to be in (in python).

2019-02-04 16:31 UTC, bhushan23 commented
@colesbury

2019-02-05 17:38 UTC, fmassa approved these changes
I think this looks good, but I'll let @colesbury have another look at it

2019-02-09 23:42 UTC, soumith commented
just fyi to all, @colesbury is on vacation. If @albanD also approves, I'm happy to ship it.

2019-02-10 09:05 UTC, albanD requested changes
Could you do the same for `THPVariable_set_grad_fn` and forbid deleting it please (A user should never delete a grad_fn but detach() the Tensor) and `THPVariable_set_backwards_hooks` to make it have the same behavior as if None was passed (this shuold not be used by users, but I think it's better to remove the case where it segfaults)? Both these functions have the same problem as the one you fixed.

2019-02-10 20:10 UTC, bhushan23 commented
@albanD sounds good to me. 
Unfortunately, I do not have my laptop with me and can not setup pytorch on temporary laptop. Will send change in next couple of days.

2019-02-18 04:46 UTC, bhushan23 commented
@albanD not allowing deletion for `THPVariable_set_grad_fn`
`THPVariable_set_backwards_hooks`'s behavior for deletion and setting to None is same, hence skipping.

2019-02-18 09:45 UTC, albanD commented
But won't the check `obj == Py_None` segfault if `obj` is already a `nullptr` for `THPVariable_set_backwards_hooks`?

2019-02-18 15:37 UTC, bhushan23 commented
> But won't the check `obj == Py_None` segfault if `obj` is already a `nullptr` for `THPVariable_set_backwards_hooks`?
@albanD No.  It won't as obj pointer is not same as one pointing to Py_None

But, if we don't want to allow deletion of backward hooks, we should definitely assert with useful error message.

2019-02-18 15:47 UTC, albanD commented
Ho my bad, for some reason I though it was the equality check that was causing issues. We are happy with deletion to behave like setting it to None !

2019-02-18 15:47 UTC, albanD approved these changes

2019-02-18 15:52 UTC, bhushan23 commented
> Ho my bad, for some reason I though it was the equality check that was causing issues. We are happy with deletion to behave like setting it to None !

FYI, I just pushed changes to assert if del is called on _backward_hooks
Fact that, deletion and setting to None behavior is same is good to have but do we want to allow it? 
Not allowing will be good as we keep consistent behavior with other grad attribute

2019-02-18 16:03 UTC, albanD commented
This particular method is an internal one. It is just used internally at the moment.
Also you don't want the user to tinker with grad_fn (there are proper functions for that) but you're happy with him removing the hooks.

2019-02-19 12:35 UTC, closed without merging