fix the bug of named_parameters
pytorch/pytorch pull request #1710
Opened 2017-06-03 07:00 UTC by mileyan

When I use the named_parametes to modify the lr and weight decay, I will face a bug. Because the value of the named_parameters return is  torch.nn.paramter.Parameter, not a generator of the Parameter.

2017-06-03 10:52 UTC, apaszke requested changes
Can you also add a test case for this?

2017-06-03 10:52 UTC, apaszke commented on torch/optim/optimizer.py
> +            if isinstance(group['params'], torch.nn.paramter.Parameter):
You should check for an autograd Variable, not a Parameter

2017-06-03 12:00 UTC, apaszke commented
@pytorchbot test this please

2017-06-03 12:01 UTC, apaszke commented
It's still missing the test case. I'll merge it once it's added.

2017-06-06 03:48 UTC, soumith commented
i've added a test for this and merged your PR into master. Thank you.

2017-06-06 03:48 UTC, soumith commented
merged via https://github.com/pytorch/pytorch/commit/a76098ac1532d5e9ee24b4776258ae731627f8e3

2017-06-06 03:48 UTC, closed without merging