Change vml.h to support sizes greater than 2**32 - 1
pytorch/pytorch pull request #17280
Opened 2019-02-20 00:58 UTC by cpuhrsch

2019-02-20 10:23 UTC, soumith requested changes
what happens here if MKL_INT is int64_t? will it silently fail, or does it work fine?

If there's silent failure, can you static_assert

2019-02-20 15:57 UTC, gchanan commented
can we add a test?  (how expensive is it?)

2019-02-20 17:55 UTC, cpuhrsch commented
@soumith - I think we'd need to worry about size_t, but for int64_t the max value should then cause it always stick to the first branch. 

There's a bunch of stuff left to do here, including benchmarks on the impact of writing these branches (which I'd be surprised if there are any).

A static assert is still a good idea. In general, we should move all includes of mkl.h into a single location and reference our own header. There are some implicit settings one can do by defining variables before the include. This can then also include the static assert, which is a good way to check that PyTorch is only built with the lp64 version (as oppposed to ilp64).

@gchanan - Since this is very specific to MKL VML and it's referenced in a single location, I'm not sure it's worth adding this to the tests we run for every built.

2019-02-20 18:46 UTC, gchanan commented
> @gchanan - Since this is very specific to MKL VML and it's referenced in a single location, I'm not sure it's worth adding this to the tests we run for every built.

We need nightlies!

2019-02-20 23:21 UTC, cpuhrsch commented
I ran some performance regression tests and the difference seems to be within the noise, so performance wise this should be fine.

2019-02-21 01:59 UTC, cpuhrsch commented
@pytorchbot rebase this please

2019-02-21 18:20 UTC, cpuhrsch commented
@pytorchbot rebase this please

2019-02-25 17:21 UTC, soumith approved these changes

2019-02-25 17:21 UTC, soumith commented on aten/src/ATen/cpu/vml.h
> +static_assert(
ship this, but we should add a global setting to allow building / linking against MKL_INT=int64_t as well, it just has to be non-default. Send a patch to do that in a follow-up PR.

2019-02-25 21:46 UTC, ezyang approved these changes
Approved via `ghapprove D14154997`

2019-02-25 21:50 UTC, cpuhrsch commented
Thanks. Will merge soon.

2019-03-02 01:24 UTC, closed without merging