[DOC][MINOR] Missing argument description (value) in scatter_ function documentation
pytorch/pytorch pull request #17467
Opened 2019-02-25 13:24 UTC by krishnakalyan3

Update the docs to include the value parameter that was missing.

cc: @fmassa @vishwakftw @soumith 

Ref:
#16014

2019-02-25 14:34 UTC, soumith requested changes
please remove the submodule changes. they look wrong.

2019-02-25 17:30 UTC, krishnakalyan3 commented
@soumith sorry for the inconvenience. Could you please have a look at the changes again?.

2019-02-25 17:36 UTC, soumith approved these changes

2019-02-25 17:36 UTC, soumith commented
thank you!

2019-02-26 17:22 UTC, soumith commented
closed via https://github.com/pytorch/pytorch/commit/59ece70201328a14e01d25c7ca856233785740bf

2019-02-26 17:22 UTC, closed without merging

2021-01-28 19:25 UTC, idigitopia commented
The bug still persists, why did we delete the scatter fix? 
The documentation is still wrong. I spent half an hour trying to figure out that the integer goes into value and not src. 

please fix this. or may be I can create another pull request for the same fix.