Make transpose consistent with numpy's behavior
pytorch/pytorch pull request #17462
Opened 2019-02-25 07:41 UTC by bhushan23

Pytorch's tensor.t() is now equivalent with Numpy's ndarray.T for 1D tensor
i.e. tensor.t() == tensor

Test case added:
- test_t

fixes #9687

2019-02-25 14:56 UTC, soumith approved these changes

2019-02-25 14:58 UTC, soumith requested changes
some jit tests are failing, but it seems more of an issue with the jit tests, rather than with your implementation. Please fix them, or let us know if we should help

2019-02-25 20:23 UTC, bhushan23 commented
@soumith it's fixed

2019-02-25 22:02 UTC, soumith approved these changes

2019-02-25 22:02 UTC, soumith commented
thanks Bhushan!

2019-02-26 22:24 UTC, closed without merging

2019-02-26 23:32 UTC, gchanan commented
Nice improvement.  Also note the same thing can be done with 0-dimensional tensors, see:
https://github.com/pytorch/pytorch/issues/17520.