Change Dispatch.h to use ScalarType over Type
pytorch/pytorch pull request #17527
Opened 2019-02-27 00:58 UTC by li-roy

Differential Revision: [D14235395](https://our.internmc.facebook.com/intern/diff/D14235395/)

2019-03-07 02:15 UTC, gchanan requested changes
This made a number of error messages worse.

For example, let's say I have a CPU and CUDA implementation of the same function, fn, which I give in both cases to the dispatch macro as "fn".  And as with most functions, I implement the half variant on CUDA, but not CPU.

Then, the user tries to call "fn" with CPU half, and gets the message "fn is not implemented for Half" which is wrong.

Can you just go through and find the cases where this exists (if such a case exists, note it _will_ exist if you shepherd TH functions through this macro).

2019-03-08 19:09 UTC, ezyang commented on aten/src/ATen/native/BatchLinearAlgebra.cpp
> +  AT_DISPATCH_ALL_TYPES(self.scalar_type(), "tril", [&]{
`tril_cpu` here

2019-03-08 19:09 UTC, ezyang commented on aten/src/ATen/native/BatchLinearAlgebra.cpp
> +  AT_DISPATCH_ALL_TYPES(self.scalar_type(), "tril", [&]{
ditto

2019-03-08 19:14 UTC, ezyang commented on aten/src/ATen/native/BatchLinearAlgebra.cpp
> +  AT_DISPATCH_ALL_TYPES(self.scalar_type(), "triu", [&]{
ditto

2019-03-08 19:15 UTC, ezyang commented on aten/src/ATen/native/BatchLinearAlgebra.cpp
> +  AT_DISPATCH_ALL_TYPES(self.scalar_type(), "triu", [&]{
ditto

2019-03-08 19:15 UTC, ezyang commented on aten/src/ATen/native/Copy.cpp
> +          at::ScalarType::Half, self.scalar_type(), "_copy_same_type_", [&]() {
cpu

2019-03-08 19:16 UTC, ezyang commented on aten/src/ATen/native/Copy.cpp
> +      at::ScalarType::Half, self.scalar_type(), "_copy_same_type_", [&]() {
cpu

2019-03-08 19:16 UTC, ezyang commented on aten/src/ATen/native/FractionalMaxPool2d.cpp
>    "fractional_max_pool2d_out_frame", [&] {
cpu

2019-03-08 19:16 UTC, ezyang commented on aten/src/ATen/native/FractionalMaxPool2d.cpp
> +    input.scalar_type(), "fractional_max_pool2d_backward_out_frame", [&] {
cpu

2019-03-08 19:16 UTC, ezyang commented on aten/src/ATen/native/FractionalMaxPool3d.cpp
>      "fractional_max_pool3d_out_frame",
cpu

2019-03-08 19:17 UTC, ezyang requested changes
I stopped something like 30% of the way through the patch, but it seems there are still a lot of missing sites

2019-03-08 19:18 UTC, li-roy commented
@ezyang I only changed the strings that are used on both cpu and gpu kernels.

2019-03-08 19:24 UTC, gchanan approved these changes

2019-03-09 00:44 UTC, closed without merging