Adds Cyclical Learning Rate and Momentum
pytorch/pytorch pull request #18001
Opened 2019-03-13 22:42 UTC by sampepose

This implements a cyclical learning rate (CLR) schedule with an optional inverse cyclical momentum. More info about CLR: https://github.com/bckenstler/CLR

This is finishing what #2016 started. Resolves #1909.

2019-03-13 22:43 UTC, soumith commented
thanks Sam (and @thomasjpfan too). Let me know if you need a review / re-review.

2019-03-14 02:30 UTC, sampepose commented
Hey @soumith! I'd appreciate a review, thank you!

2019-03-14 02:48 UTC, thomasjpfan commented
It would be good if this PR or #2016 gets merged. (I started #2016 in 2017) 😄

2019-03-20 21:38 UTC, sampepose commented
ping @soumith :)

2019-03-27 16:51 UTC, soumith requested changes
comments are minor, but need necessary changes.

Thanks, the PR looks pretty good.

2019-03-27 16:51 UTC, soumith commented on torch/optim/lr_scheduler.py
> +            Default: 0.001
I'd suggest to not have a default for the base learning rate. It makes it too easy to shoot oneself in the foot

2019-03-27 16:51 UTC, soumith commented on torch/optim/lr_scheduler.py
> +            scaling function. Default: 0.006
You either want to make the max_lr default be a multiple of base_lr, or simply remove a default

2019-03-27 16:51 UTC, soumith commented on torch/optim/lr_scheduler.py
> +            mode parameter is ignored
" mode parameter is ignored" -> "If specified, then `mode` is ignored"

2019-03-27 16:51 UTC, soumith commented on torch/optim/lr_scheduler.py
> +        last_batch_idx (int): The index of the last batch. Default: -1
what exactly does `-1` do here?

2019-03-27 16:51 UTC, soumith commented on torch/optim/lr_scheduler.py
> +        last_batch_idx (int): The index of the last batch. Default: -1
also, it's not clear what this is used for, explaining what the index of the last batch is, or where / why it is used will help

2019-03-27 16:51 UTC, soumith commented on torch/optim/lr_scheduler.py
> +        >>>         scheduler.step()
Shouldn't it be:

```
train_batch(...)
scheduler.step()
```

2019-03-27 16:51 UTC, soumith commented on torch/optim/lr_scheduler.py
> +                 base_lr=1e-3,
comments above about default values

2019-03-27 16:51 UTC, soumith commented on torch/optim/lr_scheduler.py
> +        step_size_down = step_size_down or step_size_up
do you mean `step size_down = step_size_down if step_size_down is not None else step_size_up`

2019-03-27 16:51 UTC, soumith commented on torch/optim/lr_scheduler.py
> +        self.total_size = float(step_size_up + step_size_down)
it seems safer to actually convert step_size_up and step_size_down to float immediately on entry into the function.

2019-03-27 18:19 UTC, soumith approved these changes
lgtm. thank you!

2019-03-28 02:57 UTC, closed without merging