JIT Layernorm fusion
pytorch/pytorch pull request #18266
Opened 2019-03-21 06:52 UTC by wanchaol

2019-03-26 16:33 UTC, zou3519 commented on test/test_jit.py
> +            print(rep)
Is this print supposed to be here?

2019-03-26 16:35 UTC, zou3519 commented on torch/csrc/jit/passes/graph_fuser.cpp
> +      // We don't do any fusions in here, but simply decompose the batch norm
s/batch norm/layer norm/

2019-03-26 19:35 UTC, apaszke commented on test/test_jit.py
> +    def test_fuse_layer_norm(self):
Yes please! This test is huge

2019-03-26 19:35 UTC, apaszke commented on torch/csrc/jit/passes/graph_fuser.cpp
> +    layer_norm->destroy();
This infra should also be shared. THey take almost the same arguments, only need a different reshape and replacement.

2019-04-10 18:10 UTC, wanchaol commented
@apaszke @ngimel I merged batchnorm and layernorm infrastructure together. Please take a look again when you get some time

2019-04-12 04:08 UTC, ngimel requested changes
Please remove code that is no longer used.

2019-04-12 04:08 UTC, ngimel commented on torch/csrc/jit/passes/graph_fuser.cpp
> +  void decomposeLayerNorm(Node* layer_norm) {
you don't need this anymore

2019-04-12 04:08 UTC, ngimel commented on torch/csrc/jit/passes/graph_fuser.cpp
>    void decomposeBatchNorm(Node* batch_norm) {
you don't need this anymore, you have common function

2019-04-12 04:56 UTC, ngimel approved these changes

2019-04-12 21:40 UTC, closed without merging