Add model builder for jit test
pytorch/pytorch pull request #18396
Opened 2019-03-24 05:37 UTC by nishantpdce

Summary: Add model builder file to create simple models for testing jit passes

Differential Revision: D14537862

2019-03-24 17:31 UTC, apaszke requested changes
Currently the file does nothing at the moment. What's the plan for this test?

2019-03-25 17:58 UTC, nishantpdce commented
> Currently the file does nothing at the moment. What's the plan for this test?

There is a follow up change which will be using this change for jit passes

2019-03-26 01:51 UTC, ZolotukhinM commented
> Currently the file does nothing at the moment. What's the plan for this test?

Think about this file as a collection of convenience methods for creating similar to real-world models. The plan is to build kind of integration testing on top of it (along with small local tests for each particular jit pass). I'm not sure we need it right now, but I can see how it could be useful in future.

2019-03-29 00:50 UTC, ZolotukhinM reviewed
It looks good to me (modulo one remark inline), but I'd wait for @apaszke's approval since originally he had questions about this.

2019-03-29 00:50 UTC, ZolotukhinM commented on test/model_builder.py
> +    return model
This will fail if `model_name` != `None` is passed.

2019-04-04 09:19 UTC, apaszke requested changes
>  I'm not sure we need it right now, but I can see how it could be useful in future.

I understand that this _might_ be useful at some point, but that's not a good enough reason to check in code. If it _doesn't_ turn out to be useful it will stay there unused and will only pollute the test directory. It's ok to merge this, but only once it is used _somewhere_.

2022-05-12 03:06 UTC, closed without merging