Append c10 libs to TorchConfig.cmake
pytorch/pytorch pull request #18418
Opened 2019-03-25 05:48 UTC by peterjc123

Fixes #18416.

2019-03-25 08:10 UTC, peterjc123 commented
@pytorchbot retest this please

2019-03-25 15:04 UTC, xsacha commented
Is this like the Caffe2 libs where it would not need to be added to linker list if built statically?
Not sure if it needs wrapping with `if (@BUILD_SHARED_LIBS@)`.

2019-03-25 15:33 UTC, peterjc123 commented
> Is this like the Caffe2 libs where it would not need to be added to linker list if built statically?
> Not sure if it needs wrapping with `if (@BUILD_SHARED_LIBS@)`.
> 
> On Linux I build statically for example and did not need this added. I discovered this issue on Windows as static was broken and the nightlies are shared.

Actually, it should be `if (NOT @BUILD_SHARED_LIBS@).`, but it won't be a problem since, in shared builds, the symbols are all contained in `torch.dll` so adding any other libraries will have no effect. The linker will remove useless libraries specified by the user automatically.

2019-03-25 20:20 UTC, ezyang commented
@peterjc123 This seems fine, but is there any chance we could get a test for this? This seems like the kind of thing we'd be likely to break upon a cmake refactor without a test for it.

2019-03-25 20:20 UTC, ezyang approved these changes

2019-03-25 20:21 UTC, ezyang commented on cmake/TorchConfig.cmake.in
> +  list(APPEND TORCH_LIBRARIES ${C10_CUDA_LIBRARY})
Actually, are you sure this shouldn't be `TORCH_CUDA_LIBRARIES`?

2019-03-25 20:21 UTC, ezyang requested changes
one question

2019-03-26 03:32 UTC, peterjc123 commented
@ezyang About the test, I'll do it in another PR. Is it a good idea to add the cpp-extensions tests to `caffe2-py2-cuda9.0-cudnn7-windows-build` and change it to use `build_libtorch.py` instead of `build_windows.bat`? cc @orionr

2019-03-26 17:51 UTC, orionr commented
Moving to `build_libtorch.py` would be a win, IMO. cc @kostmo and @pjh5

2019-03-27 02:27 UTC, ezyang approved these changes

2019-03-27 02:54 UTC, closed without merging