[WIP] Choice equivalent for PyTorch
pytorch/pytorch pull request #18457
Opened 2019-03-25 23:29 UTC by LeviViana

Related to #16897.

I'm having a hard time with `.../pytorch/build/lib/libcaffe2.so: undefined reference to 'at::native::choice(at::Tensor const&, at::Tensor const&, bool, long)'`. I tried many workarounds and read some recent PR's trying to figure out how to solve this, but the main problem is that the trial-and-error cycle is too long due to the build time (30 min), so I think I'm gonna need some help in integrating it into PyTorch.

2019-03-26 01:25 UTC, soumith requested changes

2019-03-26 01:25 UTC, soumith commented on aten/src/ATen/native/native_functions.yaml
> +- func: choice(Tensor& input, Tensor& weights, bool replacement, int k) -> Tensor
not Tensor&, just Tensor

2019-03-26 16:44 UTC, ezyang commented on aten/src/ATen/native/TensorFactories.cpp
> +  Tensor& input,
These arguments should be `const Tensor&` (and fix @soumith's comment too)

2019-03-26 16:45 UTC, ezyang commented
@LeviViana Meta advice: the translation to c++ is documented in the README in https://github.com/pytorch/pytorch/tree/master/aten/src/ATen/native

Also, we generate prototypes for all native functions in `build/aten/src/ATen/NativeFunctions.h` which you can use to find the correct spelling.

2019-03-27 12:53 UTC, fmassa requested changes
Could you add some tests?

2019-03-28 00:23 UTC, LeviViana commented
The reproducibility tests are not passing for the moment. I'm trying to get some inspiration on how `randperm` is implemented to make it pass. Any tips on how to do it will be much appreciated.

2019-03-28 10:09 UTC, fmassa commented on aten/src/ATen/native/TensorFactories.cpp
> +  THGenerator* generator = THGenerator_new();
This creates a new random number generator. You should ideally get the generator from somewhere else, or else you won't be able to set a random seed. I'm not sure what's the best option here now, given that the RNG is being completely refactored in https://github.com/pytorch/pytorch/pull/16604

2019-03-29 15:36 UTC, fmassa commented on aten/src/ATen/native/cuda/TensorFactories.cu
> +
Can you add a `AT_CUDA_CHECK(cudaGetLastError());` here and after you called the kernels in the other branch?



AT_CUDA_CHECK(cudaGetLastError());
707

` here and in the other branch?

(note: there is probably a different way of doing this with ATen now, I vaguely remember that something has changed :-)

2019-03-29 16:52 UTC, LeviViana commented
Sorry, I messed up (early rebase). I'm trying to fix it.

2019-03-29 17:59 UTC, LeviViana commented
I'm closing this PR and opening a new one (cleaner). Sorry for this mess.

2019-03-29 17:59 UTC, closed without merging