More type stubs
pytorch/pytorch pull request #18511
Opened 2019-03-27 02:57 UTC by malmaud

Added stubs for:

* The `device` module
* The `cuda` module
* Began adding stubs for the `autograd` module. I'll annotate more later but `no_grad` and friends are probably the most used exports from it so it seemed like a good place to start.

This would close #16996, although comments on that issue reference other missing stubs so maybe it's worth keeping open as an umbrella issue.

The big remaining missing package is `nn`.

Also added a `py.typed` file so mypy will pick up on the type stubs. That closes #17639.

2019-03-27 15:55 UTC, ezyang commented on torch/cuda/__init__.pyi
> +    SUCESS: int
You mean `SUCCESS`?

2019-03-27 15:57 UTC, ezyang commented
Thanks, this looks great. `torch.nn` will be trickier to do since we should probably autogenerate the stubs in that case (these files, it looks acceptable to just check in the stubs directly as you've done here.)

Lint failure is real, take a look: https://travis-ci.org/pytorch/pytorch/jobs/511828583

and there are some mypy failures too:

```
Mar 27 06:17:50 test_doc_examples (__main__.TestTypeHints) ... torch/cuda/__init__.pyi:3: error: Module 'torch' has no attribute 'device'
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:14: error: Module has no attribute "abs"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:14: error: Module not callable
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:18: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:20: error: Module has no attribute "acos"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:24: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:26: error: Module has no attribute "add"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:27: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:29: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:31: error: Module has no attribute "add"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:35: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:36: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:37: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:38: error: Module has no attribute "addbmm"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:42: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:43: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:44: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:45: error: Module has no attribute "addcdiv"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:49: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:50: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:51: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:52: error: Module has no attribute "addcmul"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:56: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:57: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:58: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:59: error: Module has no attribute "addmm"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:63: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:64: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:65: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:66: error: Module has no attribute "addmv"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:70: error: Module has no attribute "arange"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:71: error: Module has no attribute "arange"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:72: error: Module has no attribute "zeros"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:73: error: Module has no attribute "addr"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:77: error: Module has no attribute "allclose"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:77: error: Module not callable
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:78: error: Module has no attribute "allclose"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:78: error: Module not callable
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:79: error: Module has no attribute "allclose"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:79: error: Module not callable
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:80: error: Module has no attribute "allclose"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:80: error: Module not callable
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:84: error: Module has no attribute "arange"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:85: error: Module has no attribute "arange"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:86: error: Module has no attribute "arange"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:90: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:92: error: Module has no attribute "argmax"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:93: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:95: error: Module has no attribute "argmax"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:99: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:101: error: Module has no attribute "argmin"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:102: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:104: error: Module has no attribute "argmin"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:108: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:110: error: Module has no attribute "argsort"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:115: error: Module has no attribute "as_tensor"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:120: error: Module has no attribute "as_tensor"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:120: error: Module has no attribute "device"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:127: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:129: error: Module has no attribute "asin"
Mar 27 06:17:51 /var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py:133: error: Module has no attribute "randn"
Mar 27 06:17:51 /var/lib/jenkins/work [...]

2019-03-27 18:36 UTC, t-vi commented
Thanks you for working on this!
I think that either finding a way to import .py from .pyi files or auto-generating stubs from "import" and using inspect (I think I did that somewhere for the functions in torch/functional.py, but I can't remember) should be a preferred way, as we'd have a really hard time to keep these up to date.

2019-03-27 18:41 UTC, malmaud commented
Thanks @t-vi . I'm not sure I understand though - the type information isn't available from the py files even in principle. I don't see how the Python `inspect` module (if that's what you're referring to) would help - how would it know what type of arguments a Python function would accept without throwing an error?

2019-03-27 18:46 UTC, ezyang requested changes
needs to pass tests

2019-03-27 19:08 UTC, ezyang commented
Responding to @t-vi and @malmaud, there are two orthogonal problems going on here:

1. Getting autocomplete to work. In this case, t-vi's suggestion works fine, because even if there are no types in the py file, you'll get enough info to generate the autocomplete
2. Actually having real type stubs for PyTorch, so you can use mypy on code that uses it. In this case, we really do need honest to goodness stubs.

We're unlikely to be able to type the inside of PyTorch any time soon, so we'll have to do type stubs in the meantime. I agree there is a maintenance risk here, but I think it is acceptable (we're actually pretty conservative when it comes to Python side changes).

2019-03-27 20:50 UTC, t-vi commented
I think we would need a way to keep the type information close to the function definitions.
My understanding is the "just adding type information" will not work.
But we could try:
- add type info to the module *and* generate a stub from that and ship it. (In the expectation that once we have a stub, nothing checking types will look at out py module.)
- if that doesn't work for some reason, find another way to include the information in the regular file and get the type hints from there (either via a decorator mechanism or by adding a function cal similar to how we add docstrings to the C or something).

2019-03-27 22:54 UTC, malmaud commented
If I understand that your concern is that the stubs are a separate file, then a few points come to mind:

*  you can include type annotations directly in the implementation - either be giving up compatibility with Python 2 by putting annotations on function implementations, or keeping compatibility by using a string-based syntax for encoding types in docstrings and comments. 

I personally dislike the string syntax since it's (IMO) pretty inelegant and makes IDEs unable to provide syntax highlighting or other help in writing the typing annotations, as well as making the implementation harder to read. But that's just a subjective of opinion and it's definitely a possibility.

* The stubs can also live in a third-party package which is not maintained by the pytorch team, freeing the team of any worry about maintaining them.

* The stubs might not get out of sync with the implementation as fast as you might think since they only need to include functions that are part of the public API of pytorch, which doesn't change very often. When the API does change, you already have to remember to update the documentation and guides so it doesn't seem so bothersome to also update the stub.

* Even if the stubs do occasionally get a bit out of sync with the corresponding implementation, the only effect will be to cause some `mypy` analyses or autocomplete suggestions to be incorrect, and it's easily fixable once a user raises an issue.

2019-03-27 23:09 UTC, malmaud commented
Flake errors fixed, still have to work on the others.

2019-03-28 01:55 UTC, malmaud commented
@ezyang I could use a pointer wrt to the failing mypy test, if you have any quick insights. It passes locally for me. I run

```
 mypy --follow-imports silent --check-untyped-defs tests/generated_type_hints_smoketest.py 
```

and don't get back any errors. I don't know enough about your testing architecture to understand why it would fail on circle.

2019-03-28 08:08 UTC, t-vi commented
> I personally dislike the string syntax since it's (IMO) pretty inelegant and makes IDEs unable to provide syntax highlighting or other help in writing the typing annotations, as well as making the implementation harder to read. 

Yes, well. I don't like it either and I just use Python 3 syntax for my own projects (and TBH I don't think that it had been a good decision to not just add the type hint syntax to Python 2 because it effectively bars projects from using the Python 3 version). But having a library of the scope of PyTorch changes that a bit, and as long as we support Python 2, my point of view is that we will have to do things in a compatible way. My guess is that in a year or so, we'll drop support along [with everyone else](https://python3statement.org/), but I don't decide that.

When I first started type hints, avoiding things to break due to library changes was a priority and I think it is still a good one, as breaking hints will leave people with more or less subtle and hard to understand breakage.

2019-03-28 21:44 UTC, malmaud commented on torch/cuda/__init__.pyi
> +    SUCESS: int
fixed

2019-03-29 15:40 UTC, malmaud commented
@ezyang The remaining test failures seem spurious. The failing ones are about CUDA-related failures that I don't think can be related to this PR. 

The [lint failure](https://travis-ci.org/pytorch/pytorch/jobs/512825689) is also wrong. It's complaining about assigning `...` as default parameters to typed arguments in the stubs, but that's the correct syntax.

2019-03-29 15:58 UTC, ezyang commented
> The lint failure is also wrong. It's complaining about assigning ... as default parameters to typed arguments in the stubs, but that's the correct syntax.

Yeah, add `*.pyi` to the ignores in flake8 please!

2019-03-29 16:00 UTC, ezyang approved these changes

2019-03-29 17:02 UTC, malmaud commented
Done!

2019-04-01 15:02 UTC, malmaud commented
Is this good to merge now @ezyang ?

2019-04-01 23:06 UTC, closed without merging