Materialize a non-default device for C2 legacy storage.
pytorch/pytorch pull request #18605
Opened 2019-03-29 03:47 UTC by gchanan

It's not intended that Storages have 'default' CUDA devices, but this is allowable via the Storage::create_legacy codepath.

This also messages with device_caching, because the initial cache is obtained from the Storage, which may have a 'default' device.

Instead, we materialize a device by allocating 0 bytes via the allocator.

2019-03-29 03:48 UTC, gchanan commented
@dzhulgakov does this look correct for C2?

@ezyang can we use this same pattern to address the Sparse issue in https://github.com/pytorch/pytorch/pull/18578?

2019-03-29 07:12 UTC, dzhulgakov reviewed
I'm not sure it's worth it. Right now it'd resolve to CUDA allocator and trigger cudaMalloc with 0 bytes. In general, the partially initialized tensor might be created on one device and get its storage only later on another device. So it doesn't solve your problem. I've commented on another PR.

2019-03-29 13:55 UTC, ezyang commented
It won't call cudaMalloc. Relevant code:

```
struct CudaCachingAllocator : public Allocator {
  DataPtr allocate(size_t size) const override {
    int device;
    C10_CUDA_CHECK(cudaGetDevice(&device));
    void* r = nullptr;
    if (size != 0) {
      caching_allocator.malloc(&r, size, cuda::getCurrentCUDAStream(device));
    }
    return {r, r, &CudaCachingDeleter, Device(DeviceType::CUDA, device)};
  }
  DeleterFnPtr raw_deleter() const override {
    return &CudaCachingDeleter;
  }
};
```

You'll get the current device but that's it.

2019-03-29 13:56 UTC, ezyang commented
> In general, the partially initialized tensor might be created on one device and get its storage only later on another device.

This may very well be true, I don't know enough about Caffe2 to say :)

2019-03-29 16:28 UTC, dzhulgakov commented
@ezyang - actually we register this wrapper as the allocator so it might call cudaMalloc under some settings: https://github.com/pytorch/pytorch/blob/master/caffe2/core/context_gpu.cu#L488 (we should probably fix that)

2019-03-29 22:22 UTC, gchanan commented
@dzhulgakov I still think

2019-04-01 16:52 UTC, ezyang requested changes
Do you want to also fix the unguarded cudaMalloc on zero size site?

2019-04-04 05:18 UTC, dzhulgakov commented on caffe2/core/context_gpu.cu
> +        }
also CudaMemoryPoolType::CUB: below for completeness?

2019-04-08 23:51 UTC, bddppq commented
@pytorchbot retest this please

2019-04-09 15:54 UTC, gchanan commented
@pytorchbot retest this please.

2019-04-09 20:40 UTC, ezyang approved these changes

2019-04-11 20:52 UTC, closed without merging