[WIP] Fix empty tensor for unique_dim
pytorch/pytorch pull request #19000
Opened 2019-04-07 19:20 UTC by codexetreme

Fixes: #18408

cc: @zasdfgbnm

2019-04-08 19:08 UTC, zasdfgbnm requested changes
Hi @codexetreme, could you please complete this PR first, i.e. to add unit test, and do the same check for GPU? By adding unit test, you could basically find problem by yourself, and change it without having to ask help. The error messages in circle CI should be fairly helpful. Also, please resolve merge conflicts.

2019-04-08 19:08 UTC, zasdfgbnm commented on aten/src/ATen/native/Unique.cpp
> +        break;
I don't think this works either. You need to make sure that all dimensions are nonzero, not just one of it.

2019-04-08 19:08 UTC, zasdfgbnm commented on aten/src/ATen/native/Unique.cpp
> +    for (int64t i=0; i< self.dim(); ++i){
Should be `int64_t`.

2019-04-09 10:14 UTC, codexetreme reviewed
I have fixed merge conflicts, the other irregularities you mentioned. Also I am having a bit of difficulty writing tests. Where are these supposed to go exactly? there are many test folders. Should I add the tests in `test_torch.py` or in some other test folder?

2019-04-09 10:14 UTC, codexetreme commented on aten/src/ATen/native/cuda/Unique.cu
> +      THCudaCheck(cudaGetLastError());
Here, I am not sure if the cuda code is right. Could you please check and let me know what has to be done?

2019-04-09 10:14 UTC, codexetreme commented on aten/src/ATen/native/Unique.cpp
> +        break;
I have fixed this, hopefully, this is what is required?

2019-04-09 10:14 UTC, codexetreme commented on aten/src/ATen/native/Unique.cpp
> +    for (int64t i=0; i< self.dim(); ++i){
Ah yes, sorry my bad. I have fixed this.

2019-04-11 02:21 UTC, zasdfgbnm commented
@codexetreme Sorry for the late reply, yes, for the test, you need to write it at `test_torch.py`. Just search for `test_unique_dim` in that file. I will check your work later. But in the mean time, could you resolve the merge conflicts again?

2019-04-11 02:23 UTC, zasdfgbnm commented
BTW, I am working on unique also, so some of my work might frequently cause merge conflicts for this. You might also continue your work, and resolve the conflicts later, which might be of less trouble. It's your choice.

2019-04-11 02:25 UTC, zasdfgbnm commented on aten/src/ATen/native/cuda/Unique.cu
> +      THCudaCheck(cudaGetLastError());
Well, the logic for checking shape should be the same for CPU and CUDA, correct? In this case, why not create a `Unique.h` file, put the logic there as a function, and just call that function for CPU and CUDA?

2019-04-11 02:26 UTC, zasdfgbnm commented
@codexetreme Also, whenever you see build failures from CI, could you also please check where is error and try fixing it? :)

2019-04-11 16:31 UTC, codexetreme commented
Alright, I am looking into the CI logs... I'll write the tests as well.

> You might also continue your work, and resolve the conflicts later, which might be of less trouble.

I will do this..

2019-04-11 19:20 UTC, codexetreme commented
So in some of the CI logs, the error that is said is :
>Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

>The following packages have unmet dependencies:
 nvidia-docker2 : Depends: nvidia-container-runtime (= 2.0.0+docker18.06.2-1) but 2.0.0+docker18.06.2-2 is to be installed
E: Unable to correct problems, you have held broken packages.
Exited with code 100

Does this mean that the containers have not been properly instantiated or that the code in the commit is broken? And what to do for these?

2019-04-12 04:19 UTC, zasdfgbnm commented
@codexetreme For these kind of failures, you could do a "@pytorchbot retest this please"

2019-04-13 06:34 UTC, codexetreme commented
@pytorchbot retest this please

2019-04-13 14:16 UTC, zasdfgbnm commented
@codexetreme The bot is currently broken. You may try again next week.

2019-04-15 19:12 UTC, zasdfgbnm commented
@pytorchbot retest this please

2019-04-15 21:22 UTC, codexetreme commented
The same issue persists with the tests. What should be done ?

2019-04-15 22:36 UTC, zasdfgbnm commented
@codexetreme I think you need to resolve the conflict and merge with the latest master branch now. They must have updated CircleCI configurations.

2019-04-18 10:35 UTC, codexetreme commented
Sorry for the late reply (uni assignments take up time :(  ). Could you tell me the use of the `counts` bool? my code is failing as I am not returning a third tensor that should contain the counts tensor. According to my understanding, if the tensor is empty should I just return an empty tensor for it? (since there are no elements in the tensor and count would be zero anyway)

2019-04-18 17:17 UTC, zasdfgbnm commented
@codexetreme Yes

2019-04-23 06:47 UTC, codexetreme commented
Sorry for the late reply, In unique.cu, the error I'm getting is 

> Apr 18 22:10:06 
Apr 18 22:10:06 /var/lib/jenkins/workspace/aten/src/ATen/native/cuda/Unique.cu(167): error: "input_flat" has already been declared in the current scope
Apr 18 22:10:06 

in particular, the error is because input_flat has already been declared previously, a simple fix is to simply rename the variable in one of the 2 places ( and all its corresponding usages).

2019-04-23 09:15 UTC, codexetreme commented
In the `Unique.cu` file, in `unique_dim_cuda_template` `input_flat`, is declared twice, a simple fix is to just rename its usages here, since I dont see these particular lines being used elsewhere.
`Tensor input_flat = self.transpose(dim, 0);`
`auto orig_sizes = input_flat.sizes().vec();`
 `input_flat = input_flat.contiguous().view({input_flat.size(0), -1});`

2019-04-24 08:12 UTC, codexetreme commented
Hello, sorry to bother you again, but, I wanted to know if I can run just 1 test (any CPU based build and test is fine) because I cannot compile the code on my system, and so I will have to keep committing and wait till all the CI's are run and then check if tests pass and/or are made correctly. If I can download the python wheels from this current push that also is fine so that I can check the tests locally. Thanks for your patience :)

2019-04-30 12:20 UTC, codexetreme commented
@pytorchbot retest this please

2019-04-30 15:26 UTC, codexetreme commented
So all checks have passed,  whatv to do next?

2019-04-30 19:27 UTC, zasdfgbnm requested changes
@codexetreme Please see the review

2019-04-30 19:27 UTC, zasdfgbnm commented on test/test_torch.py
> +            expected_inverse_empty = torch.zeros(5, 0, dtype=dtype, device=device)
Shouldn't inverse index always be long tensor?

2019-04-30 19:27 UTC, zasdfgbnm commented on test/test_torch.py
> +            expected_counts_empty = torch.tensor([], dtype=dtype, device=device)
Same here

2019-04-30 19:27 UTC, zasdfgbnm commented on aten/src/ATen/native/Unique.cpp
> +        // found atleast 1 zero sized dimention, hence the tensor is not well formed
nit: "atleast" and "dimention"

2019-04-30 19:27 UTC, zasdfgbnm commented on test/test_torch.py
> +            # test empty tensor
Could you also add the test case when the tensor is not well formed?

2019-04-30 19:27 UTC, zasdfgbnm commented on aten/src/ATen/native/Unique.cpp
> +      Tensor output = at::empty({0}, self.options().dtype(kLong));
Why output is dtype long, instead of the same type as self?

2019-04-30 19:27 UTC, zasdfgbnm commented on aten/src/ATen/native/Unique.cpp
> +          at::empty(self.sizes(), self.options().dtype(kLong));
For inverse indices of `unique_dim`, shouldn't it be a 1D vector?

2019-04-30 19:27 UTC, zasdfgbnm commented on aten/src/ATen/native/cuda/Unique.cu
> +      THCudaCheck(cudaGetLastError());
I don't think there is need to do `THCudaCheck`

2019-04-30 19:27 UTC, zasdfgbnm commented on aten/src/ATen/native/cuda/Unique.cu
> +      Tensor output = at::empty({0},self.options().dtype(kLong));
Same problem here as in the review of CPU version

2019-04-30 19:27 UTC, zasdfgbnm commented on aten/src/ATen/native/cuda/Unique.cu
> +    Tensor input_flat_ = self.transpose(dim, 0);
What are these lines for?

2019-05-03 11:26 UTC, codexetreme commented
Hello, I have fixed the changes you specified. these 4 tests are pending for long, so I am sure about their status. Any other fixes are required?

2019-05-03 15:07 UTC, zasdfgbnm requested changes
@codexetreme Please see the comments

2019-05-03 15:07 UTC, zasdfgbnm commented on aten/src/ATen/native/Unique.cpp
> +      if (self.size(i) == 0) {
Would it be better to change the whole `if` to something like
```C++
AT_CHECK(self.size(i) > 0, "Some error message here");
```

2019-05-03 15:07 UTC, zasdfgbnm commented on aten/src/ATen/native/Unique.cpp
> +  if (dim <= self.dim() && self.size(dim) == 0) {
What would happen if `self.size(dim) != 0` but there is another dim that has zero size? Shouldn't this case be handled as well?

2019-05-03 15:07 UTC, zasdfgbnm commented on aten/src/ATen/native/cuda/Unique.cu
> +  if (dim <= self.dim() && self.size(dim) == 0) {
Please fix this part following the review of CPU implementation accordingly :)

2019-05-03 15:07 UTC, zasdfgbnm commented on aten/src/ATen/native/Unique.cpp
> +          at::empty(self.contiguous().view({self.size(0),-1}).sizes(), self.options().dtype(kLong));
Shouldn't the shape of inverse indices be `{self.size(dim)}`?

2019-05-03 15:32 UTC, codexetreme commented on test/test_torch.py
> +            # make src smaller. this should fail
this was due to a merge conflict, i'm not sure what why it gave one there, but i selected the lines  that the master branch has, ill roll back and fix it

2019-05-03 15:33 UTC, codexetreme commented on aten/src/ATen/native/Unique.cpp
> +      if (self.size(i) == 0) {
is there any documentation on such functionality? I feel like I'm missing out on a lot of these predefined functions/macros

2019-05-03 15:34 UTC, codexetreme commented on aten/src/ATen/native/Unique.cpp
> +          at::empty(self.contiguous().view({self.size(0),-1}).sizes(), self.options().dtype(kLong));
Oh, I thought it returned all indices, my bad, I will fix it

2019-05-04 16:12 UTC, codexetreme commented
So, I have made the changes you requested, I changed the logic so now it handles the `self.size(dim) !=0` case as well. Can you please check and let me know it is right?

2019-05-04 20:59 UTC, zasdfgbnm reviewed
It looks much better now. Could you please also fix the linter failures in Travis CI?

```
./test/test_torch.py:10963:17: E128 continuation line under-indented for visual indent
./test/test_torch.py:10964:17: E128 continuation line under-indented for visual indent
./test/test_torch.py:10965:17: E128 continuation line under-indented for visual indent
./test/test_torch.py:10966:17: E128 continuation line under-indented for visual indent
./test/test_torch.py:10969:17: E128 continuation line under-indented for visual indent
./test/test_torch.py:10970:17: E128 continuation line under-indented for visual indent
./test/test_torch.py:10971:17: E128 continuation line under-indented for visual indent
./test/test_torch.py:10972:17: E128 continuation line under-indented for visual indent
The command "flake8" exited with 1.
```

2019-05-04 20:59 UTC, zasdfgbnm commented on aten/src/ATen/native/Unique.cpp
> +          at::empty(self.size(dim), self.options().dtype(kLong));
Isn't `size(dim)` just 0?

2019-05-04 20:59 UTC, zasdfgbnm commented on aten/src/ATen/native/Unique.cpp
> +    if (self.size(dim) != 0 ){
Isn't `self.size(dim) != 0` always true here?

2019-05-04 21:02 UTC, zasdfgbnm commented on aten/src/ATen/native/Unique.cpp
> +      if (self.size(i) == 0) {
I don't think there is any document for these functions. The best way to learn may be looking at other codes that uses those functions...

2019-05-05 05:47 UTC, codexetreme commented on aten/src/ATen/native/Unique.cpp
> +          at::empty(self.size(dim), self.options().dtype(kLong));
yes, I will change it

2019-05-05 08:09 UTC, codexetreme commented
Ok, so I have fixed the linting

2019-05-06 03:07 UTC, zasdfgbnm commented on aten/src/ATen/native/Unique.cpp
> +    auto num_zero_dims = std::count(sizes.begin(), sizes.end(),0);
nit: space between `sizes.end(),` and `0`

2019-05-06 03:07 UTC, zasdfgbnm commented on aten/src/ATen/native/Unique.cpp
> +    if (self.size(dim)==0){
nit: space before and after `==`

2019-05-06 03:07 UTC, zasdfgbnm commented on aten/src/ATen/native/Unique.cpp
> +    if (self.size(dim) != 0 ){
@codexetreme How about this? You are basically checking a condition that is always true.

2019-05-06 21:29 UTC, codexetreme commented on aten/src/ATen/native/Unique.cpp
> +    if (self.size(dim) != 0 ){
yep, you're right, I've kept it there to check the condition where the selected dim is non zero in size and there are zero sized dims in the tensor, but in hindsight, it's not going to do much there, ill remove it. :)

2019-05-07 04:30 UTC, codexetreme commented
Why is that 1 particular test failing? The other cuda based tests seem to have passed...

2019-05-07 14:40 UTC, zasdfgbnm approved these changes
@codexetreme That failure is not your fault, just ignore it. The code LGTM now. @VitalyFedyunin Could you please take a look and merge?

2019-05-12 13:26 UTC, codexetreme commented
When will this be merged? Kinda curious .....

2019-05-12 20:20 UTC, zasdfgbnm commented
@pytorchbot rebase this please

2019-05-12 20:21 UTC, zasdfgbnm commented
kindly ping @VitalyFedyunin :)

2019-05-13 15:05 UTC, VitalyFedyunin commented
Sure, I was hoping to have #20017  fixed (this helps to write tests quickly), guess I will do workaround.

2019-05-22 21:18 UTC, VitalyFedyunin approved these changes

2019-05-22 21:18 UTC, VitalyFedyunin commented on aten/src/ATen/native/Unique.cpp
> +    // tensor is not well formed as it has 0 sized dimentions
nit: dimenSions, here and everywhere

2019-05-22 21:18 UTC, VitalyFedyunin commented on test/test_torch.py
> +            self.assertRaises(
nit: It is cleaner to write
```python
with self.assertRaises(RuntimeError):
  torch.unique(
                x_ill_formed_empty, 
                return_inverse=True, 
                return_counts=True, 
                dim=1)
```

2019-05-23 07:09 UTC, codexetreme commented on test/test_torch.py
> +            self.assertRaises(
I have made the change like suggested :)

2019-05-23 07:10 UTC, codexetreme commented on aten/src/ATen/native/Unique.cpp
> +    // tensor is not well formed as it has 0 sized dimentions
fixed this :)

2019-05-23 15:54 UTC, VitalyFedyunin commented
Could you please cleanup training whitespaces

2019-05-29 20:52 UTC, closed without merging