use C10_REGISTER for gelp op
pytorch/pytorch pull request #19090
Opened 2019-04-10 00:34 UTC by hl475

Differential Revision: D14864737

2019-04-10 06:48 UTC, houseroad requested changes
Please add the test here: https://github.com/pytorch/pytorch/blob/master/caffe2/python/operator_test/torch_integration_test.py

2019-04-11 03:21 UTC, houseroad reviewed
Please address inline comments

2019-04-11 03:21 UTC, houseroad commented on caffe2/operators/gelu_op.cc
> +        c10::Argument("fast_gelu", BoolType::get()),
set default value?

2019-04-11 03:21 UTC, houseroad commented on caffe2/operators/gelu_op.cc
> +#include <c10/core/Tensor.h>
why include Tensor.h?

2019-04-11 03:21 UTC, houseroad commented on caffe2/python/operator_test/torch_integration_test.py
> +            expected_output, actual_output, rtol=rtol, atol=atol)
actual_output.cpu()

2019-04-11 18:42 UTC, hl475 commented
@pytorchbot retest this please

2019-04-11 21:07 UTC, houseroad approved these changes
Looks good.

2019-04-11 21:07 UTC, houseroad commented
Let's wait a bit for the IC signals

2019-04-11 22:26 UTC, xiaomengy approved these changes

2019-04-12 18:42 UTC, closed without merging