Adds `fakeQuantizeMinMaxArgsOp` to pytorch
pytorch/pytorch pull request #19387
Opened 2019-04-18 01:25 UTC by zafartahirov

2019-04-22 20:00 UTC, raghuramank100 requested changes

2019-04-22 20:00 UTC, raghuramank100 commented on test/test_fake_quant.py
> +    def test_forward(self):
Can you add a test where a quantize_linear(), followed by a dequantize() produces consistent output for the forward?

2019-04-22 21:10 UTC, raghuramank100 approved these changes

2019-04-23 18:15 UTC, closed without merging

2019-04-23 20:24 UTC, SsnL commented
broke lint

2019-04-23 20:50 UTC, jerryzh168 commented
will fix