Let script module buffer attributes can also cast device/type
pytorch/pytorch pull request #19700
Opened 2019-04-24 22:59 UTC by wanchaol

This should fix #19039

2019-04-25 00:11 UTC, eellison commented
Take a look at test/cpp/api/jit.cpp, pretty sure you can create a scriptmodule in cpp

2019-04-25 00:15 UTC, wanchaol commented
> Take a look at test/cpp/api/jit.cpp, pretty sure you can create a scriptmodule in cpp

@eellison I was looking at this file, it can let you create a ScripModule from the function text using `torch::jit::compile`, but it could not let you defined a ScriptModule class manually. In the case of the issue, we could only trigger this case when we have a ScriptModule class in C++, where it could not be created directly in C++ (only via python + torch.jit.save + load)

2019-04-25 17:23 UTC, eellison commented
In cpp you can define a script module with text, save it, and load it. Not sure i'm understanding how this doesn't cover your use case.

2019-04-25 21:04 UTC, eellison submitted a review, later dismissed
Looks good! thanks for adding the test.

2019-04-25 21:04 UTC, eellison commented on test/cpp/api/jit.cpp
> +    auto module = torch::jit::load("bn_gpu.pt");
Could you please add a run of it with GPU tensors first ?

2019-04-25 21:05 UTC, driazati commented on test/cpp/api/jit.cpp
> +TEST(TorchScriptTest, Conversion_MultiCUDA) {
The test should be in `cpp/jit/`, not `api/jit.cpp`, see `testModuleDefine` to see an example of a manually added parameter (attributes have pretty much the same API on modules)

2019-04-25 21:05 UTC, driazati commented on torch/csrc/jit/script/module.cpp
> +      autograd::Variable variable = parameter.value().toTensor();
This should be moved out to a function so it's not just a copy-paste of the above code for parameters

2019-04-25 21:06 UTC, driazati requested changes
I don't think we should be committing binaries to the repo to be used in tests

2019-04-26 19:15 UTC, driazati approved these changes

2019-04-26 20:09 UTC, closed without merging