Adds Cyclical Learning Rates
pytorch/pytorch pull request #2016
Opened 2017-07-08 02:18 UTC by thomasjpfan

Adds feature requested in https://github.com/pytorch/pytorch/issues/1909. Mimics the parameters from https://github.com/bckenstler/CLR. Since Cyclical Learning Rate (CLR) requires updating the learning rate after every batch, I added `batch_step` which should be called after feeding a batch through a neutral network.

2017-07-10 18:20 UTC, Jiaming-Liu commented
The usage of lambda would make the instance of CycleLR not pickle-able. Also, it would be nice if this can be written as a subclass of _LRScheduler.

2017-07-10 19:24 UTC, thomasjpfan commented
`_LRScheduler` interface seems to imply that `step` is called at the end of each epoch. The cyclical learning rate policy updates the learning rate after every batch. If `CyclicLR` were to subclass `_LRSchleduler` it would have to raise an exception for calling `step` and ask the user to call `batch_step` instead. Basically it comes down to a design decision.

2017-07-10 20:59 UTC, Jiaming-Liu commented
You are right -- some scheduling methods require a different calling frequency. The main discrepancy would be the timing to call `.step()` and the name of some methods/attributes/parameters. It might be helpful if there is another abstract class for batch-wise scheduler. @apaszke Any suggestion?

2018-02-28 20:35 UTC, thomasjpfan commented
I think the only thing stopping this PR is the added complexity of the `batch_step` function to `CyclicLR`. All the other schedulers are updated after every epoch, while `CyclicLR` is updated every batch.

2018-03-22 22:31 UTC, Aphaniteja commented
I hope this gets added. Recent papers(https://github.com/timgaripov/swa) are building upon this concept.

2018-03-24 23:01 UTC, thomasjpfan commented
https://github.com/timgaripov/swa could be implemented in this `_LRScheduler` framework. The `step` function would have to return the weight of the moving average, and the user would have to update the moving average of the model weights themselves.

2018-04-15 21:38 UTC, sean-adler commented
> You are right -- some scheduling methods require a different calling frequency. The main discrepancy would be the timing for `.step()` and the name of some methods/attributes/parameters. It might be helpful if there is another abstract class for batch-wise scheduler. @apaszke Any suggestion?

Sorry to ask a newbie question - is it necessary to have a different API for updating the learning rate per-batch rather than per-epoch?

If `CyclicLR` were rewritten to subclass `_LRScheduler` and implement `step()` instead of `batch_step()`, it kind of seems like doing this would be fine:

```
for epoch in range(num_epochs):
    for batch in data_loader:
        optimizer.zero_grad()
        output = model(input)
        loss = criterion(output, target)
        loss.backward()

        optimizer.step()
        scheduler.step()  #  <- apply CLR per-batch
```

Because `step_size` is an argument to `CyclicLR` in this changeset, making cycles follow a schedule similar to those in [the paper](https://arxiv.org/pdf/1506.01186.pdf) by e.g. setting `step_size` to a multiple of `len(data_loader)` seems like it'd make the above work (and be reasonably straightforward).

(One downside of doing this is that `CyclicLR` would have a misleading `last_epoch` attribute, but I have no idea how big a deal that is.)

I have very little pytorch-specific context here, so any feedback would be hugely appreciated.

2018-05-09 07:29 UTC, EtienneDesticourt commented
Very useful stuff, can't wait for this PR to be merged!  

I've been using it to train my models and I think the ``step_size`` parameter is confusing though. From its name you would expect it to be the amount of change in the learning rate at each step i.e: ``step_size = (max_lr - min_lr) / num_steps_per_cycle``. Whereas in this implementation ``step_size`` is actually the number of steps per half cycle (I also think the "number of training iterations per half cycle" part of the description is needlessly cryptic, speaking in terms of steps makes it much clearer, the mental connection between training iterations and steps happens when you call batch_step either way.)

So to sum up I propose something like this instead:  
`
num_steps(int): Number of steps per half cycle. Authors suggest setting num_steps
                         2-8 x training steps in epoch. Default: 2000
`

2018-05-09 07:57 UTC, sai-prasanna commented
Is there a way to find the optimal learning rate as mentioned in that paper in this commit? If not,  If I wish to add that, which part of torch would be best suited ?

2018-06-14 17:29 UTC, Randl commented
What's up with this PR?

2018-06-17 03:31 UTC, Randl commented
@thomasjpfan @apaszke What if we add `batch_step` to `_LRScheduler`? It would add some complexity, but at least it will be uniform along different schedulers. The code of form
```python3
for epoch in epochs:
    scheduler.step()
    ...
    for batch in batches:
        scheduler.batch_step()
        ...
```
would work for all schedulers then.

2018-06-18 14:11 UTC, apaszke commented
But that's so verbose... If we need a per-batch callback we might want to write a wrapper around an iterator that returns the batches (e.g. `DataLoader`)

2018-08-02 01:40 UTC, thomasjpfan commented
@sethah Good point. I agree that it would be better to just let the user decide when to call `step`. I will update this PR with that in mind.

2018-11-13 22:58 UTC, slowbull commented
Have anyone tried it on training cifar or imagenet? any code available?

2018-11-29 09:56 UTC, suruoxi commented
@slowbull  You can check https://github.com/Randl/MobileNetV2-pytorch

2018-12-31 10:12 UTC, Randl commented
ping reviewers

2019-01-09 05:47 UTC, soumith requested changes

2019-01-09 05:47 UTC, soumith commented on torch/optim/lr_scheduler.py
> +import numpy as np
numpy is an optional dependency into PyTorch.
Please remove the dependence of np in this file.

2019-01-09 05:47 UTC, soumith commented on test/test_optim.py
> +        targets = [[0.05 * (0.9 ** x) for x in range(epochs)], [0.4 * (0.8 ** x)
please only change lines relevant to your PR.
We have line limits of 120 characters, so your changes here and above in this file are not needed, and actively introduce noise.

2019-01-09 05:47 UTC, soumith commented on torch/optim/lr_scheduler.py
> +            mode paramater is ignored
*parameter

2019-01-09 05:47 UTC, soumith commented on torch/optim/lr_scheduler.py
> +        step_size_up (int): Number of training iterations in the
this has a default value below, but doc is missing

2019-01-09 05:47 UTC, soumith commented on torch/optim/lr_scheduler.py
> +        step_size_down (int): Number of training iterations in the
this has a default value below, but doc is missing

2019-01-18 09:39 UTC, klicperajo commented
This only implements a cyclical LR change. However, both the Leslie Smith paper that introduced the 1cycle schedule (https://arxiv.org/pdf/1803.09820.pdf) and the fast.ai library (https://docs.fast.ai/callbacks.one_cycle.html#Training-with-the-1cycle-policy) recommend to decrease the momentum as the learning rate increases, which helps with convergence. Would this be possible to add?

2019-01-18 13:36 UTC, thomasjpfan commented
The 1cycle policy can be configured by setting the `step_size_up` to half the total number of training iterations. Yes, it is possible to add the momentum piece to this PR.

2019-03-27 18:20 UTC, soumith commented
finished by https://github.com/pytorch/pytorch/pull/18001 which is landing

2019-03-27 18:20 UTC, closed without merging