symeig for variables
pytorch/pytorch pull request #2026
Opened 2017-07-09 20:12 UTC by ncullen93

this implements the symeig function for variables... I grabbed the gradient implementation directly from [theano](https://github.com/Theano/theano/blob/52903f8267cff316fc669e207eac4e2ecae952a6/theano/tensor/nlinalg.py#L432-L461) ... And I test it in [this gist](https://gist.github.com/ncullen93/9acefab137976712de0a51d88b39ffe7) to show that it gets the same gradient as the theano version. I've used this in actual networks so I'm fairly confident it's correct.

I obviously need to add actual tests, so any direction for that and anything else is much appreciated.

2017-07-11 00:12 UTC, fmassa commented on torch/autograd/_functions/linalg.py
> +        x = x.data
This doesn't look right. If you need tensors in your backward, you should use the devorator `once_differentiable` in the function, but looking at the functions used, that shouldn't be necessary.

2017-07-11 00:13 UTC, fmassa commented on torch/autograd/_functions/linalg.py
> +            return sum([v[:, m] * grad_v.t()[n].matmul(v[:, m]) / (w[n] - w[m])
Can't we simplify that by using sopething like `baddbmm` or some matrix manipulation? This will be very expensive on the GPU as is

2017-07-11 00:14 UTC, fmassa commented on torch/autograd/_functions/linalg.py
> +        g = sum([torch.ger(v[:, n], v[:, n] * grad_w[n] + G(n))
Same here, can't we use a single matrix op to avoid the for loop?

2017-07-11 00:22 UTC, fmassa requested changes
Thanks for the PR! Do you think it would be possible to get `eig` as well?
I made some comments that I think need to be addressed before this PR can be merged. You could get the template for the tests from the gesv or inverse functions (I can give them to you tomorrow if needed, typing from the phone)

2017-07-11 00:22 UTC, fmassa commented on torch/autograd/_functions/linalg.py
> +        ctx.eigenvectors = eigenvectors
Do you use it elsewhere? Also, what happens if `eigenvectors=False`? The backward requires then, right?

2017-07-13 18:37 UTC, ncullen93 commented on torch/autograd/_functions/linalg.py
> +        ctx.eigenvectors = eigenvectors
no, i dont use it elsewhere atm - it's there for your second point on what to do if `eigenvectors=False`. Seems like you shouldn't be able to calculate the backward if so. Should I raise an exception in `backward` if it's called with `eigenvectors=False` ?

2017-07-13 18:39 UTC, ncullen93 commented on torch/autograd/_functions/linalg.py
> +        x = x.data
yeah this is where I'm confused. I don't understand why I have to call `.data` when no other functions do. This does need `x`, `w`, and `v` for the backward.

2017-07-13 18:40 UTC, ncullen93 commented on torch/autograd/_functions/linalg.py
> +            return sum([v[:, m] * grad_v.t()[n].matmul(v[:, m]) / (w[n] - w[m])
yes definitely, but I figure this will be a drop-in replacement once we sort out the other details above.

2017-07-13 18:42 UTC, ncullen93 commented
Major questions right now:

1. What to do if `eigenvectors=False`. I think an exception should be raised, because it's not clear how to compute the gradient without it.

2. Why do I have to call `.data` on `x`, `w`, and `v`? Am I saving those for the backend correctly?

2017-07-13 19:14 UTC, apaszke commented
1. You should probably override the flag and save the result for backward.
2. They're saved correctly, but something must be wrong with your `backward` implementation. What error do you get when you don't unpack the variables?

2017-07-13 19:14 UTC, apaszke commented
Ad 2. You can use `@once_differentiable` and use `ctx.saved_tensors`. It will work, but won't be differentiable twice

2017-07-13 20:31 UTC, ncullen93 commented
Re: 1. Ok, great that's a good solution. I will work on that.

Re: 2. Well I just tested it again - in the codebase, it only works without `.data`. However, implemented stand-alone (i.e. implemented as recommended [here](http://pytorch.org/docs/master/notes/extending.html)) it only works <i>with</i> `.data`. Weird. I updated to reflect this.

I get the standard error:
```python
TypeError: torch.dot received an invalid combination of arguments - got (torch.FloatTensor, !Variable!), but expected (torch.FloatTensor source, torch.FloatTensor tensor)
```

2017-07-13 23:05 UTC, apaszke commented
It seems that the only problem is that you're mixing tensors with Variables, so just making sure that you keep everything wrapped would be enough. Add a couple of prints and see why do they get mixed up

2018-07-31 16:49 UTC, zou3519 commented
I think this is superceded by https://github.com/pytorch/pytorch/pull/8586; please reopen if I am incorrect.

2018-07-31 16:49 UTC, closed without merging