support dictionary return types in __call__
pytorch/pytorch pull request #2037
Opened 2017-07-10 16:53 UTC by DeNeutoy

using `__call__` currently throws an error if the return type of `forward` is a `dict`. It would be useful to be able to return complex outputs with names - this PR just hooks the backward hooks onto an arbitrary element of the return dict (I assumed this was ok because previously the hook is just registered to the first element returned from `forward`). Let me know if i've put the test in the wrong place/ you would like it to be different. 

Thanks!

2017-07-10 21:57 UTC, colesbury commented on test/test_nn.py
> +        net(data)
This doesn't look like it actually tests the new behavior since there are no backward hooks.

2017-07-10 22:50 UTC, DeNeutoy commented on test/test_nn.py
> +        net(data)
My bad - I was thinking from an older version where this would have been run, but it changed recently. Updated with a backward hook with just passes.

2017-07-11 06:01 UTC, apaszke reviewed
This doesn't really seem like a robust solution. It's subject to random crashes if you have at least a single non-Variable key in the dict. Python dicts don't define any ordering on their keys, so the first of `.values()` will be a different thing at every run

2017-07-11 15:37 UTC, matt-gardner commented on torch/nn/modules/module.py
> +                    var = list(var.values())[0]
Would changing this to `list(v in var.values() if isinstance(v, Variable))[0]` resolve that concern?

2017-07-11 16:24 UTC, apaszke commented on torch/nn/modules/module.py
> +                    var = list(var.values())[0]
Yeah that looks better. BTW You can just use `next(...)` instead of `list(...)[0]`.

2017-07-11 16:46 UTC, fmassa commented
For info, here are some related PRs
https://github.com/pytorch/pytorch/pull/1205
https://github.com/pytorch/pytorch/pull/1239

2017-07-12 23:05 UTC, apaszke requested changes
The test seems a bit incomplete. It doesn't even call backward, nor does it check if the hook was actually called. Add a backward call, and set a flag inside the hook and assert that it is set at the end.

2017-08-02 23:19 UTC, DeNeutoy commented
@apaszke, sorry for the delay - hopefully these commits address your concerns!

2017-09-30 23:59 UTC, DELTA37 approved these changes
We are waiting for a merging, we very need this update

2017-10-01 21:39 UTC, apaszke approved these changes

2017-10-02 00:15 UTC, soumith commented
@pytorchbot test this please

2017-10-02 00:33 UTC, merged

2017-10-02 00:33 UTC, soumith commented
thank you @DeNeutoy !