Fix momentum bug in CyclicLR
pytorch/pytorch pull request #20401
Opened 2019-05-12 00:07 UTC by emerali

Resolves issue #19003

The author of this issue also asked that `cycle_momentum` default to `False` if the optimizer does not have a momentum parameter, but I'm not sure what the best way to do this would be. Silently changing the value based on the optimizer may confuse the user in some cases (say the user explicitly set `cycle_momentum=True` but doesn't know that the Adam optimizer doesn't use momentum). 

Maybe printing a warning when switching this argument's value would suffice?

2019-05-13 23:09 UTC, soumith commented
@emerali this looks good, thanks for fixing the bug. Can you add a test to test/test_optim.py that triggers this case so that we dont regress in the future?

2019-05-14 15:12 UTC, ezyang commented on test/test_optim.py
> +        scheduler = CyclicLR(adam_opt, cycle_momentum=False)
You need to actually call `self._test_cycle_lr` here...

2019-05-14 15:12 UTC, ezyang requested changes
test is incomplete

2019-05-15 20:22 UTC, emerali commented
I've fixed the test as requested. It required a little bit of a hack though, as the `TestLRScheduler._test_cycle_lr` function uses the object's internal optimizer (SGD), so I temporarily swapped it out with an Adam optimizer object inside of the test body.

2019-05-17 15:42 UTC, ezyang commented
> It required a little bit of a hack though, as the TestLRScheduler._test_cycle_lr function uses the object's internal optimizer (SGD), so I temporarily swapped it out with an Adam optimizer object inside of the test body.

Would you mind elaborating on this more? (Or @soumith, can you tell what's going on here?) I'm not sure why use of the internal optimizer causes a problem for the test (I might be missing something obvious!)

2019-05-17 16:10 UTC, emerali commented
The `TestLRScheduler` object carries around and SGD optimizer to avoid having to instantiate one for every test. This gets in the way for our very specific case in which we need to use Adam (or really any optimizer that doesn't use momentum) in order to test that the momentum bug in CyclicLR is fixed (the bug is described in more detail in the corresponding issue).

Does that answer your question?

2019-06-01 05:14 UTC, emerali commented
Friendly nudge as this seems to have fallen under the radar.

2019-06-11 19:17 UTC, ezyang commented
@pytorchbot rebase this please

2019-06-11 19:20 UTC, ezyang approved these changes

2019-06-11 19:20 UTC, ezyang commented
I added your comment here as a comment in the code. This is good to go as soon as the rebased CI passes.

2019-06-11 22:13 UTC, closed without merging

2019-10-27 12:43 UTC, mugheesahmad commented
Sorry for the immature question but I am still facing this issue at my PyTorch. kindly suggest me how can I update this in my PyTorch framework.

2020-06-15 12:43 UTC, zwep commented
Yup, same here. Still the same error when using CyclicLR and Adam together

2020-06-16 13:55 UTC, ezyang commented
Try upgrading your version of PyTorch; the latest version should have this fix.

2020-06-17 07:31 UTC, zwep commented
Yeah, even the 1.4 version has this fix. (Just so you know 1.5 is not your only option. Since in 1.5 you also need cuda version 10.2 or so to have it working)

2020-09-21 03:32 UTC, ytfksw commented
This issue has not yet been fixed in the version 1.6...

2020-11-07 23:51 UTC, austinmw commented
I'm using 1.6 and encountered this bug