Fix optimizer type hint
pytorch/pytorch pull request #20648
Opened 2019-05-17 17:31 UTC by TheCodez

Fixes https://github.com/pytorch/pytorch/issues/20548

2019-05-18 22:42 UTC, soumith approved these changes

2019-05-18 22:43 UTC, soumith requested changes
valid contbuild failure:

```
May 17 18:40:58 test_doc_examples (__main__.TestTypeHints) ... torch/optim/optimizer.pyi:4: error: Name 'Dict' is not defined
May 17 18:40:59 FAIL
```

2019-05-20 16:51 UTC, TheCodez commented
@soumith my bad. I fixed it now.

2019-05-20 19:02 UTC, soumith approved these changes
@pytorchbot merge this please

2019-05-22 18:30 UTC, closed without merging