sum_pool2d for LongTensor
pytorch/pytorch pull request #20731
Opened 2019-05-20 22:39 UTC by ifedan

2019-06-06 15:59 UTC, gchanan commented
can we add an optional "divisor" or something to AvgPool instead of adding an additional module?

2019-06-12 19:00 UTC, gchanan requested changes

2019-06-13 16:24 UTC, gchanan requested changes
In C++, can the paramter be `optional<Scalar>` / `Scalar?` in the schema?

2019-07-02 18:46 UTC, ifedan commented
PR was merged and moved to https://github.com/pytorch/pytorch/pull/22433/

2019-07-02 18:46 UTC, closed without merging