Moved THTensor_(cauchy) to ATen
pytorch/pytorch pull request #21086
Opened 2019-05-29 20:07 UTC by moon05

I think the headings says it all. Will update if more description is necessary.

2019-05-29 20:18 UTC, syed-ahmed requested changes
Wait for this to go in: https://github.com/pytorch/pytorch/pull/20622. Otherwise LGTM :)

2019-05-29 20:18 UTC, syed-ahmed commented on aten/src/ATen/Declarations.cwrap
>    types:
Once https://github.com/pytorch/pytorch/pull/20622 is in, remove this whole block: 
```
[[
  name: _th_cauchy_
  types:
    - floating_point
  backends:
    - CPU
  cname: cauchy
  variants: function
  return: self
  arguments:
    - THTensor* self
    - arg: THGenerator* generator
      default: nullptr
      kwarg_only: True
    - arg: double median
      default: 0
    - arg: double sigma
      default: 1
]]
```

2019-05-29 20:18 UTC, syed-ahmed commented on aten/src/ATen/native/LegacyDefinitions.cpp
> +  return at::legacy::th::_th_cauchy_(self, median, sigma, generator);
Remove this function when this is in: https://github.com/pytorch/pytorch/pull/20622

2019-05-29 20:18 UTC, syed-ahmed commented on aten/src/ATen/native/native_functions.yaml
> +  - func: cauchy_(Tensor(a!) self, float median=0, float sigma=1, *, Generator? generator=None) -> Tensor(a!)
there is an extra space in front of the `- func`

2019-06-06 16:53 UTC, ezyang commented
Obsoleted by @syed-ahmed's port,

2019-06-06 23:51 UTC, syed-ahmed commented
Re-opening because this is porting the CPU side from TH to ATen. I didn't do that in my PR.

2019-06-07 00:38 UTC, syed-ahmed approved these changes

2019-06-07 02:06 UTC, ezyang commented
@pytorchbot rebase this please

2019-06-07 14:35 UTC, zou3519 requested changes
Could we see some before/after performance numbers to ensure there isn't a performance regression?

2019-07-11 21:15 UTC, fmassa commented on aten/src/ATen/native/Distributions.cpp
> +    CPU_tensor_apply1<scalar_t>(
Shouldn't we be preferably using TensorIterator here instead?

2019-07-12 17:20 UTC, VitalyFedyunin commented on aten/src/ATen/native/Distributions.cpp
> +    CPU_tensor_apply1<scalar_t>(
To be honest we havn't yet tested parallel calls to random generators. `CPU_tensor_apply1` here does serial processing.

2019-08-16 19:59 UTC, VitalyFedyunin commented
Implements #24684

2019-08-17 19:30 UTC, ezyang commented
@moon05 Do you still have time to work on this PR?

2022-06-27 20:36 UTC, closed without merging