Operator Metadata
pytorch/pytorch pull request #21083
Opened 2019-05-29 19:54 UTC by smessmer

2019-05-30 05:47 UTC, zdevito requested changes
We need further discussion before this approach is landed. It seems more complicated than needed right now and further encourages a dumping ground for arbitrary stuff about operators. It _should_ be difficult to add new operator information, because any additional thing then requires all ~400 operators to add that info. This design encourages the opposite by using extra machinery to make it easy to add addition info to operators.

2019-05-30 05:47 UTC, zdevito commented on aten/src/ATen/core/dispatch/OperatorMetadata.h
> + * OperatorMetadataType is an extensible way to store metadata for an operator
I think this is over-engineered. We _don't want_ people adding arbitrary stuff here, we want to just have storage for the specific things we know we care about.

Meta-data is a code smell. There is either data we understand and can name. Or there is data we do not know anything about, and should not be in the business of storing.

2019-05-30 18:38 UTC, dzhulgakov reviewed
I think it's better to start with hard-coded metadata structure in a single place before we introduce arbitrary open registration.

Reasoning: it's really hard to guarantee coverage if both metadata categories and operator are open registered.

The only problem might be build cyclical dependencies. But using raw c++ types (and ongoing .so unification) should help here.

2019-05-31 00:14 UTC, smessmer commented
superseded by https://github.com/pytorch/pytorch/pull/21181

2019-05-31 00:14 UTC, closed without merging