Improve build docs for Windows
pytorch/pytorch pull request #21190
Opened 2019-05-31 06:13 UTC by peterjc123

1. Improve build docs for Windows
2. Change `BUILD_SHARED_LIBS=ON` for Caffe2 local builds
3. Change to out-source builds for LibTorch and Caffe2

2019-05-31 10:54 UTC, peterjc123 commented
@pytorchbot rebase this please

2019-05-31 13:17 UTC, ezyang commented
Waiting for Windows CI to finish

2019-05-31 13:19 UTC, ezyang commented
Maybe we should just give Windows install its own section in the README? I'm happy to rearrange things if you think so.

2019-05-31 13:32 UTC, peterjc123 commented
@pytorchbot retest this please

2019-05-31 16:14 UTC, peterjc123 commented
This test is failing on Windows but I don't think it's caused by this PR.
```
15:36:10 ======================================================================
15:36:10 FAIL: test_Conv2d_groups_nobias_v2 (__main__.TestNN)
15:36:10 ----------------------------------------------------------------------
15:36:10 Traceback (most recent call last):
15:36:10   File "test_nn.py", line 4804, in test_Conv2d_groups_nobias_v2
15:36:10     self.assertEqual(output, torch.cat([output1, output2], 1))
15:36:10   File "C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-test1\test\common_utils.py", line 503, in assertEqual
15:36:10     assertTensorsEqual(x, y)
15:36:10   File "C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-test1\test\common_utils.py", line 495, in assertTensorsEqual
15:36:10     self.assertLessEqual(max_err, prec, message)
15:36:10 AssertionError: tensor(1.5259e-05, device='cuda:0', dtype=torch.float16,
15:36:10        grad_fn=<MaxBackward1>) not less than or equal to 1e-05 : 
15:36:10 
15:36:10 ----------------------------------------------------------------------
```

2019-05-31 19:52 UTC, ezyang commented
Yes, Windows was broken this morning. Should be fixed now.

@pytorchbot rebase this please

Excerpts from peterjc123's message of 2019-05-31 09:15:36 -0700:
> This test is failing on Windows but I don't think it's caused by this PR.
> ```
> 15:36:10 ======================================================================
> 15:36:10 FAIL: test_Conv2d_groups_nobias_v2 (__main__.TestNN)
> 15:36:10 ----------------------------------------------------------------------
> 15:36:10 Traceback (most recent call last):
> 15:36:10   File "test_nn.py", line 4804, in test_Conv2d_groups_nobias_v2
> 15:36:10     self.assertEqual(output, torch.cat([output1, output2], 1))
> 15:36:10   File "C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-test1\test\common_utils.py", line 503, in assertEqual
> 15:36:10     assertTensorsEqual(x, y)
> 15:36:10   File "C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-test1\test\common_utils.py", line 495, in assertTensorsEqual
> 15:36:10     self.assertLessEqual(max_err, prec, message)
> 15:36:10 AssertionError: tensor(1.5259e-05, device='cuda:0', dtype=torch.float16,
> 15:36:10        grad_fn=<MaxBackward1>) not less than or equal to 1e-05 : 
> 15:36:10 
> 15:36:10 ----------------------------------------------------------------------
> ```
>

2019-06-02 09:24 UTC, peterjc123 commented
@pytorchbot rebase this please

2019-06-03 14:05 UTC, ezyang commented on tools/build_libtorch.py
> +                 rerun_cmake=True, cmake_only=False, build_dir='build')
This is probably causing the Caffe2 tests to fail; we'll need to fix the paths.

2019-06-03 14:06 UTC, ezyang requested changes
Build failures seem legit

2019-06-04 14:17 UTC, peterjc123 commented
@ezyang Could you please tell me which part of the cmake script is related to the installation of the `test_jit` binary when doing out-source builds?

2019-06-06 08:57 UTC, peterjc123 commented
@ezyang I moved that part to #21452, so it won't block CI build anymore.

2019-06-06 15:01 UTC, ezyang approved these changes

2019-06-06 15:02 UTC, ezyang commented
> Could you please tell me which part of the cmake script is related to the installation of the test_jit binary when doing out-source builds?

I'm not sure. Do you want me to look at this more closely? It's probably one of the scripts in `.jenkins` (or possibly `.circleci`)

2019-06-06 15:46 UTC, ezyang commented
Merge conflict?!

2019-06-06 16:09 UTC, peterjc123 commented
@ezyang Resolved.

2019-06-06 20:49 UTC, closed without merging