Make rshift implementation consistent between pytorch and numpy
pytorch/pytorch pull request #21414
Opened 2019-06-05 15:48 UTC by ifedan

Currently rshift function is inconsistent between numpy and pytorch:
```
>>> import torch
>>> import numpy as np
>>> a = torch.tensor([-1], dtype=torch.int, device="cpu")
>>> a >> 1
tensor([2147483647], dtype=torch.int32)
>>> a = torch.tensor([-1], dtype=torch.int, device="cuda")
>>> a >> 1
tensor([-1], device='cuda:0', dtype=torch.int32)
>>> a = np.array([-1])
>>> a >> 1
array([-1])
```

2019-06-05 18:52 UTC, gchanan commented on test/test_torch.py
> +    def test_rshift_same_as_numpy(self):
this needs to check that numpy is available (see other tests)

2019-06-10 13:09 UTC, apaszke commented
Or maybe we should just forbid shifts for signed types? Aren’t those implementation-defined in C++?

2019-06-11 12:41 UTC, apaszke requested changes
Yep, shifts of signed numbers are implementation-dependent, and shifts of floating points are not supported in C/C++. I really think we should forbid those operations for all but unsigned types.

2019-06-18 22:41 UTC, gchanan commented
@apaszke I would agree if we had good support unsigned int types, so users could easily specify what they wanted, but we don't.  There's just no good alternative.

Given that, plus these other reasons below, I'm inclined to accept this:
1) we already supplied this functionality to users (if inconsistently)
2) numpy implements this the same way
3) we are literally just translating the C++ call (I'm okay putting a warning though).

2019-06-18 22:46 UTC, gchanan requested changes
Please provide a better PR description; there's no explanation of the issue (i.e. discussion about how it's implementation defined, what the BC-breaking change is).

2019-06-18 22:46 UTC, gchanan commented on aten/src/TH/generic/THTensorEvenMoreMath.cpp
> +        rp[i] = ((accreal) tp[i]) >> value;
why is doing this in terms of accreal the correct thing to do as opposed to scalar_t?

2019-06-22 22:15 UTC, apaszke commented
I don't know, shifts on signed types feel like something you _really_ don't want to do... I would really be ok and would feel much better if we limited this only to byte tensors.

2022-07-11 03:50 UTC, closed without merging