Add a postfix to binaries to make mixed packaging easier
pytorch/pytorch pull request #21586
Opened 2019-06-10 13:19 UTC by sarthakpati

2019-06-11 05:01 UTC, peterjc123 reviewed
Yes, that's great! But I guess you'll need to change `FindTorch.cmake` too. Otherwise, it will break the linkage to the debug version of LibTorch DLLs.

2019-06-11 05:10 UTC, peterjc123 commented
The related file: https://github.com/pytorch/pytorch/blob/master/cmake/TorchConfig.cmake.in.
An example from CMake: https://gitlab.kitware.com/cmake/cmake/merge_requests/2398/diffs#c02662467bc732b07e07137a73750ae1ae0b6ca3_45_53

2019-06-11 13:04 UTC, sarthakpati commented
@peterjc123 Done! https://github.com/sarthakpati/pytorch/commit/a81224456003640ec94094310585e4463dca5876

2019-06-12 08:52 UTC, peterjc123 requested changes
I don't think they are correct. BTW, you'll have to do that for Caffe2 libraries too.

2019-06-12 08:52 UTC, peterjc123 commented on cmake/TorchConfig.cmake.in
> +  set(TORCH_LIBRARIES ${TORCH_LIBRARY_RELEASE} ${TORCH_LIBRARY_DEBUG} ${Caffe2_MAIN_LIBS})
I don't think linking against both the debug and release libraries will work here. You should use `select_library_configurations` as an alternative.

2019-06-12 08:52 UTC, peterjc123 commented on cmake/TorchConfig.cmake.in
> +  list(APPEND TORCH_LIBRARIES ${C10_LIBRARY_DEBUG} ${C10_LIBRARY_RELEASE})
and here

2019-06-12 08:52 UTC, peterjc123 commented on cmake/TorchConfig.cmake.in
> +    list(APPEND TORCH_CUDA_LIBRARIES ${C10_CUDA_LIBRARY_DEBUG} ${C10_CUDA_LIBRARY_RELEASE})
here, too.

2022-07-11 03:50 UTC, closed without merging