Remove the misguided attempt at TORCH_STATIC.
pytorch/pytorch pull request #21704
Opened 2019-06-12 21:37 UTC by ezyang

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

TORCH_STATIC does something, but it's not what you want.  What the
TORCH_STATIC toggle does is cause libtorch to be generated as a static
library, rather than a dynamic library.  This sounds useful, until you
realize that it doesn't affect any of the *other* libraries we also
define in PyTorch, e.g., libcaffe2 or libc10, etc. etc.  So you end up
with one library that is static... that links to a pile of dynamic
libraries.  Not useful.

The proper way to build everything "static" is to set -DBUILD_SHARED_LIBS=OFF
which will turn the interpretation of any add_library() specifier to
generate a static library (assuming you didn't override it with SHARED
which is what happened here).

There is some attempt at building static libraries in builder, but it
doesn't seem to work, and in any case we don't seem to publish them.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

2019-06-12 21:39 UTC, soumith approved these changes

2019-06-12 21:42 UTC, kostmo requested changes
Can you hold off on this?  I'm trying to land the last piece of my unification work, and this will conflict.

2019-06-13 02:17 UTC, xsacha commented
Essentially everything should be static or shared.
So TORCH_STATIC shouldn't exist but it should instead comply to BUILD_SHARED_LIBS CMake varaible.

Thanks for this, it has been such a simple but annoying issue.
I hope to also see static nightly/stable builds if possible?

2019-06-13 04:37 UTC, kostmo commented
#20774 is landed, so it's ok to proceed with this now, thanks.

2019-06-13 04:38 UTC, kostmo approved these changes

2019-06-13 05:03 UTC, peterjc123 approved these changes
I'm just wondering why merging `torch` and `torch_gpu` doesn't trigger the error on the `build_shared_libs=off` builds on Windows. They are almost close to the maximum size (2GB) before merging.

2019-06-13 05:19 UTC, peterjc123 commented
@xsacha I was working on that, but still has some problems generating the new Windows AMI. I could not tell whether the issue is actually on MSBuild or the CMake side, but using this combination will throw some weird build errors, mainly related to some racing conditions when running the custom build jobs.

2019-06-13 15:45 UTC, ezyang commented on caffe2/CMakeLists.txt
> +add_library(torch ${DUMMY_EMPTY_FILE})
I think @kostmo is the one who would know. But I think we just need to swing over all the source files from caffe2 to torch.

2019-06-13 15:46 UTC, ezyang commented
@xsacha At the end of this I too would like to see a static libtorch build. But there are a lot of roadblocks along the way. I'm working on a write up right now.

2019-06-13 15:49 UTC, ezyang commented
It looks after @kostmo's patch `TORCH_STATIC` is gone anyway, so this PR is moot.

2019-06-13 15:49 UTC, closed without merging

2019-07-12 18:23 UTC, rishikhan commented
@ezyang Is there any progress on the roadblock to a static build? I'd like to see this happen too.

2019-07-14 15:41 UTC, ezyang commented
Take a look at https://github.com/pytorch/pytorch/issues/21737 at this
point the issue just needs hands.

Excerpts from Rishi Khan's message of 2019-07-12 11:25:01 -0700:
> @ezyang Is there any progress on the roadblock to a static build? I'd like to see this happen too.
>