default_collate: Support regular tuples as well as namedtuple
pytorch/pytorch pull request #21788
Opened 2019-06-14 17:04 UTC by cannon

2019-06-14 18:11 UTC, zhangguanheng66 commented
@SsnL Appreciate it if you could review this PR.

2019-06-14 18:17 UTC, SsnL commented
I'm not against this. This is sort of BC breaking, but I don't think it matters much. But this deserves a test.

2019-06-14 18:26 UTC, ssnl requested changes
thanks! but this needs a test.

2019-06-16 03:37 UTC, SsnL commented on torch/utils/data/_utils/collate.py
>          return type(batch[0])(*(default_collate(samples) for samples in zip(*batch)))
oh and the tuple ctor can not be called this way, so this should be another elif.

2022-06-27 20:36 UTC, closed without merging