handle slice with negative indices and indices exceeding tensor dimen…
pytorch/pytorch pull request #21811
Opened 2019-06-15 00:37 UTC by liqunfu

handle slice with negative indices and indices exceeding tensor dimensions.

2019-06-19 18:19 UTC, spandantiwari requested changes

2019-06-21 16:12 UTC, liqunfu commented on test/onnx/test_utility_funs.py
> +    def test_constant_fold_narrow(self):
resolved

2019-06-21 16:54 UTC, spandantiwari approved these changes
LGTM.

2019-06-21 18:26 UTC, houseroad approved these changes
LGTM, thanks.

2019-06-21 18:26 UTC, houseroad commented on test/onnx/test_utility_funs.py
> +        graph, _, __ = utils._model_to_graph(NarrowModule(), (x, ),
nit: __ => _

also can you change all the __ to _?

2019-06-21 18:26 UTC, houseroad commented on torch/csrc/jit/passes/onnx/constant_fold.cpp
> +      updated_val = at::narrow(updated_val, axis, start, length);
you may also want to try at::slice

2019-06-21 20:35 UTC, houseroad commented
will merge this pr first, feel free to open another pr to address nits.

2019-06-21 20:40 UTC, closed without merging