Return device object instead of device index for torch.cuda.current_device
pytorch/pytorch pull request #21982
Opened 2019-06-19 20:08 UTC by Stonesjtu

Semantically `current_device` should return a device object. It may break some backwards-compatibility BTW.

2019-06-19 20:30 UTC, SsnL commented
Just a note, this is BC breaking.

2019-06-19 22:27 UTC, soumith requested changes
this is very very very BC breaking, i dont think this should go in without a proper deprecation path

2019-06-19 22:32 UTC, Stonesjtu commented
My advice would be to add a new API named `current_device_id`.

2019-06-20 20:39 UTC, SsnL commented
> My advice would be to add a new API named `current_device_id`.


This is not a deprecation plan. And you can just do `device.index` instead of adding a new `current_device_id`.

This will break a lot old code, and I don't know if the benefit justifies it.

2019-06-20 21:31 UTC, Stonesjtu commented
Or can we just update the documents for this function?

2019-06-20 22:18 UTC, SsnL commented
@Stonesjtu go ahead, we will happily accept a PR that updates the doc.

2019-06-25 03:42 UTC, soumith commented
closing until the PR just becomes a doc update

2019-06-25 03:42 UTC, closed without merging

2019-08-08 10:07 UTC, Stonesjtu commented
Sorry for the late reply, but it seems the doc has been updated already.