TRT5-friendly ONNX exporter
pytorch/pytorch pull request #22001
Opened 2019-06-19 23:22 UTC by drnikolaev

This PR addresses  #21727 and replaces Gather-by-axis-0 cases with shorter Slice operators making output onnx files to be TRT5 and ONNX Runtime compatible. Also, minor issues with million annoying warnings have been fixed. As a bonus track, Filler Op now really asserts input tensor to be 1D.

2019-06-19 23:29 UTC, drnikolaev commented
@houseroad

2019-07-08 22:02 UTC, drnikolaev commented
Also, this would be terrific to put these tests back to CI, see #21727 for details.

2019-07-08 22:43 UTC, houseroad commented
Sorry about the delay, will check this PR soon.

2019-07-09 06:04 UTC, houseroad requested changes
Thanks a lot for sending this PR.

It did multiple things together. Some changes are good to land, and some need more polish. I would like to split the changes into small PRs: 1) filler_op change, 2) ignore the warning (I would like to know what warnings are suppressed), 3) skip tests, 4) constant folding change, 5) gather -> slice change. 
This split will make reviewing and landing code easier.

2019-07-12 06:09 UTC, drnikolaev commented on caffe2/python/brew.py
> +            with warnings.catch_warnings():
Deprecation warning. Lot's of them. I'll put a comment in a separate PR.

2019-07-12 06:15 UTC, drnikolaev commented on test/onnx/test_pytorch_onnx_caffe2.py
> +    @skipIfEmbed  # TODO - error above in embedded case only
No,it does not pass in master, checked today:
```
$ ./scripts/onnx/test.sh
....
======================================= 22 failed, 1012 passed, 473 skipped, 7 deselected, 11855 warnings in 475.59 seconds ========================================
```
I could investigate why but let's first make the world green then cherry-pick and fix those 22 bad guys. Makes sense?

2019-07-12 06:30 UTC, drnikolaev commented on torch/csrc/jit/passes/onnx/constant_fold.cpp
> +%30 : Float(2, 256, 6, 6) = onnx::AveragePool[kernel_shape=[1, 1],strides=[1, 1]](%29), scope:
@houseroad @spandantiwari - this is actually the main thing breaking PT-exported ONNX. It feels like hacky but it's localized. I thought about to make it on demand feature but passing boolean switch to this place seems to be too much either. I'd love to hear your ideas about alternatives. These 5 operators are all over the place and they should be collapsed one way or another.

2019-07-12 21:34 UTC, spandantiwari commented on torch/csrc/jit/passes/onnx/constant_fold.cpp
> +%30 : Float(2, 256, 6, 6) = onnx::AveragePool[kernel_shape=[1, 1],strides=[1, 1]](%29), scope:
hi @drnikolaev - the current constant folding is written to fold only sub-tree starting with a leaf node. It seems like you are doing something similar in your CollectFoldables() method. If that's the intent then I agree with @houseroad that we should handle this case seamlessly in the existing code and fix any issues. If that is not the intent and this is not working with leaf nodes only, then I would suggest creating a new pass for this, and not try to handle everything here to keep the code design clean.

2019-07-19 08:23 UTC, drnikolaev commented on caffe2/python/rnn_cell.py
> +        with warnings.catch_warnings():
Fied in #23064

2019-07-19 08:44 UTC, drnikolaev commented on test/onnx/test_pytorch_onnx_caffe2.py
> +    @skipIfEmbed  # TODO - error above in embedded case only
#21727 for details

2021-08-31 21:58 UTC, garymm commented
since there's been no response to @houseroad and @spandantiwari comments in over 2 years, I'm closing this.
@drnikolaev please feel free to open a new PR (ideally against onnx_ms_1) if you'd like to revive any of these changes.

2021-08-31 21:58 UTC, closed without merging