Add hidden visibility to _C.so
pytorch/pytorch pull request #22076
Opened 2019-06-21 16:09 UTC by dzhulgakov

See https://pybind11.readthedocs.io/en/stable/faq.html#someclass-declared-with-greater-visibility-than-the-type-of-its-field-someclass-member-wattributes

Let's see whether it passes CI

2019-06-21 16:23 UTC, soumith commented
wouldn't C++ extensions fail because of this? they require the symbols coming out of libtorch_python and stuff to be global visibility in the current process, or else they fail to load at runtime (but the C++ extensions will compile fine)

2019-06-21 16:26 UTC, xuhdev commented on torch/CMakeLists.txt
> +if (NOT WIN32)
Do you think it's better to put `if (NOT MSVC)` here?

2019-06-21 17:11 UTC, ezyang commented
UBSAN failure looks real:

```
Jun 21 16:45:39 /var/lib/jenkins/workspace/build/aten/src/ATen/Functions.h:2779:12: runtime error: call to function at::TypeDefault::randn(c10::ArrayRef<long>, c10::TensorOptions const&) through pointer to incorrect function type 'at::Tensor (*)(c10::ArrayRef<long>, const c10::TensorOptions &)'
Jun 21 16:45:39 (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch.so+0xa6b7860): note: at::TypeDefault::randn(c10::ArrayRef<long>, c10::TensorOptions const&) defined here
Jun 21 16:45:40     #0 0x7f25f2696882 in torch::randn(c10::ArrayRef<long>, c10::TensorOptions const&) (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so+0x11aa882)
Jun 21 16:45:40     #1 0x7f25f2694ccc in torch::autograd::dispatch_randn(c10::ArrayRef<long>, c10::TensorOptions const&) (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so+0x11a8ccc)
Jun 21 16:45:40     #2 0x7f25f258d08d in torch::autograd::THPVariable_randn(_object*, _object*, _object*) (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so+0x10a108d)
Jun 21 16:45:40     #3 0x558025dc7743 in _PyCFunction_FastCallDict /tmp/build/80754af9/python_1546130271559/work/Objects/methodobject.c:231
Jun 21 16:45:40     #4 0x558025e4e42b in call_function /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4851
Jun 21 16:45:40     #5 0x558025e73389 in _PyEval_EvalFrameDefault /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
Jun 21 16:45:40     #6 0x558025e47bfd in _PyEval_EvalCodeWithName /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
Jun 21 16:45:40     #7 0x558025e48770 in fast_function /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4992
Jun 21 16:45:40     #8 0x558025e4e504 in call_function /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4872
Jun 21 16:45:40     #9 0x558025e73389 in _PyEval_EvalFrameDefault /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
Jun 21 16:45:40     #10 0x558025e49288 in _PyEval_EvalCodeWithName /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
Jun 21 16:45:40     #11 0x558025e49288 in PyEval_EvalCodeEx /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4187
Jun 21 16:45:40     #12 0x558025e4a01b in PyEval_EvalCode /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:731
Jun 21 16:45:40     #13 0x558025e70c8a in builtin_exec_impl.isra.11 /tmp/build/80754af9/python_1546130271559/work/Python/bltinmodule.c:983
Jun 21 16:45:40     #14 0x558025e70c8a in builtin_exec /tmp/build/80754af9/python_1546130271559/work/Python/clinic/bltinmodule.c.h:283
Jun 21 16:45:40     #15 0x558025dca710 in PyCFunction_Call /tmp/build/80754af9/python_1546130271559/work/Objects/methodobject.c:114
Jun 21 16:45:40     #16 0x558025e784ac in do_call_core /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:5116
Jun 21 16:45:40     #17 0x558025e784ac in _PyEval_EvalFrameDefault /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3404
Jun 21 16:45:40     #18 0x558025e478e3 in _PyEval_EvalCodeWithName /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
Jun 21 16:45:40     #19 0x558025e48770 in fast_function /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4992
Jun 21 16:45:40     #20 0x558025e4e504 in call_function /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4872
Jun 21 16:45:40     #21 0x558025e73389 in _PyEval_EvalFrameDefault /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
Jun 21 16:45:40     #22 0x558025e4853a in _PyFunction_FastCall /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4933
Jun 21 16:45:40     #23 0x558025e4853a in fast_function /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4968
Jun 21 16:45:40     #24 0x558025e4e504 in call_function /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4872
Jun 21 16:45:40     #25 0x558025e73389 in _PyEval_EvalFrameDefault /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
Jun 21 16:45:40     #26 0x558025e4853a in _PyFunction_FastCall /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4933
Jun 21 16:45:40     #27 0x558025e4853a in fast_function /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4968
Jun 21 16:45:40     #28 0x558025e4e504 in call_function /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4872
Jun 21 16:45:40     #29 0x558025e73389 in _PyEval_EvalFrameDefault /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
Jun 21 16:45:40     #30 0x558025e4853a in _PyFunction_FastCall /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4933
Jun 21 16:45:40     #31 0x558025e4853a in fast_function /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4968
Jun 21 16:45:40     #32 0x558025e4e504 in call_function /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4872
Jun 21 16:45:40     #33 0x558025e73389 in _PyEval_EvalFrameDefault /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
Jun 21 16:45:40     #34 0x558025e48baa in _PyFunction_FastCall /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4933
Jun 21 16:45:40     #35 0x558025e48baa in _PyFunction_FastCallDict /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:5035
Jun 21 16:45:40     #36 0x558025dc7b0e in _PyObject_FastCallDict /tmp/build/80754af9/python_1546130271559/work/Objects/abstract.c:2310
Jun 21 16:45:40     #37 0x558025e0980f in _PyObject_CallMethodIdObjArgs /tmp/build/80754af9/python_1546130271559/work/Objects/abstract.c:2796
Jun 21 16:45:40     #38 0x558025dbeb0f in PyImport_ImportModuleLevelObject /tmp/build/80754af9/python_1546130271559/work/Python/import.c:1578
Jun 21 16:45:40     #39 0x558025e75a8a in import_name /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:5245
Jun 21 16:45:40     #40 0x558025e75a8a in _PyEval_EvalFrameDefault /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:2899
Jun 21 16:45:40     #41 0x558025e49288 in _PyEval_EvalCodeWithName /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
Jun 21 16:45:40     #42 0x558025e49288 in PyEval_EvalCodeEx /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4187
Jun 21 16:45:40     #43 0x558025e4a01b in PyEval_EvalCode /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:731
Jun 21 16:45:40     #44 0x558025ecc3c3 in run_mod /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:1025
Jun 21 16:45:40     #45 0x558025ecc7c0 in PyRun_FileExFlags /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:978
Jun 21 16:45:40     #46 0x558025ecc9c2 in PyRun_SimpleFileExFlags /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:419
Jun 21 16:45:40     #47 0x558025ed04b2 in run_file /tmp/build/80754af9/python_1546130271559/work/Modules/main.c:340
Jun 21 16:45:40     #48 0x558025ed04b2 in Py_Main /tmp/build/80754af9/python_1546130271559/work/Modules/main.c:811
Jun 21 16:45:40     #49 0x558025d9902d in main /tmp/build/80754af9/python_1546130271559/work/Programs/python.c:69
Jun 21 16:45:40     #50 0x7f26053c082f in __libc_start_main /build/glibc-LK5gWL/glibc-2.23/csu/../csu/libc-start.c:291
Jun 21 16:45:40     #51 0x558025e79e0d in _start /home/rdonnelly/mc/conda-bld/compilers_linux-64_1534865402226/work/.build/src/glibc-2.12.2/csu/../sysdeps/x86_64/elf/start.S:103
Jun 21 16:45:40 
Jun 21 16:45:40 SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /var/lib/jenkins/workspace/build/aten/src/ATen/Functions.h:2779:12 in 
Jun 21 16:45:40 Traceback (most recent call last):
```

2019-06-21 17:12 UTC, ezyang commented
I guess, ideally, we'd expose symbols that our ours, but not expose anything from pybind11. I don't know how easy that is to do. (Maybe this is a reason not to use pybind11, but that ship has kind of sailed...)

2019-06-21 18:42 UTC, xuhdev commented
If everything works on MSVC with its default option -- that is, no exposure unless explicitly asked to -- could replacing all occurrences of `__declspec(dllexport)` with something also compatible with `gcc` work? Like something similar to [this](https://stackoverflow.com/a/8258786/1150462)?

2019-06-24 07:01 UTC, dzhulgakov commented
Yes, I realized that it needs adjusting annotations.

As @xuhdev pointed out, we should have already annotated all the right things to make Windows work. But we use windows-only macro in THP_API/THP_CLASS (https://github.com/pytorch/pytorch/blob/master/torch/csrc/THP_export.h). We should do the same thing as for other places - https://github.com/pytorch/pytorch/blob/master/c10/macros/Export.h

I'll try to get back to it at some point.

2019-06-24 13:36 UTC, ezyang requested changes
Needs work

2022-05-12 03:46 UTC, closed without merging