Numerical stability of embedding kernels
pytorch/pytorch pull request #22401
Opened 2019-07-01 19:10 UTC by madsbk

Address the issue raised in #22377

2019-07-01 19:48 UTC, ngimel requested changes
there is still partials_per_segment_offset device_vector, and direct access to its elements.

2019-07-01 19:54 UTC, madsbk commented
It was my impression that the `policy` in `thrust::exclusive_scan` would make it use the THC allocator? 

The  direct access to the two elements is unfortunately necessary. It need to know the size of `partial_segment_offset` and how many threads to spawn.

2019-07-01 20:07 UTC, ngimel commented
device_vector with default allocator template argument https://github.com/pytorch/pytorch/pull/22401/files#diff-5e16509ef3a09789b80e5d16f8dc3062R248 won't use any specified policy, as there's no policy argument in the constructor. 
It's unfortunate about accesses to device memory, if this results in the slowdown for other workloads perhaps the old path will need to be brought back (also it will be needed for cuda graphs later on), but for now it's not a blocker. device_vector is, though.

2019-07-01 20:29 UTC, madsbk commented
Make sense, thanks

2019-07-01 20:47 UTC, ngimel approved these changes
approving, hope this will fix @chenyangyu1988 accuracy problems.

2019-07-02 03:24 UTC, mrshenli commented on aten/src/ATen/native/cuda/EmbeddingBackwardKernel.cu
> +#include <torch/types.h>
@madsbk  I think this file should not include headers under `torch/csrc/api`. If you need to use `torch::kFloat16` and `torch::kFloat32`, you can replace them with `at::kHalf` and `at::kFloat` [[link](https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/include/torch/types.h#L24-L25)].

2019-07-02 15:55 UTC, closed without merging