hardshrink_cpu and hardshrink_backward_cpu refactoring with at::native::cpu_kernel
pytorch/pytorch pull request #22459
Opened 2019-07-02 18:56 UTC by pbelevich

2019-07-02 20:26 UTC, fmassa commented
We can potentially get better performance tha is to vectorization if you move this code to the `cpu` folder, see binary ops there for an example

2019-07-05 14:41 UTC, VitalyFedyunin commented
Please include performance comparison and measurements strategy as part of PR description.

2019-07-05 17:33 UTC, fmassa commented on aten/src/ATen/native/Activation.cpp
> +#include <ATen/native/cpu/Loops.h>
nit: is this header needed, now that you have moved the loops to the `cpu/` folder?

2019-07-06 00:02 UTC, pbelevich commented
CPU_tensor_apply2: 4.88 ms ± 213 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
cpu_kernel:         223 µs ± 2.72 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
cpu_kernel_vec:    40.1 µs ± 7.64 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

cpu_kernel_vec gives 100x performance boost

2019-07-07 19:48 UTC, VitalyFedyunin commented on aten/src/ATen/native/cpu/Activation.cpp
> +        return ((self_val < -lambd_val) | (self_val > lambd_val)) & grad_val;
Im not sure we support & for such use case, can you please write a test that compares internal implementation and manual python iteration over numel > 50000k 1D tensor.

2019-07-15 15:24 UTC, VitalyFedyunin requested changes
Please undo submodule changes

2019-07-16 11:51 UTC, pbelevich commented
@pytorchbot retest this please

2019-07-16 14:51 UTC, pbelevich commented
@pytorchbot retest this please

2019-07-16 16:52 UTC, VitalyFedyunin approved these changes
Everything looks good, you may or may not apply additional changes request before landing.

2019-07-16 16:52 UTC, VitalyFedyunin commented on aten/src/ATen/native/Activation.cpp
> +  hardshrink_cpu_stub(iter->device_type(), *iter, lambd);
`hardshrink_cpu_stub(kCPU, *iter, lambd);` just to be sure, as we are in the CPU function

2019-07-16 16:52 UTC, VitalyFedyunin commented on aten/src/ATen/native/Activation.cpp
> +  hardshrink_backward_cpu_stub(iter->device_type(), *iter, lambd);
`hardshrink_cpu_stub(kCPU, *iter, lambd);` just to be sure, as we are in the CPU function

2019-07-16 21:01 UTC, pbelevich commented
@pytorchbot retest this please

2019-07-17 02:01 UTC, closed without merging