Make shuffling optional in DistributedSampler
pytorch/pytorch pull request #22479
Opened 2019-07-02 23:43 UTC by dehuacheng

Summary:
In some cases, for example, when we training on CTR data, we would like to start training from old samples and finish on new recent samples.

This diff add the option to disable the shuffling in DistributedSampler to accommodate this use case.

Differential Revision: D16100388

2019-07-03 00:36 UTC, soumith requested changes

2019-07-03 00:36 UTC, soumith commented on torch/utils/data/distributed.py
> +            torch.randperm(len(self.dataset), generator=g).tolist()
break this out into a separate if/else block, instead inlining if/else inside indices = (

2019-07-03 00:38 UTC, soumith commented
I'm also really confused. If you dont need random shuffling, you dont need a DistributedSampler at all, right?
It will just be a pure iterator with no shuffling

2019-07-06 00:30 UTC, soumith commented
okay, nevermind, this actually makes sense to effectively do sharding without shuffling. It took me a second to wrap my head around this

2019-07-06 00:30 UTC, soumith approved these changes

2019-07-06 01:59 UTC, closed without merging

2019-07-06 04:56 UTC, SsnL commented
test?

2019-07-09 07:00 UTC, soumith commented
my bad on the code review. i should've requested a test