[UpSample nearest]
pytorch/pytorch pull request #22602
Opened 2019-07-08 23:32 UTC by jjsjann123

1. update on restricting block.z <= 64, compliant to CUDA maximum z-dimension of
a block;
2. clang-format

2019-07-09 00:15 UTC, ngimel commented
test case please?

2019-07-09 00:24 UTC, ngimel commented on aten/src/ATen/native/cuda/UpSampleNearest2d.cu
> +      std::min<int>(64, std::min<int>(nc, max_threads / block_x / block_y));
Can you please query maxThreadDims?  
https://docs.nvidia.com/cuda/cuda-runtime-api/structcudaDeviceProp.html#structcudaDeviceProp_192d195493a9d36b2d827aaf3ffd89f1e

2019-07-09 06:27 UTC, soumith requested changes
waiting for a test case

2019-07-09 17:24 UTC, jjsjann123 commented
Test case added to test_cuda.py.
Verified test failure without the fix.

2019-07-09 17:49 UTC, jjsjann123 commented
FYI, We should close #22526 after merging this one.

2019-07-09 22:53 UTC, ngimel approved these changes
There's still lint.

2019-07-09 23:32 UTC, jjsjann123 commented
Lint complains about something in the generated file: 
```$ flake8
./test/test_quantization.py:4:1: F401 'torch.quantization as tq' imported but unused
The command "flake8" exited with 1.```

Maybe it's caused by the added test in common_nn.py? I don't see anything wrong there tho and lint doesn't give enough hint :/

2019-07-09 23:45 UTC, ngimel commented
Yeah, it's probably unrelated then.

2019-07-10 16:17 UTC, ngimel commented
@pytorchbot rebase this please

2019-07-10 17:01 UTC, jjsjann123 commented
OK, flake8 seems to be very specific about one line that is >120, while it's OK with other lines in the same manner in that function. There seems to be something funky there.

I can change that line just to bypass the pylinter. But I don't think it's relevant to this PR and probably would conflict with other PRs doing the same thing. Maybe we should just ignore it here?

2019-07-10 18:21 UTC, ngimel commented
linter is broken by recently merged #21860, it has a few lines that are longer than 120 characters.

2019-07-11 16:31 UTC, ngimel commented
@pytorchbot merge this please

2019-07-11 16:31 UTC, ngimel commented
lint should now be fixed, all other tests are green.

2019-07-11 19:05 UTC, closed without merging