Move addcmul to Aten
pytorch/pytorch pull request #22874
Opened 2019-07-15 19:41 UTC by VitalyFedyunin

Implementing #22797 
(version w/o Vec256 to test benchmarking tools)

2019-07-15 22:31 UTC, xuhdev commented on aten/src/ATen/native/cpu/PointwiseOpsKernel.cpp
> +    at::native::cpu_kernel(
nit: no need to write at::native::

2019-07-15 22:33 UTC, xuhdev commented on aten/src/ATen/native/PointwiseOps.cpp
> +#include <ATen/native/PointwiseOps.h>
Can we add a comment here? Something like:

> Ternary and higher-order pointwise operations.

2019-07-18 17:49 UTC, xuhdev commented on aten/src/ATen/native/PointwiseOps.cpp
> +  checkBackend("bitwise_not", result, self.type().backend());
"bitwise_not" --> "addcmul"?

2019-07-19 14:46 UTC, ifedan approved these changes

2019-07-19 14:47 UTC, ifedan requested changes
Do you have tests?

2019-07-22 19:50 UTC, VitalyFedyunin commented
@pytorchbot retest this please

2019-07-22 19:51 UTC, VitalyFedyunin commented
> Do you have tests?

Already tested by common_methods_invocations.py

2019-07-25 17:27 UTC, gchanan approved these changes
I'm curious -- wouldn't it only be a few more lines to move the CUDA implementation as well?

2019-07-30 18:53 UTC, VitalyFedyunin commented
> I'm curious -- wouldn't it only be a few more lines to move the CUDA implementation as well?

Only to show how to separate migration, and have this PR as example of it.

2019-08-01 19:43 UTC, closed without merging