added opset10 ORT tests
pytorch/pytorch pull request #22993
Opened 2019-07-17 21:23 UTC by neginraoof

2019-07-17 23:05 UTC, lara-hdr commented on test/onnx/test_pytorch_onnx_onnxruntime.py
> +RNN_BATCH_SIZE = 7
add and import these variables from test_pytorch_common to avoid duplicating them with the ones in the caffe2 file

2019-07-17 23:08 UTC, lara-hdr commented on test/onnx/test_pytorch_onnx_onnxruntime.py
> -    def test_adaptive_max_pool(self):
why did we remove this test?

2019-07-17 23:09 UTC, lara-hdr commented on test/onnx/test_pytorch_onnx_onnxruntime.py
> -    def test_adaptive_max_pool(self):
nvm I just noticed it was renamed

2019-07-18 16:52 UTC, jeffreyksmithjr commented
I get the gist of this PR, but I think it would be helpful to write even a single sentence stating what this PR is all about.

2019-07-22 21:51 UTC, houseroad requested changes
Please make sure all tests passing. Right now, py2 tests are failing.

2019-07-27 07:44 UTC, neginraoof commented
@houseroad related tests are fixed

2019-07-28 01:20 UTC, neginraoof commented
@pytorchbot retest this please

2019-07-29 20:37 UTC, neginraoof commented
@houseroad Please review. Tests passed.

2019-07-29 21:34 UTC, bddppq approved these changes
LGTM

2019-07-29 21:34 UTC, bddppq commented on test/onnx/test_pytorch_onnx_onnxruntime.py
> +    assert test_count == 144, test_count
better to check and raise here, some linters complain that `assert` can be disabled.

2019-07-29 22:06 UTC, neginraoof commented
@bddppq please review

2019-07-31 03:22 UTC, neginraoof commented
@bddppq This PR is updated. Please merge

2019-08-02 17:20 UTC, neginraoof commented
@bddppq Please review the updates

2019-08-02 20:40 UTC, bddppq commented
@pytorchbot rebase this please

2019-08-03 00:37 UTC, closed without merging