Allow uppercase letters in einsum equation string
pytorch/pytorch pull request #23277
Opened 2019-07-23 23:34 UTC by emprice

Following up on [previous pull request](https://github.com/pytorch/pytorch/pull/23214), here is a much simpler implementation that allows uppercase letters, increasing the number of tensor indices allowed to 52. Please let me know how to improve it further!

2019-07-24 15:06 UTC, ezyang requested changes
Just needs some tests, and it's good to go!

2019-07-24 15:07 UTC, ezyang commented on aten/src/ATen/native/Linear.cpp
> +        TORCH_CHECK(('A' <= c) && (c <= 'z'), "only letters [A-Z,a-z] allowed as indices");
Oh, it's not sound to treat A-Z and a-z as one contiguous range; there is some punctuation in the middle which you need to reject.

2021-03-30 20:35 UTC, jcmgray commented
Any progress on this? This would be a very useful upgrade! Might it just a matter tweaking that line to:
```
(('a' <= c) && (c <= 'z')) || (('A' <= c) && (c <= 'Z'))
```
?

2021-03-31 02:52 UTC, ezyang commented
Fell off everyone's radar. I redid the patch on the new implementation of einsum and put it up at https://github.com/pytorch/pytorch/pull/55013

2021-03-31 02:52 UTC, closed without merging