[pytorch][doc] Threading and CPU Inference note
pytorch/pytorch pull request #23417
Opened 2019-07-26 03:36 UTC by ilia-cher

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Summary:
A note on thread settings for inference.

Test Plan:
cd docs; make html

2019-07-26 04:45 UTC, ilia-cher commented
[html.zip](https://github.com/pytorch/pytorch/files/3434201/html.zip)

2019-07-26 11:44 UTC, soumith commented on docs/source/notes/inference_threading.rst
> +.. _inference-threading:
the heading should be cpu inference as well, if it shows up in the side bar

2019-07-26 20:31 UTC, ilia-cher commented
Would appreciate comments on wording too
[html.zip](https://github.com/pytorch/pytorch/files/3437324/html.zip)

2019-07-26 23:00 UTC, soumith requested changes

2019-07-26 23:00 UTC, soumith commented on docs/source/notes/threading_cpu_inference.rst
> +
Add a pragraph stating why you would want to use multiple libraries and what trade-offs they might have -- or why the user should be interested in these build options / build settings.

2019-07-27 03:11 UTC, ilia-cher commented on docs/source/notes/threading_cpu_inference.rst
> +primitive to launch some of the ops in parallel, as an asynchronous task, and
sounds good, the only minor change - I wanted to avoid explicit 'you' here

2019-07-27 03:11 UTC, ilia-cher commented on docs/source/notes/threading_cpu_inference.rst
> +PyTorch uses a single thread pool for the inter-op parallelism, this thread pool
minor correction: the tasks don't have to be forked at the same time, the thread pool is going to be the same in any case

2019-07-27 06:15 UTC, ilia-cher commented
Partial rewrite based on @soumith comments
[html_doc.zip](https://github.com/pytorch/pytorch/files/3437903/html_doc.zip)

2019-07-27 14:20 UTC, soumith approved these changes

2019-07-28 18:22 UTC, apaszke commented on docs/source/notes/cpu_threading_torchscript_inference.rst
> +.. image:: cpu_threading_torchscript_inference.png
Can we make this a vector graphic? 78kB tucked to the repo history forever is not a idea 😕

2019-07-29 20:32 UTC, jspisak commented
@brianjo - does this PR need to be in a different repo?

2019-07-29 20:41 UTC, brianjo commented
> @brianjo - does this PR need to be in a different repo?

Should be good once the branch gets merged.

2019-07-29 21:41 UTC, ilia-cher commented
Using SVG, minor edits.

2019-07-29 21:53 UTC, ilia-cher commented
[html_doc.zip](https://github.com/pytorch/pytorch/files/3444379/html_doc.zip)

2019-07-29 22:48 UTC, closed without merging