Increasing precision for avg pool
pytorch/pytorch pull request #23906
Opened 2019-08-06 22:12 UTC by zafartahirov

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

The 1-off error is expected for the average pool due to double rounding.
Increasing unittest precision tolerance to 1.0 to avoid failing.

2019-08-06 23:13 UTC, jerryzh168 approved these changes

2019-08-06 23:14 UTC, jerryzh168 requested changes
actually this should be for `int_repr` only right? could you check these separately? I think we still want to make sure q_scale(), q_zero_point() and q_scheme() match with default precision

2019-08-06 23:29 UTC, zafartahirov commented
> actually this should be for `int_repr` only right? could you check these separately? I think we still want to make sure q_scale(), q_zero_point() and q_scheme() match with default precision

I agree --will check

2019-08-14 02:22 UTC, jerryzh168 approved these changes

2019-08-16 20:07 UTC, closed without merging