Enabled torch.mm and torch.mv for bfloat16
pytorch/pytorch pull request #24224
Opened 2019-08-13 03:11 UTC by izdeby

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2019-08-13 19:47 UTC, VitalyFedyunin reviewed
Will merge conflict with #23492 ( cc @pbelevich )

2019-08-13 19:47 UTC, VitalyFedyunin commented on test/test_torch.py
> +            self.assertEqual(res1, res2, _prec)
Usually underscore notation means unused variable, so you might want to rename it to `prec`.

2019-08-13 21:43 UTC, ezyang requested changes
yeah, don't use `_prec` please

2019-08-15 17:21 UTC, gchanan approved these changes

2019-08-15 17:21 UTC, gchanan commented on test/test_torch.py
> +            'torch.BFloat16Tensor': 0.4,
use the same format please.

2019-08-15 17:21 UTC, gchanan commented on test/test_torch.py
> +            'torch.BFloat16Tensor': 0.3,
use the  same format please.

2019-08-16 22:46 UTC, closed without merging