Improve Windows Compatibility(for lib/TH)
pytorch/pytorch pull request #2439
Opened 2017-08-16 02:50 UTC by peterjc123

Win64 support for lib/TH

2017-08-16 18:46 UTC, fmassa requested changes
Thanks for the PR!
I did a first pass on it, and had a look on the output of the contribuild. TH compiles, but the compiler outputs some warnings that might be good to fix before merging this PR.
Also, I didn't check the implementation inside `THAllocator.c`.

2017-08-16 18:46 UTC, fmassa commented on torch/lib/TH/THAtomic.c
> +  //assert(sizeof(int32_t) == sizeof(long));
we can probably remove this comment

2017-08-16 18:46 UTC, fmassa commented on torch/lib/TH/THAtomic.c
> +  //assert(sizeof(int32_t) == sizeof(long));
this one as well

2017-08-16 18:46 UTC, fmassa commented on torch/lib/TH/THFile.c
> +IMPLEMENT_THFILE_STORAGE(Long, int32_t)
`int64_t`

2017-08-16 18:46 UTC, fmassa commented on torch/lib/TH/generic/THBlas.h
> +TH_API void THBlas_(swap)(int64_t  n, real *x, int64_t  incx, real *y, int64_t  incy);
nit: there are two spaces after `int64_t` everywhere in this file

2017-08-16 18:46 UTC, fmassa commented on torch/lib/TH/generic/THTensor.c
> +    n += snprintf(str+n, L-n, "%lld", tensor->size[i]);
nit: is this the right format? I'm looking at https://stackoverflow.com/questions/9225567/how-to-print-a-int64-t-type-in-c and I'm not sure it's exactly what you are looking for. (This appears elsewhere in the codebase as well). Also, there are warning in the CI due to those changes, with warnings like
```
warning: format ‘%lld’ expects argument of type ‘long long int *’, but argument 3 has type ‘int64_t * {aka long int *}’ [-Wformat=]
```

2017-08-16 18:46 UTC, fmassa commented on torch/lib/TH/generic/THTensorRandom.c
> +      _mask = (int) THRandom_bernoulli(_generator, _q);
`_mask` is a `int64_t`, so no need for the casting I think

2017-08-16 18:46 UTC, fmassa commented on torch/lib/TH/THDiskFile.c
>          if(pos == 0)
There are warnings in the contribuild down in this file, maybe you miss some castings? Example of warning
```
/home/travis/build/pytorch/pytorch/torch/lib/TH/THDiskFile.c: In function ‘THDiskFile_new’:
/home/travis/build/pytorch/pytorch/torch/lib/TH/THDiskFile.c:618:5: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
     THDiskFile_readChar,
     ^
```

2017-08-17 07:07 UTC, peterjc123 commented
There 're no warnings now.

2017-08-17 15:45 UTC, fmassa commented
Thanks for the changes!
TH seems now to compile without any warnings.
The build fails because of the dependency of THPP in TH, so we should probably only merge these PRs together.
@apaszke any better ideas on how we can run the tests with all the changes? The monolithic PR was too hard to review, the separate PRs are easier but running the full test suite is trickier.

2017-08-17 16:49 UTC, peterjc123 commented
@fmassa I tried to make CI builds with windows-full branch. Every time a change is made, it will be merged into this branch. Maybe it's useful.
For Linux/Mac    [![Build Status](https://travis-ci.org/peterjc123/pytorch.svg?branch=windows-full)](https://travis-ci.org/peterjc123/pytorch)
For Windows    [![Build status](https://ci.appveyor.com/api/projects/status/8xiih9d2w4pwnq4k?svg=true)](https://ci.appveyor.com/project/peterjc123/pytorch)

2017-08-18 17:39 UTC, fmassa approved these changes
Thanks a lot for your effort!
I think this is ready for merge. TH builds without warnings.
Let's wait until the other folders are reviewed so that we can merge them all.

2017-08-18 17:39 UTC, fmassa commented on torch/lib/TH/generic/THTensorRandom.c
> +  TH_TENSOR_APPLY(real, self, *self_data = (int64_t)THRandom_random(_generator););
We don't need the modulo here I suppose?

2017-09-17 03:40 UTC, merged

2017-09-17 03:41 UTC, soumith commented
Thanks a ton @peterjc123 for doing this big PR. This is really good stuff.