Improve Windows Compatibility(lib/THC)
pytorch/pytorch pull request #2440
Opened 2017-08-16 02:51 UTC by peterjc123

Win64 support for lib/THC

2017-08-16 14:30 UTC, alykhantejani commented on torch/lib/THC/THCAtomics.cuh
> +      old = atomicCAS((uint64_t *) address_as_ui, (uint64_t) assumed, (uint64_t) newval);
nit:`address_as_ui` and `assumed` should already by `uint64_t` i.e. is the cast necessary?

2017-08-16 14:30 UTC, alykhantejani commented on torch/lib/THC/THCReduceApplyUtils.cu
> +  int dims = THCudaTensor_nDimension(state, tensor);
shouldn't this be `int64_t`?

2017-08-16 14:30 UTC, alykhantejani commented on torch/lib/THC/THCTensorRandom.cuh
> +    output[idx] = J[rand_ind]*(1 -_mask) + (rand_ind+1LL) * _mask;
Why was `1L` changed to a `long long`?

2017-08-16 14:30 UTC, alykhantejani commented on torch/lib/THC/THCTensorSort.cu
> +  int dims = THCudaLongTensor_nDimension(state, t);
`int` -> `int64_t`?

2017-08-16 14:30 UTC, alykhantejani commented on torch/lib/THC/THCTensorSort.cu
> +    TensorInfo<int64_t, unsigned int> info =
nit: can also change `unsigned int` to `uint32_t` to be more consistent with this change in other places

2017-08-16 14:30 UTC, alykhantejani commented on torch/lib/THC/generic/THCTensorIndex.cu
> +  int dims = (int) THCTensor_(nDimension)(state, dst);
I don't think the cast is necessary

2017-08-16 14:30 UTC, alykhantejani commented on torch/lib/THC/generic/THCTensorIndex.cu
> +  int srcDims = (int) THCTensor_(nDimension)(state, src);
I don't think the cast is necessary

2017-08-16 14:30 UTC, alykhantejani commented on torch/lib/THC/generic/THCTensorIndex.cu
> +  int dims = (int) THCTensor_(nDimension)(state, dst);
I don't think the cast is necessary

2017-08-16 14:30 UTC, alykhantejani commented on torch/lib/THC/generic/THCTensorIndex.cu
> +  int srcDims = (int) THCTensor_(nDimension)(state, src);
I don't think the cast is necessary

2017-08-16 14:30 UTC, alykhantejani commented on torch/lib/THC/generic/THCTensorMathPointwise.cu
> +  int nd = (int) THCTensor_(nDimension)(state, x);
I don't think the cast is necessary

2017-08-16 14:34 UTC, alykhantejani commented
Just a general comment: `long long` and `unsigned long long` have  been changed to `int64_t` and `uint64_t` respectively. Do we not want to use `int_least64_t` and `uint_least64_t`?

2017-08-18 17:53 UTC, fmassa commented
@alykhantejani I think that it's fine to leave them as `int64_t` and `uint64_t`, as that maintains the default behavior of what we had before I believe

2017-08-18 18:28 UTC, fmassa requested changes
This looks very good, thanks!
There is a memory leak in one of the files that needs to be addressed. The other comments are mostly minor.

2017-08-18 18:28 UTC, fmassa commented on torch/lib/THC/THCNumerics.cuh
> +  static inline __host__ __device__ int64_t min() { return LONG_MIN; }
Do you want to keep `LONG_MIN` or use another macro (something like `INT64_MIN`)?

2017-08-18 18:28 UTC, fmassa commented on torch/lib/THC/THCNumerics.cuh
> +  static inline __host__ __device__ int64_t max() { return LONG_MAX; }
Same here, and on the lines above, for the sake of consistency.

2017-08-18 18:28 UTC, fmassa commented on torch/lib/THC/THCTensorTypeUtils.cu
> +  /* We order the size/stride arrays by stride, skipping dimensions */  \
Thanks for fixing the indentation! 👍

2017-08-18 18:28 UTC, fmassa commented on torch/lib/THC/generic/THCTensor.c
> +  int64_t **op_sizes = (int64_t **)malloc(count * sizeof(int64_t *));
If you do a `malloc` you need to free it afterwards.
We have functions for the `malloc`/`free` that you could use (`THAlloc` and `THFree`).

2017-08-18 18:28 UTC, fmassa commented on torch/lib/THC/generic/THCTensor.c
> +  int64_t *op_dims = (int64_t *)malloc(count * sizeof(int64_t));
Same here. Can't we have those arrays allocated as is in MSVC?

2017-08-18 18:28 UTC, fmassa commented on torch/lib/THC/generic/THCTensor.c
> +    n += snprintf(str+n, L-n, "%lld", tensor->size[i]);
Can you use the same macro that you used in `TH` for the print of `int64_t`?

2017-08-18 18:28 UTC, fmassa commented on torch/lib/THC/generic/THCTensorIndex.cu
> +  int64_t dims = THCTensor_(nDimension)(state, dst);
I think you want to make this `int`?

2017-08-18 18:28 UTC, fmassa commented on torch/lib/THC/generic/THCTensorIndex.cu
> +  int64_t srcDims = THCTensor_(nDimension)(state, src);
`int` here as well? Or let's just cast to `int64_t`?

2017-08-18 18:28 UTC, fmassa commented on torch/lib/THC/generic/THCTensorIndex.cu
> +  int64_t dims = THCTensor_(nDimension)(state, dst);
same here, `int` or cast to `int64_t`?

2017-08-18 18:28 UTC, fmassa commented on torch/lib/THC/generic/THCTensorIndex.cu
> +  int ndim = (int) THCTensor_(nDimension)(state, indexed);
Do you need this cast?

2017-08-18 18:28 UTC, fmassa commented on torch/lib/THC/generic/THCTensorMathReduce.cu
> +THCTensor_(sum)(THCState* state, THCTensor *self, THCTensor *src, int dimension, int keepdim) {
While I agree with this change, I'm commenting this here just to raise awareness to others of this change (the same repeats all over this file).

2017-08-18 18:28 UTC, fmassa commented on torch/lib/THC/generic/THCTensorMathReduce.cu
> +  int t_size_dim, k;
Shouldn't this be `int64_t`? In line 377 you use it in `THCTensor_(size)`, which returns `int64_t`, right?

2017-08-18 18:28 UTC, fmassa commented on torch/lib/THC/generic/THCTensorMathScan.cu
> +void THCTensor_(cumsum)(THCState *state, THCTensor *self, THCTensor *src, int dimension)
Same nit comment here about changing the types.

2017-08-18 18:28 UTC, fmassa commented on torch/lib/THC/generic/THCTensorScatterGather.cu
> +  for (int d = 0; d < (int) THCTensor_(nDimension)(state, tensor); d++) {
Do we need this cast?

2017-08-19 10:34 UTC, peterjc123 commented on torch/lib/THC/generic/THCTensor.c
> +  int64_t *op_dims = (int64_t *)malloc(count * sizeof(int64_t));
No, dynamic array is not supported in MSVC 2015.

2017-08-19 10:50 UTC, peterjc123 commented on torch/lib/THC/THCNumerics.cuh
> +  static inline __host__ __device__ int64_t min() { return LONG_MIN; }
It may be kept at this timee because the whole project has dependency upon it.

2017-08-19 11:07 UTC, alykhantejani commented
@fmassa I think `int64_t` and `uint64_t` have the same behaviour as `long long` and `unsigned long long` on 64-bit machines, but `long long` means at least 64 bits. I'm not why these types were defined `long long` instead of just `long` in the first version, but if we want to preserve that behaviour I think `int_least_64t` is the correct way (however I could be wrong here)?

2017-08-19 13:03 UTC, pavanky commented
> I'm not why these types were defined `long long` instead of just `long` in the first version

@alykhantejani what do you mean the first version ? Doesn't the current version of pytorch use `long` instead of `long long` ?

2017-08-19 13:24 UTC, alykhantejani commented
@pavanky no in some places `long long` and `unsigned long long` have been used, and in this PR they have been changed to `int64_t` and `uint64_t` instead of `int_least_64t` and `uint_least_64t`

2017-08-19 13:33 UTC, pavanky commented
@alykhantejani That should be fine because there aren't many implementations that have `long long` be more than 64 bits. AFAIK this is true for all of the platforms that pytorch supports.

Besides the bigger problem is changing `long` to `int64_t` as this changes a 32 bit integer type to 64 bit integer type on windows.

2017-08-23 10:09 UTC, fmassa commented
I think changing `long` to `int64_t` should be fine. Torch/PyTorch was never officially supported on windows, and I think that it's best to have size-fixed types in the library.

2017-08-23 10:11 UTC, fmassa commented on torch/lib/THC/THCNumerics.cuh
> +  static inline __host__ __device__ int64_t min() { return LONG_MIN; }
Could you clarify this point? Won't this give incorrect results on windows platforms then?

2017-08-23 10:13 UTC, peterjc123 commented on torch/lib/THC/THCNumerics.cuh
> +  static inline __host__ __device__ int64_t min() { return LONG_MIN; }
No problem for building and using now.

2017-08-23 10:28 UTC, fmassa commented on torch/lib/THC/THCNumerics.cuh
> +  static inline __host__ __device__ int64_t min() { return LONG_MIN; }
I think the only occurrences of `THCNumerics<type>::min()` and `THCNumerics<type>::max()` are [here](https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/generic/THCTensorMathReduce.cu#L327) and [here](https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/generic/THCTensorMathReduce.cu#L311), so maybe use-cases where we might have problems is when a `LongTensor` has a value greater than `2^32` inside and we call `torch.min(tensor)`?

2017-08-23 10:29 UTC, fmassa commented on torch/lib/THC/THCNumerics.cuh
> +  static inline __host__ __device__ int64_t min() { return LONG_MIN; }
But this might be a very rare corner case. I'm unsure if it's actually a problem though, I'll let the others comment on that.

2017-08-23 10:39 UTC, peterjc123 commented on torch/lib/THC/THCNumerics.cuh
> +  static inline __host__ __device__ int64_t min() { return LONG_MIN; }
https://msdn.microsoft.com/en-us/library/296az74e.aspx I just searched for the document is MSDN and that says the _I64_MIN and _I64_MAX should be used in MSVC.

2017-09-11 16:29 UTC, fmassa approved these changes
I think this looks good, thanks a lot for all your work!
There were some type changes from `long` to `int` in some function arguments (like `std`, `sum`, `mean`, etc), but I agree with them.

2017-09-17 03:50 UTC, merged

2017-09-17 03:50 UTC, soumith commented
thank you. i'm 3 down, a few more merges to go. :D