Improve Windows Compatibility(lib/THCUNN)
pytorch/pytorch pull request #2443
Opened 2017-08-16 02:53 UTC by peterjc123

Win64 support for lib/THCUNN

2017-08-18 18:41 UTC, fmassa requested changes
Thanks for the PR!
There are some things that I didn't understand. Did you start off from a different branch than master? There were a number of changes in `SpatialFullConvolution` that are not meant to be in this PR. Same with the change in function signature in `col2im`. Could you look into that?

2017-08-18 18:41 UTC, fmassa commented on torch/lib/THCUNN/CMakeLists.txt
> +#  SET_TARGET_PROPERTIES(THCUNN PROPERTIES PREFIX "lib" IMPORT_PREFIX "lib")
Remove the comment?

2017-08-18 18:41 UTC, fmassa commented on torch/lib/THCUNN/generic/SpatialConvolutionLocal.cu
> +      nInputPlane, inputHeight, inputWidth, outputHeight, outputWidth, kH, kW, padH, padW, dH, dW,
Was that a bug in the code?

2017-08-18 18:41 UTC, fmassa commented on torch/lib/THCUNN/generic/SpatialConvolutionMM.cu
> +      nInputPlane, inputHeight, inputWidth, outputHeight, outputWidth, kH, kW, padH, padW, dH, dW,
Same comment here, why was this missing?

2017-08-18 18:41 UTC, fmassa commented on torch/lib/THCUNN/generic/SpatialDepthWiseConvolution.cu
> +        1, inputHeight, inputWidth, outputHeight, outputWidth, kH, kW, padH, padW, dH, dW,
Same here

2017-08-18 18:41 UTC, fmassa commented on torch/lib/THCUNN/generic/SpatialDilatedConvolution.cu
> +      nInputPlane, inputHeight, inputWidth, outputHeight, outputWidth, kH, kW, padH, padW, dH, dW,
Same here. Did you change the api of `col2im`?

2017-08-18 18:41 UTC, fmassa commented on torch/lib/THCUNN/generic/SpatialFractionalMaxPooling.cu
> +  int64_t numInputDims = THCTensor_(nDimension)(state, input);
While I'm ok with that, does `THCTensor_(nDimension)` returns an `int`?

2017-08-18 18:41 UTC, fmassa commented on torch/lib/THCUNN/generic/SpatialFullConvolution.cu
> -static inline void THNN_(SpatialFullConvolution_shapeCheck)(
Was this PR made on top of a different branch than master?

2017-08-19 07:57 UTC, TestItOnlyOnce commented on torch/lib/THCUNN/generic/SpatialFullConvolution.cu
> -static inline void THNN_(SpatialFullConvolution_shapeCheck)(
I am extremely sorry. The blame is on me for this one. The merge was done with older branch and I just copied some cu files over as I got tired and other files being different in just types.

2017-08-21 16:53 UTC, fmassa approved these changes
This now looks good to me, thanks!
I'm just curious though why the THCUNN build was not launched here, maybe I'm looking at the wrong place?
Once again, let's wait until the other PRs are reviewed so we merge them all together.

2017-08-21 17:13 UTC, peterjc123 commented
The build is failing because there're C wrappers for THCUNN. It checks types for it and finds out that int64_t is not one of the type supported. The C wrappers that supported int64_t is in another pull. That's the reason, I think.

2017-09-17 03:58 UTC, merged

2017-09-17 03:58 UTC, soumith commented
thanks @peterjc123 !!!