Improve Windows Compatibility(lib/THNN)
pytorch/pytorch pull request #2446
Opened 2017-08-16 02:55 UTC by peterjc123

Win64 support for lib/THNN

2017-08-16 20:17 UTC, fmassa requested changes
Thanks a lot for the PR!
This looks good for the most part. I have some comments.
I think the best before merging this in would be to first have TH merged in master, and then we run the contribuild again for THNN (but merging TH might break other things, to see).

2017-08-17 15:47 UTC, fmassa commented on torch/lib/THNN/generic/TemporalRowConvolution.c
> +			ix = (size_t)(kw);
I think you missed this casting here

2017-08-18 17:51 UTC, fmassa approved these changes
I added some minor comments that don't need to be addressed.
THNN builds without warnings in Unix.
I think this is ready for merge! But let's hold until the other PRs are reviewed so that we can merge them all at once.

Thanks a lot!

2017-08-18 17:51 UTC, fmassa commented on torch/lib/THNN/generic/THNN.h
> +          int64_t ignore_index);          // target index to ignore (loss = 0, gradInput = 0)
nit: the comment is not aligned anymore with the other comments. Not important, but mentioning anyway

2017-08-18 17:51 UTC, fmassa commented on torch/lib/THNN/generic/THNN.h
> +          int64_t ignore_index);          // target index to ignore (loss = 0, gradInput = 0)
same here

2017-08-18 17:51 UTC, fmassa commented on torch/lib/THNN/generic/THNN.h
> +          int64_t ignore_index);          // target index to ignore (loss = 0, gradInput = 0)
and here

2017-08-18 17:51 UTC, fmassa commented on torch/lib/THNN/generic/THNN.h
> +          int64_t ignore_index);          // target index to ignore (loss = 0, gradInput = 0)
and here.

2017-09-17 03:55 UTC, merged

2017-09-17 03:55 UTC, soumith commented
4 down. thank you @peterjc123 !!!!