[pt1][quant] Clang-formatting the Quantized Linear/LSTM files
pytorch/pytorch pull request #24986
Opened 2019-08-21 20:44 UTC by jianyuh

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

The code is formatted by `clang-format -i *.h *.cpp`.

Differential Revision: [D16946350](https://our.internmc.facebook.com/intern/diff/D16946350/)

2019-08-22 18:33 UTC, dskhudia approved these changes

2019-08-22 18:33 UTC, z-a-f approved these changes
LGTM

2019-08-22 21:39 UTC, jamesr66a requested changes

2019-08-22 21:39 UTC, jamesr66a commented on aten/src/ATen/native/RNN.cpp
> +//         member_ref=member_ref(i//2)))
This is wrong

2019-08-22 21:41 UTC, jamesr66a commented
I'm also not a fan of wholesale formatting diffs on entire files, since is screws up blame information. Can you just clang-format the lines you touch?

2019-08-23 02:42 UTC, jianyuh commented on aten/src/ATen/native/RNN.cpp
> +//         member_ref=member_ref(i//2)))
Will modify.

2019-08-23 02:42 UTC, jianyuh commented
> I'm also not a fan of wholesale formatting diffs on entire files, since is screws up blame information. Can you just clang-format the lines you touch? You can easily do this automatically with the pre-commit hook https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#pre-commit-tidylinting-hook

Agreed. I will only format the code I touch.

2022-05-12 03:06 UTC, closed without merging