Manually implement `is_zipfile`
pytorch/pytorch pull request #25279
Opened 2019-08-27 23:25 UTC by driazati

The default implementation is lenient in that it recognizes a zipfile if the magic number appears anywhere in the archive. So if someone has the bytes `PK\x03\x04` in a tensor, it gets recognized as a zipfile. See https://bugs.python.org/issue28494
    
This implementation only checks the first 4 bytes of the file for the zip magic number. We could also copy https://github.com/python/cpython/pull/5053's fix, but that seems like overkill.
    
Fixes #25214

Differential Revision: [D17102516](https://our.internmc.facebook.com/intern/diff/17102516/)

2019-08-28 01:16 UTC, zou3519 requested changes
Needs test unless it's hard to repro the bug. However, it sounds like one just needs to serialize a tensor with the magic numbers?

2019-08-28 13:08 UTC, ezyang requested changes
As Richard said, needs test. Lint failures are real too. Also, shouldn't we be using `b''` strings?

2019-08-28 22:04 UTC, driazati commented
`b''` doesn't do anything in Python 2, `ord()` takes care of turning things into bytes

2019-08-29 19:53 UTC, ezyang commented on torch/serialization.py
> +    # This is a stricter implmentation than zipfile.is_zipfile().
nit: implementation

2019-08-29 19:53 UTC, ezyang approved these changes

2019-08-29 20:42 UTC, zou3519 approved these changes

2019-08-30 23:48 UTC, closed without merging