Fix invalid function cast warnings that show up with GCC 8/9
pytorch/pytorch pull request #25483
Opened 2019-08-30 18:53 UTC by rgommers

Fixes ~5000 lines of warnings like:

```
In file included from ../aten/src/TH/TH.h:4,
                 from ../torch/csrc/Storage.cpp:11:
../torch/csrc/Storage.h:6:39: warning: cast between incompatible function types from ‘PyObject* (*)(THPStorage*)’ {aka ‘_object* (*)(THPStorage*)’} to ‘getter’ {aka ‘_object* (*)(_object*, void*)’} [-Wcast-function-type]
    6 | #define THPStorage_(NAME) TH_CONCAT_4(THP,Real,Storage_,NAME)
      |                                       ^~~
caffe2/aten/src/TH/THGeneral.h:154:37: note: in definition of macro ‘TH_CONCAT_4_EXPAND’
  154 | #define TH_CONCAT_4_EXPAND(x,y,z,w) x ## y ## z ## w
      |                                     ^
../torch/csrc/Storage.h:6:27: note: in expansion of macro ‘TH_CONCAT_4’
    6 | #define THPStorage_(NAME) TH_CONCAT_4(THP,Real,Storage_,NAME)
      |                           ^~~~~~~~~~~
../torch/csrc/generic/Storage.cpp:299:22: note: in expansion of macro ‘THPStorage_’
  299 |   {"device", (getter)THPStorage_(device), nullptr, nullptr, nullptr},
      |                      ^~~~~~~~~~~
../torch/csrc/Storage.h:6:39: warning: cast between incompatible function types from ‘PyObject* (*)(THPStorage*)’ {aka ‘_object* (*)(THPStorage*)’} to ‘getter’ {aka ‘_object* (*)(_object*, void*)’} [-Wcast-function-type]
    6 | #define THPStorage_(NAME) TH_CONCAT_4(THP,Real,Storage_,NAME)
      |                                       ^~~
caffe2/aten/src/TH/THGeneral.h:154:37: note: in definition of macro ‘TH_CONCAT_4_EXPAND’
  154 | #define TH_CONCAT_4_EXPAND(x,y,z,w) x ## y ## z ## w
      |                                     ^
../torch/csrc/Storage.h:6:27: note: in expansion of macro ‘TH_CONCAT_4’
    6 | #define THPStorage_(NAME) TH_CONCAT_4(THP,Real,Storage_,NAME)
      |                           ^~~~~~~~~~~
```

This issue and the fix is very similar to how CPython fixed it, see https://bugs.python.org/issue33012.

There's still more of these warnings left, but this fixes the majority of them.

2019-08-30 19:49 UTC, ezyang approved these changes

2019-08-30 19:49 UTC, ezyang requested changes
Hmm, clang-tidy seems to hate it:

```
/home/vsts/work/1/s/torch/csrc/generic/StorageMethods.cpp:7:19: error: cannot initialize a variable of type 'PyObject *' (aka '_object *') with an lvalue of type 'int64_t (const at::Tensor &, int64_t)' (aka 'long (const at::Tensor &, long)') [clang-diagnostic-error]
static PyObject * THPStorage_(size)(THPStorage *self, PyObject *noargs)
```

2019-08-30 23:10 UTC, rgommers commented
Hmm, not sure how to interpret that. Running `clang-tidy` over the whole code base given O(1000) errors and O(1e6) warnings. 

I'll see if I can reproduce this locally and make `clang-tidy` happy. CPython introduced `Py_UNUSED` specifically for this purpose, so you can write `PyObject *Py_UNUSED(ignored)` instead of `PyObject *noargs`.
`Py_UNUSED` special-cases GCC and LLVM: https://github.com/python/cpython/blob/master/Include/pymacro.h#L92. It's only available from Python 3.4 though, so it'd need to be vendored somewhere.

2019-08-31 22:03 UTC, ezyang commented
Err, is that with the `.clang-tidy` config? I think we do have some areas of master which are not clang-tidy clean, but not to the degree you describe. `tools/clang_tidy.py` is used to operate with this config.

2019-08-31 22:04 UTC, ezyang commented
It is possible that it's not worth fixing this clang tidy warning, in which case we would need to agree that this was the case and then disable this warning.

2019-09-01 02:17 UTC, rgommers commented
> Err, is that with the `.clang-tidy` config? I think we do have some areas of master which are not clang-tidy clean, but not to the degree you describe. `tools/clang_tidy.py` is used to operate with this config.

Note that in CI `clang-tidy` is only run on `torch/csrc`, and even there it still excludes 3 files:
```
python tools/clang_tidy.py             \
  --verbose                                 \
  --paths torch/csrc/                       \
  --diff "$BASE_BRANCH"                     \
  -g"-torch/csrc/jit/export.cpp"            \
  -g"-torch/csrc/jit/import.cpp"            \
  -g"-torch/csrc/jit/netdef_converter.cpp"  \
  "$@"
```

When you run it on the whole codebase rather than just `torch/csrc`, there really are that many errors and warnings.

> It is possible that it's not worth fixing this clang tidy warning, in which case we would need to agree that this was the case and then disable this warning.

That would not be necessary I believe. CI is only run on the diff of a PR, so once you merge any PR there won't be subsequent failures.


More importantly, this stuff is already not accepted by `clang-tidy` in its current form:
```
$ git checkout master
$ python tools/clang_tidy.py --verbose --paths torch/csrc/ --diff "master" -g"-torch/csrc/jit/export.cpp" -g"-torch/csrc/jit/import.cpp" -g"-torch/csrc/jit/netdef_converter.cpp"
...
No files detected.

$ git checkout try-tidy  # adds a single commit with a single blank space added on the problematic line:
$ git diff try-tidy..master
diff --git a/torch/csrc/generic/StorageMethods.cpp b/torch/csrc/generic/StorageMethods.cpp
index 1f4adcc384..d268646615 100644
--- a/torch/csrc/generic/StorageMethods.cpp
+++ b/torch/csrc/generic/StorageMethods.cpp
@@ -4,7 +4,7 @@
 #include <cuda_runtime.h>
 #endif
 
-static PyObject * THPStorage_(size)(THPStorage *self) 
+static PyObject * THPStorage_(size)(THPStorage *self)
 {
   HANDLE_TH_ERRORS
   return PyLong_FromLong(THWStorage_(size)(LIBRARY_STATE self->cdata));

$ python tools/clang_tidy.py --verbose --paths torch/csrc/ --diff "master" -g"-torch/csrc/jit/export.cpp" -g"-torch/csrc/jit/import.cpp" -g"-torch/csrc/jit/netdef_converter.cpp" # ends in:

...

error: cannot initialize a variable of type 'PyObject *' (aka '_object *') with an lvalue of type 'int64_t (const at::Tensor &, int64_t)' (aka 'long (const at::Tensor &, long)') [clang-diagnostic-error]
static PyObject * THPStorage_(size)(THPStorage *self) 
                  ^
/home/rgommers/code/pytorch/torch/csrc/generic/StorageMethods.cpp:7:31: error: use of undeclared identifier 'size'; did you mean 'at::size'? [clang-diagnostic-error]
static PyObject * THPStorage_(size)(THPStorage *self) 
                              ^~~~
                              at::size
aten/src/ATen/Functions.h:5984:23: note: 'at::size' declared here
static inline int64_t size(const Tensor & self, int64_t dim) {
                      ^
/home/rgommers/code/pytorch/torch/csrc/generic/StorageMethods.cpp:7:36: error: expected ';' after top level declarator [clang-diagnostic-error]
static PyObject * THPStorage_(size)(THPStorage *self) 
                                   ^
                                   ;
/home/rgommers/code/pytorch/torch/csrc/generic/StorageMethods.cpp:172:2: error: "Unknown type" [clang-diagnostic-error]
#error "Unknown type"
```

Full output of the last command:

<details>

```
$ python tools/clang_tidy.py --verbose --paths torch/csrc/ --diff "master" -g"-torch/csrc/jit/export.cpp" -g"-torch/csrc/jit/import.cpp" -g"-torch/csrc/jit/netdef_converter.cpp"
git diff-index --diff-filter=AMU --ignore-all-space --name-only master torch/csrc
Filtering with these file patterns: Patterns(positive=[re.compile('.*\\.c(c|pp)?')], negative=[re.compile('(?s:torch\\/csrc\\/jit\\/export\\.cpp)\\Z'), re.compile('(?s:torch\\/csrc\\/jit\\/import\\.cpp)\\Z'), re.compile('(?s:torch\\/csrc\\/jit\\/netdef_converter\\.cpp)\\Z')])
git diff-index --unified=0 master torch/csrc/generic/StorageMethods.cpp
tools/clang_tidy.py:172: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  command += ["-config", json.dumps(yaml.load(config))]
clang-tidy -p build -config {"Checks": " -* ,bugprone-* ,-bugprone-forward-declaration-namespace ,-bugprone-macro-parentheses ,-bugprone-lambda-function-name ,cppcoreguidelines-* ,-cppcoreguidelines-interfaces-global-init ,-cppcoreguidelines-owning-memory ,-cppcoreguidelines-pro-bounds-array-to-pointer-decay ,-cppcoreguidelines-pro-bounds-constant-array-index ,-cppcoreguidelines-pro-bounds-pointer-arithmetic ,-cppcoreguidelines-pro-type-cstyle-cast ,-cppcoreguidelines-pro-type-reinterpret-cast ,-cppcoreguidelines-pro-type-static-cast-downcast ,-cppcoreguidelines-pro-type-union-access ,-cppcoreguidelines-pro-type-vararg ,-cppcoreguidelines-special-member-functions ,hicpp-exception-baseclass ,hicpp-avoid-goto ,modernize-* ,-modernize-return-braced-init-list ,-modernize-use-auto ,-modernize-use-default-member-init ,-modernize-use-using ,performance-* ,-performance-noexcept-move-constructor ", "WarningsAsErrors": "*", "HeaderFilterRegex": "torch/csrc/.*", "AnalyzeTemporaryDtors": false, "CheckOptions": null} -line-filter [{"name": "torch/csrc/generic/StorageMethods.cpp", "lines": [[7, 8]]}] torch/csrc/generic/StorageMethods.cpp
7102 warnings and 4 errors generated.
Error while processing /home/rgommers/code/pytorch/torch/csrc/generic/StorageMethods.cpp.
Suppressed 7102 warnings (7098 in non-user code, 4 with check filters).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
Traceback (most recent call last):
  File "tools/clang_tidy.py", line 54, in run_shell_command
    output = subprocess.check_output(arguments).decode().strip()
  File "/home/rgommers/anaconda3/envs/pytorch-gcc91/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/rgommers/anaconda3/envs/pytorch-gcc91/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['clang-tidy', '-p', 'build', '-config', '{"Checks": " -* ,bugprone-* ,-bugprone-forward-declaration-namespace ,-bugprone-macro-parentheses ,-bugprone-lambda-function-name ,cppcoreguidelines-* ,-cppcoreguidelines-interfaces-global-init ,-cppcoreguidelines-owning-memory ,-cppcoreguidelines-pro-bounds-array-to-pointer-decay ,-cppcoreguidelines-pro-bounds-constant-array-index ,-cppcoreguidelines-pro-bounds-pointer-arithmetic ,-cppcoreguidelines-pro-type-cstyle-cast ,-cppcoreguidelines-pro-type-reinterpret-cast ,-cppcoreguidelines-pro-type-static-cast-downcast ,-cppcoreguidelines-pro-type-union-access ,-cppcoreguidelines-pro-type-vararg ,-cppcoreguidelines-special-member-functions ,hicpp-exception-baseclass ,hicpp-avoid-goto ,modernize-* ,-modernize-return-braced-init-list ,-modernize-use-auto ,-modernize-use-default-member-init ,-modernize-use-using ,performance-* ,-performance-noexcept-move-constructor ", "WarningsAsErrors": "*", "HeaderFilterRegex": "torch/csrc/.*", "AnalyzeTemporaryDtors": false, "CheckOptions": null}', '-line-filter', '[{"name": "torch/csrc/generic/StorageMethods.cpp", "lines": [[7, 8]]}]', 'torch/csrc/generic/StorageMethods.cpp']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/clang_tidy.py", line 297, in <module>
    main()
  File "tools/clang_tidy.py", line 293, in main
    print(run_clang_tidy(options, line_filters, files), file=sys.stderr)
  File "tools/clang_tidy.py", line 187, in run_clang_tidy
    output = run_shell_command(command)
  File "tools/clang_tidy.py", line 58, in run_shell_command
    raise RuntimeError("Error executing {}: {}".format(" ".join(arguments), error_output))
RuntimeError: Error executing clang-tidy -p build -config {"Che [...]

2019-09-01 14:32 UTC, ezyang approved these changes

2019-09-06 18:30 UTC, li-roy commented
@pytorchbot retest this please

2019-09-09 13:35 UTC, closed without merging