The float version of calc_digamma should return float type.
pytorch/pytorch pull request #25488
Opened 2019-08-30 19:39 UTC by xuhdev

Besides common understanding, the only occurrence of calc_digamma is in UnaryOpsKernel.cpp, which clearly sees the float version of calc_digamma as returning float type.

2019-09-02 22:02 UTC, VitalyFedyunin commented
```cpp 
#define AT_DISPATCH_FLOATING_TYPES(TYPE, NAME, ...)                          \
  [&] {                                                                      \
    const auto& the_type = TYPE;                                             \
    /* don't use TYPE again in case it is an expensive or side-effect op */  \
    at::ScalarType _st = ::detail::scalar_type(the_type);                    \
    switch (_st) {                                                           \
      AT_PRIVATE_CASE_TYPE(at::ScalarType::Double, double, __VA_ARGS__)      \
      AT_PRIVATE_CASE_TYPE(at::ScalarType::Float, float, __VA_ARGS__)        \
      default:                                                               \
        AT_ERROR(#NAME, " not implemented for '", toString(_st), "'");       \
    }                                                                        \
  }()
```

Apparently UnaryOpsKernel.cpp requires both float and double

2019-09-02 22:03 UTC, VitalyFedyunin requested changes
Will lower precision for torch.double, please abandon.

2019-09-03 17:38 UTC, xuhdev commented
@VitalyFedyunin Probably my comment was confusing, actually I meant that the `calc_digamma` that accepts float should also return float. In the same file, you'll find another overload of `calc_digamma` that accepts double and returns double, so there is no loss for double.

2019-09-03 21:35 UTC, VitalyFedyunin commented
Ah, right, agree. Can you please also comment the operator code with precision loss remark.

2019-09-03 21:50 UTC, xuhdev commented
Sure. Where and what would you like me to add? I think this is already pretty self-explanatory...

2019-09-03 21:55 UTC, VitalyFedyunin commented
Just around `static void digamma_kernel(TensorIterator& iter)` so next person will quickly see that float type wasn't intentional and some work need to be done to support double precision.

2019-09-03 22:05 UTC, xuhdev commented
@VitalyFedyunin I'm very confused. `calc_digamma` has two versions, one for float and one for double. Before this PR, the float version messed up some precision, including the return type. This PR fixes that. I'm not sure what you meant by "float type wasn't intentional"...

2019-09-03 22:19 UTC, VitalyFedyunin commented
Ah, right, I totally missed second version. This PR is totally fine. But we need another one fixing double version, as internally it is using floats for math ops.

2019-09-03 22:19 UTC, VitalyFedyunin approved these changes

2019-09-06 18:12 UTC, xuhdev commented
Could you explain a bit more about the issue in the double version?

2019-09-10 23:12 UTC, xuhdev commented
@pytorchbot merge this please

2019-09-11 14:10 UTC, closed without merging