Add requests as a legit dependency
pytorch/pytorch pull request #25596
Opened 2019-09-03 18:36 UTC by jamesr66a

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2019-09-03 18:55 UTC, pietern reviewed
LGTM, but will defer approval to @ezyang or @soumith since this adds a new dep.

2019-09-03 18:55 UTC, pietern commented on requirements.txt
> +requests
Seems to be ordered alphabetically.

2019-09-03 21:05 UTC, soumith commented
but why?

2019-09-03 21:07 UTC, jamesr66a commented
@soumith because this seems like a pretty poor experience: https://github.com/pytorch/pytorch/pull/25083#issuecomment-527219928

2019-09-03 21:12 UTC, ezyang approved these changes

2019-09-03 21:58 UTC, xuhdev commented on torch/hub.py
> +    file_size = content_length
Actually I don't see how `content_length` is used. Perhaps we should remove it?

2019-09-04 00:07 UTC, soumith requested changes
can you please add requests to requirements.txt and to README but leave the code unchanged.
Once we switch to Python3 when Py2 EOLs, we can remove this dependency with the current code.

2019-09-04 19:05 UTC, jamesr66a commented
@soumith does this look OK now?

2019-09-04 21:10 UTC, soumith approved these changes
thanks lgtm

2019-09-05 00:43 UTC, closed without merging