Added possible out of shared memory error message
pytorch/pytorch pull request #25730
Opened 2019-09-05 20:57 UTC by pbelevich

Fixes #5040

2019-09-05 21:04 UTC, zou3519 approved these changes

2019-09-05 21:04 UTC, zou3519 commented on torch/csrc/DataLoader.cpp
> +            oss << "Possibly because out of shared memory. ";
nit: we can make this a little more detailed. "It is possible that you are out of shared memory. Please try to raise your shared memory limit."

2019-09-05 22:33 UTC, ssnl reviewed
There is already a similar message in line 61.

2019-09-06 13:58 UTC, zou3519 requested changes
Thanks for pointing that out, @SsnL. The question now is to figure out if it gets triggered when we send a SIGBUS. I was reading the original issue (#5040) and that one implies that the error message at line 61 might not get triggered, but no one has posted a recent copy of it.

2019-09-13 21:47 UTC, zou3519 approved these changes
Based on https://github.com/pytorch/pytorch/issues/5040#issuecomment-531401065, it looks like the signal handlers print before the stack trace. It would be nice for the error message in the signal handler to also appear at the end of the stack trace. 

This PR makes the SIGBUS error message happen at the end of the stack trace, which is great.

2019-09-14 12:27 UTC, closed without merging