serialize xla tensor
pytorch/pytorch pull request #25882
Opened 2019-09-09 22:21 UTC by ailzhang

Currently `pytorch/xla` carries this as a patch but it makes more sense to upstream this change here. 
Basically it allows 
- `copy.copy(xla_tensor)` returns a xla tensor(two tensors don't share storage like CPU/CUDA tho).
- `torch.save(xla_tensor, 'temp'), loaded = torch.load('temp')`, `loaded` is a CPU tensor (explained in the note).
This is the best solution I can think of so far. I'm happy to implement other ways if we could simplify the serialization logic.

2019-09-09 22:47 UTC, gchanan commented
isn't this just because, roughly, XLATensor doesn't have a storage and our serialization depends on having a storage?

Can we instead make the serialization not depend on having a storage?

2019-09-09 22:59 UTC, ailzhang commented
@gchanan I don't have a full solution how to get rid of storage in serialization yet, but I could give it a try locally. :D  
I didn't go down that path mainly because changes along that direction usually means BC-breaking, unless we restrict this change only applicable for XLA. Which made it almost equally bad and less appealing.

2019-09-10 01:03 UTC, soumith commented
you cannot have serialization of regular Tensors not dependent on storage, because think of the views.
Example: `torch.save([x, x.view(10, 20)], 'foo.pt'); torch.load('foo.pt')` where you want to preserve view sharing.

2019-09-10 14:16 UTC, ezyang commented on torch/tensor.py
> +#     - first construct Tenosr on top of an randomly initialized storage
nit: Tensor

2019-09-10 14:18 UTC, ezyang commented
This might be the right patch in the end, but like @gchanan, I'd like to explore if there is a cleaner way to solve the problem.

Based on my current reading of the patch, when I serialize an XLA tensor, and then grab it back, it comes back as a CPU tensor (with no sharing), in contrast to current behavior with cpu and cuda. (1) Is this desirable behavior from the XLA end? (2) Why can't we serialize the xla type directly, and then generate an XLA tensor when we load? There's some commentary about how the storage-based deserialization mechanism doesn't work; my suggestion would have been just to short circuit all of that code and do something specifically for XLA.

2019-09-10 17:13 UTC, ailzhang commented
Thanks for the review @gchanan @ezyang @soumith ! 
As I thought more about the storage/view comments, I feel XLA cannot simply discard the `view` relationship as it currently does in this PR. It might cause mismatched results (with CPU/CUDA) in fine-tuning tasks. 
I agree that a better approach is
1.  Specialize XLA to serialize tensor type directly without worrying about storage.
2. Make XLA expose `view` relationship in python and preserve that information in serialization as well. 
My gut feeling is both should be doable and then XLA serialization behavior should fully match other devices. I'll look into implementing this. Please let me know if you foresee other issues in the approach. Thanks! 

Also cc: @dlibenzi @asuhan for the updated plan above.

2019-09-16 15:58 UTC, gchanan commented
> you cannot have serialization of regular Tensors not dependent on storage, because think of the views.
Example: torch.save([x, x.view(10, 20)], 'foo.pt'); torch.load('foo.pt') where you want to preserve view sharing.

Sure, you need to track the views across serialization, but that's not dependent on serializing storages as its done now.  For example, we have a plan to get rid of storages, but obviously we wouldn't just throw away the views.

2019-09-16 16:16 UTC, dlibenzi commented
We have added an API to hard fail in case one serializes XLA tensors which share a view:

https://github.com/pytorch/xla/blob/ca854a8303c4f9f4e2e88ff55fe62c61e433d37e/torch_xla_py/xla_model.py#L312

We just need to add it to the patch we carry for pytorch serialization. @ailzhang will talk to you today.

But, for us, the most common case to cover is model checkpoint.
There, one already does:
```Python
xla_model = network().to(xla_device)
... # Use xla_model
```
And that should already discard the view fabric of the network's CPU tensors (if any), no?

2019-09-17 13:34 UTC, ezyang commented on torch/serialization.py
> +            return ('OpaqueDevice', 'cpu')
I still don't understand why you are special casing the XLA device object on serialization to be an "opaque cpu device". You're just losing information doing this; seems weird to me.

2019-09-17 15:49 UTC, gchanan commented
@dlibenzi good question!

The answer is the view is not maintained, although PyTorch kind of lies to you and says that it is maintained.  Example:
```
>>> m=torch.nn.Identity()
>>> m.base = torch.nn.Parameter(torch.randn(2,3))
>>> m.view = m.base[0]
# we have a view on CPU
>>> m.view[0] = 5
>>> m.base
Parameter containing:
tensor([[ 5.0000, -0.9108, -0.3298],
        [-0.7786,  2.4771,  0.1038]], grad_fn=<CopySlices>)

# view is not maintained after moving
>>> m.to('cuda')
>>> m.view[0]=7
>>>  m.base
Parameter containing:
tensor([[ 5.0000, -0.9108, -0.3298],
        [-0.7786,  2.4771,  0.1038]], device='cuda:0', grad_fn=<CopySlices>)
# but it still says we have a view "base", although it's disconnected
>>> m.view._base
Parameter containing:
tensor([[ 5.0000, -0.9108, -0.3298],
        [-0.7786,  2.4771,  0.1038]], device='cuda:0', grad_fn=<CopySlices>)
```

Which gets back to a question I asked @ailzhang -- is there actually a case we've run into that we can't serialize because there are views?

2019-09-17 15:54 UTC, ailzhang commented
@gchanan we haven't seen a case that requires serilaizing views. 

I think current behavior is Pytorch does keep view in serialization but not across device

2019-09-17 15:59 UTC, gchanan commented
So, the above example is problematic because it's lying to you about the view relationship, but if that were fixed, could you not check whether `_base` were None to decide if you can safely serialize?

2019-09-17 16:00 UTC, dlibenzi commented
> @dlibenzi good question!
> 
> The answer is the view is not maintained, although PyTorch kind of lies to you and says that it is maintained. Example:
> 
> ```
> >>> m=torch.nn.Identity()
> >>> m.base = torch.nn.Parameter(torch.randn(2,3))
> >>> m.view = m.base[0]
> # we have a view on CPU
> >>> m.view[0] = 5
> >>> m.base
> Parameter containing:
> tensor([[ 5.0000, -0.9108, -0.3298],
>         [-0.7786,  2.4771,  0.1038]], grad_fn=<CopySlices>)
> 
> # view is not maintained after moving
> >>> m.to('cuda')
> >>> m.view[0]=7
> >>>  m.base
> Parameter containing:
> tensor([[ 5.0000, -0.9108, -0.3298],
>         [-0.7786,  2.4771,  0.1038]], device='cuda:0', grad_fn=<CopySlices>)
> # but it still says we have a view "base", although it's disconnected
> >>> m.view._base
> Parameter containing:
> tensor([[ 5.0000, -0.9108, -0.3298],
>         [-0.7786,  2.4771,  0.1038]], device='cuda:0', grad_fn=<CopySlices>)
> ```
> 
> Which gets back to a question I asked @ailzhang -- is there actually a case we've run into that we can't serialize because there are views?

I think there are two cases at hands.
One is the general case where one builds tensors on, say, CPU, serialize them back/forth, and the he assume he can find the same buffer sharing.
This, we cannot do (note, simple views are OK - views shared by multiple tensors within the serialization stream, are not).
Remember we do not have a storage and our view system is graph based.
Is it impossible? Maybe not.
Since our view system is probably the most complex piece of infrastructure we have, we need to consider how much complexity needs to be added to cover that case.
For now, given @ailzhang patch to serialize XLA tensors, and given an explicit hard fail on that corner case, I think we can call it done.

The far more occurring case is the user doing `torch.save(model, file)`.
Hard failing there would be bad because checkpoints we really need them working.
For these cases though, we are lucky as it seems that parameters of all the models I tested, do not fall into the first category.

2019-09-20 18:10 UTC, ezyang commented on torch/serialization.py
> +            values = obj.cpu().tolist()
This looks extremely wrong (even if, maybe it is accidentally doing what you want). C.f. the docs for `persistent_id`:

> For the benefit of object persistence, the pickle module supports the notion of a reference to an object outside the pickled data stream. Such objects are referenced by a persistent ID, which should be either a string of alphanumeric characters (for protocol 0) 5 or just an arbitrary object (for any newer protocol).

What are you doing here? You're reading out all of the values from the XLA tensor, and using that to form the ID. That's hardly an ID.

What I /expected/ to happen is that `__reduce_ex__` on Tensor detect when it's the XLA, decompose the tensor into its constituent pieces, and then define a rebuild function to rebuild them. What you seem to have done in the corresponding parts of this patch are just save the XLA tensor directly. Ummmm.

2019-09-20 18:10 UTC, ezyang requested changes
The way serialization is implemented right now looks like a massive hack.

2019-09-28 00:05 UTC, ailzhang commented
@ezyang There isn't an easy way to call `restore_location`(to remap XLA tensors) before XLA tensor is rebuilt in `__reduce_ex__` if I don't add a thing in `persistent_id/load` and that'll definitely be hacky. 
And to make `copy.copy` work with xla it also requires a bit hacky workaround. 
I thought about this change together with @mruberry and we agreed that the following two features may not be critical so I perfer to refactor the `restore_location` logic after the release. 
I'll just document in XLA for these caveats.

2019-09-29 22:25 UTC, closed without merging