"fixing" gcc bug introduced with cuda 10.1
pytorch/pytorch pull request #26445
Opened 2019-09-19 00:09 UTC by mingbowan

> Cuda 10.1: Nvidia, you're now "fixing" gcc bugs that gcc doesn't even have

see [discussion]( https://devtalk.nvidia.com/default/topic/1048037/linux/cuda-10-1-nvidia-you-re-now-quot-fixing-quot-gcc-bugs-that-gcc-doesn-t-even-have/) for detail

2019-09-19 17:34 UTC, bddppq approved these changes

2019-09-19 17:34 UTC, bddppq commented on caffe2/operators/utility_ops.h
> +    // as discussed at https://fburl.com/pwe6h1zo
Could you replace the fburl link with the actual link?

2019-09-19 17:45 UTC, soumith requested changes
replace fburl with actual link

2019-09-23 19:59 UTC, soumith approved these changes

2019-09-23 21:08 UTC, closed without merging