[pytorch] [distributed] [easy] Made test forgiving to allow rpc agent to return one of the two errors
pytorch/pytorch pull request #26506
Opened 2019-09-19 22:20 UTC by satgera

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

[pytorch] [distributed] Made test forgiving to allow rpc agent to return one of the two errors.

Differential Revision: [D17488899](https://our.internmc.facebook.com/intern/diff/D17488899/)

2019-09-20 00:13 UTC, pritamdamania87 requested changes

2019-09-20 00:13 UTC, pritamdamania87 commented on test/test_rpc.py
> +        dist.init_model_parallel(self_name='worker{}'.format(self.rank),
Shouldn't we have two separate tests here? One uses duplicate worker name and raises an error with message "is not unique" and then another initializes model_parallel again with a unique name but should raise an error with "is already initialized"?

2019-09-24 15:38 UTC, satgera commented
@pytorchbot retest this please

2019-09-24 15:41 UTC, pietern commented on test/test_rpc.py
>                                       init_method=RPC_INIT_URL)
AFAICT this shouldn't initialize with `init_model_parallel` outside the `assertRaisesRegex` wrapper.

The purpose is to only test for duplicate names right? Not that it was already initialized.

2019-09-24 16:26 UTC, pietern approved these changes
LGTM, provided CI passes.

2019-09-24 22:05 UTC, satgera commented
@pytorchbot retest this please

2019-09-24 23:14 UTC, satgera commented
Retried the CI to ensure all pass but looks like infra issue. Some of the failure which indicate build failure seems to have succeed.
Since this is a trivial change and other test have passed, landing.

2019-09-24 23:39 UTC, closed without merging