Register values listed in __constant__ as attributes of the Module.
pytorch/pytorch pull request #26581
Opened 2019-09-20 23:56 UTC by ZolotukhinM

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

We're currently inlining immediate values of the constants directly into
IR when we generate it providing no way to access these values by their
names later. This change registers such values as atrtibutes of the
module so that they are not lost after IR generation.

2019-09-21 23:17 UTC, suo requested changes
I am about to put up a substantial rewrite of ModuleValue and associated logic, so I think it would be better  to base these changes off of that. In particular, we are (for the most part) going to disallow `py_module_` lookups in `ModuleValue::attr`

2019-09-23 17:27 UTC, jerryzh168 commented
@suo is that going to be done before branch cut(9/24)?

2019-09-23 22:51 UTC, suo commented
No. Is this functionality needed for the release?

2019-09-23 22:57 UTC, jerryzh168 commented
> No. Is this functionality needed for the release?

I think so, otherwise BatchNorm folding is not going to work properly

2019-09-24 06:09 UTC, suo approved these changes

2019-09-24 06:09 UTC, suo commented on torch/csrc/jit/script/python_sugared_value.cpp
> +    if (py::isinstance<py::bool_>(attr)) {
`pybind_utils.h` has the functions `tryToInferType` and `toIValue`, which can be combined to make this more general.

2019-09-24 17:30 UTC, closed without merging

2019-09-24 20:57 UTC, suo commented
this PR breaks mkldnn tests on master