[quant] Add QuantFusion to graph_executor
pytorch/pytorch pull request #26591
Opened 2019-09-21 05:17 UTC by jerryzh168

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Summary:
att

Test Plan:
.

Reviewers:
pt1quant

Subscribers:

Tasks:

Tags:

2019-09-23 18:52 UTC, jerryzh168 commented
btw this PR is regenerated, last PR is merged somehow.

2019-09-27 20:30 UTC, ZolotukhinM requested changes

2019-09-27 20:30 UTC, ZolotukhinM commented on torch/csrc/jit/graph_executor.cpp
> +      at::globalContext().qEngine() == at::kQNNPACK) {
Optimization pipeline in graph executor cannot be conditionalized on a global state. We need to make sure QuantFusion is always correct and run it unconditionally.

2019-09-27 21:11 UTC, ZolotukhinM approved these changes
Looks good!

2019-09-27 21:11 UTC, ZolotukhinM commented on torch/csrc/jit/graph_executor.cpp
> +
This is unused.

2019-09-28 01:01 UTC, closed without merging