[qconv] Remove duplicate calculation of output shape
pytorch/pytorch pull request #26684
Opened 2019-09-23 22:50 UTC by dskhudia

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Output heights and widths are already calculated by conv_p. Remove the duplicate calculation.

Differential Revision: [D17538375](https://our.internmc.facebook.com/intern/diff/D17538375/)

2019-09-23 22:55 UTC, raghuramank100 approved these changes

2019-09-23 23:01 UTC, supriyar commented
@dskhudia `convOutputShape` is also used by qnnpack code below. Please don't delete it.

2019-09-23 23:01 UTC, supriyar requested changes
Don't delete convOutputShape

2019-09-24 00:28 UTC, dskhudia commented
@supriyar left the convOutputShape as is.

2019-09-24 00:39 UTC, supriyar approved these changes

2019-09-24 16:49 UTC, closed without merging