Update Convolution.cpp (NNPACK batchsize condition remove)
pytorch/pytorch pull request #26711
Opened 2019-09-24 07:17 UTC by snippler

As discussed in the issues forum the condition on batchsize is contradictory, see
https://github.com/pytorch/pytorch/issues/26396

2019-09-24 07:18 UTC, snippler commented
Reviewer: ezyang

2019-09-24 13:43 UTC, ezyang approved these changes

2019-09-24 13:44 UTC, ezyang requested changes
It looks like there were correctness reasons why we didn't turn on NNPACK in this case. Take a look at these test failures:

```
Sep 24 08:18:15 ======================================================================
Sep 24 08:18:15 ERROR: test_Conv1d_zero_batch (__main__.TestNN)
Sep 24 08:18:15 ----------------------------------------------------------------------
Sep 24 08:18:15 Traceback (most recent call last):
Sep 24 08:18:15   File "test_nn.py", line 9161, in <lambda>
Sep 24 08:18:15     add(test_name, lambda self, test=test: test(self))
Sep 24 08:18:15   File "/var/lib/jenkins/workspace/test/common_nn.py", line 3523, in __call__
Sep 24 08:18:15     self._do_test(test_case, module, input)
Sep 24 08:18:15   File "test_nn.py", line 326, in _do_test
Sep 24 08:18:15     module(input)
Sep 24 08:18:15   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 545, in __call__
Sep 24 08:18:15     result = self.forward(*input, **kwargs)
Sep 24 08:18:15   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 202, in forward
Sep 24 08:18:15     self.padding, self.dilation, self.groups)
Sep 24 08:18:15 RuntimeError: NNPACK SpatialConvolution_updateOutput failed
Sep 24 08:18:15 
Sep 24 08:18:15 ======================================================================
Sep 24 08:18:15 ERROR: test_Conv2d_zero_batch (__main__.TestNN)
Sep 24 08:18:15 ----------------------------------------------------------------------
Sep 24 08:18:15 Traceback (most recent call last):
Sep 24 08:18:15   File "test_nn.py", line 9161, in <lambda>
Sep 24 08:18:15     add(test_name, lambda self, test=test: test(self))
Sep 24 08:18:15   File "/var/lib/jenkins/workspace/test/common_nn.py", line 3523, in __call__
Sep 24 08:18:15     self._do_test(test_case, module, input)
Sep 24 08:18:15   File "test_nn.py", line 326, in _do_test
Sep 24 08:18:15     module(input)
Sep 24 08:18:15   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 545, in __call__
Sep 24 08:18:15     result = self.forward(*input, **kwargs)
Sep 24 08:18:15   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
Sep 24 08:18:15     return self.conv2d_forward(input, self.weight)
Sep 24 08:18:15   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
Sep 24 08:18:15     self.padding, self.dilation, self.groups)
Sep 24 08:18:15 RuntimeError: NNPACK SpatialConvolution_updateOutput failed
Sep 24 08:18:15 
Sep 24 08:18:15 ======================================================================
Sep 24 08:18:15 FAIL: test_Conv2d_groups_nobias (__main__.TestNN)
Sep 24 08:18:15 ----------------------------------------------------------------------
Sep 24 08:18:15 Traceback (most recent call last):
Sep 24 08:18:15   File "test_nn.py", line 4819, in test_Conv2d_groups_nobias
Sep 24 08:18:15     dtype2prec[dtype])
Sep 24 08:18:15   File "/var/lib/jenkins/workspace/test/common_utils.py", line 698, in assertEqual
Sep 24 08:18:15     assertTensorsEqual(x, y)
Sep 24 08:18:15   File "/var/lib/jenkins/workspace/test/common_utils.py", line 668, in assertTensorsEqual
Sep 24 08:18:15     self.assertLessEqual(max_err, prec, message)
Sep 24 08:18:15 AssertionError: tensor(2.0183, dtype=torch.float32) not less than or equal to 1e-05 : 
Sep 24 08:18:15 
Sep 24 08:18:15 ======================================================================
Sep 24 08:18:15 FAIL: test_Conv2d_groups_nobias_v2 (__main__.TestNN)
Sep 24 08:18:15 ----------------------------------------------------------------------
Sep 24 08:18:15 Traceback (most recent call last):
Sep 24 08:18:15   File "test_nn.py", line 4855, in test_Conv2d_groups_nobias_v2
Sep 24 08:18:15     dtype2prec[dtype])
Sep 24 08:18:15   File "/var/lib/jenkins/workspace/test/common_utils.py", line 698, in assertEqual
Sep 24 08:18:15     assertTensorsEqual(x, y)
Sep 24 08:18:15   File "/var/lib/jenkins/workspace/test/common_utils.py", line 668, in assertTensorsEqual
Sep 24 08:18:15     self.assertLessEqual(max_err, prec, message)
Sep 24 08:18:15 AssertionError: tensor(5.1778, dtype=torch.float32) not less than or equal to 1e-05 : 
Sep 24 08:18:15 
Sep 24 08:18:15 ======================================================================
Sep 24 08:18:15 FAIL: test_Conv2d_naive_groups (__main__.TestNN)
Sep 24 08:18:15 ----------------------------------------------------------------------
Sep 24 08:18:15 Traceback (most recent call last):
Sep 24 08:18:15   File "test_nn.py", line 3462, in test_Conv2d_naive_groups
Sep 24 08:18:15     self._test_Conv2d_naive_groups()
Sep 24 08:18:15   File "test_nn.py", line 4783, in _test_Conv2d_naive_groups
Sep 24 08:18:15     prec=dtype2prec[dtype])
Sep 24 08:18:15   File "/var/lib/jenkins/workspace/test/common_utils.py", line 698, in assertEqual
Sep 24 08:18:15     assertTensorsEqual(x, y)
Sep 24 08:18:15   File "/var/lib/jenkins/workspace/test/common_utils.py", line 668, in assertTensorsEqual
Sep 24 08:18:15     self.assertLessEqual(max_err, prec, message)
Sep 24 08:18:15 AssertionError: tensor(1.9479, dtype=torch.float32) not less than or equal to 1e-05 : 
Sep 24 08:18:15 
Sep 24 08:18:15 ======================================================================
Sep 24 08:18:15 FAIL: test_conv_double_backward (__main__.TestNN)
Sep 24 08:18:15 ----------------------------------------------------------------------
Sep 24 08:18:15 Traceback (most recent call last):
Sep 24 08:18:15   File "test_nn.py", line 8404, in test_conv_double_backward
Sep 24 08:18:15     "\ndtype: " + str(dtype))
Sep 24 08:18:15 AssertionError: False is not true : Conv double backward test failed with parameters:
Sep 24 08:18:15 kern: 3
Sep 24 08:18:15 stride: 1
Sep 24 08:18:15 padding: 0
Sep 24 08:18:15 chan_in: 2
Sep 24 08:18:15 chan_out: 3
Sep 24 08:18:15 batch_size: 2
Sep 24 08:18:15 inp_size: 6
Sep 24 08:18:15 dilation: 1
Sep 24 08:18:15 dtype: torch.float32
Sep 24 08:18:15 
Sep 24 08:18:15 ----------------------------------------------------------------------
Sep 24 08:18:15 Ran 1452 tests in 1494.167s
```

2019-09-24 13:45 UTC, ezyang commented
The first two failures should be easy to deal with, it looks like nnpack doesn't handle zero-size batches correctly. I don't know about the other ones though.

2019-09-24 14:04 UTC, snippler commented
Maybe we could have the condition batchsize >= 1 and demand bias. Backward could be excluded. Not sure about remaining issue.

2021-01-10 13:41 UTC, t-vi commented
I hit this as a perf bottleneck on raspi again. @snippler Do you still want to handle this, or should I see to fix it?

2021-01-10 13:46 UTC, t-vi commented
(and it could be that the solution is "don't use NNPACK but always XNNPACK" or somesuch)

2021-01-11 06:37 UTC, snippler commented
@t-vi I did not look back after having started it. Now I see that merging was blocked due to some changes that were requested. Feel free to take over. Thank you.

2022-06-27 21:37 UTC, closed without merging