[pytorch] add default constructor to ivalue::Future
pytorch/pytorch pull request #26746
Opened 2019-09-24 20:16 UTC by ljk53

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Summary:
PR #25439 introduced type() to IValue, which enforced ivalue::Future to
be constructed with type. This broke ParallelNative.h and a few other
places where Future was constructed without type and simply used as a barrier:
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/ParallelNative.h#L63

We could set NoneType by default if we want to enforce non-null type
everywhere, but looks like Tuple can take null TupleType so just follow
it.

Test Plan:
- builds

2019-09-24 21:23 UTC, smessmer reviewed
Are we sure we want to be able to construct Futures without type information? Afaik, we want to have types everywhere. cc @zdevito

2019-09-24 21:23 UTC, smessmer commented on aten/src/ATen/core/ivalue_inl.h
> +  Future() {}
nit: `Future() = default;` is better

2019-09-25 02:26 UTC, suo requested changes
I don't think this makes a ton of sense. TupleType takes a null type because the type can be lazily inferred by inspecting the types of the contained elements, not because it actually doesn't have a type.

I would prefer not to default construct `Future` as there is not an obvious default. Can we change ParallelNative and friends to use `Future<None>`?

2019-09-25 02:50 UTC, ilia-cher commented
@suo I wonder would it make sense to make it None by default (with default ctor)

2019-09-25 04:21 UTC, ljk53 commented on aten/src/ATen/ParallelNative.h
> +    }
@ilia-cher let me know if I should move this to a common util function, maybe in Parallel.h? I can reuse it in ParallelNativeMobile.h as well.

2019-09-25 04:51 UTC, zdevito commented
This and https://github.com/pytorch/pytorch/pull/26739 are duplicates, fyi.

2019-09-26 05:54 UTC, closed without merging