Choose num_threads in parallel_for based on GRAIN_SIZE
pytorch/pytorch pull request #26886
Opened 2019-09-26 09:46 UTC by peterbell10

Fixes #24080 

The OpenMP implementation of `parallel_for` now chooses the number of cores to use on a sliding scale between 1 and `OMP_NUM_THREADS`. This prevents wasteful core usage on many-core systems such as in #24080.

This is also consistent with the comment on GRAIN_SIZE:
https://github.com/pytorch/pytorch/blob/e327df396564f937d17b5f28e2529229260c65bf/aten/src/ATen/Parallel.h#L10-L11

2019-09-26 14:43 UTC, ezyang approved these changes

2019-09-26 14:44 UTC, ezyang commented on aten/src/ATen/ParallelOpenMP.h
> +  num_threads = std::min(num_threads, divup(num_iter, grain_size));
`grain_size` is allowed to be zero.

2019-09-26 14:44 UTC, ezyang requested changes
need to handle `grain_size == 0` case

2019-09-26 20:48 UTC, ezyang approved these changes

2019-09-26 21:11 UTC, closed without merging

2019-09-27 02:34 UTC, soumith commented
fyi this PR has been reverted because it broke a bunch of torchvision tests and also a bunch of aten-native tests

2019-09-27 02:35 UTC, soumith commented
I wonder if it has to do with `#pragma omp parallel num_threads(num_threads)` which has unintended consequences, where even if `num_threads=1`, entering an omp block inside an omp block results in bad behavior.

2019-09-27 02:37 UTC, soumith commented
some more info -- it broke down only in clang + openmp (not in gcc + openmp that is in the open-source CI)

2019-09-27 12:20 UTC, ezyang commented
@soumith Where can I see the tests that failed?

2019-09-27 12:21 UTC, ezyang commented
Oh, internal tests