[ONNX] Export det
pytorch/pytorch pull request #26958
Opened 2019-09-27 06:06 UTC by neginraoof

Added symbolic to export det in opset 11

2019-10-01 17:28 UTC, BowenBao approved these changes
LGTM, minor comment on better test coverage.

2019-10-01 17:28 UTC, BowenBao commented on test/onnx/test_pytorch_onnx_onnxruntime.py
> +        x = torch.randn(2, 3, 5, 5, requires_grad=True)
Can we add another test case where input shape is (5, 5)? That covers the case where output is scalar.

2019-10-01 20:28 UTC, lara-hdr commented
@neginraoof TestOperators.test_det is failing

2019-10-07 16:30 UTC, neginraoof commented
@pytorchbot rebase this please

2019-10-09 23:22 UTC, houseroad requested changes
Export looks good.

`RuntimeError: lu: LAPACK library not found in compilation`

Please fix the tests.

2019-10-10 01:12 UTC, neginraoof commented
@houseroad I didn't see this locally. Trying to repro. Do you have an idea why it complains about the missing package?

2019-10-11 16:27 UTC, neginraoof commented
cc @houseroad for review

2019-10-13 04:55 UTC, houseroad reviewed
Fix the conflict?

2019-10-14 05:23 UTC, neginraoof commented
@houseroad just updated. please review

2019-10-16 18:25 UTC, houseroad requested changes
Please do NOT update onnx submodule

2019-10-16 21:22 UTC, neginraoof commented
@houseroad onnx is reset. Just rebased this

2019-10-16 23:18 UTC, neginraoof commented
@houseroad this is ready

2019-10-22 16:24 UTC, neginraoof commented
@houseroad please review the updates

2019-10-22 17:09 UTC, houseroad approved these changes
LGTM

2019-10-22 20:33 UTC, closed without merging