Migrate nonzero from the TH to Aten(CPU)
pytorch/pytorch pull request #27217
Opened 2019-10-02 15:28 UTC by ifedan

#24745

2019-10-07 23:42 UTC, ifedan commented
![image](https://user-images.githubusercontent.com/12058312/66356832-86c5dd80-e93a-11e9-9b88-2a9b1dfb46f9.png)

2019-10-08 00:07 UTC, ifedan commented
```python
import torch
import timeit
import itertools
import statistics

for i in [10, 100, 10000, 100000, 1000000]:
    setup_code = '''import torch; w = (torch.rand({0}) < 0.5).double()'''.format(i)
    test_code = '''torch.nonzero(w);'''
    result = timeit.repeat(setup = setup_code,stmt = test_code,repeat = 3,number = 100)
    mean = statistics.mean(result)
    std = statistics.stdev(result)
    print('''size = {0} time = {1}'''.format(i, mean))
```

2019-10-08 17:21 UTC, ifedan commented
https://github.com/pytorch/pytorch/pull/27513

2019-10-08 19:35 UTC, VitalyFedyunin requested changes
Not working for non contiguous tensors.

```python 

In [8]: x = (torch.randn(2,5)<0.5).double()                                                                                                                                                                                                                                                

In [9]: x.t()                                                                                                                                                                                                                                                                              
Out[9]: 
tensor([[1., 1.],
        [1., 1.],
        [1., 0.],
        [0., 0.],
        [1., 1.]], dtype=torch.float64)

In [10]: x                                                                                                                                                                                                                                                                                 
Out[10]: 
tensor([[1., 1., 1., 0., 1.],
        [1., 1., 0., 0., 1.]], dtype=torch.float64)

In [11]: x.t().is_contiguous()                                                                                                                                                                                                                                                             
Out[11]: False

In [12]: x.t().nonzero()                                                                                                                                                                                                                                                                   
Out[12]: 
tensor([[0, 0],
        [0, 1],
        [1, 0],
        [2, 0],
        [2, 1],
        [3, 0],
        [4, 1]])

In [13]: x.t().nonzero()                                                                                                                                                                                                                                                                   
Out[13]: 
tensor([[0, 0],
        [0, 1],
        [1, 0],
        [2, 0],
        [2, 1],
        [3, 0],
        [4, 1]])

In [14]: x.t().contiguous().nonzero()                                                                                                                                                                                                                                                      
Out[14]: 
tensor([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1],
        [2, 0],
        [4, 0],
        [4, 1]])
                                                                                                                                                                                                                                                                         
```

compare last 2 statements.

As `cpu_serial_kernel` doesn't guarantee traverse order.

2019-10-08 21:06 UTC, albanD commented
Can the TH implementation be deleted? Or is it used in other places?

2019-10-11 23:03 UTC, ifedan commented
> Can the TH implementation be deleted? Or is it used in other places?

deleted

2019-10-11 23:03 UTC, ifedan commented
> Not working for non contiguous tensors.
> 
> ```python
> In [8]: x = (torch.randn(2,5)<0.5).double()                                                                                                                                                                                                                                                
> 
> In [9]: x.t()                                                                                                                                                                                                                                                                              
> Out[9]: 
> tensor([[1., 1.],
>         [1., 1.],
>         [1., 0.],
>         [0., 0.],
>         [1., 1.]], dtype=torch.float64)
> 
> In [10]: x                                                                                                                                                                                                                                                                                 
> Out[10]: 
> tensor([[1., 1., 1., 0., 1.],
>         [1., 1., 0., 0., 1.]], dtype=torch.float64)
> 
> In [11]: x.t().is_contiguous()                                                                                                                                                                                                                                                             
> Out[11]: False
> 
> In [12]: x.t().nonzero()                                                                                                                                                                                                                                                                   
> Out[12]: 
> tensor([[0, 0],
>         [0, 1],
>         [1, 0],
>         [2, 0],
>         [2, 1],
>         [3, 0],
>         [4, 1]])
> 
> In [13]: x.t().nonzero()                                                                                                                                                                                                                                                                   
> Out[13]: 
> tensor([[0, 0],
>         [0, 1],
>         [1, 0],
>         [2, 0],
>         [2, 1],
>         [3, 0],
>         [4, 1]])
> 
> In [14]: x.t().contiguous().nonzero()                                                                                                                                                                                                                                                      
> Out[14]: 
> tensor([[0, 0],
>         [0, 1],
>         [1, 0],
>         [1, 1],
>         [2, 0],
>         [4, 0],
>         [4, 1]])
>                                                                                                                                                                                                                                                                          
> ```
> 
> compare last 2 statements.
> 
> As `cpu_serial_kernel` doesn't guarantee traverse order.

fixed and added tests

2019-10-11 23:04 UTC, ifedan commented on aten/src/ATen/native/TensorIterator.h
> +  bool reverse_order_dims_ = false;
maybe we need to use a better name

2022-04-12 18:53 UTC, albanD commented
TH is no more so this already happened somewhere else I'm sure.

2022-04-12 18:53 UTC, closed without merging