C++ API: torch::nn::LogSoftmax
pytorch/pytorch pull request #27462
Opened 2019-10-07 13:55 UTC by nuka137

Add torch::nn::LogSoftmax module and functional support for the C++ API.

Related Issue: #25883 

Reviewer: @yf225

2019-10-07 16:47 UTC, pbelevich requested changes

2019-10-07 16:47 UTC, pbelevich commented on torch/csrc/api/include/torch/nn/options/activation.h
> +  TORCH_ARG(int, dim);
Please change it to c10::optional<int64_t> with c10::nullopt default value

2019-10-09 21:25 UTC, yf225 commented
Thanks a lot for the great work! We will need some fixes as suggested in https://github.com/pytorch/pytorch/pull/27446.

2019-10-10 04:31 UTC, nuka137 commented
@yf225

Fixed all issues discussed in #27446, and rebased to newest master branch.
Could you review this PR again?

2019-10-10 22:25 UTC, yf225 approved these changes
Thanks so much for the great work @nuka137!

2019-10-10 23:18 UTC, closed without merging