Add instructions for setting up ccache from conde
pytorch/pytorch pull request #27481
Opened 2019-10-07 18:45 UTC by ngoldbaum

I was unable to use the existing instructions since I don't have sudo priveleges on my GPU development machine and couldn't easily install `ccache` or the build dependencies for `ccache`.

However, I was able to get it working by installing `ccache` with `conda` and then creating symlinks to shadow my compilers as in the build-from-source installation instructions. I figure this might be generally useful as others might not have sudo privileges on their pytorch development machine.

2019-10-07 18:55 UTC, pearu requested changes
Suggested a couple of fixes.

2019-10-07 18:55 UTC, pearu commented on CONTRIBUTING.md
> +export CUDA_NVCC_EXECUTABLE=~/ccacche/cuda/nvcc
Typo: `ccacche`

2019-10-07 18:55 UTC, pearu commented on CONTRIBUTING.md
> +ln -s ~/miniconda3/bin/ccache ~/ccache/lib/cc
Use `$CONDA_PREFIX` instead of `~/miniconda3`.

2019-10-07 18:59 UTC, ngoldbaum commented
Thanks @pearu, TIL `CONDA_PREFIX` is a thing.

2019-10-09 15:30 UTC, ezyang commented
Can you double check that the conda ccache has the necessary fixes for working correctly with nvcc?

2019-10-09 15:30 UTC, ezyang approved these changes

2019-10-09 15:50 UTC, closed without merging