[ROCm] Add bfloat16 support in linear algebra on ROCm
pytorch/pytorch pull request #27719
Opened 2019-10-10 22:28 UTC by iotamudelta

2019-11-12 22:51 UTC, iotamudelta commented
@gottbrath this is the BLAS bringup for bf16

2019-11-18 14:48 UTC, ezyang commented
This patch is described to be ROCm specific, but the contents of the diff suggest to me that it is turning on bfloat16 on regular CUDA as well. What's going on here? 

Additionally, I didn't see any test modifications.

2019-11-18 17:06 UTC, iotamudelta commented
@ezyang thanks for looking at it! I don't think we can discriminate between CUDA/ROCm in the Declarations?

Test cases: that's a good point. We've tested with actual scripts but let me see if we can also enable some unit tests here.

2019-11-19 16:31 UTC, ezyang commented
I guess what I'm mostly wondering is, does this PR also accidentally add support for CUDA at the same time? Or will the CUDA paths just error.

2019-11-19 17:57 UTC, rohithkrn commented
@ezyang cuda paths will just error if bfloat16 type is used.

2019-11-20 18:31 UTC, ezyang commented
Thanks. This looks gtg, just needs to resolve merge conflict

2019-11-21 07:09 UTC, bddppq requested changes
Could you add some tests? Maybe refer to https://github.com/pytorch/pytorch/pull/27259 to see how to add bfloat16 tests.

2019-11-21 15:16 UTC, izdeby commented on aten/src/THC/generic/THCTensorMathBlas.cu
> +#elif defined(THC_REAL_IS_HALF)  || defined(THC_REAL_IS_BFLOAT16)
minor: double space

2019-11-21 15:17 UTC, izdeby commented
Can you, please, add some description of what and why are these changes for? Also, add tests

2019-11-21 15:26 UTC, iotamudelta commented
@bddppq @izdeby tests are incoming.

@izdeby I thought the title was pretty self-explanatory but added more words to the description now. OK?

2019-11-21 21:49 UTC, rohithkrn commented
@bddppq @izdeby @ezyang the tests for gemms are under `tensor_op_tests`. Added `bfloat16_precision`(defaults to 1e-5) arg to the argument list and enabled `bfloat16` tests for gemm ops on ROCm

2019-11-21 22:20 UTC, izdeby approved these changes

2019-11-22 03:43 UTC, bddppq approved these changes

2019-11-22 07:54 UTC, closed without merging