Allow Tracing of convolution function #18776
pytorch/pytorch pull request #28027
Opened 2019-10-15 20:00 UTC by bzinodev

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Currently tracing convolution operations wraps to internal implementation
    _convolution function. As a result 'benchmark' and other flags are hard
    wired. Changes to these context flags at later stages are ignored.

    The proposed fix is to remove 'convolution' from DONT_RECORD_TRACE.
    Note all convolution operations end up calling convolution
    function so this fix applies to all convolution operations.

2019-10-15 21:19 UTC, soumith requested changes
afaik this means that we will start tracing backend-specific autograd functions, which means the traced graph will be specialized to a device (for example, it'll instead trace cudnn_convolution_forward).

Tell me why I'm wrong.

2019-10-16 14:00 UTC, ezyang commented
Yeah, I'm very doubtful we should do this. If you want to avoid hardwiring the benchmark flag, we should introduce a new variant of convolution that doesn't take benchmark as an argument, trace that, and have that pull out the actual value for use. (Maybe this function could even be called `_convolution`; I'm not sure what the BC implications of this are.)

2019-10-16 18:32 UTC, zdevito commented
Changing the way we produce convolutions from traces will break a lot of things downstream that expect to see `_convolution` and changing the API of `_convolution` will break backwards compatibility for serialized models unless we implement an upgrader path in the input pipeline.  Instead, I think the best approach here is to keep the boolean options to enable benchmarking, but make the semantic be:

`do_benchmarking = benchmarking_argument_from_operator or benchmarking_enabled_in_thread_local_context`

The following scenarios are or will be common:

(1) user previously exported a model for their custom predictor service, and made sure to set benchmarking on export. They expect benchmarking. (benchmarking_argument_from_operator=True, benchmarking_enabled_in_thread_local_context=False).
(2) user exported a model, and now that there is a C++ version of the thread local context to enable benchmarking, they expect the exported model to run with it. (benchmarking_argument_from_operator=False, benchmarking_enabled_in_thread_local_context=True)
(3) (1) and (2) together (True, True)

The scarior where (1) happens except they expect benchmarking not to happen in predictor is going to be so rare we do not need to worry the fact that it is impossible to disable benchmarking at the predictor level in this scenario.

2019-10-21 21:52 UTC, bzinodev commented
Thank you everyone for your valuable comments. I am glad I posted this patch :).  I agree this is not a good fix. The current design  captures exactly the setting of convolution operation as expected for tracing. My change breaks this expectation.  I'd like to summarize various options that many proposed:

1)  Keep current design and close issue.   Submit a patch to document and improve comment DO_NOT_TRACE. With this option setting the context flags after tracing are silently ignored.
2) Keep same design and emit a warning when the context flag value mismatches the hard-wired value captured from tracing and also the context flag value is also different from its default value. 
3) Allow late partial setting (Devito proposal). Use OR operation in _convolution (e.g. benchmark |= Context.benchmark). Choose only the flag that make sense to override (e.g. benchmark and deterministic? but not cudnn_enabled? 
4) Override hard-wired flags in _convolution by context flags  when they differ from their default value. 

My $0.02 is to opt for option 1 or 2.

2022-05-12 03:47 UTC, closed without merging