Optimize GroupNorm on CPU
pytorch/pytorch pull request #28203
Opened 2019-10-17 04:19 UTC by BIT-silence

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Optimize GroupNorm on CPU

Differential Revision: [D17901506](https://our.internmc.facebook.com/intern/diff/D17901506/)

2019-10-17 04:23 UTC, BIT-silence commented
link to https://github.com/pytorch/pytorch/issues/28201

2019-10-17 05:12 UTC, BIT-silence commented
cc @ppwwyyxx

2019-10-17 16:09 UTC, ngimel requested changes
This generally looks good, but I have a suggestion regarding dispatch mechanism. You can either use device-specific dispatch defined in native_functions.yaml (there are many examples of that), or you can use stubs mechanism to achieve basically the same effect (see e.g. how it is done for indexing https://github.com/pytorch/pytorch/blob/15f9fe1d92a5d1e86278ae25f92dd9677b4956dc/aten/src/ATen/native/Normalization.cpp#L63-L71). Mixing the two is rarely if ever necessary, and creates a much more complicated code. Can you please stick to one of those? Otherwise the implementation itself is fine.

2020-04-24 15:46 UTC, bonlime commented
Hi.
@BIT-silence are you planning to do the requested changes?

2020-04-24 17:28 UTC, BIT-silence commented
Yes, just previously I don't have enough time to work on this. I will try to fix the things and merge it soon.

2020-05-23 23:13 UTC, BIT-silence commented on aten/src/ATen/native/cpu/group_norm_kernel.cpp
> +      const T* X_ptr = X_data + i * C * HxW + j * D * HxW;
Made it a single for-loop and also added multi-threading.

2020-05-23 23:13 UTC, BIT-silence commented on aten/src/ATen/native/cpu/group_norm_kernel.cpp
> +  const T* dY_data = dY.template data_ptr<T>();
Cleared.

2020-05-24 00:24 UTC, BIT-silence commented
> This generally looks good, but I have a suggestion regarding dispatch mechanism. You can either use device-specific dispatch defined in native_functions.yaml (there are many examples of that), or you can use stubs mechanism to achieve basically the same effect (see e.g. how it is done for indexing
> 
> https://github.com/pytorch/pytorch/blob/15f9fe1d92a5d1e86278ae25f92dd9677b4956dc/aten/src/ATen/native/Normalization.cpp#L63-L71
> 
> ). Mixing the two is rarely if ever necessary, and creates a much more complicated code. Can you please stick to one of those? Otherwise the implementation itself is fine.

Done.

2020-06-03 01:05 UTC, ngimel reviewed
Looks good, I have only minor comments.

2020-06-03 01:05 UTC, ngimel commented on aten/src/ATen/native/native_functions.yaml
> +  dispatch:
do you need to define dispatch now? native_group_norm is not device-specific, it should work without dispatch.

2020-06-03 03:01 UTC, BIT-silence commented on aten/src/ATen/native/cpu/group_norm_kernel.cpp
> +  DCHECK_EQ(X.numel(), N * C * HxW);
Done.

2020-06-03 21:41 UTC, ngimel approved these changes

2020-06-03 21:42 UTC, ngimel commented
Thanks!

2020-06-04 06:53 UTC, closed without merging