Update docs for `new_group` to reflect all processes need to call it only for
MPI.
pytorch/pytorch pull request #28247
Opened 2019-10-17 20:49 UTC by pritamdamania87

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

MPI.

The documentation for `new_group` mentioned the following:

```
This function requires that all processes in the main group (i.e. all
processes that are part of the distributed job) enter this function, even
if they are not going to be members of the group
```

Although, this is only true for the MPI backend and not true for GLOO or NCCL.
As a result, in this change we're updating the docs to reflect this accurately.

Differential Revision: [D17988969](https://our.internmc.facebook.com/intern/diff/D17988969/)

2019-10-20 09:23 UTC, apaszke requested changes
I think we should be careful with changes like this one. My idea for backends is that changing between those should be only a matter of changing the argument to the initializing function. To achieve this, our semantics need to be a lowest common denominator of all the supported backends. Why is calling this function in all processes an issue?

2019-10-21 21:32 UTC, pritamdamania87 commented
> Why is calling this function in all processes an issue?

This was mostly motivated by the question on slack. It is confusing for users that they need to call this method on nodes that are not supposed to be part of the new process group.

2019-10-22 21:10 UTC, nottombrown commented
>> Why is calling this function in all processes an issue?

> This was mostly motivated by the question on slack. It is confusing for users that they need to call this method on nodes that are not supposed to be part of the new process group.

It also makes it harder to write clean abstractions if we have to initialize new groups on all ranks (including ranks that are not involved the groups).

2019-10-28 17:44 UTC, pritamdamania87 commented
@apaszke @pietern What is your recommendation here? It does seem a little confusing from an API perspective that users have to call `new_group` on all nodes.

2019-10-29 09:36 UTC, pietern commented
I agree with @apaszke's portability argument here. If we allow this for the non-MPI process groups, it's no longer as simple as changing the backend to make the same code run in a different environment.

That said, I agree not having to do this for the Gloo/NCCL backends would be nice.

We could think of a new `new_group` API that doesn't have this constraint and include the caveat that you can't use it with MPI. We would need to figure out a way to make all participating ranks use the same store prefix, so they can find each other. Otherwise, we run into the same problem that users run into when using the existing `new_group` call with different subsets of ranks -- they end up using the same prefix and interfere in each other's initialization. Currently we use an increasing integer, which only works if all global ranks are in sync.

2019-11-20 13:22 UTC, pietern commented
Adding some analysis.

The problem of the store prefix is that every group we create must have its own store prefix, as to avoid interfering with the creation of other groups. Currently, because all ranks have to call into `new_group`, even if they don't participate, a simple counter is enough. But if not all ranks call into the alternative `new_group`, then this won't work. Namely, if we have 4 ranks, and we concurrently create groups for `[0, 1]` and `[2, 3]`, they'll try to use the same prefix. Therefore, we need to incorporate the set of ranks into the prefix somehow. We could sort the ranks and feed them through some hash function to arrive at a unique prefix for the set of ranks. Then, on each rank, we can keep a dictionary with a counter per hash, so we can still create multiple groups for the same set of participants. I think this should work and be robust against whatever permutation of sets of ranks and time.

The next question is how we would surface this. Overloading `new_group` doesn't seem like a great idea, which means we'd have to come up with a new name, or API altogether. Perhaps `create_group` would do the trick to disambiguate the two? I don't particularly like it, but `new_group_v2` definitely doesn't cut it...

Thoughts?

2019-12-02 17:50 UTC, pritamdamania87 commented
>  We could sort the ranks and feed them through some hash function to arrive at a unique prefix for the set of ranks. Then, on each rank, we can keep a dictionary with a counter per hash, so we can still create multiple groups for the same set of participants. I think this should work and be robust against whatever permutation of sets of ranks and time.

Yes, I believe this should work and a separate API sounds appropriate as well. Is there a reason we need to store this counter per hash on each rank instead of the store itself? Also, would it be just easier to have the store generate a new UUID each time for the prefix?

2019-12-11 09:12 UTC, pietern commented
> Is there a reason we need to store this counter per hash on each rank instead of the store itself?

We could keep it in the store, but we already assume that these processes don't fail, so we might as well keep them local instead of making the code more complex. After all, if any of the participating ranks fail, we need to reinitialize the global group anyway, and go through rank reassignment.

> Also, would it be just easier to have the store generate a new UUID each time for the prefix?

We'd need a way to communicate the prefix between the participating ranks. Instead, if we can deterministically compute it on all processes given the same input, we no longer need to communicate it.

2020-07-15 19:00 UTC, closed without merging