Change error message for torch.linspace().
pytorch/pytorch pull request #28274
Opened 2019-10-18 04:26 UTC by v0dro

Fix for https://github.com/pytorch/pytorch/issues/25810

Basically moves the error checking from the device-specific function to the native function.

2019-10-18 14:59 UTC, ezyang requested changes
I don't think this is right. the `_out` variant may be called directly if you say `torch.linspace(..., out=...)`. Tests would demonstrate this

2019-10-18 23:31 UTC, v0dro commented
Ah my bad. So the correct way would be not delete the lines in the `_out` variants right? Is the rest okay?

2019-10-19 03:37 UTC, v0dro commented
Fixed.

2019-10-20 15:02 UTC, ezyang approved these changes

2019-10-21 20:03 UTC, closed without merging