RFC: Add index_max to pytorch
pytorch/pytorch pull request #28372
Opened 2019-10-21 18:05 UTC by ggoossen

Summary:
Add index_max to pytorch.
This is basically copying everything for index_add (indexAdd) and replacing add with max.

I only added support for floats, if this is the right approch to add index_max we can easily add the other types by just creating the corresponding atomicMax functions.

Test Plan: Used in model in graph attention network, has the same results on toy examples as python implementation I had before.

Differential Revision: D18039379

2019-10-21 22:28 UTC, vadimkantorov commented
On a side note, many such operations are useful, index_mul, index_logical_and, index_logical_or etc. In general for any monoid operation it makes sense (if we get some generic treatment like NumPy ufuncs)

2019-10-21 23:23 UTC, ngimel commented
Reusing index_add implementations is generally a good idea, but I would prefer
1) using this opportunity to move indexAdd to aten
2) refactoring the code in a way that does not require lots of copy-paste in order to support different monoid operations as requested in the comment above. Templating on functions should do it.

2019-10-22 00:42 UTC, ezyang requested changes
This diff adds new TH code, making it a hard NACK from me. Write it as an ATen native function. If you need help understanding how to translate code in the new world look at https://github.com/pytorch/pytorch/wiki/TH-to-ATen-porting-guide

2019-10-22 16:04 UTC, ggoossen commented
Thanks @ezyang / @ngimel
I started migrating index_add to ATen in #28421 
And indeed the amount of copy-paste is a bit much, and I'll look at templating functions after the aten migration.

2019-10-24 19:41 UTC, ggoossen commented
Changing to first migrate to ATen and then implement it again using more code reuse.

2019-10-24 19:41 UTC, closed without merging