Add support for negative index to ArrayRef `operator[]` and `at()`
pytorch/pytorch pull request #28391
Opened 2019-10-21 22:31 UTC by yf225

This PR adds support for negative index to ArrayRef `operator[]` and `at()`, so that we can write the following logic:
```cpp
input = torch::cat({input, input.narrow(2, 0, padding[-1])}, /*dim=*/2);
```
instead of
```cpp
input = torch::cat({input, input.narrow(2, 0, padding[(-1 + padding.size())])}, /*dim=*/2);
```

2019-10-22 15:58 UTC, ezyang commented on c10/util/ArrayRef.h
> +    }
I'm... a little concerned about the performance implications here, as previously operator[] was unchecked and now it is checked. I suppose it is not too dangerous as the prevailing use of ArrayRef for sizes means that you aren't going to do very many accesses (so it's fast), but, if we are going to test for negative, we might as well ALWAYS do bounds checks (and then offer an unsafe fast index option.)

2019-10-22 15:59 UTC, ezyang commented
@dzhulgakov for a second opinion on perf characteristics

2019-10-31 17:06 UTC, gchanan commented
I don't think we should do this:

- the implementation isn't complete --  I would expect `slice` to be able to work with negative indices but that doesn't seem to be the case.

- ArrayRef is a C++ concept that people may be familiar with and is used for a variety of of uses beyond sizes/strides/padding.  We shouldn't be adding our own characteristics and leaving the name the same.

- I could probably be convinced that it's worth adding a "WrappedIntArrayRef" or something that does this for cases we really want to support, but changing ArrayRef globally with no benchmarks is a no-go.

2019-10-31 17:06 UTC, gchanan requested changes
see comment.

2020-01-09 21:14 UTC, closed without merging