Add start_method kwarg to torch.multiprocessing.spawn
pytorch/pytorch pull request #28493
Opened 2019-10-23 05:12 UTC by ailzhang

2019-10-25 19:47 UTC, soumith requested changes
the function itself is `spawn`, so I don't get why this is added

2019-10-26 13:22 UTC, thomasbrandon commented
Might still be WIP but related to [this `torch_xla` issue](https://github.com/pytorch/xla/issues/1217).In notebooks

2019-11-05 01:35 UTC, ailzhang commented
@soumith How about adding a more general API like `create_processes` as shown in the latest commit? 
I also renamed `SpawnContext` to `ProcessContext` since it's not really specific to `spawn`. 
This change will allow environments like jupyter notebook(like Colab) to use torch.multiprocessing as well.

2019-11-05 04:40 UTC, soumith reviewed
I want to give some context about `torch.multiprocessing`. We mirror upstream Python `multiprocessing`'s API, and this is deliberate. The thing we do additionally is that we route the pickling through our custom pickler.

So, if we are changing something like SpawnContext -> ProcessContext, and changing any existing function signatures, @ailzhang please confirm that we are not changing the API signatures of functions that are mirrored from upstream Python `multiprocessing`

2019-11-05 05:00 UTC, SsnL commented on torch/multiprocessing/spawn.py
> +def start_processes(fn, args=(), nprocs=1, join=True, daemon=False, start_method='spawn'):
Is this meant to be public? If so, maybe add doc entries and move the docstring to here?

2019-11-05 19:02 UTC, ailzhang commented
@soumith Hmmm python multiprocessing doesn't have a `.spawn()` function/method. It 's only available as an option in keyword arg `start_method`. Do you know which Python API we are mirroring here?

2019-11-06 20:54 UTC, ailzhang commented
@SsnL @apaszke Could you help confirm whether it's okay to rename `SpawnContext` and the changes in this PR? Thank you!

2019-11-06 21:54 UTC, SsnL commented
@ailzhang Yeah, I think it is fine.

2019-11-06 22:00 UTC, SsnL commented
I think spawncontext was added to be used as a helper for distributed packages. It is not in the python stdlib.

2019-11-06 22:01 UTC, SsnL commented
If start_process is not supposed to be part of a public API, I think this PR is good to go.

2019-11-06 22:14 UTC, ailzhang commented
> If start_process is not supposed to be part of a public API, I think this PR is good to go.

Yep I'm thinking about keep it not documented for now, and XLA will use it mainly for colab training for 8TPU cores. If it gets popular we can refine and add documentation to make it public?

2019-11-07 00:45 UTC, ssnl approved these changes

2019-12-02 18:49 UTC, ssnl approved these changes
LGTM!

2019-12-03 18:39 UTC, closed without merging