Specify the device when wrap a scalar as a tensor for binary ops
pytorch/pytorch pull request #28534
Opened 2019-10-23 19:38 UTC by xuhdev

The default device of scalar_to_tensor is CPU. This causes CI failure in #25665

2019-10-23 22:12 UTC, ailzhang reviewed
Changes make sense to me... Although I'm curious why CUDA didn't error out hmmm

2019-10-23 22:17 UTC, xuhdev commented
@ailzhang It also puzzled me. This didn't break add, sub, mul, div, but breaks bitwise_xor XD

2019-10-24 14:56 UTC, ezyang requested changes
I don't think this is correct. If I do an addition with a tensor (on gpu) and a scalar (on cpu), I shouldn't do a transfer of the scalar to gpu, and then run a gpu kernel: the scalar should be passed along with the launch arguments of the add kernel so I only need to do one gpu computation.

2019-10-24 18:23 UTC, xuhdev commented
@ezyang Would that require rewriting Tensor - Scalar add/sub/mul/div then? I'm wondering how much benefit it will bring, because we are transferring one single scalar for a whole addition operation. But we do need to make changes, I think I'll create another PR to handle that case specifically.

2019-10-24 20:07 UTC, xuhdev commented
I'm actually now more confused. A bit of experimenting shows that, when I call `torch.add(a, 2)` (where `a=torch.ones(10)`), the entry seems to be

    Tensor add(const Tensor& self, const Tensor& other, Scalar alpha)

That means, the following scalar version function is not called:

    Tensor add(const Tensor& self, Scalar other, Scalar alpha)

But `torch.pow(a, 2)` will call the scalar version of pow:

    Tensor pow(const Tensor& base, Scalar exp)

Do you have any idea why this is happening?

2019-10-24 21:08 UTC, ailzhang commented
@xuhdev  Oh I see, so there are two source of conversion from number to tensors. 
For python number, it goes through `torch/csrc/autograd/generated/python_variable_methods.cpp`. you'll see for `THPVariable_add` it only parse to `Tensor other`, which means python number is converted to a `Tensor` instead of `Scalar` here. 
For cpp frontend, users would usually write `torch::Scalar` and then that will go through the `add(Tensor, Scalar)` and `wrap_scalar_tensor` to call `add(Tensor, Tensor)`. 
This is my understanding from talking to people/reading the code. 
And for `pow(Tensor, Scalar)` we do parse it first as `Scalar` and it goes through `pow_out(Tensor, Scalar...)` and `native::pow_out(Tensor, Tensor)`.  
Hope this helps :P 
cc: @gchanan this is the one I mentioned we have multiple ways of handling scalars in our codebase.

2019-10-24 22:04 UTC, xuhdev commented
Thanks, it helps. I guess we "correct" the entry point then? At least we'll make C++ and Python on the same page.

2019-10-25 13:59 UTC, ezyang commented
Yes, what I am thinking is that calls from Python should go through the Scalar overload. I think @ngimel would agree.

2019-10-25 14:58 UTC, ngimel commented
I agree with @ezyang's last point but please please please don't send cpu scalars to gpu, it's a significant performance drag (we've seen 20% end-to-end) that takes a lot of time to diagnose and fix.

2019-10-25 17:09 UTC, ezyang commented
> please don't send cpu scalars to gpu

Just to double check we're on the same page, you're referring to a cpu scalar *tensor*, which then gets transferred to gpu ala `scalar.cuda()`

2019-11-04 22:42 UTC, xuhdev commented
OK, closing now.

2019-11-04 22:42 UTC, closed without merging