Fix for torch.save not saving source files
pytorch/pytorch pull request #28642
Opened 2019-10-25 06:53 UTC by chauhang

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Summary: Fixed the reference to correct object

Test Plan:
Verified by running the sample test case to see file getting saved with no errors or warnings
import torch
m = torch.nn.Linear(500, 10)
torch.save(m, './test.pth')

Reviewers: vincentqb

Subscribers: gchauhan

Tasks:

Tags:

Fix for torch.save not saving file

Fix for torch.save not working

2019-10-25 14:51 UTC, vincentqb commented
Thanks for looking into this! Some tests are failing, and they seem related:
```
Oct 25 01:08:35 test_zeros_like_cpu (__main__.TestTorchDeviceTypeCPU) ... ok
Oct 25 01:08:35 
Oct 25 01:08:35 ======================================================================
Oct 25 01:08:35 FAIL: test_serialization_container (__main__.TestTorch)
Oct 25 01:08:35 ----------------------------------------------------------------------
Oct 25 01:08:35 Traceback (most recent call last):
Oct 25 01:08:35   File "test_torch.py", line 4162, in test_serialization_container
Oct 25 01:08:35     self._test_serialization_container('file', tempfile.NamedTemporaryFile)
Oct 25 01:08:35   File "test_torch.py", line 4148, in _test_serialization_container
Oct 25 01:08:35     self.assertEquals(len(w), 0)
Oct 25 01:08:35 AssertionError: 2 != 0
Oct 25 01:08:35 
Oct 25 01:08:35 ======================================================================
Oct 25 01:08:35 FAIL: test_serialization_container_filelike (__main__.TestTorch)
Oct 25 01:08:35 ----------------------------------------------------------------------
Oct 25 01:08:35 Traceback (most recent call last):
Oct 25 01:08:35   File "test_torch.py", line 4165, in test_serialization_container_filelike
Oct 25 01:08:35     self._test_serialization_container('filelike', BytesIOContext)
Oct 25 01:08:35   File "test_torch.py", line 4148, in _test_serialization_container
Oct 25 01:08:35     self.assertEquals(len(w), 0)
Oct 25 01:08:35 AssertionError: 2 != 0
Oct 25 01:08:35 
Oct 25 01:08:35 ----------------------------------------------------------------------
Oct 25 01:08:35 Ran 591 tests in 109.759s
Oct 25 01:08:35 
Oct 25 01:08:35 FAILED (failures=2, skipped=34)
Oct 25 01:08:36 Traceback (most recent call last):
Oct 25 01:08:36   File "test/run_test.py", line 455, in <module>
Oct 25 01:08:36     main()
Oct 25 01:08:36   File "test/run_test.py", line 447, in main
Oct 25 01:08:36     raise RuntimeError(message)
Oct 25 01:08:36 RuntimeError: test_torch failed!
```

Depending on the updates needed on the existing tests, we may want to add a new test for this change.

2019-10-25 14:53 UTC, vincentqb requested changes
Thanks for looking into this! Some tests are failing, and they seem related:
```
Oct 25 01:08:35 test_zeros_like_cpu (__main__.TestTorchDeviceTypeCPU) ... ok
Oct 25 01:08:35 
Oct 25 01:08:35 ======================================================================
Oct 25 01:08:35 FAIL: test_serialization_container (__main__.TestTorch)
Oct 25 01:08:35 ----------------------------------------------------------------------
Oct 25 01:08:35 Traceback (most recent call last):
Oct 25 01:08:35   File "test_torch.py", line 4162, in test_serialization_container
Oct 25 01:08:35     self._test_serialization_container('file', tempfile.NamedTemporaryFile)
Oct 25 01:08:35   File "test_torch.py", line 4148, in _test_serialization_container
Oct 25 01:08:35     self.assertEquals(len(w), 0)
Oct 25 01:08:35 AssertionError: 2 != 0
Oct 25 01:08:35 
Oct 25 01:08:35 ======================================================================
Oct 25 01:08:35 FAIL: test_serialization_container_filelike (__main__.TestTorch)
Oct 25 01:08:35 ----------------------------------------------------------------------
Oct 25 01:08:35 Traceback (most recent call last):
Oct 25 01:08:35   File "test_torch.py", line 4165, in test_serialization_container_filelike
Oct 25 01:08:35     self._test_serialization_container('filelike', BytesIOContext)
Oct 25 01:08:35   File "test_torch.py", line 4148, in _test_serialization_container
Oct 25 01:08:35     self.assertEquals(len(w), 0)
Oct 25 01:08:35 AssertionError: 2 != 0
Oct 25 01:08:35 
Oct 25 01:08:35 ----------------------------------------------------------------------
Oct 25 01:08:35 Ran 591 tests in 109.759s
Oct 25 01:08:35 
Oct 25 01:08:35 FAILED (failures=2, skipped=34)
Oct 25 01:08:36 Traceback (most recent call last):
Oct 25 01:08:36   File "test/run_test.py", line 455, in <module>
Oct 25 01:08:36     main()
Oct 25 01:08:36   File "test/run_test.py", line 447, in main
Oct 25 01:08:36     raise RuntimeError(message)
Oct 25 01:08:36 RuntimeError: test_torch failed!
```

Depending on the updates needed on the existing tests, we may want to add a new test for this change.

2019-10-28 16:59 UTC, zou3519 commented on torch/serialization.py
> +                source = ''.join(source_file)
Shouldn't this be `''.join(source_lines)`?

2019-10-31 18:14 UTC, chauhang commented
Replacing with https://github.com/pytorch/pytorch/pull/28965

2019-10-31 18:14 UTC, closed without merging