argmax for half datatype fix
pytorch/pytorch pull request #28706
Opened 2019-10-25 20:44 UTC by pbelevich

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2019-10-27 17:12 UTC, peterbell10 approved these changes
Looks good, just a minor comment.

2019-10-27 17:12 UTC, peterbell10 commented on aten/src/THC/THCDeviceUtils.cuh
> +__device__ __forceinline__ c10::Half WARP_SHFL_DOWN<c10::Half>(c10::Half value, unsigned int delta, int width, unsigned int mask)
Why is this a template specialisation and not just a function overload?

2019-10-27 19:28 UTC, ngimel requested changes
Rather than adding `is_nan` and `warp_shfl_down` for halfs, I'd prefer to convert halfs to float on read, and do all the operations in float, like it's done for other reductions. While it does not matter for max operation, adding `shfl_down` for halfs will make it easy to overlook incorrect reduction unexpectedly truncating intermediate values to half in cases where it does matter (sums, products, norms etc). The implementation would look similar to other reductions, I checked that it compiles, but feel free to also template `*_impl` on the comparison functor:
```
template <typename scalar_t, typename acc_t=scalar_t>
void argmax_kernel_cuda_impl(TensorIterator& iter) {
  gpu_reduce_kernel<scalar_t, int64_t>(
    iter, 
    ArgMaxOps<acc_t>{},
    thrust::pair<scalar_t, int64_t>(at::numeric_limits<scalar_t>::lower_bound(), 0));
};
  
template <typename scalar_t, typename acc_t=scalar_t>
void argmin_kernel_cuda_impl(TensorIterator& iter) {
  gpu_reduce_kernel<scalar_t, int64_t>(
    iter, 
    ArgMinOps<acc_t>{},
    thrust::pair<scalar_t, int64_t>(at::numeric_limits<scalar_t>::lower_bound(), 0));
};

void argmax_kernel_cuda(TensorIterator& iter) {
  if (iter.dtype() == kHalf) {
    return argmax_kernel_cuda_impl<at::Half, float>(iter);
  } 
  AT_DISPATCH_ALL_TYPES(iter.dtype(), "argmax_cuda", [&]() {
    argmax_kernel_cuda_impl<scalar_t>(iter);
  });
}

void argmin_kernel_cuda(TensorIterator& iter) {
  if (iter.dtype() == kHalf) {
    return argmin_kernel_cuda_impl<at::Half, float>(iter);
  } 
  AT_DISPATCH_ALL_TYPES(iter.dtype(), "argmin_cuda", [&]() {
    argmin_kernel_cuda_impl<scalar_t>(iter);
  });
}
```

2019-10-27 19:30 UTC, ngimel commented
I've also noticed, while we are at it, that `min_values/max_values` are not dispatched for half. It seems those functions are only accessible from C++, and I don't know how widely they are used in C++ frontend if at all, but probably it would make sense to fix that also?

2019-10-28 15:50 UTC, gchanan commented
> I've also noticed, while we are at it, that min_values/max_values are not dispatched for half. It seems those functions are only accessible from C++, and I don't know how widely they are used in C++ frontend if at all, but probably it would make sense to fix that also?

Yes, it would make sense to fix these.  @pbelevich can you file an issue?

2019-10-28 15:59 UTC, gchanan commented
> Rather than adding is_nan and warp_shfl_down for halfs, I'd prefer to convert halfs to float on read, and do all the operations in float, like it's done for other reductions. While it does not matter for max operation, adding shfl_down for halfs will make it easy to overlook incorrect reduction unexpectedly truncating intermediate values to half in cases where it does matter (sums, products, norms etc). The implementation would look similar to other reductions, I checked that it compiles, but feel free to also template *_impl on the comparison functor:

@ngimel: I'd like to get this fix in ASAP since this is a regression from our previous release.  Your changes look pretty easy to apply (correct me if I'm wrong).  Otherwise we can just do something like go back to the old implementation where we ran `max` for `argmax`.

2019-10-28 16:03 UTC, ngimel commented
Yes, they are easy to apply, I've just basically posted the full (untested) diff, only one file is affected.  Do you want me to open a new PR, or can @pbelevich do it?

2019-10-28 18:17 UTC, pbelevich commented
https://github.com/pytorch/pytorch/pull/28787

2019-10-28 20:05 UTC, closed without merging