[fixing cuda launch config failure on UpSampleNearest]
pytorch/pytorch pull request #28927
Opened 2019-10-30 21:56 UTC by jjsjann123

This is to fix #22526 

Adding limitation on launch config for grid sizes as well, previous code is asking to launch blocks more than what's supported by the hardware;
Test added in test_cuda;

2019-10-31 04:50 UTC, soumith approved these changes

2019-10-31 05:23 UTC, ngimel requested changes
Please make sure that if you are limiting the grid dimensions, you are handling it correctly in the kernel.  I've flagged 2 places where you are not doing that, there are likely others. Also, you've added a single test that's not testing everything you changed, and it is also not testing correctness, just that you are not erroring out. That's the wrong kind of test to find silent wrong answers.

2019-10-31 05:23 UTC, ngimel commented on aten/src/ATen/native/cuda/UpSampleNearest2d.cu
> +      maxGridSize[1], cuda::ATenCeilDiv(output_height, block_y));
Granted, your grid_y and especially grid_x are very unlikely to be more than maxGridSize, but if they ever are, you don't have a loop in the kernel to handle that, so better error out. 
Also, if your grid_x is ever more than maxGridSize[0] (which is 2**31), you'll overflow in your offset computation which uses `int` type.

2019-10-31 05:23 UTC, ngimel commented on aten/src/ATen/native/cuda/UpSampleNearest2d.cu
> +      cuda::ATenCeilDiv(n, bdim.x))};
same here, you are not handling it correctly in the kernel, so don't truncate grid dim here just to silently produce wrong results

2019-10-31 07:30 UTC, jjsjann123 commented
@ngimel good catch!

Let me take a better look tomorrow to make sure it errors out in cases where the kernel would otherwise produce wrong results.

2019-10-31 08:01 UTC, closed without merging

2019-10-31 14:48 UTC, soumith commented
okay I'm reverting the PR, sorry. I'll wait for a new PR with changes that Natalia asked for.

2019-11-01 21:26 UTC, zhanwenchen commented
Any update?

2019-11-01 21:38 UTC, ngimel commented
#29016