enable fast path for TensorIterator for contiguous inputs/no broadcast
pytorch/pytorch pull request #29180
Opened 2019-11-05 03:19 UTC by ngimel

As title. Also, replaces output allocation by `empty` instead of `empty_strided` in the regular path when possible, thus avoiding resizing of outputs and taking additional DeviceGuard for that. 
Test plan: covered by existing tests

2019-11-05 17:56 UTC, VitalyFedyunin requested changes

2019-11-05 17:58 UTC, VitalyFedyunin commented on aten/src/ATen/native/TensorIterator.cpp
> +      if (!op.tensor.is_contiguous()) {
Sorry, I take it back. We need to compare strides too.

2019-11-05 18:08 UTC, ngimel commented on aten/src/ATen/native/TensorIterator.cpp
> +      bool inverted = true;
It is noticeable, see @zou3519 's PR doing the same to at::empty https://github.com/pytorch/pytorch/pull/13785

2019-11-06 20:58 UTC, ngimel commented
Benchmarks on fbcode, times in microseconds

```
                        This PR      Before
a+b, out of place, 1D | 1.22       | 1.37
a+b, in-place 1D      | 0.83       | 0.85
a+b, out of place, 3D | 1.23       | 1.59
a+b, in-place, 3D     | 0.83       | 0.98
```
The benchmark is here https://gist.github.com/ngimel/001bbe2fe2263f2084ae6aad87763b32

2019-11-06 21:22 UTC, VitalyFedyunin approved these changes

2019-11-08 00:23 UTC, closed without merging