Fix the breaking changes in ONNX PR #58
pytorch/pytorch pull request #2922
Opened 2017-10-01 06:50 UTC by houseroad

(1) Regenerate the nanopb files,
(2) Add ModelProto
(3) Fix the test expect files.

CC: @ezyang

2017-10-01 07:10 UTC, soumith commented
AttributeError: module 'onnx' has no attribute 'ModelProto'

2017-10-01 23:46 UTC, ezyang requested changes
This is great, thank you! There is one improvement that can be made, but besides that, let's get this in!

2017-10-01 23:46 UTC, ezyang commented on torch/csrc/onnx/onnx.h
> +  GraphProto graph;
There is a better way to handle this case, see `Note [Callback for nested messages]` in `torch/csrc/onnx/onnx.options`.

2017-10-01 23:46 UTC, ezyang commented on torch/csrc/onnx/onnx.h
> +  void set_graph() { proto.has_graph = true; proto.graph = graph.proto; }
And then this goes away, and we get an exact API compatibility with the Google Protobuf C++ interface :)

2017-10-02 01:28 UTC, houseroad commented
ModelProto.graph is changed to callback type. Thanks for the information, @ezyang .

2017-10-02 01:47 UTC, ezyang approved these changes

2017-10-02 01:48 UTC, ezyang commented
Looks great, thank you!

2017-10-02 03:09 UTC, merged