Correct topological sorting of declarations.
pytorch/pytorch pull request #29237
Opened 2019-11-05 20:27 UTC by xuhdev

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2019-11-05 22:40 UTC, gchanan commented
description?  What's the problem?

2019-11-05 23:30 UTC, xuhdev commented
@gchanan Updated

2019-11-08 22:14 UTC, VitalyFedyunin commented
Please cleanup test failures and re-add me as reviewer.

2019-11-11 20:18 UTC, gchanan requested changes
I'm a bit confused how this interacts with the stacked PR.

What's the state of world when this goes in but the next one hasn't yet?  (Actually, all three cases would be good to understand, i.e.):
1) now
2) after this
3) after the stack

2019-11-11 20:18 UTC, gchanan commented on tools/autograd/gen_python_functions.py
> +    return [decl for i, decl in reversed(sorted_deps)]
comment.

2019-11-11 21:46 UTC, xuhdev commented
> I'm a bit confused how this interacts with the stacked PR.

After a long time investigation, I have to admit that I probably have mistaken. I write my original thought below, just in case I double mistook myself (Since much of the following is no longer true, I'm a bit confused by the purpose of the changed topological sort):

The stacked PR won't work properly without ordering declarations correctly, because, based on the current ordering, enabling the Scalar version of add/sub/... only adds them to the end of the list of declarations, and thus they are still not called because the tensor version would match first (**this seems not true any more, at least for the current master**). For example, after this PR, the stacked PR would generate in `torch/csrc/autograd/generated/python_torch_functions.cpp`:

```cpp
   static PythonArgParser parser({
    "add(Tensor input, Scalar other, Scalar alpha=1)",
     "add(Tensor input, Scalar alpha, Tensor other, *, Tensor out=None)|deprecated",
     "add(Tensor input, Tensor other, *, Scalar alpha=1, Tensor out=None)",
   }, /*traceable=*/true);
```

Before this PR, the stacked PR would generate

```cpp
   static PythonArgParser parser({
     "add(Tensor input, Scalar alpha, Tensor other, *, Tensor out=None)|deprecated",
     "add(Tensor input, Tensor other, *, Scalar alpha=1, Tensor out=None)",
     "add(Tensor input, Scalar other, Scalar alpha=1)",
   }, /*traceable=*/true);
```

In this order, when `torch.add(torch.tensor([1, 1]), 2)` is called, the second declaration would take effect, instead of the third one (**not true on current master**). I believe this is also the reason we have the topological sort at issue here, according to a comment above the changed lines:

```python
# This function declares a partial order on declarations, and sorts them according
# to its linear extension. This is necessary, because there's some ambiguity in the
# choice of overload, and we want a different order.
```

2019-11-11 21:46 UTC, xuhdev commented
I'm closing this now so as to have a fresh CI run for the stacked PR

2019-11-11 21:46 UTC, closed without merging