[dlpack] Conversion for python tensor <--> dlpack via ATen
pytorch/pytorch pull request #2933
Opened 2017-10-02 20:13 UTC by prigoyal

To make it easy to pass tensors across frameworks for example pytorch <-> dlpack <-> caffe2, I added conversion for ATen tensor to DLpack tensor last week in the main ATen repo. The second step is to add support for converting the python tensors in pytorch to dlpack. This PR does that. I wrote a unit test for it and it runs fine

This PR depends on Updating Aten subtree and PR for that is here https://github.com/pytorch/pytorch/pull/2930

2017-10-02 20:38 UTC, apaszke requested changes
I don't think these functions should be exposed as part of the public API. They're highly unsafe. DLPack has no notion of allocators, which means DLTensors are valid for only as long as the original tensor is alive. If they are going to be public API, we should return a PyCapsule that contains the DLPack tensor as first field AND a regular tensor pointer and has a destructor that decrefs the tensor. If the struct is POD it will still be possible to pass it as a pointer to other libraries, but it will ensure that the tensor is alive as long as someone keeps the reference to capsule alive.

Same applies to conversion in the opposite direction. It should either be internal or clone the data so that it is owned.

2017-10-02 20:38 UTC, apaszke commented on test/common.py
> +TEST_DLPACK = True
There's no need for this if it's always going to be true

2017-10-02 20:48 UTC, ezyang commented
@apaszke I'm confused; it looks like this PR is already using PyCapsule?

2017-10-02 20:54 UTC, prigoyal commented
@apaszke  like @ezyang said, I am returning a PyCapsule object which takes a destructor as well. 
as a next step, I'll work on the memory management as well and for this PR, I can remove exposing the python functions?

2017-10-02 21:01 UTC, apaszke commented
@ezyang It returns a PyCapsule, but this capsule only manages the lifetime of the DLTensor, not torch tensor which actually owns the memory that DLTensor points to.

2017-10-02 21:03 UTC, apaszke commented
To sum up, the DLTensor will have dangling pointers if you keep the capsule alive for longer than the original tensor lives.

2017-10-02 21:23 UTC, prigoyal commented
cc @zdevito

2017-10-03 01:52 UTC, zdevito commented
The problem is deeper than managing the memory of the PyCapsule, because the DLTensor is going to get handed off to another library, which will then hold the view. The PyCapsule will likely die right after the handoff in the common case, so having it manage the lifetime of the tensor ref will not prevent many crashes:
```
c2.from_dlpack(torch.to_dlpack(t))
```
We are working to get a `ManagedDLTensor` that includes a deleter callback so that memory management can be done correctly. Until then, there really isn't a good way to make this crash free.

2017-10-03 06:40 UTC, apaszke commented
@zdevito That's a whole different problem and I can't see how to solve it without modifying dlpack. How external libraries manage lifetimes of memory they get is their problem, but we should never let dlpack capsules have dangling data if we export them. If you need this for testing just make the API private.

2017-10-03 13:33 UTC, soumith commented
we should take the same approach as we took for CUDA multiprocessing Tensors. We need to allow dangling and document it.
I think there's enough clarity in that approach and converting to/from DLPack is niche enough that this is completely okay.

2017-10-03 19:03 UTC, prigoyal commented
can this be merged? the dlpack functions are now private and we can rethink making them public once we have the memory management sorted out 
cc @apaszke @soumith @zdevito

2017-10-04 09:38 UTC, apaszke reviewed
I'm ok with merging this as internal, but note that making `toDLPack` safe is as easy as doing this:
```cpp
struct DLTensorCapsule {
  DLTensor tensor;
  PyObject *object;
};
static_assert(std::type_traits<DLTensorCapsule>::value, "DLTensorCapsule is not POD");

static void DLTensorCapsule_destroy(PyObject *capsule) {
  DLTensorCapsule *capsule = static_cast<DLTensorCapsule*>(PyCapsule_GetPointer(obj, "tensor"));
  PY_DECREF(capsule->object);
  delete capsule;
}

PyObject *THPModule_toDLPack(PyObject*, PyObject *data) {
  ...
  DLTensorCapsule *capsule = new DLTensorCapsule();
  PY_INCREF(data);
  capsule->object = data;
  ...
}
```

2017-10-04 12:27 UTC, prigoyal commented
thanks @apaszke I am working no memory management for dlpack integration separately and will get to this at that time and not in this PR

2017-10-04 12:35 UTC, merged