observer benchmarking
pytorch/pytorch pull request #29508
Opened 2019-11-09 07:36 UTC by z-a-f

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2019-11-11 06:22 UTC, mingzhe09088 commented
Can you rename the test name to qobserver_test.py so it is consistent with other quantized tests?

2019-11-11 06:22 UTC, mingzhe09088 commented on benchmarks/operator_benchmark/pt/observer_test.py
> +
remove this line?

2019-11-12 03:09 UTC, raghuramank100 commented on benchmarks/operator_benchmark/pt/qobserver_test.py
> +    qscheme=[torch.per_tensor_affine, torch.per_tensor_symmetric,
For observers, cross products wont work.  per-channel qconfig only works with per-channel observer for example. I would write this by having one set of configs for per-tensor-quant (HistogramObserver/MinMax/MovingAverage) and another set of configs for per-channel quant (PerChannelMinMax/PerChannelMovingAverage)
We can fix the dtype to be torch.quint8 for all these tests.

2019-11-12 03:09 UTC, raghuramank100 requested changes
We will need to restrict configs so that the tests run, thanks

2019-11-13 07:01 UTC, raghuramank100 approved these changes

2019-11-13 07:28 UTC, closed without merging