Graph-mode quantization for convolution from traced model
pytorch/pytorch pull request #30245
Opened 2019-11-21 19:07 UTC by lly-zero-one

In the PR, we enhance the graph-mode quantization for aten::_convolution, which could be generated from tracing path. There is TODO item here: we need to have quantized version with the extra arguments like transposed, benchmark, and etc.

2019-11-22 01:29 UTC, jerryzh168 commented on torch/csrc/jit/passes/quantization.cpp
> +void insertPrepackUnpackForConvolution(std::shared_ptr<Graph>& graph) {
please change this to replacing `aten::_convolution` to `aten::conv2d` as discussed.

2019-11-22 07:47 UTC, ZolotukhinM requested changes

2019-11-22 07:47 UTC, ZolotukhinM commented on test/test_quantization.py
> +        for trace in [True, False]:
Nit: I'd rather trace and script before the loop and then iterate over two scripted models in the loop, i.e.:
```
traced = torch.jit.trace(conv_model_to_script, self.img_data[0][0])
scripted = torch.jit.script(conv_model_to_script)
for model_under_test in [traced, scripted]:
  ...
```
Also, `result_eager` can be computed once before the loop.

2019-11-22 07:47 UTC, ZolotukhinM commented on torch/csrc/jit/passes/quantization.cpp
> +      "_convolution",
How about we call `replaceConvolutionWithConv2d` in the very beginning, before we even inserted observers? In this case we won't need to extend the special handling of `conv2d` to `_convolution`. For instance, you've already forgotten to update one function: `isBiasOfConvOrLinear`.

2019-11-22 07:47 UTC, ZolotukhinM commented on torch/csrc/jit/passes/quantization.cpp
> +    if (!transposed_value && !benchmark_value && !deterministic_value && cudnn_enabled_value
Please clang-format the PR.

2019-11-22 07:47 UTC, ZolotukhinM commented on torch/csrc/jit/passes/quantization_patterns.h
> -
Nit: please try to avoid unnecessary changes.

2019-11-23 07:49 UTC, ZolotukhinM approved these changes
Looks good, thanks!

2019-11-23 09:25 UTC, closed without merging