Change startTime_ to endTime_ in FutureInfo
pytorch/pytorch pull request #30342
Opened 2019-11-22 21:40 UTC by xush6528

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

This can eliminate the unnecessary calls to getRPCEndTime().

Differential Revision: [D5705624](https://our.internmc.facebook.com/intern/diff/D5705624/)

2019-12-10 19:45 UTC, mrshenli approved these changes
This LGTM! Just have one minor comment on the var name.

2019-12-10 19:45 UTC, mrshenli commented on torch/csrc/distributed/rpc/process_group_agent.h
> +        const std::chrono::milliseconds& endTime_,
remove the trailing underscore from the var name?

2019-12-10 22:17 UTC, rohan-varma approved these changes
Thanks, this is a great enhancement.

2019-12-11 08:41 UTC, pietern requested changes
This piggybacks unrelated changes.

2019-12-11 17:27 UTC, xush6528 commented
@pietern I re-exported. It's gone.

2019-12-11 20:11 UTC, rohan-varma approved these changes
Restamp since the botched merge has been fixed now.

2019-12-11 20:56 UTC, jjlilley commented
fwiw, LGTM, but might need to rebase/reupload, since I believe there was a bad merge earlier. :/

2019-12-11 22:05 UTC, closed without merging