More shape checking for ConvNd
pytorch/pytorch pull request #3052
Opened 2017-10-10 20:03 UTC by SsnL

Provides better error handle and message. Fixes #3039 .

2017-10-10 20:59 UTC, soumith commented
failing basic contbuild (not sure how it compiled for you locally)

2017-10-10 21:02 UTC, SsnL commented
Whoops my bad. Should be compilable now.

2017-10-11 00:50 UTC, killeent commented
At some point we need to figure out how to unify `Conv`, including where the shape-checking logic should rely.

2017-10-11 06:45 UTC, SsnL commented
There's something wrong about my understanding of bias. I'll fix these errors.

2017-10-11 17:41 UTC, SsnL commented
Didn't consider the transpose case :) Now it's fixed.

2017-10-11 21:44 UTC, soumith requested changes

2017-10-11 21:44 UTC, soumith commented on torch/csrc/autograd/functions/convolution.cpp
> +      ss << "Expected " << k << "-dimensional weight for " << k
it's the other way around: "Expected K-dimensional input for K-dimensional weight, but got input of size..."

2017-10-11 21:53 UTC, soumith approved these changes

2017-10-13 14:56 UTC, merged