Added Class-Aware Sampler
pytorch/pytorch pull request #3062
Opened 2017-10-11 04:59 UTC by frombeijingwithlove

Implemented Class-Aware Sampling: https://arxiv.org/abs/1512.05830. Li Shen, Zhouchen Lin, Qingming Huang, Relay Backpropagation for Effective Learning of Deep Convolutional Neural Networks, ECCV 2016

2017-10-14 19:27 UTC, YanWang2014 commented
Great! I am just looking for this.

2018-08-14 21:58 UTC, weiyangfb commented
thoughts on this PR? @fmassa @SsnL

2018-11-13 17:38 UTC, fmassa requested changes
Hi,

Thanks for the PR and sorry for the delay in reviewing it.

While this is a nice addition, it makes assumptions that do not hold for general `Dataset` classes.
For this reason, I think it might be better to submit this PR to [`torchcontrib`](https://github.com/pytorch/contrib).

Thanks!

2018-11-13 17:38 UTC, fmassa commented on torch/utils/data/sampler.py
> +        n_cls = len(data_source.classes)
This makes the assumption that `data_source` has a `classes` field, which is not in general valid

2018-11-13 17:38 UTC, fmassa commented on torch/utils/data/sampler.py
> +        for i, (_, label) in enumerate(data_source.imgs):
Same comment here, `imgs` is not generally an attribute of a `Dataset`.

2018-11-13 17:38 UTC, closed without merging

2020-01-22 08:00 UTC, EaglesKK commented
hi, @fmassa @frombeijingwithlove 
I'm new here, and I was trying to use the ClassAwareSampler, but after I tried `from torchcontrib import ClassAwareSampler` it didn't work, could you tell me how to use it properly? Thanks