Add Layout type and ScalarType
pytorch/pytorch pull request #30694
Opened 2019-12-03 22:12 UTC by charliechen0401

Summary: Creating those two jit types.

Test Plan: Need suggestions on what to add unit/integration tests

Differential Revision: D18792522

2019-12-03 22:32 UTC, smessmer approved these changes

2019-12-03 22:32 UTC, smessmer commented on aten/src/ATen/core/jit_type.h
> +        new ScalarTypeType()); // NOLINT(modernize-make-shared)
let's use `make_shared` here

2019-12-07 01:18 UTC, suo requested changes
Hi, changes to the fundamental JIT type system ought to have a JIT team member reviewing in the loop 😄. I have a few questions:
1. What is the purpose of this change? The PR description has no information.
2. What tests verify that the change is correct? There are no unit tests added in this PR.
Thanks!

2019-12-07 02:13 UTC, smessmer commented
Background: TensorOptions (i.e. ScalarType, Layout, Device, pin_memory) arguments are relevant for dispatch because tensor factories use them to dispatch to different backends. In the unboxed world, this is not an issue, because the c++ type tells you if something was a ScalarType or just an int. But in the boxed world, i.e. in a jit stack, this information is lost and ScalarType values are just stored as Ints in IValue. So the dispatcher needs to get this information from the FunctionSchema instead.

This PR introduces the ability for the FunctionSchema to have the information that the dispatcher needs here.

In my understanding, having these types map to IntType in the function_schema_parser was a hack that wasn't meant to stay anyways and this PR is fixing that hack.

2019-12-07 02:28 UTC, smessmer commented
The lack of test cases is my fault. @charliechen0401 asked me how to test this and I couldn't find the test folders and told him it's ok to test it together with the changes we're planning to stack on top. Can you point to the test folders?

2019-12-09 23:16 UTC, suo commented
Hey, here are a few open questions that we will need to answer before we can merge this:
- Backward compatibility—will existing models be able to load and run with these new changes? I think probably not, because existing models may serialize layout and scalar as ints, and LayoutType/DeviceType should probably not be implicitly convertible from ints by default. We need an upgrade path so that production models do not break.
- Forward compatibility—Will older versions of PyTorch be able to interpret the new types? This is not necessarily a dealbreaker but we need to understand what the behavior is here.
- Runtime representation—I don't see additions of Layout/Scalar IValue tags, which implies that the runtime representation is an `int`. This will lead to subtle mismatch bugs in the future, because the type of the IValue will not properly reflect the type in the type system.
- Enum-ish behavior—we have a constrained set of "correct" values the a DeviceType instance can take at runtime. How do we specify and enforce this?
- Serialization and deserialization—how do we represent Device/Scalar in the serialized format? What do they look like? If a DeviceType or ScalarType is an attribute/constant of a module, is this fact preserved across save and load?

2019-12-10 19:26 UTC, charliechen0401 commented
After discussing with @suo offline, we agreed on doing the following step by step:
Step 1: Introducing new type like ScalarTypeType and LayoutType but not using them in any place at this time. Also to make code looks better, introducing a new Enum base type (which is "Enum-ish behavior" in @suo 's comment above).
Step 2: Updating IValue logic, including "Runtime representation" and "Serialization and deserialization" part in the above comment.
Step 3: Using LayoutType and ScalarTypeType in the real world, and then check with other folks on Backward compatibility issue. Very likely, we will need to do something specific for upgrading path so existing models don't break after the changes. (I don't too much idea now, but we can sync with @suo and others at this point).

cc @smessmer , @suo , @zdevito

2020-11-14 08:37 UTC, zasdfgbnm commented
What is the current state of this? JIT is still using int to represent scalar type https://github.com/pytorch/pytorch/issues/47964. Can I change this behavior?

2022-05-12 03:47 UTC, closed without merging