Fix CPU min_values/max_values initial value bug
pytorch/pytorch pull request #30854
Opened 2019-12-06 02:55 UTC by take-cheeze

Without specifying initial value in `binary_kernel_reduce_vec` it would be `0` which cause unexpected result in min_values/max_values.

2019-12-06 03:56 UTC, take-cheeze commented
Hmm, seems I need to support complex types

2020-02-03 17:24 UTC, ezyang commented
Tentatively assigning review to @ngimel, but let me know if you think someone else should review this

2020-02-04 00:52 UTC, ngimel commented
Can you please rebase and add tests to make sure that min_values/max_values results are as expected?

2020-02-04 00:53 UTC, ngimel requested changes
Can you please rebase and add tests to make sure that min_values/max_values results are as expected?

2020-02-04 21:37 UTC, kostmo commented
## :pill: CircleCI build failures summary and remediations
As of commit 345f52c8:


* **9/9** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=345f52c83b6d40ca54ede9ebf097e1d80c8b0846).

### :detective: 9 new failures recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [![See CircleCI build](https://avatars0.githubusercontent.com/ml/7?s=12)](https://circleci.com/gh/pytorch/pytorch/4414514) pytorch_linux_xenial_py3_clang5_mobile_build (1/9)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=95202242) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=95202242))
<details>
<summary>
<code>native/cpu/ReduceOpsKernel.cpp.DEFAULT.cpp:190:30: error: no matching function for call to 'binary_kernel_reduce_vec(at::TensorIterator&, at::native::{anonymous}::max_values_kernel_impl(at::TensorIterator&)::<lambda()>::<lambda()>::<lambda(scalar_t, scalar_t)>, at::native::{anonymous}::max_values_kernel_impl(at::TensorIterator&)::<lambda()>::<lambda()>::<lambda(at::vec256::{anonymous}::Vec256<std::complex<double> >, at::vec256::{anonymous}::Vec256<std::complex<double> >)>, std::complex<double>)'</code>
</summary>

```
Feb 04 21:33:47 /var/lib/jenkins/workspace/build_mobile/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.DEFAULT.cpp:190:28: note:   cannot convert 'at::native::{anonymous}::lower_bound<std::complex<float> >()' (type 'std::complex<float>') to type 'double' 
Feb 04 21:33:47        lower_bound<scalar_t>()); 
Feb 04 21:33:47                             ^ 
Feb 04 21:33:47 /var/lib/jenkins/workspace/aten/src/ATen/Dispatch.h:12:12: note: in definition of macro 'AT_PRIVATE_CASE_TYPE' 
Feb 04 21:33:47      return __VA_ARGS__();                          \ 
Feb 04 21:33:47             ^ 
Feb 04 21:33:47 /var/lib/jenkins/workspace/build_mobile/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.DEFAULT.cpp:185:3: note: in expansion of macro 'AT_DISPATCH_ALL_TYPES_AND_COMPLEX' 
Feb 04 21:33:47    AT_DISPATCH_ALL_TYPES_AND_COMPLEX(iter.dtype(), "max_values_cpu", [&iter] { 
Feb 04 21:33:47    ^ 
Feb 04 21:33:47 /var/lib/jenkins/workspace/build_mobile/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.DEFAULT.cpp: In lambda function: 
ative/cpu/ReduceOpsKernel.cpp.DEFAULT.cpp:190:30: error: no matching function for call to 'binary_kernel_reduce_vec(at::TensorIterator&, at::native::{anonymous}::max_values_kernel_impl(at::TensorIterator&)::<lambda()>::<lambda()>::<lambda(scalar_t, scalar_t)>, at::native::{anonymous}::max_values_kernel_impl(at::TensorIterator&)::<lambda()>::<lambda()>::<lambda(at::vec256::{anonymous}::Vec256<std::complex<double> >, at::vec256::{anonymous}::Vec256<std::complex<double> >)>, std::complex<double>)' 
Feb 04 21:33:47        lower_bound<scalar_t>()); 
Feb 04 21:33:47                               ^ 
Feb 04 21:33:47 /var/lib/jenkins/workspace/aten/src/ATen/Dispatch.h:12:12: note: in definition of macro 'AT_PRIVATE_CASE_TYPE' 
Feb 04 21:33:47      return __VA_ARGS__();                          \ 
Feb 04 21:33:47             ^ 
Feb 04 21:33:47 /var/lib/jenkins/workspace/build_mobile/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.DEFAULT.cpp:185:3: note: in expansion of macro 'AT_DISPATCH_ALL_TYPES_AND_COMPLEX' 
Feb 04 21:33:47    AT_DISPATCH_ALL_TYPES_AND_COMPLEX(iter.dtype(), "max_values_cpu", [&iter] { 
Feb 04 21:33:47    ^ 
Feb 04 21:33:47 In file included from /var/lib/jenkins/workspace/build_mobile/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.DEFAULT.cpp:11:0: 
Feb 04 21:33:47 /var/lib/jenkins/workspace/aten/src/ATen/native/cpu/Reduce.h:247:6: note: candidate: template<class func_t, class vec_func_t> void at::native::{anonymous}::binary_kernel_reduce_vec(at::TensorIterator&, func_t, vec_func_t, double) 
```

</details>

#### [![See CircleCI build](https://avatars0.githubusercontent.com/ml/7?s=12)](https://circleci.com/gh/pytorch/pytorch/4414523) caffe2_onnx_py2_gcc5_ubuntu16_04_build (2/9)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=95202690) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=95202690))
<details>
<summary>
<code>Ten/native/cpu/ReduceOpsKernel.cpp.AVX.cpp:190:30: error: no matching function for call to 'binary_kernel_reduce_vec(at::TensorIterator&, at::native::{anonymous}::max_values_kernel_impl(at::TensorIterator&)::<lambda()>::<lambda()>::<lambda(scalar_t, scalar_t)>, at::native::{anonymous}::max_values_kernel_impl(at::TensorIterator&)::<lambda()>::<lambda()>::<lambda(at::vec256::{anonymous}::Vec256<std::complex<double> >, at::vec256::{anonymous}::Vec256<std::complex<double> >)>, std::complex<double>)'</code>
</summary>

```
Feb 04 21:34:04 /var/lib/jenkins/workspace/build/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.AVX.cpp:190:28: note:   cannot convert 'at::native::{anonymous}::lower_bound<std::complex<float> >()' (type 'std::complex<float>') to type 'double' 
Feb 04 21:34:04        lower_bound<scalar_t>()); 
Feb 04 21:34:04                             ^ 
Feb 04 21:34:04 /var/lib/jenkins/workspace/aten/src/ATen/Dispatch.h:12:12: note: in definition of macro 'AT_PRIVATE_CASE_TYPE' 
Feb 04 21:34:04      return __VA_ARGS__();                          \ 
Feb 04 21:34:04             ^ 
Feb 04 21:34:04 /var/lib/jenkins/workspace/build/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.AVX.cpp:185:3: note: in expansion of macro 'AT_DISPATCH_ALL_TYPES_AND_COMPLEX' 
Feb 04 21:34:04    AT_DISPATCH_ALL_TYPES_AND_COMPLEX(iter.dtype(), "max_values_cpu", [&iter] { 
Feb 04 21:34:04    ^ 
Feb 04 21:34:04 /var/lib/jenkins/workspace/build/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.AVX.cpp: In lambda function: 
en/native/cpu/ReduceOpsKernel.cpp.AVX.cpp:190:30: error: no matching function for call to 'binary_kernel_reduce_vec(at::TensorIterator&, at::native::{anonymous}::max_values_kernel_impl(at::TensorIterator&)::<lambda()>::<lambda()>::<lambda(scalar_t, scalar_t)>, at::native::{anonymous}::max_values_kernel_impl(at::TensorIterator&)::<lambda()>::<lambda()>::<lambda(at::vec256::{anonymous}::Vec256<std::complex<double> >, at::vec256::{anonymous}::Vec256<std::complex<double> >)>, std::complex<double>)' 
Feb 04 21:34:04        lower_bound<scalar_t>()); 
Feb 04 21:34:04                               ^ 
Feb 04 21:34:04 /var/lib/jenkins/workspace/aten/src/ATen/Dispatch.h:12:12: note: in definition of macro 'AT_PRIVATE_CASE_TYPE' 
Feb 04 21:34:04      return __VA_ARGS__();                          \ 
Feb 04 21:34:04             ^ 
Feb 04 21:34:04 /var/lib/jenkins/workspace/build/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.AVX.cpp:185:3: note: in expansion of macro 'AT_DISPATCH_ALL_TYPES_AND_COMPLEX' 
Feb 04 21:34:04    AT_DISPATCH_ALL_TYPES_AND_COMPLEX(iter.dtype(), "max_values_cpu", [&iter] { 
Feb 04 21:34:04    ^ 
Feb 04 21:34:04 In file included from /var/lib/jenkins/workspace/build/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.AVX.cpp:11:0: 
Feb 04 21:34:04 /var/lib/jenkins/workspace/aten/src/ATen/native/cpu/Reduce.h:247:6: note: candidate: template<class func_t, class vec_func_t> void at::native::{anonymous}::binary_kernel_reduce_vec(at::TensorIterator&, func_t, vec_func_t, double) 
```

</details>

#### [![See CircleCI build](https://avatars0.githubusercontent.com/ml/7?s=12)](https://circleci.com/gh/pytorch/pytorch/4414531) caffe2_onnx_py3_6_clang7_ubuntu16_04_build (3/9)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=95202993) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=95202993))
<details>
<summary>
<code>Feb 04 21:34:19 /var/lib/jenkins/workspace/build/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.AVX.cpp:186:5: error: no matching function for call to 'binary_kernel_reduce_vec'</code>
</summary>

```
Feb 04 21:34:19     ^~~~~~~~~~~~~~~~~~~~~~~~ 
Feb 04 21:34:19 /var/lib/jenkins/w [...]

2020-02-05 09:53 UTC, take-cheeze commented
@ezyang Thank you for re-merging.

@ngimel  
Thanks for the review.
I've added a test to check the output is correct in negative cases.
flake8 check seems to be unrelated to this PR.
Could you please take a look?

2020-02-05 18:10 UTC, ngimel commented
You've added tests that are run on cuda tensors only https://github.com/pytorch/pytorch/pull/30854/files#diff-61da4c73cc05556599dea7f248c1da25L13, and yet your fixes are for cpu. How can these tests be passing? Does it mean that cuda is ok, and bug is present for cpu only? Can you add cpu tests please?

2020-02-06 16:42 UTC, ngimel reviewed
Can you please rebase to clear the test errors that are unrelated to your PR?

2020-02-06 16:42 UTC, ngimel commented on aten/src/ATen/test/reduce_ops_test.cpp
> +      auto a = (at::rand({H, W}, TensorOptions(dev).dtype(kFloat)) * 10).to(dtype);
You can initialize with randint and specify the necessary dtype, that way you won't have to do this awkward multiplication and cast. Also, if you have both positive and negative values in your tensor, you don't need additional tests with .neg

2022-04-12 05:21 UTC, closed without merging