[jit] Fix getConstant
pytorch/pytorch pull request #31012
Opened 2019-12-09 23:32 UTC by jerryzh168

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Summary:
- getConstant should throw when the item is not found
- add another getConstant which takes slot index as argument

Test Plan:
test_class_type.cpp

Reviewers:
suo
Subscribers:

Tasks:

Tags:

2019-12-10 02:41 UTC, suo requested changes
Same note as the other PR: we need `findConstant`.

2019-12-12 05:59 UTC, kostmo commented
## CircleCI build failures summary
As of commit 7d42881:
* **2/2** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=7d42881a71542a6c4e53c0cd3305af3e76eb888a).

### 1 new failure recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [![See CircleCI build](https://avatars0.githubusercontent.com/ml/7?s=12)](https://circleci.com/gh/pytorch/pytorch/3919484) binary_linux_manywheel_3_7mu_cpu_devtoolset7_build (1/1)
**Step:** "Build" ([details](https://dr.pytorch.org/build-details.html?build_id=72954613))
```
Dec 12 05:57:03 [ 79%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/passes/utils/subgraph_utils.cpp.o
Dec 12 05:57:04 [ 79%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/passes/utils/check_alias_annotation.cpp.o
Dec 12 05:57:04 [ 79%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/passes/utils/memory_dag.cpp.o
Dec 12 05:57:04 [ 79%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/passes/quantization.cpp.o
Dec 12 05:57:05 [ 79%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/passes/fuse_linear.cpp.o
Dec 12 05:57:05 [ 79%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/print_handler.cpp.o
Dec 12 05:57:05 [ 79%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/fuser/interface.cpp.o
Dec 12 05:57:06 [ 79%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/register_prim_ops.cpp.o
Dec 12 05:57:06 [ 79%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/register_string_ops.cpp.o
Dec 12 05:57:06 /pytorch/torch/csrc/jit/passes/python_print.cpp: In member function ‘void torch::jit::PythonPrintImpl::printModuleMetadata(const ClassTypePtr&)’:
Dec 12 05:57:06 /pytorch/torch/csrc/jit/passes/python_print.cpp:1263:53: error: ‘struct c10::IValue’ has no member named ‘value’; did you mean ‘IValue’?
Dec 12 05:57:06        const auto& v = moduleType->getConstant(name).value();
Dec 12 05:57:06                                                      ^~~~~
Dec 12 05:57:06                                                      IValue
Dec 12 05:57:07 [ 79%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/register_special_ops.cpp.o
Dec 12 05:57:08 [ 79%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/scope.cpp.o
Dec 12 05:57:10 gmake[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/passes/python_print.cpp.o] Error 1
Dec 12 05:57:10 gmake[2]: *** Waiting for unfinished jobs....
Dec 12 05:57:31 gmake[1]: *** [caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
Dec 12 05:57:31 gmake: *** [all] Error 2
Dec 12 05:57:31 Traceback (most recent call last):
```


---
This comment was automatically generated by [Dr. CI](https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment).
Follow [this link to opt-out](https://dr.pytorch.org/admin/comments-opt-out.html) of these comments for your Pull Requests.


Please report bugs/suggestions on the [GitHub issue tracker](https://github.com/kostmo/circleci-failure-tracker/issues).

2019-12-12 08:04 UTC, suo approved these changes
Accepting but please address inline comments!

2019-12-12 08:04 UTC, suo commented on torch/csrc/jit/script/class_type.cpp
> +  TORCH_INTERNAL_ASSERT(constantNames_.size() == constantValues_.size());
Same comment as the other one; let's re-use `findConstant` instead of duplicating the code.

2019-12-12 08:04 UTC, suo commented on torch/csrc/jit/script/class_type.cpp
> +  TORCH_CHECK(slot < constantValues_.size());
Let's add an error message like the one in the other `getConstant`

2019-12-16 23:44 UTC, zdevito approved these changes

2020-01-04 07:06 UTC, closed without merging