Move exponential to Aten(CPU)
pytorch/pytorch pull request #31621
Opened 2019-12-26 10:09 UTC by XiaobingSuper

@VitalyFedyunin , this PR is about move exponential distribution to Aten.
Benchmark script :
```
import torch
import torch.nn as nn
import time
torch.manual_seed(0)
def _time():
    return time.time()
device = "cpu"
#warm up
for n in [10, 100, 1000]:
    input = torch.randn(128, n, requires_grad=False, device=device)
    for i in range(1000):
        input.exponential_()

for n in [1, 10, 100, 1000]:
    fwd_t = 0
    bwd_t = 0
    input = torch.randn(128, n, requires_grad=False, device=device)
    for i in range(10000):
        t1 = _time()
        input.exponential_()
        t2 = _time()
        fwd_t = fwd_t + (t2 -t1)
    fwd_avg = fwd_t / 10000 * 1000
    print("input size(128, %d) forward time is %.2f (ms)." % (n, fwd_avg))
```
Deviece: skx-8180.
Before:
```
input size(128, 1) forward time is 0.01 (ms).
input size(128, 10) forward time is 0.05 (ms).
input size(128, 100) forward time is 0.53 (ms).
input size(128, 1000) forward time is 5.34 (ms).
```
After:
```
input size(128, 1) forward time is 0.01 (ms).
input size(128, 10) forward time is 0.06 (ms).
input size(128, 100) forward time is 0.57 (ms).
input size(128, 1000) forward time is 5.67 (ms).
```

2019-12-26 12:27 UTC, kostmo commented
## :pill: CircleCI build failures summary and remediations
As of commit d650d9a0:


* **1/1** broken upstream at merge base a54dc87e (see [grid view](https://dr.pytorch.org/master-timeline.html?count=1&sha1=a54dc87e8ebf7634d3fb2f32dd32b73c1a4d095f&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35))
  <details>
  <summary>
  You may want to rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
  ```
  git fetch origin viable/strict
  git rebase --onto viable/strict $(git merge-base origin/master HEAD)
  ```
  If your commit is older than `viable/strict`:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  
* **0/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=d650d9a00e805dd9033eea1fa02aafaec79a67e3).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably caused by upstream breakages:
* [pytorch_linux_xenial_py3_clang5_asan_test](https://dr.pytorch.org/build-details.html?build_id=78662417)



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

2019-12-27 07:16 UTC, XiaobingSuper commented
Will add MKL path to improve the performance.

2019-12-30 06:16 UTC, XiaobingSuper commented
@VitalyFedyunin , MKL path added to improve the performance, please see it.

2019-12-30 06:33 UTC, XiaobingSuper commented
For Exponential distribution, lambda should be a positive numer, see https://en.wikipedia.org/wiki/Exponential_distribution, we should return an error as [numpy](https://docs.scipy.org/doc/numpy-1.9.0/reference/generated/numpy.random.exponential.html)'s doing when lambda is a negative number.

2020-02-03 16:27 UTC, VitalyFedyunin requested changes
Please use `TensorIterator` and `cpu_serial_ketnel` instead of `CPU_tensor_apply1`

2020-02-26 03:22 UTC, closed without merging