Expose RRef.rref_id() API to return a string of RRefId
pytorch/pytorch pull request #31639
Opened 2019-12-26 21:09 UTC by mrshenli

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

The string formart is RRefId.createdOn_ + "_" + RRefId.localId_

2019-12-26 22:04 UTC, zzzwen commented
It will be great if we can override the  "==" operator

2019-12-26 22:13 UTC, mrshenli commented
> It will be great if we can override the "==" operator

Do you mean "rref1==rref2" should return true as long as the RRefid is the same, even if they have different ForkIds?

2019-12-26 22:46 UTC, kostmo commented
## :pill: CircleCI build failures summary and remediations
As of commit 270f67ce:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=270f67cea1a560c6285c465586e57d83fdaf0c68).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [![See CircleCI build](https://avatars0.githubusercontent.com/ml/7?s=12)](https://circleci.com/gh/pytorch/pytorch/4069136) caffe2_onnx_py3_6_clang7_ubuntu16_04_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=78688465) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=78688465))
<details>
<summary>
<code>ore dumped) pytest "${args[@]}" -k 'not (TestOperators and test_full_like) and not (TestOperators and test_zeros_like) and not (TestOperators and test_ones_like) and not (TestModels and test_vgg16) and not (TestModels and test_vgg16_bn) and not (TestModels and test_vgg19) and not (TestModels and test_vgg19_bn)' --ignore "$top_dir/test/onnx/test_pytorch_onnx_onnxruntime.py" --ignore "$top_dir/test/onnx/test_custom_ops.py" --ignore "$top_dir/test/onnx/test_models_onnxruntime.py" "${test_paths[@]}"</code>
</summary>

```
Dec 26 22:45:39   File "/usr/local/lib/python3.6/dist-packages/pluggy/hooks.py", line 286 in __call__ 
Dec 26 22:45:39   File "/usr/local/lib/python3.6/dist-packages/_pytest/main.py", line 237 in _main 
Dec 26 22:45:39   File "/usr/local/lib/python3.6/dist-packages/_pytest/main.py", line 193 in wrap_session 
Dec 26 22:45:39   File "/usr/local/lib/python3.6/dist-packages/_pytest/main.py", line 230 in pytest_cmdline_main 
Dec 26 22:45:39   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 187 in _multicall 
Dec 26 22:45:39   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 86 in <lambda> 
Dec 26 22:45:39   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 92 in _hookexec 
Dec 26 22:45:39   File "/usr/local/lib/python3.6/dist-packages/pluggy/hooks.py", line 286 in __call__ 
Dec 26 22:45:39   File "/usr/local/lib/python3.6/dist-packages/_pytest/config/__init__.py", line 90 in main 
Dec 26 22:45:39   File "/usr/local/bin/pytest", line 11 in <module> 
re dumped) pytest "${args[@]}" -k 'not (TestOperators and test_full_like) and not (TestOperators and test_zeros_like) and not (TestOperators and test_ones_like) and not (TestModels and test_vgg16) and not (TestModels and test_vgg16_bn) and not (TestModels and test_vgg19) and not (TestModels and test_vgg19_bn)' --ignore "$top_dir/test/onnx/test_pytorch_onnx_onnxruntime.py" --ignore "$top_dir/test/onnx/test_custom_ops.py" --ignore "$top_dir/test/onnx/test_models_onnxruntime.py" "${test_paths[@]}" 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

2019-12-27 20:15 UTC, pritamdamania87 commented
Instead of exposing rref_id or supporting the equality operator, can we have an API like `is_sibling(rref1, rref2)` or `rref1.is_sibling(rref2)` (open to a better name :) ), which returns True if they share the same owner rref. I feel the equality operator might not be correct since it would ignore the fork id.

2019-12-27 20:23 UTC, mrshenli commented
> Instead of exposing rref_id or supporting the equality operator, can we have an API like is_sibling(rref1, rref2) or rref1.is_sibling(rref2) (open to a better name :) ), which returns True if they share the same owner rref. I feel the equality operator might not be correct since it would ignore the fork id.

I like this idea. @zzzwen will this be sufficient for your use case?

2020-01-16 02:06 UTC, pritamdamania87 requested changes
Requesting changes since I believe we need some changes here before this is ready for review. @mrshenli could you request review again once this PR is ready to review?

2022-05-12 04:45 UTC, closed without merging