Fixing issue https://github.com/pytorch/pytorch/issues/31515
pytorch/pytorch pull request #31694
Opened 2019-12-30 02:07 UTC by leedtan

Fixing bug to handle cumsum and cumprod with 0 elements, such as non-zero dimensional tensors aggregating over a dimension with 0 length. Previously backprop in this setting caused an exception.

2019-12-30 20:20 UTC, mrshenli requested changes
Thanks for contributing! Some general comments:

1. The title of the PR needs to be more descriptive. This title will be the git commit title. Think from a reader's perspective, what title will make it easier for a reader to understand what this PR is doing.
2. Same applies to the PR description, it will be the commit message.
3. You can add "closes #31515" to the PR description, it will then automatically close the issue when this PR is merged.
4. Make sure you updated the internal diff description and title accordingly as well.

2019-12-30 20:20 UTC, mrshenli commented on test/test_torch.py
> +
Let's verify the dimension of the grad (`integrated .grad`) should match.

2020-01-02 19:04 UTC, leedtan commented on test/test_torch.py
> +        zeroNumelTensor = torch.zeros(2, 0, requires_grad=True)
I copied nearby lines, such as:
        aRes = torch.cumsum(a, 1)
        bRes = torch.cumsum(b, 1)

But if thats the chosen practices, I also see examples a few hundred lines above that are snake_case so I'll make the change 
"
                empty_strided = torch.empty_strided(shape, strides, device=device)
                as_strided = torch.empty(empty_strided.storage().size(),
                                         device=device).as_strided(shape, strides)
"
Should I also replace aRes to a_res?

2020-01-02 19:07 UTC, leedtan commented on test/test_torch.py
> +        integrated = zeroNumelTensor.cumsum(dim=-1).sum()
What do you mean cumsum on a scalar? I'm going to interpret this as "put up more tests" and I will add tests like shape: (2, 1, 4) and shape: (0, 2, 3) and try out cumsum on (0, 1, 2) on all of the above shapes.

2020-01-02 20:21 UTC, mrshenli approved these changes
LGTM! Thanks for fixing!

2020-01-02 20:22 UTC, mrshenli requested changes
Lint failures are real, please address.

2020-01-02 20:51 UTC, kostmo commented
## :pill: CircleCI build failures summary and remediations
As of commit fce6a06b:


**None of the build failures appear to be your fault**.

* **1/1** [broken upstream](https://dr.pytorch.org/master-timeline.html?count=1&sha1=b522a8e1ff8a531c4ac75a3551b99d5b40125cf0&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35) at merge base b522a8e1 since Dec 27
  <details>
  <summary>
  You may want to rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  Since your merge base is older than `viable/strict`, run these commands:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  


---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

2020-01-03 18:17 UTC, closed without merging