Wrap TypeErrors to NotImplemented Errors for Tensor Magic Methods
pytorch/pytorch pull request #31769
Opened 2020-01-02 10:27 UTC by justusschock

Wrapping the following magic methods to return/raise `NotImplementedError` instead of `TypeError` to allow things like `torch.tensor([1]) + my_fancy_class` if `my_fancy_class` implements `__radd__`:

* `__rsub__`
* `__rdiv__`
* `__add__`
* `__radd__`

I have not found any tests related to this return type, so I have not added tests for that. If I should add some, please let me know.

2020-01-02 10:43 UTC, kostmo commented
## :pill: CircleCI build failures summary and remediations
As of commit 5d368816:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=5d368816aea62375f7b0c3db85a98dd5b1ee4ed4).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [![See CircleCI build](https://avatars0.githubusercontent.com/ml/7?s=12)](https://circleci.com/gh/pytorch/pytorch/4097760) pytorch_xla_linux_xenial_py3_6_clang7_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=79204194) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=79204194))
<details>
<summary>
<code>Jan 02 10:34:11 caused by: Connection refused (os error 111)</code>
</summary>

```
Jan 02 10:34:11 +++ eval 'extract_trap_cmd ' 
Jan 02 10:34:11 ++++ extract_trap_cmd 
Jan 02 10:34:11 ++++ printf '%s\n' '' 
Jan 02 10:34:11 +++ printf '%s\n' cleanup 
Jan 02 10:34:11 ++ trap -- ' 
Jan 02 10:34:11 cleanup' EXIT 
Jan 02 10:34:11 ++ which sccache 
Jan 02 10:34:11 ++ sccache --stop-server 
Jan 02 10:34:11 Stopping sccache server... 
Jan 02 10:34:11 error: couldn't connect to server 
Jan 02 10:34:11 caused by: Connection refused (os error 111) 
Jan 02 10:34:11 ++ true 
Jan 02 10:34:11 ++ rm /var/lib/jenkins/sccache_error.log 
Jan 02 10:34:11 rm: cannot remove '/var/lib/jenkins/sccache_error.log': No such file or directory 
Jan 02 10:34:11 ++ true 
Jan 02 10:34:11 ++ SCCACHE_ERROR_LOG=/var/lib/jenkins/sccache_error.log 
Jan 02 10:34:11 ++ SCCACHE_IDLE_TIMEOUT=1200 
Jan 02 10:34:11 ++ RUST_LOG=sccache::server=error 
Jan 02 10:34:11 ++ sccache --start-server 
Jan 02 10:34:11 Starting sccache server... 
Jan 02 10:34:11 ++ sccache --zero-stats 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

2020-01-09 19:28 UTC, zou3519 requested changes
We have tests here:
https://github.com/pytorch/pytorch/issues/26333

It looks like we already support returning NotImplemented from the magic methods that you've listed; see https://github.com/pytorch/pytorch/pull/27423 . Do you know if that is correct?

2020-01-10 09:57 UTC, justusschock commented
yeah, I tried it on the latest release and this did not work. But after I opened this PR, I was told, that this was maybe already fixed on the C++ side (rather than the Python side, where I fixed this). 

Since this seems to be already fixed on master, Should I close this PR?

2020-01-10 15:19 UTC, zou3519 commented
Yeah, it should be in the next release.

2020-01-10 15:55 UTC, closed without merging