Make VC++ version a parametrizable option for Windows CI.
pytorch/pytorch pull request #32043
Opened 2020-01-10 16:09 UTC by ezyang

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

2020-01-10 16:27 UTC, peterjc123 approved these changes

2020-01-10 16:27 UTC, peterjc123 commented on .jenkins/pytorch/win-test-helpers/build_pytorch.bat
> +call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=%VC_VERSION%
Actually, we can make 2017 and BuildTools as parameters too.
`VS_VERSION`: 2017
`VS_PRODUCT`: BuildTools

2020-01-10 17:04 UTC, kostmo commented
## :pill: CircleCI build failures summary and remediations
As of commit 0fb0c616:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=0fb0c616c8597bce77b69c210400c9a18d282ecd).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [![See CircleCI build](https://avatars0.githubusercontent.com/ml/7?s=12)](https://circleci.com/gh/pytorch/pytorch/4201025) pytorch_windows_test2 (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=83222958) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=83222958))
<details>
<summary>
<code>C:\Users\circleci\project\build\win_tmp\build\torch\include\torch/csrc/autograd/custom_function.h(143): error C2872: 'std': ambiguous symbol</code>
</summary>

```
        [ 
            _Ty=int64_t 
        ] 
C:\Users\circleci\project\build\win_tmp\build\torch\include\torch/csrc/autograd/custom_function.h(141): error C2872: 'std': ambiguous symbol 
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\forward_list(20): note: could be 'std' 
C:\Users\circleci\project\build\win_tmp\build\torch\include\torch/csrc/autograd/custom_function.h(141): note: or       'std' 
C:\Users\circleci\project\build\win_tmp\build\torch\include\torch/csrc/autograd/custom_function.h(149): note: see reference to class template instantiation 'torch::autograd::CppNode<T>' being compiled 
C:\Users\circleci\project\build\win_tmp\build\torch\include\torch/csrc/autograd/custom_function.h(142): error C2872: 'std': ambiguous symbol 
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\forward_list(20): note: could be 'std' 
C:\Users\circleci\project\build\win_tmp\build\torch\include\torch/csrc/autograd/custom_function.h(142): note: or       'std' 
C:\Users\circleci\project\build\win_tmp\build\torch\include\torch/csrc/autograd/custom_function.h(143): error C2872: 'std': ambiguous symbol 
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\forward_list(20): note: could be 'std' 
C:\Users\circleci\project\build\win_tmp\build\torch\include\torch/csrc/autograd/custom_function.h(143): note: or       'std' 
C:\Users\circleci\project\build\win_tmp\build\torch\include\torch\csrc\api\include\torch/optim/optimizer.h(83): warning C4251: 'torch::optim::detail::OptimizerBase::parameters_': class 'std::vector<at::Tensor,std::allocator<_Ty>>' needs to have dll-interface to be used by clients of class 'torch::optim::detail::OptimizerBase' 
        with 
        [ 
            _Ty=at::Tensor 
        ] 
C:\Users\circleci\project\build\win_tmp\build\torch\include\ATen/core/TensorBody.h(479): note: see declaration of 'std::vector<at::Tensor,std::allocator<_Ty>>' 
        with 
        [ 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

2020-01-10 17:45 UTC, peterjc123 requested changes

2020-01-10 17:45 UTC, peterjc123 commented on .circleci/verbatim-sources/pytorch-job-specs.yml
> +      VC_VERSION: "14.11"
Looks like you'll need to add them to the test job too.

2020-01-22 14:05 UTC, peterjc123 commented
@ezyang Do you plan to update this?

2020-01-23 15:30 UTC, ezyang commented
Ya, doing so now.

2020-01-24 12:08 UTC, peterjc123 commented
Looks like the change is not working.

2020-01-28 03:22 UTC, peterjc123 commented on .circleci/verbatim-sources/pytorch-job-specs.yml
> -    parameters:
Looks like we will need to keep some of the lines here.

2020-01-29 03:54 UTC, peterjc123 approved these changes

2020-01-29 03:54 UTC, peterjc123 commented
@pytorchbot merge this please

2020-01-29 20:13 UTC, closed without merging