.circleci: Remove Python 2.7 tests
pytorch/pytorch pull request #32310
Opened 2020-01-16 18:58 UTC by seemethere

Python 2.7 was EOL as of January 1, 2020

PyTorch 1.4 was the last release to support Python 2.7

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

2020-01-16 20:39 UTC, kostmo commented
## :pill: CircleCI build failures summary and remediations
As of commit 6944a090:


* **1/1** failures introduced in this PR


---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

2020-01-16 22:00 UTC, seemethere commented
I believe test failures are unrelated to the changes presented in this PR

2020-01-17 23:07 UTC, yns88 commented on .circleci/verbatim-sources/workflows-binary-builds-smoke-subset.yml
>              - setup
Is this intentionally left behind?

2020-01-22 13:19 UTC, ezyang requested changes
This is a really good start.

However, we have to do the hard work of verifying that there isn't any testing that is hardcoded to Python 2, and would be lost if we dropped it this way.  Grepping for py2, I see the following special cases:

```
  if [[ "$BUILD_ENVIRONMENT" == *-xenial-cuda9-cudnn7-py2* ]]; then
    # TODO: move this to Docker
    sudo apt-get -qq update
    sudo apt-get -qq install --allow-downgrades --allow-change-held-packages openmpi-bin libopenmpi-dev
    sudo apt-get -qq install --no-install-recommends openssh-client openssh-server
    sudo mkdir -p /var/run/sshd
  fi
```

So we need to ensure that testing with MPI is still being covered somewhere else.

2020-04-08 17:44 UTC, closed without merging