Migrate  from the TH to Aten (CPU)
pytorch/pytorch pull request #32534
Opened 2020-01-23 15:33 UTC by pbelevich

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2020-01-23 17:09 UTC, kostmo commented
## :pill: CircleCI build failures summary and remediations
As of commit e80fb25a:


**None of the build failures appear to be your fault**.

* **1/1** recognized as flaky :snowflake:
    * Re-run these jobs?


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=e80fb25a7c7ca408e36a01808ed08e163ce5be67).

### :snowflake: 1 failure recognized as flaky
The following build failures have been detected as flaky and **may not be your fault**:
#### [![See CircleCI build](https://avatars0.githubusercontent.com/ml/7?s=12)](https://circleci.com/gh/pytorch/pytorch/4323893) caffe2_onnx_py2_gcc5_ubuntu16_04_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=89859256) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=89859256)) :snowflake:
<details>
<summary>
<code>Jan 23 17:07:00 unknown file: Failure</code>
</summary>

```
Jan 23 17:07:00 [       OK ] TensorIteratorTest.ComparisonLoopBinary_Short (0 ms) 
Jan 23 17:07:00 [ RUN      ] TensorIteratorTest.ComparisonLoopBinary_Int 
Jan 23 17:07:00 [       OK ] TensorIteratorTest.ComparisonLoopBinary_Int (0 ms) 
Jan 23 17:07:00 [ RUN      ] TensorIteratorTest.ComparisonLoopBinary_Long 
Jan 23 17:07:00 [       OK ] TensorIteratorTest.ComparisonLoopBinary_Long (0 ms) 
Jan 23 17:07:00 [ RUN      ] TensorIteratorTest.ComparisonLoopBinary_Float 
Jan 23 17:07:00 [       OK ] TensorIteratorTest.ComparisonLoopBinary_Float (0 ms) 
Jan 23 17:07:00 [ RUN      ] TensorIteratorTest.ComparisonLoopBinary_Double 
Jan 23 17:07:00 [       OK ] TensorIteratorTest.ComparisonLoopBinary_Double (0 ms) 
Jan 23 17:07:00 [ RUN      ] TensorIteratorTest.ComparisonLoopBinary_Bool 
Jan 23 17:07:00 unknown file: Failure 
Jan 23 17:07:00 C++ exception with description "random_ can not accept 'from' and 'to' on boolean tensors (random_ at /var/lib/jenkins/workspace/aten/src/ATen/native/Distributions.cpp:229) 
Jan 23 17:07:00 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7f919edda28a in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libc10.so) 
Jan 23 17:07:00 frame #1: at::native::random_(at::Tensor&, long, long, at::Generator*) + 0x1f8 (0x7f919f9233c8 in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_cpu.so) 
Jan 23 17:07:00 frame #2: <unknown function> + 0xe341a0 (0x7f919fe221a0 in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_cpu.so) 
Jan 23 17:07:00 frame #3: at::Tensor& c10::KernelFunction::callUnboxed<at::Tensor&, at::Tensor&, long, long, at::Generator*>(c10::OperatorHandle const&, at::Tensor&, long, long, at::Generator*) const + 0x5f (0x7f919f990a0f in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_cpu.so) 
Jan 23 17:07:00 frame #4: <unknown function> + 0x27afc71 (0x7f91a179dc71 in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_cpu.so) 
Jan 23 17:07:00 frame #5: at::Tensor& c10::KernelFunction::callUnboxed<at::Tensor&, at::Tensor&, long, long, at::Generator*>(c10::OperatorHandle const&, at::Tensor&, long, long, at::Generator*) const + 0x5f (0x7f919f990a0f in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_cpu.so) 
Jan 23 17:07:00 frame #6: at::native::randint(long, long, c10::ArrayRef<long>, at::Generator*, c10::TensorOptions const&) + 0x116 (0x7f919f986936 in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_cpu.so) 
Jan 23 17:07:00 frame #7: at::native::randint(long, long, c10::ArrayRef<long>, c10::TensorOptions const&) + 0x22 (0x7f919f986b02 in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_cpu.so) 
Jan 23 17:07:00 frame #8: <unknown function> + 0xe4f953 (0x7f919fe3d953 in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_cpu.so) 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

2020-01-24 16:31 UTC, ezyang commented
Gonna let Vitaly handle this one :)

2020-01-27 20:01 UTC, VitalyFedyunin requested changes
Please add benchmark numbers.

2020-02-07 18:43 UTC, VitalyFedyunin commented on aten/src/ATen/native/cpu/DistributionTemplates.h
> +          return generator->random() & 1;
Not sure, but can you please check distribution of booleans in randomly generated tensor

2020-02-10 18:36 UTC, ezyang commented
Adding @anjali411 as complex may be affected by this

2020-02-13 00:11 UTC, pbelevich commented on aten/src/ATen/native/Distributions.cpp
> +  if (to) {
addressed

2020-02-13 18:34 UTC, VitalyFedyunin commented on aten/src/ATen/native/DistributionTemplates.h
> +template<typename scalar_t>
Please inline comment why we have to do it.

2020-02-13 19:22 UTC, VitalyFedyunin reviewed
Please change PR description to reflect why we are adding templates around generator.

2020-02-13 19:22 UTC, VitalyFedyunin commented on aten/src/ATen/native/cpu/DistributionTemplates.h
> +      TORCH_CHECK(false, "random_full_64_range_kernel_cpu handles only int64, double and float");
I think you need to use `TORCH_INTERNAL_ASSERT` here instead.

2020-02-17 19:13 UTC, pbelevich commented
```
import torch

##############################################################

t = torch.empty(1000, dtype=torch.int64, device='cpu')
timeit t.random_()
Before : 8.1 µs ± 29.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
After  : 7.81 µs ± 26.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.int64, device='cpu')
timeit t.random_()
Before : 7.2 ms ± 74.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After  : 6.98 ms ± 17.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

t = torch.empty(1000, dtype=torch.int32, device='cpu')
timeit t.random_()
Before : 4.95 µs ± 19 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
After  : 4.85 µs ± 14.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.int32, device='cpu')
timeit t.random_()
Before : 4.08 ms ± 21.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After  : 4.01 ms ± 17.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

t = torch.empty(1000, dtype=torch.float64, device='cpu')
timeit t.random_()
Before : 9.25 µs ± 223 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
After  : 8.78 µs ± 52.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.float64, device='cpu')
timeit t.random_()
Before : 8.08 ms ± 216 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After  : 7.87 ms ± 13.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

t = torch.empty(1000, dtype=torch.float32, device='cpu')
timeit t.random_()
Before : 6.56 µs ± 192 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
After  : 5.82 µs ± 24.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.float32, device='cpu')
timeit t.random_()
Before : 5.5 ms ± 29 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After  : 4.87 ms ± 18.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each

t = torch.empty(1000, dtype=torch.bool, device='cpu')
timeit t.random_()
Before : 5.44 µs ± 76.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
After  : 4.99 µs ± 21.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.bool, device='cpu')
timeit t.random_()
Before : 4.2 ms ± 68.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After  : 4.1 ms ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

##############################################################

t = torch.empty(1000, dtype=torch.int64, device='cpu')
timeit t.random_(42)
Before : 12.1 µs ± 261 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
After  : 11.7 µs ± 35.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.int64, device='cpu')
timeit t.random_(42)
Before : 10.9 ms ± 26.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After  : 10.8 ms ± 21.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

t = torch.empty(1000, dtype=torch.int32, device='cpu')
timeit t.random_(42)
Before : 12.1 µs ± 333 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
After  : 11.7 µs ± 16.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.int32, device='cpu')
timeit t.random_(42)
Before : 10.9 ms ± 110 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After  : 10.8 ms ± 21.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

t = torch.empty(1000, dtype=torch.float64, device='cpu')
timeit t.random_(42)
Before : 12.2 µs ± 258 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
After  : 11.8 µs ± 35.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.float64, device='cpu')
timeit t.random_(42)
Before : 11 ms ± 229 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After  : 10.8 ms ± 24 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

t = torch.empty(1000, dtype=torch.float32, device='cpu')
timeit t.random_(42)
Before : 12 µs ± 24.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
After  : 12.1 µs ± 34.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.float32, device='cpu')
timeit t.random_(42)
Before : 11.4 ms ± 335 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After  : 11.1 ms ± 21.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

t = torch.empty(1000, dtype=torch.bool, device='cpu')
timeit t.random_(42)
Before : 12.2 µs ± 31.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
After  : 11.7 µs ± 28.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.bool, device='cpu')
timeit t.random_(42)
Before : 11.1 ms ± 23.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After  : 10.8 ms ± 26.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

##############################################################

t = torch.empty(1000, dtype=torch.int64, device='cpu')
timeit t.random_(-42, 42)
Before : 11.9 µs ± 33.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
After  : 11.8 µs ± 36.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.int64, device='cpu')
timeit t.random_(-42, 42)
Before : 11 ms ± 131 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After  : 10.8 ms ± 25.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

t = torch.empty(1000, dtype=torch.int32, device='cpu')
timeit t.random_(-42, 42)
Before : 11.8 µs ± 18 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
After  : 11.8 µs ± 27.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.int32, device='cpu')
timeit t.random_(-42, 42)
Before : 10.8 ms ± 33.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After  : 10.8 ms ± 19.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

t = torch.empty(1000, dtype=torch.float64, device='cpu')
timeit t.random_(-42, 42)
Before : 12 µs ± 83 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
After  : 11.9 µs ± 27.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.float64, device='cpu')
timeit t.random_(-42, 42)
Before : 11.2 ms ± 304 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After  : 10.8 ms ± 20.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

t = torch.empty(1000, dtype=torch.float32, device='cpu')
timeit t.random_(-42, 42)
Before : 12.1 µs ± 35.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
After  : 12.2 µs ± 29 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.float32, device='cpu')
timeit t.random_(-42, 42)
Before : 11.1 ms ± 249 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After  : 11.1 ms ± 34.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

t = torch.empty(1000, dtype=torch.bool, device='cpu')
timeit t.random_(-42, 42)
Before : 12.2 µs ± 35.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
After  : 11.8 µs ± 24.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.bool, device='cpu')
timeit t.random_(-42, 42)
Before : 11.1 ms ± 9.73 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After  : 10.8 ms ± 49.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

##############################################################

t = torch.empty(1000, dtype=torch.int64, device='cpu')
timeit t.random_(torch.iinfo(torch.int64).min, to=None)
Before : N/A
After  : 8.13 µs ± 35.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

t = torch.empty(1000000, dtype=torch.int64, device='cpu')
timeit t.random_(torch.iinfo(torch.int64).min, to=None)
Before : N/A
After  : 6.64 ms ± 20 µs per loop (mean ± std. dev. of 7 runs, 100 loops ea [...]

2020-02-18 19:05 UTC, VitalyFedyunin approved these changes
LGTM with couple buts: 1) Please avoid so big PRs in the future 2) Please update docs as follow-up PR.

2020-02-22 00:15 UTC, closed without merging