min, max: check that operand and outputs are on the same device type
pytorch/pytorch pull request #32862
Opened 2020-01-31 09:29 UTC by Baranowski

Fixes #32001

2020-01-31 10:19 UTC, kostmo commented
## :pill: CircleCI build failures summary and remediations
As of commit 9fabf25b:


**None of the build failures appear to be your fault**.

* **1/1** [broken upstream](https://dr.pytorch.org/master-timeline.html?count=1&sha1=affd598c1fc781919b88aa2efc4a2c1f2d2c96a7&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35) at merge base affd598c since Jan 30
  <details>
  <summary>
  Please rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  Since your merge base is older than `viable/strict`, run these commands:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=9fabf25b51673c6d5979cb814ed0d0a78d0b457f).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably **caused by upstream breakages**:
* [pytorch_linux_xenial_py2_7_9_test](https://dr.pytorch.org/build-details.html?build_id=93687537) from Jan 30 until Jan 30



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

2020-01-31 14:56 UTC, ezyang commented on aten/src/ATen/native/TensorCompare.cpp
> +              "expected device type ", self.device().type(), " but got ",
You should just check that the `device()` are equal, as mixed-device operations won't work on this kernel anyway

2020-01-31 14:56 UTC, ezyang requested changes
LGTM, but let's test `device()`

2020-02-03 15:22 UTC, ezyang approved these changes

2020-02-03 18:18 UTC, closed without merging