Move cumprod to Aten(CPU)
pytorch/pytorch pull request #33280
Opened 2020-02-13 03:27 UTC by XiaobingSuper

This PR is about move cumprod to Aten.
Test script:
```
 import torch
 import torch.nn as nn
 import time

 torch.manual_seed(0)

 def _time():
     return time.time()

 device = "cpu"

 #warm up
 for n in [10, 100]:
     for c in [10, 100]:
         for h in [10, 100]:
             input = torch.randn(n, c, h, requires_grad=False, device=device)
             for dim in range(input.dim()):
                 for i in range(1000):
                     output = input.cumprod(dim)
for n in [10, 100]:
     for c in [10, 100]:
         for h in [10, 100]:
             input = torch.randn(n, c, h, requires_grad=False, device=device)
             for dim in range(input.dim()):
                 fwd_t = 0
                 for i in range(10000):
                     t1 = _time()
                     input.cumprod(dim)
                     t2 = _time()
                     fwd_t = fwd_t + (t2 -t1)
                 fwd_avg = fwd_t / 10000 * 1000
                 print("input size(%d, %d, %d) with reduce dim is %d : forward time is %.4f (ms)." % (n, c, h, dim,      fwd_avg))
```
Test device: **skx-8180**.
Before:
```
input size(10, 10, 10) with reduce dim is 0 : forward time is 0.0117 (ms).
input size(10, 10, 10) with reduce dim is 1 : forward time is 0.0110 (ms).
input size(10, 10, 10) with reduce dim is 2 : forward time is 0.0109 (ms).
input size(10, 10, 100) with reduce dim is 0 : forward time is 0.0742 (ms).
input size(10, 10, 100) with reduce dim is 1 : forward time is 0.0672 (ms).
input size(10, 10, 100) with reduce dim is 2 : forward time is 0.0223 (ms).
input size(10, 100, 10) with reduce dim is 0 : forward time is 0.0714 (ms).
input size(10, 100, 10) with reduce dim is 1 : forward time is 0.0233 (ms).
input size(10, 100, 10) with reduce dim is 2 : forward time is 0.0695 (ms).
input size(10, 100, 100) with reduce dim is 0 : forward time is 0.6805 (ms).
input size(10, 100, 100) with reduce dim is 1 : forward time is 0.1907 (ms).
input size(10, 100, 100) with reduce dim is 2 : forward time is 0.1793 (ms).
input size(100, 10, 10) with reduce dim is 0 : forward time is 0.0241 (ms).
input size(100, 10, 10) with reduce dim is 1 : forward time is 0.0612 (ms).
input size(100, 10, 10) with reduce dim is 2 : forward time is 0.0630 (ms).
input size(100, 10, 100) with reduce dim is 0 : forward time is 0.2150 (ms).
input size(100, 10, 100) with reduce dim is 1 : forward time is 0.5965 (ms).
input size(100, 10, 100) with reduce dim is 2 : forward time is 0.1766 (ms).
input size(100, 100, 10) with reduce dim is 0 : forward time is 0.2235 (ms).
input size(100, 100, 10) with reduce dim is 1 : forward time is 0.1863 (ms).
input size(100, 100, 10) with reduce dim is 2 : forward time is 0.5903 (ms).
input size(100, 100, 100) with reduce dim is 0 : forward time is 4.6726 (ms).
input size(100, 100, 100) with reduce dim is 1 : forward time is 4.7819 (ms).
input size(100, 100, 100) with reduce dim is 2 : forward time is 1.7215 (ms).
```
After:
```
input size(10, 10, 10) with reduce dim is 0 : forward time is 0.0061 (ms).
input size(10, 10, 10) with reduce dim is 1 : forward time is 0.0059 (ms).
input size(10, 10, 10) with reduce dim is 2 : forward time is 0.0058 (ms).
input size(10, 10, 100) with reduce dim is 0 : forward time is 0.0113 (ms).
input size(10, 10, 100) with reduce dim is 1 : forward time is 0.0113 (ms).
input size(10, 10, 100) with reduce dim is 2 : forward time is 0.0151 (ms).
input size(10, 100, 10) with reduce dim is 0 : forward time is 0.0112 (ms).
input size(10, 100, 10) with reduce dim is 1 : forward time is 0.0153 (ms).
input size(10, 100, 10) with reduce dim is 2 : forward time is 0.0106 (ms).
input size(10, 100, 100) with reduce dim is 0 : forward time is 0.0696 (ms).
input size(10, 100, 100) with reduce dim is 1 : forward time is 0.1099 (ms).
input size(10, 100, 100) with reduce dim is 2 : forward time is 0.0301 (ms).
input size(100, 10, 10) with reduce dim is 0 : forward time is 0.0148 (ms).
input size(100, 10, 10) with reduce dim is 1 : forward time is 0.0112 (ms).
input size(100, 10, 10) with reduce dim is 2 : forward time is 0.0103 (ms).
input size(100, 10, 100) with reduce dim is 0 : forward time is 0.1190 (ms).
input size(100, 10, 100) with reduce dim is 1 : forward time is 0.0729 (ms).
input size(100, 10, 100) with reduce dim is 2 : forward time is 0.0294 (ms).
input size(100, 100, 10) with reduce dim is 0 : forward time is 0.1203 (ms).
input size(100, 100, 10) with reduce dim is 1 : forward time is 0.1053 (ms).
input size(100, 100, 10) with reduce dim is 2 : forward time is 0.0250 (ms).
input size(100, 100, 100) with reduce dim is 0 : forward time is 1.2151 (ms).
input size(100, 100, 100) with reduce dim is 1 : forward time is 1.1373 (ms).
input size(100, 100, 100) with reduce dim is 2 : forward time is 0.0443 (ms).
```
Fix https://github.com/pytorch/pytorch/issues/24668.

2020-02-13 06:53 UTC, ngimel commented
cc @anjali411

2020-02-13 07:28 UTC, ngimel commented
#33137 and this generally look good. 
- There's a lot of code repetition between them (the only difference is init value, and + or *), so consider templating. 
- Don't hardcode GRAIN_SIZE, better use internal::GRAIN_SIZE. Since in your case each thread is doing a fair amount of work, GRAIN_SIZE/N/n seems reasonable. 
- Please also provide single-threaded benchmarks (you can use `torch.set_num_threads(1)`)

2020-02-13 12:40 UTC, XiaobingSuper commented
There has a performance issue for cumprod, working in progress.

2020-02-13 21:27 UTC, anjali411 commented on aten/src/ATen/native/ReduceOps.cpp
> +              || (0 == wrap_dim && wrap_dim == self.dim()) , "invaild dim to reduce");
I don't think this check is required. maybe_wrap_dim already does that

2020-02-13 21:33 UTC, anjali411 commented on aten/src/ATen/native/ReduceOps.cpp
> +    result.copy_(self);
'''result.fill_(self)'''

2020-02-13 21:40 UTC, anjali411 commented
I think we should have a general function with equivalent logic to TENSOR_DIM_APPLY2. you can check my PR here where I porter TENSOR_DIM_APPLY3 for cummax, cummin https://github.com/pytorch/pytorch/pull/32537/files it would be nice if you can add your function to the new file I am adding through this PR

2020-02-13 21:41 UTC, anjali411 requested changes
I think we should have a general function with equivalent logic to TENSOR_DIM_APPLY2. you can check my PR here where I porter TENSOR_DIM_APPLY3 for cummax, cummin https://github.com/pytorch/pytorch/pull/32537/files it would be nice if you can add your function to the new file I am adding through this PR

2020-02-14 05:21 UTC, XiaobingSuper commented
@anjali411, @ngimel , @VitalyFedyunin , DIM_APPlY is not be parallelized, it has a bad performance compare with this PR's method even for non_contiguous tensor(amost),  please see the performance of cumsum when input is discontiguous :
**Before:**
```
size = (10, 10, 10); reduce dim=0; compute time is 0.0096(ms)
size = (10, 10, 10); reduce dim=1; compute time is 0.0088(ms)
size = (10, 10, 10); reduce dim=2; compute time is 0.0087(ms)
size = (300, 300, 300); reduce dim=0; compute time is 220.7853(ms)
size = (300, 300, 300); reduce dim=1; compute time is 249.2653(ms)
size = (300, 300, 300); reduce dim=2; compute time is 66.2485(ms)
number_threads =1:
size = (10, 10, 10); reduce dim=0; compute time is 0.0095(ms)
size = (10, 10, 10); reduce dim=1; compute time is 0.0089(ms)
size = (10, 10, 10); reduce dim=2; compute time is 0.0089(ms)
size = (300, 300, 300); reduce dim=0; compute time is 224.9825(ms)
size = (300, 300, 300); reduce dim=1; compute time is 251.4869(ms)
size = (300, 300, 300); reduce dim=2; compute time is 66.5189(ms)
```
After:
```
size = (10, 10, 10); reduce dim=0; compute time is 0.0062(ms)
size = (10, 10, 10); reduce dim=1; compute time is 0.0061(ms)
size = (10, 10, 10); reduce dim=2; compute time is 0.0061(ms)
size = (300, 300, 300); reduce dim=0; compute time is 90.9508(ms)
size = (300, 300, 300); reduce dim=1; compute time is 86.9578(ms)
size = (300, 300, 300); reduce dim=2; compute time is 27.2669(ms)

number_threads =1:
size = (10, 10, 10); reduce dim=0; compute time is 0.0056(ms)
size = (10, 10, 10); reduce dim=1; compute time is 0.0055(ms)
size = (10, 10, 10); reduce dim=2; compute time is 0.0056(ms)
size = (300, 300, 300); reduce dim=0; compute time is 111.3135(ms)
size = (300, 300, 300); reduce dim=1; compute time is 106.2396(ms)
size = (300, 300, 300); reduce dim=2; compute time is 77.9179(ms)
```

2020-02-14 05:35 UTC, ngimel commented
Agreed, you don't need to use dim_apply. Did you fix issues that you have for cumprod performance? If so, then there are small things left to fix
1) add scalar handling before maybe_wrap_dim because maybe_wrap_dim will error out on scalar, and you want to be able to do the following, it is currently supported 
```
a=torch.tensor(1) # create scalar tensor with 0 dims
a.cumprod(dim=0)
```
2) remove TORCH_CHECK on the `wrap_dim` as @anjali411 suggests, it is done by maybe_wrap_dim
3) add a test for cumsum/cumprod on a scalar, apparently it is not tested.

2020-02-15 05:35 UTC, XiaobingSuper commented
Using TensorItereator can get a more performance improvement than parallel_for(will have **~2x** improvement) when dim != input.dim() - 1. TODO: solve the performance degradation for dim == input.dim() - 1.

2020-02-18 16:59 UTC, ngimel commented
@XiaobingSuper what approach are you using with TensorIterator? Is it similar to Scatter/Gather (restriding original tensor so that the stride is 0 for reduced dimension, capturing the op over that dimension in the function that is passed to iterator)? https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cpu/ScatterGatherKernel.cpp. 
If TensorIterator still does not give you performance, you can continue with your original approach, it still offers benefits compared to current implementation. 
Let me know if you need help or when your PR is ready for review.

2020-02-19 01:51 UTC, XiaobingSuper commented
@ngimel, I revert TensorIterator patch, just using original approch now, cumprod still have a performance degradation for single thread case.

2020-02-19 05:42 UTC, ngimel commented
Hm, it's so weird that cumsum and cumprod perf is different, the code is literally the same.

2020-02-20 20:34 UTC, VitalyFedyunin commented on aten/src/ATen/native/ReduceOps.cpp
> +        scalar_t cum_number = init_v;
You might get precision problem here, as original code had accumulator of `accreal` type

2020-02-20 20:34 UTC, VitalyFedyunin commented on aten/src/ATen/native/ReduceOps.cpp
> +static void _cumop_out_cpu_template(Tensor& result, const Tensor& self,
Wild guess, try force inlining, maybe it will solve perf problem.

2020-02-20 20:50 UTC, VitalyFedyunin commented on aten/src/ATen/native/ReduceOps.cpp
> +        scalar_t cum_number = init_v;
Discussed with @ngimel, we are fine using scalar_t here for acc.

2020-02-20 22:16 UTC, VitalyFedyunin commented
I want to support @ngimel 's proposal to have quick path in case of `dim == input.dim()-1` this should remove performance degradation.

2020-02-22 01:10 UTC, ngimel commented
The reason for the slowdown is denormals appearing at the end of the long chain of multiplying numbers less than 1. If the inputs to the benchmark are prepared as 
```
input = torch.rand(n, n, n, requires_grad=False, device=device, dtype=torch.float)
    input = input * 0.01 + 1
```
there's no difference in performance between cumsum and cumprod.

2020-02-22 03:42 UTC, XiaobingSuper commented
> The reason for the slowdown is denormals appearing at the end of the long chain of multiplying numbers less than 1. If the inputs to the benchmark are prepared as
> 
> ```
> input = torch.rand(n, n, n, requires_grad=False, device=device, dtype=torch.float)
>     input = input * 0.01 + 1
> ```
> 
> there's no difference in performance between cumsum and cumprod.

@ngimel , yes, it works. Thanks!

2020-02-24 00:35 UTC, ngimel commented
@XiaobingSuper can you please resolve a conflict?

2020-02-24 08:48 UTC, XiaobingSuper commented
@ngimel, @VitalyFedyunin , C@anjali411, there have some updates:
1. Using TensorIterator as implementation method.
2. Updata performance data.
3. Using acctype to make computation.

2020-02-24 21:34 UTC, VitalyFedyunin approved these changes

2020-02-25 21:05 UTC, closed without merging

2020-04-09 20:00 UTC, zou3519 commented
Doesn't look BC-breaking because the code does use an acctype for accumulation