[pytorch] Add a new Python test file to test DDP with RPC
pytorch/pytorch pull request #33455
Opened 2020-02-18 19:47 UTC by hczhu

Summary:

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

2020-02-18 20:12 UTC, hczhu commented on test/distributed/test_ddp_with_rpc.py
> +        self.net = nn.Linear(d_in, d_out)
Wrap this in DDP doesn't work on the remote server

2020-02-18 20:14 UTC, hczhu commented on test/distributed/test_ddp_with_rpc.py
> +        x = self.net1(x)
The autograd graph may break because DDP doesn't know the remote net.

2020-02-18 20:15 UTC, hczhu commented on test/distributed/test_ddp_with_rpc.py
> +class DdpModelWithRpc(nn.Module):
Init server group without the remote one so that DDP works on the group.

2020-02-18 21:26 UTC, pritamdamania87 requested changes
Nice stuff! Can we actually make this a unit test (with the entire training loop containing forward, backward and optimizer.step) and use it as validation as we work on supporting this use case.

cc @gqchen This is a simple example of what we're trying to enable for DDP with RPC.

2020-02-18 21:26 UTC, pritamdamania87 commented
cc @zhaojuanmao

2020-02-18 21:27 UTC, hczhu commented
> Can we actually make this a unit test (with the entire training loop containing forward, backward and optimizer.step) and use it as validation as we work on supporting this use case.

I'm planned to do that.

2020-02-19 02:25 UTC, hczhu commented on test/distributed/test_ddp_with_rpc.py
> +        rpc.init_rpc(
This `init_rpc` will fail because the master port is already in use by `init_process_group()` call above.

2020-02-20 22:57 UTC, hczhu commented
Got a new PR #33587 to merge from a origin branch.

2020-02-20 22:57 UTC, closed without merging