[C++ API] Add PackedSequence / pack_padded_sequence / pad_packed_sequence / pack_sequence
pytorch/pytorch pull request #33652
Opened 2020-02-22 05:06 UTC by yf225

Most of the function implementation and test code are translated from the Python version.

2020-02-22 05:42 UTC, yf225 commented
TODO: need to debug `PackedSequenceTest.To` in CUDA

2020-02-24 16:32 UTC, pbelevich approved these changes

2020-02-24 16:32 UTC, pbelevich commented on torch/csrc/api/include/torch/nn/utils/rnn.h
> +///     total_length (int64_t, optional): if not ``None``, the output will be padded to
```suggestion
///     total_length (int64_t, optional): if specified, the output will be padded to
```

2020-02-24 16:34 UTC, pbelevich requested changes

2020-02-24 16:34 UTC, pbelevich commented on test/cpp/api/nn_utils.cpp
> +  auto lengths = torch::empty({ordered.size()}, torch::kInt64);
..\test\cpp\api\nn_utils.cpp(218): error C2398: Element '1': conversion from 'unsigned __int64' to '_Ty' requires a narrowing conversion

2020-02-25 19:28 UTC, pbelevich approved these changes

2020-02-25 20:55 UTC, closed without merging