[WIP] removed .data from test_autograd.py
pytorch/pytorch pull request #33886
Opened 2020-02-27 18:46 UTC by anjali411

issue: https://github.com/pytorch/pytorch/issues/33630

2020-02-27 22:34 UTC, albanD requested changes
Looks mostly good, just small changes

2020-02-27 22:34 UTC, albanD commented on test/test_autograd.py
> -        x_grad = 2 * x.data + y.data
Potentially we want these to run in no_grad mode, but that doesn't really change anything give that they are just used in the assertEqual below...

2020-02-27 22:34 UTC, albanD commented on test/test_autograd.py
> +            indexed_var_t = indexed_var
The goal of this code is to ensure that indexing with a Tensor or a Variable gives the same result.
If we keep this test, then we should keep the `.data` here.
@gchanan should we keep this test though?

2020-02-27 22:34 UTC, albanD commented on test/test_autograd.py
> +            x = None
That does not raise any error right? This should fail.
And you want to keep the original `.data` here as we explicitely want to check that its behavior did not change.

2020-02-27 22:34 UTC, albanD commented on test/test_autograd.py
> +                    ctx.x = Variable(x, requires_grad=True)
You want a `.detach()` here I think. As you don't want `ctx.x` to be linked to `x` in a differentiable manner.

2020-02-27 22:34 UTC, albanD commented on test/test_autograd.py
> +                    ctx.x = Variable(x, requires_grad=True)
Same as above.

2020-02-27 22:34 UTC, albanD commented on test/test_autograd.py
> +        self.assertEqual(1, counter[0])
Why did that change?

2020-02-27 22:38 UTC, anjali411 commented on test/test_autograd.py
> +        self.assertEqual(1, counter[0])
assertEquals has been deprecated

2020-02-28 15:20 UTC, albanD approved these changes
Looks good !

2020-02-28 16:25 UTC, closed without merging