[c10] remove calling __host__ from __device__ not allowed warning
pytorch/pytorch pull request #34046
Opened 2020-03-01 18:50 UTC by jspark1105

Summary:
Remove warning
```
caffe2/c10/util/TypeCast.h(80): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
```

Test Plan: CI

Differential Revision: D20185011

2020-03-11 15:27 UTC, ezyang requested changes
This doesn't seem like the right way to fix the error. We should be compiling with `--expt-relaxed-constexpr`; so we should work out why this flag isn't being passed in whatever situation you're trying to suppress this warning for.

2020-03-11 16:04 UTC, jspark1105 commented
> This doesn't seem like the right way to fix the error. We should be compiling with `--expt-relaxed-constexpr`; so we should work out why this flag isn't being passed in whatever situation you're trying to suppress this warning for.

Sorry I should've wrote more comments why I did this. I thought compiling with expt-relaxed-constexpr is a big hammer because it relaxes a behavior for all functions while the pragma is just for that specific function. I briefly read https://stackoverflow.com/questions/55481202/how-to-disable-cuda-host-device-warning-for-just-one-function and https://github.com/ComputationalRadiationPhysics/picongpu/pull/1707 that led me to use the pragma, but I admit I don't have a lot of CUDA experience. Let me take a closer look when I can find time and get back to you.

2020-03-11 18:17 UTC, ezyang commented
It's not a big hammer when the entire codebase is already using it :)

2020-03-15 15:47 UTC, jspark1105 commented
> It's not a big hammer when the entire codebase is already using it :)

Got it. Maybe we can also ask @ngimel if adding --expt-relaxed-constexpr nvcc option is a right solution?

2020-03-15 17:54 UTC, ngimel commented
To @ezyang's point, the codebase already is (or should be) compiled with `--expt-relaxed-constexpr` https://github.com/pytorch/pytorch/blob/ccf4d69b756919fe831f0c9bcb5beb9aa7832c03/cmake/public/cuda.cmake#L450, so it would be interesting to learn why the warning you are trying to fix still happens.

2020-03-16 20:00 UTC, ezyang commented
This might be a bug in our internal build system.

2020-06-02 16:31 UTC, closed without merging