End of the .data removal in torch/optim
pytorch/pytorch pull request #34211
Opened 2020-03-04 14:36 UTC by albanD

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2020-03-04 17:38 UTC, vincentqb requested changes
As discussed, let's explicitly wait on the results from the internal tests.

2020-03-04 17:40 UTC, vincentqb commented
can you link the previous `.data` pr?

2020-03-04 20:10 UTC, vincentqb approved these changes
Internal tests have passed. LGTM.

2020-03-04 22:57 UTC, vincentqb requested changes
As discussed offline with @albanD, we need
- [x] a new test that does fail without the `.data` removal, but passes with it.
- [x] sign-off from someone in jit (e.g. @suo) that we can modify this test, so that it passes with and without `.data` removal
- [x] measure impact of replacing `module.forward(first_forward)` by `module.forward(x)` on line 114 in this test
- [x] all tests on CI external/internal to pass

2020-03-04 22:57 UTC, vincentqb commented on test/jit/test_data_parallel.py
> +        replica = dp.replicate(module, {0, 1})
As discussed with @albanD, this is not the correct way of modifying this test.

2020-03-06 15:47 UTC, vincentqb commented
Just to clarify:
* `test_tensor_sharing` is the new test: it fails without this patch, and succeeds with?
* `test_tensor_sharing_with_forward` is an updated version of the old test, where `module.forward(first_forward)` is replaced by `module(x)`?

There is still a handful of tests running on internal as of this moment :)

2020-03-06 16:10 UTC, albanD commented
> test_tensor_sharing is the new test: it fails without this patch, and succeeds with?

Not it is my version of making sure that the parameters and buffers are properly shared. It works both with and without the patch. And it has the advantage of not relying on `.data`.

> test_tensor_sharing_with_forward:

yes updated version with `x` and without using the `torch/optim` package as we cannot use it anymore if we want to keep the old logic.

2020-03-06 16:55 UTC, vincentqb commented
> yes updated version with `x` and without using the `torch/optim` package as we cannot use it anymore if we want to keep the old logic.

Alright, so that test fails without the patch, but not with. Great :)

2020-03-06 16:56 UTC, vincentqb approved these changes
Based on the discussion, I'm assuming the PR is no longer [WIP]. LGTM.

2020-03-09 13:42 UTC, closed without merging