Move max pooling construction logic to functions
pytorch/pytorch pull request #343
Opened 2016-12-22 11:10 UTC by szagoruyko

* unifies MaxPool[1,2,3]d functions interfaces and internal modules calls
* removes `*args` and `*additional args` code from functions

2016-12-22 15:58 UTC, colesbury reviewed
LGTM, I'd just be consistent about kh/kw expansion vs kernel_size

2016-12-23 01:14 UTC, apaszke requested changes
As @colesbury, I'm also for using tuples for kernel sizes, strides, etc. in all functions

2016-12-25 07:02 UTC, soumith requested changes
almost looks good. small changes to __repr__ needed. See inline comments

2016-12-25 15:27 UTC, soumith approved these changes

2016-12-25 15:28 UTC, merged