add dtype attributes is_integral and is_quantized.
pytorch/pytorch pull request #34312
Opened 2020-03-05 18:41 UTC by nairbv

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2020-03-05 23:56 UTC, vishwakftw reviewed
I think for consistency with c++, we should include `bool` in `is_integral`.

2020-03-06 15:05 UTC, nairbv commented
@vishwakftw 

> I think for consistency with c++, we should include `bool` in `is_integral`.

if not explicitly requesting includeBool, it looks like we exclude it in C++, at least in ScalarType.h. Are you thinking of somewhere else?

I'm looking at:
```
C10_DEPRECATED_MESSAGE("isIntegralType is deprecated. Please use the overload with 'includeBool' parameter instead.")
static inline bool isIntegralType(ScalarType t) {
  return (
      t == ScalarType::Byte || t == ScalarType::Char || t == ScalarType::Int ||
      t == ScalarType::Long || t == ScalarType::Short);
}

static inline bool isIntegralType(ScalarType t, bool includeBool) {
  bool isIntegral = (
      t == ScalarType::Byte || t == ScalarType::Char || t == ScalarType::Int ||
      t == ScalarType::Long || t == ScalarType::Short);

  return includeBool ? isIntegral || (t == ScalarType::Bool) : isIntegral;
}
```

2020-03-06 15:07 UTC, vishwakftw commented
Oh I meant with respect to C++ as a language, not the API sorry.

2020-03-06 15:10 UTC, nairbv commented
> Oh I meant with respect to C++ as a language, not the API sorry.

Ah that makes sense. I do sort of prefer including bool and that's a good argument in favor, though I'm also afraid it might be odd in pytorch with our type categories for promotion and existing C++ API.

2020-03-06 21:26 UTC, gchanan commented
I think it makes sense for boolean not to be integral, it matches NumPy, see: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dtype.kind.html#numpy.dtype.kind.

I think the NumPy kind API is better, because it forces you to consider all the possibilities.  Another case: are quantized floating point?  That's not usually the question you are actually asking.

What about doing a `kind` API instead?  I'm not sure whether we want quantized to be "quantized" or "signed quantized", I don't really know how people use them.

2020-03-06 21:35 UTC, nairbv commented
> What about doing a `kind` API instead? I'm not sure whether we want quantized to be "quantized" or "signed quantized", I don't really know how people use them.

Hm... I'm not a big fan of the `kind` API since it sort of implies mutual exclusivity of types. Numpy also has a "sub-type" API we could consider:

```
In [20]: np.issubdtype(np.uint32, np.integer)
Out[20]: True

In [21]: np.issubdtype(np.uint32, np.signedinteger)
Out[21]: False

In [22]: np.issubdtype(np.uint32, np.unsignedinteger)
Out[22]: True

In [23]: np.issubdtype(np.uint32, np.floating)
Out[23]: False

In [24]: np.issubdtype(np.float16, np.floating)
Out[24]: True
```

2020-03-10 16:06 UTC, nairbv commented
@gchanan as implemented in numpy, the kind API on its own doesn't seem like it will actually help much:
```
>>> np.dtype('i')
dtype('int32')
>>> np.dtype('i') == np.int
False
>>> np.dtype('i4') == np.int
False
>>> np.dtype('i4') == np.int32
True
```
I'm also not seeing a way to get a `kind` value from a dtype, though maybe I'm missing it.

Adding is_integral / is_quantized might not be a bad thing even if we do also later add an is_subdtype and/or kind API. I think we already have is_floating_point and is_complex.

2020-03-10 22:04 UTC, gchanan commented
> I'm also not seeing a way to get a kind value from a dtype, though maybe I'm missing it.

```
>>> np.dtype(np.int32).kind
'i'
```

2020-03-10 22:05 UTC, gchanan commented
> @gchanan as implemented in numpy, the kind API on its own doesn't seem like it will actually help much:

I'm not sure what you mean here or what the example is showing.

2020-03-10 22:11 UTC, gchanan commented
@nairbv: I do buy your argument about mutual exclusivity, that seems legit.  The main thing I'm trying to get is an API that people actually look up to figure out the subtleties, they don't just see an "is_integral" and think "oh I know what that means".

On that topic, the subdtype API looks nice and not introducing new properties that we'd want to deprecate later seems desirable.  Any objection to doing the subdtype thing instead?

2020-03-11 14:57 UTC, nairbv commented
>>> np.dtype(np.int32).kind

ah I hadn't seen this.

> On that topic, the subdtype API looks nice and not introducing new properties that we'd want to deprecate later seems desirable. Any objection to doing the subdtype thing instead?

It'll take a bit longer so might delay some test changes I'd like to make, but yes I think subdtype is a preferable API.

Interestingly, the way bool/integral is captured in numpy is that integers are a subtype of bool:
```
>>> np.issubdtype(np.int, np.bool)
True
```
It feels a bit odd, but makes sense to me.

2020-06-03 15:55 UTC, gchanan requested changes
just marking that I believe the current plan is to do issubdtype.

2022-05-12 05:39 UTC, closed without merging