[WIP] Refactored rpc docs
pytorch/pytorch pull request #35109
Opened 2020-03-20 18:51 UTC by rohan-varma

Will add screenshots soon

2020-03-20 20:27 UTC, rohan-varma commented
<img width="962" alt="toctree" src="https://user-images.githubusercontent.com/8039770/77203771-82d3e500-6aae-11ea-8542-e5b43b24386e.png">

@jlin27 This is the RPC doc page with the `toctree` approach

2020-03-25 15:04 UTC, mrshenli commented on docs/source/rpc/index.rst
> +  rref.rst
@jlin27 
Do we also need to add tutorials links here? I noticed that distributed tutorials are no longer available in the left navigation bar or tutorial landing page. Is that intentional?

2020-03-27 00:50 UTC, rohan-varma commented
@jlin27 Most recent update:
<img width="897" alt="refactor" src="https://user-images.githubusercontent.com/8039770/77710053-3e52b880-6f8a-11ea-88bc-e81429da6cb3.png">

Echoing @mrshenli , should we add tutorials here as well?

2020-03-27 15:49 UTC, mrshenli commented
Shall we add a note on the top of the `rpc.rst` page saying that 

> APIs in the RPC package are stable. There are multiple ongoing work items to improve performance and error handling, which will ship in future releases.

2020-03-27 15:50 UTC, mrshenli commented
> Echoing @mrshenli , should we add tutorials here as well?

Will need @jlin27's input. If we decided to remove PTD tutorial from the left navigation bar. We probably need to add them here.

2020-03-27 18:25 UTC, rohan-varma commented
<img width="899" alt="rpc_warning" src="https://user-images.githubusercontent.com/8039770/77787961-ab635e00-701d-11ea-92b0-3def1a100a2f.png">
@mrshenli

2020-03-27 23:37 UTC, jlin27 commented
The new rpc/index.rst landing page looks.
The PDT Tutorials will be moved over to a new recipes landing page because they fit that format better - succinct actionable explanations as opposed the longer format tutorials. I'm in the process of moving some of the exiting tutorials over the recipes landing page and will let you know when they are out so the can be linked from this landing page if desired.

The tutorials should still be accessible by their old urls if you would like to use those as placeholders for now. e.g. https://pytorch.org/tutorials/intermediate/ddp_tutorial.html

2020-03-27 23:38 UTC, jlin27 requested changes
New build looks good. I added my comments about adding tutorials/recipes in the main conversation.

2020-03-31 22:08 UTC, rohan-varma commented
![doc_updat_rpc](https://user-images.githubusercontent.com/8039770/78079677-6f9fff80-7361-11ea-83d1-7231253888ac.png)

@mrshenli @jlin27 , this is the latest update

2020-03-31 23:21 UTC, jlin27 approved these changes

2020-04-01 09:04 UTC, closed without merging