Avoid one unnecessary memory allocation in XNNPACK integration.
pytorch/pytorch pull request #35350
Opened 2020-03-25 01:43 UTC by AshkanAliabadi

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Currently we call input.contiguous() on the input tensor resulting in an
unecessary allocation and copy in cases where the input is not contiguous
with regards to the requested memory format.  The reason is that in such
scenarios, this call re-allocates and copies the input tensor into
contiguous storage, only for this newly allocated tensor to be used as
the source of another copy to the final destination.  Instead, if we copy
into the destination directly in such circumstances, we will save an
allocation and a copy.

2020-03-25 01:47 UTC, AshkanAliabadi commented
Do we have any tests that I can use to validate that the results are correct?  I'm not sure this code is exercised through CI.

2020-03-25 15:31 UTC, kimishpatel commented
> Do we have any tests that I can use to validate that the results are correct? I'm not sure this code is exercised through CI.

You can try `python test/test_xnnpack_integration.py`. I suggest add, in one or two tests, trying different memory formats for inputs, including channels first and channels last.

2020-03-25 15:37 UTC, kimishpatel commented on aten/src/ATen/native/xnnpack/Factory.cpp
> +  if ((allocator == guarding_allocator) && input.is_contiguous(memory_format)) {
This function is called only with `MemoryFormat::ChannelsLast`, right? If there is no other use case, then I am wondering if we should make that explicit in the function name and not pass memory_format argument? Just a thought.

2020-03-25 15:42 UTC, kimishpatel requested changes
LG for the most part. Can you add the test I mentioned in the comment or try the existing tests?

2020-04-01 18:46 UTC, dreiss approved these changes

2020-04-03 04:35 UTC, closed without merging