Port `renorm` cpu from TH to ATen
pytorch/pytorch pull request #35537
Opened 2020-03-27 15:10 UTC by shihongzhi

Fixes: #24754

2020-03-30 16:51 UTC, vincentqb commented
@VitalyFedyunin -- since you are on #24754, can you review this PR?

2020-03-31 16:51 UTC, VitalyFedyunin commented on aten/src/ATen/native/TensorShape.cpp
> +    apply_renorm<scalar_t>(result.contiguous(), self.contiguous(), p.to<scalar_t>(), dim, maxnorm.to<scalar_t>());
If you are making self and result contiguous, you will have problems with `x.renorm_`called on non-contiguous tensor. Please add such test and fix it.

2020-03-31 16:52 UTC, VitalyFedyunin requested changes
Problems with non-contiguous tensors. Also please add benchmarks comparing old and new implementations.

2021-01-18 16:07 UTC, nikitaved commented
Hi, @shihongzhi , are you still working on this?

2021-02-23 22:14 UTC, glaringlee commented
> Hi, @shihongzhi , are you still working on this?

@nikitaved, since this is no longer updated, we will use it as an onboarding task for a new member in the team.

2022-06-27 21:37 UTC, closed without merging