Support cudnn in load_lua
pytorch/pytorch pull request #357
Opened 2016-12-27 14:24 UTC by szagoruyko

A couple of dirty hacks to support cudnn. Main problems:
* there's no torch.cuda.FloatStorage.from_buffer so reading fails on CudaStorages https://github.com/pytorch/pytorch/blob/master/torch/utils/serialization/read_lua_file.py#L163
* there's no torch.CudaTensor backend, I added a fallback to torch.FloatTensor

2016-12-27 14:43 UTC, apaszke requested changes

2017-01-21 00:23 UTC, Wakeupbuddy commented on torch/utils/serialization/read_lua_file.py
I think we need to call some decorators for cudnn modules as well, like:

`ensure_attr('cudnn.SpatialConvolution', 'bias', 'finput', 'fgradInput', 'gradWeight', 'gradBias')
ensure_attr('cudnn.SpatialBatchNormalization', 'weight', 'bias', 'gradWeight', 'gradBias')
ensure_attr('cudnn.BatchNormalization', 'weight', 'bias', 'gradWeight', 'gradBias')`

2017-01-21 05:54 UTC, closed without merging

2017-01-21 05:55 UTC, soumith commented
the PR needs to be reopened, as it now comes from a private branch

2018-02-08 04:02 UTC, WayneZww commented on torch/utils/serialization/read_lua_file.py
> +
But where were these code gone? I find the currently code dose not contain these lines and I still got error when loading model contains cudnn.SpatialConvolution