[WIP] Complex Storage
pytorch/pytorch pull request #35771
Opened 2020-03-31 19:04 UTC by anjali411

2020-04-06 20:21 UTC, izdeby requested changes
Please fix tests and make sure that phabricator build passes as well.

2020-04-06 22:11 UTC, anjali411 commented on aten/src/TH/THGenerateComplexFloatType.h
> +#define accreal double
double

2020-04-30 02:12 UTC, anjali411 commented on torch/csrc/utils/byte_order.cpp
> +void THP_decodeComplexFloatBuffer(std::complex<float>* dst, const uint8_t* src, THPByteOrder order, size_t len)
I am converting the complex tensors to float tensors so the decoding logic used for complex tensors is the same as float tensors

2020-04-30 16:54 UTC, zasdfgbnm commented on c10/util/TypeCast.h
> +
Is this necessary?

2020-04-30 17:00 UTC, anjali411 commented on aten/src/THC/THCTensorCopy.cu
> +    *dst = c10::static_cast_with_inter_type<T, T>::apply(*src);
cc. @zasdfgbnm

2020-04-30 17:01 UTC, anjali411 commented on c10/util/TypeCast.h
> +
linked you to where I am using it

2020-04-30 17:39 UTC, anjali411 commented on c10/util/TypeCast.h
> +
updated!

2020-04-30 20:46 UTC, izdeby approved these changes
Look good overall. just remove the log file

2020-04-30 20:46 UTC, izdeby commented on aten/src/THC/THCTensorCopy.cu
> +    *dst = c10::static_cast_with_inter_type<T, T>::apply(*src);
why is this needed?

2020-04-30 20:46 UTC, izdeby commented on errors.txt
> +-- Found PythonInterp: /data/users/chourdiaanjali/miniconda3/envs/myenv2/bin/python (found suitable version "3.6.9", minimum required is "3.0")
this should not be included

2020-04-30 21:36 UTC, anjali411 commented on errors.txt
> +-- Found PythonInterp: /data/users/chourdiaanjali/miniconda3/envs/myenv2/bin/python (found suitable version "3.6.9", minimum required is "3.0")
oops

2020-04-30 23:50 UTC, zasdfgbnm commented on aten/src/THC/THCTensorRandom.cu
> +__host__ void THCRandom_getRNGState(at::Generator gen_, THByteTensor *rng_state)
You might also need to change line 43

2020-04-30 23:53 UTC, anjali411 commented on aten/src/THC/THCTensorRandom.cu
> +__host__ void THCRandom_getRNGState(at::Generator gen_, THByteTensor *rng_state)
ah yeah just realized! thanks

2020-05-01 18:49 UTC, closed without merging