Fix NaN error in dynamic quantization in qLinear, re-enable test_quantized_rnn
pytorch/pytorch pull request #36009
Opened 2020-04-04 01:23 UTC by raghuramank100

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

When scale is very small (less than float eps, but greater than minimum double precision value), computation of reciprocal of scale in floating point precision within FBGEMM returns inf, while QuantUtils does not. Changed computation in QuantUtils to occur with floating point precision to re-enable tests.

Differential Revision: [D20853000](https://our.internmc.facebook.com/intern/diff/D20853000/)

2020-04-05 05:41 UTC, jianyuh commented
Still see the errors in the OSS unit test:
https://circleci.com/gh/pytorch/pytorch/5053092?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

2020-04-06 03:07 UTC, z-a-f commented
This change doesn't fix the flakiness of the test. The nan error happens because inside the observer we get `qmin > qmax`, not because of the float. In fact, `float(np.nan)` is a valid NaN value.

2020-04-06 03:09 UTC, z-a-f commented
I will take a shot at this issue tomorrow evening, if this is not fixed by then

2020-04-06 21:48 UTC, z-a-f requested changes
As mentioned -- this change reenables the test without fixing the flakiness.

2020-04-10 00:14 UTC, supriyar commented on test/quantization/test_quantization.py
>      @given(qengine=st.sampled_from(("fbgemm",)))
@raghuramank100 could you add `qnnpack` here as well? I believe it was skipped for the same reason.

2020-04-24 17:25 UTC, z-a-f commented on test/quantization/test_quantize.py
> +        for qengine in ['fbgemm', 'qnnpack']:
This will fail because `qengine` is not defined

2020-04-24 17:25 UTC, z-a-f commented on test/quantization/test_quantize.py
> +        for qengine in ['fbgemm', 'qnnpack']:
Same here

2020-04-24 17:29 UTC, z-a-f approved these changes

2020-04-25 01:32 UTC, z-a-f commented on test/quantization/test_quantize.py
> +                if qengine in torch.backends.quantized.supported_engines:
I think this line should be before the `override_quantized_engine`:

```python
if qengine in torch.backends.quantized.supported_engines:
  continue
with override_quantized_engine(qengine):
```

2020-04-27 23:41 UTC, z-a-f commented
Reverting because of the test_qelu breakage https://app.circleci.com/pipelines/github/pytorch/pytorch/160770/workflows/a3ca7391-3ba4-4558-9929-7ff1ffd4794c/

2022-05-18 02:12 UTC, closed without merging