Ensure DataParallel replicas can be saved
pytorch/pytorch pull request #37307
Opened 2020-04-25 17:43 UTC by peterbell10

Fixes #37182

The `zero_grad` wrapper from `_replicate_for_data_parallel` can't be pickled. So instead, I set an attribute `_is_replica = True` and check for this in `Module.zero_grad`.

2020-04-25 17:57 UTC, mrshenli approved these changes
Thanks a lot for fixing!! Added two minor comments.

2020-04-25 17:57 UTC, mrshenli commented on test/distributed/test_data_parallel.py
> +import io
nit: Shall we sort the import? io should be between contextlib and unittest?

2020-04-25 17:57 UTC, mrshenli commented on test/distributed/test_data_parallel.py
> +        dpm = torch.nn.parallel.replicate(module, devices=[0, 1])
shall we cover `detach=True` case as well?

2020-04-25 21:16 UTC, mrshenli requested changes
Test failure is real:

```
Apr 25 19:25:16 ======================================================================
Apr 25 19:25:16 FAIL [0.005s]: test_zero_grad (__main__.TestDataParallel)
Apr 25 19:25:16 ----------------------------------------------------------------------
Apr 25 19:25:16 Traceback (most recent call last):
Apr 25 19:25:16   File "distributed/test_data_parallel.py", line 656, in test_zero_grad
Apr 25 19:25:16     dpm(torch.rand(4, 3, 6, 5))
Apr 25 19:25:16   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 562, in __call__
Apr 25 19:25:16     result = self.forward(*input, **kwargs)
Apr 25 19:25:16   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
Apr 25 19:25:16     outputs = self.parallel_apply(replicas, inputs, kwargs)
Apr 25 19:25:16   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
Apr 25 19:25:16     return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
Apr 25 19:25:16   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
Apr 25 19:25:16     output.reraise()
Apr 25 19:25:16   File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
Apr 25 19:25:16     raise self.exc_type(msg)
Apr 25 19:25:16 AssertionError: Caught AssertionError in replica 0 on device 0.
Apr 25 19:25:16 Original Traceback (most recent call last):
Apr 25 19:25:16   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
Apr 25 19:25:16     output = module(*input, **kwargs)
Apr 25 19:25:16   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 562, in __call__
Apr 25 19:25:16     result = self.forward(*input, **kwargs)
Apr 25 19:25:16   File "distributed/test_data_parallel.py", line 651, in forward
Apr 25 19:25:16     self.zero_grad()
Apr 25 19:25:16   File "/opt/conda/lib/python3.6/unittest/case.py", line 265, in __exit__
Apr 25 19:25:16     self.expected_regex.pattern, str(first_matching)))
Apr 25 19:25:16   File "/opt/conda/lib/python3.6/unittest/case.py", line 135, in _raiseFailure
Apr 25 19:25:16     raise self.test_case.failureException(msg)
Apr 25 19:25:16 AssertionError: "Calling \.zero_grad\(\) from a module that was passed to a nn\.DataParallel\(\) has no effect." does not match "Calling .zero_grad() from a module created with nn.DataParallel() has no effect. The parameters are copied (in a differentiable manner) from the original module. This means they are not leaf nodes in autograd and so don't accumulate gradients. If you need gradients in your forward method, consider using autograd.grad instead."
```

2020-04-26 01:20 UTC, mrshenli approved these changes

2020-04-26 03:58 UTC, closed without merging

2021-02-05 06:42 UTC, v-yunbin commented
> Test failure is real:
> 
> ```
> Apr 25 19:25:16 ======================================================================
> Apr 25 19:25:16 FAIL [0.005s]: test_zero_grad (__main__.TestDataParallel)
> Apr 25 19:25:16 ----------------------------------------------------------------------
> Apr 25 19:25:16 Traceback (most recent call last):
> Apr 25 19:25:16   File "distributed/test_data_parallel.py", line 656, in test_zero_grad
> Apr 25 19:25:16     dpm(torch.rand(4, 3, 6, 5))
> Apr 25 19:25:16   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 562, in __call__
> Apr 25 19:25:16     result = self.forward(*input, **kwargs)
> Apr 25 19:25:16   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
> Apr 25 19:25:16     outputs = self.parallel_apply(replicas, inputs, kwargs)
> Apr 25 19:25:16   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
> Apr 25 19:25:16     return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
> Apr 25 19:25:16   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
> Apr 25 19:25:16     output.reraise()
> Apr 25 19:25:16   File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
> Apr 25 19:25:16     raise self.exc_type(msg)
> Apr 25 19:25:16 AssertionError: Caught AssertionError in replica 0 on device 0.
> Apr 25 19:25:16 Original Traceback (most recent call last):
> Apr 25 19:25:16   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
> Apr 25 19:25:16     output = module(*input, **kwargs)
> Apr 25 19:25:16   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 562, in __call__
> Apr 25 19:25:16     result = self.forward(*input, **kwargs)
> Apr 25 19:25:16   File "distributed/test_data_parallel.py", line 651, in forward
> Apr 25 19:25:16     self.zero_grad()
> Apr 25 19:25:16   File "/opt/conda/lib/python3.6/unittest/case.py", line 265, in __exit__
> Apr 25 19:25:16     self.expected_regex.pattern, str(first_matching)))
> Apr 25 19:25:16   File "/opt/conda/lib/python3.6/unittest/case.py", line 135, in _raiseFailure
> Apr 25 19:25:16     raise self.test_case.failureException(msg)
> Apr 25 19:25:16 AssertionError: "Calling \.zero_grad\(\) from a module that was passed to a nn\.DataParallel\(\) has no effect." does not match "Calling .zero_grad() from a module created with nn.DataParallel() has no effect. The parameters are copied (in a differentiable manner) from the original module. This means they are not leaf nodes in autograd and so don't accumulate gradients. If you need gradients in your forward method, consider using autograd.grad instead."
> ```

@mrshenli have you solved the problem？