[cmake] create symlink third_party/googletest pointint to GOOGLETEST_SOURCE_DIR when appropriate
pytorch/pytorch pull request #37564
Opened 2020-04-30 04:22 UTC by cdluminate

Some other cmake files do not honour the GOOGLETEST_SOURCE_DIR variable,
and insist on using the hardcoded <...>/third_party/googletest path.
This commits works around the problem.

@ezyang 

as a part of #14699

2020-04-30 13:59 UTC, ezyang commented
This seems... super hacky. Did you look how hard it would be to make everyone honor `GOOGLETEST_SOURCE_DIR` ?

2020-04-30 14:06 UTC, cdluminate commented
> This seems... super hacky. Did you look how hard it would be to make everyone honor `GOOGLETEST_SOURCE_DIR` ?

Ummm... Let me try that

2020-05-05 16:32 UTC, malfet requested changes
Rather than creating a symlink, wouldn't it be better to modify `cmake/Dependencies.cmake` to check for `GOOGLETEST_SOURCE_DIR`? See https://github.com/pytorch/pytorch/blob/master/cmake/Dependencies.cmake#L548

2020-05-07 04:12 UTC, cdluminate commented
@malfet Thanks for the suggestion and I agree with that. I'm somewhat busy recently to finish the revision.

2022-05-12 04:46 UTC, closed without merging