Memory profiling
pytorch/pytorch pull request #37775
Opened 2020-05-04 17:35 UTC by ilia-cher

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Summary:
Adding memory usage into profiler table output

Test Plan:
BUILD_BINARY=1 USE_BLAS=MKL USE_MKLDNN=0 USE_CUDA=0 python setup.py
develop install --cmake

python

import torch
import torchvision.models as models
model = models.resnet18()
inp = torch.randn(5, 3, 224, 224)

with torch.autograd.profiler.profile(profile_memory=True, record_shapes=True) as prof:
    model(inp)

print(prof.key_averages(group_by_input_shape=True).table(sort_by="cpu_memory_usage", row_limit=15))

---------------------------  ---------------  ---------------  ---------------  ---------------  ---------------  ---------------  ---------------  -----------------------------------
Name                         Self CPU total %  Self CPU total   CPU total %      CPU total        CPU time avg     CPU Mem Total    Number of Calls  Input Shapes
---------------------------  ---------------  ---------------  ---------------  ---------------  ---------------  ---------------  ---------------  -----------------------------------
resize_                      0.37%            577.936us        0.37%            577.936us        9.796us          339.03 Mb        59               [[0]]
empty                        0.69%            1.061ms          0.74%            1.139ms          5.556us          47.42 Mb         205              []
stride                       0.00%            0.853us          0.00%            0.853us          0.853us          19.53 Kb         1                [[5, 1000]]
empty_strided                0.01%            21.393us         0.02%            26.033us         5.207us          252 b            5                []
is_complex                   0.02%            37.425us         0.02%            37.425us         1.291us          208 b            29               [[]]
masked_select                0.04%            55.333us         0.06%            93.616us         46.808us         120 b            2                [[30], [30]]
conv2d                       0.01%            18.009us         9.62%            14.902ms         14.902ms         0 b              1                [[5, 3, 224, 224], [64, 3, 7, 7], [
convolution                  0.01%            12.436us         9.61%            14.884ms         14.884ms         0 b              1                [[5, 3, 224, 224], [64, 3, 7, 7], [
_convolution                 0.03%            52.381us         9.60%            14.871ms         14.871ms         0 b              1                [[5, 3, 224, 224], [64, 3, 7, 7], [
size                         0.00%            5.429us          0.00%            5.429us          0.339us          0 b              16               [[5, 3, 224, 224]]
contiguous                   0.00%            1.934us          0.00%            1.934us          0.967us          0 b              2                [[5, 3, 224, 224]]
_convolution_nogroup         0.02%            27.505us         9.57%            14.814ms         14.814ms         0 b              1                [[5, 3, 224, 224], [64, 3, 7, 7], [
_nnpack_available            0.02%            34.267us         0.02%            34.267us         1.713us          0 b              20               []
thnn_conv2d                  0.01%            13.274us         9.54%            14.771ms         14.771ms         0 b              1                [[5, 3, 224, 224], [64, 3, 7, 7], [
thnn_conv2d_forward          5.98%            9.264ms          19.02%           29.446ms         14.723ms         0 b              2                [[5, 3, 224, 224], [64, 3, 7, 7], [
---------------------------  ---------------  ---------------  ---------------  ---------------  ---------------  ---------------  ---------------  -----------------------------------
Self CPU time total: 154.855ms

2020-05-05 06:04 UTC, dzhulgakov requested changes
What about testing? Can you write unittests? (including enabling profiler in the middle of the allocation)

I'd also double-triple check that memory allocation tracking works well with non-standard allocators, e.g. if one does MKLDNN allocations (with to_mkldnn) or some of the internal ones (huge pages)

2020-05-15 04:51 UTC, dzhulgakov approved these changes
Great! I think it's good to go! (and nice catch on overlapping ranges)

There's also some allocator stuff left in TH, but I'm not sure what it is and I didn't trace where it gets called:
https://github.com/pytorch/pytorch/blob/40265e2d663cc0027cffa6e80ee1ec67d467ca00/aten/src/TH/THAllocator.cpp

2020-05-15 04:51 UTC, dzhulgakov commented on c10/core/Allocator.h
> +  MemoryReportingInfoBase() {}
as discussed - move it to .cpp file to avoid potentially duplicated symbols

2020-05-18 21:43 UTC, ilia-cher commented
from what I got (thanks @ezyang) this is a special allocator used to allocate tensors in shared memory space used for inter-process communication; I guess we can add memory reporting to there too

2020-05-19 22:51 UTC, closed without merging

2020-05-20 14:50 UTC, ezyang commented
This broke ROCm tests:

```

01:17:35 ======================================================================
01:17:35 FAIL: test_memory_profiler (__main__.TestAutograd)
01:17:35 ----------------------------------------------------------------------
01:17:35 Traceback (most recent call last):
01:17:35   File "test_autograd.py", line 2940, in test_memory_profiler
01:17:35     "test_user_scope_dealloc",
01:17:35   File "test_autograd.py", line 2897, in check_metrics
01:17:35     self.assertTrue(stat_metrics[alloc_fn] > 0)
01:17:35 AssertionError: False is not true
01:17:35 
01:17:35 ----------------------------------------------------------------------
```

2020-05-20 14:50 UTC, ezyang commented
Was failing on https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28393/console

cc @jeffdaily

2020-05-20 16:10 UTC, jeffdaily commented
Thank you for the notification.  In the future, if a new test for a new feature is breaking ROCm CI, can we have the developer(s) add the `skipIfRocm` decorator and tag me to look into it?  This would help with our CI stability.  Ideally, it would be fixed prior to merging the PR, but I understand at present it's a tough request.

2020-05-20 16:38 UTC, jeffdaily commented
cc @ezyang https://github.com/pytorch/pytorch/pull/38790

2020-05-20 20:31 UTC, ilia-cher commented
I'm landing the fix https://github.com/pytorch/pytorch/pull/38795

2020-05-20 20:34 UTC, ilia-cher commented
have you noticed though that py3.6-clang7-rocmdeb-ubuntu16.04-test2 was broken on trunk at least since May 16 
https://ezyang.github.io/pytorch-ci-hud/build/pytorch-master ?

2020-05-20 20:37 UTC, albanD commented
I don't think it was continuously broken, it was fixed on the 19th, then broken again 3 commits later :/