Migrate `lstsq` from the TH to Aten (CPU) #24726
pytorch/pytorch pull request #38210
Opened 2020-05-10 22:28 UTC by wDaniec

Lstsq is now written in Aten instead of TH. I had a few concern while writing this PR. 
1) Don't know if it's the correct place to write the code. I used BatchLinearAlgebra.cpp, even though there was a file named LinearAlgebra.cpp. Only the first one includes the LApack functions so I didn't want to make a mess. On the other hand I saw an issue asking for lstsq to work in batchform, so futurewise  it may a good choice.
2) I am concerned about the fact that LApack functions accept columMajor matrixes, while pyTorch uses rowMajor matrixes. I made a workaround that just increases the step size. It may cause a huge performance drop on large matrixes, i.e. a whole row of values may be written into cache at each step. I didn't figure out how to change the LAPack function to work on rowMajor matrixes. I also don't understand why intel definitions of said functions are different than the ones used in code.
3) TH file with LAPack functions is imported. Is there a way to import the LAPack library to the Aten workspace? 

If the solution is acceptable I am open to moving more algebraic functions to ATen.

cc @VitalyFedyunin

2020-05-11 20:20 UTC, VitalyFedyunin commented
1. The place is good, don't worry.
2. Please include performance benchmarks
3. It is fine to use this import as it is not you who introduced it.

2020-05-11 20:20 UTC, VitalyFedyunin commented
PS. Test failures are legit and related to PR.

2020-05-13 17:14 UTC, VitalyFedyunin requested changes
Please fix tests and re-request review, thanks.

2020-05-31 15:17 UTC, wDaniec commented
Benchmarking code:

```
import torch
import time

torch.manual_seed(0)

def _time():
    return time.time()

device = "cpu"

#warm up
for i in [10, 100, 1000]:
    for _ in range(1000):
        n = torch.randint(1, i, (1,)).item()
        m = torch.randint(1, i, (1,)).item()
        k = torch.randint(1, i, (1,)).item()

        input = torch.randn(128, n, requires_grad=False, device=device)
        b = torch.randn(n, k, requires_grad=False, device=device)
        a = torch.randn(n, m, requires_grad=False, device=device)
        torch.lstsq(b, a)


for i in [10, 100, 1000]:
    fwd_t = 0
    for _ in range(10000):
        n = torch.randint(1, i, (1,)).item()
        m = torch.randint(1, i, (1,)).item()
        k = torch.randint(1, i, (1,)).item()

        input = torch.randn(128, n, requires_grad=False, device=device)
        b = torch.randn(n, k, requires_grad=False, device=device)
        a = torch.randn(n, m, requires_grad=False, device=device)
        t1 = _time()
        torch.lstsq(b, a)
        t2 = _time()
        fwd_t = fwd_t + (t2 -t1)
    fwd_avg = fwd_t / 10000 * 1000
    print("average calculation time is %.4f (ms)." % (fwd_avg))
```

Results:
ATen:
average calculation time is 0.0259 (ms)
average calculation time is 1.1662 (ms)
average calculation time is 28.5751 (ms)

TH:
average calculation time is 0.0176 (ms).
average calculation time is 1.7690 (ms).
average calculation time is 24.5436 (ms).

2020-05-31 15:28 UTC, wDaniec commented
The code passes all the functional tests, but it still fails build on mobile devices. I can't figure out what's the problem. Other algebraic functions from BatchLinearAlgebra.cpp seem to be working fine with similar code structure. Should the function lapackGels be declared in some other file?

2021-03-16 02:00 UTC, VitalyFedyunin commented
Please er-add me as reviewer when you are ready with it, thanks.

2021-03-16 15:12 UTC, vishwakftw commented
This has already been done in #49093, cc: @nikitaved to confirm.

2021-03-16 15:15 UTC, nikitaved commented
Hi! The porting was not done, but a new method `linalg.lstsq` is implemented. Unlike `linalg.lstsq` it does support batching/broadcasting and several drivers to choose from depending on your needs.

2021-03-16 17:09 UTC, vishwakftw commented
Right, but `torch.lstsq` will be deprecated in favour of `torch.linalg.lstsq` correct?

2021-03-16 18:15 UTC, nikitaved commented
That is correct.

2021-09-07 08:02 UTC, IvanYashchuk commented
`lstsq` was migrated from TH to ATen with https://github.com/pytorch/pytorch/pull/59400.

2021-09-07 08:02 UTC, closed without merging