Implementing a Moyal distribution.
pytorch/pytorch pull request #38984
Opened 2020-05-25 14:02 UTC by fearghuskeeble

This adds a [Moyal distribution](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.moyal.html) to pytorch's distributions library. 

I've more or less followed the recipe from the Gumbel distribution since they are very similar but this distribution also required the addition of the error function to the list of transforms available for `TransformedDistribution`.

2020-05-26 17:08 UTC, fritzo requested changes
Looks great!

- Could you point me to a reference so I can check math?
- Add tests for `ErfTransform` (e.g. similar to `ExpTransform`).
- Add both `Moyal` and `ErfTransform` to [docs/source/distributions.rst](https://github.com/pytorch/pytorch/blob/master/docs/source/distributions.rst).

2020-05-26 17:08 UTC, fritzo commented on torch/distributions/transforms.py
> +    codomain = constraints.positive
This should be `constraints.interval(-1., 1.)`, right?

2020-05-26 17:08 UTC, fritzo commented on torch/distributions/transforms.py
> +class ErfTransform(Transform):
Can you add tests for `ErfTransform` (e.g. to catch the codomain bug)?

2020-05-27 12:37 UTC, fearghuskeeble commented
Thanks for your review @fritzo and well spotted on the codomain of the error function. 

As to the maths, I solved the various divergences in Mathematica as these are not written down anywhere (that I can find).  If I find some time I will write them down myself and amend this comment.

2022-07-11 04:45 UTC, closed without merging