ROCm jenkins run distributed tests separately as new test3
pytorch/pytorch pull request #39106
Opened 2020-05-27 22:29 UTC by jeffdaily

CC @ezyang @xw285cornell @sunway513 

Corresponds to https://github.com/pytorch/ossci-job-dsl/pull/65

2020-05-28 15:30 UTC, jeffdaily commented
@pytorchbot retest this please

2020-05-28 17:07 UTC, ezyang commented
I think this is affecting non-ROCm builds. Not all of our configs do three test configs, which means it would be invalid to exclude things from test2, since test3 will never get run.

2020-05-28 17:09 UTC, ezyang requested changes
I don't think this works

2020-05-28 17:12 UTC, xw285cornell commented
qq: does circleci also uses the same test script? I thought it's ok because it's under the jenkins folder. If so, we can add a rocm guard for test2/3?

2020-05-28 17:22 UTC, jeffdaily commented
Does circleci use the same test script?

2020-05-28 17:35 UTC, ezyang commented
CircleCI uses this script (it is confusingly named)

2020-06-01 13:49 UTC, ezyang commented on .jenkins/pytorch/test.sh
> +elif [[ "${BUILD_ENVIRONMENT}" == *-test3 || "${JOB_BASE_NAME}" == *-test3 ]]; then
`JOB_BASE_NAME`? If this is to deal with Jenkins differences, don't you have to apply this everywhere else?

2020-06-01 13:50 UTC, ezyang commented
Please give evidence that: (1) non-ROCm jobs are still running distributed tests and (2) ROCm jobs are not running distributed tests

2020-06-02 16:42 UTC, jeffdaily commented
ROCm kernel was patched on CI hosts.  This PR might not be needed any longer since the sporadic mem access faults should be resolved with the patched kernel.  This PR was only creating the test3 to separate out the mGPU tests that seemed to exercise the fault more frequently than sGPU tests.

2020-06-05 15:36 UTC, jeffdaily commented
If the need arises again to have a test3, we will open a new PR.  As of today, ROCm CI has stabilized.

2020-06-05 15:36 UTC, closed without merging