Remove hacky double registration of to_here op in reg_distributed_ops
pytorch/pytorch pull request #39602
Opened 2020-06-05 21:27 UTC by rohan-varma

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

This was added as a part of
https://github.com/pytorch/pytorch/pull/38590 but we can use default arguments
here. We use fmt:;format to bind the default value to the rpc timeout at
runtime.

Differential Revision: [D21912719](https://our.internmc.facebook.com/intern/diff/D21912719/)

2020-06-06 19:03 UTC, mrshenli approved these changes

2020-06-16 17:19 UTC, xush6528 requested changes

2020-06-16 17:19 UTC, xush6528 commented on torch/csrc/jit/runtime/register_distributed_ops.cpp
> +             "aten::to_here(RRef(t) self, float timeout = {}) -> t",
"aten::to_here(RRef(t) self, float timeout = {}) -> t(*)",

2020-06-16 17:50 UTC, rohan-varma commented on torch/csrc/jit/runtime/register_distributed_ops.cpp
> +             "aten::to_here(RRef(t) self, float timeout = {}) -> t",
@xush6528 fixed.

2020-06-16 23:13 UTC, xush6528 approved these changes

2020-06-17 03:21 UTC, closed without merging