[WIP] Replace CPU_tensor_apply functions with cpu_serial_kernel
pytorch/pytorch pull request #39711
Opened 2020-06-09 06:02 UTC by RockingJavaBean

Resolve #39556
Related to #38558

Replace CPU_tensor_apply functions with cpu_serial_kernel in bernoulli_kernel, unifying bernoulli_kernel with all other kernels in `cpu/DistributionTemplates.h`.

Signed-off-by: Xiong Wei <xiongw.fnst@cn.fujitsu.com>

2020-06-11 12:19 UTC, RockingJavaBean commented
The `TensorIterator` is constructed for the `cpu_serial_kernel` function to replace CPU_tensor_apply functions.
Please kindly review this PR. @pbelevich

2020-06-11 22:10 UTC, pbelevich requested changes
I tested your branch vs master manually and unfortunately found performance degradation and even crashes. 
1. Please add(or change existing) tests to make sure that it doesn't crash
2. Please manually test performance using ipython's "timeit" and post the results here
3. Make sure that scalar_types semantics was not changed
```
import torch

size = 1000000

t = torch.empty(size, dtype=torch.int32, device='cpu')

p = torch.rand(size, dtype=torch.float32, device='cpu')

timeit t.bernoulli_(p)
BEFORE: 13 ms ± 78.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
AFTER : 21.3 ms ± 53.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

t = torch.empty(size, dtype=torch.int64, device='cpu')

p = torch.rand(size, dtype=torch.float32, device='cpu')

timeit t.bernoulli_(p)
BEFORE: 13.5 ms ± 43.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
AFTER : 19.7 ms ± 77.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

t = torch.empty(size, dtype=torch.float32, device='cpu')

p = torch.rand(size, dtype=torch.float32, device='cpu')

timeit t.bernoulli_(p)
BEFORE: 20 ms ± 51.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
AFTER : 20.4 ms ± 118 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

t = torch.empty(size, dtype=torch.float64, device='cpu')

p = torch.rand(size, dtype=torch.float32, device='cpu')

timeit t.bernoulli_(p)
BEFORE: 19.9 ms ± 46 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
AFTER : 21.2 ms ± 34.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

t = torch.empty(size, dtype=torch.bool, device='cpu')

p = torch.rand(size, dtype=torch.float32, device='cpu')

timeit t.bernoulli_(p)
BEFORE: 12.9 ms ± 174 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
AFTER : 19.4 ms ± 21.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

t = torch.empty(size, dtype=torch.int32, device='cpu')

p = torch.rand(size, dtype=torch.float64, device='cpu')

timeit t.bernoulli_(p)
BEFORE: 26.8 ms ± 94 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
AFTER : RuntimeError: !needs_dynamic_casting<func_t>::check(iter) INTERNAL ASSERT FAILED at "../aten/src/ATen/native/cpu/Loops.h":245, please report a bug to PyTorch.

t = torch.empty(size, dtype=torch.int64, device='cpu')

p = torch.rand(size, dtype=torch.float64, device='cpu')

timeit t.bernoulli_(p)
BEFORE: 26.8 ms ± 195 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
AFTER : RuntimeError: !needs_dynamic_casting<func_t>::check(iter) INTERNAL ASSERT FAILED at "../aten/src/ATen/native/cpu/Loops.h":245, please report a bug to PyTorch

t = torch.empty(size, dtype=torch.float32, device='cpu')

p = torch.rand(size, dtype=torch.float64, device='cpu')

timeit t.bernoulli_(p)
BEFORE: 26.7 ms ± 86.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
AFTER : RuntimeError: !needs_dynamic_casting<func_t>::check(iter) INTERNAL ASSERT FAILED at "../aten/src/ATen/native/cpu/Loops.h":245, please report a bug to PyTorch.

t = torch.empty(size, dtype=torch.float64, device='cpu')

p = torch.rand(size, dtype=torch.float64, device='cpu')

timeit t.bernoulli_(p)
BEFORE: 21.6 ms ± 99.2 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
AFTER : 23.2 ms ± 105 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

t = torch.empty(size, dtype=torch.bool, device='cpu')

p = torch.rand(size, dtype=torch.float64, device='cpu')

timeit t.bernoulli_(p)
BEFORE: 26.3 ms ± 192 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
AFTER : RuntimeError: !needs_dynamic_casting<func_t>::check(iter) INTERNAL ASSERT FAILED at "../aten/src/ATen/native/cpu/Loops.h":245, please report a bug to PyTorch.
```

2020-06-12 12:50 UTC, RockingJavaBean commented on aten/src/ATen/native/cpu/DistributionTemplates.h
> +      auto iter = TensorIterator();
Thanks for pointing out, I will put them into the beginning of the function.

2020-06-12 12:52 UTC, RockingJavaBean commented on aten/src/ATen/native/cpu/DistributionTemplates.h
> +          return static_cast<scalar_t>(bernoulli(generator));
Yes, I will use the original `self_t` instead of `p_.scalar_type()`.

2020-06-12 12:53 UTC, RockingJavaBean commented on aten/src/ATen/native/cpu/DistributionTemplates.h
> +      cpu_serial_kernel(iter, [&](const scalar_t p_val) -> scalar_t {
Thanks for pointing out, I will use double directly.

2020-06-12 12:54 UTC, RockingJavaBean commented on aten/src/ATen/native/cpu/DistributionTemplates.h
> -    CPU_tensor_apply1<scalar_t>(
I will remove it from `aten/src/ATen/CPUApplyUtils.h`.

2020-06-12 12:56 UTC, RockingJavaBean commented on aten/src/ATen/native/cpu/DistributionTemplates.h
> +      cpu_serial_kernel(iter, [&](const scalar_t p_val) -> scalar_t {
Thanks for pointing out, I will use double directly.

2020-06-12 13:12 UTC, RockingJavaBean commented on aten/src/ATen/native/cpu/DistributionTemplates.h
> +      iter.cast_common_dtype_to_outputs(true);
The reason is that #39655 introduces new flags for `TensorIterator`.

According to comment here: https://github.com/pytorch/pytorch/pull/39655/files#diff-361e42c2f0222e9901eec1ff739c1af4R325

```
// Sets the check_all_same_dtype_ flag, which is true by default
// If true, checks that all inputs and defined outputs have the same dtype
// Setting either of promote_inputs_to_common_dtype_
//   or cast_common_dtype_to_outputs_ to true will set
//   check_all_same_dtype_ to false.
```

The `TensorIterator` will check all inputs and outputs that have the same dtype by default, which is not the appropriate behavior for the `bernoulli_` function.

I use the `cast_common_dtype_to_outputs` function to set `cast_common_dtype_to_outputs_`  flag to true and disable `same dtype checking` in the meanwhile.

2020-06-12 14:02 UTC, RockingJavaBean commented
@pbelevich Thank you so much for the kind review and providing the performance test script.

I have tested the performance using ipython's "timeit" on my laptop (`Intel Core i5-1035G1`).
Below is the test result.

```python
import torch
size = 1000000

t = torch.empty(size, dtype=torch.int32, device='cpu')
p = torch.rand(size, dtype=torch.float32, device='cpu')

timeit t.bernoulli_(p)
------------------
Before: 11.4 ms ± 61.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After: 14.5 ms ± 686 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
------------------

t = torch.empty(size, dtype=torch.int64, device='cpu')
p = torch.rand(size, dtype=torch.float32, device='cpu')

timeit t.bernoulli_(p)
------------------
Before: 11.6 ms ± 336 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After: 14.2 ms ± 255 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
------------------

t = torch.empty(size, dtype=torch.float32, device='cpu')
p = torch.rand(size, dtype=torch.float32, device='cpu')

timeit t.bernoulli_(p)
------------------
Before: 11.1 ms ± 73.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After: 9.58 ms ± 82 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
------------------

t = torch.empty(size, dtype=torch.float64, device='cpu')
p = torch.rand(size, dtype=torch.float32, device='cpu')

timeit t.bernoulli_(p)
------------------
Before: 11.7 ms ± 447 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After: 13.1 ms ± 392 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
------------------

t = torch.empty(size, dtype=torch.bool, device='cpu')
p = torch.rand(size, dtype=torch.float32, device='cpu')

timeit t.bernoulli_(p)
------------------
Before: 21.9 ms ± 247 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
After: 25.8 ms ± 322 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
------------------

t = torch.empty(size, dtype=torch.int64, device='cpu')
p = torch.rand(size, dtype=torch.float64, device='cpu')

timeit t.bernoulli_(p)
------------------
Before: 15 ms ± 159 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After: RuntimeError: !needs_dynamic_casting<func_t>::check(iter) INTERNAL ASSERT FAILED at "..\\aten\\src\\ATen/native/cpu/Loops.h":245, please report a bug to PyTorch.
------------------

t = torch.empty(size, dtype=torch.float32, device='cpu')
p = torch.rand(size, dtype=torch.float64, device='cpu')

timeit t.bernoulli_(p)
------------------
Before: 15.1 ms ± 79.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After: RuntimeError: !needs_dynamic_casting<func_t>::check(iter) INTERNAL ASSERT FAILED at "..\\aten\\src\\ATen/native/cpu/Loops.h":245, please report a bug to PyTorch.
------------------

t = torch.empty(size, dtype=torch.float64, device='cpu')
p = torch.rand(size, dtype=torch.float64, device='cpu')

timeit t.bernoulli_(p)
-------------------
Before: 15.2 ms ± 112 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After: 14 ms ± 315 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
-------------------

t = torch.empty(size, dtype=torch.bool, device='cpu')
p = torch.rand(size, dtype=torch.float64, device='cpu')

timeit t.bernoulli_(p)
-------------------
Before: 24.9 ms ± 297 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
After: RuntimeError: !needs_dynamic_casting<func_t>::check(iter) INTERNAL ASSERT FAILED at "..\\aten\\src\\ATen/native/cpu/Loops.h":245, please report a bug to PyTorch.
-------------------
```

Compared with ` CPU_tensor_apply2`, using `TensorIterator` with `cpu_serial_kernel` is

- **slower**: when the dtype of input `tensor p` is `float32`, and the dytpe of `tensor t ` is not the `float32`.
- **similar performance**: when `tensor p` and `tensor t` have the same dtype (float32/float64). The performance is even better on my laptop.
- **runtime error**: when the dtype of input `tensor p` is `float64`, and `t` is not a `float64` tensor.

The runtime error is thrown by `aten/src/ATen/native/cpu/Loops.h` due to the failure of the `TORCH_INTERNAL_ASSERT`.
https://github.com/pytorch/pytorch/blob/246d7bb41d138a3b05834c17311f2c326d1d2536/aten/src/ATen/native/cpu/Loops.h#L244-L245

The possible causes for the failed assert in the `loops.h` when input tensor is `float64` are needed to be found out.
My guess is the failed assert is due to the new behaviors and checks of `TensorIterator`.

2020-06-13 00:55 UTC, RockingJavaBean commented
The performance degradation of `TensorIterator with cpu_serial_kernel` will have to do with the casting behaviors of `TensorIterator` when the input and output tensor do not share the same dtype.

2020-06-15 03:01 UTC, pbelevich requested changes
Please add(or change existing) `test_bernoulli*` in `test_torch.py` to make sure that we cover cases when the dtype of input tensor p is float64, and t is not a float64 tensor

It's very bad that we caught RuntimeError manually but our `test_bernoulli*` don't caught it automatically :(

2020-06-15 12:33 UTC, RockingJavaBean commented on aten/src/ATen/native/cpu/DistributionTemplates.h
> +        cpu_serial_kernel(iter, [&](const p_t p_val) -> scalar_t {
Thanks for pointing out the cause, I will update the code according to the kind suggestions.

2020-06-15 12:34 UTC, RockingJavaBean commented on aten/src/ATen/native/cpu/DistributionTemplates.h
> +      cpu_serial_kernel(iter, [&](const double p_val) -> scalar_t {
I will change `scalar_t` to `self_t` here to emphasize the result dtype.

2020-06-15 12:35 UTC, RockingJavaBean commented on aten/src/ATen/native/cpu/DistributionTemplates.h
> +    iter.cast_common_dtype_to_outputs(true);
Thanks for the tip, I will change the code accordingly to let `TensorIterator` not check the dtype.

2020-06-15 14:39 UTC, RockingJavaBean commented
@pbelevich thanks so much for your kind help and guidance through this pull request.
I have updated the code according to the feedback, and enhance the test method `test_bernoulli_self` by adding more float dtypes to the input tensor p.

I also manually re-tested the performance using `ipython's timeit` on my laptop.
Below is the test result, while `after` is the performance of latest PR.

```python
import torch
size = 1000000

t = torch.empty(size, dtype=torch.int32, device='cpu')
p = torch.rand(size, dtype=torch.float32, device='cpu')
timeit t.bernoulli_(p)
------------------
Before: 11.4 ms ± 61.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After: 9.77 ms ± 85.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
------------------

t = torch.empty(size, dtype=torch.int64, device='cpu')
p = torch.rand(size, dtype=torch.float32, device='cpu')
timeit t.bernoulli_(p)
------------------
Before: 11.6 ms ± 336 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After: 10.5 ms ± 147 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
------------------

t = torch.empty(size, dtype=torch.float32, device='cpu')
p = torch.rand(size, dtype=torch.float32, device='cpu')
timeit t.bernoulli_(p)
------------------
Before: 11.1 ms ± 73.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After: 9.5 ms ± 108 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
------------------

t = torch.empty(size, dtype=torch.float64, device='cpu')
p = torch.rand(size, dtype=torch.float32, device='cpu')
timeit t.bernoulli_(p)
------------------
Before: 11.7 ms ± 447 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After: 9.82 ms ± 111 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
------------------

t = torch.empty(size, dtype=torch.bool, device='cpu')
p = torch.rand(size, dtype=torch.float32, device='cpu')
timeit t.bernoulli_(p)
------------------
Before: 21.9 ms ± 247 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
After: 20.9 ms ± 148 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
------------------

t = torch.empty(size, dtype=torch.int64, device='cpu')
p = torch.rand(size, dtype=torch.float64, device='cpu')
timeit t.bernoulli_(p)
------------------
Before: 15 ms ± 159 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After: 13.2 ms ± 56.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
------------------

t = torch.empty(size, dtype=torch.float32, device='cpu')
p = torch.rand(size, dtype=torch.float64, device='cpu')
timeit t.bernoulli_(p)
------------------
Before: 15.1 ms ± 79.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After: 13.9 ms ± 274 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
------------------

t = torch.empty(size, dtype=torch.float64, device='cpu')
p = torch.rand(size, dtype=torch.float64, device='cpu')
timeit t.bernoulli_(p)
-------------------
Before: 15.2 ms ± 112 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After: 14 ms ± 176 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
-------------------

t = torch.empty(size, dtype=torch.bool, device='cpu')
p = torch.rand(size, dtype=torch.float64, device='cpu')
timeit t.bernoulli_(p)
-------------------
Before: 24.9 ms ± 297 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
After: 24 ms ± 512 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
---------------
```

No performance degradation and runtime errors are found during the manual test.

2020-06-15 20:50 UTC, pbelevich approved these changes

2020-06-15 21:13 UTC, closed without merging