Add `generator=` kwarg for all `torch.rand*`
pytorch/pytorch pull request #39804
Opened 2020-06-10 21:28 UTC by ShawnZhong

Fix #29692

This PR makes sure that all `torch.rand*` functions support `generator=` and are properly documented. 

FYI, here is a summary of what we have on the master: 

| | Supported | Documented | 
| --- | --- | --- |
| rand | Yes | [No](https://pytorch.org/docs/master/generated/torch.rand.html) | 
| rand_like | No | [No](https://pytorch.org/docs/master/generated/torch.rand_like.html) | 
| randint | Yes | Yes | 
| randint_like |  No |  [No](https://pytorch.org/docs/master/generated/torch.randint_like.html) | 
| randn | Yes | [No](https://pytorch.org/docs/master/generated/torch.randn.html) | 
| randn_like | No | [No](https://pytorch.org/docs/master/generated/torch.randn_like.html) |
| randperm |  Yes | [No](https://pytorch.org/docs/master/generated/torch.randperm.html) |

The new docs are listed below: 

https://5826492-65600975-gh.circle-artifacts.com/0/docs/generated/torch.rand.html
https://5826492-65600975-gh.circle-artifacts.com/0/docs/generated/torch.rand_like.html
https://5826492-65600975-gh.circle-artifacts.com/0/docs/generated/torch.randint.html
https://5826492-65600975-gh.circle-artifacts.com/0/docs/generated/torch.randint_like.html
https://5826492-65600975-gh.circle-artifacts.com/0/docs/generated/torch.randn.html
https://5826492-65600975-gh.circle-artifacts.com/0/docs/generated/torch.randn_like.html
https://5826492-65600975-gh.circle-artifacts.com/0/docs/generated/torch.randperm.html

cc: @SsnL, @albanD

2020-06-12 19:38 UTC, ShawnZhong commented on torch/_torch_docs.py
> +factory_like_common_args = merge_dicts(common_args, parse_kwargs("""
The description of `generator` is in `common_args`.

2020-06-26 15:47 UTC, pbelevich requested changes
Also please replace [at::empty_like(self).uniform_(0, 1, gen);](https://github.com/pytorch/pytorch/blob/dfc7e71d136c726cf1c76edd92f9e82f4d5a7620/aten/src/ATen/native/Distributions.cpp#L477) with `at::rand_like(self, gen)`

2020-06-26 15:47 UTC, pbelevich commented on aten/src/ATen/native/TensorFactories.cpp
>    return result.random_(0, high, c10::nullopt);
Make is similar to `randint` and `randint_out` above: reuse new `randint_like` here
```suggestion
  return native::randint_like(self, high, c10::nullopt, options, optional_memory_format);
```

2020-06-26 15:47 UTC, pbelevich commented on aten/src/ATen/native/TensorFactories.cpp
>    return result.random_(low, high, c10::nullopt);
Make is similar to `randint` and `randint_out` above: reuse new `randint_like` here
```suggestion
  return native::randint_like(self, low, high, c10::nullopt, options, optional_memory_format);
```

2020-06-26 15:47 UTC, pbelevich commented on aten/src/ATen/native/TensorFactories.cpp
>    return result.normal_(0, 1, c10::nullopt);
reuse new `randn_like`:
```suggestion
  return native::randn_like(self, c10::nullopt, options, optional_memory_format);
```

2022-07-11 04:46 UTC, closed without merging