[WIP]Fix the issue that max_unpool2d and max_unpool3d cpp signature should…
pytorch/pytorch pull request #40155
Opened 2020-06-17 09:28 UTC by chengjinfang1216

… be similar(#39757)

2020-08-20 11:38 UTC, chengjinfang1216 commented
@ailzhang,  
could you please review current source code for me?
Note: about moving calculate output_size logic to cpp side, there seems to be a lot of code changes, so it is not included in this PR.

2020-09-22 09:17 UTC, chengjinfang1216 commented
hello @mruberry, is there any comment about this? I'm very sorry  I have been busy recently and forgot to check this issue, waiting for your reply

2020-09-22 16:52 UTC, mruberry commented
> hello @mruberry, is there any comment about this? I'm very sorry I have been busy recently and forgot to check this issue, waiting for your reply

Sorry @chengjinfang1216, looks like this slipped through the cracks. We'll take a look soon!

2020-09-24 20:23 UTC, heitorschueroff requested changes
This looks great!

I left a lot of comments but they are mostly around 2 issues. One is to do the shape check before accessing the elements in output_size and the other is to handle 2D and 3D cases properly in the new unpool1d code.

You can look at the max_unpool2d for an example on how to handle the 2D vs 3D (there is 4D vs 5D) case properly. I also linked to some original code that does not do this as well, it would be great if you could include a fix for it in this PR.

Looking forward for the updates and let me know if you have any questions.

2020-09-24 20:23 UTC, heitorschueroff commented on aten/src/ATen/native/MaxUnpooling.cpp
> +  auto self = self_.contiguous().unsqueeze(3);
The input could be 2D or 3D (batch), so you need to condition the unsqueeze on that. The original code actually has the same issue and does not handle non-batch input correctly. See here https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L694

Could you change both this and the code in functional.py to do the unsqueeze conditionally on whether the input is 2D or 3D?

2020-09-24 20:23 UTC, heitorschueroff commented on aten/src/ATen/native/MaxUnpooling.cpp
> +  return output.squeeze(3);
Squeeze must be conditioned on input dimension 2D or 3D

2020-09-24 20:23 UTC, heitorschueroff commented on aten/src/ATen/native/MaxUnpooling.cpp
> +Tensor& max_unpooling1d_backward_out_cpu(
This has the same issues with the forward. Namely, check shape before accessing elements and handle 2D vs 3D input size

2020-09-24 20:23 UTC, heitorschueroff commented on aten/src/ATen/native/cuda/MaxUnpooling.cu
> +static void max_unpooling2d_shape_check(
Maybe move this to Pool.h. There's already some utility shape checking code there for other pooling functions. Then call it on both CPU and CUDA

2020-09-24 20:23 UTC, heitorschueroff commented on aten/src/ATen/native/cuda/MaxUnpooling.cu
> +static void max_unpooling1d_shape_check(
Same here, move it to Pool.h.

2020-09-28 06:13 UTC, mruberry commented on aten/src/ATen/native/MaxUnpooling.cpp
> +  int dimw = 2;
Do this with an if/else block instead of adding

2020-09-28 06:28 UTC, mruberry commented on aten/src/ATen/native/MaxUnpooling.cpp
> +  if (self_.ndimension() == 4) {
Same issue with these additions as above. use an if/else for the number of dimensions to set these properly.

2020-09-28 06:28 UTC, mruberry commented on aten/src/ATen/native/MaxUnpooling.cpp
> +  int nslices;
Declare these when they're defined, not up front in the function.

2020-09-28 06:32 UTC, mruberry commented on torch/nn/functional.py
> +    return torch._C._nn.max_unpool1d(input, indices,
Is this PR combining multiple changes? That is, is this change required to fix the issue?

2020-09-28 06:42 UTC, mruberry commented
Hey @chengjinfang1216, thanks for the PR! I have a few questions/concerns:

- The new behavior needs to be tested. The tests can go in test_nn.py/TestNNDeviceType. Let us know if you have questions about writing tests.
- If this change is made, will it break existing C++ programs and serialized Torchscript that was using the existing signatures? This can be tested by scripting a simple function that uses these operations (from Python), saving that script, building with your change, and then verifying the script still runs as expected.
- Is this change as simple as possible? Do the 1d variants of this function need to be added to address the issue?

2020-09-29 04:03 UTC, chengjinfang1216 commented
> This looks great!
> 
> I left a lot of comments but they are mostly around 2 issues. One is to do the shape check before accessing the elements in output_size and the other is to handle 2D and 3D cases properly in the new unpool1d code.
> 
> You can look at the max_unpool2d for an example on how to handle the 2D vs 3D (there is 4D vs 5D) case properly. I also linked to some original code that does not do this as well, it would be great if you could include a fix for it in this PR.
> 
> Looking forward for the updates and let me know if you have any questions.

Hi, @heitorschueroff ， appreciate for your kind reply， I’ll take a look for detail.

2021-03-22 14:02 UTC, heitorschueroff commented
@chengjinfang1216 Are you still interested in pursuing this PR? If so, let me know so I can take another look and help you if you  are blocked in anyway. We really appreciate this contribution to the project.

2021-05-26 23:43 UTC, shubhambhokare1 commented
Was wondering, if there is going to be any work on this.
I am currently working on adding maxUnpool support to ONNX exporter as in the PR #55411

2021-05-26 23:45 UTC, shubhambhokare1 commented on aten/src/ATen/native/native_functions.yaml
> +- func: max_unpool2d_backward(Tensor grad_output, Tensor self, Tensor indices, int[2] output_size, int[2] stride, int[2] padding) -> Tensor
Would it be possible to add kernel_size as a param to these signatures?

2022-07-11 04:46 UTC, closed without merging