Add size checks for sparse tensor constructor
pytorch/pytorch pull request #4113
Opened 2017-12-11 15:03 UTC by zou3519

Fixes #4093

There was a bug where users could pass in indices to the sparse tensor constructor that imply tensors that have larger sizes than the size that was passed to the constructor. This adds error checking for that.

2017-12-12 15:10 UTC, zou3519 commented
@pytorchbot retest this please

2017-12-18 06:53 UTC, soumith requested changes

2017-12-18 06:53 UTC, soumith commented on aten/src/THS/generic/THSTensor.c
> +    THLongTensor *max_indices = THLongTensor_new();
`max_indices` is never freed. This is a memory leak.

2018-02-01 20:14 UTC, SsnL commented
Looks good, but please fix the merge conflicts. 

We should really move all of sparse tensor into ATen one day, i.e.. having _indices and _values both be ATen tensors.

2018-02-02 02:49 UTC, zou3519 commented
Rebased. The onnx-fb-univese check seems to have failed because a build script won't run?

2018-02-02 03:08 UTC, merged