Update NCCL from 2.4.8 to 2.7.6
pytorch/pytorch pull request #41608
Opened 2020-07-17 19:51 UTC by malfet

2020-07-18 00:59 UTC, ngimel approved these changes

2020-07-18 17:07 UTC, mrshenli requested changes
There are test failures when bumping up NCCL version since 2.6.4. 

@agolynski is working on fixing it. See #37506 and #40622

2020-07-20 18:32 UTC, mrshenli approved these changes
Thanks for fixing!!! `ci/circleci: pytorch_linux_xenial_py3_6_gcc5_4_ge_config_simple_test` is now green!

2020-07-20 19:06 UTC, agolynski approved these changes

2020-07-20 19:18 UTC, mrshenli commented
@agolynski mentioned that NCCL 2.7 might drop support for cuda 9.2, but we still have cuda 9.2 tests on master. Do we need to worry about this? @malfet @ngimel

2020-07-20 20:24 UTC, closed without merging