replace the white list from default mappings
pytorch/pytorch pull request #41802
Opened 2020-07-21 16:08 UTC by VinodSKumar

Replaced "whitelist" from default_mappings.py

2020-08-05 19:40 UTC, z-a-f commented
Please, rebase :)

2020-08-05 19:42 UTC, z-a-f approved these changes
Will recheck after rebase

2020-08-10 18:48 UTC, malfet commented on torch/quantization/quantize.py
> +def prepare(model, inplace=False, white_list=DEFAULT_QCONFIG_PROPAGATE_ALLOWED_LIST,
```suggestion
# Testing CI hooks
def prepare(model, inplace=False, white_list=DEFAULT_QCONFIG_PROPAGATE_ALLOWED_LIST,
```

2020-08-10 18:50 UTC, malfet commented on torch/quantization/quantize.py
> +# Testing CI hooks
Reverting temp change
```suggestion
```

2020-08-11 02:39 UTC, VinodSKumar commented
@z-a-f rebase has been done

2020-08-11 16:18 UTC, VinodSKumar commented
@z-a-f rebased again to since one CI was failing due to base env.

2020-08-12 18:25 UTC, VinodSKumar commented
Resolved new conflicts and rebased

2020-08-13 09:52 UTC, VinodSKumar commented
Rebased again to resolve conflicts

2020-08-13 20:09 UTC, malfet requested changes
You've forgot to rename the argument name
Also, you still have the merge conflicts (please feel free to post git commands you are using to rebase your change here)

2020-08-13 20:09 UTC, malfet commented on torch/quantization/_numeric_suite.py
> +    white_list=DEFAULT_NUMERIC_SUITE_COMPARE_MODEL_OUTPUT_ALLOWED_LIST,
Forgot to rename this argument
```suggestion
    allow_list=DEFAULT_NUMERIC_SUITE_COMPARE_MODEL_OUTPUT_ALLOWED_LIST,
```

2020-08-13 20:09 UTC, malfet commented on torch/quantization/_numeric_suite.py
> +    white_list=DEFAULT_NUMERIC_SUITE_COMPARE_MODEL_OUTPUT_ALLOWED_LIST,
This needs to be renamed as well
```suggestion
    allow_list=DEFAULT_NUMERIC_SUITE_COMPARE_MODEL_OUTPUT_ALLOWED_LIST,
```

2020-08-14 07:38 UTC, VinodSKumar commented
> You've forgot to rename the argument name
> Also, you still have the merge conflicts (please feel free to post git commands you are using to rebase your change here)

@malfet This PR was for the issue [41756](https://github.com/pytorch/pytorch/issues/41756) relating to default_mappings.py, I presumed that it should only be related to it. Thanks for the feedback will update the argument and its usage.

 Regarding the rebase steps, please find the history of git commands used in this branch, Please let me know if any more information is required.
git checkout remove_black_white_list 
git fetch upstream
git rebase upstream/master
git add torch/quantization/quantize.py 
git add torch/testing/_internal/common_quantization.py 
git commit -m "Resolve conflicts from master"
git rebase --abort //due to the commit, the changes were not there in the staging area, hence restarted the rebasing.
git fetch upstream
git rebase upstream/master
git add torch/quantization/quantize.py 
git add torch/testing/_internal/common_quantization.py 
git rebase --continue 
git push origin remove_black_white_list -f

// second time rebasing for new conflicts, usually below are the steps for rebasing
git fetch upstream
git rebase upstream/master
git add torch/testing/_internal/common_quantization.py 
git rebase --continue
git push origin remove_black_white_list -f

2020-08-21 06:13 UTC, z-a-f commented
LGTM, will leave to @malfet for landing

2020-08-26 20:08 UTC, z-a-f approved these changes
LGTM

2020-09-04 01:14 UTC, malfet approved these changes

2020-09-04 01:44 UTC, VinodSKumar commented
Rebased to double check the PR changes

2020-09-04 17:04 UTC, closed without merging