Replace whitelist with allowlist #41757
pytorch/pytorch pull request #42067
Opened 2020-07-25 18:53 UTC by kalmufti

Fixes #41757

I've replaced all the whitelist with allowlist for this issue.

2020-07-27 15:14 UTC, peterjc123 approved these changes

2020-07-27 17:05 UTC, malfet requested changes
This change is syntactically incomplete. Please also change the name of the macro in 
https://github.com/pytorch/pytorch/blob/96aaa311c0251d24decb9dc5da4957b7c590af6f/cmake/Whitelist.cmake#L23
And also rename this file to `Allowlist.cmake`

2020-07-27 19:05 UTC, kalmufti commented
Sure will do, should I replace all whitelisting within ```pytorch/cmake/Whitelist.cmake``` or just what's inside that macro?

2020-07-27 22:39 UTC, SplitInfinity commented
@kalmufti Replace all the instances as well please.

2020-07-28 13:42 UTC, malfet approved these changes

2020-07-28 15:03 UTC, closed without merging