Implement _infer_size with Sizes of 1-d tensors for tracing support
pytorch/pytorch pull request #42309
Opened 2020-07-30 14:45 UTC by wconstab

Fixes #40679

2020-07-30 14:46 UTC, wconstab commented
@suo I wanted to ask for initial feedback, this change seems to work for the repro snippet in #40679, but I still have to support other size-related functions, figure out how to properly test, and convince myself that the IR for the traced graph looks right.

2020-07-31 16:08 UTC, gchanan requested changes

2020-07-31 16:25 UTC, wconstab commented on torch/csrc/Module.cpp
> +std::vector<at::Tensor> THPUtils_unpackTensors(PyObject *arg);
oh definitely. i was just hacking, and didn't want to recompile too many files so put them here for now.. :)

2020-08-05 20:49 UTC, wconstab commented
Closing in favor of alternate approach #42631

2020-08-05 20:49 UTC, closed without merging