Python/C++ API Parity: TransformerDecoderLayer
pytorch/pytorch pull request #42587
Opened 2020-08-05 06:41 UTC by VinodSKumar

Fixes #[37756](https://github.com/pytorch/pytorch/issues/37756)

2020-08-05 23:00 UTC, glaringlee requested changes
I have a draft TransformerDecoderLayer here:
https://github.com/pytorch/pytorch/pull/42633

Sorry for post this out late, I was struggling on how to write test cases and where to put them.
Please take a look at my draft, we do have similar stuff there:))). 

I commented you code as much as possible and listed the reasons.

I put all the transformer tests into a new file test/api/transformer.cpp since module.cpp is getting bigger and bigger, we want to separate them into smaller files. but you can leave your test in module.cpp I can move them to transformer.cpp later, but please add CUDA coverage.

It seems your code did not trigger all of our CI test, let's see whether you code can trigger our CI test after you updated your code

2020-08-06 00:41 UTC, glaringlee requested changes

2020-08-06 00:41 UTC, glaringlee commented on torch/csrc/api/include/torch/nn/modules/transformer.h
> +  // void pretty_print(std::ostream& stream) const override;
Please implement this method if having time. Basically, just printout all the submodules it has

2020-08-06 21:12 UTC, closed without merging

2020-08-07 02:18 UTC, VinodSKumar commented
> I have a draft TransformerDecoderLayer here:
> #42633
> 
> Sorry for post this out late, I was struggling on how to write test cases and where to put them.
> Please take a look at my draft, we do have similar stuff there:))).
> 
> I commented you code as much as possible and listed the reasons.
> 
> I put all the transformer tests into a new file test/api/transformer.cpp since module.cpp is getting bigger and bigger, we want to separate them into smaller files. but you can leave your test in module.cpp I can move them to transformer.cpp later, but please add CUDA coverage.
> 
> It seems your code did not trigger all of our CI test, let's see whether you code can trigger our CI test after you updated your code

@glaringlee There was some issue with this PR in git, I have created a new PR  [42717](https://github.com/pytorch/pytorch/pull/42717) addressing all the review comments from this PR sorry for the trouble of raising a new PR, could you please help to continue the review on the new PR.