Python/C++ API Parity: TransformerDecoder
pytorch/pytorch pull request #42886
Opened 2020-08-11 22:37 UTC by VinodSKumar

Fixes #{[37756](https://github.com/pytorch/pytorch/issues/37756)}

2020-08-23 17:35 UTC, VinodSKumar commented
@glaringlee The PR has been set to review state, still it says as draft[WIP]. Is there something that I need to do for it.

2020-08-24 20:45 UTC, glaringlee requested changes

2020-08-24 20:45 UTC, glaringlee commented on test/cpp/api/transformer.cpp
> +  at::Tensor decoder_input = torch::tensor({{{20, 30, 40, 50}}},
Please use torch::Tensor instead of at::Tensor for the following lines where ever at::Tensor is there.

2020-08-24 20:45 UTC, glaringlee commented on test/cpp/api/transformer.cpp
> +  TransformerDecoder multi_layer_model(
multi_layer_model is defined here, but `model->to()` is called in the following lines which is not correct.
You can either call multi_layer_model->to() or just use `model = TransformerDecoder(TransformerDecoderOptions(decoder_layer, 2));`

2020-08-24 20:45 UTC, glaringlee commented on test/cpp/api/transformer.cpp
> +  TransformerDecoder multi_layer_model2(
Same here, decoder defined and the one calls ->to() are not consistent.

2020-08-24 20:45 UTC, glaringlee commented on test/cpp/api/transformer.cpp
> +  TransformerDecoder multi_layer_norm_model(
Same here, this inconsistency caused illegal memory access in the layer ASSERT_TRUE comparison.
I recommend always use `model = TransformerDecoder(...)`

2020-08-24 20:45 UTC, glaringlee commented on test/cpp/api/transformer.cpp
> +  TransformerDecoder multi_layer_norm_model2(
Same here as above.

2020-08-24 20:45 UTC, glaringlee commented on test/cpp/api/transformer.cpp
> +  at::Tensor t_key_padding_mask = {};
torch::Tensor instead of at::Tensor

2020-08-24 20:45 UTC, glaringlee commented on test/cpp/api/transformer.cpp
>    at::Tensor decoder_input = torch::tensor({{{20, 30, 40, 50}}},
torch::Tensor instead of at::Tensor

2020-08-24 20:45 UTC, glaringlee commented on test/cpp/api/transformer.cpp
> +  at::Tensor decoder_input = torch::tensor({{{20, 30, 40, 50}}},
use torch::Tensor instead of at::Tensor for the following lines. at scope is internal.

2020-08-24 20:45 UTC, glaringlee commented on test/cpp/api/transformer.cpp
> +  at::Tensor t_mask = {};
torch::Tensor for the following 3 lines

2020-08-27 22:54 UTC, glaringlee approved these changes
LGTM now, thanks a lot for contributing.

2020-08-29 03:15 UTC, closed without merging