[Distributed] DeleteKey API for c10d TCP Store
pytorch/pytorch pull request #43963
Opened 2020-09-01 17:39 UTC by osalpekar

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Added a DeleteKey API for the TCP Store

Differential Revision: [D23009117](https://our.internmc.facebook.com/intern/diff/D23009117/)

**NOTE FOR REVIEWERS**: This PR has internal Facebook specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D23009117/)!

2020-09-23 23:51 UTC, pritamdamania87 requested changes
Requesting changes since I think the API should return a bool

2020-09-23 23:51 UTC, pritamdamania87 commented on caffe2/distributed/file_store_handler.cc
> +  CHECK(false) << "deleteKey not implemented for FileStoreHandler";
`TORCH_CHECK`?

2020-09-23 23:51 UTC, pritamdamania87 commented on torch/lib/c10d/test/TCPStoreTest.cpp
> +    numKeys = serverStore->getNumKeys();
nit: probably also test `getKey` returns an error.

2020-09-23 23:51 UTC, pritamdamania87 commented on torch/lib/c10d/Store.hpp
> +  virtual void deleteKey(const std::string& key) = 0;
Usually a delete API returns true/false about whether the key was removed or not. I think this should return a bool.

2020-09-23 23:51 UTC, pritamdamania87 commented on torch/csrc/distributed/c10d/init.cpp
>                "add",
All of these would need docs for python users. We can do that in a separate PR.

2020-09-25 19:32 UTC, pritamdamania87 approved these changes

2020-09-25 19:32 UTC, pritamdamania87 commented on torch/lib/c10d/test/TCPStoreTest.cpp
> +    numKeys = serverStore->getNumKeys();
Can we add a test here for calling `getKey()` on a delete key?

2020-09-26 07:54 UTC, closed without merging

2020-09-27 18:57 UTC, ngimel commented
Reverting, as it is breaking OSS build
```
08:04:53 /var/lib/jenkins/workspace/caffe2/distributed/redis_store_handler.cc: In member function ‘virtual bool caffe2::RedisStoreHandler::deleteKey(const string&)’:
08:04:53 /var/lib/jenkins/workspace/caffe2/distributed/redis_store_handler.cc:86:1: error: no return statement in function returning non-void [-Werror=return-type]
08:04:53  }
08:04:53  ^
08:04:53 cc1plus: some warnings being treated as errors
08:04:53 caffe2/CMakeFiles/torch_cpu.dir/build.make:10370: recipe for target 'caffe2/CMakeFiles/torch_cpu.dir/distributed/redis_store_handler.cc.o' failed
08:04:53 make[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/distributed/redis_store_handler.cc.o] Error 1
08:04:53 make[2]: *** Waiting for unfinished jobs....
08:04:58 CMakeFiles/Makefile2:6884: recipe for target 'caffe2/CMakeFiles/torch_cpu.dir/all' failed
08:04:58 make[1]: *** [caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
08:04:58 Makefile:140: recipe for target 'all' failed
08:04:58 make: *** [all] Error 2
```
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/pytorch-linux-bionic-rocm3.7-py3.6-build/5732//console