[JIT] Add reference semantics to TorchScript classes
pytorch/pytorch pull request #44324
Opened 2020-09-08 20:30 UTC by SplitInfinity

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

**Summary**
This commit adds reference semantics to TorchScript class types;
modifications made to them within TorchScript will be visible in Python.

**Test Plan**
This commit adds a unit test to `TestClassType` that checks that
modifications made to a class type instance passed into TorchScript are
visible in Python after executing the scripted function or module.

**Fixes**
This commit closes #41421.

2020-09-29 00:48 UTC, gmagogsfm commented on torch/csrc/jit/python/python_sugared_value.cpp
> +  obj = py::module::import("inspect").attr("unwrap")(obj);
Overwriting `obj` changes behavior of all following logic, is this intended?

2020-09-29 00:48 UTC, gmagogsfm commented on torch/csrc/jit/python/script_init.cpp
> +              "equals",
should we just consider overriding `__eq__` so that comparison in python is more natural?

2020-09-29 00:48 UTC, gmagogsfm commented on torch/jit/_recursive.py
> +import pdb
accident?

2020-12-10 22:33 UTC, SplitInfinity commented on torch/csrc/jit/api/object.h
> +      return std::make_tuple(prop.name, Method(_ivalue(), prop.getter), setter);
The getter must exist but the setter is optional (for the TorchScript implementation of properties).

2020-12-10 22:36 UTC, SplitInfinity commented on test/jit/test_class_type.py
> +        with self.assertRaisesRegex(TypeError, r"takes 2 positional arguments but 4 were given"):
I think this is a consequence of the decorator I added; `Base` is now an instance of `ScriptClassWrapper`, which cannot be inherited from.

2020-12-15 17:50 UTC, SplitInfinity commented
@eellison curious for your thoughts on this, other reviewers seem to be busy.

2020-12-16 01:20 UTC, eellison commented
@gmagogsfm do you mind reviewing ?  dont know that I have bandwidth for 500+ line PR right now

2020-12-18 21:25 UTC, eellison commented
@suo is a good person to review this

2021-01-29 21:29 UTC, suo requested changes

2021-02-05 00:17 UTC, ppwwyyxx commented
I've tried this PR and it now allows me to run a scripted detectron2 model in C++. Looking forward to it!

2021-06-02 06:40 UTC, gmagogsfm approved these changes

2021-06-02 06:40 UTC, gmagogsfm commented on torch/jit/_script.py
>      # No-op for modules and functions that are already scripted
```suggestion
    # No-op for modules, functions, class instances that are already scripted
```

2021-06-02 06:40 UTC, gmagogsfm commented on torch/jit/_script.py
> +    class RecursiveScriptClass(object):
What does this mean? Has this comment been resolved offline?

2021-06-28 23:56 UTC, SplitInfinity commented
@splitinfinity has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D24912807).

2021-06-29 00:02 UTC, SplitInfinity commented
@splitinfinity has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D24912807).

2021-06-29 00:13 UTC, SplitInfinity commented on torch/jit/_script.py
> +                return super(RecursiveScriptClass, self).__getattr__(attr)  # type: ignore
```
error: "__getattr__" undefined in superclass  [misc]
```

2021-06-29 00:23 UTC, SplitInfinity commented
@splitinfinity has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D24912807).

2021-06-30 21:28 UTC, closed without merging