use non-overflowing divide in cuda kernel util GET_BLOCKS
pytorch/pytorch pull request #44391
Opened 2020-09-09 15:56 UTC by walterddr

Fixes #{43476}.

2020-09-09 16:14 UTC, malfet commented on aten/src/ATen/cuda/detail/KernelUtils.h
> +  return N / CUDA_NUM_THREADS + (N % CUDA_NUM_THREADS == 0 ? 0 : 1);
Is this for one dimensional kernel? In that case, shouldn't the maximum number of blocks be capped to 65535?

2020-09-09 16:32 UTC, malfet commented on aten/src/ATen/cuda/detail/KernelUtils.h
> +  return N / CUDA_NUM_THREADS + (N % CUDA_NUM_THREADS == 0 ? 0 : 1);
Would that be equivalent, considering that it's already be asserted that N > 0?
```suggestion
  return 1 + (N -1 ) / CUDA_NUM_THREADS;
```

2020-09-09 16:39 UTC, malfet commented
@walterddr , thank you for the fix, but can you please just merge two variants of GET_BLOCKS into:
```
inline int GET_BLOCKS(const int64_t N) {
   AT_ASSERTM(N > 0, "CUDA kernel launch blocks must be positive, but got N=", N);
  constexpr int64_t max_int = std::numeric_limits<int>::max();
  // Round up division for positive number that can not cause integer overflow
  auto block_num = (N - 1) / CUDA_NUM_THREADS + 1; 
  return static_cast<int>(std::min(block_num, max_int));
}
```

2020-09-09 16:41 UTC, malfet requested changes
Please fold two version of `GET_BLOCK` together as suggested in comment, that would return a correct number of blocks if N is greater than int32_t

2020-09-09 17:01 UTC, ngimel approved these changes

2020-09-09 17:41 UTC, malfet approved these changes

2020-09-09 17:41 UTC, malfet commented on aten/src/ATen/cuda/detail/KernelUtils.h
> +  return static_cast<int>(std::min(block_num, max_int));
Nit (from the assert above we already know that it can be safely cast to int32
```suggestion
  return static_cast<int>(block_num);
```

2020-09-09 23:23 UTC, closed without merging

2020-09-10 09:55 UTC, artsobolev commented
Wait, but there are still places that compute `GET_BLOCKS`'s argument in `int` and could overflow.

https://github.com/pytorch/pytorch/blob/c010ef7f0c6d837809a7e973048afac76373e3de/aten/src/ATen/native/cuda/vol2col.cuh#L107

https://github.com/pytorch/pytorch/blob/c010ef7f0c6d837809a7e973048afac76373e3de/aten/src/THCUNN/generic/SpatialDepthwiseConvolution.cu#L71

https://github.com/pytorch/pytorch/blob/c010ef7f0c6d837809a7e973048afac76373e3de/aten/src/THCUNN/generic/SpatialDepthwiseConvolution.cu#L154

https://github.com/pytorch/pytorch/blob/c010ef7f0c6d837809a7e973048afac76373e3de/aten/src/ATen/native/cuda/MaxUnpooling.cu#L431

And probably some other places as well, github's search is imperfect.

2020-09-10 15:33 UTC, walterddr commented
that's true but it wasn't the overflow int divide issue this PR wa addressing. I will follow up in #44472.