[WIP] Adding profiling capability to ddp collective functions
pytorch/pytorch pull request #44436
Opened 2020-09-09 22:37 UTC by mrzzd

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Differential Revision: [D23611359](https://our.internmc.facebook.com/intern/diff/D23611359/)

2020-09-11 18:41 UTC, pritamdamania87 commented
Could you update the PR summary to include a sample of what the autograd profiler output looks like with these changes?

2020-09-11 20:49 UTC, rohan-varma commented on torch/distributed/distributed_c10d.py
> +def async_collective(func):
If this isn't meant to be used directly by PT users, maybe prefix it with an `_`?

2020-09-11 20:50 UTC, rohan-varma commented on torch/distributed/distributed_c10d.py
> +        if work is None:
What are the semantics here? If I call `work.wait()` in a collective and decorate with `@async_collective`, will it not be profiled correctly? If we want to use `async_collective` would the function have to return a `work` object?

2020-09-11 20:50 UTC, rohan-varma commented on torch/distributed/distributed_c10d.py
> +            rf = torch.autograd.profiler.record_function(func.__name__)
Should we somehow distinguish between async and sync calls in the profiling output?

2020-09-11 20:52 UTC, rohan-varma commented
Thank you for working on this! I was concurrently putting together an RFC for DDP/collectives profiling and hoping to get input from @pritamdamania87 and @ilia-cher, but I will take this PR into account as well while preparing the RFC.

2020-09-11 22:18 UTC, pritamdamania87 commented on torch/distributed/distributed_c10d.py
> +                    fut = rf._call_end_callbacks_on_future(work.get_future())
`get_future` currently only works for NCCL, I'm wondering if there is away to ensure `with record_function` works for async cuda events.

2020-09-12 00:48 UTC, pritamdamania87 requested changes
Awesome work! I think the major change we need is that the profiling should probably be at the C++ level such that C++ invocations are profiled too.

2020-09-12 00:48 UTC, pritamdamania87 commented on torch/distributed/distributed_c10d.py
> +def async_collective(func):
As @rohan-varma mentioned in a separate thread, we could call `process_group->allreduce()` from C++ (ex: c10d/reducer.cpp). Let's put all the RecordFunction logic in ProcessGroupGloo.cpp and ProcessGroupNCCL.cpp to ensure pure C++ invocations are profiled as well.

2020-09-12 00:48 UTC, pritamdamania87 commented on torch/testing/_internal/distributed/distributed_test.py
> +                        work._get_profiling_future().wait()
What is the reason to have these 3 lines? Shouldn't the profiling work even without this?

2020-09-12 00:48 UTC, pritamdamania87 commented on torch/lib/c10d/ProcessGroupGloo.hpp
> +      resultFuture = c10::make_intrusive<c10::ivalue::Future>(
nit: `resultFuture_` for private members.

2020-09-12 00:48 UTC, pritamdamania87 commented on torch/lib/c10d/ProcessGroupGloo.hpp
> +      work->resultFuture->markCompleted();
Shouldn't this be done after `work->finish()`?

2020-09-12 00:48 UTC, pritamdamania87 commented on torch/lib/c10d/ProcessGroupGloo.hpp
> +    c10::intrusive_ptr<c10::ivalue::Future> getFuture() override {
We should update our docs for `get_future` to reflect this now works for Glooo as well: https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/c10d/init.cpp#L756 (except send/recv).

2020-09-12 00:48 UTC, pritamdamania87 commented on torch/testing/_internal/distributed/distributed_test.py
> +                self.assertGreater(recv_event.cpu_time, 0)
We should proobably validate cuda time as well for NCCL?

2020-09-12 00:48 UTC, pritamdamania87 commented on torch/testing/_internal/distributed/distributed_test.py
> +                group_id,
Would be nice to add tests for all the collectives we have enabled to ensure they're profiled correctly.

2020-10-16 15:03 UTC, mrzzd commented
Closing it in favour of #46471

2020-10-16 15:03 UTC, closed without merging