[WIP][numpy] torch.{all, any} : Extend Dtype Support
pytorch/pytorch pull request #44790
Opened 2020-09-16 15:55 UTC by kshitij12345

Reference #44779

2020-10-19 15:24 UTC, heitorschueroff approved these changes
LGTM. Thanks for this PR, it's a very welcomed change.

Note: Now that torch.all and torch.any supports all dtypes, we should document it in the public APIs as mentioned here https://github.com/pytorch/pytorch/issues/44779, but this can be a separate PR.

2020-10-19 15:30 UTC, heitorschueroff requested changes
It looks like the XLA failures are related to the changes. Could you look into what's causing it please?

2020-10-19 15:53 UTC, kshitij12345 commented
@heitorschueroff Thanks for looking at it. 

As for XLA, I m not really sure what is happening. 
Maybe @JackCaoG can have a look. 

Thanks!

2020-11-05 18:52 UTC, JackCaoG commented
@kshitij12345 XLA change is ready, I will merge it when this pr is merged.

2020-11-06 13:48 UTC, kshitij12345 commented
@heitorschueroff Have fixed the conflict. ROCm failure looks irrelevant.

2020-11-06 13:59 UTC, heitorschueroff commented
> @heitorschueroff Have fixed the conflict. ROCm failure looks irrelevant.

Thank you for this contribution, I'm important your changes now.

2020-11-06 14:38 UTC, heitorschueroff approved these changes

2020-11-09 21:28 UTC, heitorschueroff requested changes
It looks like I missed some details in my review. Our internal tests on phabricator are complaining. I left some comments from phabricator, they should be fairly quick to fix and then I can land it without problems.

2020-11-09 21:28 UTC, heitorschueroff commented on aten/src/ATen/native/cpu/ReduceOpsKernel.cpp
> +  if (c10::isIntegralType(iter.dtype(), /*include_bool=*/true)) {
include_bool -> includeBool

2020-11-09 21:28 UTC, heitorschueroff commented on aten/src/ATen/native/cpu/ReduceOpsKernel.cpp
> +  if (c10::isIntegralType(iter.dtype(), /*include_bool=*/true)) {
include_bool -> includeBool

2020-11-09 21:28 UTC, heitorschueroff commented on aten/src/ATen/native/cpu/ReduceOpsKernel.cpp
> +        [=](uint8_t a, uint8_t b) -> uint8_t { return a && b; },
Avoid the implicit cast with:
`[=](uint8_t a, uint8_t b) -> uint8_t { return ((a && b) ? 1 : 0); },`

2020-11-09 21:28 UTC, heitorschueroff commented on aten/src/ATen/native/cpu/ReduceOpsKernel.cpp
> +        [=](uint8_t a, uint8_t b) -> uint8_t { return a || b; },
Avoid the implicit cast with:
[=](uint8_t a, uint8_t b) -> uint8_t { return ((a && b) ? 1 : 0); },

2020-11-09 21:28 UTC, heitorschueroff commented on aten/src/ATen/native/cpu/ReduceOpsKernel.cpp
> +            c[i] = a[i] && b[i];
Avoid implicit cast with:
`c[i] = ((a[i] && b[i]) ? 1 : 0);`

2020-11-09 21:28 UTC, heitorschueroff commented on aten/src/ATen/native/cpu/ReduceOpsKernel.cpp
> +            c[i] = a[i] || b[i];
Avoid implicit cast with:
`c[i] = ((a[i] && b[i]) ? 1 : 0);`

2020-11-10 14:34 UTC, kshitij12345 commented
@heitorschueroff Done.

2020-11-10 15:14 UTC, heitorschueroff approved these changes

2020-11-11 01:14 UTC, closed without merging

2020-11-11 05:07 UTC, kshitij12345 commented
@JackCaoG Please merge the XLA fix. Thanks!

2020-11-11 18:48 UTC, ngimel commented
@kshitij12345 there are a few problems with this PR
1) as noted already, it breaks XLA CI, @heitorschueroff please avoid landing things before XLA fix is merged
2) it produces results of the same dtype as input, this is different from numpy:
```
In [9]: a=torch.randn(3,3)                                                                                                                                                                    
In [10]: anp=a.numpy()                                                                                                                                                                        
In [11]: np.all(anp, 0)                                                                                                                                                                       
Out[11]: array([ True,  True,  True])
In [12]: a.all(0)                                                                                                                                                                             
Out[12]: tensor([1., 1., 1.])
```
3) it introduces performance cliff for non-bool input types, because it does not use binary_kernel_reduce_vec, and instead uses binary_kernel_reduce which is much (5-10x) slower.

Can you please work on fixing 2) and 3) ?

2020-11-11 19:12 UTC, JackCaoG commented
> @kshitij12345 there are a few problems with this PR
> 
> 1. as noted already, it breaks XLA CI, @heitorschueroff please avoid landing things before XLA fix is merged
> 2. it produces results of the same dtype as input, this is different from numpy:
> 
> ```
> In [9]: a=torch.randn(3,3)                                                                                                                                                                    
> In [10]: anp=a.numpy()                                                                                                                                                                        
> In [11]: np.all(anp, 0)                                                                                                                                                                       
> Out[11]: array([ True,  True,  True])
> In [12]: a.all(0)                                                                                                                                                                             
> Out[12]: tensor([1., 1., 1.])
> ```
> 
> 1. it introduces performance cliff for non-bool input types, because it does not use binary_kernel_reduce_vec, and instead uses binary_kernel_reduce which is much (5-10x) slower.
> 
> Can you please work on fixing 2) and 3) ?

I merged XLA change. If this pr will be reverted I will revert the xla pr as well. Otherwise I will work on a companion pr to fix the result type.

2020-11-11 22:05 UTC, gchanan commented
I'd look at the `logical_or` and `logical_and` kernels for how to get the dtypes correct; note that it's a little different because of the performance issue @ngimel mentioned above.

2020-11-11 23:04 UTC, ngimel commented
Also please don't forget to update documentation.

2020-11-12 06:49 UTC, kshitij12345 commented
@ngimel 
For 2, it would be a BC-Breaking to change the result-type to `bool`,
I think it would be better to add a warning first otherwise it may break code for users. Let me know what you think about that.

Behaviour in previous version (1.5.1)
```python
>>> import torch
>>> torch.__version__
'1.5.1+cu101'
>>> x = torch.zeros(3,3)
>>> x.to(torch.uint8).all()
tensor(0, dtype=torch.uint8)
>>> x.to(torch.bool).all()
tensor(False)
```

2020-11-12 07:05 UTC, ngimel commented
cc @mruberry for deprecating return type for uint8. In any case, for all other types there are no bc breaking concerns, so we should implement correct behavior.

2020-11-12 07:07 UTC, mruberry commented
I would try to update the uint8 behavior to be consistent and document the change as BC-breaking. If a scripted network relies on the current behavior (extremely unlikely) we can write an upgrader.