Add HalfToFloat + FloatToHalf operators to PyTorch
pytorch/pytorch pull request #45092
Opened 2020-09-21 22:31 UTC by radkris-git

Summary:
Adding two operators
1. at::float_to_half -> Converts FP32 tensor to FP16 tensor
2. at::half_to_float -> Converts FP16 tensor to FP32 tensor.

These operators internally use the kernel provided by FBGeMM. Both C2 and PT will use the same FBGeMM kernel underneath.

Test Plan: buck test caffe2/test:conversion_ops

Differential Revision: D23824869

2020-09-22 20:59 UTC, supriyar commented on aten/src/ATen/native/HalfFloatOps.cpp
> +  #ifdef CPU_CAPABILITY_AVX2
Can we combine these two `ifdef` statements?

2020-09-22 21:00 UTC, supriyar commented on aten/src/ATen/native/HalfFloatOps.cpp
> +Tensor half_to_float(const Tensor& input) {
Some documentation on these conversion ops wil be useful. How is this different from the existing `.to(dtype)` in pytorch?

2020-09-22 21:00 UTC, supriyar commented on test/test_half_float_ops.py
> +        def get_c2_result(weights):
I don't think we need to test against C2 for this. Can we add a reference implementation in PT itself?

2020-10-15 19:10 UTC, dzhulgakov requested changes
Please don't add separate ops. There's existing API `x.to(torch.float16)` or `x.half()`. It probably has a terrible implementation on CPU (vanilla tensor iterator) and we should bind it to fbgemm kernel instead. @ngimel can help you with pointers on how to do that

2020-10-15 20:01 UTC, ngimel commented
Agree with @dzhulgakov, you should provide a more efficient implementation for x.float() and x.half() that go through .to method. The implementations for the `.to` are in TensorConversions.cpp, you are interested in this overload of .to https://github.com/pytorch/pytorch/blob/c1141b6f68dc7a842f3d947ffb3c9f261940d31d/aten/src/ATen/native/TensorConversions.cpp#L86 and to_impl that it calls.

2020-11-10 20:04 UTC, closed without merging