ONNX export: propagate node metadata across passes
pytorch/pytorch pull request #45256
Opened 2020-09-24 02:28 UTC by tbennun

Fixes #45255 

Mostly straightforward. Only downside in this PR is the lack of more scalable way to check for all newly-created nodes in `callPySymbolicFunction`. The other options were:
* Create a scope within the node's scope and loop through all nodes that correspond to the scope. The code would still need to loop through all nodes.
* Add extra state to the graph (no good reason to do so).
* Add extra state to the ONNX exporter, since python calls go back to `g.op(...)` (no good reason to do so, also not very pythonic).

2021-08-31 22:32 UTC, garymm requested changes
@tbennun thanks for this change, it's awesome!

Could you please add a unit test?
The sourceRange appears to be exposed to Python so you could add it to test/jit/test_onnx_export.py

Please also rebase.

2021-08-31 22:32 UTC, garymm commented on torch/csrc/jit/passes/onnx.cpp
> +    for (auto node : g->nodes())
please add curly braces around loop body

2021-08-31 23:41 UTC, garymm commented
@shubhambhokare1 CC

2021-09-15 00:00 UTC, tbennun commented
Thanks for reviewing! Will take care of it ASAP.

2021-10-07 01:25 UTC, tbennun commented
@garymm yes, apologies for the delay. Due to a deadline this Friday, I'll take care of it by the beginning of the next week (the 12th EOD). I already rebased and performed the change in the comment but still need to add the unit test.

2021-10-07 21:57 UTC, garymm requested changes
Thanks! Once you've made the minor changes I think this is ready to go, but we'll need a Facebook employee to actually merge it.

2021-10-08 16:23 UTC, garymm approved these changes

2021-10-08 16:24 UTC, garymm commented
@msaroufim please import this community contribution.

2021-10-21 18:18 UTC, malfet approved these changes

2021-10-21 18:49 UTC, closed without merging