Change codecov comment style to be less verbose
pytorch/pytorch pull request #46499
Opened 2020-10-16 22:03 UTC by malfet

Do not post comments if there are no changes in coverage and post only diff stats

Partially addresses an issue raised in https://github.com/pytorch/pytorch/issues/44187

2020-10-16 22:06 UTC, walterddr requested changes

2020-10-16 22:06 UTC, walterddr commented on codecov.yml
> +  behavior: oce
once?

2020-10-16 23:19 UTC, walterddr approved these changes

2020-10-17 00:04 UTC, seemethere approved these changes

2020-10-17 14:58 UTC, walterddr approved these changes

2020-10-18 21:15 UTC, closed without merging

2020-10-19 16:52 UTC, rgommers commented
Thanks @malfet, this is helpful.