gate load_library tests behding BUILD_TEST=1
pytorch/pytorch pull request #46556
Opened 2020-10-19 19:31 UTC by suo

2020-10-19 20:52 UTC, SplitInfinity commented
I think I'm missing some context; what's this for and why is it needed?

2020-10-20 00:52 UTC, malfet approved these changes

2020-10-20 03:57 UTC, malfet requested changes
Sorry, but where is the master PR for this diff?

2020-10-21 01:57 UTC, seemethere approved these changes

2020-10-21 01:57 UTC, merged

2020-10-21 22:18 UTC, seemethere commented
Doesn't actually look like this resolved the issues we were hoping it was going to resolve.

Tests with `v1.7.0-rc3`:
https://app.circleci.com/pipelines/github/pytorch/pytorch-integration-testing/57/workflows/a7266b2a-a504-4db3-b919-7335bc5385b8/jobs/328