Add CUDA 11.1 CI
pytorch/pytorch pull request #46616
Opened 2020-10-20 21:25 UTC by zasdfgbnm

Fixes #{issue number}

2020-10-21 17:32 UTC, malfet requested changes
LGTM, but is there a reason why you don't want to just replace 11.0 with 11.1 config?

2020-10-21 17:45 UTC, zasdfgbnm commented
@malfet That makes sense. I have modified this PR to keep 11.1 CI only

2020-10-21 17:46 UTC, malfet approved these changes

2020-10-27 23:02 UTC, closed without merging

2020-10-28 17:48 UTC, malfet commented
@zasdfgbnm have to unland it as it caused CI failures on a newly added config, see https://app.circleci.com/pipelines/github/pytorch/pytorch/232112/workflows/4131d4ca-cd51-44e3-8e6c-b1c3555c62fa/jobs/8523970