Add instruction on how to handle the potential linker error on Linux
pytorch/pytorch pull request #47593
Opened 2020-11-09 08:25 UTC by skyline75489

The original issue is #16683, which contains a https://github.com/pytorch/pytorch/issues/16683#issuecomment-459982988 that suggests manually un-shadowing the `ld`. 

A better approach can be found at https://github.com/ContinuumIO/anaconda-issues/issues/11152#issuecomment-573120962, which suggests that using a newer version can effectively fix this. 

It took me quite some time to realize that this is in fact an issue caused by Anaconda. I think we should add it in README.

2020-11-09 09:04 UTC, skyline75489 commented on README.md
> +If you are installing from source, you will need Python 3.6.2 or later and a C++14 compiler. Also, we highly recommend installing an [Anaconda](https://www.anaconda.com/distribution/#download-section
The minimum version supported is `3.6.2` in `setup.py`.

2020-11-09 09:15 UTC, skyline75489 commented on README.md
>  On macOS
I don't know if this also happens on macOS.  Based on my experience and the original issue, this is a reproducible issue on Linux.

Windows is spared from this issue.

2020-11-09 22:00 UTC, heitorschueroff requested changes
Thanks for your contribution. Just a small typo fix and it will be good.

2020-11-10 00:44 UTC, skyline75489 commented on README.md
> +This is caused by `ld` from Conda environment shaddowing the system `ld`. You should use a newer version of Python that fixes this issue. The recommended Python version is 3.6.10+, 3.7.6+ and 3.8.1+.
Thanks for the prompt reply. Fixed.

2020-11-10 02:15 UTC, skyline75489 commented on README.md
> +If you are installing from source, you will need Python 3.6.2 or later and a C++14 compiler. Also, we highly recommend installing an [Anaconda](https://www.anaconda.com/distribution/#download-section
This actually will cause build failure on current master with Python < 3.6.2, due to the usage of [typing.NoReturn](https://docs.python.org/3/library/typing.html#typing.NoReturn) which was first introduced in 3.6.2

2020-11-10 16:14 UTC, heitorschueroff approved these changes

2020-11-11 22:29 UTC, closed without merging