Fix override pickle redo
pytorch/pytorch pull request #47732
Opened 2020-11-11 07:15 UTC by hameerabbasi

Fixes #47051 
Redo of #47115

2020-11-11 17:33 UTC, ezyang requested changes
Pending investigation why we broke things.

@hameerabbasi a start to make this patch better, would be to make sure our Pickle format doesn't change for non-subclasses of tensors. This means that when `type is Tensor`, we must not use `_rebuild_from_type` as the rebuild function, as these pickles won't be accessible from earlier version. Also would be great to add big warning blinky lights to this function warning against edits.

2020-12-09 06:41 UTC, hameerabbasi commented
Only failed test is on the C++ layer, which wasn't touched in this PR.

2020-12-10 16:41 UTC, ezyang commented on torch/tensor.py
> +            return self._reduce_ex_internal(proto)
Good

2021-01-18 12:29 UTC, hameerabbasi commented
Anything else needed here?

2021-01-20 14:09 UTC, hameerabbasi commented
@ezyang This PR could use some attention too.

2021-01-21 14:56 UTC, ezyang commented
This one is going to take a little more time because I need to root cause why internal builds failed when we put this change in.

2021-01-29 16:42 UTC, ezyang approved these changes
crypten test no longer fails with the BC-compatible pickle change

2021-02-01 15:36 UTC, closed without merging