distributed_test: Map rank to GPU accordingly
pytorch/pytorch pull request #47898
Opened 2020-11-13 05:46 UTC by jaglinux

If world_size is lesser than or equal to number of GPU's available
then the rank can be directly mapped to corresponding GPU.
This fixes the issue referenced in #45435 and #47629

For world_size = 3 and number of GPU's = 8, the rank to GPU mapping
will be 0,2,4. This is due to the introduction of barrier,
(refer PR #45181)
the tensors in barrier is mapped to cuda0,1,2 and the tensors in the
actual test cases are mapped to cuda0,2,4 resulting in different streams and
leading to timeout. This issue is specific to default process group.
Issue is not observed in new process group since the streams are created again
after the initial barrier call.

This patch maps the rank to corresponding GPU's when the world_size is
less than or equal to the number of GPU's, in this case 0,1,2

Note: The barrier function in distributed_c10d.py should include new parameter
to specify the tensor or rank to GPU mapping. In that case, this patch will be
redundant but harmless since the tests can specify the tensors with appropriate
GPU rankings.

Fixes #47629

2020-11-13 05:48 UTC, jaglinux commented
@jeffdaily @pruthvistony please review

2020-11-13 17:00 UTC, rohan-varma approved these changes
Thank you for this fix! @jeffdaily Would you be able to verify if this fixes the issue on your end? @jaglinux Would you mind signing the CLA when you get a chance? Thank you!

2020-11-13 18:08 UTC, jaglinux commented
@rohan-varma thanks for the review. I signed CLA.
I have tested the patch on 8 GPU machine with world_size as 3.
All the test cases including the global test cases or the default pg passed.

2020-11-13 18:25 UTC, jeffdaily requested changes
@rohan-varma I completely trust @jaglinux here.  He's part of our ROCm PyTorch team and was leading the triage effort for these related issues.  He's done all the work of fixing and testing and we've had many discussions about it.  Besides the suggested comment change, we're all good!

2020-11-13 18:25 UTC, jeffdaily commented on torch/testing/_internal/distributed/distributed_test.py
> +            """
```suggestion
            # If rank is lesser than or equal to number of available GPU's
            # then each rank can be mapped to corresponding GPU.
```

2020-11-13 18:25 UTC, jeffdaily commented on torch/testing/_internal/distributed/distributed_test.py
> +            """
nit: multi-line comment should use `#`.

2020-11-13 18:49 UTC, jeffdaily approved these changes

2020-11-14 03:05 UTC, rohan-varma commented
Did some local testing and I believe this PR should also fix https://github.com/pytorch/pytorch/issues/47676, https://github.com/pytorch/pytorch/issues/47675, and https://github.com/pytorch/pytorch/issues/47676

2020-11-14 08:04 UTC, closed without merging