Add libATen.so symlink.
pytorch/pytorch pull request #4820
Opened 2018-01-23 22:35 UTC by ezyang

Right now, when you install PyTorch, only libATen.so.1 is installed, not
libATen.so.  I'm not sure this is the "right" way to fix the problem but it's
what we are doing for nccl.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

2018-01-23 22:41 UTC, soumith commented
why do you need the libATen.so symlink?
A better fix is to remove this line: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/CMakeLists.txt#L180

2018-01-23 22:51 UTC, ezyang commented
@prigoyal was attempting to link against the embedded ATen but the obvious incant of `find_libraries` doesn't work when there is a suffixed so but no non-suffixed one.

2018-01-24 01:40 UTC, prigoyal commented
@ezyang I tested your changes on **master** and they work fine. We are also doing similar thing for libnccl.so 

I also tested another solution which is to comment out this piece of code
https://github.com/pytorch/pytorch/blob/94f439c07c4f3e13fbd87016212b3534d31a7165/torch/lib/build_libs.sh#L113-L116 which is removing .so libs. I am not sure why they are removed or why do we need to build .so.1 but it is valid concern to not increase the binary size by keeping .so and .so.1 both

I also tested what @soumith suggested but it requires fixing at more places and I didn't go further with it

2018-01-24 01:41 UTC, prigoyal approved these changes
looks good to me! thanks for this. Similar thing is done for libnccl.so already so should be okay

2018-01-24 02:27 UTC, ezyang commented
The removal code dates back to:

```
commit b5dc36f278fc296e8b9cd4f4f826f4840907b60e
Author: Soumith Chintala <soumith@gmail.com>
Date:   Sat Dec 31 10:30:36 2016 -0500

    explicitly linking against v1 libs to avoid lua-torch conflicts (#386)
```

Now that luatorch is dead maybe we can get rid of all of this code.

2018-01-24 04:49 UTC, soumith requested changes
can I request this to be a modification in aten/src/ATen/CMakeLists.txt where you remove the line that sets version.

Adding a symlink doesn't end well for binary sizes (wheel zips dont support symlinks and create copies)

2018-01-25 18:58 UTC, ezyang commented
Apparently this patch doesn't work for local development in any case....

2018-02-02 14:37 UTC, prigoyal commented
what's the issue with local building @ezyang ? I tried patch your PR and installed pytorch locally successfuly

2018-02-02 15:48 UTC, ezyang commented
When I ran a build with OS X it didn't work. I didn't investigate further because Soumith has requested a different implementation strategy that should  not have the problem.

2018-02-16 01:39 UTC, closed without merging