Fix pin_memory to return correctly typed sequences
pytorch/pytorch pull request #48476
Opened 2020-11-26 07:34 UTC by scarecrow1123

Fixes #48419 

cc: @SsnL

2020-11-26 15:27 UTC, SsnL commented
Needs a test in test_dataloader.py

2020-11-27 01:04 UTC, mariosasko commented
`iter` is redundant here.

This should do the job:
```
type(data)(pin_memory(sample) for sample in data)
```

2020-11-27 01:56 UTC, mariosasko commented on torch/utils/data/_utils/pin_memory.py
> +        return type(data)(iter(pin_memory(sample) for sample in data))
`iter` is redundant here

2020-12-02 19:34 UTC, VitalyFedyunin requested changes
Please add test and remove redundant `iter`

2020-12-02 19:34 UTC, VitalyFedyunin commented
Also rebasing will clear onnx errors.

2022-05-12 06:42 UTC, closed without merging