Change aten::native_layer_norm signature to match torch.layer_norm definition
pytorch/pytorch pull request #48971
Opened 2020-12-08 00:13 UTC by rdspring1

This PR is to change the `aten::native_layer_norm` and `aten::native_layer_norm_backward` signature to match `torch.layer_norm` definition.

`native_layer_norm(X, gamma, beta, M, N, eps)` => 
`native_layer_norm(input, normalized_shape, weight, bias, eps)`

`native_layer_norm_backward(dY, X, mean, rstd, gamma, M, N, grad_input_mask)` => 
`native_layer_norm_backward(dY, input, normalized_shape, mean, rstd, weight, bias, grad_input_mask)`

2020-12-11 08:52 UTC, jjsjann123 commented
I saw Tensorflow in the log from failed CI:
https://app.circleci.com/pipelines/github/pytorch/pytorch/249129/workflows/ac2e7cf6-8815-4e41-91d6-494f78f6efbd/jobs/9520714

2020-12-11 17:04 UTC, ngimel commented
cc @ailzhang, this PR changed the signature of math layer norm kernel (replaced ints with IntArrayRef), and is failing xla test. Is it something that can be fixed on the XLA side?

2020-12-12 03:09 UTC, ailzhang requested changes
Test failure was caused by passing an empty tensor to XLA, which should have been guarded by `_prepare_layer_norm_inputs` before calling into it. I put a comment inline which I think should fix it, let me know if you have further questions. Thanks!

2020-12-12 03:09 UTC, ailzhang commented on aten/src/ATen/native/layer_norm.cpp
> -  auto inputs = _prepare_layer_norm_inputs(input, normalized_shape, weight, bias);
Previously before dispatching to device we do _prepare_layer_norm_inputs(which does input validation etc) first, but now it has been moved into device kernels. If this is intended you should also add it to math_native_layer_norm as well.

2020-12-15 00:04 UTC, jjsjann123 commented
Looks like XLA tests are passing now. I'm updating to resolve conflicts on backward compatibility exceptions, this should be good for review @ailzhang

2020-12-15 05:26 UTC, ailzhang approved these changes
Thanks!

2020-12-15 10:29 UTC, jjsjann123 commented
Thanks for stamping. PR failures doesn't look to be related. Can we get someone to start importing this? :pray:

2020-12-15 23:43 UTC, ngimel approved these changes
LGTM

2020-12-16 19:38 UTC, ngimel commented
Can you please fix a conflict?

2020-12-17 07:11 UTC, closed without merging