[WIP] Enable BFloat16 type input for torch.where()
pytorch/pytorch pull request #49004
Opened 2020-12-08 07:10 UTC by Kiyosora

2020-12-10 17:55 UTC, H-Huang requested changes
Thanks for the PR! Left some feedback to remove the named arguments.

2020-12-10 17:55 UTC, H-Huang commented on test/test_torch.py
> +                for dt1 in torch.testing.get_all_dtypes(include_half=True, include_bfloat16=True):
We can remove these, default is True

2020-12-10 17:55 UTC, H-Huang commented on test/test_torch.py
> +    @dtypes(*(torch.testing.get_all_int_dtypes() + torch.testing.get_all_fp_dtypes(include_bfloat16=True) +
Same as above

2020-12-10 17:55 UTC, H-Huang commented on test/test_torch.py
> +    @dtypes(*(torch.testing.get_all_int_dtypes() + torch.testing.get_all_fp_dtypes(include_bfloat16=True) +
Same as above

2020-12-11 03:19 UTC, Kiyosora commented on test/test_torch.py
> +                for dt1 in torch.testing.get_all_dtypes(include_half=True, include_bfloat16=True):
Addressed! Thanks for reminding that!

2020-12-11 03:19 UTC, Kiyosora commented on test/test_torch.py
> +    @dtypes(*(torch.testing.get_all_int_dtypes() + torch.testing.get_all_fp_dtypes(include_bfloat16=True) +
Addressed!

2020-12-11 03:19 UTC, Kiyosora commented on test/test_torch.py
> +    @dtypes(*(torch.testing.get_all_int_dtypes() + torch.testing.get_all_fp_dtypes(include_bfloat16=True) +
Addressed!

2020-12-11 15:05 UTC, H-Huang approved these changes
LGTM!

2020-12-11 21:41 UTC, closed without merging