Drop FutureNCCL in favor of vanilla CUDAFuture
pytorch/pytorch pull request #49014
Opened 2020-12-08 12:23 UTC by lw

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

We extracted a generic and reusable CUDAFuture class from FutureNCCL, but we had left FutureNCCL around, as a subclass of CUDAFuture, in order to deal with some peculiarity of ProcessGroupNCCL, namely that the future would be completed right away when constructed and that its CUDA events would be _shared_ with the ones of the WorkNCCL. This required some "hacks" in CUDAFuture itself (protected members, fields wrapped in shared_ptrs, ...).

My understanding is that creating CUDA events is a rather cheap operation. That would mean that we could afford to record _twice_ the events after each NCCL call, once for the WorkNCCL and once for the future. By doing so, we can use the CUDAFuture class directly and revert all its hacks.

Differential Revision: [D25355272](https://our.internmc.facebook.com/intern/diff/D25355272/)

2020-12-08 20:39 UTC, mrshenli requested changes
test failures look relevant on this one

2020-12-08 20:53 UTC, mrshenli commented on torch/lib/c10d/ProcessGroupNCCL.hpp
> -  struct FutureNCCL : at::cuda::CUDAFuture {
nice!

2020-12-08 20:53 UTC, mrshenli commented on torch/lib/c10d/ProcessGroupNCCL.hpp
> -  struct FutureNCCL : at::cuda::CUDAFuture {
`FutureNCCL` is also mentioned in our docs. Let update those too:

https://github.com/pytorch/pytorch/blob/dee82ef3ea1ed2cae4e891f071adff03cb4a6e0d/torch/csrc/distributed/c10d/init.cpp#L1140-L1144

2020-12-08 20:58 UTC, mrshenli reviewed
Rest of the change LGTM!

2020-12-11 12:14 UTC, lw commented
I think I have fixed the build failures

2020-12-11 15:48 UTC, mrshenli approved these changes
LGTM!

2020-12-11 17:30 UTC, closed without merging