Add export_to_tensorboard for auto_grad/profiler
pytorch/pytorch pull request #49231
Opened 2020-12-11 11:04 UTC by guyang3532

2020-12-11 11:25 UTC, gaoteng-git commented on torch/autograd/profiler.py
> +            raise RuntimeError(log_dir + " is not a directory.")
"{} is not a directory.".format(log_dir)
Same for other strings below

2020-12-11 11:25 UTC, gaoteng-git commented on torch/autograd/profiler.py
> +        if run_name == None:
Maybe "run_name is None" is better

2020-12-11 12:21 UTC, gaoteng-git commented on torch/autograd/profiler.py
> +            os.mkdir(log_dir)
Need use try-catch?
        try:
            os.mkdir(logdir)
        except os.OSError as e:
            # throw exception?

2020-12-11 20:16 UTC, ilia-cher requested changes
the added function named export_to_tensorboard, but it just simply calls export_chrome_trace, that is confusing and unnecessary;

as discussed, the way to implement this is a) work with new profiler in torch/profiler b) pass format parameter in save trace (kineto api) c) add support for multiple formats into kineto cc. @gdankel

2020-12-15 07:14 UTC, nbcsm commented on torch/autograd/profiler.py
> +                    str(int(time.time()*1000)) + ".pt.trace.json"
try to use `format`

2020-12-15 07:16 UTC, nbcsm commented on torch/autograd/profiler.py
> +            file_name = prefix + "_" + file_name
`hostname_pid.timestamp.pt.trace.json` or `prefix.timestamp.pt.trace.json`

2020-12-15 07:16 UTC, nbcsm commented on torch/autograd/profiler.py
> +    def export_to_tensorboard(self, dir_name, prefix=None):
need a test

2020-12-15 13:24 UTC, guyang3532 commented
This helps users easy to formalize directory structure and file names for tensorboard plugin especially in distributed cases.

For DDP example:

    import torch.multiprocessing as mp
    from torch.nn.parallel import DistributedDataParallel as DDP

    def func(rank, world_size):
        with torch.autograd.profiler.profile(use_cuda=True) as prof:
            ddp_model = DDP(model, device_ids=[rank])
            ...
            loss.backward()
            optimizer.step()
	    prof.export_to_tensorboard()
	    # This will automatically output to 8 files for 8 gpus respectively.

    gpu_num = 8
    mp.spawn(func,args=(gpu_num,),nprocs=gpu_num)

In this case, users only need to call p.export_to_tensorboard(), then the result files will aotomatically output to different files for each gpu.
Users need not to known which node and which gpu is each output file for.
And then the tensorboard plugin api can easy to recognize and parse them.

This function will be called from the new profiler api in torch/profiler when that pr be merged.
@ilia-cher

2020-12-15 21:31 UTC, ilia-cher commented
let's continue the discussion after https://github.com/pytorch/pytorch/pull/48280 is landed

2021-01-20 20:48 UTC, ilia-cher commented
Hi, now that #48280 is landed, this kind of functionality is supported by specifying `on_trace_ready` parameter - you're free to pass any lambda function, e.g. the one that's generated from the logging directory path. Also let's keep the profiler code changes in torch/autograd/profiler.py to a minimum, as we're transitioning away from the older API.

2021-01-26 12:24 UTC, guyang3532 commented
resubmit it at https://github.com/pytorch/pytorch/pull/50875

2021-01-26 12:24 UTC, closed without merging