pass through *EXITCODE *EXITCODE__TRYRUN_OUTPUT variables
pytorch/pytorch pull request #49646
Opened 2020-12-19 19:42 UTC by isuruf

This is needed to allow cross compiling to work

2021-01-11 18:17 UTC, malfet requested changes
@isuruf change looks fine to me, but can you please update the PR description with more details (i.e. why EXITCODE is needed for cross-compilation)

2021-01-11 18:22 UTC, isuruf commented
Done

2021-07-27 13:42 UTC, isuruf commented
This is being used by conda-forge for the Apple silicon build. It'd be good to land this as well.
cc @rgommers

2021-07-27 13:54 UTC, rgommers approved these changes
LGTM too, and PR description is clear. Could you rebase this as well @isuruf, so we get a fresh CI signal?

2021-07-28 06:00 UTC, isuruf commented
Done

2021-07-28 11:37 UTC, rgommers commented
CI is green except for a single unrelated Mypy failure. @malfet could you please land this one too?

2021-07-28 12:06 UTC, malfet commented
@isuruf unrelated to the change, but can you please point out to how PyTorch is cross-compiled in conda-forge right now?As we've been successfully cross-compiling PyTorch for M1  using `CMAKE_OSX_ARCHITECTURES=arm64` environment variable, see 
https://github.com/pytorch/pytorch/blob/c06b6e445f022b062924ae9b49e2739c2992d067/.jenkins/pytorch/macos-build.sh#L38 
And perhaps it will be better to consolidate those codepaths in the long run

2021-07-28 12:14 UTC, isuruf commented
We do 
```
export CC=arm64-apple-darwin20.0.0-clang
export CXX=arm64-apple-darwin20.0.0-clang++
export USE_MKLDNN=0
export BLAS=OpenBLAS
export CMAKE_SYSTEM_NAME=Darwin
export CMAKE_SYSTEM_PROCESSOR=arm64
export CMAKE_SYSTEM_VERSION=20.0.0
python -m pip install . --no-deps -vv
```  and a bunch of other variables like `CMAKE_AR, CMAKE_LINKER, CMAKE_STRIP` etc

2021-07-28 12:33 UTC, malfet commented
@isuruf oh, so you are cross-compiling from x86 linux machine to M1? In that case, it makes total sense to just bypass all try_compile statements. But please keep an eye on something like https://github.com/pytorch/pytorch/pull/60703 (not sure if bypassed try_compile will yield correct results in this case.)

2021-07-28 14:32 UTC, isuruf commented
No, we are compiling from macos x86_64 to macos arm64, but it's possible do so from linux too. We are not using `CMAKE_OSX_ARCHITECTURES` precisely because of issues like #60703.

2021-07-28 23:16 UTC, malfet approved these changes

2021-07-30 15:24 UTC, closed without merging