Dataparallel leak
pytorch/pytorch pull request #4988
Opened 2018-02-01 16:11 UTC by zou3519

Addresses #4865 

DataParallel's `scatter` and `gather` methods contain reference cycles. Based on how python scopes work, the recursion in those functions creates reference cycles. This PR breaks the recursion in `scatter` and `gather`.

There's something up with Python 2.7 that creates reference cycles when a module is replicated, so the unit test I wrote is only for Python 3. As far as I can tell, those reference cycles are created internally by Python so I don't think there's anything we can do about that.

### Test Plan
Unit test to test the multi-gpu behavior under Python 3.

2018-02-01 16:45 UTC, apaszke requested changes

2018-02-01 16:45 UTC, apaszke commented on torch/nn/parallel/scatter_gather.py
> +            return list(map(type(obj), zip(*map(scatter_var, obj.items()))))
But after this change the function will no longer be able to handle arbitrarily nested data structures, right? I don't think it's a good fix.

2018-02-05 21:25 UTC, zou3519 commented
I added a better fix: it turns out that setting the inner functions equal to `None` before returning clears the cell object that has reference cycles. See [this](https://mail.python.org/pipermail/python-dev/2009-December/094439.html) for an explanation.

2018-02-05 21:27 UTC, soumith approved these changes

2018-02-05 21:55 UTC, apaszke commented on torch/nn/parallel/scatter_gather.py
> +        scatter_map = None
Comment!!!

2018-02-05 22:19 UTC, merged