tools: Move sha check to else statement
pytorch/pytorch pull request #50773
Opened 2021-01-19 23:24 UTC by seemethere

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Summary: Moves the sha check for version generation to the else clause
since it was causing issues for users building pytorch when the .git
directory was not present and PYTORCH_BUILD_VERSION was already set

Test Plan: CI
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

2021-01-19 23:26 UTC, samestep approved these changes

2021-01-19 23:42 UTC, janeyx99 approved these changes

2021-01-20 09:25 UTC, Flamefire commented on tools/generate_torch_version.py
> +        if sha is None:
Caution: This is a functional change and will add "Unknown" to the version as `sha` is already used in the `elif`

2021-01-20 13:04 UTC, Flamefire requested changes
The `get_sha` call on line 43 needs to be removed too (so maybe also the parameter altogether): https://github.com/pytorch/pytorch/pull/50773/files#diff-b276b28d4f6ce7bb5745d853b4791e1c9e2022801ade42a507fc6ac3d81bd874R43

Reason: CMake calls generate_torch_version.py directly, so `git` is still executed and the problem from #50730 remains

2021-01-20 17:38 UTC, closed without merging