Fix CPU torch.multinomial with noncontiguous prob tensor
pytorch/pytorch pull request #5093
Opened 2018-02-06 22:49 UTC by SsnL

The CPU code previously uses `resize2d` which does not safely preserve data when input is not contiguous. This PR changes it to `unsqueeze1d` in both CPU and GPU functions, and add strided support for the two functions. As a result, `distributions.Categorical` now doesn't need to call `contiguous()` when the probabilities are not batched.

Also in this PR are 
1. updated tests for `torch.multinomial`,
2. updated doc for `distrbutions.OneHotCategorical` and `distrbutions.Categorical`, and
3. shape tests for `distrbutions.OneHotCategorical` and `distrbutions.Categorical` in unbatched mode.

Fixes #5062 

cc @neerajprad for `distributions.*` changes review.

2018-02-06 22:53 UTC, soumith requested changes
minor typo changes needed.

code looks good and correct

2018-02-06 22:53 UTC, soumith commented on aten/src/TH/generic/THTensor.h
> +// resize* methods simplit resize the storage. So they may not retain the current data at current indices.
*simplit

2018-02-06 22:53 UTC, soumith commented on aten/src/TH/generic/THTensor.h
> +// values, unless you are doing some size and stride tricks, do not use reize*.
reize*

2018-02-06 22:53 UTC, soumith commented on aten/src/THC/generic/THCTensor.h
> +// resize* methods simplit resize the storage. So they may not retain the current data at current indices.
same typos here too

2018-02-06 22:53 UTC, SsnL commented on aten/src/THC/generic/THCTensor.h
> +// resize* methods simplit resize the storage. So they may not retain the current data at current indices.
lol thanks!

2018-02-06 22:58 UTC, soumith approved these changes

2018-02-07 02:51 UTC, neerajprad approved these changes
Thanks for the doc fixes, and adding on the unbatched params tests. Looks great!

2018-02-07 03:11 UTC, merged