Added check and test for betas parameter in Adam optimizer
pytorch/pytorch pull request #5147
Opened 2018-02-09 00:55 UTC by lazypanda1

This PR adds a check to prevent division by zero errors and give users friendlier error messages when using the Adam optimizer.

Currently, if one specifies the beta value of the Adam optimizer as `1.0` for the first parameter, the program fails with the error message, `ZeroDivisionError: float division by zero`. According to the definition of [Adam](https://arxiv.org/abs/1412.6980), beta values should be in the range \[0, 1\).

Also referring [#751](https://github.com/uber/pyro/pull/751) where I encountered and tried to fix this issue in the first place. I believe this would benefit all clients using pytorch as backend.

2018-02-09 13:49 UTC, apaszke requested changes

2018-02-09 13:49 UTC, apaszke commented on test/test_optim.py
> +            )
There’s no reason to run the whole test if you expect the constructor to fail. Just assert that it fails upon construction

2018-02-09 13:49 UTC, apaszke commented on test/test_optim.py
> +        )
Just put an assertRaises here, no need for a helper

2018-02-09 22:22 UTC, lazypanda1 commented
@apaszke I have reduced the test. Please review

2018-02-11 22:55 UTC, apaszke approved these changes

2018-02-11 22:55 UTC, apaszke commented
@pytorchbot test this please

2018-02-12 01:24 UTC, merged

2018-02-12 01:24 UTC, soumith commented
thank you @lazypanda1 !