Update to replace AT_ERROR with TORCH_CHECK
pytorch/pytorch pull request #52711
Opened 2021-02-24 01:23 UTC by lware1m1s

Fixes #{52699}

2021-02-24 19:41 UTC, malfet requested changes
Mostly looks good, but please add space after `false,`

2021-02-24 19:41 UTC, malfet commented on c10/core/Backend.h
> +    TORCH_CHECK(false,"Unrecognized tensor type ID: ", t);
Please add space between function/macro arguments. I.e. `foo(1, 2)` rather `foo(1,2)`
```suggestion
    TORCH_CHECK(false, "Unrecognized tensor type ID: ", t);
```

2021-02-24 21:09 UTC, lware1m1s commented on c10/core/Backend.h
> +    TORCH_CHECK(false,"Unrecognized tensor type ID: ", t);
@malfet fixed spacing issue lastest commit.

2021-02-25 01:55 UTC, malfet approved these changes

2021-02-25 01:55 UTC, malfet commented on c10/cuda/CUDACachingAllocator.cpp
> +      TORCH_CHECK(false,"should_split: invalid pool");
nit
```suggestion
      TORCH_CHECK(false, "should_split: invalid pool");
```

2021-02-25 01:55 UTC, malfet commented on c10/cuda/CUDACachingAllocator.cpp
> +      TORCH_CHECK(false,"invalid device pointer: ", ptr);
```suggestion
      TORCH_CHECK(false, "invalid device pointer: ", ptr);
```

2021-02-25 01:55 UTC, malfet commented on c10/cuda/CUDACachingAllocator.cpp
> +      TORCH_CHECK(false,"invalid device pointer: ", ptr);
```suggestion
      TORCH_CHECK(false, "invalid device pointer: ", ptr);
```

2021-02-26 03:53 UTC, closed without merging