[doc] reorg dist init and non-init functions
pytorch/pytorch pull request #52976
Opened 2021-02-27 22:40 UTC by stas00

This PR proposes:

1. putting the init functions together
2. moving post-init functions into its own sub-header as they are only available after init

If this is too much, could we at least put these 2 functions together:

```
.. autofunction:: init_process_group

.. autofunction:: is_initialized
```
as they are interconnected.

One other option is to move the 2nd group of post-init functions a few sections down, after all the different `Init` sections:

Probably to be placed, right before:
```
Distributed Key-Value Store
---------------------------
```

Thank you.

2021-03-11 22:45 UTC, mrshenli approved these changes
Hey @stas00, thanks a lot for adding this! Sorry about the delay.

2021-03-11 22:47 UTC, mrshenli requested changes
Hey @stas00 , I just noticed that there is an doc build error. Could you please add 5 more "-" below "Post-Initialization"? Thanks!

```
Feb 27 23:42:11 =========================
Feb 27 23:42:11 /var/lib/jenkins/workspace/docs/source/distributed.rst:266: WARNING: Title underline too short.
Feb 27 23:42:11 /var/lib/jenkins/workspace/docs/source/distributed.rst:266: WARNING: Title underline too short.
```

2021-03-11 22:57 UTC, stas00 commented
oops, added! thank you for letting me know it was broken

2021-03-12 01:42 UTC, mrshenli approved these changes

2021-03-12 16:50 UTC, closed without merging