Fix win-test.sh for Windows CPU tests
pytorch/pytorch pull request #53422
Opened 2021-03-05 23:20 UTC by skyline75489

Fixes #{issue number}

2021-03-08 17:43 UTC, malfet requested changes
Hmm, existing check seems to rely on job names and some pre-defined location and will start to fail if location of NVIDIA-smi is moved.
How about iterating over potential paths and executing the program if it exists?
Something like
```
for p in /a /b;
  if [ -x $p/nvidia-smi.exe ];
     $p/nvidia-smi.exe
  fi
done
```

2021-03-08 17:43 UTC, malfet commented on .jenkins/pytorch/win-test.sh
> +
```suggestion
    # Run nvidia-smi if available
    for path in  /c/Program Files/NVIDIA Corporation/NVSMI/nvidia-smi.exe /c/Windows/System32/nvidia-smi.exe; do
    if [ -x $path ]; then
       $path;
       break
    fi
    done
```

2021-03-10 06:46 UTC, skyline75489 commented on .jenkins/pytorch/win-test.sh
> +
Yeah thanks!

2021-03-10 19:38 UTC, malfet commented on .jenkins/pytorch/win-test.sh
> +             break
Nit
```suggestion
            $path;
            break
```

2021-03-10 19:38 UTC, malfet approved these changes

2021-03-11 17:14 UTC, closed without merging