add reduce=True arg to MarginRankingLoss
pytorch/pytorch pull request #5346
Opened 2018-02-22 03:54 UTC by li-roy

As per #264. When reduce is False, MarginRankingLoss outputs a loss per sample in minibatch. When reduce is True (default), the current behavior is kept.

Test Plan
test/run_test.sh
Added unit tests for MarginRankingLoss.

2018-02-22 16:01 UTC, SsnL commented
why doesn't this also have a backward function?

2018-02-22 22:24 UTC, li-roy commented
I used #5080 as a reference for this PR, and a backwards wasn't implemented there as well. Should I also add a backwards?

2018-02-22 22:33 UTC, SsnL commented
The fact that it is moved from python to cpp might be enough to justify ignoring backward. You should either implement it or do a speed benchmark as #5080 .

2018-02-23 16:19 UTC, ezyang commented
```
17:48:04 ======================================================================
17:48:04 ERROR: test_MarginRankingLoss_reduce (__main__.TestNN)
17:48:04 ----------------------------------------------------------------------
17:48:04 Traceback (most recent call last):
17:48:04   File "test_nn.py", line 4576, in <lambda>
17:48:04     setattr(TestNN, test_name, lambda self, test=test: test(self))
17:48:04   File "/var/lib/jenkins/workspace/test/common_nn.py", line 1041, in __call__
17:48:04     deepcopy(target), module)
17:48:04   File "test_nn.py", line 4735, in <lambda>
17:48:04     marginrankingloss_reference(i[0], i[1], t, size_average=get_size_average(m)),
17:48:04 NameError: global name 'marginrankingloss_reference' is not defined
17:48:04 
17:48:04 ======================================================================
17:48:04 ERROR: test_MarginRankingLoss_reduce_no_size_average (__main__.TestNN)
17:48:04 ----------------------------------------------------------------------
17:48:04 Traceback (most recent call last):
17:48:04   File "test_nn.py", line 4576, in <lambda>
17:48:04     setattr(TestNN, test_name, lambda self, test=test: test(self))
17:48:04   File "/var/lib/jenkins/workspace/test/common_nn.py", line 1041, in __call__
17:48:04     deepcopy(target), module)
17:48:04   File "test_nn.py", line 4735, in <lambda>
17:48:04     marginrankingloss_reference(i[0], i[1], t, size_average=get_size_average(m)),
17:48:04 NameError: global name 'marginrankingloss_reference' is not defined
17:48:04 
```

2018-02-23 18:47 UTC, li-roy commented
@ezyang Yeah I have an update, was going to run benchmarks first.

2018-02-27 02:08 UTC, li-roy commented
benchmarks run with inputs of size (1000), 5000 times:

forward (old) [0.8390149101614952, 0.8477208158001304, 0.859797858633101]
backward (old) [2.4765465622767806, 2.535214721225202, 2.4746940098702908]
double backward (old) [0.7999639995396137, 0.7724319389089942, 0.7383095575496554]

forward (new) [0.7037791842594743, 0.7032447448000312, 0.6909415749832988]
backward (new) [0.8209385611116886, 0.8369621662423015, 0.8271905779838562]
double backward (new) [0.8673017444089055, 0.8709612749516964, 0.8717606142163277]

2018-02-28 18:34 UTC, li-roy commented
@pytorchbot retest this please

2018-02-28 19:29 UTC, SsnL commented
Interesting that double backward slows down, but this is fine given the single backward improvements.

2018-03-01 00:08 UTC, li-roy commented
@pytorchbot retest this please

2018-03-09 03:06 UTC, li-roy commented
@pytorchbot retest this please

2018-03-09 20:47 UTC, li-roy commented
@pytorchbot retest this please

2018-03-17 21:38 UTC, ssnl requested changes
Looks good in general. But please fix the conflict :)

2018-03-17 21:38 UTC, SsnL commented on aten/src/ATen/native/native_functions.yaml
> +- func: margin_ranking_loss(Tensor input1, Tensor input2, Tensor target, double margin, bool size_average, bool reduce) -> Tensor
nit: please put this at the correct spot wrt alphabetical ordering :)

2018-03-21 18:56 UTC, ssnl approved these changes
LGTM!

2018-03-21 19:40 UTC, merged