[WIP] Port NumPy typing testing style to PyTorch
pytorch/pytorch pull request #54234
Opened 2021-03-18 03:56 UTC by guilhermeleobas

This is a follow-up PR of #52408 and includes the `pass/` and `fail/` directories.

2021-03-26 01:58 UTC, guilhermeleobas commented
Hi @rgommers, can you do an initial review? I'll add more examples to the `fail/` dir in the upcoming days.

2021-03-30 20:14 UTC, rgommers requested changes
Thanks @guilhermeleobas, overall this looks good. A number of small things to fix. Would also be good to merge with master to get a fresh CI run.

2021-03-30 20:14 UTC, rgommers commented on test/test_typing.py
> +    """Strip the filename from a mypy message."""
This change is helpful

2021-03-30 20:14 UTC, rgommers commented on test/typing/pass/creation_ops.py
> +                         device=torch.device('cuda:0'))
minor: funky indentation here. also further down in multiple places. maybe you had an editor setup issue? would be good to clean up

2021-03-30 20:14 UTC, rgommers commented on test/typing/pass/creation_ops.py
> +torch.zeros(2, 3)
would be good to also add
```
torch.zeros((2, 3))
torch.zeros([2, 3])
```
to ensure list and tuple input work as advertised.

2021-03-30 20:14 UTC, rgommers commented on test/typing/pass/math_ops.py
> +torch.absolute(torch.Tensor([-1, -2, 3]))
Please don't use `torch.Tensor`, it's the deprecated constructor and we just got rid of it everywhere. use `torch.tensor` instead

2021-03-30 20:14 UTC, rgommers commented on test/typing/pass/math_ops.py
> +# logaddexp2
missing code here?

2021-03-30 20:14 UTC, rgommers commented on test/typing/pass/math_ops.py
> +torch.nextafter(torch.Tensor([1, 2]), torch.Tensor([2, 1])) == torch.Tensor([eps + 1, 2 - eps])
more `Tensor` -> `tensor`

2021-03-30 20:14 UTC, rgommers commented on test/typing/reveal/tensor_sampling.py
> +# set_rng_state
Were you planning to finish these, or are they left like this on purpose?

2021-03-30 20:14 UTC, rgommers commented on test/typing/reveal/tensor_sampling.py
> +# set_rng_state
There are some more further down.

2021-03-30 20:14 UTC, rgommers commented on torch/quasirandom.py
> +                   dtype: torch.dtype = torch.float32):
missing return type

2021-04-01 22:38 UTC, guilhermeleobas commented
Hi Ralf, I've addressed all your comments

2021-04-09 15:59 UTC, rgommers approved these changes
Thanks @guilhermeleobas, this LGTM now.

2021-04-09 17:28 UTC, malfet approved these changes

2021-04-09 17:51 UTC, walterddr approved these changes

2021-04-15 08:26 UTC, closed without merging