Improve error message while setting error twice.
pytorch/pytorch pull request #54464
Opened 2021-03-23 00:37 UTC by pritamdamania87

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

In case where we accidentaly set an error twice on a Future, we get a
cryptic error like this:

```
Exception in thread pool task: !completed() INTERNAL ASSERT FAILED at "aten/src/ATen/core/ivalue_inl.h":534, please report a bug to PyTorch.
```

This PR, updates the error message to include some additional information about
what the previous error was.

Differential Revision: [D27249758](https://our.internmc.facebook.com/intern/diff/D27249758/)

2021-03-23 17:48 UTC, swolchok requested changes
setErrorInternal looks fine to me, though I think @ezyang has more specific thoughts on error message wording than I do. please move the test

2021-03-23 17:48 UTC, swolchok commented on test/cpp/jit/test_misc.cpp
> +TEST(FuturesTest, SetError) {
shouldn't this go in aten/src/ATen/test/ivalue_test.cpp?

2021-03-23 17:48 UTC, swolchok commented on aten/src/ATen/core/ivalue_inl.h
> +        "Error already set on the Future: ",
nit: s/the Future/this Future/ ?

2021-03-23 18:42 UTC, ezyang commented
> though I think @ezyang has more specific thoughts on error message wording than I do

Wording seems fine, don't think this will actually show up for end users

2021-03-26 08:38 UTC, rohan-varma commented on aten/src/ATen/test/ivalue_test.cpp
> +    EXPECT_THAT(e.what(), ::testing::HasSubstr("Error already set"));
nit: also test that it has the original error message? 
EXPECT_THAT(e.what(), ::testing::HasSubstr("foo"));

2021-03-27 01:14 UTC, pritamdamania87 commented
@swolchok Could you take another look at this PR? Thanks!

2021-03-27 02:32 UTC, swolchok approved these changes
Looks good, sorry for the delay!

2021-03-27 04:57 UTC, closed without merging