Add a gaussian sampler
pytorch/pytorch pull request #5487
Opened 2018-03-01 09:12 UTC by pajotarthur

With @emited, adding a C and CUDA functions for a gaussian grid sampler, similar with the one described in https://openreview.net/pdf?id=SkZXoGZC- .

2018-03-01 17:02 UTC, ezyang commented
@pajotarthur If you fix the merge conflicts I'll run this on CI for you.

2018-03-07 15:30 UTC, ezyang commented
@pytorchbot test this please

2018-03-12 19:55 UTC, zou3519 commented
@pytorchbot test this please

2018-03-13 14:02 UTC, ezyang commented on .jenkins/macos-build-test.sh
> +export MAX_JOBS=3
Haha, thanks. We might be able to bump this all the way to 4, actually, since we've got quad core machines. Or 5, to hide IO latency.

2018-03-13 14:03 UTC, ezyang commented
What's going on with the pybind11 submodule update?

2018-03-13 15:48 UTC, pajotarthur commented
I'm not really sure, I pulled from https://github.com/pybind/pybind11 manually by mistake a long time ago, I can checkout to the correct commit, but when I git submodule update, it reverts to the wrong one. Is there a workaround ? It doesn't seems to break anything though.

2018-03-23 18:23 UTC, ezyang commented
@pajotarthur The main reason to not update it here is to let a pybind11 submodule be its own commit, so that's easier to notice if you're reading the commit stream.

An easy way to fix the problem is to "redo" your commit:

1. `git reset HEAD~`
2. `git submodule update`
3. `git commit -C $oldcommithash`

Another way is to manually checkout the submodule to the correct commit, and then do a `git commit --amend`.

2018-03-27 14:52 UTC, ezyang commented
@pytorchbot test this please

2018-03-27 14:53 UTC, ezyang commented
The submodule still looks updated to me

2018-03-27 14:53 UTC, ezyang commented
BTW, you can check locally if you've done the fix properly by running `git diff origin/master` and seeing if the submodule update shows up there.

2018-04-16 18:47 UTC, ezyang commented on test/test_nn.py
> +            def test_cpu_against_cuda(N, C, D, H, W, padding_mode):
The extra indent here was totally unnecessary

2018-04-16 18:49 UTC, ezyang commented
@pajotarthur Did @emited do a math check on the two kernel implementations?

2018-04-17 12:14 UTC, pajotarthur commented
Absolutely. Do you need the maths in writing ?

2018-04-17 19:17 UTC, ezyang approved these changes
Nope, that's good enough for me.

2018-04-26 03:11 UTC, ezyang commented
Looks like there is some sort of submodule update disaster. https://stackoverflow.com/questions/7718780/how-to-undo-git-submodule-update?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa can tell you how to fix it (you'll have to find the correct hashes)

2018-04-27 11:41 UTC, pajotarthur commented
I messed up my commit, I'll correct it soon.

2018-05-15 03:16 UTC, ezyang commented
Needs rebasing :(

2018-05-15 13:59 UTC, goldsborough commented
I think you did `git pull upstream master`. Please undo this and `git pull --rebase upstream master` instead

2018-05-15 14:00 UTC, goldsborough commented
You should probably also squash your commits into a single one

2018-05-15 19:48 UTC, ezyang commented
@pytorchbot retest this please

2018-08-21 18:29 UTC, weiyangfb commented
@pajotarthur needs another rebasing now

2019-06-05 00:42 UTC, sfotiadis commented
Hey, fellas where is this standing right now?

2019-06-07 14:30 UTC, ezyang requested changes
Unfortunately, due to our negligence, this PR has severely bitrotten. Probably the best thing to do is for someone to redo it in ATen (c.f. https://github.com/pytorch/pytorch/wiki/TH-to-ATen-porting-guide) and resubmit. Sorry :(

2020-10-22 19:06 UTC, anderspapitto reviewed
.

2022-06-27 21:37 UTC, closed without merging

2023-09-24 08:01 UTC, xming521 commented
Anything new?