Allow uppercase letters in einsum equation string
pytorch/pytorch pull request #55013
Opened 2021-03-31 02:52 UTC by ezyang

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Based off of emprice's PR at https://github.com/pytorch/pytorch/pull/23277
but rebased past a major rewrite of the einsum engine.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

2021-03-31 14:16 UTC, ezyang commented
cc @emprice @jcmgray

2021-03-31 15:37 UTC, t-vi approved these changes
With the suggested fix for the test, it looks good to me.
That said, I think at some point we might just as well use a hash table to support all unicode (greek letters probably are the next thing that isn't an unreasonable request).

2021-03-31 15:37 UTC, t-vi commented on test/test_linalg.py
> +        check('A', [1], expected_output=1)
```suggestion
        check('A', [1], expected_output=[1])
```
Other than that looks good.

2021-03-31 16:27 UTC, heitorschueroff approved these changes
LGTM!

2021-03-31 16:30 UTC, heitorschueroff commented
> With the suggested fix for the test, it looks good to me.
> That said, I think at some point we might just as well use a hash table to support all unicode (greek letters probably are the next thing that isn't an unreasonable request).

That seems reasonable. I am working on adding sublist support similar to np.einsum (https://github.com/pytorch/pytorch/issues/21412) and some other major changes to einsum.

2021-03-31 16:43 UTC, ezyang commented
Implementation is still buggy lol, need to fix

2021-03-31 17:19 UTC, ezyang commented
@heitorschueroff I only revived this PR because someone was asking about an old PR that I was on the cusp of merging but the submitter disappeared. Do you want to just take responsibility for shepherding this through, esp if you're doing a full rewrite of einsum again?

2021-03-31 17:34 UTC, heitorschueroff commented
> @heitorschueroff I only revived this PR because someone was asking about an old PR that I was on the cusp of merging but the submitter disappeared. Do you want to just take responsibility for shepherding this through, esp if you're doing a full rewrite of einsum again?

Sure, I'll address this PR since I'm working on einsum anyway.

2021-03-31 17:34 UTC, heitorschueroff requested changes
I'll address this PR along with my current changes to einsum.

2021-03-31 17:38 UTC, ezyang commented
Thanks! BTW the bug in this PR is there are a few other places that need to handle the lower-upper translation; probably best to factor it into a pair of helper functions projecting to and out of int indices.

2021-03-31 20:36 UTC, heitorschueroff commented
> Thanks! BTW the bug in this PR is there are a few other places that need to handle the lower-upper translation; probably best to factor it into a pair of helper functions projecting to and out of int indices.

Yes, einsum could use a refactor haha. Thanks for the hints.

2021-04-20 13:02 UTC, heitorschueroff commented
Closing in favor of https://github.com/pytorch/pytorch/pull/56475

2021-04-20 13:02 UTC, closed without merging