[WIP][package] Add tracing to exporter for automocking
pytorch/pytorch pull request #55167
Opened 2021-04-01 17:56 UTC by SplitInfinity

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Summary:
This commit uses `sys.setprofile` to trace the execution of an object
before it is packaging to automatically discover dependencies that are
*not* used and can be automatically mocked.

Test Plan:
This commit adds a unit test to `test_dependency_api.py` that tests this
feature.

Reviewers:

Subscribers:

Tasks:

Tags:

2021-04-05 20:49 UTC, SplitInfinity commented on torch/package/package_exporter.py
> -
Undo.

2021-04-08 16:35 UTC, suo requested changes
I think we should move this out of the core packageexporter logic until we bake the functionality more fully. I think there should be a `torch/package/analyze` module or similar where we house some of this stuff (dependency visualization, pickler disassembler, trace mocker, etc.).

2021-04-12 17:18 UTC, SplitInfinity commented
Okay, I moved it to a separate directory as discussed, but now it only traces and returns dependencies. It won't be useful until we also land the change we discussed that adds a `get_dependency_graph` method to the `PackageExporter`, after which that graph can be combined with the results of this dependency tracing function to automatically mock dependencies.

2021-04-13 01:53 UTC, suo approved these changes

2021-04-13 01:53 UTC, suo commented on torch/package/analyze/trace_dependencies.py
> +    sys.setprofile(record_used_modules)
probably want to put this in a try-finally so that the profile doesn't get stuck on.

2021-04-13 01:53 UTC, suo commented on test/package/test_analyze.py
> +        import automock
nit: this looks like a real package instead of test package, can we change the name 📦

2021-04-14 07:08 UTC, closed without merging