Add handling of symbolic shapes
pytorch/pytorch pull request #55925
Opened 2021-04-13 17:17 UTC by eellison

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2021-04-20 02:05 UTC, ZolotukhinM commented on torch/csrc/jit/passes/symbolic_shape_analysis.cpp
> +                }
Are you sure this is needed? I think accessing a map element via `operator[]` would insert an empty element if it didn't exist (in contrast to `.at`).

2021-04-20 02:07 UTC, ZolotukhinM commented on torch/csrc/jit/passes/symbolic_shape_analysis.cpp
> +    std::unordered_map<int64_t, std::vector<Value*>> symbolic_shape_map;
Im having hard times following what's going on here: do you mind adding some comments, maybe with examples?

2021-04-20 02:12 UTC, ZolotukhinM commented on torch/csrc/jit/passes/symbolic_shape_analysis.cpp
> +    std::unordered_map<int64_t, std::vector<Value*>> symbolic_shape_map;
Note that readers of that code would not first see the commit message or the test coming in this PR - it's good for the code to have a similar description too.

2021-04-21 21:02 UTC, eellison commented
@ZolotukhinM @penguinwu PTAL

2021-04-21 22:23 UTC, penguinwu commented on test/jit/test_symbolic_shape_analysis.py
> +        prop_shapes_on_graph([None, None], [None, None, None])
Does `None` mean symbolic shape? But then there is `new_sybolic_shape_symbol` used later. Adding a comment would help.

2021-04-21 22:31 UTC, penguinwu commented on torch/csrc/jit/passes/symbolic_shape_analysis.cpp
> +    // dim1 = inp1[0], dim2 = inp2[0]; return dim1 if dim2 == 1 else dim2
Break line on the examples to make it easier to read

2021-04-21 22:39 UTC, penguinwu commented on torch/csrc/jit/passes/symbolic_shape_analysis.cpp
> +  void substituteInputTensorProperties(bool substitute_symbolic_dims) {
What is the difference between `substitute_symbolic_dims` being true or false? Adding a comment would help

2021-04-21 22:41 UTC, penguinwu commented on torch/csrc/jit/passes/symbolic_shape_analysis.cpp
> +              if (norm_index &&
Since both conditions have `norm_index`, it may be more readable to hoist `if (norm_index)` out as a top-level branch

2021-04-21 22:44 UTC, penguinwu commented on torch/csrc/jit/passes/symbolic_shape_analysis.cpp
> +  void mergeSymbolicShapeSets(const std::vector<Value*>& symbolic_set) {
Do not understand what this tries to do, could you add more comments to explain?

2021-04-21 22:47 UTC, penguinwu requested changes, later dismissed
A couple of places need more explanation for me to understand better. Will do another read after the comments.

2021-04-22 22:03 UTC, ZolotukhinM approved these changes
Looks good to me, thanks for adding more comments!

2021-05-14 16:57 UTC, eellison commented
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27750996).

2021-05-17 23:14 UTC, eellison commented
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27750996).

2021-05-20 20:22 UTC, eellison commented
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27750996).

2021-05-20 23:25 UTC, eellison commented
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27750996).

2021-05-21 01:54 UTC, eellison commented
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27750996).

2021-05-21 04:30 UTC, eellison commented
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27750996).

2021-05-21 15:51 UTC, closed without merging