Fix cxx11 abi
pytorch/pytorch pull request #55984
Opened 2021-04-14 03:04 UTC by zasdfgbnm

Fixes https://github.com/pytorch/pytorch/issues/55829

2021-04-14 03:21 UTC, ngimel approved these changes
lgtm, @seemethere can you check if it fixes nightly builds?

2021-04-14 18:19 UTC, seemethere approved these changes

2021-04-14 19:27 UTC, malfet requested changes
Hmm, perhaps rather than fixing syntactic error, function signature better be fixed?
Returning reference to object from function is a bad practice, that can lead to hard to catch errors. Which makes me wonder, why it returns those in the first place.

2021-04-14 19:38 UTC, zasdfgbnm commented
@malfet Isn't returning reference of tensors the required behavior for all `xxx_out` operators?

```python
>>> import torch
>>> a = torch.randn(5, 5)
>>> b = torch.randn(5)
>>> torch.sum(a, dim=0, out=b).requires_grad_()
tensor([-2.3231e-01, -2.1876e+00,  1.7415e+00, -3.2706e-03,  3.7022e+00],
       requires_grad=True)
>>> b
tensor([-2.3231e-01, -2.1876e+00,  1.7415e+00, -3.2706e-03,  3.7022e+00],
       requires_grad=True)
```

2021-04-14 19:48 UTC, malfet approved these changes
LGTM, but please use `std::forward_as_tuple` to make sure those are returned as references

2021-04-14 19:48 UTC, malfet commented on aten/src/ATen/native/cuda/Sort.cu
> +    return std::tuple<Tensor &, Tensor &>(values, indices);
Please use [std::forward_as_tuple](https://en.cppreference.com/w/cpp/utility/tuple/forward_as_tuple)
```suggestion
    return std::forward_as_tuple(values, indices);
```

2021-04-14 19:48 UTC, malfet commented on aten/src/ATen/native/cuda/Sort.cu
> +    return std::tuple<Tensor &, Tensor &>(values, indices);
Same as above
```suggestion
    return std::forward_as_tuple(values, indices);
```

2021-04-14 19:48 UTC, malfet commented on aten/src/ATen/native/cuda/Sort.cu
> +  return std::tuple<Tensor &, Tensor &>(values, indices);
Same as above
```suggestion
  return std::forward_as_tuple(values, indices);
```

2021-04-14 20:32 UTC, zasdfgbnm commented
@malfet fixed

2021-04-16 00:01 UTC, seemethere commented
Looks like there might be a `clang-format` issue?

2021-04-20 05:21 UTC, closed without merging