Add SpatialLogSoftMax as LogSoftmax2d
pytorch/pytorch pull request #564
Opened 2017-01-23 21:05 UTC by desimone

See #551

2017-01-23 21:27 UTC, apaszke requested changes
You changed permissions on a lot of files (from 644 to 755 - added executable bit). Can you revert that please?

2017-01-23 21:27 UTC, apaszke commented on torch/nn/modules/activation.py
> +        return F.log_softmax(input)
Are you sure regular log_softmax works with spatial inputs too?

2017-01-23 21:29 UTC, apaszke commented on torch/nn/modules/activation.py
> +        return F.log_softmax(input)
Ah, I see. Cool. Just fix the permissions please.

2017-01-23 21:35 UTC, desimone commented on torch/nn/modules/activation.py
> +        return F.log_softmax(input)
Sure thing!

2017-01-23 21:38 UTC, desimone commented
@apaszke thanks for the review. I've reverted the permission changes.

2017-01-23 21:40 UTC, apaszke approved these changes

2017-01-23 21:40 UTC, apaszke commented
@pytorchbot test this please

2017-01-23 21:48 UTC, apaszke commented
@desimone the tests have failed

2017-01-23 21:54 UTC, desimone commented
@pytorchbot test this please

2017-01-23 22:41 UTC, apaszke commented
Haha, yeah it know who should it listen to 😄

@pytorchbot test this please

2017-01-23 23:05 UTC, desimone commented
I'm at a bit of a loss on this one. Maybe I over-reached.

```bash
FAIL: test_MultiLabelMarginLoss (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 1157, in <lambda>
    setattr(TestNN, test_name, lambda self,test=test: test(self))
  File "/tmp/builder/pytorch/test/common_nn.py", line 595, in __call__
    test_case.check_criterion_jacobian(module, input, self.target)
  File "/tmp/builder/pytorch/test/common_nn.py", line 444, in check_criterion_jacobian
    PRECISION
AssertionError: 2.0637550102259317e-05 not less than or equal to 1e-05

----------------------------------------------------------------------
Ran 265 tests in 26.546s

FAILED (failures=1, skipped=4)Build step 'Execute shell' marked build as failure
```

2017-01-24 02:42 UTC, desimone commented
Any thoughts on why this would cause the `MultiLabelMarginLoss` test to fail `check_criterion_jacobian`? The connection is non-obvious to me.

2017-01-24 03:43 UTC, soumith commented
@desimone afai can see, this is not a failure from you. The ordering of the tests changed and we found that we need to bump the tolerance on that test. :)

2017-01-24 09:40 UTC, apaszke commented
Actually we've discussed this, and decided that since the code is exactly the same for `LogSoftmax` and `LogSoftmax2d`, we'd rather keep only the regular one. Can you just limit your changes to `test/test_nn.py`, but use `LogSoftmax` in that test case? Thanks!

2017-01-24 19:25 UTC, desimone commented
Makes sense given LogSoftmax (seems to be) a superset of `LogSoftMax` and `SpatialLogSoftMax`. Let me know if this is what you had in mind.

2017-01-24 19:26 UTC, soumith commented
@pytorchbot  test this please

2017-01-24 22:24 UTC, apaszke approved these changes

2017-01-24 22:24 UTC, merged

2017-01-24 22:24 UTC, apaszke commented
Thanks!