Add Symbolic Shape Registry and define in C++
pytorch/pytorch pull request #56815
Opened 2021-04-23 20:25 UTC by eellison

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2021-04-26 14:49 UTC, penguinwu commented on torch/csrc/jit/passes/symbolic_shape_analysis.cpp
>  void PropagateShapesOnGraph(std::shared_ptr<Graph>& graph) {
Could you add a comment on what `PropagateShapesOnGraph` does? It is not clear to me what we are propagating. I would expect some input shapes to be passed into `PropagateShapesOnGraph` for propagation, but the code seems to just propagate the symbolic shapes (represented as `shapeComputeGraphForSchema`)  associated w/ the node to compute the shape of the output nodes? If we do not use any outside information, then it seems that we could statically deduce the output tensor shapes. I could have misunderstood the codes, but it is definitely not intuitive and warrants some comments here.

2021-04-26 14:53 UTC, penguinwu commented on torch/csrc/jit/runtime/symbolic_shape_registry.cpp
> +std::unordered_map<std::string,  std::string> schema_string_to_function_name_mappings = {
Reaability nip: `schema_string_to_function_name_mappings` -> `schema_string_to_shape_function_name_mappings`

2021-04-26 14:54 UTC, penguinwu commented on torch/csrc/jit/runtime/symbolic_shape_registry.cpp
> +std::unordered_map<std::string, std::shared_ptr<Graph>> schema_string_to_function_graph;
Readability: `schema_string_to_function_graph` -> `schema_string_to_shape_function_graph`

2021-04-26 14:55 UTC, penguinwu commented on torch/csrc/jit/runtime/symbolic_shape_registry.cpp
> +std::unordered_map<const FunctionSchema*, std::shared_ptr<Graph>> cached_schema_to_graph;
Readability: `cached_schema_to_graph` -> `cached_schema_to_shape_function_graph`

2021-04-26 14:57 UTC, penguinwu commented on torch/csrc/jit/runtime/symbolic_shape_registry.cpp
> +  std::unordered_map<std::string, std::shared_ptr<Graph>> reused_functions;
[Readability nip] It is easier to understand to use `shape_function` instead of `function` in the following codes.

2021-04-26 15:09 UTC, penguinwu requested changes
LGTM, just some readability nips and one question regarding `PropagateShapesOnGraph` (that may require additional comment)

2021-04-26 16:11 UTC, penguinwu approved these changes

2021-05-14 16:57 UTC, eellison commented
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444662).

2021-05-14 18:11 UTC, eellison commented
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444662).

2021-05-17 23:14 UTC, eellison commented
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444662).

2021-05-20 20:23 UTC, eellison commented
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444662).

2021-05-20 23:25 UTC, eellison commented
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444662).

2021-05-25 01:26 UTC, eellison commented
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444662).

2022-05-13 04:48 UTC, closed without merging