Fix NVRTC versioning for CUDA 11.3, CUDA 12 and later
pytorch/pytorch pull request #57204
Opened 2021-04-28 22:25 UTC by zasdfgbnm

NVRTC versioning has changed starting 11.3. See comment in code for detail.

2021-04-29 00:12 UTC, zasdfgbnm commented
cc: @ptrblck @ngimel

2021-04-29 02:33 UTC, malfet requested changes
Thank you for the fix, but can you please rework it (using preprocessor or metaprogramming) to keep `libname` static for performance reasons? (otherwise libname would be computed every time this function is called)
Or initialize explicitly using `std::once` construct

2021-04-29 02:45 UTC, zasdfgbnm commented
@malfet Done

2021-04-30 16:59 UTC, malfet approved these changes

2021-04-30 20:25 UTC, closed without merging