Helper function for skipping module parameter / buffer initialization
pytorch/pytorch pull request #57555
Opened 2021-05-04 17:54 UTC by jbschlosser

This PR introduces a helper function named `torch.nn.utils.skip_init()` that accepts a module class object and returns a function usable to instantiate that module on a specified device while skipping initialization of parameter / buffer values. See discussion at https://github.com/pytorch/pytorch/issues/29523 for more context. Example usage:

```python
import torch

l = torch.nn.utils.skip_init(torch.nn.Linear)
m = l(5, 1)
print(m.weight)

l_gpu = torch.nn.utils.skip_init(torch.nn.Linear, device='cuda')
m2 = l_gpu(4, 1)
print(m2.weight)
```
```
Parameter containing:
tensor([[-3.3011e+28,  4.5915e-41, -3.3009e+28,  4.5915e-41,  0.0000e+00]],
       requires_grad=True)
Parameter containing:
tensor([[-2.5339e+27,  4.5915e-41, -2.5367e+27,  4.5915e-41]],
       device='cuda:0', requires_grad=True)
```

Bikeshedding on the name / namespace is welcome, as well as - just wanted to get something out there for discussion.

2021-05-04 20:01 UTC, ezyang commented
cc @vadimkantorov

2021-05-04 20:03 UTC, ezyang commented
Do you actually want the function to be curried? A more straightforward usage API, I imagine, might look like:

```
torch.nn.utils.skip_init(nn.Linear, 1, 2)
```

2021-05-04 20:17 UTC, vadimkantorov commented
I think this pattern would be very frequent for anyone who works with even medium-sized models. Enabling/disabling this pattern is much more simple with an argument. Imagine rewriting a resnet constructors with optional skip_init wrapper at all steps. It's much harder to propagate compared to an argument...

2021-05-04 20:23 UTC, jbschlosser commented
> Do you actually want the function to be curried? A more straightforward usage API, I imagine, might look like:
> 
> ```
> torch.nn.utils.skip_init(nn.Linear, 1, 2)
> ```

So I actually started out with something like this- the `device` arg makes it a little weird though.

```python
# Works, but device must always be specified and it can't be kw-only.
# skip_init(torch.nn.Linear, 'cpu', 5, 1)
def skip_init(module_cls, device, *args, **kwargs):
  ...

# Bad; skip_init(torch.nn.Linear, 5, 1) will treat 5 as the device.
def skip_init(module_cls, device='cpu', *args, **kwargs):
  ...

# Invalid syntax.
def skip_init(module_cls, *args, **kwargs, device='cpu'):
  ...
```

Could also leave out the device arg and assume CPU, but we lose flexibility.

2021-05-04 20:42 UTC, ezyang commented
> I think this pattern would be very frequent for anyone who works with even medium-sized models. Enabling/disabling this pattern is much more simple with an argument. Imagine rewriting a resnet constructors with optional skip_init wrapper at all steps. It's much harder to propagate compared to an argument...

@vadimkantorov I'm not sure you'd need to rewrite the resnet constructors. All you need is a working device kwarg on the module you're interested in, and then it will automatically propagate recursively. Could you perhaps explain your concern in more detail?

Concretely, if I have `Resnet50(device)`, then `skip_init(Resnet50, ...)` will recursively skip initialization on ALL of Resnet50's submodules, not just the top level module.

> So I actually started out with something like this- the device arg makes it a little weird though.

No problem.

```
def skip_init(module_cls, *args, **kwargs):
    final_device = kwargs.pop('device')
    kwargs['device'] = 'meta'
    return module_cls(*args, **kwargs).empty_to(final_device)
```

2021-05-04 20:54 UTC, jbschlosser commented
> No problem.
> 
> ```
> def skip_init(module_cls, *args, **kwargs):
>     final_device = kwargs.pop('device')
>     kwargs['device'] = 'meta'
>     return module_cls(*args, **kwargs).empty_to(final_device)
> ```

Nice, a slight tweak to `final_device = kwargs.pop('device', 'cpu')` does the trick!

2021-05-05 19:51 UTC, vadimkantorov commented
One naming suggestion: maybe `.materialize(device)` instead of `empty_to`?

2021-05-05 20:00 UTC, jbschlosser commented
> One naming suggestion: maybe `.materialize(device)` or `materialize_to(device)` instead of `empty_to`?

@vadimkantorov The `to_empty()` name was chosen because this is a method on `nn.Module` that can be applied regardless of what the current device is. I like the name `materalize*` wrt "meta-modules", but it breaks down a bit beyond that. The semantics of the function are to mutate the module such that its parameters / buffers are uninitialized (as if `torch.empty()` was called), and I'm worried the name `materialize()` doesn't fit with these semantics. Example:

```python
import torch

# Create module on default CPU device.
m = torch.nn.Linear(5, 1)

# Results in a CPU module with uninitialized parameters.
# Name doesn't indicate that this will happen.
m.materialize(device='cpu')
```

See discussion here: https://github.com/pytorch/pytorch/issues/54600

2021-05-05 20:03 UTC, vadimkantorov commented
`materialize_empty`?

2021-05-20 18:37 UTC, ezyang approved these changes

2021-05-24 12:52 UTC, albanD requested changes
The code looks good to me.
You need to update the `.rst` for torch.nn though for it to actually appear in the doc!

2021-05-24 14:17 UTC, albanD approved these changes
Thanks for the update!

2021-05-24 14:25 UTC, vadimkantorov commented
I think it would be good to update the docs with some recommendations of usage. E.g. if I have a model that I distribute via torch hub (or just in the codebase), how do I use this? in client code or in some constructor method or in model constructor etc

2021-05-24 14:41 UTC, jbschlosser commented
> I think it would be good to update the docs with some recommendations of usage. E.g. if I have a model that I distribute via torch hub (or just in the codebase), how do I use this? in client code or in some constructor method or in model constructor etc

Definitely agree and this will be addressed in the next PR, but there is some question as to the best location for these docs. A [recipe](https://pytorch.org/tutorials/recipes/recipes_index.html) (linked to from the function docs) may be appropriate but I'm open to other options that may have better discoverability. The new docs will demonstrate how to update a given module to fit with the criteria for usage of `skip_init()`.

2021-05-24 18:29 UTC, closed without merging

2021-09-08 17:25 UTC, malfet commented
Removing this PR from 1.9.1 milestone, as it looks like a feature work