Enable resetting of batchnorm running stats and cumulative ("simple") moving average
pytorch/pytorch pull request #5766
Opened 2018-03-14 03:06 UTC by jma127

This is a proposed implementation of ``reset_running_stats``, which I discussed with @soumith earlier today. In addition, it enables the use of the simple moving average for running stats in place of the exponential moving average, with a ``momentum=None`` setting.

The motivation behind these changes is to faithfully execute the moment estimation of [the original batchnorm paper](https://arxiv.org/abs/1502.03167) (line 10 in Algorithm 2). To do this, you would do:

    bn_layer = BatchNorm(..., momentum=None)
    
    # construct the rest of the network and train
    
    bn_layer.reset_running_stats()
    for i in range(num_bn_meanvar_batches):
        model.forward(get_new_batch())

    bn_layer.eval()

    # use the model

2018-03-14 04:44 UTC, goldsborough commented
@pytorchbot retest this please

2018-03-14 05:08 UTC, jma127 commented
(for some possibly confusing chicken-scratch motivation of why SMA is needed, see https://www.overleaf.com/read/xydtqhmhmtdz)

2018-03-14 05:27 UTC, goldsborough commented
@pytorchbot retest this please

2018-03-14 05:45 UTC, goldsborough commented
Our CI was having issues, but it now works again and the failure is on your side. Please fix your PR :)

2018-03-14 05:49 UTC, jma127 commented
OK, wasn't sure on that -- thanks for confirming! Looks like I didn't update some JIT unit test expected value, fixed now.

2018-03-14 05:49 UTC, jma127 commented
@pytorchbot retest this please

2018-03-14 05:52 UTC, goldsborough commented
@pytorchbot retest this please

2018-03-17 01:42 UTC, ssnl requested changes
looks good in general except for minor comments. after fixing and rebasing this should be mergeable.

2018-03-17 01:42 UTC, SsnL commented on torch/nn/modules/batchnorm.py
> +
nit: extra empty line

2018-03-17 01:42 UTC, SsnL commented on torch/nn/modules/batchnorm.py
> +            ("simple" average). Default: 0.1
these are indeed simple average, maybe we can remove the quotes? or we can call it arithmetic average?

2018-03-17 01:45 UTC, SsnL commented
It would also be great if we can test the arithmetic average `test_nn.py`

2018-03-17 02:10 UTC, jma127 commented
@pytorchbot retest this please

2018-03-17 02:32 UTC, jma127 commented
@pytorchbot retest this please

2018-03-17 02:45 UTC, SsnL commented
It seems that there are gloo changes. Could you try `git submodule update --init` to resolve it?

2018-03-17 02:46 UTC, jma127 commented
Whoops, yeah. There are also some failing tests -- I will debug and @mention you when ready.

2018-03-17 02:54 UTC, jma127 commented
@pytorchbot retest this please

2018-03-17 05:05 UTC, jma127 commented
@pytorchbot retest this please

2018-03-17 06:16 UTC, jma127 commented
@SsnL ready for another look!

2018-03-17 21:31 UTC, ssnl reviewed
Only one minor nit. Otherwise looks great!

2018-03-17 21:31 UTC, SsnL commented on test/test_nn.py
> +        data1 = Variable(torch.rand(4, 3).type(test_type), requires_grad=True)
nit: `Variable` wrapper is not needed anymore. We are also removing it from other test cases, so could you also not use it?

2018-03-18 03:38 UTC, jma127 commented
@pytorchbot retest this please

2018-03-18 03:41 UTC, ssnl approved these changes
this can be merged if tests pass :) Thanks @jma127 !

2018-03-18 03:41 UTC, goldsborough commented
Is the CI not working for you? Tests start automatically (within ~10 secs) every time you push new commits (i.e. Usually no need to use pytorchbot) -- just FYI

2018-03-18 03:52 UTC, jma127 commented
Oh OK, good to know :P

2018-03-18 04:40 UTC, jma127 commented
One test is giving a 404 right now so I'll restart again.

2018-03-18 04:40 UTC, jma127 commented
@pytorchbot retest this please

2018-03-18 04:55 UTC, jma127 commented
Hmm, now I get:

    04:51:16 Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Delete http://%2Fvar%2Frun%2Fdocker.sock/v1.32/containers/4631e92d8a4fd7a9deca52381a4024a52713bcd3979b6425abdff43d7fa91feb?force=1: dial unix /var/run/docker.sock: connect: permission denied

Will retest one more time -- if it still persists, @goldsborough could you investigate?

2018-03-18 04:55 UTC, jma127 commented
@pytorchbot retest this please

2018-03-18 04:57 UTC, goldsborough commented
Sure

2018-03-18 05:15 UTC, ezyang commented
@pytorchbot retest this please

2018-03-18 06:14 UTC, goldsborough commented
Let's merge it

2018-03-19 15:47 UTC, merged