[torch.package/TorchScript] flag to gate allowance of TS serializaiton in torch.package
pytorch/pytorch pull request #57678
Opened 2021-05-05 20:14 UTC by Lilyjjo

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2021-05-05 20:17 UTC, Lilyjjo commented
@Lilyjjo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28232891).

2021-05-05 21:25 UTC, Lilyjjo commented
@Lilyjjo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28232891).

2021-05-06 20:59 UTC, Lilyjjo commented
@Lilyjjo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28232891).

2021-05-10 21:52 UTC, suo requested changes

2021-05-10 21:52 UTC, suo commented on torch/package/package_exporter.py
> +        self.gate_torchscript_serialization = True
let's just make this a global with a leading underscore, and set it in the `setUp()` for the tests. It's fine to be a universal setting for now.

2021-05-11 16:36 UTC, suo approved these changes

2021-05-12 23:47 UTC, Lilyjjo commented
@Lilyjjo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28232891).

2021-05-13 00:07 UTC, Lilyjjo commented
@Lilyjjo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28232891).

2021-05-13 16:27 UTC, Lilyjjo commented
@Lilyjjo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28232891).

2021-05-14 00:28 UTC, Lilyjjo commented
@Lilyjjo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28232891).

2021-05-14 15:21 UTC, closed without merging