Remove macos, libtorch, python 3.6, cpu, rocm, cu101 builds
pytorch/pytorch pull request #57838
Opened 2021-05-07 18:38 UTC by Lynx1820

removing macos, libtorch, python 3.6, cpu, rocm, cu101 builds

2021-05-07 20:47 UTC, antoniovs1029 commented
Seems your branch doesn't include the changes I introduced on https://github.com/pytorch/pytorch/pull/57362 In particular, your builds aren't checking out the 1.8 version of `pytorch/builder`, so my guess is that the failing builds are related to that.

2021-05-12 16:58 UTC, malfet requested changes
Can you please elaborate the reason behind each removal?
I.e. cu101 (not supported) and rocm (beta) sounds reasonable.
But Python-3.6 and MacOS needs some discussion.
Same about ASAN config: what is the motivation behind it?

2021-05-12 18:14 UTC, Lynx1820 commented
> Can you please elaborate the reason behind each removal?
> I.e. cu101 (not supported) and rocm (beta) sounds reasonable.
> But Python-3.6 and MacOS needs some discussion.
> Same about ASAN config: what is the motivation behind it?

We were only planning to test cuda builds (10.2 and 11.1), so that's why I removed ASAN configs, since they don't seem to be run on cuda. However, I have added them back. @harishsk, does these subset of builds look ok, or should I remove any others?

2021-05-17 16:03 UTC, malfet approved these changes

2021-05-17 16:03 UTC, malfet commented on .circleci/cimodel/data/simple/ge_config_tests.py
> -    ),
Why this configuration is getting removed? (which tests some of the jit legacy modes?)

2021-05-17 17:52 UTC, Lynx1820 commented
@malfet do you know if it's possible to disable the `pr/pytorch-linux-bionic-rocm4.1-py3.6` build?

2021-05-17 19:33 UTC, seemethere commented
> @malfet do you know if it's possible to disable the `pr/pytorch-linux-bionic-rocm4.1-py3.6` build?

@jithunnair-amd or @jeffdaily is it possible to disable this jenkins job for particular branches?

2021-05-17 20:56 UTC, jeffdaily commented
> > @malfet do you know if it's possible to disable the `pr/pytorch-linux-bionic-rocm4.1-py3.6` build?
> 
> @jithunnair-amd or @jeffdaily is it possible to disable this jenkins job for particular branches?

Why do we want to disable our Jenkins job for PRs?

2021-05-17 21:55 UTC, Lynx1820 commented
> > > @malfet do you know if it's possible to disable the `pr/pytorch-linux-bionic-rocm4.1-py3.6` build?
> > 
> > 
> > @jithunnair-amd or @jeffdaily is it possible to disable this jenkins job for particular branches?
> 
> Why do we want to disable our Jenkins job for PRs?

The LTS branch will not be responsible for supporting rocm, so we're trying to remove all builds that include this configuration, which includes the Jenkins job.

2021-05-26 23:11 UTC, Lynx1820 commented
> > > @malfet do you know if it's possible to disable the `pr/pytorch-linux-bionic-rocm4.1-py3.6` build?
> > 
> > 
> > @jithunnair-amd or @jeffdaily is it possible to disable this jenkins job for particular branches?
> 
> Why do we want to disable our Jenkins job for PRs?

@jeffdaily any updates on this?

2021-06-04 18:08 UTC, jeffdaily commented
@Lynx1820 , ossci-job-dsl that controls our Jenkins jobs was updated by @seemethere in https://github.com/pytorch/ossci-job-dsl/pull/104.

2021-06-11 21:27 UTC, malfet approved these changes

2022-04-12 18:28 UTC, seemethere approved these changes

2022-05-12 18:41 UTC, closed without merging