Only sync CUDA if the operation is run on GPU
pytorch/pytorch pull request #58564
Opened 2021-05-19 15:52 UTC by Flamefire

This fixes test failures when PyTorch is build without CUDA

Fixes #58563

I used the same is_cuda check that is used in test_nn.py

2021-05-20 05:44 UTC, ailzhang approved these changes

2021-05-20 17:22 UTC, ailzhang commented on test/test_torch.py
> +                out = torch.multinomial(probs.to(device), 2)
Can you just use the passed in `device` argument here?

2021-05-20 17:22 UTC, ailzhang requested changes
LGTM! Just had a minor question, rebasing should fix the flaky CI as well. Thanks!

2022-04-16 07:04 UTC, Flamefire commented
not stale

2022-05-16 07:37 UTC, closed without merging