[nnc] Add hardsigmoid
pytorch/pytorch pull request #59069
Opened 2021-05-27 06:20 UTC by bertmaher

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2021-05-27 06:22 UTC, bertmaher commented
@bertmaher has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28738166).

2021-05-27 15:14 UTC, eellison approved these changes
looks good! if you add symbolic script support it will also speed up training and not just inference :)

2021-05-27 16:54 UTC, bertmaher commented
> looks good! if you add symbolic script support it will also speed up training and not just inference :)

Nice!  Do we have a test harness for backward where I can add hardsigmoid to make sure I've done my differentiation correctly?

2021-05-27 16:57 UTC, eellison commented
Yep, you can follow as https://github.com/pytorch/pytorch/pull/58773/files

2021-05-27 20:50 UTC, desertfire commented on torch/csrc/jit/runtime/symbolic_script.cpp
> +                return torch.where((result > -3.) & (result < 3.), 0., grad_output * (1.0 / 6.0))
I think you need to swap the if and else part.

2021-05-27 20:54 UTC, desertfire requested changes
symbolic_script.cpp needs to updated.

2021-05-27 22:18 UTC, bertmaher commented
Thank you.  I was misled by the order of args of Vec:vblend, and didn't think hard enough about the math :-(.  It's disturbing that no tests caught this?

2021-05-27 22:29 UTC, eellison commented
yea, that is not good... I think we need to add more warmup runs to trigger the path

2021-05-27 23:27 UTC, Krovatkin commented
@bertmaher could you try adding your test here : https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/jit_metaprogramming_utils.py I wonder if its the integration of autodiff testing into OpInfo or our actual autodiff testing that's borked.

2021-06-01 17:59 UTC, desertfire approved these changes

2021-06-03 20:17 UTC, bertmaher commented
@bertmaher has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28738166).

2021-06-04 06:12 UTC, closed without merging