nonzero: Default to transposed output strides
pytorch/pytorch pull request #59370
Opened 2021-06-03 11:42 UTC by peterbell10

Fixes #46224

cc @ailzhang

2021-06-08 19:23 UTC, ailzhang requested changes
Hey @peterbell10 thanks for sending out the PR! I think now I figure out what's happening in the failed test, it's actually a bit indirect but triggered by this change. 

To start with, this change returns a strided tensor for `nonzero` instead of always contiguous tensor. This now goes through a different path when we call `result.to('xla')` in AtenXlaTypeDefault.cpp. Namely it calls `as_strided` with an unsupported config in native xla so it pushes back to CPU(https://github.com/pytorch/xla/blob/master/torch_xla/csrc/aten_xla_type.cpp#L591) for execution. However our cpu implementation of `to` employes `empty_strided` for some cases, which creates an infinite call loop here: 
`to -> empty_strided -> as_strided -> to`. 

To break the loop, we shouldn't call empty_strided when `options.device()=='xla'`, https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/TensorConversions.cpp#L36 A better fix is that we have `device.support_as_strided()` and condition on it here. (note it's currently on tensor but can be moved down to device. https://github.com/pytorch/pytorch/blob/master/c10/core/TensorImpl.h#L907

Hopefully this explains what cause of the failed test, please feel free to ping me if you have any other questions! Thanks!

2021-06-15 20:12 UTC, peterbell10 commented
@ngimel the suggested changes seem to have worked.

2021-06-15 20:19 UTC, ngimel approved these changes

2021-06-17 05:52 UTC, closed without merging

2021-10-13 18:07 UTC, ngimel commented
No, we don't provide guarantees on the strides of the output and have changed them in the past.