add support for constant
pytorch/pytorch pull request #60166
Opened 2021-06-17 08:33 UTC by praneethratna

Fixes #{58739} Add support for constants according to python array API stipulation.
Also sorry as I have made a mess with commits , so have to delete the previous branch

2021-06-17 08:34 UTC, praneethratna commented
@pmeier sorry as I have made a mess with commits , so have to delete the previous branch, I`ve updated here again

2021-06-17 09:34 UTC, pmeier requested changes
> sorry as I have made a mess with commits , so have to delete the previous branch, I`ve updated here again

Happens to the best of us :wink: You accidentally included updates to the `ideep` submodule in the branch. Here is how you get them out again:

```shell
$ cd $PYTORCH/third_party/ideep 
$ git checkout f9468ff1a3d601b509ebe2c17d2ed0a58dffacee
$ git commit -am "revert submodule update"
$ git push
```

If you run `git submodule update` after doing a `git pull` you won't have this problem in the future.

2021-06-17 09:35 UTC, pmeier commented
For reference, the old PR is #59910.

2021-06-17 10:45 UTC, praneethratna commented
@pmeier I have tried your steps but i am getting a permission denied while trying to push could you help me figure it out?

2021-06-17 10:50 UTC, pmeier commented
You need to perform these steps while on your branch. "Permission denied" most likely means that your trying to push to branch that isn't yours. Probably master.

2021-06-17 10:51 UTC, praneethratna commented
I have tried these steps on my branch itself but still it shows "Permission Denied"

2021-06-17 11:01 UTC, pmeier commented
Ahh sorry, do a `cd $PYTORCH` before the commit.

2021-06-17 11:37 UTC, pmeier commented
The commit is still there. Is it ok for you if I fix the branch so we can land this PR?

2021-06-17 11:38 UTC, praneethratna commented
yes absolutely not an issue 😃

2021-06-17 13:59 UTC, pmeier approved these changes
Should be good to go now. Thanks @praneethratna!

2021-06-17 14:50 UTC, pmeier commented on torch/__init__.py
> +# for Python Array API consistency (https://data-apis.org/array-api/latest/API_specification/constants.html) and NumPy consistency (https://numpy.org/devdocs/reference/constants.html)
```suggestion
# For Python Array API (https://data-apis.org/array-api/latest/API_specification/constants.html) and 
# NumPy consistency (https://numpy.org/devdocs/reference/constants.html)
```

2021-06-17 14:52 UTC, pmeier commented on torch/__init__.py
> +# NumPy consistency (https://numpy.org/devdocs/reference/constants.html)
```suggestion
# For Python Array API (https://data-apis.org/array-api/latest/API_specification/constants.html) and
# NumPy consistency (https://numpy.org/devdocs/reference/constants.html)
```

2021-06-20 08:36 UTC, mruberry approved these changes
Cool, thank you @praneethratna!

2021-06-22 03:47 UTC, closed without merging

2024-04-26 22:27 UTC, mikaylagawarecki reviewed
EDIT: Sorry I unintentionally commented here