Mkl sets num threads locally
pytorch/pytorch pull request #60471
Opened 2021-06-22 16:50 UTC by raven38

Fixes #60469

In `ParallelOpenMP.cpp`
https://github.com/pytorch/pytorch/blob/cac9ae1506feabfc87d37a208b3d39ed46c59483/aten/src/ATen/ParallelOpenMP.cpp#L44-L65

Instead of `omp_set_num_threads` which changes the number of threads locally, `mkl_set_num_threads` changes the number of threads globally. I think changing the number of threads should only be done locally after a fork.

2021-06-22 20:10 UTC, imaginary-person commented
@raven38, do you also have any idea about solving #60000? Thanks!

2021-06-23 02:45 UTC, raven38 commented
@imaginary-person, thank you for the comment.  I have no idea now. I'll check it.

2021-07-15 18:14 UTC, ejguan requested changes
Thank you for filing the issue and submitting the patch. This change makes sense. Could you please add a test for it?

2021-07-16 16:06 UTC, raven38 commented
Could I make a cpp file under `pytorch/aten/src/ATen/test/` for test?

2021-07-16 17:49 UTC, ejguan commented
@raven38 
Can you add test to this file? https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/test/test_parallel.cpp

2021-08-02 18:33 UTC, ejguan commented
Hey @raven38, just want to follow up to check if you are still working on it?

2021-08-09 14:41 UTC, ejguan commented
@raven38 
I just merge a PR taking this PR as a reference and add a test against this problem. Closing this PR for now. Really appreciate your investigation and work.

2021-08-09 14:41 UTC, closed without merging

2021-08-11 01:44 UTC, raven38 commented
@ejguan 
Hi, I couldn't touch the PR recently. Thank you for adding the test.