Default initial hidden states for recurrent layers #434
pytorch/pytorch pull request #605
Opened 2017-01-27 02:33 UTC by goelhardik

Setting a default initial hidden state of zeros if the hidden state is not provided by the user. Doing this in the RNNBase class, so it works for all three - RNN, GRU and LSTM.

2017-01-27 10:03 UTC, apaszke requested changes

2017-01-27 10:03 UTC, apaszke commented on torch/nn/modules/rnn.py
> +        if (hx == None):
Remove parenthesis and change to `hx is None`.

2017-01-27 10:03 UTC, apaszke commented on torch/nn/modules/rnn.py
> +            batch_sz = input.size()[0] if self.batch_first else input.size()[1]
Use `input.size(0)` and `input.size(1)`.

2017-01-27 10:03 UTC, apaszke commented on torch/nn/modules/rnn.py
> +            hx = torch.autograd.Variable(torch.Tensor(self.num_layers, batch_sz,
Should be `self.num_layers * num_directions`. Also, use `input.new` instead of `torch.Tensor` (won't work for GPU otherwise).

2017-01-27 10:03 UTC, apaszke commented on torch/nn/modules/rnn.py
> +                                                   self.input_size).zero_())
Should be `self.hidden_size`.

2017-01-27 10:03 UTC, apaszke commented on torch/nn/modules/rnn.py
> +            if (self.mode == 'LSTM'):
Remove parenthesis

2017-01-27 10:03 UTC, apaszke commented on torch/nn/modules/rnn.py
> +                      torch.autograd.Variable(hx.data))
Use the same Variable twice, it's not supported to have many `Variable`s referencing the same tensor.
`hx = (hx, hx)`

2017-01-27 15:36 UTC, apaszke commented
One last thing. Can you please add a test that uses this change? Just instantiate one of each kind of RNNs we have and pass a batch through it - once without passing the hidden state, and once with a manually constructed one. Then use `self.assertEqual` to compare them and make sure that it works as we want. Thanks!

2017-01-29 02:27 UTC, goelhardik commented
I think I did a merge while trying to rebase my branch - that's why it shows the last commit 722c407. Is this okay? Should I try to revert this or just go ahead with adding the test case?

2017-01-29 04:38 UTC, soumith commented
go ahead and add the testcase. we'll squash it down before merging.

2017-01-29 11:38 UTC, apaszke approved these changes

2017-01-29 11:38 UTC, merged