Fix `searchsorted` not contiguous out
pytorch/pytorch pull request #60508
Opened 2021-06-23 03:13 UTC by emcastillo

Fixes  #60492

TODO: add test

2021-07-13 18:15 UTC, heitorschueroff requested changes
@emcastillo Thank you for fixing this bug. You have a small bug where you're checking for contiguity in out instead of result. And although not part of your changes, would you replace the resize call with a call to `at::native::resize_output` which is the preferred way to resize out tensors. Besides that, mostly stylistic changes.

Also, could you create an OpInfo test for `searchsorted`. The OpInfo should automatically test for the`out=` parameter and should fail for the current implementation which does not work for discontiguous out tensors.

Feel free to ping me if you have any questions and I look forward to the next update. Thanks!

2021-07-13 18:15 UTC, heitorschueroff commented on aten/src/ATen/native/Bucketization.cpp
> +  if (!out.is_contiguous()) {
out -> result

2021-07-13 18:15 UTC, heitorschueroff commented on aten/src/ATen/native/Bucketization.cpp
>    return result;
Can you combine lines 104-107 above with these ones so there's a single return statement. The two different dispatch calls can be in an if-else statement.

2021-07-13 18:15 UTC, heitorschueroff commented on aten/src/ATen/native/Bucketization.cpp
> +  }
Can you move lines 92 and 96-98 after line 101 which is when we do need to create the out tensor?

2021-07-13 18:15 UTC, heitorschueroff commented on aten/src/ATen/native/Bucketization.cpp
>      result.resize_(self.sizes());
We should use `at::native::resize_output` for resizing output tensors passed with `out=` parameter. It already checks that either the `out` tensor is empty or it's size is correct with the desired size.

2021-07-13 18:15 UTC, heitorschueroff commented on aten/src/ATen/native/cuda/Bucketization.cu
>      result.resize_(self.sizes());
Same as above, use at::native::resize_output

2021-07-13 18:15 UTC, heitorschueroff commented on aten/src/ATen/native/cuda/Bucketization.cu
> +  Tensor out = result;
nit: we usually want to declare variables closest to when we need them, could you move this before line 116

2021-07-13 18:15 UTC, heitorschueroff commented on aten/src/ATen/native/cuda/Bucketization.cu
> +  }
Same as above, could you combine the two dispatch cases in an if-else and have a single is_contiguous check?

2021-07-19 08:18 UTC, emcastillo commented
Hi!
Thanks for the review!
I am currently looking info regarding the `OpInfo` tests but I can only find TODOs in the tests/ folder 😅

2021-07-19 11:32 UTC, heitorschueroff commented
> I see the implementation in `toirch/testing/_internal/common_methods_invocations.py` but should the `searchsorted` test go there?

Good question! All OpInfo tests currently go into the list here https://github.com/pytorch/pytorch/blob/552eab7935c44d5f04b727fc4914559d6029ea64/torch/testing/_internal/common_methods_invocations.py#L4776

You can read through a few examples as well as the comment on the OpInfo class. Let me know if you have any questions regarding the tests, I am happy to answer them. Once you'd like me to take another look at the PR please request my review again. Thanks!

2021-11-09 01:57 UTC, closed without merging