[quant, sparsity] Generic convert function
pytorch/pytorch pull request #60728
Opened 2021-06-25 08:01 UTC by z-a-f

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2021-06-29 01:49 UTC, raghuramank100 commented on torch/ao/utils/__init__.py
> +def convert(model: nn.Module, mapping: dict = None, config: dict = None) -> nn.Module:
For eager mode, the API should only take the config for sparsity, the qconfig is an attribute of the module.  The config is identical to the config arg that is passed to the prepare function of the sparsifier.

```
config = {
        ...         'seq.0.linear1': {
        ...             'zero_block_shape': (1, 4)
        ...         'seq.0.linear2: {
        ...             'zero_block_shape': (1, 4)
        ...         }
        ... }
```

2021-06-29 02:41 UTC, raghuramank100 commented on torch/ao/utils/__init__.py
> +    for mode in config.keys():
Lets do this instead.  We can reuse the logic in swap_module for eager mode quantization and keep the configs for 
sparsity and quantization separate
```python


def convert(model: nn.Module, mapping: dict = None, config: dict = None, convert_custom_config_dict:dict=None) -> nn.Module:
if mapping is None:
        mapping = dict()
    if config is None:
        raise AttributeError('Currently, you have to specify the convert config')
    mapping.setdefault('quantized', torch.quantization.get_static_quant_module_class())
    mapping.setdefault(
        'sparse_quantized',
        {
            'static': {nn.Linear, torch.ao.nn.sparse.quantized.Linear},
            'dynamic': {nn.Linear, torch.ao.nn.sparse.quantized.dynamic.Linear},
        })
   if 'sparse' in config:
        raise AttributeError('FP sparse convert is not yet supported')

    if convert_custom_config_dict is None:
        convert_custom_config_dict = {}
    custom_module_class_mapping = convert_custom_config_dict.get("observed_to_quantized_custom_module_class", {})

  model = _joint_convert(model, mapping, config, custom_module_class_mapping)

 def _joint_convert(model, mapping, config, custom_module_class_mapping):
       reassign = {}
       for name, mod in module.named_children():
        # both fused modules and observed custom modules are
        # swapped as one unit
        if not isinstance(mod, _FusedModule) and \
           type(mod) not in custom_module_class_mapping:
            _joint_convert(mod, mapping, config)
            # if mod has qconfig attribute and is present in sparsifier config:
            if hasattr(mod, 'qconfig') 
                 if _module_to_path(mod) in config:
                    mapping = mapping['sparse_quantized']
                 else: 
                    mapping = mapping['quantized']
               # custom module class mapping will not work with sparsity, for now we could set it to None.
                 torch.quantization.swap_module(mod, mapping, custom_module_class_mapping)
                
            
        reassign[name] = swap_module(mod, mapping, custom_module_class_mapping)

    for key, value in reassign.items():
        module._modules[key] = value
 return module

2021-06-29 02:41 UTC, raghuramank100 requested changes
Please see comments

2021-06-29 19:11 UTC, z-a-f commented
@zafartahirov has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29465899).

2021-06-29 20:25 UTC, z-a-f commented
@zafartahirov has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29465899).

2021-07-01 10:31 UTC, z-a-f commented
@zafartahirov has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29465899).

2021-07-01 20:43 UTC, z-a-f commented
@zafartahirov has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29465899).

2021-07-01 21:36 UTC, z-a-f commented
@zafartahirov has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29465899).

2021-07-02 17:54 UTC, z-a-f commented
@zafartahirov has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29465899).

2021-07-02 19:15 UTC, z-a-f commented
@zafartahirov has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29465899).

2022-05-13 10:39 UTC, closed without merging