fix torch.cat bug with boxed CPUFallback
pytorch/pytorch pull request #60993
Opened 2021-06-29 21:59 UTC by bdhirsh

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2021-06-29 22:12 UTC, bdhirsh commented
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29471577).

2021-06-30 16:33 UTC, asuhan requested changes

2021-06-30 16:33 UTC, asuhan commented on aten/src/ATen/native/CPUFallback.cpp
> +            for (auto& tens_list : tensorlist_args) {
This should go in a helper, it's too hard to tell right away what these nested loops are doing.

2021-06-30 19:54 UTC, bdhirsh commented
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29471577).

2021-06-30 20:12 UTC, asuhan approved these changes

2021-06-30 20:23 UTC, asuhan commented on aten/src/ATen/native/CPUFallback.cpp
> +  c10::optional<c10::Device> tgt_device = c10::nullopt;
This is unused.

2021-06-30 20:49 UTC, bdhirsh commented
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29471577).

2021-07-01 04:22 UTC, ezyang approved these changes
okey dokey

2021-07-08 02:29 UTC, closed without merging