[package] PackageExporter visualization methods
pytorch/pytorch pull request #61147
Opened 2021-07-01 22:54 UTC by Lilyjjo

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2021-07-06 16:06 UTC, Lilyjjo commented
@Lilyjjo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29559683).

2021-07-07 21:07 UTC, suo requested changes
Overall looks good to me, had some small comments to improve API consistency

2021-07-07 21:07 UTC, suo commented on torch/package/package_exporter.py
> +    def externed_list(self) -> List[str]:
maybe `externed_modules` and so on?

2021-07-07 21:07 UTC, suo commented on torch/package/package_exporter.py
> +    def relied_on_by(self, module_name: str) -> List[str]:
The "rely" language is not previously present in the API/docs—I think we should try to stay consistent with talking about "dependencies". The typical term is "reverse dependency", so maybe: `get_reverse_dependencies` or `get_rdeps`,

2021-07-07 21:07 UTC, suo commented on torch/package/package_exporter.py
> +        """Return a list of all modules which rely on the module ``module_name``.
rely -> depend

2021-07-09 17:02 UTC, Lilyjjo commented
@Lilyjjo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29559683).

2021-07-09 17:19 UTC, suo approved these changes

2021-07-09 22:27 UTC, closed without merging