[pytorch] Lazy Module Fix for kwargs argument support on forward
pytorch/pytorch pull request #61606
Opened 2021-07-13 22:23 UTC by ertrue

Summary:
This is a fix to resolve the issue: #35643 and #59923

It should not impact LazyModuleExtensionMixin, which contains the lazy_apply feature.

TorchRec user should still use LazyModuleExtensionMixin instead of LazyModuleMixin

Test Plan:
python3 test: caffe2/test/test_nn.py

python3 test on torchrec/fb/module

Differential Revision: D29687148

2021-07-15 13:10 UTC, albanD requested changes

2021-07-15 13:10 UTC, albanD commented on torch/nn/modules/lazy.py
> +        self._initialize_hook = self.register_forward_pre_hook(self._infer_parameters, with_kwargs=True)
This would be BC-breaking no?
Even for simple things like the LazyLinear, this will make it fail if any argument is passed as a kwargs.

2021-07-15 13:10 UTC, albanD commented on torch/nn/modules/module.py
> +            return self.hook(module, input)
You will need to fix the return type here to make sure both the updated input and kwargs are returned.

2021-07-15 13:10 UTC, albanD commented on torch/nn/modules/module.py
> +                result = hook_wrapper.run(self, input, kwargs)
This should allow to update the kwargs now

2022-05-13 10:39 UTC, closed without merging

2023-03-07 03:15 UTC, y-x-c commented
hi team, is there a plan to support this feature in the future? Thanks.