Test PR: Back out "Revert D29687143: [3/N] Nnapi Backend Delegate Preprocess: Basic OSS Test"
pytorch/pytorch pull request #61878
Opened 2021-07-20 00:52 UTC by Amyh11325

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Summary:
Using this PR to test CI tests in
https://github.com/pytorch/pytorch/pull/61787, since I'm also trying to
learn how to debug by rerunning jobs with SSH.

Test Plan:

Reviewers:

Subscribers:
myuan

Tasks:

Tags:

2021-07-20 03:50 UTC, iseeyuan commented
Looks like it has the undefined python symbol issue with Mac build?

2021-07-20 19:19 UTC, Amyh11325 commented
@Amyh11325 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29799895).

2021-07-20 19:45 UTC, iseeyuan approved these changes
LGTM. Thanks!

2021-07-20 19:45 UTC, iseeyuan commented on test/jit/test_backend_nnapi.py
> +from torch.testing._internal.common_utils import (
Please fix the lint error before landing it.

2021-07-20 19:46 UTC, iseeyuan requested changes

2021-07-20 21:35 UTC, iseeyuan approved these changes

2021-07-20 22:14 UTC, Amyh11325 commented
@Amyh11325 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29799895).

2021-07-21 05:42 UTC, Amyh11325 commented
@Amyh11325 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29799895).

2021-07-21 19:00 UTC, closed without merging