[pytorch] don't LOG by default when everything is fine
pytorch/pytorch pull request #61943
Opened 2021-07-21 02:21 UTC by ppwwyyxx

Summary:
These logs are added in D24183463 (https://github.com/pytorch/pytorch/commit/c83314e9829822fcdc765e0b1eb9585a6b114c83) for debugging.

However in fbcode they appear in everyone's job. A normal job that runs fine should ideally not print extra logs. So I changed some that I observed to VLOG.

Test Plan: no longer see these logs when training

Differential Revision: D29810706

2021-07-21 04:25 UTC, rohan-varma requested changes
I think demoting the watchdog to VLOG may be fine, although keeping the PG NCCL init is IMO very valuable when things go wrong and the distributed team needs to debug.

Even regarding the watchdog, it can be useful to see this log in certain jobs to ensure nothing went wrong with NCCL as we frequently run into hangs etc.

2021-07-21 21:25 UTC, ppwwyyxx commented
Default behavior for a python library should be to not print anything that's not error/warning. Debugging is a rare event and I think these logs should be enabled only when needed, like how `NCCL_DEBUG=info` is used. 

It currently heavily affects user experience: for 8GPU tasks, logs from this file always take up more than a whole screen and is especially problematic for small workloads that don't print much themselves:
```
I0719 10:50:33.485718 219407 ProcessGroupNCCL.cpp:482] [Rank 3] ProcessGroupNCCL initialized with following options:
NCCL_ASYNC_ERROR_HANDLING: 0
NCCL_BLOCKING_WAIT: 0                                                                                                                                                                 
TIMEOUT(ms): 1800000                                                                                                                                                                  
USE_HIGH_PRIORITY_STREAM: 0                                                                                                                                                           
NCCL_DEBUG: WARN                                                                                                                                                                      
I0719 10:50:33.485716 219402 ProcessGroupNCCL.cpp:482] [Rank 1] ProcessGroupNCCL initialized with following options:
NCCL_ASYNC_ERROR_HANDLING: 0
NCCL_BLOCKING_WAIT: 0
TIMEOUT(ms): 1800000
USE_HIGH_PRIORITY_STREAM: 0
NCCL_DEBUG: WARN
I0719 10:50:33.485841 220673 ProcessGroupNCCL.cpp:581] [Rank 1] NCCL watchdog thread started!
I0719 10:50:33.485882 220672 ProcessGroupNCCL.cpp:581] [Rank 3] NCCL watchdog thread started!      
I0719 105033.485 distributed_c10d.py:213] Added key: store_based_barrier_key:1 to store for rank: 3                 
I0719 105033.485 distributed_c10d.py:213] Added key: store_based_barrier_key:1 to store for rank: 1
I0719 10:50:33.559300 219400 ProcessGroupNCCL.cpp:482] [Rank 0] ProcessGroupNCCL initialized with following options:
NCCL_ASYNC_ERROR_HANDLING: 0
NCCL_BLOCKING_WAIT: 0
TIMEOUT(ms): 1800000
USE_HIGH_PRIORITY_STREAM: 0
NCCL_DEBUG: WARN
I0719 10:50:33.559444 220675 ProcessGroupNCCL.cpp:581] [Rank 0] NCCL watchdog thread started!
I0719 105033.559 distributed_c10d.py:213] Added key: store_based_barrier_key:1 to store for rank: 0
I0719 10:50:33.577245 219415 ProcessGroupNCCL.cpp:482] [Rank 4] ProcessGroupNCCL initialized with following options:
NCCL_ASYNC_ERROR_HANDLING: 0
NCCL_BLOCKING_WAIT: 0
TIMEOUT(ms): 1800000
USE_HIGH_PRIORITY_STREAM: 0
NCCL_DEBUG: WARN
I0719 10:50:33.577381 220676 ProcessGroupNCCL.cpp:581] [Rank 4] NCCL watchdog thread started!
I0719 105033.577 distributed_c10d.py:213] Added key: store_based_barrier_key:1 to store for rank: 4
I0719 10:50:33.583372 219404 ProcessGroupNCCL.cpp:482] [Rank 2] ProcessGroupNCCL initialized with following options:
NCCL_ASYNC_ERROR_HANDLING: 0
NCCL_BLOCKING_WAIT: 0
TIMEOUT(ms): 1800000
USE_HIGH_PRIORITY_STREAM: 0
NCCL_DEBUG: WARN
I0719 10:50:33.583511 220677 ProcessGroupNCCL.cpp:581] [Rank 2] NCCL watchdog thread started!                                                                                         
I0719 105033.583 distributed_c10d.py:213] Added key: store_based_barrier_key:1 to store for rank: 2                                                                                   
I0719 10:50:33.672052 219421 ProcessGroupNCCL.cpp:482] [Rank 5] ProcessGroupNCCL initialized with following options:                                                                  
NCCL_ASYNC_ERROR_HANDLING: 0                                                                                                                                                          
NCCL_BLOCKING_WAIT: 0                                                                                                                                                                 
TIMEOUT(ms): 1800000                                                                                                                                                                  
USE_HIGH_PRIORITY_STREAM: 0                                                                                                                                                           
NCCL_DEBUG: WARN                                                                                                                                                                      
I0719 10:50:33.672153 220684 ProcessGroupNCCL.cpp:581] [Rank 5] NCCL watchdog thread started!                                                                                         
I0719 105033.672 distributed_c10d.py:213] Added key: store_based_barrier_key:1 to store for rank: 5                                                                                   
I0719 10:50:33.844262 219427 ProcessGroupNCCL.cpp:482] [Rank 6] ProcessGroupNCCL initialized with following options:                                                                  
NCCL_ASYNC_ERROR_HANDLING: 0                                                                                                                                                          
NCCL_BLOCKING_WAIT: 0                                                                                                                                                                 
TIMEOUT(ms): 1800000                                                                                                                                                                  
USE_HIGH_PRIORITY_STREAM: 0                                                                                                                                                           
NCCL_DEBUG: WARN                                                                                                                                                                      
I0719 10:50:33.844411 220687 ProcessGroupNCCL.cpp:581] [Rank 6] NCCL watchdog thread started!                                                                                         
I0719 105033.844 distributed_c10d.py:213] Added key: store_based_barrier_key:1 to store for rank: 6                                                                                   
I0719 10:50:33.853435 219432 ProcessGroupNCCL.cpp:482] [Rank 7] ProcessGroupNCCL initialized with following options:                                                                  
NCCL_ASYNC_ERROR_HANDLING: 0                                                                                                                                                          
NCCL_BLOCKING_WAIT: 0                                                                                                                                                                 
TIMEOUT(ms): 1800000                                                                                                                                                                  
USE_HIGH_PRIORITY_STREAM: 0                                                                                                                                                           
NCCL_DEBUG: WARN
I0719 10:50:33.853551 220688 ProcessGroupNCCL.cpp:581] [Rank 7] NCCL watchdog thread started!
I0719 105033.854 distributed_c10d.py:213] Added key: store_based_barrier_key:1 to store for rank: 7
I0719 105033.854 distributed_c10d.py:247] Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 8 nodes.
I0719 105033.854 distributed_c10d.py:247] Rank 7: Completed store-based barrier for key:store_based_barrier_key:1 with 8 nodes.

```

2021-08-03 18:29 UTC, ppwwyyxx commented
Any comments?

Another thing we can do to reduce messages is to only print initialization messages on rank0.

2021-12-06 21:24 UTC, pritamdamania87 commented
@ppwwyyxx We definitely need these logs to aid in debugging. This is not similar to `NCCL_DEBUG=INFO` where you can enable it and run your local test script again. There are very expensive production jobs that run and might fail later on and logging like this helps considerably to debug failed jobs.

For your particular use case, you can set your glog level to WARN and none of the `LOG(INFO)` prints would appear.

2022-05-13 10:40 UTC, closed without merging