[ONNX] add tests for custom_opsets param from torch.onnx.export() function.
pytorch/pytorch pull request #61969
Opened 2021-07-21 17:09 UTC by hwangdeyu

`custom_opsets` arg from torch.onnx.export() is no needed to be removed.
Add some description and tests for easier understanding.

2021-07-21 18:42 UTC, neginraoof requested changes

2021-07-21 18:42 UTC, neginraoof commented on test/onnx/test_pytorch_onnx_onnxruntime.py
> +    def test_custom_opsets_triu(self):
We already have tests for this argument in test_utility_funs.py.
Is the purpose of the new tests to verify ORT custom kernels? Or you are just testing the custom export functionality?

2021-07-21 18:47 UTC, neginraoof commented on torch/onnx/__init__.py
> +            opset_version is used on ONNX opset version.
```suggestion
            Note that only custom opset domain name and version should be indicated through this argument.
```

2021-07-23 08:50 UTC, hwangdeyu commented
Close this PR,  as it adds a lot of reviewers that should not be added.

2021-07-23 08:50 UTC, closed without merging