Add squid proxy as egress cache
pytorch/pytorch pull request #62103
Opened 2021-07-23 18:40 UTC by zhouzhuojie

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2021-07-23 19:19 UTC, malfet commented
Can you please add a bit more details to PR description? I.e. why both `http_proxy` and `HTTP_PROXY` is needed. Same about `use_proxy=on`

2021-07-23 19:19 UTC, janeyx99 approved these changes

2021-07-23 19:19 UTC, malfet requested changes
I think you are missing `-e` option in bazel workflow template

2021-07-23 19:19 UTC, malfet commented on .github/templates/bazel_ci_workflow.yml.j2
> +            -e use_proxy=on http_proxy="$SQUID_PROXY" -e https_proxy="$SQUID_PROXY" -e HTTP_PROXY="$SQUID_PROXY" -e HTTPS_PROXY="$SQUID_PROXY" \
```suggestion
            -e use_proxy=on -e http_proxy="$SQUID_PROXY" -e https_proxy="$SQUID_PROXY" -e HTTP_PROXY="$SQUID_PROXY" -e HTTPS_PROXY="$SQUID_PROXY" \
```

2021-07-23 19:19 UTC, malfet commented on .github/templates/bazel_ci_workflow.yml.j2
> +            -e use_proxy=on http_proxy="$SQUID_PROXY" -e https_proxy="$SQUID_PROXY" -e HTTP_PROXY="$SQUID_PROXY" -e HTTPS_PROXY="$SQUID_PROXY" \
```suggestion
            -e use_proxy=on -e http_proxy="$SQUID_PROXY" -e https_proxy="$SQUID_PROXY" -e HTTP_PROXY="$SQUID_PROXY" -e HTTPS_PROXY="$SQUID_PROXY" \
```

2021-07-24 01:06 UTC, zhouzhuojie commented
@zhouzhuojie has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29892919).

2021-07-26 18:35 UTC, seemethere approved these changes
LGTM

Note entirely sure if case matters for these calls but the Docker documentation does suggest using all uppercase for the env variable names:

<img width="1011" alt="Screen Shot 2021-07-26 at 11 35 10 AM" src="https://user-images.githubusercontent.com/1700823/127040770-7b1a4917-f8c0-424a-b1d4-a8f8593a798e.png">

From https://docs.docker.com/network/proxy/

2021-07-26 18:37 UTC, driazati approved these changes
lgtm too, just curious if squid proxy is down / unreachable for some reason all network accesses will timeout / fail right?

2021-07-26 18:43 UTC, zhouzhuojie commented
> lgtm too, just curious if squid proxy is down / unreachable for some reason all network accesses will timeout / fail right?

Yes, the proxy is in the critical path, and we will beef up the monitoring of it

2021-07-26 18:47 UTC, zhouzhuojie commented
> LGTM
> 
> Note entirely sure if case matters for these calls but the Docker documentation does suggest using all uppercase for the env variable names:
> 
> <img alt="Screen Shot 2021-07-26 at 11 35 10 AM" width="1011" src="https://user-images.githubusercontent.com/1700823/127040770-7b1a4917-f8c0-424a-b1d4-a8f8593a798e.png">
> 
> From https://docs.docker.com/network/proxy/

The common http clients usually respect both format, and lowercase is kind of the default. Found a good summary on this topic

https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/


![image](https://user-images.githubusercontent.com/658840/127042321-e00d4192-5b28-4532-9a1a-eadaa1a357d8.png)

2021-07-26 18:49 UTC, malfet approved these changes

2021-07-26 20:02 UTC, closed without merging