[Static Runtime] Enabled building Static Runtime tests and benchmarks in OSS CI
pytorch/pytorch pull request #62226
Opened 2021-07-26 23:25 UTC by navahgar

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2021-07-26 23:27 UTC, navahgar commented
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29923800).

2021-07-27 21:05 UTC, navahgar commented
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29923800).

2021-07-28 00:11 UTC, malfet requested changes
It does not sound like a good idea to force building this benchmark for all opensource users by default. This could be enabled in CI by adding `export BUILD_STATIC_RUNTIME_BENCHMARK=ON` to https://github.com/pytorch/pytorch/blob/master/.jenkins/pytorch/build.sh for one of the supported configs, for example, similarly how torch_deploy is tested right now:
https://github.com/pytorch/pytorch/blob/e3be185069b3ae183c3575b8fe5ebe44f6728b62/.jenkins/pytorch/build.sh#L27-L30

2021-07-28 18:32 UTC, navahgar commented
> It does not sound like a good idea to force building this benchmark for all opensource users by default. This could be enabled in CI by adding `export BUILD_STATIC_RUNTIME_BENCHMARK=ON` to https://github.com/pytorch/pytorch/blob/master/.jenkins/pytorch/build.sh for one of the supported configs, for example, similarly how torch_deploy is tested right now:
> https://github.com/pytorch/pytorch/blob/e3be185069b3ae183c3575b8fe5ebe44f6728b62/.jenkins/pytorch/build.sh#L27-L30

Thanks for that pointer. That is very helpful.

While I know that we don't want to enable this for `*mobile*` builds, I am not sure about the rest. Is there anyway to figure that out? Is there any place where I can find the full list of builds?

2021-07-28 18:56 UTC, navahgar commented
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29923800).

2021-07-28 21:52 UTC, navahgar commented
Also, one other related question: how can I ensure the tests built by setting this env variable, specifically `build/bin/static_runtime_test` runs every time in CI? @malfet

2021-07-28 23:12 UTC, malfet approved these changes

2021-07-28 23:12 UTC, malfet commented on .jenkins/pytorch/build.sh
> +  if [[ "${BUILD_ENVIRONMENT}" != *android* && "${BUILD_ENVIRONMENT}" != *ios* && "${BUILD_ENVIRONMENT}" != *mobile* && "${BUILD_ENVIRONMENT}" != *cuda* ]]; then
Android and cuda should be sufficient, shouldn't it, as `ios` builds could not run on linux
```suggestion
  if [[ "${BUILD_ENVIRONMENT}" != *android* && "${BUILD_ENVIRONMENT}" != *cuda* ]]; then
```

2021-07-29 00:22 UTC, navahgar commented
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29923800).

2021-07-29 16:22 UTC, navahgar commented
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29923800).

2021-08-02 18:55 UTC, navahgar commented
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29923800).

2021-08-02 20:56 UTC, navahgar commented
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29923800).

2021-08-03 05:24 UTC, navahgar commented
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29923800).

2021-08-03 15:54 UTC, closed without merging