Show warning in eager mode for empty containers
pytorch/pytorch pull request #62978
Opened 2021-08-09 17:21 UTC by karolsputo

Fixes #{54873}

2021-08-11 19:52 UTC, ansley requested changes
Looks great! I left a small note about the wording of your warning, but it's otherwise ready to go. Thanks for contributing!

2021-08-12 08:41 UTC, karolsputo commented on torch/_jit_internal.py
> +        warnings.warn("Type annotations are lost in eager mode. False posivites will be shown for empty containers.")
I see how that's accurate, thanks. I've changed it slightly, hope you don't mind.

2021-08-12 08:41 UTC, karolsputo reviewed
Fixed the warning text.

2021-08-12 13:47 UTC, ansley commented on torch/_jit_internal.py
> +        warnings.warn("Type annotations are lost in eager mode. False posivites will be shown for empty containers.")
Perfect! I like your phrasing a lot better...mine was too wordy :)

2021-08-12 13:49 UTC, ansley approved these changes
Great job, Karol! Thanks for working on these OSS issues. I'll try to keep my eye out for some other good ones you could do, if you'd like. Do you have an area of focus or special interest?

2021-08-12 14:51 UTC, karolsputo commented
I'm currently trying to get a feel for the whole codebase so no specific areas. I'm taking a look at some DataParallel issues right now for a change. I'm interested in AI frameworks and training hardware so I'd like to progressively get closer to the core and hardware stuff. Taking small steps :)

2021-08-12 23:12 UTC, closed without merging