Move auto_gpu code into auto_gpu.cpp
pytorch/pytorch pull request #6361
Opened 2018-04-06 19:54 UTC by goldsborough

Fixes #6285 -- auto_gpu.h should be include-able without CUDA

Also puts `AutoGPU` into the `torch::` namespace, which I think is better style

CC @ebetica

2018-04-06 21:04 UTC, colesbury requested changes
`auto_gpu.h` is already includable without CUDA. Don't move it to a .cpp file -- it's included in performance critical code paths.

2018-04-06 21:16 UTC, goldsborough commented
Yes but not without `WITH_CUDA` (sorry I was unclear in the description). @ebetica mentioned it was annoying to have to define this in their build when using this file, when they already define `WITH_CUDA` when compiling pytorch. By moving it into the cpp file it gets baked into the library and they don't have to define it. @colesbury will this be a major performance hit? @ebetica we might have to keep it then

2018-04-06 21:30 UTC, ebetica commented
What about one of the AT_CUDA_ENABLED macros?

2018-04-06 21:32 UTC, goldsborough commented
Hmm I don't see it used anywhere in `torch/csrc`. @colesbury what do you think?

2018-04-06 21:35 UTC, colesbury commented
I don't see how that fixes the issue. AT_CUDA_ENABLED() shouldn't be used in public headers

2018-04-06 21:36 UTC, colesbury commented
It makes things more complicated, but you can have two AutoGPU classes, one for internal use with everything in the header and the other as a public class

2018-04-06 21:51 UTC, goldsborough commented
@ebetica would it be feasible for you to do this inside autogradpp?

2018-04-07 04:52 UTC, ebetica commented
Definitely possible. AFAIK it's already done. Feel free to close.

2018-04-07 05:27 UTC, closed without merging

2018-04-08 20:58 UTC, ezyang commented
@colesbury I don't see why `AT_CUDA_ENABLED` can't be used in public headers, if inlining is needed. It's defned in a configure generated header which we install in users, so it will work correctly in any situation. What we're not supposed to do is change the API depending on if you compiled with CUDA or not, but that's not what's going on here.

2018-04-09 17:14 UTC, ebetica commented
Yes, I think it's already done. Feel free to close.