ENH Adds _zero_if_all_neg_inf to softmax for multiheadattention
pytorch/pytorch pull request #63730
Opened 2021-08-22 01:04 UTC by thomasjpfan

Fixes https://github.com/pytorch/pytorch/issues/41508
Fixes https://github.com/pytorch/pytorch/issues/55056

1. This PR adds a private `_zero_if_all_neg_inf` kwarg to `softmax` that sets the softmax to 0 when `-inf`. Another option would be to add a new `_safe_softmax` operator. 

2. For CPU kernels, the `_zero_if_all_neg_inf` is passed to the kernel as a boolean option. For CUDA, `_zero_if_all_neg_inf` is passed down and the dispatched to different templates.

3. I ran the following CPU/GPU benchmark script and this PR does not add any additional overhead to softmax:

<details>
 <summary>Benchmark script</summary>

```python
from itertools import product

import torch
import torch.nn as nn
import torch.nn.functional as F
import time
import statistics

torch.manual_seed(0)
MS_PER_SECOND = 1000

def _time(device):
    if device == "cuda":
        torch.cuda.synchronize()
    return time.perf_counter() * MS_PER_SECOND

devices = ["cuda", "cpu"]
n_runs = 30
device_Ns = [
    ("cuda", 64),
    ("cuda", 128),
    ("cuda", 256),
    ("cuda", 512),
    ("cuda", 1024),
    ("cpu", 64),
    ("cpu", 128),
    ("cpu", 256),
]
dims = [0, 1, 2]

for (device, N), dim in product(device_Ns, dims):
    total_fwd_times = []

    for _ in range(n_runs):
        input = torch.randn(N, 1000, 1000, device=device)

        # forward
        start = _time(device)
        F.softmax(input, dim=dim)
        total_fwd_times.append(_time(device) - start)

    fwd_avg = statistics.mean(total_fwd_times)
    fwd_std = statistics.stdev(total_fwd_times)
    print(
        f"input size({N}, 1000, 1000), dim={dim}, device={device}, "
        f"fwd: {fwd_avg:.2f} +/- {fwd_std:.2f}(ms)"
    )

```

</details>

2021-08-23 20:56 UTC, thomasjpfan commented
I updated this PR by adding a new private operator: `_safe_softmax_last_dim`. Since MHA only uses the last dimension for softmax, I restricted this PR to only work with the last dimension. This reduces the number of changes in the CPU kernels.

For the CUDA kernels, this PR updates `SoftMaxForwardEpilogue` to template out `_zero_if_all_neg_inf`, which is used to compute the softmax.

2021-08-23 21:40 UTC, thomasjpfan commented
Comparing `_safe_softmax_last_dim` to `softmax(dim=-1)` with a tensor with `-inf`.

<details>
 <summary>Benchmark script</summary>

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import time
import statistics

torch.manual_seed(0)
MS_PER_SECOND = 1000


def _time(device):
    if device == "cuda":
        torch.cuda.synchronize()
    return time.perf_counter() * MS_PER_SECOND


devices = ["cuda", "cpu"]
n_runs = 30
device_Ns = [
    ("cuda", 64),
    ("cuda", 128),
    ("cuda", 256),
    ("cuda", 512),
    ("cuda", 1024),
    ("cpu", 64),
    ("cpu", 128),
]

for device, N in device_Ns:
    total_softmax_times = []
    total_safe_softmax_times = []

    for _ in range(n_runs):
        input = torch.randn(N, 1000, 1000, device=device)
        input[N//2:] = float("-inf")

        # forward
        start = _time(device)
        input.softmax(dim=-1)
        total_softmax_times.append(_time(device) - start)

        # forward
        start = _time(device)
        input._safe_softmax_last_dim()
        total_safe_softmax_times.append(_time(device) - start)

    soft_fwd_avg = statistics.mean(total_softmax_times)
    soft_fwd_std = statistics.stdev(total_softmax_times)

    safe_fwd_avg = statistics.mean(total_safe_softmax_times)
    safe_fwd_std = statistics.stdev(total_safe_softmax_times)
    print(
        f"input size({N}, 1000, 1000), device={device}, "
        f"soft_fwd: {soft_fwd_avg:.2f} +/- {soft_fwd_std:.2f}(ms) "
        f"safe_fwd: {safe_fwd_avg:.2f} +/- {safe_fwd_std:.2f}(ms) "
    )


```

</details>

I get:

```
input size(64, 1000, 1000), device=cuda, soft_fwd: 0.63 +/- 0.05(ms) safe_fwd: 0.62 +/- 0.00(ms) 
input size(128, 1000, 1000), device=cuda, soft_fwd: 1.23 +/- 0.05(ms) safe_fwd: 1.22 +/- 0.00(ms) 
input size(256, 1000, 1000), device=cuda, soft_fwd: 2.45 +/- 0.10(ms) safe_fwd: 2.43 +/- 0.00(ms) 
input size(512, 1000, 1000), device=cuda, soft_fwd: 4.88 +/- 0.18(ms) safe_fwd: 4.86 +/- 0.01(ms) 
input size(1024, 1000, 1000), device=cuda, soft_fwd: 9.75 +/- 0.31(ms) safe_fwd: 9.71 +/- 0.01(ms) 
input size(64, 1000, 1000), device=cpu, soft_fwd: 29.37 +/- 1.28(ms) safe_fwd: 14.65 +/- 0.71(ms) 
input size(128, 1000, 1000), device=cpu, soft_fwd: 60.92 +/- 1.57(ms) safe_fwd: 29.77 +/- 1.03(ms)
```

The safe softmax does not add any time to the `cuda` implementation and reduces the runtime for `cpu`.

2021-09-09 00:17 UTC, jbschlosser requested changes
As discussed offline, we have decided not to move forward with this approach, but rather to wait for a better fix involving correct masking semantics.

2021-09-09 00:18 UTC, closed without merging

2023-09-18 10:46 UTC, rodosingh commented on torch/nn/functional.py
> +    attn = attn._safe_softmax_last_dim()
@jbschlosser and @ngimel I found out that using `nan_to_num(0.0)` doesn't solve the issue as after the **first forward pass**, `Q`, `K`, and `V` (of course) becomes `nan` (tried and tested).

So without even going for replacing `1`s with `-inf` as done in `.masked_fill(tensor, float("-inf"))`, we can just multiply `1-attn_mask` (as `PyTorch` convention of masking is different from that of `Hugging-Face`) with `softmax(Q*K^T)`, and that solves the problem. Again we just need to do `.masked_fill(tensor, 1.0)`.

Here is the snippet of code that describes what I explained above:
```python3
def _scaled_dot_product_attention(
    q: Tensor,
    k: Tensor,
    v: Tensor,
    attn_mask: Optional[Tensor] = None,
    dropout_p: float = 0.0,
) -> Tuple[Tensor, Tensor]:
    r"""
    Computes scaled dot product attention on query, key and value tensors, using
    an optional attention mask if passed, and applying dropout if a probability
    greater than 0.0 is specified.
    Returns a tensor pair containing attended values and attention weights.

    Args:
        q, k, v: query, key and value tensors. See Shape section for shape details.
        attn_mask: optional tensor containing mask values to be added to calculated
            attention. May be 2D or 3D; see Shape section for details.
        dropout_p: dropout probability. If greater than 0.0, dropout is applied.

    Shape:
        - q: :math:`(B, Nt, E)` where B is batch size, Nt is the target sequence length,
            and E is embedding dimension.
        - key: :math:`(B, Ns, E)` where B is batch size, Ns is the source sequence length,
            and E is embedding dimension.
        - value: :math:`(B, Ns, E)` where B is batch size, Ns is the source sequence length,
            and E is embedding dimension.
        - attn_mask: either a 3D tensor of shape :math:`(B, Nt, Ns)` or a 2D tensor of
            shape :math:`(Nt, Ns)`.

        - Output: attention values have shape :math:`(B, Nt, E)`; attention weights
            have shape :math:`(B, Nt, Ns)`
    """
    B, Nt, E = q.shape
    q = q / math.sqrt(E)
    # (B, Nt, E) x (B, E, Ns) -> (B, Nt, Ns)
    # if attn_mask is not None:
    #     attn = torch.baddbmm(attn_mask, q, k.transpose(-2, -1))
    # else:
    attn = torch.bmm(q, k.transpose(-2, -1))

    attn = F.softmax(attn, dim=-1)
    if attn_mask is not None:
        attn = attn * (1-attn_mask)
    if dropout_p > 0.0:
        attn = F.dropout(attn, p=dropout_p)
    # (B, Nt, Ns) x (B, Ns, E) -> (B, Nt, E)
    output = torch.bmm(attn, v)
    return output, attn
```
#### Detailed explanation and cause of issue is explained [here](https://github.com/pytorch/pytorch/issues/41508#issuecomment-1723119580) at #41508.