Fixes #6386, Use copies instead of symbolic files
pytorch/pytorch pull request #6396
Opened 2018-04-08 05:30 UTC by peterjc123

2018-04-08 14:33 UTC, ezyang submitted a review, later dismissed
Won't your working copy still be clobbered after running setup.py?

2018-04-08 14:35 UTC, peterjc123 commented
@ezyang No, it is listed in `.gitignore`. So the working copy won't change.

2018-04-08 14:41 UTC, ezyang commented
That's not how gitignore works. If a file is already committed in the repo, gitignore has no affect on whether or not updates show up or not.

2018-04-08 14:44 UTC, peterjc123 commented
@ezyang So would you please tell me what should I do?

2018-04-08 20:35 UTC, apaszke requested changes

2018-04-08 20:35 UTC, apaszke commented on setup.py
> +    shutil.copyfile(orig_file, sym_file)
We probably don't want to do this every time `setup.py` is ran. It should be part of the command that needs it (`build_deps`?)

2018-04-08 20:50 UTC, ezyang commented
I think one concrete course of action that will probably work is to delete the symlink `tools/shared/cwrap_common.py`, and then do some sort of copy to fill it in (as I mentioned in #6386). The primary downside is that timestamp on the file would keep changing, but given that it's Python I don't think it should matter that much; at least, the Windows code suggests as much. @apaszke I don't know what you think about that, but I don't think it should cause too much trouble.

2018-04-08 21:03 UTC, apaszke commented
@ezyang if you put things in `setup.py` then they will run no matter what command you execute. This include things like `egginfo`, which should only print some information, and we should avoid side effects in this case.

2018-04-09 10:44 UTC, apaszke approved these changes

2018-04-09 17:54 UTC, merged