Skip superfluous store operations while constructing tensors from data
pytorch/pytorch pull request #65331
Opened 2021-09-20 13:17 UTC by cbalioglu

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Differential Revision: [D31055036](https://our.internmc.facebook.com/intern/diff/D31055036/)

2021-09-20 13:43 UTC, ezyang requested changes
thanks, much appreciated. Just a small semantics change and this is good to go. A test for the case I mention would also be great.

2021-09-20 13:43 UTC, ezyang commented on torch/csrc/utils/tensor_new.cpp
> +    }
When the source is meta, I'd prefer if we error in this case (because the target will be uninitialized garbage if you don't copy here)

2022-01-21 01:38 UTC, cbalioglu commented
@ezyang I actually simplified the logic a bit in the second revision which is now also covered by the existing tests.

2022-02-10 03:17 UTC, ezyang approved these changes

2022-02-11 12:55 UTC, closed without merging