Fix  some mistake usage of LinearFunction.backward(...) and a argument of gradcheck(...) in the documents
pytorch/pytorch pull request #6587
Opened 2018-04-13 14:05 UTC by sccbhxc

2018-04-13 14:27 UTC, zou3519 requested changes
Thanks for the catch! It is intended that we're using `ctx.saved_tensors` instead of `ctx.saved_variables.`

2018-04-13 14:27 UTC, zou3519 commented on docs/source/notes/extending.rst
> -            # unpack saved_tensors and initialize all gradients w.r.t. inputs to
We renamed saved_variables as saved_tensors, so this change is not necessary

2018-04-13 14:27 UTC, zou3519 commented on docs/source/notes/extending.rst
> -            input, weight, bias = ctx.saved_tensors
See above

2018-05-01 09:12 UTC, SsnL commented
@sccbhxc Thanks for your PR. This is good to merge once the minor nit is fixed.

2018-05-21 15:20 UTC, zou3519 commented
https://github.com/pytorch/pytorch/pull/7725 fixes this, so I'm closing this PR.

2018-05-21 15:20 UTC, closed without merging