Add uniform to onnx export
pytorch/pytorch pull request #66263
Opened 2021-10-07 17:19 UTC by metalprogrammer

Fixes #42230 and #54483
ONNX supports RandomUniform from opset 1 but there was not a file for said opset in torch/onxx, please advise if the symbol should be moved to a different file,

2021-10-08 14:05 UTC, ezyang requested changes
This isn't going to fly, renaming from/to is a BC-breaking change for traditional Python API. Why do you need to rename it anyway?

2021-10-11 01:56 UTC, ezyang commented
Good point. Can you file an issue about this?

For your case, there is a simple workaround: accept the arguments as kwargs and then you can get out the from keyword argument.

cc @mruberry for possibility of making uniform accept low/high making it more similar to numpy

2021-10-25 18:10 UTC, garymm requested changes

2021-11-02 16:55 UTC, metalprogrammer commented on test/onnx/test_operators.py
> +        self.assertONNX(lambda x: x.uniform_(2, to=2), x, operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN)
@garymm I will remove this test. it looks like there are tests for uniform export in test/onnx/test_pytorch_onnx_onnxruntime.py so is there any further additions I should add there?
https://github.com/pytorch/pytorch/blob/master/test/onnx/test_pytorch_onnx_onnxruntime.py#L10030-L10064

2021-11-02 17:15 UTC, metalprogrammer commented on torch/onnx/symbolic_opset9.py
> +    from_v = g.op("Constant", value_t=torch.tensor(from_, dtype=torch.float))
Previous version used them and just forgot to remove them, they are now gone

2021-11-02 17:15 UTC, metalprogrammer commented on torch/onnx/symbolic_opset9.py
> +    return g.op("Uniform", self, generator, **kwargs)
Completed

2021-11-02 18:34 UTC, garymm commented on test/onnx/test_operators.py
> +        self.assertONNX(lambda x: x.uniform_(2, to=2), x, operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN)
If there's no test that fails before this change and passes now then I don't understand what you're actually fixing or improving.
I just checked and exporting distributions.Uniform seems to work on the latest PyTorch nightly:

```python
!pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html -U
import torch
print("torch version:", torch.__version__)

class M(torch.nn.Module):
    def forward(self, x, y):
        return torch.distributions.Uniform(x, y).sample().size(0), x , y

m = M()
inp = (torch.tensor([[0.0], [6.0]]), torch.tensor([[1.0], [7.0]]))
torch.onnx.export(
    m, inp,
    "/dev/null", verbose=True, opset_version=9)
```

Produces output:
```
torch version: 1.11.0.dev20211102+cpu
graph(%0 : Float(2, 1, strides=[1, 1], requires_grad=0, device=cpu),
      %1 : Float(2, 1, strides=[1, 1], requires_grad=0, device=cpu)):
  %2 : Long(2, strides=[1], device=cpu) = onnx::Shape(%0) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %3 : Float(2, 1, device=cpu) = onnx::ConstantOfShape[value={0}](%2) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %4 : Float(2, 1, strides=[1, 1], device=cpu) = onnx::Add(%3, %0) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %5 : Float(2, 1, strides=[1, 1], device=cpu) = onnx::Add(%4, %1) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %6 : Long(2, strides=[1], device=cpu) = onnx::Shape(%5) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %7 : Float(2, 1, strides=[1, 1], requires_grad=0, device=cpu) = onnx::Expand(%0, %6) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %8 : Long(2, strides=[1], device=cpu) = onnx::Shape(%5) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %9 : Float(2, 1, strides=[1, 1], requires_grad=0, device=cpu) = onnx::Expand(%1, %8) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %10 : Long(requires_grad=0, device=cpu) = onnx::Constant[value={2}]() # <ipython-input-5-6eed90abf6ca>:3:0
  return (%10, %7, %9)
```

Maybe this got fixed at some point (maybe in https://github.com/pytorch/pytorch/pull/33789)?

2021-11-11 23:01 UTC, garymm commented
Awaiting responses from @metalprogrammer to my comments [here](https://github.com/pytorch/pytorch/pull/66263#discussion_r741366575).

If there's no response in a few weeks I'll close this PR.

2021-11-12 16:41 UTC, closed without merging