[sharded_tensor] easier initialization for Shard
pytorch/pytorch pull request #66351
Opened 2021-10-08 23:26 UTC by wanchaol

Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #66351
* #64481

This add the ability for use to just provide shard_offsets and optionally rank, to construct a local shard, instead of knowing there's a ShardedMetadata. Under the hood, we will construct the ShardedMetadata by inferring shard_lengths and device from the local tensor.

Differential Revision: [D31519919](https://our.internmc.facebook.com/intern/diff/D31519919/)

2021-10-09 01:04 UTC, pritamdamania87 reviewed
Could you also add a short description of the use case which needs this sort of construction?

2021-10-13 17:23 UTC, bowangbj reviewed
Thanks Wanchao.

2021-10-18 19:45 UTC, pritamdamania87 requested changes
@wanchaol Maybe your changes weren't pushed to gh successfully? I don't see any updates to the PR in the latest version.

2021-10-26 00:50 UTC, pritamdamania87 approved these changes

2021-10-28 05:20 UTC, closed without merging