[sparsity] Enable FX quantization for sparse linear
pytorch/pytorch pull request #66779
Opened 2021-10-18 07:11 UTC by z-a-f

Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #66779
* #66778
* #66777
* #69415

Tests: TBD

Differential Revision: [D31835720](https://our.internmc.facebook.com/intern/diff/D31835720)

2021-10-20 21:38 UTC, vkuzo requested changes
It's not ideal to attach a custom attribute to a module in one framework and then check for that attribute in a different framework.  A way to make this more discoverable would be to annotate the `sparse_params` attribute on all types of modules which are expected to support it.  Requesting changes for now, would be great to discuss next steps.

2021-12-03 18:29 UTC, z-a-f commented
@zafartahirov has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31835720).

2021-12-03 19:17 UTC, vkuzo commented on torch/ao/quantization/fx/quantization_patterns.py
> +                                         additional_static_quant_mapping)
this still means that quantization knows about sparsity.  If we want them to be fully independent, we could move this to an external API.  Something like

```
prepare_custom_config_dict = {
  'float_to_observed_custom_module_class_with_lambda': {
    'static': {
      'float_class': torch.nn.Linear,
      'observed_class': torch.ao.nn.sparse.Linear,  # or whatever the type is
      'lambda': lambda x: module_has_sparse_params(x),
    },
  },
  # repeat for observed to quantized
}
```

and then make the quantization prepare and convert honor these swaps with lambda

or something similar

2021-12-04 08:36 UTC, z-a-f commented
@zafartahirov has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31835720).

2021-12-04 08:43 UTC, z-a-f commented
@zafartahirov has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31835720).

2021-12-04 09:18 UTC, z-a-f commented
@zafartahirov has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31835720).

2021-12-08 18:22 UTC, z-a-f commented
@zafartahirov has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31835720).

2022-06-20 22:37 UTC, closed without merging