[ONNX] Remove the argument example_outpus of export() method entirely.
pytorch/pytorch pull request #67082
Opened 2021-10-22 07:29 UTC by hwangdeyu

This argument was deprecated in PyTorch 1.10: https://github.com/pytorch/pytorch/pull/62815.
Now we remove this argument entirely.

## BC-breaking note
### The signature of torch.onnx.export() function is changed: the argument `example_outpus ` has been removed.

In version 1.9 and older, `example_outputs` was required when the input was a `ScriptModule`.
In version 1.10, `example_outputs` was deprecated and never required.
In latest version, setting `example_outpus` will fail.

Example code:

Version 1.10 and older:

```python
model = torch.jit.script(MyModel())
example_outputs = model(x)
torch.onnx.export(model, (x,), "model.onnx", example_outputs=example_outputs)
```

Version 1.11:

```python
model = torch.jit.script(MyModel())
torch.onnx.export(model, (x,), "model.onnx")
```

2021-10-25 18:39 UTC, garymm requested changes
Please add a BC-breaking note in the PR description. See here for an example: https://github.com/pytorch/pytorch/pull/66611

2021-10-28 16:33 UTC, garymm approved these changes
Please address the comment before merging. Thanks!

2021-10-29 08:28 UTC, merged

2021-11-01 17:32 UTC, BowenBao commented
@hwangdeyu There is CI failure for this PR ...
```
2021-10-29T08:42:06.7066630Z ――――――――――――――――――― TestUtilityFuns_opset11.test_output_list ―――――――――――――――――――
2021-10-29T08:42:06.7067528Z Traceback (most recent call last):
2021-10-29T08:42:06.7068546Z   File "/var/lib/jenkins/workspace/test/onnx/test_utility_funs.py", line 144, in test_output_list
2021-10-29T08:42:06.7069580Z     opset_version=self.opset_version)
2021-10-29T08:42:06.7072385Z   File "/opt/conda/lib/python3.6/unittest/case.py", line 203, in __exit__
2021-10-29T08:42:06.7073576Z     self._raiseFailure("{} not raised".format(exc_name))
2021-10-29T08:42:06.7079677Z   File "/opt/conda/lib/python3.6/unittest/case.py", line 135, in _raiseFailure
2021-10-29T08:42:06.7080830Z     raise self.test_case.failureException(msg)
2021-10-29T08:42:06.7081833Z AssertionError: RuntimeError not raised
```

Are we expecting this test to pass now after this change?

2021-11-01 20:36 UTC, BowenBao commented on test/onnx/test_utility_funs.py
> +                # type: (Tensor, int) -> List[Tensor]
I think the test was to catch incorrect `example_outputs` format... See original PR #55802.

The model output is intended to be single tensor, and the `example_outputs` is intended to be passed in as list, hence the runtime error.

2021-11-01 20:59 UTC, garymm commented on test/onnx/test_utility_funs.py
> +                # type: (Tensor, int) -> List[Tensor]
Thanks for looking into it @BowenBao. Sorry I didn't understand this enough when reviewing it initially.
@hwangdeyu please fix. If Bowen is right, this test is not needed now, so just delete it.

2021-11-02 14:27 UTC, hwangdeyu commented
> @hwangdeyu There is CI failure for this PR ...
> 
> ```
> 2021-10-29T08:42:06.7066630Z ――――――――――――――――――― TestUtilityFuns_opset11.test_output_list ―――――――――――――――――――
> 2021-10-29T08:42:06.7067528Z Traceback (most recent call last):
> 2021-10-29T08:42:06.7068546Z   File "/var/lib/jenkins/workspace/test/onnx/test_utility_funs.py", line 144, in test_output_list
> 2021-10-29T08:42:06.7069580Z     opset_version=self.opset_version)
> 2021-10-29T08:42:06.7072385Z   File "/opt/conda/lib/python3.6/unittest/case.py", line 203, in __exit__
> 2021-10-29T08:42:06.7073576Z     self._raiseFailure("{} not raised".format(exc_name))
> 2021-10-29T08:42:06.7079677Z   File "/opt/conda/lib/python3.6/unittest/case.py", line 135, in _raiseFailure
> 2021-10-29T08:42:06.7080830Z     raise self.test_case.failureException(msg)
> 2021-10-29T08:42:06.7081833Z AssertionError: RuntimeError not raised
> ```
> 
> Are we expecting this test to pass now after this change?
> 
> Update: looking at past PRs, I think this test can be removed after this change.

Yes, I have checked this test again, it can be removed.