[ONNX] Remove the argument use_external_data_format of export() method entirely.
pytorch/pytorch pull request #67080
Opened 2021-10-22 06:44 UTC by hwangdeyu

This was deprecated in PyTorch 1.10: https://github.com/pytorch/pytorch/pull/62257.
There are no any issue request yet.

## BC-breaking note
### The signature of `torch.onnx.export()` changed: the argument `use_external_data_format` has been removed.
Setting `use_external_data_format` in a call to `torch.onnx.export()` will fail. Since version 1.9, the `export()` code automatically uses the external data format if the exported model size > 2GiB.

Below are examples of how to export a large model:

Version 1.9 and older:
```
torch.onnx.export(MyModel(), (x,), 'test_export_arg.onnx', use_external_data_format=True)

```

Version 1.11
```
torch.onnx.export(MyModel(), (x,), 'test_export_arg.onnx')

```

2021-10-25 18:35 UTC, garymm requested changes

2021-10-25 18:36 UTC, garymm requested changes
Please add a BC-breaking note in the PR description. See here for an example: https://github.com/pytorch/pytorch/pull/66611

2021-10-29 17:16 UTC, garymm approved these changes

2021-11-01 08:00 UTC, hwangdeyu commented on torch/csrc/jit/python/python_ir.cpp
> +            bool val_use_external_data_format;
Cause we set it as `False` in _export_onnx before. Recovered it.

2021-11-01 08:04 UTC, hwangdeyu commented on torch/onnx/utils.py
> +                    val_add_node_names, False, model_file_location,
Removed it in `_export_onnx`. Still reserve it in export_onnx() in cpp, in case there are demand to using the external data format for normal model.

2021-11-01 13:52 UTC, merged