[ONNX] Add module name as PythonOp attribute
pytorch/pytorch pull request #67193
Opened 2021-10-25 17:09 UTC by shubhambhokare1

Stores the module name of the autograd function as attribute for a PythonOp node in the IR graph.

Before this modification:
```
graph(%input : Float(1, strides=[1], requires_grad=0, device=cpu)):
  %3 : Float(1, strides=[1], requires_grad=0, device=cpu) = ^MyExp[inplace=0]()(%input)]
  %6 : Float(1, strides=[1], requires_grad=0, device=cpu) = ^MyExp[inplace=0]()(%input)]
  %7 : int = prim::Constant[value=1]()
  %8 : Float(1, strides=[1], requires_grad=0, device=cpu) = aten::add(%3, %6, %7)
  return (%8)
```
After this modification:
```
graph(%input : Float(1, strides=[1], requires_grad=0, device=cpu)):
  %3 : Float(1, strides=[1], requires_grad=0, device=cpu) = ^MyExp[module="autograd1", inplace=0]()(%input)]
  %6 : Float(1, strides=[1], requires_grad=0, device=cpu) = ^MyExp[module="autograd2", inplace=0]()(%input)]
  %7 : int = prim::Constant[value=1]()
  %8 : Float(1, strides=[1], requires_grad=0, device=cpu) = aten::add(%3, %6, %7)
  return (%8)
```

2021-10-25 18:51 UTC, garymm requested changes
1. Could you please add a test that demonstrates the new behavior?
2. The PR title is misleading. This change does not actually add the fully qualified name as an attribute, it adds the module name. I think it'd be perfectly reasonable to add the qualified name instead if that's what you want to do. Just use `__qualname__` instead of `__module__`. That may actually be better since it seems from [the docs](https://docs.python.org/3/reference/datamodel.html) that `__module__` may be `None` but `__qualname__` should always be set. But either way seems OK to me, just make sure the PR title matches the implementation.

2021-12-09 20:01 UTC, garymm approved these changes
Thanks!

2021-12-09 20:01 UTC, garymm commented on torch/csrc/autograd/python_function.cpp
> +          node->s_(jit::attr::module, modname);
Suggestion for slightly more compact code without loss of clarity:
```suggestion
          node->s_(jit::attr::module, std::string(ptr));
```

2021-12-09 20:17 UTC, BowenBao commented on torch/csrc/autograd/python_function.cpp
> +    if (module_name) {
nit: more compat code, same with `ptr` below.
```suggestion
    if (auto module_name = PyDict_GetItemString(((PyTypeObject*)op_obj)->tp_dict, "__module__")) {
```

2021-12-09 23:26 UTC, BowenBao approved these changes
LGTM

2021-12-10 18:25 UTC, merged