Move Concat Linear out of Optimize Numerics
pytorch/pytorch pull request #67196
Opened 2021-10-25 17:55 UTC by Gamrix

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #67792
* #67201
* __->__ #67196

Differential Revision: [D32154788](https://our.internmc.facebook.com/intern/diff/D32154788)

2021-10-25 18:01 UTC, eellison reviewed
can you just remove https://github.com/pytorch/pytorch/blob/master/torch/jit/_freeze.py#L162 and have it call into `OptimizeFrozenGraph` ? originally there was some thought of python hackability etc, but we should just remove the duplication.

can you also hook up the pretranspose pass?

2021-10-26 22:56 UTC, eellison approved these changes

2021-10-26 22:57 UTC, eellison requested changes
we still need to replace the python api to call into this version, that's why no tests are breaking

2021-10-26 22:58 UTC, eellison reviewed
we're probably going to need to remove the MKLDNN Linear tests, that's fine. can we remove https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/frozen_ops_to_mkldnn.cpp#L939 the linear here and say that we get more speedup by pretransposing linear layers than running them in mkldnn

2021-10-27 16:24 UTC, eellison reviewed
hey, some of the tests need to be rewritten with conv

2021-10-28 00:47 UTC, eellison approved these changes
nice!!

2021-11-02 00:31 UTC, eellison commented
hey - we have an internal user who's optimization is blocked by this. could we try to land it ?

2021-11-03 17:05 UTC, Gamrix commented on torch/jit/_freeze.py
> +        - Pretranspose Linear Layers
Remove this one

2021-11-03 22:43 UTC, Gamrix commented
@gamrix has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32154788).

2021-11-04 18:32 UTC, closed without merging