Fix DLPack CUDA stream convention
pytorch/pytorch pull request #67618
Opened 2021-11-01 08:46 UTC by emcastillo

Apparently for the array API, cuda default stream and per thread stream should be 1 and 2 instead of 0 and 1:

https://data-apis.org/array-api/latest/API_specification/array_object.html?dlpack-self-stream-none#dlpack-self-stream-none.

This caused a problem in the interop with CuPy.

cc @rgommers @leofang @mruberry

2021-11-01 14:52 UTC, leofang requested changes
Thanks, Emilio! Look like we missed `stream_ptr` here?

2021-11-01 14:52 UTC, leofang commented on torch/utils/dlpack.py
> +                stream_ptr = 1
```suggestion
                stream_ptr = 1
            else:
                stream_ptr = stream.cuda_stream
```

2021-11-01 14:54 UTC, leofang commented
Question for @rgommers @mruberry: Would there be PyTorch 1.10.1? If so we should backport this patch.

2021-11-02 01:04 UTC, emcastillo commented on torch/utils/dlpack.py
> +                stream_ptr = 1
fixed in new commit, thanks!

2021-11-02 14:37 UTC, rgommers approved these changes
This LGTM, thanks @emcastillo!

2021-11-10 11:47 UTC, mruberry commented
Hey @emcastillo!

Thanks for this fix and your patience (I was moving from the West Coast to the East Coast)!

It looks like the ROCm failure is real, however:

```
08:18:53 ======================================================================
08:18:53 FAIL [0.075s]: test_dlpack_default_stream_cuda (__main__.TestTorchDeviceTypeCUDA)
08:18:53 ----------------------------------------------------------------------
08:18:53 Traceback (most recent call last):
08:18:53   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1422, in wrapper
08:18:53     method(*args, **kwargs)
08:18:53   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1422, in wrapper
08:18:53     method(*args, **kwargs)
08:18:53   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
08:18:53     result = test(self, **param_kwargs)
08:18:53   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 772, in dep_fn
08:18:53     return fn(slf, *args, **kwargs)
08:18:53   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 891, in only_fn
08:18:53     return fn(slf, *args, **kwargs)
08:18:53   File "test_torch.py", line 7336, in test_dlpack_default_stream
08:18:53     from_dlpack(x)
08:18:53   File "/opt/conda/lib/python3.6/site-packages/torch/utils/dlpack.py", line 68, in from_dlpack
08:18:53     dlpack = ext_tensor.__dlpack__(stream=stream_ptr)
08:18:53   File "test_torch.py", line 7328, in __dlpack__
08:18:53     assert stream == 1
08:18:53 AssertionError
```

Any idea what's going on there? One option would be to file a follow-up issue and skip the test on ROCm for now (with a link to the issue).

2021-11-10 14:48 UTC, rgommers commented
> It looks like the ROCm failure is real,

Stream numbering for CUDA and ROCm is different, it's `1` for CUDA default stream and `0` for ROCm: see https://data-apis.org/array-api/latest/API_specification/array_object.html#dlpack-self-stream-none. 

I have a vague memory about us talking about this before, and there being an issue with detecting whether we're running on ROCm, but I can't find it back.

2021-11-15 07:53 UTC, emcastillo commented
Thanks @mruberry, ler me take a closer look and fix it!

2021-11-17 02:17 UTC, emcastillo commented
@mruberry all tests passed :)

2021-11-18 04:16 UTC, mruberry approved these changes

2021-11-18 16:37 UTC, closed without merging