add BFloat16 operators on CPU: trace, histc, atan2
pytorch/pytorch pull request #67759
Opened 2021-11-03 09:13 UTC by jiayisunx

Fixes #{issue number}

2021-11-11 11:53 UTC, kshitij12345 requested changes
Thanks @jiayisunx 

OpInfo doesn't check for the correctness unless `ref` is specified. (And even if `ref` is specified it doesn't check for `bfloat16`). 
https://github.com/pytorch/pytorch/blob/aea4e61ec3dd1e1970232dc93abdf5cc2ff4a4a8/test/test_ops.py#L203-L207
So we will need additional test for that.

@mruberry should we also add OpInfo for `histc` while at it. (Or maybe that should be a seperate PR)?

2021-11-12 02:48 UTC, jiayisunx commented
> Thanks @jiayisunx
> 
> OpInfo doesn't check for the correctness unless `ref` is specified. (And even if `ref` is specified it doesn't check for `bfloat16`).
> 
> https://github.com/pytorch/pytorch/blob/aea4e61ec3dd1e1970232dc93abdf5cc2ff4a4a8/test/test_ops.py#L203-L207
> 
> 
> So we will need additional test for that.
> @mruberry should we also add OpInfo for `histc` while at it. (Or maybe that should be a seperate PR)?

I have added UT to check the BF16 correctness of these three OPs, thanks.

2021-11-12 12:38 UTC, kshitij12345 commented
Failure on CI looks real, you may have to relax the tolerances I think.

```
======================================================================
FAIL [0.004s]: test_trace_bfloat16_cuda_bfloat16 (__main__.TestShapeOpsCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1457, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
    result = test(self, **param_kwargs)
  File "test_shape_ops.py", line 268, in test_trace_bfloat16
    test(shape)
  File "test_shape_ops.py", line 258, in test
    self.assertEqual(tensor_bf16.trace().float(), tensor_fp32.trace())
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1938, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 1 element(s) (out of 1) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.03125 (14.25 vs. 14.21875), which occurred at index 0.

----------------------------------------------------------------------
```

2021-11-12 12:42 UTC, kshitij12345 commented on test/test_binary_ufuncs.py
> +            self.assertEqual(actual_bf16, actual.bfloat16())
I think we'd want to check against expected, since `actual` is similar to `expected` within certain tolerance only.

2021-11-12 12:45 UTC, kshitij12345 commented on test/test_binary_ufuncs.py
> +            self.assertEqual(actual_bf16, actual.bfloat16())
Also you can do `self.assertEqual(actual_bf16, expected, exact_dtype=False, rtol=,atol=)`.

2021-11-16 12:13 UTC, kshitij12345 commented on test/test_binary_ufuncs.py
> +            self.assertEqual(actual_bf16, actual.bfloat16())
I think we can just remove this `self.assertEqual(actual_bf16, actual.bfloat16())` as we are testing with expected below.

2021-11-16 12:14 UTC, kshitij12345 commented on test/test_shape_ops.py
> +            self.assertEqual(tensor_bf16.trace().float(), tensor_fp32.trace())
Even here we can use `self.assertEqual` with `exact_dtype=False` and tolerances as required.

2021-11-16 12:17 UTC, kshitij12345 commented
Failure on Windows looks real
```
/Focaffe2\CMakeFiles\torch_cpu.dir\__\aten\src\ATen\native\ReduceOps.cpp.obj /Fdcaffe2\CMakeFiles\torch_cpu.dir\ /FS -c C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\ReduceOps.cpp
C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\ReduceOps.cpp(1055): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'at::native::trace_cpu::<lambda_b4f287a6b69af1f77d5a008b887098f0>::()::<lambda_1d29e7e0893c0a371cafcacd9f815caf>::()::<lambda_38a6b36b69b9da6a0f4772f0a0aea6d0>'
C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\ReduceOps.cpp(1077): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\ReduceOps.cpp(1055): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'at::native::trace_cpu::<lambda_b4f287a6b69af1f77d5a008b887098f0>::()::<lambda_1d29e7e0893c0a371cafcacd9f815caf>::()::<lambda_52324e4c4d90eb340d744169279746ff>'
C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\ReduceOps.cpp(1077): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\ReduceOps.cpp(1055): error C2672: 'c10::guts::if_constexpr': no matching overloaded function found
C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\ReduceOps.cpp(1077): error C2780: 'decltype(auto) c10::guts::if_constexpr(ThenCallback &&,ElseCallback &&)': expects 2 arguments - 1 provided
C:\actions-runner\_work\pytorch\pytorch\c10/util/C++17.h(328): note: see declaration of 'c10::guts::if_constexpr'
```

2022-02-11 02:59 UTC, closed without merging