added set_printoptions examples
pytorch/pytorch pull request #68324
Opened 2021-11-14 17:48 UTC by aditkumar72

Added examples for `torch.set_printoptions`

```
>>> torch.set_printoptions(precision=2)
>>> torch.tensor([1.12345])
tensor([1.12])
>>> torch.set_printoptions(threshold=5)
>>> torch.arange(10)
tensor([0, 1, 2, ..., 7, 8, 9])
```

2021-11-15 21:53 UTC, mrshenli approved these changes
Thanks for contributing!

2021-11-15 21:54 UTC, mrshenli requested changes
Oops, lint error is real. Could you please fix?

```
torch/_tensor_str.py:45:    
The above lines have trailing spaces; please remove them
```

2021-11-16 13:31 UTC, aditkumar72 commented
@mrshenli I have made the changes; please review

2021-12-13 17:38 UTC, anjali411 approved these changes

2021-12-14 15:42 UTC, closed without merging