[ROCm] use hipCUB chained iterator
pytorch/pytorch pull request #68487
Opened 2021-11-16 23:13 UTC by jaglinux

For inclusive_scan and exclusive_scan, use hipCUB / rocPRIM's chained iterator.
Implemented for ROCm 5.0 and above.

Signed-off-by: Jagadish Krishnamoorthy <jagdish.krishna@gmail.com>

Fixes #60190

2021-11-17 22:10 UTC, zasdfgbnm commented
I don't understand the title of this PR, because I didn't see any "chained iterator" in the newly added path. But from the diff, are you saying that ROCm's `InclusiveScan` will handle 64bit indexing internally?

2021-11-17 22:18 UTC, jaglinux commented
Implementation is in hipCUB / rocPRIM,  @stanley.tsang@amd.com please provide the implementation details.

2021-11-17 22:47 UTC, stanleytsang-amd commented
Hi,

in response to @zasdfgbnm question, yes, large indices are now handled internally in hipCUB/rocPRIM.
https://github.com/ROCmSoftwarePlatform/rocPRIM/commit/5673df4422ad6f04dad1940024c3cf6cd7582c0c#diff-47f4ef75e5af60dd5fe3906df9cf971f0635602a6b64a706dee6633d6677ef1a

I suppose in that sense, rocPRIM/hipCUB aren't using chained iterators.  Perhaps a better PR title is "Use hipCUB/rocPRIM scan algorithms with large index support".

2021-11-17 23:51 UTC, zasdfgbnm approved these changes

2021-11-18 23:10 UTC, jithunnair-amd commented
@malfet This PR is ready to merge. Can you please take a look?

2021-11-18 23:38 UTC, malfet approved these changes

2021-11-18 23:41 UTC, malfet commented
Hmm, this PR does not really fixes #60190, as it does not remove `@skipIfRocm` decorator from the test, see
https://github.com/pytorch/pytorch/blob/ab1d879b33bae968e22e098b0e6aa01af821efe2/test/test_torch.py#L6248-L6251

2021-11-18 23:44 UTC, malfet requested changes
Marking as "Request change" to address the feedback (I can remove "Fixes" from the PR description myself, just let me know if the followup PR is coming)

2021-11-19 00:29 UTC, jaglinux commented
Removed the "fixes" comment, will re-enable the test when ROCm 5.0 is released.

2021-11-19 19:54 UTC, malfet approved these changes

2021-11-19 20:53 UTC, closed without merging