always use max cmake when cmake3 and cmake are all existed
pytorch/pytorch pull request #69355
Opened 2021-12-03 08:27 UTC by XiaobingSuper

For Pytorch source build when using Ninja generator, it requires **CMake >=3.13**,  Pytorch always check **cmake3 >= 3.10** first, so when we check  **3.13> cmake3 >= 3.10** and use cmake3, there will report an error: ```Using the Ninja generator requires CMake version 3.13 or greater``` even **cmake >=3.13**.  

For example: for my centos machine, the system cmake3 is ```3.12```,  and my conda env's cmake is ```3.19.6```,  there will have a build error which PyTorch choose cmake3,  One solution is to update cmake3,  but the cmake3 update needs root privileges which not applied to a non-root user. Another solution is always to use the max cmake version when cmake and cmake3 are all existed.

2021-12-08 01:57 UTC, XiaobingSuper commented
@gchanan, could you help review this PR? I think the user don't need to upgrade the system's cmake3 when conda's cmake has meet the build‘s requirements.

2021-12-13 15:14 UTC, XiaobingSuper commented
@malfet @ezyang

2021-12-13 15:41 UTC, malfet requested changes
Thank you for proposing the change. Overall change looks good to me, but can you please make a few BE changes:
- Instead of repeating `distutils.version.LooseVersion("3.10.0")` turn into a `_CMAKE_MIN_VERSION` constant
- Perhaps modify `CMake._get_version` to accept None and return None as result
Then the code will look much simpler.
Also, please modify PR description to jsut state, that `_get_cmake_command` should return newest cmake executable (unless explicitly overriden with same `CMAKE_PATH` environment variable)

And description about "updating cmake requires root privileges" is not accurate, one can always create an alias or a symlink

2021-12-15 05:21 UTC, malfet approved these changes

2021-12-15 05:21 UTC, malfet commented on tools/setup_helpers/cmake.py
> +                (cmake_version is None or cmake_version < _cmake_min_version):
```suggestion
        if all(ver is None or ver < _cmake_min_version) for ver in [cmake_version, cmake3_version]):
```

2021-12-15 07:47 UTC, XiaobingSuper commented on tools/setup_helpers/cmake.py
> +                (cmake_version is None or cmake_version < _cmake_min_version):
Chnaged.

2021-12-17 20:55 UTC, closed without merging