[onnx export] Add broadcast to matmul shape inference
pytorch/pytorch pull request #70534
Opened 2021-12-30 22:42 UTC by lazycal

When exporting a model to onnx format, the current shape inference logic of matmul does not take broadcast into consideration: 

https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/onnx/shape_type_inference.cpp#L974-L982 

It simply uses the larger-dimensional input as the output shape (for the broadcast dimensions). A reproducible code snippet:
```python
import torch
import numpy as np

class Model(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()

    def forward(self, x, y):
        return torch.matmul(x, y)

x_np = np.random.rand(1, 5, 8, 16).astype(np.float32)
y_np = np.random.rand(3, 1, 16, 4).astype(np.float32)
filename = 'output.onnx'

dummy_inputs = [torch.tensor(x_np), torch.tensor(y_np)]
print(Model()(*dummy_inputs).shape)
torch.onnx.export(
    Model(), tuple(dummy_inputs),
    filename,
    input_names=['x', 'y'],
    opset_version=14)

# uncomment the following lines to see what onnx shape inferencer complains about the shapes conflict
# from onnx import shape_inference, load
# inferred_model = shape_inference.infer_shapes(load("output.onnx")) 
```
The correct output shape should be [3,5,8,4], but got 1,5,8,4 from the generated model:
![image](https://user-images.githubusercontent.com/7333325/147789537-204823b2-8126-42cf-8de1-b267a966a0c1.png)

This PR fixes this issue by reusing the same code of broadcast from the function `ProcessBroadcastNode`.

2022-01-22 01:51 UTC, garymm requested changes
Thanks for the contribution!

Please add a test that fails before this change and passes afterwards.

Perhaps in test/jit/test_onnx_export.py

2022-01-22 01:51 UTC, garymm commented on torch/csrc/jit/passes/onnx/shape_type_inference.cpp
> +    for (auto idx = rank_min; idx < rank_max; idx++) {
```suggestion
    for (size_t idx = rank_min; idx < rank_max; idx++) {
```

2022-01-22 01:51 UTC, garymm commented on torch/csrc/jit/passes/onnx/shape_type_inference.cpp
> +      auto shape_idx = rank_max - 1 - idx;
```suggestion
      size_t shape_idx = rank_max - 1 - idx;
```

2022-01-22 01:51 UTC, garymm commented on torch/csrc/jit/passes/onnx/shape_type_inference.cpp
> +    for (auto idx = rank_min; idx < rank_max; idx++) {
```suggestion
    for (size_t idx = rank_min; idx < rank_max; idx++) {
```

2022-01-22 01:51 UTC, garymm commented on torch/csrc/jit/passes/onnx/shape_type_inference.cpp
> +      auto shape_idx = rank_max - 1 - idx;
```suggestion
      size_t shape_idx = rank_max - 1 - idx;
```

2022-01-22 01:51 UTC, garymm commented on torch/csrc/jit/passes/onnx/shape_type_inference.cpp
> +      std::vector<::c10::ShapeSymbol>(input_shape_value_0.begin(), input_shape_value_0.end() - 2),
Please add a comment explaining the `- 2`.

2022-01-22 01:51 UTC, garymm commented on torch/csrc/jit/passes/onnx/shape_type_inference.cpp
> +      final_shape.emplace_back(input_shape_value_1[rank_1 - 1]);
Please add a comment explaining the `- 1`.

2022-01-22 23:33 UTC, lazycal commented
@garymm Thanks for reviewing this PR! I have made the changes according to your suggesetion. One difference is that I put the unit test in test/onnx/test_pytorch_onnx_shape_inference.py. Can you take a look again?

2022-01-24 21:55 UTC, garymm approved these changes
Thanks!

2022-01-24 21:55 UTC, garymm commented on test/onnx/test_pytorch_onnx_shape_inference.py
> +    def test_bcast_matmul(self):
please spell out "broadcast"

2022-01-24 21:55 UTC, garymm commented on torch/csrc/jit/passes/onnx/shape_type_inference.cpp
> +    // the matmul supports the rank of either or both inputs to be 1
```suggestion
    // Inputs of rank 1 handled as in numpy.matmul:
    // https://numpy.org/doc/stable/reference/generated/numpy.matmul.html
```

2022-01-24 21:55 UTC, garymm commented on torch/csrc/jit/passes/onnx/shape_type_inference.cpp
> +    // the behavior is the same as appending a 1 to the input(s), do the matmul and remove the appended 1(s)
Please delete the rest of the comment.

2022-01-24 21:55 UTC, garymm commented on torch/csrc/jit/passes/onnx/shape_type_inference.cpp
> +    // the matmul supports the rank of either or both inputs to be 1
```suggestion
    // Handle inputs of rank 1 just like numpy.matmul:
    // https://numpy.org/doc/stable/reference/generated/numpy.matmul.html
```

2022-01-24 21:55 UTC, garymm commented on test/onnx/test_pytorch_onnx_shape_inference.py
> +    def test_bcast_matmul(self):
```suggestion
    def test_broadcast_matmul(self):
```

2022-01-24 23:51 UTC, lazycal commented
Thanks. The comment and name are changed as you suggested.

2022-01-25 19:28 UTC, garymm commented
@pytorchbot merge this

2022-01-25 21:27 UTC, garymm commented
@msaroufim could you please import this? (the new merge bot doesn't work for this case it seems)

2022-01-27 22:56 UTC, garymm commented
@lazycal if you open a new PR with the same content against the branch `onnx_ms_1`, then I can merge it for you, and it will eventually make it into `master`.

2022-01-28 07:20 UTC, lazycal commented
@garymm I changed the PR instead to merge into `onnx_ms_1`. If this is not OK I can also make a new PR.

2022-01-28 19:34 UTC, garymm commented
@lazycal please resolve the merge conflicts and then I will merge this.

2022-01-28 23:01 UTC, merged