fix: onnx PReLU unidirectional broadcasting
pytorch/pytorch pull request #70571
Opened 2022-01-03 04:50 UTC by ganler

Fixes https://github.com/pytorch/pytorch/issues/70570

2022-01-03 22:53 UTC, thiagocrepaldi reviewed
LGTM, could you also add a unit test for this case?

2022-01-04 00:21 UTC, ganler commented on torch/onnx/symbolic_opset9.py
> +    assert sym_help._get_tensor_rank(self) >= len(sym_help._get_tensor_sizes(weight)), "slope must be unidirectionally broadcastable to input tensor"
The bug needs to be reproduced using TVM but will introduce a huge testing dependency. So instead I added a rank checking for it.

2022-01-04 00:24 UTC, ganler commented on torch/onnx/symbolic_opset9.py
> +    assert self_rank is None or sym_help._get_tensor_rank(self) >= len(sym_help._get_tensor_sizes(weight)), "slope must be unidirectionally broadcastable to input tensor"
The bug needs to be reproduced using TVM but will introduce a huge testing dependency. So instead I added a rank checking for it.

2022-01-04 23:34 UTC, ganler commented
timeout tests seem to be flaky. pushed an empty commit to trigger the ci.

2022-01-24 23:16 UTC, ganler commented
Hi @thiagocrepaldi , could you also double-check the added test case? Thank you!

2022-01-31 22:06 UTC, garymm reviewed
I don't think this is actually needed. See my comment here:
https://github.com/pytorch/pytorch/issues/70570#issuecomment-1026258821

2022-01-31 22:06 UTC, garymm commented on test/onnx/test_pytorch_onnx_onnxruntime.py
> +    def test_prelu_scalar(self):
Does this test fail before this change and pass afterwards? If not then I don't think this test is useful.

2022-02-01 00:33 UTC, ganler commented
Hi @garymm , thanks for the review and I have addressed the comments. 

Regarding the benefit of this PR, this change will help:
1. TVM accepts the model in https://github.com/pytorch/pytorch/issues/70570#issue-1092220771
2. ORT reduces the warning of "Expected shape from model of {} does not match actual shape of {1} for output 2"

2022-02-10 01:54 UTC, garymm requested changes
Thanks for the contribution, and sorry for the latency.

2022-02-10 01:54 UTC, garymm commented on torch/onnx/symbolic_opset9.py
> +    slope_rank = sym_help._get_tensor_rank(weight)
Don't mix torch names and ONNX names, it's confusing.

```suggestion
    weight_rank = sym_help._get_tensor_rank(weight)
```

2022-02-10 01:54 UTC, garymm commented on torch/onnx/symbolic_opset9.py
> +            self_rank = sym_help._get_tensor_rank(self)
Don't we know this for sure?
```suggestion
            self_rank = 1
```

2022-02-10 01:54 UTC, garymm commented on torch/onnx/symbolic_opset9.py
> +            weight = sym_help._unsqueeze_helper(g, weight, list(range(1, self_rank - 1)))
```suggestion
            # make weight unidirectional broadcastable
            weight = sym_help._unsqueeze_helper(g, weight, list(range(1, self_rank - 1)))
```

2022-02-10 01:54 UTC, garymm commented on torch/onnx/symbolic_opset9.py
> +            self = sym_help._unsqueeze_helper(g, self, [0])
```suggestion
            # weight is always rank 1. torch allows scalar self, and ONNX is ambiguous
            # about whether this is allowed, but some implementations enforce
            # rank(self) >= rank(weight), which makes sense.
            self = sym_help._unsqueeze_helper(g, self, [0])
```

2022-02-10 01:54 UTC, garymm commented on test/onnx/test_pytorch_onnx_onnxruntime.py
>                        test_with_inputs=[y])
Add a test that uses scalar inputs to trigger the new code path.
Even if the difference between the old behavior and new behavior is just "ORT doesn't print a warning", that's OK. Better to have a test that executes the code path and makes sure it basically works.

2022-02-10 19:32 UTC, garymm requested changes

2022-02-10 19:32 UTC, garymm commented on test/onnx/test_pytorch_onnx_onnxruntime.py
> +                      test_with_inputs=[x])
Remove test_with_inputs. By default `run_test` will test with the inputs in the second argument, so this is redundant.

2022-02-10 19:46 UTC, garymm approved these changes
Will merge once checks pass.

2022-02-11 01:32 UTC, garymm commented
@msaroufim could you please import? (non-MS contribution, can't use merge bot yet)

2022-02-16 22:26 UTC, garymm commented
@pytorchbot merge this

2022-02-16 22:28 UTC, closed without merging