[pkg] detect bad packages while interning
pytorch/pytorch pull request #70955
Opened 2022-01-06 23:51 UTC by PaliC

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2022-01-07 00:04 UTC, PaliC commented
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33466521).

2022-01-07 00:25 UTC, PaliC commented
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33466521).

2022-01-07 00:56 UTC, PaliC commented
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33466521).

2022-01-07 18:20 UTC, suo requested changes

2022-01-07 18:20 UTC, suo commented on torch/package/package_exporter.py
> +        error = BadPackageError(f"{module_obj.__name__} is an improperly formed package "
Can we improve the error message to explain why the package is improperly formed? Most of our users probably don't know anything about the Python import/module system.

2022-01-07 18:20 UTC, suo commented on torch/package/package_exporter.py
> +            for i in module_obj.__name__:
I don't understand what we're testing here, I assume it has something to do with iterableness; can you add a comment explaining

2022-01-07 20:10 UTC, PaliC commented
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33466521).

2022-01-07 22:12 UTC, suo approved these changes
lgtm!

2022-01-07 23:11 UTC, PaliC commented
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33466521).

2022-01-08 00:00 UTC, PaliC commented
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33466521).

2022-01-08 03:21 UTC, PaliC commented
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33466521).

2022-06-21 00:50 UTC, closed without merging