Remove deprecated torch.cholesky
pytorch/pytorch pull request #70979
Opened 2022-01-07 10:50 UTC by IvanYashchuk

The time has come to remove deprecated linear algebra related functions. This PR removes torch.cholesky.

Fixes to torch/xla need to be merged before this PR:

- [ ] https://github.com/pytorch/xla/pull/3274

2022-01-11 10:42 UTC, Lezcano approved these changes

2022-01-11 10:42 UTC, Lezcano commented on test/test_linalg.py
> -     iter_indices, gradcheck, gradgradcheck,
niiiiiceee!

2022-01-11 11:48 UTC, IvanYashchuk commented
@pytorchbot ciflow rerun

2022-03-24 23:28 UTC, Lezcano commented
Note. This PR partially fixes https://github.com/pytorch/pytorch/issues/71084

2022-11-22 02:42 UTC, kit1980 commented
/easycla

2023-02-24 23:43 UTC, kit1980 commented
@IvanYashchuk revive?

2023-04-05 13:30 UTC, malfet approved these changes
Please make sure to add `this PR updates XLA submodule` otherwise merge bot would refuse to merge

2023-07-01 00:22 UTC, kit1980 commented
@IvanYashchuk @lezcano A question.
Why currently the doc recommends updating `torch.cholesky(A, upper=True)` to `torch.linalg.cholesky(A).mH` instead of `torch.linalg.cholesky(A, upper=True)`?

2023-07-01 00:56 UTC, kit1980 commented
> Why currently the doc recommends updating `torch.cholesky(A, upper=True)` to `torch.linalg.cholesky(A).mH` instead of `torch.linalg.cholesky(A, upper=True)`?

In my tests `torch.linalg.cholesky(A, upper=True)` is the same, so I assume it correct to replace with it?

TorchFix PR to do this replacement: https://github.com/pytorch/test-infra/pull/4336

2023-07-01 09:55 UTC, lezcano commented
Intially, we didn't want to have an `upper=True` flag in `linalg.cholesky`, as it's functionally equivalent to `cholesky(A).mT`. When we first did this, we had some pushback from members of the community, and we ended up adding that `upper` flag, but we decided that we were not going to advertise it too much.

That's the historical context of that weird flag :)

2023-07-01 16:09 UTC, kit1980 commented
> but we decided that we were not going to advertise it too much.

I see, I'll use `.mH` then.

2023-07-01 16:11 UTC, kit1980 commented
@lezcano `mH`, not `mT`, right?

2023-07-01 19:25 UTC, lezcano commented
`mH` so that it works also for complex inputs.

2023-07-01 19:26 UTC, lezcano commented
ah, I see, yeah, I meant `mH` in the previous message :)

2026-05-17 21:26 UTC, jansel commented
@claude explain those CI failures, are they related?

2026-05-17 22:07 UTC, jansel requested changes
fix merge conflicts

2026-05-27 12:40 UTC, IvanYashchuk commented
@jansel Could you or your agent please take a look and help merge

2026-05-27 13:56 UTC, jansel approved these changes

2026-05-27 13:56 UTC, jansel commented on .github/ci_commit_pins/xla.txt
> +ddddae93c250527d74200838f17d26b9c7009f0c
Is this intentional?

2026-05-29 01:22 UTC, zou3519 approved these changes

2026-06-04 16:43 UTC, IvanYashchuk commented
@pytorchbot merge

2026-06-05 21:04 UTC, IvanYashchuk commented on .github/ci_commit_pins/xla.txt
> +ddddae93c250527d74200838f17d26b9c7009f0c
It used to be required, but now it seems that there's no XLA CI anymore and everything is green without this pin.

2026-06-09 18:18 UTC, IvanYashchuk commented
Closing in favor of fresh replacement PR #186817 to avoid the old PR automation/check-run state.

2026-06-09 18:18 UTC, closed without merging