[ONNX] Improve scope inference in function extraction
pytorch/pytorch pull request #71618
Opened 2022-01-21 02:18 UTC by BowenBao

Cover more cases of scope inferencing where consecutive nodes don't have valid scope information. Usually these nodes are created in some pass where authors forgot to assign meaningful scope to them.
* One rule of `InferScope` is to check if the current node's outputs' users share the same scope. Recursively run `InferScope` on the user nodes if they are missing scope as well. Since the graph is SSA, the depth is finite.
* Fix one pass that missed scope information for a new node.

2022-01-22 02:00 UTC, garymm requested changes

2022-01-22 02:00 UTC, garymm commented on test/onnx/test_utility_funs.py
> +    def test_local_function_infer_scopes(self):
Could you add a comment here explaining why this tests for scope inference?

2022-01-25 18:59 UTC, garymm approved these changes

2022-01-27 01:37 UTC, BowenBao commented
@pytorchbot merge this

2022-01-27 02:12 UTC, BowenBao commented
reopened #71897 to swap to same repo merge. closing this one.

2022-01-27 02:12 UTC, closed without merging