[ONNX] Export aten::mul(bool, bool) to onnx::and instead of onnx::mul
pytorch/pytorch pull request #72102
Opened 2022-02-01 07:34 UTC by wschin

As title. We don't need to implement onnx::mul for bool because it's already onnx::and. It's also semantically better to keep boolean to use their specific operations (AND, OR, XOR, etc).

2022-02-01 18:13 UTC, BowenBao commented
Thank you for PR, could you validate if this test case works under your change?

```python
>>> a  = torch.tensor([True, False])
>>> b = torch.tensor([1., 2.])
>>> (a * b).dtype
torch.float32
```

2022-02-01 19:01 UTC, wschin commented
> 

I don't think this will work.
```python
    def test_mul_float_bool(self):
        x = torch.tensor([True, False, True, False])
        y = torch.tensor([1.0, 2.0, 3.0, 4.0])
        self.assertONNX(lambda x, y: torch.mul(x, y), (x, y))
```
generates
```
ir_version: 4
producer_name: "pytorch"
producer_version: "1.11.0"
graph {
  node {
    input: "onnx::And_0"
    input: "onnx::And_1"
    output: "2"
    name: "And_0"
    op_type: "And"
  }
  name: "torch-jit-export"
  input {
    name: "onnx::And_0"
    type {
      tensor_type {
        elem_type: 9
        shape {
          dim {
            dim_value: 4
          }
        }
      }
    }
  }
  input {
    name: "onnx::And_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 4
          }
        }
      }
    }
  }
  output {
    name: "2"
    type {
      tensor_type {
        elem_type: 9
        shape {
          dim {
            dim_value: 4
          }
        }
      }
    }
  }
}
opset_import {
  version: 9
}
```

2022-02-01 19:05 UTC, BowenBao commented
@wschin will it work if you convert to `And` only when both self and other are bool type?

If so please add as test case under `test_pytorch_onnx_onnxruntime.py`.

2022-02-01 19:20 UTC, garymm requested changes
Please change the target branch from `master` to `onnx_ms_1`

2022-02-01 19:20 UTC, garymm commented on torch/onnx/symbolic_helper.py
> +_fp_tensor_types = set((torch.float16, torch.float32, torch.float64, torch.bfloat16))
Let's add more structure:
```suggestion
_TypeGroup = collections.namedtuple("TypeGroup", ("tensor_types", "scalar_types"))
_FPTypeGroup = _TypeGroup((torch.float16, torch.float32, torch.float64, torch.bfloat16), ("Float", "Double", "Half", "BFloat16"))
_BoolTypeGroup = _TypeGroup((torch.bool,), ("Bool",))
```

2022-02-01 19:20 UTC, garymm commented on torch/onnx/symbolic_helper.py
> +def _is_specific_type_group(value, tensor_types, scalar_types):
```suggestion
def _is_in_type_group(value: Union[torch.Tensor, torch._C.Value], type_group: _TypeGroup) -> bool:
```

2022-02-01 19:58 UTC, wschin commented on torch/onnx/symbolic_helper.py
> +_fp_tensor_types = set((torch.float16, torch.float32, torch.float64, torch.bfloat16))
Sure.

2022-02-01 19:58 UTC, wschin commented on torch/onnx/symbolic_helper.py
> +def _is_specific_type_group(value, tensor_types, scalar_types):
Looks great. Thanks.

2022-02-04 18:28 UTC, BowenBao commented
@wschin please check CI ONNX test failure.

2022-02-22 18:45 UTC, BowenBao commented
@wschin friendly ping. Please note you no longer need to change base from master to onnx_ms_1.

2022-06-21 03:13 UTC, closed without merging