Don't check BC/FC for ops with valid upgrader
pytorch/pytorch pull request #72193
Opened 2022-02-02 19:05 UTC by tugsbayasgalan

Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #72193

This PR removes the operators that have valid upgraders from the BC table. 

Differential Revision: [D33948943](https://our.internmc.facebook.com/intern/diff/D33948943)

2022-02-02 19:06 UTC, tugsbayasgalan commented
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33948943).

2022-02-02 20:15 UTC, gmagogsfm requested changes

2022-02-02 20:15 UTC, gmagogsfm commented on test/forward_backward_compatibility/check_forward_backward_compatibility.py
> +    for i in possible_overloads:
Nit:
rename `i` to something like `schema_name`. `i` gives the impression that it is a number

2022-02-02 20:15 UTC, gmagogsfm commented on torch/csrc/jit/python/script_init.cpp
> +  m.def("_is_op_current", &isOpSymbolCurrent);
Normally, it is slightly better for C++ function and Python method name to approximately match to reduce cognitive load when reading code.

2022-02-02 20:15 UTC, gmagogsfm commented on test/forward_backward_compatibility/check_forward_backward_compatibility.py
> +    if len(possible_overloads) == 0:
Do we need to verify that these upgraders actually have same schema (not just same op name) as `existing_schema`?

2022-02-02 22:28 UTC, tugsbayasgalan commented on test/forward_backward_compatibility/check_forward_backward_compatibility.py
> +    version_map = torch._C._get_operator_version_map()
It is hard because if we split the key and look up by op name, there will be duplicates because of overloads.

2022-02-02 22:29 UTC, tugsbayasgalan commented on test/forward_backward_compatibility/check_forward_backward_compatibility.py
> +    current_version = torch._C._get_max_operator_version()
Yeah sounds good. This existed before this PR

2022-02-02 22:38 UTC, gmagogsfm commented on test/forward_backward_compatibility/check_forward_backward_compatibility.py
> +    version_map = torch._C._get_operator_version_map()
You can process the map to be [op_name, pair< overload, schema>] or whatever that's convenient for look up.

2022-02-03 18:45 UTC, tugsbayasgalan commented
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33948943).

2022-02-03 23:14 UTC, mruberry commented
Can you elaborate on this PR, @tugsbayasgalan? Like just because an op has an upgrader doesn't mean that future BC-breaking changes can't be made to it, or that users won't experience a BC-breaking change.

2022-02-03 23:16 UTC, mruberry commented on test/forward_backward_compatibility/check_forward_backward_compatibility.py
> +def has_valid_upgraders(schema, version_map):
We don't require upgraders for every BC-breaking change that would trigger this test today. For example, ops in prototype and beta modules have no BC guarantees.

2022-06-21 03:13 UTC, closed without merging