Move torch::deploy tests to their own workflow job
pytorch/pytorch pull request #72637
Opened 2022-02-10 00:17 UTC by PaliC

Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #72637

Differential Revision: [D34563885](https://our.internmc.facebook.com/intern/diff/D34563885)

2022-02-10 01:04 UTC, suo requested changes
So, we need:
1. A specialized build of PyTorch, built with `USE_DEPLOY=1`.
2. A special test workflow that pretty much only calls the Python deploy tests `test/test_deploy.pt` and the C++ ones `build/bin/test_deploy`.

For the first one:
- You need to define a new workflow in `.github/scripts/generate_ci_workflow.py`. A very similar one would be `parallelnative`. You'll need to give a build environment name.
- In `.jenkins/pytorch/build.sh` you need to correctly export `USE_DEPLOY=1` if the name of the build environment matches your workflow's build environment name. Example: https://github.com/pytorch/pytorch/blob/master/.jenkins/pytorch/build.sh#L60-L62

Then for the second one, I think the easiest thing to do is match on build environment name in `.jenkins/pytorch/test.sh` and call the right tests, like: https://github.com/pytorch/pytorch/blob/master/.jenkins/pytorch/test.sh#L534-L536

2022-02-14 20:50 UTC, suo requested changes
You probably need to rerun `generate_ci_workflows.py`? I don't see a generated deploy workflow. Similarly, your change should not be affecting any existing workflows, but I see several changed workflows in the PR.

2022-02-14 20:50 UTC, suo commented on .circleci/docker/build.sh
> +       --build-arg "USE_DEPLOY=${USE_DEPLOY}" \
We should delete this line, it turns on deploy builds for everything. We just want it on for the deploy workflow (which we do below in build.sh anyway)

2022-02-14 20:50 UTC, suo commented on .github/scripts/generate_ci_workflows.py
> +            docker_image_base=f"{DOCKER_REGISTRY}/pytorch/pytorch-linux-xenial-cuda11.3-cudnn8-py3-gcc7",
please address lint

2022-02-14 20:50 UTC, suo commented on .github/scripts/generate_ci_workflows.py
> +    deploy_test: bool = False
I think we don't need this; it should be controlled by the workflow name (e.g. in test.sh).

2022-02-14 20:51 UTC, suo commented
What we should be seeing is a `deploy-linux-xenial-cuda11.3-cudnn8-py3-gcc7-build` and `deploy-linux-xenial-cuda11.3-cudnn8-py3-gcc7-test` workflow, which is not in the list of signals

2022-02-18 02:23 UTC, suo commented on .github/scripts/generate_ci_workflows.py
> +    deploy_test: bool = False
same comment

2022-02-18 02:24 UTC, suo requested changes

2022-02-18 22:32 UTC, suo requested changes

2022-02-18 22:32 UTC, suo commented on .github/scripts/generate_ci_workflows.py
> +    enable_deploy_test: bool = False
you no longer need this, it's not used anywhere.

2022-02-18 22:32 UTC, suo commented on .github/scripts/generate_pytorch_test_matrix.py
> +#!/usr/bin/env python3
This file was removed, but you re-added it. Please remove

2022-02-19 03:43 UTC, suo approved these changes

2022-03-01 22:16 UTC, PaliC commented
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34563885).

2022-06-21 03:51 UTC, closed without merging