[Qunat] Refactor reference module mapping
pytorch/pytorch pull request #72755
Opened 2022-02-11 23:31 UTC by terrychenism

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Summary:
Add is_refernece flag in convert function

Test Plan:
python3 test/test_quantization.py TestQuantizeEagerOps.test_conv_transpose_2d

Reviewers:

Subscribers:

Tasks:

Tags:

2022-02-12 00:08 UTC, terrychenism commented
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34188856).

2022-02-15 17:58 UTC, jerryzh168 commented on torch/ao/quantization/quantize.py
> +        mapping = get_default_static_quant_reference_module_mappings()
I think we should do this in _convert, to keep everything in the same place

2022-02-15 17:58 UTC, jerryzh168 commented on torch/nn/quantized/_reference/modules/linear.py
> +    _IS_REFERENCE = True
is linear not tested right now? should we add a test?

2022-02-15 18:32 UTC, terrychenism commented
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34188856).

2022-03-01 00:10 UTC, terrychenism commented
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34188856).

2022-03-04 22:18 UTC, jerryzh168 commented on torch/ao/quantization/quantize.py
>      r"""Converts submodules in input module to a different module according to `mapping`
maybe add some docs for `is_reference` flag?

2022-03-04 22:19 UTC, jerryzh168 approved these changes
looks good, would be better to have a more detailed summary message as well. e.g. talk about the motivation and impact of the change and how the is_reference flag is implemented

2022-03-04 22:20 UTC, jerryzh168 commented on torch/ao/quantization/quantize.py
> +        mapping = get_default_static_quant_reference_module_mappings()
actually not like this, this should go within the L530 branch I think

2022-03-04 22:21 UTC, jerryzh168 commented on torch/ao/quantization/quantize.py
> +        mapping = get_default_static_quant_reference_module_mappings()
user should be able to overwrite the default mapping with explicit mappings, if user do not provide any mapping, we can provide a default mapping based on `is_reference` flag

2022-03-04 22:22 UTC, jerryzh168 requested changes
need to change the place for `is_reference` check in `_convert` function

2022-03-04 22:45 UTC, terrychenism commented
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34188856).

2022-03-04 22:49 UTC, jerryzh168 commented on torch/ao/quantization/quantize.py
> +        if is_reference:
nit: the following is a little bit better
```
if is_reference:
   ...
else:
   ...
```

2022-03-04 22:49 UTC, jerryzh168 commented on torch/ao/quantization/quantize.py
> +        if is_reference:
or just a single line with
```
mapping = xxx if is_reference else yyy
```

2022-03-04 22:55 UTC, terrychenism commented
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34188856).

2022-03-04 22:58 UTC, jerryzh168 approved these changes

2022-03-07 17:42 UTC, terrychenism commented
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34188856).

2022-03-07 22:00 UTC, terrychenism commented
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34188856).

2022-03-08 00:27 UTC, terrychenism commented
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34188856).

2022-03-08 06:48 UTC, closed without merging