add BFloat16 sparse operators on CPU: copy, coalesce, sparse_mask, ad…
pytorch/pytorch pull request #72846
Opened 2022-02-15 06:56 UTC by jiayisunx

…d_out, addmm

Fixes #ISSUE_NUMBER

2022-02-16 22:15 UTC, zou3519 commented
@cpuhrsch could you please suggest a reviewer for this? Thank you.

2022-02-16 22:44 UTC, cpuhrsch requested changes
Why does additional bfloat support require new tests instead of adding to the dtypes decorator?

2022-02-17 19:11 UTC, cpuhrsch commented on test/test_sparse.py
> +    def test_sparse_add_out_bfloat16_cpu(self, device, dtype, coalesced):
Why is this additional test needed as opposed to extending an existing test for addition?

2022-02-18 16:04 UTC, cpuhrsch approved these changes

2022-02-19 01:33 UTC, closed without merging

2022-02-21 07:39 UTC, IvanYashchuk commented
Tests fail on master due to this PR.
See https://github.com/pytorch/pytorch/runs/5256388151?check_suite_focus=true

2022-02-21 17:27 UTC, malfet commented
Reverting