Update references to master to main in .jenkins and tools
pytorch/pytorch pull request #73297
Opened 2022-02-23 17:13 UTC by musebc

Fixes #71806

2022-03-09 17:29 UTC, suo commented
driveby comment: this seems like the rare case where a global env var is the best solution. If we just set $GIT_DEFAULT_BRANCH at the beginning of everything and use that throughout the codebase (and eventually delete it in favor of direct references to main) it's probably cleaner than routing arguments through all the scripts.

2022-03-14 15:21 UTC, janeyx99 commented on .jenkins/pytorch/short-perf-test-cpu.sh
>      MASTER_COMMIT_ID=$(git log --format="%H" -n 1)
do we want to rename these vars as well?

2022-03-14 15:22 UTC, janeyx99 commented on .jenkins/pytorch/short-perf-test-cpu.sh
> +if [[ "$COMMIT_SOURCE" == master || "$COMMIT_SOURCE" == main ]]; then
```suggestion
if [[ "$COMMIT_SOURCE" == "$UPSTREAM_DEFAULT_BRANCH" ]]; then
```
why not

2022-03-14 15:23 UTC, janeyx99 commented on .jenkins/pytorch/short-perf-test-cpu.sh
> +if [[ "$COMMIT_SOURCE" == master || "$COMMIT_SOURCE" == main ]]; then
same for two other instances below

2022-03-14 15:25 UTC, janeyx99 requested changes
CI failures look legit

2022-03-14 15:26 UTC, musebc commented
> CI failures look legit

Yep. taking a look now.

2022-03-14 15:53 UTC, musebc commented on .jenkins/pytorch/short-perf-test-cpu.sh
> +if [[ "$COMMIT_SOURCE" == master || "$COMMIT_SOURCE" == main ]]; then
Updated.

2022-03-14 15:54 UTC, musebc commented on .jenkins/pytorch/short-perf-test-gpu.sh
> +if [[ "$COMMIT_SOURCE" == master || "$COMMIT_SOURCE" == main ]]; then
Yep. Updated.

2022-03-14 16:36 UTC, malfet approved these changes
LGTM, but please avoid "main" in the comments, use "default branch"/"trunk"

2022-03-14 16:36 UTC, malfet commented on .jenkins/pytorch/short-perf-test-gpu.sh
> +    # Get current main commit hash
s/main/default branch/
```suggestion
    # Get current default branch commit hash
```

2022-03-16 14:25 UTC, musebc commented
@pytorchbot merge this please

2022-03-16 14:45 UTC, closed without merging