Use COO mul kernel for CSR
pytorch/pytorch pull request #74266
Opened 2022-03-15 22:22 UTC by cpuhrsch

Basic fallback implementation. Let's make this faster once used.

2022-03-23 09:06 UTC, pearu requested changes
I have a few nits and a question. Otherwise looks good!

2022-03-23 09:06 UTC, pearu commented on torch/_tensor_docs.py
> +    25
This example uses a private feature (`_nnz`) and may give a different result when executed locally (although, rarely).
```suggestion
    >>> sparse.is_sparse_csr
    True
```
? Or use `dense=torch.tensor([[1, 0, 2], [0, 3, 0]])` as an example input and use `repr(sparse)` as example output?

2022-03-23 15:24 UTC, cpuhrsch commented on aten/src/ATen/native/sparse/SparseTensorMath.cpp
> +  TORCH_CHECK(other.is_sparse_csr(), "mul(sparse_csr, dense) is not supported");
Yes, but it could be called by itself using the out flag in the Python frontend

2022-03-23 15:27 UTC, cpuhrsch commented on test/test_sparse_csr.py
> +                t23 * s
`mul(sparse_csr, sparse_csr)` dispatched to `mul(sparse_coo, sparse_coo)` which isn't implemented for CUDA.

2022-03-23 15:28 UTC, cpuhrsch commented
@pearu I'm going to address the CI failures before addressing comments and requesting another review. Thanks for taking a look!

2022-03-23 17:44 UTC, pearu commented on test/test_sparse_csr.py
> +            self.assertEqual(res, expected)
You are right. My comment applies only to `matmul`, not for `mul`.

2022-03-24 12:42 UTC, pearu approved these changes
LGTM!

2022-03-24 16:05 UTC, malfet approved these changes

2022-03-24 16:12 UTC, cpuhrsch commented
@pytorchbot merge this

2022-03-25 17:09 UTC, cpuhrsch commented
@pytorchbot merge this

2022-03-25 17:10 UTC, closed without merging