Emit ATen ops when symbolics raise + minor fixes
pytorch/pytorch pull request #74759
Opened 2022-03-25 17:28 UTC by thiagocrepaldi

Currently `torch.onnx.export(.., operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK)` only issues ATen ops through explicit requests (e.g. `g.at()`) calls inside each op symbolic function. This is done based on specific conditions such as `operator_export_type==OperatorExportTypes.ONNX_ATEN_FALLBACK)` or `is_caffe2_aten_fallback()`

This PR extends the ATen fallback mechanism for scenarios when the symbolic function raises `RuntimeError` during export. The idea is that partial implementation of existing ONNX ops can fallback to ATen as a last resort. That is valuable because each operator can have many input combinations and not all are always implemented. 

A minor fix was done to make sure the `overload_name` attribute is added to explicit ATen op fallback requests when a symbolic is not registered to a particular op.

ps: The behavior for builds with BUILD_CAFFE2=1 is not changed to ensure BC.

2022-03-25 20:12 UTC, thiagocrepaldi commented
Must be merged after https://github.com/pytorch/pytorch/pull/73954

2022-04-20 22:36 UTC, garymm requested changes, later dismissed
Thanks!

2022-04-20 22:36 UTC, garymm commented on test/onnx/test_operators.py
> +            fake_missing_symbolics = ('clamp')
This is not creating a tuple, I'm pretty sure this is a bug.
You need a trailing comma `("clamp",)`

2022-04-20 22:36 UTC, garymm commented on test/onnx/test_operators.py
> +            # Monkey patch to force missing symbolic for well-known op
can you use unittest.mock instead of doing this manual try / finally stuff?

2022-04-20 22:36 UTC, garymm commented on torch/onnx/utils.py
> +        # TODO: Should RuntimeError be used for unsupported operators?
I think a custom exception type makes sense but I would file an issue in GitHub rather than adding a TODO comment here.

2022-04-21 12:30 UTC, thiagocrepaldi commented on test/onnx/test_pytorch_onnx_onnxruntime.py
> +            return False
```suggestion
        assert all_aten_nodes
```

2022-04-21 12:31 UTC, thiagocrepaldi commented on test/onnx/test_pytorch_onnx_onnxruntime.py
> +        return True
```suggestion
```

2022-04-21 15:31 UTC, garymm requested changes

2022-04-21 15:31 UTC, garymm commented on test/onnx/test_pytorch_onnx_onnxruntime.py
> +                    verbose=False, operator_export_type=torch.onnx.OperatorExportTypes.ONNX):
Add `from torch.onnx import OperatorExportTypes` at the top to make other references to it much shorter.

2022-04-21 15:31 UTC, garymm commented on test/onnx/test_pytorch_onnx_onnxruntime.py
> +    def test_clip_aten_fallback_due_exception(self):
can you move these to `test/jit/test_onnx_export.py`? These tests don't use onnxruntime, so it's confusing to have them in this file.

2022-04-21 22:48 UTC, garymm approved these changes
Thanks!
Please address comments before merging.

2022-04-21 22:48 UTC, garymm commented on test/onnx/test_pytorch_onnx_onnxruntime.py
> +                    verbose=False, operator_export_type=torch.onnx.OperatorExportTypes.ONNX):
can we revert all changes in this file now?

2022-04-21 22:48 UTC, garymm commented on torch/testing/_internal/common_utils.py
> +        self.assertTrue(len(all_aten_nodes) > 0)
```suggestion
        self.assertTrue(all_aten_nodes)
```

2022-04-21 22:48 UTC, garymm commented on torch/testing/_internal/common_utils.py
> +        self.assertEqual(attrs.get("operator"), operator)
can operator be None?
If not, then replace with
```suggestion
        self.assertEqual(attrs["operator"], operator)
```

2022-04-22 01:26 UTC, thiagocrepaldi commented
@garymm @bowangbj It seems that the pipelines that run `test/jit/test_onnx_export.py` does not support `onnx` (either not installed or maybe an ancient version)? 

```
======================================================================
ERROR [0.080s]: test_clip_aten_fallback_due_exception (jit.test_onnx_export.TestONNXExport)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1072, in wrapper
    return func(self)
  File "/var/lib/jenkins/workspace/test/jit/test_onnx_export.py", line 395, in test_clip_aten_fallback_due_exception
    onnx_model = onnx.load_from_string(f.getvalue())
AttributeError: module 'onnx' has no attribute 'load_from_string'

======================================================================
ERROR [0.018s]: test_clip_aten_fallback_explicit_request (jit.test_onnx_export.TestONNXExport)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1072, in wrapper
    return func(self)
  File "/var/lib/jenkins/workspace/test/jit/test_onnx_export.py", line 417, in test_clip_aten_fallback_explicit_request
    onnx_model = onnx.load_from_string(f.getvalue())
AttributeError: module 'onnx' has no attribute 'load_from_string'

----------------------------------------------------------------------
Ran 2644 tests in 122.392s

FAILED (errors=2, skipped=130, expected failures=13)
```

Have you seen this before? It does work on my machine and the test also worked on `test/onnx/test_pytorch_onnx_onnxruntime.py`

2022-04-22 17:35 UTC, garymm approved these changes
Thanks!

2022-04-22 17:35 UTC, garymm commented on test/onnx/test_onnx_export.py
> +# Owner(s): ["module: onnx"]
I'm OK with this for now but I'll want to combine it with this file once it's merged:
https://github.com/pytorch/pytorch/pull/73284/files#diff-630243becc710c122152dc52e75109e86fc92a505fb293584e47ad3e4031fb65

2022-04-22 17:35 UTC, garymm commented on test/onnx/test_operators.py
> -from torch.onnx.symbolic_helper import parse_args, _get_tensor_dim_size, _get_tensor_sizes
please revert changes to this file.

2022-04-22 17:35 UTC, garymm commented on scripts/onnx/test.sh
> +
remove empty line

2022-04-23 18:59 UTC, thiagocrepaldi commented
@pytorchmergebot merge this

2022-04-23 21:22 UTC, msaroufim approved these changes

2022-04-23 21:23 UTC, msaroufim commented
@pytorchbot merge this

2022-04-23 21:24 UTC, closed without merging