Use batched operations for PowerSGD
pytorch/pytorch pull request #75157
Opened 2022-04-03 15:01 UTC by MagiaSN

This implements method proposed in #74907

2022-04-06 05:59 UTC, wayi1 commented
> cc @wayi1 

Thanks for cc'ing me. On travel this week. If it's not urgent, I can take a look next week.

2022-04-11 06:38 UTC, wayi1 commented on torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py
>      Decide between Gram-Schmidt or QR factorization to orthogonalize the matrix.
s/matrix/a batch of matrices.

2022-04-11 06:39 UTC, wayi1 commented on torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py
>      Decide between Gram-Schmidt or QR factorization to orthogonalize the matrix.
Also better to rename "matrix" as "matrices" in L13.

2022-04-11 06:57 UTC, wayi1 commented on torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py
> +    shape_to_tensors: Dict[torch.Size, List[torch.Tensor]] = {}
Optional: you can just use `shape_to_tensors = defaultdict(list)` to save L439-L440.

2022-04-11 07:02 UTC, wayi1 commented on torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py
> +    batch_size = matrix.shape[0]
Optional: what about replacing `batch_size` with `num_matrices`?

2022-04-11 07:11 UTC, wayi1 commented on torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py
> +            batched_tensors_to_compress.append(torch.stack(tensors))
I guess will incur extra memory footprint and increase the peak memory usage. Shall we make such batching optimization configurable?

My concern is that for some memory-intensive use cases, enabling such optimization may cause OOM. Wdyt?

2022-04-11 07:12 UTC, wayi1 requested changes
Thanks for this great optimization! Most are minor nitpicks. The only concern is the extra memory usage due to stacking tensors of the same shape.

2022-04-11 13:50 UTC, MagiaSN commented
> Thanks for this great optimization! Most are minor nitpicks. The only concern is the extra memory usage due to stacking tensors of the same shape.

Thanks for your advice, The memory issue is a concern indeed, I think the best solution is putting tensors of the same shape together in the bucketing stage, so we can replace `stack` with `view`, which introduces no extra memory usage, but this would introduce far more modification than expected, so I add a switch to this optimization and it's turned off by default.

BTW, I see CI falling but didn't figure out how it is related to my update. Anyone have a look?

2022-04-11 17:04 UTC, wayi1 commented on torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py
> +        batch_tensors_with_same_shape (bool): A boolean value that when set to ``True``, compress and decompress tensors with
This needs to be placed inside `PowerSGDState`. A valid hook cannot accept a third arg.

2022-04-11 17:05 UTC, wayi1 commented on torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py
> +        batch_tensors_with_same_shape (bool): A boolean value that when set to ``True``, compress and decompress tensors with
Nit: Replace "A boolean value that when set to ``True``," by "Whether to".

2022-04-11 17:06 UTC, wayi1 commented on torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py
> +            and communication. Set to ``True`` if the compression / decompression computation is a bottleneck.
Please add "and increase the memory footprint due to stacking the tensors of the same shape" as another potential downside.

2022-04-11 17:08 UTC, wayi1 commented on torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py
> +            same shape in a batched operation to achieve higher parallelism. Note that you should also increase the bucket size
Nit: Use "bucket size (i.e., ``bucket_cap_mb`` arg in DDP ctor)" to be more clear.

2022-04-12 17:53 UTC, wayi1 approved these changes
Thanks for the optimization!

cc: @rohan-varma, @pritamdamania  Do you want to enable `batch_tensors_with_same_shape` arg for some internal use cases to see if there can be any speedup? Some NLP use cases may benefit from this optimization.

2022-04-13 22:29 UTC, rohan-varma approved these changes
Thanks for this change! And thanks @wayi1 for reviewing the changes. 

We will give this a try internally soon, and report back with our findings. It may take some effort to identify a workload with neighbouring tensors of the same shape, but if we find something like that hopefully the perf improvement can be sizeable.

2022-04-13 22:44 UTC, rohan-varma requested changes
Looks like lint is failing, can we fix that: https://github.com/pytorch/pytorch/runs/5990406716?check_suite_focus=true? 

Also, would be great to add unittests - we can probably reuse the existing powerSGD tests in https://github.com/pytorch/pytorch/blob/master/test/distributed/test_c10d_nccl.py, and then run all of them with this new option to ensure correctness and parity (correctness wise) with the case when this option is not enabled.

2022-04-14 14:05 UTC, MagiaSN commented
The lint error seems to be introduced by rebase, it is not included in the change, but I could fix it together. Also added unittest :)

For the performance test, I suggest using a deep model (with more than 24 layers) and increase `bucket_cap_mb` to the model size, the gradients of each layer are same-shaped, so they can naturally form a batch.

2022-04-18 04:26 UTC, rohan-varma approved these changes
lgtm

2022-04-18 04:33 UTC, rohan-varma commented
@pytorchbot merge this

2022-04-18 04:34 UTC, closed without merging

2022-04-18 13:05 UTC, albanD commented
@pytorchbot revert this please 

See https://github.com/pytorch/pytorch/runs/6058704725?check_suite_focus=true for example failure.

2022-04-18 14:20 UTC, MagiaSN commented
Sorry, it seems this branch is behind `master` and some tests are missing. Could someone give suggestions on how to fix this?

```
======================================================================
FAIL [1.175s]: test_correct_module_names (__main__.TestPublicBindings)
An API is considered public, if  its  `__module__` starts with `torch.`
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_public_bindings.py", line 350, in test_correct_module_names
    self.assertTrue(not failure_list, msg)
AssertionError: False is not true : Following new APIs ( displayed in the form (module, element, element module) ) were added that do not meet our guidelines for public API Please review  https://docs.google.com/document/d/10yx2-4gs0gTMOimVS403MnoAWkqitS8TUHX73PN8EjE/edit?pli=1# for more information:
('torch.distributed.algorithms.ddp_comm_hooks.powerSGD_hook', 'Dict', 'typing')
('torch.distributed.algorithms.ddp_comm_hooks.powerSGD_hook', 'defaultdict', 'collections')
```

2022-04-18 14:34 UTC, albanD commented
You can rebase on top of master to make sure the test is there.
For that particular error, you can see the doc linked or the wiki: https://github.com/pytorch/pytorch/wiki/Public-API-definition-and-documentation

2022-04-19 08:02 UTC, MagiaSN commented
Thanks for the guidance, but this pull request is already closed and I can't add more commits. Tell me if you need a fresh new pull request, or there is something else I could help :)

2022-04-19 13:18 UTC, albanD commented
Opening a fresh new PR is the simplest way to go yes.