[quant] remove reduce_range in customized qrange
pytorch/pytorch pull request #75357
Opened 2022-04-06 20:37 UTC by terrychenism

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Summary:
reduce_range in customized qrange is not needed, since user should set the customized qrange correctly

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

2022-04-06 23:59 UTC, terrychenism commented
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35452674).

2022-04-07 01:47 UTC, terrychenism commented
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35452674).

2022-04-07 17:25 UTC, terrychenism commented
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35452674).

2022-04-07 19:38 UTC, terrychenism commented
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35452674).

2022-04-08 15:22 UTC, terrychenism commented
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35452674).

2022-04-08 17:12 UTC, vkuzo requested changes
Are we sure this is correct?  This PR seems to leave the reduce_range argument in the API, but changes it to be unused, which would make any customer who is actually trying to use this argument get incorrect results.  

What is the goal of this PR?

2022-04-08 17:18 UTC, terrychenism commented
> correct



> Are we sure this is correct? This PR seems to leave the reduce_range argument in the API, but changes it to be unused, which would make any customer who is actually trying to use this argument get incorrect results.
> 
> What is the goal of this PR?

we delete reduce_range argument which in the custimized qconfig. if user use customized qmin/qmax, it means they can specify the numbers for qmin/qmax and don't need to use 'reduce_range'.  @jerryzh168

2022-04-08 17:24 UTC, jerryzh168 commented
yeah, and we should remove reduce_range in our calls as well, when we specify quant_min/quant_max, maybe we can add an assert saying quant_min/quant_max and reduce_range should not be specified at the same time

2022-04-08 17:25 UTC, jerryzh168 commented on test/quantization/core/test_workflow_module.py
> +        obs = FusedMovingAvgObsFakeQuantize(quant_min=0, quant_max=127, dtype=torch.quint8, reduce_range=True)
we should remove reduce_range here

2022-04-08 17:25 UTC, jerryzh168 commented on torch/ao/quantization/fake_quantize.py
> +default_fake_quant = FakeQuantize.with_args(observer=MovingAverageMinMaxObserver, quant_min=0, quant_max=127,
also here

2022-04-08 17:25 UTC, jerryzh168 commented
I think we should add an assert to catch everything and make this a bc-breaking change

2022-04-08 17:28 UTC, terrychenism commented
> yeah, and we should remove reduce_range in our calls as well, when we specify quant_min/quant_max, maybe we can add an assert saying quant_min/quant_max and reduce_range should not be specified at the same time

Yes makes sense

2022-04-08 18:11 UTC, terrychenism commented
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35452674).

2022-04-11 18:35 UTC, terrychenism commented
> I think a change like this needs a significantly more comprehensive PR summary. It should detail:
> 
> 1. how things work now - including all the edge cases
> 2. what specifically this PR is changing for the user, which users are affected and what is the change for them
> 3. if there are any BC breaking changes, what the users need to change should be laid out

summary updated.

2022-04-11 18:35 UTC, vkuzo commented
Hmm, I'm still not sure about the goal.  Before this PR, we had qmin, qmax, reduce_range, which all worked correctly with each other.  It was slightly confusing if reduce_range interacted with qmin and qmax, but it still worked logically.

Now, we still have qmin, qmax and reduce_range, but we've made some of the behaviors which were working correctly before throw an error.  Not sure why?  Could we throw a warning instead of breaking things?
 
I feel like it would make more sense to remove reduce_range from the API, but that's something which will break BC and will need a warning with a specific release version before we do it.

2022-04-11 18:44 UTC, jerryzh168 commented
> Hmm, I'm still not sure about the goal. Before this PR, we had qmin, qmax, reduce_range, which all worked correctly with each other. It was slightly confusing if reduce_range interacted with qmin and qmax, but it still worked logically.

I think the goal is that we'd like to move away from using both quant_min/quant_max and reduce_range because it does not make a lot of sense, i.e. when user is providing custom quant_min/quant_max, why not just provide the final quant_min/quant_max that is going to be used, but relying on reduce_range to do the divide by 2 calculation?
Yeah and agree that we should just remove reduce_range.

regarding how to get to the final state, if we can't break bc now then I feel it would make sense to put up a warning for now and still support this behavior

2022-04-11 19:24 UTC, terrychenism commented
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35452674).

2022-06-23 07:01 UTC, closed without merging