TEST - Add test for Buck workflow.
pytorch/pytorch pull request #75360
Opened 2022-04-06 21:23 UTC by kit1980

2022-04-13 22:31 UTC, linbinyu requested changes

2022-04-13 22:31 UTC, linbinyu commented on .github/workflows/buck_build_test.yml
> +          buck build third_party:fmt
use this command to build all targets in this folder (we will add more) 
buck build --keep-going //third_party:

2022-04-13 23:00 UTC, linbinyu approved these changes

2022-04-13 23:39 UTC, kit1980 commented
@pytorchbot merge this

2022-04-13 23:48 UTC, seemethere approved these changes

2022-04-13 23:49 UTC, seemethere commented
@pytorchbot merge this

2022-04-13 23:50 UTC, closed without merging

2022-04-14 18:00 UTC, kit1980 commented
@pytorchbot revert this