[wip] Fix cusparse SPMM broadcasting issue in cuda 11.6 update 1
pytorch/pytorch pull request #75784
Opened 2022-04-14 05:44 UTC by xwang233

pending internal tests, do not merge yet
---

Starting cuda 11.6 update 1, cusparse CSR SPMM may silently give wrong output when the input sparse CSR matrix A is broadcasted, by setting both strides to 0 in `cusparseCsrSetStridedBatch` call.

While the internal fix is still ongoing, it's necessary to have a workaround in pytorch repo to fix this issue. The issue is "fixed" in pytorch by doing batched CSR SPMM on each matrix separately in a `for` loop.

See also https://github.com/pytorch/pytorch/pull/68711

2022-04-14 11:46 UTC, IvanYashchuk requested changes
I'm trying to understand what's the exact problem introduced in CUDA 11.6 Update 1.

Is that right that the problem occurs only for the case when A is a single matrix and B is batched, i.e. the first batch mode from the documentation:
![image](https://user-images.githubusercontent.com/19621411/163383131-7b16e167-85f5-4675-80a1-ad1064c95300.png)

Also, I'd like to note that the other two batch modes are known not to work despite the documentation, and it's only mentioned in a comment in the code example from NVIDIA:
https://github.com/NVIDIA/CUDALibrarySamples/blob/1c825f412455a52f718aa9425e3b5574d17efff5/cuSPARSE/spmm_csr_batched/spmm_csr_batched_example.c#L160
It could be fixed in recent versions but didn't try.

Does the broadcasting of matrix A work in CUDA Toolkit 11.6 Update 2?

If it's known to be broken only for CUDA Toolkit 11.6 Update 1, instead of workarounds that leads to less comprehensive code, I'd suggest simply checking for CUDA version and raising an error.

2022-04-14 11:57 UTC, IvanYashchuk commented
This problem is not in the "Known issues" part of the release notes, is it?

2022-04-14 13:17 UTC, IvanYashchuk commented
I compiled PyTorch with CUDA 11.6 Update 1 and I see failures for complex numbers but everything else passes:
```
test/test_sparse_csr.py::TestSparseCSRCUDA::test_baddbmm_cuda_complex128 FAILED                                                                                                                                                                                                  [ 56%]
test/test_sparse_csr.py::TestSparseCSRCUDA::test_baddbmm_cuda_complex64 FAILED                                                                                                                                                                                                   [ 62%]
test/test_sparse_csr.py::TestSparseCSRCUDA::test_baddbmm_cuda_float32 PASSED                                                                                                                                                                                                     [ 68%]
test/test_sparse_csr.py::TestSparseCSRCUDA::test_baddbmm_cuda_float64 PASSED                                                                                                                                                                                                     [ 75%]
test/test_sparse_csr.py::TestSparseCSRCUDA::test_bmm_cuda_complex128 PASSED                                                                                                                                                                                                      [ 81%]
test/test_sparse_csr.py::TestSparseCSRCUDA::test_bmm_cuda_complex64 PASSED                                                                                                                                                                                                       [ 87%]
test/test_sparse_csr.py::TestSparseCSRCUDA::test_bmm_cuda_float32 PASSED                                                                                                                                                                                                         [ 93%]
test/test_sparse_csr.py::TestSparseCSRCUDA::test_bmm_cuda_float64 PASSED
```

2022-04-14 22:48 UTC, xwang233 commented
The functionality failure occurs when sparse matrix A is broadcasted. Yes, you're right. We've only seen failures on complex inputs.

It's not in the "known issue" section.

Unfortunately, this issue started from cuda 11.6 update 1 and will still be existed in cuda 11.7 release. The fix will be targeted in the next minor release after 11.7 (cuda 11.7 update 1, if any).

I'm ok to fix this either way in pytorch: error out in those affected versions, or add a loop workaround. Also wanted to hear what @ngimel thinks, and maybe @cpuhrsch @ptrblck .

2022-04-20 00:03 UTC, xwang233 commented
ping @ngimel and @IvanYashchuk for the review

2022-04-21 09:14 UTC, IvanYashchuk requested changes
Thank you for identifying the problem and proposing the workaround! I think it's better to have it only for complex inputs.

2022-04-21 09:14 UTC, IvanYashchuk commented on aten/src/ATen/native/sparse/cuda/SparseBlasImpl.cpp
> +  if (mat1.dim() == 2) {
As we found out the bug is present only for complex inputs. Let's use the workaround only for complex inputs then. I expect a for-loop solution to be slower and no need to slow down the code path for reals if it works fine. A comment above should include info that the bug is present only for complex inputs.
```suggestion
  if (mat1.dim() == 2 || mat1.is_floating_point()) {
```

2022-04-21 22:32 UTC, xwang233 commented on aten/src/ATen/native/sparse/cuda/SparseBlasImpl.cpp
> +      set_sizes_contiguous(mat1_copy.sizes().slice(sparse_dim - 2));
Thanks! Looking forward to the update on CSR descriptor!

2022-04-21 22:34 UTC, xwang233 commented on aten/src/ATen/native/sparse/cuda/SparseBlasImpl.cpp
> +    int batch_count = at::native::cuda_int_cast(at::native::batchCount(mat1), "batch_count");
I was following the existing code in `CuSparseSpMatCsrDescriptor` constructor to make the code base look consistent.

2022-07-24 18:38 UTC, closed without merging