[quant][core][gpu][cudnn] Added support for nhwc tensors in quantized cudnn add_relu op
pytorch/pytorch pull request #75806
Opened 2022-04-14 17:49 UTC by dzdang

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Summary:
When using the the quantized cudnn add operator, if the input tensors are 4D,
cudnn requires NHWC format in v. 8.4.0 (older versions may have relaxed this constraint).
Previously, all tensors defaulted to NCHW format.

Test plan:
```
python test/test_quantization.py -k test_qadd_relu_cudnn
```

2022-04-14 17:50 UTC, dzdang commented
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35651368).

2022-04-15 19:59 UTC, jerryzh168 commented on aten/src/ATen/native/quantized/cudnn/BinaryOps.cpp
> +                                        : at::empty(qa.sizes(), at::device(at::kCUDA).dtype(at::kFloat));
nit: there are some duplicated code here, can we have a variable to represent memoryformat and only apply the branch for the variable? like:
```
memory_format = a if xxx else b
add_output = at:empty(qa.sizes(), ..., memory_format)
```

2022-04-15 19:59 UTC, jerryzh168 commented on aten/src/ATen/native/quantized/cudnn/BinaryOps.cpp
> +  at::Tensor quantized_output = qa.dim() == 4 ? at::_empty_affine_quantized(qa.sizes(),
same here

2022-04-15 19:59 UTC, jerryzh168 commented on aten/src/ATen/native/quantized/cudnn/BinaryOps.cpp
> +  at::Tensor requantize_multiplier_tensor = qa.dim() == 4 ? at::empty(quantized_output.sizes(), at::device(at::kCUDA).dtype(at::kFloat), at::MemoryFormat::ChannelsLast)
same for all the code in this change

2022-04-15 20:00 UTC, jerryzh168 requested changes
please remove duplicated code

2022-04-18 15:09 UTC, dzdang commented
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35651368).

2022-04-18 15:29 UTC, dzdang commented
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35651368).

2022-04-20 02:12 UTC, jerryzh168 approved these changes

2022-04-20 13:48 UTC, closed without merging