Add asin, acos, tan, atan operators
pytorch/pytorch pull request #7600
Opened 2018-05-15 22:53 UTC by highker

2018-05-16 00:09 UTC, salexspb requested changes

2018-05-16 00:09 UTC, salexspb commented on caffe2/python/gradient_check_test.py
> +class TestAcos(test_util.TestCase):
don't add new tests here, use folder caffe2/python/operator_test, create new files for your operators (or group of operators). Then use helpers such as assertReferenceChecks and assertGradientChecks. Fbgs those for more examples

2018-05-16 00:09 UTC, salexspb commented on caffe2/python/hypothesis_test.py
> +    @given(input_tensor=hu.arrays(
ditto, don't add stuff to this file, create new files

2018-05-16 07:04 UTC, highker commented
Comments addressed. Thanks @salexspb

2018-05-16 17:05 UTC, salexspb requested changes

2018-05-16 17:05 UTC, salexspb commented on caffe2/python/operator_test/asin_op_test.py
> +from __future__ import absolute_import
looks like asin and acos can go together and reuse the same test with except passing different lambda for reference as well as different operator name, what do you think?

2018-05-16 17:05 UTC, salexspb commented on caffe2/python/operator_test/tan_op_test.py
> +from __future__ import absolute_import
and other same tests as well :)

2018-05-16 17:05 UTC, salexspb commented on caffe2/operators/asin_op.cc
> +    return vector<OperatorDef>{CreateOperatorDef(
how about just fusing this manually? this implementation on Caffe2 graph seems to be  inefficient. And we are not there for full compilers support yet.

2018-05-16 17:05 UTC, salexspb commented on caffe2/operators/atan_op.cc
> +    return vector<OperatorDef>{CreateOperatorDef(
ditto

2018-05-16 17:05 UTC, salexspb commented on caffe2/operators/acos_op.cc
> +    return vector<OperatorDef>{CreateOperatorDef(
ditto

2018-05-17 01:02 UTC, salexspb approved these changes
should be good to go, thanks!

2018-05-17 01:09 UTC, merged