Move `ATen/core/DimVector.h` to `c10/util/DimVector.h`.
pytorch/pytorch pull request #77045
Opened 2022-05-08 08:20 UTC by ysiraichi

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

This PR moves `ATen/core/DimVector.h`, as suggested in:
https://github.com/pytorch/pytorch/pull/76812#discussion_r866875924

The changes can be summarized as:

- Changing includes from `ATen/core/DimVector.h` to `c10/util/DimVector.h`
- Re-declaring both the type and constant size in `at` namespace
- Making `c10::contiguous_strides` return a `DimVector`

2022-05-08 12:50 UTC, ezyang commented
lint

2022-05-09 00:10 UTC, peterbell10 requested changes

2022-05-10 09:16 UTC, ysiraichi commented on aten/src/ATen/ExpandUtils.h
> +#include <ATen/DimVector.h>
Agreed. Also, that would reduce the number of modified files.

2022-05-10 13:23 UTC, peterbell10 approved these changes

2022-05-10 19:38 UTC, ezyang commented
@pytorchbot merge this

2022-05-10 23:02 UTC, Lezcano commented on c10/util/strides.h
>      strides.assign(dims, 0);
I'd like to take this failed landing to small improvement to this code:
```suggestion
  DimVector strides(dims);

  if (dims > 0) {
```

2022-05-11 01:28 UTC, ezyang approved these changes

2022-05-11 01:29 UTC, ezyang commented
@pytorchbot merge this

2022-05-11 01:31 UTC, closed without merging