[DataPipe] Update `mux` data pipe (#76384)
pytorch/pytorch pull request #77145
Opened 2022-05-10 05:32 UTC by ninginthecloud

Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/76384

OSS issue discussion: https://github.com/pytorch/data/issues/346
This diff updates `mux` and `mux_longest` data pipe.
`mux`: Yields one element at a time from each of the input Iterable DataPipes (functional name: ``mux``). As in, one element from the 1st input DataPipe, then one element from the 2nd DataPipe in the next iteration, and so on. It ends when the shortest input DataPipe is exhausted.

`mux` example:

```
>>> from torchdata.datapipes.iter import IterableWrapper
>>> dp1, dp2, dp3 = IterableWrapper(range(3)), IterableWrapper(range(10, 15)), IterableWrapper(range(20, 25))
>>> list(dp1.mux(dp2, dp3))
[0, 10, 20, 1, 11, 21, 2, 12, 22]
```

Test Plan:
buck test mode/opt //caffe2/test:datapipe

https://www.internalfb.com/intern/testinfra/testrun/4785074706282345

Differential Revision: D36017945

2022-05-10 20:40 UTC, NivekT approved these changes
LGTM! Just one small comment about buffer, please see my comment in the internal diff.

2022-05-16 18:02 UTC, NivekT requested changes
FYI, there is current one CI test failing:

```
Traceback (most recent call last):
  File "test_datapipe.py", line 2247, in test_simple_sharding
    self.assertEqual([1, 20, 40, 70], items)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 2258, in assertEqual
    msg=msg,
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_comparison.py", line 1049, in assert_equal
    raise error_meta.to_error() from None
AssertionError: The length of the sequences mismatch: 4 != 2
```

2022-05-17 19:20 UTC, ejguan approved these changes

2022-05-17 20:21 UTC, NivekT approved these changes
CIs look good so far. We will wait a little bit til it is done to confirm, but LGTM!

Thanks for submitting the PR!

2022-05-18 16:23 UTC, closed without merging