Switch to use nested tensor by-default in TransformerEncoder
pytorch/pytorch pull request #77217
Opened 2022-05-11 01:16 UTC by zrphercule

Summary: Switch to use nested tensor as by default setting in TransformerEncoderLayer.

Test Plan:
CI

Torchtext
buck test mode/opt pytorch/text/test:integration_tests_test_models -- test_xlmr_base_model

Reviewed By: frank-wei

Differential Revision: D36153335

2022-05-11 17:08 UTC, cpuhrsch requested changes
I think we need to be a lot more selective for this optimization, since the padding ratio needs to be relatively high for it to be worth it. Also NestedTensor doesn't autograd for now.

2022-05-19 18:16 UTC, cpuhrsch approved these changes

2022-05-19 18:21 UTC, cpuhrsch commented
cc @jbschlosser @albanD @jisaacso @gchanan

2022-05-19 21:57 UTC, closed without merging

2022-05-19 22:59 UTC, albanD commented
@pytorchbot revert this please as it broke many tests: https://github.com/pytorch/pytorch/runs/6515962633?check_suite_focus=true

2022-05-19 23:01 UTC, albanD commented
@zrphercule also the PR signal is mostly red. So we should avoid merging PRs with broken CI.