[GHF] Skip internal checks for bot comments
pytorch/pytorch pull request #77465
Opened 2022-05-13 23:01 UTC by malfet

As @facebook-github-bot is special

Fixes #ISSUE_NUMBER

2022-05-13 23:24 UTC, bigfootjon requested changes
AFAICT, this doesn't do what we need to fix cases like https://github.com/pytorch/pytorch/pull/77109

FB bot needs an opt-out for these lines (on the revert side)

https://github.com/pytorch/pytorch/blob/b08e9051ab3d2e69f3757dca7f5246e6adea7c56/.github/scripts/trymerge.py#L843-L844

2022-05-13 23:30 UTC, malfet commented
> AFAICT, this doesn't do what we need to fix cases like #77109
> 
> FB bot needs an opt-out for these lines (on the revert side)

Good point, updated PR

2022-05-14 00:07 UTC, osalpekar approved these changes

2022-05-14 00:19 UTC, malfet commented
@pytorchbot merge this please

2022-05-14 00:22 UTC, closed without merging