Added note about Dev Infra Office Hours in CONTRIBUTING.md (#76667)
pytorch/pytorch pull request #77883
Opened 2022-05-19 20:02 UTC by swang392

Fixes #76667

2022-05-19 21:02 UTC, janeyx99 commented on CONTRIBUTING.md
> +
Instead of copying and pasting the whole contents of the wiki, add a link to the wiki itself here and summarize the contents into a single sentence.

2022-05-19 21:02 UTC, janeyx99 requested changes
Don't include the third_party changes! Or a.out haha 

The lintrunner issues are not related to your changes.

2022-05-19 22:33 UTC, janeyx99 commented
https://github.com/pytorch/pytorch/runs/6515302527?check_suite_focus=true this is a legitimate error

2022-05-20 14:57 UTC, janeyx99 approved these changes
Looks good to me.

@suo any ideas why the lintrunner mypy is failing on this PR on untouched files but not on trunk?

2022-05-20 15:32 UTC, suo commented
Rebase?

2022-05-20 17:09 UTC, zengk95 approved these changes

2022-05-20 17:09 UTC, zengk95 commented on CONTRIBUTING.md
> +[Dev Infra Office Hours](https://github.com/pytorch/pytorch/wiki/Dev-Infra-Office-Hours) are hosted every Friday to answer any further questions regarding developer experience, green HUD, and CI.
```suggestion
[Dev Infra Office Hours](https://github.com/pytorch/pytorch/wiki/Dev-Infra-Office-Hours) are hosted every Friday to answer any questions regarding developer experience, Green HUD, and CI.
```

2022-05-20 18:30 UTC, swang392 commented
@pytorchbot rebase

2022-05-20 19:43 UTC, swang392 commented
@pytorchbot merge -g

2022-05-20 19:44 UTC, closed without merging