Add sharding tests to multigpu-test.sh and fix custom operator decorator
pytorch/pytorch pull request #77987
Opened 2022-05-20 18:05 UTC by pritamdamania87

1. Enabled multigpu tests.
2. Fixed failing multigpu tests.
3. Fixed custom operator decorator to be first preference in operator dispatch.

2022-05-20 18:41 UTC, fduwjj approved these changes

2022-05-20 18:50 UTC, wanchaol approved these changes

2022-05-20 19:16 UTC, janeyx99 commented on .jenkins/pytorch/multigpu-test.sh
> +time python test/run_test.py --verbose -i distributed/_shard/sharding_plan/test_sharding_plan
```suggestion
```
repeated

2022-05-20 19:16 UTC, janeyx99 commented on .jenkins/pytorch/multigpu-test.sh
> +time python test/run_test.py --verbose -i distributed/_shard/sharding_spec/test_sharding_spec
```suggestion
```
also repeated

2022-05-20 19:18 UTC, janeyx99 requested changes
I still see some duplication

2022-05-20 19:22 UTC, pritamdamania87 commented
@janeyx99 Fixed them in the latest update

2022-05-20 22:01 UTC, janeyx99 approved these changes
Looks good code wise! 

Please wait for the multigpu tests to pass before landing :D

2022-05-20 22:24 UTC, pritamdamania87 commented
@pytorchbot rebase this please

2022-05-21 02:41 UTC, pritamdamania87 commented
@pytorchbot merge this please

2022-05-21 02:44 UTC, pritamdamania87 commented
@janeyx99 Lint seems to be failing due to an unrelated reason:

```
>>> Lint for .github/scripts/trymerge.py:

  Error (MYPY) [comparison-overlap]
    Non-overlapping equality check (left operand type: "Tuple[str, str]",
[2022-05-20T22:31:02Z DEBUG lintrunner::persistent_data] Writing run info to /home/runner/.local/share/lintrunner/a37df4630fe1f5acff882ee64ccae4fb5dc8d95c582db33d3b69846b93567c2c/runs/2022-05-20T22:29:05.011Z_0483e62621e5043a5d98eefbd9eb26338128bcae37b14d65aadd9b075982a9ab
    right operand type: "Literal['SUCCESS']")

        907  |                for check in checks:
        908  |                    if checks[check] is None:
        909  |                        pending_checks.append(check)
    >>> 910  |                    elif checks[check] != 'SUCCESS':
        911  |                        failed_checks.append(check)
        912  |                if len(failed_checks) > 0:
        913  |                    raise RuntimeError(f"Failed to merge due to failing checks, {','.join(failed_checks)}")
```

Is it ok to merge this using "@pytorchbot merge -f"?

2022-05-21 02:51 UTC, pritamdamania87 commented
@pytorchbot rebase this please

2022-05-21 05:51 UTC, pritamdamania87 commented
@pytorchbot rebase this please

2022-05-21 05:52 UTC, pritamdamania87 commented
@pytorchbot merge this please

2022-05-21 22:30 UTC, pritamdamania87 commented
@pytorchbot merge this please

2022-05-21 22:34 UTC, closed without merging

2022-05-23 15:33 UTC, janeyx99 commented
@pritamdamania87 looks like a rebase fixed the lint issue + you've landed successfully, let me know if there's more I should look into.