Legendre polynomial
pytorch/pytorch pull request #78304
Opened 2022-05-25 21:23 UTC by 0x00b1

2022-06-02 04:55 UTC, mruberry commented on torch/special/__init__.py
> +    {input}
n is also an arg

2022-06-02 04:55 UTC, mruberry commented on torch/special/__init__.py
> +Args:
n is also an arg

2022-06-02 04:56 UTC, mruberry requested changes
Looks good overall but it's picked up a peachpy update I don't think we want?

There are also some small doc issues and this should update the .rst file to render the docs, too

2022-06-02 14:51 UTC, 0x00b1 commented
@mruberry Fixed the python-pypeach issue. :)

2022-06-03 18:52 UTC, mruberry approved these changes
Cool! Test failures are unrelated. Looking forward to the .rst update!

2022-06-03 22:37 UTC, 0x00b1 commented
@pytorchbot merge

2022-06-03 22:38 UTC, closed without merging