Update the governance page
pytorch/pytorch pull request #78850
Opened 2022-06-03 21:40 UTC by svekars

2022-06-03 23:16 UTC, ezyang commented
Deferring to @orionr

2022-06-06 20:53 UTC, orionr approved these changes
Let's remove the TBA links but otherwise looks good!

2022-06-06 20:53 UTC, orionr commented on docs/source/community/governance.rst
> +* We have a `nomination form <TBA>`__, where anyone in the community can
Should we change this to `We will have a nomination form, where...` and no link for now? @b0noI we are still blocked on the form, correct? Thanks.

2022-06-06 20:53 UTC, orionr commented on docs/source/community/governance.rst
> +  can `nominate a person to be removed <TBA>`__ from a Module maintainer
Same, but just skip the link for now?

2022-06-09 15:42 UTC, b0noI approved these changes

2022-06-09 16:05 UTC, orionr commented on docs/source/community/governance.rst
> +* We have a `nomination form <TBA>`__, where anyone in the community can
@svekars can you update to the above suggestion please and then we can land this? Thanks!

2022-06-09 16:06 UTC, orionr requested changes
Let's be explicit for those changes needed.

2022-06-09 21:41 UTC, orionr approved these changes
LGTM! Thanks.

2022-06-13 22:14 UTC, svekars commented
@pytorchbot rebase

2022-06-14 15:38 UTC, svekars commented
@pytorchbot merge

2022-06-14 15:39 UTC, closed without merging