[ao][sparsity] Base class for Data Sparsifiers
pytorch/pytorch pull request #79141
Opened 2022-06-08 18:20 UTC by macandro96

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Base Data Sparsifier class for all Data sparsifiers.
The abstract class accepts raw torch tensors / embedding / embedding bags (refer to SUPPORTED_TYPES above)
to prepare for sparsification.
In this case, mask (and parametrizations) is owned by the class and not by the user.
Specifically, the container object inside the class maintains the mask and parametrizations of the input data

Abstract methods that need to be implemented:
- update_mask: Function to compute a new mask for all keys in the
    `data_groups`.
     Should contain at least 2 arguments - name, data.

Test Plan:
```python test/test_ao_sparsity.py TestBaseDataSparsifier```

2022-06-08 18:28 UTC, z-a-f requested changes
It seems to me there are >1 different things being contributed here:

1. The parametrizations container -- let's split it into a separate diff + add tests if that would work from the point of view of access
1. The support for embeddings and tensors -- that seems like two different functionalities, and, IMHO, should be contributed individually (basically split the diff with one PR taking care of embeddings and another taking care of tensors
1. BaseSparsifier -- this could be inherited from the original BaseSparsifier, with some overrides of the internal variables and functionality. That way you can reuse the `__state_dict__` utilities

2022-06-08 18:28 UTC, z-a-f commented on torch/ao/sparsity/experimental/data_sparsifier/base_data_sparsifier.py
> +        # TODO: Call the torch.ao.utils.convert in here
Remove this line

2022-06-08 18:32 UTC, z-a-f commented on torch/ao/sparsity/experimental/data_sparsifier/base_data_sparsifier.py
> +__all__ = [Dict, Any, FakeSparsity, List, Optional, Tuple, defaultdict, 'BaseDataSparsifier', 'Container']
`__all__` should be inside the `torch/ao/sparsity/experimental/data_sparsifier/__init__.py`

2022-06-08 18:33 UTC, z-a-f commented on torch/ao/sparsity/experimental/data_sparsifier/base_data_sparsifier.py
> +            format_string += f'\Data Group\n'
Careful with escape chars

2022-06-08 19:18 UTC, z-a-f commented on torch/ao/sparsity/experimental/data_sparsifier/base_data_sparsifier.py
> +        self.__dict__.update(state)
The `self._container` is not loaded here. Consider the following:

```python
def __setstate__(self, state):
    container_state = state.pop('container_state')
    self.__dict__.update(state)
    self._container.load_from_state_dict(container_state)
```

2022-06-10 00:16 UTC, macandro96 commented
Created a new one [here](https://github.com/pytorch/pytorch/pull/79254)

2022-06-10 00:16 UTC, closed without merging