[quant][core][improvement] Added warnings for when reduce_range is set to true when using qnnpack backend
pytorch/pytorch pull request #79273
Opened 2022-06-10 12:35 UTC by dzdang

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Summary:
Previously, the backend code "silently" ignores reduce_range=true when
using the qnnpack backend (which does not require a reduction in range).
We evaluated either 1) respecting the reduction in range to conform with
other backends (e.g., fbgemm) even when qnnpack does support the full
range 2) throwing a warning and letting the user know that the
reduce_range=true setting is being ignored.

Option 1 would halve the range which could have some negative
implications to accuracy, so we have opted for option 2, which has the
negative consequence of overriding the user's input. If there is a
strong objection to this, we could explore option 1 again, or allow the
user to choose either option.

Fixes #68278

Test plan:

2022-06-10 12:40 UTC, dzdang commented
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37068897).

2022-06-11 04:50 UTC, jerryzh168 approved these changes

2022-06-13 14:25 UTC, vkuzo requested changes
it's unexpected to ignore a user setting, can we honor the setting and change the warning to let the user know there is a better way?

2022-06-13 17:01 UTC, dzdang commented
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37068897).

2022-06-14 00:06 UTC, jerryzh168 commented
@vkuzo we definitely should make this better but honoring the option would be bc-breaking right now, maybe we should not make bc-breaking changes until we finalize the plan for quantized engines? wdyt?

2022-06-14 00:12 UTC, dzdang commented
@vkuzo @jerryzh168 I tried honoring `reduce_range=True` for qnnpack, and it led to a lot of test failures (see current failures in the CI, a lot of it are from jit). I dug a bit deeper into some of the test failures and found that a lot of these tests (and our workflow) assume qnnpack never reduces the range, so this would be a bit tricky to fix all of these inherent assumptions

2022-06-14 02:11 UTC, vkuzo commented
makes sense, then can we make the warning say something like "currently, qnnpack incorrectly ignores reduce_range, this may change in a future release"?

2022-06-14 15:21 UTC, vkuzo commented on aten/src/ATen/native/quantized/cpu/qconv_dynamic.cpp
> +    "Reducing the range for qnnpack would currently lead to bc-breaking behavior.");
nit: maybe we can remove this line?

2022-06-14 15:21 UTC, vkuzo approved these changes

2022-06-14 21:37 UTC, dzdang commented
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37068897).

2022-06-15 01:26 UTC, dzdang commented
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37068897).

2022-06-15 14:18 UTC, dzdang commented
@pytorchbot merge -g

2022-06-15 14:18 UTC, dzdang commented
not sure why this didn't get auto merged when the internal diff landed. going to try to merge it manually

2022-06-15 17:15 UTC, closed without merging