Add new checks in CI system to verify the built linux pip wheel with cpu-cxx11-abi
pytorch/pytorch pull request #79409
Opened 2022-06-13 09:33 UTC by zhuhong61

We added the linux pip wheel with cpu-cxx11-abi in pytorch/builder, see: https://github.com/pytorch/builder/pull/990 and https://github.com/pytorch/builder/pull/1023

The purpose of this PR is to add new checks in pytorch CI system to verify the linux pip wheel with cpu-cxx11-abi.

Co-authored-by: Zhu Hong <hong.zhu@intel.com>
Co-authored-by: Guo Yejun <yejun.guo@intel.com>

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

2022-06-28 07:47 UTC, zhuhong61 commented
Hi @malfet, any comment for this? This PR is for https://github.com/pytorch/builder/pull/990#issuecomment-1104440290, thanks!

2022-07-04 04:45 UTC, gujinghui commented
Hi @@malfet 
Could you help review? Thanks.

2022-07-13 23:11 UTC, malfet approved these changes

2022-07-13 23:17 UTC, malfet commented
@zhuhong61 please rebase, otherwise looks good to me

2022-07-14 12:40 UTC, zhuhong61 commented
@malfet Rebase finished. Thanks!

2022-07-27 23:16 UTC, malfet requested changes
It could not go until https://github.com/pytorch/builder/pull/1062 is re-landed, is it?

2022-07-29 07:44 UTC, zhuhong61 commented
> It could not go until [pytorch/builder#1062](https://github.com/pytorch/builder/pull/1062) is re-landed, is it?

Thanks @malfet 
https://github.com/pytorch/pytorch/pull/79409 and https://github.com/pytorch/builder/pull/1062 are two things.
This PR https://github.com/pytorch/pytorch/pull/79409 is to support the ci system for **pip wheel** (merged now, please see https://github.com/pytorch/builder/pull/990 and https://github.com/pytorch/builder/pull/1023) , and https://github.com/pytorch/builder/pull/1062 is for building the **conda wheel**.

When conda wheel https://github.com/pytorch/builder/pull/1062 is ready, I will add checks in ci system for it separately.

2022-08-03 09:32 UTC, gujinghui commented
> It could not go until [pytorch/builder#1062](https://github.com/pytorch/builder/pull/1062) is re-landed, is it?

@malfet  This one is ready to merge. Pls help review.

2022-08-10 22:37 UTC, malfet commented
Can we validate that it is compatible with manylinux_2_28?

2022-08-11 03:27 UTC, zhuhong61 commented
> Can we validate that it is compatible with manylinux_2_28?

Thanks for your reply. We have validated the pip wheel built with cpu-cxx11-abi in manylinux_2_28 (x86_64 image: quay.io/pypa/manylinux_2_28_x86_64 https://github.com/pypa/manylinux), and it is compatible with manylinux_2_28.

2022-09-07 02:41 UTC, zhuhong61 commented
Hi @malfet Any comments? Thanks!

2022-09-16 16:33 UTC, gujinghui commented
@malfet 
The PR is ready to land. Could you help review again? Thanks.

2022-11-02 02:11 UTC, zhuhong61 commented
Hi @malfet, I have signed the EasyCLA and this PR has been rebased. Is there any other suggestions? Thanks!

2022-11-27 13:55 UTC, zhuhong61 commented
Hi @malfet Could you please help check why after the build for cxx11-cpu-abi still failed? The workflow has been added. https://github.com/pytorch/builder/pull/1198
<img width="725" alt="image" src="https://user-images.githubusercontent.com/95205772/204138974-469902cd-4761-41d2-94c3-ae8d1e2ca000.png">

2022-12-01 08:48 UTC, zhuhong61 commented
Hi @malfet We found the reason for the docker pull failure: although the website (https://hub.docker.com/r/pytorch/manylinuxcxx11-abi-builder) has generated the pytorch/manylinuxcxx11-abi-builder, but it is empty without any images, so we can't pull it. Do we need other steps to upload the image? Thanks!

2022-12-05 15:40 UTC, zhuhong61 commented
Hi @malfet Any suggestions? Thanks!

2022-12-22 03:07 UTC, zhuhong61 commented
Hi @malfet @atalman We submit another PR to fix the cpu-cxx11-abi check failure. https://github.com/pytorch/builder/pull/1251 Could you please help review? Thanks!

2023-02-02 05:26 UTC, zhuhong61 commented
This PR is for validating the changes https://github.com/pytorch/pytorch/pull/92550

2023-02-06 03:38 UTC, malfet approved these changes
Again, this approach does not make much sense to me, but there is nothing inherently bad in adding a nightly build (as long as it's not going to get promoted into release channel)

2023-02-06 17:11 UTC, atalman commented
@zhuhong61 Could you please specify use case for adding new build? specially if it will not be included in the release. Is this in intended for nightly only ?

2023-02-07 01:51 UTC, zhuhong61 commented
> @zhuhong61 Could you please specify use case for adding new build? specially if it will not be included in the release. Is this in intended for nightly only ?

Hi @malfet @atalman We are targeting this PT2.0 release. The PRs for this nightly build is for verifying we can build this new wheel successfully without blocking pytorch's current builds. But our final purpose is release. Could you please provide the methods for release?

2023-02-07 03:17 UTC, malfet commented
> Hi @malfet @atalman We are targeting this PT2.0 release. The PRs for this nightly build is for verifying we can build this new wheel successfully without blocking pytorch's current builds. But our final purpose is release. Could you please provide the methods for release?

Correct me if I'm wrong, but we've discussed this a few time. This change makes the package interoperable with the rest of the ecosystem(i.e. torch vision build for manylinux2014 would not be able to use cxx11-abi package, would it) Also, switching CXX11 ABI does not bring any performance gains, does it? Moreover, I'm not sure if  this package will be compatible with say [manylinux_2_28_x86_64](https://quay.io/repository/pypa/manylinux_2_28_x86_64)?

 If one's goal is to distributed custom build PyTorch with some additional extensions, then In my opinion best delivery mechanism is a Linux container, for example, docker.

2023-02-07 07:08 UTC, fzhao3 commented
@malfet Understood the concern of interoperating with the rest ecosystem, so the request here is to publish CXX11-ABI wheels as an additional offer, without messing up the existing PyTorch released binaries, to accommodate the part of ecosystem which has moved to CXX11-ABI. Besides the extension requirement, seems there have been some long standing demand from community as well (https://github.com/pytorch/pytorch/issues/51039). Do you think it's feasible to host CXX-ABI wheels in a separate folder or something on the download server for PyTorch releases so that people can either self-discover or we can point to them in some side documents, but keeping the get started page intact? At the meantime, we can explore ways to make PyTorch dual ABI compatible.

2023-02-07 14:01 UTC, gujinghui commented
> > Hi @malfet @atalman We are targeting this PT2.0 release. The PRs for this nightly build is for verifying we can build this new wheel successfully without blocking pytorch's current builds. But our final purpose is release. Could you please provide the methods for release?
> 
> Correct me if I'm wrong, but we've discussed this a few times. This change makes the package interoperable with the rest of the ecosystem(i.e. torch vision build for manylinux2014 would not be able to use cxx11-abi package, would it) Also, switching CXX11 ABI does not bring any performance gains, does it? Moreover, I'm not sure if this package will be compatible with say [manylinux_2_28_x86_64](https://quay.io/repository/pypa/manylinux_2_28_x86_64)?
> 
> If one's goal is to distributed custom build PyTorch with some additional extensions, then In my opinion best delivery mechanism is a Linux container, for example, docker.

@malfet  Thanks for reply.
This build should be not for performance. Its aim should be to provide an option to ecosystem, to make full coverage of PyTorch use case. As @fzhao3 mentioned above, PyTorch users in community do have the ask to ABI=1 build for a long time. So do we.
To cover ABI=1 use case in ecosystem, we have to start from PyTorch, because PyTorch is the foundation of the whole ecosystem. Although torchvison already has build option for ABI=1, without corresponding PyTorch package, torchvision users are in same situation, to build torchvision with ABI=1 by themselves. So do other torch infrastructures.

To solve or bypass the ABI issue, I think we have 3 options as below.
1. Wrap PyTorch C++ APIs in which has std::string or std::list, to support both ABI=1 and ABI=0
2. Applications has glue layer to covert ABI=1 std::string to ABI=1 std::string when talking with PyTorch
3. Provide PyTorch release package with ABI=1

For #1, it should be a perfect solution, but with PyTorch API changes, which will pollute ecosystem, as well?
For #2, PyTorch APIs with std::string are widely used in our application/extension. It's too difficult to completely hook each invocation, and introduce huge maintain efforts, as PyTorch is evolving fast. Anyway, we will still try to figure out whether it's a doable solution for our requirement.

For #3, @fzhao3 proposed a great idea, that, only provide a release build package on download server in a separate folder, instead of official release path? Could you consider this option? Thanks.

2023-02-07 14:50 UTC, atalman commented
@fzhao3 @gujinghui  some concerns regarding publishing new binary:
1. If we decide to publish this binary, we would need to have not only the binary itself but all the associated smoke tests and validation workflows implemented in order to ensure the build does not break from one release to another.  Please refer to: https://github.com/pytorch/test-infra/wiki/Validation-Framework#using-validation-framework-for-nightly-and-release-validation
2. Publishing it in separate folder, is problematic since our releng team would need to support new workflow specially for publishing and testing this package.
3. Is there a way instead of publishing new binary to provide a users with a flag/variable such that people can compile this binary just by setting this flag ?

2023-02-09 00:05 UTC, malfet commented
@pytorchbot rebase

2023-02-10 13:38 UTC, gujinghui commented
@zhuhong61

2023-02-10 13:47 UTC, gujinghui commented
@malfet  @atalman 

To fix the failure in xla build as below, we reverted the change in CMakeLists.txt.
Same as previous, only set "-fabi-version=11" for ABI=0 build.
```
+ python -c 'import torch; exit(0 if torch._C._PYBIND11_BUILD_ABI == '\''_cxxabi1011'\'' else 1)'
Error: Process completed with exit code 1.
```
Could you please review and merge the PR https://github.com/pytorch/builder/pull/1303 ?
Then, this PR should be able to land.

2023-02-10 16:31 UTC, atalman commented
@pytorchbot rebase

2023-02-14 02:09 UTC, zhuhong61 commented
@pytorchbot merge

2023-02-14 05:44 UTC, zhuhong61 commented
@pytorchbot rebase

2023-02-14 12:56 UTC, zhuhong61 commented
@pytorchbot merge

2023-02-14 12:59 UTC, closed without merging