Clone tensor to write in ShardedTensor checkpoint
pytorch/pytorch pull request #79400
Opened 2022-06-13 05:35 UTC by zhuzilin

The `torch.save` api will save the origin tensor of a view, which will results in saving a much larger checkpoint when parameters are fused, e.g. in torchrec.

Fixes #79016

2022-06-22 15:10 UTC, kumpera requested changes

2022-06-23 02:53 UTC, zhuzilin commented on torch/distributed/_shard/checkpoint/resharding.py
> +            tensor=tensor.detach().clone(),
fixed.

2022-06-24 17:35 UTC, H-Huang commented
@pytorchbot rebase

2022-06-24 20:36 UTC, kumpera approved these changes
Looks good. Thanks for the PR!

2022-06-24 20:37 UTC, kumpera commented
The failure is unrelated to this PR

2022-06-24 20:38 UTC, kumpera commented
@pytorchmergebot  merge

2022-06-27 15:31 UTC, kumpera commented
@pytorchbot rebase

2022-06-27 19:46 UTC, kumpera commented
@pytorchbot merge

2022-06-28 14:39 UTC, janeyx99 commented
@pytorchbot merge

Kicking off a job here which should wait and pass if the docs job passes.

2022-06-28 17:10 UTC, kumpera commented
@pytorchbot rebase

2022-06-29 03:46 UTC, zhuzilin commented
@pytorchbot merge

2022-06-29 03:47 UTC, closed without merging