Propose code owners from Intel
pytorch/pytorch pull request #80218
Opened 2022-06-24 11:23 UTC by jgong5

This PR proposes a list of CPU-related PyTorch modules that Intel is willing to own or co-own.

2022-06-25 03:11 UTC, jgong5 commented
The proposed list contains modules that fall into the following categories:
1. Intel was the primary contributor and is willing to own the modules (“CPU frontend”, “oneDNN graph integration” and “IDEEP”).
2. Intel made significant contributions and is willing to co-own with Meta and other parties (“CPU ATen backend”, “Autocast”).
3. Intel just started contributing, plans to put major effort and becomes the major contributor. Intel is willing to co-own with Meta (“NNC”).

2022-07-14 06:40 UTC, jgong5 commented
@malfet I applied the changes in CODEOWNERS to the merge_rules.json. Could you please review? For modules in category 2 and 3, there should be Meta owners and/or third-party owners too but I am not sure the appropriate persons to add. Please suggest anything we need to revise. Also, do we need to revert the changes in CODEOWNERS?

2022-07-27 22:38 UTC, malfet requested changes
Let's separate this one from CODEOWNER and exclude NCC for now (I remember @VitalyFedyunin had some concerns about it)

Also, I'm not sure if submodule update would work as `ideep/**` pattern, but we can give it a try

2022-07-27 22:40 UTC, malfet commented on .github/merge_rules.json
> +        "third-party/ideep/**",
I though it should be something like the following
```suggestion
        "third_party/ideep",
```

2022-07-28 13:15 UTC, jgong5 commented
@malfet I removed NNC from the merge_rules.json and reverted changes from CODEOWNERS. Please review. Thanks.

2022-08-10 03:41 UTC, jgong5 commented
Hi @malfet Does the PR look good to you? Any more comments?

2022-08-10 22:12 UTC, malfet approved these changes

2022-08-10 23:27 UTC, jgong5 commented
@pytorchbot merge

2022-08-11 07:14 UTC, jgong5 commented
@pytorchbot rebase

2022-08-11 10:34 UTC, jgong5 commented
@pytorchbot merge

2022-08-11 13:11 UTC, closed without merging