Move the RemoveProfileNodesAndSpecializeTypes pass to the beginning o…
pytorch/pytorch pull request #80583
Opened 2022-06-30 01:51 UTC by chengjunlu

## Motivation
It is found that some optimization passes cannot run successfully with extra prim::profile nodes in the graph in `ProfilingGraphExecutorImpl::runNoGradOptimizations`. (e.g: BatchMM or customPrePasses).
After reviewing the code, it seems the `RemoveProfileNodesAndSpecializeTypes` is a common passes required for both TE and non-TE path.

## Solution
By moving the RemoveProfileNodesAndSpecializeTypes from the TE path to the beginning of `ProfilingGraphExecutorImpl::runNoGradOptimizations` and making it a common passes for all other passes.

2022-08-03 06:34 UTC, ZhiweiYan-96 commented
@ZolotukhinM Hi, could you please review our code?

2022-08-28 13:02 UTC, ZhiweiYan-96 commented
@ZolotukhinM  Hello, do we have any update? : )

2022-09-07 03:07 UTC, gujinghui commented
@ezyang  @eellison @ZolotukhinM @malfet

Could you help review and give suggestion. or tell how should review this PR?
Thanks.

2022-09-07 03:27 UTC, malfet commented
@gujinghui I'm not familiar with that codepath, but sounds like PR are expected to yield are some perf improvement, but at the same time description lacks any absolute/relative perf numbers for any common models. 

Also, this optimization is currently available for TEfuser.
What were the original motivation to limit it and what has changed?

2022-09-08 02:26 UTC, ZhiweiYan-96 commented
hi, @malfet, The profiling node may  be inserted between 2 fusable nodes and it blocks the fusion.  Then it will have impact on performance. 
We contemplate that, the `removingprofilingNode` is a common path for TE and non-TE path,  and it can be a common pass.

2022-12-09 14:30 UTC, jgong5 requested changes

2022-12-09 14:30 UTC, jgong5 commented on torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp
> +        "After RemoveProfileNodesAndSpecializeTypes, before BatchMM\n", *graph);
nit: it is not "before BatchMM" now.

2023-01-08 14:33 UTC, closed without merging