Add shape functions for conv_transpose2d.input and convolution
pytorch/pytorch pull request #80860
Opened 2022-07-05 08:38 UTC by gpetters94

As @silvasean requested in [this issue](https://github.com/llvm/torch-mlir/pull/917#discussion_r896154545) here is the shape code from Torch-MLIR for conv_transpose2d.input and convolution (updated for the transposed case).

2022-07-06 23:48 UTC, gpetters94 commented
> @gpetters94 i fired the tests but they're gonna fail (though I'm not sure which ones) because you haven't genereated the cpp definitions like here https://github.com/pytorch/pytorch/pull/79194/files. you need to run [gen_jit_shape_functions.py](https://github.com/pytorch/pytorch/blob/45cb8199df131a333615123e76c9cf5b37b7cdf1/torchgen/shape_functions/gen_jit_shape_functions.py#L14-L17).

Oh, I see. Doing that right now.

2022-07-07 02:47 UTC, gpetters94 commented
Sorry for all the small commits, still not used to locally testing PyTorch code.

2022-07-07 04:21 UTC, makslevental commented
> Sorry for all the small commits, still not used to locally testing PyTorch code.

np but you're gonna have to squash before it can be merged

2022-07-13 02:17 UTC, gpetters94 commented
> > Sorry for all the small commits, still not used to locally testing PyTorch code.
> 
> np but you're gonna have to squash before it can be merged

Done, sorry about that.

2022-07-15 21:44 UTC, gpetters94 commented
@makslevental Okay, it's rebased to TOM and squashed, so it should be good to go.

2022-07-27 16:52 UTC, gpetters94 commented
@eellison Some of the tests are failing, but it doesn't look like the errors are due to my code. Do you think this can be merged as it is now, or should I be tracking these errors down?

2022-07-27 20:13 UTC, eellison commented
@pytorchbot rebase

2022-07-28 19:45 UTC, Gamrix requested changes
Could you add a assert_jit_shape_analysis=True in the relevant place like is done in the following diff so that we can test this function: https://github.com/pytorch/pytorch/commit/6b6c63ce5e0b54eb92cdd88f3bb87efc7adeaf9c

Also I recommend rebasing on viable/strict so that we can isolate you from irrelevant test failures.

2022-07-29 20:02 UTC, gpetters94 commented
> Could you add a assert_jit_shape_analysis=True in the relevant place like is done in the following diff so that we can test this function: [6b6c63c](https://github.com/pytorch/pytorch/commit/6b6c63ce5e0b54eb92cdd88f3bb87efc7adeaf9c)
> 
> Also I recommend rebasing on viable/strict so that we can isolate you from irrelevant test failures.

Good idea, I've done so.

2022-08-04 19:53 UTC, Gamrix requested changes
The tests are erroring out due to an incorrect shape compute mapping function schema name. Could you apply the suggested changes and rerun the commit?

2022-08-04 19:53 UTC, Gamrix commented on torch/jit/_shape_functions.py
> +add_shape_compute_mapping("aten::conv_transpose2d.input : (Tensor, Tensor, Tensor?, int[], int[], int[], int, int[]) -> (Tensor)", conv_transpose2d_input)
```suggestion
add_shape_compute_mapping("aten::convolution(Tensor input, Tensor weight, Tensor? bias, int[] stride, int[] padding, int[] dilation, bool transposed, int[] output_padding, int groups) -> Tensor", conv_forwards)
add_shape_compute_mapping("aten::conv_transpose2d.input(Tensor input, Tensor weight, Tensor? bias=None, int[2] stride=1, int[2] padding=0, int[2] output_padding=0, int groups=1, int[2] dilation=1) -> Tensor)
```

The tests are erroring out due to the incorrect format.

2022-08-04 23:15 UTC, gpetters94 commented
> The tests are erroring out due to an incorrect shape compute mapping function schema name. I applied the changes and am rerunning tests.

Ah, I see. Thanks for the help!

2022-08-10 18:31 UTC, Gamrix commented
I have recently pushed some fixes in this diff: https://github.com/pytorch/pytorch/pull/79571

I recommend rebasing on top of it. The easiest way to do so would be to rebase on top of viable/strict tomorrow (8/11) or later. Then ignore any merge conflict in the generated file and regenerate it.

2022-08-10 23:21 UTC, gpetters94 commented
> I have recently pushed some fixes in this diff: #83092
> 
> You will need to rebase on top of it. The easiest way to do so would be to rebase on top of viable/strict tomorrow (8/11) or later. Then ignore any merge conflict in the generated file and regenerate it.

Fantastic, thank you.

2022-08-12 18:09 UTC, Gamrix commented
@albanD @seemethere This PR is incorrectly erroring out on the 2000 LOC maximum check in `[pr-sanity-checks](https://github.com/pytorch/pytorch/runs/7810904545?check_suite_focus=true#logs)` . There is only 124 LOC of changes. Could you check the logic for this code and see why this is happening?

2022-08-12 19:17 UTC, albanD commented
@Gamrix sorry about that. The fix is here: https://github.com/pytorch/pytorch/pull/83344

2022-08-12 21:06 UTC, Gamrix commented on torch/jit/_shape_functions.py
> +
```suggestion

```

2022-08-12 22:41 UTC, Gamrix approved these changes
Looks good, now just waiting for all the tests to pass before I land this. 

(I will ignore the PR line count error)

2022-08-13 01:17 UTC, Gamrix commented
@pytorchmergebot merge --force "Overriding the broken `pr-sanity-checks` check."

2022-08-13 01:20 UTC, closed without merging

2022-08-15 17:41 UTC, Gamrix commented
Thanks @gpetters94 for contributing :D

2023-06-16 06:26 UTC, CaoE commented
@gpetters94 May I know which tests can cover this change, and how do we use `conv_forwards` and `conv_transpose2d_input` defined in `serialized_shape_function_registry.cpp` or `_shape_functions.py`. 

Seems the code below can't utilize `conv_forwards`  since the node in the graph generated by torch.jit.trace for conv2d is `_convolution` instead of `convolution`, considering `{"aten::convolution(Tensor input, Tensor weight, Tensor? bias, int[] stride, int[] padding, int[] dilation, bool transposed, int[] output_padding, int groups) -> Tensor", "conv_forwards"}`
```
inp_shape = torch.rand([1, 16, 5, 10])
weight_shape = torch.rand([33, 16, 3, 3])
bias = None
stride = [2, 2]
padding = [0, 0]
dilation = [1, 1]
groups = 1
res = torch.nn.functional.conv2d(inp_shape, weight_shape, bias, stride, padding, dilation, groups).size()

def foo(inp_shape, weight_shape):
    return torch.nn.functional.conv2d(inp_shape, weight_shape, bias, stride, padding, dilation, groups)

fn = torch.jit.trace(foo, (inp_shape, weight_shape))
torch._C._jit_erase_non_input_shape_information(fn.graph)
torch._C._jit_pass_peephole(fn.graph)
torch._C._jit_pass_constant_propagation(fn.graph)
self.checkShapeAnalysis(res, fn.graph, assert_propagation=True)
```