[WIP] Testing use fabi-version=11
pytorch/pytorch pull request #81058
Opened 2022-07-07 20:28 UTC by atalman

Fixes #ISSUE_NUMBER

2022-07-08 14:36 UTC, zou3519 approved these changes

2022-07-08 14:43 UTC, malfet requested changes
This is a wrong location to put this constraint, as it has nothing to do with generic PyTorch builds, but specific to how we are packaging it for release

2022-07-08 14:51 UTC, malfet commented on CMakeLists.txt
> +    # Please note this is required in order to ensure compatibility between gcc 9 and gcc 7
This codeblock would be a good location for this change. Aso, please edit a comment a bit to indicate 
```suggestion
    # Pin C++ ABI compatibility to version 11(first introduced in gcc-7), see https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html 
```
https://github.com/pytorch/pytorch/blob/4bf076e964a6304fdcfbfc3fc0475da65de00fc9/CMakeLists.txt#L44-L46

2022-07-11 18:07 UTC, malfet approved these changes

2022-07-11 18:07 UTC, malfet commented on CMakeLists.txt
> +    # This needs to be removed when we stop compiling with gcc 7
```suggestion
    # This could be removed when all Linux PyTorch binary builds are compiled by the same toolchain again
```

2022-07-11 21:53 UTC, malfet reviewed
You need to add
```
if(${GLIBCXX_USE_CXX11_ABI} EQUAL 0)
 string(APPEND CMAKE_CXX_FLAGS " -fabi-version=11")
endif()
```
to 
https://github.com/pytorch/pytorch/blob/28776c45e393ec7d6731a5613f5d79d309036d3a/caffe2/CMakeLists.txt#L1227

2022-07-11 21:59 UTC, atalman commented
> You need to add
> 
> ```
> if(${GLIBCXX_USE_CXX11_ABI} EQUAL 0)
>  string(APPEND CMAKE_CXX_FLAGS " -fabi-version=11")
> endif()
> ```
> 
> to
> 
> https://github.com/pytorch/pytorch/blob/28776c45e393ec7d6731a5613f5d79d309036d3a/caffe2/CMakeLists.txt#L1227



> in [28776c4](/pytorch/pytorch/commit/28776c45e393ec7d6731a5613f5d79d309036d3a)

As discussed will not be doing this change in this PR, but refactor it

2022-07-12 13:10 UTC, atalman commented
@pytorchbot merge

2022-07-12 14:20 UTC, atalman commented
@pytorchbot merge

2022-07-12 17:56 UTC, closed without merging

2022-07-13 17:56 UTC, JackCaoG commented
OK CI is actually OK, it is our internal build failed. I will try to look into it this afternoon.

2022-07-14 01:05 UTC, JackCaoG commented
this seems to break our setup when using gcc8. I run into errors like
```
Building wheel torch-1.13.0a0+gitc657c3d
-- Building version 1.13.0a0+gitc657c3d
cmake -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/pytorch/torch -DCMAKE_PREFIX_PATH=/root/anaconda3/envs/pytorch/lib/python3.7/site-packages -DGLIBCXX_USE_CXX11_ABI=0 -DNUMPY_INCLUDE_DIR=/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/root/anaconda3/envs/pytorch/bin/python -DPYTHON_INCLUDE_DIR=/root/anaconda3/envs/pytorch/include/python3.7m -DPYTHON_LIBRARY=/root/anaconda3/envs/pytorch/lib/libpython3.7m.so.1.0 -DTORCH_BUILD_VERSION=1.13.0a0+gitc657c3d -DUSE_CUDA=0 -DUSE_NUMPY=True /pytorch
-- The CXX compiler identification is Clang 8.0.1
-- The C compiler identification is Clang 8.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++-8 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang-8 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Not forcing any particular BLAS to be found
-- Could not find ccache. Consider installing ccache to speed up compilation.
-- Performing Test COMPILER_WORKS
-- Performing Test COMPILER_WORKS - Success
-- Performing Test SUPPORT_GLIBCXX_USE_C99
-- Performing Test SUPPORT_GLIBCXX_USE_C99 - Failed
CMake Error at cmake/MiscCheck.cmake:63 (message):
  The C++ compiler does not support required functions.  This is very likely
  due to a known bug in GCC 5 (and maybe other versions) on Ubuntu 17.10 and
  newer.  For more information, see:
  https://github.com/pytorch/pytorch/issues/5229
Call Stack (most recent call first):
  CMakeLists.txt:695 (include)
```
```
(pytorch) root@803de85a4f7e:/# gcc --version
gcc (Debian 8.3.0-6) 8.3.0
```

any insight?

2022-07-14 03:22 UTC, JackCaoG commented
I guess pytorch/xla would just always enable `GLIBCXX_USE_CXX11_ABI` which seems to solve the issue. We have been doing this for the release wheel and ci anyway