[PyTorch] [STFT] use fft when fft_size == frame_length
pytorch/pytorch pull request #8123
Opened 2018-06-04 18:53 UTC by SsnL

Addresses #7883 
Using script in #7883 , here are the new timings:
```
librosa: 1.918302297592163
(2049, 2647)
torch: 0.34431028366088867
torch.Size([10, 2639, 2049])
```
The output shape difference is expected as explained in https://github.com/pytorch/pytorch/issues/7038 .

2018-06-04 19:38 UTC, SsnL commented
cc @zou3519 for another interesting failing instance of `test_expect` on mac:
```
19:32:09 - [pip] torch (0.5.0a0+23384)
19:32:09 ?                     ------
19:32:09 + [pip] torch (0.5.0a0)
```

2018-06-04 19:57 UTC, SsnL commented
@pytorchbot retest this please

2018-06-04 21:02 UTC, SsnL commented
@pytorchbot retest this please

2018-06-06 02:08 UTC, ezyang commented on aten/src/ATen/native/SpectralOps.cpp
> +    REPR(ss) << ": expected hop > 0, but got hop=" << hop;
FYI you can conveniently do this with `AT_CHECK` now (but you would have to rewrite `REPR` macro, so maybe not for this patch)

2018-06-06 02:09 UTC, ezyang approved these changes

2018-06-10 03:31 UTC, ezyang requested changes
reconciling with librosa

2018-06-12 19:18 UTC, ezyang commented
@pytorchbot retest this please

2018-06-12 22:13 UTC, SsnL commented
@pytorchbot retest this please

2018-06-22 20:22 UTC, SsnL commented
i'll re-submit the pr after #8721

2018-06-22 20:22 UTC, closed without merging