[ONNX] remove outdated ImplicitCastType QA in onnx.rst
pytorch/pytorch pull request #81268
Opened 2022-07-11 19:39 UTC by AllenTiTaiWang

Extend work from: https://github.com/pytorch/pytorch/pull/80596
This PR removes outdated QA of ImplicitCastType , as the coverage is greatly increased with the introduction of onnx shape inference and scalar type analysis.

2022-07-11 19:50 UTC, justinchuby commented
@BowenBao I realized

> Q: Does ONNX support implicit scalar datatype casting?
  No, but the exporter will try to handle that part. Scalars are exported as constant tensors.
  The exporter will try to figure out the right datatype for scalars. 

Is probability still valid. Is that accurate?

2022-07-12 22:52 UTC, justinchuby commented on docs/source/onnx.rst
```suggestion

Q: Does ONNX support implicit scalar datatype casting?

  No, but the exporter will try to handle that part. Scalars are exported as constant tensors.
  The exporter will figure out the right data type for scalars. In rare cases when it is unable
  to do so, you will need to manually specify the datatype with e.g. `dtype=torch.float32`.
  If you see any errors, please create a GitHub issue.
```

2022-07-12 22:52 UTC, justinchuby requested changes
I would retain a part of the answer

2022-07-12 23:41 UTC, justinchuby approved these changes
LGTM🚀

2022-07-15 16:15 UTC, BowenBao approved these changes

2022-07-15 16:18 UTC, closed without merging