has_any_layout utility function
pytorch/pytorch pull request #82167
Opened 2022-07-25 21:36 UTC by cpuhrsch

### Description
This is a proposal with a few integration sites for a utility function that can help us save a few lines of code and typos.

### Issue

### Testing
This is a refactor and covered by existing tests

2022-07-26 13:12 UTC, pearu requested changes
Other than one bug, this looks good to me.

Would it make sense to expose `has_any_layout` as a tensor method?

2022-07-26 13:12 UTC, pearu commented on aten/src/ATen/native/sparse/SparseCsrTensorMath.h
> +  if (has_any_layout(self.layout(), kSparse, kSparseCsr, kSparseCsc, kSparseBsr, kSparseBsc)) {
This should read:
```suggestion
  if (has_any_layout(self, kSparse, kSparseCsr, kSparseCsc, kSparseBsr, kSparseBsc)) {
```

2022-07-26 15:14 UTC, cpuhrsch commented
@pearu - Maybe, but then we'll potentially need to discuss it from an API perspective. Right now it's just an innocent refactor that saves us time and bugs.

2022-08-05 16:50 UTC, bhosmer commented
see [here](https://github.com/pytorch/pytorch/pull/82122#discussion_r938993325) for the argument against 😁 (and an alternative)

2022-10-12 21:49 UTC, closed without merging