ONNX cherry picks for 1.12.1
pytorch/pytorch pull request #82435
Opened 2022-07-28 21:58 UTC by BowenBao

2022-07-28 22:30 UTC, justinchuby approved these changes

2022-07-29 17:18 UTC, BowenBao commented
@malfet this should be ready once CI is green.

2022-07-29 19:11 UTC, justinchuby commented on test/onnx/test_pytorch_onnx_no_runtime.py
>  instantiate_parametrized_tests(TestOptionalOutput)
We may need to move this to the bottom

2022-08-01 16:23 UTC, justinchuby approved these changes

2022-08-01 21:16 UTC, BowenBao commented
@malfet This 1.12.1 pull request for ONNX is ready. Please help us cherry pick.

2022-08-01 22:56 UTC, malfet requested changes
What are the corresponding trunk PRs? (Nothing can be cherry-picked into release branch unless it were landed in trunk first)
And what is the justification for those fixes? Is this a regression from 1.11? Or a bug in a newly introduced feature?

2022-08-01 23:58 UTC, BowenBao commented
> What are the corresponding trunk PRs? (Nothing can be cherry-picked into release branch unless it were landed in trunk first) And what is the justification for those fixes? Is this a regression from 1.11? Or a bug in a newly introduced feature?

What are trunk PRs? We are following cherry pick steps like #81976. Please let us know if we missed any steps. 
These are important fixes that unblock customer models. Justifications are as follows. 
```
Regression from 1.12:
0b13260 [ONNX] Test and address autograd.func (FusedLayerNorm) shape inference (#81931)

Fixing quantization export introduced in 1.12:
11f7463 Add more functions to __init__.pyi.in for torch._C for Node and Value (#79654)
ed1da2a [ONNX] Quantization support for quantized::cat (#79826)
356341a [ONNX] Add quantization support to _avg_pool opset 9 and clean up (#79793)
def7785 [ONNX] Quantization support for five ops (#78103)
c0814bf [ONNX] Variable length argument support for quantized_args (#78775)
```

2022-08-02 17:38 UTC, atalman approved these changes
Approving as per discussion

2022-08-02 17:44 UTC, merged