[ONNX] Add an ATen fallback pathway for ONNX export
pytorch/pytorch pull request #8273
Opened 2018-06-08 03:58 UTC by jamesr66a

This adds a flag that makes it so that if we cannot export an operator, we will fall back to exporting an op of type ATen with the appropriate schema. This will help smooth over our production use cases, where if ONNX supports and op we want to use that translation pathway, but if it does not we want to simply use ATen for speed of deployment

2018-06-08 23:58 UTC, dzhulgakov requested changes

2018-06-08 23:58 UTC, dzhulgakov commented on torch/csrc/jit/export.cpp
> +  bool aten_fallback = false;
time to make it an enum - too many bool fields flying around.

Basically we have:
- raw
- onnx strict
- onnx with Aten ops everywhere (added by Lu)
- onnx with Aten ops as fallback

I think export mode would make it much saner - with your diff we now have 3 bool fields :( And it's pretty confusing for this code maintainability

2018-06-12 01:21 UTC, dzhulgakov approved these changes
Looks great, thanks for making code to have less unnamed bools :)

2018-06-12 01:21 UTC, dzhulgakov commented on torch/csrc/Module.cpp
> +  torch::jit::initJITBindings(module);
please add comments that the order is important to preserve future pain :)

2018-06-12 17:43 UTC, apaszke approved these changes

2018-06-12 17:43 UTC, apaszke commented on torch/onnx/utils.py
> +           input_names=None, output_names=None, operator_export_type=OperatorExportTypes.ONNX):
This changes the public interface? Did we advertise the bool args previously? If yes, add bc compat code to translate them to enum values

2018-06-12 17:43 UTC, apaszke commented on torch/onnx/utils.py
> +                    (not is_exportable_aten_op and operator_export_type == OperatorExportTypes.ONNX_ATEN_FALLBACK):
Can you please split the two branches in this if into variables and use them in here? It's very hard to read at the moment.

2018-06-13 05:59 UTC, merged