[MPS] Fix for matmul errors in test consistency
pytorch/pytorch pull request #83124
Opened 2022-08-09 22:38 UTC by kulinseth

* Handle empty input with non-empty output
* Remove transpose options from mm op

2022-08-10 15:58 UTC, albanD reviewed
Should the test be re-enabled?

2022-08-10 21:22 UTC, malfet requested changes
+1 on Alban's feedback: should this change include some testing?

2022-08-11 14:19 UTC, kulinseth commented
> +1 on Alban's feedback: should this change include some testing?

Agreed, the testConsistency `nn.functional.linear` still has some issues. I will enable a subset which was fixed.

2022-08-12 16:40 UTC, kulinseth commented
> +1 on Alban's feedback: should this change include some testing?

@malfet , can you please take a look now.

2022-08-12 16:45 UTC, malfet approved these changes
LGTM, see nits

2022-08-12 16:45 UTC, malfet commented on aten/src/ATen/native/mps/operations/Activation.mm
> +
nit: per PyTorch coding standard we should use curly braces even for single line return blocks
```suggestion
  if(output.numel() == 0) {
    return;
  }

```

2022-08-12 16:45 UTC, malfet commented on aten/src/ATen/native/mps/operations/Linear.mm
> +
nit
```suggestion
  if(output.numel() == 0) {
    return output;
  }

```

2022-08-12 16:45 UTC, malfet commented on aten/src/ATen/native/mps/operations/PointwiseOps.mm
> +
```suggestion
  if(output.numel() == 0) {
    return output;
  }

```

2022-08-12 16:46 UTC, malfet commented
Added `ciflow/mps` tag to schedule just the tests we care about (plan to add action that auto assigns this label soon)

2022-08-12 21:17 UTC, kulinseth commented
> Added `ciflow/mps` tag to schedule just the tests we care about (plan to add action that auto assigns this label soon)

Sound great.

2022-08-12 23:27 UTC, kulinseth commented
@pytorchbot merge

2022-08-12 23:28 UTC, closed without merging