removed duplicate_quantize_dynamic_node
pytorch/pytorch pull request #83459
Opened 2022-08-15 19:51 UTC by danrecoskie

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2022-08-16 16:47 UTC, jerryzh168 approved these changes
thanks! changes looks good

2022-08-16 16:49 UTC, jerryzh168 commented on torch/ao/quantization/fx/_lower_to_native_backend.py
> +        model.graph.erase_node(node)
we can rely on dead code elimination to remove this I think: https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/fx/_lower_to_native_backend.py#L966

2022-08-16 16:55 UTC, jerryzh168 requested changes
actually I think there are more changes that's needed, for pattern:
quantize_dynamic - dequantize - fp_op
we also need to allow dequantize to be used by multiple ops, like

quantize_dynamic - dequantize - fp_op
                                           \ -- fp_op2

right now there is still a check in L532 saying dq should not be used by multiple users and in L564 
```dq_node.replace_all_uses_with(input_dynamic_q_node)``` also assumes that dq is only used by one node I think

2022-08-17 18:32 UTC, jerryzh168 approved these changes
lg, thanks!

2022-08-17 21:24 UTC, danrecoskie commented
@pytorchbot merge

2022-08-17 21:26 UTC, closed without merging

2022-08-18 20:29 UTC, danrecoskie commented
@danrecoskie has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38841053).