Test type promotion assertignoretypes
pytorch/pytorch pull request #83867
Opened 2022-08-22 19:57 UTC by sladebot

Fixes #38095

2022-08-22 20:41 UTC, kit1980 commented
I've removed "Fixes" from the description because this is only a partial fix.

2022-08-22 20:44 UTC, kit1980 requested changes

2022-08-22 20:44 UTC, kit1980 commented on test/test_type_promotion.py
> +        self.assertEqual(f + f, d, exact_dtype=False)
We don't want to just add `exact_dtype=False` - this should be the last resort only in there is no way to align the types in other ways.

2022-08-23 17:21 UTC, mruberry approved these changes
LGTM! Thanks @sladebot!

2022-08-23 17:21 UTC, mruberry commented
@pytorchbot merge

2022-08-23 17:37 UTC, kit1980 approved these changes

2022-08-23 18:22 UTC, kit1980 commented
There are some ongoing unrelated infra issues are happening, let's try to merge again a bit later.

2022-08-24 05:17 UTC, kit1980 commented
@pytorchbot merge

2022-08-24 05:18 UTC, kit1980 commented
> > There are some ongoing unrelated infra issues are happening, let's try to merge again a bit later.
> 
> @kit1980 - I reran it and they all passed now.

FYI, you can also comment pytorchbot merge, no special permissions needed for that after review.

2022-08-24 08:00 UTC, closed without merging