[WIP] Increase timeout test for linux builds
pytorch/pytorch pull request #84008
Opened 2022-08-24 19:16 UTC by atalman

Increase timeout test for linux builds 
Trying to understand the cause of Linux cu113 and cu116 build conda jobs timing out

2022-08-24 20:43 UTC, ZainRizvi approved these changes, later dismissed

2022-08-24 22:07 UTC, malfet requested changes
As PR states, it's a work-in-progress, so let's not land it as is

2022-08-25 00:46 UTC, atalman commented
@malfet @ZainRizvi should we land it to mitigate the issue with nighly builds ?

2022-08-25 01:06 UTC, malfet approved these changes
As a temp measure, this is fine

2022-08-25 01:06 UTC, malfet commented
@pytorchbot merge -f "Affects only binary builds"

2022-08-25 01:08 UTC, closed without merging