CUDA 11.6 slow grad checks tune tolerance on test_fn_gradgrad
pytorch/pytorch pull request #84313
Opened 2022-08-30 22:58 UTC by atalman

CUDA 11.6 slow grad checks tune tolerance on test_fn_gradgrad

2022-08-30 23:07 UTC, malfet approved these changes

2022-08-30 23:07 UTC, malfet commented on torch/testing/_internal/opinfo/definitions/linalg.py
> +                "test_fn_gradgrad",
Don't you want to limit tolerance reduction to just cuda tests?
```suggestion
                "test_fn_gradgrad",
                device="cuda",
```

2022-08-30 23:07 UTC, huydhn approved these changes
Linter, otherwise LGTM!

2022-08-30 23:17 UTC, atalman commented on torch/testing/_internal/opinfo/definitions/linalg.py
> +                toleranceOverride({torch.float64: tol(atol=1e-4, rtol=1e-4)})
```suggestion
                toleranceOverride({torch.float64: tol(atol=1e-4, rtol=1e-4)}),
```

2022-08-31 00:02 UTC, atalman commented
@pytorchmergebot merge -g

2022-08-31 00:14 UTC, atalman commented
@pytorchmergebot merge -g

2022-08-31 09:05 UTC, Lezcano approved these changes
the linalg part LGTM!

2022-09-01 19:27 UTC, malfet requested changes
Please update PR description (namely remove "Fixes" statement, as it does not fix the problem, but rather disables those tests)
And reference the issue in test skip reason

2022-09-01 19:27 UTC, malfet commented on torch/testing/_internal/opinfo/definitions/linalg.py
> +                unittest.skip("Skipped!"),
```suggestion
                unittest.skip("Skipped, see https://github.com/pytorch/pytorch/issues/84192"),
```

2022-09-01 19:32 UTC, atalman commented on torch/testing/_internal/opinfo/definitions/linalg.py
> +                unittest.skip("Skipped!"),
```suggestion
                unittest.skip("Skipped, see https://github.com//issues/84192"),
```

2022-09-01 19:59 UTC, malfet approved these changes

2022-09-01 20:21 UTC, atalman commented
@pytorchmergebot merge -f "Failures on bezel job are not related to this PR"

2022-09-01 20:24 UTC, closed without merging