[TensorImpl] Make set_storage_keep_dtype virtual
pytorch/pytorch pull request #84855
Opened 2022-09-12 08:48 UTC by amitchawla1

Summary:

For lazy tensor impl, set_storage_keep_dtype needs to be virtual to take care of dummy storage created for frontend tensors. For lazy tensor impl, simple move of storage doesn't work because it may not have been evaluated and for other book keeping that TensorImpl need to do, this function should be virtual.

2022-09-15 16:30 UTC, Krovatkin commented
@amitchawla1 could you please elaborate maybe with some examples why a dummy storage option won't work? 

This PR only makes `LTCTensorImpl::set_storage_keep_dtype` virtual, if it's called via a base class pointer, it would still be using the base class implementation?

For example,

```cpp
#include <iostream>


struct A {
    void foo() {std::cout << "A\n"; }
};

struct AA: public A {
    virtual void foo() {std::cout << "AA\n"; }
};

struct BB: public AA {
    void foo() override {std::cout << "BB\n"; }
};

int main() {
    
    A* a = new BB();
    AA* aa = (AA*)a;
    a->foo(); // this still prints A
    aa->foo();
    return 0;
}
```
This could be inconsistent and confusing.

2022-09-22 03:50 UTC, sujoysaraswati commented
@Krovatkin - I have added my comments below -

> @amitchawla1 could you please elaborate maybe with some examples why a dummy storage option won't work?
> 
> This PR only makes `LTCTensorImpl::set_storage_keep_dtype` virtual, if it's called via a base class pointer, it would still be using the base class implementation?

This PR is making the base tensor TensorImpl::set_storage_keep_dtype` virtual, so that it can be overridden by other derived classes of TensorImpl. If there is no overloading, then the base class TensorImpl::set_storage_keep_dtype` would be called, the purpose of making this virtual is to handle derived class specific functionality. This would be similar to existing virtual methods in TensorImpl like has_storage(), storage() etc.

> 
> For example,
> 
> ```c++
> #include <iostream>
> 
> 
> struct A {
>     void foo() {std::cout << "A\n"; }
> };
> 
> struct AA: public A {
>     virtual void foo() {std::cout << "AA\n"; }
> };
> 
> struct BB: public AA {
>     void foo() override {std::cout << "BB\n"; }
> };
> 
> int main() {
>     
>     A* a = new BB();
>     AA* aa = (AA*)a;
>     a->foo(); // this still prints A
>     aa->foo();
>     return 0;
> }
> ```
> 
> This could be inconsistent and confusing.

2022-09-28 07:39 UTC, amitchawla1 commented
@Krovatkin Any thoughts on what @sujoysaraswati mentioned.
Basically, in your example we are doing 
struct A {
    **virtual** void foo() {std::cout << "A\n"; }
};

2022-09-29 04:17 UTC, wconstab commented
> @Krovatkin Any thoughts on what @sujoysaraswati mentioned.
Basically, in your example we are doing
struct A {
virtual void foo() {std::cout << "A\n"; }
};

I think i agree that the proposed change is making the base TensorImpl method virtual and thus doesn't apply to your example @Krovatkin.

But I also don't understand the implications of making this change well enough or whether there is a better way to achieve the goals.  Maybe @ezyang can help.

2022-09-29 04:38 UTC, ezyang requested changes
I haven't read the back story but no, I'm not accepting this. We should figure out some other way to do what you want.

2022-09-30 03:47 UTC, ezyang commented
Could you give us some more context on the lazy tensor implementation you're working on?

2022-09-30 04:59 UTC, amitchawla1 commented
Hi @ezyang, we are facing issue with jit.load using Habana backend.
In rebuildTensor() function in unpickler.cpp, empty tensor is created and then some storage from some other tensor is attached to it.
storage() of tensor in lazy mode may be just dummy storage, if "impl->set_storage_keep_dtype(storage_tensor.storage());" is called, we want control for our impl to evaluate the ops accumulated till that point, so that storage is actual storage.
I see set_storage_offset is already virtual, that's why proposed that if set_storage_keep_dtype can also be made virtual.

Other option is to create a new function that encapsulates set_storage_keep_dtype, set_storage_offset, set_sizes_and_strides into one function and make it as virtual and call only from rebuildTensor.

2022-10-01 02:20 UTC, ezyang commented
What is stopping Habana from having a real storage for its serialization format?

2022-10-07 01:17 UTC, amitchawla1 commented
@ezyang, problem is set_storage_keep_dtype is setting storage directly and we can't assume it to be actual storage, since this function is used at many places.

2023-01-05 08:35 UTC, closed without merging