Enable CSC @ CSC addmm
pytorch/pytorch pull request #85379
Opened 2022-09-20 22:47 UTC by amjames

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2022-09-21 13:21 UTC, nikitaved commented on aten/src/ATen/native/sparse/cuda/SparseBlasImpl.cpp
> +      }
A note for the future: looks like MKL/CuSparse `addmm_out` methods are almost identical. We can easily refactor that.

2022-09-21 13:23 UTC, nikitaved commented on aten/src/ATen/native/sparse/cuda/SparseBlasImpl.cpp
> +      if (result.layout() == kSparseCsc) {
Same as the comment above.

2022-09-21 15:14 UTC, pearu requested changes
I have minor nit and a request to update `_test_addmm_addmv` so that in the `all_sparse` case the layout of the result is checked as well. Say:
```python
    if mode == "all_sparse":
        res1 = f(*map(convert_layout, (t, m, v)), alpha=alpha, beta=beta)
        test_case.assertEqual(res1.layout, layout)

```


Otherwise, LGTM! Thanks, @amjames!

2022-09-26 09:39 UTC, pearu approved these changes
LGTM!

2022-09-27 03:41 UTC, cpuhrsch approved these changes

2022-09-27 12:52 UTC, amjames commented
@pytorchbot merge

2022-09-27 15:26 UTC, amjames commented
@pytorchbot merge

2022-09-27 16:34 UTC, amjames commented
@pytorchbot merge

2022-09-27 17:21 UTC, amjames commented
@pytorchbot merge -g

2022-09-27 19:49 UTC, closed without merging