Fixes #8508 Broadcasted loc to 1-d if a scalar loc is provided to MultivariateNormal
pytorch/pytorch pull request #8543
Opened 2018-06-15 01:39 UTC by praveen-palanisamy

This fix unsqueezes the `loc` argument to make it 1-Dimensional in `torch.distributions.MultivariateNormal.__init__` if the provided `loc` is a scalar thereby preventing the SIGFPE.

This is a simple fix for #8508

2018-06-15 15:01 UTC, praveen-palanisamy commented
The failed CI builds are due to docker not being able to pull some images (example: `Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-cuda8.0-cudnn7-ubuntu16.04:125 not found`) and the other seems unrelated to this commit. Can someone please review/check?

2018-06-15 16:20 UTC, ezyang commented
@pytorchbot retest this please

2018-06-25 18:02 UTC, praveen-palanisamy commented
Can someone please review this? It will probably take very less time to review but fixes the SIGFPE issue.
cc: @ezyang @zdevito @colesbury @soumith @gchanan @apaszke

2018-06-25 19:20 UTC, fritzo approved these changes
Please do not update args in-place. Instead use
```py
loc = loc.unsqueeze(0)
```

2018-06-25 19:21 UTC, fritzo requested changes
Could you avoid updating `loc` in-place?

2018-06-25 19:27 UTC, soumith approved these changes
will merge after contbuilds pass

2018-06-25 22:06 UTC, praveen-palanisamy commented
@soumith Notification: Builds have passed

2018-06-25 22:06 UTC, merged

2018-06-25 22:06 UTC, soumith commented
thanks Praveen!