[MPS] Add tensor::index_put op
pytorch/pytorch pull request #85672
Opened 2022-09-26 22:06 UTC by kulinseth

2022-09-27 15:56 UTC, malfet requested changes
Lots of lint errors, and code does not compile

2022-09-27 16:26 UTC, DenisVieriu97 commented on torch/testing/_internal/common_device_type.py
> +    TEST_WITH_MIOPEN_SUGGEST_NHWC, NATIVE_DEVICES, skipIfTorchDynamo, TEST_WITH_MPS
Yes, I think that part of code got accidentally checked-in during rebase - I've removed it 👍

2022-09-27 21:54 UTC, malfet approved these changes

2022-09-27 21:55 UTC, kulinseth commented
@pytorchbot merge -g

2022-09-27 21:55 UTC, malfet commented
@pytorchbot merge

2022-09-28 00:44 UTC, malfet commented
@pytorchbot merge -g

2022-09-28 00:48 UTC, closed without merging