Fix the performance issue that the for-loop before ExternallCall
pytorch/pytorch pull request #86516
Opened 2022-10-08 01:33 UTC by EikanWang

Currently, NNC only parallelizes the loop statement of the graph outputs. The logic could bypass some loop statements that could be parallelized. Take an example as follows and suppose the output of `ExternallCall` is also the output of NNC fusion group. Current [parallel logic](https://github.com/pytorch/pytorch/pull/85056/files#diff-9a11174c26e4b57ab73e819520122bc314467c72962f3a5b79e7400ea3c4bbe5L781-L785) only tries to parallel the `ExternalCall` and bypass `stmt1` and `stmt2`.

```c++
stmt1: For:
stmt2:   For:
stmt3: ExternalCall
```
Pull Request resolved: https://github.com/pytorch/pytorch/pull/85056
Approved by: https://github.com/frank-wei, https://github.com/bertmaher

2022-10-12 18:47 UTC, atalman approved these changes
Approving, since internal facing changes only

2022-10-12 19:12 UTC, atalman requested changes
Please provide some details if this fix falls into Critical Issues:
[silent correctness](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+correctness+%28silent%29%22), [backwards compatibility](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+bc-breaking%22+), [crashes](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+crash%22+), [deadlocks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+deadlock%22+), (large) [memory leaks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+memory+usage%22+)

2022-10-13 07:21 UTC, EikanWang commented
@atalman , This PR is to fix the critical performance regression.

We planned three features for NNC: Channels Last, BF16, and Post-op fusion. Regarding the Post-op fusion, it is for channels-last only. And there is still some design open. Hence, it will be suspended. But some post-op fusion PRs([77157](https://github.com/pytorch/pytorch/pull/77157) and [84038](https://github.com/pytorch/pytorch/pull/84038)) have been landed. Since the implementation is on top of ExternalCall, it will trigger the NNC ExternalCall performance issue frequently compared to 1.12. Meanwhile, the post-op fusion is for channels last only. It impacts the NNC channels-last feature.

2022-10-14 00:05 UTC, EikanWang commented
@atalman , please let me know if you have any other comments. cc @bertmaher

2022-10-17 07:15 UTC, EikanWang commented
@atalman , may I know if you have any comments on this PR?

2022-10-17 08:45 UTC, EikanWang commented
@atalman , this is a regression. Should I label it as a regression?

2022-10-18 00:31 UTC, atalman commented
@EikanWang could you please explain the details of regression ?

2022-10-18 14:45 UTC, malfet approved these changes

2022-10-18 14:47 UTC, merged