torchdynamo: add convolution pointwise(unary) fusion kernel
pytorch/pytorch pull request #86581
Opened 2022-10-10 08:39 UTC by XiaobingSuper

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #86583
* #86582
* __->__ #86581

Support unary fusion of Convolution with:

- relu
- sigmoid
- tanh
- hardswish
- leaky_relu
- hardtanh
- gelu

2022-10-11 12:03 UTC, jgong5 requested changes

2022-10-11 12:03 UTC, jgong5 commented on test/test_mkldnn_fusion.py
>  class EltwiseFusionOp(NamedTuple):
`PointwisePostOp` is more accurate?

2022-10-12 04:36 UTC, XiaobingSuper commented on aten/src/ATen/native/mkldnn/Conv.cpp
> +    std::string attr,
Yes, changed.

2022-10-12 04:36 UTC, XiaobingSuper commented on aten/src/ATen/native/mkldnn/Conv.cpp
> +    c10::optional<std::string> algorithm) {
changed.

2022-10-12 04:36 UTC, XiaobingSuper commented on aten/src/ATen/native/mkldnn/Conv.cpp
> +    std::vector<c10::optional<at::Scalar>> scalars,
done.

2022-10-12 04:36 UTC, XiaobingSuper commented on test/test_mkldnn_fusion.py
>  class EltwiseFusionOp(NamedTuple):
Yes, I change it.

2022-10-12 04:44 UTC, jgong5 approved these changes

2022-10-12 09:21 UTC, jgong5 approved these changes

2022-10-13 02:21 UTC, EikanWang commented
@jansel , could you help review this PR for TorchInductor?

2022-10-13 12:08 UTC, EikanWang commented
@jansel , I noticed that you approved the other two PRs. May I know if you have any concerns about this PR?

2022-10-13 16:03 UTC, jansel approved these changes

2022-10-13 16:03 UTC, jansel commented
> @jansel , I noticed that you approved the other two PRs. May I know if you have any concerns about this PR?

Nope just missed it.  Sorry, too many notifications!

2022-10-13 23:58 UTC, EikanWang commented
@pytorchbot merge

2022-10-14 00:01 UTC, EikanWang commented
@XiaobingSuper , could you please rebase the PR and resolve the conflict?

2022-10-14 01:22 UTC, XiaobingSuper commented
@EikanWang , code rebased.

2022-10-15 01:49 UTC, EikanWang commented
@pytorchbot merge

2022-10-15 01:51 UTC, closed without merging