Add a warning in gradcheck if inputs precision < float64
pytorch/pytorch pull request #8663
Opened 2018-06-19 19:50 UTC by vishwakftw

Fixes #8659 . This PR adds a warning to alert users about the possibility of a failure in the `gradcheck` and `gradgradcheck` functions.

Why warning? Users might alter the values of `eps`, `atol` and/or `rtol` to make their custom tests pass. Throwing errors in such scenarios could be bad.

2018-06-19 20:00 UTC, ssnl requested changes

2018-06-19 20:00 UTC, SsnL commented on torch/autograd/gradcheck.py
> +            'At least one of the inputs is of single precision. '
They could be half precision / integral types / not requiring grad. The check should be `if any((t.requires_grad and t.dtype != torch.float64) for t in tupled_inputs):`

2018-06-19 20:20 UTC, SsnL commented
Could you update the warning message too? Thanks!

2018-06-19 20:23 UTC, vishwakftw commented
Currently, this is the warning message:
```
'At least one of the inputs is of single precision. '
'The default values are designed for :attr:`input` of double precision. '
'This check will likely fail if :attr:`input` is of single precision. ')
```

I could change it to:
```
'At least one of the inputs is of single precision. This check will likely fail if the inputs are of single precision.'
```

2018-06-19 20:30 UTC, SsnL commented
What I meant was that the tensor could be half, etc. I think it might be better to read `At least one of the input tensor that requires gradient is not double precision floating type, ....`.

2018-06-19 20:37 UTC, ssnl approved these changes
Thanks!

2018-06-20 16:23 UTC, ezyang approved these changes
g

2018-06-20 16:23 UTC, merged