Add multi-grad hooks (#86260)
pytorch/pytorch pull request #86672
Opened 2022-10-11 04:58 UTC by soulitzer

Pull Request resolved: https://github.com/pytorch/pytorch/pull/86260
Approved by: https://github.com/albanD

This PR is mainly to add a new feature, but it also makes a crucial bug fix to a new feature 
- new feature: multi-hooks are introduced
- bug fix: `torch._C._will_engine_execute_node` in the release branch produces incorrect returns that the tensor will be executed by backward when the tensor is directly passed as input to .grad, but this tensor is not part of the backward graph 

Alternatively I can create a new PR for the release branch with only the bug-fix changes.

2022-10-12 19:11 UTC, atalman requested changes
@soulitzer  Since this is cherry-pick could you please provide only bugfix change rather then including feature.

2022-10-12 21:27 UTC, albanD reviewed
The bugfix looks good

2022-10-13 11:41 UTC, atalman approved these changes

2022-10-13 13:48 UTC, malfet requested changes
Please add test to the cherry-pick as well

2022-10-13 13:57 UTC, soulitzer commented
Updated to add the test!

2022-10-13 13:58 UTC, soulitzer commented on test/test_autograd.py
> +        torch.autograd.backward(out, inputs=(a, b2), retain_graph=True)
b2 is not part of the graph, but is passed to backward as an input. When the hook is run, we validate that _will_engine_execute_node returns False.

2022-10-18 18:44 UTC, malfet approved these changes
Thank you for the explanation. It would be good to keep the same test on master and release/1.13, but this change is well contained.

2022-10-18 18:44 UTC, merged