update quantization doc: add onednn and x86 backend description
pytorch/pytorch pull request #86794
Opened 2022-10-12 14:24 UTC by XiaobingSuper

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2022-10-13 01:42 UTC, jgong5 commented
Since x86 is now the default qengine replacing fbgemm, can we only recommend x86 for server CPUs? We can leave a note that fbgemm is still available but not recommended.

2022-10-13 10:15 UTC, jgong5 requested changes

2022-10-13 10:15 UTC, jgong5 commented on docs/source/quantization.rst
> +* x86 CPUs with AVX2 support or higher (without AVX2 some operations have inefficient implementations), via `x86` to apply the optimization of `fbgemm <https://github.com/pytorch/FBGEMM>`_ and `onedn
```suggestion
* x86 CPUs with AVX2 support or higher (without AVX2 some operations have inefficient implementations), via `x86` optimized by `fbgemm <https://github.com/pytorch/FBGEMM>`_ and `onednn <https://github.com/oneapi-src/oneDNN>`_ (see the details at `RFC <https://github.com/pytorch/pytorch/issues/83888>`_)
```

2022-10-13 14:12 UTC, jgong5 approved these changes

2022-11-18 01:58 UTC, kit1980 commented
@pytorchbot rebase

2022-11-18 01:59 UTC, kit1980 approved these changes

2022-11-18 01:59 UTC, kit1980 commented
@XiaobingSuper feel free to merge when ready.

2022-12-01 02:23 UTC, XiaobingSuper commented
@kit1980 @jerryzh168, code is rebased.

2022-12-02 01:37 UTC, kit1980 approved these changes

2022-12-02 02:08 UTC, XiaobingSuper commented
@pytorchbot merge

2022-12-02 02:10 UTC, closed without merging