TorchDynamo: Add convolution binary fusion for cpu in inference mode
pytorch/pytorch pull request #87064
Opened 2022-10-17 06:54 UTC by XiaobingSuper

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2022-10-24 07:34 UTC, jgong5 requested changes

2022-10-24 07:34 UTC, jgong5 commented on torch/_inductor/overrides.py
> +        )
Simpler to just return the value of this boolean expression instead of an extra "if-else" here?

2022-10-24 10:24 UTC, jgong5 approved these changes

2022-10-28 03:52 UTC, XiaobingSuper commented
@jansel , could you help review this PR? Thanks!

2022-11-02 04:42 UTC, XiaobingSuper commented
@jansel

2022-11-03 16:13 UTC, jansel approved these changes

2022-11-04 01:08 UTC, XiaobingSuper commented
@pytorchbot merge

2022-11-04 01:10 UTC, closed without merging