fsdp lazy_init typo
pytorch/pytorch pull request #87184
Opened 2022-10-18 08:12 UTC by chiaolun

Minor typo, changed with -> without

2022-10-18 12:56 UTC, awgu approved these changes
Thanks for catching this! This was my typo 😄

2022-10-18 13:30 UTC, awgu requested changes

2022-10-19 00:32 UTC, chiaolun commented on torch/distributed/fsdp/fully_sharded_data_parallel.py
> +            # Allow the FSDP constructor to run even without CUDA but check
got it

2022-10-19 01:16 UTC, awgu approved these changes

2022-10-19 01:16 UTC, awgu commented
@pytorchbot merge

2022-10-19 01:55 UTC, awgu commented
@pytorchbot rebase -s

2022-10-19 02:13 UTC, awgu commented
@pytorchbot merge

2022-10-19 05:11 UTC, closed without merging