Minor fixes for finding CUDNN
pytorch/pytorch pull request #8743
Opened 2018-06-21 13:43 UTC by peterjc123

2018-06-21 14:13 UTC, soumith commented on tools/setup_helpers/cudnn.py
> +        lib_paths.append(os.path.join(CUDA_HOME, suffix))
the ordering in lib_paths matters. You've appended `CUDA_HOME + suffix` entries to `lib_paths`, which means they will be considered after system paths like `/usr/lib/x86_64-linux-gnu/`. What you need to do is insert them right after os.getenv('CUDNN_LIB_DIR')

2018-06-21 14:13 UTC, soumith commented on tools/setup_helpers/cudnn.py
> +LIB_SUFFIXS = ['lib', 'lib64', 'lib/x64']
it's `SUFFIXES`, not `SUFFIXS`

2018-06-21 14:13 UTC, soumith requested changes
see inline comments

2018-06-21 14:34 UTC, peterjc123 commented on tools/setup_helpers/cudnn.py
> +LIB_SUFFIXS = ['lib', 'lib64', 'lib/x64']
Yes, will fix!

2018-06-21 15:06 UTC, soumith approved these changes

2018-06-21 15:06 UTC, soumith commented
lint needs to be fixed

2018-06-21 15:17 UTC, peterjc123 commented
@pytorchbot retest this please

2018-06-22 03:45 UTC, peterjc123 commented
@pytorchbot retest this please

2018-06-22 04:31 UTC, peterjc123 commented
The CI failure seems to have nothing to do with this PR.

2018-06-22 04:35 UTC, soumith commented
let's wait for the pytorch CI to pass

2018-06-22 05:00 UTC, peterjc123 commented
@soumith The pytorch CI tests all passed.

2018-06-25 01:40 UTC, peterjc123 commented
@pytorchbot retest this please

2018-06-25 01:42 UTC, soumith approved these changes

2018-06-25 01:42 UTC, merged