Deprecated torch.nn.functional.tanh()
pytorch/pytorch pull request #8748
Opened 2018-06-21 16:48 UTC by weiyangfb

## summary
1. fixes #6245
2. removed tanh() from functional.py and rnn.py

2018-06-21 17:29 UTC, soumith requested changes

2018-06-21 17:29 UTC, soumith commented on torch/distributions/utils.py
> +        return torch.nn.Sigmoid(logits)
isn't this `torch.sigmoid(logits)`

2018-06-21 17:29 UTC, soumith commented on torch/distributions/transforms.py
> +        z = torch.nn.Sigmoid(x - offset.log())
isn't this `torch.sigmoid(logits)`

2018-06-21 17:29 UTC, soumith commented on torch/distributions/transforms.py
> +        z = torch.nn.Sigmoid(x - offset.log())
isn't this `torch.sigmoid(logits)`

2018-06-21 17:29 UTC, soumith commented on torch/distributions/transforms.py
> +        return torch.nn.Sigmoid(x)
isn't this `torch.sigmoid(logits)`

2018-06-21 17:29 UTC, soumith commented on test/test_jit.py
> +                return torch.nn.Sigmoid(self.fc4(h3))
isn't this `torch.sigmoid(logits)`

2018-06-21 17:29 UTC, soumith commented on test/test_jit.py
> +    outgate = torch.nn.Sigmoid(outgate)
isn't this `torch.sigmoid(logits)`

2018-06-21 17:29 UTC, soumith commented on test/test_jit.py
> +    ingate = torch.nn.Sigmoid(ingate)
isn't this `torch.sigmoid(logits)`

2018-06-21 17:29 UTC, soumith commented on test/test_jit.py
> +    outgate = torch.nn.Sigmoid(outgate)
isn't this `torch.sigmoid(logits)`

2018-06-21 17:32 UTC, soumith commented
what happens if user tries to do `torch.nn.functional.sigmoid(x)` now, is it an error or a deprecated warning? (it should be a deprecated warning)

2018-06-21 17:37 UTC, weiyangfb commented
@soumith ah, I see. Now it is an error, I will make a deprecated warning

2018-06-21 18:12 UTC, vishwakftw commented
Other functions in `torch.nn.functional` that could be deprecated:
1. `selu`
2. `rrelu`

Let me know what you think @soumith , I could open a PR for those.

2018-06-25 19:48 UTC, weiyangfb commented
@vishwakftw Yes I can deprecate `relu` and `rrelu`. But after that people can only use modules `nn.ReLU` and `nn.RReLU`. Should we do this? 

cc @soumith

2018-06-25 19:55 UTC, soumith commented
wait, why would we deprecate `relu` and `rrelu`? we dont have `torch.relu` and `torch.rrelu`

2018-06-25 20:03 UTC, weiyangfb commented
@soumith That's right. We will keep them for now then.

2018-06-25 20:03 UTC, weiyangfb commented
@pytorchbot retest this please

2018-06-25 20:03 UTC, vishwakftw commented
I thought we could deprecate `torch.nn.functional.rrelu` and `torch.nn.functional.selu`. Both are available as `torch.rrelu` and `torch.selu` (and their inplace versions).

2018-06-25 20:10 UTC, weiyangfb commented
@vishwakftw Ah, I see! So they are just not documented yet, I will add them to the docs. This way I think `functional.selu` and `functional.rrelu` can be safely deprecated then.

```
input = torch.randn(2)
torch.selu(input)
```
tensor([1.4261, 0.2250])

```
input = torch.randn(2)
torch.rrelu(input)
```
tensor([-0.0398, -0.1174])

2018-06-26 16:11 UTC, fmassa commented
So the goal now is to expose everything in the `torch` namespace?

2018-06-26 17:57 UTC, weiyangfb commented
After offline discussion, we decide to move tanh and sigmoid from nn.functional to torch since they are more of common scientific functions, and keep the others at nn.functional for now.

2018-06-27 22:28 UTC, weiyangfb commented
Failed Caffe2 CI tests look not related. Can I get a stamp on this?

2018-06-28 14:57 UTC, weiyangfb commented
@pytorchbot retest this please

2018-06-29 17:51 UTC, soumith approved these changes

2018-06-30 19:17 UTC, vadimkantorov commented
`relu` also already is available on `torch` namespace: ` torch.relu(torch.Tensor([1]))` works

2018-07-01 13:49 UTC, soumith commented
@vadimkantorov we probably will remove that, please dont rely on undocumented features. the `nn` namespace is really the place for neural-net specifi functions

2018-07-01 13:59 UTC, vadimkantorov commented
@soumith ok :) I was hesitating if it was a deficit of documentation or a blunder of auto bindings :)

2018-07-01 14:00 UTC, soumith commented
the latter :)

2018-07-02 22:55 UTC, closed without merging