torchdynamo support modules() for nn_module
pytorch/pytorch pull request #88023
Opened 2022-10-28 23:34 UTC by ydwu4

Differential Revision: D40820879

2022-10-31 21:24 UTC, tugsbayasgalan approved these changes

2022-10-31 21:29 UTC, voznesenskym requested changes
Can you add compile counter to the test? Also, please add a PR description.

2022-10-31 21:53 UTC, jansel approved these changes

2022-10-31 22:33 UTC, ydwu4 commented
> Can you add compile counter to the test? Also, please add a PR description.

Sure! I've updated the pr accordingly.

2022-10-31 23:52 UTC, voznesenskym approved these changes

2022-10-31 23:52 UTC, voznesenskym commented
> > Can you add compile counter to the test? Also, please add a PR description.
> 
> Sure! I've updated the pr accordingly.

Beautiful, ty!

2022-11-01 17:08 UTC, ydwu4 commented
@pytorchbot merge

2022-11-02 22:33 UTC, mehtanirav commented
@pytorchbot revert -m "[Internal breakages](https://www.internalfb.com/intern/sandcastle/job/13510799692855066/insights)" -c ghfirst

2022-11-08 18:20 UTC, ydwu4 commented
@pytorchbot merge

2022-11-08 18:36 UTC, ydwu4 commented
@pytorchbot revert -m "[Internal breakages] https://www.internalfb.com/intern/sandcastle/job/9007200067589062/" -c ghfirst

2022-11-08 20:53 UTC, closed without merging