Add test c10d ucc tests
pytorch/pytorch pull request #88110
Opened 2022-10-31 18:28 UTC by Fuzzkatt

Creates the equivalent c10d test for ucc for https://github.com/pytorch/pytorch/blob/master/test/distributed/test_c10d_gloo.py and https://github.com/pytorch/pytorch/blob/master/test/distributed/test_c10d_nccl.py. Uses test_c10d_gloo.py as the reference and adds all the common ops. More detailed comparison of available ops here: https://docs.google.com/document/d/1yPsa_X9EiEiqo-j2Yn7ierhccBtEjwoqC-B7-amI0MI/edit?usp=sharing

2022-11-21 19:42 UTC, Fuzzkatt commented
Ready for review

2022-11-21 20:12 UTC, kwen2501 commented
Cc @vtlam @kingchc . Can you please help take a look? Thanks!

2023-04-01 02:11 UTC, zasdfgbnm reviewed
Finished reading. Lots of my comments are about adding new tests, considering the size of this PR, I these comments are better resolved in followup PRs. For this PR, I also have a few comments, please fix them here.

2023-04-03 20:55 UTC, Fuzzkatt commented on test/distributed/test_c10d_ucc.py
> +        super(ProcessGroupUCCTest, self).tearDown()
fixed

2023-04-03 20:55 UTC, Fuzzkatt commented on test/distributed/test_c10d_ucc.py
> +            self.assertEqualIgnoreType(torch.tensor([i]), output[0])
fixed

2023-04-03 20:55 UTC, Fuzzkatt commented on test/distributed/test_c10d_ucc.py
> +                    self.assertEqualIgnoreType(output, result[0])
fixed

2023-04-03 20:55 UTC, Fuzzkatt commented on test/distributed/test_c10d_ucc.py
> +            self.assertEqualIgnoreType(expected, result[0])
fixed

2023-04-03 20:55 UTC, Fuzzkatt commented on test/distributed/test_c10d_ucc.py
> +    def test_nested_comm_tensor_wrapping(self):
fixed, will add

2023-04-03 20:56 UTC, Fuzzkatt commented on test/distributed/test_c10d_ucc.py
> +
Yes, I'll remove the skipped tests for now

2023-04-03 20:56 UTC, Fuzzkatt commented on test/distributed/test_c10d_ucc.py
> +def simple_coalesced_reduce_tests(rank, world_size):
no, removed

2023-04-03 20:56 UTC, Fuzzkatt commented on test/distributed/test_c10d_ucc.py
> +def simple_multi_input_reduce_tests(rank, world_size):
no, removed

2023-04-03 20:56 UTC, Fuzzkatt commented on test/distributed/test_c10d_ucc.py
> +        super(ProcessGroupUCCTest, self).setUp()
fixed

2023-04-03 20:56 UTC, Fuzzkatt commented on test/distributed/test_c10d_ucc.py
> +        self._test_allgather_work_wait(
Good catch, fixed.

2023-04-03 20:58 UTC, zasdfgbnm approved these changes
LGTM

2023-04-03 21:20 UTC, kit1980 commented on test/distributed/test_c10d_ucc.py
> +                    self.assertEqualIgnoreType(output, result[0])
I see there are more of these, line 167, for example.
All existing #38095-related issues were fixed some time ago and the issue was closed, please don't re-introduce.

2023-04-03 21:20 UTC, kit1980 requested changes
All existing https://github.com/pytorch/pytorch/issues/38095-related issues were fixed some time ago and the issue was closed, please don't re-introduce.

2023-04-03 21:34 UTC, Fuzzkatt commented
> All existing #38095 issues were fixed some time ago and the issue was closed, please don't re-introduce.

Sorry about that, the comments referencing #38095 were outdated (this PR is a couple months old) and I removed them. There are no actual issues relating to #38905.

2023-04-05 16:27 UTC, zasdfgbnm commented
@kit1980 Do you still have something to request change or are you OK with the current status?

2023-04-05 17:18 UTC, kit1980 approved these changes

2023-04-05 20:20 UTC, kwen2501 approved these changes

2023-04-05 21:47 UTC, Fuzzkatt commented
@pytorchbot merge

2023-04-06 23:19 UTC, malfet approved these changes

2023-04-06 23:49 UTC, Fuzzkatt commented
@pytorchbot merge

2023-04-06 23:51 UTC, closed without merging