Uses cuda pypi nccl
pytorch/pytorch pull request #88125
Opened 2022-10-31 19:41 UTC by syed-ahmed

2022-11-08 17:45 UTC, atalman commented on .github/workflows/generated-linux-binary-manywheel-nightly.yml
> +  CU117_DEPENDENCIES: "nvidia-cuda-runtime-cu11==11.7.99;\
Was this file manually edited ? This is generated file, should not be edited manually

2022-11-08 17:45 UTC, atalman commented on .github/workflows/generated-linux-binary-manywheel-nightly.yml
> +  CU117_DEPENDENCIES: "nvidia-cuda-runtime-cu11==11.7.99;\
Also please keep the previous logic using PYTORCH_EXTRA_INSTALL_REQUIREMENTS

2022-11-08 17:52 UTC, atalman commented on .github/scripts/generate_binary_build_matrix.py
>                          "build_name":
Should we also add libnvrtc here ? as in this PR https://github.com/pytorch/builder/pull/1183 
And remove libnvrtc from patch ?

2022-11-08 17:52 UTC, atalman requested changes
Thank you Syed! Please see comments below.

2022-11-28 20:03 UTC, atalman commented
@pytorchbot -help

2022-11-28 20:03 UTC, atalman commented
@pytorchbot --help

2022-12-02 19:41 UTC, syed-ahmed commented
Merged this PR here: https://github.com/pytorch/pytorch/pull/89944. Closing.

2022-12-02 19:41 UTC, closed without merging