pprint dynamo optimized model
pytorch/pytorch pull request #88164
Opened 2022-11-01 01:18 UTC by msaroufim

Fixes #ISSUE_NUMBER

2022-11-02 00:25 UTC, Chillee commented
Can you do a more exhaustive comparison of this API? For example, can you verify that we don't increase memory usage by copying the module? And that torchdynamo actually works? 

Also, cc: @albanD on whether shallow copy of the module is going to have any unexpected effects.

2022-11-02 05:20 UTC, anijain2305 commented on torch/_dynamo/eval_frame.py
> -            new_mod._torchdynamo_orig_callable = mod
You forgot to keep this line of code. This is useful for nested torchdynamo optimize calls.

2022-11-02 16:18 UTC, msaroufim commented on torch/_dynamo/eval_frame.py
> +            new_mod = copy.copy(fn)
We could do that but i was wondering/hoping there'd be other benefits to making an optimized model an nn.module outside of just printing

2022-11-02 18:50 UTC, msaroufim commented on torch/_dynamo/eval_frame.py
> +            any_arg_is_proxy = any(
This was a contribution by `lintrunner -a torch/_dynamo/eval_frame.py`

2022-11-02 20:21 UTC, Chillee commented on torch/_dynamo/eval_frame.py
> +            new_mod = copy.copy(fn)
@msaroufim I don't think `__repr__` is enough. A lot of the other things folks want to do with modules are not handled by monkeypatching the `__repr__`.

@albanD do you have any concrete objections to doing a shallow copy?

2022-11-02 20:32 UTC, albanD reviewed
You might want a small smoke test to make sure it runs?

2022-11-02 20:32 UTC, albanD commented on torch/_dynamo/eval_frame.py
> +                    return self.__repr__(*args, **kwargs)
Isn't that infinite recursing? you meant `mod.__repr__()` ?

2022-11-02 21:42 UTC, albanD approved these changes
SGTM !

2022-11-02 21:43 UTC, msaroufim commented
@pytorchbot merge

2022-11-02 21:46 UTC, Chillee commented
No, I disagree with merging this.

2022-11-02 21:46 UTC, Chillee requested changes
@albanD what's the issue with the shallow copy?

2022-11-29 21:58 UTC, msaroufim commented
Closing since it seems like we instead have went for a module wrapper

2022-11-29 21:58 UTC, closed without merging