[inductor] Add lowering for as_strided_scatter
pytorch/pytorch pull request #88379
Opened 2022-11-03 00:11 UTC by peterbell10

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Ref pytorch/torchdynamo#327

The use of as_strided does require in-memory manipulations, however this
 lowering allows those memory ops to be fused with any preceding calculations.
e.g.

```
def f(a, b):
    return torch.as_strided_scatter(
        a * 8 + 10,
        b * 2 - 4,
        size=(a.numel() // 2,),
        stride=(2,))
```

Before this compiles to two kernels and a call to `aten.as_strided_scatter` and
with this PR it compiles to just two kernels and no additional operator calls.

In theory I think this could be a decomposition, but in practice I saw the
`output_view.copy_(src)` being optimized out in some cases when this was
implemented as a decomposition.

2022-11-03 10:37 UTC, lezcano commented
Note that it'd still be valuable to implement this as a decomposition for other backends to use.

2022-11-03 15:43 UTC, jansel approved these changes

2022-11-03 15:43 UTC, jansel requested changes
Actually, can you add a test for this?

2022-11-03 23:47 UTC, peterbell10 commented
@jansel PTAL, I've added a test.

2022-11-06 17:08 UTC, jansel approved these changes

2022-11-06 22:25 UTC, peterbell10 commented
@pytorchbot merge

2022-11-07 00:59 UTC, closed without merging

2022-11-07 18:41 UTC, ngimel commented
```
output_view.copy_(src)
```
being optimized away is worrying, @peterbell10 do you have a repro? cc @bdhirsh

2022-11-07 21:47 UTC, peterbell10 commented
On the next PR in the stack, if I enable the decomposition in `torch/_inductor/decomposition.py` then this reproducer fails for me:
```python
import torch
from torch.fx.experimental.proxy_tensor import make_fx
from torch._inductor.compile_fx import compile_fx

x = torch.rand((1,), device="cuda", requires_grad=True)
y = torch.rand((1,), device="cuda", requires_grad=True)
def f(a, b):
    return torch.as_strided_scatter(
        a,
        b,
        size=(1,),
        stride=(1,)),

torch._inductor.config.debug = True
args = [x, y]

decomposed = make_fx(f, tracing_mode="fake")(*args)
compiled_decomposed = compile_fx(decomposed, args)
expect = f(*args)
actual = compiled_decomposed(*args)
print(f'Expected {expect}\nActual: {actual}')
```

The `requires_grad=True` on the input is important.

2022-11-08 20:22 UTC, bdhirsh commented
Thanks for the repro @peterbell10 

I'm going to add asserts in aot autograd soon to check that there are no mutable ops in the graph right before we run DCE, which is what causes problems.

For the actual fix, I think what we should probably do is use functionalization to "functionalize" every decomposition right before we run it, during proxy tensor tracing. That way we don't need to worry about / establish invariants on whether decomps are allowed to call mutations. I'm gonna try to POC this soon.

There's probably some question as to whether or not proxy tensor tracing should functionalize decomps by default or not. Maybe we need another feature flag, in `make_fx`? (lol)