TorchDynamo: weight prepack for onednn convolution external call
pytorch/pytorch pull request #88988
Opened 2022-11-14 12:47 UTC by XiaobingSuper

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2022-11-17 09:45 UTC, jgong5 requested changes

2022-11-17 09:45 UTC, jgong5 commented on torch/_inductor/ir.py
> +        stride_order = [0] + list(reversed(range(1, 2 + 1)))
nit: is `2` the kernel size?

2022-11-17 09:45 UTC, jgong5 commented on torch/_inductor/overrides.py
> +def fused_binary_unary_eval(conv_binary: nn.Module, unary: nn.Module, input_size: list):
nit: `fused_conv_binary_unary_eval` instead?

2022-11-17 12:44 UTC, XiaobingSuper commented on aten/src/ATen/native/mkldnn/Utils.cpp
> +  }
Yes, we can add dtype check.

2022-11-17 13:52 UTC, XiaobingSuper commented on torch/_inductor/ir.py
> +        stride_order = [0] + list(reversed(range(1, 2 + 1)))
Yes, using stride's size now.

2022-11-17 13:53 UTC, XiaobingSuper commented on torch/_inductor/overrides.py
> +def fused_binary_unary_eval(conv_binary: nn.Module, unary: nn.Module, input_size: list):
Chaneged.

2022-11-21 05:30 UTC, jgong5 approved these changes

2022-11-23 12:45 UTC, desertfire commented
> For better performance, we always use channels_last for CPU convolution path. because we test that the channels_last path can get a better performance than block input path

Is this conclusion always true? Does the better performance depend on conditions like input shapes?

2022-11-23 12:58 UTC, desertfire commented on torch/_inductor/ir.py
> +        ouput_stride = make_channels_last_strides_for(output_size)
Nit: typo, `output_stride`

2022-11-23 14:59 UTC, EikanWang commented
> Does the better performance depend on conditions like input sha

Compared with PyTorch's current solution, it might not be true for some particular shapes but it should always be true from the E2E perspective. Channels-first Conv uses blocked format for computation and converts blocked format tensor to channels-first.

2022-11-23 15:18 UTC, jgong5 commented
> > Does the better performance depend on conditions like input sha
> 
> Compared with PyTorch's current solution, it might not be true for some particular shapes but it should always be true from the E2E perspective. Channels-first Conv uses blocked format for computation and converts blocked format tensor to channels-first.

Right. For individual convs, there are some special shapes for which THNN implementation is used (https://github.com/jgong5/pytorch/blob/407d93bd7911f54460831a68cfec9fe5a09c733c/aten/src/ATen/native/Convolution.cpp#L509) that works directly with channels-first format and is faster than oneDNN conv with channel-first (oneDNN requires an extra layout conversion to blocked). But as @EikanWang pointed out, channels last benefits end-to-end workload in general since 1) little chance for all those conv shapes to be special shapes; 2) the format can propagate through the model without conversions in the middle of the model.

2022-11-23 15:54 UTC, jansel approved these changes

2022-11-24 00:10 UTC, XiaobingSuper commented on torch/_inductor/ir.py
> +        ouput_stride = make_channels_last_strides_for(output_size)
Yes, changed.

2022-11-25 01:14 UTC, XiaobingSuper commented
@pytorchbot merge -f "unrelated CI failures"

2022-11-25 01:16 UTC, closed without merging