Check key should be string in nn.Module.add_module, parameter and buffer
pytorch/pytorch pull request #8905
Opened 2018-06-26 18:47 UTC by karandwivedi42

cc @SsnL

2018-06-26 19:26 UTC, ssnl requested changes

2018-06-26 21:59 UTC, ssnl approved these changes
lgtm

2018-06-27 01:07 UTC, SsnL commented
@pytorchbot retest this please

2018-06-27 15:09 UTC, SsnL commented on torch/nn/modules/module.py
> +        if name is None or not isinstance(name, torch._six.string_classes):
This `is None` check seems unnecessary. The `isinstance` will catch it anyways. Can you remove it?

2018-06-27 17:28 UTC, SsnL commented
Thanks! Can you pull & rebase to upstream master please? We made some changes to the system so current PRs needs to be rebased to master to land. (Wont be a problem for future PRs). Sorry about it!

2018-06-27 19:35 UTC, karandwivedi42 commented
Reopened in https://github.com/pytorch/pytorch/pull/8960

2018-06-27 19:35 UTC, closed without merging

2018-06-27 19:52 UTC, SsnL commented
lol I just went to your branch and fixed the history. I guess that also works :)