Add factory functions to python frontend
pytorch/pytorch pull request #89230
Opened 2022-11-17 18:25 UTC by rdspring1

- Add `full` nvprim to support factory functions because the full reference uses `empty` and `fill` while we have a full factory function.
- Change `full_like` reference to call `full` to avoid defining another nvprim.
- Enable support for new_zeros to enable `cudnn_batch_norm` decomposition.

2022-11-18 08:28 UTC, mruberry commented
Let's add a test, too! Also added @kevinstephano to review

2022-11-30 17:15 UTC, kevinstephano requested changes

2022-11-30 17:15 UTC, kevinstephano commented on torch/csrc/jit/codegen/cuda/python_frontend/python_bindings.cpp
> +          py::return_value_policy::reference)
`full` should be put under the `ops` with other operations like `view` and `squeeze`.

2022-12-05 19:44 UTC, kevinstephano approved these changes
LGTM.

2022-12-05 21:02 UTC, rdspring1 commented
@pytorchbot merge

2022-12-05 21:48 UTC, rdspring1 commented
@mruberry I added tests to test/test_prims.py, so the PR is ready.

2022-12-05 22:01 UTC, mruberry approved these changes
Stamped!

2022-12-05 22:01 UTC, mruberry commented
@pytorchbot merge -g

2022-12-05 22:05 UTC, rdspring1 commented
@pytorchbot merge -g

2022-12-06 07:09 UTC, rdspring1 commented
@pytorchbot merge -g

2022-12-06 07:16 UTC, closed without merging