[Inductor] Add option to build without OpenMP
pytorch/pytorch pull request #89262
Opened 2022-11-18 03:06 UTC by malfet

Move compiler standard/optimization flags to `config.cpp` class
Add option to disable OpenMP integration if `config.cpp.threads` is set
to 1

This unblocks testing Inductor on M1 machines by making following tweaks
to config:
```
import torch._inductor.config as config
config.cpp.threads=1
config.cpp.cxx_opt_flags = config.cpp.cxx_opt_flags.replace("-march=native","")
config.cpp.cxx=("clang++")
```

On MacOS, compiler does not support `-fopenmp` by default

Fixes #ISSUE_NUMBER

2022-11-18 03:17 UTC, voznesenskym commented
`#pragma omp` should be safe to no-op... but If you had a python level equivalent of "ifdef _OPENMP" you could avoid generating this code altogether. This is beneficial because the

2022-11-18 16:40 UTC, malfet commented
Come to think of it probably make sense to split it into several PRs: one that moves install step only after fails to find all compilers, another that moves the flags to config (and adds flags for omp lib, as even for x86 pythorch is packaged by default with libiomp rather than with gomp)

2022-11-18 20:41 UTC, jansel approved these changes

2023-01-18 07:23 UTC, jgong5 requested changes

2023-01-18 07:23 UTC, jgong5 commented on torch/_inductor/codecache.py
> +    if config.cpp.threads != 1:
```suggestion
    if config.cpp.threads != 1 or config.dynamic_threads:
```

2023-01-18 07:23 UTC, jgong5 commented on torch/_inductor/codecache.py
> +    omp_flags = "-fopenmp" if config.cpp.threads != 1 else ""
```suggestion
    omp_flags = "-fopenmp" if config.cpp.threads != 1 or config.dynamic_threads else ""
```

2023-02-17 07:33 UTC, closed without merging