[inductor] generate nan in the cpp backend
pytorch/pytorch pull request #89289
Opened 2022-11-18 16:20 UTC by desertfire

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #89289

Summary: Fixes https://github.com/pytorch/torchdynamo/issues/1797

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10

2022-11-18 17:29 UTC, ngimel approved these changes

2022-11-18 20:43 UTC, jansel approved these changes

2022-11-18 21:37 UTC, desertfire commented
@pytorchbot merge

2022-11-19 02:22 UTC, jgong5 requested changes

2022-11-19 02:22 UTC, jgong5 commented on torch/_inductor/codegen/cpp.py
> +            return f"std::numeric_limits<{DTYPE_TO_CPP[dtype]}>::quiet_NaN()"
```suggestion
            quote = f"std::numeric_limits<{DTYPE_TO_CPP[dtype]}>::quiet_NaN()"
```
Please add the case to cover it too. Code sequence like below can trigger this vec path:
```python
    a = torch.tensor(float("nan"))
    b = torch.empty([100])
    b.fill_(a)
```

2022-11-22 07:06 UTC, jgong5 approved these changes

2022-11-22 15:51 UTC, desertfire commented
@pytorchbot merge

2022-11-22 15:54 UTC, closed without merging