[Dynamo] Fix several bugs & code refactor in RangeVariable
pytorch/pytorch pull request #89322
Opened 2022-11-18 23:21 UTC by yanboliang

Fix bug in 7k github models: https://github.com/jansel/pytorch-jit-paritybench/blob/master/generated/test_clovaai_stargan_v2.py
```
E       TypeError: 'list' object cannot be interpreted as an integer
E       
E       from user code:
E          File "/scratch/ybliang/work/repos/pytorch-jit-paritybench/generated/test_clovaai_stargan_v2.py", line 335, in forward
E           idx = torch.LongTensor(range(y.size(0)))
```

2022-11-18 23:32 UTC, yanboliang commented on torch/_dynamo/variables/lists.py
> +        super().__init__([start, stop, step], **kwargs)
```range``` is similar to ```slice```, we only need to store ```[start, stop, step]``` in ```self.items```. Moved the unpack logics to ```unpack_var_sequence```. This refactor fixed the reported bug and made API more concise/consistent.

2022-11-18 23:32 UTC, yanboliang commented on test/dynamo/test_functions.py
> +
There are ```test_restore_range``` and ```test_restore_range_iter``` in ```test_subgraphs.py``` used to test ```range``` works well after graph break, so only add these two to cover this bug fix.

2022-11-20 03:30 UTC, jansel requested changes

2022-11-20 03:30 UTC, jansel commented on torch/_dynamo/variables/lists.py
> +        codegen.append_output(codegen.create_load_global("range", add=True))
`range` could be shadowed by a user defined global, we should load this via one of the helpers.

2022-11-23 15:59 UTC, jansel approved these changes

2022-11-23 19:42 UTC, yanboliang commented
@pytorchbot merge

2022-11-23 19:44 UTC, closed without merging