[C++ API] Create nn::Module::is
pytorch/pytorch pull request #8970
Opened 2018-06-27 22:57 UTC by goldsborough

When initializing weights for my C++ model, I had to write

```cpp
void initialize_weights(nn::Module& module) {
  if (module.name().find("Conv2d") != std::string::npos) {
    module.parameters()["weight"].data().normal_(0.0, 0.02);
  } else if (module.name().find("BatchNorm") != std::string::npos) {
    auto parameters = module.parameters();
    parameters["weight"].data().normal_(1.0, 0.02);
    parameters["bias"].data().fill_(0);
  }
}
```

The string-based module determination is not very nice, and not very C++-y. So I created `nn::Module::is<T>` which does a `dynamic_cast` inside. It also handles the `ModuleHolder` vs. `Module` distinction.

It now becomes

```cpp
if (module.is<nn::Conv2d>()) {
    module.parameters()["weight"].data().normal_(0.0, 0.02);
  } else if (module.is<nn::BatchNorm>()) {
    auto parameters = module.parameters();
    parameters["weight"].data().normal_(1.0, 0.02);
    parameters["bias"].data().fill_(0);
  }
```

@ebetica @ezyang @apaszke

2018-06-28 03:50 UTC, ezyang commented
If you're going to go through all the trouble of a dynamic cast, shouldn't we encourage you to refine the type?

2018-06-28 05:54 UTC, goldsborough commented
What does it mean to "refine the type"?

2018-06-28 12:58 UTC, ezyang commented
If you use `module.is<nn::Conv2d>()`, `module` is still a `Module` and not a `Conv2d`. So you still had to use string access to get at the parameters. Wouldn't you be able to use a method directly if you actually casted to `nn::Conv2d`?

2018-06-28 16:20 UTC, SsnL commented
How about this?
```cpp
if (nn::Conv2d* conv2d = dynamic_cast<nn::Conv2d*>(&module)) {
  conv2d->weight.data().normal_(0, 0.02);
  conv2d->bias.data().fill_(0);
}
```

2018-06-28 16:40 UTC, ezyang approved these changes

2018-06-28 16:41 UTC, ezyang requested changes
sorry, this is a test reject

2018-06-28 17:57 UTC, goldsborough commented
@SsnL that's what `nn::Module::is` basically does, but the thing is that `Conv2d` is actually not the `nn::Module` -- it holds a `nn::Conv2dImpl` underneath, which is the real module. That's what I'm trying to hide for the user.

@ezyang modules don't expose their variables (e.g. `Linear::weight_` is private). It's intended you use `.parameters()` to access the parameters.

2018-06-28 22:11 UTC, ezyang approved these changes

2018-06-28 22:11 UTC, ezyang commented
k

2018-06-28 23:11 UTC, closed without merging

2018-07-02 15:35 UTC, goldsborough commented
@apaszke I have indeed pondered about this and the promise of encapsulation really might not scale here. I think I’ll change it

2018-07-02 16:38 UTC, apaszke commented
Remember that a lot of use cases we're catering are for research, and encapsulation is one of the things that will make people resort to ugly hacks just to simplify accessing the state. It's not always going to be code that is supposed to be maintained for years.