Fix ATen Fallback for BUILD_CAFFE2=0 for ONNX-only ops (#88504)
pytorch/pytorch pull request #90104
Opened 2022-12-03 03:00 UTC by izaitsevfb

Cherry-pick for 1.13.1 release. Original PR: #88504

Original description below:
----
Follow-up for #87735

Once again, because BUILD_CAFFE2=0 is not tested for ONNX exporter, one scenario slipped through. A use case where the model can be exported without aten fallback when operator_export_type=ONNX_ATEN_FALLBACK and BUILD_CAFFE2=0

A new unit test has been added, but it won't prevent regressions if BUILD_CAFFE2=0 is not executed on CI again

Fixes #87313

Pull Request resolved: https://github.com/pytorch/pytorch/pull/88504 Approved by: https://github.com/justinchuby, https://github.com/BowenBao

(cherry picked from commit 5f0783bd6d27a0a239263b943d626c533b8b9a90)

Fixes #ISSUE_NUMBER

2022-12-05 15:41 UTC, thiagocrepaldi requested changes
FAILED test/onnx/test_pytorch_onnx_no_runtime.py - NameError: name 'common_quantization`

Other than that, looks good to me

2022-12-05 15:41 UTC, thiagocrepaldi commented on test/onnx/test_pytorch_onnx_no_runtime.py
> +    @common_quantization.skipIfNoFBGEMM
`common_quantization` was not imported in this file

2022-12-05 15:42 UTC, thiagocrepaldi commented on test/onnx/test_pytorch_onnx_no_runtime.py
>  from torch.testing._internal import common_utils
```suggestion
from torch.testing._internal import common_utils, common_quantization
```

2022-12-07 16:43 UTC, thiagocrepaldi commented
> cc @thiagocrepaldi the tests is still failing even after the changes

This is the culprit:

```bash
2022-12-06T23:11:36.7836729Z   File "/var/lib/jenkins/workspace/test/onnx/test_pytorch_onnx_no_runtime.py", line 961, in test_lower_graph_conv2d
2022-12-06T23:11:36.7837274Z     data_numpy = np.random.rand(1, 3, 6, 6).astype(np.float32)
2022-12-06T23:11:36.7837758Z NameError: name 'np' is not defined
```

2022-12-07 16:45 UTC, thiagocrepaldi requested changes

2022-12-07 16:45 UTC, thiagocrepaldi commented on test/onnx/test_pytorch_onnx_no_runtime.py
> +from torch.onnx import OperatorExportTypes, symbolic_helper, utils
```suggestion
import numpy as np
from torch.onnx import OperatorExportTypes, symbolic_helper, utils
```

Add the numpy import in the right position (Github editor does not let me suggest changes to lines that were not updated by the PR)

2022-12-07 18:46 UTC, atalman commented on test/onnx/test_pytorch_onnx_no_runtime.py
> +import numpy as np
```suggestion
```

2022-12-07 20:01 UTC, thiagocrepaldi approved these changes
All ONNX pipelines are now passing!

Thanks a lot for helping landing this!

2022-12-07 22:06 UTC, merged