[MPS] Add Inverse op.
pytorch/pytorch pull request #90428
Opened 2022-12-08 00:17 UTC by kulinseth

2022-12-12 22:35 UTC, DenisVieriu97 approved these changes
looks good

2022-12-12 22:46 UTC, DenisVieriu97 reviewed
The build still seems to be failing due to missing selector for `inverseOfTensor`

2022-12-12 22:48 UTC, DenisVieriu97 requested changes

2022-12-12 22:48 UTC, DenisVieriu97 commented on aten/src/ATen/native/mps/operations/Inverse.mm
> +
I think we should import MPSGraphVenturaOps.h here. I'll quickly try locally to check if the build is gone
```suggestion
aten/src/ATen/native/mps/MPSGraphVenturaOps.h
```

2022-12-16 18:09 UTC, DenisVieriu97 approved these changes

2022-12-16 18:09 UTC, DenisVieriu97 commented
@pytorchbot rebase

2022-12-19 20:44 UTC, malfet commented
@pytorchbot rebase

2022-12-19 21:56 UTC, malfet approved these changes

2022-12-19 21:56 UTC, malfet commented
@pytorchbot merge -f "MPS tests are green"

2022-12-19 22:00 UTC, closed without merging