Various fix
pytorch/pytorch pull request #90651
Opened 2022-12-11 09:20 UTC by cyyever

Fixes #ISSUE_NUMBER

2022-12-11 14:59 UTC, Skylion007 commented on c10/util/SmallBuffer.h
> +    size_ = rhs.size_;
```suggestion
  SmallBuffer(SmallBuffer&& rhs) : size_{rhs.size} {
```
The above is slightly more efficient / readable.

2022-12-30 20:04 UTC, Skylion007 commented on c10/util/SmallBuffer.h
> +        storage_[i] = rhs.storage_[i];
```suggestion
        storage_[i] = std::move(rhs.storage_[i]);
```
This will allow it to work if T is not copyable.

2022-12-30 20:06 UTC, Skylion007 commented on c10/util/SmallBuffer.h
> +  SmallBuffer(SmallBuffer&& rhs) : size_{rhs.size_} {
```suggestion
  SmallBuffer(SmallBuffer&& rhs) noexcept : size_{rhs.size_} {
```

2023-01-14 15:19 UTC, cyyever commented
cc @Skylion007  @zou3519  The tests all pass.

2023-01-14 21:37 UTC, Skylion007 commented on c10/util/SmallBuffer.h
>    T storage_[N];
One minor nit while we are touching this file, can change this to an std::array?

2023-01-14 21:38 UTC, Skylion007 commented on c10/util/SmallBuffer.h
> +      for (size_t i = 0; i < N; i++) {
If we change storage to an std::array, this loop is unnecessary.

2023-01-14 21:39 UTC, Skylion007 requested changes
A lot of the code in the custom move ctor can be simplfied by just converting the underlying C_array to an std::array. Any reason we aren't doing that?

2023-01-14 21:42 UTC, Skylion007 approved these changes
I guess on 2nd thought that would require a larger refactor. This is still better than what was there before.

2023-01-15 03:44 UTC, cyyever commented
> I guess on 2nd thought that would require a larger refactor. This is still better than what was there before.

We can try to use std::array, but on a latter PR

2023-01-15 03:45 UTC, cyyever commented
@pytorchbot merge

2023-01-15 09:09 UTC, cyyever commented
@pytorchbot merge

2023-01-15 09:14 UTC, cyyever commented
@pytorchbot merge

2023-01-16 07:21 UTC, cyyever commented
@pytorchbot  merge

2023-01-21 06:25 UTC, cyyever commented
@pytorchbot merge

2023-01-21 06:26 UTC, closed without merging