quantization qconfig: set per_channel quant as default for QNNPACK
pytorch/pytorch pull request #90782
Opened 2022-12-13 19:25 UTC by isdanni

Summary:
The current default `qconfig` for qnnpack is per-tensor quantization. Since per channel quantization has been supported on qnnpack for a while, setting per channel quant as default qconfig.

**Note**: per channel is for weights only.

Test Plan: contbuild & OSS CI, see

Differential Revision: D42005831

2022-12-13 20:03 UTC, vkuzo requested changes
thanks for doing this!  This is a very nice improvement.

Can we add a version 2 to `get_default_qat_config`, make version 2 the default and keep behavior of versions 0 and 1 as is?  This would enable customers to easily use the old settings if needed.

Can we also add this to `get_default_qconfig`, with a new version?

2023-01-11 18:42 UTC, digantdesai approved these changes
LGTM

2023-03-25 14:32 UTC, vkuzo commented
do we plan to make the new behavior default?

2023-03-28 18:24 UTC, vkuzo commented
how about:
1. change the default version to be your new one (this is BC breaking)
2. in the same diff, update Meta callsites to use the previous version (this makes the Meta callsites behave as before)

This will still be BC breaking for non-Meta, but I think it's a good change to make.  However, I'm not sure that we should add a new version without setting it as the default, as that wouldn't actually enable the functionality by default for anyone.

wdyt?

2023-03-28 21:42 UTC, isdanni commented
> how about:
> 
> 1. change the default version to be your new one (this is BC breaking)
> 2. in the same diff, update Meta callsites to use the previous version (this makes the Meta callsites behave as before)
> 
> This will still be BC breaking for non-Meta, but I think it's a good change to make. However, I'm not sure that we should add a new version without setting it as the default, as that wouldn't actually enable the functionality by default for anyone.
> 
> wdyt?

sounds good.  I will make changes accordingly :)

2023-04-04 03:08 UTC, closed without merging