fix the matcher for graph with unused placeholder
pytorch/pytorch pull request #90792
Opened 2022-12-13 20:56 UTC by cccclai

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Differential Revision: [D42011594](https://our.internmc.facebook.com/intern/diff/D42011594/)

2022-12-14 00:17 UTC, mergennachin commented on test/fx/test_pass_infra.py
> +            graph_module.graph, graph_module.graph
Can you add more test cases? This one is only comparing with itself.

2022-12-14 00:19 UTC, mergennachin reviewed
Also please fix "line too long" lint errors

2022-12-14 00:21 UTC, SherlockNoMad commented on torch/fx/passes/utils/matcher_utils.py
> +        if len(self.unused_pattern_placeholder_nodes) == len(unused_graph_placeholder_nodes):
I am afraid this is not a general rule that we can accept. 
A pattern graph with unused placeholder is not a well-defined pattern. How should the unused placeholder be interpreted in this case? As it has no consumer, it's effectively a dangling argument can be match with any tensor in the target graph. 
For this very reason, we disallow pattern graph with unused placeholder. If we are missing an assert statement to check this, I should add it.

2022-12-14 00:22 UTC, SherlockNoMad requested changes
Sorry, pattern graph with unused placeholder is not a well defined pattern.

2023-01-05 22:09 UTC, cccclai commented
abandon as we don't need it now.

2023-01-05 22:09 UTC, closed without merging