[Quant] make x86 the default quantization backend (qengine)
pytorch/pytorch pull request #91235
Opened 2022-12-21 07:21 UTC by Xia-Weiwen

**Summary**
Make x86 the default quantization backend (qengine) for X86 CPU platforms.
X86 is a unified quantization backend combining goodness of fbgemm and onednn. For more details please see https://github.com/pytorch/pytorch/issues/83888

**Test plan**
python test/test_quantization.py

2022-12-22 02:04 UTC, jgong5 approved these changes

2023-01-03 08:58 UTC, XiaobingSuper approved these changes

2023-01-12 00:30 UTC, malfet requested changes
PR description does not match with the actual implementation - i.e. it makes x86 a default backend for all platforms (not just x86, but ARM as well)

If this quantization backend supposed to work on all CPUs, let's rename it to something else.
If not, please guard the check with `#if defined(__x86_64__) || defined(WHATEVER_IT_SHOULD_BE_FOR_WINDOWS)`

2023-01-12 02:03 UTC, Xia-Weiwen commented
> PR description does not match with the actual implementation - i.e. it makes x86 a default backend for all platforms (not just x86, but ARM as well)
> 
> If this quantization backend supposed to work on all CPUs, let's rename it to something else. If not, please guard the check with `#if defined(__x86_64__) || defined(WHATEVER_IT_SHOULD_BE_FOR_WINDOWS)`

Thanks @malfet. X86 backend is only enabled when fbgemm is enabled. Looks like fbgemm only supports x86_64 platforms, right? In that case, x86 backend is enabled on x86_64 platforms only, and additional guard is not needed.

2023-01-12 02:11 UTC, malfet approved these changes

2023-01-12 02:12 UTC, malfet commented
> Thanks @malfet. X86 backend is only enabled when fbgemm is enabled. Looks like fbgemm only supports x86_64 platforms, right? In that case, x86 backend is enabled on x86_64 platforms only, and additional guard is not needed.

Good point, looks good to me then.

2023-01-12 02:12 UTC, malfet commented
@pytorchbot merge

2023-01-12 02:14 UTC, closed without merging