[bazel] change visibility for //c10:headers
pytorch/pytorch pull request #91422
Opened 2022-12-27 23:28 UTC by vors

At Cruise we are actively depending on the c10 headers, I'm not certain what is the reason to hide them to the pkg level.

2023-01-04 18:08 UTC, malfet approved these changes

2023-01-04 18:14 UTC, malfet requested changes
Hmm, looks like it legitimately breaks bazel build, but imo that's because default visibility is private and it should be public, shouldn't it?
```
ERROR: /var/lib/jenkins/workspace/BUILD.bazel:1281:11: in cc_library rule //:caffe2_for_aten_headers: target '//c10:headers' is not visible from target '//:caffe2_for_aten_headers'. Check the visibility declaration of the former target if you think the dependency is legitimate
```
If this passes the build (sorry, can't make suggestions on deleted line), will merge it: https://github.com/pytorch/pytorch/pull/91715

2023-01-04 18:28 UTC, vors commented
Oh lol, I must be too used to our setup. Let me fix it, thank you.

2023-01-04 18:40 UTC, malfet approved these changes

2023-01-04 18:41 UTC, malfet commented
Thank you for the quick fix, looks good to me.

2023-01-04 18:49 UTC, dagitses commented
Why are you depending on the headers rather than the full library?

2023-01-04 19:02 UTC, malfet commented
@pytorchbot merge -f "Bazel cpu builds passing"

2023-01-04 19:03 UTC, dagitses commented
> > Why are you depending on the headers rather than the full library?
> 
> I wonder why `:headers` library is there the first place, and why say `:caffe2_for_aten_headers` depends on `//c10:headers`?

Agreed. It really only exists because the Bazel build has been pretty haphazard with defining libraries of headers. I would like to see this cleaned up, and having an external user depending on this is not ideal for that goal.

2023-01-04 19:04 UTC, closed without merging

2023-01-04 19:05 UTC, malfet commented
> > > Why are you depending on the headers rather than the full library?
> > 
> > 
> > I wonder why `:headers` library is there the first place, and why say `:caffe2_for_aten_headers` depends on `//c10:headers`?
> 
> Agreed. It really only exists because the Bazel build has been pretty haphazard with defining libraries of headers. I would like to see this cleaned up, and having an external user depending on this is not ideal for that goal.

I though for `c10` we have full unification between internal and public builds, don't we?

2023-01-04 19:28 UTC, vors commented
I don't think that `c10` target exposes the headers (it doesn't depend on it) https://github.com/pytorch/pytorch/blob/master/c10/build.bzl

Also these queries show that

```
sergei.vorobev@cs-7xn77uoy-gpu-homedir-848671:~/workspaces/c2/src/github.robot.car/cruise/cruise$ bazel query 'somepath(@pytorch//c10, @pytorch//c10:headers)'
WARNING: build volume is nearly full (104.165 GB remain). Free up space to avoid running out of disk!

INFO: Invocation ID: ddea5aba-8c65-11ed-b684-42010ad8716a
INFO: Empty results
Loading: 18 packages loaded
sergei.vorobev@cs-7xn77uoy-gpu-homedir-848671:~/workspaces/c2/src/github.robot.car/cruise/cruise$ bazel query 'somepath(@pytorch//c10:headers, @pytorch//c10)'
WARNING: build volume is nearly full (104.165 GB remain). Free up space to avoid running out of disk!

INFO: Invocation ID: e3970a9e-8c65-11ed-b684-42010ad8716a
INFO: Empty results
Loading: 0 packages loaded
```

2023-01-05 03:41 UTC, vors commented
I filled https://github.com/pytorch/pytorch/issues/91751 to track improving this c10:headers situation.