Check the semantic of loading the mask value
pytorch/pytorch pull request #91755
Opened 2023-01-05 05:46 UTC by EikanWang

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-01-17 05:39 UTC, jgong5 requested changes

2023-01-17 05:39 UTC, jgong5 commented on torch/_inductor/codegen/cpp.py
> +            return True
For `bool` from a type case from `uint8`, do we need to check the user is `where` or `masked` here? Also, any other integer that can be casted to bool?

2023-01-17 05:39 UTC, jgong5 commented on torch/_inductor/codegen/cpp.py
> +            return user_nodes == set(["where", "masked"])
Do you intend to check if any of the user is either "where" or "masked"? If so, `all(user.target in ("where", "masked") for user in users.keys())` sounds correct then.

2023-01-22 02:18 UTC, jansel approved these changes

2023-01-25 02:56 UTC, jgong5 approved these changes

2023-02-06 14:17 UTC, EikanWang commented
@pytorchbot rebase

2023-02-07 08:46 UTC, EikanWang commented
@pytorchbot merge

2023-02-08 02:32 UTC, EikanWang commented
@pytorchbot merge

2023-02-08 02:34 UTC, closed without merging