[MPS] Fix convolution `Source and weight input channels mismatch' crash
pytorch/pytorch pull request #91822
Opened 2023-01-06 21:14 UTC by DenisVieriu97

Fixes crashes in conv input/weight backward passes due to NCHW / NHWC formats.

2023-01-09 16:11 UTC, razarmehr requested changes

2023-01-09 16:18 UTC, DenisVieriu97 commented on aten/src/ATen/native/mps/operations/Convolution.mm
> +MPSShape* get_mps_conv_shape(const Tensor& tensor, bool is_channels_last) {
I'll fix that - I've picked up directly what was available on kulin's master during conflicts. Thanks

2023-01-09 16:31 UTC, DenisVieriu97 commented on aten/src/ATen/native/mps/operations/Convolution.mm
> +    MPSShape* inputShape = get_mps_conv_shape(input_t, is_channels_last);
Thanks. Updated

2023-01-09 16:31 UTC, DenisVieriu97 commented on aten/src/ATen/native/mps/operations/Convolution.mm
> -  MPSShape* gradOutputShape = getMPSShape(grad_output_t, memory_format);
Thanks, updated

2023-01-09 17:41 UTC, razarmehr approved these changes
LGTM

2023-01-09 18:05 UTC, DenisVieriu97 commented
@pytorchbot rebase

2023-01-10 15:03 UTC, DenisVieriu97 commented
@pytorchbot merge

2023-01-10 18:28 UTC, DenisVieriu97 commented
@pytorchbot merge -f "Lint+MPS is green"

2023-01-10 18:30 UTC, closed without merging