Updated WeightedRandomSampler to fit usage of other samplers
pytorch/pytorch pull request #9183
Opened 2018-07-05 13:02 UTC by rsnk96

Commit to address #9171 

It does not break functioning of `BatchSampler()` or any of the other samplers, tested with the following code. It should also make it easy to dynamically change sampling weights in every call of the iterator of `WeightedRandomSampler`

```python
import torch
from torchvision import datasets, transforms
from torch._six import int_classes as _int_classes

mnist_dataset = datasets.MNIST(
    "../data",
    train=False,
    download=True,
    transform=transforms.Compose([transforms.ToTensor()]),
)
train_loader_no_sampler = torch.utils.data.DataLoader(
    mnist_dataset, batch_size=1, shuffle=True
)
train_loader_random = torch.utils.data.DataLoader(
    mnist_dataset, sampler=torch.utils.data.sampler.RandomSampler(mnist_dataset)
)
train_loader_subsetrandom = torch.utils.data.DataLoader(
    mnist_dataset, sampler=torch.utils.data.sampler.SubsetRandomSampler(range(10000))
)
train_loader_subsetrandom_2 = torch.utils.data.DataLoader(
    mnist_dataset,
    batch_size=100,
    num_workers=4,
    sampler=torch.utils.data.sampler.SubsetRandomSampler(range(10000)),
)
train_loader_weightedrandom = torch.utils.data.DataLoader(
    mnist_dataset,
    sampler=torch.utils.data.sampler.WeightedRandomSampler(weights=[1] * 10000),
)
train_loader_weightedrandom_2 = torch.utils.data.DataLoader(
    mnist_dataset,
    batch_size=100,
    num_workers=4,
    sampler=torch.utils.data.sampler.WeightedRandomSampler(
        weights=[1] * 10000, num_samples=2
    ),
)

for iter_no, (data, label) in enumerate(train_loader_no_sampler):
    continue
print("No sampler: ", iter_no)

for iter_no, (data, label) in enumerate(train_loader_random):
    continue
print("Random sampler: ", iter_no)

for iter_no, (data, label) in enumerate(train_loader_subsetrandom):
    continue
print("Subset Random sampler: ", iter_no)

for iter_no, (data, label) in enumerate(train_loader_subsetrandom_2):
    continue
print("Subset Random sampler with batch size 100: ", iter_no)

for iter_no, (data, label) in enumerate(train_loader_weightedrandom):
    continue
print("Weighted Random sampler: ", iter_no)

for iter_no, (data, label) in enumerate(train_loader_weightedrandom_2):
    continue
print("Weighted Random sampler 100 batch size and 2 samples every draw: ", iter_no)

```

Output:
```
No sampler:  9999
Random sampler:  9999
Subset Random sampler:  9999
Subset Random sampler with batch size 100:  99
Weighted Random sampler:  9999
Weighted Random sampler 100 batch size and 2 samples every draw:  199
```

2018-07-06 12:42 UTC, apaszke requested changes
I don't think this is an improvement. I'm not sure what was the issue with `num_samples` previously, it seems quite clear what the usage is. Maybe we could just improve the docs. The current PR is not great because:
1. The sampler can be iterated over only once.
2. It adds unnecessary logic to BatchSampler. All Samplers should have the same interface and the try block shouldn't be there

2018-07-06 14:04 UTC, rsnk96 commented
@apaszke Thank you for your comments

1. I agree that all samplers should have the same interface, which is why this pull request. Please refer to issue #9171 . This pull request makes it possible to use `WeightedRandomSampler` the same way as the other samplers
    1. Other samplers don't require the `num_samples` argument as a mandatory argument. So a user who has not gone through the source code might assume it is the number of samples drawn per iteration of the weight distribution, which they would leave as 1 (hence, a for loop would iterate over the `DataLoader` only once). Take `SubsetRandomSampler`, for instance. It's usage should ideally be the same as a `WeightedRandomSampler` code with all the weights being the same (as in the test example in the PR). This can be solved by either adding a `num_samples` argument to all the other samplers or by making `WeightedRandomSampler` similar to the other samplers right now (see code below for an example).
    2. Another problem that is solved with this PR is that a user can now dynamically change the weights of the distribution after every sample when used in a manner similar to the [Pytorch Tutorials](https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html#training-the-model) where we iterate over the epochs and then an inner for loop for iterating over samples within that epoch
2. Thank you for pointing out the iterability issue. I've pushed another change, it can be iterated over multiple times now. You can use the following code to check the same

```python
import torch
from torchvision import datasets, transforms

mnist_dataset = datasets.MNIST('data', train=False, download=True, 
                               transform=transforms.Compose(
                                   [transforms.ToTensor()]))
train_loader_weightedrandom = torch.utils.data.DataLoader(mnist_dataset,
    sampler=torch.utils.data.sampler.WeightedRandomSampler(weights=[1] * 10000))
# This is the equivalent of
# train_loader_subsetrandom = torch.utils.data.DataLoader(mnist_dataset,
#         sampler = torch.utils.data.sampler.SubsetRandomSampler(range(10000)))

for epoch_no in range(3):  # Assuming 3 epochs for simplicity
    iter_no = 0
    for iter_no, (data, label) in enumerate(train_loader_weightedrandom):
        continue
    print("Weighted Random sampler: ", iter_no)```

Output:
```
Weighted Random sampler:  9999
Weighted Random sampler:  9999
Weighted Random sampler:  9999
```

2018-07-24 16:51 UTC, ailzhang commented
cc: @apaszke

2018-07-24 21:50 UTC, rsnk96 commented
I would actually recommend other samplers like subset random sampler also not be defined in the `__iter__()` function itself, as that prevents it from being used for dynamic sampling/importance sampling

([Sample implementations from this year's ICML](https://github.com/idiap/importance-sampling))

2018-07-31 16:59 UTC, SsnL commented
Feels like a reasonable changes. @apaszke any further thoughts?

2018-09-12 18:59 UTC, SsnL commented
@apaszke

2019-04-02 21:53 UTC, NickMcKillip commented
@apaszke This change looks great to me, in fact, I only found this PR because I was trying to figure out what num_samples was as it wasn't clear and I was confused why WeightedRandomSampler required it when other samplers did not.

2022-07-05 14:34 UTC, closed without merging