Easy: add instructions for testing pytorch/builder
pytorch/pytorch pull request #91923
Opened 2023-01-09 22:10 UTC by dzhulgakov

Also makes the repo name configurable for branches in forks

2023-01-09 22:13 UTC, malfet requested changes
Thank you for the documentation improvements, but do you mind moving requirements.txt to  https://github.com/pytorch/pytorch/tree/master/.github/requirements  )

2023-01-09 22:13 UTC, malfet commented on .github/scripts/README.md
> +In order to test changes to the builder scripts, submit a fake PR against PyTorch that specifies your PR's branch as `builder_branch` in [`.github/templates/common.yml.j2`](https://github.com/pytorch
Hmm, this link would become invalid really soon, should we have an absolute link here (i.e. https://github.com/pytorch/pytorch/blob/26beb46da4b4c778e8162a67711ebe8fcd1408ae/.github/templates/common.yml.j2#LL10C9-L10C23 )
```suggestion
In order to test changes to the builder scripts, submit a fake PR against PyTorch that specifies your PR's branch as `builder_branch` in [`.github/templates/common.yml.j2`](https://github.com/pytorch/pytorch/blob/26beb46da4b4c778e8162a67711ebe8fcd1408ae/.github/templates/common.yml.j2#LL10C9-L10C23). Make sure to regenerate workflow files with `.github/regenerate.sh` (see above).
```

2023-01-09 22:14 UTC, malfet commented
Also, just curious, would it really be discoverable in pytorch, or would it better to add this doc note to the builder?

2023-01-09 22:27 UTC, seemethere approved these changes
Looks mostly good to me, just hinging on @malfet's comment

2023-01-09 22:28 UTC, dzhulgakov commented
I already added it in my other PR to builder/README.md: https://github.com/pytorch/builder/pull/1264/files?file-filters%5B%5D=.md&show-viewed-files=true (given it's just a readme change I'm lazy to separate it out)

2023-01-09 22:49 UTC, malfet approved these changes
LGTM, thank you for the updates.

2023-01-10 17:10 UTC, dzhulgakov commented
@pytorchbot merge please

2023-01-10 17:10 UTC, dzhulgakov commented
@pytorchbot merge

2023-01-11 07:24 UTC, dzhulgakov commented
@pytorchbot merge -f

2023-01-11 07:25 UTC, dzhulgakov commented
@pytorchbot merge -f "Unrelated upstream breakage"

2023-01-11 07:26 UTC, closed without merging