Proposal: Add complex-valued constraints for distributions
pytorch/pytorch pull request #92241
Opened 2023-01-16 10:11 UTC by felixdivo

Also make the `real`/`real-vector` only pass the check if they are not complex-valued.

## Rationale

In some discussions on forums as well es in, for example, #83376 complex-valued distributions were discussed. None of them have been implemented iny mainline PyTorch so far (AFAIK), but a first step would be the ability to express the constraints on these distributions. This is helpful for downstream libraries even if PyTorch never actually implements these in the main codebase. The extension is straight-forward and easy to maintain.

In addition, I noticed that the `real`/`real-vector` would also pass for complex-valued constraints. I suppose that this was not intentional.

## Next steps

If this change is deemed helpful, I'll add the nessesary tests. I think that this does not require more documentation, but please correct me if I am wrong with that.

2023-01-16 11:25 UTC, lezcano requested changes
Have you run locally even a smoke tests? I don't think that the current implementation works when the first logical argument is `False`, as it will return a Python scalar and not a PyTorch tensor.

2023-01-16 11:26 UTC, lezcano commented
I'll let @fritzo assess whether this is structurally desirable within the context of distributions.

2023-01-16 13:36 UTC, felixdivo commented on torch/distributions/constraints.py
> +        return not torch.is_complex(value) and value == value  # False for NaNs.
```suggestion
        return (torch.is_complex(value) | torch.isnan(value)).logical_not()

2023-01-16 13:38 UTC, lezcano commented on torch/distributions/constraints.py
> +        return not torch.is_complex(value) and value == value  # False for NaNs.
They are equivalent, both logically and in terms of performance, so whatever you prefer.

2023-01-16 13:38 UTC, felixdivo commented
I didn't do a smoke test yet, since the "open as GH codspaces" didn't work at all. I'll add some tests and let the CI run it. But first, it should be decided whether this features is desired.

2023-01-16 13:40 UTC, lezcano commented
Given that it is a python-only change, you can simply install the nightly and perform the changes on the Python source code directly. You can then run the relevant tests and even play around with the change.

2023-01-16 13:42 UTC, felixdivo commented
Shounds easy! I'll do that once I get a general greenish light.

2023-01-16 13:44 UTC, lezcano approved these changes
LGTM modulo putting in some proper testing. But again, let's wait for @fritzo's review on whether we want this feature, but a priori I think it should be fine.

2023-01-16 17:26 UTC, fritzo requested changes
Let's hold off on this PR until we have concrete use cases and a design discussion.

Generally, before we start down the path of supporting complex valued distributions, I think we should have a broader design discussion and ideally create a design document / RFC.  I'd suggest using a google doc and soliciting comments from stakeholders. Github issue's are too temporally linear for deep design discussions.  Maybe a wiki page would work.  Here's an [example design document for torch.distributions](https://docs.google.com/document/d/1wnABg0cdyaVMr-Xqz_brHBwnPJuzTeSk3Oqko2HHSfE/edit?usp=sharing) and a bunch of other [design documents for Pyro](https://github.com/pyro-ppl/pyro/wiki/Design-Docs).

Here are some topics we should discuss before starting down this path:
1. What are the first few example use cases for complex-valued distributions?
2. Mathematically the real line is sometimes considered a subset of the complex plane, and other times considered to trivial injection into the complex plane via `x ↦ (x, 0)`. What is the convention in PyTorch, i.e. is a real tensor allowed whenever a complex tensor is required (the former case), or do users need to cast to complex (the latter case)?
3. As I understand, `complex` concerns `dtype`, whereas torch.distributions generally dispatches based on `.shape` and checks constraints based on value.  What new checks would we need to add to the rest of torch.distributions to make constraints play well with complex `.dtype`s?
4. Can we get by with a single bijection : complex <--> real x real in torch.distributions.transforms, or are there intrinsically complex-valued distributions or constraints warranting a finer handling of dtype? 

Focusing on this PR, there are a few concept mismatches, again it would be worthwhile to start with an RFC for deeper discussion.
a. `torch.is_complex(-)` returns a `bool`, whereas `Constraint.check()` returns a batched boolean tensor describing whether each element's value is in the specified subset.
b. No existing constraints check `.dtype`, even the integer vs real constraints; this allows e.g. real-valued `.dtype` observations on a `Poission`, which is cheaper than `torch.long`.
c. If we add a `constraints.complex` that checks dtype `torch.is_complex(-)`, that suggests we'd need to add `not torch.is_complex(-)` checks to all other constraints, which seems like a big change.
d. If we add `is_complex(-)` checks to other constraints, how do we deal with constraint combinators like cat and stack?
e. Constraints are primarily used in torch.distributions.transforms e.g. in `AffineLinear`. Should such transforms also handle complex constraints, or should we populate a sister universe of `ComplexAffineLinear` etc.?

2023-01-25 11:27 UTC, felixdivo commented
Hey @fritzo, thank you for your extensive take on this. I understand that with a project of his size, care must be taken with such changes. If someone goes ahead and starts such a discussion, I am happy to contribute. However, I do not have the time to manage this proposal at the moment.

I want to point out though, that we do not need to specify the "complete" set of distributions that should be supported at some point in the future. Even if there are some distributions where there is ambiguity in how to define the distributions in the complex case, there is still merit in providing these constrains here in PyTorch for other libraries to then implement the distributions/transforms/... and have them be interoperable by using the same constraints.

2023-01-25 11:52 UTC, lezcano commented
I linked in https://github.com/pytorch/pytorch/issues/83376 Fritzo's point. Let's continue the discussion there then.

2023-01-25 11:52 UTC, closed without merging