[ FL-gradient quantization] Adding QNN unpack feature
pytorch/pytorch pull request #92714
Opened 2023-01-20 22:49 UTC by kwanghoon-meta

Summary: We are trying to add a new feature for quantized gradient computation which enables backward() function for QNNPACK

Test Plan: buck2 test //caffe2/test/quantization:quantization -- test_qlinear_qnnpack_free_memory_and_unpack

Differential Revision: D40927291

2023-01-21 04:11 UTC, digantdesai approved these changes
LGTM

2023-01-21 06:00 UTC, jianyuh approved these changes

2023-01-21 06:24 UTC, jianyuh requested changes
Check lint / test failures.

2023-01-23 08:28 UTC, kwanghoon-meta commented
@jianyuh 
https://github.com/pytorch/pytorch/actions/runs/3978787028/jobs/6828556833
I'm unsure if this cancelled job is related to my PR.
Would you please check?

2023-01-24 04:11 UTC, jianyuh approved these changes
LGTM! cc @jerryzh168 : who is the current maintainer for QNNPACK?

2023-01-24 17:08 UTC, digantdesai approved these changes
LGTM

2023-01-27 05:37 UTC, closed without merging