Added support for multidimensional tensors in PReLU
pytorch/pytorch pull request #932
Opened 2017-03-05 23:30 UTC by goelhardik

Fixes #724 
Also, for tensors with more than 1 dimension, the number of PReLU channels is now to be input in the second tensor dimension.

2017-03-07 15:53 UTC, soumith requested changes

2017-03-07 15:53 UTC, soumith commented on torch/lib/THCUNN/generic/PReLU.cu
> +      THError("wrong number of input planes");
it's very helpful to report the number of input planes. We have been slowly and proactively changing error messages to do this, so this is a good time to do:
```
THError("wrong number of input planes. Expected %d but got %d.", input->size[ndim > 1], nOutputPlane);
```

2017-03-07 15:53 UTC, soumith commented on torch/lib/THCUNN/generic/PReLU.cu
> +      THError("wrong number of input planes");
Same here

2017-03-07 15:53 UTC, soumith commented
Made some comments inline. Logically, PR looks good.

2017-03-07 15:54 UTC, soumith commented
Also, add a test case for PReLU 3d in test_nn.py

2017-03-07 18:07 UTC, goelhardik commented on torch/lib/THCUNN/generic/PReLU.cu
> +      THError("wrong number of input planes");
Should it be this?

`THError("wrong number of input planes. Expected %d but got %d.", nOutputPlane, input->size[ndim > 1]);`

Expected should be what we defined in PReLU() module, right?

2017-03-07 18:37 UTC, soumith commented on torch/lib/THCUNN/generic/PReLU.cu
> +      THError("wrong number of input planes");
yea you're right

2017-03-07 19:24 UTC, goelhardik commented
I have added a basic PReLU test that tests the forward and backward pass. If you had any other ideas, please let me know.

2017-03-07 19:46 UTC, soumith commented
@pytorchbot add to whitelist

2017-03-07 19:48 UTC, soumith commented on test/test_nn.py
> +        input = Variable(torch.randn(2, 3, 4), requires_grad=True)
you also prob want to test for the case you fixed in this PR, which is a 5D Tensor

2017-03-07 20:01 UTC, goelhardik commented on test/test_nn.py
> +        input = Variable(torch.randn(2, 3, 4), requires_grad=True)
done

2017-03-08 20:52 UTC, goelhardik commented
Should be ready, I suppose

2017-03-09 20:57 UTC, soumith approved these changes

2017-03-22 19:22 UTC, apaszke commented on test/test_nn.py
> +    def test_PReLU(self):
Actually it would be better to provide `reference_fn` to the PReLU tests. Grad is checked automatically. Can you please change that?

2017-03-22 19:47 UTC, soumith commented
I've rebased this branch to only have tests. The other changes are coming through subtree updates from respective upstreams in THNN / THCUNN

2017-03-23 00:37 UTC, soumith commented
merged into master via https://github.com/pytorch/pytorch/commit/6b7aef63ac96187f6651897789ccfe058ddc8cc1

Thanks a lot Hardik!

2017-03-23 00:37 UTC, closed without merging