Remove cuda 11.6 from CI replace with 11.7
pytorch/pytorch pull request #93406
Opened 2023-01-31 23:10 UTC by atalman

Remove cuda 11.6 from CI replace with 11.7
Following the Release readme here: https://github.com/pytorch/pytorch/blob/master/RELEASE.md#release-compatibility-matrix

2023-01-31 23:24 UTC, malfet approved these changes
Looks good to me, if it passes CI

2023-02-02 16:27 UTC, desertfire approved these changes

2023-02-02 16:31 UTC, desertfire requested changes
Wait, you need to delete `inductor-perf-smoke-test.yml` as it is now merged into `inductor.yml`.

2023-02-02 16:36 UTC, desertfire approved these changes

2023-02-02 19:14 UTC, atalman commented
@pytorchbot merge -f "test are green before rebase"

2023-02-02 19:16 UTC, closed without merging