[pt2] Fix multiple races in log folder
pytorch/pytorch pull request #93407
Opened 2023-01-31 23:39 UTC by xw285cornell

Summary:
There are a few races/permission errors in file creation, fixing
OSS:
1. caffe2/torch/_dynamo/utils.py, get_debug_dir: multiple process may conflict on it even it's using us. Adding pid to it
2. caffe2/torch/_dynamo/config.py: may not be a right assumption that we have permission to cwd

Test Plan: sandcastle

Differential Revision: D42905908

2023-02-03 05:52 UTC, soumith approved these changes

2023-02-07 09:34 UTC, mlazos requested changes
Rather than changing the config default for the debug dir location for everyone, please patch this for internal code

2023-02-07 19:00 UTC, xw285cornell commented on torch/_dynamo/config.py
> +debug_dir_root = os.path.join(tempfile.gettempdir(), "torch_compile_debug")
I think there maybe a few things: (1) often times cwd is under source control so it'll add files that can make git/hg a little messy; (2) sometimes we don't have permission on cwd; also it's a little weird(?) that if we run the binary under different folder it'll end up different place; change to /tmp should get rid of those problems; (3) the logic here won't work as os.rename doesn't work across different file systems https://github.com/pytorch/pytorch/blob/d690a596dcbccf943f90c3e5353394cadc29dfd1/torch/_inductor/debug.py#L267

2023-02-07 23:15 UTC, mlazos approved these changes
Thanks!!

2023-02-09 21:10 UTC, closed without merging