Plumb dynamic_spec to meta converter
pytorch/pytorch pull request #93820
Opened 2023-02-01 05:38 UTC by SherlockNoMad

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-02-01 14:33 UTC, ezyang commented
this plumbing is what i expected and seems fine to me

2023-02-01 22:38 UTC, jansel requested changes

2023-02-01 22:38 UTC, jansel commented on torch/_dynamo/variables/base.py
> +        dynamic_spec = None,
I don't think the dynamic_spec should go on the base class for VariableTracker, it seems specific to Tensors.  

Could we encode this in the shape env?

2023-02-02 08:46 UTC, SherlockNoMad commented
Abort, using ShapeEnv to skip plumbing.

2023-02-02 08:46 UTC, closed without merging