[Export] Introudce Epilogue for buffer mutation
pytorch/pytorch pull request #94147
Opened 2023-02-05 01:43 UTC by SherlockNoMad

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-02-05 01:48 UTC, SherlockNoMad commented on export_workspace/example_mutate_buffer.py
> +my_decomp = get_decompositions(
Both index_add_ and index_copy_ can be decomposed into index_put_.

2023-02-05 01:51 UTC, SherlockNoMad commented on export_workspace/example_mutate_buffer.py
> +        )  # ScatterWeightedSum
Notice that these are two inplace ops mutating the same buffer. 
If we were to preserve them in export, computes in the Epilogue needs to be ordered.

2023-02-05 01:52 UTC, SherlockNoMad commented on export_workspace/example_mutate_buffer.py
> +        index_put__default = torch.ops.aten.index_put_.default(_tensor_constant0_2, [_to_copy_default], squeeze_default);  _tensor_constant0_2 = _to_copy_default = squeeze_default = None
index_copy_ decomposed into index_put_(..., accumulate=False)

2023-02-05 01:52 UTC, SherlockNoMad commented on export_workspace/example_mutate_buffer.py
> +        index_put__default_1 = torch.ops.aten.index_put_.default(index_put__default, [arg1], squeeze_default_1, True);  index_put__default = arg1 = squeeze_default_1 = None
index_add_ decomposed into index_put_(..., accumulate=True)

2023-02-05 01:57 UTC, SherlockNoMad commented on torch/_export/logical_schema.py
> +    inputs: List[TensorArgument]
For the example above, 

inputs should have [index_for_first_index_put, value_for_firs_index_put, index_for_second_index_put, value_for_second_index_put]

2023-02-05 01:58 UTC, SherlockNoMad commented on torch/_export/logical_schema.py
> +    mutated_values: List[TensorArgument]
mutated_values should be [_tensor_constant0]

2023-02-05 01:59 UTC, SherlockNoMad commented on torch/_export/logical_schema.py
> +    nodes: List[Node]
nodes should contain two aten.index_put_ nodes.

2023-02-05 22:04 UTC, suo requested changes
pedantic complaint about schema, otherwise lgtm

2023-02-05 22:04 UTC, suo commented on torch/_export/logical_schema.py
> +    epilogue: Epilogue   # Epilogue program for the mutation of parameters and buffers
nit: this should contain the name `Mutation` to make clear its purpose.

2023-02-07 05:37 UTC, zhxchen17 commented on torch/_export/logical_schema.py
> +class Epilogue:
an alternative design I think also works here:
```Python
class Epilogue:
    copies: List[...]
    index_puts: List[...]
```
and inputs data can be expressed implicitly inside `...` part.

2023-05-08 08:33 UTC, closed without merging