Fix out-of-range error for test_neg
pytorch/pytorch pull request #9431
Opened 2018-07-13 20:52 UTC by yf225

`test_neg` sometimes fails internally because `random_()` can generate an out-of-range value for CharTensor. This PR fixes it.

2018-07-13 21:03 UTC, soumith approved these changes

2018-07-13 21:05 UTC, colesbury commented
I'm OK with this if we need to fix the tests immediately, but shouldn't we fix `random_()` on CharTensor instead?

I don't understand the strategy of enabling overflow tests, but trying to avoid triggering them in test code. If we're OK with overflows then they shouldn't break tests. If we're not OK, then we shouldn't try to avoid testing broken code.

2018-07-15 02:31 UTC, apaszke requested changes
`int8_t` tensors can represent numbers in range of [-128, 127], not [-128, 128]!

2018-07-16 03:14 UTC, yf225 commented
@apaszke `random_(A, B)` seems to be picking number from range `[A, B)`? e.g. `torch.Tensor(1).type('torch.CharTensor').random_(0, 1)` will always give 0, not 1.

2018-07-16 14:42 UTC, apaszke approved these changes

2018-07-16 17:27 UTC, closed without merging