[MPS] Enable index add for TestConsistency
pytorch/pytorch pull request #94356
Opened 2023-02-08 00:06 UTC by DenisVieriu97

Enable index_add TestConsistency TestCase

2023-02-08 04:48 UTC, malfet requested changes
Lint is correct, you need to add dtypes  to `index_add` on line 8368

2023-02-09 02:09 UTC, kulinseth approved these changes

2023-02-09 04:37 UTC, DenisVieriu97 commented
@pytorchbot rebase

2023-02-10 00:19 UTC, DenisVieriu97 commented
@pytorchbot merge -f "Lint+MPS is green"

2023-02-10 00:21 UTC, closed without merging