[ONNX] Use onnxruntime to run fx tests
pytorch/pytorch pull request #94638
Opened 2023-02-10 23:40 UTC by justinchuby

2023-02-10 23:59 UTC, BowenBao approved these changes

2023-02-11 00:14 UTC, wschin approved these changes
Thanks. LGTM.

2023-02-11 00:29 UTC, titaiwangms approved these changes

2023-02-11 00:34 UTC, BowenBao requested changes
linter and onnx test failing

2023-02-11 00:57 UTC, BowenBao approved these changes

2023-02-11 00:59 UTC, justinchuby commented on test/onnx/test_fx_to_onnx_with_onnxruntime.py
> +    onnx.save_model(onnx_model, "mnist.onnx")
```suggestion
```

2023-02-11 01:01 UTC, justinchuby commented
@pytorchbot merge -g

2023-02-11 01:05 UTC, justinchuby commented on test/onnx/test_fx_to_onnx_with_onnxruntime.py
> +import onnx
```suggestion
```

2023-02-11 01:14 UTC, justinchuby commented
@pytorchbot merge -g

2023-02-11 15:28 UTC, justinchuby commented
@pytorchbot merge -f unrelated trunk failures

2023-02-11 15:30 UTC, justinchuby commented
@pytorchbot merge -f "unrelated trunk failures"

2023-02-11 15:32 UTC, closed without merging