Implementing torch.isfinite
pytorch/pytorch pull request #9487
Opened 2018-07-17 07:03 UTC by bhushan23

fixes #9132

2018-07-17 13:12 UTC, vishwakftw commented on test/test_torch.py
> +        self.assertEqual(torch.isinf(x), torch.ByteTensor([1, 0, 1, 0, 0]))
This test is wrong.

2018-07-17 15:28 UTC, zou3519 approved these changes

2018-07-17 15:36 UTC, ssnl requested changes

2018-07-17 15:36 UTC, SsnL commented on torch/functional.py
> +    return (isinf(tensor) | isnan(tensor)) == 0
This should be more efficient as `(tensor == tensor) & (tensor.abs() != math.inf)`.

2018-07-17 16:40 UTC, bhushan23 commented
Thanks @zou3519 @vishwakftw for the review
@SsnL your suggested is indeed efficient 4 ops vs earlier 5 ops - updated.

2018-07-17 16:40 UTC, ssnl approved these changes

2018-07-17 22:40 UTC, bhushan23 commented
@ezyang approval required!!

2018-07-18 14:57 UTC, soumith approved these changes

2018-07-18 15:26 UTC, closed without merging