Expose Joint graph from AOTAutograd
pytorch/pytorch pull request #94965
Opened 2023-02-16 05:11 UTC by SherlockNoMad

Summary:
This PR introduces an experimental training mode for dynamo.export().
It exposes the joint graph of AOTAutograd to the export path.

We also introduces a set of constrains to the exported program, such that the resulting joint graph would have the following signature.

        class JointGraphSignature:
            # joint graph inputs
            num_lifted_parameters: int
            num_lifted_buffers: int
            num_user_inputs: int
            num_gradient_user_outputs: int

            # joint graph outputs
            num_input_mutations: int
            num_users_outputs: int
            num_gradient_parameters: int
            num_gradient_buffers: int
            num_gradient_user_inputs: int

A sample of the joint graph: https://www.internalfb.com/phabricator/paste/view/P624481899

Test Plan:
buck2 run mode/dev-sand mode/inplace -c fbcode.enable_gpu_sections=True sigmoid/frontend:main

buck2 run mode/dev-sand sigmoid/backend:main -- --device="cuda:1"

Differential Revision: D43215635

2023-02-22 06:51 UTC, SherlockNoMad commented on torch/_functorch/aot_autograd.py
> +            backward_out = torch.autograd.grad(out[0], args[:len(named_parameters)])
Obviously, out[0] is a hack here. 

We have 3 options for UX of training mode export. 
1. Assuming out[0] is the loss to backprob with, so user must write the forward function to always return loss as the first return. 
2. Ask user to pass in an index to indicate which output is the loss value.
3. We can require that only one of the output can can require_grad=True. User would have to call .detach on the output that is not the loss. 

Ideas?

2023-02-22 06:57 UTC, SherlockNoMad commented on torch/_functorch/aot_autograd.py
> +
`args[:len(named_parameters)]` is only back-propagating to parameters, and not to buffers and user inputs. 
Do we need to support computing gradients for user inputs? @suo 

I think it's needed as SparseArch output is fed as input to dense part as user input. Gradient needs to further backprob to SparseArch.

2023-02-22 07:00 UTC, SherlockNoMad commented on torch/_functorch/aot_autograd.py
> +            num_gradient_buffers: int
we can drop the gradient for buffers, as buffers cannot have gradient.

2023-02-22 07:47 UTC, SherlockNoMad commented on torch/_functorch/aot_autograd.py
> +    ), preserve_rng_state(), cross_ref, fake_mode, python_dispatcher_mode:
Do I really need all these context? 
I don't think I need cross_ref. What about other?

2023-02-22 12:28 UTC, ezyang requested changes
I said it before and I'll say it again, please don't use argument position (e.g., counting the number of user outputs / gradient params / etc) to differentiate between params/buffers/user inputs. Force a more structured in/out representation.

2023-02-22 14:51 UTC, bdhirsh commented
One thing that seems like it's missing: do you want to add extra asserts for the classes of model that export currently doesn't allow?

(1) Mutating an input that requires grad. Technically this is fine under `torch.no_grad()`, but I don't think we have an easy way to distinguish that case right now (but maybe this isn't a problem if you aren't exporting the optimizer step). This works today in aot autograd, but causes extra `.clone()`'s to show up in the graph

(2) Metadata mutations on inputs. You could probably in theory append `.as_strided_()` calls to the end of the graph if you detect input mutations, but that doesn't happen today (and another case where that isn't enough is if you see a `.resize_()` on an input).

(3) Mutating an input that aliases another input. The logic that checks for this today is in `merge_view_inputs`. Today, the second output from that function is an optional dict, and if the dict exists, then you know you hit that case (I think this could be refactored better though 🙁 )

2023-02-24 00:41 UTC, voznesenskym commented on torch/_dynamo/eval_frame.py
> +    f, *args, aten_graph=False, decomposition_table=None, tracing_mode="real", training_mode=False, **kwargs
Please no more notions and forks in export, let's start the unbundling yesterday?

2023-02-24 00:43 UTC, voznesenskym commented on torch/_functorch/aot_autograd.py
> +    params_len = len(params_flat)
Dupe of L2571 in `aot_module_simplified` please pull into util

2023-02-24 00:46 UTC, voznesenskym requested changes
Paused reviewing - there's too much dupe code. If there's one thing we don't need, it's a bigger aot_autograd.py

If you need to have some upstream PRs to pull utils out of common places in aot_autograd, so be it!

Also, PR is untested.

2023-02-25 20:14 UTC, ezyang commented
The resolution from Fri meeting was that s-curve will check in a private version of their code and @bdhirsh will do the refactor.

2023-05-11 22:21 UTC, closed without merging