Fix: `validate_input_col` for partial functions
pytorch/pytorch pull request #95067
Opened 2023-02-17 15:47 UTC by BeckerFelix

Fixes #95066

Proposed changes:
* do not call `str()` on a `Callable` to determine its name

Reasoning:
Please see https://github.com/pytorch/pytorch/issues/95066 for reasoning and examples

2023-02-23 01:07 UTC, NivekT approved these changes
LGTM! Thanks for spotting this issue and fixing it. I don't think this should cause any issue for lambda function right?

cc: @ejguan I will cherry-pick this into the release.

2023-02-23 09:45 UTC, BeckerFelix commented
> LGTM! Thanks for spotting this issue and fixing it. I don't think this should cause any issue for lambda function right?
> 
> cc: @ejguan I will cherry-pick this into the release.

thanks for the review. 
`__name__` is valid on lambda functions, so we should be good.

2023-02-23 09:46 UTC, BeckerFelix commented
@pytorchmergebot merge

2023-02-23 09:53 UTC, BeckerFelix commented
@pytorchbot rebase

2023-02-23 10:01 UTC, BeckerFelix commented
@pytorchmergebot merge

2023-02-23 14:27 UTC, ejguan requested changes
Can you pls add tests to `test/test_datapipe.py`?
You can inject them into `test_map_tuple_list_with_col_iterdatapipe` and `test_map_dict_with_col_iterdatapipe`

2023-03-03 15:10 UTC, BeckerFelix commented
> test_map_tuple_list_with_col_iterdatapipe

Happy to enhance the tests. Can you be more specific of what exactly you would like to see tested, please? In both `test_map_tuple_list_with_col_iterdatapipe` and `test_map_dict_with_col_iterdatapipe` map functions, partials, and lambdas get mapped over a datapipe. 
I could provide a test which creates a partial with a large input argument and maps this over the datapipe. Similar to the code snippet I provided in https://github.com/pytorch/pytorch/issues/95066. wdyt?

2023-03-03 15:52 UTC, ejguan commented
> I could provide a test which creates a partial with a large input argument and maps this over the datapipe. Similar to the code snippet I provided in #95066. wdyt?

Sounds good to me.

2023-03-03 17:36 UTC, BeckerFelix commented
> 

let me know what you think about d4b3ed997ae603379ca93798c87744ecde69c5e1, please

2023-03-03 17:49 UTC, ejguan commented
@pytorchbot rebase

2023-03-03 19:26 UTC, ejguan approved these changes

2023-03-03 19:26 UTC, ejguan commented
@pytorchbot merge

2023-03-03 21:05 UTC, closed without merging

2023-03-07 18:25 UTC, ejguan commented on torch/utils/data/datapipes/utils/common.py
> +        fn_name = fn.__name__
This causes lots of problem as not all of callable objects have `__name__`
I am going to do a forward fix.

2023-03-07 18:26 UTC, ejguan commented on torch/utils/data/datapipes/utils/common.py
> +        fn_name = fn.__name__
Simple example would be a `nn.Module`