Don't replace FloorDiv with floor in simplify, do simplifications for divisible exprs
pytorch/pytorch pull request #95076
Opened 2023-02-17 17:59 UTC by ngimel

I don't see why `floor` is better than `FloorDiv` and solve with `FloorDiv` doesn't work anyway (the solution wouldn't be unique even if it worked).

2023-02-17 18:01 UTC, nkaretnikov commented on torch/fx/experimental/symbolic_shapes.py
> +        print("EXPR", expr)
reminder to remove this later

2023-02-17 18:04 UTC, nkaretnikov commented
I've added some CI tags to see how this affects models. Will take a look closely once everything is green (or broken).

2023-02-17 18:25 UTC, jansel approved these changes

2023-02-17 18:25 UTC, malfet approved these changes

2023-02-17 19:00 UTC, Chillee requested changes
I'm somewhat confused here - I don't see why this is any better. FloorDiv is still not simplifiable by us. Perhaps we could just add a pass in simplify that simplifies FloorDiv patterns? 

I also have another (hacky) idea - what if we replaced `FloorDiv(a, b)` with `a/b` for the duration of the simplify, and then remap `a/b` back to `FloorDiv(a, b)` if it doesn't simplify?

2023-02-17 20:08 UTC, ngimel commented on torch/fx/experimental/symbolic_shapes.py
> -                if self.replace(base % divisor) in self.divisible:
We are not doing anything with divisibility anyway, floor(a/b) is correct replacement even for non-divisible a and b. Replacing for the duration of simplify and trying to cancel division with multiplication is good, I'll add this.

2023-02-17 21:36 UTC, Chillee commented on torch/fx/experimental/symbolic_shapes.py
> -                if self.replace(base % divisor) in self.divisible:
Sympy implicitly simplifies a bunch of divisibility related things, which is why this is here.

2023-02-17 22:46 UTC, ngimel commented on torch/fx/experimental/symbolic_shapes.py
> -                if self.replace(base % divisor) in self.divisible:
Does sympy do anything for `a/b` that FloorDiv doesn't do in eval (like dividing by gcd)?

2023-02-17 23:43 UTC, ngimel commented
@pytorchbot rebase

2023-02-18 01:35 UTC, ngimel commented
@pytorchbot rebase -b master

2023-02-18 02:19 UTC, jansel commented
> I also have another (hacky) idea - what if we replaced `FloorDiv(a, b)` with `a/b` for the duration of the simplify, and then remap `a/b` back to `FloorDiv(a, b)` if it doesn't simplify?

This is a bad idea.  Don't do it.

`a//b*b` will become `a`, which is incorrect if there is a remainder in the divide.

2023-02-18 03:39 UTC, ngimel commented
> `a//b*b` will become `a`, which is incorrect if there is a remainder in the divide.

We should do it only if a is divisible by b (we have divisibility info in shape env).

2023-02-18 11:51 UTC, nkaretnikov commented on torch/fx/experimental/symbolic_shapes.py
> -                if self.replace(base % divisor) in self.divisible:
For reference: `floor` has some things that are different compared to `FloorDiv`. See `class floor` [here](https://github.com/sympy/sympy/blob/fb7c59c1e5f15b625bc3b777c55e26872ec787b9/sympy/functions/elementary/integers.py#L95):
-  more `_eval` methods
-  an eval rule that is triggered during equality (`_eval_is_eq`).

It's hard to say whether these matter much _for us_ in practice, though. However, waiting on cases that are hard to `solve` is a real problem that we have now, so I guess it makes sense to do this change just to fix that.

As for divisibility, we could try to do optimizations somewhere else, e.g., in custom `Mul`, but that's separate. Natalia correctly pointed out that we're not doing much with divisibility here anyway.

We can always go back or do something else if there are problems, so I see no reason to block this.

2023-02-18 11:52 UTC, nkaretnikov approved these changes

2023-02-18 16:26 UTC, nkaretnikov commented on torch/fx/experimental/symbolic_shapes.py
> -                if self.replace(base % divisor) in self.divisible:
FYI: floor/mul optimization PR is here: https://github.com/pytorch/pytorch/pull/95120 (WIP)

2023-02-19 20:59 UTC, ngimel commented on torch/fx/experimental/symbolic_shapes.py
> -                if self.replace(base % divisor) in self.divisible:
I've added floor/mul optimization to this PR, it works for all tricky cases in swin.

2023-02-20 01:52 UTC, ngimel commented
@pytorchbot merge

2023-02-20 01:54 UTC, closed without merging