[dynamo] Adding missing source for default_generator
pytorch/pytorch pull request #95433
Opened 2023-02-24 01:49 UTC by anijain2305

Stumbled across this error while working on activation checkpointing.

2023-02-24 17:29 UTC, anijain2305 commented
Unrelated failure which will be fixed by - https://github.com/pytorch/pytorch/pull/95473

2023-02-27 17:41 UTC, jansel approved these changes

2023-02-27 17:44 UTC, jansel requested changes
Actually, shouldn't this one not have a source since it isn't an input, it is part of the graph?

2023-02-28 01:24 UTC, mlazos approved these changes
Approved: am also curious about Jason's question

2023-04-02 06:21 UTC, closed without merging