Fix typo and grammatical errors in community docs and dynamo docs
pytorch/pytorch pull request #95692
Opened 2023-02-28 07:31 UTC by ajithvallabai

Fixes typo and grammatical errors in community docs and dynamo docs

2023-02-28 16:21 UTC, H-Huang requested changes
Thanks! The grammar changes don't need to be added, will accept and merge the typo changes if those are removed

2023-03-01 06:03 UTC, ajithvallabai commented on docs/source/community/design.rst
> -building performant features at higher layers in the stack, and often
done

2023-03-01 06:03 UTC, ajithvallabai commented on docs/source/dynamo/faq.rst
> -libraries is under discussion.
done

2023-03-01 06:03 UTC, ajithvallabai commented on docs/source/dynamo/get-started.rst
> -most important optimization that inductor does is fusion. So back to our
done

2023-03-01 14:38 UTC, H-Huang approved these changes
LGTM

2023-03-01 14:39 UTC, H-Huang commented
@pytorchbot merge

2023-03-01 18:10 UTC, closed without merging