Fix unpickable object in AveragedModel
pytorch/pytorch pull request #95979
Opened 2023-03-03 17:10 UTC by DavidFM43

Fixes #95376

Don't store the callable `avg_fn`, instead test if `avg_fn` is None and call
the default impl if it's not.

2023-03-03 19:08 UTC, janeyx99 requested changes
Could you add a test case showing that it is picklable when no avg_fn is provided?

2023-03-03 20:33 UTC, DavidFM43 commented
Sure

2023-03-10 22:39 UTC, albanD commented
ping @janeyx99

2023-03-11 01:02 UTC, janeyx99 reviewed
sorry for the delay! overall looks good so I approved CI—also left some comments

2023-03-11 05:15 UTC, DavidFM43 commented on test/test_optim.py
> +        dnn = torch.nn.Sequential(
Agree, I'll change that.

2023-03-12 02:39 UTC, janeyx99 approved these changes
looks good!

2023-03-12 02:39 UTC, janeyx99 commented
@pytorchbot merge

2023-03-12 05:13 UTC, closed without merging