add runtime enable/disable for mkldnn matmul kernel
pytorch/pytorch pull request #96169
Opened 2023-03-07 03:54 UTC by snadampal

this control allows applications to disable the mkldnn matmul backend if the additional graph rewrite and onednn overhead is not acceptable for any matmul tensors.

use, export MKLDNN_MATMUL_ENABLE=0, to disable.

Fixes #https://github.com/pytorch/pytorch/issues/96140

2023-03-07 19:04 UTC, malfet approved these changes
Please consider using `constexpr` to avoid `#ifdef` guards in `addmm_impl_cpu_`. Also, we commonly prefix all PyTorch env vars with `TORCH_`

2023-03-07 19:04 UTC, malfet commented on aten/src/ATen/native/LinearAlgebra.cpp
> +  }(std::getenv("MKLDNN_MATMUL_ENABLE"));
Nits: Please use `TORCH_` prefix for all PyTorch env vars and use ternaries to make code a bit more compact.
```suggestion
  static bool value = [&]() {
    const char *ptr = std::getenv("TORCH_MKLDNN_MATMUL_ENABLE");
     return pt != nullptr ? std::atoi(pt) : 1;
  }();
```

2023-03-07 19:06 UTC, malfet requested changes
Sorry, I didn't realize it targets 2.0 branch. For trunk this is totally fine.

2023-03-07 19:18 UTC, malfet approved these changes
LGTM, but please consider addressing nit and define `static constexpr bool is_mkldnn_matmul_enable() { return true;}` for non-aarch64 platforms to avoid extra `#ifdef` in `addmm_impl_cpu_`

2023-06-17 00:00 UTC, kit1980 commented
Hi @snadampal, I wonder if you're still interested in merging this?

2023-06-17 00:06 UTC, snadampal commented
Hi @kit1980 , yes. btw, this PR was raised on 2.0 branch which is no longer relevant, but I have the below PR for the main branch which needs to be reviewed.
https://github.com/pytorch/pytorch/pull/96141

2023-06-17 00:08 UTC, kit1980 commented
Closing this in favor of https://github.com/pytorch/pytorch/pull/96141

2023-06-17 00:08 UTC, closed without merging