Use int64_t instead of ptrdiff_t for size / Rename flag to resizable_
pytorch/pytorch pull request #9654
Opened 2018-07-20 20:15 UTC by cpuhrsch

2018-07-20 20:22 UTC, gchanan commented on aten/src/ATen/Storage.h
> +  void clear_flag(bool flag) {
having this be called flag when it means resizable doesn't make sense.

2018-07-20 20:22 UTC, gchanan commented on aten/src/TH/THStorageClass.cpp
> +    bool flag)
here too.

2018-07-20 21:44 UTC, ezyang commented
@pytorchbot retest this please

2018-07-23 13:23 UTC, ezyang commented
```
22:31:01 /var/lib/jenkins/workspace/aten/src/ATen/test/atest.cpp:25
22:31:01 ...............................................................................
22:31:01 
22:31:01 /var/lib/jenkins/workspace/aten/src/ATen/test/atest.cpp:41: FAILED:
22:31:01   {Unknown expression after the reported line}
22:31:01 due to a fatal error condition:
22:31:01   SIGSEGV - Segmentation violation signal
```

Looks real.

2018-07-23 13:29 UTC, ezyang commented on aten/src/ATen/templates/StorageDerived.cpp
> +  THStorage_setResizable(storage, TH_STORAGE_RESIZABLE);
Don't use this constant anymore, right? Also, don't you want to say this is NOT resizable.

2018-07-23 13:30 UTC, ezyang commented on aten/src/TH/THGeneral.h.in
> +#include <stdbool.h>
Hm?

2018-07-23 13:30 UTC, ezyang commented on aten/src/TH/generic/THStorage.cpp
> +      TH_STORAGE_RESIZABLE);
You don't want to use this flag anymore either, right?

2018-07-23 13:31 UTC, ezyang commented on aten/src/TH/generic/THStorage.h
> +#define TH_STORAGE_RESIZABLE  1
Just delete this constant altogether...

2018-07-23 13:32 UTC, ezyang requested changes
1. There are some mistakes in the refactoring; that's probably why the tests fail
2. Expunge `TH_STORAGE` entirely; just use a bool.

2018-07-23 21:23 UTC, closed without merging