Enable cadd_sparse for BFloat16 on CPU
pytorch/pytorch pull request #96767
Opened 2023-03-14 19:32 UTC by itaraban

Enabling **cadd_sparse** operation for BFloat16 on CPU to support BFloat16 operations in GNN libraries.

2023-03-15 01:04 UTC, jgong5 approved these changes

2023-03-30 17:04 UTC, cpuhrsch requested changes
See inline comments around test. Otherwise code change looks like.

2023-03-30 21:42 UTC, itaraban commented on test/test_sparse.py
> +        if device == 'cuda':
Thanks, I'll remove this part and change `dtypes` to `torch.float`

2023-04-07 06:33 UTC, jgong5 commented
@cpuhrsch @itaraban has updated the code. Is it good to land?

2023-04-13 21:15 UTC, cpuhrsch approved these changes

2023-04-13 21:15 UTC, cpuhrsch commented
@pytorchbot merge

2023-04-14 17:22 UTC, cpuhrsch commented
@pytorchbot merge

2023-04-14 19:50 UTC, closed without merging