lint aot_autograd with mypy
pytorch/pytorch pull request #96784
Opened 2023-03-14 23:23 UTC by bdhirsh

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-03-15 04:25 UTC, Skylion007 approved these changes

2023-03-16 03:28 UTC, ezyang commented on torch/_functorch/aot_autograd.py
> +        assert isinstance(non_param_args, list)
??? this isn't even true

```
>>> (1,2,3)[2:]
(3,)
```

2023-03-16 03:30 UTC, ezyang commented on torch/_functorch/aot_autograd.py
> +    input_metadata_output_info = []
don't you have to annotate this

2023-03-16 03:30 UTC, ezyang commented on torch/_functorch/aot_autograd.py
> +        assert isinstance(curr_info, tuple)
why don't you just annotate `synthetic_base_info` properly

2023-03-16 03:31 UTC, ezyang requested changes
there seems to be a lot of unidiomatic fixes to type errors

2023-03-24 17:10 UTC, ezyang commented
explicitly retag when you want review

2023-06-22 20:34 UTC, closed without merging