[functorch][experimental] Support while_loop in eager_mode
pytorch/pytorch pull request #96899
Opened 2023-03-15 23:03 UTC by ydwu4

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-03-16 09:02 UTC, vadimkantorov commented
@ydwu4 btw is the proposed pseudo-code for while_loop here similar to "reduce while" (in functional programming terms)? It would also be nice to have a regular "reduce" - then EMA over a dimension could be nicely and efficiently coded: https://github.com/pytorch/pytorch/issues/70555 :)

2023-03-16 16:17 UTC, ydwu4 commented
>  is the proposed pseudo-code for while_loop here similar to "reduce while" (in functional programming terms)? 

I think the proposed pseudo-code can support "reduce while" but can be more general e.g. it could also be used as a map by looping over a certain dimension. 

> It would also be nice to have a regular "reduce" - then EMA over a dimension could be nicely and efficiently coded: #70555 :)

I agree with you that regular "reduce" is a nice feature but I'm afraid we don't have the bandwidth to support it now. It feels more comfortable for me to provide solid implementations for existing operators before adding new operators unless we have to :).

2023-03-16 17:44 UTC, vadimkantorov commented
Maybe if it can support `cond = True` (instead of passing a function returning True), it would also be nice and could stand for implementing `reduce` along a dimension :)

2023-03-17 14:43 UTC, ezyang requested changes
If you come into the office (MPK) today, I'm in town and we can talk about it. I am generally against adding complicated control flow operations to our IR as they make downstream optimization and analysis substantially more complicated (for example, how are you going to functionalize a while_loop that internally causes mutation?) and they lead to people asking for Python data type support in the IR (which leads you down the path that TorchScript took).

If you want to convince me this is a good idea, (1) you have to argue why this time is different from TorchScript, and (2) show that the downstream second order effects from this complexity are manageable in the long term.

2023-03-18 06:37 UTC, vadimkantorov commented
@ezyang In my perspective - supporting some high-level constructs like scans / reduce / map tensor functions should make transformations / optimizations easier as they express various RNNs and maybe even solver loops (like fixed point iterations). For mutation - this may happen in the wild if one codes a loop that modifies some hidden state inplace. How this impacts the inner architecture of IR - no idea :)

2023-03-20 02:02 UTC, ezyang commented
We discussed this in person. The resolution was:

* There is definitely utility in preserving control flow operators all the way to inductor. First, control flow operators can be used to implement "device side" control flow; e.g., a device_cond could be used to perform a conditional *inside* the CUDA kernel, eliminating the need for a D2H sync (at the cost of always running both sides of the branch: likely worth it if you are bandwidth bound). Second, even if the control flow is host side and otherwise unoptimizable, propagating it to inductor means we still have the opportunity optimize around the control flow operator (not propagating, e.g., as in a graph break, eliminates this possibility). However...
* ...this depends on the control flow operator being well behaved enough that we can treat it as a "complicated opaque operator". Importantly, this means the control flow operator is not permitted to mutate inputs. So these operators will be strongly restricted and not as expressive as Python control flow operators they emulate.
* To preserve a control flow operator to inductor, it must work with all of our subsystems, most notably autograd, functionalization and vmap
* If a control flow operator is to be used for inference export only and does not work with these subsystems, it should not be put in PyTorch core and should be instead done elsewhere, e.g., Executorch-only

2023-03-20 16:54 UTC, ydwu4 commented
@ezyang @zou3519 After the discussion, the next step I'd like to take is making sure control flow operators can work with all torch subsystems. Specifically, 1. I'll add backward implementation for cond, map and while_loop, and 2. add tests to make sure vmap also work.

2023-03-21 08:36 UTC, clegaard commented
> @ezyang In my perspective - supporting some high-level constructs like scans / reduce / map tensor functions should make transformations / optimizations easier as they express various RNNs and maybe even solver loops (like fixed point iterations). For mutation - this may happen in the wild if one codes a loop that modifies some hidden state inplace (especially if we don't need to backprop through the loop'ed computation). How this impacts the inner architecture of IR - no idea :)

Another use-case is solving ordinary differential equations. Models like neural ordinary differential equations use numerical solvers to obtain a trace of the system.
In Jax these can easily be expressed with the scan function, which traces in constant time
``` Python
def solve_euler_scan(f, t, y0, *args, **kwargs):
    step_sizes = t[1:] - t[:-1]

    def f_scan(y_cur, t_and_step):
        t, step_size = t_and_step
        dydt = f(t, y_cur, *args)
        y_new = y_cur + step_size * dydt
        return y_new, y_new

    _, Y = scan(f_scan, init=y0, xs=(t[1:], step_sizes))
    Y = jnp.concatenate((y0.reshape(-1, 1), Y.T), axis=1)
    return Y
```
From my limited experiments, tracing a Python for loop takes a very long time as it scaled with the number of iterations.

2023-03-22 13:55 UTC, vadimkantorov commented
And would probably be useful for deep equilibrium models

2023-06-20 14:33 UTC, closed without merging