Set up sccache inside the DockerFile.
pytorch/pytorch pull request #9697
Opened 2018-07-23 02:09 UTC by Jorghi12

Start setting up sccache inside of the DockerFile, instead of in the jenkins build script.

2018-07-23 02:29 UTC, yf225 requested changes
See comment

2018-07-23 02:42 UTC, Jorghi12 commented
@yf225  I'll add the logic for that right now.

2018-07-23 03:00 UTC, yf225 approved these changes

2018-07-23 03:00 UTC, yf225 commented
I will start a Caffe2 docker image build based on the changes here.

2018-07-23 03:04 UTC, Jorghi12 commented
Spoke with @yf225. Easiest way to deploy this is to create two separate Pull Requests. First creating one for the new DockerFile and having it merged to master. Then, create one with the build script adjustment, which will make it easier to test on the new Docker Images.

2018-07-24 00:39 UTC, Jorghi12 commented
Since this change is updating the DockerFile & the build script at once, the caffe2-docker trigger https://ci.pytorch.org/jenkins/job/caffe2-docker-trigger/148/ will be the source of truth.

2018-07-24 02:32 UTC, Jorghi12 commented
The Caffe2 Docker Trigger passes all but one: https://ci.pytorch.org/jenkins/job/caffe2-docker-trigger/149/

Due to:
`denied: The repository with name 'caffe2/py2-mkl-ubuntu16.04' in registry with id '308535385114' already has the maximum allowed number of images which is '10000'`

2018-07-25 13:58 UTC, ezyang commented on docker/caffe2/jenkins/build.sh
> +docker build $(if [[ "$image" == *rocm* ]]; then echo "--memory-swap -1"; fi) \
Doesn't this control the swap memory available when building the docker image, not when running it?

2018-07-25 15:37 UTC, Jorghi12 commented on docker/caffe2/jenkins/common/install_rocm.sh
>  install_hcrng() {
The PyTorch rocRAND PR hasn't been merged yet. And hcrng isn't part of the ROCm distribution it seems.

2018-07-30 13:17 UTC, ezyang commented
@pytorchbot retest this please

2018-07-30 13:17 UTC, ezyang commented
Can we merge this?

2018-08-01 15:18 UTC, ezyang commented
This must be landed with an update to the Docker images.

2018-08-21 16:53 UTC, yf225 commented
@Jorghi12 Is there a new status on this one?

2018-10-11 06:56 UTC, ezyang commented
This diff is abandoned.

2018-10-11 06:56 UTC, closed without merging