Fixes an ONNX export error with unflatten
pytorch/pytorch pull request #97131
Opened 2023-03-20 06:36 UTC by teodorToshkov

When trying to export to onnx a model, calling tensor.unflatten, the following error occurs:
```
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::unflatten' to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
```

Converting ```input.unflatten``` to ```input.view``` fixes this issue.

Fixes #ISSUE_NUMBER

2023-03-20 23:42 UTC, cpuhrsch requested changes
It seems like an anti-pattern to change a module called nn.Unflatten to not use unflatten to resolve an issue with ONNX

2023-03-21 20:04 UTC, justinchuby commented
You may consider implementing this operator in torch/onnx/symbolic_opset9

2023-03-23 02:58 UTC, teodorToshkov commented
@justinchuby Thank you for the comment. I implemented the unflatten operator in torch/onnx/symbolic_opset9
Please have a look at the fix and let me know if it is compliant with PyTorch's code rules.

2023-03-23 03:56 UTC, justinchuby commented on torch/onnx/symbolic_opset9.py
> +    input_dim = symbolic_helper._get_tensor_rank(input)
```suggestion
    input_rank = symbolic_helper._get_tensor_rank(input)
```

nit

2023-03-23 03:58 UTC, justinchuby commented
Thanks! Could you add enable the test in https://github.com/pytorch/pytorch/blob/master/test/onnx/test_op_consistency.py#L311?

2023-03-23 04:15 UTC, teodorToshkov commented
@justinchuby 
Thank you very much for the quick response!
I am not sure how exactly to add a test in https://github.com/pytorch/pytorch/blob/master/test/onnx/test_op_consistency.py#L311, but I will attempt it by adding it as a tested operator in the list.

2023-03-25 16:45 UTC, justinchuby commented
Could you take a look at the test errors: https://hud.pytorch.org/pr/97131

2023-04-13 18:08 UTC, titaiwangms commented
Closed in favor of #99056

2023-04-13 18:08 UTC, closed without merging