fix doc preview s3-prefix
pytorch/pytorch pull request #97433
Opened 2023-03-23 09:20 UTC by pmeier

Sister patch for pytorch/test-infra#3917. TL;DR this moves the doc preview scheme to $OWNER/$REPO rather than $REPO that we are currently rolling.

2023-03-23 17:10 UTC, seemethere approved these changes

2023-03-23 21:12 UTC, malfet requested changes
Landing this pair of PR will create about a week of confusion, until folks rebase past this one.(As for all devs who have work-in-progress PRs, docs will be generated in old location, but DrCI will point to a new one)

If I'm to make the transition, I'll probably create a PR that uploads to two locations, landed it right a way, waited for a week, than landed test-infra PR that uses new location and finally deleted upload to the old location.

2023-03-28 17:48 UTC, malfet approved these changes

2023-03-29 07:27 UTC, pmeier commented
@pytorchbot merge -r viable/strict

2023-03-29 10:13 UTC, closed without merging