Fix typos under torch/ao directory
pytorch/pytorch pull request #97679
Opened 2023-03-27 16:55 UTC by kiszk

This PR fixes typos in comments and messages of `.py` files under `torch/ao` directory

2023-03-28 16:06 UTC, janeyx99 commented on torch/ao/pruning/_experimental/data_sparsifier/data_norm_sparsifier.py
> +        if len(data_norm.shape) > 2:  # only supports 2 dimensitional data at the moment
```suggestion
        if len(data_norm.shape) > 2:  # only supports 2 dimensional data at the moment
```

2023-03-28 16:07 UTC, janeyx99 requested changes
small nit, overall fine!

2023-03-28 16:54 UTC, kiszk commented
@janeyx99 Thank you for your comment. I addressed it.

2023-03-28 17:03 UTC, janeyx99 approved these changes
👍

2023-04-10 19:29 UTC, kit1980 approved these changes

2023-04-10 19:29 UTC, kit1980 commented
@pytorchbot merge -r

2023-04-10 22:25 UTC, closed without merging