[inductor] more cuda metrics in wrapper
pytorch/pytorch pull request #97723
Opened 2023-03-28 00:43 UTC by shunting314

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-03-28 15:30 UTC, jansel requested changes

2023-03-28 15:30 UTC, jansel commented on torch/_inductor/codegen/wrapper.py
> +                output.writeline("times = 10")
Let's move this stuff into a helper function `import`ed from the generated code.  It is better not to repeat a ton of stuff in every generated file.

2023-03-28 16:39 UTC, ngimel commented on torch/_inductor/utils.py
> +            f"\nPercent of time when GPU is busy: {total_cuda_ms / wall_time_ms * 100:.2f}%"
>100% numbers are likely due to caching during acquiring wall_time, so during`wall_time` benchmarking kernels are faster than during profiling. I guess we'll have to live with this.

2023-03-31 02:49 UTC, jansel approved these changes

2023-04-01 05:03 UTC, shunting314 commented
@pytorchbot merge

2023-04-01 08:04 UTC, closed without merging