add channel last 3d support for maxpool3d on CPU
pytorch/pytorch pull request #97775
Opened 2023-03-28 13:47 UTC by CaoE

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #98819
* __->__ #97775

### Testing
Single socket (28 cores):

shape | fp32 forward / ms | bf16 forward / ms | fp32 backward / ms  | bf16 backward / ms
-- | -- | -- | -- | --
size: (1, 56, 264, 264), kernel: 3,   stride: 1, mem_format: contig | 3.959584 | 5.493402 | 0.557232 | 0.568485
size: (1, 56, 264, 264), kernel: 3,   stride: 1, mem_format: CL | 0.815511 | 1.351261 | 5.710506 | 10.57506
size: (32, 32, 100, 100), kernel: 3,   stride: 1, mem_format: contig  | 10.63426 | 15.28637 | 2.67656 | 1.71365
size: (32, 32, 100, 100), kernel: 3,   stride: 1, mem_format: CL | 2.63570 | 2.05532 | 2.55452 | 2.33923
size: (4, 19, 10, 16, 16), kernel:   3, stride: 1, mem_format: contig | 0.375469 | 0.479748 | 0.066364 | 0.065155
size: (4, 19, 10, 16, 16), kernel:   3, stride: 1, mem_format: CL3d | 0.112197 | 0.112326 | 0.111697 | 0.145364

Single core:

shape | fp32 forward / ms | bf16 forward / ms | fp32 backward / ms | bf16 backward / ms
-- | -- | -- | -- | --
size: (1, 56, 264, 264), kernel: 3,   stride: 1, mem_format: contig | 92.16582 | 128.6513 | 6.684325 | 12.21541
size: (1, 56, 264, 264), kernel: 3,   stride: 1, mem_format: CL | 10.14318 | 29.80297 | 7.350142 | 11.25323
size: (32, 32, 100, 100), kernel: 3,   stride: 1, mem_format: contig | 238.55453 | 331.89967 | 19.694657 | 32.78853
size: (32, 32, 100, 100), kernel: 3,   stride: 1, mem_format: CL | 30.17079 | 32.75628 | 22.44543 | 30.17796
size: (4, 19, 10, 16, 16), kernel:   3, stride: 1, mem_format: contig | 7.474389 | 9.937217 | 0.236015 | 0.434229
size: (4, 19, 10, 16, 16), kernel:   3, stride: 1, mem_format: CL3d | 2.318954 | 2.469444 | 0.262125 | 0.401361

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

2023-03-29 02:26 UTC, mingfeima requested changes

2023-03-29 02:26 UTC, mingfeima commented on aten/src/ATen/native/DilatedMaxPool3d.cpp
> +<<<<<<< HEAD
Oops, some rebase error here ~_~

2023-03-29 09:26 UTC, CaoE commented on aten/src/ATen/native/DilatedMaxPool3d.cpp
> +<<<<<<< HEAD
Fixed the rebase error.

2023-04-13 10:21 UTC, jgong5 reviewed
Any performance numbers on the channels last 3d optimiziation and bfloat16?

2023-04-13 10:21 UTC, jgong5 commented on aten/src/ATen/native/cpu/MaxPoolKernel.cpp
> +void cpu_max_pool_3d(
possible to share code between `cpu_max_pool` and `cpu_max_pool_3d` too?

2023-05-04 09:45 UTC, CaoE commented on test/nn/test_pooling.py
> +            helper(0, 6, 12, 13, 14, (5, 6, 7))
When dims of input is 4, maxpool3d on CUDA will unsqueeze input at dim 0 and check if it is in channels last 3d. If yes, unsqueeze output and indices, and resize them to channels last 3d too, then squeeze output and indices. The behavior on CPU is different.  Maxpool3d on CPU uses input.suggest_memory_format() to decide whether to go channels last 3d pass. For such case input.suggest_memory_format() is contiguous.

2023-05-04 10:24 UTC, jgong5 commented on test/nn/test_pooling.py
> +            helper(0, 6, 12, 13, 14, (5, 6, 7))
For such a case, input would be suggested as channels first on CPU but channels last contiguous? Why CPU implementation has to be different from CUDA?

2023-05-09 12:57 UTC, CaoE commented
> Any performance numbers on the channels last 3d optimiziation and bfloat16?

Will provide performance numbers later.

2023-05-10 06:02 UTC, jgong5 approved these changes

2023-05-10 06:02 UTC, jgong5 approved these changes

2023-05-15 03:01 UTC, CaoE commented on aten/src/ATen/native/cpu/MaxPoolKernel.cpp
> +      indices_sizes.insert(indices_sizes.begin(), 1);
Added TORCH_CHECK.

2023-07-03 07:13 UTC, CaoE commented
@ngimel Could you please review this PR ? Thank you.

2023-07-03 07:14 UTC, CaoE commented
@Skylion007 Could you please review this PR ? Thank you.

2023-07-04 03:27 UTC, CaoE commented
@cpuhrsch  Could you please review this PR ? Thank you.

2023-08-11 01:23 UTC, CaoE commented
@mikaylagawarecki Could you please review this PR ? Thank you.

2023-08-11 15:02 UTC, mikaylagawarecki reviewed
Hey @CaoE as a broader comment

Following up from our previous discussion, is https://github.com/pytorch/pytorch/pull/106104 ready for review? Happy to review it if it is!

Separately, we must be wary that the `test_memory_format` tests for ModuleInfos has been skipped rather than xfailed for quite a few ops, as we add channels_last_3d support for more of them, could we unskip these tests as well please e.g. https://github.com/pytorch/pytorch/blob/main/torch/testing/_internal/common_modules.py#L2555

2023-08-25 01:04 UTC, CaoE commented
@mikaylagawarecki Could you please review this PR ? https://github.com/pytorch/pytorch/pull/106104 is ready for review. Thank you.

2023-08-25 15:28 UTC, CaoE commented
@mikaylagawarecki  Can we merge this PR before 2.1 branch if possible ?

2023-08-25 20:12 UTC, mikaylagawarecki approved these changes
Thanks for using the ModuleInfo testing

2023-08-26 00:17 UTC, mikaylagawarecki commented
@pytorchbot merge -f "macos failures are unrelated"

2023-08-26 00:21 UTC, closed without merging