Type conversion between float/complex dtypes
pytorch/pytorch pull request #97935
Opened 2023-03-30 01:58 UTC by gautierronan

This PR is an implementation of the feature request https://github.com/pytorch/pytorch/issues/97888, for the implementation of `torch.dtype.to_complex()` and `torch.dtype.to_float()` methods that convert between float and complex dtypes of the same precision.

Disclaimer: it's the first time I code in C++ so hopefully the code is correct, but I'm not super confident about the PR. Any advice/comment is welcome.

2023-03-31 16:50 UTC, ezyang commented
Oops, this was different than what I thought I was asking for in https://github.com/pytorch/pytorch/issues/97888#issuecomment-1489446040 Maybe we can still add it? Let's see:

I originally was responding to:

> Thanks for pointing this function out, I didn't know it existed. One drawback is that it doesn't support float to float or complex to complex conversion (which does nothing, but it could come in handy). And it's lacking documentation in case other users would want to same feature as me.

It seemed to me that you were requesting corresponding_real_dtype to return torch.float if given torch.float. This PR, does not seem to do that.

Do you still want this PR? There might be some extra bikeshedding we will need to do, as the methods you're adding have no analogue in numpy.

2023-03-31 17:44 UTC, gautierronan commented
> Oops, this was different than what I thought I was asking for in [#97888 (comment)](https://github.com/pytorch/pytorch/issues/97888#issuecomment-1489446040) Maybe we can still add it? Let's see:
> 
> I originally was responding to:
> 
> > Thanks for pointing this function out, I didn't know it existed. One drawback is that it doesn't support float to float or complex to complex conversion (which does nothing, but it could come in handy). And it's lacking documentation in case other users would want to same feature as me.
> 
> It seemed to me that you were requesting corresponding_real_dtype to return torch.float if given torch.float. This PR, does not seem to do that.
> 
> Do you still want this PR? There might be some extra bikeshedding we will need to do, as the methods you're adding have no analogue in numpy.

Well as you wish ! Now that I personally know that `corresponding_real_dtype` exists, I can use it for my own needs. Indeed I can just extend it to support float->float and complex->complex conversion, which would be very simple. 

The question is rather: do you want the method I was initially proposing (i.e. `torch.dtype.to_real`) for other users? I think it's quite handy, but you might have reasons to not want that.

2023-04-01 02:13 UTC, ezyang commented
On reflection, I think I will take this PR too, we just need to change it to `to_real`.

2023-04-01 16:27 UTC, gautierronan commented
Alright, let me know if there's anything else I can do.

2023-04-02 19:52 UTC, ezyang approved these changes

2023-04-02 19:53 UTC, ezyang requested changes
Actually the mechanism for making a new Python binding may not be correct. More coming later

2023-04-03 18:33 UTC, ezyang commented on torch/csrc/Dtype.cpp
> +  return THPDtype_New(scalar_type, primary_name);
Use getTHPDtype instead.

2023-04-03 18:33 UTC, ezyang requested changes
how to fix it

2023-04-03 23:59 UTC, ezyang approved these changes

2023-04-03 23:59 UTC, ezyang commented
@pytorchbot merge

2023-04-04 00:28 UTC, ezyang commented
still doesn't compile

2023-05-12 11:54 UTC, gautierronan commented
Unsure how to fix this but I'm still very much interested in the PR. Any help is appreciated !

2023-05-15 20:51 UTC, ezyang commented
@pytorchbot merge

2023-05-16 14:39 UTC, closed without merging