Fix ddp static graph mode error when some outputs are not used
pytorch/pytorch pull request #98084
Opened 2023-03-31 15:09 UTC by VincentLeeMax

Fixes #97030

In static mode, those outputs without backward will stuck the reducer logic, use `_DDPSink` logic to handle the case.

Since static graph mode will omit `find_unused_parameters` argument, use `find_unused_parameters=True, static_graph=True` to specify this case.

2023-03-31 21:32 UTC, awgu requested changes
`static_graph` is not supposed to require `find_unused_parameters`. In my understanding, this solution is not the desired one.

2023-04-01 07:57 UTC, VincentLeeMax commented
@awgu 
The reason is that, in `static_graph` and first iteration,  the `_DDPSink` logic  make the parameters `self.b` still in the backward graph, even if it's `backward` is not called. After the first iteration, parameter `self.b` is still pushed into bucket, while it's `autograd_hook` is not triggered due to the lack of `_DDPSink` logic, causing failure.

The propose of the PR is to explicitly use the `_DDPSink` logic to ensure that the outputs always in the backward graph. Considering that `find_unused_parameters` is not used when setting `static_graph`, use `find_unused_parameters=True` to specify this case is the easiest way.

If this solution is not the desired one, what about add a logic to automatically add the parameters with `None` grad to `unused_parameters_` when `Reducer::static_graph_first_iteration`. Without setting `find_unused_parameters=True`, I think this will help solve this problem.

2023-04-05 14:26 UTC, VincentLeeMax commented
@awgu 
After trying the solution of marking the parameters with `None` grad as `unused_parameters_` in static graph mode, I found that it's not the perfect solution for some special case (Model was trained standalone and then encapsulated as DDP model, etc).
So I fix it by always using `_DDPSink`  to chain the outputs if finding some outputs that are not used in the first iteration.

2023-04-06 07:02 UTC, rohan-varma reviewed
This new fix looks promising to me, thanks! 

Could we fix the unittest as I mentioned?

2023-04-06 07:02 UTC, rohan-varma commented on torch/testing/_internal/distributed/distributed_test.py
> +        def _test_output_unused_in_loss(self, module_cls, static_graph):
oops, look like this test never tested grad_as_bucket_view as we should be. Could we add grad_as_bucket view to DDP ctor below?

2023-04-06 17:03 UTC, rohan-varma commented
LG, thanks! We will need to run some tests internally so I've imported it.

2023-06-13 09:27 UTC, VincentLeeMax commented
> LG, thanks! We will need to run some tests internally so I've imported it.

Hi, it this PR ready to go or have any problem?

2023-06-13 09:28 UTC, VincentLeeMax commented
> LG, thanks! We will need to run some tests internally so I've imported it.

Hi @rohan-varma , it this PR ready to go or have any problem?

2023-09-11 09:33 UTC, closed without merging