[hypothesis==6.70.1] Fix more test errors
pytorch/pytorch pull request #98685
Opened 2023-04-08 18:54 UTC by MaigoAkisame

Summary:
This diff fixes more test failures (T150117218) caused by upgrading the "hypothesis" library to 6.70.1 (D44523679).

# //caffe2/caffe2/python:hypothesis_test
This test generates float numbers and filters out those whose absolute values are less than 1e-2.
It is a known issue of the new version of "hypothesis" that it generates zeros or floats with small absolute values too often:
https://github.com/HypothesisWorks/hypothesis/issues/3603
I'm circumventing this issue by suppressing the health check `filter_too_much`.

# //caffe2/caffe2/quantization/server:resize_nearest_dnnlowp_op_test
All arithmetic should be done in float32 when calculating the reference, since the network being tested uses float32 everywhere.
Mixing float32, float64 or even integers will result in intermediate values in float64.
The different precision may cause off-by-1 errors when converting to integer.

Test Plan:
Run all the tests in both "dev" and "opt" modes:
```
for mode in dev opt; do
  buck2 test mode/$mode //caffe2/caffe2/python:hypothesis_test -- --run-disabled
  buck2 test mode/$mode //caffe2/caffe2/quantization/server:resize_nearest_dnnlowp_op_test -- --run-disabled
  buck2 test mode/$mode //caffe2/caffe2/fb/layers/tests:tum_history_test -- --run-disabled
  buck2 test mode/$mode //caffe2/caffe2/fb/dper/layer_models/tests:nn_ops_test -- --run-disabled
  buck2 test mode/$mode //caffe2/caffe2/fb/metrics:metrics_test -- --run-disabled
  buck2 test mode/$mode //deeplearning/numeric_suite/toolkit/test:net_transform_test -- --run-disabled
  buck2 test mode/$mode //f3/type_system:tests -- --run-disabled
done
```

**NOTE:** In the first test (`//caffe2/caffe2/python:hypothesis_test`), the two methods `test_constant_fill_from_tensor` and `test_recurrent` would crash.
But these crash on hypothesis 5.49.0, too, so I'm leaving them alone.

Differential Revision: D44812706

2023-04-09 23:12 UTC, malfet approved these changes
Those are old caffe2 tests

2023-04-09 23:18 UTC, malfet requested changes
Even though caffe2 tests are not running by default, it would be nice to make sure that they are using , if you are working towards updating hypothesis, please update supported version in https://github.com/pytorch/pytorch/blob/7e0c26d4d80d6602aed95cb680dfc09c9ce533bc/.ci/docker/requirements-ci.txt#L39

2023-04-11 18:08 UTC, MaigoAkisame commented
The changes are backward compatible: after the changes, the tests work with hypothesis both before and after 6.17.4.

2023-04-11 18:10 UTC, malfet approved these changes

2023-04-11 19:08 UTC, closed without merging