[inductor][easy] create a wrap for triton do_bench function
pytorch/pytorch pull request #99216
Opened 2023-04-15 01:19 UTC by shunting314

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-04-15 02:03 UTC, jansel requested changes
Let's just change our wrapper to return a single value rather than a tuple.

I believe all our usage just ignores the extra values.

2023-04-17 18:13 UTC, shunting314 commented
I did a `grep -r 'bench('` under `torch/_inductor` directory and update all the call sites to assume a item returned from do_bench.

I also checked `torch/_dynamo`, `benchmarks/dynamo` folder, looks like `torch._inductor.testing.do_bench` is not used there.

2023-04-17 18:30 UTC, ngimel approved these changes

2023-04-17 20:16 UTC, jansel approved these changes

2023-04-18 00:50 UTC, shunting314 commented
@pytorchbot merge -f "SEGFAULT and model accuracy check fail are unrelated"

2023-04-18 00:52 UTC, closed without merging