torch._int_mm: fix triton kernel caching
pytorch/pytorch pull request #99283
Opened 2023-04-17 03:23 UTC by vkuzo

Summary:

A fix to ensure that kernels generated for `torch._int_mm` can be cached. We can remove this hack one eager mode `torch._int_mm` is better supported.

Let me know if something more proper is needed instead of the hack.

Test plan:

```
// running the script below led to two compilations of triton
// int8,int8->int32 kernel before this PR, and only has
// one compilcation which is reused after this PR

import torch
import torch.nn as nn

x = torch.randint(-128, 127, (32, 32), device='cuda', dtype=torch.int8)
y = torch.randint(-128, 127, (32, 32), device='cuda', dtype=torch.int8)

class M(nn.Module):
    def forward(self, x):
        x = torch._int_mm(x, y)
        x = x.to(torch.int8)
        x = torch._int_mm(x, y)
        return x

m = M().cuda().half()
m = torch.compile(m, options={"max-autotune": True})

z = m(x)
z = m(x)
```

Fixes #ISSUE_NUMBER

2023-04-17 22:43 UTC, nmacchioni requested changes
I'm not convinced this is needed, since I recently changed the way things are cached in #98351. Tl;dr; the caching is not longer based on the default choice's name but rather is hardcores into the autotuning call.

2023-04-17 22:50 UTC, vkuzo commented
> I'm not convinced this is needed, since I recently changed the way things are cached in #98351. Tl;dr; the caching is not longer based on the default choice's name but rather is hardcored into the autotuning call.

here is the line using choice[0] name as the cache key: https://github.com/pytorch/pytorch/blob/c2fd198cafaac3e5de6d72a80cd4ad19da042ce5/torch/_inductor/select_algorithm.py#L742

I guess we can just use that instead of this hack then, I wasn't sure if there was some reason it had to be `choice[0]`.

2023-04-17 22:58 UTC, nmacchioni commented
> > I'm not convinced this is needed, since I recently changed the way things are cached in #98351. Tl;dr; the caching is not longer based on the default choice's name but rather is hardcored into the autotuning call.
> 
> here is the line using choice[0] name as the cache key:
> 
> https://github.com/pytorch/pytorch/blob/c2fd198cafaac3e5de6d72a80cd4ad19da042ce5/torch/_inductor/select_algorithm.py#L742
> 
> I guess we can just use that instead of this hack then, I wasn't sure if there was some reason it had to be `choice[0]`.

Oh good catch, we never actually pass the hardcoded name to the lookup function. I think if we just pass `name` here instead of `choices[0].name` that would be a good fix. Thanks!

2023-04-17 23:10 UTC, nmacchioni approved these changes

2023-04-18 04:19 UTC, vkuzo commented
@pytorchbot merge

2023-04-18 16:32 UTC, vkuzo commented
@pytorchbot merge -f 'rule requiring approvers from an allowlist seems unrelated'

2023-04-18 16:40 UTC, nmacchioni commented
@vkuzo I'm not on the list of maintainers, so you'll still need a stamp from one of them. @jansel can you review?

2023-04-18 16:41 UTC, vkuzo commented
I guess each failed merge unmasks 5 more reviewers, so I can keep failing to merge until I see a familiar name...

2023-04-18 16:42 UTC, vkuzo commented
> @vkuzo I'm not on the list of maintainers, so you'll still need a stamp from one of them. @jansel can you review?

do you know what the list is? I didn't see anyone I know so far on the 5 people the job gives.  Didn't want to ask a rando.

2023-04-18 16:42 UTC, vkuzo commented
@pytorchmergebot merge -f 'give me 5 more names, bot'

2023-04-18 16:45 UTC, nmacchioni commented
> > @vkuzo I'm not on the list of maintainers, so you'll still need a stamp from one of them. @jansel can you review?
> 
> 
> 
> do you know what the list is? I didn't see anyone I know so far on the 5 people the job gives.  Didn't want to ask a rando.

I'm not sure of the full list, but Jason can definitely stamp this as he leads the autotuning work.

2023-04-18 16:49 UTC, vkuzo commented
@pytorchbot merge -f 'gimme 5 more names plz'

2023-04-18 16:50 UTC, vkuzo commented
> > > @vkuzo I'm not on the list of maintainers, so you'll still need a stamp from one of them. @jansel can you review?
> > 
> > 
> > do you know what the list is? I didn't see anyone I know so far on the 5 people the job gives.  Didn't want to ask a rando.
> 
> I'm not sure of the full list, but Jason can definitely stamp this as he leads the autotuning work.

thx! I'll see who manages to stamp this first.  I gave some feedback to the job maintainers so hopefully we can make it less cryptic for next time.

2023-04-18 16:52 UTC, vkuzo commented
@pytorchbot merge -f 'gimme 5 more names plz'

2023-04-18 17:02 UTC, janeyx99 approved these changes
a stamp

2023-04-18 21:56 UTC, vkuzo commented
@pytorchbot merge

2023-04-18 22:05 UTC, vkuzo commented
@pytorchbot merge -f 'CI failure seems unrelated'

2023-04-18 22:07 UTC, closed without merging