inductor: align inductor behavior with eager mode for split_with_sizes
pytorch/pytorch pull request #99702
Opened 2023-04-21 06:44 UTC by XiaobingSuper

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-04-21 07:30 UTC, jgong5 requested changes

2023-04-21 07:30 UTC, jgong5 commented on torch/_decomp/decompositions.py
> +def sum(x: List[int]):
why not use the builtin `sum`?

2023-04-21 07:51 UTC, XiaobingSuper commented on torch/_decomp/decompositions.py
> +def sum(x: List[int]):
yes, changed.

2023-04-21 10:01 UTC, EikanWang commented
> but inductor can run

Do you mean there is no correctness issue?

2023-04-23 01:19 UTC, XiaobingSuper commented
> > but inductor can run
> 
> Do you mean there is no correctness issue?


For the definition of split_with_size, we should report an error to the user for the given case.

2023-04-24 08:13 UTC, lezcano commented on test/inductor/test_torchinductor.py
> +        with self.assertRaisesRegex(RuntimeError, ""):
Actually, shouldn't this be a `ValueError`?

2023-04-24 08:32 UTC, XiaobingSuper commented on test/inductor/test_torchinductor.py
> +        with self.assertRaisesRegex(RuntimeError, ""):
I used ValueError, but it seems catch RuntimeError firstly even the error log is:
```
Traceback (most recent call last):
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/utils.py", line 1267, in run_node
    return node.target(*args, **kwargs)
  File "/home/xiaobing/pytorch-offical/torch/functional.py", line 189, in split
    return tensor.split(split_size_or_sections, dim)
  File "/home/xiaobing/pytorch-offical/torch/_tensor.py", line 804, in split
    return torch._VF.split_with_sizes(self, split_size, dim)
  File "/home/xiaobing/pytorch-offical/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/xiaobing/pytorch-offical/torch/_subclasses/fake_tensor.py", line 1095, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/xiaobing/pytorch-offical/torch/_subclasses/fake_tensor.py", line 1259, in dispatch
    return decomposition_table[func](*args, **kwargs)
  File "/home/xiaobing/pytorch-offical/torch/_decomp/decompositions.py", line 1102, in split_with_sizes
    raise ValueError(
ValueError: Split sizes don't add up to the tensor's size in the given dimension

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/utils.py", line 1215, in get_fake_value
    return wrap_fake_exception(
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/utils.py", line 835, in wrap_fake_exception
    return fn()
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/utils.py", line 1216, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/utils.py", line 1279, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_function <function split at 0x7f45b8402ee0>(*(FakeTensor(..., size=(1, 5)), [2, 1, 1]), **{'dim': 1}):
Split sizes don't add up to the tensor's size in the given dimension
(scroll up for backtrace)

The above exception was the direct cause of the following exception:
```

2023-04-24 08:34 UTC, lezcano approved these changes

2023-04-24 12:51 UTC, jgong5 approved these changes

2023-04-24 18:25 UTC, jansel approved these changes

2023-04-25 01:11 UTC, XiaobingSuper commented
@pytorchbot merge

2023-04-25 01:14 UTC, closed without merging