[doc] linalg.ldl_factor: render the Shape of tensor A
pytorch/pytorch pull request #99777
Opened 2023-04-22 00:25 UTC by isdanni

Summary: Fix: #96864

Test Plan: Please see GitHub tests.

Differential Revision: D45204660

2023-04-22 09:31 UTC, lezcano requested changes
Please, see the format that's used in the rest of linalg. In particular, we avoid using `:math:` as it takes quite a long time to render. Use single backticks instead.

2023-04-23 12:38 UTC, lezcano commented on torch/linalg/__init__.py
>                      `(*, n, n)` where `*` is one or more batch dimensions.
Feel free to delete this line as well, as it's repeated. Same in the other function.

2023-04-23 12:38 UTC, lezcano commented on torch/linalg/__init__.py
>                      `(*, n, n)` where `*` is one or more batch dimensions.
Also, this line has extra indentation. Same in the other one

2023-04-24 08:01 UTC, lezcano approved these changes
Thank you!

2023-06-27 20:16 UTC, isdanni commented
@lezcano @IvanYashchuk any plans to merge this? :)

2023-06-28 04:14 UTC, lezcano commented
You can merge it yourself writing `@pytorchbot merge` in a comment  :)

2023-06-28 04:59 UTC, isdanni commented
@pytorchbot merge

2023-06-28 05:02 UTC, isdanni commented
@pytorchbot merge -r

2023-06-28 05:31 UTC, isdanni commented
@pytorchbot merge -r

2023-06-28 05:42 UTC, isdanni commented
@pytorchbot merge -f

2023-06-28 05:42 UTC, isdanni commented
@pytorchbot merge -f "test failure unrelated"

2023-06-28 06:02 UTC, lezcano commented
Since you imported this, you should import the rebased branch onto phabricator as well, I believe.

2023-06-28 06:45 UTC, isdanni commented
@pytorchbot merge

2023-06-28 09:28 UTC, closed without merging